### PR TITLE
✨ GalleryItem description wrapper

### LINKED ISSUE #1473: i cant select the text in collection description / or click on the link
### What happened?

i cant select the text in collection description / or click on the link

### Please reproduce in steps

/

### Expected Behavior

/

### What browsers are you seeing the problem on?

Chrome

### Are you logged in?

Yes

### At which address did you encounter bug?

nft.kodadot.xyz / kodadot.xyz

### Screenshots

/

### Relevant log output

```shell
/
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by roiLeo**
### PR type
- [x] Bugfix
- [x] Feature

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional
- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>

### What's new?
- [x] PR closes #1473 
- [x] new collection description wrapper
- [x] sync CollapseWrapper component 
- [x] #1032, #1101 related 

#### small description
Screenshot 2021-12-10 at 11-06-34 nft-gallery-nuxt

#### large description
Screenshot 2021-12-10 at 11-07-06 nft-gallery-nuxt

### CODE REVIEW

**Review by vikiival — APPROVED** [review]
Cute! 

Let it snow! ❄️

**Comment by vikiival** [comment]
We discussed it with @yangwao and It would be better to move the `DescriptionWrapper` into the `GalleryItem.vue`

**Comment by roiLeo** [comment]
> And leave Collection item as it is

With the previous wrapper?

**Comment by yangwao** [comment]
Overall I really welcome this approach, 
it makes our UI more polished and adult! 😄 

> > And leave Collection item as it is
> 
> With the previous wrapper?

yeah, point is that we want users at the collection to focus on the numbers, 
so if you can come up with some neat solutions which include this one and don't disturb audience, let's see. 
If there is potential to replace the eye icon for down chevron, I'm up to it! 

image

For gallery item, this would be a super value add as some collections have tons of un-interesting texts tbh! and I basically just eyeball piece and that's it. We can add it btw to vuex if people want it to be folded or unfolded

#1308 #1118 #1160

**Comment by roiLeo** [comment]
Screenshot 2021-12-10 at 16-06-14 nft-gallery-nuxt

**Review by vikiival — APPROVED** [review]
LGTM 🚀 
Let it fly

**Comment by roiLeo** [comment]
How?

**Comment by vikiival** [comment]
> How?
?

**Pull request merged**
