### PR TITLE
fix: fetch image on explore collection

### LINKED ISSUE #4651: Gallery images don't load in Firefox Private mode
### What happened?

Gallery / collections content won't load when using Firefox (Developer's edition) in Private mode

### Please reproduce in steps

Install latest Firefox Developer's edition
Enter private mode
Navigate to https://beta.kodadot.xyz/bsx/explore/?tab=COLLECTION&page=1

### Expected Behavior

Content should be logging

### What browsers are you seeing the problem on?

Firefox

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

None

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

_No response_

### Screenshots

Screenshot 2023-01-10 at 10 52 03

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4651

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

Screenshot 2023-01-10 at 19 01 18

### CODE REVIEW

**Comment by roiLeo** [comment]
> TIL: indexedDB will throw an error on firefox private mode. so functions that rely on indexedDB will have different behaviour than chrome

Aight, this is only present in firefox private mode. Will we restrict all browsers only for this case?
Or we can try to migrate idb store to Vuex/Pinia

> btw, is that ok if I remove `prefetchPage()` on that page? @Jarsen136 @roiLeo

isn't this used for infiniteScroll? it seems to me that this has been added to speed up images display

**Review by vikiival — APPROVED** [review]
Code LGTM

ref:
- https://github.com/kodadot/rubick/issues/175

**Comment by vikiival** [comment]
Ref 
- https://github.com/kodadot/rubick/issues/176

**Review by roiLeo — APPROVED** [review]
let's go

**Comment by vikiival** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 27.49 USD/KSM ~ 1.819 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0x6946cd8545b33906bc9f0251e875d87036c550fd5f5698ffd6bd044c4834ed57](https://kusama.subscan.io/extrinsic/0x6946cd8545b33906bc9f0251e875d87036c550fd5f5698ffd6bd044c4834ed57)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
