### PR TITLE
fix: relist event, does not update directly on the page

### LINKED ISSUE #3688: relist event, does not update directly on the page
### What happened?

I made a relist of the nft, but this action does not appear in the history after completing the tx in the block, it only appears after reloading the page
the price if it updates immediately, but not history

 it is similar to bug #3686

### Please reproduce in steps

relist a nft, and after complete the tx, check history rewards, not will appear the new list, after reload and will appear

### Expected Behavior

update all info related with new event

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

_No response_

### Which wallet you are using?

Talisman

### At which chain did you encounter bug?

Basilisk

### Screenshots

Screenshot_101
Screenshot_102

### Relevant log output

_No response_

### Payment link for reward

https://beta.kodadot.xyz/transfer?target=Hy8UnZSNvchEzKLBZ6X6qXq6xc8gVNGyo8ALuuNUXeTiD6K&usdamount=0&donation=true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3688
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by jrafaelangarita** [comment]
yep, these work for me, now update the history on the page without reload

**Review by prachi00 — APPROVED** [review]

**Comment by prachi00** [comment]
LGTM

**Comment by petersopko** [comment]
> LGTM

let's start adding [✅ -code-LGTM](https://github.com/kodadot/nft-gallery/labels/%E2%9C%85%20-code-LGTM) label when reviewed code looks good, this helps us a lot to sort through the PRs and process them faster 😄

**Comment by petersopko** [comment]
pay 75 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $75 @ 66.08 USD/KSM ~ 1.135 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xfc1cbbbe67ed5a898bd32f6d965f85e65cdf561e74a833d40af480ac43723065](https://kusama.subscan.io/extrinsic/0xfc1cbbbe67ed5a898bd32f6d965f85e65cdf561e74a833d40af480ac43723065)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
