### PR TITLE
fix: download

### PR DESCRIPTION
**Pull request by nick-dev123**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [X] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [X] Related to #7375
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [X] My contribution builds **clean without any errors or warnings**
- [X] I've merged recent default branch -- **main** and I've no conflicts
- [X] I've tried to respect high code quality standards
- [X] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [X] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=12ZLwasAvpdxDiiMedr11VeKUyQkY3WfneMkswBCAHVvxAqe)

#### Community participation

- [ ] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at 58e9055</samp>

Refactored `downloadImage` function to use `useFetch` composable and validate response data. Improved error handling and code consistency in `utils/download.ts`.

### <samp>🤖 Generated by Copilot at 58e9055</samp>

> _`useFetch` instead_
> _refines `downloadImage`_
> _autumn of errors_

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
I would change it by

```ts
  try {
    const { data } = await useFetch(imageSrc)
    const image = data.value

    if (!(image instanceof Blob)) {
      return
    }

    const link = document.createElement('a')
    link.href = URL.createObjectURL(image)
    link.download = name
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    return link
  } catch (error) {
    $consola.warn('[ERR] unable to fetch image')
    return
  }
```

**Review by vikiival — CHANGES_REQUESTED** [review]
as mentioned by @roiLeo

**Comment by nick-dev123** [comment]
@roiLeo And maybe add a `warningMessage('Unable to download image')` in the catch?

**Comment by roiLeo** [comment]
> @roiLeo And maybe add a `warningMessage('Unable to download image')` in the catch?

Yessir

**Review by roiLeo — APPROVED** [review]

**Pull request merged**
