### PR TITLE
#3278 Limit input for user could not submit lower than minimum offer …

### LINKED ISSUE #3278: Limit input for user could not submit lower than minimum offer size
As we would like to avoid submitting lower than allowed offer size, 
limit users submitting lower offers 
This would prevent users not waiting for results from rpc   

https://beta.kodadot.xyz/bsx/gallery/2735277589-3?page=1

image

### LINKED ISSUE #3361: Invalid prop: tooltipOfferLabel
### What happened?

Added in bf523e0e1522615dc211343801678025e597b2ff and 99672bcd1c8cc2d32b3995b0cd0863fcf71ed8e6

Screenshot 2022-07-07 at 10 47 40

### Please reproduce in steps

- [ ] As logged user open some NFT detail on Basilisk
- [ ] e.g (http://localhost:9090/bsx/gallery/3195582573-1)

### Expected Behavior

Console should be without warnings :)

### What browsers are you seeing the problem on?

Chrome

### Are you logged in?

Yes

### At which address did you encounter bug?

_No response_

### Screenshots

~

### Relevant log output

```shell
[Vue warn]: Invalid prop: type check failed for prop "tooltipOfferLabel". Expected String, got Object 

found in

---> <ActionList> at components/rmrk/Gallery/Item/ActionList.vue
       <AvailableActions> at components/bsx/Gallery/Item/AvailableActions.vue
         <BaseGalleryItem> at components/shared/gallery/BaseGalleryItem.vue
           <GalleryItem> at components/bsx/Gallery/Item/GalleryItem.vue
             <GalleryItemPage> at pages/bsx/gallery/_id.vue
               <Nuxt>
                 <Layouts/default.vue> at layouts/default.vue
                   <Root>
```

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by prachi00**
…size

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #3278 
- [x] PR closes #3361 

- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
This could work out but I think a better solution would be to update `min` attribute from `BalanceInput` component

**Comment by prachi00** [comment]
> BalanceInput
Screen Shot 2022-07-05 at 9 14 39 PM
yeah it wont work tho because even if the input will throw error, button will not be disabled and user can still click on it, so we kinda do need he disabled attribute on the button

**Comment by roiLeo** [comment]
> This could work out but I think a better solution would be to update `min` attribute from `BalanceInput` component

`max` attribute could be user balance ref #3346

**Comment by roiLeo** [comment]
> yeah it wont work tho because even if the input will throw error, button will not be disabled and user can still click on it, so we kinda do need he disabled attribute on the button

Things is I find disabled "buttons/switch/inputs" a bad design pratice, this issue can be solved using simple html form validation.

You solution is working but mobile experience will be bad since user won't be able to know why the button is disabled.

**Comment by prachi00** [comment]
@roiLeo used `min max `and `buefy input validation` method to check it now

**Review by roiLeo — CHANGES_REQUESTED** [review]
`min` is always same value for me (10 000), could you check why?

Form validation looks way better now! didn't knew about buefy checkHtml5Validity method

**Comment by prachi00** [comment]
> 

not sure about min (calculating through `api.consts.marketplace.minimumOfferAmount`), its 10k for me too, its probably fixed?

**Comment by roiLeo** [comment]
> > 
> 
> not sure about min (calculating through `api.consts.marketplace.minimumOfferAmount`), its 10k for me too, its probably fixed?

this looks like it will always be at 10k since it's not related to current item

@vikiival any idea where we can find documentation of this feature?

**Comment by vikiival** [comment]
> @vikiival any idea where we can find documentation of this feature?

Unfortunately no.

The code is currently set to `10k` 
https://github.com/galacticcouncil/Basilisk-node/blob/b3b0b63c0b4098b0f0ca18ac43e748da85540f7c/runtime/basilisk/src/lib.rs#L803
But it can change so I would use `api.consts.marketplace.minimumOfferAmount` instead of setting 10k there


Also be aware that the api call can return you a special type (like u128) so you need to apply proper formatting

**Comment by prachi00** [comment]
@roiLeo can we merge this now?

**Comment by yangwao** [comment]
Seems on account with 19000 bsx 

image

is ok

when I submit offer for 21000 BSX where account balance is 19000 bsx got error, could be fixed in #3346  

image

#3361 seems doesn't happen to me

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 52.86 USD/KSM ~ 0.946 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0xd37fd1edfc3485cf72d95659aa44d8a4322605ae3d5490e6046c3f652f8329f9](https://kusama.subscan.io/extrinsic/0xd37fd1edfc3485cf72d95659aa44d8a4322605ae3d5490e6046c3f652f8329f9)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
