### PR TITLE
feat: add github cli instruction to first-time.md

### LINKED ISSUE #6967: Mention for first time blog post to use GH CLI
I've noticed that first-timers probably don't use GH cli, bc of submitting empty PR templates tbh 

Maybe include it here to install gh cli before first PR or use to make PR?

What is the best flow we should have there?

I've tried it myself after long time and seems flawless, so why not recommend it for contributors?

Task
---
Add mention to use GH cli before making first pull request 
- https://kodadot.xyz/blog/first-time
- https://cli.github.com/

image

### PR DESCRIPTION
**Pull request by thnaylor**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #6967
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=123PCJXhjb15i6JwVVRGd7KvN2sSNZrtPjr5doJq9oWctoTt)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at e6a1481</samp>

Added a new section on how to use GitHub CLI to create pull requests to `first-time.md` blog post. This change helps first-time contributors follow the project's contribution guidelines and templates.

### <samp>🤖 Generated by Copilot at e6a1481</samp>

> _`first-time.md` changed_
> _Learn to use GitHub CLI_
> _Autumn of coding_

### CODE REVIEW

**Review by stephenjason89 — APPROVED** [review]
Looks good 👍 I like github cli 🤩

**Review by roiLeo — APPROVED** [review]

**Comment by prury** [comment]
wait, mobile has a small problem: 
image
maybe use formatting similar to the other parts of the article to avoid it?

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 4.5 USD/DOT ~ 4.444 $DOT
🧗 [123PCJXhjb15i6JwVVRGd7KvN2sSNZrtPjr5doJq9oWctoTt](https://polkadot.subscan.io/account/123PCJXhjb15i6JwVVRGd7KvN2sSNZrtPjr5doJq9oWctoTt)
🔗 [0xf1a1084823b2c12eae3a2ce6e80012a19a91d19309f9d4b95fe9cd4a624b6a67](https://polkadot.subscan.io/extrinsic/0xf1a1084823b2c12eae3a2ce6e80012a19a91d19309f9d4b95fe9cd4a624b6a67)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
