### PR TITLE
#7746 toggle changes

### LINKED ISSUE #7746: On/off button styling
image

The default and active states should look a bit different in dark mode 

image

figma: 
https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=1287%3A18959&mode=design&t=CHyw8GVwoKn7OfQx-1

the white version is off as well 
image
image

plus one thing is that the circle part moves beyond the component
image
- its over the component in the on state

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #7746
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)

## Screenshot 📸

- [x] My fix has changed UI

Screen Shot 2023-10-19 at 9 21 56 PM
Screen Shot 2023-10-19 at 9 21 58 PM
Screen Shot 2023-10-19 at 9 22 03 PM
Screen Shot 2023-10-19 at 9 22 06 PM

### CODE REVIEW

**Comment by exezbcz** [comment]
could you fix the animation please. 

https://github.com/kodadot/nft-gallery/assets/90852205/bcdd1311-4f59-47e3-aa99-5ebb40b81885

on canary it is smoother

**Comment by prachi00** [comment]
@exezbcz check now

**Comment by exezbcz** [comment]
canary: 
image

deploy: 
image


- make it same height please

**Comment by prachi00** [comment]
> canary: image
> 
> deploy: image
> 
> * make it same height please
> 
> otherwise good!

@exezbcz on figma, height is 20, I followed that
Screen Shot 2023-10-22 at 3 14 33 PM

**Review by preschian — APPROVED** [review]

**Comment by exezbcz** [comment]
@prachi00 my bad, could you please change it to 24px, feel like its better

thank you! After this visual oki

**Comment by prachi00** [comment]
> 24px

done

**Review by roiLeo — APPROVED** [review]

**Comment by vikiival** [comment]
pay 25 usd

**Pull request merged**
