### PR TITLE
fix: Wrong USD denomination on gallery item

### LINKED ISSUE #7663: Wrong USD denomination on gallery item, in list it's ok
https://canary.kodadot.xyz/ahp/gallery/13-565

image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix

  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #7663
  - [ ] Requires deployment <snek/rubick/worker>

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

image

  ## Copilot Summary
  
### <samp>🤖 Generated by Copilot at 9062b61</samp>

This pull request enhances the gallery item action section by showing more accurate and consistent token balances and prices. It refactors some code in `GalleryItemActionSection.vue` to use a new function and clearer variable names.

  
### <samp>🤖 Generated by Copilot at 9062b61</samp>

> _To display token prices and balances_
> _The code needed some enhancements_
> _It used `calculateBalanceUsdValue`_
> _To convert and round with a clue_
> _And renamed some vars for clearances_

### CODE REVIEW

**Review by roiLeo — CHANGES_REQUESTED** [review]
https://deploy-preview-7666--koda-canary.netlify.app/ahp/gallery/13-565

Screenshot 2023-10-16 at 08-38-56 Rare Whale

**Comment by Jarsen136** [comment]
> https://deploy-preview-7666--koda-canary.netlify.app/ahp/gallery/13-565
> 
> Screenshot 2023-10-16 at 08-38-56 Rare Whale


It looks like a network request failure. Could you please try again?
image

**Comment by roiLeo** [comment]
> It looks like a network request failure. Could you please try again? 

Still the same only issue i see in console
Capture d’écran 2023-10-16 à 10 02 01 AM

**Comment by roiLeo** [comment]
> https://canary.kodadot.xyz/ahp/gallery/13-565

Nein

Screenshot 2023-10-16 at 10-19-40 Rare Whale

I'll check out your branch

**Review by roiLeo — CHANGES_REQUESTED** [review]
This is `NaN`:
`const number = Number(value.toLocaleString().replace(/,/g, ''))`

`1000` in my local is `1 000`

**Comment by Jarsen136** [comment]
> This is `NaN`: `const number = Number(value.toLocaleString().replace(/,/g, ''))`
> 
> `1000` in my local is `1 000`

Interesting. I will check it.

**Review by roiLeo — APPROVED** [review]
Now it work, ty!

Screenshot 2023-10-16 at 10-54-48 Rare Whale

**Comment by yangwao** [comment]
image
interesting
- https://app.netlify.com/sites/koda-canary/deploys/652cf9814c857f000971a6b3

**Comment by yangwao** [comment]
retried deployment, let's see, if it works I'll merge it  as it's blocking few other things for me

**Comment by yangwao** [comment]
looks works for me here

image

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 3.78 USD/DOT ~ 7.937 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x45027f87d2d738f7e81d0e63b7715958cfeeec10c82e34a5f89ce0d4dea6dce7](https://polkadot.subscan.io/extrinsic/0x45027f87d2d738f7e81d0e63b7715958cfeeec10c82e34a5f89ce0d4dea6dce7)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
