### PR TITLE
subsocial

### PR DESCRIPTION
**Pull request by vikiival**
- WIP: latest subsocial
- fixed packages
- Guess What
- 199 back on track
- 199 flexing
- 199 comments WIP
- 199  WIP reply should work at this moment
- 199 fails on PostExtension/Comment
- 199 Upvote works
- 199 can post <3
- 199 working post + small css flex
- 199 in case of fire
- 199 ready for posting on subsocial
- 199 in case of fire
- 199 post should work
- fixed post resolving

#### Comments
- [x] if `post` show comments
- [x] show nested comments 

#### Likes
- [x] if `comment` show likes
- [x] create like
- [x] change like
- [x] remove like

#### Post
- [x] if `!post` show post button
- [x] create post

#### Edge Cases
- [x] if `!balance` show faucet
- [x] if `!account` show : "Log in"
- [x] if `!balance` disable reply, post and likes
- [x] reload comments/ikes after  change
- [ ] add some magic `nftId` to IPFS DAG ?

### CODE REVIEW

**Comment by yangwao** [comment]
Merge from Main 👀

**Comment by yangwao** [comment]
Demo https://deploy-preview-458--nftkodadot.netlify.app/rmrk/detail/7843653-0E76E3AC15B4C1FA1E-VOLCANO-BITCOIN_VOLCANO_MINING-0000000000000001

**Comment by yangwao** [comment]
Make it pink, 
embrace same united style
image

**Comment by yangwao** [comment]
> You have to be logged in
-> "You have to be logged in to vote and comment." ?

**Comment by yangwao** [comment]
What about adding some padding lines as Reddit does?
image

**Comment by yangwao** [comment]
Showign there are two comments 
image

Probably 2 top level comments?

But turns out there are 7 of them
image

**Comment by vikiival** [comment]
`2 comments` have depth 0
other comments are replies to other

**Comment by yangwao** [comment]
> I guess we could show a number of top-level comments & total comments?

What about this?

**Comment by yangwao** [comment]
lol faucet is gone 
image

**Pull request merged**
