### PR TITLE
refactor: using nuxt helper to detect network connection

### PR DESCRIPTION
**Pull request by KngZhi**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #2645
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer?target=DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc&usdamount=100&donation=true)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by roiLeo** [comment]
pay 50

**Comment by KngZhi** [comment]
Hey @yangwao, could you check this payout, it seems wasn't sent successfully?

**Comment by yangwao** [comment]
Interesting seems something with a link or address.

processed manually https://kusama.subscan.io/extrinsic/0x05a63c8f0146ee8feed6d1ee8e4815ac9c75d40ab6c40fc7282012d51b5f47e2

**Comment by KngZhi** [comment]
Yeah, hahaha, it seems the payout bot only process link prefixed with `https://beta.kodadot.xyz`. If using `https://kodadot.xyz` it would be error.

**Pull request merged**
