### PR TITLE
Series table

### LINKED ISSUE #1057: Add number of trades on series
When I'm eyeballing the collection, an interesting fact could be, 
how many trades happened compared to volume.

Add a column to show the number of total BUYs

image

### PR DESCRIPTION
**Pull request by devVenus1202**
**Thank you for your contribution** to the KodaDot NFT gallery.

👇 Let's do a quick check before the merge.

### PR type
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional
- [x] I've tested PR on mobile and everything works
- [ ] I found edge cases

### What's new?
- [x] PR closes #1057
- [ ] add number of trades in the collection series table

### Had issue bounty label ?
- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=HPQZ5yS3oKSwQwpiReGuo2Ug7qm9RR64bZXMfNbh8rD8Mwa)

### Community participation
- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [x] My fix has changed **something** on UI, a screenshot for others, is best to understand changes.

### CODE REVIEW

**Comment by yangwao** [comment]
I would move BUYs column right after Floor price and let's merge it! :)

**Comment by devVenus1202** [comment]
Okay, I will move it.

**Comment by devVenus1202** [comment]
@yangwao , I moved buys column to right of floor price.

**Comment by yangwao** [comment]
Hey, seems it doesn't work properly. 
Sorted by BUYs highest to descending 
This is what I've got
image

**Comment by yangwao** [comment]
Hey @devVenus1202 I've put it into the draft as it's not working. 
Lmk when it's would be working.

**Comment by devVenus1202** [comment]
Hey @yangwao,  I updated it to sort by buys.
Please check it.

**Comment by yangwao** [comment]
I mean, let's merge it.
Payout sent! https://kusama.subscan.io/extrinsic/0xd2cb95fd62f98cde83f1ce47dab3fa7636b111116a193f6185d26b7c376f7f4f

**Pull request merged**
