### PR TITLE
#2774 Extended number of items from collection at item

### LINKED ISSUE #2774: Extended number of items from collection at item
Let's extend the number of showing items from the collection to 20 at item view.

image

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #2774
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
I tested on different nft and there are times when it is displayed less than 20 items (any substrate knights collection)
You should filter the burned nft too in the query just in case

**Comment by prachi00** [comment]
> I tested on different nft and there are times when it is displayed less than 20 items (any substrate knights collection) You should filter the burned nft too in the query just in case

@roiLeo added burned check

**Review by roiLeo — APPROVED** [review]
> I tested on different nft and there are times when it is displayed less than 20 items (any substrate knights collection)

My bad, I didn't knew that we display only listed nfts in this component

**Comment by roiLeo** [comment]
pay 50 usd

**Comment by roiLeo** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 182.41 USD/KSM ~ 0.274 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0xce89993a8a663e6a8680297eaee2e39e89692c58c00d691a456dfc12b660e6f9](https://kusama.subscan.io/extrinsic/0xce89993a8a663e6a8680297eaee2e39e89692c58c00d691a456dfc12b660e6f9)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
