### PR TITLE
fix: Unnecessary zeros

### LINKED ISSUE #8956: Unneccessary zeros
There zeros are unneccessary. Can we have always just 0.5 and 0.3? 

Drop page
On production

Screenshot 2024-01-11 at 17 02 04

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix

  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #8956

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

image

image

  ## Copilot Summary
  copilot:summary

  copilot:poem

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
might need to check if every format is good now

**Review by preschian — APPROVED** [review]

**Comment by prury** [comment]
previously comma was showing and now it isn't, apart from that everything else looks good

https://github.com/kodadot/nft-gallery/assets/36627808/1e5970d4-a7ba-48e5-9bda-c815ff08ce5f

**Comment by Jarsen136** [comment]
> previously comma was showing and now it isn't, apart from that everything else looks good
> 
>  comma.mp4

How about now? It should work for you too. @prury

**Comment by prury** [comment]
> > previously comma was showing and now it isn't, apart from that everything else looks good
> > comma.mp4
> 
> How about now? It should work for you too. @prury

it works, thank you! my prices on explorer show with a comma as well too, nice

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 7.59 USD/DOT ~ 3.953 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x9c6f16ab616ffd71301ef36b53d20ad89909029ea5a6c59ad7b421cd08b32edd](https://polkadot.subscan.io/extrinsic/0x9c6f16ab616ffd71301ef36b53d20ad89909029ea5a6c59ad7b421cd08b32edd)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
