### PR TITLE
add: Generate new cursor loading state

### LINKED ISSUE #8634: Generate new cursor loading state
I used the Talisman app and saw this. I think it would be nice to use on our generate new button 
image

image

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #8634

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2023-12-26 at 11 10 37

## Copilot Summary
copilot:summary

copilot:poem

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
hmmmm... might be good to wrap `document.body` with `process.client`

I would only use css for this solution (hover state on btn loading) but if it's what's excepted then let's go 🚀

**Comment by hassnian** [comment]
> I would only use css for this solution **(hover state on btn loading)** but if it's what's excepted then let's go 🚀

@exezbcz should the loading cursor be present only on hover btn or the entire page

**Comment by exezbcz** [comment]
@hassnian should be only over the button, sorry i did not specify it


thanks!

**Comment by exezbcz** [comment]
thank you!

**Review by vikiival — APPROVED** [review]

**Pull request merged**
