### PR TITLE
fix: Remove upcoming section when empty

### LINKED ISSUE #7848: Remove upcoming section when empty
image
- there hasn't been an upcoming drop since we created the drop landing page
- remove when empty 
- if there will be an upcoming drop, this section will show 
- please keep the divider there

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix

  ## Needs Design check

  - @exezbcz please review

  ## Context

  - [x] Closes #7848
  - [ ] Requires deployment <snek/rubick/worker>

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

image

  ## Copilot Summary
  
### <samp>🤖 Generated by Copilot at e48f93e</samp>

Removed unused code from `components/drops/Drops.vue`. Simplified the drops page UI by relying on existing components.

  
### <samp>🤖 Generated by Copilot at e48f93e</samp>

> _No more title, message_
> _`upcomingDrops` code removed_
> _Winter of empty state_

### CODE REVIEW

**Comment by exezbcz** [comment]
I would also increase the margin


image

- to 40px please

**Comment by Jarsen136** [comment]
> I would also increase the margin
> 
> image
> 
> * to 40px please

Done

**Comment by yangwao** [comment]
thanks!
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 4.21 USD/DOT ~ 4.751 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x31a72914d1a277eb4c27d29ed64460b095b033f91562335f4ad24ab0f88738e4](https://polkadot.subscan.io/extrinsic/0x31a72914d1a277eb4c27d29ed64460b095b033f91562335f4ad24ab0f88738e4)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
