### PR TITLE
fix: Use new logo on our app

### LINKED ISSUE #10369: Use new logo on our app
KODA_fill_dark
KODA_fill_dark
KODA_transparent_dark
KODA_transparent_dark
------------

Light mode:
KODA_fill
KODA_fill
KODA_transparent
KODA_transparent

## Info
- there is both filled and transparent, png and SVG

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs Design check

- @exezbcz please review

## Context

- [x] Closes #10369

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by exezbcz** [comment]
fast, thanks a lot and works for me

**Comment by prury** [comment]
placeholder will only be updated for new mints, correct?

**Comment by Jarsen136** [comment]
> placeholder will only be updated for new mints, correct?

placeholder image for nft? It will not update.
That needs another design btw.

**Comment by prury** [comment]
> > placeholder will only be updated for new mints, correct?
> 
> placeholder image for nft? It will not update. That needs another design btw.

@exezbcz

**Review by preschian — APPROVED** [review]

**Review by vikiival — APPROVED** [review]
Amazing!

**Pull request merged**
