### PR TITLE
🔧 invalid props

### LINKED ISSUE #5947: Neo Modal invalid props
image

```rootClass``` ```contentClass```  props don't exist in oruga modal
https://oruga.io/components/Modal.html#props

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5947
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=v)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at b6f43f6</samp>

Refactored the `NeoModal` component to remove unnecessary code and improve readability. Used the `class` prop to allow custom styles for different modal types.

### <samp>🤖 Generated by Copilot at b6f43f6</samp>

> _Oh we're the crew of the NeoModal, we like to keep things neat_
> _We don't need no redundant props or data to repeat_
> _We heave away and simplify the template and the script_
> _We only use the `class` prop to give our modal some zip_

### CODE REVIEW

**Review by preschian — APPROVED** [review]

**Comment by roiLeo** [comment]
Hmm.. It can be used as [prop](https://oruga.io/documentation/#overriding-classes) ([Modal Doc](https://oruga.io/components/Modal.html#class-props))

**Comment by daiagi** [comment]
It crashes the app on local host and prevent the modal from showing on canary

**Comment by roiLeo** [comment]
> It crashes the app on local host and prevent the modal from showing on canary

```vue
const props = withDefaults(
  defineProps<{
    value: boolean
    destroyOnHide?: boolean
    canCancel?: boolean
    fullScreen?: boolean
    contentClass?: string
    rootClass?: string
  }>(),
  {
    destroyOnHide: true,
    canCancel: true,
    fullScreen: false,
    contentClass: '',
    rootClass: '',
  }
)
```

**Review by roiLeo — APPROVED** [review]
✅ code lgtm

**Pull request merged**
