### PR TITLE
Korean lang

### PR DESCRIPTION
**Pull request by yangwao**

### CODE REVIEW

**Comment by vikiival** [comment]
unable to fix this one 

```json
{
 "FAQA3": "<a href=\"/#/rmrk/create\"로 이동합니다.">만든다. 먼저 컬렉션을 만든 다음 토큰을 만들어야 합니다. 비디
    오로 녹화하려면 디엠주세요!",
 }
 ```
 
` parse error: Invalid numeric literal at line 75, column 71`

**Comment by vikiival** [comment]
And lot of translations are missing

**Comment by yangwao** [comment]
Which are missing? 👀

**Comment by yangwao** [comment]
Android clipboard has limits.
Thanks for Korean translations to https://t.me/fireantcrypto

**Pull request merged**
