### PR TITLE
fix/input-dark-mode

### LINKED ISSUE #3830: Black on black input on LIST
Black on black while listing NFT 
Please check all inputs 😇🙏

https://user-images.githubusercontent.com/5887929/186452771-b0a77c6c-790c-4a80-8515-596a281882c1.mov

### PR DESCRIPTION
**Pull request by KngZhi**
- fix: all input color

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3830
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer?target=HgpGWWmqrw8t6viwSy6LPcTVr2SuVPKWW5ArdNp2xCJY2U4)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by KngZhi** [comment]
Fixed all input colors including balance input.

**Review by prachi00 — APPROVED** [review]

**Review by roiLeo — COMMENTED** [review]
> Fixed all input colors including balance input.

Screenshot 2022-08-25 at 08-53-13 KodaDot - Kusama NFT Market Explorer

cover4

**Comment by KngZhi** [comment]
There is always a corner you don't know when you changed css.

image

**Comment by cryptodamsky** [comment]
While hovering over some fileds in the navbar, this could be fixed aswell?

image

**Review by roiLeo — APPROVED** [review]
this changes will fix dark-mode inputs only

**Comment by yangwao** [comment]
pay 50

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 48.71 USD/KSM ~ 1.026 $KSM
🧗 [HgpGWWmqrw8t6viwSy6LPcTVr2SuVPKWW5ArdNp2xCJY2U4](https://kusama.subscan.io/account/HgpGWWmqrw8t6viwSy6LPcTVr2SuVPKWW5ArdNp2xCJY2U4)
🔗 [0x0852a5ea98a4de885efe916ed2d4e5e33b310de3beab1dfa708d7c0b777c5a81](https://kusama.subscan.io/extrinsic/0x0852a5ea98a4de885efe916ed2d4e5e33b310de3beab1dfa708d7c0b777c5a81)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
