### PR TITLE
fix: offer request fail while non-logged

### LINKED ISSUE #3920: bad user input at global offers
while I visit non-logged, got error from graphql endpoint 
https://beta.kodadot.xyz/snek/offers/

```
"message": "Variable \"$id\" of required type \"String!\" was not provided.",
            "extensions": {
                "code": "BAD_USER_INPUT",
                "exception": {
                    "stacktrace": [
                        "GraphQLError: Variable \"$id\" of required type \"String!\" was not provided.",
                        "    at _loop (/squid/node_modules/graphql/execution/values.js:94:17)",
                        "    at coerceVariableValues (/squid/node_modules/graphql/execution/values.js:121:16)",
                        "    at getVariableValues (/squid/node_modules/graphql/execution/values.js:50:19)",
                        "    at buildExecutionContext (/squid/node_modules/graphql/execution/execute.js:203:61)",
                        "    at executeImpl (/squid/node_modules/graphql/execution/execute.js:101:20)",
                        "    at execute (/squid/node_modules/graphql/execution/execute.js:60:35)",
                        "    at execute (/squid/node_modules/apollo-server-core/dist/requestPipeline.js:205:48)",
                        "    at processGraphQLRequest (/squid/node_modules/apollo-server-core/dist/requestPipeline.js:148:34)",
                        "    at runMicrotasks (<anonymous>)",
                        "    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
                    ]
                }
            }
```

image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3920
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by prachi00** [comment]
This is probably not related to this PR but when not logged in, and you reload on rmrk, there is an error 
Screen Shot 2022-09-07 at 10 31 14 PM

**Comment by prachi00** [comment]
and on Snek also
https://www.loom.com/share/abe5217107d34717b1d6f1b7ee5a3935
there is this error

**Comment by Jarsen136** [comment]
>This is probably not related to this PR but when not logged in, and you reload on rmrk, there is an error

will take a look




> and on Snek also https://www.loom.com/share/abe5217107d34717b1d6f1b7ee5a3935 there is this error

This error was traced in another issue https://github.com/kodadot/nft-gallery/issues/3919

**Comment by Jarsen136** [comment]
> This is probably not related to this PR but when not logged in, and you reload on rmrk, there is an error Screen Shot 2022-09-07 at 10 31 14 PM

✅  Fixed

**Comment by prachi00** [comment]
> > This is probably not related to this PR but when not logged in, and you reload on rmrk, there is an error Screen Shot 2022-09-07 at 10 31 14 PM
> 
> ✅ Fixed

Screen Shot 2022-09-09 at 11 42 32 AM
I see this

**Comment by Jarsen136** [comment]
> Screen Shot 2022-09-09 at 11 42 32 AM
> 
> I see this

It also should be solved in #3919

**Review by vikiival — APPROVED** [review]
Code LGTM.

**Review by prachi00 — APPROVED** [review]

**Comment by petersopko** [comment]
@Jarsen136 can you please also take a look at this? non-logged in user behavior at snek/offers
image

**Review by petersopko — CHANGES_REQUESTED** [review]
check pls

**Comment by petersopko** [comment]
nevermind, another variation of: 
- https://github.com/kodadot/nft-gallery/issues/3919

**Comment by Jarsen136** [comment]
> @Jarsen136 can you please also take a look at this? non-logged in user behavior at snek/offers image

Yes but I could not reproduce this error in beta env or 
https://deploy-preview-3921--koda-nuxt.netlify.app/snek/offers 

Could you expand it more?

**Review by petersopko — APPROVED** [review]

**Comment by petersopko** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 52.9 USD/KSM ~ 0.945 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x81ae1511a132454216aaf1c38d7a54b10cbb24ce80abc3afcf69a4ae9ee3a917](https://kusama.subscan.io/extrinsic/0x81ae1511a132454216aaf1c38d7a54b10cbb24ce80abc3afcf69a4ae9ee3a917)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
