### PR TITLE
fix: gallery sorting was broken on rmrk

### LINKED ISSUE #3696: when I'm going from landing to newest lists on rmrk
I'll land on https://beta.kodadot.xyz/rmrk/explore?page=1&sort=UPDATED_AT_DESC&tab=GALLERY and seems we don't support filters through subsquid there? 

https://user-images.githubusercontent.com/5887929/183407915-2df1c6b9-11b3-4d7a-a724-1b004ef60267.mov

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3696
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Review by prachi00 — APPROVED** [review]

**Comment by prachi00** [comment]
LGTM

**Comment by cryptodamsky** [comment]
image


Probably not ideal? 

It should disappear

**Comment by petersopko** [comment]
> Probably not ideal?
> 
> It should disappear

If the user wants to select more than one sorting criteria, he would have to open it up again. If he wanted to select 3 sorting options, that's three clicks/taps on "Sort By". 

But it does feel off in the current implementation. I think search section will be one of the most refactored parts with the upcoming redesign and refactor, we'll address the whole filtering part for sure to make it more user friendly :)

That being said, sorting works for me here.

**Comment by petersopko** [comment]
`:data-cy="$t('sort.' + action)">`

@Jarsen136 thankfully we have working tests in pipeline now, you're the first one running into issue here 😆 basically, the way we target the tested elements is by adding custom html tags which we use as selectors. I assume, the test is failing in this case, because you've changed something regarding these tags. Can you check pls? 
https://docs.cypress.io/guides/references/best-practices

// this is partially my fault, we need some docs to make sure devs keep the tests updated in case they're touching it

**Review by petersopko — CHANGES_REQUESTED** [review]
make tests happy 🙏🏻

**Comment by Jarsen136** [comment]
I will check it later.

**Comment by Jarsen136** [comment]
The root issue is the query `nftListWithSearch` do not support sorting by `most reacted`,  after this commit 52af7112ce8b66f5cacd9dcff1b8ee51dae26656, which replace Magick with rubick for rmrk.

I remove this sort condition in this PR, so the e2e test failed.
I guess we need to do something in `rubick` to bring `most reacted` back. cc @vikiival 👀

**Comment by Jarsen136** [comment]
The e2e test passes now.

**Comment by petersopko** [comment]
pay 75 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $75 @ 61.84 USD/KSM ~ 1.213 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x507dbf19608128399af1127ab9fce664fcdc492e88fe598c86626fb4f43d7cc6](https://kusama.subscan.io/extrinsic/0x507dbf19608128399af1127ab9fce664fcdc492e88fe598c86626fb4f43d7cc6)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
