### PR TITLE
🔧 evm close modal reconnect

### LINKED ISSUE #10754: xmark does not close reconnect modal + styling
https://github.com/user-attachments/assets/fecbcf31-d7cf-4196-a1f9-efb1d33dc5b9

x mark does not close modal, clicking outside does. 

cc @hassnian

### PR DESCRIPTION
**Pull request by roiLeo**
## PR Type

- [x] Bugfix

## Needs Design check

- @exezbcz please review

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #10754 

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=167akbb3uAPL7GLeFpvFuKAVdU9fcGsEWs7Uk8xgUKZEuXpC)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

https://github.com/user-attachments/assets/43ddd3b8-ae65-4db2-b8d7-92b12e2b3e3d

### CODE REVIEW

**Review by preschian — APPROVED** [review]

**Comment by Jarsen136** [comment]
It seems that this bug has been fixed on canary env. Could you please check it? @roiLeo

**Comment by roiLeo** [comment]
> It seems that this bug has been fixed on canary env. Could you please check it? @roiLeo

the modal is not showed anymore .. but it still fix the bug if you display it

**Comment by Jarsen136** [comment]
> > It seems that this bug has been fixed on canary env. Could you please check it? @roiLeo
> 
> the modal is not showed anymore .. but it still fix the bug if you display it


I just tested it on `https://canary.kodadot.xyz/base/drops/quadz`

Kapture 2024-08-22 at 11 27 31

**Comment by roiLeo** [comment]
> I just tested it on `https://canary.kodadot.xyz/base/drops/quadz`

Aight, close issue + PR then

**Pull request closed without merging**
