### PR TITLE
Remove subsocial implementation

### LINKED ISSUE #1259: Remove Subsocial from Nuxt
remove subsocial packages and rest stuff which is connected to it 

`yarn remove @subsocial/api @subsocial/types @subsocial/utils`

image

### PR DESCRIPTION
**Pull request by dezine2dev**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇  _ Do a quick check before the merge. 

### PR type
- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted screenshot of demonstrated change in this PR

### What's new?
- [x] PR closes #1259 
- [x] Removed everything related to subsocial

### Question
I also removed pinPost.ts, searchPost.ts and requestFaucet.ts in src-functions. Is this ok?

### CODE REVIEW

**Comment by roiLeo** [comment]
Ref #498, #686, #888

**Comment by vikiival** [comment]
😿

**Comment by vikiival** [comment]
@dezine2dev pls resolve conflicts and we can push this out. It's blocking for #1110

**Comment by dezine2dev** [comment]
> @dezine2dev pls resolve conflicts and we can push this out. It's blocking for #1110

Yes resolved

**Review by vikiival — APPROVED** [review]

**Pull request merged**
