### PR TITLE
🔧 NeoField & NeoInput

### PR DESCRIPTION
**Pull request by roiLeo**
Related with #6116 

- fixed inputs padding
- fixed text label weight & padding
- fixed counter position
- fixed error icon not showin
- fixed textarea placeholder color
- Removed duplicate import
- Removed unused code

Screenshot 2023-06-05 at 14-39-14 KodaDot Low fees and low carbon minting KodaDot - NFT Market Explorer

### // TODO
- [ ] rewritte `AddressInput`
- [ ] fix /transfer grouped fields
- [ ] ??

### CODE REVIEW

**Comment by prury** [comment]
looking cool! 
some small adjustments(RMRK1 and 2): 
image
image

**Comment by prury** [comment]
Royalty rate on white mode: 
image

**Comment by roiLeo** [comment]
> its best that i open a new issue then! ty, sorry to bother

Plus I think we have a new profile page design in pipeline (but I can't find the related issue) @kodadot/design-squad

**Review by vikiival — APPROVED** [review]
Code LGTM ✅

**Comment by exezbcz** [comment]
@roiLeo correct

**Pull request merged**
