### PR TITLE
feat: show recent NFT listings in SearchBar on focus 🔍 

### LINKED ISSUE #2257: On focus in search bar show recent listings
Once the user focus, spin up a query that would show recent listed (maybe option for sold) NFTs (3?), a query could be found in #2018  
Later could be combined with #2222 for more refined results for logged in user.

- #1294

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

Screenshot 2022-04-21 at 13 37 31

### What's new?

- [x] PR closes #2257
- [x] when user focuses searchbar in navbar, show recent listings if no query is set yet

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by yangwao** [comment]
siiick

image

**Review by prachi00 — APPROVED** [review]

**Comment by prachi00** [comment]
@kkukelka found this bug, I can still see the results from bear after clearing

https://user-images.githubusercontent.com/39299315/164711967-571c3bba-bb28-44fe-b7d8-cf3f5c3ed2c2.mov

**Review by prachi00 — CHANGES_REQUESTED** [review]
bug found

**Comment by kkukelka** [comment]
> @kkukelka found this bug, I can still see the results from bear after clearing

@prachi00  interesting catch. don't know if it's an actual bug, but i can see that it could be confusing to users. 
fixed it by resetting nft and collection results once query is emptied

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 165.07 USD/KSM ~ 0.606 $KSM
🧗 [EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW](https://kusama.subscan.io/account/EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)
🔗 [0xfc378a0152653635d0950176cf3e1a89f1059df0286780cb7a18f34104425a66](https://kusama.subscan.io/extrinsic/0xfc378a0152653635d0950176cf3e1a89f1059df0286780cb7a18f34104425a66)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
