### PR TITLE
fix: gallery item event chart not working

### LINKED ISSUE #7107: gallery item chart not working
### What happened?

All gallery item charts are now empty.

example:
https://canary.kodadot.xyz/rmrk/gallery/9437001-c095ca1430a05e7d6b-TOPIA-CRYSTAL_MOTHER_097-0000000000000097

https://github.com/kodadot/nft-gallery/assets/10708802/12938074-faad-41fa-9ba1-22a6d5758ece

### Please reproduce in steps

1. goto any nft detail page
2. check chart tab

### Expected Behavior

If nft has LIST and BUY events, then the chart should have content.

### What browsers are you seeing the problem on?

_No response_

### At which address did you encounter bug?

_No response_

### Are you logged in?

None

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

_No response_

### Screenshots

see above.

### Relevant log output

_No response_

### Payment link for reward

[Payout](https://canary.kodadot.xyz/dot/transfer?target=1CAv6Zq3yVxL3eKhC94GWTWVwp1w4jZbqeZ6wXx1rPAhrce&usdamount=0&donation=true)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by newraina**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #7107 
- [ ] Requires deployment <snek/rubick/worker>

**Cause:**
LazyGalleryHistory component is gone:

CleanShot 2023-09-02-sVtYkpkK@2x

**Fix:** 
- Restore the calculation logic of `priceChartData` in `GalleryItemChart.vue`.
- Remove the `priceChartData` calculation logic from `History.vue`, as there is no use of the `@setPriceChartData` event anywhere. Also this component is now in the profile directory and is no longer directly related to the gallery item.

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [x] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer?target=1CAv6Zq3yVxL3eKhC94GWTWVwp1w4jZbqeZ6wXx1rPAhrce&usdamount=0&donation=true)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at 8de30c0</samp>

This pull request improves the performance and reusability of the price chart functionality in the gallery and profile components. It extracts the chart logic and data from the `History.vue` component and moves it to the `GalleryItemChart.vue` component, which is simplified and optimized.

### <samp>🤖 Generated by Copilot at 8de30c0</samp>

> _We simplify the template, we remove the unused code_
> _We unleash the power of `GalleryItemChart`_
> _We refactor the history, we move the chart logic_
> _We make it reusable, we optimize the performance_

### CODE REVIEW

**Comment by prury** [comment]
i like your bug catching skills @newraina

**Comment by yangwao** [comment]
let's resolve conflicts @newraina 
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 4.23 USD/DOT ~ 11.82 $DOT
🧗 [1CAv6Zq3yVxL3eKhC94GWTWVwp1w4jZbqeZ6wXx1rPAhrce](https://polkadot.subscan.io/account/1CAv6Zq3yVxL3eKhC94GWTWVwp1w4jZbqeZ6wXx1rPAhrce)
🔗 [0x36adfdf733481171ac1f6b2530c4b6c37af139f912509a5d4ac83884f8798b03](https://polkadot.subscan.io/extrinsic/0x36adfdf733481171ac1f6b2530c4b6c37af139f912509a5d4ac83884f8798b03)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by newraina** [comment]
@yangwao resolved, but auto merge was disabled...
CleanShot 2023-09-04-O2e01XM8@2x

**Review by preschian — APPROVED** [review]

**Pull request merged**
