### PR TITLE
e2e: simple mint (rmrk)

### LINKED ISSUE #3680: Simple mint RMRK - E2E Test
We would like to expand our current E2E test by testing simple mint from the user perspective.

Could be done like this:

- [ ]  upload file (https://www.tutorialspoint.com/how-to-upload-a-file-in-cypress)
- [ ] fill out name
- [ ] fill out symbol
- [ ] fill out some tags
- [ ] fill out the price price
- [ ] check out the calculated fees, toggles and check whether button to create NFT gets clickable
image

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3680 

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged the recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by petersopko** [comment]
@kkukelka can we use your 🧠 and experience here? Two questions I have:
1. file structure when it comes to tests. should the logic of singular tests be extracted to custom commands, or is the approach @preschian selected here enough?
2. I've initially crammed all of the tests into one test spec, should we split it in similar fashion to @preschian's approach here?

thanks in advance 🚀

**Comment by kkukelka** [comment]
> @kkukelka can we use your 🧠 and experience here? Two questions I have:
> 
> 1. file structure when it comes to tests. should the logic of singular tests be extracted to custom commands, or is the approach @preschian selected here enough?
> 2. I've initially crammed all of the tests into one test spec, should we split it in similar fashion to @preschian's approach here?
> 
> thanks in advance 🚀

regarding 1.: custom commands are mostly the way 2 go when you have to reuse certain functionality across many tests (logging in the user, filling out a certain type of form, etc). other than that the logic should be in written in the respective test file (like preschian did it)

regarding 2.: it depends. I tend to create 1 test file per user flow i want to test (e.g. Minting an NFT, Minting a Collection, Doing searches in the Gallery). Where I don't have a definitive answer is when it comes to testing the same flow on multiple chains. It might make sense to test both BSX and RMRK in a "CreateNFT" test file.
Furthermore splitting up code into several tests makes debugging tests via the cypress GUI a lot faster.
Additionally, in the future we may run tests in parallel which requires one to have multiple test files.

**Comment by petersopko** [comment]
@kkukelka thanks for clarifying this, can we get reviews from you guys with @Jarsen136 ? 😅

**Review by Jarsen136 — APPROVED** [review]
LGTM

Let's resolve some conflict and it's good to go.

**Comment by Jarsen136** [comment]
There're some new conflicts.

**Comment by petersopko** [comment]
> There're some new conflicts.

aaand again. sorry, if you can resolve them now, we can go forward with merging :)

**Review by kkukelka — APPROVED** [review]

**Comment by petersopko** [comment]
pay 50 usd

**Comment by petersopko** [comment]
> pay 50 usd

we know bot doesn't work, I'm posting this here regardless so @yangwao has perhaps an easier time to follow-up

**Comment by yangwao** [comment]
pay 50

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 54.64 USD/KSM ~ 0.915 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0x0b9b7af60f7638eb5c87faf727b2086b1ceb70768d04881f94bbd8b67b69a08e](https://kusama.subscan.io/extrinsic/0x0b9b7af60f7638eb5c87faf727b2086b1ceb70768d04881f94bbd8b67b69a08e)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
