### PR TITLE
fix: Withdraw or accept offer wont refresh table

### LINKED ISSUE #5880: Withdraw or accept offer wont refresh table
### What happened?

commit 1c400d32bc32f08fe3f0ed73b8068a3cbc2b1a2e removed ability to refetch table after transaction is successfully submitted

### Please reproduce in steps

1. on Snek/bsx chain make an offer
2. withdraw the offer
3. change is not reflected

### Expected Behavior

The table would refresh

Quick and dirty hack

```ts
watch(status, (value, oldValue) => {
  if (shouldUpdate(value, oldValue) && status === 'loader.finalized') {
    refetch()
  }
})

```

### What browsers are you seeing the problem on?

_No response_

### At which address did you encounter bug?

_No response_

### Are you logged in?

None

### Which wallet you are using?

_No response_

### Screenshots

~

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5880
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at d1fc7f8</samp>

Improved the offers component to update automatically when offers change. Used a new hook to subscribe to a GraphQL query for offers by `nftId`.

### <samp>🤖 Generated by Copilot at d1fc7f8</samp>

> _`useSubscriptionGraphql`_
> _Subscribes to offers for NFT_
> _Data refreshes like spring_

### CODE REVIEW

**Comment by vikiival** [comment]
cc @kodadot/qa-guild

**Comment by vikiival** [comment]
@yangwao this would be also worth to beta

**Comment by vikiival** [comment]
LOOKS LIKE THERE IS SOME Balance issue

Screenshot 2023-05-12 at 14 03 07

Screenshot 2023-05-12 at 14 03 16

**Comment by Jarsen136** [comment]
> LOOKS LIKE THERE IS SOME Balance issue
> 
> Screenshot 2023-05-12 at 14 03 07 Screenshot 2023-05-12 at 14 03 16

I have created an issue for this bug because it's not related to this PR. It only happens on the nft that has no price on bsx. 

 /bsx/gallery/226018301-16
image

**Review by preschian — APPROVED** [review]

**Comment by vikiival** [comment]
pay 10 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $10 @ 25.52 USD/KSM ~ 0.392 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x2894d9fc948935f25df77e1b3346774ec94d101d847464fb96cdfbbc5c6187d1](https://kusama.subscan.io/extrinsic/0x2894d9fc948935f25df77e1b3346774ec94d101d847464fb96cdfbbc5c6187d1)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
