### PR TITLE
fix: Party kit followups

### LINKED ISSUE #9422: No hover or click possible over other cursors - partykit
image
this can lead to blocking generate new button if there are more users than one :D

### LINKED ISSUE #9423: Party kit followup
image

it can be smoother - wao mentioned something with the usage and placement

some cursors in dark mode are the same as the background - when you switch to light, its for example pink 

image

cc @hassnian

### LINKED ISSUE #9428: Cursors showing 0 DOT
Not inherently bug but I sense maybe it doesn't load balances always? 
Or I mean it's fresh address which spent? 

I was thinking that showing maximum 10 of "0 DOT" cursors? 

image

### LINKED ISSUE #9451: Partykit other cursor's opacity is not lowered when hovering over preview card
### What happened?

sometimes other cursor's opacity is not lowered when hovering over preview card 

CleanShot 2024-02-17 at 11 23 07@2x

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

❗️ Needs https://github.com/kodadot/workers/pull/252

- [x] Closes #9423
- [x] Closes #9422
- [x] Closes #9428
- [x] Closes #9451

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [ ] My fix has changed **something** on UI;

### CODE REVIEW

**Comment by yangwao** [comment]
probably this supposed to be me 

telegram-cloud-photo-size-4-5945224384484589729-m

but on profile

image

**Comment by hassnian** [comment]
> probably this supposed to be me
> 
> telegram-cloud-photo-size-4-5945224384484589729-m
> 
> but on profile
> 
> image

I thought it was total spent on that specific drop, just fixed it, now it will show the same value as the profile page

**Comment by yangwao** [comment]
found some niche bug 

telegram-cloud-photo-size-4-5947351600181918965-x

**Comment by yangwao** [comment]
> found some niche bug

ok double cursor it's official

image

**Comment by yangwao** [comment]
or it's some state? 

image

**Comment by hassnian** [comment]
since the worker is not updated , I'd say that is the issue

**Comment by yangwao** [comment]
> since the worker is not updated , I'd say that is the issue

should be deployed already

**Comment by yangwao** [comment]
rounded numbers as three decimals are useless in this case and we can push it to canary

telegram-cloud-photo-size-4-5947351600181919001-m

**Comment by yangwao** [comment]
Thanks!
pay 80 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $80 @ 7.59 USD/DOT ~ 10.54 $DOT
🧗 [16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD](https://polkadot.subscan.io/account/16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)
🔗 [0x70f4e8cb9a3efa37784b4f11f522b9e0769fe3f8c515ba0a20c2bcab83ceec16](https://polkadot.subscan.io/extrinsic/0x70f4e8cb9a3efa37784b4f11f522b9e0769fe3f8c515ba0a20c2bcab83ceec16)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
