### PR TITLE
🐛 chain on carousel nft cards

### LINKED ISSUE #4787: Show network on NFT cards
some of the cards dont have network displayed. The item can be unlisted but the network should be there.
image
image
- happens mostly in gallery item.

### PR DESCRIPTION
**Pull request by petersopko**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4787 
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [x] I've tested it at </bsx/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

### CODE REVIEW

**Comment by exezbcz** [comment]
image
font size of colletion, price, network should be 12px (text small)

**Comment by petersopko** [comment]
@exezbcz fixed the font, I just thought since we have 16px + 16px (price + chain) on gallery item cards, we want the same here. 

gallery item:
image

carousel item (16+12):
image

**Comment by exezbcz** [comment]
the spotlight still looks different compared to beta.kodadot.xyz
beta:
image
deploy:

**Comment by petersopko** [comment]
changed font of price to 12 to match:
image

empty carousel cards should be empty now:
image

**Review by roiLeo — APPROVED** [review]
☑️ wfm

**Comment by exezbcz** [comment]
ou, we can maybe leave the price 16px, sorry, my bad - it was a design for the dynamic grid minimal cards and it looked ok. 
Otherwise its alright!

**Comment by petersopko** [comment]
> Otherwise its alright!

I think it's all good now :)

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 35.93 USD/KSM ~ 0.835 $KSM
🧗 [FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y](https://kusama.subscan.io/account/FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y)
🔗 [0x80b20e53e33c49a14f6540dd13b29a45597519f6d5c48333e9de952e28f45e97](https://kusama.subscan.io/extrinsic/0x80b20e53e33c49a14f6540dd13b29a45597519f6d5c48333e9de952e28f45e97)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
