### PR TITLE
feat: generate substack post before build command

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] add small script to fetch substack post
- [x] no need to update substack.json to git. it will fetch latest post before `pnpm generate` command. if there are some new post, just retry deployment to get newest post
- [x] add retry some command in e2e.yml

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

### CODE REVIEW

**Comment by Jarsen136** [comment]
That's really a smart way to update the article automatically. 👍 
However, I just have one question. What if we would like to pick up some selected articles instead of the latest three 🤔 

beta env:
image


the latest three articles:

image

**Comment by Jarsen136** [comment]
> > What if we would like to pick up some selected articles instead of the latest three 🤔
> 
> can't, it only gets the latest 3
> 
> another approach if we want selected articles: put `substack.md` in this public repo https://github.com/kodadot/docs so the non-dev team can edit the file directly. and our script fetches that `.md` file
> 
> format on that `.md` file something like this:
> 
> ```
> # https://kodadot.substack.com/p/travel-with-kodadot-to-lisbon-and
> # https://kodadot.substack.com/p/ride-on-art-7-chigo-artish
> # https://kodadot.substack.com/p/how-was-dotbrno
> ```

Good idea! This approach would be more flexible. I prefer this one and let's wait for the other team members' confirmation.

**Comment by vikiival** [comment]
@kodadot/internal what do you think?

**Comment by cryptodamsky** [comment]
We’ll be switching back over to medium unfortunatelly

**Comment by yangwao** [comment]
> We’ll be switching back over to medium unfortunatelly

We will keep Substack for current Artist Interviews and Announcements.

We will also look up on Medium as it can give us bit better recognition among other newsletter, we will keep it for ambassadors content and external contributors.

**Review by vikiival — COMMENTED** [review]
Very hacky, isn't there some api that we can use and wrap this to worker instead?

**Review by vikiival — CHANGES_REQUESTED** [review]
```
GET https://kodadot.substack.com/api/v1/archive?sort=new&search=&offset=0&limit=3
```

**Comment by vikiival** [comment]
Otherwise I like your approach!

**Comment by vikiival** [comment]
A I am fine with latest 3

**Review by Jarsen136 — APPROVED** [review]

**Pull request merged**
