### PR TITLE
fix: Error on stick indexer on explorer items with ticked collection

### LINKED ISSUE #7379: Error on stick indexer on explorer items with ticked collection
When I open https://canary.kodadot.xyz/ahk/explore/items?listed=true&collections=u-2024

there is error on `stick` indexer

image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix

  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #7379
  - [ ] Requires deployment <snek/rubick/worker>

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [ ] My fix has changed UI

  ## Copilot Summary
  
### <samp>🤖 Generated by Copilot at 57a67dd</samp>

Refactored `SearchSuggestion` component to use a prop for default suggestions. This improves the component's reusability and responsiveness.

  
### <samp>🤖 Generated by Copilot at 57a67dd</samp>

> _There once was a component `SearchSuggestion`_
> _That used a local variable for default completion_
> _But to make it more flexible_
> _And parent state reflexible_
> _It switched to a prop for better adaptation_

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
what's the default value?
I would only remove suggestion for chain that don't have `series` query (ahp, ahk ..)

**Comment by Jarsen136** [comment]
> what's the default value? I would only remove suggestion for chain that don't have `series` query (ahp, ahk ..)

The default value is prefix equal to rmrk or bsx, that is from the props. The original logic is broken by some refactoring PR IMO.
After this fixing, the  `series` query would not be fetched on the incorrect prefix.

**Review by roiLeo — APPROVED** [review]

**Comment by roiLeo** [comment]
Another issue:
- go to AssetHub chain
- search for something
- floor price show DOT on ksm item

Screenshot 2023-09-27 at 17-31-28 KodaDot - NFT Market Explorer

**Comment by Jarsen136** [comment]
> Another issue:
> 
> * go to AssetHub chain
> * search for something
> * floor price show DOT on ksm item
> 
I will solve it in another issue because it has nothing related to this one. https://github.com/kodadot/nft-gallery/issues/7387

**Pull request merged**
