### PR TITLE
mobile / Nova Wallet -> full screen button in galleryItem

### LINKED ISSUE #8078: Full Screen button not working on Gallery item

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #8078

## Tested

on Android phone with Nova Wallet
on desktop works as before -> no UX change

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)

## Screenshot 📸

- [x] My fix has changed UI

https://github.com/kodadot/nft-gallery/assets/22791238/a2cab763-7ae7-49d7-8d07-bffaf61cfb6b

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 505e00f</samp>

Enhanced the fullscreen functionality and mobile compatibility of the `GalleryItem` component. Removed unused code and added type annotations.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 505e00f</samp>

> _`GalleryItem` shines_
> _Fullscreen fallback and previews_
> _Winter of unused code_

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
Maybe test it on other media

**Review by Jarsen136 — APPROVED** [review]

**Comment by daiagi** [comment]
@yangwao  fixed
photo1700140758

**Comment by yangwao** [comment]
thanks!
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 5.48 USD/DOT ~ 3.65 $DOT
🧗 [1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8](https://polkadot.subscan.io/account/1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)
🔗 [0xa7f7c3208b4244b26b2390543c6cccdafc80b0216252532a3e76ee95aede9a67](https://polkadot.subscan.io/extrinsic/0xa7f7c3208b4244b26b2390543c6cccdafc80b0216252532a3e76ee95aede9a67)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
