### PR TITLE
fix: remove clarity

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] There are too many errors on the console related to the `clarity`

image

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by hassnian** [comment]
Is clarity still being used?

cc @exezbcz

**Comment by exezbcz** [comment]
> Is clarity still being used?
> 
> 
> 
> cc @exezbcz 

Sometimes yup


What is the reason to remove it?

**Comment by vikiival** [comment]
Doesnt it need an update?

**Comment by Jarsen136** [comment]
> Doesnt it need an update?

I have no access to the clarity platform to get the latest code.

https://learn.microsoft.com/en-us/clarity/setup-and-installation/clarity-setup#install-manually

image

**Comment by exezbcz** [comment]
@Jarsen136 can add you

**Comment by Jarsen136** [comment]
The install code is still the same as the current one. There's not much can do from our side.

image

**Comment by vikiival** [comment]
prob resolved ?

**Comment by vikiival** [comment]
@Jarsen136 Looks like there is a module for nuxt 

https://scripts.nuxt.com/scripts/marketing/clarity

**Comment by Jarsen136** [comment]
It seems like clarity has fixed itself. I can't reproduce the same error on the console again in the prod env.  Then we can close this issue.

**Pull request closed without merging**
