### PR TITLE
feat: rename moonsama to moonriver

### PR DESCRIPTION
**Pull request by vikiival**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### Related 
- https://github.com/kodadot/packages/pull/45

### What's new?

Updated 

```json
{
  "@kodadot1/vuex-options": "0.0.2"
}
```

Screenshot 2022-09-02 at 14 57 04

### CODE REVIEW

**Comment by yangwao** [comment]
image

**Comment by yangwao** [comment]
> POST https://app.gc.subsquid.io/beta/click/001-rc0/graphql net::ERR_FAILED

in #3884 we have 🤔
```
click: 'https://squid.subsquid.io/click/v/001/graphql',
```

**Review by Jarsen136 — APPROVED** [review]

**Comment by yangwao** [comment]
wait for https://github.com/kodadot/nft-gallery/issues/3905

**Comment by yangwao** [comment]
Something that could be tackled in 
- #3842 
image

other than that seems it's up 

image

**Comment by yangwao** [comment]
https://deploy-preview-3904--koda-nuxt.netlify.app/movr/explore?tab=GALLERY&page=1

```
{
    "errors": [
        {
            "message": "Variable \"$orderBy\" of type \"[NFTEntityOrderByInput]\" used in position expecting type \"[NFTEntityOrderByInput!]\".",
            "extensions": {
                "code": "GRAPHQL_VALIDATION_FAILED",
                "exception": {
                    "stacktrace": [
                        "GraphQLError: Variable \"$orderBy\" of type \"[NFTEntityOrderByInput]\" used in position expecting type \"[NFTEntityOrderByInput!]\".",
                        "    at Object.leave (/squid/node_modules/graphql/validation/rules/VariablesInAllowedPositionRule.js:55:35)",
                        "    at Object.leave (/squid/node_modules/graphql/language/visitor.js:344:29)",
                        "    at Object.leave (/squid/node_modules/graphql/utilities/TypeInfo.js:390:21)",
                        "    at visit (/squid/node_modules/graphql/language/visitor.js:243:26)",
                        "    at validate (/squid/node_modules/graphql/validation/validate.js:69:24)",
                        "    at validate (/squid/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)",
                        "    at processGraphQLRequest (/squid/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)",
                        "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
                        "    at async processHTTPRequest (/squid/node_modules/apollo-server-core/dist/runHttpQuery.js:220:30)"
                    ]
                }
            }
        }
    ]
}
```

**Comment by yangwao** [comment]
metadata on item detail? 

https://deploy-preview-3904--koda-nuxt.netlify.app/movr/gallery/0x0dad866dc0c13fb8e4a91d1b5e83cf3a61d4cee2-7636

```
{
    "errors": [
        {
            "message": "Unknown type \"ID\".",
            "extensions": {
                "code": "GRAPHQL_VALIDATION_FAILED",
                "exception": {
                    "stacktrace": [
                        "GraphQLError: Unknown type \"ID\".",
                        "    at Object.NamedType (/squid/node_modules/graphql/validation/rules/KnownTypeNamesRule.js:57:29)",
                        "    at Object.enter (/squid/node_modules/graphql/language/visitor.js:323:29)",
                        "    at Object.enter (/squid/node_modules/graphql/utilities/TypeInfo.js:370:25)",
                        "    at visit (/squid/node_modules/graphql/language/visitor.js:243:26)",
                        "    at validate (/squid/node_modules/graphql/validation/validate.js:69:24)",
                        "    at validate (/squid/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)",
                        "    at processGraphQLRequest (/squid/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)",
                        "    at runMicrotasks (<anonymous>)",
                        "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
                        "    at async processHTTPRequest (/squid/node_modules/apollo-server-core/dist/runHttpQuery.js:220:30)"
                    ]
                }
            }
        }
    ]
}
```

**Comment by yangwao** [comment]
Collection View 

https://deploy-preview-3904--koda-nuxt.netlify.app/movr/collection/0xb6e9e605aa159017173caa6181c522db455f6661

```
{
    "errors": [
        {
            "message": "Unknown type \"ID\".",
            "extensions": {
                "code": "GRAPHQL_VALIDATION_FAILED",
                "exception": {
                    "stacktrace": [
                        "GraphQLError: Unknown type \"ID\".",
                        "    at Object.NamedType (/squid/node_modules/graphql/validation/rules/KnownTypeNamesRule.js:57:29)",
                        "    at Object.enter (/squid/node_modules/graphql/language/visitor.js:323:29)",
                        "    at Object.enter (/squid/node_modules/graphql/utilities/TypeInfo.js:370:25)",
                        "    at visit (/squid/node_modules/graphql/language/visitor.js:243:26)",
                        "    at validate (/squid/node_modules/graphql/validation/validate.js:69:24)",
                        "    at validate (/squid/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)",
                        "    at processGraphQLRequest (/squid/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)",
                        "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
                        "    at async processHTTPRequest (/squid/node_modules/apollo-server-core/dist/runHttpQuery.js:220:30)"
                    ]
                }
            }
        }
    ]
}```

```
{
    "errors": [
        {
            "message": "Unknown type \"ID\".",
            "extensions": {
                "code": "GRAPHQL_VALIDATION_FAILED",
                "exception": {
                    "stacktrace": [
                        "GraphQLError: Unknown type \"ID\".",
                        "    at Object.NamedType (/squid/node_modules/graphql/validation/rules/KnownTypeNamesRule.js:57:29)",
                        "    at Object.enter (/squid/node_modules/graphql/language/visitor.js:323:29)",
                        "    at Object.enter (/squid/node_modules/graphql/utilities/TypeInfo.js:370:25)",
                        "    at visit (/squid/node_modules/graphql/language/visitor.js:243:26)",
                        "    at validate (/squid/node_modules/graphql/validation/validate.js:69:24)",
                        "    at validate (/squid/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)",
                        "    at processGraphQLRequest (/squid/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)",
                        "    at runMicrotasks (<anonymous>)",
                        "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
                        "    at async processHTTPRequest (/squid/node_modules/apollo-server-core/dist/runHttpQuery.js:220:30)"
                    ]
                }
            }
        }
    ]
}
```

**Comment by vikiival** [comment]
Screenshot 2022-09-03 at 16 57 53

**Comment by vikiival** [comment]
Best would be to dowgrade `click`

**Comment by yangwao** [comment]
one random 
image

otherwise, seems working? 

image

**Comment by yangwao** [comment]
@petersopko let's check what's missing and what's needs to be done and update 
- #3647 
accordingly with sub-issues

**Comment by petersopko** [comment]
1. collections don't show image previews+ errors in console
image

2. same for landing / curated lists
image

3. searching through explorer is hard / takes too long to load (sometimes it just gets stuck)
image

**Comment by petersopko** [comment]
holders/flippers:
image

**Comment by vikiival** [comment]
@petersopko 

I am unable to reproduce your bug.

Can you may provide the steps?

**Comment by vikiival** [comment]
@yangwao the issue is already there for 3 months #3338

**Comment by petersopko** [comment]
> let's check what's missing and what's needs to be done and update
 https://github.com/kodadot/nft-gallery/issues/3647
> accordingly with sub-issues

@yangwao @vikiival I'm kind of confused about this PR, are we just renaming moonsama to moonriver, or fixing everything that's wrong with MOVR?

**Comment by yangwao** [comment]
> are we just renaming moonsama to moonriver, 

yes
- #3902 

> or fixing everything that's wrong with MOVR?

also fixing rest once it's this minimum viable working version merged so others can continue
- #3647

**Comment by yangwao** [comment]
fix tests here or merge it and fix them afterwards? 

wyt @petersopko

**Comment by petersopko** [comment]
> fix tests here or merge it and fix them afterwards?
> 
> wyt @petersopko

image

the failing tests here are the usual media tests 
- #3812

I've hit re-run but regardless, I think it's save to merge

**Pull request merged**
