### PR TITLE
3162 Adjust Basilisk to Basilisk (testnet)

### LINKED ISSUE #3162: Adjust Basilisk to Basilisk (testnet) to chain selector
To avoid any confusion people in production, let's rename there Basilisk to "Basilisk (testnet)" 

image

### PR DESCRIPTION
**Pull request by zhengow**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3162
- [ ] Requires deployment <rubick/magick_issue>
- [x] change basilisk name from `@kodadot1/vuex-options`

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
hmm why is it failing?

**Comment by zhengow** [comment]
cuz i pr before u publish new npm package



发自我的iPhone


------------------ Original ------------------
From: Viki Val ***@***.***&gt;
Date: Fri,Jun 17,2022 0:25 AM
To: kodadot/nft-gallery ***@***.***&gt;
Cc: zhengow ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [kodadot/nft-gallery] issue_3162Adjust Basilisk to Basilisk (testnet) (PR #3164)





 
hmm why is it failing?

**Comment by zhengow** [comment]
> i guess you need to add normally so pnpm-lock.yaml gets updated accordingly :)

done:)

**Comment by vikiival** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 49.83 USD/KSM ~ 1.003 $KSM
🧗 [EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws](https://kusama.subscan.io/account/EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)
🔗 [0xc6030b97644d0f083978cadf6aaa441774b8827d3304c180b9ae703f58caf6db](https://kusama.subscan.io/extrinsic/0xc6030b97644d0f083978cadf6aaa441774b8827d3304c180b9ae703f58caf6db)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Review by roiLeo — COMMENTED** [review]
Looks like `@kodadot1/vuex-options` hasn't been updated
Capture d’écran 2022-06-17 à 11 43 45 AM

**Comment by zhengow** [comment]
which link？
Maybe need to clear cookie



发自我的iPhone


------------------ Original ------------------
From: roiLeo ***@***.***&gt;
Date: Fri,Jun 17,2022 5:44 PM
To: kodadot/nft-gallery ***@***.***&gt;
Cc: zhengow ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [kodadot/nft-gallery] 3162 Adjust Basilisk to Basilisk (testnet)(PR #3164)

**Comment by roiLeo** [comment]
> which link？ Maybe need to clear cookie 

On your [preview](https://deploy-preview-3164--koda-nuxt.netlify.app/) and/or [beta](https://beta.kodadot.xyz/)

**Pull request merged**
