### PR TITLE
feat: show last buy price in `Newest list card`

### LINKED ISSUE #3752: Newest list has showing recent listing price instead old one?
- I've bought NFT for 10000 BSX 
- List it for 333333 BSX 
- Noticed on landing it's shows at newest list, recent price on second card, where should show old one - 10000 BSX 

image

### Case 
https://beta.kodadot.xyz/bsx/gallery/1643292083-2

image

### PR DESCRIPTION
**Pull request by zhengow**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3752 
- [ ] Requires deployment <rubick/magick_issue>
- [x] fetch the last buy price of nfts which are in newest list card.

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

### CODE REVIEW

**Comment by yangwao** [comment]
I've put numbers below how it supposed to be , hope it helps now 🙂

**Comment by zhengow** [comment]
> I've put numbers below how it supposed to be , hope it helps now 🙂
> 
> 

Fix it:)
Find that it's the mistake by `apollo query` that it will mix up response data if there is `id` prop in `**.graphql` and two or more data have the same id.

**Review by roiLeo — APPROVED** [review]
Screenshot 2022-08-18 at 08-12-18 KodaDot - Kusama NFT Market Explorer

wfm

**Comment by yangwao** [comment]
pay 50

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 54.8 USD/KSM ~ 0.912 $KSM
🧗 [EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws](https://kusama.subscan.io/account/EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)
🔗 [0x286ba4c6a7d2a51e93ff0647e97a644b462c402b5ddbda37dda2e52e4480800c](https://kusama.subscan.io/extrinsic/0x286ba4c6a7d2a51e93ff0647e97a644b462c402b5ddbda37dda2e52e4480800c)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
