### PR TITLE
add modal to layout

### LINKED ISSUE #9670: Clicking listing closed modal on drop success modal
around 1m: 

https://github.com/kodadot/nft-gallery/assets/36627808/31da8de3-beb0-409b-9451-0dcac00dd192

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #9670

### Where it came from?

* #9650

removed `<ListingCartModal />` from `Generative` and `PaidGenerative`
but did not replace it with   `<ListingCartModal />` in  `unlockable-mint-layout`

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)

## Screenshot 📸

- [ ] My fix has changed UI

### CODE REVIEW

**Comment by prury** [comment]
thank you @daiagi

**Comment by prury** [comment]
modal now appears again, but never loads: 

https://github.com/kodadot/nft-gallery/assets/36627808/93ae089c-fc88-4117-b7a5-beb9a885005d

**Comment by hassnian** [comment]
> removed <ListingCartModal /> from Generative and PaidGenerative
> but did not replace it with <ListingCartModal /> in unlockable-mint-layout

mb, added it to a wrong layout `generative-mint-layout` , can you remove that also, tyvm 🙏

**Comment by yangwao** [comment]
waiting for this as can be done post-release as it break one of two buttons we have on successful modals

**Comment by daiagi** [comment]
>modal now appears again, but never loads:

introduced by 
* #9631

@hassnian 

can you imagine how difficult it is to find that passing `{passimistic: true}` to a child component of `ListingCart` makes the listing cart not load?

it took hours...

why?

1. you made the parent (`ListingCartModal`) loading state be dependent on child component(`AutoTeleportActionButton`). this is not something i've seen before. is there a good reason for it?

usually loading state flows from parent to child and not the other way around

2. in order to debug it, one needs to go into the `ActionButton` -> `useAutoTeleport` -> `useAutoTeleportTransition` -> `useAutoTeleportTransitionDetails`
only there finally the `pessimistic` argument is actually being used
then understand what it does
and now drill back through 3 composables and a component to see how it affects `ListingCartModal`

**this prop drilling stuff is a nightmare to debug.**

**composbales should ideally have no arguments**
**use store to hold state**

in this case probably `isReady` belongs in store, where could be accessed easily wherever it's needed

**Comment by hassnian** [comment]
> > modal now appears again, but never loads:
> 
> introduced by
> 
> * [fix: List modal loading when clicking button or typing #9631](https://github.com/kodadot/nft-gallery/pull/9631)
> 
> @hassnian
> 
> can you imagine how difficult it is to find that passing `{passimistic: true}` to a child component of `ListingCart` makes the listing cart not load?
> 
> it took hours...
> 

 I can’t apologize enough. 🙏

> why?
> 
> 1. you made the parent (`ListingCartModal`) loading state be dependent on child component(`AutoTeleportActionButton`). this is not something i've seen before. is there a good reason for it?
> 

My train of thought was. Since the entire autotelport logic runs inside `AutoTeleportActionButton` and we could have multiple buttons at once, and `isReady` is used for other composables inside, that's where 'isReady' ended up being. 

> usually loading state flows from parent to child and not the other way around
> 
> 2. in order to debug it, one needs to go into the `ActionButton` -> `useAutoTeleport` -> `useAutoTeleportTransition` -> `useAutoTeleportTransitionDetails`
>    only there finally the `pessimistic` argument is actually being used
>    then understand what it does
>    and now drill back through 3 composables and a component to see how it affects `ListingCartModal`
> 
> **this prop drilling stuff is a nightmare to debug.**
> 
> **composbales should ideally have no arguments** **use store to hold state**
> 
> in this case probably `isReady` belongs in store, where could be accessed easily wherever it's needed

duly noted 

not sure what to say, autotelport had so much code that I had to split it up into smaller composables, thus creating the prop drilling issue,  it seems like the autotelport should've had a store to manage it 

@daiagi pls review #9686

**Comment by yangwao** [comment]
@prury you can test now

**Comment by prury** [comment]
> @prury you can test now

first test was ok, can keep checking later as i have appointment now

https://github.com/kodadot/nft-gallery/assets/36627808/f3fd9763-0d0f-4ac6-a18a-d10ac4f55d30

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 10.41 USD/DOT ~ 2.882 $DOT
🧗 [1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8](https://polkadot.subscan.io/account/1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)
🔗 [0x3321ee07dafcbb025b21ce9b0d5bc4c15bd28f468489349d5275443be88b0784](https://polkadot.subscan.io/extrinsic/0x3321ee07dafcbb025b21ce9b0d5bc4c15bd28f468489349d5275443be88b0784)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by daiagi** [comment]
>autotelport had so much code that I had to split it up into smaller composables

i understand and kudos to you for a good job. it is a major piece of code and it works well


>Since the entire autotelport logic runs inside AutoTeleportActionButton
 
not the best design to have such a complicated code + state all hinging on one button
a button should just be a button

> thus creating the prop drilling issue


both of these points are technical debs we will need to refactor and fix at some point
especially since the autoteleport touches so many points in the app and have become quite omnipresent

**Pull request merged**
