### PR TITLE
feat: activity tabs

### LINKED ISSUE #4234: redesign: Item Activity section
requirements: https://github.com/kodadot/nft-gallery/issues/4111#activity-section

## <a href="#activity-section" id="activity-section">Item Activity</a>
image
An important one, it's coming. 
Instead of dropdown, we plan to have selecting boxes, where multi-checkbox is possible. So for example you could see Listings and Sales at once. 
Default could be Sales.
**Event** column would be name of events
**Price** column would be denominated in that asset
**From** column address 
**Date** will be relative date with possibility hover to get exact date

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [x] Redesign

## Context

- [x] Closes #4234
- [x] branching from https://github.com/kodadot/nft-gallery/pull/4360, so that PR need to merge first

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by yangwao** [comment]
Merged :)
- https://github.com/kodadot/nft-gallery/pull/4360

**Comment by yangwao** [comment]
Seems like the tabs component is getting destroyed and re-rendered sometimes on clicks.  
I'm looking at that weird whiteout between clicks; it doesn't always happen and is just pretty random

https://user-images.githubusercontent.com/5887929/206205882-d3186e25-869c-40a4-94f2-b19cb8468187.mov

**Review by roiLeo — COMMENTED** [review]
- oruga component outside `libs/ui`? Why? we now have mixed library

btw you can define oruga css variable 
[tooltip example](https://oruga.io/components/Tooltip.html#style)

- Do we really need to use `date-fns` instead of native js?
- events query without limit, is this not a problem?

**Comment by roiLeo** [comment]
> for this, I will wrap them alongside the table component in this issue #4368, wdyt @roiLeo ?

Yes! I may need your help on #4430 
When I move `@oruga-ui` imports ([NeoButton](https://github.com/kodadot/nft-gallery/blob/80df618e184dfbd42ed80a413c7588d7ad1bbb9d/libs/ui/src/components/NeoButton/NeoButton.vue#L23)) in `histoire.scss` the preview is good but I don't have the same rendering in kodadot app.
It would be a shame to have to import in all our new components the oruga-ui variables, lmk if you have any idea why it works this way.

**Comment by yangwao** [comment]
> eh, I think we need pagination in this section. so, temporary I will limit the results to `100`

feel free to address @exezbcz in case, and I'll go through it with him; we are trying to have weekly calls to resolve some design issues in best efforts 
- #4403 

Plus, I think categories/tags should be as a multi-check box? Like for example, I would like to see Sales and Transfers at once.
image

**Comment by exezbcz** [comment]
> > Plus, I think categories/tags should be as a multi-check box? Like for example, I would like to see Sales and Transfers at once.
> 
> yes, that should work on the multi-check box. maybe the active state to thin? i'm using text-shadow to avoid glitch instead of font-weight bold image

Active state to thin is not a great system. Is there really that big of a problem with the bold active state?

**Comment by yangwao** [comment]
Does 
- #4456 helps fix this?

**Comment by yangwao** [comment]
Current issues are 
- user doesn't know which tab is currently selected -- bold text issues, we may change to different font?
- currently there are missing wrapping text, we can use `...` ? For addresses I would like to use some filter function with 3 beginning letters and 3 ending letters for now? Like `2Xk...9oP`
- hover card should pop up under cursor. Now position is showing over whole table
- events name should not be in capslock, only capital letter on event
- on the time column we probably can strip "about" if there is "about 1 month ago"  
- link between tabs and column names should be k-white? 
image
- responsive issues but can be solved separately, we will came up with design

**Comment by yangwao** [comment]
let it fly!

**Pull request merged**
