### PR TITLE
Chore/h1

### LINKED ISSUE #7002: H1 tag missing or empty
Some of them are h2 for some reason; let's adjust to h1, please. 

image

image
image

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] SEO

## Context

- [x] Closes #7002

#### Did your issue had any of the "$" label on it?

Yes $

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)

## Summary

| URL        | Existing Tag| Changed?  |
|------------|-----------|-----------|
| /series-insight| h1       |     No   |
| /cookie-notice| h2     | Yes        |
| /prefix/explore/items| h1     | No       |
| /prefix/explore/collectibles| h1     | No       |
| /prefix/claim| p     | Yes       |
| /hot| h1     | No       |
| /prefix/incomingOffers| h1     | No       |
| /error| p     | Yes       |
| /prefix/assets| h1     | No       |
| /| h1     | No       |
| /prefix/stats| h1     | No       |
| /rmrk/mint| h1     | No       |
| /prefix/waifu| h1     | Yes       |
| /qrCode| None     | Not applicable       |
| /e2e-login| None     | Not applicable       |
| /prefix/offers| None     | Not applicable       |
| /prefix/massmint| None     | Not applicable       |
| /settings| None     | Not applicable       |
| /carbonless| h1     | No       |
| /sustainability| h1     | No       |
| /spotlight| h1     | No       |
| /sales| h1     | No       |
| /identity| p     | Yes       |
| /prefix/drops| div     | Yes       |
| /prefix/teleport| p     | Yes       |

/prefix/create -  collection tab
skipped on account of
* #6974

@yangwao the image you posted in the issue is largly inaccurate, many of the pages did have a proper h1 already

### <samp>🤖 Generated by Copilot at 04ef6a6</samp>

This pull request enhances the accessibility and readability of various components and pages by using proper heading tags for titles and tooltips. It also refactors some code to use a utility function for formatting addresses. The files affected are `IdentityForm.vue`, `Teleport.vue`, `Drops.vue`, `ClaimForm.vue`, `Error.vue`, and `cookie-notice.vue`.

### <samp>🤖 Generated by Copilot at 04ef6a6</samp>

> _`<p>` tags replaced_
> _with `<h1>` for accessibility_
> _a winter project_

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]

**Comment by vikiival** [comment]
Is this for semantic purposes or unificstin?

**Comment by yangwao** [comment]
> image you posted in the issue is largly inaccurate, many of the pages did have a proper h1 already

Yes, it's ahref tooling sometimes has misreadings. Even it classifies we have broken image pictures going to `.webp` however when I click on them they works!

We are aim to get back our health score of main domain back on legs! :)
thank you!



> Is this for semantic purposes

^ @vikiival

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 4.58 USD/DOT ~ 10.917 $DOT
🧗 [1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8](https://polkadot.subscan.io/account/1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)
🔗 [0x635b805df5c617ee91d013370c275382c704905b3925a9232529bbb486067ca6](https://polkadot.subscan.io/extrinsic/0x635b805df5c617ee91d013370c275382c704905b3925a9232529bbb486067ca6)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
