### PR TITLE
fix: Clicking followed by should open followers tab

### LINKED ISSUE #10245: Clicking followed by should open followers tab
image

Clicking this (mainly the bubbles) should lead to this: 
image

could be combined: 
- https://github.com/kodadot/nft-gallery/issues/10242

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs Design check

- @exezbcz please review

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #10245

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

test URL path: `/ahp/u/1CBmjqJvV1ha8BPQ5JAXGEzeJBLmGHNG9gYg96eC1dnjH5W`

### CODE REVIEW

**Comment by daiagi** [comment]
@exezbcz 

does this means that the user avatar inside the followers tab should link to their profile?

**Review by daiagi — APPROVED** [review]

**Comment by exezbcz** [comment]
> does this means that the users' avatars inside the followers tab should link to their profile?

can be, but the bold name is enough 

as in: 
- https://github.com/kodadot/nft-gallery/pull/10196

**Comment by exezbcz** [comment]
should be the same overlap styling as on canary
image

**Comment by Jarsen136** [comment]
> should be the same overlap styling as on canary image

✅ Fixed

**Comment by daiagi** [comment]
>but the bold name is enough


Enough for what? 
as it is, it is really hard to navigate between profiles

Should be easy to go from 1 profile to the following / followers

**Comment by Jarsen136** [comment]
> > but the bold name is enough
> 
> Enough for what? as it is, it is really hard to navigate between profiles
> 
> Should be easy to go from 1 profile to the following / followers

As I have implemented on https://github.com/kodadot/nft-gallery/pull/10196, the profile avatar is clickable and could be navigated to its profile page.

**Comment by prury** [comment]
what should happen if i click on it with a disconnected account? 

[Gravação de tela de 07-05-2024 09:39:59.webm](https://github.com/kodadot/nft-gallery/assets/36627808/eb627f1f-454e-4078-9a89-e532a6d7bd92)

**Comment by vikiival** [comment]
pay 5 usd

**Comment by vikiival** [comment]
pay 5 usd

**Comment by vikiival** [comment]
😍 Perfect, I’ve sent the payout
💵 $5 @ 6.73 USD/DOT ~ 0.743 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x839d3fdd897012f14f05ddfb759e4e1a0a75b0ddaccca4d1d29d3fc1abe9fb40](https://polkadot.subscan.io/extrinsic/0x839d3fdd897012f14f05ddfb759e4e1a0a75b0ddaccca4d1d29d3fc1abe9fb40)
🪅 Let’s grab another issue and get rewarded!
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by hassnian** [comment]
@Jarsen136 tabs are not loading 


https://github.com/kodadot/nft-gallery/assets/44554284/47d77a7e-97f8-4332-a803-ecaeb12ce8e4

**Comment by Jarsen136** [comment]
> @Jarsen136 tabs are not loading
> 
>  CleanShot.2024-05-14.at.09.44.04.mp4

It's related to unconnected status and fixed on https://github.com/kodadot/nft-gallery/pull/10260

**Review by hassnian — APPROVED** [review]

**Review by vikiival — APPROVED** [review]

**Pull request merged**
