### PR TITLE
fix: Wrap markdown in description

### LINKED ISSUE #4731: Wrap markdown in description
I guess now it's bit breaking UX in gallery item detail 

https://beta.kodadot.xyz/bsx/gallery/1000011-16

https://user-images.githubusercontent.com/5887929/212880882-2cbe833c-ab30-4351-87f7-d5eca48e8e22.mov

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4731
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by Jarsen136** [comment]
Feel free to drop some design suggestions for the markdown section. @exezbcz 

I found that the scrolling part in the original issue is code type, which means we could not make the text wrap to the next line

image

ref: http://miaolz123.github.io/vue-markdown/

**Review by roiLeo — COMMENTED** [review]
Have you tried `white-space: pre-wrap;`?

**Comment by Jarsen136** [comment]
> Have you tried `white-space: pre-wrap;`?

That's really cool. It works now.
image

**Review by roiLeo — APPROVED** [review]
✅ wfm

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 34.88 USD/KSM ~ 1.433 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x18ca7061a23d2eb453cd5b4acc2ceeecf21fc71535c71a606dbf9055c190ecd7](https://kusama.subscan.io/extrinsic/0x18ca7061a23d2eb453cd5b4acc2ceeecf21fc71535c71a606dbf9055c190ecd7)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
pay 50

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 35.11 USD/KSM ~ 1.424 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xfbd0ed7632ba7fda2abbe6b48e596990af1ea8ffe93fe5c04639ca5d86356983](https://kusama.subscan.io/extrinsic/0xfbd0ed7632ba7fda2abbe6b48e596990af1ea8ffe93fe5c04639ca5d86356983)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
