### PR TITLE
Batch transfers

### LINKED ISSUE #4435: Extend Transfers with Add Address to batch transaction
Right now, we are using the transfer functionality in KodaDot 
https://beta.kodadot.xyz/transfer

What I would like to see to use our stuff would be to **add more addresses in one batch transaction.**

The sufficient way would be to  **add plus button** next to the current address row - https://buefy.org/documentation/button/
To process more than one transfer in the same transaction, here is how to, but not sure if we need to extend our sub-api? but hopefully, it would works out of the box 
- https://polkadot.js.org/docs/api/cookbook/tx/#how-can-i-batch-transactions

For simplicity, we could make it it would send the same amount for each address (good for surveys or some mass drop we will be doing in the future to have a more straightforward process for some stuff internally)

- Adjust the format for the **query strings**; it could be like 
```url
https://beta.kodadot.xyz/transfer?target=DGDsRWwni3ks3HNqUp1DLVsVyVgib1r6jz5AoanxswgNCGH&target1=g29NScLSew5zqwmJAPupvJWDCDkpxKUhDnMeVdD2BBcnHar&target2=J29ScJV5xTrMisy32HAcTCdhac4KRATkbsJnNZnE3ZFRTeC&usdamount=50
```
- amount of addresses should be not limited

If you have questions, shoot them  

### Ref
- image
- https://en.wikipedia.org/wiki/Query_string

### PR DESCRIPTION
**Pull request by daiagi**
:sparkles: add ability to do batch transfers
:bug: :wrench:  BalancedInput did not respond to value prop changed **(fixed)**

reproduce:

 go to https://kodadot.xyz/transfer/?target=5CJwP2M3cHEQHLNZUgaY4yVDpdJvoaS272y1tjuK1ctKkocH&usdamount=30
USD amount is 30 but KSM amount stays 0 (should be ~1KSM)

**Leftovers**

1. :bug: IdentityIndex component doesn't respond when address changes

reproduce:

  * go to https://kodadot.xyz/transfer/?target=5CJwP2M3cHEQHLNZUgaY4yVDpdJvoaS272y1tjuK1ctKkocH&usdamount=30
  * in address field, copy paste a new, valid address
  * address in "Your donation will be sent to" doesn't change
  
image

2. :bug: when changing wallet, the Identity Icon changes, but the address doesn't
affect the wallet dropdown as well
**caused by the bug above**

notice in the below 2 pictures that the balance changes and the identity icon changes but the address string doesn't

image
image

3. add button to remove empty address fields?
4. prevent duplicate addresses

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #4435 
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image
image

### CODE REVIEW

**Comment by yangwao** [comment]
i've entered two addresses, but it seems to have sent only to one.

been testing with 
`G29NScLSew5zqwmJAPupvJWDCDkpxKUhDnMeVdD2BBcnHar`
`Fksmad33PFxhrQXNYPPJozgWrv82zuFLvXK7Rh8m1xQhe98`

https://kusama.subscan.io/extrinsic/15668819-5

**Comment by yangwao** [comment]
hmm maybe some glitch, on second try it has worked

https://kusama.subscan.io/extrinsic/0x9e5403f6f3c89ec74e6fa7994ad7a4c42b9aab754565350c31520f7fb70c6741

**Comment by yangwao** [comment]
oh nice seems link works now too 

https://deploy-preview-4449--koda-nuxt.netlify.app/transfer/?target=G29NScLSew5zqwmJAPupvJWDCDkpxKUhDnMeVdD2BBcnHar&target1=Fksmad33PFxhrQXNYPPJozgWrv82zuFLvXK7Rh8m1xQhe98&usdamount=10

**Comment by yangwao** [comment]
I really value your quick efforts and fixed bugs on the way there! :)

pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 29.37 USD/KSM ~ 3.405 $KSM
🧗 [5CJwP2M3cHEQHLNZUgaY4yVDpdJvoaS272y1tjuK1ctKkocH](https://kusama.subscan.io/account/5CJwP2M3cHEQHLNZUgaY4yVDpdJvoaS272y1tjuK1ctKkocH)
🔗 [0x2a5ae5bb319f5fb58f3822ef1f2d7462b8eb9f605929d40f0c4591dbe4f60264](https://kusama.subscan.io/extrinsic/0x2a5ae5bb319f5fb58f3822ef1f2d7462b8eb9f605929d40f0c4591dbe4f60264)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by daiagi** [comment]
> hmm maybe some glitch, on second try it has worked
> 
> https://kusama.subscan.io/extrinsic/0x9e5403f6f3c89ec74e6fa7994ad7a4c42b9aab754565350c31520f7fb70c6741

@yangwao  yes it takes a few seconds to fully show on subscan.
I've tested multiple times. it works
FYI if only 1 address is inputted previous behavior is conserved (i.e regular transfer, not batch)

**Pull request merged**
