### PR TITLE
#5852 Buefy checkbox to neo checkbox

### LINKED ISSUE #5852: Goodbye Buefy
## Rewrite [Buefy](https://buefy.org/documentation) components in `libs/ui` using [Oruga-ui](https://oruga.io/documentation/)
part of 
- #2690 

#### In Progress
- [x] replace buefy snackbar & toast #6744 

#### Done
- [x] `<b-progress />` => component or check Bulma #5895
- [x] `<b-carousel />` => `<NeoCarousel />` (Oruga [Carousel](https://oruga.io/components/Carousel.html))  #5884
- [x] `<b-carousel-item />` => `<NeoCarouselItem />` #5884
- [x] `<b-icon />` => `<NeoIcon />` #5858
- [x] `<b-modal />` => `<NeoModal />` #5883 
- [x] `<b-datepicker />` => `<NeoDatepicker />` (Oruga [Datepicker](https://oruga.io/components/Datepicker.html)) #5946
- [x] `<b-checkbox />` => `<NeoCheckbox />` #6000 
- [x] `<b-steps />` => `<NeoSteps />` (Oruga [Steps](https://oruga.io/components/Steps.html)) #5917
- [x] `<b-step-item />` => `<NeoStepItem />` #5917
- [x] `<b-switch />` => `<NeoSwitch />` (Oruga [Switch](https://oruga.io/components/Switch.html)) #5945
- [x] `<b-radio-button />` => `<NeoRadioButton />` (Oruga [Radio](https://oruga.io/components/radio.html)) #5976 
- [x] `<b-autocomplete />` => `<NeoAutocomplete />` (Oruga [Autocomplete](https://oruga.io/components/autocomplete.html)) #6018 
- [x] `<b-loading />` => `<NeoLoading />` (Oruga [Loading](https://oruga.io/components/Loading.html)) #5933
- [x] `<b-tooltip />` => #5856 
- [x] `<b-message />` => notification or Bulma [message](https://bulma.io/documentation/components/message/) - 3 results #6068
- [x] `<b-image />` => `` #5854
- [x] `<b-field />` => `<NeoField />` #5870 
- [x] `<b-input />` => `<NeoInput />` #5870
- [x] `<b-tag />` => `<NeoTag />` check Bulma [Tag](https://bulma.io/documentation/elements/tag/) - 3 results #6155 
- [x] `<b-table />` => `<NeoTable />` (Oruga [Table](https://oruga.io/components/Table.html)) - 8 results (related with #6110, #6144)
- [x] `<b-table-columns />` => `<NeoTableColumn />` - 87 results (related with #6110, #6144)
- [x] `<b-numberinput />` => `<NeoInput />` type=number??  - 3 results #6195 
- [x] `<b-taginput />` => `<NeoInputitems />` - 1 result #6183 
- [x] `<b-collapse />` => `<NeoCollapse />` (Oruga [Collapse](https://oruga.io/components/Collapse.html)) -  <s>13</s> 10 results #6249
- [x] `<b-dropdown />` => `<NeoDropdown />` - 3 results #6196
- [x] `<b-dropdown-item />` => `<NeoDropdownItem />` - 26 results #6196
- [x] `<b-slider />` => `<NeoSlider />` Oruga [slider](https://oruga.io/components/slider.html) - #6340
- [x] `<b-upload />` => `<NeoUpload />` Oruga [upload](https://oruga.io/components/upload.html) - #6341
- [x] `<b-pagination />` => `<NeoPagination />` Oruga [Pagination](https://oruga.io/components/pagination.html) #6366 
- [x] `<b-tabs />` => `<NeoTabs />` (Oruga [Tabs](https://oruga.io/components/Tabs.html))  - 9 results #6231 
- [x] `<b-tab-item />` => `<NeoTabItem />` -  15 results #6231 
- [x] `<b-navbar />` => [Bulma Navbar](https://bulma.io/documentation/components/navbar/) #6382 
- [x] `<b-navbar-item />` => custom html ??? #6382 
- [x] `<b-select />` => `<NeoSelect />` - 15 results #6200, #6338
- [x] `<b-button />` => `<NeoButton />` - <s>64</s> <s>47</s> <s>41</s> 35 results (make it the last one) #6437 #6449 
- [x] #6277 

lmk if you want to work on a specific component.

### PR DESCRIPTION
**Pull request by emagici**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] related with #5852 
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at 8a05013</samp>

Updated checkbox components to use `NeoCheckbox` from `@kodadot1/brick` for better UI design and consistency. Affected files are `Holder.vue` and `BasicCheckbox.vue`.

### <samp>🤖 Generated by Copilot at 8a05013</samp>

> _To make the UI more refined_
> _We replaced Buefy checkboxes in kind_
> _With `NeoCheckbox` from `brick`_
> _Which is custom and slick_
> _And now our components are well-aligned_

### CODE REVIEW

**Review by Jarsen136 — CHANGES_REQUESTED** [review]
It does not work in fact.

https://deploy-preview-5868--koda-canary.netlify.app/settings?tab=advanced
image


https://beta.kodadot.xyz/settings?tab=advanced
image

**Comment by vikiival** [comment]
cc @emagici

**Comment by emagici** [comment]
@vikiival working in progress

**Comment by vikiival** [comment]
Hello, its been more than a week since this PR has been raised. 

I am happy to see the working version of this feature 😇. 

For now I am closing this one.

**Pull request closed without merging**
