### PR TITLE
fix: searchbar dropdown styling

### LINKED ISSUE #6344: Searchbar: Lines under active tab are not showing
Lines under tabs are not showing: 
image
image

i think it should at least resemble this one: 
image

or have the same color of the other lines

_Originally posted by @prury in https://github.com/kodadot/nft-gallery/issues/6264#issuecomment-1610273721_

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Needs Design check

- @exezbcz please review

## Context

- [x] Closes #6344
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed UI

before:

image

after:

image

### <samp>🤖 Generated by Copilot at c9d4b9b</samp>

This pull request enhances the appearance and functionality of the search feature and the tabs component in the NFT gallery. It applies better `scss` rules to `styles/components/_search.scss` and fixes some layout and color bugs.

### <samp>🤖 Generated by Copilot at c9d4b9b</samp>

> _The search input was looking quite drab_
> _And the autocomplete menu was bad_
> _So they tweaked the layout_
> _And the style throughout_
> _And now the tabs component is rad_

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
Hey! I've finally found the [figma](https://www.figma.com/file/3iOjW12ERFRDSVnpLuhQmf/landing-page-handoff?node-id=1305%3A5613&mode=dev) file with design and it doesn't seem to have a pink border. Could you take a look?

**Comment by prury** [comment]
Also, while the problem seems to be solved for the search bar at the top when clicking on explore, the search bar from the initial kodadot page still has the problem:

image

explore/items(fixed): 

image

**Comment by Jarsen136** [comment]
> Hey! I've finally found the [figma](https://www.figma.com/file/3iOjW12ERFRDSVnpLuhQmf/landing-page-handoff?node-id=1305%3A5613&mode=dev) file with design and it doesn't seem to have a pink border. Could you take a look?

Thanks for pointing out. I have removed the pink border.

> Also, while the problem seems to be solved for the search bar at the top when clicking on explore, the search bar from the initial kodadot page still has the problem:

I guess it's a style issue related to the Windows OS. I just did some magic to try to fix it. Could pls check if it works or not? @prury 

image

**Comment by prury** [comment]
> I guess it's a style issue related to the Windows OS. I just did some magic to try to fix it. Could pls check if it works or not? 

your magic worked really well, ty!

**Review by roiLeo — APPROVED** [review]
lgtm

**Review by vikiival — APPROVED** [review]
Some CSS magic

**Pull request merged**
