### PR TITLE
feat(Profile activity): Responsive visual changes

### LINKED ISSUE #7094: Profile activity visual things
In case of the desktop, would it be possible to put it at the same row as the filters please?
image
- On mobile, its okay to leave them like this, 24px top bottom margin would be better tho
image

- Please make the filters jump to the second row if they don't fit 
image

other than that its okay!

_Originally posted by @exezbcz in https://github.com/kodadot/nft-gallery/issues/7021#issuecomment-1702428817_

cc @hassnian

### PR DESCRIPTION
**Pull request by hassnian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #7094

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

https://github.com/kodadot/nft-gallery/assets/44554284/c00bc7ca-4dca-4cb1-8f1e-4b09f0881afe

### <samp>🤖 Generated by Copilot at b2cb6b6</samp>

Improved the user interface and functionality of the `History` component in the profile page by adding filter and pagination features. Refactored some components to use a common `useResponsive` composable for better responsiveness and performance.

### <samp>🤖 Generated by Copilot at b2cb6b6</samp>

> _To make the profile page more attractive_
> _The `History` component got adaptive_
> _Using `useResponsive` and `Pagination`_
> _They improved the layout and prop relation_
> _And made the code more concise and effective_

### CODE REVIEW

**Comment by hassnian** [comment]
@exezbcz visual check pls

**Comment by exezbcz** [comment]
nice! one thing to the pagination component 

- Could you please limit how much of the pages are actually showing 
image
- in this case I would only show 1...8, 9, 10(active), 11, 12... and last page 
- also with the arrows there 
- this way, it would also with better on mobile 
image


otherwise really nice job! thanks

**Comment by hassnian** [comment]
@exezbcz done

desktop
CleanShot 2023-09-04 at 09 47 53@2x

mobile
CleanShot 2023-09-04 at 09 48 46@2x

**Review by preschian — COMMENTED** [review]
@hassnian inconsistent arrow width on mobile between first/last page and middle page

**Comment by hassnian** [comment]
@preschian could you share screenshot not sure what you mean

**Comment by preschian** [comment]
first page

image


in the middle
image

is that expected?

**Comment by hassnian** [comment]
> first page
> 
> image
> 
> in the middle image
> 
> is that expected?

I would think so,  I didn't really change anything regarding the main logic of the pagination component other than updating these props

CleanShot 2023-09-04 at 14 31 28@2x

cc: @exezbcz

**Comment by exezbcz** [comment]
@preschian you mean the styling ?

**Comment by exezbcz** [comment]
> > first page
> > image
> > in the middle image
> > is that expected?
> 
> I would think so, I didn't really change anything regarding the main logic of the pagination component other than updating these props
> 
> CleanShot 2023-09-04 at 14 31 28@2x
> cc: @exezbcz

I think i don't understand the issue here, could you please explain?

**Comment by hassnian** [comment]
@preschian was asking if this is normal


CleanShot 2023-09-11 at 14 31 00@2x
like why are the width of the arrows changing
CleanShot 2023-09-11 at 14 33 20@2x 

and as I mentioned I did not change anything regarding that , that's how it worked before

**Comment by exezbcz** [comment]
> @preschian was asking if this is normal
> 
> 
> 
> 
> 
> CleanShot 2023-09-11 at 14 31 00@2x
> 
> like why are the width of the arrows changing
> 
> CleanShot 2023-09-11 at 14 33 20@2x 
> 
> 
> 
> and as I mentioned I did not change anything regarding that , that's how it worked before 

Ah ic, its oki for me

**Review by preschian — APPROVED** [review]

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 4.03 USD/DOT ~ 12.407 $DOT
🧗 [13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh](https://polkadot.subscan.io/account/13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)
🔗 [0x7dd3606789ba68a9490f89c53cd8fe88e99a74f5b57a5ef942d4fbadda380168](https://polkadot.subscan.io/extrinsic/0x7dd3606789ba68a9490f89c53cd8fe88e99a74f5b57a5ef942d4fbadda380168)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
