### PR TITLE
refactor: unify user identity fetching

### LINKED ISSUE #3783: Tracking: Identity
### Is your feature request related to a problem?

Current implementation of the indentity is so far really bad and therefore I would like to propose a new way of doing/handling identity:

Technical background:
- [ ] Implement multichain @subsquid identity indexer (for Kusama, Basilisk, Moonriver, Acala, Astar).
- [ ] fetch data from indexer instead of connecting to chain - That's why you see hundreds of connection logs on the landing page
- [ ] Cache the data for at least 3 days - indentity does not change much. 

Vue: 
- [ ] rewrite into a smaller pieces (may fixed by #3749)
- [ ] turn off that hover on the phone :)

### Describe the solution you would like

~

Just a 🧠 dump, will process after 🇪🇸 

### Describe alternatives you have considered

~

### Screeenshots

_No response_

### Are there opened related issues?

_No response_

### LINKED ISSUE #7069: onchain identity fetch gone in sidebar?
It seems I don't see on-chain identity in the sidebar
image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix
  - [x] Refactoring

  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #7069 (identity support for ahp and ahk)
  - [x] Closes #3783  fetch identity data from indexer instead of connecting to chain 
  - [x] Refactor: unify the process of fetching and updating user identity

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [ ] My fix has changed UI

  ## Copilot Summary
  
### <samp>🤖 Generated by Copilot at 9f12854</samp>

This pull request refactors the identity-related components and logic to use the Subsquid GraphQL endpoint for fetching the identity data, instead of querying the chain directly. This improves the performance and reliability of the identity features. It also removes unused code and dependencies, and adds support for Polkadot and Kusama data. The main changes are in the `useIdentity` hook, the `useGraphql` composable, and the `identityById.graphql` query.

  
### <samp>🤖 Generated by Copilot at 9f12854</samp>

> _We are the masters of identity_
> _We use the power of GraphQL_
> _We query the Subsquid endpoints_
> _We optimize our code and performance_

### CODE REVIEW

**Comment by prury** [comment]
@Jarsen136 strangely, by checking this PR, nothing related to identity is loading here for me

**Comment by yangwao** [comment]
seems same for me

image

**Comment by Jarsen136** [comment]
It works for me on dot and ahp networks. I will check what happened on rmrk2
image

image

**Comment by Jarsen136** [comment]
> https://github.com/kodadot/nft-gallery/issues/7069#issuecomment-1701161163
> Hello Viki Val here 👋
> 
> Luckily we can ditch on-chain identity from chain for GraphQL
> 
> Call
> 
> ```graphql
> query identityById($id: String!) {
>   identity: identityById(id: $id) {
>     id
>     handle: display
>     email
>     riot
>     twitter
>     image
>     web
>     additional {
>       name
>       value
>     }
>   }
> }
> ```
> 
> For `dot` and `ahp` chain we will use
> 
> ```
> pid: https://squid.subsquid.io/gs-main-polkadot/graphql
> ```
> 
> for `rmrk`, `ksm`, `bsx`, `snek` we will use
> 
> ```
> kid: https://squid.subsquid.io/gs-main-kusama/graphql
> ```
> 
> ## Mind that `$id` is in format of public key
> Screenshot 2023-08-31 at 16 21 40
> Therefore there is need to convert it
> 
> ```ts
> import { decodeAddress } from '@polkadot/util-crypto'
> import { u8aToHex } from '@polkadot/util'
> 
> export function accountToPublicKey(account: string): `0x{string}` {
>   const decoded = decodeAddress(account)
>   return u8aToHex(decoded)
> }
> ```

I found that the public key only works for the dot/ahp indexer. (https://squid.subsquid.io/gs-main-polkadot/graphql)
As for  `rmrk`, `ksm`, `bsx`, `snek`, the id should be in format of kusama(prefix: 2)

I have made the change in the previous commit and it works.

However, I also found an issue in that we could not fetch the identity for bsx \ snek. Look like the indexer only return the identity for kusama (kid: https://squid.subsquid.io/gs-main-kusama/graphql) Do you have any idea? @vikiival

**Comment by vikiival** [comment]
> However, I also found an issue in that we could not fetch the identity for bsx \ snek. Look like the indexer only return the identity for kusama 


As how i wrote previously.
for rmrk, ksm, bsx, snek we will use gsKusama. The identities for bsx are not present in any gs and also polkadot-js shows identities from relaychain

**Comment by Jarsen136** [comment]
> > However, I also found an issue in that we could not fetch the identity for bsx \ snek. Look like the indexer only return the identity for kusama
> 
> As how i wrote previously. for rmrk, ksm, bsx, snek we will use gsKusama. The identities for bsx are not present in any gs and also polkadot-js shows identities from relaychain

OK. Then I guess there is something redesign stuff to do for the identity page. https://kodadot.xyz/identity/ For now, user could create identity on bsx. We may need to drop the page.

**Comment by Jarsen136** [comment]
@prury Everything should work now. Please check again.

**Comment by prury** [comment]
> @prury Everything should work now. Please check again.

ok, now it shows my id properly 

about the identity form, its not updating the fields properly when i change chains. (note that i only have the twitter handle on BSX, but shows that i have it in any chain)

https://github.com/kodadot/nft-gallery/assets/36627808/00f1f846-384e-43c9-ae77-40c4d482f114

balance updates accordingly

it also says i have identity on Kusama Assethub, which i have not, unless you are taking it from Kusama

**Comment by Jarsen136** [comment]
> 
> ok, now it shows my id properly
> 
> about the identity form, its not updating the fields properly when i change chains. (note that i only have the twitter handle on BSX, but shows that i have it in any chain)
> 
Indeed. It's a bug that happened on switching networks. I have fixed it.

**Comment by Jarsen136** [comment]
> > > However, I also found an issue in that we could not fetch the identity for bsx \ snek. Look like the indexer only return the identity for kusama
> > 
> > 
> > As how i wrote previously. for rmrk, ksm, bsx, snek we will use gsKusama. The identities for bsx are not present in any gs and also polkadot-js shows identities from relaychain
> 
> OK. Then I guess there is something redesign stuff to do for the identity page. https://kodadot.xyz/identity/ For now, user could create identity on bsx. We may need to drop the page.

@prury 
As we have discussed before, there will be no identity on bsx/snek anymore.
There will be only two kinds of identity.
 kusama:  rmrk, ksm, bsx, snek
 polkadot: dot, ahp

**Comment by prury** [comment]
> > > > However, I also found an issue in that we could not fetch the identity for bsx \ snek. Look like the indexer only return the identity for kusama
> > > 
> > > 
> > > As how i wrote previously. for rmrk, ksm, bsx, snek we will use gsKusama. The identities for bsx are not present in any gs and also polkadot-js shows identities from relaychain
> > 
> > 
> > OK. Then I guess there is something redesign stuff to do for the identity page. https://kodadot.xyz/identity/ For now, user could create identity on bsx. We may need to drop the page.
> 
> @prury As we have discussed before, there will be no identity on bsx/snek anymore. There will be only two kinds of identity. kusama: rmrk, ksm, bsx, snek polkadot: dot, ahp

thanks for updating me! 
deposit amounts for both asset hubs are not showing, we will leave them for later? 

When clicking on create identity: 

image

`
Error: createType(Call):: Call: failed decoding identity.setIdentity:: Struct: failed on args: {"info":"{\"additional\":\"Vec<(Data,Data)>\",\"display\":\"Data\",\"legal\":\"Data\",\"web\":\"Data\",\"riot\":\"Data\",\"email\":\"Data\",\"pgpFingerprint\":\"Option<[u8;20]>\",\"image\":\"Data\",\"twitter\":\"Data\"}"}:: Struct: failed on info: {"additional":"Vec<(Data,Data)>","display":"Data","legal":"Data","web":"Data","riot":"Data","email":"Data","pgpFingerprint":"Option<[u8;20]>","image":"Data","twitter":"Data"}:: Struct: failed on additional: Vec<(Data,Data)>:: Expected array/hex input to Vec<*> decoding, found object: {"raw":[]}`

**Comment by vikiival** [comment]
The error says that `additional` field is getting value `{ raw: [] }` instead of `[]`

But I would open it as a follow up issue if it wasn't broken by this 

+ `/identity` should have a redesign per `relay-chain`

**Comment by prury** [comment]
> The error says that `additional` field is getting value `{ raw: [] }` instead of `[]`
> 
> But I would open it as a follow up issue if it wasn't broken by this
> 
>     * `/identity` should have a redesign per `relay-chain`

kind of works fine on canary, here it happens as soon as i click the create identity button, without filling anything

**Comment by Jarsen136** [comment]
> > The error says that `additional` field is getting value `{ raw: [] }` instead of `[]`
> > But I would open it as a follow up issue if it wasn't broken by this
> > ```
> > * `/identity` should have a redesign per `relay-chain`
> > ```
> 
> kind of works fine on canary, here it happens as soon as i click the create identity button, without filling anything

✅  fixed

**Comment by prury** [comment]
@Jarsen136 last thing i guess, 
Discord field no longer there

**Comment by Jarsen136** [comment]
> @Jarsen136 last thing i guess, Discord field no longer there

It's expected. I have removed the discord & Instagram field from the identity form because it does not exist on the new identity structure.

**Comment by prury** [comment]
> 



> > @Jarsen136 last thing i guess, Discord field no longer there
> 
> It's expected. I have removed the discord & Instagram field from the identity form because it does not exist on the new identity structure.

oh, ok ok! ty

**Comment by yangwao** [comment]
image
works
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 4.23 USD/DOT ~ 11.82 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x21b650ac540814c16bf80a0d5cc3f3300fe2c5b929f64accd5c2b61cd6ebab37](https://polkadot.subscan.io/extrinsic/0x21b650ac540814c16bf80a0d5cc3f3300fe2c5b929f64accd5c2b61cd6ebab37)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by roiLeo** [comment]
so no more discord & instagram? (#5226)

**Comment by Jarsen136** [comment]
> so no more discord & instagram? (#5226)

Probably yes because there is no such filed for them. Correct me if I miss something. @vikiival 
image



> For dot and ahp chain we will use
> pid: https://squid.subsquid.io/gs-main-polkadot/graphql
> for rmrk, ksm, bsx, snek we will use
> kid: https://squid.subsquid.io/gs-main-kusama/graphql

**Comment by roiLeo** [comment]
> Probably yes because there is no such filed for them.

Maybe on `additional` key? Not related but are we able to fetch collection banner now? did the indexer parse md5 string?

**Pull request merged**
