### PR TITLE
Update keyboard shortcuts on collections

### LINKED ISSUE #1778: Add to collections sort by
Sort by 
- biggest collections by assets
- most buys 
- most owners
- volume 
- floor price

image

Hints are in series insight https://deploy-preview-1775--koda-nuxt.netlify.app/series-insight/

Probably would require a write resolver to https://github.com/kodadot/rubick

### Ref
- #1357

### LINKED ISSUE #2655: Update keyboard shortcuts in collection
curious, is this reflected in keyboard hint when you press `?` ?  as seems different keyboard shortcuts

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/2619#issuecomment-1076436365_

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2655

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by preschian** [comment]
initially, I want to exclude some sort of options in the collection, but @Jarsen136 was doing better in the PR https://github.com/kodadot/nft-gallery/pull/2636

so, I just update keyboard shortcuts in this PR

**Comment by yangwao** [comment]
curious, is this reflected in keyboard hint when you press `?` ?  as seems different keyboard shortcuts

**Comment by preschian** [comment]
> curious, is this reflected in keyboard hint when you press `?` ? as seems different keyboard shortcuts

ahh, I didn't aware of that component. will check that component probably in 6 hours

**Comment by yangwao** [comment]
> > curious, is this reflected in keyboard hint when you press `?` ? as seems different keyboard shortcuts
> 
> ahh, I didn't aware of that component. will check that component probably in 6 hours

Curious, are you sure you linked the right issue? What's kind of it fixes it? Because by code doesn't seem to add these filter to me.

**Comment by preschian** [comment]
my first commit in this PR was trying to fix the linked issue https://github.com/kodadot/nft-gallery/pull/2619/commits/b98d8e58e2a4a42aab9758c71909d64c7f05e2dc
exclude `'PRICE_ASC', 'PRICE_DESC'` in collections

but, recently it has already been fixed in this PR https://github.com/kodadot/nft-gallery/pull/2636

**Comment by preschian** [comment]
my first commit related to this comment https://github.com/kodadot/nft-gallery/issues/1778#issuecomment-1068706307

**Comment by yangwao** [comment]
> my first commit related to this comment [#1778 (comment)](https://github.com/kodadot/nft-gallery/issues/1778#issuecomment-1068706307)

mmm, for issue dance, it's okay to create side/follow up issue and link that one rather than accidentally closing the main purpose of the previous issue, it's okay to spot other bugs while fixing the primary one 😇

**Comment by preschian** [comment]
updated, need your feedback. is it okay to show some shortcuts in collections/galleries?

| Other pages | Collection | Gallery |
| ------------- | ------------- | ------------- |
| Screen Shot 2022-03-24 at 5 57 30 PM | Screen Shot 2022-03-24 at 5 57 39 PM | Screen Shot 2022-03-24 at 5 57 50 PM |

**Comment by yangwao** [comment]
yup, lfg 👨‍🎤

**Comment by yangwao** [comment]
it's ready to merge? Seems work ok for me

**Comment by preschian** [comment]
@yangwao yaps, if there is no concern, done from me

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 159.35 USD/KSM ~ 0.628 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0xa4e816303fab2acc4deb851f3730a4047cd05107456e1f78bb742d8454fd0311](https://kusama.subscan.io/extrinsic/0xa4e816303fab2acc4deb851f3730a4047cd05107456e1f78bb742d8454fd0311)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
