### PR TITLE
fix: Weird hover in connect wallet 

### LINKED ISSUE #9058: Weird hover in connect wallet
image
and if you click there is blue stroke

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Needs Design check

- @exezbcz please review

## Context

- [x] Closes #9058

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI;

CleanShot 2024-01-21 at 10 50 32 

CleanShot 2024-01-21 at 10 51 12

### CODE REVIEW

**Comment by exezbcz** [comment]
nice! 


one side comment, any idea why it now has different animation from the subselection hover? 
image
image

**Comment by hassnian** [comment]
> one side comment, any idea why it now has different animation from the subselection hover?

@exezbcz  fixed

CleanShot 2024-01-22 at 10 42 26

**Review by roiLeo — APPROVED** [review]

**Comment by yangwao** [comment]
thanks!
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 6.67 USD/DOT ~ 2.999 $DOT
🧗 [16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD](https://polkadot.subscan.io/account/16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)
🔗 [0x772f19b5a5832bf108706f9c93d27c41eccdfbbea30ec9a8bf5c746f6b1e045e](https://polkadot.subscan.io/extrinsic/0x772f19b5a5832bf108706f9c93d27c41eccdfbbea30ec9a8bf5c746f6b1e045e)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
