### PR TITLE
#7685 replace placeholders

### LINKED ISSUE #7685: Replace gallery item place holder with koda v4 logo
Seems we've got new logo meanwhile

image

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #7685
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)

## Screenshot 📸

- [x] My fix has changed UI

Screen Shot 2023-10-16 at 8 58 29 PM
Screen Shot 2023-10-16 at 8 58 59 PM

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
could you use minimized .webp instead?

**Comment by prachi00** [comment]
> could you use minimized .webp instead?

I converted online, the quality is reduced though
Screen Shot 2023-10-17 at 8 49 45 PM


 @exezbcz can you provide webp?

**Review by daiagi — APPROVED** [review]

**Comment by exezbcz** [comment]
@prachi00 Hope this helps. Decided to make it k-grey for both modes, since its placeholder, it does not have to have big contrast 
image

# ZIP 
here is zip, both dark and light version with 4 quality versions - levels of compression. 
[kdarkplaceholder.zip](https://github.com/kodadot/nft-gallery/files/13031436/kdarkplaceholder.zip)
[klightplaceholder.zip](https://github.com/kodadot/nft-gallery/files/13031440/klightplaceholder.zip)

**Comment by prachi00** [comment]
@exezbcz check now

**Comment by prury** [comment]
@exezbcz i think placeholder when loading collection logo image could also be reduced, wdyt
on canary it also had some margins around)

image

**Comment by exezbcz** [comment]
weird, still see the old one on explorer

image

**Comment by exezbcz** [comment]
@prury yup, smaller please and without the stretch

**Comment by prachi00** [comment]
> weird, still see the old one on explorer
> 
> image
Screen Shot 2023-10-21 at 4 37 04 PM

where is this? dont we have skeletons in explore now?

**Comment by prachi00** [comment]
Screen Shot 2023-10-21 at 4 38 32 PM
@prury

**Comment by prury** [comment]
> Screen Shot 2023-10-21 at 4 38 32 PM
> @prury 

@prachi00 the image you attached still shows the old logo. I believe its supposed to show the new logo, but using the same margins and image proportions that we have on canary

**Comment by prachi00** [comment]
@prury 
Screen Shot 2023-10-22 at 3 56 22 PM

**Comment by prury** [comment]
> > weird, still see the old one on explorer
> > image
> 
> Screen Shot 2023-10-21 at 4 37 04 PM
> 
> where is this? dont we have skeletons in explore now?

@prachi00 this one happens in a split of a second when browsing 3D NFTs i guess, hard one to reproduce: 

https://github.com/kodadot/nft-gallery/assets/36627808/76b94dfc-f2ef-4bfd-ae4e-9ba946fc8f1d

**Comment by prachi00** [comment]
Screen Shot 2023-10-23 at 9 12 48 PM
it seems the old placeholder is coming from `nftListWithSearch` query
@roiLeo @prury can we add this in a separate issue ?

**Comment by roiLeo** [comment]
>  it seems the old placeholder is coming from `nftListWithSearch` query @roiLeo @prury can we add this in a separate issue ?

it's comming from `IPFS_KODADOT_IMAGE_PLACEHOLDER`

**Comment by prachi00** [comment]
> IPFS_KODADOT_IMAGE_PLACEHOLDER

okay so what should be the value now for this? how do I get that ipfs hash thingy for new logo?

**Comment by prachi00** [comment]
> > IPFS_KODADOT_IMAGE_PLACEHOLDER
> 
> okay so what should be the value now for this? how do I get that ipfs hash thingy for new logo?

@roiLeo would you know?

**Comment by daiagi** [comment]
>okay so what should be the value now for this? how do I get that ipfs hash thingy for new logo?

maybe I am wrong and we have another way but my guess would be

1. download IPFS desktop
2. upload the new image file from your computer
3. use the new identifier in the code

https://docs.ipfs.tech/how-to/desktop-app/

**Comment by roiLeo** [comment]
> > okay so what should be the value now for this? how do I get that ipfs hash thingy for new logo?
 
Mint it!

**Comment by prachi00** [comment]
> IPFS_KODADOT_IMAGE_PLACEHOLDER

would you mind generating one? I am having trouble loading it
I got this QmVFb2qxyFePqzMqMrwcszpavi95FUhwapPVPu3z7Fxf1B hash but it doesn't load 

https://image-beta.w.kodadot.xyz/ipfs/QmVFb2qxyFePqzMqMrwcszpavi95FUhwapPVPu3z7Fxf1B

**Comment by prachi00** [comment]
> > IPFS_KODADOT_IMAGE_PLACEHOLDER
> 
> would you mind generating one? I am having trouble loading it I got this QmVFb2qxyFePqzMqMrwcszpavi95FUhwapPVPu3z7Fxf1B hash but it doesn't load
> 
> https://image-beta.w.kodadot.xyz/ipfs/QmVFb2qxyFePqzMqMrwcszpavi95FUhwapPVPu3z7Fxf1B

@roiLeo @daiagi

**Comment by daiagi** [comment]
Which network did you mint it in?
I didn't find it browsing through explore

**Comment by prachi00** [comment]
> Which network did you mint it in? I didn't find it browsing through explore

I did it through the ipfs thing you mentioned

**Comment by daiagi** [comment]
Roileo advice was better. Mint it

**Comment by prachi00** [comment]
> Roileo advice was better. Mint it

yeah so about that, I dont have any balance for testing stuff, and I don't know how to get tokens since we shifted on telegram from discord, would you be able to mint it? or tell me how I can get some test tokens? @daiagi

**Comment by daiagi** [comment]
there you go:
https://kodadot.xyz/ahk/collection/197

**Comment by prachi00** [comment]
> there you go: https://kodadot.xyz/ahk/collection/197
> 
> https://image.w.kodadot.xyz/ipfs/bafkreiddaramgs4jvneno4pkjhrs4lr3dbxmrgpqqtviwhco674qeu4vx4 https://image.w.kodadot.xyz/ipfs/bafkreigbvowevtdh5ktnr5kyfxf2b56lp4424zj2gb6wona6if4lh35mbe

thank you

what is the equivalent for the drip thing on telegram?

**Comment by prachi00** [comment]
@roiLeo @daiagi it seems even after replacing the hash
https://deploy-preview-7698--koda-canary.netlify.app/ksm/explore/items?listed=true&search=bureau
still has the old placeholder with hash bafkreifahjdjerrz65puqznmsu2acoktrxjbo3vvp2f2j4eb7h5tc345fi
I searched the codebase and we don't have it anywhere else 
Screen Shot 2023-10-30 at 10 37 46 PM

**Comment by daiagi** [comment]
It seems that `IPFS_KODADOT_IMAGE_PLACEHOLDER` is only used while minting
so any nft minted before this PR will show the previous placeholder

it looks like we're just going to have to live with it

image

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 4.35 USD/DOT ~ 6.897 $DOT
🧗 [13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1](https://polkadot.subscan.io/account/13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)
🔗 [0x932790f73fcd5119aa0cef35a9e75b0d781f35b46b02af0231721cedb9a2cf23](https://polkadot.subscan.io/extrinsic/0x932790f73fcd5119aa0cef35a9e75b0d781f35b46b02af0231721cedb9a2cf23)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
