### PR TITLE
fix: profile dropdown text color in light mode

### LINKED ISSUE #4345: profile dropdown text color
image
wrong text color - should stay black

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4345 
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

### CODE REVIEW

**Comment by exezbcz** [comment]
its still showing the wrong color text color
image

**Comment by daiagi** [comment]
> its still showing the wrong color text color

Done

image

**Comment by yangwao** [comment]
Hey, I guess we should more likely use scoped CSS than !important ?

**Comment by roiLeo** [comment]
> Hey, I guess we should more likely use scoped CSS than !important ?

family-guy-css

**Comment by daiagi** [comment]
Hi guys
I didn't use scoped CSS
but i cleaned up _light.scss and removed !important

Visual Differences:
:zap: hover color on explore and on chain select (it was missing before)
image

:zap:  text color in drop downs, as requested:
image
image
image

**Comment by roiLeo** [comment]
FYI there are [sass variables](https://bulma.io/documentation/components/navbar/#variables) that can be defined

**Comment by daiagi** [comment]
>  FYI there are [sass variables](https://bulma.io/documentation/components/navbar/#variables) that can be defined

Very good tip. thank you
unfortunately it only works if the variables are defined in global scope.

this doesn't work:

```scss
@import "abstracts/variables";
@import "abstracts/animations";
@import "abstracts/fonts";


html.light-mode{
    $navbar-item-color: $text-light-theme;
    $navbar-item-hover-color: $primary-light;
}


// FRAMEWORK (note: don't move this on top)
@import "~bulma";
@import "~buefy/src/scss/buefy";
@import "~@oruga-ui/oruga/src/scss/oruga";
```

**Comment by exezbcz** [comment]
not sure whether its related to this issue but in the deploy preview the color of text in wallet dropdown is incorrect
image

**Comment by daiagi** [comment]
> not sure whether its related to this issue but in the deploy preview the color of text in wallet dropdown is incorrect

Jesus... how the ### did i miss that?!
it's fixed
sorry for wasting your time :disappointed: 

image

**Comment by yangwao** [comment]
lal nice identicon! love it 
image

I mean, let's put it out to beta
pay 80 USD for extra will and quick reactions!

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $80 @ 24.52 USD/KSM ~ 3.263 $KSM
🧗 [EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L](https://kusama.subscan.io/account/EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L)
🔗 [0x6c4eb94fcb4c172ee99d72f769f6f9bf3f78d1397beb1677e00387a9ec93bb4e](https://kusama.subscan.io/extrinsic/0x6c4eb94fcb4c172ee99d72f769f6f9bf3f78d1397beb1677e00387a9ec93bb4e)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
oh need to replenish payout stuff >.>

**Comment by yangwao** [comment]
pay 80 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $80 @ 24.11 USD/KSM ~ 3.318 $KSM
🧗 [EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L](https://kusama.subscan.io/account/EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L)
🔗 [0xdb9a64798e82ae71bf6afc5a4581af5d5ec0e6abf6dbdc6c2c641a949a04d202](https://kusama.subscan.io/extrinsic/0xdb9a64798e82ae71bf6afc5a4581af5d5ec0e6abf6dbdc6c2c641a949a04d202)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
