### PR TITLE
implement skeleton default loading dialog

### PR DESCRIPTION
**Pull request by emagici**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [- ] Feature
- [ ] Refactoring

## Context

- [ ] Closes #5479 
- [] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [-] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality

#### Optional

- [- ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [-] Fill up your KSM address: DaJ6DPPTDy7w2vW2pDmDmYaXxvc6yth6Dd7quhuw5woD224(https://beta.kodadot.xyz/transfer/?target=
<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

#### Community participation

- [-] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [-] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at f3cf10d</samp>

Replaced the EmptyResult component template with a skeleton loading card component to enhance the UX of empty or loading search results. This was part of a PR to add skeleton loading components to `kodadot/nft-gallery`.

### <samp>🤖 Generated by Copilot at f3cf10d</samp>

> _`EmptyResult` changed_
> _Skeleton card shows loading_
> _Winter of waiting_

### CODE REVIEW

**Review by roiLeo — CHANGES_REQUESTED** [review]
Please check how it's done in `/components/landing/topCollections/TopCollections.vue`

I wouldn't put the logic into `EmptyResult` component

**Review by floyd-li — COMMENTED** [review]
is it break the original function of this component?

**Comment by emagici** [comment]
I changed the text component with sekeleton

**Comment by exezbcz** [comment]
image
hey hey, can you please format the skeleton so it has the shape of the item that will be shown?

**Comment by exezbcz** [comment]
hmm, this does not look like collection card skeleton
image
- lmk if its not in the scope of this issue

**Comment by emagici** [comment]
not sure about the shape of collection and card

**Comment by yangwao** [comment]
> can you please link legit issue for this PR and fix formatting in description? Thank you :)

seems skeleton is not working by screenshot and no issue linked to this pr, closing

**Pull request closed without merging**
