### PR TITLE
:zap: fix identity reactivity

### PR DESCRIPTION
**Pull request by daiagi**
make identity reactive
address and on-chain identity updates without needing to refresh page

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [ ] Closes #<issue_number>
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screenshot from 2022-12-15 17-06-38
Screenshot from 2022-12-15 17-06-52

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
indeed I came across this bug, nice fix.
✅ works for me

**Comment by daiagi** [comment]
> edit: what would happen if I set a different identity on my address? is it something possible?
> _example: On BSX -> XXX; On Kusama -> YYY_


Good question. I haven't tested that scenario

**Comment by yangwao** [comment]
> example: On BSX -> XXX; On Kusama -> YYY

Now we are picking it up from Kusama iirc, BSX doesn't have an on-chain identity module. 

In the future, we would offset it using KILT probably

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 26.38 USD/KSM ~ 1.895 $KSM
🧗 [EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L](https://kusama.subscan.io/account/EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L)
🔗 [0xf7e9c42ef552487ce214bf47204b1affa0650f39e6c33371a9d292059c88a3f0](https://kusama.subscan.io/extrinsic/0xf7e9c42ef552487ce214bf47204b1affa0650f39e6c33371a9d292059c88a3f0)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by daiagi** [comment]
@yangwao  the payment failed （InsufficientBalance）

**Comment by yangwao** [comment]
yes

pay 50 usd

- #4523

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 25.19 USD/KSM ~ 1.985 $KSM
🧗 [EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L](https://kusama.subscan.io/account/EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L)
🔗 [0x538697071956f7808d916e7fd0293a4dfa7ab2ea7c642a27bde03736e20f721c](https://kusama.subscan.io/extrinsic/0x538697071956f7808d916e7fd0293a4dfa7ab2ea7c642a27bde03736e20f721c)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
