### PR TITLE
#2468 fetch identity on mounted()

### LINKED ISSUE #2468: Sometimes it won't load identity of an address
Hey. I don't think this will correct anything, Twitter link is working well, thing is that sometimes it won't load identity of an address

_Originally posted by @roiLeo in https://github.com/kodadot/nft-gallery/pull/2429#pullrequestreview-890708515_

Continue from https://github.com/kodadot/nft-gallery/issues/1416

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2468
- [x] Added fetch identity on mounted

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### Before:
https://user-images.githubusercontent.com/734428/158045442-ac0a4467-df84-4a2e-bee1-88ca93663072.mov

### After:
https://user-images.githubusercontent.com/734428/158045847-4938d5f1-2fe3-45df-9bb2-6cb12a77993d.mov

### CODE REVIEW

**Review by vikiival — CHANGES_REQUESTED** [review]
`identityOf` cries in the corner on the line 120.

Your PR makes request on RPC node each time the component mounts :) This feature does not leverage cache at all

**Comment by preschian** [comment]
> `identityOf` cries in the corner on the line 120.
> 
> Your PR makes request on RPC node each time the component mounts :) This feature does not leverage cache at all

updated, to use `identityOf` instead

**Comment by vikiival** [comment]
Screenshot 2022-03-16 at 11 20 46
Just 🔇 `console.log` and we are good to go 

(Tested)

**Review by vikiival — CHANGES_REQUESTED** [review]
🔇

**Review by vikiival — APPROVED** [review]
OKI ✅

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 125.13 USD/KSM ~ 0.799 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0x3cc0ff8f370dacc6aab97493ee130dfd26436a9daa4363241e340456bfc74bce](https://kusama.subscan.io/extrinsic/0x3cc0ff8f370dacc6aab97493ee130dfd26436a9daa4363241e340456bfc74bce)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
