### PR TITLE
fix: Seems popular collections are gone

### LINKED ISSUE #7686: Seems popular collections are gone?
https://kodadot.xyz/ahk/explore/items?listed=true

image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix
  - [x] Refactoring

  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #7686
  - [ ] Requires deployment <snek/rubick/worker>

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

image

  ## Copilot Summary
  
### <samp>🤖 Generated by Copilot at e0b00a5</samp>

Improved the code quality and efficiency of `usePopularCollections.ts` by renaming a type, simplifying a function, and refactoring another function. These changes make it easier to fetch and display popular collections from the chain.

  
### <samp>🤖 Generated by Copilot at e0b00a5</samp>

> _To fetch popular collections by chain_
> _They renamed a type and simplified a function's domain_
> _They also refactored another_
> _To make it run smoother_
> _And thus improved the performance and readability of their code's main_

### CODE REVIEW

**Comment by prury** [comment]
filter won't work on AssetHubs: 
image

**Comment by Jarsen136** [comment]
> Collection filter won't work on Ahp & Ahk #7693

I have created an issue for it https://github.com/kodadot/nft-gallery/issues/7693

**Comment by prury** [comment]
> > filter won't work on AssetHubs:
> 
> I have created an issue for it #7693

thank you so much

**Comment by Jarsen136** [comment]
> > > filter won't work on AssetHubs:
> > 
> > 
> > I have created an issue for it #7693
> 
> thank you so much
> 
> last thing, did we had popular collections on RMRK1? i don't quite remember

No. We only had popular collections on rmrk2, bsx, ank and ahp.

**Review by roiLeo — APPROVED** [review]
should be in composable folder..

**Comment by Jarsen136** [comment]
> should be in composable folder..

✅ Done

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 3.73 USD/DOT ~ 8.043 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x2016560b3ac4704ad11079849a549d4bd008727c9db39d18cc7a548024060f6c](https://polkadot.subscan.io/extrinsic/0x2016560b3ac4704ad11079849a549d4bd008727c9db39d18cc7a548024060f6c)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
