### PR TITLE
:tada: Hello Statemint

### PR DESCRIPTION
**Pull request by vikiival**
- :tada: Statemint
- :zap: asset
- :wrench: for any chain use system token if not specified
- :tada: speck
- :wrench: one prefix rules them all
- :wrench: enable dot on beta
- :wrench: stt config
- :zap: static from workspace

**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 \_\_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [ ] Closes #<issue_number>
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

### <samp>🤖 Generated by Copilot at 95be9ac</samp>

This pull request adds support for Statemint (`stt`), a Polkadot parachain, to the app. It updates various modules and types with the `stt` chain prefix and its properties, urls, and features. It also creates a new workspace package called `static` that contains the chain-related constants and types.

### <samp>🤖 Generated by Copilot at 95be9ac</samp>

> _We're adding `stt` to the app, me hearties_
> _A new chain for the Polkadot family_
> _So pull on the rope and update the code_
> _And we'll sail with Statemint across the web_

### CODE REVIEW

**Comment by vikiival** [comment]
Oh fuk I miss actions

**Review by roiLeo — APPROVED** [review]
`kodadot/vuex-options` ?

otherwise lgtm

where can I find infos about differences between Statemine & Statemint?
is there a rococo testnet?

**Comment by prury** [comment]
- Chain selection working on both mobile and desktop

Statemint button only works after i click on some other network:

https://github.com/kodadot/nft-gallery/assets/36627808/218391dd-32d5-481a-af80-b4b7834b2dd2

**Comment by vikiival** [comment]
> * Chain selection working on both mobile and desktop
> 
> Statemint button on main page only works after i click on some other network:
> 
>  statemint.mp4

Sir you were already on statemint ^-^ 
That's the reason it hasn't worked for you

**Comment by prury** [comment]
> > * Chain selection working on both mobile and desktop
> > 
> > Statemint button on main page only works after i click on some other network:
> > statemint.mp4
> 
> Sir you were already on statemint ^-^ That's the reason it hasn't worked for you

nooooooooo :

> > * Chain selection working on both mobile and desktop
> > 
> > Statemint button on main page only works after i click on some other network:
> > statemint.mp4
> 
> Sir you were already on statemint ^-^ That's the reason it hasn't worked for you

nooooooo, mb! hahaha

**Comment by vikiival** [comment]
> `kodadot/vuex-options` ?
> 

0.1.5 just for u

> where can I find infos about differences between Statemine & Statemint? is there a rococo testnet?

The biggest difference is coming in next few days 

https://support.polkadot.network/support/solutions/articles/65000181800-what-is-statemint-and-statemine-and-how-do-i-use-them-

> testnet

It's name is WestMint and I will add it as soon as I get access to the archive node

**Comment by vikiival** [comment]
Soo can we merge?

**Comment by yangwao** [comment]
pay 100 usd

**Pull request merged**
