### PR TITLE
feat: rmrk stellate endpoint

### LINKED ISSUE #9467: Upgrade rmrk endpoint with Stellate endpoint
- https://rmrk.gql.api.kodadot.xyz/

ref
-
- #9438 
- #9401

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Closes #9467

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)

### CODE REVIEW

**Comment by preschian** [comment]
Probably still dns provisioning? 

image

will check tomorrow

**Comment by yangwao** [comment]
> Probably still dns provisioning?

I think we've crossed something in CF 
Turned it off so could be till TTL expires
I have same thing, weird
image

**Comment by yangwao** [comment]
lol u faster

image

**Comment by yangwao** [comment]
image

**Review by vikiival — APPROVED** [review]

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
> LGTM I would just do
> 
> ```js
> {
>   ksm: 'https://ksm.gql.api.kodadot.xyz/',
> }
> 
> as ksm: rmrk is confusing
> ```

and this one is still in use or disabled already? if used we can use rmrk prefix for that?

https://github.com/kodadot/nft-gallery/blob/57c8ac00a3c93fe2d049a49c41ad9c0054e9c123/libs/static/src/indexers.ts#L9

**Comment by vikiival** [comment]
> and this one is still in use or disabled already? 

Still in use

**Pull request merged**
