### PR TITLE
Japanese Translation

### PR DESCRIPTION
**Pull request by tokchin**

### CODE REVIEW

**Comment by yangwao** [comment]
ah, it should be against i18n and now I see there are missing translations from faq, so I can merge it or wait till you translate whole faq

**Comment by yangwao** [comment]
Here is the full version at `i18n` branch https://github.com/kodadot/nft-gallery/blob/i18n/dashboard/src/locales/jp.json :)

**Comment by avcdsld** [comment]
It seems that the work has been duplicated. I was also working on the same translation. 😂
The result of this translation may also be helpful for discussion.
https://github.com/kodadot/nft-gallery/compare/i18n...avcdsld:i18n?expand=1

**Comment by yangwao** [comment]
yeah, you can split workload as you both know each other tho:D

**Comment by yangwao** [comment]
dont forget post KSM address for NFT rewards:)

**Comment by algoor-creator** [comment]
hi, yesterday i completed the spanish translation and forget post my KSM address: 5FCmj5wrQy9AesJarL5VguZKnCaXPdfAbUqzBsjaPY4r56ii

**Comment by tokchin** [comment]
I made new pr for i18n, so you can close this one.
https://github.com/kodadot/nft-gallery/pull/96

**Comment by yangwao** [comment]
yup, seen, merged, thank you!:)

**Pull request closed without merging**
