### PR TITLE
fix: Nested nfts does not appears in More & Visited

### LINKED ISSUE #8020: Nested nfts doesn't appears in More & Visited
https://canary.kodadot.xyz/ksm/gallery/17583474-3289d9f38266576b1c-AMERICAS2_S01EPISODES-EPISODE_23_LEDC-00000010

image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix

  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #8020
  - [ ] Requires deployment <snek/rubick/worker>

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

image

  ## Copilot Summary
  
### <samp>🤖 Generated by Copilot at a0d77c7</samp>

Added a new fragment `nftResources` to query the resources of NFT entities, and used it in two existing queries (`collectionEntityById` and `nftEntitiesByIDs`) to fetch more information about the NFTs in a collection. This improves the data retrieval and display of NFTs in the gallery.

  
### <samp>🤖 Generated by Copilot at a0d77c7</samp>

> _Sing, O Muse, of the skillful coder who devised_
> _A fragment called `nftResources` to query with ease_
> _The id, thumb, and src of each NFT entity_
> _And added it to queries that needed those fields._

### CODE REVIEW

**Review by roiLeo — CHANGES_REQUESTED** [review]
Capture d’écran 2023-11-12 à 12 24 39 PM

**Comment by Jarsen136** [comment]
> Capture d’écran 2023-11-12 à 12 24 39 PM

✅ Fixed

**Review by roiLeo — APPROVED** [review]
looks same as https://github.com/kodadot/nft-gallery/pull/8035/files, we could consider to unify this

✅ code lgtm

**Comment by Jarsen136** [comment]
> looks same as https://github.com/kodadot/nft-gallery/pull/8035/files, we could consider to unify this
> 
It's similar but not the same because they are in different queries. I have no good idea to unify them unless we unify the structure on the indexer side.

**Review by preschian — APPROVED** [review]

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 5.54 USD/DOT ~ 5.415 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x641bde82c803149ad463665d45c08574701d1e85dbe7c781684333cf3ed977c3](https://polkadot.subscan.io/extrinsic/0x641bde82c803149ad463665d45c08574701d1e85dbe7c781684333cf3ed977c3)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
