### PR TITLE
refactor: adjust profile bottom nav

### LINKED ISSUE #7015: Margin on profile sidebar bottom buttons
image

- should be 24px bottom margin instead of 16
- please make the icons slightly bigger 
image

- 20px icon size itself would be nice 
- it will be then more accessible

### PR DESCRIPTION
**Pull request by thnaylor**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Closes #7015
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=123PCJXhjb15i6JwVVRGd7KvN2sSNZrtPjr5doJq9oWctoTt)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at c6744e0</samp>

Improved the UI and UX of the wallet asset menu component. Used `nuxt-link` for settings to optimize performance.

### <samp>🤖 Generated by Copilot at c6744e0</samp>

> _Oh we're the crew of the nuxt-link ship, and we sail the web so fast_
> _We tweak the icons and align the elements, to make the wallet asset menu last_
> _Heave away, me hearties, heave away with glee_
> _We'll raise the yardarm with our code, on the count of one, two, three_

### CODE REVIEW

**Comment by thnaylor** [comment]
Hi @exezbcz

Just want to clear some things before submitting...

1. Did you want to increase the padding above & below the buttons to 24px?
image

2. The closest natural size on font awesome is 24px (fa-2x) which is the same as the Figma design. is that okay?
image

**Comment by exezbcz** [comment]
@thnaylor good, thanks!

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 4.54 USD/DOT ~ 6.608 $DOT
🧗 [123PCJXhjb15i6JwVVRGd7KvN2sSNZrtPjr5doJq9oWctoTt](https://polkadot.subscan.io/account/123PCJXhjb15i6JwVVRGd7KvN2sSNZrtPjr5doJq9oWctoTt)
🔗 [0xedccfacee5e04cca6e5ccd1a476b6a09300289abebd407ba2a3031ff6d70a058](https://polkadot.subscan.io/extrinsic/0xedccfacee5e04cca6e5ccd1a476b6a09300289abebd407ba2a3031ff6d70a058)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 4.59 USD/DOT ~ 6.536 $DOT
🧗 [123PCJXhjb15i6JwVVRGd7KvN2sSNZrtPjr5doJq9oWctoTt](https://polkadot.subscan.io/account/123PCJXhjb15i6JwVVRGd7KvN2sSNZrtPjr5doJq9oWctoTt)
🔗 [0xfcfab801b6e91842e553f59fb40d5184352b826db281d970e929b2113a196a04](https://polkadot.subscan.io/extrinsic/0xfcfab801b6e91842e553f59fb40d5184352b826db281d970e929b2113a196a04)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
