### PR TITLE
fix: drop calendar small visual things

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

can be tested after https://github.com/kodadot/private-workers/pull/96

- [x] calendar cards: v2 update provide `supply` 
- [x] add placeholder image when no  calendar items are set
- [X] calendar preview: only show carousel if  `calendar` has  `calendar_items` 
- [x] make twitter handle nullable 

## Needs QA check

- @kodadot/qa-guild please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2024-03-25 at 14 35 20@2x

### CODE REVIEW

**Comment by hassnian** [comment]
now that we have https://github.com/kodadot/private-workers/pull/96 can someone populate the db with some  `calendars`  

cc @yangwao  @vikiival 

thanks

**Comment by yangwao** [comment]
> can someone populate the db with some `calendars`

- https://github.com/kodadot/private-workers/pull/96#issuecomment-2017688392

**Comment by hassnian** [comment]
> > can someone populate the db with some `calendars`
> 
> * [feat: Add to calendar API  private-workers#96 (comment)](https://github.com/kodadot/private-workers/pull/96#issuecomment-2017688392)

yes I could add them myself.

but I meant someone who access full access to the list of scheduled drops can add them (I can't see ops-internal) ,  since beta and prod use the same DB , we will need real data

>Calendar table is here: https://www.notion.so/metaprime/4253b4dc2d9d49e0ab1ac095cd1619a6?v=670ccd6a45f84fcb955a9633509bc6fe 

the only relevant info that I can see are twitter_handle and date 

can't see , name, description  and I'd need more details  (if present) like 

`````
{
 "name": "calendar name",
 "description": "calendar description",
 "address": "",
 "content": "",
 "date": "2024-04-21",
 "time": "15:00:00",
 "holder_of": "44",
 "location": "Spain, Barcelona",
 "price": "5000000000",
 "royalty": 10,
 "supply": 500,
 "twitter_handle": "KodaDot"
}

`````

  plus  images

**Comment by prury** [comment]
time will only show in the last 24h like we were talking or will it always show(i prefer the last one)? 

image

**Comment by vikiival** [comment]
> now that we have [kodadot/private-workers#96](https://github.com/kodadot/private-workers/pull/96) can someone populate the db with some `calendars`
> 
> cc @yangwao @vikiival

I can add that later today

**Review by Jarsen136 — APPROVED** [review]
code lgtm

**Comment by vikiival** [comment]
@hassnian there should be two entries in calendar + one image each

**Comment by hassnian** [comment]
> time will only show in the last 24h like we were talking or will it always show(i prefer the last one)?
> 
> image

 for calendar cards if time is provided , it  always will be visible 

CleanShot 2024-03-26 at 16 41 11@2x

> @hassnian there should be two entries in calendar + one image each

now we've got some calendar drops 🚀

@prury let me know if you find anything 

CleanShot 2024-03-26 at 16 37 56@2x

**Comment by prury** [comment]
@hassnian here it still won't show me the full time (date/time)



and when i open the card it shows me the full date/time but not in my timezone/locale

**Comment by hassnian** [comment]
@prury test again 

CleanShot 2024-03-27 at 15 29 22@2x

**Review by Jarsen136 — APPROVED** [review]

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 9.61 USD/DOT ~ 3.122 $DOT
🧗 [16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD](https://polkadot.subscan.io/account/16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)
🔗 [0x29c0b387ac951a1dbb1fc1fcc9d26b0b38fceaea8253cb2cf3322859a651ef47](https://polkadot.subscan.io/extrinsic/0x29c0b387ac951a1dbb1fc1fcc9d26b0b38fceaea8253cb2cf3322859a651ef47)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
