### PR TITLE
feat: hidden `westend` `westmint` in production env

### LINKED ISSUE #3561: Sunsetting unique-west & RMRK (westend)
As we don't need current ones as it was used for implementation, we can remove them from the selector or make them only for development mode when someone wants to run the local environment.

image

### PR DESCRIPTION
**Pull request by zhengow**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3561
- [ ] Requires deployment <rubick/magick_issue>
- [x] <brief_description_of_what_I've_added>
according to env variables, to determine whether show these two test chains.

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

- development env
image

- production env
image

### CODE REVIEW

**Comment by JustLuuuu** [comment]
Sorting: if you click on Explore - after clicking on the top of the column (for example, sort by Price), it will sort offers only on the open page. However, the price should be sorted based on all the items (on all pages), not only one page. This way, you see the highest price only on the open page - the most expensive items can still stay "hidden" on the other pages.

image

**Review by JustLuuuu — APPROVED** [review]
wfm

**Review by roiLeo — APPROVED** [review]
✅ code lgtm

**Comment by yangwao** [comment]
pay 50

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 56.71 USD/KSM ~ 0.882 $KSM
🧗 [EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws](https://kusama.subscan.io/account/EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)
🔗 [0x0883e8673259b564d15e25d7e3671503442b04b4cfac6d7b7e5959b2b4044ffe](https://kusama.subscan.io/extrinsic/0x0883e8673259b564d15e25d7e3671503442b04b4cfac6d7b7e5959b2b4044ffe)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
