### PR TITLE
WIP: new i18n structure proposal

### PR DESCRIPTION
**Pull request by riton**
:warning: This P.R is still a _Work In Progress_ :warning:

This P.R tries to solve #101 and is opened to start a discussion about the data structure and technical solution.

_Note_: It was based on the `i18n-markdown` you initially created.

### CODE REVIEW

**Comment by riton** [comment]
As you'll see, the current version relies on [all_lang.json](https://github.com/riton/nft-gallery/blob/feature/i18n-rework/dashboard/src/locales/all_lang.json) file that contains _lang agnostic_ data (links, etc...).

Only the _link target_ is factorized in the `all_lang.json` file, not the _link text_ . This text can be different between two locales.

You can see in [nl.json](https://github.com/riton/nft-gallery/blob/feature/i18n-rework/dashboard/src/locales/nl.json#L87) how I use a [dummy i18n modifier](https://github.com/riton/nft-gallery/blob/feature/i18n-rework/dashboard/src/i18n.ts#L41) to fetch a given link by name.

This is still not fully functional and bogus but I'd like to discuss about the data structure and the technical solution I've chosen here.

**Comment by yangwao** [comment]
I originally thought to have just markdown links to keep it simple for translators. 
Like here 
image

What are pros cons of my proposition vs yours? 
I guess I miss something as been two months when I hacked on this last time and it's bit complex issue.

**Comment by yangwao** [comment]
Bump on this, we would like to close it to some usable state to have a markdown structure :)

**Comment by riton** [comment]
Hi @yangwao . Sorry for the delay, was AFK for a while. What do you think about the proposed _F.A.Q_ structure ?

### Pros

* Only write information _common to all lang_ in a single place
* 
### Cons

* May be more complicated to write documentation

What's your though on this ?

**Comment by yangwao** [comment]
hey @riton 
I mean, well, let's finish it in this form, so we can unlock adding new FAQ as there was lot of them since while and later we can iterate on better version.
To finish it, would be perfect to have foldable/unfoldable answers, so while you scrolling you don't need to see everything, only stuff you are looking for..
And most important I guess, to be linkable FAQs, so community managers, stewards, &c can pinpoint onboarding users to frequent questions directly :)

I'm amazed to test this stuff and launch translations again as lot of people helped to onboard to this repository :)

**Comment by vikiival** [comment]
Hey @riton,

long time no see! 
How is it going with this proposal ? 

I would love to see a new structure for translations.

**Pull request merged**
