### PR TITLE
fix: Unable to fill footer form

### LINKED ISSUE #5265: Unable to fill footer form
Tested on firefox beta.kodadot.xyz

Screenshot 2023-03-14 at 08-50-32 KodaDot - NFT Market Explorer

footer image is overflowing input & button

might be fixeable with z-index

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5265
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
I'm not sure `z-index` is the best solution.
check out https://github.com/kodadot/nft-gallery/pull/5273#issuecomment-1469609268

IMO it should be something simple:
```html
<footer>
    <img style="position: absolute; bottom: 0; left: 0;" src="..." width="..." height="...">
    <div style="position: relative;">...</div>
</footer>
```

otherwise works for me ✅

**Review by vikiival — APPROVED** [review]
🙈 I will close my eyes for the `z-index`

**Comment by vikiival** [comment]
pay 10 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $10 @ 36.83 USD/KSM ~ 0.272 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x542a45bc8da82f0f88049be902514e0e7010f633b41f0ee342a68850c30cabd1](https://kusama.subscan.io/extrinsic/0x542a45bc8da82f0f88049be902514e0e7010f633b41f0ee342a68850c30cabd1)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
