### PR TITLE
feat: Add to landing generative mints

### LINKED ISSUE #7974: Add to landing generative mints
We will soon have other generative collections, and we can give them spotlight on landing

Till now, make strip under latest sales with collection showing activity list+sales

https://canary.kodadot.xyz/ahk/collection/176

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Feature

  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #7974
  - [ ] Requires deployment <snek/rubick/worker>

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

image

  ## Copilot Summary
  
### <samp>🤖 Generated by Copilot at ba243d1</samp>

This pull request adds a new carousel component for generative NFTs from a specific collection on the AHK chain. It also improves the performance and functionality of the existing carousel components by using custom hooks and lazy loading.

  
### <samp>🤖 Generated by Copilot at ba243d1</samp>

> _`CarouselTypeGenerative` shows us the art of the chain_
> _NFTs of creation, beauty and pain_
> _We filter and sort them with hooks of power_
> _`Lazy` components make the landing page devour_

### CODE REVIEW

**Comment by yangwao** [comment]
Perfecto!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 5.09 USD/DOT ~ 5.894 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x10f355cdce5b97651078313bc296a8d624799ea9f27f5cbd6d2748275c07a476](https://polkadot.subscan.io/extrinsic/0x10f355cdce5b97651078313bc296a8d624799ea9f27f5cbd6d2748275c07a476)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
wait at buy now I see 4 listed? 

image

on landing page are only 3? 

ah realized now we have showing only 3 per collections. 
Hope we will deploy soon another collections soon

**Comment by Jarsen136** [comment]
> wait at buy now I see 4 listed?
> 
> image
> 
> on landing page are only 3?
> 
> ah realized now we have showing only 3 per collections. Hope we will deploy soon another collections soon

will check

**Comment by Jarsen136** [comment]
> wait at buy now I see 4 listed?
> 
> image
> 
> on landing page are only 3?
> 
> ah realized now we have showing only 3 per collections. Hope we will deploy soon another collections soon

The logic of fetching event is not the same as "buy now". We have a limit of four events for the event query, so it only fetched the latest 'buy' and 'list' events. I have made a fix to expand the limit only for generative items. #7993

@yangwao

**Pull request merged**
