### PR TITLE
chore: use more space efficient svg

### PR DESCRIPTION
**Pull request by kkukelka**
🥇 much better
Screenshot 2022-02-06 at 11 54 04

### CODE REVIEW

**Comment by yangwao** [comment]
Actually, @jkdizajn has objections to his own work and working on some improvements! :D Sorry for pushing this fast but happy to have v2 version ;)

**Comment by jkdizajn** [comment]
Hi, I'm sending a slightly reworked version. More dice on the tail, more magic 
**Transparent CSS version:**
Update_3_KodaDot_preloader_css_transparent_bg_responsive

**CSS black background:**

Update_3_KodaDot_preloader_css_black_bg_responsive

**Comment by kkukelka** [comment]
> Hi, I'm sending a slightly reworked version. More dice on the tail, more magic

sweet, just replaced it! 👍

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
lol I spent like at least 30 seconds thinking what's wrong :D 

anyway at least I can handle it

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 194.82 USD/KSM ~ 0.257 $KSM
🧗 [EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW](https://kusama.subscan.io/account/EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)
🔗 [0x7430d3914937f11cb0c1d0793b374af8418281c32efd6614b016a385682d9399](https://kusama.subscan.io/extrinsic/0x7430d3914937f11cb0c1d0793b374af8418281c32efd6614b016a385682d9399)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
