### PR TITLE
fix: incorrect text on above offers table

### LINKED ISSUE #3531: Text of global marketplace offers
Seems we are showing text where it should not be? 

https://beta.kodadot.xyz/bsx/gallery/840505278-1

image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3531
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

stats:

image

incoming offers

image

gallery offers

image

### CODE REVIEW

**Review by prachi00 — APPROVED** [review]

**Comment by prachi00** [comment]
LGTM

**Comment by yangwao** [comment]
let's resolve conflicts and merge this:)

wfm

**Comment by Jarsen136** [comment]
> let's resolve conflicts and merge this:)
> 

Done

**Review by DeluneClaire — APPROVED** [review]
works for me

**Comment by Jarsen136** [comment]
pay 50

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 65.56 USD/KSM ~ 0.763 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x52045dfb6bfca2f7fd57b99f6cff893cdcf1e4386fb606df0fd7b5750ca543ee](https://kusama.subscan.io/extrinsic/0x52045dfb6bfca2f7fd57b99f6cff893cdcf1e4386fb606df0fd7b5750ca543ee)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
