### PR TITLE
🎩 new logo

### PR DESCRIPTION
**Pull request by roiLeo**
### PR type
- [x] Feature #1207 but on main

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### What's new?
- [x] new kodadot logo
- [x] #1225 
- [x] changed primary color to #DA076D (logo test #fc007f) 
- [x] changed light text to #f8f4f6
- [ ] favicon

#### V1 primary logo color
Screenshot 2021-11-19 at 14-37-18 KodaDot - Kusama NFT Market explorer

#### V2 accessible tweak
Screenshot 2021-11-19 at 14-53-59 KodaDot - Kusama NFT Market explorer

Screenshot 2021-11-19 at 14-53-34 Color contrast checker - Coolors

### CODE REVIEW

**Comment by vikiival** [comment]
How about  `#db2980` as the primary colour?

**Comment by roiLeo** [comment]
> How about `#db2980` as the primary colour?

Screenshot 2021-11-19 at 15-49-20 KodaDot - Kusama NFT Market explorer

Screenshot 2021-11-19 at 15-48-42 Color contrast checker - Coolors

**Comment by yangwao** [comment]
Point of fade #1131 was the reason that our pink is pretty invasive for the eye and disturbs it while collecting.
That's why the best reason would be having this one which is not invading your thoughts and figure out better color combo.
I'm even up to add there background like dark github theme has #22272e afaik?

**Comment by roiLeo** [comment]
> Point of fade #1131 was the reason that our pink is pretty invasive for the eye and disturbs it while collecting. That's why the best reason would be having this one which is not invading your thoughts and figure out better color combo. I'm even up to add there background like dark github theme has `#22272e` afaik?

The thing is we shouldn't have to set alpha value on a primary color it's really disturbing.

**Comment by yangwao** [comment]
> > Point of fade #1131 was the reason that our pink is pretty invasive for the eye and disturbs it while collecting. That's why the best reason would be having this one which is not invading your thoughts and figure out better color combo. I'm even up to add there background like dark github theme has `#22272e` afaik?
> 
> The thing is we shouldn't have to set alpha value on a primary color it's really disturbing.

Yeah alpha was just a quick hack of mine, we can figure out something on long-term. 
I guess playing with colours will be a long-term job to find the right sweet spot. 

Generally, let's go with something boring default and then we can play wild with #153 Themes

@xylodrone recently played with new colours, updating you about this
https://www.figma.com/file/XEiqGUitNgIFE0AIgA6XAx/KodaDot_Design-Kit?node-id=40%3A105

**Comment by yangwao** [comment]
Seems like the logo doesn't stand out rn. 
I'd suggest putting it a bit bigger and what about putting border CSS canvas over logo?

**Comment by yangwao** [comment]
Let's replace a new logo on landing as well
image

**Comment by XyloDrone** [comment]
KODA (1)

**Comment by XyloDrone** [comment]
This is our "official" color: E6007E. I will see if we can add some secondary color or different theme. The updated primary color is too dark and it is not a good solution either(I find it as equally distracting as I can't see well).

**Comment by vikiival** [comment]
Can We close it in favour of #1274 ?

**Comment by roiLeo** [comment]
> Can We close it in favour of #1274 

Alright then closing in favor of #1274

**Pull request closed without merging**
