### PR TITLE
#6369 hover effect on dark mode

### LINKED ISSUE #6369: Hover effect on dark mode buttons
image
- I think its time to change this hover effect, let's move to a more subtle color and unify it as for example, in gallery item we are already using different color 
image

### Task
- change hover effect on all button secondary to k-accentlightdark
- the change is for button that currently change from k-darkmode (default state) to k-accent (hover state) 

button: 
image

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #6369
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)

## Screenshot 📸

- [x] My fix has changed UI
Screen Shot 2023-07-05 at 3 53 53 PM

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
is this the expected result? big change compared to beta

Capture d’écran 2023-07-06 à 8 44 42 AM
Capture d’écran 2023-07-06 à 8 44 32 AM

**Comment by exezbcz** [comment]
@roiLeo I have been reconsidering the hover effect for some time already. The accent color was nice. With cart buttons on hover, this change makes sense imo. Wdyt sir?

**Comment by roiLeo** [comment]
> @roiLeo I have been reconsidering the hover effect for some time already. The accent color was nice. With cart buttons on hover, this change makes sense imo. Wdyt sir?

Personally, I like to have a slight hover change like this similar to what is being done at the moment ([nuxt ui](https://ui.nuxtlabs.com/elements/button#white), radix ui, tailwind ui...)

I would keep "accent color" for CTA only

**Comment by exezbcz** [comment]
@roiLeo yup, then it will serve its purpose, thanks!

**Review by roiLeo — APPROVED** [review]

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
pay 15 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $15 @ 5.29 USD/DOT ~ 2.836 $DOT
🧗 [13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1](https://polkadot.subscan.io/account/13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)
🔗 [0xb8ed3a992964b8e3c54f16761bb63c2ca62a0e511c8e3f038e7c208a10b25e3e](https://polkadot.subscan.io/extrinsic/0xb8ed3a992964b8e3c54f16761bb63c2ca62a0e511c8e3f038e7c208a10b25e3e)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
