### PR TITLE
fix: call unbound methods with expected scope

### LINKED ISSUE #2321: (JS-0387) Prefer that unbound methods are called with their expected scope
## Description
Warning is raised when a method is used outside of a method call. Class functions don&#x27;t preserve the class scope when passed as standalone variables.

## Occurrences
There are 5 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/kodadot/nft-gallery/issue/JS-0387/occurrences/](https://deepsource.io/gh/kodadot/nft-gallery/issue/JS-0387/occurrences/)

image

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2321
- [x] call unbound methods with expected scope

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by kkukelka** [comment]
just creates new antipattern... deepsource just doesnt get that keyboardEventsMixin is used as a vue mixin. current implementation is actually correct i believe. the args warning is correct though.

**Comment by kkukelka** [comment]
asked for help on deepsource discord 

Screenshot 2022-02-11 at 16 02 58

**Comment by yangwao** [comment]
should we wait for reply?

**Comment by kkukelka** [comment]
> That's amazing you've reached out to their Discord! :)
> 
> should we wait for a reply?

yes, please 😄 already talking to a staff member

**Comment by kkukelka** [comment]
Screenshot 2022-02-12 at 18 42 25

**Comment by yangwao** [comment]
🫣

**Comment by yangwao** [comment]
If we've fixed it, deepsource should not raise alarms about that in future?

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 163.64 USD/KSM ~ 0.611 $KSM
🧗 [EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW](https://kusama.subscan.io/account/EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)
🔗 [0x8be040272b307e806d807ef64f3f1120c3df0326339bcbb97d30d274e3460939](https://kusama.subscan.io/extrinsic/0x8be040272b307e806d807ef64f3f1120c3df0326339bcbb97d30d274e3460939)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
