### PR TITLE
test: increase requestTimeout and fix identity test

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] increase requestTimeout for media.cy.ts
- [x] fix identity test

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by preschian** [comment]
@yangwao @petersopko 
let's try increasing `requestTimeout` first, maybe I'm wrong regarding `429` errors. if `media.cy.ts` still error in another PR, we skip it then until finding a better solution

**Review by kkukelka — APPROVED** [review]
sounds good to me

**Review by petersopko — APPROVED** [review]
wfm

**Comment by petersopko** [comment]
@yangwao not sure whether we do payouts here or not, I've noticed @preschian started adding his address

**Comment by preschian** [comment]
> @yangwao not sure whether we do payouts here or not, I've noticed @preschian started adding his address

hhmm, no issue for me. yes, I added the address because I copied my gist template to fill in the description. to easier for me to fill the description in every PR 🙈 and this PR only assumption, not 100% sure it will work

Screen Shot 2022-09-02 at 16 38 51

**Pull request merged**
