### PR TITLE
fix: Drop page does not respect visibility from backend

### LINKED ISSUE #9901: Drop page does not respect visibility from backend
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

pink drop is hidden on the backend side, however the frotend still shows it

IMG_0324

### Please reproduce in steps

Go to drop pages 
See there a pink drop

### Expected Behavior

Drops with active == 0 should not be visible on frontend. 

- #9893

### What browsers are you seeing the problem on?

_No response_

### At which address did you encounter bug?

_No response_

### Are you logged in?

None

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

_No response_

### Screenshots

_

### Wallet Address & Transaction hash

_No response_

### Relevant log output

_No response_

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #9901

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed UI

image

### CODE REVIEW

**Comment by yangwao** [comment]
needs to be for release? I mean we can still set pink drop to other time or what is happening?

**Comment by Jarsen136** [comment]
> needs to be for release? I mean we can still set pink drop to other time or what is happening?

It could be set from the worker database
cc @vikiival

**Review by preschian — APPROVED** [review]

**Comment by preschian** [comment]
> needs to be for release? I mean we can still set pink drop to other time or what is happening?

for set to other time, need to set it from worker
for the issue that Vik mentioned, disabled drops showing on the page are fixed in this PR

**Comment by vikiival** [comment]
This are currently hidden drops except pink all the drops are past ones


Screenshot 2024-03-29 at 13 14 33

**Comment by prury** [comment]
@yangwao payment

**Comment by prury** [comment]
pay 15 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $15 @ 8.45 USD/DOT ~ 1.775 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0xfe6b1443b1c1b65d2f68a546a2a9bc8e8256f06b4ccd37bf1349c84e5db7d224](https://polkadot.subscan.io/extrinsic/0xfe6b1443b1c1b65d2f68a546a2a9bc8e8256f06b4ccd37bf1349c84e5db7d224)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
