### PR TITLE
🔧 withdraw offers on burn

### LINKED ISSUE #3584: Burning NFT should cancel Offers
Expanding from @roileo comment here:

why do we need to show burned content?
If it's burned, the offer shouldn't exist anymore

_Originally posted by @roiLeo in https://github.com/kodadot/nft-gallery/pull/3575#pullrequestreview-1051999846_

Currently, burning NFT doesn't affect offers around the NFT at all. I suppose, this is not ideal since it would be only logical to have burning NFT with offers trigger withdrawal / cancellation of offers. 

@vikiival wdyt, what would it take to have it working like this

### PR DESCRIPTION
**Pull request by roiLeo**
waiting for new bsx/snek release to test it

linter is freewheeling..

## PR Type

- [x] Bugfix

## Context

- [x] Closes #3584 
- [x] relate with #4540

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

## Screenshot 📸

⏳

### CODE REVIEW

**Review by vikiival — CHANGES_REQUESTED** [review]
Withdraw offer requires params of maker 

```rs
		pub fn withdraw_offer(
			origin: OriginFor<T>,
			collection_id: T::NftCollectionId,
			item_id: T::NftItemId,
			maker: T::AccountId,
		) -> DispatchResult {
		```

**Comment by vikiival** [comment]
https://github.com/galacticcouncil/Basilisk-node/blob/4c240952f6a9c8d98f10c109befe88a891bb3e9a/pallets/marketplace/src/lib.rs#L219

**Comment by vikiival** [comment]
> related with https://github.com/kodadot/nft-gallery/pull/4540 (https://github.com/kodadot/nft-gallery/pull/4540#issuecomment-1370751062 ❓)

When you want to withdraw offer from nft with id `1001001-2` and me (`bXkoDafMy8Boj55M1KW5dNucT9U7itQLEe7TCwrNykFabADDi`) was the original maker 

You need to call it like:

```ts
const maker = 'bXkoDafMy8Boj55M1KW5dNucT9U7itQLEe7TCwrNykFabADDi'
const cb = api.tx.marketplace.withdrawOffer(this.collectionId, this.nftId, maker)
```

Otherwise you do not know which offer to withdraw 

In other words `withdrawOffer` takes 3 parameters: collectionId, nftId and who

**Comment by vikiival** [comment]
From `OfferUsersTable.vue`

```ts
const cb = api.tx.marketplace.withdrawOffer
const { id, item } = tokenIdToRoute(nft.id)
const args = [id, item, caller]
```

**Comment by roiLeo** [comment]
closing for #4811

**Pull request closed without merging**
