### PR TITLE
:tada: Read on Base

### PR DESCRIPTION
**Pull request by vikiival**
- **base in libs/static/src/chains.ts**
- **:wrench: indexer for base**

**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [x] Integration

## Context

Adding read-only support for Base. 

Some images throw errors as image worker is incorrectly handling arweave urls cc @preschain ^^ 

Rel
-
- https://warpcast.com/yangwao/0xee490dea

### CODE REVIEW

**Comment by vikiival** [comment]
Example of failing address 

- https://image-beta.w.kodadot.xyz/metadata?url=https%3A%2F%2Fimage-beta.w.kodadot.xyz%2Fipfs%2F4e5d146e7ca934fa7d17629d89a9a5cc

**Comment by preschian** [comment]
> Adding read-only support for Base.

woooh 🎉🎉

> Some images throw errors as image worker is incorrectly handling arweave urls cc @preschain ^^

interesting, checking

**Comment by vikiival** [comment]
> Can you give me a metadata link for this or the original ipfs/arweave url without our worker domain

https://squid.subsquid.io/basick/graphql

```graphql
query x {
  nftEntities(limit:10) {
    id
    name
    metadata
    image
    media
  }
}
```

**Comment by vikiival** [comment]
Works as expected!

Thanks.

Screenshot 2024-03-21 at 12 04 56
Screenshot 2024-03-21 at 12 04 47

**Comment by yangwao** [comment]
Can we merge it if it's done so we avoid merge conflicts arising here

**Review by Jarsen136 — APPROVED** [review]

**Pull request merged**
