### PR TITLE
fix: Missing USD value on gallery item

### LINKED ISSUE #6954: Missing USD value on gallery item?
image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Feature

  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #6954
  - [ ] Requires deployment <snek/rubick/worker>

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

image

  ## Copilot Summary
  
### <samp>🤖 Generated by Copilot at f8208fa</samp>

Added USD prices to NFT activity table and made coingecko utility function more generic. This improves the user experience and the code maintainability.

  
### <samp>🤖 Generated by Copilot at f8208fa</samp>

> _Sing, O Muse, of the skillful coder who modified the function_
> _That `getApproximatePriceOf` was called, to take a string as input_
> _And not a fixed union of tokens, as before, that limited its use_
> _But now with `tokenMap` he made it work for any coin of value._

### CODE REVIEW

**Comment by exezbcz** [comment]
uuu, nice nice

Could you just put the USD prices in brackets to a k-grey color + put a gap between the ksm price and USD 
image

**Comment by Jarsen136** [comment]
> uuu, nice nice
> 
> Could you just put the USD prices in brackets to a k-grey color + put a gap between the ksm price and USD image

✅ Updated. Please check it. @exezbcz 
image

**Review by preschian — APPROVED** [review]

**Comment by exezbcz** [comment]
thanks!

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 4.44 USD/DOT ~ 6.757 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0xcf6f68a71e8602fbc25060161b533eecca923ca003082850faee90ba311e7b92](https://polkadot.subscan.io/extrinsic/0xcf6f68a71e8602fbc25060161b533eecca923ca003082850faee90ba311e7b92)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
next I think would be to have only one decimal should be enough to have clear UI 
for bigger numbers I would use "k, M" 1000 -> 1k  & 1,000,000 -> 1M as some tokens are low on value

image

image

**Pull request merged**
