### PR TITLE
preserve random button and pagination

### LINKED ISSUE #2843: Preserve random button and pagination
Once 
- #2781 is merged 
Preserve the ability to go to a particular page or randomize page number, maybe making it sticky while scrolling down?

image

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/2781#issuecomment-1097869853_

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2843
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by Jarsen136** [comment]
It's also weird  because the page automatically loads the next page of content : )

**Review by roiLeo — COMMENTED** [review]
missing:
- hideSearch bar
- fix sort & listed

**Comment by Jarsen136** [comment]
update:
- [x] hideSearch bar
- [x] fix sort & listed 

I found another problem:

Some sort options does not work well. 
'new first' 'old first' works well but the others dont. Do you have any ideas? 👀   @roiLeo 
image

image

image

**Comment by roiLeo** [comment]
> I found another problem:
> 
> Some sort options do not work well. 'new first' 'old first' works well but the others dont. Maybe related to #2718 Do you have any ideas? 👀 

```ts
enum CollectionEntityOrderByInput {
  version_ASC
  version_DESC
  name_ASC
  name_DESC
  max_ASC
  max_DESC
  issuer_ASC
  issuer_DESC
  symbol_ASC
  symbol_DESC
  id_ASC
  id_DESC
  metadata_ASC
  metadata_DESC
  currentOwner_ASC
  currentOwner_DESC
  blockNumber_ASC
  blockNumber_DESC
  meta_id_ASC
  meta_id_DESC
  meta_name_ASC
  meta_name_DESC
  meta_description_ASC
  meta_description_DESC
  meta_image_ASC
  meta_image_DESC
  meta_animationUrl_ASC
  meta_animationUrl_DESC
  meta_type_ASC
  meta_type_DESC
  createdAt_ASC
  createdAt_DESC
}
```

looks like `updateAt` is missing

**Comment by Jarsen136** [comment]
> looks like updateAt is missing in collection we might need to filter on NFTEntityOrderByInput instead

Sorry but I don't understand what should I do to fix it.

**Comment by roiLeo** [comment]
> > looks like updateAt is missing in collection we might need to filter on NFTEntityOrderByInput instead
> 
> Sorry but I still don't understand what should I do to fix it. Could you pls expand more?

For the moment I don't have a quick solution but basically we can't sort CollectionEntity by `updatedAt`, we'll need to edit the graphql query to sort by updateAt on NFTEntity.

**Review by roiLeo — COMMENTED** [review]
could you remove isEqual import since it's not used anymore?

**Comment by Jarsen136** [comment]
>For the moment I don't have a quick solution but basically we can't sort CollectionEntity by updatedAt, we'll need to edit > the graphql query to sort by updateAt on NFTEntity.

How about removing these unSupported sort options?
'Last interacted' and 'Least Interacted'

> could you remove isEqual import since it's not used anymore?

Sure, I have done

**Review by roiLeo — APPROVED** [review]
✅ tested

**Comment by Jarsen136** [comment]
> Tested one more thing
> 
> https://deploy-preview-2850--koda-nuxt.netlify.app/rmrk/explore?page=1&search=&sort=blockNumber_ASC&listed=true
> 
> should show me "Old first" but it show me the newest

I have fixed it just now.

**Review by roiLeo — APPROVED** [review]
pay 100

**Comment by roiLeo** [comment]
hmmmmm???

**Comment by roiLeo** [comment]
pay 100

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 158.42 USD/KSM ~ 0.631 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xe5543faa1fe45d6f70380864c6de9617957e260705fbdb5d6bfd8243dbf132ce](https://kusama.subscan.io/extrinsic/0xe5543faa1fe45d6f70380864c6de9617957e260705fbdb5d6bfd8243dbf132ce)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
