### PR TITLE
fix: Item name drop

### LINKED ISSUE #8717: Item name drop
image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix

  ## Context

  - [x] Closes #8717

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Copilot Summary
  copilot:summary

  copilot:poem

### CODE REVIEW

**Review by daiagi — COMMENTED** [review]
simple change, but what about this?
>3. Just an idea: When all the items are named the same, and the image is the same, maybe it's better to add the item's id to the title?

https://github.com/kodadot/nft-gallery/issues/7857

**Comment by Jarsen136** [comment]
> simple change, but what about this?
> 
> > 3. Just an idea: When all the items are named the same, and the image is the same, maybe it's better to add the item's id to the title?
> 
> #7857


The id is still there after the name, but remove the duplicate id.
https://deploy-preview-8728--koda-canary.netlify.app/ahp/drops/christmascity

image

**Comment by daiagi** [comment]
related:

are we cool with all the nft's having the same name in Explore?
@exezbcz @yangwao 

image

**Review by roiLeo — APPROVED** [review]

**Comment by Jarsen136** [comment]
> related:
> 
> are we cool with all the nft's having the same name in Explore? @exezbcz @yangwao
> 
> image

It's not related to this PR because it's the same as canary env.

Look like it does not have the id after the name on the Explorer page. I will add it.

image

**Comment by daiagi** [comment]
>Look like it does not have the id after the name on the Explorer page. I will add it.

iirc it was there but then there was an issue where unique nfts (not generative) add the id shown as well
we need a way to tell apart 'regular' from generative nfts

**Review by daiagi — APPROVED** [review]

**Comment by Jarsen136** [comment]
> > Look like it does not have the id after the name on the Explorer page. I will add it.
> 
> iirc it was there but then there was an issue where unique nfts (not generative) add the id shown as well we need a way to tell apart 'regular' from generative nfts
> 

Got it. The nft id could be shown on the collection page as I have seen. That makes more sense. Then I would hold it on the explorer page for now.

> > It's not related to this PR because it's the same as canary env.
> 
> sorry, i meant the topic is related. indeed not stemming from this PR

That's ok. I just a bit confused : )

**Comment by yangwao** [comment]
> are we cool with all the nft's having the same name in Explore?

i think that was issue why it appeared in drops, we want it in collection yup

**Comment by yangwao** [comment]
thanks!
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 8 USD/DOT ~ 2.5 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x0a9f21387af0af95d7817e898b69dc59866d2e5bcdb81a17e1de786a9b07c968](https://polkadot.subscan.io/extrinsic/0x0a9f21387af0af95d7817e898b69dc59866d2e5bcdb81a17e1de786a9b07c968)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
