### PR TITLE
fix: set sorting to desc by default on spotlight and series

### LINKED ISSUE #1807: Adjust sorting to be descending at first click
At first, click make it show descending numbers, not ascending numbers

Both for series and spotlight
Probably blocking issue for series is #1757 

https://user-images.githubusercontent.com/5887929/149490372-247a0408-6d7e-45e3-ae85-48f9c816690d.mov

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

https://user-images.githubusercontent.com/17953978/153388974-56932d2f-3c03-4f87-9a39-057f3743ac35.mov

### What's new?

- [x] PR closes #1807
- [x] table sorting now descending by default

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
Nice catch! lgtm

**Comment by kkukelka** [comment]
> When I click on Price it puts first 4 0.00 as first and then it goes desc.. it's string/bignum issue?
> 
> image
> 
> Score, unique items and unique collections could not be sorted hmm, I recall @roiLeo was looking on this one?

yes, formatting issue 
Screenshot 2022-02-11 at 07 38 16

**Comment by kkukelka** [comment]
But i believe this is out of scope of this ticket. 
Let's pick it up here 👉  #2327

**Comment by yangwao** [comment]
pay 50 usd

**Pull request merged**
