### PR TITLE
fix: Transfer doing weird thing

### LINKED ISSUE #5628: Transfer doing weird thing
Transfer on Beta doing weird thing. When you open it - it appears as a network on the top of the page. (?) Not sure how to explain it. So here is a video:

https://user-images.githubusercontent.com/104380776/231508050-3b838062-c194-4e82-8db5-078228b36514.mov

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5628
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by vikiival** [comment]
or move transfer under prefix ;D so we don't have issues like this

**Comment by Jarsen136** [comment]
> or move transfer under prefix ;D so we don't have issues like this

There are also some other route have this bug, like /teleport-bridge /faq etc, so we should not try to move the file. wdyt?

**Comment by vikiival** [comment]
> we should not try to move the file. wdyt?

It would still do weird shit, because we highly rely on the prefix in the route,
at least I would like to have workable transfer without breaking any magic/logic

**Comment by Jarsen136** [comment]
> > we should not try to move the file. wdyt?
> 
> It would still do weird shit, because we highly rely on the prefix in the route, at least I would like to have workable transfer without breaking any magic/logic

Once we move the transfer under `/prefix`, something would break. For example, the transfer url would become `/rmrk/transfer?target=address.` instead of `/transfer?target=address.`. Then some previous payment links in our project and in the PR payout link would be invalid.

image

If we confirm that we still would like to do so, I will commit the changes.

**Comment by vikiival** [comment]
cc @yangwao

**Comment by yangwao** [comment]
> if we put prefix to url aka kodadot.xyz/rmrk/transfer will it break the payment bot ?

yes

```
const lookupForAddress = /kodadot\.xyz\/transfer\/?\?target=\w[a-zA-Z0-9]{46,}\b/g;
```

we can make breaking change here, probably we will have transfer.kodadot.xyz or pay.kodadot.xyz we will see
- #5575 

plus there are bunch of pre-generated links with that stuff for payments waiting etc, don't make it worse 😅 aka please don't break it now.

**Comment by Jarsen136** [comment]
Then I guess this PR is good to go, to fix the original bug.

**Comment by yangwao** [comment]
wkrs!

image

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 36.93 USD/KSM ~ 0.812 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x1f49ccab6ac2531c80d0d5f9359930eff6f2c479af88103345ab9c280468e0ee](https://kusama.subscan.io/extrinsic/0x1f49ccab6ac2531c80d0d5f9359930eff6f2c479af88103345ab9c280468e0ee)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
