### PR TITLE
fix: 5099 sort by button variant

### LINKED ISSUE #5099: Sort by filter count
image
- wrong bg color, should be k-accent

### PR DESCRIPTION
**Pull request by maderi21**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5099 
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [x] I've tested it at </bsx/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=JHJGu2aWyAFBfcso8bR7ma82p15YAavyN6vQfJyWuhniNGa)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

### CODE REVIEW

**Review by roiLeo — CHANGES_REQUESTED** [review]
Hey @maderi21 issue is to change the background color of `sort-count` (on darkmode?)

It should look like this:
Screenshot 2023-02-23 at 09-20-05 Low minting fees and carbonless NFTs KodaDot - NFT Market Explorer

**Comment by maderi21** [comment]
> Hey @maderi21 issue is to change the background color of `sort-count` (on darkmode?)
> 
> It should look like this: Screenshot 2023-02-23 at 09-20-05 Low minting fees and carbonless NFTs KodaDot - NFT Market Explorer

fixed now, I misunderstood. thanks.

**Review by roiLeo — APPROVED** [review]
✅ lgtm

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
pay 10 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $10 @ 42.07 USD/KSM ~ 0.238 $KSM
🧗 [JHJGu2aWyAFBfcso8bR7ma82p15YAavyN6vQfJyWuhniNGa](https://kusama.subscan.io/account/JHJGu2aWyAFBfcso8bR7ma82p15YAavyN6vQfJyWuhniNGa)
🔗 [0xa4e148a63111df8c201c22b7849e94bfa9b486627f2d10834fbe934b8e4c76a7](https://kusama.subscan.io/extrinsic/0xa4e148a63111df8c201c22b7849e94bfa9b486627f2d10834fbe934b8e4c76a7)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
