### PR TITLE
⚠️ Stick v4

### LINKED ISSUE #6774: NFT set_attribute calls ignored by UI?
### What happened?

I am minting an NFT here: https://assethub-kusama.subscan.io/extrinsic/5163694-2
and then setting the attribute: https://assethub-kusama.subscan.io/extrinsic/5163738-2
the kodadot UI does not display the attributes in the "properties" tab: https://kodadot.xyz/ahk/gallery/97-5812

Also on this item: https://kodadot.xyz/ahk/gallery/97-2583060150 Only properties from the metadata are displayed while there are many set_attribute calls for the nft present in this extrinsic: https://assethub-kusama.subscan.io/extrinsic/5163596-2

I also checked the substrate portal if attributes are really saved to nft and they are, see the output on [this gist](https://gist.github.com/niklasp/172d9e0325e208e9b60cf86411652c06)

Is it because there is metadata? Does the ui take set_attribute calls into account? are they overriden by the metadata?

### Please reproduce in steps

mint an nft, do a `set_attribute` extrinsic, check the UI, attributes are not displayed in Kodadot

### Expected Behavior

attributes to be a merge from the metadata attributes and the attributes set in `set_attribute` extrinsics

### At which address did you encounter bug?
- beta.kodadot.xyz
- kodadot.xyz
- canary.kodadot.xyz

### At which address did you encounter bug?

Kusama Asset Hub

### Payment link for reward

https://kodadot.xyz/ksm/transfer/?target=DT7kRjGFvRKxGSx5CPUCA1pazj6gzJ6Db11xmkX4yYSNK7m

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by vikiival**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

# Please do not merge this PR, It is intended just for the testing purposes

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #6774

#### Before submitting pull request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

please @prury for test

### <samp>🤖 Generated by Copilot at e18ddbe</samp>

Updated the URLs for the `ahk` and `stick` indexers to use the new version that supports the latest metadata and events features. This improves the indexing performance and accuracy for the NFT gallery.

### <samp>🤖 Generated by Copilot at e18ddbe</samp>

> _Indexers upgraded_
> _`ahk` and `stick` use v4_
> _Autumn of changes_

### CODE REVIEW

**Comment by preschian** [comment]
@vikiival curious, why we go back to v4 instead of set v4 to prod?

**Comment by vikiival** [comment]
> @vikiival curious, why we go back to v4 instead of set v4 to prod?

Screenshot 2023-08-18 at 14 24 11

**Comment by preschian** [comment]
aahh, sorry, my bad

I think it's better to set it as a draft PR instead

**Comment by prury** [comment]
@vikiival is for me to check if stuff loads on the Kusama Asset Hub? if yes, it works

**Comment by niklasp** [comment]
please see my question concerning duplicates: https://github.com/kodadot/nft-gallery/issues/6774#issuecomment-1683860996

**Comment by prury** [comment]
seems allright

**Comment by vikiival** [comment]
https://github.com/kodadot/nft-gallery/assets/22471030/176925e4-2f32-4c0b-9bca-4bef4b0ead73

**Pull request closed without merging**
