### PR TITLE
:zap: Create is back

### PR DESCRIPTION
**Pull request by hassnian**
This reverts commit c716ffd1c71329c3d342075eb2a70887bc440091, reversing changes made to eb9f53e2649266dd7c34fcf777282a9588c8e3ca.

### CODE REVIEW

**Comment by Jarsen136** [comment]
Could you pls remove `create` from BASE and other evm chain.

image

**Comment by hassnian** [comment]
> Could you pls remove `create` from BASE and other evm chain.
> 

done [0626a8b](https://github.com/kodadot/nft-gallery/pull/10626/commits/0626a8b6f603c398e8fe9b7f91610898729840d3)

**Comment by vikiival** [comment]
> > Could you pls remove `create` from BASE and other evm chain.
> 
> done [0626a8b](https://github.com/kodadot/nft-gallery/pull/10626/commits/0626a8b6f603c398e8fe9b7f91610898729840d3)

Screenshot 2024-07-17 at 13 30 54

**Comment by vikiival** [comment]
Pushed IPOS for nftstorage replacement

blocked by
https://github.com/kodadot/workers/issues/318

**Comment by vikiival** [comment]
@kodadot/internal @kodadot/internal-dev can you please test ?

**Comment by Jarsen136** [comment]
WFM

**Comment by damskyftw** [comment]
Minted collection + 3 nfts into it

works well

https://deploy-preview-10626--koda-canary.netlify.app/ahp/collection/168

**Comment by vikiival** [comment]
> > > Could you pls remove `create` from BASE and other evm chain.
> > 
> > 
> > done [0626a8b](https://github.com/kodadot/nft-gallery/pull/10626/commits/0626a8b6f603c398e8fe9b7f91610898729840d3)
> 
> Screenshot 2024-07-17 at 13 30 54

@hassnian can you please hide this?

**Comment by hassnian** [comment]
> > > > Could you pls remove `create` from BASE and other evm chain.
> > > 
> > > 
> > > done [0626a8b](https://github.com/kodadot/nft-gallery/pull/10626/commits/0626a8b6f603c398e8fe9b7f91610898729840d3)
> > 
> > 
> > Screenshot 2024-07-17 at 13 30 54
> 
> @hassnian can you please hide this?

create on evm is already hidden

**Pull request merged**
