### PR TITLE
check and justify sort condition from url

### LINKED ISSUE #3143: Something broken in /explore/Gallery
- Sorting doesn't work as excepted
- passion feed toggle doesn't change data
- https://beta.kodadot.xyz/rmrk/explore/?page=1&tab=GALLERY&listed=false&sort=B&sort=L&sort=O&sort=C&sort=K&sort=_&sort=N&sort=U&sort=M&sort=B&sort=E&sort=R&sort=_&sort=D&sort=E&sort=S&sort=C&sort=EMOTES_COUNT_DESC when using double sorting

Here is my address If you want to test the query:
`HguGafrfk8nRP9a4tgJf7hLvSSFie8GtkDjyWFHQ2kDUAMc`

#### video as example

https://user-images.githubusercontent.com/9987732/173069609-1a77decd-fa8b-4bb5-95a2-a22f86e9cbae.mov

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3143 
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

when open the link:
 https://deploy-preview-3147--koda-nuxt.netlify.app/rmrk/explore/?page=1&tab=GALLERY&listed=false&sort=B&sort=L&sort=O&sort=C&sort=K&sort=_&sort=N&sort=U&sort=M&sort=B&sort=E&sort=R&sort=_&sort=D&sort=E&sort=S&sort=C&sort=EMOTES_COUNT_DESC

it will redirect to
https://deploy-preview-3147--koda-nuxt.netlify.app/rmrk/explore/?page=1&tab=GALLERY&listed=false&sort=EMOTES_COUNT_DESC

image

### CODE REVIEW

**Comment by Jarsen136** [comment]
> hing, I'm not sure if I'm doing something wrong, but I can't see the passion feed toggle at all? I'd like to test that as well since it's mentioned in the origi

it's maybe because you don't have any nft in your account. 
I think you could try to toggle off the passion feed to test this issue.

**Review by petersopko — APPROVED** [review]
wfm, let's go

**Comment by petersopko** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 48.81 USD/KSM ~ 2.049 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x3f0fd19356696e88749d7c64014cada684d1a8dca7012cb804052c86f52b4486](https://kusama.subscan.io/extrinsic/0x3f0fd19356696e88749d7c64014cada684d1a8dca7012cb804052c86f52b4486)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
