### PR TITLE
fix: adjust query in landing page

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Related #6739
- [x] Related https://github.com/kodadot/stick/issues/93

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)

### CODE REVIEW

**Comment by preschian** [comment]
It seems like we don't need the `lastEvent` query for the carousel on the landing page. Since we already had `nftEntities` or `events` query

in this PR I try to change the query with `nftEntities`

wdyt? @vikiival @roiLeo

**Review by roiLeo — APPROVED** [review]
Lgtm

**Review by daiagi — APPROVED** [review]

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 4.48 USD/DOT ~ 11.161 $DOT
🧗 [1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p](https://polkadot.subscan.io/account/1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)
🔗 [0x5e1bf69eeb2f3c89091a736aa3b00c6d738fbbecf9b4f8645def6eb3a78b2249](https://polkadot.subscan.io/extrinsic/0x5e1bf69eeb2f3c89091a736aa3b00c6d738fbbecf9b4f8645def6eb3a78b2249)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
