### PR TITLE
feat: Recent generative nft mints in drop page

### LINKED ISSUE #9476: Recent generative nft mints in drop page
some updates, the main one is the look, filters, infinite scroll 
image

## design
- updated in handoff https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=394-6126&mode=design&t=EmUe59kRyBTfd3zb-11
- new heading
- new filters
- footer removed
- infinity scroll
- please Reuse Explorer layout 
- new slightly upgraded card 

## Bottom section
shares some similarities with profile layout 
image

- new heading 
- filters - please refer to the component page or reuse the same ones as in the profile 
- default filter is sort by newest - active buy now filter is button active 

## card
image
card is small card from explorer with one addition, instead of the network, there is time, there is no"ago" etc. just time. 

its the same grey tag we are using next to cursor in partykit:
- #9413 

thanks!

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #9476

## Needs Design check

- @exezbcz please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2024-02-24 at 10 54 44

### CODE REVIEW

**Comment by exezbcz** [comment]
bullish


image

top margin to 80px please



image
- padding to 12px at least? (inside the card for the text)

**Comment by exezbcz** [comment]
> top margin to 80px please

image

only margin-top

**Comment by exezbcz** [comment]
on mobile it can probably stack on top of each other 
image


so on top is heading, under are filters

**Review by Jarsen136 — APPROVED** [review]

**Comment by prury** [comment]
> i think some unneeded parameters are being passed if you filter and click on an nft
> 
> `?listed=true` https://deploy-preview-9536--koda-canary.netlify.app/ahp/gallery/99-92?listed=true
> 
> otherwise looks good

as @hassnian discovered is actually from canary, will open issue

**Comment by yangwao** [comment]
Thanks, very well made!
pay 70 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $70 @ 7.88 USD/DOT ~ 8.883 $DOT
🧗 [16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD](https://polkadot.subscan.io/account/16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)
🔗 [0xa148fe1b9c1542ab878595eba9d27879de91828239e8251da63523ce6ad563e3](https://polkadot.subscan.io/extrinsic/0xa148fe1b9c1542ab878595eba9d27879de91828239e8251da63523ce6ad563e3)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
