### PR TITLE
feat: calculate 14days expiration for `offer`

### LINKED ISSUE #3339: When user submits make offer action, offer should have 14 day expiration on-chain
### Is your feature request related to a problem?

Currently offers are set to block 1mil

### Describe the solution you would like

I would like to see that we take current block and add number of blocks * 14

Screenshot 2022-07-06 at 13 00 14

basically formula => 
```ts
const BLOCK_OFFSET = 5 // time between submit & finalization
const BLOCK_PER_DAY_COUNT = 7200 // as on the picture 
const DAY_COUNT = 14 // two weeks
const currentBlock = await api.query.system.number()
const expiration = currentBlock + BLOCK_OFFSET + (BLOCK_PER_DAY_COUNT * DAY_COUNT)
```

### Describe alternatives you have considered

Screenshot 2022-07-06 at 13 04 56

### Screeenshots

_No response_

### Deliverables

When user makes transaction to make offer.
- [ ] instead of passing block [1 000 000](https://github.com/kodadot/nft-gallery/blob/dec0f3754b662423581420d999753934d946f8c9/utils/gallery/abstractCalls.ts#L33)
- [ ]  make sure you calculate the correct expiration date using formula above
- [ ] therefore `abstractCalls.ts#L33` should look like -> `MAKE_OFFER: [collectionId, tokenId, meta, expiration],`

### PR DESCRIPTION
**Pull request by zhengow**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3339 
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

### CODE REVIEW

**Review by prachi00 — APPROVED** [review]

**Comment by prachi00** [comment]
LGTM

**Comment by prachi00** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 51.94 USD/KSM ~ 0.963 $KSM
🧗 [EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws](https://kusama.subscan.io/account/EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)
🔗 [0xed9945aa46108c9865b1cfc95fd56a37371633fcc4074df9ea5fb235d79d3e82](https://kusama.subscan.io/extrinsic/0xed9945aa46108c9865b1cfc95fd56a37371633fcc4074df9ea5fb235d79d3e82)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by vikiival** [comment]
Dafuq

**Comment by prachi00** [comment]
> Dafuq

yeah my bad, I later on realized that this wasn't doing anything and reopened, I'll make sure to balance out the payment with the new PR that @zhengow will raise, sorry about this

**Comment by vikiival** [comment]
> yeah my bad, 


It was also my bad, it haven't provided proper description of the task. So basically @zhengow made what was written there. 

I'll try to provide better description next time ^-^

**Comment by zhengow** [comment]
> > yeah my bad,
> 
> It was also my bad, it haven't provided proper description of the task. So basically @zhengow made what was written there.
> 
> I'll try to provide better description next time ^-^

My bad too. Actually I want to pull a request to figure out what need to do. 
Emmm... 🤣

**Pull request merged**
