### PR TITLE
:memo: tables update 24.11.2022

### PR DESCRIPTION
**Pull request by petersopko**
@yangwao I've just noticed bot doesn't update the tables, it's because the dedicated bot branch keeps getting deleted :) it would be best if you could keep one branch named `kodabot` which will be used for automated updates (as was done before). I don't have the rights anymore, lmk what you think.

### CODE REVIEW

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
Thanks for your contribution @petersopko
I was thinking to make kodabot as a part of kodadot/bao#15 so we are able to automatize that.

**Review by Jarsen136 — APPROVED** [review]

**Comment by petersopko** [comment]
> Thanks for your contribution @petersopko I was thinking to make kodabot as a part of [kodadot/bao#15](https://github.com/kodadot/bao/issues/15) so we are able to automatize that.

👍🏻 resolved in DMs

**Comment by vikiival** [comment]
Maybe update table to this day and lets merge it?

**Comment by petersopko** [comment]
> Maybe update table to this day and lets merge it?

It's updated 🚀

**Pull request merged**
