### PR TITLE
fix: uppercase on network indicators

### LINKED ISSUE #8777: uppercase on network indicators
we should make this unified 

- Lets use Ahp since its used everywhere apart from explore cards 

so on explore part, it should be Ahp instead of AHP

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix
  
  ## Needs Design check

  - @exezbcz please review

  ## Context

  - [x] Closes #8777
  - [ ] Requires deployment <snek/rubick/worker>

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

image
image

  ## Copilot Summary
  copilot:summary

  copilot:poem

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
I would remove `chain-name` class and add `text-k-grey` class

**Comment by Jarsen136** [comment]
> I would remove `chain-name` class and add `text-k-grey` class

Good point. I have updated it.

**Comment by roiLeo** [comment]
> > I would remove `chain-name` class and add `text-k-grey` class
> 
> Good point. I have updated it.

`has-text-k-grey` is Bulma legacy, new one with tailwind is `text-k-grey`

**Comment by Jarsen136** [comment]
> > > I would remove `chain-name` class and add `text-k-grey` class
> > 
> > 
> > Good point. I have updated it.
> 
> `has-text-k-grey` is Bulma legacy, new one with tailwind is `text-k-grey`

Ok. I have replaced them in the codebase globally to avoid confusion.

**Review by roiLeo — APPROVED** [review]

**Comment by Jarsen136** [comment]
@yangwao code conflicts resolved

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Pull request merged**
