### PR TITLE
refactor: remove idb-keyval

### LINKED ISSUE #4744: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
Sentry Issue: [NFT-GALLERY-Y9](https://sentry.io/organizations/kodadot/issues/3875348276/?referrer=github_integration)

```
InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
  at transaction ([native code])
  at promiseReactionJob ([native code])
```

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Closes #4744 

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
🚀 yolo

**Comment by vikiival** [comment]
pay 49 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $49 @ 35.51 USD/KSM ~ 1.38 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0x34d94123580a5508237eeefa3aeccaa4b942177e2bbae85fa09740562208817b](https://kusama.subscan.io/extrinsic/0x34d94123580a5508237eeefa3aeccaa4b942177e2bbae85fa09740562208817b)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
pay 49 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $49 @ 36.47 USD/KSM ~ 1.344 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0x7dd9757975fadfeb18b200b08bd403cc4385bd6698c7df75d6de213f7dee0562](https://kusama.subscan.io/extrinsic/0x7dd9757975fadfeb18b200b08bd403cc4385bd6698c7df75d6de213f7dee0562)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
