### PR TITLE
#5419 grid color

### LINKED ISSUE #5419: Collection Chart - background lines
I would put background lines something gray or closer to background color? it's hard to read and look on it in lot of events

https://deploy-preview-5352--koda-nuxt.netlify.app/rmrk2/collection/66241b171becfd500e-EGG/activity

image

comparing old one

image

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Closes #5419
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screen Shot 2023-03-29 at 8 50 09 PM

### CODE REVIEW

**Comment by exezbcz** [comment]
is it possible to maybe show every second line after some specific line count? This way it would not be only lines but it will show also some data :D 


Otherwise oki, good job!

**Comment by yangwao** [comment]
> show every second line after some specific line count?

yes this, if it would be possible, would help

**Comment by exezbcz** [comment]
and how does it look like now on charts that had only 2 lines? Yes, on these charts its what we wanted

**Review by vikiival — APPROVED** [review]
Code is LGTM,
once approved by @exezbcz we can merge

**Comment by yangwao** [comment]
> I increased it to 2 from 1

hey, feel free to put it to 3

**Comment by prachi00** [comment]
> > I increased it to 2 from 1
> 
> hey, feel free to put it to 4

increased to 4

**Comment by prachi00** [comment]
Screen Shot 2023-04-01 at 3 30 39 PM
Now

**Comment by vikiival** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 33.88 USD/KSM ~ 0.59 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0xc99ae36ee96c13745b3eb8d17cdc23648c278df85ce4a95eb99ff793d0e922c9](https://kusama.subscan.io/extrinsic/0xc99ae36ee96c13745b3eb8d17cdc23648c278df85ce4a95eb99ff793d0e922c9)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
