### PR TITLE
docs: specified correct node version to avoid --openssl-legacy-provid…

### LINKED ISSUE #6646: --openssl-legacy-provider error
### What happened?

With node version 18.13, I am getting this error after pnpm dev

node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
 ELIFECYCLE  Command failed with exit code 9.

### Please reproduce in steps

Use node 18.13 
pnpm dev

### Expected Behavior

no errors

### What browsers are you seeing the problem on?

_No response_

### At which address did you encounter bug?

_No response_

### Are you logged in?

None

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

_No response_

### Screenshots

image

### Payment link for reward

https://kodadot.xyz/ksm/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by stephenjason89**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Documentation
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #6646
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [ ] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer?target=16UcV9V6nVvPYdHz98ymUKmNLkzjCEU5sbKJMi7hxYyTHjzR&usdamount=100&donation=true)

### <samp>🤖 Generated by Copilot at b2873a2</samp>

Updated the node version to 18.17 in the blog post `content/blog/first-time.md` and the `package.json` file. This change follows the latest node LTS release and improves the project's compatibility and security.

### <samp>🤖 Generated by Copilot at b2873a2</samp>

> _Blog post and code_
> _`node` version harmonized_
> _Fall of LTS_

### CODE REVIEW

**Comment by stephenjason89** [comment]
@yangwao should we also change the minimum requirement from package.json?
I am not so sure what version fixes this issue but definitely 18.13 and below has this issue.

Some test are failing if i change to 18.16 
image

Because node version on the tests uses 18.13

by the way i am using mac and can't say certainly if windows users has the same issue

**Comment by stephenjason89** [comment]
> Screenshot 2023-08-10 at 14-59-06 Commit range not found · Pull Request #6651 · kodadot_nft-gallery
> 
> pather

sorry about that haha. I never really force push but in this case it was just 1min haha.

**Comment by stephenjason89** [comment]
@yangwao mine could be an edge case as i have node 18.13 installed on my machine. 

Let's close this issue for now 😁

**Comment by yangwao** [comment]
bonus points for finding 
- #5961

**Comment by yangwao** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 5.03 USD/DOT ~ 3.976 $DOT
🧗 [16UcV9V6nVvPYdHz98ymUKmNLkzjCEU5sbKJMi7hxYyTHjzR](https://polkadot.subscan.io/account/16UcV9V6nVvPYdHz98ymUKmNLkzjCEU5sbKJMi7hxYyTHjzR)
🔗 [0xfa6d1c4c1f4cc350feb093a52a4c02c6efd6b6c197cc8b6941faaf23065a47d2](https://polkadot.subscan.io/extrinsic/0xfa6d1c4c1f4cc350feb093a52a4c02c6efd6b6c197cc8b6941faaf23065a47d2)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
