### PR TITLE
format price on bsx

### LINKED ISSUE #3332: can we format bsx $ better?
Would it be possible to show only 2 decimals or hide it for bsx price numbers?

Capture d’écran 2022-07-05 à 9 15 20 AM

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3332
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
RMRK:
image

BSX: 
image

### CODE REVIEW

**Comment by Jarsen136** [comment]
Another solution is to modify the method `formatBalance` from `@polkadot/util`, but it's more of a hassle

**Review by roiLeo — COMMENTED** [review]
Looks nice, would it be possible to remove decimal from prices only if they end with ".00"?

**Comment by Jarsen136** [comment]
> Looks nice, would it be possible to remove decimal from prices only if they end with ".00"?

It's possible but I think the number format should be uniform on the same chain : )

**Comment by roiLeo** [comment]
What do you mean by 
> confuse about the decimals

I find it better from a design aspect & for more readability

here's some examples from different marketplace

Capture d’écran 2022-07-06 à 11 36 43 AM

Capture d’écran 2022-07-06 à 11 38 20 AM

Capture d’écran 2022-07-06 à 11 57 19 AM

Capture d’écran 2022-07-06 à 11 56 43 AM

**Comment by Jarsen136** [comment]
tested on `/bsx/gallery/2526524581-1`

before:  
image



after:    
image

**Review by roiLeo — APPROVED** [review]
way better now!
Capture d’écran 2022-07-06 à 4 53 15 PM

might need this for moonsama too (and maybe rmrk?)

✅ tested & lgtm

**Comment by Jarsen136** [comment]
> 
> might need this for moonsama too (and maybe rmrk?)

It's a shared component. It will work well in the same way on moonsama/rmrk/bsx.

**Comment by roiLeo** [comment]
> It's a shared component. It will work well in the same way on moonsama/rmrk/bsx.

`!isBsx` 👀

**Comment by Jarsen136** [comment]
> > It's a shared component. It will work well in the same way on moonsama/rmrk/bsx.
> 
> `!isBsx` 👀

Yeap, I just found out that. May need some extra work.

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 50.69 USD/KSM ~ 0.986 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x050ae6fe9712bbed7692a2abe206ba8633b10c543ef4286e41e521084d8f2ea6](https://kusama.subscan.io/extrinsic/0x050ae6fe9712bbed7692a2abe206ba8633b10c543ef4286e41e521084d8f2ea6)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
