### PR TITLE
feat(SearchBar): Show price range next to the filter

### LINKED ISSUE #2400: Show price range next to the filter
Show price range next to showing results 

Whenever the filter is folded, users don't see what price range is looking at.

image

image

### PR DESCRIPTION
**Pull request by zhengow**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2400 
- [x] Show price range next to the filter

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed sticky header in series and spotlight on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by yangwao** [comment]
hey, this issue should follow after this one https://github.com/kodadot/nft-gallery/pull/2398

if you can fetch changes from that PR into yours

**Comment by yangwao** [comment]
Hey @zhengow this doesn't seems to be fixed well 
image

**Comment by zhengow** [comment]
> 

I change the text position and now it looks like this:
image
plz review again.
btw, what device do u use to check? and what's the screen resolution？

**Comment by yangwao** [comment]
It should be next to the filter.
You've made it under filter. :)

It was made on desktop

**Comment by zhengow** [comment]
fix the postion to "next to"
now it looks like this:

https://user-images.githubusercontent.com/38389586/154815733-7a54dc18-4bf5-4fb4-8976-5c4873852c0e.mp4

plz review again :)

**Comment by yangwao** [comment]
okay let's go! :)

pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 138.87 USD/KSM ~ 0.72 $KSM
🧗 [EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws](https://kusama.subscan.io/account/EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)
🔗 [0x0ba82161c726d9d5cdca69fb032e85df969f216c1b89a06d57ecdacb75b31682](https://kusama.subscan.io/extrinsic/0x0ba82161c726d9d5cdca69fb032e85df969f216c1b89a06d57ecdacb75b31682)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
