### PR TITLE
🧪 vue-gtag-next plugin

### PR DESCRIPTION
**Pull request by roiLeo**
## Context

- [x] ref #4856

### CODE REVIEW

**Comment by vikiival** [comment]
@yangwao let's merge it and check if it works for beta

**Comment by roiLeo** [comment]
Meanwhile new package https://github.com/johannschopplich/nuxt-gtag

**Comment by yangwao** [comment]
> .env variables from netlify

`GOOGLE_ANALYTICS_ID` should be updated or changed ? 
I haven't been changing anything on netlify past 6 months maybe more.

**Comment by roiLeo** [comment]
> or maybe try use that one? if this one doesn't yield any data

Capture d’écran 2023-03-24 à 10 03 32 AM

**Comment by vikiival** [comment]
🥲🥲🥲

**Pull request merged**
