### PR TITLE
display long size image/nft

### LINKED ISSUE #2923: Find a way to display long size image/nft
Goto `/rmrk/gallery/9596440-800f8a914281765a7d-DREAMSCAPES-CHARON_OR_110-0000000000000001`

I'm not able to see the full size image because of ratio

#### screenshot
Capture d’écran 2022-04-29 à 4 37 00 PM

It should be something like this:

Capture d’écran 2022-04-29 à 4 39 02 PM

⚠️ This could be a breaking change

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2923 
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
regular
image

full screen: 
image

### CODE REVIEW

**Review by kkukelka — APPROVED** [review]
lgtm
only tested with /rmrk/gallery/9596440-800f8a914281765a7d-DREAMSCAPES-CHARON_OR_110-0000000000000001 though

could there be a problem with images that have more width than height? are they also centered?

**Comment by Jarsen136** [comment]
images that have more width than height also WFM
test case:   
https://deploy-preview-2925--koda-nuxt.netlify.app/rmrk/gallery/11163267-4a4c04c0029f17067c-INGQ1-LONG_NECKS_UNITED_TOWER_BANNER-0000000000000130

**Comment by kkukelka** [comment]
> images that have more width than height also WFM test case: https://deploy-preview-2925--koda-nuxt.netlify.app/rmrk/gallery/11163267-4a4c04c0029f17067c-INGQ1-LONG_NECKS_UNITED_TOWER_BANNER-0000000000000130

sweet!

pay 75

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $75 @ 146.73 USD/KSM ~ 0.511 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x3c2d18683d8c621d5f96c2c2d524c3cdd069ce46ba4582349cb3d920984ef8b5](https://kusama.subscan.io/extrinsic/0x3c2d18683d8c621d5f96c2c2d524c3cdd069ce46ba4582349cb3d920984ef8b5)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
