### PR TITLE
fix(profile): link to subscan on profile page

### LINKED ISSUE #1027: Fix component on profile redirecting you back to profile
When I'm at the profile and click on Sango Xango in the first row, 
it should redirect me to subscan, not back to profile
https://kodadot.xyz/rmrk/u/FZpjhYdt6fqRSzW1nR4fRejavcrSo7UXYP4TDhE3mgimgeC

image

### PR DESCRIPTION
**Pull request by roiLeo**
more like a hotfix

### PR type
- [x] Bugfix

### Before submitting this PR, please make sure:
- [x] Code builds clean without any errors or warnings
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've didn't break any original functionality

### What's new? (may be part of changelog)
- This PR closes #1027

### CODE REVIEW

**Comment by vikiival** [comment]
Screenshot 2021-11-05 at 12 44 19

**Review by vikiival — CHANGES_REQUESTED** [review]
Link routes internally.

**Comment by vikiival** [comment]
It is possible to open it on the new tab?

**Comment by yangwao** [comment]
works clicks

**Pull request merged**
