### PR TITLE
✨ enter key icon in search bar

### LINKED ISSUE #4387: Button in searchbar need some love
🥺

https://user-images.githubusercontent.com/5887929/203584387-8bce3773-932f-4561-8858-576aaafdb443.mp4

### PR DESCRIPTION
**Pull request by shashkovdanil**
## PR Type

Refactoring

## Context

Closes #4387 

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer?target=bXn3ExwLs8rpcpknp9wNqnNVgEYVLnTtFPDrJtaPHYds7Vfjv&usdamount=0&donation=true>)

## Screenshot 📸

image
image

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
Hey! Something strange happen on first click, could you take a look

https://user-images.githubusercontent.com/9987732/203721806-7d9a9cf0-aa62-4da6-8f21-21ce4b66171a.mov

**Comment by shashkovdanil** [comment]
Hey! I'll check

**Comment by shashkovdanil** [comment]
@roiLeo Screencast: https://monosnap.com/file/O8Lk1smhEP2V45XITZN2ZtsmeYrICc

**Review by roiLeo — COMMENTED** [review]
you could try to toggle visibility with `is-invisible` class

height on k-search-enter.svg is not the one defined (should be same height as the other one)
Capture d’écran 2022-11-24 à 1 48 55 PM

**Comment by shashkovdanil** [comment]
image

**Review by roiLeo — APPROVED** [review]
perfect! 

✅ code lgtm & wfm

**Comment by yangwao** [comment]
pay 30 usd

yesss

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 26.07 USD/KSM ~ 1.151 $KSM
🧗 [bXn3ExwLs8rpcpknp9wNqnNVgEYVLnTtFPDrJtaPHYds7Vfjv](https://kusama.subscan.io/account/bXn3ExwLs8rpcpknp9wNqnNVgEYVLnTtFPDrJtaPHYds7Vfjv)
🔗 [0x7c8cab07c4e3aa6f13e882fd5e9efbf7007a3f17367c67d1ea54bfe13a9f4624](https://kusama.subscan.io/extrinsic/0x7c8cab07c4e3aa6f13e882fd5e9efbf7007a3f17367c67d1ea54bfe13a9f4624)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
