### PR TITLE
Road to EVM

### PR DESCRIPTION
**Pull request by Jarsen136**

### CODE REVIEW

**Comment by vikiival** [comment]
image

**Comment by Jarsen136** [comment]
> image

same here https://github.com/kodadot/nft-gallery/pull/10322#issuecomment-2172608195

**Comment by Jarsen136** [comment]
image
need failed log again..

**Comment by preschian** [comment]
> need failed log again..

scary error I guess

Capture-2024-06-20-192428

**Comment by Jarsen136** [comment]
> > need failed log again..
> 
> scary error I guess
> 
> Capture-2024-06-20-192428

@hassnian Would you like to take a look at it?

**Comment by Jarsen136** [comment]
I have no idea why the build on Cloudflare would fail. 

It builds and deploys successfully with the same branch when I use my private account on Cloudflare.

image

**Pull request merged**
