### PR TITLE
feat: show who reacted to nft in gallery detail

### LINKED ISSUE #2917: see who reacted to nft even if you are not connected
When i haven't connected my wallet, I can't see who has reacted to the nft
I would like to be able to access user's profile who sent an emote

Is this done on purpose?

#### Screenshot
Capture d’écran 2022-04-29 à 8 32 04 AM

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2917 
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

### CODE REVIEW

**Comment by roiLeo** [comment]
> I found that there are two solutions:
> 
> 1. show the person who reacted to nft when hover the button.
> 
> 2. show "details" button forever if there is someone reacted to nft.

I was looking for n°2 button but your hover solution is nice too

**Review by vikiival — CHANGES_REQUESTED** [review]
Waiting for second version of implementation

**Comment by Jarsen136** [comment]
Now I keep both of them 🚶‍♂️

**Comment by vikiival** [comment]
As I read the issue it would be also nice to fix this


Screenshot 2022-04-29 at 19 04 08

I clicked on the emote and I have not been connected

**Comment by Jarsen136** [comment]
Now it can show a warning toast instead of show `error` toast.

image

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
Awesome

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 131.27 USD/KSM ~ 0.762 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x21ae942678feaa5b74125be316da1097e1f7da9740bf9a04bd9d64f84175449d](https://kusama.subscan.io/extrinsic/0x21ae942678feaa5b74125be316da1097e1f7da9740bf9a04bd9d64f84175449d)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by vikiival** [comment]
Thanks @yangwao! I forgot to make a payout, my mistake

**Pull request merged**
