### PR TITLE
Nft Interaction History

### LINKED ISSUE #570: NFT Interaction history
**Is your feature request related to a problem? Please describe.**
As user I would like to see the interactions  in the NFT detail

**Describe the solution you'd like**
Simple accordion card under the share card in NFT detail

**Additional context**
there is field for that called interactions in the graphQL.

So task is simple:
- [ ] have a table with following columns -> Type From To Amount Date
- [ ] extend the graphql query with the interaction field
- [ ] show :)

In case of any question feel free to hit me up on Discord/ Telegram/ Twitter.

### PR DESCRIPTION
**Pull request by pandasamanvaya**
**Thank you for your contribution** to the KodaDot NFT gallery.
Let's do a quick check before the merge.
Your contribution will be an eternal part of the community codebase.

### Before submitting this PR, please make sure:
- [x] Code builds clean without any errors or warnings
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I didn't break any original functionality

### Optional
- [x] I've tested it on mobile and everything works

### PR type
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new? (maybe part of changelog)
- closes #570
Extracted the events property from nft object and created a table from its fields.

### If issue contains bounty label ($,$$,$$$)
- Your KSM address: <Kusama_address>

### Community participation
- [x] Are you at KodaDot Discord? If no, [let's join us - https://discord.gg/35hzy2dXXh](https://discord.gg/35hzy2dXXh)

### Screenshot
- [x] Whenever your fix will change **something** on UI, a screenshot is more than welcome

### CODE REVIEW

**Comment by pandasamanvaya** [comment]
For large-screens:-
Screenshot from 2021-07-16 21-44-26

For smaller-screens:-
Screenshot from 2021-07-16 21-44-04

**Comment by yangwao** [comment]
I would change order, newest on the top?
Screenshot_2021-07-16-18-31-04-013_com android chrome

**Comment by vikiival** [comment]
Hey,
the app looks awesome! Just small things:

Can we get rid of `NA...NA` ? 
Screenshot 2021-07-20 at 15 15 14

Is it possible to make date like `19 Jul 2021 21:56:48 GMT`?
Screenshot 2021-07-20 at 15 15 18

**Comment by pandasamanvaya** [comment]
Now the table looks something like this
Screenshot from 2021-07-20 19-57-48

**Pull request merged**
