### PR TITLE
fix: sanitize ipfs url

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Fix sanitize ipfs url

#### Had issue bounty label?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 53dd63e</samp>

This pull request improves the IPFS handling and sanitization in the project by using the `is-ipfs` library, adding new helper functions, replacing the IPFS gateway, and removing the `cache-control` header. It also updates the `pnpm-lock.yaml` file and adds a test case for the IPFS utils.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 53dd63e</samp>

> _`is-ipfs` helps_
> _validate and check IPFS_
> _better sanitization_

### CODE REVIEW

**Comment by vikiival** [comment]
Why not use `minipfs` + `hyperdata`? Having 3 different implemntations (squids, workers, nft-gallery) is not a good way :)

**Comment by preschian** [comment]
> Why not use `minipfs` + `hyperdata`? Having 3 different implemntations (squids, workers, nft-gallery) is not a good way :)

My bad, this does make sense. I always forget that we already have minipfs (and another lib under packages repo) 🤣🙏🏻

**Comment by vikiival** [comment]
>  I always forget that we already have minipfs

Do not worry. I learned that hard way when I was copying same files over indexers ;D

**Comment by vikiival** [comment]
Screenshot 2023-12-14 at 12 40 42


Hey I has been 10 days since last commit, for the sake of cleaner repository I will close this PR. Please open a new PR with  `minipfs` + `hyperdata`?

**Comment by preschian** [comment]
@vikiival continue in #8688

**Pull request closed without merging**
