### PR TITLE
#2062 typos/grammar

### LINKED ISSUE #2062: Typos / Grammar fix in .md docs
### What happened?

found few typos / grammar issues when reading through docs here

### Please reproduce in steps

mainly CONTRIBUTIONS.md but some in Readme.md as well

### Expected Behavior

fixed the obvious things, perhaps further proofreading / copywriting could be useful to make repo look more appealing for new devs

### What browsers are you seeing the problem on?

Chrome

### Are you logged in?

No

### At which address did you encounter bug?

nft.kodadot.xyz / kodadot.xyz

### Screenshots

example
image

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by petersopko**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Do a quick check before the merge.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #2062
- [x] Few grammar fixes in markdown docs, eslint seemed to have some kind of problem with couple of .md signs such as # and I couldn't find a simple workaround except for ignoring eslint. Hopefully this is okay. As @yangwao commented, this PR is related to #1870 I've looked for some way to connect these PRs but haven't found it (sorry, mainly used GitLab up to this point). 

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings** <- eslint mentioned above
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases

### Had issue bounty label ?

- [ ] Fill up your KSM address: just minor grammar fixes + some lessons along the way
### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI, a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]

**Comment by yangwao** [comment]
in the top right you can easily checkout PR and commit changes with that 
image

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
ah no address :| that's why it has failed :D umm

**Comment by petersopko** [comment]
> ah no address :| that's why it has failed :D umm

Fixed it 👨‍💻😅

**Pull request merged**
