### PR TITLE
#9684 button styling

### LINKED ISSUE #9684: Button styling
as far as i am aware, these buttons are on more places than just drop page nfts 

image

the correct hover should be 
image

as in: https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=5311-18771&mode=design&t=H89BpYMt5hwXu1XH-11

task: find and replace all incorrect button states for this component

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #9684

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)

## Screenshot 📸

- [x] My fix has changed UI

Screenshot 2024-03-13 at 9 20 36 PM

### CODE REVIEW

**Comment by exezbcz** [comment]
sort by on profile now has different styling 
image

**Comment by prachi00** [comment]
> any progress?

@exezbcz fixed , sorry about the delay

**Comment by exezbcz** [comment]
> task: find and replace all incorrect button states for this component



the states are correct, could you please now replace all the button with the correct component as mentioned in the issue? 
image

profile: 
image

image


cart: 
image
(here, can you please replace it with the same height as we have in the profile?)

**Comment by prachi00** [comment]
@exezbcz height for what? explore nfts button? it seems to be same 24px

**Comment by prachi00** [comment]
@exezbcz is it okay now? I increased the height of the create on chain button

**Review by exezbcz — APPROVED** [review]

**Comment by exezbcz** [comment]
works for me, thank you!

**Review by Jarsen136 — APPROVED** [review]

**Comment by yangwao** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 9.38 USD/DOT ~ 2.132 $DOT
🧗 [13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1](https://polkadot.subscan.io/account/13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)
🔗 [0xa4067d08d782804dade4c4b2e180c12ebab0da69c9c2af6a5cf93e2028b38980](https://polkadot.subscan.io/extrinsic/0xa4067d08d782804dade4c4b2e180c12ebab0da69c9c2af6a5cf93e2028b38980)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
