### PR TITLE
New placeholder while NFT is loading

### PR DESCRIPTION
**Pull request by vikiival**
Thank you for your contribution to the KodaDot NFT gallery.

### Before submitting this PR, please make sure:
- [x] Your code builds clean without any erros or warnigns
- [x] You've posted screenshot of demonstrated change in this PR
- [x] Merged recent default branch, **main** and you have no conflicts
- [x] Didn't break any original functionality 

### Optional
- [ ] You've tested it on mobile

### PR type
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### CODE REVIEW

**Comment by roiLeo** [comment]
Does it look good on Gallery ?

**Comment by vikiival** [comment]
It’s only in gallery detail

**Comment by yangwao** [comment]
👀🥨
image

**Comment by yangwao** [comment]
What about this 👀

**Comment by yangwao** [comment]
I guess, maybe @roiLeo can look at that, I'm happy to test it one more time to have it there for bigger assets would be definitely great than the boring K logo 😄

**Comment by yangwao** [comment]
works 
image

**Pull request merged**
