### PR TITLE
✨ burn collection with items

### LINKED ISSUE #3206: Add possibility to remove collection
Currently, empty collections don't show up in the explorer. However, in order to delete a collection (`destroy class` from the initial implementation requirements, ref. #660) it must be empty.

Catch 22 with collections, I'm thinking, adding option to show user his/her empty collections and add option to delete them. This could be done under profile tab Collections with simple checkbox such as `Show empty collections`

/edit with @roiLeo idea:

can't we create a /bsx/admin like for rmrk? Is this page used for that kind of stuff?

### PR DESCRIPTION
**Pull request by roiLeo**
This feature allow to Burn collection on bsx chain

## PR Type

- [x] Feature

## Context

- [x] Closes #3206 

## TODO

- [ ] #3584 

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [x] I've tested it at `/snek/collection/1631038496`
- [x] I've found edge cases: BSX testnet (Rococo) outdated?

#### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

### CODE REVIEW

**Review by Jarsen136 — APPROVED** [review]
code lgtm

**Comment by Jarsen136** [comment]
>  I've tested it at /snek/collection/1631038496

I could see that the collection is still there, instead of being burned. I guess it should be burned, right?
https://deploy-preview-4546--koda-nuxt.netlify.app/snek/collection/1631038496

image

**Comment by roiLeo** [comment]
> > I've tested it at /snek/collection/1631038496
> 
> I could see that the collection is still there, instead of being burned. I guess it should be burned, right? https://deploy-preview-4546--koda-nuxt.netlify.app/snek/collection/1631038496

IMO something wrong with Rococo, looks like the chain is frozen but I received the success msg.

#3992 related

**Comment by roiLeo** [comment]
```gql
query MyQuery {
  collectionEntityById(id: "1631038496") {
    id
    name
    burned
    createdAt
    currentOwner
    nftCount
    nfts {
      id
      name
      burned
      blockNumber
    }
  }
}
```

### result

```json
{
  "data": {
    "collectionEntityById": {
      "id": "1631038496",
      "name": "🕊 Kusama",
      "burned": true,
      "createdAt": "2022-09-21T09:36:00.141000Z",
      "currentOwner": "bXhWeVLtArWauM8UmbaVdDmXmo5uSDk6DAa2YxQ5zbt2sDcbW",
      "nftCount": 2,
      "nfts": [
        {
          "id": "1631038496-1",
          "name": "[TEST] BURN †",
          "burned": true,
          "blockNumber": "857590"
        },
        {
          "id": "1631038496-2",
          "name": "SUCCESS",
          "burned": true,
          "blockNumber": "1098515"
        }
      ]
    }
  }
}
```

**Comment by yangwao** [comment]
If it's working, let's merge it

**Comment by yangwao** [comment]
pay 50 usd

**Comment by vikiival** [comment]
@yangwao maybe bot is out of funds ?

**Pull request merged**
