### PR TITLE
perf: Graphql CDN using Stellate

### PR DESCRIPTION
**Pull request by preschian**
Hi @kodadot/internal-dev. Would you like to try Stellate for our GraphQL endpoint? In a simple comparison, it appears to be faster. This could help us if we get a large number of visitors at the same time. Perhaps if the number of visitors is not too high, the effect might not be too noticeable. For now, I’ve set the cache on this endpoint to last for 60 seconds.

| Before | After |
|---|---|
| Screenshot 2023-10-12 152306 | Screenshot 2023-10-12 152243 |
| https://canary.kodadot.xyz/ahk/collection/150 | https://deploy-preview-7623--koda-canary.netlify.app/ahk/collection/150 |

https://stellate.co/docs/graphql-edge-cache/cache-rules
```js
// cache rules

rules: [
  {
    types: [
      'NFTEntity',
      'NFTEntitiesConnection',
      'CollectionEntity',
      'CollectionEntitiesConnection',
      'Event',
      'EventEntity',
      'LastEventEntity'
    ],
    maxAge: 60,
    swr: 600,
    description: 'Cache some types',
  },
],
```

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Related: https://github.com/kodadot/nft-gallery/issues/2743
- [x] Related: https://github.com/kodadot/nft-gallery/issues/4657

#### Had issue bounty label?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)

### <samp>🤖 Generated by Copilot at 45af347</samp>

This pull request adds support for the new Stellate indexers, which are a different kind of Subsquid indexer for the NFT gallery. It updates the `indexers.ts` and `constants.ts` files to handle both Stellate and Squid indexers and use the appropriate one for each network.

### <samp>🤖 Generated by Copilot at 45af347</samp>

> _`SquidEndpoint` changes_
> _Stellate indexers join in_
> _Autumn of networks_

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
How does it work? does it only cache data?
Will we need it for all indexers? wouldn't we have a problem on the billing?
Do you have acces at some sort of backend dashboard?

**Comment by preschian** [comment]
> How does it work? does it only cache data?

It wraps the subsquid endpoint with stellate

```
before:
user -> https://squid.subsquid.io/stick/graphql

after:
user -> https://query-stick.stellate.sh/ -> cache miss -> https://squid.subsquid.io/stick/graphql
user -> https://query-stick.stellate.sh/ -> cache hit -> return the cache response
```

> Will we need it for all indexers? wouldn't we have a problem on the billing?

for testing maybe we can test with one endpoint first? they have a free plan with unlimited requests. the limitation is only working on 2 endpoints, and need to put their badge

- https://stellate.co/pricing
- https://stellate.co/docs/platform/adding-powered-by-stellate-badge

> Do you have acces at some sort of backend dashboard?

I just created the account by myself. what we need only subsquid endpoint to use stellate

**Comment by Jarsen136** [comment]
Caching graphql is a good idea, but I also have some concerns.

- I wonder if it supports bypassing the cache. For example, if a user buy a nft we need to fetch the latest information instead of cache.

- Is it compatible with the current real-time subscription feature `useSubscriptionGraphql`? I'm afraid the cache would affect it.

**Comment by preschian** [comment]
> Caching graphql is a good idea, but I also have some concerns.
> 
> * I wonder if it supports bypassing the cache. For example, if a user buy a nft we need to fetch the latest information as fast as possible instead of cache.
> * Is it compatible with the current real-time subscription feature `useSubscriptionGraphql`? I'm afraid the cache would affect it.

we can use custom header to bypass the cache https://stellate.co/docs/graphql-edge-cache/bypass-the-cache

or, not putting all Types in the cache. currently in the rules I put 

```js
[
  'NFTEntity',
  'NFTEntitiesConnection',
  'CollectionEntity',
  'CollectionEntitiesConnection',
  'Event',
  'EventEntity',
  'LastEventEntity',
]
```

**Comment by yangwao** [comment]
Ah GraphCDN => Stellate?

We've been considering this one in the past.

**Comment by preschian** [comment]
For the subscription query, what if we fallback to the subsquid endpoint? like this c01503c20eed8db3b2dc55266c1bba17c4551f8b



> Ah GraphCDN => Stellate?
> 
> We've been considering this one in the past.

yes, cdn for graphql

**Comment by vikiival** [comment]
So looking forward to hear opinion from @kodadot/internal-dev about using stellate.

> unfortunately, we need to adjust the subscription over HTTP instead of WS

We can fallback to the sqd endpoint. 
the point why we use WebSocket on some parts of the app is the reason that we need fresh data.

But I would be happy to try it on AssetHubs (2 endpoints) and if we would see potential benefit we can scale from there.

**Comment by roiLeo** [comment]
> So looking forward to hear opinion from @kodadot/internal-dev about using stellate.

meh.. I have no opinion

> But I would be happy to try it on AssetHubs (2 endpoints) and if we would see potential benefit we can scale from there.

yes we could try that first

**Comment by preschian** [comment]
lets try it then? @vikiival 
added Stellate badge in the footer

image

**Comment by vikiival** [comment]
> added Stellate badge in the footer

Shouldn't be the badge in the readme?

**Review by vikiival — APPROVED** [review]

**Comment by yangwao** [comment]
Thanks!
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 4.58 USD/DOT ~ 10.917 $DOT
🧗 [1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p](https://polkadot.subscan.io/account/1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)
🔗 [0x3a9f96740a41ae5e790748c4f0b85d17e381cf7562d08bb4aa24e3880fd72967](https://polkadot.subscan.io/extrinsic/0x3a9f96740a41ae5e790748c4f0b85d17e381cf7562d08bb4aa24e3880fd72967)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
looking for improvement. 
300ms cut seems fair, might improve the lighthouse?

**Comment by preschian** [comment]
> might improve the lighthouse?

It is probably not significant since I only set the cache to 60 seconds
but if the LCP in some page rely on graphql request, we can test to set a longer cache on that

**Comment by vikiival** [comment]
> but if the LCP in some page rely on graphql request,

90% of landing 🥹

**Comment by preschian** [comment]
> 90% of landing 🥹

aahh, I see. let me check

**Comment by preschian** [comment]
After some checking, our FCP is currently a bit high. Currently, adjustment on LCP will not give significant results. We need to reduce the javascript size on the client

image

SSR or reducing unused JS in the pages could be helpful in this case, I guess 

image

**Comment by roiLeo** [comment]
> SSR or reducing unused JS in the pages could be helpful in this case, I guess

feel free to test on #7725

**Comment by preschian** [comment]
> > SSR or reducing unused JS in the pages could be helpful in this case, I guess
> 
> feel free to test on #7725

checking 👍

**Comment by preschian** [comment]
confirmed, with SSR from #7725 looks better

FCP from 9xx ms -> 6xx ms
Unused JS 3.2 MB -> 2.5 MB

this will help us to increase the scores

image

**Pull request merged**
