### PR TITLE
#7762 tags

### LINKED ISSUE #7762: Stretched out tags
image
should have fixed height of 22px

as in collection activity tags
https://www.figma.com/file/7BWdGiowrvTucpSFLE0kRX/Collection-detail-handoff?type=design&node-id=0%3A1&mode=design&t=YjqA76a9wr4zt7ok-1

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #7762
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)

## Screenshot 📸

- [x] My fix has changed UI
Screen Shot 2023-10-22 at 3 33 31 PM

### CODE REVIEW

**Comment by daiagi** [comment]
why is css from `SignupBanner` bleeding out and affecting other components?

**Comment by prachi00** [comment]
> 1. fixed-height  in SingupBanner does not need to be !important
> 2. worse, why is css from `SignupBanner` bleeding out and affecting other components?
> 
> image
> 
> that's why

fixed, nice catch thank you

**Review by daiagi — APPROVED** [review]

**Review by preschian — APPROVED** [review]

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
pay 10 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $10 @ 4.18 USD/DOT ~ 2.392 $DOT
🧗 [13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1](https://polkadot.subscan.io/account/13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)
🔗 [0x36519ae7c254d520a0350777c2478f66500eb1d8d14aec9178f1f50d75a80e7a](https://polkadot.subscan.io/extrinsic/0x36519ae7c254d520a0350777c2478f66500eb1d8d14aec9178f1f50d75a80e7a)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
