### PR TITLE
#2261-search-unification

### LINKED ISSUE #2261: Unite search experience in Collections with Gallery
### Is your feature request related to a problem?

When you try search in "Collections" you are getting realtime results with loading progress while you typing.
It's messy and not much user friendly.
Screenshot 2022-02-07 at 12 22 51

### Describe the solution you would like

It will be nice to implement same search experience that is used in "Gallery".

Screenshot 2022-02-07 at 12 23 22

### PR DESCRIPTION
**Pull request by petersopko**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #2261
- [x] What has changed:
- search is now done from one file and it's done the same way for gallery and collections
- kept searchbar only in search section when it comes to Gallery/Collections (since search recommendations is now split into categories)
- added headers for Gallery/Collections since it now looks way too similiar
- fixed design issues

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image
image

### CODE REVIEW

**Comment by petersopko** [comment]
this can be done before mentioned resolver is written for recently listed(not attempting to do that myself for now) https://github.com/kodadot/nft-gallery/issues/842
image

**Comment by yangwao** [comment]
The search bar should be kept in the navbar as it's on `main` now :)

As still, we haven't thought what merger of explore+collections feed would look like I'm open to new ideas and sense this is the time

Probably closest to the easiness of browsing, rarible has answer https://rarible.com/search/collections/kusama and there would not be a need to show what you are looking at as it eats lot's of vertical space and not a contextual primer

i.e. we can still make one wrapping view on the top of the gallery and collections, wyt?

**Comment by petersopko** [comment]
> The search bar should be kept in the navbar as it's on `main` now :)
> 

okay, I'll revert it to the state it was in, as was planned in https://github.com/kodadot/nft-gallery/pull/2430

> As still, we haven't thought what merger of explore+collections feed would look like I'm open to new ideas and sense this is the time 

> Probably closest to the easiness of browsing, rarible has answer https://rarible.com/search/collections/kusama and there would not be a need to show what you are looking at as it eats lot's of vertical space and not a contextual primer


Maybe we could merge the Gallery + Collections under one tab in the navbar (Explore) and have it separated by tabs within the search section? 

image

> i.e. we can still make one wrapping view on the top of the gallery and collections, wyt?

**Comment by yangwao** [comment]
> Maybe we could merge the Gallery + Collections under one tab in the navbar (Explore) and have it separated by tabs within the search section? Is that what you're thinking? I think it would simplify both the user experience and app architecture.

yes! 😇 let's try. 
Originally collection has started as a way to have a dedicated way for collections but I guess it requires more work than I anticipated so let's stick with a unified experience probably once we have search working well where it highlights collections :)

**Comment by petersopko** [comment]
> > Maybe we could merge the Gallery + Collections under one tab in the navbar (Explore) and have it separated by tabs within the search section? Is that what you're thinking? I think it would simplify both the user experience and app architecture.
> 
> yes! 😇 let's try. Originally collection has started as a way to have a dedicated way for collections but I guess it requires more work than I anticipated so let's stick with a unified experience probably once we have search working well where it highlights collections :)

Since this task expanded quite a bit, I'm going to close this and re-open with your comments and tabs worked in to avoid merge conflicts and stalling.

**Pull request closed without merging**
