### PR TITLE
🌞 identitypopover, footer, card, box, carousel, wallet btn, chart axis fix

### PR DESCRIPTION
**Pull request by roiLeo**
### PR type

- [x] Bugfix

### What's new?

- [x] PR related with #3713 
- [x] identitypopover, footer, card, box, carousel, wallet btn, chart axis light mode fix

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Screenshot

<details>
  <summary>Before</summary>
  
Capture d’écran 2022-08-15 à 1 32 45 PM

</details>

<details>
  <summary>After</summary>
  
Capture d’écran 2022-08-15 à 1 33 38 PM

</details>

### CODE REVIEW

**Comment by yangwao** [comment]
works! 



image

**Comment by yangwao** [comment]
j'ai découvert un bug

image

**Comment by yangwao** [comment]
J'ai trouvé une erreur dans le tableau
like x-axis 👀

image

**Comment by roiLeo** [comment]
> j'ai découvert un bug
> 
> image

barva tlačítek je opravena

> J'ai trouvé une erreur dans le tableau like x-axis & y-axis 👀

This one won't be easy since x-axis y-axis text color are defined before canvas rendering

possible solution for now: find a color that work on both (could be primary pink)

**Comment by roiLeo** [comment]
> possible solution for now: find a color that work on both (could be primary pink)

Screenshot 2022-08-15 at 16-11-03 KodaDot KodaDot - Kusama NFT Market Explorer
Screenshot 2022-08-15 at 16-11-24 KodaDot KodaDot - Kusama NFT Market Explorer

**Comment by yangwao** [comment]
> possible solution for now: find a color that work on both (could be primary pink)

ship it

**Comment by yangwao** [comment]
https://user-images.githubusercontent.com/5887929/184652238-f112ead5-3046-4236-9407-bcf299ed6675.mov

**Pull request merged**
