### PR TITLE
address input mismatch in bsx

### LINKED ISSUE #3656: Can't send/Gift NFTs
### What happened?

Trying to gift it, but appear " prefix mistake, i only copy and paste the  bsx adress from the extensión "

### Please reproduce in steps

Send Gift - paste the adress

### Expected Behavior

Send the gift without problem 

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

Talisman

### Screenshots

Screenshot_88

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3656
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by yangwao** [comment]
[jrafaelangarita](https://github.com/jrafaelangarita) you can try [deploy-preview-3662--koda-nuxt.netlify.app](https://deploy-preview-3662--koda-nuxt.netlify.app/) :)

**Comment by vikiival** [comment]
This basically turns off the check ;D

**Comment by Jarsen136** [comment]
> This basically turns off the check ;D

Yup, because the check is for ksm address only.
image

**Comment by jrafaelangarita** [comment]
> [jrafaelangarita](https://github.com/jrafaelangarita) you can try [deploy-preview-3662--koda-nuxt.netlify.app](https://deploy-preview-3662--koda-nuxt.netlify.app/) :)

 i cant try withou a nft on the account for send jajaj, but if you can, try to put with bsx adress and with other different ones, like ksm, acala adress for see how work

**Comment by vikiival** [comment]
Fixed in #3683

**Pull request closed without merging**
