### PR TITLE
New GraphQL routes

### LINKED ISSUE #3813: Deorbitting rubick-005 & rubick-006
As stated here

- https://github.com/kodadot/nft-gallery/issues/3808

we will be turning off 005 & 006 

Check if everything works without 006 

https://github.com/kodadot/nft-gallery/blob/3cfbd90799ace8e40af11f24899570ff5017aaff/utils/constants.ts#L34

- https://github.com/kodadot/nft-gallery/pull/3884

### PR DESCRIPTION
**Pull request by vikiival**
## What is new?

- Subsquid changed the routes on the Dashbord so we should do the same to avoid future bugs
- Added new FireSquid EVM indexer kodadot/click#26

- :zap: new SubSquid routes
- :construction: removed deprecated indexers
- :truck: renamed subsquidv6 to rubick
- :top: updated grapgql config

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

- PR closes #3813 
- Check if everything works without 006, look for ✅ at tests

### PR type

- [ ] Bugfix
- [x] Feature
- [x] Refactoring

### Why DRAFT?

30.08.2022, indexer has only 23%
Screenshot 2022-08-30 at 17 14 25

### CODE REVIEW

**Comment by vikiival** [comment]
Screenshot 2022-08-31 at 16 17 10

**Comment by roiLeo** [comment]
ping #1492

**Comment by yangwao** [comment]
Seems explorer failing? https://github.com/kodadot/nft-gallery/runs/8133153114?check_suite_focus=true#step:10:111

**Comment by petersopko** [comment]
> Seems explorer failing? https://github.com/kodadot/nft-gallery/runs/8133153114?check_suite_focus=true#step:10:111

not just explorer I think /bsx in general, this is at /offers:
image

**Comment by petersopko** [comment]
/snek tests are OK now, I wonder whether we should temporarily disable/skip `media.cy.ts` until we figure out a way in which this can run without failing every other PR, it seems that it's in this hit or miss state currently @preschian 👀 
- #3812
image

**Comment by preschian** [comment]
> /snek tests are OK now, I wonder whether we should temporarily disable/skip `media.cy.ts` until we figure out a way in which this can run without failing every other PR, it seems that it's in this hit or miss state currently @preschian 👀

yes, I agree if we want to skip it temporarily. I think we need to revisit `media.cy.ts`. seems the root cause is still the same `429` errors

**Pull request merged**
