### PR TITLE
🔧 wallet ProfileAssetsList

### LINKED ISSUE #5080: wrong equivalent in BSX-USD
### What happened?

I see wrong equivalent of usd to my BSX availlable in account.

### Please reproduce in steps

Wallet-asset

### Expected Behavior

I think it should show correct USD equivalent

### What browsers are you seeing the problem on?

Desktop Firefox

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### At which chain did you encounter bug?

Basilisk

### Screenshots

Знімок екрана 2023-02-21 о 15 51 42
Знімок екрана 2023-02-21 о 15 36 02

### Relevant log output

_No response_

### Payment link for reward

FS59f9ermK48dPhwg6eG1Af77bN8bd7vuEYrowJf5VL9PAp

KSM adress

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by roiLeo**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Context

- [x] Closes #5080 

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

## Screenshot 📸

**before**
Screenshot 2023-02-22 at 15-19-30 KodaDot - NFT Market Explorer

**after**
Screenshot 2023-02-22 at 15-16-34 KodaDot - NFT Market Explorer

### CODE REVIEW

**Comment by yangwao** [comment]
now you're not rich anymore 🙄

**Comment by exezbcz** [comment]
can the usd amounts also be aligned to right? so the total count is in line with the amounts above? :D

**Comment by roiLeo** [comment]
> can the usd amounts also be aligned to right? so the total count is in line with the amounts above? :D

I would suggest to align every numbers in this table to the right, wdyt?

**Comment by exezbcz** [comment]
@roiLeo 
yes
image

**Review by vikiival — APPROVED** [review]
Some magic. YOLO

**Pull request merged**
