### PR TITLE
Update 🇷🇺Russian translation in KodaDot

### PR DESCRIPTION
**Pull request by jakartinho**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [ ] PR closes #<issue_number>
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EaCNjunMHRRPZfzGCX66dbZcwrZsRZBBVu4YzBU58t1TwwG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by spacesmutje** [comment]
i assume we run into the same issues here, that we faced in my translation @petersopko

**Comment by kkukelka** [comment]
we need to find some way to encode cyrillic characters
```
You may need an additional loader to handle the result of these loaders.
  SyntaxError: Unexpected string in JSON at position 34455 while parsing '{
  "translation": "Русский",
```

**Comment by petersopko** [comment]
> we need to find some way to encode cyrillic characters

just invalid json with curly brackets misplaced

**Review by kkukelka — APPROVED** [review]
@petersopko ah sweet. code-lgtm, can't say much about the validity of the translations

**Comment by petersopko** [comment]
@jakartinho do you know anybody else who speaks the language and can also verify some of this? 😄

**Comment by jakartinho** [comment]
> @jakartinho do you know anybody else who speaks the language and can also verify some of this? 😄 

I'll try to find it :)

**Review by petersopko — COMMENTED** [review]
waiting for review from somebody who has required language skills here

**Comment by jakartinho** [comment]
> has 

I found a man, he will check today and report back here.

**Comment by Black322** [comment]
Greetings! Jakartinho asked me to check for grammatical and syntactical mistakes. I declare that after checking the translation, no mistakes were found. It is a high-quality translation.

**Comment by jakartinho** [comment]
> Greetings! Jakartinho asked me to check for grammatical and syntactical mistakes. I declare that after checking the translation, no mistakes were found. It is a high-quality translation.

Thanks, buddy! 

@petersopko Done, the work has been checked!

**Review by petersopko — APPROVED** [review]

**Comment by petersopko** [comment]
pay 100 usd

**Comment by petersopko** [comment]
> pay 100 usd

looks like this payment didn't happen? gonna try again

**Comment by petersopko** [comment]
pay 100 usd

**Comment by petersopko** [comment]
not sure what kind of problem is here, @yangwao pls check

**Comment by jakartinho** [comment]
> > pay 100 usd
> 
> 
> 
> looks like this payment didn't happen? gonna try again

Hi, maybe I filled something wrong. Here's my wallet, last time someone added it as well.


EaCNjunMHRRPZfzGCX66dbZcwrZsRZBBVu4YzBU58t1TwwG

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 43.36 USD/KSM ~ 2.306 $KSM
🧗 [EaCNjunMHRRPZfzGCX66dbZcwrZsRZBBVu4YzBU58t1TwwG](https://kusama.subscan.io/account/EaCNjunMHRRPZfzGCX66dbZcwrZsRZBBVu4YzBU58t1TwwG)
🔗 [0x0462209a8cbd3be3817fa40ae956f9956e0a89b78b522635f46814a70aa6affb](https://kusama.subscan.io/extrinsic/0x0462209a8cbd3be3817fa40ae956f9956e0a89b78b522635f46814a70aa6affb)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
autocode had some outage, those webhooks doesn't pick up tho later on so, not perfect, not terrible

**Pull request merged**
