### PR TITLE
Vietnamese translation KodaDot

### PR DESCRIPTION
**Pull request by harrymoneyy**

### CODE REVIEW

**Comment by yangwao** [comment]
Seems dope! Perfect, mergin.

**Comment by yangwao** [comment]
Don't forget post your KSM address to this PR!

**Comment by harrymoneyy** [comment]
GZpaSnA8kmwriepqPDAv6w4RA5huToUfPZuMqvVVq9z5ZzC

**Comment by harrymoneyy** [comment]
Many thanks my mate.

**Pull request merged**
