### PR TITLE
fix: Art shortcuts are not working in fullscreen mode

### LINKED ISSUE #10082: Art shortcuts are not working in fullscreen mode
This art has a schortcut: when you click on art and then click A the art will start to move. It doesn't work in fullscreen mode. I tried it in code-checker.

[Unfoldings.v1_9.zip](https://github.com/kodadot/nft-gallery/files/14994217/Unfoldings.v1_9.zip)

https://github.com/kodadot/nft-gallery/assets/104380776/6082ccfc-7a1e-428b-bf7c-6cb94ead7031

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs QA check

- @kodadot/qa-guild please review
@JustLuuuu 
## Context

- [x] Closes #10082

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [ ] My fix has changed UI

### CODE REVIEW

**Comment by prury-temporary** [comment]
just checking, but here, it only works if i click on the image and then press the shortcut
how can we make sure that when art appears on gallery item, i can press the shortcut without having to click on the image?

**Comment by Jarsen136** [comment]
> just checking, but here it only works if i click on the image and then press the shortcut 
It works when it enters fullscreen mode without clicking the nft. That's what the original issue mentioned.

> how can we make sure that when art appears on gallery item, i can press the shortcut without having to click on the image?

The nft should be focused by click, then the shortcut would work. It makes no sense to keep the nft focus all the time while browsing the gallery item page.

**Comment by Jarsen136** [comment]
> > The nft should be focused by click, then the shortcut would work. It makes no sense to keep the nft focus all the time while browsing the gallery item page.
> 
> if this is the case, wouldn't we also want to **not have it focused** after you leave `fullscreen` mode ?

it does not bring anything bad to keep the same focused status immediately after leaving fullscreen mode. That's why I keep it. Do you prefer to change it?

**Comment by hassnian** [comment]
@Jarsen136 

> Do you prefer to change it?

don't have a preference tbh , but  to me it's just odd you can press `A` after fullscreen and the shortcut works but before fullscreen mode you have to click , I'd would have it either always without clicking or not have that shortcut after the fullscreen mode is ended

[from](https://github.com/kodadot/nft-gallery/issues/10117#issue-2256100737)

> Bacuse also animations are not working (click on picture + press A to start the animation)

should also work inside `/gallery` ?

**Comment by JustLuuuu** [comment]
I don't know how to open the code-checker with a deployed link. Sorry I cannot test 😅

**Comment by Jarsen136** [comment]
> @Jarsen136
> 
> > Do you prefer to change it?
> 
> don't have a preference tbh , but to me it's just odd you can press `A` after fullscreen and the shortcut works but before fullscreen mode you have to click , I'd would have it either always without clicking or not have that shortcut after the fullscreen mode is ended
> 
> from #10117

Okay, I have made it. The shortcut would not keep working after exiting full screen.

> 
> > Bacuse also animations are not working (click on picture + press A to start the animation)
> 
> seems this should this also work inside `/gallery`. can you add it ?

Yes, I added it.

**Comment by Jarsen136** [comment]
> I don't know how to open the code-checker with a deployed link. Sorry I cannot test 😅

Just wait a few minutes for it to deploy. Then there will be a test link.

**Comment by hassnian** [comment]
@Jarsen136 what about something like 

`useMediaFullscreen({ ref, isFullscreen })` 

and put watch inside

**Comment by JustLuuuu** [comment]
looks like its working, just my full-screen mode is not really fullscreen:
Screenshot 2024-04-23 at 13 51 50

**Review by hassnian — APPROVED** [review]

**Comment by Jarsen136** [comment]
> looks like its working, just my full-screen mode is not really fullscreen: 

It's because this art is not responsive enough for different screen sizes.

**Comment by JustLuuuu** [comment]
> > looks like its working, just my full-screen mode is not really fullscreen:
> 
> It's because this art is not responsive enough for different screen sizes.

The same collection minted on Base here is visibly bigger: https://zora.co/collect/base:0xc029b380f8a451cfd9e5124fa9fcad4397b8c119/3. But yeah nevermind important that its working.

**Review by daiagi — APPROVED** [review]

**Pull request merged**
