### PR TITLE
Add and configure jest

### PR DESCRIPTION
**Pull request by JKrupinski**
**Thank you for your contribution** to the KodaDot NFT gallery.
Let's do a quick check before the merge.
Your contribution will be an eternal part of the community codebase.

### PR type
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### Before submitting this PR, please make sure:
- [ ] Code builds clean without any errors or warnings
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've didn't break any original functionality
- [ ] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested it on mobile and everything works
- [ ] I found edge cases

### What's new? (may be part of changelog)
- This PR closes #<issue_number> - <Brief_description_how_I've_fixed_it>

### If issue had bounty label ($,$$,$$$)
- Fill up your KSM address: https://kodadot.xyz/transfer/?target=<Kusama_Address> 

### Community participation
- [ ] Are you at KodaDot Discord? If not yet, [let's join us - https://discord.gg/35hzy2dXXh](https://discord.gg/35hzy2dXXh)

### Screenshot
- [ ] Whenever my fix has changed **something** on UI, a screenshot for others, is more than welcome

### CODE REVIEW

**Comment by vikiival** [comment]
Looking forward 👀.
Can it pass the the sample test with @polkadot/api ?

**Comment by yangwao** [comment]
Can be this merged? @vikiival

**Comment by vikiival** [comment]
Closing as we use mocha from that.
I think for the Nuxt we will go for [uvu](https://github.com/lukeed/uvu). If you know how to configure that happy to drop a bounty 💵

**Comment by yangwao** [comment]
> Closing as we use mocha from that. I think for the Nuxt we will go for [uvu](https://github.com/lukeed/uvu). If you know how to configure that happy to drop a bounty 💵

Open a new issue and link it here, probably add $$$ label, it would be more than worth having tests

**Pull request closed without merging**
