### PR TITLE
fix: Collections sort by filter breaks when multiple options are selected

### LINKED ISSUE #9967: Collections sort by filter breaks when multiple options are selected
>Guess this is the origin of - https://github.com/kodadot/stick/issues/263#issuecomment-2033965881

>vikiival  I think this might be the problem, it's happening on canary 

https://github.com/kodadot/nft-gallery/assets/44554284/d74f7ce1-bd51-43b5-98bf-d95e83d41be8

_Originally posted by @hassnian in https://github.com/kodadot/nft-gallery/pull/9959#discussion_r1549361761_

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Closes #9967

## Needs QA check

- @kodadot/qa-guild please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

https://github.com/kodadot/nft-gallery/assets/44554284/ddaf9471-ff14-4161-b726-59bd2ce876b5

### CODE REVIEW

**Comment by daiagi** [comment]
something is not right

**scenario** a: sort by _"Least Supply_" and after add "_Newest_"
**scenario** b: sort by "_Newest_" and after add "_Least Supply_"

### Expected 

Grid order to be same

**Comment by vikiival** [comment]
> Grid order to be same

well, order wont be the same as preffered sorting is the first one and then second applied 

This is a default behaviour of PSQL :)
only if we would sort the filters?

```sql
select id, name, supply, created_at from collection_entity order by created_at desc, supply limit 10;
```

```json
[
  {
    "id": "119",
    "name": "Aurora",
    "supply": 0,
    "created_at": "2024-04-09 12:32:12.000000 +00:00"
  },
  {
    "id": "118",
    "name": null,
    "supply": 0,
    "created_at": "2024-04-09 12:09:24.000000 +00:00"
  },
  {
    "id": "117",
    "name": "Eka the Italian Greyhound & friends",
    "supply": 14,
    "created_at": "2024-04-01 10:46:24.000000 +00:00"
  },
  {
    "id": "116",
    "name": "Shapes",
    "supply": 81,
    "created_at": "2024-03-27 12:51:48.000000 +00:00"
  },
  {
    "id": "115",
    "name": "Tilescapes",
    "supply": 96,
    "created_at": "2024-03-26 12:50:48.000000 +00:00"
  },
  {
    "id": "114",
    "name": "Tied to Pink",
    "supply": 0,
    "created_at": "2024-03-21 10:04:36.000000 +00:00"
  },
  {
    "id": "113",
    "name": "The Break",
    "supply": 16,
    "created_at": "2024-03-19 11:02:06.000000 +00:00"
  },
  {
    "id": "112",
    "name": "Convergente",
    "supply": 171,
    "created_at": "2024-03-12 05:50:36.000000 +00:00"
  },
  {
    "id": "111",
    "name": "KodaDot at Sub0 Asia 2024",
    "supply": 21,
    "created_at": "2024-03-12 04:55:00.000000 +00:00"
  },
  {
    "id": "110",
    "name": "Buddhist Scriptures",
    "supply": 30,
    "created_at": "2024-03-08 08:14:48.000000 +00:00"
  }
]
```
```sql
select id, name, supply, created_at from collection_entity order by supply, created_at desc limit 10;
```

```json
[
  {
    "id": "119",
    "name": "Aurora",
    "supply": 0,
    "created_at": "2024-04-09 12:32:12.000000 +00:00"
  },
  {
    "id": "118",
    "name": null,
    "supply": 0,
    "created_at": "2024-04-09 12:09:24.000000 +00:00"
  },
  {
    "id": "114",
    "name": "Tied to Pink",
    "supply": 0,
    "created_at": "2024-03-21 10:04:36.000000 +00:00"
  },
  {
    "id": "109",
    "name": "Buddhist Scriptures",
    "supply": 0,
    "created_at": "2024-03-08 05:55:24.000000 +00:00"
  },
  {
    "id": "105",
    "name": "e1f42999-0c9e-4170-a6fb-17943f4c0832",
    "supply": 0,
    "created_at": "2024-02-26 11:36:36.000000 +00:00"
  },
  {
    "id": "100",
    "name": "Markedot - $PINK is $DED",
    "supply": 0,
    "created_at": "2024-02-20 21:24:18.000000 +00:00"
  },
  {
    "id": "94",
    "name": null,
    "supply": 0,
    "created_at": "2024-02-10 12:26:30.000000 +00:00"
  },
  {
    "id": "90",
    "name": null,
    "supply": 0,
    "created_at": "2024-02-04 17:41:48.000000 +00:00"
  },
  {
    "id": "79",
    "name": "Polkadots",
    "supply": 0,
    "created_at": "2024-01-18 04:13:42.000000 +00:00"
  },
  {
    "id": "75",
    "name": "Cindy Mark I",
    "supply": 0,
    "created_at": "2024-01-09 13:03:06.000000 +00:00"
  }
]
```

**Comment by prury** [comment]
looks fine to me my friends, couldn't find the order issue

**Review by vikiival — APPROVED** [review]

**Comment by prury** [comment]
pay 40 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $40 @ 8.26 USD/DOT ~ 4.843 $DOT
🧗 [16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD](https://polkadot.subscan.io/account/16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)
🔗 [0xd7ab94bc465fe095f05e657079fa1e71533899bba9dc1507e84468839937b84a](https://polkadot.subscan.io/extrinsic/0xd7ab94bc465fe095f05e657079fa1e71533899bba9dc1507e84468839937b84a)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
