### PR TITLE
#3576 Fixed: Duplicate nfts in user profile created section

### LINKED ISSUE #3576: Duplicate nfts in user profile created section
### What happened?

Screen Shot 2022-07-26 at 6 16 28 PM

### Please reproduce in steps

https://beta.kodadot.xyz/bsx/u/bXj1N8PuXSaZAR3TdMxmXAce32FhZpW3qy8NSj9djB1SAPhz7?page=1

### Expected Behavior

.

### What browsers are you seeing the problem on?

_No response_

### At which address did you encounter bug?

_No response_

### Are you logged in?

_No response_

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

_No response_

### Screenshots

.

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3576
- [ ] Requires deployment <rubick/magick_issue>
- [x] Took some time to debug this but hopefully it wont break any other flow that we have 🙏

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by roiLeo** [comment]
Test:
https://deploy-preview-3577--koda-nuxt.netlify.app/bXj1N8PuXSaZAR3TdMxmXAce32FhZpW3qy8NSj9djB1SAPhz7?page=1

**Review by roiLeo — APPROVED** [review]
this code is definitely hotfix, ✅ works for me, we'll need to clean some stuff in the `PaginatedCardList` component (ref #3579)

**Comment by petersopko** [comment]
@prachi00 @roiLeo I'm trying to test this at both [beta](https://beta.kodadot.xyz/bsx/u/bXj1N8PuXSaZAR3TdMxmXAce32FhZpW3qy8NSj9djB1SAPhz7?page=1), and [prod](https://kodadot.xyz/bsx/u/bXj1N8PuXSaZAR3TdMxmXAce32FhZpW3qy8NSj9djB1SAPhz7?page=1) and I can't see any duplicates tho? 😆

**Comment by roiLeo** [comment]
> @prachi00 @roiLeo I'm trying to test this at both [beta](https://beta.kodadot.xyz/bsx/u/bXj1N8PuXSaZAR3TdMxmXAce32FhZpW3qy8NSj9djB1SAPhz7?page=1), and [prod](https://kodadot.xyz/bsx/u/bXj1N8PuXSaZAR3TdMxmXAce32FhZpW3qy8NSj9djB1SAPhz7?page=1) and I can't see any duplicates tho? 😆

When I click directly on: https://beta.kodadot.xyz/bsx/u/bXj1N8PuXSaZAR3TdMxmXAce32FhZpW3qy8NSj9djB1SAPhz7?page=1

I see
Capture d’écran 2022-07-27 à 12 10 43 PM

**Comment by petersopko** [comment]
> I see Capture d’écran 2022-07-27 à 12 10 43 PM

Okay now I see it too, weird, but I guess the hotfix works for now.

**Review by petersopko — APPROVED** [review]
wfm

**Comment by petersopko** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 56.5 USD/KSM ~ 0.885 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0xc189798342621a762b5b5d5cba24e198978d21306ba351f03af399f17c34e268](https://kusama.subscan.io/extrinsic/0xc189798342621a762b5b5d5cba24e198978d21306ba351f03af399f17c34e268)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
