### PR TITLE
fix: missing trait_type on nft/collection

### LINKED ISSUE #3195: Seems bug in trait table in bsx?
https://beta.kodadot.xyz/bsx/gallery/235937109-1?page=1

image

https://beta.kodadot.xyz/bsx/gallery/235937109-3?page=1
image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3195
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by vikiival** [comment]
Doable

**Review by petersopko — APPROVED** [review]
wfm

**Comment by Jarsen136** [comment]
@petersopko  
How about calling the bounty bot 👀

**Comment by petersopko** [comment]
pay 75 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $75 @ 53.46 USD/KSM ~ 1.403 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x35389e11f9a42e279a7cbc3c00f8f170754b7547f54fb8ef66bcb68339e6064b](https://kusama.subscan.io/extrinsic/0x35389e11f9a42e279a7cbc3c00f8f170754b7547f54fb8ef66bcb68339e6064b)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
