### PR TITLE
remove debounced watch

### LINKED ISSUE #9696: Infinite generating loop on canary
Okay, this is a random find

https://github.com/kodadot/nft-gallery/assets/5887929/c8c93a88-5c34-47fb-8bb5-94ef2915ece4

I thought it was oke then but then I spot then it goes triggered go mint and then cancel and keeps generating things 

https://github.com/kodadot/nft-gallery/assets/5887929/b8c60719-f8fe-4615-81fc-5e3d58eec79a

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Context

- [x] Closes #9696

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)

### CODE REVIEW

**Comment by yangwao** [comment]
wut no deploy preview 
image

**Comment by yangwao** [comment]
idk hopefuly does the job, not even in netlify dp list
thanks!
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 10.62 USD/DOT ~ 1.883 $DOT
🧗 [1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8](https://polkadot.subscan.io/account/1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)
🔗 [0x928e0791ea3fd768df060989ba3b7e7ac1a46b8a20d8926fe370fc6b9c6e307d](https://polkadot.subscan.io/extrinsic/0x928e0791ea3fd768df060989ba3b7e7ac1a46b8a20d8926fe370fc6b9c6e307d)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
oh it's against `drops-refactor` branch.

**Comment by preschian** [comment]
@daiagi need to make sure to always get a valid base64 image. if not, will throw an error this one https://github.com/kodadot/nft-gallery/issues/9559#issuecomment-1968954266

maybe log the payload image? once logged, we can try to click the "generate" button so many times to see if is it always valid or not

**Comment by daiagi** [comment]
OK. I'll check
Thanks

**Comment by daiagi** [comment]
@preschian 

seems good

**Comment by preschian** [comment]
> seems good

cool 👍🏻

**Pull request merged**
