### PR TITLE
feat: show placeholder variant based on colormode

### LINKED ISSUE #3754: K placeholder with transparent background for white/black version
We would need some version of K with transparent background

Options which would work

From #3345 options 
A) K with transparent background

B) having two assets and set them based on white/black mode
- black logo on white
- white log on black 

Presskit could be found here 
- https://github.com/kodadot/kodadot-presskit/tree/main/v3

**Explore:** collections/gallery: Not sure if this is also something our dev team can fix, but maybe it would be prettier if the "loading form" of NFTs had our logo on a white background. You can see in this picture that our K logo is on a black background, and it's kinda ruining the whole white mode effect.
image

Also, it would be nice to have a white version of the short loading gif, that appears after you open each NFT. This one:
image

ht @JustLuuuu 

_Originally posted by @JustLuuuu in https://github.com/kodadot/nft-gallery/issues/3742#issuecomment-1216288409_

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

https://user-images.githubusercontent.com/17953978/185156232-499b9828-0589-4b1c-b1c3-77a096f82248.mov

### What's new?

- [x] PR closes #3754
- [ ] Requires deployment <rubick/magick_issue>
- [x] show either white or basic version based on chosed colormode

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
Screenshot 2022-08-17 at 16-26-05 KodaDot - Kusama NFT Market Explorer

I'm not really into gradient as I was tempted to scroll right.
Can we see a full white bg version?

Other than that ✅ code lgtm

edit:
What about preloader svg on galleryItem?
Screenshot 2022-08-17 at 16-29-51 KodaDot - Kusama NFT Market Explorer

**Comment by kkukelka** [comment]
> Screenshot 2022-08-17 at 16-26-05 KodaDot - Kusama NFT Market Explorer
> 
> I'm not really into gradient as I was tempted to scroll right. Can we see a full white bg version?
> 
> Other than that ✅ code lgtm
> 
> edit: What about preloader svg on galleryItem? Screenshot 2022-08-17 at 16-31-06 KodaDot - Kusama NFT Market Explorer

i'll try and create fully white versions of both of them

**Comment by kkukelka** [comment]
@roiLeo  went for the black&white. looks fire
Screenshot 2022-08-17 at 17 50 44
Screenshot 2022-08-17 at 17 49 52

**Comment by roiLeo** [comment]
This looks way better !
The only thing that bothers me is that we have:
- darkmode: placeholder => primary logo on black bg
- lighmode: placeholder => black logo on white bg

What do you think about this?

Should we have unified placeholder?: 
- primary logo on white/black bg
- or black/white logo on white/black bg
I vote for the second option :)

**Comment by kkukelka** [comment]
> This looks way better ! The only thing that bothers me is that we have:
> 
> * darkmode: placeholder => primary logo on black bg
> * lighmode: placeholder => black logo on white bg
> 
> What do you think about this?
> 
> Should we have unified placeholder?:
> 
> * primary logo on white/black bg
> * or black/white logo on white/black bg
>   I vote for the second option :)

the reason i went for black on white is because the dot of the primary version is already white

**Comment by roiLeo** [comment]
placeholder dark

**Comment by kkukelka** [comment]
> placeholder dark

thanks! 👍

**Review by roiLeo — APPROVED** [review]
Noice!

Capture d’écran 2022-08-19 à 3 26 07 PM
Capture d’écran 2022-08-19 à 3 25 41 PM

So we remove animated placeholder for now?

**Comment by kkukelka** [comment]
> So we remove animated placeholder for now?

i would say yes. at least until someone designs a solution for the light theme

**Comment by yangwao** [comment]
Some tests have failed? 👀

**Comment by kkukelka** [comment]
> Some tests have failed? 👀

fake news... there's a flaky test we need to take a look at. 😞

**Comment by yangwao** [comment]
pay 50

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 49.77 USD/KSM ~ 1.005 $KSM
🧗 [EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW](https://kusama.subscan.io/account/EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)
🔗 [0x95411b2384b61c2958a7339be905adb5f9003de3da952c31ec599a91346c52a7](https://kusama.subscan.io/extrinsic/0x95411b2384b61c2958a7339be905adb5f9003de3da952c31ec599a91346c52a7)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
