### PR TITLE
fix: collectionId in path of url

### LINKED ISSUE #6278: collectionId in path
### Step to reproduce:
- go to any chain
- click on explore
- click on any collection item
- you'll have a `?collectionId=...` param in path which is redundant

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #6278
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [ ] My fix has changed UI

### <samp>🤖 Generated by Copilot at 1f57248</samp>

This pull request refactors the collection search feature to use a pinia store and a composable function. This simplifies the code and makes the collection search mode accessible to other components. It also adds a feature to disable the collection search mode on mobile devices.

### <samp>🤖 Generated by Copilot at 1f57248</samp>

> _Search by collection_
> _Refactored with `pinia`_
> _No more on mobile_

### CODE REVIEW

**Comment by prury** [comment]
Ways of triggering the error:
go to a collection page and switch between activity and items
go to a nft and click on the link that leads to its collection

the redundant collection id **does not show up** on the address bar anymore, but the warning still appears: 

image

**Comment by Jarsen136** [comment]
> Ways of triggering the error: go to a collection page and switch between activity and items go to a nft and click on the link that leads to its collection
> 
> the redundant collection id **does not show up** on the address bar anymore, but the warning still appears:
> 
> image


✅ Fixed. I have removed the annoying warning. TBH, this warning is related to other issues instead of the collection search.

**Review by vikiival — APPROVED** [review]
CODE LGTM

@prury please check if it works as intended

**Comment by prury** [comment]
> CODE LGTM
> 
> @prury please check if it works as intended

yup, no more warnings and redundancy

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
pay 15 usd

**Pull request merged**
