### PR TITLE
fix(3069): fetch total numer of lots of tabs

### LINKED ISSUE #3069: Tabs on artist's profile are missing count
### What happened?

Seems that somewhere along the way, we've lost the displayed count of NFTs Sold, etc. The number is displayed only after selection of given tab.

image

### Please reproduce in steps

Go to ... Click on .... See error

### Expected Behavior

I've expected ...

### What browsers are you seeing the problem on?

_No response_

### Are you logged in?

_No response_

### At which address did you encounter bug?

_No response_

### Screenshots

Paste from your clipboard or upload screenshots/video

### Relevant log output

_No response_

### Payment link for reward

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by zhengow**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3069
- [x] while Profile Component created, fetch totalCount of each tabs to set.

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at /rmrk/u/DQcegDuBQG6V99hgRd87UJ8anZxTcumJEVBAnAGomXCJ3dc?tab=sold&page=1
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

### CODE REVIEW

**Comment by kkukelka** [comment]
@petersopko maybe we should just hide tabs if they dont have anything to show?

**Comment by petersopko** [comment]
> @petersopko maybe we should just hide tabs if they dont have anything to show?

@zhengow i think it's a good idea, please, can you add that?

**Comment by zhengow** [comment]
image
already done, plz check

**Comment by zhengow** [comment]
> > @petersopko maybe we should just hide tabs if they dont have anything to show?
> 
> @zhengow i think it's a good idea, please, can you add that?

image

already done, plz check

**Comment by zhengow** [comment]
> > @petersopko maybe we should just hide tabs if they dont have anything to show?
> 
> @zhengow i think it's a good idea, please, can you add that?

@petersopko add this feature just now, plz check
image

**Comment by kkukelka** [comment]
pay 100

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 72.08 USD/KSM ~ 1.387 $KSM
🧗 [EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws](https://kusama.subscan.io/account/EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)
🔗 [0xf27aeb1126cf77c5e216bfe9251192b0c23d272536c0a6d7864541cf0ee1d997](https://kusama.subscan.io/extrinsic/0xf27aeb1126cf77c5e216bfe9251192b0c23d272536c0a6d7864541cf0ee1d997)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
