### PR TITLE
fix: Optimize expiration time for shorter format

### LINKED ISSUE #3621: Optimize expiration time for shorter format
I guess expiration is an issue on smaller/mobile screens, and overall we don't need to show it longer if it's expiration longer than one day.

- Make mixin, which helps show expiration in the shorter format. 
- Change everywhere in offer tables 

I.e. example 
13 days 15 hours 38 minutes -> 13 days
15 hours 38 minutes -> 15 hours
38 minutes -> 38 minutes

https://user-images.githubusercontent.com/5887929/181906017-7325cdc6-de87-4d19-81d1-76e5bbf34612.mov

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3621
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image
image

### CODE REVIEW

**Comment by petersopko** [comment]
can we somehow give user the ability to see the actual approximation of expiration time? Like full date popup on click or something. Maybe @roiLeo can think of something UX friendly 😅

**Comment by yangwao** [comment]
> can we somehow give user the ability to see the actual approximation of expiration time?

yup, reference in new issue

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 63.94 USD/KSM ~ 0.469 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x390bbe782d93f716c9c31a15b95cb3dcdcce2d02544f37c5aed7106fe5a09bf3](https://kusama.subscan.io/extrinsic/0x390bbe782d93f716c9c31a15b95cb3dcdcce2d02544f37c5aed7106fe5a09bf3)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
