### PR TITLE
Audio NFT player

### LINKED ISSUE #3248: Audio NFT player
Test:
`/rmrk/gallery/10732439-cc89eac7f82ae14164-8IR8T4P35V1-BIRB_TAPES_VOL_1_HOUSEY_CHAOS_SOUNDS-0000000000000022`

The audio player has disappeared :(

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3248
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Review by prachi00 — APPROVED** [review]

**Comment by prachi00** [comment]
LGTM

**Comment by prachi00** [comment]
@Jarsen136 one doubt though
https://deploy-preview-3268--koda-nuxt.netlify.app/rmrk/gallery/10249720-466e8b6338599eaf1e-GAVCUBE-GAV_CUBE_101-0000000000000101?page=1
is this also an audio nft?

**Comment by Jarsen136** [comment]
> @Jarsen136 one doubt though https://deploy-preview-3268--koda-nuxt.netlify.app/rmrk/gallery/10249720-466e8b6338599eaf1e-GAVCUBE-GAV_CUBE_101-0000000000000101?page=1 is this also an audio nft?

Hey, it's just a image 🚶 
image

**Comment by prachi00** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 57.73 USD/KSM ~ 0.866 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x7c842769c2375b71e825b089613f1cf732bf60cea5c84dab09f07a22a82deceb](https://kusama.subscan.io/extrinsic/0x7c842769c2375b71e825b089613f1cf732bf60cea5c84dab09f07a22a82deceb)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
