### PR TITLE
[Blogpost] How do unlockable content NFTs work on KodaDot ?

### LINKED ISSUE #6558: [Blogpost] How do unlockable content NFTs work on KodaDot ?
date
---
12/12/2022

# How do unlockable content NFTs work on KodaDot ?
unlockable

## Unveiling Hidden Content and Free Merch for NFT Owners
At KodaDot, our NFT marketplace is not just about owning unique and valuable digital assets. We believe in providing an immersive and rewarding experience for our community of collectors and creators. That's why we're thrilled to introduce Unlockables, a revolutionary feature that adds an element of excitement and exclusivity to your NFT ownership.

image

Unlockables are hidden content and special perks that become accessible to NFT owners once they mint their digital assets. These unique unlockable experiences are designed to enhance the value and enjoyment of your NFT collection.
Gain access to exclusive, unlockable content associated with specific NFTs. Unlockables provide a thrilling sense of discovery. It's an invitation to explore the intricacies and stories that lie beneath the surface of the artwork, making your ownership even more special and unique. 
Unlockables create a sense of exclusivity and value for our community members. They foster a deeper connection between creators and collectors, allowing NFT owners to experience a level of engagement that goes beyond the initial purchase. As an NFT owner on KodaDot, you become part of a vibrant ecosystem where creativity, exploration, and rewards converge.

## Campaigns with anime waifu
You may be the owner of one of these first NFTs we introduced with Claimables. This was our testing campaign during a mini-conference in Bled, Slovenia. Guests were able to create their own NFT and claim their reward.

image

Currently, on KodaDot we support unlockables in private and we've demonstrated unlockables with vouchers to claim free t-shirts from our [shop.kodadot.xyz](https://shop.kodadot.xyz/).

### We are preparing more detailed, exciting, and new campaigns for you! 
You'll also have the opportunity to claim free merchandise associated with the unlockable content. This means that you can tangibly enjoy the world of your NFT collection beyond the digital realm. Get limited-edition physical items and our merchandise as a token of appreciation for your support and loyalty as an NFT owner.

## How does it work?
Follow KodaDot on [Twitter](https://twitter.com/KodaDot) and wait for the announcement. Minting will be free but limited by number. First come, first serve. These drops will be limited to a specific number of NFTs for each phase. Connected to our anime waifu characters, you will be able to see which NFT you will claim. Each waifu will have a voucher to claim one design.

image

To participate in the unlockable journey, you only need to simply mint an NFT on KodaDot during one of our campaigns.
Join us on KodaDot and unlock a world of hidden treasures within your NFT collection. Experience the thrill of discovery, claim your free merchandise, and be part of an innovative community that celebrates the power of creativity and ownership. 

*Welcome to the era of Unlockables – a new dimension in NFTs.*

### PR DESCRIPTION
**Pull request by hassnian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

Added _blog/how-do-unlockable-content-nfts-work-on-kodadot_ post

- [x] Closes #6558
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

CleanShot 2023-08-05 at 20 44 45@2x

### <samp>🤖 Generated by Copilot at ae593e1</samp>

Added a new blog post `how-do-unlockable-content-nfts-work-on-kodadot.md` to inform and educate users about the unlockable content feature on KodaDot. The post showcases the benefits and use cases of unlockables for NFT creators and collectors.

### <samp>🤖 Generated by Copilot at ae593e1</samp>

> _`Unlockables` post_
> _Explains a cool NFT feature_
> _Autumn campaign calls_

### CODE REVIEW

**Comment by hassnian** [comment]
waiting on https://github.com/kodadot/nft-gallery/issues/6558#issuecomment-1666532760

**Comment by exezbcz** [comment]
can you please update the thumbnail for this please 👀 
image

**Review by roiLeo — APPROVED** [review]

**Comment by yangwao** [comment]
I'm special? 

image

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 4.93 USD/DOT ~ 10.142 $DOT
🧗 [16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD](https://polkadot.subscan.io/account/16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)
🔗 [0x1be648afacd688df6c245f2b148088563a517e40a5eacacc6ec853597c98dd4e](https://polkadot.subscan.io/extrinsic/0x1be648afacd688df6c245f2b148088563a517e40a5eacacc6ec853597c98dd4e)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
maybe fixed in 
- https://github.com/kodadot/nft-gallery/issues/6524

**Pull request merged**
