### PR TITLE
mimetype from static

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Related #6782

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)

### <samp>🤖 Generated by Copilot at 4fad24a</samp>

Improved modularity and readability of `useZipValidator.ts` by extracting `mimeTypes` to a separate module.

### <samp>🤖 Generated by Copilot at 4fad24a</samp>

> _We'll haul away the zip validator_
> _And import `mimeTypes` from afar_
> _It makes the code more neat and clear_
> _So heave away, me hearties, heave away_

### CODE REVIEW

**Comment by daiagi** [comment]
fix this:
image

**Review by preschian — APPROVED** [review]

**Comment by preschian** [comment]
not sure if this is related or not. seems like false alarm

image

**Comment by daiagi** [comment]
@preschian 
looks false to me too. it is exactly what this PR fixes

**Comment by vikiival** [comment]
Why it is in static in the first place 🥺. 

But LGTM

**Comment by daiagi** [comment]
> Why it is in static in the first place 🥺.


here you go sir:

https://github.com/kodadot/nft-gallery/pull/5882#discussion_r1210216205

**Review by vikiival — APPROVED** [review]

**Comment by yangwao** [comment]
pay 30 usd
great catch!

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 4.48 USD/DOT ~ 6.696 $DOT
🧗 [1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8](https://polkadot.subscan.io/account/1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)
🔗 [0xd35d9ab121648b012d8fa09f3cd6f48942192b511b7b190581b4fbd13e5b4697](https://polkadot.subscan.io/extrinsic/0xd35d9ab121648b012d8fa09f3cd6f48942192b511b7b190581b4fbd13e5b4697)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by daiagi** [comment]
@yangwao 
payment failed. not enough balance

**Comment by yangwao** [comment]
pay 30 usd
classics

**Comment by daiagi** [comment]
@yangwao
Shots not fired

**Comment by yangwao** [comment]
pay 30 usd
these serverless things these days should be much better :D

**Comment by yangwao** [comment]
pay 30 usd
ah, should be now :)

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 4.46 USD/DOT ~ 6.726 $DOT
🧗 [1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8](https://polkadot.subscan.io/account/1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)
🔗 [0xf1847a6384b8f465363791703881cbb5a4a1edd6fbbb83c8963322005a513893](https://polkadot.subscan.io/extrinsic/0xf1847a6384b8f465363791703881cbb5a4a1edd6fbbb83c8963322005a513893)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
