### PR TITLE
feat: code checker open in a new tab button

### LINKED ISSUE #10470: [code-checker] files is not uploaded to r2 bucket
Hi @kodadot/internal-dev, does anyone know why this file fails to upload to r2 buckets? Or did I miss anything?

[xest3.zip](https://github.com/user-attachments/files/15836907/xest3.zip)

And can we add one button somewhere to open a new link to the public bucket after the file is uploaded?

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

> And can we add one button somewhere to open a new link to the public bucket after the file is uploaded?

- [x] Closes #10470

## Needs QA check

- @kodadot/qa-guild please review

## Needs Design check

- @exezbcz please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2024-06-15 at 18 59 35@2x

### CODE REVIEW

**Review by Jarsen136 — APPROVED** [review]

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
@preschian can u check if it works for u pls?

**Comment by prury** [comment]
small: if i click on open new tab right after I've loaded the art, it still shows the 404, then if i close and click again its loaded.
maybe add small loader?

**Comment by hassnian** [comment]
> small: if i click on open new tab right after I've loaded the art, it still shows the 404, then if i close and click again its loaded. maybe add small loader?

fixed, needs https://github.com/kodadot/private-workers/pull/181

**Comment by prury** [comment]
waiting for @preschian here

**Comment by preschian** [comment]
nice, it works now 👍🏻

**Pull request merged**
