### PR TITLE
fix: diagram workflow issue

### LINKED ISSUE #2834: Seems diagram fails
Seems workflow on diagram is failing 🫣

https://github.com/kodadot/nft-gallery/actions/workflows/diagram.yml

image

### PR DESCRIPTION
**Pull request by KngZhi**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2834
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by yangwao** [comment]
this will be generating a diagram on each push. that's not solution I guess?

**Comment by KngZhi** [comment]
Hmm, I see, I would check it later.

**Comment by KngZhi** [comment]
@yangwao the new commit would create a new PR to bypass the protection rule. The result would be like [this tested result](https://github.com/KngZhi/nft-gallery/pull/4). Sadly we have to manually merge that. 😞 

Besides, I noticed a [comment](https://github.com/kodadot/nft-gallery/blob/f92d2e96f13017d6b6ba235ce067f56689c450ad/.github/workflows/diagram.yml#L22) wants to ignore the `*.md` files within root dir, but from the SVG generated, `md` files are not included. Maybe we should detele that.

**Comment by yangwao** [comment]
okay let's go with that one, probably setting it to bi-weekly is fair enough :)

**Comment by KngZhi** [comment]
Okay, all set. 😄  Update at 1, 15 for each month.

**Comment by yangwao** [comment]
pay 100 usd 
lets see

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 163.75 USD/KSM ~ 0.611 $KSM
🧗 [DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc](https://kusama.subscan.io/account/DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc)
🔗 [0xc4d4416f5b44307d89d6afd7def4a6b9e5c90ed0f48992bb72b1ee5543b6e3b0](https://kusama.subscan.io/extrinsic/0xc4d4416f5b44307d89d6afd7def4a6b9e5c90ed0f48992bb72b1ee5543b6e3b0)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by KngZhi** [comment]
haven't changed the pull request branch...
I will revise that.

**Pull request merged**
