### PR TITLE
Revert "[skip netlify] Update Bumped minor version of packages (patch)"

### LINKED ISSUE #2826: Builds are broken
To me looks like a Netlify outage?

`Deploy did not succeed: Deploy directory 'dist' does not exist`

First failed build seems on `main` at 11:44am

My bet is at 

https://github.com/kodadot/nft-gallery/pull/2815/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R27

### Ref
- https://github.com/kodadot/nft-gallery/pull/2812
- https://github.com/kodadot/nft-gallery/pull/2825
- #2718 

https://app.netlify.com/teams/yangwao/builds/625549e849e59900089b0d26

image

https://app.netlify.com/sites/koda-nuxt/deploys/62554a7806c0270008e7f412

image

### PR DESCRIPTION
**Pull request by yangwao**
PR closes #2826 
PR closes #2827 

Reverts kodadot/nft-gallery#2810

### CODE REVIEW

**Comment by vikiival** [comment]
Yup https://github.com/kodadot/nft-gallery/commit/d6cc369c0b4d44f4e7fa9420db7d14c64fcf7720

**Comment by vikiival** [comment]
First one that failed on CF

**Comment by vikiival** [comment]
Please work ❤️

**Review by vikiival — APPROVED** [review]

**Comment by yangwao** [comment]
it's better than new years countdown 
image

**Comment by yangwao** [comment]
but it's takes so long that seems would be working?

**Comment by yangwao** [comment]
seems Cloudflare works but GitHub failed? 

image

**Pull request merged**
