### PR TITLE
✨ GenerativeMint redesign

### PR DESCRIPTION
**Pull request by roiLeo**
Goes after #6083 
🚧 work in progress, good start to redesign

#### TODO:
- [ ] cover background
- [ ] heading related with buttons
- [ ] Buttons step2 and step3

## PR Type

- [x] Refactoring

## Context

- [x] Related with #6062 

## Screenshot 📸

Screenshot 2023-05-23 at 11-41-13 KodaDot Low fees and low carbon minting KodaDot - NFT Market Explorer

Screenshot 2023-05-23 at 11-59-17 KodaDot Low fees and low carbon minting KodaDot - NFT Market Explorer

### <samp>🤖 Generated by Copilot at 8d8b381</samp>

This pull request adds and improves features for minting generative NFTs. It introduces a new `size` prop for the `SubmitButton` component, a new `generative-mint-layout` component for the waifu page, and a new `multiline` and `rounded` props for the `RadioSelect` component. It also enhances the appearance and functionality of the `NeoSteps`, `GenerativeMintForm`, and `NeoRadioButton` components.

### <samp>🤖 Generated by Copilot at 8d8b381</samp>

> _To mint a generative NFT_
> _We made a new layout, you see_
> _With `NeoSteps` and `RadioSelect`_
> _And `SubmitButton` to connect_
> _The options for the NFT to be_

### CODE REVIEW

**Comment by vikiival** [comment]
Woah nice

**Comment by vikiival** [comment]
Gonna merge #6083 first

**Comment by Jarsen136** [comment]
I guess there is a responsive issue on mobile. Could you pls check it?
image

**Comment by roiLeo** [comment]
> I guess there is a responsive issue on mobile. Could you pls check it? 

aware of that, now fixed (copy/paste code power)

**Review by Jarsen136 — APPROVED** [review]

**Comment by prury** [comment]
cool, so far, apart from the AI generating issues(non related, takes a lot of tries to get some images), looks fine, will be following this PR

**Review by daiagi — APPROVED** [review]
Lgtm

**Comment by roiLeo** [comment]
I'll merge this for now, feel free to take over

**Pull request merged**
