### PR TITLE
fix: set address on prefix

### LINKED ISSUE #6045: update wallet address/identity based on prefix
> @preschian i am not seeing the issue i've jut creates test-massmint collection on snek and it appears in the massmint dropdown as expected

oh, nvm, seems like I've got an unrelated issue. reproduce:
1. visit other than `snek` pages, e.g: https://canary.kodadot.xyz/rmrk/explore/collectibles
2. open `snek` page in a new tab, e.g: https://canary.kodadot.xyz/snek/create/?tab=Collection
3. bug: my wallet address is not updated to `snek` address

_Originally posted by @preschian in https://github.com/kodadot/nft-gallery/issues/5882#issuecomment-1553956982_

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #6045

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

### <samp>🤖 Generated by Copilot at 9fc456d</samp>

Prefix middleware to handle different address formats for different chains. It uses `useIdentityStore` and `ss58Of` to adapt the format based on the url.

### <samp>🤖 Generated by Copilot at 9fc456d</samp>

> _Sing, O Muse, of the code that sets the address format_
> _By the chain prefix in the url, a subtle mark of fate_
> _That guides the useIdentityStore hook and the ss58Of function_
> _To render the correct form, like Zeus who shapes the world by his unction_

### CODE REVIEW

**Review by vikiival — APPROVED** [review]

**Comment by prury** [comment]
Was able to successfully reproduce the issue using Chrome, tested with deployed version and its working properly.

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 25.05 USD/KSM ~ 1.198 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0xb1af0b6136a864e90f75133385ff880c1656584b6faf12f7f6e227a2cc5b56ad](https://kusama.subscan.io/extrinsic/0xb1af0b6136a864e90f75133385ff880c1656584b6faf12f7f6e227a2cc5b56ad)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by preschian** [comment]
> Should we keep `store`? ref #5984
> 
> I've remove something like this in #5655 (`formatPlugin`)
> 
> otherwise ✅ code lgtm (I'd still be careful about #6064)

oohh, didn't aware of these PR. checking

**Pull request merged**
