### PR TITLE
🔧 windows workflow

### PR DESCRIPTION
**Pull request by roiLeo**
🧪

### CODE REVIEW

**Comment by roiLeo** [comment]
hello @yangwao I think you need to unset required build workflow
Screenshot 2023-04-14 at 14-29-46 🔧 windows workflow by roiLeo · Pull Request #5661 · kodadot_nft-gallery

**Comment by yangwao** [comment]
wild neomodal component appears in PR 👀

**Comment by roiLeo** [comment]
> wild neomodal component appears in CI PR 👀

yep typo in file fixed https://github.com/kodadot/nft-gallery/pull/5661/commits/6f94e63ac2b91763889740e3c0ab4fe13060ff33

**Comment by daiagi** [comment]
how to test that it works?

**Comment by yangwao** [comment]
> how to test that it works?

there is only one way to find out 

image

**Review by daiagi — APPROVED** [review]

**Comment by roiLeo** [comment]
> we can see the result in this PR. need to unset required for ubuntu-latest and windows-latest

is it set on "Settings" tab?

By the way we have errors on histoire build, I'm preparing a fix

**Comment by yangwao** [comment]
this? 

https://user-images.githubusercontent.com/5887929/232060787-d45d1525-6762-4154-8027-4b16aa4ac8bd.mov

which checks I should add? I guess we just want to things to build

**Pull request merged**
