### PR TITLE
WIP: parallel tests + rmrk stats 

### LINKED ISSUE #3681: E2E - Spotlight / Series Insight / Hot
We would like to expand our current E2E test by testing Spotlight / Series Insight and Hot stats on RMRK

- [ ] check if filtering works
- [ ] check if sorting works
- [ ] check if data fetching behaves as expected after testing
- [ ] check if clickable links behave as expected

### LINKED ISSUE #3841: E2E - Cypress parallelization
currently we are at about 11min on ` Lint, Build & Test workflow`

### PR DESCRIPTION
**Pull request by petersopko**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [ ] PR closes #3841, closes #3681
- [ ] Requires deployment <rubick/magick_issue>
- [ ] test parallelization + stats test, coming soon

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by petersopko** [comment]
✅ 

image

**Comment by petersopko** [comment]
I need to ask for help from the pros here, I'm not making much progress on the parallelization part of the PR:

In order to parallelize the tests with cypress (not locally) cypress test needs to be recorded (happening with secret key which is saved in our GH repo already - it can be accessed through `${{ secrets.CYPRESS_RECORD_KEY }}`).

However, here's what I'm getting when trying to record our tests to Cypress dashboard:
image

Is it possible to start passing those keys to forked builds? this way, we can get to a point where the `install and cache` jobs gets saved in cypress dashboard and parallelized tests will run on virtual machines in the dashboard.
ref: https://docs.cypress.io/guides/guides/parallelization#CI-parallelization-interactions

@kkukelka @preschian I know you guys have worked with both workflows and Cypress before 🙏🏻 I'm trying couple workflows there, feel free to push in any ideas you might have straight to the PR.

**Comment by kkukelka** [comment]
> I need to ask for help from the pros here, I'm not making much progress on the parallelization part of the PR:
> 
> In order to parallelize the tests with cypress (not locally) cypress test needs to be recorded (happening with secret key which is saved in our GH repo already - it can be accessed through `${{ secrets.CYPRESS_RECORD_KEY }}`).
> 
> However, here's what I'm getting when trying to record our tests to Cypress dashboard: image
> 
> Is it possible to start passing those keys to forked builds? this way, we can get to a point where the `install and cache` jobs gets saved in cypress dashboard and parallelized tests will run on virtual machines in the dashboard. ref: https://docs.cypress.io/guides/guides/parallelization#CI-parallelization-interactions
> 
> @kkukelka @preschian I know you guys have worked with both workflows and Cypress before 🙏🏻 I'm trying couple workflows there, feel free to push in any ideas you might have straight to the PR.

i believe you have to set this CYPRESS_RECORD_KEY in the repository as well since we don't push our `.env` file to remote.
maybe this [article](https://glebbahmutov.com/blog/secrets-to-env/) can help

**Comment by preschian** [comment]
> Is it possible to start passing those keys to forked builds?

hhmm, interesting 🤔. maybe for cypress, we use another platform for CI (https://buildkite.com/ for example) and put that `secrets.CYPRESS_RECORD_KEY` into that platform

I need to test it out

**Comment by petersopko** [comment]
> i believe you have to set this CYPRESS_RECORD_KEY in the repository as well since we don't push our `.env` file to remote. maybe this [article](https://glebbahmutov.com/blog/secrets-to-env/) can help

it is set as this (kodadot/nft-gallery) secret, I've tried to set it in my fork as well, that didn't do the job

**Comment by petersopko** [comment]
> * use https://circleci.com/, "If you are comfortable sharing secrets with anyone who forks your project and opens a PR, you can enable the Pass secrets to builds from forked pull requests option" https://circleci.com/docs/oss#pass-secrets-to-builds-from-forked-pull-requests

This would also enable the native Cypress solution 😄 I'd rather stick with that then

> * use gitlab as ci/cd. cons, need premium account https://docs.gitlab.com/ee/ci/ci_cd_for_external_repos/github_integration.html

Generally speaking, it would be better in my opinion to stick with one solution for E2E tests -> from actual tests to parallelization. @yangwao could we pass the cypress secret (saved in this repo) to other forks? 

This would be the solution here, without requiring another CI/CD service (just Cypress + GH)

**Comment by petersopko** [comment]
expanding e2e test suite makes no sense without parallelization, this needs to get revisited once somebody manages to do that

**Pull request closed without merging**
