### PR TITLE
Load collection detail chart data when activity tab is clicked

### LINKED ISSUE #1754: Don't render graph until tab is clicked
When you open collection I have highly suspect we are fetching data for Activity tab and we should not to

https://nft-gallery-5ci.pages.dev/rmrk/collection/66241b171becfd500e-EGG?tab=collection

image

### PR DESCRIPTION
**Pull request by chandradot99**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇  _ Do a quick check before the merge.

### PR type
- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?
- [x] PR closes #1754
- [x] Load stats only when tab is clicked
- [x] Fix duplicate navigation warning

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main-nuxt** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases

### Had issue bounty label ?
- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=CeBWgisygADqqxGk7ju8aMNEKz1K2WkxMKC3G8HsMnm119n)

### Community participation
- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [ ] My fix has changed **something** on UI, a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
- Tested on `/rmrk/collection/800f8a914281765a7d-KITTY` 🆗 
- Let's say a new element is added to collection, would it be possible to refresh graph on demand?

**Comment by chandradot99** [comment]
@roiLeo yes it's possible, for that we have to add refresh button somewhere on top of chart. Should I add that refresh functionality also in this PR.

**Comment by roiLeo** [comment]
we can leave it like that for the moment, the refresh functionality will not be in this same component

**Comment by yangwao** [comment]
> we can leave it like that for the moment, the refresh functionality will not be in this same component

I guess subsquid/subquery has some listener for events? cc @vikiival 

Check how it's made for example once you are on NFT item detail and meanwhile someone made a action on-chain we refreshed "interactively"

**Comment by vikiival** [comment]
> I guess subsquid/subquery has some listener for events? cc @vikiival

"Hi, @vikiival! No, it doesn't."

**Comment by yangwao** [comment]
Perfect, I’ve sent the payout https://kusama.subscan.io/extrinsic/0x623248754376213985655e7fe0d430de56f0ace24768a6055e488d0b1c99eff9

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/

**Pull request merged**
