### PR TITLE
fix: Relocate first page query in searchbar

### LINKED ISSUE #3012: Relocate first page query in searchbar
`lastNftListByEvent` query should be executed once the navigation bar is clicked

Bonus:  remove query for other chains
Capture d’écran 2022-05-13 à 2 20 58 PM

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3012 
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by petersopko — CHANGES_REQUESTED** [review]
hey, thank you for your contribution again :) Can we please remove the query from other chains as described here? https://github.com/kodadot/nft-gallery/issues/3012 
when clicking the searchbar on westmint, I get query from RMRK. 
image

**Comment by Jarsen136** [comment]
> hey, thank you for your contribution again :) Can we please remove the query from other chains as described here? #3012 when clicking the searchbar on westmint, I get query from RMRK. image

Oh thanks for noticing that, I have fixed it.

**Review by petersopko — APPROVED** [review]
wfm

**Comment by petersopko** [comment]
@Jarsen136 one more thing please, check https://deepscan.io/dashboard/#view=project&tid=13903&pid=16948&bid=372223&subview=pull-request&prid=1232154

are we using `once` and deepscan is just confused? I see you added the import, but can't see where is it being used.

**Comment by Jarsen136** [comment]
> @Jarsen136 one more thing please, check https://deepscan.io/dashboard/#view=project&tid=13903&pid=16948&bid=372223&subview=pull-request&prid=1232154
> 
> are we using `once` and deepscan is just confused? I see you added the import, but can't see where is it being used.

OK, I will remove it.

**Comment by petersopko** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 75.06 USD/KSM ~ 1.332 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xbe600e79fe85666ad381dad6d826c2816568cda4dca16d3849a174a76f6b8424](https://kusama.subscan.io/extrinsic/0xbe600e79fe85666ad381dad6d826c2816568cda4dca16d3849a174a76f6b8424)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
