### PR TITLE
#2188 Twitter sharing bugs

### LINKED ISSUE #2188: Twitter sharing has bugs and needs some care
We've found something special about that twitter sharing 👀

@prachi00 may take look as need some proper testing:)

Apparently it put my handle instead owner :) 
image

image

image

https://kodadot.xyz/rmrk/gallery/11062915-8000262b13545ea72d-KPIZZA-LASER_PIZZA-0000000000000010

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2188
- [ ] 

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by yangwao** [comment]
Seems doesn't work for me :| 

image


image

**Comment by prachi00** [comment]
@yangwao is there any error on console?

**Comment by yangwao** [comment]
> @yangwao is there any error on console?

That's the trick, no error 😄

image

**Comment by prachi00** [comment]
@yangwao on local it seems to work fine, I'll try to debug more

**Comment by prachi00** [comment]
Screenshot 2022-02-03 at 4 38 46 PM
@yangwao also in the preview url here, I don't see twitter identity, maybe thats the issue?
https://deploy-preview-2190--koda-nuxt.netlify.app/rmrk/gallery/11062915-8000262b13545ea72d-KPIZZA-LASER_PIZZA-0000000000000010

**Comment by yangwao** [comment]
> Screenshot 2022-02-03 at 4 38 46 PM
> 
> @yangwao also in the preview url here, I don't see twitter identity, maybe thats the issue?
> [deploy-preview-2190--koda-nuxt.netlify.app/rmrk/gallery/11062915-8000262b13545ea72d-KPIZZA-LASER_PIZZA-0000000000000010](https://deploy-preview-2190--koda-nuxt.netlify.app/rmrk/gallery/11062915-8000262b13545ea72d-KPIZZA-LASER_PIZZA-0000000000000010)

yes, I guess so, not everyone artists has twitter

**Comment by prachi00** [comment]
@yangwao yeah so thats why I think you aren't able to see the 'made by' text here
https://deploy-preview-2190--koda-nuxt.netlify.app/rmrk/gallery/11101946-7294d22dea11a96c3f-ZEUE1-LAZY_KITTEN_061-0000000000000061

this is owned by you right but I cant see your twitter here in preview url

I would suggest that we merge this and then check whether its working fine or not in kodadot.xyz

**Comment by yangwao** [comment]
Just tried on this one, has both twitters but did not displayed handle :|

https://deploy-preview-2190--koda-nuxt.netlify.app/rmrk/detail/11218135-160a6f4320f11acb25-LCKWV-PIXEL_BABE_037-0000000000000037

image


image

**Comment by yangwao** [comment]
> I would suggest that we merge this and then check whether its working fine or not in kodadot.xyz

yup, we can test it at https://beta.kodadot.xyz tho

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 159.38 USD/KSM ~ 0.314 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x2e8a7782037ffe62634ac07dd7b318f13e6f77ed0bfad12dd397459823792e9d](https://kusama.subscan.io/extrinsic/0x2e8a7782037ffe62634ac07dd7b318f13e6f77ed0bfad12dd397459823792e9d)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
