### PR TITLE
1a Next Merge - Get rid of dashboard catalog 

### PR DESCRIPTION
**Pull request by JKrupinski**

### CODE REVIEW

**Comment by JKrupinski** [comment]
@yangwao Can you set deployment from `nft-gallery` repo?

**Comment by yangwao** [comment]
I guess once @vikiival submit that rework for subquery - would be probably bigger commit, we can merge this, let's make this on hold till then :)

**Comment by yangwao** [comment]
I see some conflicts @JKrupinski probably because #421 ?

**Comment by JKrupinski** [comment]
> I see some conflicts @JKrupinski probably because #421 ?

I'll fix conflicts during the weekend

**Comment by JKrupinski** [comment]
@yangwao  please reconfigure deployment and test if everything works

**Comment by yangwao** [comment]
Wondering why I can't resolve these conflicts from UI :| 
Okay, probably the next merged issue is yours!

**Comment by JKrupinski** [comment]
@yangwao you can test it

**Comment by yangwao** [comment]
Let me check it out https://media.giphy.com/media/MFz8M8VnWdEZmw5Jed/giphy.gif

**Pull request merged**
