### PR TITLE
sold by creator filter

### LINKED ISSUE #5453: Buy from the creator on collection
### Is your feature request related to a problem?

Can we have the option to filter NFTs only for those that are sold by the creator? 🥹
image

Our menu on the left will look less "empty". 👯

### Describe the solution you would like

Add filter sold be creator or buy from creator or something similar

### Describe alternatives you have considered

-

### Screenshots

_No response_

### Are there opened related issues?

_No response_

### PR DESCRIPTION
**Pull request by iMac7**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #5453 
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer?target=14dLrAvjDw7cFLaxM7VWR6YtHd7bGZY2QpzXDhAJJ4yv6oGw&usdamount=undefined)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screenshot_20240312_205147

### CODE REVIEW

**Comment by prury** [comment]
i think the issue specifies that it should only show the filter when you are on a collection, am i correct?
it is showing on explorer here

**Comment by vikiival** [comment]
>  filter when you are on a collection, am i correct?

Prefferably both, but I would take definition of done is to have it on collection detail

https://github.com/kodadot/nft-gallery/issues/5453#issuecomment-1493281352

> i also think we should not show this filter on gen art collections, since the owner will be always kodadot minter

Creator of NFT is always a person who called MINT :) so in case of gen drops it is always a user

**Comment by iMac7** [comment]
> > filter when you are on a collection, am i correct?
> 
> Prefferably both, but I would take definition of done is to have it on collection detail
> 
> [#5453 (comment)](https://github.com/kodadot/nft-gallery/issues/5453#issuecomment-1493281352)
> 
> > i also think we should not show this filter on gen art collections, since the owner will be always kodadot minter
> 
> Creator of NFT is always a person who called MINT :) so in case of gen drops it is always a user

@prury based on this do I still need to make changes :thinking:

**Review by preschian — COMMENTED** [review]
fix deepscan issues

**Comment by prury** [comment]
> > > filter when you are on a collection, am i correct?
> > 
> > 
> > Prefferably both, but I would take definition of done is to have it on collection detail
> > [#5453 (comment)](https://github.com/kodadot/nft-gallery/issues/5453#issuecomment-1493281352)
> > > i also think we should not show this filter on gen art collections, since the owner will be always kodadot minter
> > 
> > 
> > Creator of NFT is always a person who called MINT :) so in case of gen drops it is always a user
> 
> @prury based on this do I still need to make changes 🤔

Sorry for the delay, 
As far as i could see it is working ok for collections that are not generative art.
the problem with collections that are gen art is that the nfts are generated trough an account that is called Kodadot Minter.
So, on genart collections you will have to verify if the person who minted the nft is currently the owner of the NFT being sold, otherwise, it should not show when you filter by sold by creator.

Example:
if you go to the latest drop collection and filter by sold by creator, it doesn't show anything, probably because logic is identifying kodadot minter as creator: 

image

**Comment by prury** [comment]
> Interesting, how can I tell the difference between 'normal' and generative art? I could replicate your findings but if you told me `motherboard` collection is generative art while `convergente` is not, I would believe you 😆 Even the graphql responses look similar
> 

i think everything that we made a drop page for it is gen art, sorry for the delayed response

> edit: does kodadot minter make any nfts which are not generative?

yes, kodadot minter made some NFTs in the past that were not genart

**Comment by prury** [comment]
found one bug: 

https://github.com/kodadot/nft-gallery/assets/36627808/6d9767c2-219e-4673-982a-42d480d3451e

@iMac7 as per new guidelines defined internally, i have to close this PR due to too much back and forth and time it took for a proper solution to be presented

Please open a new PR once you find a suitable solution for the issue that has been properly tested

Regarding how things should work, i know we don't have too much instructions on how everything should be, but let's try to discuss it on the issue before PR gets opened, Ty so much.

**Comment by prury** [comment]
> @prury this filter is offline and it filters the pages that loaded. if you scroll a bit and more items load, the filter updates accordingly as in my comment above, so I believe this PR still solves the issue. Of course a more noticeable change happens in the grid when more items from page 1 are filtered out, that looks broken otherwise :D
> 

i see, but maybe it should work like the buynow filter, otherwise it would may cause confusion

i rechecked and could verify that even if i update the page with the filter on, items that are not being sold by the creator are still present as in the video: 

https://github.com/kodadot/nft-gallery/assets/36627808/e5c124d7-b98b-40f2-b5d0-3aff2f4abf6b




> I understand if updated internal guidelines require that this PR be closed. Just wanted to let you know that I learn so much from these reviews and edge cases

i do as well my friend

**Pull request closed without merging**
