### PR TITLE
Add cross env and test windows build

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] https://github.com/kodadot/nft-gallery/issues/3594#issuecomment-1198951306
  - add cross-env to support running dev on windows
  - test build with windows environments in github actions

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged the recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by preschian** [comment]
cc @petersopko

**Comment by DeluneClaire** [comment]
I'm not sure I understand what should i test; it seems to me as a code only.

**Comment by petersopko** [comment]
> I'm not sure I understand what should i test; it seems to me as a code only.

don't worry about this one, it's code only :)

**Comment by petersopko** [comment]
> cc @petersopko

let's wait for https://github.com/paritytech/smoldot/pull/2565 to test this out and see it working :)

**Comment by preschian** [comment]
> let's wait for https://github.com/paritytech/smoldot/pull/2565 to test this out and see it working :)

seems already released. because the package is too deep, need parent dependencies to update also. we can speed it up to test by forcing the package version with `overrides` to force the package version.
```json
"overrides": {
  "@substrate/smoldot-light": "^0.6.27"
}
```

| before | after |
| --- | --- |
| Screen Shot 2022-07-30 at 15 54 24 | Screen Shot 2022-07-30 at 15 54 58 |

**Comment by petersopko** [comment]
> 



> > let's wait for [paritytech/smoldot#2565](https://github.com/paritytech/smoldot/pull/2565) to test this out and see it working :)
> 
> seems already released. because the package is too deep, need parent dependencies to update also. we can speed it up to test by forcing the package version with `overrides` to force the package version.
> 
> ```json
> "overrides": {
>   "@substrate/smoldot-light": "^0.6.27"
> }
> ```

hmm, just adding this "overrides" thing doesn't help, I've added it to package.json, hit `pnpm i` and then tried build again, it still gets stuck at 0.6.25. Any idea how to achieve what you've got there on the right side @preschian ?

**Comment by preschian** [comment]
> hmm, just adding this "overrides" thing doesn't help, I've added it to package.json, hit pnpm i and then tried build again, it still gets stuck at 0.6.25. Any idea how to achieve what you've got there on the right side @preschian ?

hmm, just add this line, like in this PR. with that changes in this PR, the build was a success in windows
refer to this file, bottom line section https://github.com/kodadot/nft-gallery/blob/1dd8ba7817adc4dc24aeb6320b17d48b61128c6f/package.json
Screen Shot 2022-08-01 at 09 16 33

**Review by petersopko — APPROVED** [review]
wfm

**Review by prachi00 — APPROVED** [review]

**Comment by prachi00** [comment]
LGTM

**Comment by petersopko** [comment]
@preschian I'm wondering whether we have to have the over ride here now, since the packages and dependencies were updated? https://github.com/polkadot-js/api/commit/830871515bd738d086399c459991c1d1c0b7b3f2

**Comment by preschian** [comment]
> @preschian I'm wondering whether we have to have the over ride here now, since the packages and dependencies were updated? [polkadot-js/api@8308715](https://github.com/polkadot-js/api/commit/830871515bd738d086399c459991c1d1c0b7b3f2)

still not yet I think, latest version was released 4 days ago, and the PR just merged yesterday
Screen Shot 2022-08-03 at 15 17 09

oh, one thing. need to update the GitHub branch protection rule, because in this PR I added build for windows, and steps names were automatically renamed to `build (ubuntu-latest)` and `build (windows-latest)` from `build`

something like this:
cc @yangwao @vikiival 
Screen Shot 2022-08-03 at 15 20 45

**Comment by vikiival** [comment]
Screenshot 2022-08-04 at 13 14 45

**Comment by petersopko** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 60.85 USD/KSM ~ 1.643 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0x049fccc01e29739105279a34a909add93fb6b70af0b08c5a336aaf7a03e13f19](https://kusama.subscan.io/extrinsic/0x049fccc01e29739105279a34a909add93fb6b70af0b08c5a336aaf7a03e13f19)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
