### PR TITLE
fix: reactive identity

### LINKED ISSUE #4693: Missing Creator and Owner on item
Missing Creator and Owner

image

Seems also on old one item

https://beta.kodadot.xyz/bsx/gallery/3579963603-29?redesign=true

image

~~So probably indexer issue?~~

data are there, someone broke component? 

```json
{
    "data": {
        "nftEntities": [
            {
                "id": "3579963603-29",
                "metadata": "ipfs://ipfs/bafkreicpbr3rq7e4daebmwtf5ouzn76jyk5wgmyh7vqt6gpuxgiw7kb4te",
                "issuer": "bXmj2uCvRkyw2bUzRsxoAbNQi47EhvWvPreAb1wMKGo5VtZ8h",
                "currentOwner": "bXkaQPkcaNytoF6rAg5nbmrMy5wWGZrykUMGD39yqxvzivRTr",
                "blockNumber": "2355815",
                "burned": false,
                "updatedAt": "2023-01-13T13:18:00.312000Z",
                "__typename": "NFTEntity",
                "name": "Urban #25",
                "sn": "29",
                "price": "0",
                "collection": {
                    "id": "3579963603",
                    "name": "Hooker's Urban",
                    "__typename": "CollectionEntity"
                },
                "meta": {
                    "id": "ipfs://ipfs/bafkreicpbr3rq7e4daebmwtf5ouzn76jyk5wgmyh7vqt6gpuxgiw7kb4te",
                    "image": "ipfs://ipfs/bafybeicgb2xeaiycydd5gvtomtm7s5s3sejnjrb4tcupebywkobsq3nja4",
                    "animationUrl": "",
                    "__typename": "MetadataEntity"
                }
            }
        ]
    }
}
```

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #4693

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

Screenshot 2023-01-14 at 13 16 57

### CODE REVIEW

**Comment by Jarsen136** [comment]
> how to reproduce, open the link in incognito:
> 
> * before: https://beta.kodadot.xyz/snek/gallery/659233203-5?redesign=true

Wired, I still could not reproduce it in incognito mode on the beta env. Is it related to the cache?
image

**Review by Jarsen136 — APPROVED** [review]
It works. code lgtm

**Comment by yangwao** [comment]
yes I've noticed on bsx, not on rmrk, which is strange

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 32.22 USD/KSM ~ 1.552 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0xd279d5d44b178d4e6511ead4fd5f30393cbcad5755fca93b1330e13a45b88b3a](https://kusama.subscan.io/extrinsic/0xd279d5d44b178d4e6511ead4fd5f30393cbcad5755fca93b1330e13a45b88b3a)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
