### PR TITLE
Profile layout switch

### LINKED ISSUE #1170: Add pagination under collected
Hey seems #1166 blown out pagination on the top of the collected tab.
Once you attention is there let's put layout switcher to the pagination for collections on artist as well

https://main--nftkodadot.netlify.app/rmrk/u/CdA62JpyfEyEASA5XKYJAyYZmdQPqe5X9x8MLnoTWtc9rNn?tab=collected
image

https://main--nftkodadot.netlify.app/rmrk/u/CdA62JpyfEyEASA5XKYJAyYZmdQPqe5X9x8MLnoTWtc9rNn?tab=collection
image

Please check it on sold tab as well
image

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the KodaDot NFT gallery.

👇 Do a quick check before the merge. 

### PR type
- [x] Bugfix
- [ ] Feature
- [x] Refactoring

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested PR on mobile and everything works
- [ ] I found edge cases

### What's new?
- [x] PR closes #1170
- [ ] <brief_description_of_what_I've_added>

### Had issue bounty label ?
- [x] Fill up your KSM address: 
[Payout](https://kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation
- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [x] My fix has changed **something** on UI, a screenshot for others, is best to understand changes
Screenshot 2021-11-16 at 8 48 37 PM

### CODE REVIEW

**Comment by yangwao** [comment]
Payout sent https://kusama.subscan.io/extrinsic/10122675-3
If code is okay after @roiLeo review, let's merge it to `main` :)

**Review by roiLeo — APPROVED** [review]
LGTM but this would break #1170, I still prefer my solution

**Comment by yangwao** [comment]
> ... I still prefer my solution

You mean https://github.com/kodadot/nft-gallery/pull/1179 ?

**Comment by yangwao** [comment]
I've merged https://github.com/kodadot/nft-gallery/pull/1179 so this PR is obsolete or we can reuse something?

**Comment by vikiival** [comment]
Closing in favour of #1179

**Pull request closed without merging**
