### PR TITLE
feat: On teleport should be selected related pair of chain

### LINKED ISSUE #8021: On teleport should be selected related pair of chain?
https://kodadot.xyz/ahk/teleport I'm selected on AHK and suggest in teleport is Polkadot.

I think it should be Kusama and Kusama Assets Hub.

image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Feature

  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #8021
  - [ ] Requires deployment <snek/rubick/worker>

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

image

  ## Copilot Summary
  
### <samp>🤖 Generated by Copilot at d9f4e21</samp>

Added chain switching functionality to `Teleport.vue` component. It detects the chain name from the URL prefix and updates the state and UI accordingly.

  
### <samp>🤖 Generated by Copilot at d9f4e21</samp>

> _To switch chains with ease and no glitch_
> _The `Teleport.vue` got a switch_
> _It uses `usePrefix`_
> _And `prefixToChainMap`_
> _To set `fromChain` and the UI niche_

### CODE REVIEW

**Review by daiagi — APPROVED** [review]
lgtm

**Comment by yangwao** [comment]
Can we  make it default Kusama -> Kusama Assets Hub?

As we will deprecating BSX..
This is what I've got landing on https://deploy-preview-8025--koda-canary.netlify.app/ksm/teleport

image

otherwise good!

**Comment by prury** [comment]
> As we will deprecating BSX.. 
any dates for when it will happen?

**Comment by Jarsen136** [comment]
> Can we make it default Kusama -> Kusama Assets Hub?
> 
> As we will deprecating BSX.. This is what I've got landing on https://deploy-preview-8025--koda-canary.netlify.app/ksm/teleport
> 
> image
> 
will check it

**Comment by yangwao** [comment]
thanks!
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 5.51 USD/DOT ~ 3.63 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x0cba914315ee96822abd24c17de9b2ca3ca1b15042cbf12e44fcfe239597fa61](https://polkadot.subscan.io/extrinsic/0x0cba914315ee96822abd24c17de9b2ca3ca1b15042cbf12e44fcfe239597fa61)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
> any dates for when it will happen?

I think end of year something, goal is migration could work for BSX users if any tho lol

**Pull request merged**
