### PR TITLE
feat: fixed container width on super wide screen

### LINKED ISSUE #7703: Remove full width and back to fix width 1280px on gallery item?
I found our gallery item looks not so great on super wide as feels more like random trashed information around.

wyt @exezbcz

### PR DESCRIPTION
**Pull request by newraina**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 \_\_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #7703 
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer?target=1CAv6Zq3yVxL3eKhC94GWTWVwp1w4jZbqeZ6wXx1rPAhrce&usdamount=0&donation=true)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

The container width of the gallery item is fixed to 1344px when the screen width exceeds 1440px.

CleanShot 2023-10-28-Kh582O9P@2x

### <samp>🤖 Generated by Copilot at 2b8ace8</samp>

This pull request introduces a new layout component `gallery-item-layout.vue` that is used for displaying gallery items (NFTs) and their collections with a consistent UI and SEO features. The pull request also applies this layout to the existing pages that show the details and the gallery of NFTs based on their prefix and id.

### <samp>🤖 Generated by Copilot at 2b8ace8</samp>

> _`gallery-item-layout`_
> _A new component for NFTs_
> _With navbar and footer_

### CODE REVIEW

**Comment by exezbcz** [comment]
nice job, thank you. 


I am now thinking whether move the breakpoint to the 1920px 

what do you think guys?

**Comment by newraina** [comment]
> nice job, thank you.
> 
> I am now thinking whether move the breakpoint to the 1920px
> 
> what do you think guys?

@exezbcz OK for me, easy to change.

It's true that 1440 isn't very wide.

**Comment by yangwao** [comment]
> I am now thinking whether move the breakpoint to the 1920px

let's stick now with 1440p and let see

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 4.21 USD/DOT ~ 7.126 $DOT
🧗 [1CAv6Zq3yVxL3eKhC94GWTWVwp1w4jZbqeZ6wXx1rPAhrce](https://polkadot.subscan.io/account/1CAv6Zq3yVxL3eKhC94GWTWVwp1w4jZbqeZ6wXx1rPAhrce)
🔗 [0x7b0a943e0aff426f2796507d1e3e22ff6cecb1a4d6fb5a6ed8032d65e9b4a6c5](https://polkadot.subscan.io/extrinsic/0x7b0a943e0aff426f2796507d1e3e22ff6cecb1a4d6fb5a6ed8032d65e9b4a6c5)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
