### PR TITLE
:bug: navbar on big touch devices

### LINKED ISSUE #4685: Navbar at big touch devices is broken
> So is that oki? Bit confused that you wrote oki and removed label @exezbcz
> 
> image

nope, the bug is still there. 

image

- the navbar on big touch devices is broken. 

Probably it was fixed in
- #4622

Close if done so

_Originally posted by @exezbcz in https://github.com/kodadot/nft-gallery/issues/4580#issuecomment-1381939698_

### PR DESCRIPTION
**Pull request by petersopko**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4685 
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

Before:
image

After: 
image

### CODE REVIEW

**Comment by exezbcz** [comment]
hmm, looks like its fixed but when resizing the screen and switching from mobile size to tablet size, it still isnt ideal. 

### step one:
image

### step two: 
- swithing to mobile view

**Comment by exezbcz** [comment]
somehow reproduced it in chrome. I think its when switching from mobile to desktop mode and resizing it in responsive mode. 
image

**Comment by petersopko** [comment]
> somehow reproduced it in chrome. I think its when switching from mobile to desktop mode and resizing it in responsive mode. 

That definitely shouldn't happen.

I'm trying to reproduce this right now (along with your comment from yesterday), and I'm failing to do so 🤔 

I know why it happened before -> We were differentiating the navbar based on device type, i.e., mobile(touch) and desktop.

But we've switched from that to caring only about the device's viewport, so that should adjust accordingly.

@exezbcz I've pushed some changes to remove unused code, can you try to update the app and try again?

**Comment by exezbcz** [comment]
> > somehow reproduced it in chrome. I think its when switching from mobile to desktop mode and resizing it in responsive mode.
> 
> That definitely shouldn't happen.
> 
> I'm trying to reproduce this right now (along with your comment from yesterday), and I'm failing to do so 🤔
> 
> I know why it happened before -> We were differentiating the navbar based on device type, i.e., mobile(touch) and desktop.
> 
> But we've switched from that to caring only about the device's viewport, so that should adjust accordingly.
> 
> @exezbcz I've pushed some changes to remove unused code, can you try to update the app and try again?

i reproduced it on the beta, seems like here its fixed.
Tried it on chrome for ipad and safari, the issue is only with chrome when resizing and using split screen. 

When adjusting the navbar on mobile, we should be extra cautious because it could break this again.

**Comment by petersopko** [comment]
> i reproduced it on the beta, seems like here its fixed.

okay, if there are any issues with this branch (not beta, we are fixing the beta here), let me know 😄

**Comment by exezbcz** [comment]
> > i reproduced it on the beta, seems like here its fixed.
> 
> okay, if there are any issues with this branch (not beta, we are fixing the beta here), let me know 😄
> 
> // still weird you got that result on this deploy before

yup, i mentioned that because you wrote that you dont know how to reproduce this earlier :D Nothing important

**Comment by yangwao** [comment]
pay 20

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 31.49 USD/KSM ~ 0.635 $KSM
🧗 [FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y](https://kusama.subscan.io/account/FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y)
🔗 [0xc5585c49ff01b2db799707a7a2813b22f11dbc98423d55dec859cc1d18d9b1ff](https://kusama.subscan.io/extrinsic/0xc5585c49ff01b2db799707a7a2813b22f11dbc98423d55dec859cc1d18d9b1ff)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
