### PR TITLE
fix: Paid mint modal auto-teleport flow

### LINKED ISSUE #10253: Paid mint modal closes if transaction `errors` while `auto teleporting`
### What happened?

Mint modal closes when mint action is cancelled, if the bellow is not implemented  , mint flow should work the same after an error occurs and be able to move to the success step

https://github.com/kodadot/nft-gallery/assets/44554284/35607850-78cd-49a4-ba5c-7a8bab7ebb9b

## only one modal at a time 

probably the auto teleport flow should be the same as the normal mint

normal: overviews -> signing modal -> success 
auto-teleport: overview -> open auto teleport modal (close PaidMint.vue ) -> on success open it again 

if you close at any point it starts from scratch 

this way we don't have the two modals overlapping when doing auto-teleport

like this 

CleanShot 2024-05-07 at 12 16 48@2x

and there is always **only one**

wdyt @exezbcz ?

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

> option 2 , have always one, once auto-teleport modal is open the below one is gone and once the teleport is done the other one appears with the success step

1. paid mint auto-teleport flow changed (only one modal at a time)
2. fix: minting session getting cleared on mint cancel when doing teleport

@prury pls test theses 3 flows 

-  normal flow 
- autoteleport flow
- mutiple autotelport in one session 
 
I've attached bellow videos for each one , thanks 

- [x] Closes #10253

## Needs QA check

- @kodadot/qa-guild please review

## Needs Design check

- @exezbcz please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

## paid mint auto teleport 

https://github.com/kodadot/nft-gallery/assets/44554284/c2d8e919-0bbd-44c3-88ce-99befde27168

## paid mint normal flow 

https://github.com/kodadot/nft-gallery/assets/44554284/6b3a867f-366c-42b9-b1bf-81d0c1e1784b

## testing multiple autotelport in one session

https://github.com/kodadot/nft-gallery/assets/44554284/5e7c5963-37c2-42ab-bbe1-d658dfbe198a

### CODE REVIEW

**Comment by prury** [comment]
i was testing and normal flow went ok, but then i started facing issues with auto-teleport that we are solving in #10264 , let's wait for it to be merged

**Comment by hassnian** [comment]
> i was testing and normal flow went ok, but then i started facing issues with auto-teleport that we are solving in #10264 , let's wait for it to be merged. So far one modal at time was working ok

What drop are you using to do the tests ? I tested it with meadow and worked fine , didn't face that issue once 

#10264 it's only happening with hdd drop isn't ? 

These two issue are not related , but we can wait if the balance check issue is happening  in other drops

**Comment by prury** [comment]
> These two issue are not related , and should be able to be solved independently , but we can wait.
> 
> Is the balance check issue also happening in other drops ?

sorry for the lack of info, but yes, it also happened on meadow.

**Comment by vikiival** [comment]
cc @daiagi

**Review by daiagi — APPROVED** [review]

**Comment by vikiival** [comment]
cc @prury ?

**Comment by prury** [comment]
> cc @prury ?

i was OOO
but now i can test this one properly as the other two PRs needed have been merged

**Comment by prury** [comment]
@hassnian i think we are good, only thing i was found uncommon was loading modal between some steps(1:56), but its coming from canary, so.

overlapping modals seems to be solved, and modals seems to be appearing in right places at the right time.

whole autoteleport + autoteleport process:

[Gravação de tela de 16-05-2024 10:25:55.webm](https://github.com/kodadot/nft-gallery/assets/36627808/9e6bd064-7426-4c7c-8ec5-ccf84c5b5a7a)

**Comment by vikiival** [comment]
@JustLuuuu can u please check?

**Review by vikiival — APPROVED** [review]

**Pull request merged**
