### PR TITLE
💅 customize collection

### PR DESCRIPTION
**Pull request by roiLeo**
ref #8037 

Screenshot 2023-11-13 at 15-59-00 GenArt

// TODO:
- <s>tx `set_collection_max_supply`</s>
- informative text
- test it

### CODE REVIEW

**Comment by AshutoshSingh00001** [comment]
I think you should not limit their minimum supply it would feel much centralised

**Comment by exezbcz** [comment]
@roiLeo woho I approve 

I would maybe switch the font weights

Customize collection - bold 
maximum NFTs .... - regular

**Comment by AshutoshSingh00001** [comment]
@roiLeo I don't think we should add this one this will let creators to change maxSupply time to time it won't make any sense of setting maxSupply for them

**Comment by AshutoshSingh00001** [comment]
> > @roiLeo I don't think we should add this one this will let creators to change maxSupply time to time it won't make any sense of setting maxSupply for them
> 
> if it's possible why not?

if it's possible got for it

**Comment by vikiival** [comment]
> @roiLeo loader not showing now, not before and not after

Or it is hidden behind the modal :)

**Comment by AshutoshSingh00001** [comment]
> > [quick and dirty](https://github.com/kodadot/nft-gallery/pull/8045/commits/21b68c5be6dd8210ad969fd5ce792d6d21456ceb)
> 
> giphy-3 [ giphy-3 ](https://private-user-images.githubusercontent.com/22471030/287728712-d82372be-27df-4bcd-b6e5-77670cee49e1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MDAzMjgsIm5iZiI6MTcwMTcwMDAyOCwicGF0aCI6Ii8yMjQ3MTAzMC8yODc3Mjg3MTItZDgyMzcyYmUtMjdkZi00YmNkLWI2ZTUtNzc2NzBjZWU0OWUxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDE0MjcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkMTQ0N2NjNmI1MDM0OTcyNjEyODFiODJjMjIzM2Y3MWRlNDNjNDU5MGUwZWQyZmI4YzdlODJkZjQ1NzBiYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aJq6-LvI3fINzIFIZLGkI3uzejLE4MsPrkWUx5qHvvE) [ ](https://private-user-images.githubusercontent.com/22471030/287728712-d82372be-27df-4bcd-b6e5-77670cee49e1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MDAzMjgsIm5iZiI6MTcwMTcwMDAyOCwicGF0aCI6Ii8yMjQ3MTAzMC8yODc3Mjg3MTItZDgyMzcyYmUtMjdkZi00YmNkLWI2ZTUtNzc2NzBjZWU0OWUxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDE0MjcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkMTQ0N2NjNmI1MDM0OTcyNjEyODFiODJjMjIzM2Y3MWRlNDNjNDU5MGUwZWQyZmI4YzdlODJkZjQ1NzBiYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aJq6-LvI3fINzIFIZLGkI3uzejLE4MsPrkWUx5qHvvE)

😂

**Comment by prury** [comment]
what happens if i set max numbers in collection to 5 but it has more than 5 there already?

**Comment by roiLeo** [comment]
> what happens if i set max numbers in collection to 5 but it has more than 5 there already?

will produce error

**Comment by prury** [comment]
> > what happens if i set max numbers in collection to 5 but it has more than 5 there already?
> 
> will produce error

correct, form won't let me

**Comment by prury** [comment]
@roiLeo only problem i see now is not being able to close loader

**Comment by prury** [comment]
> > @roiLeo only problem i see now is not being able to close loader
> 
> humm, this could be an issue with loader then, I'm just calling the loader instance when transaction is init and closing it when finalized

related to collection page... let me open an issue

**Pull request merged**
