### PR TITLE
fix: balance fetching bugs

### LINKED ISSUE #10933: `Sub` wallet balance not loading when `evm` chain is selected
### What happened?

CleanShot 2024-09-05 at 10 44 05@2x

CleanShot 2024-09-05 at 10 44 39@2x

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #10933
- [x] Fixes: sub wallet malformatted
    - if sub wallet is connected and user lands on `/base` the address is not formatted correctly   
- [x] Fix: on wallet switch balance from others are not cleared

https://github.com/user-attachments/assets/b368d495-7858-4fc5-88bd-c9bcfcdd1865

- [x] Fixes: wallet `vm` and chain `vm` mismatch balance fetch using `identityStore.fetchBalance` 

covers case where wallet vm and current chain's vm do not match, since prefix is unknown at that moment we are resorting to a fallbacks instate of not making a balance fetch

### Example

evm wallet is connected , chain is ahp , navbar makes a balance fetch

this happens in the navbar and sidebar, in these scenarios what prefix should be fetched ?

@kodadot/internal-dev  pls feel free to suggest any other solution.

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

https://github.com/user-attachments/assets/0c8d1f72-a3e4-4653-9c55-5804c6665a4a

### CODE REVIEW

**Comment by Jarsen136** [comment]
> evm wallet is connected , chain is ahp , navbar makes a balance fetch
>
> this happens in the navbar and sidebar, in these scenarios what prefix should be fetched ?

IMO, the balance should always match the current connect wallet.
For example:
Connect with EVM wallet: fetch balance on base \ mantle etc.
Connect with SUB wallet: fetch balance on ahp\ahk\dot etc.

**Comment by hassnian** [comment]
> > evm wallet is connected , chain is ahp , navbar makes a balance fetch
> > this happens in the navbar and sidebar, in these scenarios what prefix should be fetched ?
> 
> IMO, the balance should always match the current connect wallet. For example: Connect with EVM wallet: fetch balance on base \ mantle etc. Connect with SUB wallet: fetch balance on ahp\ahk\dot etc.

you mean if `identityStore.fetchBalance` is called it should fetch all chains under that vm ?

if evm wallet is connected and you are on `ahp` chain what chain should the balance be fetched, 'base', 'imx' , etc
same when a sub wallet is connected and you are on evm chain.

let me know if it makes sense.

**Comment by Jarsen136** [comment]
> if evm wallet is connected and you are on `ahp` chain what chain should the balance to be fetched, 'base', 'imx' , etc

It's also what I want.

> same when a sub wallet is connected and you are on evm chain.

I'm not sure what you mean by the `same`. In this case, it should shows all the balance on sub, `dot` `ahp` `ahk` etc.


In short,  the balances should always correspond to the type of wallet, regardless of the network prefix.

**Comment by vikiival** [comment]
pls @kodadot/internal-dev waiting for review 🥺

**Review by Jarsen136 — APPROVED** [review]
work for me

**Review by preschian — APPROVED** [review]

**Pull request merged**
