### PR TITLE
fix: fallback to mp4 thumbnail

### LINKED ISSUE #6050: Collection view doesn't load
### What happened?

https://canary.kodadot.xyz/stmn/collection/18?collectionId=18

image

### Please reproduce in steps

Missing pictures

### Expected Behavior

Pictures loaded :)

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

_No response_

### Are you logged in?

No

### Which wallet you are using?

PolkadotJS

### Screenshots

reason? 
image

### Relevant log output

_No response_

### Payment link for reward

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Related #6050

https://deploy-preview-6080--koda-canary.netlify.app/stmn/collection/18?collectionId=18
image

image

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

### <samp>🤖 Generated by Copilot at f87bdc2</samp>

Updated the carousel and collection banner components to use the `MediaItem` component from the `@kodadot1/brick` library, which handles different media types and metadata. Improved the `ImageMedia` component to handle video media more efficiently and gracefully. Added utility functions for video thumbnails and local storage access to the `MediaItem` folder.

### <samp>🤖 Generated by Copilot at f87bdc2</samp>

> _To handle media items with ease_
> _We imported `MediaItem` from `brick` library_
> _It has a `rootClasses` prop for style_
> _And uses `utils.js` for video file_
> _This makes the code more consistent and reusable, you see_

### CODE REVIEW

**Comment by preschian** [comment]
this is a kinda temporary fix

I think it's better to unify some fields and add mime-type from the indexer side. on `rmrk v1`, the `image` field is only for static images, and all animated media are on the `animation_url` field. on the other chain, the `image` field can be any format

I found that on `rmrk v1`, `meta.type` is for the mime type only. but, on `rmrk v2` it can be anything. example:

<table>
<tr>
    <th>rmrk v1</th>
    <th>rmrk v2</th>
</tr>

<tr>
<td>
<pre>{
  "id": "7522506-900D19DC7D3C444E4C-AIW-AI_WOMAN-0000000000000001",
  "name": "AI woman",
  "meta": {
    "id": "ipfs://ipfs/QmVRPTEtZ7pwShvNYTxyPTE7XDzEPpwYunPhr23RFBw5aY",
    "type": "video/mp4"
  }
}
</pre>
</td>

<td>
<pre>{
  "id": "14336459-560189524f21b73a25-AXECOLLECTION2-MARKER-00002579",
  "name": "Marker of Endlessness",
  "meta": {
    "id": "ipfs://ipfs/bafybeifwsdvejxy45zzuuyyoey4wov3ftyj3ak6f7yrdqremr5apbs2474/metadata.json",
    "type": "Marker"
  }
}
</pre>
</td>
</tr>
</table>

**Review by roiLeo — COMMENTED** [review]
Loading is really really slow, maybe this could be fix if we spin up again indexer to fetch metadata

from https://github.com/kodadot/nft-gallery/issues/6050#issuecomment-1556900061 
> should we show videos player or placeholder image (thumbnail)?

**Comment by preschian** [comment]
> is it possible to save `mime-type` value directly from indexer? I thought we set only metadata without seeing the content

not sure if is it possible or not. if not possible maybe we need another service that needs to unify the nft metadata 🤔

**Comment by prury** [comment]
So far:
image

**Comment by preschian** [comment]
btw, fix in this PR is still not optimal, I think we need to find a way to unify the nft metadata https://github.com/kodadot/workers/issues/95

**Comment by vikiival** [comment]
Hey, since this has been open for a month without any progress I opt in to close this issue and continue in discussion.
Seems like it's deeper issue that can be optimally solved with your help, Please continue in 
https://github.com/kodadot/nft-gallery/discussions/4754#discussioncomment-6281383

**Pull request closed without merging**
