### PR TITLE
fix: wallet connect default project id

### LINKED ISSUE #10418: EVM Wallet init failed on localhost environment
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

EVM Wallet init failed on localhost environment 

### Please reproduce in steps

1. switch to branch `feat/evm/v0`
2. setup everything and try to connect the wallet
3.  EVM Wallet could not init so you can't connect wallet

### Screenshots

image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Context

- [x] Closes #10418

### CODE REVIEW

**Comment by hassnian** [comment]
not sure about adding a default one, each dev can get their own `WALLET_CONNECT_PROJECT_ID` pretty easily (maybe we should add this to our docs)
- https://cloud.walletconnect.com/sign-in
- create project 
- telegram-cloud-photo-size-4-5961056905247965492-y
 
and if we wanted to add a default one, would make sense to use koda's not a random one, wdyt?

**Comment by Jarsen136** [comment]
> not sure about adding a default one, each dev can get their own `WALLET_CONNECT_PROJECT_ID` pretty easily (maybe we should add this to our docs)
> 
> * https://cloud.walletconnect.com/sign-in
> * create project
> * telegram-cloud-photo-size-4-5961056905247965492-y

I understand everyone can create their own project id on wallectconnect. However, It is a hindrance to all developers who have just started the project. In this case, I have to signup an account on a third-party website to connect the wallet. 

I would simply provide the default public id or share the testing id across the internal-team members. Let me know if there is any disadvantage to using the public id.

@vikiival wdyt

**Comment by vikiival** [comment]
if the public id is usable, I am ok with that for testiing purposes

**Comment by Jarsen136** [comment]
> if the public id is usable, I am ok with that for testiing purposes

Without the id, the wallet modal even dose not show up.
With the default id, at least I can connect the browser wallet on local env. It still does not work if I want to connect with WalleConnect.
image

**Review by hassnian — APPROVED** [review]

**Pull request merged**
