### PR TITLE
feat: Wallet connect dialog init

### LINKED ISSUE #4405: Wallet connect dialog v2
connected with: 
- #4144 
- #4303 
- https://github.com/kodadot/nft-gallery/issues/4720

## Basics
landing page - main (2)

- this is how it will look like when you open the sidebar on 
- darker screen, black bg with 17% opacity
- I experienced with background blur but its not that usable when then displaying wallet. 

### warning 
- confirmation
image
- primary button there

### Connect wallet
Wallet providers as dropdowns, you can only see wallet you have downloaded. 
Other wallet are hidden under "more option" 
- these wallets have icon next to it co it indicates you can download them. 

At the bottom there is dialog with introducing into wallets and link to a educational video in case you are a beginner. 
Connect wallet-hover1 (2)

### Wallet
- we are moving it to the sidebar
Connect wallet-hover1 (1)

### hover states
wallet provider: 
- same as the search results, when you hover over, the background turns into k-accentlight2 (lighter version than k-accentlight), in dark mode its k-accentlight2dark
image

sub-select: 
- when you click the chevron turns down and reveals your accounts. 
- there is a name and short adress
- next to the icon there is line, like in vscode etc. (its clear that its sub section) 
- the line is only big as the max height of the content
- hover effect starts at the line but is slightly bigger vertically, should have same size as the wallet provider hovers. 
- there are different screens that show it. 
this shows the hover on account: 
image

More options: 
default state is k-grey, when hovering it turns into k-black
- when clicking it displays the other options/wallets you can download

Cross icon: 
turn into k-hovergrey, in case of darkmode its k-shade. 

there is a close button at the top right in every sidebar + a clickable button (with left chevron) you can use to close it as well. 
image

### Mobile
on mobile the wallet section in menu stays the same. We wont change it.
We are going to change only the connect part. 
It will popup over the whole page - it should be a overlay so once you close it you stay where you had been last time.

### Darkmode
pretty straightforward, hover on the bigger areas have k-accentlightdark instead of the k-accentlight2.
If you have any questions about the dark mode feel free to ping.

### Figma
designs are now available in gallery item handoff. 
image
https://www.figma.com/file/gHSzqGPeQ9qK4L0qIDcTjY/gallery-item-handoff?node-id=1270%3A5615&t=s0dzfVDc0DFz66R4-1

Thanks!

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [x] Refactoring

## Context

- [x] Closes #4405
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

image

### CODE REVIEW

**Comment by Jarsen136** [comment]
TODO:
- [ ] dark mode
- [ ] some visual details

**Comment by Jarsen136** [comment]
I have made two follow-up issues:
#4829 redesign: asset page in wallet dialog
#4830 redesign: icons in wallet dialog redesign

Once the current PR is merged, I will continue taking these leftover issues.

**Comment by exezbcz** [comment]
## Feedback
### Warning
image
- in design there is button with only 16px, it makes sense to make it larger but this does not look good. Also can you change the chevron? 
- the close button looks weird in dark mode - it has circle around. 

### Connect wallet
- there are some weird pixels in the middle when you open the sidebar
image
- can we make the wallet and account container same height so when you hover over the background lines up if that makes sense? Now there is a gap between them, which is good, but the background should be there as well. like here:
image
- the address text should not change to grey when hovering. 

### Dark mode
image
hover over account/wallet should be k-accentlightdark

###General
image
- make the opacity smaller please
Chevrons and icons: they look imo bad and they ruin the visual because they are too bold, could not we use for example material design icon set? 
image


Otherwise really nice job, thanks!

**Comment by Jarsen136** [comment]
> ## Feedback

Hey, @exezbcz  thanks for your detailed feedback! Now, most of the issues in the feedback have been solved, except for some icons that did not match the design. Could you pls check again?

>Chevrons and icons: they look imo bad and they ruin the visual because they are too bold, could not we use for example material design icon set?

I have made an issue for these icons, because they depend on which icon set we would like to use.
https://github.com/kodadot/nft-gallery/issues/4830 redesign: icons in wallet dialog redesign

**Comment by exezbcz** [comment]
Yup, here we go again :D Those are just some minor issues. 
### 1
image
- maybe display them all when user does not have any wallet? Now he has to click to see more. 
### 2
image
hover over cross please cursor -> pointer
### 3
image
add top margin 16px - in this case it may not line up (the background on hover)
### 4
image
- padding 10px and 32px
image

### 5 
wallet names please only the first letter capital

### 6 
padding of "more" 
top = 16px
image


### Touch devices
- can we make the side bar convert to full width page when the side bar takes up more than 1/2 of viewport width? 


I guess feel free to create separate issue for this

**Comment by Jarsen136** [comment]
> Yup, here we go again :D Those are just some minor issues.
> 
> ### 1

> 
> * maybe display them all when user does not have any wallet? Now he has to click to see more.
> 
> ### 2
> hover over cross please cursor -> pointer
> 
> ### 3
> add top margin 16px - in this case it may not line up (the background on hover)
> 
> ### 4
>
> 
> * padding 10px and 32px
>   
> 
> ### 5
> wallet names please only the first letter capital
> 
> ### 6
> padding of "more" top = 16px 
> ### Touch devices
> * can we make the side bar convert to full width page when the side bar takes up more than 1/2 of viewport width?
> 
> I guess feel free to create separate issue for this

✅ Fixed all of them. Pls check @exezbcz

**Review by roiLeo — APPROVED** [review]
🧪 ✅ wfm
⏳ code

**Comment by exezbcz** [comment]
last changes 👀 
image
- center align on x axis 
image
can you add margin to the sub-items, the line is closer to the edge of the sidebar than it should and is not also aligned with the content above. (vertically) 

the rest works

**Comment by Jarsen136** [comment]
> * argin to the sub-items, the line is closer to the edge of the sidebar than it should and is not also aligned with the content above. (vertically)


> last changes 👀 image
> 
> * center align on x axis
>   image
>   can you add margin to the sub-items, the line is closer to the edge of the sidebar than it should and is not also aligned with the content above. (vertically)
> 
> the rest works

✅ fixed.

**Comment by exezbcz** [comment]
I could have written it incorrectly.
image

**Comment by Jarsen136** [comment]
> 
> finish line soon? 🏁 xd

✅ DONE

**Comment by exezbcz** [comment]
> > finish line soon? 🏁 xd
> 
> ✅ DONE



> > finish line soon? 🏁 xd
> 
> ✅ DONE

yes

**Comment by yangwao** [comment]
pay 70 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $70 @ 37.22 USD/KSM ~ 1.881 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xa118d6680942f798c805e2cc60358ce554d331f167eb32bf02e01a7d29a11a77](https://kusama.subscan.io/extrinsic/0xa118d6680942f798c805e2cc60358ce554d331f167eb32bf02e01a7d29a11a77)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
