### PR TITLE
Airdrops for Asset Hub Polkadot & Kusama  #6247  #6248

### LINKED ISSUE #6247: Airdops for Statemine
As we have on RMRK1 a simple mint option to have airdrops - I would create this also for Statemine. 
Ideally, something simple - with an option to do an airdrop into the existing collection (if possible). 

And name it airdrop - or create a design for it or somehow add it to a simple mint in a way that artist will understand it (@EthVlad). So people can easily find (and use) this feature. 

Currently, on Kusama you need to first set a higher number of editions and then open a hidden setting to add addresses. That is not very user-friendly and also not intuitive at all. 
Screenshot 2023-06-16 at 10 58 50

### LINKED ISSUE #6248: Airdrops for Statemint
As we have on RMRK1 a simple mint option to have airdrops - I would create this also for Statemint. 
Ideally, something simple - with an option to do an airdrop into the existing collection (if possible). 

And name it airdrop - or create a design for it or somehow add it to a simple mint in a way that artist will understand it (@EthVlad). So people can easily find (and use) this feature. 

Currently, on Kusama, you need to first set a higher number of editions and then open a hidden setting to add addresses. That is not very user-friendly and also not intuitive at all. 
Screenshot 2023-06-16 at 10 58 50

### PR DESCRIPTION
**Pull request by AshutoshSingh00001**
Thank you for your contribution to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz/).

👇 __ Let's make a quick check before the contribution.

## PR Type
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #6247
- [x]  Closes #6248
- [x] ## Did your issue had any of the "$" label on it?
- [x] My DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=158VTDxZJidzsMcAdh7h828domveRvpmk1SCxwLUEHhcgY4v&usdamount=0&donation=true)

### CODE REVIEW

**Comment by roiLeo** [comment]
Not valid, I'm closing this one

**Comment by AshutoshSingh72** [comment]
> Not valid, I'm closing this one

Had some issues

**Comment by AshutoshSingh00001** [comment]
@roiLeo why and how it is invalid

**Comment by roiLeo** [comment]
> @roiLeo why and how it is invalid

your code is not working, changes has nothing to do with issue linked and you touched a sensitive part.

**Comment by AshutoshSingh00001** [comment]
> > @roiLeo why and how it is invalid
> 
> your code is not working, changes has nothing to do with issue linked and you touched a sensitive part.

ok so you mean these changes don't make any sense with linked issue , ok so I shouldn't wok more on this issue

**Pull request closed without merging**
