### PR TITLE
Add PolkaGate Extension

### PR DESCRIPTION
**Pull request by AMIRKHANEF**
## Description
This pull request aims to add the PolkaGate extension to the KodaDot (KodaArt) platform.

## Changes Proposed

- [x] Integration of the PolkaGate extension as a login option.

## Motivation and Benefits
**Improved User Experience:** The addition of the PolkaGate extension will offer users an alternative and secure login method.

**Enhanced Accessibility:** It will make it easier for users of the Polkagate extension to engage with the KodaDot (KodaArt) community.

**Community Contributions:** This integration aligns with our commitment to contributing to the broader community and improving the KodaDot (KodaArt) platform.

## Screenshots
image
image
image
image

### CODE REVIEW

**Review by preschian — APPROVED** [review]
hi, thank you for the PR 🚀

**Comment by AMIRKHANEF** [comment]
Hi, should I update this branch? I can see it says 'This branch is out of date with the base branch.'

**Comment by preschian** [comment]
> Hi, should I update this branch? I can see it says 'This branch is out of date with the base branch.'

not necessary

can we get one more reviewer? cc @kodadot/internal-dev

**Review by Jarsen136 — APPROVED** [review]
LGTM

**Comment by AMIRKHANEF** [comment]
Thanks @preschian and @Jarsen136 for your review!

**Comment by vikiival** [comment]
Hey,
thanks for the PR.

How much users currently use PolkaGate? 
I honestly learnt about it last week.

**Comment by AMIRKHANEF** [comment]
> Hey, thanks for the PR.
> 
> How much users currently use PolkaGate? I honestly learnt about it last week.

Hi @vikiival,

PolkaGate is a verified extension wallet for the Polkadot and Kusama ecosystems, funded by the Kusama treasury.
More information about PolkaGate can be found on the [Polkadot Wiki](https://wiki.polkadot.network/docs/wallets-and-extensions#browser-extensions).

You can find PolkaGate on the Chrome Store [here](https://chromewebstore.google.com/detail/polkagate-the-gateway-to/ginchbkmljhldofnbjabmeophlhdldgp?hl=en). The number of users currently using it can also be seen there.

PolkaGate is also integrated as a login option for the Staking dashboard, Subsquare, and PolkaAssembly, making it a valuable tool for interacting with the Polkadot ecosystem.

Feel free to check it out and let me know if you have any questions!

**Comment by AMIRKHANEF** [comment]
Thanks for merging the PR, we really appreciate it.

**Pull request merged**
