### PR TITLE
fix: One decimal in top collections should be enough

### LINKED ISSUE #8901: One decimal in top collections should be enough
Until dot costs $100, it's not worth having more than 1 decimal on landing.

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix

  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #8901
  - [x] Fix: decimal props does not work on Money component

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI
image

  ## Copilot Summary
  copilot:summary

  copilot:poem

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]

**Review by preschian — APPROVED** [review]

**Comment by prury** [comment]
explorer now shows an extra 0 after values compared to canary: 
image

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 7.32 USD/DOT ~ 4.098 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x136715de0955885971119daff7ee01e5eed139edad30fe44ff2ca42f158636e0](https://polkadot.subscan.io/extrinsic/0x136715de0955885971119daff7ee01e5eed139edad30fe44ff2ca42f158636e0)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by roiLeo** [comment]
Wait I think this change breaked something

**Pull request merged**
