### PR TITLE
🔧 sort by Sequence

### LINKED ISSUE #6226: Sort Option was added back but wont work properly
### What happened?

Related comments: 
https://github.com/kodadot/nft-gallery/pull/6132#issuecomment-1571805228
https://github.com/kodadot/nft-gallery/pull/6132#pullrequestreview-1449661010

Also needs renaming, maybe Sort by: "Sequence"? 

or add both Alphabetical Order and Sequence as different options.

### Please reproduce in steps

Explore - Items -> Sort

### Expected Behavior

Should sorted sequentially

nft #001, nft#002, nft#003...

### What browsers are you seeing the problem on?

Desktop Firefox

### At which address did you encounter bug?

canary.kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

_No response_

### Screenshots

image

### Relevant log output

_No response_

### Payment link for reward

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by roiLeo**
Closes #6226 

Tested on `/rmrk/collection/08C79124CAC59DC643-BOREDBARRO?collectionId=08C79124CAC59DC643-BOREDBARRO&sort=instance_ASC`

Capture d’écran 2023-06-15 à 11 49 14 AM

### CODE REVIEW

**Comment by vikiival** [comment]
This would fail on any other chains than rmrk/ksm

**Comment by roiLeo** [comment]
> This would fail on any other chains than rmrk/ksm

Should I close it or make a workaround only for `isRemark`?

**Comment by vikiival** [comment]
https://github.com/kodadot/loligo/issues/27

**Comment by vikiival** [comment]
> workaround only for isRemark?

Probably yes

**Comment by roiLeo** [comment]
Feel free to refactor computed `options`

**Comment by prury** [comment]
Tested on some collections and its working properly, will do another round later today

**Pull request merged**
