### PR TITLE
docs(CONTRIBUTING): update how to receive rewards

### PR DESCRIPTION
**Pull request by KngZhi**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [ ] PR closes #<issue_number>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer?target=DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc&usdamount=100&donation=true)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by yangwao** [comment]
hey, adding just amount only button payout appears not payment link, I guess its time to revamp this process hmm 
like I don't see payment link 😄

image

this is what I got
https://kodadot.xyz/transfer?target=CuHWHNcBt3ASMVSJmcJyiBWGxxiWLyjYoYbGjfhL4ovoeSd&usdamount=100&donation=true

maybe we should rename it to "Copy Pay Me Link", the payout might get lost in translation and to ease the process we should be showing it despite the need to enter an amount to make it easier for first-time devs.

**Comment by yangwao** [comment]
@KngZhi let's update your pr and we are good to go! :)

**Comment by KngZhi** [comment]
Okay, I would do it soon.

**Comment by yangwao** [comment]
> Okay, I will do it soon. Outside right now. Since last time I check with the link, did not find out the REWARD ME button(maybe haven't deployed).

it was on `main` which is https://beta.kodadot.xyz and now it's already live at https://kodadot.xyz :)

**Comment by KngZhi** [comment]
@yangwao it's updated.

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
https://kusama.subscan.io/extrinsic/0x4b673a4ee2b8a2ba20cc6f54a9fabbd88d60efe333eda62f83c4faf34387629b

**Comment by KngZhi** [comment]
haha, 😂 received and thanks.

**Pull request merged**
