### PR TITLE
#6208 overflow fix

### LINKED ISSUE #6208: Network switch overflowing
image
- the network switch with new redesigned profile sidebar does not have good position - it is overflowing to the edges of the screen

for testing use "?redesign=true"

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #6208
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)

## Screenshot 📸

- [x] My fix has changed UI

Screen Shot 2023-06-13 at 12 16 10 PM

### CODE REVIEW

**Comment by prury** [comment]
@prachi00 deploy has failed

**Comment by prachi00** [comment]
uh now sure why that happened, how do we redeploy? @roiLeo

**Comment by Jarsen136** [comment]
> uh now sure why that happened, how do we redeploy? @roiLeo

Push a commit with anything change, that could trigger it redeploy.

**Comment by prachi00** [comment]
> > uh now sure why that happened, how do we redeploy? @roiLeo
> 
> Push a commit with anything change, that could trigger it redeploy.

isnt there any way through netlify? @Jarsen136

**Comment by Jarsen136** [comment]
> > > uh now sure why that happened, how do we redeploy? @roiLeo
> > 
> > 
> > Push a commit with anything change, that could trigger it redeploy.
> 
> isnt there any way through netlify? @Jarsen136

Yes, but I have no permission to operate it. Pushing an empty commit would be the easier way.

**Review by Jarsen136 — APPROVED** [review]
code lgtm

**Review by roiLeo — APPROVED** [review]
Explore & Create are aligned to left where Chain dropdown & profile icon are aligned to right, feels a bit weird.

ping @exezbcz for review

otherwise lgtm

**Comment by exezbcz** [comment]
good

**Pull request merged**
