### PR TITLE
#3435 Removing warning errors on landing page reload

### LINKED ISSUE #3435: Removing warning errors on landing page reload
### What happened?

A bug happened
Screen Shot 2022-07-13 at 7 24 52 PM
!

### Please reproduce in steps

Go to ... Click on .... See error

### Expected Behavior

I've expected ...

### What browsers are you seeing the problem on?

_No response_

### At which address did you encounter bug?

_No response_

### Are you logged in?

_No response_

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

_No response_

### Screenshots

Paste from your clipboard or upload screenshots/video

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3435
- [ ] Requires deployment <rubick/magick_issue>
- [x] Passionlist prop wasn't commented properly so it was considering `nfts` as prop

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by prachi00** [comment]
@yangwao @roiLeo can we approve this PR so it can be mergeddd

**Review by roiLeo — APPROVED** [review]
✅ lgtm

**Comment by roiLeo** [comment]
pay 20

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 62.63 USD/KSM ~ 0.319 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x7eed4f76e928c098a5ba2308eae727edd2bf0dcd2e8a5f7845fc846c78277fc0](https://kusama.subscan.io/extrinsic/0x7eed4f76e928c098a5ba2308eae727edd2bf0dcd2e8a5f7845fc846c78277fc0)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
