### PR TITLE
Add 💸 cursor on buy button

### LINKED ISSUE #1772: Show 💸 cursor on buy event
https://twitter.com/mgechev/status/1480774028969353222?s=21

### PR DESCRIPTION
**Pull request by chandradot99**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇  _ Do a quick check before the merge.

### PR type
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?
- [x] PR closes #1772 
- [x] Add  💸 cursor on buy button.

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main-nuxt** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases

### Had issue bounty label ?
- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=CeBWgisygADqqxGk7ju8aMNEKz1K2WkxMKC3G8HsMnm119n)

### Community participation
- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [ ] My fix has changed **something** on UI, a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by yangwao** [comment]
Let's make it that the whole actions area area would transform curosr to money component 

https://user-images.githubusercontent.com/5887929/149098797-630c35e9-4db5-450b-86b8-10771dd69664.mov

Želim plačati s kartico

**Comment by chandradot99** [comment]
> Let's make it that the whole actions area area would transform curosr to money component
> 
>  Screen.Recording.2022-01-12.at.10.15.04.mov 
> Želim plačati s kartico

Ok got it @yangwao

**Comment by chandradot99** [comment]
Changes Suggested by you done @yangwao, Now the whole actions area will render the price cursor.

**Comment by yangwao** [comment]
Perfect, I’ve sent the payout https://kusama.subscan.io/extrinsic/0xa97fce7d6a89111975bab3ed2e3b96490a552b182dbf6b95b0e7d61366484750

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/

**Pull request merged**
