### PR TITLE
Fix/buy-nft-fail

### LINKED ISSUE #8576: Error after cancelling buy step in auto teleport
image

- yeah, so I tried to buy nft, using autoteleport
- everything was going smooth, until my polkadotjs extension did not popup to sign the buy step 
- assets were teleported successfully 
- I then checked and there was not a single popup from the wallet 
- so I closed the modal and tried again -> this is the error I got 

https://canary.kodadot.xyz/ahp/gallery/52-257?listed=true

happened here

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #8576

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)

## Screenshot 📸

- [ ] My fix has changed UI

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at e13a8dc</samp>

Updated the fee calculation functions in `utils/support.ts` to use Planck units instead of decimals, for compatibility with the Kusama currency.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at e13a8dc</samp>

> _To avoid any decimal confusion_
> _The functions had a small revision_
> _They now return `int`_
> _In Planck unit format_
> _For the Kusama currency precision_

### CODE REVIEW

**Comment by daiagi** [comment]
solves the problem in the issue
but now i am facing mysterious Token: Below Minimum error:

image


https://assethub-polkadot.subscan.io/extrinsic/5229366-2


account has plenty of money to cover costs

https://www.subscan.io/account/1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8

**Review by roiLeo — APPROVED** [review]

**Review by Jarsen136 — APPROVED** [review]

**Comment by prury** [comment]
@exezbcz is this sort of what you did? (watch till the end because I've tried two different things)


https://github.com/kodadot/nft-gallery/assets/36627808/585a2763-f8da-4e07-b697-43317b1e3d3b

**Comment by yangwao** [comment]
ok this should be better tested I guess? waiting for green from prury tho

**Comment by exezbcz** [comment]
@prury, yup, but my popup disappeared, and the UI did not reflect it. I guess it was a also bug from polkadot js IMO. 

Then i could not buy it even after refreshing.

**Comment by daiagi** [comment]
> I guess it was a also bug from polkadot js IMO

no, it was our bug
we tried to create a tx with float, where allowed params are integer only
therefore the code never reached the sign modal part

the console showed the error

**Review by preschian — APPROVED** [review]

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 6.47 USD/DOT ~ 4.637 $DOT
🧗 [1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8](https://polkadot.subscan.io/account/1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)
🔗 [0x8db4209f08d0cc5536142858516304c9f37dacb204ce032a3ddc78c00d7b39d1](https://polkadot.subscan.io/extrinsic/0x8db4209f08d0cc5536142858516304c9f37dacb204ce032a3ddc78c00d7b39d1)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
