### PR TITLE
#3627 Changing default value

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes (fixes bug) #3627
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [ ] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by Jarsen136 — COMMENTED** [review]
I would like to use `this.isLogIn` to check if the current user is login.
(at `pages/bsx/create.vue` file)

**Comment by petersopko** [comment]
I've just minted two collections in a row at: https://deploy-preview-3676--koda-nuxt.netlify.app/rmrk/create

Was redirected to NFT, no explainer showed up any of those times?

@prachi00 👀

**Comment by prachi00** [comment]
> I've just minted two collections in a row at: https://deploy-preview-3676--koda-nuxt.netlify.app/rmrk/create
> 
> Was redirected to NFT, no explainer showed up any of those times?
> 
> @prachi00 👀

I guess it only works for bsx now, I'll extend for rmrk as well

**Comment by prachi00** [comment]
> > I've just minted two collections in a row at: https://deploy-preview-3676--koda-nuxt.netlify.app/rmrk/create
> > Was redirected to NFT, no explainer showed up any of those times?
> > @prachi00 👀
> 
> I guess it only works for bsx now, I'll extend for rmrk as well

should work now

**Comment by petersopko** [comment]
ok, wfm now, just a reminder, this is what was supposed to be done in:
- https://github.com/kodadot/nft-gallery/pull/3627

Please test after yourself, sometimes our @kodadot/qa-guild doesn't catch everything

**Review by petersopko — APPROVED** [review]

**Pull request merged**
