### PR TITLE
Small various bug fixes

### PR DESCRIPTION
**Pull request by vikiival**
### What's new?

- :bug: Identity Popover is using :squid:
- :zap: Carrousel card list should use same path for links
- :zap: using correct path in popular collections
- :label: permission has duplicate Config type
- :label: chainProperties have blockExplorer
- :zap: added urls for blockExplorers
- :bug: BlockExplorer works again

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### CODE REVIEW

**Review by yangwao — APPROVED** [review]
uwu

**Comment by vikiival** [comment]
> uwu

You deserve one cornetto.
8999999056193_cornettovanilla-1249093-png

**Comment by yangwao** [comment]
> ou deserve one cornetto.

m00d

**Comment by vikiival** [comment]
image

**Pull request merged**
