### PR TITLE
fix: preheat on massmint

### LINKED ISSUE #9712: Preheating IPFS files not working on the massmint page
### What happened?

while massminting nfts , the preheat calls return 500

it's adding an extra `ipfs://`when requesting the files 

telegram-cloud-photo-size-4-6017301834156326737-y

### Please reproduce in steps

create -> nft -> mutiple -> massmint a couple of nfts and open the console

### Expected Behavior

should return the requested ipfs files

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Context

- [x] Fix #9712. extract the cid to fix the path. and, preheat with image.w.kodadot.xyz will automatically upload files to cf-images/cf-r2, no need to call direct-upload

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)

### CODE REVIEW

**Review by Jarsen136 — APPROVED** [review]

**Comment by yangwao** [comment]
Seems works when I go to collection

image

**Comment by yangwao** [comment]
On the Success modal is a preview of iterated art (good), and on the listing is the default. (bad)

I guess it's unrelated to this one? 

https://github.com/kodadot/nft-gallery/assets/5887929/5103e9cf-da4d-49be-9d2d-fb54979715bc

**Comment by preschian** [comment]
> On the Success modal is a preview of iterated art (good), and on the listing is the default. (bad)
> 
> I guess it's unrelated to this one?

Interesting, probably unrelated. **I have not checked yet**, but I assume this: the listing modal is a global component, so it will check the "real metadata" of the nft item. Meanwhile, metadata of that nft is still "processing" in the background.

But, I think it can solve the problem if we also put metadata in our minting step. Since it works on the "success modal". In [this diagram](https://github.com/kodadot/private-workers/issues/87#issuecomment-1997444473), I put "setMetadata" in the steps 2 and 6

**Review by prury — APPROVED** [review]

**Comment by prury** [comment]
@yangwao payment needed

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 9.01 USD/DOT ~ 3.33 $DOT
🧗 [1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p](https://polkadot.subscan.io/account/1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)
🔗 [0x0edaa8a7f974d50fb366b56fe895be56dd506239aea6a2537c86ff2d241668fb](https://polkadot.subscan.io/extrinsic/0x0edaa8a7f974d50fb366b56fe895be56dd506239aea6a2537c86ff2d241668fb)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
