### PR TITLE
🔧 fix & introduce burn collection on snek

### LINKED ISSUE #3423: Cannot delete collection with burned NFTs
Since we're doing lot of testing, I've created few collections with the idea of deleting them later.  Today I found out I can't delete empty collection, if there were previously any NFTs (even when they're burned).

Example: 
https://beta.kodadot.xyz/bsx/collection/3639335494

The collection itself isn't showing in the explorer, however, I can't hit the delete button and I keep seeing it when trying to mint new nfts etc.
image

image

### PR DESCRIPTION
**Pull request by roiLeo**
### PR type

- [x] Bugfix

### What's new?

- [x] PR closes #3423 
- [x] fix graphql query

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Screenshot

Screenshot 2022-09-21 at 10-44-48 kusama KodaDot - Kusama NFT Market Explorer

### CODE REVIEW

**Comment by roiLeo** [comment]
Collection is still showing on `/create` even after success burning

**Comment by petersopko** [comment]
> Collection is still showing on `/create` even after success burning

@roiLeo not sure about this one, indexer shows me it's burned but I can still visit the link and find visibly unchanged collection, even when indexer shows `"burned": true`

**Comment by roiLeo** [comment]
> @roiLeo not sure about this one, indexer shows me it's burned but I can still visit the link and find visibly unchanged collection, even when indexer shows `"burned": true`

What are we talking about? how indexer shows you it's burned? can you share an Id or link or query?

**Comment by petersopko** [comment]
> > @roiLeo not sure about this one, indexer shows me it's burned but I can still visit the link and find visibly unchanged collection, even when indexer shows `"burned": true`
> 
> What are we talking about? how indexer shows you it's burned? can you share an Id or link or query?

here's the link for the burned collection: https://deploy-preview-3991--koda-nuxt.netlify.app/snek/collection/756873665
here's link for latest snek: https://app.gc.subsquid.io/beta/snekk/004/graphql
here's the query and result:
image

**Comment by petersopko** [comment]
@roiLeo and I can select the collection and try to mint NFT in it, it results in:
image

**Comment by roiLeo** [comment]
> Collection is still showing on `/create` even after success burning

Didn't knew there was a `burned` attribute for snek/bsx CollectionEntity, it should be fix now

**Comment by petersopko** [comment]
one more thing the screen where you can see this collection doesn't look changed ( you can still try to burn it), don't we want to differentiate this in similar way to burned NFTs? (adding 🔥somewhere?) 
https://deploy-preview-3991--koda-nuxt.netlify.app/snek/collection/756873665
image

**Comment by roiLeo** [comment]
> one more thing the screen where you can see this collection doesn't look changed ( you can still try to burn it), don't we want to differentiate this in similar way to burned NFTs? (adding 🔥somewhere?) 

I don't really have an idea how to show it's burned, except maybe to add 🔥 before the name but it could be confused with collection with 🔥 in name.
Additional note: Should we change to [Fire](https://fontawesome.com/v5/icons/fire?s=solid&f=classic) icon instead of a bin?

I would like to iterate this feature in #3206 as I think I understand the process to burn a full collection.
(swip offers -> burn nfts -> burn collection)

Feel free to share burned collection & burned nfts link that could help

**Comment by petersopko** [comment]
> I don't really have an idea how to show it's burned, except maybe to add 🔥 before the name but it could be confused with collection with 🔥 in name. Additional note: Should we change to [Fire](https://fontawesome.com/v5/icons/fire?s=solid&f=classic) icon instead of a bin?

here's how it's done at NFTs level:
https://beta.kodadot.xyz/rmrk/gallery/14404871-08bfa1909b24cfe94d-%20%F0%9F%8D%AD-ME-0000000000000006
image

> I would like to iterate this feature in #3206 as I think I understand the process to burn a full collection. (swip offers -> burn nfts -> burn collection)

sure 🚀

**Comment by petersopko** [comment]
@roiLeo any updates on this? :)

**Comment by roiLeo** [comment]
> @roiLeo any updates on this? :)

This can be merged, next step will be #3206 

Changes to show Burned collection are breaking RMRK chain since it share the same query with snek

Screenshot 2022-09-27 at 08-47-09 test KodaDot - Kusama NFT Market Explorer

```
Cannot query field "burned" on type "CollectionEntity".
```

**Review by petersopko — APPROVED** [review]

**Pull request merged**
