### PR TITLE
⬆️ nuxt 3.9 & vue 3.4

### LINKED ISSUE #8799: Project Upgrade to Nuxt 3.9 to Leverage New Improvements
This upgrade will align our project with current web development advancements and optimize our development process. Anticipated benefits include enhanced performance, access to new features, and improved compatibility with modern development tools.

We look forward to the positive impact this upgrade will have on our project's capabilities.

### PR DESCRIPTION
**Pull request by roiLeo**
- close #8799

### CODE REVIEW

**Comment by yangwao** [comment]
tests?

**Comment by roiLeo** [comment]
> tests?

maybe @prury know? something strange with parallel testing

I've run all tests locally and all passed manually
Capture d’écran 2024-01-02 à 10 39 53 AM

**Comment by prury** [comment]
@roiLeo can you go to https://deploy-preview-8807--koda-canary.netlify.app/ and type ahk at the end of url to see if the same happens to you? for me it does not load the page (exactly what the test detected)

**Comment by roiLeo** [comment]
> maybe a redirection issue? but yeah, strange that it passed locally

Nice find! weird that all tests were green on my side, now it should be good

**Comment by yangwao** [comment]
oke 
image

**Comment by roiLeo** [comment]
🏎️  fast

**Comment by prury** [comment]
> 🏎️ fast

console.log has been merged 😄

**Pull request merged**
