### PR TITLE
Feature(1165) : Collector whale

### LINKED ISSUE #1165: Collector Directory
Same as Artist Directory (Spotlight) let's make one laser-focused on collectors
Add identity switch 
- Name of collector
- Number of total bought >0
- Number of total received as gift =0
- Average price of buy per NFT 
- What's distribution of owning NFT per collection
- Total volume made for buys 

| Collector | Bought | Gifted (received) | Avg price of buy | Own NFT per Collection | Volume of buys | 
|-|-|-|-|-|-|

### PR DESCRIPTION
**Pull request by MSghais**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [X] Feature
- [ ] Refactoring

### What's new?

- [X] PR closes #1165
- [] Requires deployment <rubick/magick_issue>
- [X] Collector whale view with column:
all bought items
hold items
average
volume
scoring holding
30 buy history

### Before submitting Pull Request, please make sure:

- [X] My contribution builds **clean without any errors or warnings**
- [X] I've merged recent default branch -- **main** and I've no conflicts
- [X] I've tried to respect high code quality standards
- [X] I've didn't break any original functionality
- [X] I've posted a screenshot of demonstrated change in this PR

### Optional

- [] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [X] I've tested PR on mobile and everything seems works
- [X] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [X] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=5DkJ2x6SCHsXw9jarxhv3mVx1cuGsWBLK7pZNnvdRmguDuyy

### Community participation

- [X] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [X] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image
image

### CODE REVIEW

**Comment by Jarsen136** [comment]
seem related to this PR https://github.com/kodadot/nft-gallery/pull/3049 👀

**Comment by Jarsen136** [comment]
I'm afraid that this PR does not that meet the requirement in the issue #1165 
image

image

**Comment by petersopko** [comment]
> I'm afraid that this PR does not that meet the requirement in the issue #1165 

@MSghais any upcoming updates on this? :)

**Comment by MSghais** [comment]
@Jarsen136 @petersopko difficult to have the stats Average hold time for each collector, because it's very expensive., need to calculate it with all events of BUy and SEND for each collector. 

 Have you some advices about it ?

**Comment by vikiival** [comment]
>  I have some difficulties to get the stats Average hold time for each collector, because it's very expensive.

Please open it as an issue in kodadot/rubick. 

I don't have Body Battery to solve it today, but you definitely need more data than you have rn :)

**Pull request closed without merging**
