### PR TITLE
feat: Add ability to sort bsx marketplace stats

### LINKED ISSUE #3285: Add ability to sort bsx marketplace stats
- I guess adding sorting default by recent on top would be best
- Add headline/title that it's "Basilisk Marketplace Statistics"
- resize columns, so date & item don't create new line 

https://beta.kodadot.xyz/bsx/stats/
image

### PR DESCRIPTION
**Pull request by zhengow**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3285
- [ ] Requires deployment <rubick/magick_issue>
- [x] <brief_description_of_what_I've_added>

> - I guess adding sorting default by recent on top would be best
> - Add headline/title that it's "Basilisk Marketplace Statistics"
> - resize columns, so date & item don't create new line

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </bsx/stats>
- [x] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

### CODE REVIEW

**Comment by zhengow** [comment]
@petersopko 
image

**Comment by zhengow** [comment]
sort:
```graphql
query offerList {
  offers(orderBy: createdAt_DESC) {
    caller
    expiration
    price
```

image

**Comment by kkukelka** [comment]
sorry if i'm mistaken, but shouldn't this also add the ability to sort? like when you click on date column it then sorts by Ascending? 
like we do on spotlight for instance https://beta.kodadot.xyz/spotlight

**Comment by zhengow** [comment]
> sorry if i'm mistaken, but shouldn't this also add the ability to sort? like when you click on date column it then sorts by Ascending? 
> 
> like we do on spotlight for instance https://beta.kodadot.xyz/spotlight

Sure it could be add. But it doesn't been mentioned in this issue. And I think maybe
- sort ability of each column
- page splitting
These features cloud be add together. Should I add these features together within this issue?

**Review by kkukelka — APPROVED** [review]
lgtm

**Comment by kkukelka** [comment]
pay 100

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 51.99 USD/KSM ~ 1.923 $KSM
🧗 [EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws](https://kusama.subscan.io/account/EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)
🔗 [0x782ee61f49b966a4959a58c8cb12d29647073cb810ed3a512c6fa1d795f65e42](https://kusama.subscan.io/extrinsic/0x782ee61f49b966a4959a58c8cb12d29647073cb810ed3a512c6fa1d795f65e42)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
