### PR TITLE
fix: Do not show UNLIST on landing page

### LINKED ISSUE #2637: Don't show UNLIST on landing page
Don't show nft which has listed with 0 value

image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2637
- [ ] <brief_description_of_what_I've_added>

why did it happened?
'LIST' and 'UNLIST' are the same `list` event in the database. the different of them is the mate price
image

image

History Component: 
image

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by vikiival — CHANGES_REQUESTED** [review]
Not good

**Comment by vikiival** [comment]
the correct fix 

1. Extend query with `$and`

```graphql
query lastNftListByEvent($limit: Int!, $event: Interaction!, $and: [EventWhereInput!]) {
  events(
    limit: $limit
    where: { interaction_eq: $event AND: $and }
    orderBy: timestamp_DESC
  ) {
    meta
    timestamp
    nft {
      id
      name
      issuer
      currentOwner
      meta {
        id
        image
      }
    }
  }
}

```

2. implement and as a variable

```js
variables: {
  limit: 10,
  event: 'LIST',
  and: {
    meta_not_eq: '0'
  }
}
```

3. do not forget that this query is also used elsewhere :)

**Comment by Jarsen136** [comment]
> the correct fix
> 
> 1. Extend query with `$and`
> 
> ```graphql
> query lastNftListByEvent($limit: Int!, $event: Interaction!, $and: [EventWhereInput!]) {
>   events(
>     limit: $limit
>     where: { interaction_eq: $event AND: $and }
>     orderBy: timestamp_DESC
>   ) {
>     meta
>     timestamp
>     nft {
>       id
>       name
>       issuer
>       currentOwner
>       meta {
>         id
>         image
>       }
>     }
>   }
> }
> ```
> 
> 2. implement and as a variable
> 
> ```js
> variables: {
>   limit: 10,
>   event: 'LIST',
>   and: {
>     meta_not_eq: '0'
>   }
> }
> ```
> 
> 3. do not forget that this query is also used in `LatestSales.vue` so you need to update the query accordingly :)

Wow, this solution is really cool. i will correct it.

**Comment by vikiival** [comment]
Haven't you skipped option 3 ?

**Comment by Jarsen136** [comment]
> ```graphql
> lastNftListByEvent
> ```

 The changes work well on both `NewestList` and `LatestSales`. Did something go wrong?
I think the meta of 'BUY' event will never equals to `'0'`, so I did not change it. @vikiival

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 160.13 USD/KSM ~ 0.624 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x334d046c183891db597955fdea8b628a6fa8d161d821cd8785da89f654a6f7ae](https://kusama.subscan.io/extrinsic/0x334d046c183891db597955fdea8b628a6fa8d161d821cd8785da89f654a6f7ae)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
