### PR TITLE
fix: keyboard shortcut on creat page

### LINKED ISSUE #2584: Keyboard shortcuts on the "Create" page
### What happened?

Keyboard shortcuts to delete text
this is caused by keyboard shortcuts
especially g+a

### Please reproduce in steps

When writing text in a newly created NFT, I noticed that sometimes the page loads itself, for example to the gallery or to my profile. Then, of course, the whole text was washed away and I had to write it again....
obrázok
I suggest disabling keyboard shortcuts wherever text can be typed, i.e. when creating new collections and NFTs

### Expected Behavior

I expected that not to happen :) 
this is caused by keyboard shortcuts
especially g+a
I suggest disabling keyboard shortcuts wherever text can be typed, i.e. when creating new collections and NFTs

### What browsers are you seeing the problem on?

Firefox

### Are you logged in?

Yes

### At which address did you encounter bug?

kodadot.xyz

### Screenshots

https://user-images.githubusercontent.com/81104034/158958997-86ce00db-ff22-4f4b-8db7-19f71f4ff5af.mp4

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/transfer?target=FqCJeGcPidYSsvvmT17fHVaYdE2nXMYgPsBn3CP9gugvZR5&usdamount=10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2584
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [x] I found edge cases
- [x] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by yangwao** [comment]
can @jkdizajn test if it works already? ;)

**Comment by jkdizajn** [comment]
> can @jkdizajn test if it works already? ;)


I'm testing it right now on https://deploy-preview-2586--koda-nuxt.netlify.app/rmrk/create and it's working properly - keyboard shortcuts are disabled, and text can be typed without any problems :) 
GJ :)

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 145.14 USD/KSM ~ 0.689 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x6d023fb148aa8c627c4079fddbc7da4e451d411e6dd66b9c135c4f622a650d8c](https://kusama.subscan.io/extrinsic/0x6d023fb148aa8c627c4079fddbc7da4e451d411e6dd66b9c135c4f622a650d8c)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
