### PR TITLE
fix: retry on cancel - migration page

### LINKED ISSUE #8700: Can't retry migration signing if cancelled
If i cancel the first transaction, i have to refresh the page to retry and loader state stays the same:

https://github.com/kodadot/nft-gallery/assets/36627808/6b247fd0-33cd-48d4-9029-eed39c6eebfd

### LINKED ISSUE #8996: Migrate signing last bits
image

- lets use the same components as in the autoteleport signing - for example the loading wheel is grey and rotating faster 
image

otherwise okay!

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Context

- [x] Closes #8700
- [x] Closes #8996

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
✅ code lgtm

**Comment by prury** [comment]
@preschian it works for the first step, but hitting try again on the second(Migrating your items) does not trigger the signature again

**Comment by exezbcz** [comment]
👀

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 8.33 USD/DOT ~ 3.601 $DOT
🧗 [1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p](https://polkadot.subscan.io/account/1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)
🔗 [0xba78b3de67ec7869e18e6ea7bd6a1908101e5fa67b70b06869bb7a1a574df44b](https://polkadot.subscan.io/extrinsic/0xba78b3de67ec7869e18e6ea7bd6a1908101e5fa67b70b06869bb7a1a574df44b)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
