### PR TITLE
Cards change

### LINKED ISSUE #5687: Cards change
image
dropping the drop shadow 🚀  (only there, don't worry) 

### Figma
- handoff main, page card changes https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?node-id=88%3A261&t=eiSf4SbRKw7H6ngV-1

- you can see the prototype where all card types are: https://www.figma.com/proto/JXNtryaNYhY0XJNArzvPQx/Handoff?page-id=88%3A261&node-id=88-482&viewport=1182%2C963%2C0.23&scaling=min-zoom

## Main 
- the main motivation to this change were the dark mode cards - see current explore for example, the white stroke is too contrasty 
- This means that it will be easier on the eyes.
- based on dark mode changes, we will change also the white mode cards - for consistency 
- It's a bigger first step in terms of visual id, but I believe it's for the better.
- it's also a better foundation for other changes like cart, popovers over cards etc. 

## Changes 
- change default states: 
  - stroke to lighter color 
- change of hover effect: 
  - no drop shadow 
  - change to contrast color
  - overlay over the thumbnail - depends on the mode

### Dark mode
- default state is stroke color: k-hovergrey (#6B6B6B) 
- hover state is - outer stroke to white, overlay over the img (
image
)
image

### Light mode 
- default state is stroke color: k-grey (#6B6B6B) 
- hover state is - outer stroke to black, overlay over the img (
image
)
image

### Special cases
collection card: 
only the outer stroke changes 
image

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #5687
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at 5f95f5d</samp>

Refactored the styles and components of various cards in the UI and the gallery to use a new `card-border-color` variable and to remove unnecessary animations. This improves the performance, design consistency, and code maintainability of the project.

### <samp>🤖 Generated by Copilot at 5f95f5d</samp>

> _`CardArticle` style_
> _shared across components now_
> _less code, more spring_

### CODE REVIEW

**Comment by daiagi** [comment]
Effected cards:

#### Landing Page
* All Carousel cards (Spotlight, Newest List, Latest Sales)
* Top Collections 
* Featured Articles


#### Explore / Item Grid
* items tab cards
* collections tab cards

**Comment by exezbcz** [comment]
looks good to me!

**Review by roiLeo — APPROVED** [review]
I don't really like adding opacity on hover, normally I would have seen the opposite.
Duplicate theme variable code  :/
This `libs/ui` is starting to be less sustainable.

otherwise lgtm ✅

**Comment by daiagi** [comment]
> Duplicate theme variable code  :/
> This `libs/ui` is starting to be less sustainable.

True

**Comment by exezbcz** [comment]
> I don't really like adding opacity on hover, normally I would have seen the opposite.
> Duplicate theme variable code  :/
> This `libs/ui` is starting to be less sustainable.
> 
> otherwise lgtm ✅ 

What do you mean by seeing the opposite? Would you remove the hover opacity completely? Thanks for feedback!

**Comment by roiLeo** [comment]
> What do you mean by seeing the opposite? 

Opacity by default, remove opacity on hover. I find it strange to add opacity on something that should stand out.

> Would you remove the hover opacity completely? Thanks for feedback!

I would reintroduce a slight zoom on hover effect

**Comment by exezbcz** [comment]
> Opacity by default, remove opacity on hover. I find it strange to add opacity on something that should stand out.
> 
> >

- the opacity is mainly for future cart button over the img and other functionalities 
- that means it will stands out





> I would reintroduce a slight zoom on hover effect

- yup, that sounds good, I would leave it to another version tho

**Comment by yangwao** [comment]
> I don't really like adding opacity on hover, normally I would have seen the opposite.

Inspiration was coming from https://www.tensor.trade/trade/oogy_pods this is way how we implemented it in now in visual way, as current animation when you are hovering with cursor over are quite slow nad missing, also removing that sharp borders was intrusive

> I would reintroduce a slight zoom on hover effect

yeah we had this zoom, which I was thinking, it's possible option. I would like to keep it as basic as possible those animation tbh to not disturb user. Other experiments we can try in fandoms shops for example, let's see, there is room accommodate lot of approaches I guess per collection.

**Comment by yangwao** [comment]
pay 60 usd

quick delivery on first try! like it!

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $60 @ 37.46 USD/KSM ~ 1.602 $KSM
🧗 [EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L](https://kusama.subscan.io/account/EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L)
🔗 [0x6e7450ef76cd641d5490c0bebf65d058409409124e2baa0912f369a56fc5c5a0](https://kusama.subscan.io/extrinsic/0x6e7450ef76cd641d5490c0bebf65d058409409124e2baa0912f369a56fc5c5a0)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
