### PR TITLE
clean: remove unused deps

### LINKED ISSUE #9854: update axios to 0.28.0
image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Refactoring

- remove `vue-audio-visual` and also its deps `axios`
## Context

- [x] Closes #9854

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Copilot Summary

copilot:summary

copilot:poem

### CODE REVIEW

**Review by preschian — APPROVED** [review]
code lgtm

**Comment by preschian** [comment]
> ## Copilot Summary
> copilot:summary
> 
> copilot:poem

@Jarsen136 seems like you are still using an old template 😆
https://github.com/kodadot/nft-gallery/blob/main/.github/PULL_REQUEST_TEMPLATE/QUICK_PULL_REQUEST_TEMPLATE.md

**Comment by yangwao** [comment]
> like you are still using an old template 😆

hehe if it works ,)

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 8.92 USD/DOT ~ 3.363 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x547392a4194df0e878e65418da3802bde2a6b783a6fc3f58b3ace83473aeab44](https://polkadot.subscan.io/extrinsic/0x547392a4194df0e878e65418da3802bde2a6b783a6fc3f58b3ace83473aeab44)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
