### PR TITLE
Show user balance at minting screen

### LINKED ISSUE #3459: Show user balance at minting screen
We've got numerous similar bug reports for basilisk that people get an error once they don't have a balance while minting.

A great solution would be to show users the balance above submit button so people know their balance before minting.

I guess we had something like this check for insufficient balance but was done only on rmrk iirc
ref from report-bug channel
image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3459 
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by roiLeo** [comment]
Can you rename component to `<AccountBalance />`? 
I find it more meaningfull

**Comment by Jarsen136** [comment]
> I know the issue described only adding the balance so user can see what's wrong, but perhaps we don't want to let user run into the error itself? Can we disable submit buttons on create nfts/create collections, if the balance is 0 with tooltip informing there's a balance issue? wdyt @roiLeo @Jarsen136 I'm still runing into this: image

Even if the balance is great than 0, it may still face this warning `account balance too low.
How about creating another issue to trace it. 
1. limit submit button if balance is 0.
2. Estimate the transaction gas fee and display a friendly tip to tell user has not enough balance, before they click submit.
3. ..any idea?

(btw: This PR is about building a reusable component to show user balance)

**Comment by roiLeo** [comment]
I'm not really a fan of disabled pattern as it can cause some frustrating for the UX.
To me, it should appear when user made an error in a form input AND with the error displayed near the inputs.
In this case, that can work too but i find it important to show a sentence which explains why the button has been disabled.

Tooltip component is more of a "Helper" and shouldn't be used to inform user has not enough founds + think about mobile user. (ref #3324)

**Comment by petersopko** [comment]
> Tooltip component is more of a "Helper" and shouldn't be used to inform user has not enough founds + think about mobile user. (ref #3324, [MaterialDesign](https://material.io/components/tooltips))

sure, good to know, whatever works for you and won't result in user seeing that error 😆

**Comment by yangwao** [comment]
> I'm not really a fan of disabled pattern as it can cause some frustrating for the UX.
To me, it should appear when user made an error in a form input AND with the error displayed near the inputs.
In this case, that can work too but i find it important to show a sentence which explains why the button has been disabled.

✅

**Comment by roiLeo** [comment]
Let's merge this one and open new issue for when user hasn't enough balance to mint.

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 68.13 USD/KSM ~ 1.468 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x17389c2d66cb8bf468cc084084ff1401e3e500b27a13f071bdd1830a4f0d3722](https://kusama.subscan.io/extrinsic/0x17389c2d66cb8bf468cc084084ff1401e3e500b27a13f071bdd1830a4f0d3722)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
