### PR TITLE
fix: link unclickable on ios safari

### LINKED ISSUE #2179: Unable to click on items in gallery detail
### What happened?

When I am on mobile I am unable to roll out the description or go the to artist's page 

### Please reproduce in steps

1. open [Kusama Hippie Girl 💜](https://kodadot.xyz/rmrk/gallery/11232278-d483a43afae30f4a4f-KUSAMA_HIPPIE_GIRLS-KUSAMA_HIPPIE_GIRL-0000000000000021) on mobile
2. try to interact with the app

### Expected Behavior

It should be working

### What browsers are you seeing the problem on?

Mobile iOS Safari

### Are you logged in?

No

### At which address did you encounter bug?

nft.kodadot.xyz / kodadot.xyz

### Screenshots

Uploading RPReplay_Final1643809497.MP4…

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2179
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [x] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

https://user-images.githubusercontent.com/31397967/158065737-4cf0dcc1-bc79-40a9-9fd0-3d9954a1c881.mp4

### CODE REVIEW

**Comment by Jarsen136** [comment]
This problem is caused by the wrong hierarchy in IOS safari. Took me a lot of time debugging. 🙃

**Review by roiLeo — APPROVED** [review]
lgtm, tested on Safari Version 15.3

**Comment by vikiival** [comment]
MacOS safari works too ✅

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 119.47 USD/KSM ~ 0.837 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xc5f84f2ce66b7fb6c70bae4591f8c4fe9a1617fcf5e9085127abbc1c3822467a](https://kusama.subscan.io/extrinsic/0xc5f84f2ce66b7fb6c70bae4591f8c4fe9a1617fcf5e9085127abbc1c3822467a)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
