### PR TITLE
fix: Limit image size when upload images to profile

### LINKED ISSUE #10490: Limit image size when upload images to profile
Editing profile, we have a text explaining the recommended image sizes to user (2mb, 10mb), but we don`t really check the size of the uploaded image, would be good check it and prevent user from sending large images.

i also think the 10mb for background is too much

image

thank you @JustLuuuu

### LINKED ISSUE #10508: Uploaded file exceeds the size limit/character limit
as thomas has pointed out, it would be nice to add some warning messages when user imports a image that is larger then it should be. 

Will drop some notification designs asap

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs Design check

- @exezbcz please review

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #10508
- [x] Closes #10490

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by vikiival** [comment]
I do not think that is user friendly to post a toast. Imo text would be better

**Comment by vikiival** [comment]
Cc @exezbcz

**Comment by exezbcz** [comment]
@vikiival should be this type
image


Copy is somewhat okay, would just mention that they should 


lets do: 


## File Too Large
The uploaded file exceeds the 5MB size limit.

**Comment by Jarsen136** [comment]
image

✅ UPDATED

**Review by vikiival — APPROVED** [review]
Awesome

**Comment by vikiival** [comment]
Cc @hassnian

**Review by hassnian — APPROVED** [review]

**Pull request merged**
