### PR TITLE
fix: dark mode style issue

### LINKED ISSUE #7616: Dark/white mode problems and icons still missing
### What happened?

cart icon won't load
image

chart background white on dark mode: 
image

clicking on dark/white mode button on sidebar fixes it

not sure yet on how to reproduce, only happens the first time you access the page

### PR DESCRIPTION
**Pull request by floyd-li**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #7616  
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at b0ef5b3</samp>

Fixed a bug in the color mode switching logic by using the correct `colorMode` property in `useTheme.ts`.

### <samp>🤖 Generated by Copilot at b0ef5b3</samp>

> _`colorMode.value`_
> _fixes the bug in the app_
> _autumn preference_

### CODE REVIEW

**Comment by floyd-li** [comment]
from the doc https://color-mode.nuxtjs.org/#setup

> preference: Actual color-mode selected (can be 'system'), update it to change the user preferred color mode

that we should use `value` instead of `preference` to know if it's dark mode

cc @roiLeo

**Comment by prury** [comment]
oh, first time i accessed the deployed version did not showed me the problem, nice! 
let's wait for other ppl to test

**Review by prury — APPROVED** [review]

**Review by Jarsen136 — APPROVED** [review]

**Comment by yangwao** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 3.67 USD/DOT ~ 5.45 $DOT
🧗 [13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A](https://polkadot.subscan.io/account/13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A)
🔗 [0x5b5b9a5989c2d63f22a67bd66360dc95c6e32b4c160560af39d189cf2a086fdb](https://polkadot.subscan.io/extrinsic/0x5b5b9a5989c2d63f22a67bd66360dc95c6e32b4c160560af39d189cf2a086fdb)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by floyd-li** [comment]
> 😍 Perfect, I’ve sent the payout 💵 $20 @ 3.67 USD/DOT ~ 5.45 $DOT 🧗 [13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A](https://polkadot.subscan.io/account/13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A) 🔗 [0x5b5b9a5989c2d63f22a67bd66360dc95c6e32b4c160560af39d189cf2a086fdb](https://polkadot.subscan.io/extrinsic/0x5b5b9a5989c2d63f22a67bd66360dc95c6e32b4c160560af39d189cf2a086fdb)
> 
> 🪅 Let’s grab another issue and get rewarded! 🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

@yangwao sorry sir seems the transfer failed
图片

**Comment by floyd-li** [comment]
@yangwao may you check the transfer?

**Comment by yangwao** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 3.78 USD/DOT ~ 5.291 $DOT
🧗 [13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A](https://polkadot.subscan.io/account/13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A)
🔗 [0x55630c5a2866257a5d722b16ae8387ae0a832877029aa7ec89a798aacf3ec8c4](https://polkadot.subscan.io/extrinsic/0x55630c5a2866257a5d722b16ae8387ae0a832877029aa7ec89a798aacf3ec8c4)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
