### PR TITLE
fix: incorrect number of NFTs in collection

### LINKED ISSUE #3469: Error - number of NFTs in collection  - bXiGvoYjMbEEUe27h3zFCnabsu367zEDEivu8ZHjVSm5v8mC2
### What happened?

A bug happened!

Wallet: bXiGvoYjMbEEUe27h3zFCnabsu367zEDEivu8ZHjVSm5v8mC2

Ive created 10 NFT in one cllection,   Burnt 1 NFT,  and at the end I have a 9 NFT in collection.
image

But when I try to create another one NFT, it shows 10:
image

### Please reproduce in steps

1. Create 10 NFT
2. Burn 1 NFT
3.  Try to create another one and see, how many NFTs show are there in the collection
image

### Expected Behavior

I've expected -   9 NFTs  ( 10 -1 )

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

_No response_

### Which wallet you are using?

_No response_

### Screenshots

image

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3469
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by Jarsen136** [comment]
Almost done. I need to do more tests.

**Comment by Jarsen136** [comment]
Ready for code review now.

**Comment by DeluneClaire** [comment]
It takes some time till you can see changes or minted NFTs, but it works for me.

**Review by kkukelka — APPROVED** [review]
code looks good!

**Comment by kkukelka** [comment]
pay 100

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 58.76 USD/KSM ~ 1.702 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xe0485ce3786c26e0f7eed4cde397be452a04517888f54cc69ab8a282d6bdd293](https://kusama.subscan.io/extrinsic/0xe0485ce3786c26e0f7eed4cde397be452a04517888f54cc69ab8a282d6bdd293)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
