### PR TITLE
#4252 Redesign congrats message after mint

### LINKED ISSUE #4252: Redesign congrats message after mint
> might need to rework this message design ping 🖼️ @exezbcz

Yes I was thinking same!

Once @exezbcz drops new design we can put this into work

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/pull/4250#issuecomment-1303317396_

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #4252
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screen Shot 2022-12-28 at 12 29 15 PM

### CODE REVIEW

**Comment by prachi00** [comment]
@exezbcz I am not sure about positioning though, right now it looks like this in gallery, seems a bit weird or is it okay? 
Screen Shot 2022-12-28 at 12 30 54 PM

**Comment by exezbcz** [comment]
> @exezbcz I am not sure about positioning though, right now it looks like this in gallery, seems a bit weird or is it okay? Screen Shot 2022-12-28 at 12 30 54 PM

It would be best to put it on the left, where everything pops up. How long till it disappear?

Also, the svg does not seem to be right; there is a problem with svg export in Figma.... it is also cropped and does not fill the entire space on the card.

**Comment by prachi00** [comment]
> > @exezbcz I am not sure about positioning though, right now it looks like this in gallery, seems a bit weird or is it okay? Screen Shot 2022-12-28 at 12 30 54 PM
> 
> It would be best to put it on the left, where everything pops up. How long till it disappear?
> 
> Also, the svg does not seem to be right; there is a problem with svg export in Figma.... it is also cropped and does not fill the entire space on the card.

okay, I'll add it to left
Can you give the svg here?

**Comment by exezbcz** [comment]
yup, i have to first fix it somehow because its a bug in figma..

**Comment by exezbcz** [comment]
> yup, i have to first fix it somehow because its a bug in figma..

okay, i have updated figma. With the svg export its the best i can do for now till they fix it. You can download the svg from there.

**Comment by exezbcz** [comment]
or easy fix - i can export it without the effects and then you can add the solid dropshadow through css? We then eliminate the pixelated svg. 

image

its x: 4px ;y: -4px

**Comment by prachi00** [comment]
> or easy fix - i can export it without the effects and then you can add the solid dropshadow through css? We then eliminate the pixelated svg.
> 
> image
> 
> its x: 4px ;y: -4px

I think it would be a bit complex to add it through drop shadow, it would be better to have them in svg

**Comment by prachi00** [comment]
Also, I dont think the message goes away ever, unless you move away from the page

**Comment by exezbcz** [comment]
> > or easy fix - i can export it without the effects and then you can add the solid dropshadow through css? We then eliminate the pixelated svg.
> > image
> > its x: 4px ;y: -4px
> 
> I think it would be a bit complex to add it through drop shadow, it would be better to have them in svg

I think its better to apply the filter in css because in figma there is compression of the svg effects, which is not what it was designed for. Adding filter tag would not work? We would have avoided the pixelated effect that occurs when i export it right away from figma.

**Comment by exezbcz** [comment]
> Also, I dont think the message goes away ever, unless you move away from the page

lets add the visibility of the popup to 6s, we can always change it.

**Comment by prachi00** [comment]
> > > or easy fix - i can export it without the effects and then you can add the solid dropshadow through css? We then eliminate the pixelated svg.
> > > image
> > > its x: 4px ;y: -4px
> > 
> > 
> > I think it would be a bit complex to add it through drop shadow, it would be better to have them in svg
> 
> I think its better to apply the filter in css because in figma there is compression of the svg effects, which is not what it was designed for. Adding filter tag would not work? We would have avoided the pixelated effect that occurs when i export it right away from figma.

I am not really sure how you can give this effect on a svg through css

**Comment by exezbcz** [comment]
https://codepen.io/Exez/pen/NWBNONa
i think this is the way

`svg {
  filter: drop-shadow(4px 4px 0px rgb(0 0 0 / 1));
}`

**Comment by prachi00** [comment]
> filter: drop-shadow(4px 4px 0px rgb(0 0 0 / 1))

okay I'll try doing this, thank you

**Comment by prachi00** [comment]
> https://codepen.io/Exez/pen/NWBNONa i think this is the way
> 
> `svg { filter: drop-shadow(4px 4px 0px rgb(0 0 0 / 1)); }`

yes this worked fine, can you check now

**Comment by exezbcz** [comment]
can you please give me a screenshot how it looks? Dont know how to trigger the message in web without minting lol.

**Comment by prachi00** [comment]
> can you please give me a screenshot how it looks? Dont know how to trigger the message in web without minting lol.

sure

**Comment by exezbcz** [comment]
thanks
i would maybe remove the emoji and then its good to go?

**Review by roiLeo — CHANGES_REQUESTED** [review]
what bothers me here:
- responsive not working (why is it on the top left?)
Capture d’écran 2023-01-02 à 9 15 30 AM
- message duration is to short to be able to click on icon or read message (you can set `duration` check out [Buefy doc](https://buefy.org/documentation/message/#api-view))
- missing `MessageNotify` on redesign page
- copy to clipboard should show `is-neo` toast
- " You Have New NFT(s) " text is misleading, I'll change it to: "You have successfully purchased this/a new NFT" or something like this

**Comment by prachi00** [comment]
maybe we remove the timer @exezbcz @roiLeo  ?

**Comment by roiLeo** [comment]
> maybe we remove the timer @exezbcz @roiLeo ?

or set it in `b-message` component around 8-10sec

**Comment by prachi00** [comment]
done the mentioned changes, except adding it on new screen (need design help for that) and the text change

**Comment by yangwao** [comment]
How do I trigger it @prachi00 ? `?congrats=true` or something like that?

**Comment by roiLeo** [comment]
### Done:
> * responsive not working
> * message duration is to short
> * copy to clipboard should show `is-neo` toast 


### Todo:
> * missing `MessageNotify` on redesign page
> * " You Have New NFT(s) " text => "You have successfully purchased this/a new NFT"

**Comment by yangwao** [comment]
Huh, I see two messages. 
One is toast I guess which should be removed @prachi00 ?

image

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 24.05 USD/KSM ~ 1.247 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0xef6c2989ad9616fb0f7767dad3fafa1448dcd13104eb88d2555470124b112de6](https://kusama.subscan.io/extrinsic/0xef6c2989ad9616fb0f7767dad3fafa1448dcd13104eb88d2555470124b112de6)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
