### PR TITLE
#2578 Keep only top-border on pagination and sharing buttons

### LINKED ISSUE #2578: Keep only top-border on pagination and sharing buttons
- Keep only top-border on pagination buttons

Probably reflect everywhere where we are using pagination
- gallery
- collections
- artists profile
- collection detail

image
image

On collection detail like at https://beta.kodadot.xyz/rmrk/collection/0a8ce195286c168f19-DONKEY?tab=collection
- Keep only top-border on sharing and make it 1px
image

For item action buttons and sharing do the same 🥺
image

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #2578
- [ ]

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screenshot 2022-03-17 at 7 10 50 PM
Screenshot 2022-03-17 at 7 10 54 PM
Screenshot 2022-03-17 at 7 11 11 PM

### CODE REVIEW

**Comment by vikiival** [comment]
I think that Leo can have a better judgement for CSS than me

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 131.92 USD/KSM ~ 0.758 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0xf66077fbabc2b6e7e2bb0ce4f9187db682e7a4e0b089068187d7829e729d4350](https://kusama.subscan.io/extrinsic/0xf66077fbabc2b6e7e2bb0ce4f9187db682e7a4e0b089068187d7829e729d4350)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by prachi00** [comment]
> code is okayish but design feels strange like this bloc Screenshot 2022-03-17 at 17-16-43 zcname
> 
> I noticed buttons have 2px top border while sharing bloc only have 1px (same for pagination)

yeah, I think for consistency we should have 2px everywhere
@yangwao

**Comment by yangwao** [comment]
> > code is okayish but design feels strange like this bloc Screenshot 2022-03-17 at 17-16-43 zcname
> > I noticed buttons have 2px top border while sharing bloc only have 1px (same for pagination)
> 
> yeah, I think for consistency we should have 2px everywhere @yangwao

mmm, for least disruption I guess actionable buttons should go for 1px and 2px for sections, like history/price chart and actions section has :)

In similar manner we have in markdown headlines h1,h2,h3 etc )

So let's adjust it in navbar in this PR so we can push to release and that would be amazing! :)

**Comment by prachi00** [comment]
> > > code is okayish but design feels strange like this bloc Screenshot 2022-03-17 at 17-16-43 zcname
> > > I noticed buttons have 2px top border while sharing bloc only have 1px (same for pagination)
> > 
> > 
> > yeah, I think for consistency we should have 2px everywhere @yangwao
> 
> mmm, great catch. For least disruption I guess actionable buttons should go for 1px and 2px for sections, like the history/price chart and actions section has :)
> 
> In similar manner we have in markdown headlines h1,h2,h3 etc )
> 
> So let's adjust it in navbar in this PR so we can push to release and that would be amazing! :)
Screenshot 2022-03-19 at 4 49 08 PM
@yangwao what about these, should this be 1px or 2px?

**Comment by yangwao** [comment]
> > > > code is okayish but design feels strange like this bloc Screenshot 2022-03-17 at 17-16-43 zcname
> > > > I noticed buttons have 2px top border while sharing bloc only have 1px (same for pagination)
> > > 
> > > 
> > > yeah, I think for consistency we should have 2px everywhere @yangwao
> > 
> > 
> > mmm, great catch. For least disruption I guess actionable buttons should go for 1px and 2px for sections, like the history/price chart and actions section has :)
> > In similar manner we have in markdown headlines h1,h2,h3 etc )
> > So let's adjust it in navbar in this PR so we can push to release and that would be amazing! :)
> 
> Screenshot 2022-03-19 at 4 49 08 PM
> 
> @yangwao what about these, should this be 1px or 2px?

yup, let's go with 1px :)

**Comment by prachi00** [comment]
@yangwao done the above mentioned changes

**Comment by yangwao** [comment]
lovely! merging!

**Pull request merged**
