### PR TITLE
✨ latest sales with CarouselList

### PR DESCRIPTION
**Pull request by roiLeo**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Feature

### What's new?

- [x] new component carousel list
- [x] new component latest sales visible on rmrk landing page

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

### Screenshot
Screenshot 2022-02-02 at 09-43-54 Low minting fees and carbonless NFTs

### CODE REVIEW

**Comment by yangwao** [comment]
I have two suggestions

- Probably add that shadow like you've made on hiding text in the description of the item, but vertical one and it should fade out somewhere around the arrow?
- add it to landing page and we are good to go w #2018 partially:)

Found it #1236 related hmm and perfect heads upstart for #1818

**Comment by roiLeo** [comment]
>     * Probably add that shadow like you've made on hiding text in the description of the item, but vertical one and it should fade out somewhere around the arrow? Reasoning => so it won't go over edge much uhm as at first thought it's broken but when I found small arrow, found it working

I originally removed the overflow to fix a bug with the emoji picker component. We should agree on the number of elements to display on desktop/tablet/mobile.
I like that idea of fading shadow, I'll cook something!

>     * probably resize arrow or better highlight, on particular NFT it's harder to find/spot, but with upper suggestion might be solved

otherwise we can leave it displayed all the time and make it bigger

>     * add it to the landing page and we are good to go w [Rework landing page a bit #2018](https://github.com/kodadot/nft-gallery/issues/2018) partially:)

Alright, I'll add this to /rmrk/landing but where? under buttons? under big info card?

**Comment by yangwao** [comment]
> I originally removed the overflow to fix a bug with the emoji picker component. We should agree on the number of elements to display on desktop/tablet/mobile. I like that idea of fading shadow, I'll cook something!
> 

3-4 ? 

> Alright, I'll add this to /rmrk/landing but where? under buttons? under big info card?

I guess instead big info card it can be okayish, we will be dropping it anyway.

**Comment by roiLeo** [comment]
I'm not able to add a mask yet because next&prev arrows will be hidden (see screenshot)
Screenshot 2022-02-04 at 08-51-04 KodaDot - Kusama NFT Market Explorer

There is still the possibility to add an option of:
**opacity**
Screenshot 2022-02-04 at 08-52-05 KodaDot - Kusama NFT Market Explorer

**grayscale**
Screenshot 2022-02-04 at 08-54-02 KodaDot - Kusama NFT Market Explorer

for the moment I kept the default design with the arrows visible and larger.

Bonus: I created the same slider for the last nfts put on LIST

**Comment by yangwao** [comment]
Let's remove this homebox 

image

and instead of non-working see more, we can use the pagination component to scroll next in a row?

**Comment by roiLeo** [comment]
I've removed background & big box from all landing pages.
There are still some changes to make because I don't use the (cloudfare images?) cache for now so the page will take longer time to load.

**Comment by yangwao** [comment]
> I've removed background & big box from all landing pages. There are still some changes to make because I don't use the (cloudfare images?) cache for now so the page will take longer time to load.

Yup can merge and I'm passing to my operator next to me @vikiival 

[ weekend background techno music session intensifies ] 

https://open.spotify.com/track/3b7ZA0UdkYO80VA7vjSjK0?si=19a50826aa4a47c1

**Pull request merged**
