### PR TITLE
feat: add link to collection history

### LINKED ISSUE #2562: Add link to collection history into series
Adding a link similar to a link to a chart like when someone clicks on the icon next to chart will land on history tab of the collection.

i.e. someone will want to see Donkey Gang, will directly go from Series to History tab like https://deploy-preview-2552--koda-nuxt.netlify.app/rmrk/collection/0a8ce195286c168f19-DONKEY?tab=history

Plus for activity and history, 
once user clicks, scroll viewport directly to chart or history tab

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2562
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [x] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

### CODE REVIEW

**Review by vikiival — APPROVED** [review]
OKI

**Comment by yangwao** [comment]
The graph works with scroll viewport to the right place, but history seems does not.


https://user-images.githubusercontent.com/5887929/158793390-f2b3f44a-6a95-4157-bf0c-e285ebce63b1.mov

**Comment by Jarsen136** [comment]
> The graph works with scroll viewport to the right place, but history seems does not.
> 
>  Screen.Recording.2022-03-17.at.11.48.30.mov

Got. It may only happen in some collections. Let me fix it.

**Comment by Jarsen136** [comment]
> > The graph works with scroll viewport to the right place, but history seems does not.
> > Screen.Recording.2022-03-17.at.11.48.30.mov
> 
> Got. It may only happen in some collections. Let me fix it.

@yangwao  hey, I think it works well on every collection now.

**Comment by yangwao** [comment]
wfm me! 

pay 100 usd

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
smh is wrong

**Comment by Jarsen136** [comment]
> oh @Jarsen136 can you check your address please? :)

 @yangwao  Oh, I'm so sorry. My correct KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

**Comment by yangwao** [comment]
pay 100 usd 

wfm me ;)

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 144.66 USD/KSM ~ 0.691 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x75d225e456299233b4ebd79cb77c8ca8eca8c3e61eaebd2cc1bedea8889c61c9](https://kusama.subscan.io/extrinsic/0x75d225e456299233b4ebd79cb77c8ca8eca8c3e61eaebd2cc1bedea8889c61c9)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
