### PR TITLE
#5539 button up fix

### LINKED ISSUE #5539: Button up on collection
Button up should be elsewhere?

https://deploy-preview-5442--koda-canary.netlify.app/rmrk/collection/9AFFD71D65E3DBBF29-MORBID_CON?page=1
image

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5539
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screen Shot 2023-04-08 at 5 58 26 PM

### CODE REVIEW

**Review by daiagi — APPROVED** [review]

**Comment by exezbcz** [comment]
make it square with no rounded stroke please :D 
image
+ please make the aspect ratio 1:1 so its a proper square 
image

rounded corners 👀

**Comment by prachi00** [comment]
> make it square with no rounded stroke please :D image
> 
> * please make the aspect ratio 1:1 so its a proper square
>   image
> 
> rounded corners 👀

done
Screen Shot 2023-04-09 at 5 36 45 PM

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
pay 10 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $10 @ 32.8 USD/KSM ~ 0.305 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x1ec4158d72f9d2bb043640c28726f5ca927713f73d6ac9d3c8a292edae6e5c87](https://kusama.subscan.io/extrinsic/0x1ec4158d72f9d2bb043640c28726f5ca927713f73d6ac9d3c8a292edae6e5c87)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
