### PR TITLE
fix: replace gmt with umt in history date column

### LINKED ISSUE #1161: Change GMT into UTC in history chart
image

https://en.wikipedia.org/wiki/Coordinated_Universal_Time#:~:text=Coordinated%20Universal%20Time%20or%20UTC,Greenwich%20Mean%20Time%20(GMT).

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

Screenshot 2022-05-08 at 18 24 19

### What's new?

- [x] PR closes #1161
- [x] for historical compatability reasons `toUTCString()` prints `GMT` at the end of the string -> therefore use replace function as you cannot pass any parameters to `toUTCString` call to control its behaviour
https://www.nhc.noaa.gov/aboututc.shtml#:~:text=Prior%20to%201972%2C%20this%20time,%22%20or%20%22Zulu%20Time%22.

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/gallery/10679597-0a8ce195286c168f19-DONKEY-DONKEY_GANG_391-0000000000000391>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
I would do something more like:
```js
    return date.toLocaleString('en-GB', {timeZone: 'UTC'})
```
what do you think?

**Comment by kkukelka** [comment]
> I would do something more like:
> 
> ```js
>     return date.toLocaleString('en-GB', {timeZone: 'UTC'})
> ```
> 
> what do you think?

looks way better!
additionally added `  timeZoneName: 'short',` to print the timezone name
Screenshot 2022-05-09 at 19 35 36

**Review by roiLeo — APPROVED** [review]
✅ lgtm

**Comment by roiLeo** [comment]
pay 50

**Pull request merged**
