### PR TITLE
fix: refresh page index after changing search keyword

### LINKED ISSUE #1655: Search input suggestion and history seems broken/gone
I recall we had working search suggestions?  https://github.com/kodadot/nft-gallery/pull/1576

you can try it here https://deploy-preview-1576--koda-nuxt.netlify.app/rmrk/gallery?page=2196 search for "kusama" for example

image

Search is broken as well https://beta.kodadot.xyz/rmrk/gallery/?search=kusama&page=10

### Ref 
- #1612

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #1655
- [ ] <brief_description_of_what_I've_added>
The problem is that If you are on the 10th page of a search and search for something new, you go to the 10th page of the latest search result. Happens for collection as well.

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
I'm not a fan of using event bus, isn't there another solution to correct this problem?

**Comment by yangwao** [comment]
> I'm not a fan of using event bus, isn't there another solution to correct this problem?

Yes 🥺 please, avoid event bus for any costs

**Comment by Jarsen136** [comment]
@roiLeo @yangwao EventBus is the quickest solution to this bug. Of course, there are other elegant ways, but it will take me a long time to process - -!

**Comment by yangwao** [comment]
wait I'm confused about what this PR fixes 

> The problem is that If you are on the 10th page of a search and search for something new, you go to the 10th page of the latest search result. Happens for collection as well.

This isn't happening for me on the gallery component and the collection search might be fixed in #2511

**Comment by Jarsen136** [comment]
> 

There is still the same problem online. You can have a try according to this video 

https://user-images.githubusercontent.com/31397967/157041990-c8c697ec-c795-4dbd-b59e-9a3677eea826.mov

**Comment by Jarsen136** [comment]
> > 
> 
> There is still the problem online. You can have a try to search on the nav bar.
> 
>  Screen.Recording.2022-03-07.at.9.19.04.PM.mov

Hi! Please see if this problem needs to be fixed ？ @yangwao

**Comment by yangwao** [comment]
Oh, I see now. You are right. When I search for `nft`, go to the 10th page, then search for `to` I'm actually on 10th page but URL shows page 1.

Plus I've found another issue, when I share someone's URL https://beta.kodadot.xyz/rmrk/gallery/?search=nft&page=10 it actually pushes me on page 1, rewriting the 10th page to first. If you can fix it with this that would be superior! :)

**Comment by yangwao** [comment]
If you @Jarsen136 join it with #2591 that would be superior! :)

**Comment by Jarsen136** [comment]
> I'm not a fan of using event bus, isn't there another solution to correct this problem?

Alright, I use another simple and reasonable solution to solve this bug instead of using event bus. 👋

**Comment by yangwao** [comment]
wfm! waiting some approval if so!

**Comment by yangwao** [comment]
yolo 
image

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 144.28 USD/KSM ~ 0.693 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xa019e8664673f1a96ac01516dc224ab131a538f33f9469797fd46abe7869424a](https://kusama.subscan.io/extrinsic/0xa019e8664673f1a96ac01516dc224ab131a538f33f9469797fd46abe7869424a)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
