### PR TITLE
feat: v4 koda logos 

### LINKED ISSUE #7444: The day has come - say bye to our v3 logo and hello to v4
image

- please pick svg logos from our presskit, leave the beta there please
- https://github.com/kodadot/kodadot-presskit/tree/main/pre-v4/svg
- dark for dark mode, light for light mode, use the black and white only, please, no color there
- updates in navbar

### PR DESCRIPTION
**Pull request by hassnian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #7444

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2023-10-10 at 10 30 48@2x

CleanShot 2023-10-10 at 10 31 14@2x

### <samp>🤖 Generated by Copilot at 6ff0e6f</samp>

Removed `height` attribute of logo image in `components/Navbar.vue` to fix layout issue on smaller screens. Made logo image responsive as part of mobile optimization pull request.

### <samp>🤖 Generated by Copilot at 6ff0e6f</samp>

> _`height` removed from logo_
> _layout issue is resolved_
> _website breathes in spring_

### CODE REVIEW

**Comment by exezbcz** [comment]
Light mode svgs dont load for me (also in the hero section) 
image

**Comment by hassnian** [comment]
> Light mode svgs dont load for me (also in the hero section) image

logos are there , there a bug, I remember facing the same issue when doing the audio player task, dark-light theme toggle doesn't work as expected , wanted to create an issue but I forgot

https://github.com/kodadot/nft-gallery/assets/44554284/70c0d623-cc2f-4f7b-8855-54800db5876f


> me (also in the hero section)

wdym

**Review by roiLeo — APPROVED** [review]
Could you remove fixed height? (`height="42"`) as it's not applied anymore

otherwise lgtm ✅

**Comment by exezbcz** [comment]
> wdym

just additional info that it applies to the hero svg shapes as well. 



smooth, works for me and thanks for fixing the switch!

**Comment by yangwao** [comment]
pay 20 usd

**Pull request merged**
