### PR TITLE
:tada: Updated polkadot@7.4 and other funky issues

### PR DESCRIPTION
**Pull request by vikiival**
- :construction: new api
- :broom: removed {isDev} from nuxt.config
- :memo: commented out forgoten toolbox
- :top: updated @polkadot packages
- :truck: moved plugins/api to plugins/polkadot
- :zap: removed cryptoWaitReady from the templates

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Do a quick check before the merge.

### PR type

- [x] Bugfix
- [x] Feature
- [x] Refactoring

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
Yes finally!
How did you manage to move code outside layout? What does it change? We only have to keep polkadot plugin?

**Comment by vikiival** [comment]
> How did you manage to move code outside layout?

The docs said that you should call crypto ready only once and since I had access to the store in plugins It was a great choice

> We only have to keep the polkadot plugin?

Yup!

**Comment by yangwao** [comment]
Seems related to 
- #1129 
- #1202

**Comment by yangwao** [comment]
Works way faster tho!

**Pull request merged**
