### PR TITLE
#5852 remove buefy tag

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [ ] Closes 
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)

## Screenshot 📸

- [x] My fix has changed UI
Screen Shot 2023-06-01 at 8 43 39 PM

### <samp>🤖 Generated by Copilot at 4b19b5a</samp>

Refactored and restyled the `NeoTag` component and added a `NeoIcon` component for better UI.

### <samp>🤖 Generated by Copilot at 4b19b5a</samp>

> _Oh, we're the crew of the `NeoTag` ship, and we sail the web so free_
> _We've refactored and restyled our code, to make it look so neat_
> _We've used a div and CSS, to give it some flair and flex_
> _And we've added a `NeoIcon` too, to close it with a click_

### CODE REVIEW

**Comment by prachi00** [comment]
there are 2 more files where we use <b-tag, but I think those will be deleted its Facts.vue & keyboardhosrtcutsmodal.vue , so didnt change it there 

PS. the cross icon in the tag now looks different as we use font awesome icon now

**Review by roiLeo — CHANGES_REQUESTED** [review]
No darkmode.
Screenshot 2023-06-02 at 08-02-43 Low minting fees and carbonless NFTs KodaDot - NFT Market Explorer

> there are 2 more files where we use <b-tag, but I think those will be deleted its Facts.vue & keyboardhosrtcutsmodal.vue , so didnt change it there

In keyboardhosrtcutsmodal replace b-tag with kbd.
`Facts` is not used, I would remove it.

**Review by roiLeo — APPROVED** [review]
✅ code lgtm

Next we can try to create `NeoTag` in `libs/ui`

**Review by preschian — APPROVED** [review]
already pointed by roiLeo

**Comment by prachi00** [comment]
can we merge this one?

**Pull request merged**
