### PR TITLE
fix: load-carousel-early

### LINKED ISSUE #7835: Skeleton loaders for newest list and latest sales
- I think it would be nice to introduce some sort of loader for these carousels - every time you enter the home page and scroll, it loads after getting to the bottom and seeing the footer 
image

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #7835

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)

## Screenshot 📸

- [ ] My fix has changed UI

### CODE REVIEW

**Comment by yangwao** [comment]
Can we check if LCP in the lighthouse has improved?

**Review by Jarsen136 — APPROVED** [review]
I guess we could also apply the same pattern to the Generative list on landing page

**Comment by prury** [comment]
@preschian it is faster indeed, but in the video below i could see some sort of glitch( around 0;18). 
for a moment it shows the images from the second page of the carousel and then it loads the images of the first page
not sure if it is problem worth pursuing tho, what do you think? 

https://github.com/kodadot/nft-gallery/assets/36627808/ff33b90a-6004-4dd2-93df-10bbe9494e10

**Comment by yangwao** [comment]
I see performance improvement? 

image

**Comment by yangwao** [comment]
yet mobile is still down bad 

image

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 6.76 USD/DOT ~ 4.438 $DOT
🧗 [1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p](https://polkadot.subscan.io/account/1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)
🔗 [0xa7ad40921ab14138651b78276e7f7f5e2db2ce7f930135255f94960eeede0ad0](https://polkadot.subscan.io/extrinsic/0xa7ad40921ab14138651b78276e7f7f5e2db2ce7f930135255f94960eeede0ad0)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
