### PR TITLE
feat: calculate 14days expiration for offer

### LINKED ISSUE #3339: When user submits make offer action, offer should have 14 day expiration on-chain
### Is your feature request related to a problem?

Currently offers are set to block 1mil

### Describe the solution you would like

I would like to see that we take current block and add number of blocks * 14

Screenshot 2022-07-06 at 13 00 14

basically formula => 
```ts
const BLOCK_OFFSET = 5 // time between submit & finalization
const BLOCK_PER_DAY_COUNT = 7200 // as on the picture 
const DAY_COUNT = 14 // two weeks
const currentBlock = await api.query.system.number()
const expiration = currentBlock + BLOCK_OFFSET + (BLOCK_PER_DAY_COUNT * DAY_COUNT)
```

### Describe alternatives you have considered

Screenshot 2022-07-06 at 13 04 56

### Screeenshots

_No response_

### Deliverables

When user makes transaction to make offer.
- [ ] instead of passing block [1 000 000](https://github.com/kodadot/nft-gallery/blob/dec0f3754b662423581420d999753934d946f8c9/utils/gallery/abstractCalls.ts#L33)
- [ ]  make sure you calculate the correct expiration date using formula above
- [ ] therefore `abstractCalls.ts#L33` should look like -> `MAKE_OFFER: [collectionId, tokenId, meta, expiration],`

### PR DESCRIPTION
**Pull request by zhengow**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3339 
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </bsx/gallery/2645998698-9>
- [x] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

### CODE REVIEW

**Comment by petersopko** [comment]
just from the first peak at this, can we format the estimated expiration time to something more user friendly ? 321614 doesn't tell me much 😅

**Review by petersopko — CHANGES_REQUESTED** [review]
pls let's go DD days HH hours MM minutes

**Comment by zhengow** [comment]
> pls let's go DD days HH hours MM minutes

Does **Expiration** column means the time left for offer to expire?
So I need to get current block number and expiration block number  to calculate the time with the given formula?

**Comment by yangwao** [comment]
> pls let's go DD days HH hours MM minutes

future blockchain time isn't pegged to your clock as block finalization may vary with each block; we can set only approximately estimation ~

The current block time is 12 seconds on Basilisk.

**Comment by petersopko** [comment]
> > pls let's go DD days HH hours MM minutes
> 
> 
> 
> future blockchain time isn't pegged to your clock as block finalization may vary with each block; we can set only approximately estimation ~
> 
> 
> 
> The current block time is 12 seconds on Basilisk.

Sure, we can perhaps add the info about this being just approx estimation, my point was just to make this more user friendly / useful data point 😄

**Comment by zhengow** [comment]
> > > pls let's go DD days HH hours MM minutes
> > 
> > 
> > future blockchain time isn't pegged to your clock as block finalization may vary with each block; we can set only approximately estimation ~
> > The current block time is 12 seconds on Basilisk.
> 
> Sure, we can perhaps add the info about this being just approx estimation, my point was just to make this more user friendly / useful data point 😄

Done, how about now?
image

**Comment by petersopko** [comment]
> > Done, how about now?

I have accidentally edited your comment instead of replying 😆  but you can see in it one last change I'd like @zhengow

**Comment by zhengow** [comment]
> > > Done, how about now?
> 
> I have accidentally edited your comment instead of replying 😆 but you can see in it one last change I'd like @zhengow

Ok, I remove `seconds`, pls check again:)
image

**Review by petersopko — APPROVED** [review]
tested, code looks to be doing what's it supposed to be doing
image
image

**Comment by petersopko** [comment]
I see there was a previous payout for this piece of art 😆
- https://github.com/kodadot/nft-gallery/pull/3381

I'm sending another 100 here since there was quite a bit of feedbacking and adjustments

**Comment by petersopko** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 59.13 USD/KSM ~ 1.691 $KSM
🧗 [EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws](https://kusama.subscan.io/account/EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)
🔗 [0xe77576121884bc97a4c09e5e0a3a30e32dcdbacc02dc4ccefc24db8646568241](https://kusama.subscan.io/extrinsic/0xe77576121884bc97a4c09e5e0a3a30e32dcdbacc02dc4ccefc24db8646568241)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by zhengow** [comment]
> I see there was a previous payout for this piece of art 😆
> 
> * [feat: calculate 14days expiration for `offer` #3381](https://github.com/kodadot/nft-gallery/pull/3381)
> 
> I'm sending another 100 here since there was quite a bit of feedbacking and adjustments

thanks, sir:)

**Pull request merged**
