### PR TITLE
where is my glmr

### PR DESCRIPTION
**Pull request by vikiival**
## Adding support for MoonBeam

- :bug: correct path for seo
- :wrench: added antick as indexer for glmr

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [x] Feature
- [ ] Refactoring

### CODE REVIEW

**Comment by vikiival** [comment]
Gonna update antick, some routes are failing

```js
"Variable \"$id\" of type \"String!\" used in position expecting type \"ID!\"."
```

**Comment by yangwao** [comment]
Apes are waiting 🥲

**Comment by vikiival** [comment]
https://github.com/kodadot/click/pull/42

**Comment by vikiival** [comment]
https://github.com/kodadot/click/actions/runs/3182379747/jobs/5188250336

**Comment by vikiival** [comment]
Screenshot 2022-10-04 at 15 44 21

**Comment by yangwao** [comment]
i heard after reset Antick, more collections are incoming

**Comment by vikiival** [comment]
"Can we merge ?"
- V. Buterin (Q2 2022)

**Comment by yangwao** [comment]
how it started 

telegram-cloud-photo-size-4-5899766691141892299-y

**Pull request merged**
