### PR TITLE
feat: Fix denomination to single decimal and bigger numbers short wit…

### LINKED ISSUE #6998: Fix denomination to single decimal and bigger numbers short with k & M
next I think would be to have only one decimal should be enough to have clear UI 
for bigger numbers I would use "k, M" 1000 -> 1k  & 1,000,000 -> 1M as some tokens are low on value

image

image

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/6975#issuecomment-1695423793_

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Feature

  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #6998
  - [ ] Requires deployment <snek/rubick/worker>

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

image

image

  ## Copilot Summary
  
### <samp>🤖 Generated by Copilot at c9b810b</samp>

The pull request adds a `formatNumber` function to the `format/balance` module and uses it to improve the formatting of token and usd values in the `MultipleBalances` and `GalleryItemActivityTable` components. It also adds a unit test for the `formatNumber` function. The goal is to enhance the readability and consistency of the balance formatting across the app.

  
### <samp>🤖 Generated by Copilot at c9b810b</samp>

> _`formatNumber` helps_
> _balance and transaction views_
> _autumn of clarity_

### CODE REVIEW

**Comment by Jarsen136** [comment]
It does not always display single-decimal but depends on different cases. Here are the cases inside the unit test.

```
  const cases = [
      [0, '0'],
      [1, '1'],
      [1.1, '1.1'],
      [1.15, '1.1'],
      [1.16, '1.2'],
      [0.1, '0.1'],
      [0.09, '0.09'],
      [0.009, '0.009'],
      [0.0009, '0.0009'],
      [0.00009, '0.0001'],
      [1000, '1k'],
      [1200, '1.2k'],
      [1900, '1.9k'],
      [1000000, '1M'],
      [1100000, '1.1M'],
      [1110000, '1.1M'],
      [10000000, '10M'],
    ]
```

**Review by roiLeo — APPROVED** [review]
- too many return  
- transform number to string then transforming again string to number ❔ 

but if it works as excepted lets go

**Comment by Jarsen136** [comment]
> * too many return
> * transform number to string then transforming again string to number ❔
> 
Updated. They should be solved now.

**Comment by yangwao** [comment]
will process along
- #7035

**Comment by yangwao** [comment]
pay 30

**Comment by yangwao** [comment]
test

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 4.69 USD/DOT ~ 6.397 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0xe52887681164e63cc94c3fa23729ea0f40d25dfd7e2b4432edf88c47c321f1cc](https://polkadot.subscan.io/extrinsic/0xe52887681164e63cc94c3fa23729ea0f40d25dfd7e2b4432edf88c47c321f1cc)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 4.69 USD/DOT ~ 6.397 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0xc332716fb2baf51e2b7da9d4adc22b34813c61ee5f817b5cffbe7207b96f57f8](https://polkadot.subscan.io/extrinsic/0xc332716fb2baf51e2b7da9d4adc22b34813c61ee5f817b5cffbe7207b96f57f8)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
