### PR TITLE
code checker resolve issue modals

### LINKED ISSUE #9574: Code checker - Resolve issue modals
image
image

## Design
- updated in handoff: https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=7790-35100&mode=design&t=bmCVVE54tUaBgatv-11
- it will be modal because having inline explainers will make the UI cluttered. Some explainers are longer than other

## How it works
- when a check fails, link "resolve issue" will be shown
- once clicked, it opens modal 

modal is has the same as our guide on hello: 
https://hello.kodadot.xyz/tutorial/generative-art/code-checker
thanks, @daiagi for making it! 

heading bold: 
image

then code snippet
- can be used what ever tailwind offers, nothing preferred, syntax highlighting would be nice

something like this: 
image
https://tailwindflex.com/@alok/code-block-with-copy-button

make it easy as possible, nothing custom for that

### PR DESCRIPTION
**Pull request by newraina**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Needs Design check

- @exezbcz please review

## Context

- [x] Closes #9574 
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer?target=1CAv6Zq3yVxL3eKhC94GWTWVwp1w4jZbqeZ6wXx1rPAhrce&usdamount=0&donation=true)

## Screenshot 📸

- [x] My fix has changed UI

CleanShot 2024-03-03-MpssNMBl@2x

CleanShot 2024-03-03-5RLaPJTm@2x

### CODE REVIEW

**Comment by exezbcz** [comment]
i see that you have made it custom :D 


>then code snippet
>
>can be used what ever tailwind offers, nothing preferred, syntax highlighting would be nice
>something like this:
>image
>[tailwindflex.com/@alok/code-block-with-copy-button](https://tailwindflex.com/@alok/code-block-with-copy-button)

>make it easy as possible, nothing custom for that

**Comment by newraina** [comment]
> i see that you have made it custom :D

@exezbcz Tailwindcss does not have its own code block style, and using the tailwindflex you provided also requires some extra work, so I simply implemented it according to figma, which is almost as simple as tailwindflex.

**Comment by exezbcz** [comment]
@newraina i see, appreciate that sir

**Comment by prury** [comment]
sometimes code loses formatting: 
image

sometimes code formatting gets weird: 
image

scrollbar in the same place as copy code button
image
cc: @exezbcz

**Comment by newraina** [comment]
@prury try again

**Review by preschian — APPROVED** [review]
code lgtm

**Comment by prury** [comment]
> @prury try again

thank you, only the white border text still happening: 

https://github.com/kodadot/nft-gallery/assets/36627808/9488ca2f-ba04-4252-988c-120199a742a0

**Review by Jarsen136 — APPROVED** [review]

**Comment by newraina** [comment]
@prury please try again

**Review by prury — APPROVED** [review]

**Comment by yangwao** [comment]
Thanks!
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 10.29 USD/DOT ~ 4.859 $DOT
🧗 [1CAv6Zq3yVxL3eKhC94GWTWVwp1w4jZbqeZ6wXx1rPAhrce](https://polkadot.subscan.io/account/1CAv6Zq3yVxL3eKhC94GWTWVwp1w4jZbqeZ6wXx1rPAhrce)
🔗 [0xc38a0b2716c9649f4531ec4eef4a145857e9724b0e02ea9a89b887e99790ef51](https://polkadot.subscan.io/extrinsic/0xc38a0b2716c9649f4531ec4eef4a145857e9724b0e02ea9a89b887e99790ef51)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
