### PR TITLE
#1667 Add preloader to spotlight & series

### LINKED ISSUE #1667: Add preloader to spotlight & series
Add preloader component with facts here on spotlight and series insights.

But keep it showing till all data loads

image

As on mobile, it's for mystic reasons, slow.

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇  _ Do a quick check before the merge. 

### PR type
- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main-nuxt** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases

### What's new?
- [x] PR closes #1667

### Had issue bounty label ?
- [x] Fill up your KSM address: 
[Payout](https://kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation
- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [x] My fix has changed **something** on UI, a screenshot is best to understand changes for others.
Screenshot 2022-01-06 at 1 27 20 PM

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
I found a case where I was stuck on the loader (request in error) and I could not change the page.
Looks like the `<Loader />` is blocking UI until the request ends

**Comment by prachi00** [comment]
> I found a case where I was stuck on the loader (request in error) and I could not change the page. Looks like the `<Loader />` is blocking UI until the request ends
Screenshot 2022-01-06 at 3 05 13 PM

for me its going to this page in case of errors, how do I replicate your case?

**Comment by roiLeo** [comment]
> for me its going to this page in case of errors, how do I replicate your case?

It's weird, now it works I'm redirected to Indexer Error page.

**Comment by roiLeo** [comment]
Trapped again:
Screenshot 2022-01-06 at 11-10-35 KodaDot - Polkadot Kusama NFT explorer
Capture d’écran 2022-01-06 à 11 11 58 AM

are you outdated from main-nuxt? I don't have this error on beta website
Maybe netlify cache

**Comment by prachi00** [comment]
> Trapped again: Screenshot 2022-01-06 at 11-10-35 KodaDot - Polkadot Kusama NFT explorer Capture d’écran 2022-01-06 à 11 11 58 AM
> 
> are you outdated from main-nuxt? I don't have this error on beta website Maybe netlify cache

not sure whats happening, I have the latest version running, isn't happening on the local environment tho

**Comment by vikiival** [comment]
Looks like It's an error from the 🐙 query

**Comment by vikiival** [comment]
`[{message: "Cannot query field "totalBuys" on type "SeriesEntity". Did you mean "total"?",…}]`

Beta:
Screenshot 2022-01-07 at 10 09 50

Endpoint:
Screenshot 2022-01-07 at 10 06 08


According to PR, it does not look like @prachi00 has changed the query.

Closing the issue and try to make PR again

**Comment by roiLeo** [comment]
This could be the problem.
https://github.com/prachi00/nft-gallery/blob/feat-loader-add/queries/rmrk/subsquid/collectionSeriesList.graphql

I think it should be:
```graphql
query collectionSeriesList($limit: Float) {
  collectionEntities: seriesInsightTable(limit: $limit) {
    id
    floorPrice
    averagePrice
    image
    metadata
    sold
    name
    total
    totalBuys: buys
    unique
    uniqueCollectors
    volume
  }
}
```

**Pull request closed without merging**
