### PR TITLE
fix: Popup on links in cards

### LINKED ISSUE #4707: Popup on links in cards
The hover cards popups inside the container and it blocks all the content
image

- depending on the amount of space up and down, should be at the bottom or at the top of the link you are hovering over.

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4707
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by exezbcz** [comment]
good job! 
can we also make the popup stay shorter on screen after you are not hovering over the link/popup? 
Right now it can get pretty weird when you hover over few links in a row.

**Comment by Jarsen136** [comment]
> good job! can we also make the popup stay shorter on screen after you are not hovering over the link/popup? Right now it can get pretty weird when you hover over few links in a row.

✅ done  @exezbcz

**Comment by exezbcz** [comment]
> > good job! can we also make the popup stay shorter on screen after you are not hovering over the link/popup? Right now it can get pretty weird when you hover over few links in a row.
> 
> ✅ done @exezbcz

thanks! 🚀

**Review by roiLeo — APPROVED** [review]
✅ wfm, delay is shorter now

**Comment by yangwao** [comment]
pay 30

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 31.18 USD/KSM ~ 0.962 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x4037fe199c2316ce65233ac470707e73afd424633cdf768ccd6b30438243972d](https://kusama.subscan.io/extrinsic/0x4037fe199c2316ce65233ac470707e73afd424633cdf768ccd6b30438243972d)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
