### PR TITLE
feat: use v-safe-href to sanitize url

### LINKED ISSUE #6692: Make sure bypassing Vue built-in sanitization is safe here.
would be nice to check on this security hotspot report, I think it's high severity

SonarCloud Quality Gate failed.&nbsp; &nbsp; [Quality Gate failed](https://sonarcloud.io/dashboard?id=kodadot_nft-gallery&pullRequest=6639)

[Bug](https://sonarcloud.io/project/issues?id=kodadot_nft-gallery&pullRequest=6639&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=kodadot_nft-gallery&pullRequest=6639&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=kodadot_nft-gallery&pullRequest=6639&resolved=false&types=BUG)  
[Vulnerability](https://sonarcloud.io/project/issues?id=kodadot_nft-gallery&pullRequest=6639&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=kodadot_nft-gallery&pullRequest=6639&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=kodadot_nft-gallery&pullRequest=6639&resolved=false&types=VULNERABILITY)  
[Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=kodadot_nft-gallery&pullRequest=6639&resolved=false&types=SECURITY_HOTSPOT) [E](https://sonarcloud.io/project/security_hotspots?id=kodadot_nft-gallery&pullRequest=6639&resolved=false&types=SECURITY_HOTSPOT) [1 Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=kodadot_nft-gallery&pullRequest=6639&resolved=false&types=SECURITY_HOTSPOT)  
[Code Smell](https://sonarcloud.io/project/issues?id=kodadot_nft-gallery&pullRequest=6639&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=kodadot_nft-gallery&pullRequest=6639&resolved=false&types=CODE_SMELL) [5 Code Smells](https://sonarcloud.io/project/issues?id=kodadot_nft-gallery&pullRequest=6639&resolved=false&types=CODE_SMELL)

[No Coverage information](https://sonarcloud.io/component_measures?id=kodadot_nft-gallery&pullRequest=6639) No Coverage information  
[](https://sonarcloud.io/component_measures?id=kodadot_nft-gallery&pullRequest=6639&metric=new_duplicated_lines_density&view=list) [12.0% Duplication](https://sonarcloud.io/component_measures?id=kodadot_nft-gallery&pullRequest=6639&metric=new_duplicated_lines_density&view=list)

idea Catch issues before they fail your Quality Gate with our IDE extension sonarlint [SonarLint](https://www.sonarsource.com/products/sonarlint/features/connected-mode/?referrer=sonarcloud-welcome)

_Originally posted by @sonarcloud[bot] in https://github.com/kodadot/nft-gallery/issues/6639#issuecomment-1675941713_

### PR DESCRIPTION
**Pull request by floyd-li**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

just follow the [`Vue` best practices](https://vuejs.org/guide/best-practices/security.html#url-injection), use [sanitize-url](https://www.npmjs.com/package/@braintree/sanitize-url) to avoid the `URL Injection`.

Also, to avoid change all the `href` link in the project i add a `v-safe-href` directive, so the fix will be much easier imo.

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #6692
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at 94e800e</samp>

Refactored the footer component and moved it to `components/TheFooter.vue`. Replaced `<a>` elements with `nuxt-link` or `v-safe-href` in various files to improve navigation and security. Fixed the code style of `twitterText` in `components/collection/unlockable/UnlockableLoader.vue`.

### <samp>🤖 Generated by Copilot at 94e800e</samp>

> _Sing, O Muse, of the skillful refactoring_
> _That the wise and nimble coder wrought_
> _On the many `<a>` elements, transforming_
> _Them to `nuxt-link` for speed and thought._

### CODE REVIEW

**Comment by prury** [comment]
TheFooter - ✔️ 
unlockable twitter
wallet asset menu ✔️
walletassetnfts ✔️
walletassetportfolio ✔️
shoppingcart modal ✔️

drops:
dropcard ✔️

Gallery:
galleryitemdescription ❌ (metadata)
unlockabletag - ✔️

identity:
itentityItem  

module: 
identitylink
identitypopoverheader
identitySocial
 
landing:
Featured Articles ✔️

media/type:
UnknowMedia - must search

RMRK/profile:
ProfileDetail ✔️ 

Shared:
blockexplorerlink ✔️
LinkResolver 

Format:
ExternalLink ✔️

Teleport
Teleport.vue ✔️

Transfer:
TransferOld 

components:

CardArticle.story - not sure if used
CardArticle - not sure if used

NeoNFTCard ✔️

blog links ✔️ 

QR Code

**Comment by floyd-li** [comment]
> Gallery:
> galleryitemdescription ❌ (metadata)

this one has been fixed @prury

**Review by preschian — APPROVED** [review]
cool, I like it 👍

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 4.93 USD/DOT ~ 10.142 $DOT
🧗 [13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A](https://polkadot.subscan.io/account/13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A)
🔗 [0x905640b560738b6ed4dce515562f9dbcc341893f6c84b86e41765db6556c45ad](https://polkadot.subscan.io/extrinsic/0x905640b560738b6ed4dce515562f9dbcc341893f6c84b86e41765db6556c45ad)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
