### PR TITLE
build: add nuxt-optimisations

### PR DESCRIPTION
**Pull request by preschian**
## Context

- [x] Related #6518. not a fix, just trying to optimise our build steps

### CODE REVIEW

**Comment by preschian** [comment]
> I would remove sentry if it's blocking untill we migrate to Nuxt3.

https://github.com/kodadot/nft-gallery/pull/6672

but, I guess the root cause is not Sentry

**Comment by roiLeo** [comment]
> but, I guess the root cause is not Sentry

👀 any logs output to share?

**Comment by preschian** [comment]
> 👀 any logs output to share?

wait, will explain in the main issue. the difficult part is the error was intermittent. sometimes, I face it at my local

Screenshot 2023-08-11 135903

**Comment by yangwao** [comment]
image

@preschian let's resolve and I'm ok to merge it!

**Review by yangwao — APPROVED** [review]
let's give it shot

**Comment by roiLeo** [comment]
Do we still have deploy issue after removing sentry?

**Comment by yangwao** [comment]
> Do we still have deploy issue after removing sentry?

iirc no, canary builds well

**Comment by roiLeo** [comment]
> iirc no, canary builds well

Then I don't think we need these changes since we'll drop webpack soon

**Comment by yangwao** [comment]
> we'll drop webpack soon



wen is soon 😏

**Comment by roiLeo** [comment]
> wen is soon 😏

I'll put my two cents in couple of weeks (month maybe?) 
finish #4750 first, some large components need to be rewritten (GalleryItem, BaseForm etc..), a little help wouldn't be amiss

**Comment by preschian** [comment]
> I'll put my two cents in couple of weeks (month maybe?)

what if we merge while waiting for this?

because deleting this section is not too hard, I guess. and we need to remove `build.optimization` and `build.extend(config)` if we want to drop webpack

**Comment by preschian** [comment]
> Do we still have deploy issue after removing sentry?

anyway, I hope I'm wrong

but, the build in this PR https://github.com/kodadot/nft-gallery/pull/6676/commits was incomplete. when I browse the repository based on that commit, the sentry-related package is already removed, right?

**Comment by yangwao** [comment]
> a little help wouldn't be amiss

I heard someone from unjs and nuxt team coming for rescue 🛟

**Comment by preschian** [comment]
> I heard someone from unjs and nuxt team coming for rescue 🛟

woohh, this would be great 🚀

**Comment by preschian** [comment]
> looks like it, but the package itself without token build well, soo

Another example, build in this PR failed on gh-actions https://github.com/kodadot/nft-gallery/actions/runs/5840239957/job/15839267672?pr=6685

So, even if we have already removed sentry-related packages, the error still comes back again sometimes

**Pull request merged**
