### PR TITLE
➖ b-table component

### PR DESCRIPTION
**Pull request by roiLeo**
- related with #5852 

### What need to be checked

All tables should work

### CODE REVIEW

**Comment by yangwao** [comment]
image

feel free to use 
https://github.com/kodadot/nft-gallery/blob/main/.github/PULL_REQUEST_TEMPLATE/QUICK_AND_QA_PULL_REQUEST_TEMPLATE.md

**Comment by prury** [comment]
I'm almost sure I've tackled all of them

is HoTables.vue equivalent to this path? https://deploy-preview-6144--koda-canary.netlify.app/hot/

some minor bugs:
- scroll appears when hovering on date:

https://github.com/kodadot/nft-gallery/assets/36627808/ce51bea2-f0fd-448d-a8cb-fd340debf3e2

- compared to beta, some tables are slightly closer to the left:

https://github.com/kodadot/nft-gallery/assets/36627808/21a012e7-9d16-4fc3-99c8-e4d31ccb8770

unrelated: date tool tip being shown under other components

**Comment by roiLeo** [comment]
> I'm almost sure I've tackled all of them
> 
> is HoTables.vue equivalent to this path? https://deploy-preview-6144--koda-canary.netlify.app/hot/

Yup, now fixed.

> some minor bugs:
> 
>  scroll appears when hovering on date:

fixed by changing tooltip position


> compared to beta, some tables are slightly closer to the left:

which one?

> slight.moved.mp4

Didn't touched item "Activity" table code so it should remain the same as beta

**Comment by prury** [comment]
> > I'm almost sure I've tackled all of them
> > is HoTables.vue equivalent to this path? https://deploy-preview-6144--koda-canary.netlify.app/hot/
> 
> Yup, now fixed.
> 
nice! 
> > some minor bugs:
> > scroll appears when hovering on date:
> 
> fixed by changing tooltip position
> 
Still happening, but now i can't see the tooltip unless i scroll down

image

> > compared to beta, some tables are slightly closer to the left:
> 
> which one?
> 
> > slight.moved.mp4
> 
> Didn't touched item "Activity" table code so it should remain the same as beta

The same one as the video was showing(Activity), ok, allright.

**Comment by prury** [comment]
@roiLeo also happening on the sales tab, but i guess it is part of a bigger problem? #[521](https://github.com/oruga-ui/oruga/issues/521)
mobile also displays the same behavior, i guess the solution on beta was not to show the tool tip when using mobile

**Comment by roiLeo** [comment]
may I ask review @kodadot/code-review-guild

**Comment by vikiival** [comment]
Just wondering: Why it has the light black background behind the table?
is it some design mastery? cc @exezbcz ?

243355111-09f37224-8870-41fa-9a33-cb2958606490

**Review by vikiival — APPROVED** [review]
CODE LGTM 🚀

**Comment by roiLeo** [comment]
> Just wondering: Why it has the light black background behind the table? is it some design mastery? cc @exezbcz ?

Because table is wrapped inside a `.box`

**Comment by yangwao** [comment]
> Just wondering: Why it has the light black background behind the table?

yes this is quite known bug what I've seen

**Pull request merged**
