### PR TITLE
⚒️ set identity from identityForm

### LINKED ISSUE #2706: Identity form fails to set identity
Wanted to set identity for the payout bot but our identity dialogue has failed

Address seems have do balance 9+ ksm.
https://kusama.subscan.io/account/G29NScLSew5zqwmJAPupvJWDCDkpxKUhDnMeVdD2BBcnHar

image

```
21cdd8b.js:2 2022-03-29 14:07:42             DRR: Invalid empty address passed
O @ 21cdd8b.js:2
c6205aa.js:1 [ERR: BALANCE] Error: Invalid empty address passed
```

```bash
6669c3e.js:1 Error: createType(Call):: Call: failed decoding identity.setIdentity:: Struct: failed on args: {"info":"{\"additional\":\"Vec<(Data,Data)>\",\"display\":\"Data\",\"legal\":\"Data\",\"web\":\"Data\",\"riot\":\"Data\",\"email\":\"Data\",\"pgpFingerprint\":\"Option<[u8;20]>\",\"image\":\"Data\",\"twitter\":\"Data\"}"}:: Struct: failed on info: {"additional":"Vec<(Data,Data)>","display":"Data","legal":"Data","web":"Data","riot":"Data","email":"Data","pgpFingerprint":"Option<[u8;20]>","image":"Data","twitter":"Data"}:: Struct: failed on web: {"_enum":{"None":"Null","Raw":"Bytes","BlakeTwo256":"H256","Sha256":"H256","Keccak256":"H256","ShaThree256":"H256"}}:: Data.Raw values are limited to a maximum length of 32 bytes
```

### PR DESCRIPTION
**Pull request by roiLeo**
I wanted to test it without making the transaction but I commented the wrong line during my test... 
IdentityForm work well I've manage to set a name to a wallet

### PR type

- [x] Bugfix?

### What's new?

- [x] PR closes #2706 
- [x] fix identity page layout
- [x] some refactoring
- [x] display account balance 

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=HguGafrfk8nRP9a4tgJf7hLvSSFie8GtkDjyWFHQ2kDUAMc)

### CODE REVIEW

**Review by vikiival — CHANGES_REQUESTED** [review]
Few things: 
- I would use the `BasicInput` component
- we have also `SubmitButton`
- may `metaTransactionMixin` can really be your friend

**Comment by vikiival** [comment]
> pre-fill inputs

would be lovely! 

hack

```ts
  mounted() {
    onApiConnect(async () => {
      this.identity = await this.identityOf(this.resolveAddress(this.address))
    })
  }
```

**Comment by vikiival** [comment]
Like yolo fix would be just fetch last data from the identity store. 

Let's make it that way.

Otherwise code LGTM  

Haven't tested yet

**Comment by roiLeo** [comment]
I need to find a way to transform raw Data to string (like `handleRaw` method)
```json
{ "additional": [], "display": { "raw": "0x57616c6c657420436f6e6e656374" }, "legal": { "none": null }, "web": { "none": null }, "riot": { "none": null }, "email": { "none": null }, "pgpFingerprint": null, "image": { "none": null }, "twitter": { "none": null } }
```

 it's not the first time I've been stuck on this point

**Comment by yangwao** [comment]
can I test it?

**Comment by roiLeo** [comment]
> can I test it?

sure

**Comment by yangwao** [comment]
seems worked, lgtm ✅

waiting for @vikiival 

image

**Comment by yangwao** [comment]
pay 150 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $150 @ 165.12 USD/KSM ~ 0.908 $KSM
🧗 [HguGafrfk8nRP9a4tgJf7hLvSSFie8GtkDjyWFHQ2kDUAMc](https://kusama.subscan.io/account/HguGafrfk8nRP9a4tgJf7hLvSSFie8GtkDjyWFHQ2kDUAMc)
🔗 [0x6bf04b669983dcbd04de7175dbf8a0899d6dc2dca38b9f833b3335ef22d40b27](https://kusama.subscan.io/extrinsic/0x6bf04b669983dcbd04de7175dbf8a0899d6dc2dca38b9f833b3335ef22d40b27)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
