### PR TITLE
fix: Make sure that EVM connectors work properly

### LINKED ISSUE #10747: Make sure that EVM connectors work properly
### Context

Me and @exezbcz are experiencing an issues with signing both with Metamask and Talisman.
As Metamask is frequently used wallet I would be in favour of making it work.

### Task 

1. review the current implementation of Web3 modal 
2. consult the docs - https://docs.walletconnect.com/appkit/vue/core/installation
3. Test minting of both free drops and paid drops with - Metamask, Coinbase, Talisman?

Screenshot 2024-08-05 at 12 25 17

In any case feel free to reach me in issue / TG

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #10747
- [x] fix: Evm wallet disconnect not working
- [x] fix: Paid mint modal not closing

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI;

### CODE REVIEW

**Comment by hassnian** [comment]
@vikiival can you test and let me know ?

now it should allow you sign with any evm wallet*

* I have found another case that is not working (currently investigating that), connecting directly with coinbase works , but if you connect with any evm wallet and disconnect and try to connect with coinbase that's not working for me.

**Comment by exezbcz** [comment]
@hassnian nice, managed to sign a drop mint, good job

**Comment by vikiival** [comment]
1. Metamask, Talisman works smoothly

2. Coinbase works after hard reload

>  but if you connect with any evm wallet and disconnect and try to connect with coinbase that's not working for me.

I was able to reproduce this one

**Comment by hassnian** [comment]
>>but if you connect with any evm wallet and disconnect and try to connect with coinbase that's not working for me.

> I was able to reproduce this one

took some time to debug, the issue was that we were clearing the entire localstorage when logging out, and coinbase wallet was using that to store data

--------

should work now , tried with **multiple wallets installed** and all flows works.

@vikiival @JustLuuuu  @kodadot/internal-dev  need help testing, let me know if anyone is experiencing any other issue.

pls connect with a wallet try minting (the connected wallet should appear) , disconnect that wallet and repeat the same process with another wallet.

thanks

**Comment by vikiival** [comment]
You have some conflicts

**Comment by preschian** [comment]
> pls connect with a wallet try minting (the connected wallet should appear) , disconnect that wallet and repeat the same process with another wallet.

This one looks fine

But when I want to mint, it shows the onramp button on the free drop. After reloading, it works



After minting and wanna switch to another wallet, it shows both vm. Which one is correct? On reload, it only shows the web3modal button

**Comment by vikiival** [comment]
@preschian pls open new issues

**Comment by hassnian** [comment]
> You have some conflicts

done 

> @preschian pls open new issues

opened two new issues

**Comment by preschian** [comment]
> opened two new issues

thank you

**Review by preschian — APPROVED** [review]

**Review by Jarsen136 — APPROVED** [review]

**Pull request merged**
