### PR TITLE
chore: filter out polkadot from chain selector

### LINKED ISSUE #6494: Polkadot and Kusama NFTs are the same
I'm just curious. This is in production. We have Polkadot NFTs. But they are showing the same NFTs as Kusama NFTs(rmrk). Is that intentional? 

Screenshot 2023-07-30 at 10 53 50

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Closes #6494
- [x] remove warning on explore/items

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)

image

### CODE REVIEW

**Comment by vikiival** [comment]
cc @preschian check the comment above

**Comment by preschian** [comment]
> which would state if its visible for user

In which line do we put this? and how we differentiate based on env. currently, we have two visible categories
- `['dot']` -> all env
- `['dot', 'movr', 'glmr', 'snek']` -> beta and production

**Comment by yangwao** [comment]
@JustLuuuu will be now happy

**Comment by vikiival** [comment]
Let's proceed with this quickie

**Comment by stephenjason89** [comment]
Hello guys! Just noticed that explorerVisible got removed here but there are still some files referencing it.
Please advice what to do with https://github.com/kodadot/nft-gallery/issues/6769
So I can procede with a PR

Thank you so much @vikiival @yangwao @preschian

**Comment by preschian** [comment]
hi @stephenjason89, let's revert it back on permission.config

**Comment by stephenjason89** [comment]
@preschian noted on this. Will do a PR now

**Pull request merged**
