### PR TITLE
creator twitter added

### LINKED ISSUE #1415: Creator twitter doesn't appear on collection
When I'm going from 
https://deploy-preview-1395--koda-nuxt.netlify.app/rmrk/gallery/10352274-409E451AFD98397563-AURA3D-AURA-V-0000000000000006

I see Twitter of artist  
image

When I land on collection I don't see it anymore 👀
image

### PR DESCRIPTION
**Pull request by lohba**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇  _ Do a quick check before the merge. 

Screen Shot 2021-12-08 at 6 46 06 AM

### PR type
- [X] Bugfix
- [ ] Feature
- [ ] Refactoring

### Before submitting Pull Request, please make sure:
- [X] My contribution builds **clean without any errors or warnings**
- [X] I've merged recent default branch -- **main** and I've no conflicts
- [X] I've tried respect high code quality standards
- [X] I've didn't break any original functionality
- [X] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything works
- [ ] I found edge cases

### What's new?
- [X] PR closes #1415
- [X] Added twitter account to the collection page

### Had issue bounty label ?
- [X] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EAeSkdwjgMBmVFcACVFGzqxmGqib8k8uXdNmtWTcWsLoGPU)

### Community participation
- [X] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [X] My fix has changed **something** on UI, a screenshot for others, is best to understand changes.

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
I recall this one, it happend because prop type isn't defined as Boolean in ProfileLink
ref #1147 

Edit, should work with:
```js
  @Prop(Boolean) public showTwitter!: boolean;
```

**Review by vikiival — CHANGES_REQUESTED** [review]
Please check the @roiLeo 's suggestion

```js
  @Prop(Boolean) public showTwitter!: boolean;
```

**Review by roiLeo — APPROVED** [review]
lgtm

**Comment by yangwao** [comment]
Perfect, I’ve sent the payout https://kusama.subscan.io/extrinsic/0x0ba6e1894450bfda82d058f98ffc25f8b3399c51f28d2cdfa19ea5751455d889

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/

**Pull request merged**
