### PR TITLE
Update es.json (English > Spanish)

### PR DESCRIPTION
**Pull request by katongo11**
Spanish translation completed

### CODE REVIEW

**Comment by katongo11** [comment]
I've completed the spanish translation for the kodadot dashboard.

Any doubt please let me know.

**Comment by yangwao** [comment]
Hey thank you for your translation! Don't forget post your KSM address!

**Comment by katongo11** [comment]
Thank you!
KSM address: EAsezv9EYyKQc7tbuDHp6s8GmrzCJ5fJG7gfQhaxQrf7aiQ

**Comment by katongo11** [comment]
> Hey thank you for your translation! Don't forget post your KSM address!

Thank you!
KSM address: EAsezv9EYyKQc7tbuDHp6s8GmrzCJ5fJG7gfQhaxQrf7aiQ

**Pull request merged**
