### PR TITLE
fix: make event passive to fix sluggish vertical scroll

### LINKED ISSUE #4160: Landing page issue on scroll
### What happened?
On new landing page I noticed that the vertical scroll was difficult when hovering a card
It might come from carousel component?

### Step to reproduce
- go to beta
- put your pointer on any carousel card
- scroll down or up 
- it's difficult?

### Video
📹 

___Tested on OSX 13-iinch___

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #4160
- [ ] Requires deployment <rubick/magick_issue>
- [x] Fixed an issue that prevented users from scrolling smoothly over Carousels on Firefox

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by Jarsen136 — APPROVED** [review]
code lgtm

**Review by roiLeo — APPROVED** [review]
✅ Top! wfm

**Comment by roiLeo** [comment]
pay 20

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 34.22 USD/KSM ~ 0.584 $KSM
🧗 [EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW](https://kusama.subscan.io/account/EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)
🔗 [0xf48536a5a074378fa5bdc63286a6fc1307f04c768f50fcf521e3b1c1370119fd](https://kusama.subscan.io/extrinsic/0xf48536a5a074378fa5bdc63286a6fc1307f04c768f50fcf521e3b1c1370119fd)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
