### PR TITLE
fix: request error from sort by condition

### LINKED ISSUE #3467: Seems Magick down on collection detail
Seems Magick down? 

Can't view collection detail 
https://beta.kodadot.xyz/rmrk/collection/C6E2CA836BD86CBD05-PLACE

Are we using Magick differently for collection or to rewrite it with subsquid? 

image

at collection seems it works

image

even gallery

image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3467
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Review by prachi00 — APPROVED** [review]

**Comment by prachi00** [comment]
wfm

**Comment by prachi00** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 63.56 USD/KSM ~ 0.787 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x28dd213b376ab0bd62095f88f9ca00f14ae7c49d496821a94286722d18e5fcbf](https://kusama.subscan.io/extrinsic/0x28dd213b376ab0bd62095f88f9ca00f14ae7c49d496821a94286722d18e5fcbf)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by prachi00** [comment]
heyyy @Jarsen136 before I merge this, can you take a look at the deepscan issue if it is something?

**Comment by Jarsen136** [comment]
> heyyy @Jarsen136 before I merge this, can you take a look at the deepscan issue if it is something?

Let's merge it. It's should not be a mistake.

**Pull request merged**
