### PR TITLE
chore: enable source maps for sentry

### LINKED ISSUE #4670: Enable Source maps at Sentry
Seems current issues 
- https://github.com/kodadot/nft-gallery/issues/4669
- https://github.com/kodadot/nft-gallery/issues/4668
- https://github.com/kodadot/nft-gallery/issues/4667
- https://github.com/kodadot/nft-gallery/issues/4662

As w/o source maps doesn't provide any readable stack trace 
to have it let's proceed and configure one to upload to sentry 

https://docs.sentry.io/platforms/javascript/sourcemaps/

If someone want to take a look to enable leverage Sentry and debug few errors which are happening right now, currently 64 errors happening for last hours

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #4670

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by yangwao** [comment]
> need to add `SENTRY_AUTH_TOKEN` env to netlify

done this part, let's test it?

**Review by vikiival — APPROVED** [review]

**Comment by yangwao** [comment]
Will white list work with subdomains like beta.kodadot.xyz and previews from netlify?

**Comment by yangwao** [comment]
> need to put cloudflare pages
image

done

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 28.11 USD/KSM ~ 1.779 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0x95fc56a921cabf1086b4bf9b771efc337180831aca5f85c67f4c751713da6d6f](https://kusama.subscan.io/extrinsic/0x95fc56a921cabf1086b4bf9b771efc337180831aca5f85c67f4c751713da6d6f)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
