### PR TITLE
build: temporary disable source-map

### LINKED ISSUE #6518: Inspect why Sentry plugin breaks builds on CloudFlare Pages
@preschian Okay, it's a sentry plugin. Seems builds.  

- https://github.com/nuxt-community/sentry-module

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/6470#issuecomment-1662093932_

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #6518. at least we can put `SENTRY_AUTH_TOKEN` back in the env. ongoing investigation here https://community.cloudflare.com/t/recurring-deployment-issue-on-pages-which-works-on-preview-branch-but-doesnt-on-production-branch/540278/10

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)

## Screenshot 📸

<details><summary>screenshot</summary>
<p>

Screenshot 2023-08-03 140759

</p>
</details>

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
Imo it shouldnt pass this condition since it's not NODE_ENV dev, lgtm

**Review by Jarsen136 — APPROVED** [review]
Looks like it's not the root reason. It could be a temporary fix if needed.

image

**Comment by yangwao** [comment]
I think they have different environment, as netlify builds well :D

**Comment by yangwao** [comment]
pay 50 usd

but seems we don't need to set ENV variable for sentry? 

https://docs.sentry.io/platforms/javascript/guides/vue/

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 4.99 USD/DOT ~ 10.02 $DOT
🧗 [1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p](https://polkadot.subscan.io/account/1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)
🔗 [0x99b17cd4047d1dd01a11b09fd24efd4bd0df4874890b24b7b41f44ea2719d1ea](https://polkadot.subscan.io/extrinsic/0x99b17cd4047d1dd01a11b09fd24efd4bd0df4874890b24b7b41f44ea2719d1ea)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
