### PR TITLE
fix: unable to click submit button on bsx

### LINKED ISSUE #3395: Balance on account not loading properly
~Trying to burn NFT, my balance shows me zero on both Transfer / item detail, didn't catch that in screenshot, after refresh there's a balance, but still won't let me burn because apparently, balance 0.~

When the balance reappears after refresh, I can burn/buy/perform transaction now thanks to:
- #3396 

The issue with balance initially loading with 0 is still here on deploy from #3396 or on beta.

image

Only thing I can get from console is this
image

### LINKED ISSUE #3412: Disabled buy on basilisk even I have enough balance?
Seems to buy is disabled even though I have enough balance?

https://beta.kodadot.xyz/bsx/gallery/2645998698-6
https://beta.kodadot.xyz/bsx/gallery/2645998698-9?page=1

image

after reload
seems I can "click on buy" but can't submit?
 
image

make offer worked

after making an offer, buy magically appeared it's working again.

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3412
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

related to #3324

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by petersopko** [comment]
hmm, I see what the code is supposed to do, I'm not sure how is that fixing the problem described in the issue tho? As an example, I've just logged in and clicked on transfer
image

I see balance 0, which is bigger issue than the fact that button is disabled / enabled I guess

here's another one, logged in, switched to bsx, landed on my NFT and I can click the button anyway
image

**Comment by Jarsen136** [comment]
> hmm, I see what the code is supposed to do, I'm not sure how is that fixing the problem described in the issue tho? As an example, I've just logged in and clicked on transfer image
> 
> I see balance 0, which is bigger issue than the fact that button is disabled / enabled I guess
> 
> here's another one, logged in, switched to bsx, landed on my NFT and I can click the button anyway image

Oh, I will check them.

**Comment by petersopko** [comment]
> Oh, I will check them.

one way to reproduce is to simply use the app without waiting too much between each click, I almost always break it in this way :(

**Comment by petersopko** [comment]
nvm let's merge this as we need this fixed as well, the initial problem with 0 balance can be fixed elsewhere (and is probably related to the other issues with chain being stuck / not properly switching wallets)

**Comment by yangwao** [comment]
pay 50 usd

**Pull request merged**
