### PR TITLE
feat: Calendar and scheduled drops preview 📅

### LINKED ISSUE #9634: Calendar and scheduled drops preview
yes, we currently have more and more drops scheduled, lets make calendar to keep track and tease collectors a bit 

# Design
image

preview: 
image

### How it works? 
@vikiival is currently cooking some backend solutions
- it will basically add information of scheduled drops to the preview 
- the info we don't have - it will be empty, we can put TBA as placeholder there 
- the highest prio is the preview 
- this preview will be for every drop that is in the calendar section, lets keep it simple 
- after drop is less than 24 hours till open, it has its drop page - like it was mentioned in the drop landing v2 

----------

# Calendar
image

it always start with date, then divider
- the date is in the "medium button" but has larger text 
image
- the padding remains the same 

_please ignore the "minting live status" there should be status of the date, something like this (if we know exact time, there could be exact time"_ 
image

then if you click on the "scheduled drop" it will open

# Drop preview
image
gm, new drop just dropped 
- its a full-height sidebar - it covers navbar (IMO this will make our lives easier with the sidebar interaction - wallet, profile, notifs, cart....) let me know if my assumption is not correct 

from top to bottom: 

## Top part 
there is name, x-mark to close (it has bigger touchpoints than just the 20px icon) 
- date and button to add to calendar 
image
- this is actually button that when clicked will trigger add to calendar modal
- the small dot is already reused from collection top part (it divides royalty, blockchain etc. there) 

then there is artist - they usually don't have identity, so its only link to twitter (its usually in the description) 

- next to that royalty info

## Img carousel
image
- yes, two imgs
- on mobile one 
- new carousel arrows - will create issue to update them across the app  
- the ideal state is having at least 6 art preview from the artists so there is at least something to go through cc @JustLuuuu 
- its moving by two

## Drop info
image

price, supply
 

if requirements, there is requirement section 
- just basic bullet points - use the same wording we have in the drop page 

## Description
- after divider there is description, its not that important for the collector that much, thus its on the bottom 
- probably no hard limit to the number of words, the sidebar should be scrollable 

### Mobile
on mobile its full-width sidebar, covering the whole screen 

on desktop it does not scale down till the gap between the sidebar and the desktop is 200px, this is not exact, feel free to make it differently 

for dark mode use predefined color pairs

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

 ❗️❗️ Needs https://github.com/kodadot/private-workers/pull/91 

- [x] Closes #9634 

## Needs QA check

- @kodadot/qa-guild please review

## Needs Design check

- @exezbcz please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2024-03-20 at 17 01 29@2x

### CODE REVIEW

**Comment by yangwao** [comment]
Ready for release? 🫡

**Comment by exezbcz** [comment]
@yangwao probably not as its still draft

**Comment by hassnian** [comment]
> Ready for release? 🫡

ready , needs https://github.com/kodadot/private-workers/pull/91

**Comment by yangwao** [comment]
otherwise we can merge?

image

**Comment by hassnian** [comment]
> otherwise we can merge?
> 
> image

not from this pr -> issue https://github.com/kodadot/nft-gallery/issues/9827

**Comment by yangwao** [comment]
Thanks!
pay 80 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $80 @ 9.38 USD/DOT ~ 8.529 $DOT
🧗 [16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD](https://polkadot.subscan.io/account/16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)
🔗 [0xc8983deac748955cf22687d67e01f73879285ab6eef04de54cd527088484ebb7](https://polkadot.subscan.io/extrinsic/0xc8983deac748955cf22687d67e01f73879285ab6eef04de54cd527088484ebb7)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by Jarsen136** [comment]
image

@hassnian Could you please check the request error regarding the empty drop calendar?

**Pull request merged**
