### PR TITLE
Nuxt-property-decorator/Transfer

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Related with #4750

## Pages in this PR
/prefix/transfer

## desired outcome
no change in look and/or behavior

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)
## Screenshot 📸

- [ ] My fix has changed UI

### <samp>🤖 Generated by Copilot at 825b84f</samp>

Added block explorer support and improved Auth component. The `useChain` composable can now provide a `blockExplorer` link for different chains, and the `Auth` component can be used without specifying a `size` prop.

### <samp>🤖 Generated by Copilot at 825b84f</samp>

> _We're sailing on the web with our `Auth` component_
> _We've made the `size` prop optional, so it's more convenient_
> _And when we need to check the chain, we have a handy link_
> _We use the `blockExplorer` to see what's on the brink_

### CODE REVIEW

**Review by Jarsen136 — APPROVED** [review]
code lgtm

**Comment by prury** [comment]
Made some transfers, they all went well
General check - ok 

https://polkadot.subscan.io/extrinsic/0xce98b85ceaba0096c3b2de9d4c8e43fcc2a46183ddb1a6f5db309c46aeed3db7?tab=event

https://kusama.subscan.io/tx/0x00cfd3112062021a2802742479de2252bc5667bdd3058cfa3c7dec0fb51fb66f

https://kusama.subscan.io/tx/0xecf37b126e3bfc9dacb831b79e699afd94bab3b2e1139fa2459f102ceeb1ae66

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 5.14 USD/DOT ~ 9.728 $DOT
🧗 [1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8](https://polkadot.subscan.io/account/1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)
🔗 [0x5c4505199449d3edea9058033734cf0cd549628eee8be76d184fcefc2215462e](https://polkadot.subscan.io/extrinsic/0x5c4505199449d3edea9058033734cf0cd549628eee8be76d184fcefc2215462e)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by roiLeo** [comment]
☹️

**Pull request merged**
