### PR TITLE
fix: null collection in /drops pages

### LINKED ISSUE #6992: null collection in /drops pages
image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix

  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #6992
  - [ ] Requires deployment <snek/rubick/worker>

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [ ] My fix has changed UI

image

  ## Copilot Summary
  
### <samp>🤖 Generated by Copilot at 255ad14</samp>

Updated the collection ID format and fixed a bug in the `useDrops` function. These changes enable user collections and improve the stability of the drops feature.

  
### <samp>🤖 Generated by Copilot at 255ad14</samp>

> _`STT_COLLECTION_ID`_
> _New format with prefix `u-`_
> _User collections bloom_

### CODE REVIEW

**Comment by daiagi** [comment]
That was fast


giphy

**Comment by daiagi** [comment]
wfm
would you mind deleting the console.log from the page?

**Review by daiagi — APPROVED** [review]

**Comment by Jarsen136** [comment]
> wfm would you mind deleting the console.log from the page?

Sure. I deleted it.

**Comment by yangwao** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 4.45 USD/DOT ~ 4.494 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x4e822cd31b484ff4694977e6496b82647fe24c7c622ab9ff8a7e8b2afee5e247](https://polkadot.subscan.io/extrinsic/0x4e822cd31b484ff4694977e6496b82647fe24c7c622ab9ff8a7e8b2afee5e247)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
