### PR TITLE
fix: Sidebar title padding and xmark

### LINKED ISSUE #6535: Sidebar title padding and xmark
- okay, we recently made it consistent, but I specified the wrong padding
image
- so its going to be a 24px vertical, and 32px horizontal  
- this applies to all sidebars - notif, connect wallet, profile, cart ( its already done like that) 

image
- can we please also use this xmark - regular, sharp 
`<font-awesome-icon :icon="['fasr', 'xmark']" size="sm" />`
https://fontawesome.com/icons/xmark?f=sharp&s=regular
- please make it 20px or 24. 

Q: When specifying the size of icons, do you typically base it on the padding around it to increase the clickable area, or on the size of the icon itself?

### PR DESCRIPTION
**Pull request by hardcommitoneself**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Needs Design check

- @exezbcz please review

## Context

- [x] Closes #6535

## Screenshot 📸

image
image

### <samp>🤖 Generated by Copilot at f5f0880</samp>

Changed the close icons of the connect wallet and shopping cart modals to match the design and the other modals. Added the `fasr` icon pack to use solid icons from Font Awesome. Adjusted the padding of the modal headers for consistency.

### <samp>🤖 Generated by Copilot at f5f0880</samp>

> _`xmark` icon for modals_
> _aligns with design and others_
> _a winter makeover_

### CODE REVIEW

**Comment by exezbcz** [comment]
> please make it 20px or 24.
- icon please 

+ cursor pointer on hover

**Review by roiLeo — COMMENTED** [review]
why don't you use `pack="far"` instead? When I do some test it look the same.

from #6535, it's missing:
> please make it 20px or 24.

**Comment by yangwao** [comment]
@hardcommitoneself please provide a fix till 48hours, otherwise closing this PR to leave room for someone else to take it

**Comment by prury** [comment]
closing!

**Pull request closed without merging**
