### PR TITLE
fix: disable submitting before RPC api connected

### LINKED ISSUE #2502: Transfer has issues with sending tx for sign for polkadot
image

### PR DESCRIPTION
**Pull request by newraina**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2502
- [x] Add api connected status check for submit button

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=CmVS5edpZFQeATFWFu72JzMnv6c3RzbyikpLJpYwZa9GXw9)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by newraina** [comment]
image

DeepSource suggests me adding doc for `onApiConnect`, but `onApiConnect` is so simple, maybe is not necessary for doc.

**Comment by yangwao** [comment]
Thinking
- it should be global so we could reuse it elsewhere
- do you check if api is down? Like disconnected?

**Comment by newraina** [comment]
@yangwao updated according to your suggestion :)

I recorded a video showing how event listeners affect the button status:

https://user-images.githubusercontent.com/10708802/157053081-c4dc0484-248c-4395-8667-ccab183110e8.mov

**Comment by yangwao** [comment]
Seems I'm offline by dev tools and submit is enabled.

image

**Comment by yangwao** [comment]
Turned off wifi and seems buttons show as connected 🤔💭

image

**Comment by newraina** [comment]
@yangwao  After research, I found two ways to cover the case you submitted:
1. Listening to network change event by navigator.connection (response to network change more quickly)
2. implement a simple heartbeat function for ApiPromise (response slower)

**Before starting, I want to confirm:**
1. Is the network issue after API connected really in the scope of #2502? According to my understanding, #2502 wants to resolve the TypeError when API is not ready. Because TypeError is silent for users, they cannot know what is happening. But after API is connected, even if there is a network issue, users will know by too long loading status of confirming dialog.
2. Our Connector/ApiPromise doesn't handle broken connections. Is it the duty of @kodadot1/sub-api? Maybe we should let @kodadot1/sub-api take it instead of operating in an application like nft-gallery?

After your confirmation, I will implement it if the network issue is in the scope and should be handled in nft-gallery 😊

**Comment by yangwao** [comment]
> @yangwao After research, I found two ways to cover the case you submitted:
> 
> 1. Listening to network change event by navigator.connection (response to network change more quickly)

yes, go with an easy one, as not much people are using it yet I guess :)

> **Before starting, I want to confirm:**
> 
> 1. Is the network issue after API connected really in the scope of [Transfer has issues with sending tx for sign for PolkadotJS extenstion #2502](https://github.com/kodadot/nft-gallery/issues/2502)? 

yes, we want to fix other scenario as well, it's normal we find other scenarios latter when issue was created.

> 2. Our Connector/ApiPromise doesn't handle broken connections. Is it the duty of @kodadot1/sub-api? Maybe we should let @kodadot1/sub-api take it instead of operating in an application like nft-gallery?

cc @vikiival, might be a good feature request, but it would make it a bit more opinionated.

**Comment by newraina** [comment]
@yangwao  Updated and recorded a video to demonstrate the network status change:

https://user-images.githubusercontent.com/10708802/158048814-32a9b1d9-8100-4b30-a943-77e9e06e06ab.mov

**Remark:**
1. add new state `isNetworkConnected` in global store so that others can reuse it. #2249
2. improving typing for mutations in `store/index.ts` to reduce the usage of `any`.

**Comment by vikiival** [comment]
> Our Connector/ApiPromise doesn't handle broken connections.

What does that mean? If you know the fix please open PR in [kodadot/packages](https://github.com/kodadot/packages)

**Review by vikiival — APPROVED** [review]
Looks OKI

**Comment by yangwao** [comment]
sending extra bucks that you took the extra mile with us on this! :)

pay 150 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $150 @ 119.5 USD/KSM ~ 1.255 $KSM
🧗 [CmVS5edpZFQeATFWFu72JzMnv6c3RzbyikpLJpYwZa9GXw9](https://kusama.subscan.io/account/CmVS5edpZFQeATFWFu72JzMnv6c3RzbyikpLJpYwZa9GXw9)
🔗 [0x21bbca43605aa8eacd0e901e09063a8a1613a23d68e6c6b4b792569c850c582c](https://kusama.subscan.io/extrinsic/0x21bbca43605aa8eacd0e901e09063a8a1613a23d68e6c6b4b792569c850c582c)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
