### PR TITLE
🎩 refactoring scss archi

### PR DESCRIPTION
**Pull request by roiLeo**
bobross-lede-1

### PR type

- [x] Feature
- [x] Refactoring

### What's new?

- [x] PR relate with #1348 
- [x] remove unused imports
- [x] change `styles` folder structure
Capture d’écran 2022-08-23 à 1 06 57 PM

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### CODE REVIEW

**Comment by roiLeo** [comment]
Just checked preview and it's pretty bad lol

**Comment by yangwao** [comment]
> Just checked preview and it's pretty bad lol

**Comment by yangwao** [comment]
> Just checked preview and it's pretty bad lol

almost hit merge lol

**Comment by vikiival** [comment]
> Just checked preview and it's pretty bad lol

If the preview was a cat

**Comment by roiLeo** [comment]
> Just checked preview and it's pretty bad lol

https://github.com/kodadot/nft-gallery/blob/27411ad8028e3ff8235a390cf213a46a978cc95c/styles/index.scss#L5 or feel free to move this if you want to break stuff

**Comment by yangwao** [comment]
I feel lucky

**Pull request merged**
