### PR TITLE
fix: Line in the middle after opening wallet dialog

### LINKED ISSUE #5552: Line in the middle after opening wallet dialog
image
image
- happens everywhere when you open the wallet sidebar/connect wallet

full screen preview is affected as well - even without opening the sidebar
image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5552
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

### CODE REVIEW

**Comment by exezbcz** [comment]
something still blocks the full screen preview
image
- can you please check that it is not related to this issue?

**Review by daiagi — APPROVED** [review]

**Comment by Jarsen136** [comment]
> something still blocks the full screen preview
> 
> image
> 
> - can you please check that it is not related to this issue? 

yes, I will check it

**Comment by Jarsen136** [comment]
> > something still blocks the full screen preview
> > image
> > 
> > * can you please check that it is not related to this issue?
> 
> yes, I will check it

✅  Fixed

**Comment by vikiival** [comment]
Looks oki

**Comment by vikiival** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 32.84 USD/KSM ~ 0.609 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x7e679b3918f8f38bfb39ed9bdab782dc8707d9b42d3ea7793e0d0cfc32cbf50a](https://kusama.subscan.io/extrinsic/0x7e679b3918f8f38bfb39ed9bdab782dc8707d9b42d3ea7793e0d0cfc32cbf50a)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
