### PR TITLE
One non-fungible serpent

### LINKED ISSUE #4003: Soft Basilisk launch
this is check list for @vikiival 

- [ ] check prod & critical bugs
- [ ] enable Basilisk in chain selector
- [ ] put Basilisk on Kusama first in the list for convenience for users
- [ ] test if everything works or aren't any obv bugs lurking around 

image

### PR DESCRIPTION
**Pull request by vikiival**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #4003 
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by yangwao** [comment]
@petersopko 🫡 is everything working?

**Comment by petersopko** [comment]
> @petersopko 🫡 is everything working?

well everything was working on /snek (as mentioned in #4003) but it seems that for example assets page is gone on this new /bsx route + profile dropdown looks different (missing assets route and multi-currency balance showing)
**new BSX route**:
image

**old SNEK route**:
image



As for the functionality of the rest of the live (bsx) version, if I'm supposed to see empty NFT explorer then it's working 😄 How  should I try to get some KSM and BSX here, in order to try any transactions ?

**Review by petersopko — COMMENTED** [review]
some small stuff

**Comment by vikiival** [comment]
asset page was added in [8fdb7f5](https://github.com/kodadot/nft-gallery/pull/4030/commits/8fdb7f52df747c934f109584a15e14c8139c6996)

balance should also work since [81d3cc5](https://github.com/kodadot/nft-gallery/pull/4030/commits/81d3cc503b1750236ce5b57628735706c76a2ec0)

If you need some KSM on BSX check #4036

**Comment by petersopko** [comment]
> asset page was added in [8fdb7f5](https://github.com/kodadot/nft-gallery/pull/4030/commits/8fdb7f52df747c934f109584a15e14c8139c6996)
> 
> balance should also work since [81d3cc5](https://github.com/kodadot/nft-gallery/pull/4030/commits/81d3cc503b1750236ce5b57628735706c76a2ec0)

assets route in navbar on bsx leads to /snek/assets + it seems it shows unit? After manually navigating to /bsx/assets I see only one currency here (I have 0 on both, but I guess that shouldn't matter)
image

> If you need some KSM on BSX check #4036

thanks, will do

**Comment by vikiival** [comment]
Asking for a friend

Screenshot 2022-09-28 at 12 43 24

**Comment by yangwao** [comment]
> Screenshot 2022-09-28 at 12 43 24

chad: PRO

**Review by petersopko — APPROVED** [review]
✅

**Comment by petersopko** [comment]
> Screenshot 2022-09-28 at 12 43 24

🚀

**Pull request merged**
