### PR TITLE
Revert "fix: One decimal in top collections should be enough"

### PR DESCRIPTION
**Pull request by roiLeo**
Reverts 
- kodadot/nft-gallery#8903
- https://github.com/kodadot/nft-gallery/issues/8901

Now it does show price
Screenshot 2024-01-10 at 09-11-55 KodaDot - One Stop Shop for Polkadot NFTs One Stop Shop for Polkadot NFTs

### CODE REVIEW

**Review by preschian — APPROVED** [review]

**Comment by prury** [comment]
@roiLeo something to do with comma? 

image

**Comment by roiLeo** [comment]
> @roiLeo something to do with comma?
 
compare floor price with canary

**Comment by Jarsen136** [comment]
wait, I will check it later

**Comment by prury** [comment]
> > @roiLeo something to do with comma?
> 
> compare floor price with canary

image

only problem i saw was the 1 DOT

**Comment by roiLeo** [comment]
> only problem i saw was the 1 DOT

Not correct should be 1799


Capture d’écran 2024-01-10 à 11 34 41 AM

wtf, I'm not seeing floor on firefox (canary)

**Comment by prury** [comment]
> > only problem i saw was the 1 DOT
> 
> Not correct should be 1799

yes yes

> > wtf, I'm not seeing floor on firefox (canary)

could not repro

**Pull request merged**
