### PR TITLE
#4334 loader overflow issue

### LINKED ISSUE #4334: Scrolled text in the mint popup
### What happened?

After some time as the message "Stuck? Make sure to check for any popups and SIGN the transaction. ", the rest of the text will scroll out of the UI

obrázok

### Please reproduce in steps

https://user-images.githubusercontent.com/81104034/202097806-93edc962-d280-4105-a15a-9b4fafd9da0d.mp4

### Expected Behavior

could the frame be tightened a bit, 
or the head _"Stuck? Make sure to check for any popups and SIGN the transaction."_ put separately

### What browsers are you seeing the problem on?

Firefox

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### Screenshots

I have uploaded a video

### Relevant log output

_No response_

### Payment link for reward

https://beta.kodadot.xyz/transfer?target=bXjrHpyJzSczJuuqmtN6nqCnd5b7KFa5LK1rBtF1tUHDYzp8N&usdamount=10&donation=true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Closes #4334
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screen Shot 2022-11-16 at 7 39 11 PM

### CODE REVIEW

**Comment by prachi00** [comment]
@yangwao  @exezbcz so this part wasn't covered in the designs, for now, I have just given it dynamic height so it doesn't break in this case, let me know where to put it design wise

**Comment by exezbcz** [comment]
> @yangwao @exezbcz so this part wasn't covered in the designs, for now, I have just given it dynamic height so it doesn't break in this case, let me know where to put it design wise

Hi! Not sure if i understand the question, can you please rephrase it or add some screenshots?

**Comment by yangwao** [comment]
I guess fair for now :)
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 24.18 USD/KSM ~ 0.827 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0xd80a53575b8e118a9ae353c757f69caccf2236e03b396b6a6633e8475ecbdaa2](https://kusama.subscan.io/extrinsic/0xd80a53575b8e118a9ae353c757f69caccf2236e03b396b6a6633e8475ecbdaa2)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by exezbcz** [comment]
Ahh, ic what you mean. Okay, then we could rephrase it like:
Stuck? - as a heading
the rest will be paragraph

**Comment by spacesmutje** [comment]
Fun fact 1:
Did you know that in the first 6 months after opening Subwork Bled, x other teams paid a visit to work on the future of web3?

Fun fact 2:
Did you know that the team of KodaDot attended x events to promote and nurture the idea of the only open-source, cross-chain NFT marketplace?

Fun fact 3:
Did you know that KodaDot created and hosted x events in 2022, with a total of y on-site participants and z views of the video recordings?

Fun fact 4:
Did you know that KodaDog Berry stole x sandwiches and other snacks during events? There might be even more unreported incidents.

Fun fact 5:
Did you know that more than 3400 GMs have been send on Discord until November 2022, since creating the gm-gn-channel in October 2021?

That's it for now, i will try figuring out some more in my creative moments :)

**Pull request merged**
