### PR TITLE
Redesign

### LINKED ISSUE #398: Create new landing page
I would love to see the new landing page by @XyloDrone.

Deliverables:
- [ ] Implement the design according to the image
- [ ] Links should redirect user to the correct pages

Screenshot 2021-05-24 at 12 21 10
Screenshot 2021-05-24 at 12 21 22
Screenshot 2021-05-24 at 12 21 18

@XyloDrone will attach the background image.

### PR DESCRIPTION
**Pull request by JKrupinski**
Fixes #398

### CODE REVIEW

**Comment by vikiival** [comment]
This is beyond dope :O

just a couple of things:
Can we make also loading page black ? There is font with `color: white` already
Screenshot 2021-06-05 at 15 29 00

It's hard to the text
Screenshot 2021-06-05 at 15 29 25

can we make the font white when the page is not active ? 
Screenshot 2021-06-05 at 15 29 49

**Comment by JKrupinski** [comment]
> This is beyond dope :O
> 
> just a couple of things:
> Can we make also loading page black ? There is font with `color: white` already
> Screenshot 2021-06-05 at 15 29 00
> 
> can we make the font white when the page is not active ?
> Screenshot 2021-06-05 at 15 29 25
> 
> It's hard to read the text
> Screenshot 2021-06-05 at 15 29 49

Bro, we can do everything

**Comment by yangwao** [comment]
Overall it looks dope, maybe tiny details like square like icons next to each other and it's way perfect, love!

IMG_20210605_184035

**Comment by vikiival** [comment]
I think it can go out today

Just the test on ultrawide 
Screenshot 2021-06-05 at 18 40 05
Screenshot 2021-06-05 at 18 39 54

**Review by vikiival — APPROVED** [review]
🔥

**Pull request merged**
