### PR TITLE
#7337 round price

### LINKED ISSUE #7337: Rounding NFT price in the item preview
Can we round these numbers to something more cute? With less zeros? Tested on canary/production and ahp.

Screenshot 2023-09-24 at 13 34 52

If someone decides to sell an NFT for 12.45 DOT - leave the price at 12.45. But if someone decides to sell it for 12 DOT, have a price of 12 DOT (not 12.00). Smart rounding without extra zeros.

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #7337
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)

## Screenshot 📸

- [x] My fix has changed UI
Screen Shot 2023-09-25 at 8 21 06 PM

### CODE REVIEW

**Comment by prury** [comment]
works fine for integers but not decimals: 

image

**Comment by prachi00** [comment]
Screen Shot 2023-09-26 at 9 41 46 PM

@prury it is the same here as well it seems, since we round to 4 places everywhere 
should this be changed to 2 then?

**Comment by yangwao** [comment]
pay 10 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $10 @ 4.06 USD/DOT ~ 2.463 $DOT
🧗 [13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1](https://polkadot.subscan.io/account/13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)
🔗 [0xd5c08e9c877daced389759c5e2563383bc70b4fe7ba4a03980481d7f09daddd8](https://polkadot.subscan.io/extrinsic/0xd5c08e9c877daced389759c5e2563383bc70b4fe7ba4a03980481d7f09daddd8)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
