### PR TITLE
feat: Massmint confirmation modal loading wheel

### LINKED ISSUE #9774: Massmint confirmation modal loading wheel
image

lets add loading wheel for both generating variations and uploading to ipfs 

- for the uploading, can we also add an estimate, please?

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #9774

## Needs QA check

- @kodadot/qa-guild please review

## Needs Design check

- @exezbcz please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2024-03-15 at 11 53 36

### CODE REVIEW

**Review by Jarsen136 — APPROVED** [review]

**Review by preschian — APPROVED** [review]

**Comment by exezbcz** [comment]
the button state with loading wheel is default on the right? 

i think it would look better on the left but if its the component then you can leave like this
image

**Comment by hassnian** [comment]
> the button state with loading wheel is default on the right? 
> 
> 
> 
> i think it would look better on the left but if its the component then you can leave like this
> 
> image
> 
> 

Yep, the component by default has the loading wheel on the right side

**Comment by exezbcz** [comment]
@hassnian yeah then we can leave it like that for now, thanks

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 9.91 USD/DOT ~ 3.027 $DOT
🧗 [16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD](https://polkadot.subscan.io/account/16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)
🔗 [0x8e26e2fd667429a79a2ecceadc3d4752d9336e1272cf4140692a2e22e01b93c5](https://polkadot.subscan.io/extrinsic/0x8e26e2fd667429a79a2ecceadc3d4752d9336e1272cf4140692a2e22e01b93c5)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
