### PR TITLE
#5155 adding margin when scrolling to desktop only

### LINKED ISSUE #5155: Sidebar stick to navbar placement
the sidebar is sticking to the top - that is correct, but on different place than it should 
image
how it should be: 
image
how it is
image

basically the stroke separating cards and menu bar should be aligned with navbar stroke when scrolling down - please avoid double stroke

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5155
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screen Shot 2023-03-08 at 7 50 06 PM

### CODE REVIEW

**Review by roiLeo — CHANGES_REQUESTED** [review]
I would increase `.sticky` top value instead

**Comment by prachi00** [comment]
> I would increase `.sticky` top value instead

@roiLeo tried doing that, did not work as expected

**Comment by roiLeo** [comment]
https://github.com/kodadot/nft-gallery/blob/c9072d63895d09d4194528a336b4b942aa70b53a/components/explore/SidebarFilter.vue#L28-L33

maybe if we change the two 72px value it should do the work

**Comment by exezbcz** [comment]
that is still too much no? You are scrolling like 4 px over, It should scroll only over the stroke and stop

**Review by roiLeo — APPROVED** [review]
Code lgtm

**Review by daiagi — APPROVED** [review]
wfm

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
pay 10 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $10 @ 30.07 USD/KSM ~ 0.333 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x250ad5b23edd9d1a7b87c85e1acd02121241e96e7ac1fb376ba2cc2913727065](https://kusama.subscan.io/extrinsic/0x250ad5b23edd9d1a7b87c85e1acd02121241e96e7ac1fb376ba2cc2913727065)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by prachi00** [comment]
@vikiival we can close this one

**Pull request merged**
