### PR TITLE
NeoSkeleton to tailwindcss

### PR DESCRIPTION
**Pull request by shashkovdanil**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Closes #8222 
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [x] I've tested it at </ksm/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer?target=16SpvdDgKNiQ3c53DxX7refnQcKUD3uRNim3Z1HBJLNGrtSP&usdamount=0)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 71d8568</samp>

Refactored the NeoSkeleton component to use `tailwind.css` instead of custom SCSS code, and updated the `tailwind.config.js` and `tailwind.scss` files to support opacity variations and theme compatibility for the skeleton component.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 71d8568</samp>

> _We're heaving away with `Tailwind CSS`_
> _We're making our skeletons look the best_
> _We're changing the colors and the themes_
> _We're working as one, a mighty team_

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]

**Comment by prury** [comment]
overall they are a bit brighter on deployed than on canary, both on dark/white mode, other than that looks ok

**Review by Jarsen136 — APPROVED** [review]

**Comment by exezbcz** [comment]
did you added version for dark mode?

**Comment by roiLeo** [comment]
> overall they are a bit brighter on deployed than on canary, both on dark/white mode, other than that looks ok

did you change something related to color?

**Comment by prury** [comment]
@roiLeo @shashkovdanil 
image

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 6.47 USD/DOT ~ 4.637 $DOT
🧗 [16SpvdDgKNiQ3c53DxX7refnQcKUD3uRNim3Z1HBJLNGrtSP](https://polkadot.subscan.io/account/16SpvdDgKNiQ3c53DxX7refnQcKUD3uRNim3Z1HBJLNGrtSP)
🔗 [0x8df44beeb2b87821b45d07f3cd78585065cd2421b2de4d928bdfb8a382a82627](https://polkadot.subscan.io/extrinsic/0x8df44beeb2b87821b45d07f3cd78585065cd2421b2de4d928bdfb8a382a82627)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
@prury feel free to make follow up

**Comment by prury** [comment]
> @prury feel free to make follow up

only if @exezbcz thinks [color](https://github.com/kodadot/nft-gallery/pull/8541#issuecomment-1860390801) change was significant

**Pull request merged**
