### PR TITLE
fix: Add prefix to the transfer

### LINKED ISSUE #5957: Add prefix to the transfer
Let's add prefix to url for transfer to fix between switching networks 

Like kodadot.xyz/ksm/transfer

May fix 
- #5956

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5957
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### <samp>🤖 Generated by Copilot at 4d9fa2e</samp>

This pull request updates various files related to the payment link and the network prefix for the Kusama chain. It fixes quotation marks, whitespace, and formatting issues in the issue and pull request templates, the README, and the REWARDS files. It also adds a middleware function to redirect `/transfer` routes to `/ksm/transfer` and makes the transfer and teleport pages use dynamic network prefixes. These changes improve the consistency, functionality, and user experience of the NFT gallery.

### <samp>🤖 Generated by Copilot at 4d9fa2e</samp>

> _`urlPrefix` prop_
> _helps to avoid redirection_
> _cutting through the web_

### CODE REVIEW

**Comment by vikiival** [comment]
I found the edge case with is not scope of this PR

Screenshot 2023-05-15 at 12 25 25

**Comment by vikiival** [comment]
@Jarsen136 can you please roll back change from `"` to `'` ? Its unrelated to this PR

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
Looks like deployment is failing?

**Comment by Jarsen136** [comment]
> @Jarsen136 can you please roll back change from `"` to `'` ? Its unrelated to this PR

I'm sorry for that. It's an auto format on my side.

**Pull request merged**
