### PR TITLE
fix: auto-add #{sn} to the name of nft

### LINKED ISSUE #8100: New Generative drop items have the same name
inside the collection, on more from this collection and explorer

https://canary.kodadot.xyz/ahp/gallery/38-18

image

on Drops they have proper unique names:
image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix
  - [x] Feature

  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #8100

  - [x] Check if the name contain #{sn}, if not, we will add for it.  

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

1. landing

image

2. collection 
image

3. gallery items

It's blocked by some changes on indexer side

We should add `sn` to the `tokenEntityList` entity
image

  ## Copilot Summary
  
### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at ceb004a</samp>

Added support for displaying NFT serial numbers as suffixes to their names in the UI. Refactored and moved NFT formatting logic to `composables/useNft.ts` and updated GraphQL queries to fetch `sn` field from Subsquid API.

  
### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at ceb004a</samp>

> _Sing, O Muse, of the skillful coder who devised_
> _A clever way to show the serial number of NFTs_
> _By adding `sn` to the GraphQL query that retrieves_
> _The latest events from the Subsquid API of Kusama._

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]

**Review by daiagi — APPROVED** [review]

**Comment by daiagi** [comment]
>It's blocked by some changes on indexer side

We should add sn to the tokenEntityList entity

quoting  @vikiival from https://github.com/kodadot/nft-gallery/issues/7462#issuecomment-1744571996



  >  sn - for sort

This filter does not make sense imo as there is nothing I can represent as serial number.

**Comment by vikiival** [comment]
> This filter does not make sense imo as there is nothing I can represent as serial number.

The only thing that probably makes sense to represent is amount of nfts

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
Looks the tests are failing for this one

**Comment by prury** [comment]
> Looks the tests are failing for this one

reason: 
red dot is where it clicks to access collection: 
image

unrelated i suppose, but why it failed only now? hehe

**Comment by prury** [comment]
@Jarsen136 inside profile: 

image

**Comment by Jarsen136** [comment]
> @Jarsen136 inside profile:
> 
> image


It's also blocked by change on the  `tokenEntityList` entity

> 5\. gallery items
> 
> It's blocked by some changes on indexer side
> 
> We should add `sn` to the `tokenEntityList` entity

**Comment by Jarsen136** [comment]
> > Looks the tests are failing for this one
> 
> reason: red dot is where it clicks to access collection: image
> 
> unrelated i suppose, but why it failed only now? hehe will fix in a small PR

The width of the nft name changed because we added `#{sn}` on the end. I bet that's why the red dot could not sit in the same position as before. : ) Thank you for fixing the test.

**Comment by yangwao** [comment]
thanks!
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 5.14 USD/DOT ~ 3.891 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x93d7bc89aa76151d56d313afa6a1b0bb878e19562a3cdd66fcee812c7618a6b7](https://polkadot.subscan.io/extrinsic/0x93d7bc89aa76151d56d313afa6a1b0bb878e19562a3cdd66fcee812c7618a6b7)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
