### PR TITLE
fix: Mobile activity tab

### LINKED ISSUE #8696: Mobile activity tab
image
- can we please fix this, its looking ugly

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix

  ## Needs Design check

  - @exezbcz please review

  ## Context

  - [x] Closes #8696

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

image

  ## Copilot Summary
  copilot:summary

  copilot:poem

### CODE REVIEW

**Review by preschian — APPROVED** [review]

**Review by roiLeo — APPROVED** [review]

**Comment by roiLeo** [comment]
double divider?

Screenshot 2023-12-21 at 08-56-42 Chroma Lattice #132

**Comment by Jarsen136** [comment]
> double divider?
> 
> 
> 
> Screenshot 2023-12-21 at 08-56-42 Chroma Lattice #132
> 
> 

@exezbcz Is there any UI idea about it? 👀

**Comment by yangwao** [comment]
maybe removing that shadow and horizontal line?

**Comment by Jarsen136** [comment]
✅ Updated. I have attached the new screenshot on the description.

**Comment by exezbcz** [comment]
@Jarsen136 ah, i meant only the bottom section, the top part should remain the same, no issues there

**Comment by Jarsen136** [comment]
> @Jarsen136 ah, i meant only the bottom section, the top part should remain the same, no issues there
> 
> image see this
> 
> image
> 
> * bold weight should not be there

Oh, looks like the design on the figma should be updated regarding the top part. I have reverted the changes  : )
✅ bold weight removed

**Comment by exezbcz** [comment]
@Jarsen136 yeah, changes were made, its quite old. 


it was only in the desktop part 
image


one last small thing is the divider 
image

- should not be full width

**Comment by Jarsen136** [comment]
> @Jarsen136 yeah, changes were made, its quite old.
> 
> it was only in the desktop part image
> 

Nice. I found it!



> one last small thing is the divider image
> 
> * should not be full width

✅ Fixed

**Comment by vikiival** [comment]
@exezbcz is this mergeable?

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 8.65 USD/DOT ~ 3.468 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0xc4edbc43e1fb5e8e3ccc1f400eef6984684147e291af4d79b70d3db55117723d](https://polkadot.subscan.io/extrinsic/0xc4edbc43e1fb5e8e3ccc1f400eef6984684147e291af4d79b70d3db55117723d)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
