### PR TITLE
update og card

### LINKED ISSUE #9703: Update OG cards accordingly
@exezbcz can drop the design 

image

### PR DESCRIPTION
**Pull request by zeshhaan**
- **Update page title and enable devtools to visualize og card preview for reviewers**
- **fix: broken seo tags**
- **Add SEO meta tags to index page**
- **Update og image**

**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Closes #9703 
- [ ] Requires deployment <worker/stick/speck>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [x] I've tested it at the root page (index aka landing), ahp/drops/ collection page
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [ ] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>)

#### Community participation

- [x] [Are you at Koda Ecosystem Telegram?](https://t.me/koda_eco)

## Screenshot 📸

- [x] My fix adds an updated OG image, also fixes og image not being displayed.
image

### CODE REVIEW

**Comment by yangwao** [comment]
https://www.opengraph.xyz/url/https%3A%2F%2Fdeploy-preview-9869--koda-canary.netlify.app%2F

lgtm, wil wait for others for check code

<details>
<summary>Details</summary>


image


</details>

**Comment by zeshhaan** [comment]
> only problem I'm having is on discord, its showing two different images for me:
> 


Oh it looks like Discord is taking both the OG image's. one defined globally as a fallback and the one fetched from the page. Will look into this once again.

**Comment by yangwao** [comment]
> Will look into this once again.

any chance you will make it before our release which is 2pm CET?

**Comment by zeshhaan** [comment]
> > Will look into this once again.
> 
> any chance you will make it before our release which is 2pm CET?

yes

**Comment by zeshhaan** [comment]
I have updated the PR and confined to just update OG card title and image as thats what issue #9703 targets.

If you notice its still showing two different OG preview in Discord with the staging link, i guess that might be cache of earlier version. Let me know.

**Review by preschian — APPROVED** [review]

**Comment by yangwao** [comment]
cc @prury let's check

**Review by Jarsen136 — APPROVED** [review]

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Pull request merged**
