### PR TITLE
Revert ":snake: Stuck Snek" 

### PR DESCRIPTION
**Pull request by yangwao**
- once Basilisk will be unbricked
- check for status https://kusama.polkassembly.io/referendum/245

Reverts kodadot/nft-gallery#4298

- maybe we need rotate snek indexer 

Seems 7h if I read right?

### CODE REVIEW

**Comment by vikiival** [comment]
https://kusama.subscan.io/block/15328061

**Comment by vikiival** [comment]
Few mins!

Screenshot 2022-11-15 at 14 12 29

**Comment by yangwao** [comment]
> Few mins!

some issues and changes in the background 👀 so bit delayed 😭

**Comment by vikiival** [comment]
Waiting for @galacticcouncil


```
seems that snek005 uses self-hosted archive
https://basilisk-rococo-firesquid.play.hydration.cloud/graphql

gateway version should be bumped to subsquid/substrate-gateway:2.4.8
```

**Comment by vikiival** [comment]
https://discord.com/channels/840514076538830888/881839877140930630/1042082404283719720

**Review by vikiival — APPROVED** [review]

**Pull request merged**
