### PR TITLE
Update 🇪🇸 Spanish translation in KodaDot

### PR DESCRIPTION
**Pull request by roiLeo**
Check on discord who is responsible (wagmedia?) for this translation, I just integrate it into the code base

### CODE REVIEW

**Comment by yangwao** [comment]
got some attestation from discord 

> [14:13]johnrhodel: Hey my friend
the person who is translating is the @MrDeFi#0905
> [14:16]CryptoX I💰I: @MrDeFi#0905 was the person who did it

**Comment by petersopko** [comment]
do we have somebody speaking Spanish here? I'm thinking maybe @JustLuuuu 😄

**Comment by roiLeo** [comment]
Claro que sí, hablo muy bien español

**Comment by petersopko** [comment]
@yangwao I assume the payment is being done through different channels here

**Review by petersopko — APPROVED** [review]

**Pull request merged**
