### PR TITLE
AvailableAction.vue - Unit Test

### LINKED ISSUE #2964: AvailableAction.vue - Unit Test
There are some import errors occur when running unit test, like  importing .svg error.
Would be great if someone could solve this problems and write unit test in `AvailableAction.vue`

_Originally posted by @Jarsen136 in https://github.com/kodadot/nft-gallery/issues/2948#issuecomment-1118675607_

ref: #1841

### PR DESCRIPTION
**Pull request by cazarov**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring
- [x] Tests 

### What's new?

- [x] PR closes #2964 
- [x] I have fixed the import errors that were blocking unit testing `AvailableAction.vue` (and other components) by adding the new development dependency `@rollup/plugin-graphql` and by refactoring the wallet configuration files to use ES6 imports.
- [x] I have added the new development dependency `fake-indexeddb` as it is required to make `AvailableAction.vue` work in the non-browser `jsdom` environment used for unit testing which does not have an IndexedDB implemention by default. To not slow down non-component file unit testing, I chose not to add loading it to `vitest.config.js`.
- [x] As a starting point, I have added three unit tests for `AvailableAction.vue` that check correct button type rendering based on props. More work is needed for proper unit test coverage for this component.

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [x] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer?target=J98SRy9JBahuoKgBUsTcLT3oYofoDj82fsWBsT9CaXBAmWb&usdamount=50&donation=true)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
Hey! would you mind changing `logo` name with something more meaningfull (CloverLogo, LedgerLogo, NovaLogo ...)

Tests pass
Capture d’écran 2022-08-15 à 10 48 50 PM

**Comment by cazarov** [comment]
> Hey! would you mind changing `logo` name with something more meaningfull (CloverLogo, LedgerLogo, NovaLogo ...)
Hi! :) Sure no problem, just added a commit.

**Review by roiLeo — APPROVED** [review]
✅ code lgtm

**Comment by DeluneClaire** [comment]
Looks like code only, so i will just approve this right?

**Comment by petersopko** [comment]
tests are passing for me, maybe let's resolve conflicts, update from main and lfg :)

**Comment by petersopko** [comment]
> ✅ code lgtm

👀 
image

**Review by petersopko — APPROVED** [review]
wfm

**Comment by petersopko** [comment]
@cazarov can you check out the DeepSource warnings please?

**Comment by cazarov** [comment]
> @cazarov can you check out the DeepSource warnings please?

All fixed, was just `sort-imports` after the rule got added in [#3718](https://github.com/kodadot/nft-gallery/pull/3718).

**Comment by yangwao** [comment]
pay 50

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 54.61 USD/KSM ~ 0.916 $KSM
🧗 [J98SRy9JBahuoKgBUsTcLT3oYofoDj82fsWBsT9CaXBAmWb](https://kusama.subscan.io/account/J98SRy9JBahuoKgBUsTcLT3oYofoDj82fsWBsT9CaXBAmWb)
🔗 [0x98c0ce2462fd18efa627dc8440e87f6d3d2d1760477580a072e376395f81d5d4](https://kusama.subscan.io/extrinsic/0x98c0ce2462fd18efa627dc8440e87f6d3d2d1760477580a072e376395f81d5d4)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
