### PR TITLE
:coffin: :snake: ByeSilisk

### LINKED ISSUE #8490: remove Basilisk related code
I think we will decide on a date, and we can drop a code related to BSX 

> PLUS there is BSX rpc error 

image

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/8486#issuecomment-1847346309_

### PR DESCRIPTION
**Pull request by vikiival**
- :wastebasket: remove :snake: (bsx) in libs/static/src/chains.ts
- :wastebasket: remove :snake: (bsx) in libs/static/src/endpoints.ts
- :wastebasket: remove :snake: (bsx) in libs/static/src/indexers.ts
- :wastebasket: remove :snake: (bsx) in libs/static/src/names.ts
- :wastebasket: remove :snake: (bsx) in libs/static/src/services.ts
- :wastebasket: remove :snake: (bsx) in libs/static/src/types.ts
- :wastebasket: :snake: composables
- (revert) useChain
- :wastebasket: :snake: composables
- :coffin: dead logo /bsx
- :wastebasket: :snake: balances on bsx
- :wastebasket: remove :snake: (bsx) in components/balance/MultipleBalances.vue
- :wastebasket: remove :snake: (bsx) in components/carousel/utils/useCarouselEvents.ts
- :wastebasket: :snake: uselesss import of usePrefix
- :zap: check address on KSM chain
- :wastebasket: :snake: remove import on non-existent bsx token svg
- :wastebasket: :snake: remove import of bsx on teleport
- :wastebasket: :snake: loading assets from bsx chain
- :wastebasket: :snake: transaction burn not possible
- :wastebasket: :snake: transaction buy not possible
- :wastebasket: :snake: transaction mint not possible
- :wastebasket: :snake: transaction mint token not possible
- :wastebasket: :snake: transaction send  not possible
- :wastebasket: :snake: constructing attributes  not possible
- :wastebasket: :snake: remove offers
- :wastebasket: :snake: :label: basilisk not in multibalance record
- :wastebasket: :snake: deny lists
- TODO: to be deleted
- TODO: to delete
- :wastebasket: remove offers
- :wastebasket: remove basilisk
- :wastebasket: remove bsx offers
- :bug: commented out assets page
- :wastebasket: removed bsx in create collection
- :wastebasket: removed bsx in create token
- :wastebasket: removed bsx in Confirm modal
- :wastebasket: removed bsx in Gallery item  tabs
- :wastebasket: removed bsx in useDeposit
- :wastebasket: removed series-insight
- :coffin: dead isBasilisk COmposable
- :coffin: MultiPaymentFeeButton
- :coffin: chainSupportingOffers
- :coffin: Assets
- :wastebasket: dead func computing KSM token
- :zap: no more KSM calculation
- :wastebasket: dead func getAsssetBalance
- :wastebasket: tokenId
- :wastebasket: tokenId
- :coffin: tokenId
- :wastebasket: tokenId in native balance
- :coffin: assetsVisible
- :coffin: incomingOfferssVisible
- :coffin: basilisk actions
- :wastebasket: implementation for tokenId
- :coffin: basilisk extrinsics
- :wastebasket: implementation of bsx in shopping Cart
- :coffin: dead functions
- :coffin: MakeOffer
- :wastebasket: dead fns
- :coffin: Offers
- :coffin: pages/bsx
- :bug: :label: missing AssetItem
- :wastebasket: popular on BSX
- :coffin: formatBsxBalanceEmptyOnZero
- :wastebasket: BSX in USD
- :coffin: ChartContainer.vue
- :coffin: Offers
- :wastebasket: BSX not in default state
- :coffin: queries for BSX
- :zap: no more pointing to subsquid/bsx
- :wastebasket: BSX in static
- :wastebasket: BSX indexer
- :globe_with_meridians: :wastebasket:  bsx related translations
- :bug: missing basilisk impl
- :test_tube: :wastebasket: remove bsx from tests
- :shrug: same team diff name
- :coffin: format BSX to Number

**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Closes #8490
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [ ] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>)

#### Community participation

- [ ] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by yangwao** [comment]
image

**Comment by yangwao** [comment]
After drop can be merged on Friday

**Review by Jarsen136 — APPROVED** [review]
I would remove some commented code related to basilisk. It could be another issue.

**Comment by yangwao** [comment]
Some tests broke
- https://github.com/kodadot/nft-gallery/actions/runs/7423445880/job/20200902780?pr=8776#step:7:11

**Pull request merged**
