### PR TITLE
fix: icon gone - connect wallet sidebar

### LINKED ISSUE #10651: icon gone - connect wallet sidebar
image
image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs Design check

- @exezbcz please review

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #10651

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by exezbcz** [comment]
task is to add the icon back, how is it in the design 
- this is the production image

and this ist the design: 
image

**Review by hassnian — APPROVED** [review]

**Comment by Jarsen136** [comment]
> task is to add the icon back, 

Yes I misunderstood  : )

**Comment by vikiival** [comment]
Test is failing

**Comment by hassnian** [comment]
> Test is failing

it's the same test as https://github.com/kodadot/nft-gallery/pull/10618#issuecomment-2242151709,

**Review by vikiival — APPROVED** [review]

**Pull request merged**
