### PR TITLE
chore: bump various dependecies

### LINKED ISSUE #1999: Bump various dependencies
Check if everything works in-app tho or when it could potentially harm previous application workflow or break something

```
idb-keyval | ^5.1.5 -> ^6.1.0
sass-loader | ^10.2 -> ^12.4
mingo | ^4.4.1 -> ^5.0.0
css-loader | 4.3.0 -> 6.5.1
ansi-regex | ^5.0.1 -> ^6.0.1
@vue/cli-plugin-babel | ^3.12.1 -> ^4.5.15
@types/webpack | ^4.41.32 -> ^5.28.0
@intlify/vue-i18n-loader | ^1.1.0 -> ^4.1.0
```

### Ref
- https://github.com/kodadot/nft-gallery/pull/1995
- https://github.com/kodadot/nft-gallery/pull/1998
- https://github.com/kodadot/nft-gallery/pull/1997
- https://github.com/kodadot/nft-gallery/pull/1993
- https://github.com/kodadot/nft-gallery/pull/1992
- https://github.com/kodadot/nft-gallery/pull/1991
- https://github.com/kodadot/nft-gallery/pull/1990
- https://github.com/kodadot/nft-gallery/pull/1989

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Do a quick check before the merge.

### PR type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [x] Chore

### What's new?

- [x] PR closes #1999
- [x] update dependecies too latest working-state, with some caveats though:
#### @types/webpack, sass-loader, css-loader
Vue 2.6.2 only goes together with webpack 4 -> **@types/webpack** latest we can go is **4.41.32**

-> **Css-loader** ^6.0.0 requires webpack 5 -> latest we can go is **5.2.7**

-> **sass-loader** ^11.0.0 requires webpack 5 -> latest we can go is **10.2**

####  @intlify/vue-i18n-loader 
We use **vue-i18n 8.27.0** -> The version for Vue I18n v8.x is now in @intlify/vue-i18n-loader **v1.x**! 

#### ansi-regex
We aren’t using this anymore afaik

#### @intlify/vue-i18n-loader
I’ll make a separate issue regarding this package, because I believe during nuxt migration we didn’ change to @nuxt/i18n even though we have it as a dependency. 
Config still seems to rely on `import VueI18n, { LocaleMessages } from 'vue-i18n’`

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases

### Had issue bounty label ?

- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI, a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by yangwao** [comment]
can we remove `"@types/file-saver"`? 

@vikiival claims it was been removed, maybe someone accidentally introduced it back 😄

https://github.com/kodadot/nft-gallery/blob/main/package.json#L52

**Comment by kkukelka** [comment]
> can we remove `"@types/file-saver"`?
> 
> @vikiival claims it was been removed, maybe someone accidentally introduced it back 😄
> 
> https://github.com/kodadot/nft-gallery/blob/main/package.json#L52
> 
> Suspicious https://github.com/kodadot/nft-gallery/blame/83f8ff91d30437023985ea4847ea597d7e73eb83/package.json#L52

`"@types/file-saver": "^2.0.5",` was reintroduced by renovate-bot

**Comment by yangwao** [comment]
> can we remove `"@types/file-saver"`?
> 
> @vikiival claims it was been removed, maybe someone accidentally introduced it back 😄
> 
> https://github.com/kodadot/nft-gallery/blob/main/package.json#L52
> 
> Suspicious https://github.com/kodadot/nft-gallery/blame/83f8ff91d30437023985ea4847ea597d7e73eb83/package.json#L52

@vikiival claims he got corrupted brain and blames himself and forgot to remove types 😄

**Comment by yangwao** [comment]
> 

It just bumped patch version apparently 🕵️‍♂️

image

**Comment by kkukelka** [comment]
> > 
> 
> It just bumped patch version apparently 🕵️‍♂️
> 
> image

just removed it

**Comment by yangwao** [comment]
TOP!

Perfect, I’ve sent the payout https://kusama.subscan.io/extrinsic/0x7b718a94612c97846f40bcdfc69c84d0bf06b5f1ebdeb0fbc37f7612e047a1c6

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/

**Pull request merged**
