### PR TITLE
fix: Rewrite Singular to KodaDot in item description

### LINKED ISSUE #5941: Rewrite Singular to KodaDot in item description
Links in existing collections are redirecting to Singular rather than relative addressing. 

I would like to see to redirect to KodaDot collections to keep seamless page within our page

image

https://singular.app/collections/c8d5ea648c93514667-MTPIAMRRS -> https://canary.kodadot.xyz/ksm/collection/c8d5ea648c93514667-MTPIAMRRS

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Closes #5941
- [x] Fix: url redirect modal dose not work
- [x] delete the unused component  `shared/collapse/DescriptionWrapper.vue`
- [x] Replace singular url in the description text.

#### Before submitting pull request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality

#### Optional

- [x] I've tested it at  `/ksm/gallery/12700243-c8d5ea648c93514667-MTPIAFRNDS-MTPIACJEST10-00000001`
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at 86222ac</samp>

Refactored and improved the redirect modal logic for gallery item descriptions. Extracted the `useRedirectModal` function to a separate file and simplified its usage in `GalleryItemDescription.vue` and `Markdown.vue`. Added support for singular.app collection links and removed unused files.

### <samp>🤖 Generated by Copilot at 86222ac</samp>

> _`useRedirectModal`_
> _refactored and improved_
> _autumn of clean code_

### CODE REVIEW

**Review by vikiival — COMMENTED** [review]
Code looks oki, fixed some weird hacks with attaching modals

**Review by preschian — COMMENTED** [review]
right click to open in new tab/copy the link still get singular. is it possible to edit URL in the description also?

**Comment by Jarsen136** [comment]
> right click to open in new tab/copy the link still get singular. is it possible to edit URL in the description also?

✅ Replace singular url in the description text.

**Review by daiagi — APPROVED** [review]
wfm

**Review by preschian — APPROVED** [review]

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 25.64 USD/KSM ~ 1.17 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x9e8a912e089eb719ffb14c435b19a23da3f0857c5e15f947cea1a45fd15d0eb9](https://kusama.subscan.io/extrinsic/0x9e8a912e089eb719ffb14c435b19a23da3f0857c5e15f947cea1a45fd15d0eb9)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
