### PR TITLE
fix: When I mint and want mint again, mint button doesnot work

### LINKED ISSUE #9420: When I mint and want mint again, mint button doesn't work
When I want mint again on same page, mint button is not clickable 

- https://kodadot.xyz/ahp/drops/echo

### LINKED ISSUE #9511: Minting one nft after another show success modal again
check 1:50s: 

address in the video is deployed version but i've also tested on canary: 

https://github.com/kodadot/nft-gallery/assets/36627808/ae730686-64eb-4eee-a27a-a39e1358cc7c

related: #9420 
related: #9453

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix

  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #9420
  - [x] Closes #9511

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [ ] My fix has changed UI

  ## Copilot Summary
  copilot:summary

  copilot:poem

### CODE REVIEW

**Review by preschian — APPROVED** [review]

**Comment by prury** [comment]
minted one, waited for conclusion -> clicked on mint -> wallet pop up appeared -> cancelled -> mint button doesn't work anymore: 

https://github.com/kodadot/nft-gallery/assets/36627808/48cd0f25-6c97-453a-af56-df3ece30bf25

**Comment by Jarsen136** [comment]
> minted one, waited for conclusion -> clicked on mint -> wallet pop up appeared -> cancelled -> mint button doesn't work anymore:
> 
>  double.mint.still.mp4

fixed. It should work after cancelling the tx modal.

**Comment by prury** [comment]
testing on /ahk/drops/meadow

look what happens: 

https://github.com/kodadot/nft-gallery/assets/36627808/434cb7d7-ece1-4530-b656-6a28e4d97480

**Comment by Jarsen136** [comment]
> testing on /ahk/drops/meadow
> 
> look what happens:
> 
> edit: @Jarsen136 problem coming from canary tho

The current PR is for `holderOf` drop. Could you test if it's fixed?

As for the issue you mentioned is for `paid` drop, I will check it. https://github.com/kodadot/nft-gallery/issues/9511

**Comment by prury** [comment]
> > testing on /ahk/drops/meadow
> > look what happens:
> > edit: @Jarsen136 problem coming from canary tho
> 
> The current PR is for `holderOf` drop. Could you test if it's fixed?
> 
> As for the issue you mentioned is for `paid` drop, I will check it. #9511

sorry for the confusion and thank you

**Comment by Jarsen136** [comment]
> @Jarsen136 same happened, using reflection holderof
> 
>  holderof.mp4

weird, I will check

**Comment by Jarsen136** [comment]
There are too many statuses that should be reset after minting. To refresh the page after closing the successful drop modal would be a workaround. 

Close this issue also https://github.com/kodadot/nft-gallery/issues/9511

**Comment by prury** [comment]
> There are too many statuses that should be reset after minting. To refresh the page after closing the successful drop modal would be an easier workaround.

not ideal, but ok, hope there's another workaround

> 
> Close this issue also #9511

i don't get it, should i close the PR or the issue?

**Comment by Jarsen136** [comment]
> > There are too many statuses that should be reset after minting. To refresh the page after closing the successful drop modal would be an easier workaround.
> 
> not ideal, but ok, hope there's another workaround
> 
> > Close this issue also #9511
> 
> i don't get it, should i close the PR or the issue?

I mean this PR would close both #9420 and #9511

**Review by hassnian — APPROVED** [review]

**Comment by prury** [comment]
> > > There are too many statuses that should be reset after minting. To refresh the page after closing the successful drop modal would be an easier workaround.
> > 
> > 
> > not ideal, but ok, hope there's another workaround
> > > Close this issue also #9511
> > 
> > 
> > i don't get it, should i close the PR or the issue?
> 
> I mean this PR would close both #9420 and #9511

ah got it! 
@Jarsen136 last thing i guess, i think in this PR, when i click on list on the success modal, the listing modal appears behind the success modal(something that is not happening on canary)

regarding the refresh solution, seems to be working nicely

**Review by prury — APPROVED** [review]

**Comment by yangwao** [comment]
Thanks!
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 7.77 USD/DOT ~ 6.435 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0xc523df6dc5b1f58160fcd9ca7a2fd91a7cd3a10daa05d50573f1f1e08866eee8](https://polkadot.subscan.io/extrinsic/0xc523df6dc5b1f58160fcd9ca7a2fd91a7cd3a10daa05d50573f1f1e08866eee8)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
