### PR TITLE
Add Sub.id into profile

### LINKED ISSUE #982: Add Sub.id to profile
Whenever user lands on https://kodadot.xyz/rmrk/u/CmMkskdeDpSoU2xKnZ214JkgFZKmMCZXoYyJfHYB1X1aihy can check sub.id profile through https://sub.id/#/CmMkskdeDpSoU2xKnZ214JkgFZKmMCZXoYyJfHYB1X1aihy

Suggested placement till now would be under users twitter
image

### PR DESCRIPTION
**Pull request by fairywellos**
### PR type
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### Before submitting this PR, please make sure:
- [x] Code builds clean without any errors or warnings
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional
- [x] I've tested it on mobile and everything works
- [ ] I found edge cases

### What's new? (may be part of changelog)
- This PR closes #982 - <Add sub.id link into profileLink component>

### If issue had bounty label ($,$$,$$$)
- Fill up your KSM address: https://kodadot.xyz/transfer/?target=Dr1Ech2pQami4e6bBsZe6jTLSCuF4PWLW5DMbMfR3aPoRyF

### Community participation
- [x] Are you at KodaDot Discord? If not yet, [let's join us - https://discord.gg/35hzy2dXXh](https://discord.gg/35hzy2dXXh)

### Screenshot
- In the profile page
Screen Shot 2021-11-03 at 1 48 40 PM

- In the gallery item detail
Screen Shot 2021-11-02 at 11 27 44 AM

### CODE REVIEW

**Comment by fairywellos** [comment]
> Interesting do we want it also on gallery item detail?
> 
> image
> 
> Thinking how it put efficiently on profile, probably just icon Sub.id is enough?

Sure. We can just add Sub.id into Profile component, not in ProfileLink.
Also, we can use Sub.id logo instead of using img & text.
FYI
Sub ID full logo

Does that sound good?

**Comment by fairywellos** [comment]
@yangwao Pushed the fix & updated the screenshots in the PR description.

**Comment by yangwao** [comment]
I've opened profile https://deploy-preview-1006--nftkodadot.netlify.app/rmrk/u/EAfi2vdUFfMTSAUEJgsTV95kHh9ChG1CP31FYc8x5UZwX1t

clicked on and landed here https://sub.id/#/undefined

is that should work? Probably doesn't work.

I'd would put next to the icon short address filter as sub.id has next to the icon for user recogniton
image

**Comment by fairywellos** [comment]
@yangwao Pushed the fix & updated the screenshot.
You can test it in the preview link: https://deploy-preview-1006--nftkodadot.netlify.app/rmrk/u/EAfi2vdUFfMTSAUEJgsTV95kHh9ChG1CP31FYc8x5UZwX1t

**Comment by yangwao** [comment]
LGTM

**Comment by yangwao** [comment]
let's merge it and I've sent payout https://kusama.subscan.io/extrinsic/0x9b8c61de44f59da4d0ba0ffda3b732470435bc9042604fe3c2f04a3df2585542

**Pull request merged**
