### PR TITLE
Working wallets #1714

### LINKED ISSUE #1714: Add to contributing.md working wallets
As people would like to carry their bounties in different ways and help them create their wallets, please add a list of wallets + guides on how to find new wallet to receive a bounty

Assembly some good manual with all options where we can reference new contributors.

h/t to @atharva3010 for inspiration 

### Ref
- https://wiki.polkadot.network/docs/build-wallets

### PR DESCRIPTION
**Pull request by AshutoshSingh00001**
Thank you for your contribution to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz/).

👇 __ Let's make a quick check before the contribution.

## PR Type
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #1714
- [x] ## Did your issue had any of the "$" label on it?
- [x] My DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=158VTDxZJidzsMcAdh7h828domveRvpmk1SCxwLUEHhcgY4v&usdamount=0&donation=true)

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
https://github.com/kodadot/nft-gallery/blob/8000d07c1ba398178e2c9f891f46c27e0b6b9253/Wallets.md

Screenshot missing

Maybe the issue is no longer relevant since we have dedicated [wallet page](https://hello.kodadot.xyz/tutorial/wallet)

**Comment by AshutoshSingh72** [comment]
> https://github.com/kodadot/nft-gallery/blob/8000d07c1ba398178e2c9f891f46c27e0b6b9253/Wallets.md
> 
> Screenshot missing
> 
> Maybe the issue is no longer relevant since we have dedicated [wallet page](https://hello.kodadot.xyz/tutorial/wallet)

Sorry i guess it's a bug i'll fix

**Comment by AshutoshSingh00001** [comment]
> https://github.com/kodadot/nft-gallery/blob/8000d07c1ba398178e2c9f891f46c27e0b6b9253/Wallets.md
> 
> Screenshot missing
> 
> Maybe the issue is no longer relevant since we have dedicated [wallet page](https://hello.kodadot.xyz/tutorial/wallet)
Sorry i guess it's a bug i'll fixp

**Comment by AshutoshSingh00001** [comment]
> https://github.com/kodadot/nft-gallery/blob/8000d07c1ba398178e2c9f891f46c27e0b6b9253/Wallets.md
> 
> Screenshot missing
> 
> Maybe the issue is no longer relevant since we have dedicated [wallet page](https://hello.kodadot.xyz/tutorial/wallet)

Fixed ✅

**Comment by AshutoshSingh00001** [comment]
> https://github.com/kodadot/nft-gallery/blob/8000d07c1ba398178e2c9f891f46c27e0b6b9253/Wallets.md
> 
> Screenshot missing
> 
> Maybe the issue is no longer relevant since we have dedicated [wallet page](https://hello.kodadot.xyz/tutorial/wallet)

**Pull request closed without merging**
