### PR TITLE
🔧 POW Server side rendering

### PR DESCRIPTION
**Pull request by roiLeo**
Let me know your thoughts about this change.

SSR is needed if we want to use all Nuxt power

### CODE REVIEW

**Comment by roiLeo** [comment]
😢 
Screenshot 2023-10-18 at 11-50-40 Invocation Failed

**Comment by preschian** [comment]
as long the build and deployed successfull im fine with it 👍🏻

**Comment by roiLeo** [comment]
So many things to reconfigure on client-side, don't mind first load only showing footer it's normal.
Looks like all playwright tests are broken now 😞

**Comment by yangwao** [comment]
What can potentially break?

**Comment by roiLeo** [comment]
> What can potentially break?

UI/UX, client side plugin and maybe more?

**Comment by yangwao** [comment]
> UI/UX, client side plugin and maybe more?

And do we need to setup something special from CF/Netlify to work?

**Comment by roiLeo** [comment]
> And do we need to setup something special from CF/Netlify to work?

Nope, only check which components needs to be loaded on client-side and which can be loaded on server side.
For now I've wrapped most components on client-side that why we have a "delayed loading"

**Comment by roiLeo** [comment]
// TODO: persist localstorage (or maybe vueuse equivalent)

**Comment by roiLeo** [comment]
more changes in #8356

**Pull request closed without merging**
