### PR TITLE
fix: profile tabs not working properly sometimes

### LINKED ISSUE #2723: profile Tabs not working properly sometimes
### What happened?

when i login to my account then visit my profile i get this:
.

 
 its only showing the collected tab 
 
 when i refresh the page sometime i get this: 
.

it still says collected but its actually showing the Created nfts 
.
as a way around it i go to explore page then i go back to my profile using the login tab (top right corner) 
and voila i see everything as it should look 
Note: this only happens when i don't visit kodadot for more than 24hours, and after it starts working fine, it stays like that for the rest of the day ^^ 

### Please reproduce in steps

/

### Expected Behavior

/

### What browsers are you seeing the problem on?

Chrome

### Are you logged in?

Yes

### At which address did you encounter bug?

kodadot.xyz

### Screenshots

/

### Relevant log output

```shell
/
```

### Payment link for reward

https://nft.kodadot.xyz/transfer?target=JHMAL5CyvxWc3Ud42QxRUTpSnUa4m56mRSzPK69d1TU8NG7&usdamount=10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2723 
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by vikiival** [comment]
Code looks oki

**Comment by vikiival** [comment]
@XyloDrone said she wants to test it

**Comment by XyloDrone** [comment]
Hmm, still having the same issue...
Screenshot 2022-04-01 at 13 58 00
this is via https://deploy-preview-2725--koda-nuxt.netlify.app/rmrk/u/5EekGnpPfqHYg8jSq7kxaPUEeDnVhDMJbU62jNgT5iocuvsQ?tab=collected

**Comment by Jarsen136** [comment]
> Hmm, still having the same issue... Screenshot 2022-04-01 at 13 58 00 this is via https://deploy-preview-2725--koda-nuxt.netlify.app/rmrk/u/5EekGnpPfqHYg8jSq7kxaPUEeDnVhDMJbU62jNgT5iocuvsQ?tab=collected

It seem that this address have no any collected items and nfts. So the current display is normal.

cc @vikiival 
operationName: "nftListCollected"  
image

operationName: "firstNftByIssuer"
image

**Review by roiLeo — COMMENTED** [review]
Sorry if I'm missing something but could you explain why you use a debounce? 
For me debounce & timeout are not good pratice

**Comment by Jarsen136** [comment]
> > Hmm, still having the same issue... Screenshot 2022-04-01 at 13 58 00 this is via https://deploy-preview-2725--koda-nuxt.netlify.app/rmrk/u/5EekGnpPfqHYg8jSq7kxaPUEeDnVhDMJbU62jNgT5iocuvsQ?tab=collected
> 
> It seem that this address have no any collected items and nfts. So the current display is normal.
> 



> oh, I actually have quite a few NFTs :D Seems to be working on kodadot.xyz now tho: https://kodadot.xyz/rmrk/u/FAMw7AGJCJURnYtbpa1ULqEnp4jVtAV3qvn82xQZX27ezBB?tab=collected

I found the reason. These two address are different.  Though I have no idea why they have the same display name : )
5EekGnpPfqHYg8jSq7kxaPUEeDnVhDMJbU62jNgT5iocuvsQ -> have no nfts
FAMw7AGJCJURnYtbpa1ULqEnp4jVtAV3qvn82xQZX27ezBB   -> have nfts

Actually, you may try to visit the below url to test if it works well. @XyloDrone 
https://deploy-preview-2725--koda-nuxt.netlify.app/rmrk/u/FAMw7AGJCJURnYtbpa1ULqEnp4jVtAV3qvn82xQZX27ezBB

**Comment by Jarsen136** [comment]
> Sorry if I'm missing something but could you explain why you use a debounce? For me debounce & timeout are not good pratice

OK, I explain why I use it. The error in the issue causes by repeated network requests on page initialization.

invoke request from component mounted:  
image

invoke request from pageChange:  
image

 The `this.id` is undefined when requesting from `pageChange`, so the response list may be [] sometimes. further resulted in an empty list of pages.

We need to set 'this.id' before request. Also prevent from double request by using debounce.

**Comment by XyloDrone** [comment]
Cool, it works now!

**Comment by yangwao** [comment]
pay 100 usd 
let's test on main

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 201.69 USD/KSM ~ 0.496 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x5dfec73cbc8b18b0491c409b5e0331331814ace1c14e09ba18b95357ea22709d](https://kusama.subscan.io/extrinsic/0x5dfec73cbc8b18b0491c409b5e0331331814ace1c14e09ba18b95357ea22709d)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
