### PR TITLE
fix: vue component ref type

### PR DESCRIPTION
**Pull request by Gavin-Gong**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

fix Vue Component ref type error
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer?target=15GP8zVbH2Nyw4VcznhVDXyFSx3wCzuVciUMsk5vsdMKcrMn&usdamount=0)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at b346f6b</samp>

Fixed TypeScript errors and improved type safety in several components that handle forms and inputs for collections and tokens. Refactored some refs to use `ref` instead of `as` and changed some type annotations to use `InstanceType<typeof>` instead of `typeof`.

### <samp>🤖 Generated by Copilot at b346f6b</samp>

> _We're fixing the errors in the code of doom_
> _We're using the refs and the types to improve_
> _We're refactoring the props and the inputs of balance_
> _We're the masters of TypeScript, we make it enhance_

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]

**Comment by vikiival** [comment]
pls can one more person from @kodadot/internal-dev review ?

**Comment by daiagi** [comment]
What issue / problem does it fix?

**Comment by Gavin-Gong** [comment]
> What issue / problem does it fix?

@daiagi  Just fixing the Vue ref type usage error.

`ref` prop type should be assigned an instance type instead of a component type.

Incorrect usage
```ts
const searchSuggestionRef = ref<typeof SearchSuggestion>()
```

Correct usage
```ts
const searchSuggestionRef = ref<InstanceType<typeof SearchSuggestion>>()
```
You can refer to the official Vue documentation
https://vuejs.org/guide/typescript/composition-api.html#typing-component-template-refs

And these changes will **not affect runtime business logic.**

**Review by daiagi — APPROVED** [review]

**Comment by vikiival** [comment]
thanks!

**Comment by vikiival** [comment]
pay 15 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $15 @ 4.85 USD/DOT ~ 3.093 $DOT
🧗 [15GP8zVbH2Nyw4VcznhVDXyFSx3wCzuVciUMsk5vsdMKcrMn](https://polkadot.subscan.io/account/15GP8zVbH2Nyw4VcznhVDXyFSx3wCzuVciUMsk5vsdMKcrMn)
🔗 [0xdd34c219c43d3ad4dca12d0aeb5368985c9c8c17967efe2c9a6173efed26bdfd](https://polkadot.subscan.io/extrinsic/0xdd34c219c43d3ad4dca12d0aeb5368985c9c8c17967efe2c9a6173efed26bdfd)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
