### PR TITLE
feat: Claim congrats message improvements

### LINKED ISSUE #8831: Claim congrats message improvements
lets make some improvements here 

first, lets make the list button primary 

image

then, it would be nice to give it a loading state, not just disabled

image

- Disabled state with loader wheel please (used in quick buy, generating new instance etc.) 
- button label to loading
image

components here: https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=5311-18771&mode=design&t=OQiw3j5B40sVvje5-11

and the list flow here: https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=1458-19091&mode=design&t=OQiw3j5B40sVvje5-11

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] ❗️ Fixes bigint not handled in autotelport [cf73817](https://github.com/kodadot/nft-gallery/pull/8838/commits/cf73817ea3946682f0deed11dace5afd0a6af2bb)
- [x] Closes #8831

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2024-01-03 at 16 52 04@2x

CleanShot 2024-01-03 at 16 56 13

### CODE REVIEW

**Comment by hassnian** [comment]
@exezbcz  pls review

**Review by roiLeo — APPROVED** [review]

**Comment by prury** [comment]
i think text color on list button should be black: 

image

loading seems ok i guess: 

image

functionality works as expected, loading state until listing is possible

**Comment by hassnian** [comment]
dark

CleanShot 2024-01-04 at 08 36 23@2x

**Comment by hassnian** [comment]
@roiLeo https://github.com/kodadot/nft-gallery/pull/8838/commits/6ec911c6782ef36aa3f239353ff848543732885d 👀

**Review by Jarsen136 — APPROVED** [review]

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 7.7 USD/DOT ~ 3.896 $DOT
🧗 [13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh](https://polkadot.subscan.io/account/13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)
🔗 [0x8a84cf35848b9adb26b932be8715cf4943d15590bf8f9a7558e8d1d224b4ab57](https://polkadot.subscan.io/extrinsic/0x8a84cf35848b9adb26b932be8715cf4943d15590bf8f9a7558e8d1d224b4ab57)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
