### PR TITLE
Update 🇩🇪 German/Deutsch translation in KodaDot 

### PR DESCRIPTION
**Pull request by spacesmutje**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [ ] PR closes #<issue_number>
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EFYwtJuqDVjrFXoh6uH5tv37XbLnujyRrBtrMX8v78XxVKN)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by spacesmutje** [comment]
Can you guys enable the german flag on netlify so i can check if everything is in order? @yangwao

**Comment by yangwao** [comment]
https://open.spotify.com/track/5RYLa5P4qweEAKq5U1gdcK?si=2c787f747abf4f8b

image



image


😄 

Frank can then check german translations 

image

**Comment by yangwao** [comment]
> Can you guys enable the german flag on netlify so i can check if everything is in order? @yangwao

plus, I've merged the upstream branch so pull new stuff :) 

At least I've learned to break gh pr checkout in 2 minutes and learned new trick if gh pr checkout is rejected
`gh pr checkout 3918 -b 3918-2`

deploy should be up in 5 mins I bet

**Review by Jarsen136 — APPROVED** [review]
code LGTM

**Comment by petersopko** [comment]
@spacesmutje just a limit set for first time contributors :) should be good now

**Comment by petersopko** [comment]
tbh not sure what's the problem here now, seems that netlify can't build this one?

**Comment by spacesmutje** [comment]
@petersopko yes, something is going wrong with lint. no idea what it is though.

**Comment by petersopko** [comment]
> @petersopko yes, something is going wrong with lint. no idea what it is though.

there were some invalid jsons files (missing commas and stuff), seems to be working now but netlify didn't update the deploy 👀 anyways, can we get some more german native eyes on this one? Cannot verify the quality of the translation.

**Comment by spacesmutje** [comment]
Will ping Frank again. And look for an additional reviewer

**Comment by petersopko** [comment]
@yangwao can you please check the deploy here / what can be done 😄 I don't see why isn't it redeploying again

**Comment by spacesmutje** [comment]
At least for now I only see green checkmarks, already a few steps further than this morning :)

**Comment by petersopko** [comment]
@spacesmutje the app is now deployed, please click through it and make sure there aren't any leftovers, here's some examples I found: 

image
image
image
image


I'm wondering whether these things are contained in the translation folder, I think @prachi00 was working on this, right? Do we have all the string captured?

**Comment by yangwao** [comment]
> @yangwao can you please check the deploy here / what can be done 😄 I don't see why isn't it redeploying again

you can inspect deploy logs yourself and seems it's deployed well. 
https://app.netlify.com/sites/koda-nuxt/deploys/63205cd8e765b10008c9fae7

Seems at 12:35 when you merged `main` 

PR#[3918](https://github.com/kodadot/nft-gallery/pull/3918): Update-de.json@[bbc8bce](https://github.com/kodadot/nft-gallery/commit/bbc8bceb515ed69183d7dc09b7c53a3072dc607c)

https://github.com/kodadot/nft-gallery/pull/3918/commits/bbc8bceb515ed69183d7dc09b7c53a3072dc607c

**Comment by yangwao** [comment]
> Will this stay in English, or is it some mistake?
> 
> Snímek obrazovky 2022-09-12 v 12 36 10

Seems this one issues did not covered landing 
- #3805

**Comment by petersopko** [comment]
> Seems this one issues did not covered landing

it was just faulty json, it's there now:
image

**Comment by petersopko** [comment]
> you can inspect deploy logs yourself 

I know, it was just failed deploy and the new one wasn't showing up until recently :)
image

**Comment by spacesmutje** [comment]
Footer is not scaling correctly. German is a language of long words. Might consider to scale the font. Same goes for the search tab, but i think i already saw an open issue.
Screenshot 2022-09-13 15 02 11
image

Also it appears as if the [About](https://kodadot.xyz/about) page is not included/attached to the en.json / de.json? I could not find it in there.
 
Anyhow, when clicking on it you end up here:
Screenshot 2022-09-13 15 15 11

I'am going through it as we speak. 
Screenshot 2022-09-13 14 52 46

@petersopko i left the classic, simple and creative mint in english on purpose, since Klassisch, Einfach and Kreativmint sounds weird for me. Our audience is most likely used to these terms. But of course I can translate them as well. Just let me know, i will be done with everything in the evening.

**Comment by spacesmutje** [comment]
I looked through the whole de.json, but can't find the lines of code for the underlined words.
Screenshot 2022-09-13 23 35 08

**Comment by vikiival** [comment]
@FrankBevr can you please check ?

**Comment by FrankBevr** [comment]
### Hola everyone,
I got 15 things, which catched my eyes on the deployed Website.

[No1](https://media.discordapp.net/attachments/958772808215822396/1022474753921003520/unknown.png?width=720&height=405)
[No2](https://media.discordapp.net/attachments/958772808215822396/1022474753921003520/unknown.png?width=720&height=405)
[No3](https://media.discordapp.net/attachments/958772808215822396/1022475114769555506/unknown.png?width=720&height=405)
[No4](https://media.discordapp.net/attachments/958772808215822396/1022475583218798642/unknown.png?width=720&height=405)
[No5](https://media.discordapp.net/attachments/958772808215822396/1022475801125453924/unknown.png?width=720&height=405)
[No6](https://media.discordapp.net/attachments/958772808215822396/1022475801125453924/unknown.png?width=720&height=405)
[No7](https://media.discordapp.net/attachments/958772808215822396/1022476065052049438/unknown.png?width=720&height=405)
[No8](https://media.discordapp.net/attachments/958772808215822396/1022476065052049438/unknown.png?width=720&height=405)
[No9](https://media.discordapp.net/attachments/958772808215822396/1022476336348008448/unknown.png?width=720&height=405)
[No10](https://media.discordapp.net/attachments/958772808215822396/1022476514396209202/unknown.png?width=720&height=405)
[No11](https://media.discordapp.net/attachments/958772808215822396/1022477116991877140/unknown.png?width=720&height=405)
[No12](https://media.discordapp.net/attachments/958772808215822396/1022477605271765052/unknown.png?width=720&height=405)
[No13](https://media.discordapp.net/attachments/958772808215822396/1022478026098888775/unknown.png?width=720&height=405)
[No14](https://media.discordapp.net/attachments/958772808215822396/1022478404991332382/unknown.png?width=720&height=405)
[No15](https://media.discordapp.net/attachments/958772808215822396/1022478404991332382/unknown.png?width=720&height=405)

I didnt looked thruh the json file because its soooo long. But if its urgent I will read thruh it immeditly.^^

### cheers 🖖

**Comment by spacesmutje** [comment]
@FrankBevr Thank you for your feedback. I changed creative minting to Kreatives Minting. For the others, it seems that i did something wrong at my last commit, so now it should be up to date.

Since i mentioned earlier that some parts are not showing up in the locales/lang files, i can't translate it 😄

**Review by petersopko — APPROVED** [review]
wfm

**Review by yangwao — APPROVED** [review]
some strings are still missing but let's push it live. 
continue to https://github.com/kodadot/nft-gallery/issues/4004

**Pull request merged**
