### PR TITLE
fix: Pagination and infinity scrolling is broken on Basilisk & Moonsama

### LINKED ISSUE #3342: Pagination and infinity scrolling is broken on Basilisk & Moonsama
Wait till 
- #3340 is merged

Seems pagination and infinity scrolling is broken 👀 

but manually adding pages works 

image

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/3340#issuecomment-1176146437_

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3342 
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by yangwao** [comment]
wfm! 
let's wait for a code check.

**Comment by yangwao** [comment]
wfm! 

pay 100 usd 

let's wait for a code check.

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 50.96 USD/KSM ~ 1.962 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x4195e127b1f730d91c8f199bc3b8c1c6d5b9ae2992d36a4d5c011848915aaccb](https://kusama.subscan.io/extrinsic/0x4195e127b1f730d91c8f199bc3b8c1c6d5b9ae2992d36a4d5c011848915aaccb)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Review by vikiival — APPROVED** [review]
Code looks oki

**Pull request merged**
