### PR TITLE
fix: Save Art: make it more user-friendly

### LINKED ISSUE #10199: Save Art: make it more user-friendly
Issue
---
This was bothering me for a while, but I could have survived without this. But now also more people noticed this. Saving of full-sized image is possible only when you open full-sceen. 

Screenshot 2024-05-03 at 10 57 14

Proposed solution
---
Can we have a save button below the pic? 
Screenshot 2024-05-03 at 10 59 16

Or any other suggestions how to make it simple and quick?

### PR DESCRIPTION
**Pull request by panda6151025**
- [x] Bugfix

## Needs Design check

- @exezbcz please review

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #10199
- [x] Requires deployment <worker/stick/speck>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [x] I've tested it at </ahp/collection>
- [ ] I've tested PR on mobile
- [x] I've written unit tests 🧪
- [ ] I've found edge cases

- [x] [Are you at Koda Ecosystem Telegram?](https://t.me/koda_eco)

## Screenshot 📸

- [] My fix has changed **
Capture1
** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by daiagi** [comment]
image from canary:
hdd_


image from this pr:
hdd_ hdd #115


Both 119kb, 300pxX300px, **same quality**

**Comment by panda6151025** [comment]
Hello,Daiagi, Could you explain about it more detail?

**Comment by daiagi** [comment]
The issue is about having a quick easy way to download full quality image, without opening the image in full screen. 

I have tested your pr and found that the image quality downloaded is the same as it was before. 
Therfore, this pr does not solve the issue

**Comment by panda6151025** [comment]
To improve image quality while downloading, especially when using JavaScript, you can consider the following approach:
Use high-resolution images: Make sure you are using a high-resolution image as the source for your download. High-quality images naturally provide better clarity and detail.

Compression Optimization: Compresses images in a way that maintains high quality. This may include using modern image formats such as WebP or efficient compression algorithms to reduce file size without sacrificing visual fidelity.

Dynamic Image Rendering: Dynamically render images at higher quality before downloading. Before starting the download process, leverage HTMLCanvasElement and Context2D API to manipulate and enhance image quality as needed.
So I drew an image on a canvas. We then use the nuxt/image module to compress the image into Webp.
As a result, image size was reduced from 121 kbytes to 30 kbytes and image quality was improved.

**Comment by prury** [comment]
Now the quality is way worse and a better UI solution was not provided.
Also, we do not welcome chatgptesque comments, closing PR.

**Pull request closed without merging**
