### PR TITLE
fix: add hover color on navigation bar on light mode

### LINKED ISSUE #3860: Text on hover in menu is not visible
### What happened?

text hover in menu, there is no contrast

### Please reproduce in steps

hover on menu item - Stats/create
hover on item on list - spotlight
spotlight - text is not visible

### Expected Behavior

text changing to black so it has contrast

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

No

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

_No response_

### Screenshots

image

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3860
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Review by kkukelka — APPROVED** [review]
wait .. didnt we just have this bug a few days ago hahah

**Review by roiLeo — APPROVED** [review]
https://github.com/kodadot/nft-gallery/blob/c5fadf52a522d90c67cc082ca288188e6e798436/styles/themes/_light.scss#L55

Here is the rule that causes problems

Screenshot 2022-08-30 at 08-37-10 Low minting fees and carbonless NFTs KodaDot - Kusama NFT Market Explorer

`:focus` now wfm

**Review by JustLuuuu — APPROVED** [review]
wfm

**Comment by kkukelka** [comment]
pay 50

**Pull request merged**
