### PR TITLE
⚒️ mobile wallet enable on app load

### LINKED ISSUE #2630: Nova & Math wallet connection
It's not possible to connect your wallet throught Kodadot with nova or math wallet mobile app.
It used to work when we requested access to the extension on Kodadot app loading but since we introduce multiple wallet extension, it won't ask for extension permission on mobile.

It look like the `window` is undefined in mobile app browser and we can't acces nor inject extension for now.

#### working preview (before wallet)
https://deploy-preview-2419--koda-nuxt.netlify.app/

#### non-working preview (recent)
https://deploy-preview-2628--koda-nuxt.netlify.app/

### PR DESCRIPTION
**Pull request by roiLeo**
This is more a hotfix than a bugfix. Bring back old method for mobile wallet.
- I tested it on Nova Android app
- not working yet on Math wallet (maybe cached website)

### PR type

- [x] Bugfix

### What's new?

- [x] PR closes #2630 
- [x] enable extension on app load if mobile device detected

### How to test it?
- open mobile app
- paste preview url in searchbar then hit enter
- app will now ask to connect to kodadot

### CODE REVIEW

**Comment by vikiival** [comment]
image

**Comment by vikiival** [comment]
Does not work with math wallet

**Comment by vikiival** [comment]
Something broke modal on the Nova Wallet

image

**Comment by vikiival** [comment]
App asked for the permission but unable to select an account

image

**Comment by yangwao** [comment]
> It seems that `window` is undefined in mobile app browser and I can't acces to injected extension. any idea is good to take

with current fix we at least know it's mobile?

**Comment by roiLeo** [comment]
> with current fix we at least know it's mobile?

We know when it's mobile, how to trigger extension but can't access to accounts, I'll try to cook up & push a solution

**Comment by roiLeo** [comment]
continue on new branch since force

**Pull request closed without merging**
