### PR TITLE
#2420 - fix searchbar on mobile

### LINKED ISSUE #2420: fix searchbar on mobile
### What happened?

As discussed in #beta, searchbar is gone from Gallery on mobile as presented on the screenshot below. I suggest the following:

While on mobile, in gallery (or collections), keep the searchbar in the container of Gallery/Collections as up until now. When clicked inside, the searchbar moves up, as was done in #2253 . I would remove it from the navbar in this case.

Other than that, it can stay in navbar. 

I think this could both prevent duplicit searchbars and keep easy access to search.

image

### Please reproduce in steps

Go to ... Click on .... See error

### Expected Behavior

I've expected ...

### What browsers are you seeing the problem on?

_No response_

### Are you logged in?

_No response_

### At which address did you encounter bug?

_No response_

### Screenshots

Paste from your clipboard or upload screenshots

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by petersopko**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2420
- [x] showing searchbar in gallery ~and collections~ on mobile as before, but hiding it when navbar expands. I'll follow next week in https://github.com/kodadot/nft-gallery/issues/2261

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

https://user-images.githubusercontent.com/73316633/155182728-5df16f73-7b11-4dda-a8e9-78f40fff2a96.mp4

### CODE REVIEW

**Comment by yangwao** [comment]
#2425 was merged, you've got green runway ;)

**Comment by petersopko** [comment]
I've changed the order of text in search section, in my opinion this still wasn't good: 
image
Here's the current version:

https://user-images.githubusercontent.com/73316633/156026081-4ec555eb-3290-42f4-b1a9-fec805c02b94.mp4

**Comment by petersopko** [comment]
@yangwao I've kept the search bar located in the navbar in case of collections instead of what I've described in #2420 since I've mistakenly thought that the searchbar located in navbar is "collections" on collections page. Since in navbar there's always only "gallery", it makes sense to keep it there. The gallery is fixed here, tomorrow I'll start looking into the unification of Gallery/Collections search experience.

https://user-images.githubusercontent.com/73316633/156027835-11db5b77-fe1c-4af7-aa9e-d5058578654b.mp4

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 123.91 USD/KSM ~ 0.807 $KSM
🧗 [FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y](https://kusama.subscan.io/account/FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y)
🔗 [0x18c4b4defd1c60ca878a33361c45b08bc16b946841bf145773d120a28b895d02](https://kusama.subscan.io/extrinsic/0x18c4b4defd1c60ca878a33361c45b08bc16b946841bf145773d120a28b895d02)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
