### PR TITLE
Bump paraspell SDK version

### PR DESCRIPTION
**Pull request by dudo50**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [ ] Closes #<issue_number>
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

Version bump needed only. Breaking change in new version did not touch scenarios used in Kodadot.

### CODE REVIEW

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
Does this one contain Builder?

**Comment by yangwao** [comment]
@dudo50 update pnpm-lock.yml please

**Comment by dudo50** [comment]
@vikiival it does, but implementing it is not mandatory. Old function like way still works :)

**Comment by dudo50** [comment]
@yangwao hope this does it.

**Comment by dudo50** [comment]
Just noticed, the version of ParaSpell SDK is already bumped in package.json. This PR then does not need to be open. Thus closing it.

**Pull request closed without merging**
