### PR TITLE
🔧 vue3 composition api pages

### PR DESCRIPTION
**Pull request by roiLeo**
part of #4750 

- remove ExperimentMixin
- vue3 composition `/:prefix/collection/:id/activity` page
- vue3 composition `/:prefix/explore/items` page
- vue3 composition `/:prefix/explore/collectibles` page
- vue3 composition `/identity` page
- vue3 composition `/sustainibility` page

<s>edit: DRAFT doesn't work yet</s>

### CODE REVIEW

**Comment by vikiival** [comment]
Looks good sir

**Comment by prury** [comment]
did not find any strange behavior or different console warnings compared to canary on those pages

**Comment by prury** [comment]
As suggested by @roiLeo, i'm testing share preview on the modified pages

Problems encountered so far: 
https://deploy-preview-6379--koda-canary.netlify.app/bsx/collection/1194754914/activity
image

**Review by daiagi — APPROVED** [review]
lgtm

**Comment by roiLeo** [comment]
> 



> As suggested by @roiLeo, i'm testing share preview on the modified pages
> 
> Problems encountered so far(telegram, discord): https://deploy-preview-6379--koda-canary.netlify.app/bsx/collection/1194754914/activity image

I've made some test and it's not related with this PR, preview doesn't work for url starting with `deploy-preview-...`
Tested on https://deploy-preview-6380--koda-canary.netlify.app/bsx/collection/1194754914/activity

Capture d’écran 2023-07-04 à 8 37 16 AM

**Review by vikiival — APPROVED** [review]

**Comment by prury** [comment]
> I've made some test and it's not related with this PR, preview doesn't work for url starting with `deploy-preview-...` Tested on https://deploy-preview-6380--koda-canary.netlify.app/bsx/collection/1194754914/activity

Good to know! thank you

**Comment by roiLeo** [comment]
works well now
Capture d’écran 2023-07-04 à 2 37 29 PM

**Pull request merged**
