### PR TITLE
#2799 Prevent user from minting when has insufficient balance

### LINKED ISSUE #2799: Prevent user from minting when has insufficient balance
Prevent user from minting when has insufficient balance, other actions send/consume/list/buy been solved in action component

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/65#issuecomment-1092666427_

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #2799
- [ ] Requires deployment <rubick/magick_issue>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by prachi00** [comment]
For classic mint, I am not sure what is is the required balance so have compared it with 0 for now, let me know if this needs to be changed.

**Comment by kkukelka** [comment]
> For classic mint, I am not sure what is is the required balance so have compared it with 0 for now, let me know if this needs to be changed.

@vikiival as far as im concerned its a flat fee no matter the minting process right? 
"At the time of writing, the fee for minting a NFT are 0.02 USD" according to our FAQ

**Comment by vikiival** [comment]
> @vikiival as far as im concerned its a flat fee no matter the minting process right? "At the time of writing, the fee for minting a NFT are 0.02 USD" according to our FAQ

from(#1967): The basic flat fee is $0.5 per minted collection
For the NFT mint it's also $0.5 + $1 if the NFT is carbonless

I would just check if the user has at least like $2 in the account:

Screenshot 2022-06-09 at 18 11 22

**Comment by prachi00** [comment]
> > @vikiival as far as im concerned its a flat fee no matter the minting process right? "At the time of writing, the fee for minting a NFT are 0.02 USD" according to our FAQ
> 
> from(#1967): The basic flat fee is $0.5 per minted collection For the NFT mint it's also $0.5 + $1 if the NFT is carbonless
> 
> I would just check if the user has at least like $2 in the account:
> 
> Screenshot 2022-06-09 at 18 11 22

Added $2 check

**Review by kkukelka — APPROVED** [review]
alrighty. good to go then!

**Comment by kkukelka** [comment]
pay 100

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 63.53 USD/KSM ~ 1.574 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0xcc0ab519043b411f4ea8b2d29da618c6b136bd76be87adc0ef3b643499106926](https://kusama.subscan.io/extrinsic/0xcc0ab519043b411f4ea8b2d29da618c6b136bd76be87adc0ef3b643499106926)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
