### PR TITLE
feat(collection): skeleton

### LINKED ISSUE #988: Add skeletons to collections
When user opening collection, would be amazing to have a skeleton at 
- collection name
- creator
- analytics like items, owned, floor price volume traded 24h volume traded
- items 

https://kodadot.xyz/rmrk/collection/0E76E3AC15B4C1FA1E-FROST

image

### LINKED ISSUE #1095: Add addressing to address bar to collection chart
I would like to send a link to the collection chart, but I can not rn 
Add parameter to have switched to Activity Tab to URL address .
image

### PR DESCRIPTION
**Pull request by roiLeo**
**Thank you for your contribution** to the KodaDot NFT gallery.

👇 Do a quick check before the merge. 

### PR type
- [x] Bugfix
- [x] Feature
- [x] Refactoring

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested PR on mobile and everything works
- [ ] I found edge cases

### What's new?
- [x] closes #988 
- [x] closes #1095 
- [ ] <brief_description_of_what_I've_added>

### CODE REVIEW

**Comment by yangwao** [comment]
Is it possible to challenge this bug? :D
https://user-images.githubusercontent.com/5887929/141755371-e965d595-40fa-421b-a0b5-63dac9d064c1.mov

**Comment by yangwao** [comment]
I'm looking at on the right PR deployment? https://deploy-preview-1147--nftkodadot.netlify.app/rmrk/collection/242c96bed4f3602b04-4ZLBF 

if so, 1147 still has this double layout 

image

**Comment by roiLeo** [comment]
> 
> 
> I should not be testing code, I break stuff 😄
> 
> https://deploy-preview-1147--nftkodadot.netlify.app/rmrk/collection/1eded96180db41f86e-KUTE
> 
> image

Weird, I can't reproduce it. Maybe try to clear your browser cache.

**Comment by yangwao** [comment]
oh yeah, I'm always special. 
Seems service worker doesn't update well everytime, it's not first time what I've encountered 👀

**Pull request merged**
