### PR TITLE
feat: reorder navbar elements

### LINKED ISSUE #2252: Navbar sorting & cleaning
- Probably we could move Tutorial into Log In dropdown

From Extra move to Profile, put them 
- Transfer - it's not possible to do until you logged anyway
- Teleport - same as above
- Admin -  same as above

The final state under profile should be, in a particular order
```MD
- Profile
- Settings
---------
- Admin
- Credit
- Identity
- Teleport
- Transfer
----------
- FAQ
- Tutorial
----------
- Language (icon?)
- Change Account
```
Thus you can remove the Extra, Tutorial, Language selector
The reasoning is lightweight UI doesn't show the user what's is needed. 

Once it's done @cryptodamsky could reflect in docs.kodadot.xyz :)

image

image

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

Screenshot 2022-02-07 at 19 25 09

### What's new?

- [x] PR closes #2252
- [x] reordered navbar elements to clean up UI a bit

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
Mobile menu has small glitch
Capture d’écran 2022-02-08 à 08 38 35

now if I want to access to `/faq`or `/tutorial` I need to be logged in, we could add these links in footer

**Comment by kkukelka** [comment]
> now if I want to access to `/faq`or `/tutorial` I need to be logged in, we could add these links in footer

good catch! @yangwao what's your opinion on this?

**Comment by yangwao** [comment]
> now if I want to access to `/faq`or `/tutorial` I need to be logged in, we could add these links in footer

oh sh, i was in v1 ideation thought about it and in second iteration v2 totally forgot about it. I'm trying getting someone who would help us on product on onboarding stuff as I'm deep down technical I might not see this every time and often.

I guess, having Tutorial would not be needed at all... as it's once time occasion, you are not need to return to that, probably same for FAQ hmm.

Would keep it just stuff on our landing and pretty much that's it. If we can remove in this PR 
- Create 
- What are NFTs - we can link it here to faq 
image

As on mobile navbar is not tempting to tap and for Read-only mode, we can keep
- Collections, Gallery, Spotlight, Series
- About, FAQ, Grants (I sense we will be merging this somehow in future) 

image

**Comment by yangwao** [comment]
oH found one on `main` https://beta.kodadot.xyz does this. 
That 1 px drop miss alignment. Probably relevant with mobile glitch? 

image
image

**Comment by kkukelka** [comment]
removed Tutorial and FAQ, fixed Css glitches
Screenshot 2022-02-08 at 20 35 25
Screenshot 2022-02-08 at 20 27 54
Screenshot 2022-02-08 at 20 26 12

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 187.13 USD/KSM ~ 0.534 $KSM
🧗 [EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW](https://kusama.subscan.io/account/EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)
🔗 [0xd56e3ecc7170c5fa00eb1f2e21e1661e518cd946b14e0e8c96264655ea31d948](https://kusama.subscan.io/extrinsic/0xd56e3ecc7170c5fa00eb1f2e21e1661e518cd946b14e0e8c96264655ea31d948)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
