### PR TITLE
test: cypress github workflow

### LINKED ISSUE #3679: Connect Cypress tests into CI/CD pipeline
As started in
- #2911

I was unsuccessful to implement cypress as GH action / Netlify plugin, we got the tests available to run locally right now, but the ultimate idea is to move this into automated thing which will run with every PR. @preschian you look like an ideal candidate for this one and it would help us a lot 👀 

Not sure if any of these references help:

- https://github.com/cypress-io/netlify-plugin-cypress
- https://docs.cypress.io/guides/continuous-integration/github-actions

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3679
- [ ] Requires deployment <rubick/magick_issue>
- [x] added cypress github workflow

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by kkukelka** [comment]
@petersopko 
some failed tests are being skipped for now to quickly get this into master branch (to prevent further components from breaking in the meantime)
Screenshot 2022-08-08 at 19 26 05

will track this in followup ticket https://github.com/kodadot/nft-gallery/issues/3701

**Review by JustLuuuu — APPROVED** [review]
wfm

**Comment by vikiival** [comment]
May @petersopko can have a look

**Comment by petersopko** [comment]
> May @petersopko can have a look

I've had a look and I couldn't make the tests fail, I've checked out @kkukelka branch and after removing the `.skip` commands from tests, I get all green. Reported this also in https://github.com/kodadot/nft-gallery/issues/3701
image

**Comment by petersopko** [comment]
@kkukelka @vikiival the tests were failing, because in the pipeline instance, somehow it kicked out user out of logged in state before testing the actions on item details. I've solved it by adding one more log in before these tests, temporarily it works and we didn't lose those tests, in the future, obviously more elegant solution will be needed.

**Review by petersopko — APPROVED** [review]
lfg 🚀

**Comment by petersopko** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 62.66 USD/KSM ~ 1.596 $KSM
🧗 [EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW](https://kusama.subscan.io/account/EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)
🔗 [0x9bbbd5ddb6b413113aef8d471e19399d2fd69611ad9a414d063122654b0a5bcc](https://kusama.subscan.io/extrinsic/0x9bbbd5ddb6b413113aef8d471e19399d2fd69611ad9a414d063122654b0a5bcc)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
