### PR TITLE
1245 add poster and description to 3d files in model-viewer

### LINKED ISSUE #1245: Show poster for 3d file
Before we load users 3d file on background, let's show poster before

Test https://nft.kodadot.xyz/rmrk/detail/10164463-FC77C33AB229A2056A-RAWCONCEPT-THE_PORTABLE_EXPO-0000000000000012

# Ref 
- #1244 
- https://modelviewer.dev/docs/index.html#entrydocs-loading-attributes-poster
- https://modelviewer.dev/docs/index.html#entrydocs-loading-attributes-reveal

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇  _ Do a quick check before the merge. 

### PR type
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

https://user-images.githubusercontent.com/17953978/146504501-85c863d1-d338-4f50-8cb4-071ed526cbe3.mov

### Optional
- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything works
- [ ] I found edge cases

### What's new?
- [x] PR closes #1245, #1321
- [x] model-viewer now shows poster while loading 3d file. in addition added description for screen readers  

### Had issue bounty label ?
- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation
- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [ ] My fix has changed **something** on UI, a screenshot for others, is best to understand changes.

### CODE REVIEW

**Comment by yangwao** [comment]
What if we could join it together with https://github.com/kodadot/nft-gallery/issues/1321 👀

**Comment by kkukelka** [comment]
> What if we could join it together with #1321 👀

@yangwao sure thing, ill give it a shot

**Comment by kkukelka** [comment]
> /giphy perfect!

@yangwao bumped to latest version, safari should be fixed. can't do the AR stuff though 😢

**Comment by yangwao** [comment]
Perfect, I’ve sent the payout https://kusama.subscan.io/extrinsic/0x57129d2181ee81d8f82e2643a2b5a857f57f7620942530eb8627310a88a1fe1d

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/

**Pull request merged**
