### PR TITLE
fix(ui): different landing page visual

### LINKED ISSUE #4757: Different landing page visual on firefox
image
this is firefox and imo it looks worse than for example on chrome

is there any way to fix that? 

chrome: 
image

### PR DESCRIPTION
**Pull request by floyd-li**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

i found this issue, it's caused by the svg filter `feGaussianBlur`. it has different behavior in different browsers, here's the chrome/firefox/safari's screenshot and you can easily find the difference.
also provide a codepen for this, you can use different browser to check behavior: https://codepen.io/floyd-li/pen/abaYXGg

image

---

so the solution is, replace these`svg` imgs with `png`.

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4757
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EZiu1PjV2j2JHKxY6mHnFwwCRCoV27uHKQSkKXATSh1srJT&usdamount=0&donation=true)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image
image

### CODE REVIEW

**Comment by exezbcz** [comment]
its looks much more transparent then before, not sure whether we want this tho. Is there any way to fix that? 
after:
image
before:
image

tested in chrome

**Comment by floyd-li** [comment]
thanks for your feedback, seems the svg to png convert goes wrong. i'll update it soon.

> its looks much more transparent then before, not sure whether we want this tho. Is there any way to fix that? after: image before: image
> 
> tested in chrome

**Comment by floyd-li** [comment]
@exezbcz just updat bg imgs, pls check it again :)

**Review by roiLeo — COMMENTED** [review]
What if we keep `svg` and try to use css filter instead?

**Comment by exezbcz** [comment]
@roiLeo yeah, I was thinking the same but cannot find the issue - so basically use the raw shapes and then apply layer blur?

**Comment by exezbcz** [comment]
@floyd-li yup, looks good now!

**Comment by roiLeo** [comment]
> @roiLeo yeah, I was thinking the same but cannot find the issue - so basically use the raw shapes and then apply layer blur?

I think we already mention this in older issue.

IMO we need to rework exported svg from figma.
For example on Nuxt website, there is more or less the same thing in header. 
They manage to export 3 different gradient size depending on screen size:
- [desktop](https://nuxt.com/assets/home/hero-gradient.svg)
- [tablet](https://nuxt.com/assets/home/hero-gradient-tablet.svg)
- [mobile](https://nuxt.com/assets/home/hero-gradient-mobile.svg)

**Comment by floyd-li** [comment]
@exezbcz @roiLeo I tried this before and seems not working well.
here's the codepen based on the `svg`, i just commented the `feGaussianBlur` and use css `filter: blur(185px)` instead, also displayed differently in firefox as the svg does.
seems`blur` effect has different behaviors in different broswers? 🤔️
https://codepen.io/floyd-li/pen/abaYXGg
image

**Comment by exezbcz** [comment]
@floyd-li hmm, weird, so the blur filter rendering is based on browser as well
- so then is the png the only viable option?

**Comment by floyd-li** [comment]
> @floyd-li hmm, weird, so the blur filter rendering is based on browser as well
> 
> * so then is the png the only viable option?

not sure but i think `png` or `webp` img is the low-coast solution currently

**Comment by floyd-li** [comment]
> > @floyd-li hmm, weird, so the blur filter rendering is based on browser as well
> > 
> > * so then is the png the only viable option?
> 
> not sure but i think `png` or `webp` img is the low-coast solution currently

as i tested, if the css `blur` or the svg `stdDeviation` value > 100, firefox will render significantly different with chrome

**Comment by exezbcz** [comment]
@floyd-li so i think we can go with the png approach then 

Thanks for trying tho! 
I will let other devs decide. It works for me 👍

**Review by daiagi — APPROVED** [review]
wfm

**Review by roiLeo — APPROVED** [review]
Hmm.. not really convinced with this solution but let it roll 🎢 

Next we might need to resize (& minimify) the png for better aspec ratio
(and use `b-image` or `nuxt-image` lazy loading)

**Comment by floyd-li** [comment]
> Hmm.. not really convinced with this solution but let it roll 🎢 
> 
> 
> 
> Next we might need to resize (& minimify) the png for better aspec ratio
> 
> (and use `b-image` or `nuxt-image` lazy loading)

yep i'll follow up this and try to find a better solution

**Comment by floyd-li** [comment]
@vikiival @exezbcz is this PR okay to merge?

**Comment by vikiival** [comment]
> @vikiival @exezbcz is this PR okay to merge?

let's see what will mr. design will say

**Comment by exezbcz** [comment]
@vikiival yes, its oki :D

**Pull request merged**
