### PR TITLE
hotfix: broken on mobile

### LINKED ISSUE #3963: ⚠️ search bar on mobile broken
@KngZhi in working on hotfix already👷🏻we've lost our mobile search due to 

- #3894

our search on mobile is broken / doesn't open up. Specifically, Ref for Search.vue in Navbar.vue is pointing to function which is no longer in Search.vue but was refactored into SearchBar.vue (this.

Only thing changed in navbar was the imported file from SearchBar.vue to Search.vue, this isn't enough
`TypeError: this.mobilSearchRef.focusInput is not a function`

### PR DESCRIPTION
**Pull request by KngZhi**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3963 
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer?target=HgpGWWmqrw8t6viwSy6LPcTVr2SuVPKWW5ArdNp2xCJY2U4)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by petersopko** [comment]
known followup for this will be in https://github.com/kodadot/nft-gallery/issues/3882

**Review by roiLeo — APPROVED** [review]
✅ preview

but on mobile I don't see this screen
Capture d’écran 2022-09-15 à 3 01 14 PM

**Comment by petersopko** [comment]
the failing test here for simple mint isn't related to this PR, but rather to the newest `main` development, let's merge this to have functioning search on mobile

image

**Review by petersopko — APPROVED** [review]

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 46.19 USD/KSM ~ 1.082 $KSM
🧗 [HgpGWWmqrw8t6viwSy6LPcTVr2SuVPKWW5ArdNp2xCJY2U4](https://kusama.subscan.io/account/HgpGWWmqrw8t6viwSy6LPcTVr2SuVPKWW5ArdNp2xCJY2U4)
🔗 [0x4d03bb4e51e266a36d8e4de9ef2a28746cc5cc0a8fae95ecb83a34d54f7e0d75](https://kusama.subscan.io/extrinsic/0x4d03bb4e51e266a36d8e4de9ef2a28746cc5cc0a8fae95ecb83a34d54f7e0d75)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
