### PR TITLE
#2378 Make navbar transparent aero effect

### LINKED ISSUE #2378: Make navbar transparent aero effect?
I know this isn't much fit with our design.. but figuring out some pixelized effect on the navbar could be interesting :)

https://user-images.githubusercontent.com/5887929/154329251-49869d14-caff-4ed4-9504-b8831fe98e59.mov

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #2378
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screenshot 2022-02-19 at 9 19 33 PM

### CODE REVIEW

**Comment by yangwao** [comment]
What's about  🥺
- black line under search
- history 
- chain select
- language 
- login

image

**Comment by vikiival** [comment]
Wooow this looks really nice, 
I would keep the buttons a bit darker than the navbar

**Comment by yangwao** [comment]
> Wooow this looks really nice, I would keep the buttons a bit darker than the navbar

how dark, like dark chocolate?

**Comment by prachi00** [comment]
checking these @yangwao @vikiival

**Comment by prachi00** [comment]
@yangwao have fixed the search bar issue and the others.
for the color, should I darken the aero effect?

**Comment by yangwao** [comment]
on point tho. 
@prachi00 let's try :)

**Comment by prachi00** [comment]
@yangwao 
Screenshot 2022-02-23 at 12 25 22 PM
Screenshot 2022-02-23 at 12 28 48 PM

**Comment by prachi00** [comment]
> @yangwao Screenshot 2022-02-23 at 12 25 22 PM Screenshot 2022-02-23 at 12 28 48 PM

Added fixed max width for search

**Review by roiLeo — APPROVED** [review]
lgtm

**Comment by yangwao** [comment]
let's fix conflicts and happy to merge )

**Comment by prachi00** [comment]
@yangwao done

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 123.9 USD/KSM ~ 0.807 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x8e7f6c599098bafeeb6c7a3a2c4f9d213cfaa60e636343f927f63d045f7cba44](https://kusama.subscan.io/extrinsic/0x8e7f6c599098bafeeb6c7a3a2c4f9d213cfaa60e636343f927f63d045f7cba44)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
