### PR TITLE
fix:Truncation in followers/following tab

### LINKED ISSUE #10241: Truncation for long profile names
image

### LINKED ISSUE #10244: Truncation in followers/following tab
image

Truncate the text so its one line

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs Design check

- @exezbcz please review

## Context

- [x] Closes #10244
- [x] Closes #10241 

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by daiagi** [comment]
maybe?

https://tailwindcss.com/docs/text-overflow#truncate

**Comment by Jarsen136** [comment]
> maybe?
> 
> https://tailwindcss.com/docs/text-overflow#truncate

Yup, a shortening class name 
image

**Review by daiagi — APPROVED** [review]

**Comment by prury** [comment]
smaller width that i test is 360px: 
image
if you think is worth fixing it lmk

**Comment by Jarsen136** [comment]
> smaller width that i test is 360px:
> if you think is worth fixing it lmk

✅ Updated

**Review by hassnian — APPROVED** [review]

**Pull request merged**
