### PR TITLE
fix(loader): Loader won't close when you click outside modal on BSX 

### LINKED ISSUE #6766: Loader won't close when you click outside modal on BSX
### What happened?

When trying to mint an NFT, after clicking create, the loader won't close if you click outside the modal.
works normal when trying to create a collection

image

### PR DESCRIPTION
**Pull request by hassnian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

From what I've seen there was no actual logic where it cancelled the transaction on clicking outside the modal it would just close it and then when the state changed it would open it again

- [x] Closes #6766

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; 

### <samp>🤖 Generated by Copilot at f61b00c</samp>

Added the functionality to cancel a token creation transaction in the `CreateToken` component. This involved enhancing the `Loader` component, the `useTransaction` composable, and the `txMixin` mixin to handle the cancellation logic and the user interface.

### <samp>🤖 Generated by Copilot at f61b00c</samp>

> _You can't escape the doom of the token_
> _You can only cancel the creation_
> _But the `Loader` will haunt your dreams_
> _With its `cancel` event and `onCancel` prop_

### CODE REVIEW

**Comment by hassnian** [comment]
@prury 

From what I've seen there was no actual logic where it cancelled the transaction on clicking outside the modal it would just close the loader and then when the state changed it would open it again

https://github.com/kodadot/nft-gallery/assets/44554284/37aa5b69-5cc6-46f9-83df-1d4212c1ef14


Not sure if this is by design or not , if that is the case pls let me know and then it would be as easy as changing this to true
CleanShot 2023-08-20 at 15 28 29@2x 


waiting on feedback

**Review by roiLeo — APPROVED** [review]

**Review by daiagi — APPROVED** [review]

**Comment by prury** [comment]
> @prury
> 
> From what I've seen there was no actual logic where it cancelled the transaction on clicking outside the modal it would just close the loader and then when the state changed it would open it again
> CleanShot.2023-08-20.at.15.34.16.mp4
> 
> Not sure if this is by design or not , if that is the case pls let me know and then it would be as easy as changing this to true
> 
> CleanShot 2023-08-20 at 15 28 29@2x

hmmm, let's leave the way it is, since its work it works on the other chains, if the user wants to cancel the transaction completely it will just deny the wallet signing, ty!

**Comment by vikiival** [comment]
Hey we already asked you not to force push the code. Please open a new PR.

Screenshot 2023-08-21 at 17 10 06

**Comment by hassnian** [comment]
> Hey we already asked you not to force push the code. Please open a new PR.

First time getting this warning ,didn't know,  wont do again , will open new PR

**Pull request closed without merging**
