### PR TITLE
feat: release redesign sidebar menu

### LINKED ISSUE #5820: Profile sidebar simplifications // Smart & Simple Assets
image

### Design
- in handoff main file, page profile simplifications: https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?node-id=145%3A4743&t=okpSSqS7Bxdgbqik-1

# Basics
- we will merge wallet sidebar and profile dropdown together
- after connecting, there will be only icon of your account
- after you connect, you can click on the icon - sidebar will open
- preconnect and after connect states will stay the same on mobile/desktop

### Desktop
- on desktop, you will have two button in the navbar, one being connect button, the other profile
- profile will keep its hover state - you can hover over to change language and dark mode
- connect button will open wallet connect

### Mobile
- options in burger menu staying the same 
image
- once you click connect, wallet sidebar is opened

### Desktop
- connect button disappears, only profile icon is visible with your account icon

### Mobile 
- this section changes to: 
   - profile from account and wallet
   - light mode button is not there
image
- once you click account, top part remains the same, only the content changes - sidebar into mobile view 
image

## Sidebar 
- it's fairly similar to the wallet sidebar 
- top part saying its profile with cross close button
image

### account part
(from left to right)
  - icon, without drop shadow this time
  - name on top, profile view underneath (name is address, or onchain id when possible)
  - copy and quit button - copy will result in tooltip saying - address added to clipboard (or something we already have) Quit button wont close the sidebar but will take you to wallet connect sidebar (this way we don't have to have a change account button) 
    - If i found out its its bad, we can change it in future 
  - button has a hover effect, see component in figma please
  
### Recent NFTs
- this serves as an small overview of the account, quick hint what nfts the wallet has. 
- there is room for 3 nfts, if user does not have any -> this section is not displayed and also heading recent nfts is removed 

### Assets
image

- basically a old wallet sidebar
- but we have to improve it so its displaying the correct data 
- network is added
- we dont have multichain yet in smart assets view
- #4865 
- portfolio view redirects to current assets page - it will be soon redesigned as well 
- add funds works like credit button now - ramp network

### Links 
image

- the hover is only on the text itself - changing to its hover color (k-hovergrey in light mode, shade in dark mode) 
- the links will take you to other subpages 

### Bottom part
image
- dark mode, once you click it will change to dark mode and the text to light mode
- language - when you click, dropdown is displayed with all the language options 
image
- settings will take you to current settings page 
- hover on these things is following the design - k-grey to k-black in light mode, k-grey to k-white in darkmode 

### Other
- there is also screen with a small line/dialog saying create onchain identity
image
- It would be useful to notify users who do not already have a onchain identity.
- is it possible to show it to user few times, if they dont close it manually. If they do, remember to not show it again? Clicking outside the "close" area will take you to the onchain identity page

As always, if you have any questions, please ask 🚀 
Thanks!

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Needs Design check
- @exezbcz please review

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #5820

#### Did your issue had any of the "$" label on it?

- [ ] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>)

## Screenshot 📸

- [ ] My fix has changed UI

### <samp>🤖 Generated by Copilot at 5060e79</samp>

This pull request refactors and simplifies the layout and logic of the navbar and the connect wallet components. It removes unused code, improves internationalization, and enhances type safety. It also deletes the `MobileNavbarProfile.vue` file and moves its functionality to the `Navbar.vue` component.

### <samp>🤖 Generated by Copilot at 5060e79</samp>

> _We're simplifying the code, me hearties, yo ho ho_
> _We're removing what we don't need, and making it all flow_
> _On the count of three, we'll pull and push, and test it all again_
> _We're simplifying the code, me hearties, for the `WalletAsset` and the `Navbar`_

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
✅ code lgtm

**Comment by yangwao** [comment]
looks really great at me! 

cc @exezbcz 

image

**Comment by prury** [comment]
@preschian found something on the language button: 
- when clicked its not triggering the language change on the website
- if you click on another language, the language menu stays open instead of disappearing(diff from beta)

**Comment by exezbcz** [comment]
lets solve the issue and we are done!

**Comment by preschian** [comment]
> @preschian found something on the language button:
> 
> * when clicked its not triggering the language change on the website
> * if you click on another language, the language menu stays open instead of disappearing(diff from beta)

updated cc @prury @exezbcz

**Pull request merged**
