### PR TITLE
#4161 fixes with drawer, colors // connect wallet on mobile

### LINKED ISSUE #4161: Connect wallet on mobile
seems the mobile version needs tune 🥹

image

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #4161
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screen Shot 2022-10-21 at 7 01 13 PM

### CODE REVIEW

**Review by Jarsen136 — APPROVED** [review]
code lgtm

**Comment by prachi00** [comment]
Also, whooever is doing the payout for this one, please don't, payout was done twice on #4131 and it would be cool to adjust it here 
@yangwao

**Review by roiLeo — COMMENTED** [review]
Capture d’écran 2022-10-24 à 8 27 16 AM

There are still some issues with wallet, if you would like to take a look ref #4144

**Review by roiLeo — COMMENTED** [review]
maybe wrong background?
Capture d’écran 2022-10-24 à 8 36 00 AM

Please could you update description as I don't really know what's changing here

**Comment by yangwao** [comment]
with lot of accounts on iphone 12 pro does this 

image

**Comment by prachi00** [comment]
> Few adjustments.
> 
> ### Visual:
> * popup doesn't have a stroke.
> * hover effect on each wallet should be different, not k-accent but in light mode: k-accentlight2 and in darkmode k-accentlight2dark, both are in landing page handoff - first page - colors
> * "connect wallet" section should have the same height as the wallet selection (polkadot.js etc.)
> 
> ### Functional:
> * by default, it should feature other wallet options, like in the Figma
>   image

I'll add these in #4144

**Pull request merged**
