### PR TITLE
Go back to main menu after selecting chain

### LINKED ISSUE #7883: Go back to main menu after selecting chain
When selecting chain on mobile version and then going back to menu you are still in the "chain selection". would be good if you would automatically be returned to main menu not again chain selection.

Video:

https://github.com/kodadot/nft-gallery/assets/104380776/b3df9fe6-43df-4b25-adff-d7b54b6885e5

Also not sure if this is the same issue but other menu options (notifications, cart..) are acting sus too:
https://github.com/kodadot/nft-gallery/assets/104380776/b63ffdf3-d191-4749-b1ab-4d7079b2a85c

### PR DESCRIPTION
**Pull request by shengxinjing**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #7883 
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [ ] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>)

### <samp>🤖 Generated by Copilot at ca99f20</samp>

Improved mobile navigation by closing the expandable section on page change. Added a `route` constant and a `watch` function to `MobileExpandableSection.vue`.

### <samp>🤖 Generated by Copilot at ca99f20</samp>

> _`Route` to the dark abyss_
> _`Watch` for the demons' kiss_
> _Close the gate of mobile hell_
> _Escape the expandable spell_

### CODE REVIEW

**Comment by daiagi** [comment]
too "side-effecty"

I would like to see a more direct solution where `NavbarChainOptions` emits an event that closes `MobileExpandableSection`

**Review by daiagi — CHANGES_REQUESTED** [review]
see commnet

**Comment by shengxinjing** [comment]
> too "side-effecty"
> 
> I would like to see a more direct solution where `NavbarChainOptions` emits(发出) an event that closes `MobileExpandableSection`

I got it, I just think it's too redundant to use event, and have switched to implementing it with emit

**Review by daiagi — APPROVED** [review]
tbh I am not quite sure how it works 
@shengxinjing  could you explain it to me, please
specifically the v-slot part

**Comment by shengxinjing** [comment]
> tbh I am not quite sure how it works @shengxinjing could you explain it to me, please specifically(专门) the v-slot part

Hello, the event propagation here is a bit complex. It requires passing an operation from the slot component NavbarExploreOptions to the parent component MobileExpandableSection in order to trigger the close method.

Firstly, a new event called "closeMobileSubMenu" needs to be added to NavbarExploreOptions. This event will trigger the "@closeMobileSubMenu" event. Using v-slot as a bridge, the onCloseMobileSubMenu function can be passed to closeMobileSubMenu.

The event within v-slot will trigger the function "@closeMobileSubMenu" on the slot component within the parent component.

It's a bit convoluted, and I apologize if my explanation isn't clear. If there are any similar issues involving Vue internals, you can assign them to me for further investigation.

**Comment by shengxinjing** [comment]
my english is not very good, you can see the document
https://vuejs.org/guide/components/slots.html#scoped-slots

**Comment by yangwao** [comment]
thanks @shengxinjing !

**Pull request merged**
