### PR TITLE
:sparkles: active state to `NeoDropdown`

### LINKED ISSUE #4603: Redesign Active states of button
> > is this final versions or you'll still be working on it?
> > on thing is missing: image
> > 
> > * active states, when you click on the button and the dropdown popups, the button should change itself to active state
> 
> active state of buttons seems to be still missing

@exezbcz @yangwao I am not sure how to give that yet, found nothing here https://oruga.io/components/dropdown.html
can we make a separate issue for this one?

_Originally posted by @prachi00 in https://github.com/kodadot/nft-gallery/issues/4582#issuecomment-1370242284_

### PR DESCRIPTION
**Pull request by petersopko**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #4603 
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

https://user-images.githubusercontent.com/73316633/210859536-8912dfef-5914-4270-b603-de5cac22350a.mp4

### CODE REVIEW

**Comment by petersopko** [comment]
some context:

- oruga buttons don't have active states, ref https://oruga.io/components/button.html
- oruga dropdowns emit active-change events, ref https://oruga.io/components/dropdown.html (also have states, but related only to dropdown menu, button is separate)
- if we want to have `NeoDropdowns` which support active state, we'll have to merge o-button and o-dropdown, I'm not sure how many of those are we going to need and whether it is necessary
- maybe we can have `NeoDropdownActive` which supports this -> I can make it in this PR if that's what we want
- I've moved CSS to separate file, it was getting quite long
- some leftover CSS was removed

maybe I missed something, or I'm just wrong and there are better ways to do this, if so, please let me know and I'll adjust.

**Comment by petersopko** [comment]
> 2. add additional classes on `NeoDropdown` when active. with this, the changes only on `NeoDropdown`. this one simpler
> 
> ```
> <template>
>   <o-dropdown
>     aria-role="list"
>     :position="position"
>     :append-to-body="appendToBody"
>     class="neo-dropdown"
>     :class="{ 'o-drop-active': isActive }"
>     @active-change="isActive = $event">
>     <template #trigger>
>       <slot />
>     </template>
>     <slot name="items" />
>   </o-dropdown>
> </template>
> 
> <script lang="ts" setup>
> import { ODropdown } from '@oruga-ui/oruga'
> 
> // ...
> 
> const isActive = ref(false)
> </script>
> 
> <style lang="scss">
> // ...
> 
> // example, override is-neo in here
> .o-drop-active {
>   .is-neo,
>   .is-neo:hover {
>     background-color: black;
>     color: white;
>   }
> }
> </style>
> ```

Well, I've learned something new today 😆 went with the second option; let's see what @roiLeo will have to say

**Comment by roiLeo** [comment]
> 2. add additional classes on `NeoDropdown` when active. with this, the changes only on `NeoDropdown`. this one simpler

I'm fine with this solution as long as we don't change when dropdown is used without button (check NeoDropdown story)

it's still strange that we don't have `active` state for button while using bulma theme, might be good to open an issue on oruga repo.

**Review by roiLeo — APPROVED** [review]
✅ code lgtm

**Comment by yangwao** [comment]
> it's still strange that we don't have `active` state for button while using bulma theme, might be good to open an issue on oruga repo.

yes please

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 24.41 USD/KSM ~ 1.229 $KSM
🧗 [FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y](https://kusama.subscan.io/account/FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y)
🔗 [0xadfb4fa179ddc3bb3f93533818e123747b054855b10bcf93312f9c29d18c97a0](https://kusama.subscan.io/extrinsic/0xadfb4fa179ddc3bb3f93533818e123747b054855b10bcf93312f9c29d18c97a0)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by exezbcz** [comment]
image
the connect button has now dropshadow, that is the only issue i have with it :D

**Comment by petersopko** [comment]
> the connect button has now dropshadow, that is the only issue i have with it :D

added again here, sorry
- #4624

**Pull request merged**
