### PR TITLE
fix: Zero balance on transfer when address has DOTs

### LINKED ISSUE #7674: Zero balance on transfer when address has DOTs
I go to https://canary.kodadot.xyz/dot/transfer
this is what i see 
address is 15aAxjcipFTFiyibgzT5rwS7JDfGFPRHWdRDHkdyUtDRJhyb

image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix

  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #7674
  - [ ] Requires deployment <snek/rubick/worker>

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

image

  ## Copilot Summary
  
### <samp>🤖 Generated by Copilot at efb061f</samp>

Added identity and balance management to `Transfer.vue` component. The component now uses `useIdentityStore` to access and update the user's identity and balance on different networks and accounts.

  
### <samp>🤖 Generated by Copilot at efb061f</samp>

> _`useIdentityStore`_
> _Manages user balance_
> _On KodaDot platform_

### CODE REVIEW

**Comment by prury** [comment]
do they load? yes
Assethubs are taking a bit longer than the others
Basilisk shows RPC error, probably on their end since its not the first time i see this problem
if you switch currencies a few times you get the CORS coingecko error (I'm aware its unrelated), and either the balance won't load or the currency price won't load

**Comment by Jarsen136** [comment]
This PR is mainly solving the issue that the balance would not show when We visit the transfer page directly through URL, without expanding the sidebar.


>  Basilisk shows RPC error, probably on their end since its not the first time i see this problem 

related with  https://github.com/kodadot/nft-gallery/issues/7670


> if you switch currencies a few times you get the CORS coingecko error (I'm aware its unrelated), and either the balance won't load or the currency price won't load

related with https://github.com/kodadot/nft-gallery/issues/7675

**Comment by prury** [comment]
> This PR is mainly solving the issue that the balance would not show when We visit the transfer page directly through URL, without expanding the sidebar.
> 
> > Basilisk shows RPC error, probably on their end since its not the first time i see this problem
> 
> related with #7670
> 
> > if you switch currencies a few times you get the CORS coingecko error (I'm aware its unrelated), and either the balance won't load or the currency price won't load
> 
> related with #7675

yeah i know i know, thanks for linking the issues! 

AssetHubs are taking +- 30 seconds to show balance initially, different from the other chains that take +- 5 seconds

**Comment by Jarsen136** [comment]
> 
> AssetHubs are taking +- 30 seconds to show balance initially, different from the other chains that take +- 5 seconds

The speed of fetching the balance depends on the RPC call. It only needs a few seconds to load on my side.

Kapture 2023-10-17 at 00 56 03

**Comment by yangwao** [comment]
thanks ! 

pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 3.73 USD/DOT ~ 5.362 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x631c94ddf5a2745b1a04c54b63c5e18167e61aeb7c298c96008a48700487b816](https://polkadot.subscan.io/extrinsic/0x631c94ddf5a2745b1a04c54b63c5e18167e61aeb7c298c96008a48700487b816)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
