### PR TITLE
fix: check serviceWorker in navigator

### LINKED ISSUE #4827: kodadot.xyz not loading in nova wallet
### What happened?

When trying to open kodadot.xyz in Nova Wallet DApp browser it is not loading. Error from the dev console is attached.

image_2023-01-25_14-14-19

### Please reproduce in steps

1) Open Nova Wallet app
2) Go to Browser tab
3) Put "kodadot" into the search field
4) Tap on found KodaDot option
5) Browser is opened but nothing loads

### Expected Behavior

DApp browser for KodaDot is loaded and wallet account is requested

### What browsers are you seeing the problem on?

Mobile iOS Safari (WebKit)

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

No

### Which wallet you are using?

Nova Wallet

### At which chain did you encounter bug?

Basilisk, MoonSama, RMRK

### Screenshots

https://user-images.githubusercontent.com/570634/214567060-eef8921d-4aa2-4b9e-81c9-15589d97de1d.MP4

### Relevant log output

_No response_

### Payment link for reward

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4827. check serviceWorker in navigator first, like the docs mentioned https://developer.chrome.com/docs/workbox/modules/workbox-window/#loading-workbox-with-javascript-bundlers

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
I don't have iOS to test this one
✅ code lgtm

**Comment by vikiival** [comment]
Tested on iOS

IMG_8815

IMG_8816

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 36.54 USD/KSM ~ 0.821 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0x77d62a80d9050a3ec6f497f11e783354cebd6570f6ce54725895ce7b3434598b](https://kusama.subscan.io/extrinsic/0x77d62a80d9050a3ec6f497f11e783354cebd6570f6ce54725895ce7b3434598b)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
