### PR TITLE
chore: introduce no-follow links

### LINKED ISSUE #6285: Introduce no-follow on links
We should introduce no-follow on links to 
- items at
  - landing
  - collection
  - explorer
  - profile
- profiles

Ref
---
- #6283

### PR DESCRIPTION
**Pull request by abhisheknaiidu**
fixes #6285

### CODE REVIEW

**Comment by abhisheknaiidu** [comment]
@Jarsen136 whatever you mentioned in the last PR,  i've fixed in this PR.

**Review by Jarsen136 — APPROVED** [review]

**Review by roiLeo — APPROVED** [review]

**Comment by vikiival** [comment]
pay 15 usd

**Comment by vikiival** [comment]
Thanks for the contribution ^-^ ❤️

**Comment by abhisheknaiidu** [comment]
@vikiival one ques - how will I get the 15 USD

**Comment by abhisheknaiidu** [comment]
my polkadot address - 5DPRwfHKU7vKFWoW7HvK2xeVCTqGsK1j1hM2PWQVSB9fDh64
@vikiival

**Comment by vikiival** [comment]
pay 15 usd

**Comment by vikiival** [comment]
Please follow a standard PR template, otherwise I am not able to pay

**Pull request merged**
