### PR TITLE
fix: When gifting out NFT, raw popup shows

### LINKED ISSUE #3593: When gifting out NFT, raw popup shows
### What happened?

Went out to our nft gallery on rmrk to send out nft

### Please reproduce in steps

/

### Expected Behavior

For it to look normal

### What browsers are you seeing the problem on?

Firefox

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

_No response_

### Which wallet you are using?

PolkadotJS

### At which chain did you encounter bug?

RMRK

### Screenshots

image

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3593
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

RMRK:  
image

Now it shows the same text as on what's on the other chain.

### CODE REVIEW

**Review by vikiival — APPROVED** [review]

**Review by petersopko — APPROVED** [review]
weirdly, I couldn't reproduce the raw popup on beta.kodadot.xyz, but deployed version here works as well 😆

**Comment by Jarsen136** [comment]
> weirdly, I couldn't reproduce the raw popup on beta.kodadot.xyz

That's so weird : )  😄

**Comment by Jarsen136** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 63.85 USD/KSM ~ 0.783 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xbf46ef8b420abc4e28b880e8723a665605951ef920572e3e84de2dbfcb21b4ac](https://kusama.subscan.io/extrinsic/0xbf46ef8b420abc4e28b880e8723a665605951ef920572e3e84de2dbfcb21b4ac)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
