### PR TITLE
fix: show trending collections on Rmrk2 chain when focusing on search bar.

### LINKED ISSUE #5486: No trending collection on focus on search bar
image
- when you focus on search bar on rmrk2 there is no trending dropdown as is on other chains: 

image

### PR DESCRIPTION
**Pull request by zhyd1997**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5486
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [x] I've tested it at </bsx/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=H2DifyJqaansQREdGFU4BxZyaApbkCgP1a9Pq4xKaebSFZh)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screenshot 2023-04-15 at 23 49 22

### CODE REVIEW

**Comment by zhyd1997** [comment]
Hi team, do we need to enable t**rending collections** show on _beta_ chains?

**Comment by zhyd1997** [comment]
the collections returns empty:

Screenshot 2023-04-16 at 01 24 24
Screenshot 2023-04-16 at 01 25 00


**but** the indexer is correct:

https://github.com/kodadot/nft-gallery/blob/d743caa96ab4dc646a937d6f2652599f497051aa/libs/static/src/indexers.ts#L12

https://github.com/kodadot/packages/blob/5d353c91243f4ebd835e239b133c0cd9a8575b04/vuex-options/src/defaults/indexers.ts#L12-L16

the same to https://github.com/kodadot/nft-gallery/issues/5343.

ref: https://github.com/kodadot/nft-gallery/issues/5493.

**Review by roiLeo — CHANGES_REQUESTED** [review]
`series` resolver is not fully implemented on rmrkv2 (kodadot/rubick#253)

(we might want to add `snek` prefix in `supportedChains`)

**Comment by yangwao** [comment]
@zhyd1997 if you want to help fix `series` resolver, you are more than welcome to tackle this, till seems doesn't work putting this into draft 

image

**Comment by vikiival** [comment]
Hey,
this issue has been opened for more than two months:

The fix needs to be tackled here: https://github.com/kodadot/rubick/issues/199
I would kindly ask you to take different issue to hack upon ^-^.

**Pull request closed without merging**
