### PR TITLE
fix: Can we fix this blog post

### LINKED ISSUE #9050: Can we fix this blog post
https://kodadot.xyz/blog/kodadot's-drop-page-explained
this either doesn't work - https://kodadot.xyz/blog/kodadot%27s-drop-page-explained

probably we should avoid special characters in title please

image

it's ranking high and we probably loosing on that some clicks

image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix

  ## Context

  - [x] Closes #9050

https://deploy-preview-9061--koda-canary.netlify.app/blog/kodadots-drop-page-explained

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Copilot Summary
  copilot:summary

  copilot:poem

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]

**Comment by yangwao** [comment]
can we have plus one more redirect to catch that old links 
- `/blog/kodadot's-drop-page-explained` ? 🙏
maybe this one too 
- `blog/kodadot%27s-drop-page-explained`

**Comment by Jarsen136** [comment]
> can we have plus one more redirect to catch that old links
> 
> * `/blog/kodadot's-drop-page-explained` ? 🙏
>   maybe this one too
> * `/blog/kodadot%27s-drop-page-explained`

It's a good idea. I have updated it so we can visit these URLs too.

https://deploy-preview-9061--koda-canary.netlify.app/blog/kodadot's-drop-page-explained
https://deploy-preview-9061--koda-canary.netlify.app/blog/kodadot%27s-drop-page-explained

**Comment by yangwao** [comment]
thanks!
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 6.66 USD/DOT ~ 3.003 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0xad760fea02df563d259c55b56da0f610a530b69c91779e37a7ef179f43980971](https://polkadot.subscan.io/extrinsic/0xad760fea02df563d259c55b56da0f610a530b69c91779e37a7ef179f43980971)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
