### PR TITLE
fix: Collection and Identity popover wrong data

### LINKED ISSUE #9164: Highest sale in collection - hover card
how is that highest sale? 

https://github.com/kodadot/nft-gallery/assets/90852205/d3e84260-b173-412f-aa68-a3b7b1000e29

- it should show highest sales, not highest lists

### LINKED ISSUE #9173: User identity popover wrong "sold" nfts data
### What happened?

`1bK46fKX7bcHp9WNZVijekhpgFRt9Zw13hMQCWSWpfVsgZm` sold `/ahp/gallery/77-4` for 4 DOT yet popover shows 0

CleanShot 2024-01-29 at 09 36 25@2x

and `1yHddTK4XihjK2DJE8g3oKV5d51TKPmnaCdYgPPTWqm6Ed4` 

CleanShot 2024-01-29 at 09 46 43@2x

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #9164  
- [x] Fixes: Identity popover wrong Highest Sales nfts
- [x] Closes #9173
- [x] Removed unused `useLastBought` composable and `buyEventByProfile` query (triggered when hovering over idenitity popover)

## Needs Design check

- @exezbcz please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

## Collection popover

CleanShot 2024-01-29 at 14 50 09@2x

CleanShot 2024-01-29 at 14 50 48@2x

## Identity popover 

CleanShot 2024-01-29 at 14 51 22@2x

CleanShot 2024-01-29 at 14 52 28@2x

### CODE REVIEW

**Comment by prury** [comment]
i think numbers are not showing anymore on RMRK2
high sales NFTs work properly, but not the numbers

image

**Comment by hassnian** [comment]
> i think numbers are not showing anymore on RMRK2 high sales NFTs work properly, but not the numbers
> 
> image
> 
> https://deploy-preview-9175--koda-canary.netlify.app/ksm/u/FSMdmCLv5gFZ87YerB3M8ZSQ58BGHdSnreC4J6znWpqPQK9?tab=activity&buy=false&sale=true

@roiLeo   this query is not working on `RMRK2` , indexer issue ?

``````

  sold: nftEntitiesConnection(
    orderBy: blockNumber_DESC
    where: {
      burned_eq: false
      events_some: {
        interaction_eq: BUY
        currentOwner_eq: $account
        caller_not_eq: $account
      }
    }
  ) {
    totalCount
  }
``````


CleanShot 2024-01-30 at 15 14 09@2x

``````

{
  "errors": [
    {
      "message": "canceling statement due to statement timeout",
      "locations": [
        {
          "line": 25,
          "column": 3
        }
      ],
      "path": [
        "sold"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "query": "SELECT count(*) FROM (SELECT true FROM \"nft_entity\" AS \"nft_entity\" WHERE \"nft_entity\".\"burned\" = $1 AND (SELECT true FROM \"event\" AS \"event\" WHERE \"event\".\"caller\" != $2 AND \"event\".\"current_owner\" = $3 AND \"event\".\"interaction\" = $4 AND \"event\".\"nft_id\" = \"nft_entity\".\"id\" LIMIT 1) ORDER BY \"nft_entity\".\"block_number\" DESC LIMIT 101) AS rows",
          "parameters": [
            false,
            "FSMdmCLv5gFZ87YerB3M8ZSQ58BGHdSnreC4J6znWpqPQK9",
            "FSMdmCLv5gFZ87YerB3M8ZSQ58BGHdSnreC4J6znWpqPQK9",
            "BUY"
          ],
          "driverError": {
            "length": 109,
            "name": "error",
            "severity": "ERROR",
            "code": "57014",
            "file": "postgres.c",
            "line": "3312",
            "routine": "ProcessInterrupts"
          },
          "length": 109,
          "severity": "ERROR",
          "code": "57014",
          "file": "postgres.c",
          "line": "3312",
          "routine": "ProcessInterrupts",
          "sql": "SELECT count(*) FROM (SELECT true FROM \"nft_entity\" AS \"nft_entity\" WHERE \"nft_entity\".\"burned\" = $1 AND (SELECT true FROM \"event\" AS \"event\" WHERE \"event\".\"caller\" != $2 AND \"event\".\"current_owner\" = $3 AND \"event\".\"interaction\" = $4 AND \"event\".\"nft_id\" = \"nft_entity\".\"id\" LIMIT 1) ORDER BY \"nft_entity\".\"block_number\" DESC LIMIT 101) AS rows",
          "stacktrace": [
            "QueryFailedError: canceling statement due to statement timeout",
            "    at PostgresQueryRunner.query (/squid/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
            "    at async DataSource.query (/squid/node_modules/typeorm/data-source/DataSource.js:341:20)",
            "    at async EMDatabase.query (/squid/node_modules/@subsquid/graphql-server/lib/typeorm.js:12:23)",
            "    at async TypeormOpenreaderContext.executeQuery (/squid/node_modules/@subsquid/graphql-server/lib/typeorm.js:41:22)",
            "    at async resolve (/squid/node_modules/@subsquid/openreader/lib/opencrud/schema.js:483:30)"
          ]
        }
      }
    }
  ],
  "data": null
}
``````

**Comment by roiLeo** [comment]
> @roiLeo this query fails on `RMRK2` , indexer issue ?

could be, but I don't see limit in your query and this can be potentially dangerous

**Comment by hassnian** [comment]
> > @roiLeo this query fails on `RMRK2` , indexer issue ?
> 
> could be, but I don't see limit in your query and this can be potentially dangerous
> 
> would you mind sharing the query with params?

`````

query {
  nftEntitiesConnection(
    orderBy: blockNumber_DESC
    where: {
      burned_eq: false
      events_some: {
       	interaction_eq: BUY
      	currentOwner_eq: "FSMdmCLv5gFZ87YerB3M8ZSQ58BGHdSnreC4J6znWpqPQK9"
       	caller_not_eq: "FSMdmCLv5gFZ87YerB3M8ZSQ58BGHdSnreC4J6znWpqPQK9"
    }
  }
  ) {
    totalCount
  }
}


`````

**Comment by roiLeo** [comment]
timeout means that query take to long to proceed

there's a good chance it's coming from `event_some`, maybe it's missing some primary key on indexer

**Comment by hassnian** [comment]
> timeout means that query take to long to proceed
> 
> there's a good chance it's coming from `event_some`, maybe it's missing some primary key on indexer

hmm should we keep that and create new issue for the indexer bug ? or we can do this 

`````

  eventsConnection(
    orderBy: blockNumber_ASC
    where: {
      nft: {burned_eq: false},
      interaction_eq: BUY
      currentOwner_eq: "FSMdmCLv5gFZ87YerB3M8ZSQ58BGHdSnreC4J6znWpqPQK9"
      caller_not_eq: "FSMdmCLv5gFZ87YerB3M8ZSQ58BGHdSnreC4J6znWpqPQK9"
  }) {
    totalCount
  }


`````

which works fine  , but is not really the same since we want **sold nfts** there could be multiple buy events from each nft , if the user bought it back and then another BUY interaction was made 

CleanShot 2024-01-30 at 16 39 37@2x

**Comment by roiLeo** [comment]
> hmm should we keep that and create new issue for the indexer issue ? or we can do this

https://github.com/kodadot/loligo/issues

note that it won't be that easy to deploy an update
 
> ```
> 
>   eventsConnection(
>     orderBy: blockNumber_ASC
>     where: {
>       nft: {burned_eq: false},
>       interaction_eq: BUY
>       currentOwner_eq: "FSMdmCLv5gFZ87YerB3M8ZSQ58BGHdSnreC4J6znWpqPQK9"
>       caller_not_eq: "FSMdmCLv5gFZ87YerB3M8ZSQ58BGHdSnreC4J6znWpqPQK9"
>   }) {
>     totalCount
>   }
> ```
> 
> which works fine , but is not really the same since we want **sold nfts count** there could be multiple buy events from each nft , if the user bought it back and then another BUY interaction was made

this looks like a specific hack and may introduce more bugs

**Review by preschian — COMMENTED** [review]
blocked by this? https://github.com/kodadot/loligo/issues/58

lets re-review once ready. maybe set it as draft PR?

**Comment by hassnian** [comment]
> blocked by this? [kodadot/loligo#58](https://github.com/kodadot/loligo/issues/58)
> 

yep 

> lets re-review once ready. maybe set it as draft PR?

done

**Comment by yangwao** [comment]
Stale, please reopen if there is intent to finish it or blocker was removed

**Comment by vikiival** [comment]
@hassnian on which indexer does it appear?

**Comment by hassnian** [comment]
> Wrong repo :) 

oh mb, https://ksm.gql.api.kodadot.xyz/ it should be [rubick](https://github.com/kodadot/rubick), right ?

**Pull request closed without merging**
