### PR TITLE
fix: rearrange smart portfolio view

### LINKED ISSUE #6222: rearrange smart portfolio view
- I would remove zero balance rows 
image
- I am considering making the text 16px except for the column names - Would it fit? 
- rearrange the order to: network(chain), token, amount, USD

after #6177

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Needs Design check

- @exezbcz please review

## Context

- [x] Closes #6222
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed UI

image

### <samp>🤖 Generated by Copilot at 68196f3</samp>

Improved the UI and code quality of the balance table component. Used the `ChainToken` type from the `identity` store module in `MultipleBalances.vue` and exported it for reuse.

### <samp>🤖 Generated by Copilot at 68196f3</samp>

> _`ChainToken` shared_
> _Balance table refined_
> _Autumn of clean code_

### CODE REVIEW

**Comment by preschian** [comment]
@exezbcz wondering, how about empty states? in case the user doesnt have balance in any chains yet

image

**Comment by yangwao** [comment]
> how about empty states?

let's put there placeholder text

"You've got zero balance on this address across chains we are monitoring. If you want to buy small amount of crypto, click on **Add funds** through our verified on-ramp partner."

**Comment by exezbcz** [comment]
Hey hey, I think we can tweek the spacing of the columns a bit
image

statemine is the longest word now, I think we can move the token column closer to that
image


- it would be also nice to have all the items aligned in the column

"You've got zero balance on this address across chains we are monitoring. If you want to buy small amount of crypto, click on Add funds through our verified on-ramp partner."
- its pretty long, but I guess good for now, I will come up with something shorter

**Comment by Jarsen136** [comment]
> Hey hey, I think we can tweek the spacing of the columns a bit image
> 
> statemine is the longest word now, I think we can move the token column closer to that image
> 
> * it would be also nice to have all the items aligned in the column
> 

It should be fixed now.

**Comment by yangwao** [comment]
pay 30 usd

**Pull request merged**
