### PR TITLE
fix/hover black text

### LINKED ISSUE #3836: Black text on black overlay on hover at gallery explorer
I thought this was already fixed 🥹

https://beta.kodadot.xyz/rmrk/explore?tab=GALLERY&page=1

image

### PR DESCRIPTION
**Pull request by KngZhi**
- fix: black text hover issue on gallery

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3836
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer?target=DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

from netlify

image

### CODE REVIEW

**Review by Jarsen136 — APPROVED** [review]
LGTM

**Comment by Jarsen136** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 48.92 USD/KSM ~ 0.409 $KSM
🧗 [DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc](https://kusama.subscan.io/account/DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc)
🔗 [0x2a77a4b427e84b74f4767c0b01247e6e96f623f5dc5e04f901232f00c39be532](https://kusama.subscan.io/extrinsic/0x2a77a4b427e84b74f4767c0b01247e6e96f623f5dc5e04f901232f00c39be532)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Review by roiLeo — COMMENTED** [review]
or just use `has-text-white` near `has-text-overflow-ellipsis`

**Comment by KngZhi** [comment]
> or just use `has-text-white` near `has-text-overflow-ellipsis`

👌

**Review by roiLeo — APPROVED** [review]
👌

**Pull request merged**
