### PR TITLE
fix: Mobile footer content

### LINKED ISSUE #5274: Mobile footer content
I may have break something in #5089 
Footer flex direction?
Capture d’écran 2023-03-15 à 9 13 48 AM

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5274
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

image

### CODE REVIEW

**Comment by exezbcz** [comment]
image
bit of collapsing content from 1120px till 770px

otherwise oki,
thank you!

**Comment by Jarsen136** [comment]
> bit of collapsing content from 1120px till 770px

✅ Fixed
image

**Review by daiagi — APPROVED** [review]

**Review by roiLeo — APPROVED** [review]

**Comment by vikiival** [comment]
Please check the failing workflow

**Comment by vikiival** [comment]
image


Cc @exezbcz wdyt

**Comment by roiLeo** [comment]
> image

😄

**Comment by Jarsen136** [comment]
> Please check the failing workflow

Let me re-run the workflow

**Comment by vikiival** [comment]
> 😄 

Thank you for cute image ❤️ :3
I was playing with 🍏 ✏️  😅 


But What I wanted to say wouln't it be better to have it on two rows?

**Comment by vikiival** [comment]
pay 10 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $10 @ 33.5 USD/KSM ~ 0.299 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xb23a6f48430f129fe9e04e2fc32fc9cc87c3d46217aed2a0b714728c87b5b227](https://kusama.subscan.io/extrinsic/0xb23a6f48430f129fe9e04e2fc32fc9cc87c3d46217aed2a0b714728c87b5b227)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by exezbcz** [comment]
@vikiival letsgo,
yup, possible

**Pull request merged**
