### PR TITLE
Sync rest pages

### LINKED ISSUE #1154: Keep shortest url possible, lets remove 'en'
For sharing and the rest of the stuff, we need to keep the URL shortest as possible.
Let's make EN default 

image

### PR DESCRIPTION
**Pull request by dezine2dev**
**Thank you for your contribution** to the KodaDot NFT gallery.

👇 Do a quick check before the merge. 

### PR type
- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main-nuxt** and I've no conflicts
- [ ] I've tried respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted screenshot of demonstrated change in this PR

### What's new?
- [x] PR closes #1154, #1189
- [x] Sync up with main, more fixes

### CODE REVIEW

**Review by roiLeo — CHANGES_REQUESTED** [review]
- could you change '/rmrk/collection' route to '/rmrk/collections' as it will be showing collection list 
- 'component/landing/Landing' could be move to 'pages/index'

**Comment by dezine2dev** [comment]
> * could you change '/rmrk/collection' route to '/rmrk/collections' as it will be showing a list of collections
> * 'component/landing/Landing' could be move to 'pages/index'

Pushed new commits for these

**Comment by yangwao** [comment]
> * could you change '/rmrk/collection' route to '/rmrk/collections' as it will be showing a list of collections
> * 'component/landing/Landing' could be move to 'pages/index'

I guess this is already resolved?

**Comment by roiLeo** [comment]
#### Current route to be synchronized
- '/rmrk/collections' should show list of collections
- '/rmrk/collection/{id}' shoud show collectionItem

**Comment by yangwao** [comment]
> #### Current route to be synchronized
> * '/rmrk/collections' should show list of collections
> * '/rmrk/collection/{id}' shoud show collectionItem

@dezine2dev 👀

**Comment by yangwao** [comment]
@dezine2dev continue there https://github.com/kodadot/nft-gallery/issues/1249 

Merging for unblocking others.

**Pull request merged**
