### PR TITLE
Extend-bulma-spacing-helpers

### LINKED ISSUE #5639: extend bulma margin/padding
we have classes spread all over for padding/margin of 2, 2.5 rem

use bulma style and put these classes in global.scss

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

* Bulma classes up until 5 => remain the same
* 6 is now 2rem
* 7 is 2.5 rem
* 8 is the old 6. i,e 3rem

<table><thead><tr><th>Class Name</th><th>Padding Value</th></tr></thead><tbody><tr><td><code>p-0</code></td><td>0rem</td></tr><tr><td><code>p-1</code></td><td>0.25rem</td></tr><tr><td><code>p-2</code></td><td>0.5rem</td></tr><tr><td><code>p-3</code></td><td>0.75rem</td></tr><tr><td><code>p-4</code></td><td>1rem</td></tr><tr><td><code>p-5</code></td><td>1.5rem</td></tr><tr><td><code>p-6</code></td><td>2rem</td></tr><tr><td><code>p-7</code></td><td>2.5rem</td></tr><tr><td><code>p-8</code></td><td>3rem</td></tr></tbody></table>

## PR Type

- [ ] Bugfix
- [x] Feature
- [x] Refactoring

## Context

- [x] Closes #5639
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

**Hopefuly changed nothing** 😆

### CODE REVIEW

**Comment by daiagi** [comment]
pr got mixed up with another. closing

**Comment by daiagi** [comment]
Deep source complains about functional stuff i didn't touch
unused componenets and such
dosn't make sense to touch these in this pr

**Comment by daiagi** [comment]
> Have you tried something like this?



For simplifying the loop?

**Comment by roiLeo** [comment]
> For simplifying the loop?

I don't think you need to create the loop as it's already implemented in [Bulma](https://bulma.io/documentation/helpers/spacing-helpers/#configuration)

(ref https://github.com/jgthms/bulma/blob/40850b15d916fef422ac3a086280fe838ebf94d7/sass/helpers/spacing.sass#L11)

**Comment by vikiival** [comment]
> > Have you tried something like this?
> 
> For simplifying the loop?

Wow I did not know about loops in SCSS. But may try something like @roiLeo said? 
it could be easier to read.

Otherwise lgtm

**Comment by daiagi** [comment]
>Have you tried something like this?

Done

Thanks @roiLeo . simple and clean 👍

**Comment by daiagi** [comment]
@roiLeo 
I'm thinking, we have a few places where people write specifc classes to toggle spacing on mobile

would be nice to have these as well won't it? 
maybe something like p*-*-mobile

wdyt?

**Review by vikiival — APPROVED** [review]
Looking forward for more uniform code 💚

**Comment by vikiival** [comment]
pay 15 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $15 @ 37.55 USD/KSM ~ 0.399 $KSM
🧗 [EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L](https://kusama.subscan.io/account/EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L)
🔗 [0x9188c2f19bc0707bc811c8ed7ad4548991d5e8a86d7da45a7781ecdf300b3d03](https://kusama.subscan.io/extrinsic/0x9188c2f19bc0707bc811c8ed7ad4548991d5e8a86d7da45a7781ecdf300b3d03)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
