### PR TITLE
feat: add 3rd grid size

### LINKED ISSUE #4895: Explorer - adding more NFTs in a row
### Is your feature request related to a problem?

When you click on explore - gallery, it will show you all the minted NFTs but only 3 per row. Would be awesome to have the option to see more than 3 in a row. We have this option when you open a specific collection, but not in a gallery explorer.

### Describe the solution you would like

I often visit other marketplaces and I really enjoy it when I can see more NFTs on the screen without excessive scrolling.
For example this Tezos marketplace: 
Screenshot 2023-02-02 at 10 09 17
Screenshot 2023-02-02 at 10 14 51

Our gallery explorer: 
Screenshot 2023-02-02 at 10 18 45

### Describe alternatives you have considered

Just add "small display" to the gallery. I would also make this option as a "primary" or "default" just because it looks better.

### Screenshots

_No response_

### Are there opened related issues?

_No response_

### LINKED ISSUE #5164: New option: More NFTs on one page
### Is your feature request related to a problem?

It would be cool to see more NFTs on one page. I know that something is also cooking with design changes but Im not sure what. So feel free to close this issue if the discussion is already somewhere. 

My idea is to have a third option here that will enable the option to make the NFTs even smaller:
Screenshot 2023-03-03 at 14 45 19

Having this option in profiles (collected NFTs) but also in explorer, collection view, etc. 
I want to be able to change the preview and click between these options. 
Example from Opensea:
Screenshot 2023-03-03 at 14 49 32

### Describe the solution you would like

- 

### Describe alternatives you have considered

-

### Screenshots

_No response_

### Are there opened related issues?

_No response_

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #5164 
- [x] Closes #4895
- [x] branching from https://github.com/kodadot/nft-gallery/pull/5148

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by yangwao** [comment]
yes, let's go with it

**Comment by yangwao** [comment]
@JustLuuuu 

https://deploy-preview-5172--koda-nuxt.netlify.app/bsx/explore/items?listed=true&page=1

image

**Review by Jarsen136 — APPROVED** [review]
code lgtm

**Review by roiLeo — COMMENTED** [review]
Can we change buttons order? (from larger view to small view)

**Review by daiagi — COMMENTED** [review]
hey hey
code lgtm
but because you are measuring the width of the container, it stops working on screen width 1215px or less (when sidebar is open)

I am not sure on the design requirements here, but i would expect it to still work for screens that wide

**Review by daiagi — APPROVED** [review]

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 33.43 USD/KSM ~ 1.496 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0x0a7b212b544a176d34fba60170ec0bb22cc6420a8aa9e9cc82d4dd33240f2f34](https://kusama.subscan.io/extrinsic/0x0a7b212b544a176d34fba60170ec0bb22cc6420a8aa9e9cc82d4dd33240f2f34)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
