### PR TITLE
fix: Followers UX improvements

### LINKED ISSUE #10165: Followers UX improvements
Took me a while to find out that those buttons were clickable: 
image
is there something we can do to make it more obvious? 

i do think it would be good if those profiles could be clickable and would redirect to clicked profile: 
image

@exezbcz 

after #10160

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs Design check

- @exezbcz please review

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #10165

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Review by preschian — APPROVED** [review]

**Review by daiagi — APPROVED** [review]

**Comment by prury** [comment]
it works, but will let Exez check this one

**Comment by Jarsen136** [comment]
@exezbcz May I get your review? 👀

**Comment by exezbcz** [comment]
of course, the hover looks good, nice addition. 

How can i test the hover over the profiles? Could you please send me profile that i can start following?

**Review by exezbcz — APPROVED** [review]

**Comment by exezbcz** [comment]
yup, its good!

**Pull request merged**
