### PR TITLE
set key with b-table

### LINKED ISSUE #2546: Bug in history component for list, unlist, mint?
As I guess list and unlist is made just by owner and why is in To other address?

check at https://beta.kodadot.xyz/rmrk/collection/2644199cf3652aaa78-KK01?tab=history

The list should be only by owner I guess? 

list
image

unlist
image

same go for mint? 

image

### PR DESCRIPTION
**Pull request by zhengow**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2546 
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

### CODE REVIEW

**Comment by yangwao** [comment]
Probably no need to show column "To" if it's empty?

**Comment by zhengow** [comment]
> Probably no need to show column "To" if it's empty?

hide column "To" when it's empty, plz review:)

**Review by vikiival — CHANGES_REQUESTED** [review]
1. why do you need a key prop? [custom-row-key](https://buefy.org/documentation/table#api-view)
2. `typeWithToProp` is super dark magic (You need to the column for SEND and BUY and maybe MINT)
3. Not a fan of `'all'` string better approach is to use `value=""`

**Comment by yangwao** [comment]
cc @vikiival for review 👀

**Review by vikiival — APPROVED** [review]
I DID NOT TEST IT.

Refactor #2589

**Comment by yangwao** [comment]
hey @zhengow let's resolve conflicts and happy to merge it! :)

**Comment by zhengow** [comment]
Already resolve the conflicts. As the video followed, u can see without cutsom-key, some column data will mix up and mistake.

before and without key: 

https://user-images.githubusercontent.com/38389586/159149531-6361ca67-c3f7-4de8-9638-eaff4111866c.mp4

after and with key:


https://user-images.githubusercontent.com/38389586/159149534-e86b37c4-d395-45dd-a46a-9bf7aa1e845a.mp4

Besides, I remove the "To" column if it is list, unlist and mint

**Comment by zhengow** [comment]
> Already resolve the conflicts. As the video followed, u can see without cutsom-key, some column data will mix up and mistake.
> 
> before and without key:
> 
>  before_change_Trim.mp4 
> after and with key:
> 
>  after_change_Trim.mp4 
> Besides, I remove the "To" column if it is list, unlist and mint

About [.github/diagram.svg](https://github.com/kodadot/nft-gallery/pull/2551/files#diff-15491072ef7d1bf245a6fbe8d0f7a61f5fda86e064547da61f74e95ad746bda7), I have no idea why this file is different. Actually, it's the same with master

**Comment by vikiival** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 144.3 USD/KSM ~ 0.693 $KSM
🧗 [EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws](https://kusama.subscan.io/account/EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)
🔗 [0x0221e0e2fa136caa37150856b07e60eb60f2044efbaa3ada23e1a0a268db1015](https://kusama.subscan.io/extrinsic/0x0221e0e2fa136caa37150856b07e60eb60f2044efbaa3ada23e1a0a268db1015)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
