### PR TITLE
⬆️ upgrade sub-api

### LINKED ISSUE #4499: Bump polkadot packages
released

> 📦  @kodadot1/sub-api@0.1.1-alpha.4

please bump all @polkadot-js related packages to latest in the nft-gallery

_Originally posted by @vikiival in https://github.com/kodadot/packages/issues/77#issuecomment-1351415805_

### PR DESCRIPTION
**Pull request by roiLeo**
## PR Type

- [x] Dependencies upgrade

## Context

- [x] Closes #4499 

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=GemsyWUUtZU5HAiEQJqqgVz4YkekKXnmutYryBhbcVD4YW3)

### CODE REVIEW

**Comment by vikiival** [comment]
Looks like there are some warnings? 

do we need to bump other packages?

errs

**Comment by roiLeo** [comment]
Throw error on `pnpm install` when I `pnpm up "@polkadot/*"`

**Comment by yangwao** [comment]
Same but different? 
- https://github.com/kodadot/nft-gallery/pull/4713

**Comment by vikiival** [comment]
> Throw error on `pnpm install` when I `pnpm up "@polkadot/*"`

Any news?-

**Comment by roiLeo** [comment]
> > Throw error on `pnpm install` when I `pnpm up "@polkadot/*"`
> 
> Any news?-

build 👌 since #4713

**Review by vikiival — APPROVED** [review]
LGTM

**Comment by vikiival** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 31.18 USD/KSM ~ 0.641 $KSM
🧗 [GemsyWUUtZU5HAiEQJqqgVz4YkekKXnmutYryBhbcVD4YW3](https://kusama.subscan.io/account/GemsyWUUtZU5HAiEQJqqgVz4YkekKXnmutYryBhbcVD4YW3)
🔗 [0xf13a4029141ddf9084fa215d7919f27d0b902a01bcdd0fd85c93e329bb1359b5](https://kusama.subscan.io/extrinsic/0xf13a4029141ddf9084fa215d7919f27d0b902a01bcdd0fd85c93e329bb1359b5)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
pay 20 usd

**Pull request merged**
