### PR TITLE
#1887 Hide disabled pagination buttons

### LINKED ISSUE #1887: Hide disabled pagination buttons
Let's remove pagination buttons if they are disabled.

- Collection detail
- Artist tabs 
- where else?

https://kodadot.xyz/rmrk/u/EzZjBjv9bRPYJEbUdijzgjb9VMSqrqwx2eqnfjQcY5YvXCk?search=&listed=true

image

image

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Do a quick check before the merge.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [ ] PR closes #1887

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases

### Had issue bounty label ?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI, a screenshot is best to understand changes for others.
Screenshot 2022-01-17 at 8 12 39 PM

### CODE REVIEW

**Comment by prachi00** [comment]
@yangwao even now the build is failing

**Comment by prachi00** [comment]
Screenshot 2022-01-17 at 8 43 46 PM

**Comment by roiLeo** [comment]
> Screenshot 2022-01-17 at 8 43 46 PM

(you're missing .env var)
Been there, done [that]( https://github.com/kodadot/nft-gallery/blob/main/FIRST_TIME.md)

**Comment by yangwao** [comment]
Ah seems @vikiival has fixed it here https://github.com/kodadot/nft-gallery/commit/3b82e010d207168ee69b2de3219f5fb15d9c4f75

Pinata seems other error, let me check on that

**Comment by yangwao** [comment]
> (you're missing .env var)
> Been there, done that

Seems like a type error

**Comment by yangwao** [comment]
@vikiival working on fix, it will be in `main` soon

**Comment by vikiival** [comment]
Should be fixed in #1895

**Comment by vikiival** [comment]
@prachi00 may merge latest `main`

**Comment by prachi00** [comment]
@yangwao works now

**Comment by yangwao** [comment]
Ah, good catch by @vikiival -- random button is pointless as well than if there is only one page.
Let's remove it then conditionally:)

image

**Comment by prachi00** [comment]
> Ah, good catch by @vikiival -- random button is pointless as well than if there is only one page. Let's remove it then conditionally:)
> 
> image

@yangwao yes, makes sense. Have pushed the changes for this.

**Comment by yangwao** [comment]
Perfect, I’ve sent the payout https://kusama.subscan.io/extrinsic/0x65d164cbc751ff2fcfafeca71104ea9c2573ff592db970699b414d68b4b2345c

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/

**Pull request merged**
