### PR TITLE
fix: List NFT floor price button doesn't work

### LINKED ISSUE #8867: List NFT floor price button doesn't work
### What happened?

Although there is a floor price for this collection the floor price button along with -5% and +5% buttons don't work anymore.

I really liked that button 😭

### Please reproduce in steps

Claim nft, try to list it, same happens when you try to change the price again...
https://kodadot.xyz/ahp/gallery/66-149

### Expected Behavior

-

### What browsers are you seeing the problem on?

_No response_

### At which address did you encounter bug?

_No response_

### Are you logged in?

None

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

_No response_

### Screenshots

Screenshot 2024-01-04 at 19 39 26

### Relevant log output

_No response_

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #8867

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2024-01-05 at 12 04 16@2x

CleanShot 2024-01-05 at 12 03 16@2x

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
Still doesn't work for me ie: Genera collection

Screenshot 2024-01-05 at 09-35-55 Genera #22

**Comment by hassnian** [comment]
> Still doesn't work for me ie: Genera collection
> 
> Screenshot 2024-01-05 at 09-35-55 Genera #22

 seems to be working, can you share video ?

https://github.com/kodadot/nft-gallery/assets/44554284/e89bead7-3551-4834-b6b0-027605ec8bef

**Comment by roiLeo** [comment]
>  seems to be working, where are you using the listing modal ?

Using LIST button in GalleryItem page (`/ahp/gallery/63-22`)

**Comment by hassnian** [comment]
CleanShot 2024-01-05 at 16 17 53@2x

**Review by roiLeo — APPROVED** [review]
Nice! it does work now

**Comment by yangwao** [comment]
thanks!
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 7.49 USD/DOT ~ 2.67 $DOT
🧗 [13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh](https://polkadot.subscan.io/account/13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)
🔗 [0xd4ba522c45a3a0738457cad91587723f5b4e1c97dca27f9a17d1a940410f438f](https://polkadot.subscan.io/extrinsic/0xd4ba522c45a3a0738457cad91587723f5b4e1c97dca27f9a17d1a940410f438f)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
