### PR TITLE
fix: chart.js wrong plugins config

### LINKED ISSUE #6991: /spotlight page crash
### What happened?

on canary, the loader doesn't stop

https://canary.kodadot.xyz/spotlight/

on localhost we get a crash

image

### Please reproduce in steps

go to /spotlight page

### Expected Behavior

working page

### What browsers are you seeing the problem on?

_No response_

### At which address did you encounter bug?

_No response_

### Are you logged in?

None

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

_No response_

### Screenshots

image

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/ksm/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by newraina**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #6991 
- [ ] Requires deployment <snek/rubick/worker>

The error `Reflect.getPrototypeOf...` is caused by an incorrect Chart.js plugin config.

CleanShot 2023-08-29 at 12 11 50@2x

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer?target=1CAv6Zq3yVxL3eKhC94GWTWVwp1w4jZbqeZ6wXx1rPAhrce&usdamount=0&donation=true)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at 5045290</samp>

Fixed a Chart.js warning by passing an object to the `legend` plugin option in `PulseChart.vue`.

### <samp>🤖 Generated by Copilot at 5045290</samp>

> _`legend` option changed_
> _Chart.js warning resolved_
> _Autumn leaves fall silent_

### CODE REVIEW

**Review by daiagi — APPROVED** [review]

**Comment by prury** [comment]
the infinite loading happens when using what chain? 
trying to reproduce

**Comment by daiagi** [comment]
> the infinite loading happens when using what chain? trying to reproduce

mmm weird


when I reported the bug it was on
https://canary.kodadot.xyz/spotlight/

now when I try it works ok

**Comment by prury** [comment]
> > the infinite loading happens when using what chain? trying to reproduce
> 
> mmm weird
> 
> when I reported the bug it was on https://canary.kodadot.xyz/spotlight/
> 
> now when I try it works ok

depends on the chain you were when typing /spotlight in the bar i guess

**Comment by newraina** [comment]
"infinite loading" seem to be a different issue, not related with `Reflect.getPrototypeOf...` error on localhost

**Review by floyd-li — APPROVED** [review]

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 4.48 USD/DOT ~ 6.696 $DOT
🧗 [1CAv6Zq3yVxL3eKhC94GWTWVwp1w4jZbqeZ6wXx1rPAhrce](https://polkadot.subscan.io/account/1CAv6Zq3yVxL3eKhC94GWTWVwp1w4jZbqeZ6wXx1rPAhrce)
🔗 [0x3846ea43cc35d66d9a96db877e3bf3060ac47c80cee4a416602b944397de4c03](https://polkadot.subscan.io/extrinsic/0x3846ea43cc35d66d9a96db877e3bf3060ac47c80cee4a416602b944397de4c03)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
