### PR TITLE
Translated a new language - hi.json

### LINKED ISSUE #9055: Translation in hn (hindi)
### Is your feature request related to a problem?

There is no hindi translation.

### Describe the solution you would like

I want to translate for hindi.

### Describe alternatives you have considered

hi.json is there but it's plain english or hi might not be hindi.
if it's i'll tranlate in hindi and make a PR.
So I hope it'll considered as a whole ! because hi.json is there but it's plain english or hi might not be hindi.

### Screenshots

_No response_

### Are there opened related issues?

no

### PR DESCRIPTION
**Pull request by TouchstoneTheDev**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #9055 
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=15oN3VzqvyuhQAZQQXkQ4WLjFTzuPXMXnCkgkph1BYaWQGaK)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

Solving #9055 

image

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by yangwao** [comment]
Seems needs to be enabled to be tested 

image

**Comment by TouchstoneTheDev** [comment]
@yangwao Do you mean I have to do it ? or the team will do it.
Is there something to do from my side tell me :)

**Comment by yangwao** [comment]
Someone from @kodadot/internal-dev can assist to enable it

**Review by roiLeo — COMMENTED** [review]
json file has warnings

Capture d’écran 2024-01-22 à 8 54 02 AM

What should be the label for this language? `हिंदी`?

**Comment by yangwao** [comment]
> What should be the label for this language? हिंदी?

Yes, let's try adding it please @roiLeo

**Comment by yangwao** [comment]
It seems some translations are not perfect and need peer review. 
- https://github.com/TouchstoneTheDev/nft-gallery/blob/main/locales/hi.json#L13

I mean we can merge and put it into production for now. 

You can try opening a new PR with fixes

pay 100 usd

**Comment by yangwao** [comment]
thanks @TouchstoneTheDev let's open new PR with new translations fixes :)

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
send $100 
- https://polkadot.subscan.io/extrinsic/0x7b0fc9c738a48382098f92731449c6f8413bf4aa8d7a44cbb82ea790bf617fb1

**Pull request merged**
