### PR TITLE
fix: duplicate items in itemsGrid

### LINKED ISSUE #6677: Same item twice in explore feed
image
- added two items to cart - number of items 2 
image
- scrolled bit more to see the same selected items 

- why is this happening? Looks like more same items are there.

### PR DESCRIPTION
**Pull request by stephenjason89**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context
Issue was caused by 
image

together with
image

Upon navigating to explore items, the query runs already to fetch page 1 but at the same time, breadCrumbsFilter onMounted event sets `listed=true `

Thus making the watcher to run the query again for page 1 which causes the duplicates.

The fix was to have a separate watcher for listed and only run if listed was already set by BreadCrumbsFilter.
This will avoid the re-querying of data which causes the duplicates.

- [x] Closes #6677 

- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer?target=16UcV9V6nVvPYdHz98ymUKmNLkzjCEU5sbKJMi7hxYyTHjzR&usdamount=100&donation=true)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at 769abca</samp>

Refactored the code for opening the shopping cart modal from the navbar. Moved the logic and configuration from `ShoppingCartModalConfig.ts` and `ShoppingCartButton.vue` to `Navbar.vue` to improve code organization and performance.

### <samp>🤖 Generated by Copilot at 769abca</samp>

> _`ShoppingCartButton`_
> _Simpler, no more `emit` -_
> _Autumn leaves falling_

### CODE REVIEW

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
> will plan to do release shortly if someone check this one, seems quite important for production 👀

cc @Jarsen136, @prury thanks ❤️

**Comment by Jarsen136** [comment]
The bug is still there after testing.

https://deploy-preview-6855--koda-canary.netlify.app/ksm/explore/items

Kapture 2023-08-21 at 22 35 35

**Comment by stephenjason89** [comment]
@Jarsen136, I'm sorry there was a typo.
I mistakenly included an array on the watch.

Everything is working perfectly now.

Please check @Jarsen136

**Review by Jarsen136 — COMMENTED** [review]
There is a bad case for this solutioin.

If you visit this collection page and then turn on 'listed', it would not work any more.
https://deploy-preview-6855--koda-canary.netlify.app/ksm/collection/eecde2ad072011334d-DOTPEPE

**Comment by stephenjason89** [comment]
@Jarsen136  please check https://github.com/kodadot/nft-gallery/pull/6730#issuecomment-1680374742

It was already discussed. 

I thought despite the setbacks of this implementation will make this as a quick fix.

**Comment by Jarsen136** [comment]
> @Jarsen136 please check [#6730 (comment)](https://github.com/kodadot/nft-gallery/pull/6730#issuecomment-1680374742)
> 
> It was already discussed.
> 
> I thought despite the setbacks of this implementation will make this as a quick fix.

I'm ok with a quick fix to be merged. However, I would choose a better solution if it introduces a new bug.

**Comment by stephenjason89** [comment]
> 

I completely agree. Though, it would have been really nice if you could have pointed me in the right direction for the fix as I've been discussing the bug and potential solutions on the matter. Instead of opening a new PR.

Anyway, thank you and i appreciate your efforts on checking the PR

**Comment by stephenjason89** [comment]
@Jarsen136 I have left a comment on your PR #6860 
It was not an ideal fix.

Please check if everything is working here now.

Thank you

**Comment by Jarsen136** [comment]
> @Jarsen136 I have left a comment on your PR [#6860 ](https://github.com/kodadot/nft-gallery/pull/6860#issuecomment-1686642291) It was not an ideal fix.
> 
> Please check if everything is working here now. I have revised the implementation and taken inspiration from your PR.
> 
> Thank you

I'm glad to see you continue to improve your commit. I patiently waited for you to provide a suitable fix until I repeatedly reviewed the code and found that the bug still happens. This bug fix should not take around one week. I'm sorry that I'm not going to review this PR.

**Comment by stephenjason89** [comment]
@Jarsen136, I apologize for any inconvenience this might have caused. I've been actively following up on the PR, but unfortunately, I received no assistance for a week. The issue was awaiting review, and my comments went unanswered. I was waiting with patience, so the delay wasn't from my side. I hope you can appreciate that.

The conversation progressed when @yangwao tagged @vikiival.

I completely understand that everyone has commitments, and I don't wish to chase trivial matters. My questions were genuine, and without clearer guidance on your expectations for the solution, I'm working somewhat in the dark.

Maybe @prury can assist in reviewing this PR? It's a valid fix and addresses the current problem.

**Comment by stephenjason89** [comment]
Hello @JustLuuuu, included a fix for your issue #6865 here.

Thank you for reporting it.

**Comment by Jarsen136** [comment]
> Hello @JustLuuuu, included a fix for your issue #6865 here.
> 
> Thank you for reporting it.

Hey, @stephenjason89, it's another bug that comes from some recent merging. I merged the main branch into it so that you could reproduce it.

**Comment by stephenjason89** [comment]
Hello @Jarsen136 & @preschian, 
I believe this branch is good to go. If you could kindly check it.
Blocker #6868 has been merged already.

Thank you

**Review by Jarsen136 — APPROVED** [review]
Let's go, as it's been stuck for too long.

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 4.47 USD/DOT ~ 6.711 $DOT
🧗 [16UcV9V6nVvPYdHz98ymUKmNLkzjCEU5sbKJMi7hxYyTHjzR](https://polkadot.subscan.io/account/16UcV9V6nVvPYdHz98ymUKmNLkzjCEU5sbKJMi7hxYyTHjzR)
🔗 [0x47937d6cbe63c6a931dfe729207e8c9326573a089f0ae17ff7b9f6b17dfb8b98](https://polkadot.subscan.io/extrinsic/0x47937d6cbe63c6a931dfe729207e8c9326573a089f0ae17ff7b9f6b17dfb8b98)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
