### PR TITLE
Fix/Same-transfer,different-time

### LINKED ISSUE #8703: Same transfer, different time
Same transfer, different timelines

- https://canary.kodadot.xyz/ahp/collection/50/activity - 1 day ago 
image

- https://canary.kodadot.xyz/ahp/gallery/50-224 - transfer - 2 days ago 
image

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Context

- [x] Closes #8703

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)

### CODE REVIEW

**Review by Jarsen136 — APPROVED** [review]

**Comment by prury** [comment]
i was unable to reproduce this problem on canary or kodadot.xyz 
did a general check on timestamps on deployed and looks ok for me

**Comment by daiagi** [comment]
@prury yes not easy to reproduce, it's specific timestamps that cause the mismatch.
But now both pages use the same code to create the text
Therefore they cannot be different from each other

**Review by roiLeo — APPROVED** [review]

**Comment by yangwao** [comment]
thanks!
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 8 USD/DOT ~ 2.5 $DOT
🧗 [1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8](https://polkadot.subscan.io/account/1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)
🔗 [0x89e4eb2eef22675e40443b69724c79032421df425682848a35781499a19b2339](https://polkadot.subscan.io/extrinsic/0x89e4eb2eef22675e40443b69724c79032421df425682848a35781499a19b2339)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
