### PR TITLE
fix: SearchBar in Navbar vertical-align

### LINKED ISSUE #4545: SearchBar in Navbar vertical-align
The search bar in the navigation bar is not aligned with the content

### 📸 Screenshot
Capture d’écran 2022-12-22 à 9 54 48 AM

### ⚠️ warning
you have to check that you are not breaking the design of search bar in landing page

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4545
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
Not the ideal solution, we shouldn't have to set top margin on navbar start since it's extending navbar height (and navbar-shrink)
But this hack works for now :/

Seems that `columns` class is causing problems

**Comment by Jarsen136** [comment]
> Not the ideal solution, we shouldn't have to set top margin on navbar start since it's extending navbar height (and navbar-shrink) But this hack works for now :/
> 
> Seems that `columns` class is causing problems

Both class `columns` and incorrect `margin-top` cause this problem. However, the  `columns` could not be removed or it would break the style otherwhere.  So, changing the margin-top would be a fair way to fix this issue. It's not a hack way : )

**Comment by roiLeo** [comment]
IMO, we should replace `Search` with `SearchBar` component as there is a lot of code that does not have to be present on all pages. ref #3883

**Comment by Jarsen136** [comment]
> IMO, we should replace `Search` with `SearchBar` component as there is a lot of code that does not have to be present on all pages. ref #3883

It makes sense. Should do some component refactoring to achieve so.

**Review by roiLeo — APPROVED** [review]
> It makes sense. Should do some component refactoring to achieve so.

Aight, this can continue in #3883

**Comment by yangwao** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 24.45 USD/KSM ~ 0.818 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xb7f31e8069e57d583e81828f91d54540194133ad2ce78d2d4b501c6bc43a861a](https://kusama.subscan.io/extrinsic/0xb7f31e8069e57d583e81828f91d54540194133ad2ce78d2d4b501c6bc43a861a)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
