### PR TITLE
#7879 Disable change price from explorer

### LINKED ISSUE #7879: Disable change price from explorer
image
image
image
- should stay only on profile

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #7879
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)

## Screenshot 📸

- [] My fix has changed UI

### CODE REVIEW

**Comment by prury** [comment]
still occurs on Assethubs: 
image

**Comment by prachi00** [comment]
> still occurs on Assethubs: image

is it still there for you? I cant see change price anymore

**Comment by prury** [comment]
> > still occurs on Assethubs: image
> 
> is it still there for you? I cant see change price anymore

yeah @prachi00, still the same:

image

**Comment by prachi00** [comment]
> > > still occurs on Assethubs: image
> > 
> > 
> > is it still there for you? I cant see change price anymore
> 
> yeah @prachi00, still the same:
> 
> image

weird, I am going to close this one since I cant test it properly

**Pull request closed without merging**
