### PR TITLE
feat: Grey negative indicators

### LINKED ISSUE #9935: Grey negative indicators
I thought about it for some time, saw rainbow doing it, looks nice
image

let's replace the red with k-grey

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #9935

## Needs Design check

- @exezbcz please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2024-03-30 at 09 00 03@2x

### CODE REVIEW

**Review by daiagi — APPROVED** [review]

**Review by vikiival — APPROVED** [review]

**Comment by prury** [comment]
pay 5 usd

**Comment by prury** [comment]
pay 5 usd

**Comment by prury** [comment]
pay 5 usd

**Comment by prury** [comment]
pay 10 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $10 @ 8.45 USD/DOT ~ 1.183 $DOT
🧗 [16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD](https://polkadot.subscan.io/account/16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)
🔗 [0xc7147470e02389b4bffff63c5f5c3b6232b15d59b1bca32dbe5978e8152ac1d0](https://polkadot.subscan.io/extrinsic/0xc7147470e02389b4bffff63c5f5c3b6232b15d59b1bca32dbe5978e8152ac1d0)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
