### PR TITLE
Japanese Translation KodaDot

### PR DESCRIPTION
**Pull request by kzyxyz**

### CODE REVIEW

**Comment by yangwao** [comment]
Looks promising! :)
Happy to see it whole and release it into production!
I recall few other guys we up to this so a peer-reviewed contribution would be best!

**Comment by avcdsld** [comment]
Is this an old branch that you are basing this on?
It looks like there is a missing json entry.

**Comment by tokchin** [comment]
Added other translations and created new pull request.

https://github.com/kodadot/nft-gallery/pull/80

**Comment by yangwao** [comment]
Hey closing down this in favour of https://github.com/kodadot/nft-gallery/pull/80
Dont forget to post your KSM address @kzyxyz :)

**Pull request closed without merging**
