### PR TITLE
add contributing and first_time pages

### LINKED ISSUE #1933: Embed Contributing.md & First_time.md to kodadot web
I guess for a single point of truth (file) and SEO reasons, would be nice to embed currently existing Contributing.md and First_time to help easily onboard developers.

@roiLeo suggests https://content.nuxtjs.org/
The best would be probably to leverage the existing markdown module we are using? [vue-markdown-render](https://github.com/kodadot/nft-gallery/blob/main/package.json#L94) I guess?

routes could be 
- kodadot.xyz/contribute
- kodadot.xyz/first_time 

### Ref 
- #361
- #1075
- maybe https://github.com/wxsms/vue-md-loader ?

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #1933

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screen Shot 2022-03-23 at 2 34 21 PM
Screen Shot 2022-03-23 at 2 34 31 PM

### CODE REVIEW

**Review by roiLeo — CHANGES_REQUESTED** [review]
We use MarkdownIt package with i18n plugin why would you remove it?

**Comment by preschian** [comment]
> Hey, we use MarkdownIt package with i18n plugin why would you remove it? Plus do we really need this `highlight.js` stuff? I think it could be done using bulma component.

maybe I miss something. I didn't mean to remove the existing one, can you refer to which file? in package.json I only added `highlight.js` and `vue-md-loader`

highlight.js is for syntax highlighting, especially in `FIRST_TIME.md`
| without | with highligh.js |
| ------------- | ------------- |
| Screen Shot 2022-03-23 at 4 38 00 PM | Screen Shot 2022-03-23 at 4 38 37 PM |

**Comment by roiLeo** [comment]
We use in some component `vue-markdown-render` to render md content (take a look at DescriptionWrapper.vue, GalleryItem.vue ...)


> maybe I miss something. I didn't mean to remove the existing one, can you refer to which file? in package.json I only added `highlight.js` and `vue-md-loader`

Oups, my eyes saw a deleted line (markdown-it) in the yarn.lock and I thought the package was gone. 

> highlight.js is for syntax highlighting, especially in `FIRST_TIME.md`

Rather than integrating `vue-md-loader` could you try to use [nuxtjs/markdownit-loader](https://www.npmjs.com/package/@nuxtjs/markdownit-loader) as it seems to have highlight.js features.

> I couldn't find bulma component for syntax highlight. can you send me the direct link, I only find this github issue [jgthms/bulma#690](https://github.com/jgthms/bulma/issues/690)

My bad, I didn't understand that it was a code block

**Comment by preschian** [comment]
I tried https://github.com/nuxt-contrib/markdownit-loader before, but got an error when consuming the `.md` files. in the [first commit](https://github.com/kodadot/nft-gallery/pull/2644/commits/28bbbcf9c196b390e2937ab2c5c155bc24f179a4), I end up with `@nuxtjs/markdownit`. working well, but there is a warning message when doing local development.
Screen Shot 2022-03-23 at 5 25 56 PM

pipeline for the snyk scanner also fail, I assume because of that package (I can't see snyk log) https://app.snyk.io/org/kodadot/pr-checks/474ef4f3-3452-48a5-905c-e24fd2fd1fb6
 
those packages actually have different use cases:
- `vue-markdown-render` is rendered vue component from `string` of markdown
- `vue-md-loader` is for direct consuming `.md` files, and convert it into vue component

another solution is to find another loader to turn `.md` files into a string, and then consume it with `vue-markdown-render`. tried this one, but fail and seems old https://github.com/unindented/markdown-it-loader

**Comment by preschian** [comment]
@roiLeo updated, following your suggestions, now use `vue-markdown-render` instead

**Review by roiLeo — COMMENTED** [review]
Final note on small things I would change:
- remove ContentMarkdown component and keep the logic in pages
- change snake_case page to kebab-case
- create an utils file with highlight.js config

**Comment by yangwao** [comment]
What's are final difference against #2021 👀

**Comment by preschian** [comment]
in https://github.com/kodadot/nft-gallery/pull/2021: it seems like limitation with `@nuxt/content` only can consume markdown from the `content` folder

In this PR, extend webpack config using `raw-loader`. It can import any files from javascript and convert them into a string. and then render the markdown content with the existing component `vue-markdown-render.`

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 159.3 USD/KSM ~ 0.628 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0x453baad07c7157dfcdb06315bf5bc9e3532ea6fb7ee3267031d526708c1570e9](https://kusama.subscan.io/extrinsic/0x453baad07c7157dfcdb06315bf5bc9e3532ea6fb7ee3267031d526708c1570e9)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
oh I forgot, if we can link contribute to footer 😇

**Pull request merged**
