### PR TITLE
Update es.json (English | Spanish Version)

### PR DESCRIPTION
**Pull request by CdrsAlejandro**

### CODE REVIEW

**Comment by CdrsAlejandro** [comment]
I've updated the translations until the 66 line :)

**Comment by yangwao** [comment]
Hey, actually you need to translate right thing, left are keys to match translation :)

**Comment by yangwao** [comment]
Hey thank you for your translation, don't forget to post KSM address!

**Comment by CdrsAlejandro** [comment]
Here is my KSM Address i created the address on Polka.Js idk if that's compatible with NFT's :)
EoefzRoSeepV3Kzg2aABQu6F2kkdUzCMWiJcn7aDsBg91rx

**Pull request closed without merging**
