### PR TITLE
🔧 cookie banner btn design

### LINKED ISSUE #10212: cookie popup styling
since this got recently merged, lets sync it with our design change that was few weeks ago 

image

## Data collecting 
google analytics are off by default? 
image

## styling 
image

Accept should be the "main" button 

link to figma: https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=1287-18959&mode=design&t=wIR4vUyhVh1KHnUu-11

### PR DESCRIPTION
**Pull request by roiLeo**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

(please remove design and QA checks below if not needed)

## Needs Design check

- @exezbcz please review

## Context

- [x] Closes #10212

#### Did your issue had any of the "$" label on it?

- [ ] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>)

## Screenshot 📸
Screenshot 2024-05-06 at 09-55-38 KodaDot - NFT Market Explorer
Screenshot 2024-05-06 at 09-57-06 KodaDot - NFT Market Explorer
Screenshot 2024-05-06 at 15-40-16 KodaDot - NFT Market Explorer

## Note

- https://github.com/kodadot/nft-gallery/issues/10212#issuecomment-2094085600
Capture d’écran 2024-05-06 à 10 09 18 AM

might come from recent `NeoButton` changes (ref #10210)

### CODE REVIEW

**Comment by prury** [comment]
dark mode: 

image

**Comment by exezbcz** [comment]
hello! 

could you please match the style to the cookie banner we use on production 

image


also the text of the paragraph is currently arial

**Comment by exezbcz** [comment]
> ## Note
> * [cookie popup styling  #10212 (comment)](https://github.com/kodadot/nft-gallery/issues/10212#issuecomment-2094085600)
> 
> Capture d’écran 2024-05-06 à 10 09 18 AM
> might come from recent `NeoButton` changes (ref #10210)



imo it came from here no? 
image

**Review by Jarsen136 — APPROVED** [review]
code lgtm

**Review by hassnian — APPROVED** [review]

**Pull request merged**
