### PR TITLE
refactor: useMetaTransaction.ts

### PR DESCRIPTION
**Pull request by floyd-li**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

to resolve this one: https://codeclimate.com/github/kodadot/nft-gallery/composables/useMetaTransaction.ts

affected modules:

- `components/bsx/Asset/AssetList.vue`
- `components/bsx/Offer/MyOffer.vue`
- `components/bsx/Offer/OffersUserTable.vue`
- `components/common/IdentityForm.vue`

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Part of #6782
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at 47c5b28</samp>

Refactored `useMetaTransaction` composable to improve readability and modularity. Extracted helper functions and passed parameters as objects.

### <samp>🤖 Generated by Copilot at 47c5b28</samp>

> _`useMetaTransaction`_
> _Extracted helpers, less dupes_
> _Spring cleaning the code_

### CODE REVIEW

**Comment by vikiival** [comment]
Honestly I do not want to touch this module :).

**Comment by floyd-li** [comment]
> Honestly I do not want to touch this module :).

hmmm so is this pr still valuable? or just close it and let it be

**Comment by vikiival** [comment]
> hmmm so is this pr still valuable? or just close it and let it be

As you said I do not see value refactoring this module. I am sorry for the extra work.

**Comment by floyd-li** [comment]
> > hmmm so is this pr still valuable? or just close it and let it be
> 
> As you said I do not see value refactoring this module. I am sorry for the extra work.

i'm okay with it

**Pull request closed without merging**
