### PR TITLE
Follow up top collection data volume

### LINKED ISSUE #4365: Follow up top collection data volume and & change v3
Small changes could be made in this issue

- design of time filter for black version, you can find them here https://www.figma.com/file/3iOjW12ERFRDSVnpLuhQmf/landing-page-handoff?node-id=798%3A3662

image

- we've meanwhile changed time frames as there is fewer data since design file, and we went for 
  - **7 days / 30 days / 90days / ALL** filters

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/4332#issuecomment-1322422069_

### PR DESCRIPTION
**Pull request by daiagi**
* Added "active" prop to NeoButton to trigger active / pressed down style
* Refactored TopCollections using NeoButton (from #4364)
* changed time frames to 7 days / 30 days / 90days / ALL
* uniform width for time frame buttons [see here](https://github.com/kodadot/nft-gallery/issues/4365#issuecomment-1322449239)
* mobile layout

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Closes #4365
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image
image

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
`@click.native` fix your case

**Comment by daiagi** [comment]
> `@click.native` fix your case

yessss Thank you!!

closing #4371

**Review by roiLeo — COMMENTED** [review]
Could you move scoped scss to _top-collections.scss file?
& use 
```css
@include touch {
  // Styles applied
  // below $desktop
}
```

**Comment by roiLeo** [comment]
it's great! the only thing that bothers me is that we display 4 numbers after the comma for USD values

Screenshot 2022-11-22 at 14-02-09 KodaDot - Kusama NFT Market Explorer

might be related with #3355, #4109

**Comment by exezbcz** [comment]
image
- wrong typeface
- padding should be at least:16px left right, 8px top bottom. 
- you can maybe use the same selection component that is in gallery item handoff figma
image
so making it fit size and expand the buttons

figma: https://www.figma.com/file/gHSzqGPeQ9qK4L0qIDcTjY/gallery-item-handoff?node-id=991%3A4840&t=OR6eYVD9NNevAk17-0

**Comment by daiagi** [comment]
> wrong typeface

* Fixed, NeoButton Inherits font-family

> padding should be at least:16px left right, 8px top bottom

* Increased the min-width from 95px to 98px -> larger horizontal padding
set NeoButton vertical padding to 8px.
looks good on Histoire

image

> maybe also making the container to the edges like in design?

 @exezbcz  I don't quite understand what you mean

also, since it's now 4 buttons and not 3 its too wide for mobile
image

how would you suggest dealing with this?

**Comment by exezbcz** [comment]
> > wrong typeface
> 
> * Fixed, NeoButton Inherits font-family
> 
> > padding should be at least:16px left right, 8px top bottom
> 
> * Increased the min-width from 95px to 98px -> larger horizontal padding
>   set NeoButton vertical padding to 8px.
>   looks good on Histoire
> 
> image
> 
> > maybe also making the container to the edges like in design?
> 
> @exezbcz I don't quite understand what you mean
> 
> also, since it's now 4 buttons and not 3 its too wide for mobile image
> 
> how would you suggest dealing with this?

nice! thanks

- what i meant by that is solving the issue on the image 2
- so maybe lower the left and right padding in this case so it fits into the mobile margins and its lined up with the collection containers
- if something doesnt make sense, feel free to tag me

**Review by roiLeo — APPROVED** [review]
✅ code lgtm

> also, since it's now 4 buttons and not 3 its too wide for mobile
> how would you suggest dealing with this?

you can try to reduce button minimum fixed width on mobile 

// TODO:
- label translation

**Comment by exezbcz** [comment]
> > wrong typeface
> 
> * Fixed, NeoButton Inherits font-family
> 
> > padding should be at least:16px left right, 8px top bottom
> 
> * Increased the min-width from 95px to 98px -> larger horizontal padding
>   set NeoButton vertical padding to 8px.
>   looks good on Histoire
> 
> image
> 
> > maybe also making the container to the edges like in design?
> 
> @exezbcz I don't quite understand what you mean
> 
> also, since it's now 4 buttons and not 3 its too wide for mobile image
> 
> how would you suggest dealing with this?

ad buttons - can you please change the component hover color of text to black - in dark mode
image
- text on hover should be black
- like here 
image

**Comment by daiagi** [comment]
@exezbcz 
did some work on styling for mobile
How is that?
fixed the text color on hover in dark mode too
image

**Comment by daiagi** [comment]
> @daiagi I think it's wrong hover color on darkmode should be #ff7ac3 (`hsl(327, 100%, 74%)`)

Done

**Comment by exezbcz** [comment]
now the padding is smaller on desktop
> padding should be at least:16px left right, 8px top bottom.

otherwise everything looks alright

**Comment by daiagi** [comment]
> now the padding is smaller on desktop

Done - set horizontal padding: 16px 

FYI visually it doesn't make a difference
because i set minimum width on the button
the span inside the just expands to take up the empty space around it

that's how it looks with 0 padding
the border marks the span element

image

but since it doesn't matter anyways, I've added the padding

**Comment by yangwao** [comment]
yes
image


pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 25.84 USD/KSM ~ 1.935 $KSM
🧗 [EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L](https://kusama.subscan.io/account/EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L)
🔗 [0x9c110e052a8d923d656c3c8a962929e60b219fe7c287a5a65103883b86e2cd3e](https://kusama.subscan.io/extrinsic/0x9c110e052a8d923d656c3c8a962929e60b219fe7c287a5a65103883b86e2cd3e)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
