### PR TITLE
#4244 Dark mode explore leftovers

### LINKED ISSUE #4244: Redesign: Dark mode leftovers
# Dark mode feedback
## Graphics
image
sometimes the page loads like this. 

## Navbar 
please remove the hover bg on the nav links: 
image
and also same as the nav links in white mode, they dont have any hover effect so lets keep it consistent and remove the hover effect in the darkmode too. 
- Connect button not uppercase - "Connect" 
## hover color
image
this one is too saturated and i think inherited from old version, please change it to the k-accent one. 
## Search bar
just a minor improvement, for better accesability. On focus remove the text and just leave the cursor here. 
image

_Originally posted by @exezbcz in https://github.com/kodadot/nft-gallery/issues/4185#issuecomment-1297630782_

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## PR Context?

- [x] Closes #4244
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by prachi00** [comment]
Feel free to add any more leftovers over here we may have forgotten for explore :)

**Comment by exezbcz** [comment]
> can we fix this also? on light mode, some graphic override the heading text image

yup, it would be great. It was also in landing page feedback
image

**Comment by exezbcz** [comment]
> Feel free to add any more leftovers over here we may have forgotten for explore :)

The fill of the card is true black, but it should be the darkmode black - same as bg of the landing page
image

**Comment by prachi00** [comment]
> can we fix this also? on light mode, some graphic override the heading text image

done

**Comment by prachi00** [comment]
> > Feel free to add any more leftovers over here we may have forgotten for explore :)
> 
> The fill of the card is true black, but it should be the darkmode black - same as bg of the landing page image

done

**Comment by exezbcz** [comment]
## Graphics
image
sometimes the page loads like this. 

This is still missing

**Comment by prachi00** [comment]
`hover color still not using k-accent
` 
@preschian this will be fixed in the #4243 , fixed it there

**Comment by prachi00** [comment]
> ## Graphics
> image sometimes the page loads like this.
> 
> This is still missing

I am not sure how to reproduce this, doesn't happen to me?

**Comment by exezbcz** [comment]
> > ## Graphics
> > image sometimes the page loads like this.
> > This is still missing
> 
> I am not sure how to reproduce this, doesn't happen to me?

I experience it frequently. Whenever I open the deploy preview, for instance. Another instance is when you switch to dark mode, open several tabs (such as explore and create), and then come back to the homepage.

**Comment by yangwao** [comment]
yes, seems some cache issue 

https://user-images.githubusercontent.com/5887929/200119136-16c7e932-f3c4-43f4-95e7-ab5e245a4fe7.mov

**Comment by yangwao** [comment]
pay 30

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 37.36 USD/KSM ~ 0.803 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0xf21a5b40cbc435cb39a83925b1195901d4c39c4742d56f331d5ea1a8ae433dc5](https://kusama.subscan.io/extrinsic/0xf21a5b40cbc435cb39a83925b1195901d4c39c4742d56f331d5ea1a8ae433dc5)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
