### PR TITLE
feat(profiles): faster profile images and Option to remove img and clear profile

### LINKED ISSUE #10233: Option to remove img and clear profile
image
- this will enable clearing the profile, once confirmed, it will close the modal and user will have "cleared" profile without any customizations 
- this state will display 
image

## confirmation 
- please add a small delay before the "you sure" link becomes clickable so there are no accidental clicks 
image

# Removing imgs
- one thing left compared to design is the option to remove the img when uploaded (currently we don't have the functionality) 
image

please add the x-mark there 

### Notes
- updated in profile v3 figma
- https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=2116-13786&mode=design&t=neRjoavRuafpIGjV-11
image

### LINKED ISSUE #10420: Profiles: Banner picture not loading fast enough
I created my profile and later decided to add a banner picture. I selected a banner picture from my Twitter and uploaded it. It did not show, + I didn't get any notif that there may be a problem.  

https://github.com/kodadot/nft-gallery/assets/104380776/125d178b-c1d9-47dd-b042-514b70928e18

Profile stayed without banner picture. Here is my KodaDot profile: https://kodadot.xyz/ahp/u/1NFfEH3yspdEgLnhZ5QWgb7B2z5LNCAE3HUo5nDxF5MqTcj

### LINKED ISSUE #10451: Unable to remove picture from the profile
I was testing yesterday's profiles, and I added a profile picture for my account. Today, I realized that I don't have the option to remove the picture from my profile. I can just replace it. Is that intentional? If not, maybe we should have an option to "clear profile" or something like that. 

Screenshot 2024-06-11 at 11 41 40

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

❗️❗️ Needs https://github.com/kodadot/private-workers/pull/177
❗️❗️ Needs https://github.com/kodadot/workers/pull/300

- [x] Closes #10420
- drop IPFS and use cloudflare images for faster image loading/uploading
- [x] Closes #10233
- [x] Closes #10451
- allow clearing of avatar and banner images 
- option to delete your profile 

## Needs QA check

- @kodadot/qa-guild please review

## Needs Design check

- @exezbcz please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2024-06-12 at 12 35 24

CleanShot 2024-06-14 at 10 29 30@2x

### CODE REVIEW

**Comment by hassnian** [comment]
worker ready https://github.com/kodadot/private-workers/pull/187

blocked by #10534

**Comment by hassnian** [comment]
@exezbcz it's ready to test

**Review by preschian — APPROVED** [review]
wfm

**Comment by hassnian** [comment]
@Jarsen136  can I get a review , thanks

**Review by Jarsen136 — APPROVED** [review]

**Comment by exezbcz** [comment]
it does not let me save empty profile picture, 

image



otherwise really nice job, toast notifs works nice

**Comment by hassnian** [comment]
@vikiival ready to merge

**Comment by vikiival** [comment]
Will go after 
- #10599

**Comment by vikiival** [comment]
@hassnian you have some conflicts

**Comment by hassnian** [comment]
> @hassnian you have some conflicts

solved

**Pull request merged**
