### PR TITLE
chore: downgrade sass version

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Downgrade sass version to suppress warning on development mode. until oruga+bulma removed

Related:
- https://github.com/kodadot/nft-gallery/issues/8479
- https://github.com/kodadot/nft-gallery/issues/9013

### CODE REVIEW

**Comment by preschian** [comment]
for context, this is for sass warning on terminal when running development mode

Screenshot 2024-07-30 at 14 09 56

**Review by hassnian — APPROVED** [review]

**Comment by Jarsen136** [comment]
cf build failed
image

**Review by vikiival — CHANGES_REQUESTED** [review]
build is failing

**Comment by preschian** [comment]
should be fine now, not related to this PR

Screenshot 2024-07-31 at 06 05 15

**Review by vikiival — APPROVED** [review]

**Pull request merged**
