### PR TITLE
fix: use workbox-window package

### LINKED ISSUE #4727: service worker / pwa fetch new update doesn't show up
It seems after the update of 
- #4713 

it doesn't update the client anymore. 
I did not get any new toast, or at least I still have on https://beta.kodadot.xyz all languages 
yet when I open it in incognito, I see only a new one 

current state
image

incognito 
image

I guess it's because it doesn't generate proper sw.js ? service worker where old instance was listening? 
edit seems is there, old one doesn't switch for new one?
- https://beta.kodadot.xyz/sw.js

image

## Documentation

Probably needs custom workbox service worker? 

- https://github.com/kevinmarrec/nuxt-pwa-module

- https://github.com/kodadot/nft-gallery/blob/main/nuxt.config.js#L246 🤔

## Ref 
- #4723

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #4727. previously workbox instance was `undefined`. add `workbox-window` to fix that

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by roiLeo** [comment]
> is it safe if I remove gtm script? seems like a newer version of workbox is unable to cache gtm script. this is the error count from the workbox 

Why would you want to remove it? we use it to integrate google analytics
maybe try to update package to vue3 version or disable plugin in dev mode

**Review by roiLeo — CHANGES_REQUESTED** [review]
I would like to keep a tracking service

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 33.44 USD/KSM ~ 1.495 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0xccd9a0bc23572cdd8ed8017109f7ce4dc57d840dc839e83a44172862ff89d67b](https://kusama.subscan.io/extrinsic/0xccd9a0bc23572cdd8ed8017109f7ce4dc57d840dc839e83a44172862ff89d67b)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
pay 50

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 35.12 USD/KSM ~ 1.424 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0xb16588591157ea256423fb5cd0381490be5aa89ff76b19f73fea3b612b64a402](https://kusama.subscan.io/extrinsic/0xb16588591157ea256423fb5cd0381490be5aa89ff76b19f73fea3b612b64a402)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
