### PR TITLE
ci: disable sentry on build

### LINKED ISSUE #6660: Collection and profile pages down
Collection page: 
https://canary.kodadot.xyz/ahk/collection/32
telegram-cloud-photo-size-4-5956027051867748678-y

https://canary.kodadot.xyz/ahk/collection/8
image

- profile is not working as well on the network

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## Context

- [x] Related #6518
- [x] Related #6660

hi, let's try to disable sentry until we find what the rootcause is?

### CODE REVIEW

**Comment by yangwao** [comment]
> hi, let's try to disable sentry until we find what the rootcause is?

yesss

**Comment by yangwao** [comment]
I was checking why we are down again :D 

image

**Comment by preschian** [comment]
interesting, still fails even disabled sentry plugin 🤔

**Comment by preschian** [comment]
works fine on netlify 🥲

**Pull request merged**
