### PR TITLE
#6387 alignment fix

### LINKED ISSUE #6387: Search bar results alignment
- I missed the pr to comment it, so here is followup
- #6370 

can we align these tabs to left 
image

like here 
image

+ make the user(soon) grey color since its disabled

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #6387
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)

## Screenshot 📸

- [x] My fix has changed UI
Screen Shot 2023-07-05 at 4 16 51 PM
Screen Shot 2023-07-05 at 4 17 12 PM

### CODE REVIEW

**Review by preschian — APPROVED** [review]

**Review by roiLeo — CHANGES_REQUESTED** [review]
Hey!
Design should look like [this](https://www.figma.com/file/3iOjW12ERFRDSVnpLuhQmf/landing-page-handoff?node-id=1305%3A5613&mode=dev) 

ref https://github.com/kodadot/nft-gallery/pull/6370#pullrequestreview-1510459213

edit: did someone overwritte the changes?

**Comment by preschian** [comment]
> edit: did someone overwritte the changes?

from this PR maybe https://github.com/kodadot/nft-gallery/pull/6231

**Comment by prachi00** [comment]
uh I see the pink border, did it not get removed in #6370  , should it be removed again? 
@roiLeo @exezbcz

**Comment by exezbcz** [comment]
image
the issue was created only for aligning the tab sections to left - the rest was working nicely

- the divider is not an active state indicator - that means it should always have k-shade color

image
- 32px padding, please

**Comment by prachi00** [comment]
Screen Shot 2023-07-08 at 3 20 40 PM
@exezbcz

**Comment by prury** [comment]
> Screen Shot 2023-07-08 at 3 20 40 PM @exezbcz

I believe the padding also applies to this part:
image

also: the proportion of the top and left padding also seems odd

**Comment by exezbcz** [comment]
@prury Yup, correct, it should be a divider. Please see the design

**Comment by prachi00** [comment]
Screen Shot 2023-07-10 at 8 44 33 PM

updated

**Comment by prachi00** [comment]
can me merge this one?

**Review by preschian — APPROVED** [review]

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
pay 10 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $10 @ 5.18 USD/DOT ~ 1.931 $DOT
🧗 [13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1](https://polkadot.subscan.io/account/13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)
🔗 [0x41ca6965e588a3ca71805db05f1ff90fb02a36430ccb94efe4f893e52c1daf5d](https://polkadot.subscan.io/extrinsic/0x41ca6965e588a3ca71805db05f1ff90fb02a36430ccb94efe4f893e52c1daf5d)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
