### PR TITLE
refactor: execMintStatemine and execMintStatemine

### PR DESCRIPTION
**Pull request by floyd-li**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

to resolve this one:
图片

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Part of #6782
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at cd51297</samp>

Refactored the minting logic for Basilisk and Statemine tokens by using a common `transactionFactory` function. This reduced code duplication and improved readability. Added the `transactionFactory` function to `./composables/transaction/mintToken/utils.ts`.

### <samp>🤖 Generated by Copilot at cd51297</samp>

> _We're minting tokens on the chain, me hearties_
> _We're using `transactionFactory` to make it easy_
> _We've refactored the code and removed the clutter_
> _So pull on the rope and sing with me, one, two, three!_

### CODE REVIEW

**Comment by yangwao** [comment]
> Code Climate has analyzed commit [cd51297](https://github.com/kodadot/nft-gallery/commit/cd512974dbd15034b11d76ec3650c3d945c99fec) and detected **3 issues** on this pull request.

Solving 2 code climate issues, code climate raises 3 more issues 😄

**Review by stephenjason89 — APPROVED** [review]
Code lgtm 😊

**Comment by yangwao** [comment]
great!
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 4.5 USD/DOT ~ 11.111 $DOT
🧗 [13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A](https://polkadot.subscan.io/account/13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A)
🔗 [0x5180a160fcd07fcf1962c9a7f70880e43df7d9d9e38239968f3980bd566edc38](https://polkadot.subscan.io/extrinsic/0x5180a160fcd07fcf1962c9a7f70880e43df7d9d9e38239968f3980bd566edc38)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by Jarsen136** [comment]
image

@floyd-li Hey, there is something broken here.

**Comment by floyd-li** [comment]
> image
> 
> @floyd-li Hey, there is something broken here.

sry my bad there's a constant naming issue. gonna make a quick pr for it.

**Pull request merged**
