### PR TITLE
feat: Add volume sort to ExploreSort

### LINKED ISSUE #5678: Sort collections by volume
I heard @Matehoo knows more 👀

image

### PR DESCRIPTION
**Pull request by Matehoo**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #5678 
- [x] Requires deployment kodadot/snek#170
- [x] Requires deployment kodadot/rubick

#### Before submitting pull request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screenshot 2023-04-17 at 12 45 48

### CODE REVIEW

**Review by roiLeo — CHANGES_REQUESTED** [review]
I don't see any sorting by volume option in `collectionEntities`

**Comment by Matehoo** [comment]
Volume sorting is supported in latest unreleased indexer, no ETA on the release (but should be soon)

**Comment by roiLeo** [comment]
> Volume sorting is supported in latest unreleased indexer, no ETA on the release (but should be soon)

This is changed only on rubick indexer, we need to change `CollectionEntity` Schema in [kodadot/snek](https://github.com/kodadot/snek) repo to make it work on bsx chain

**Comment by Matehoo** [comment]
> This is changed only on rubick indexer, we need to change `CollectionEntity` Schema in [kodadot/snek](https://github.com/kodadot/snek) repo to make it work on bsx chain

Oh shoot, you are right, that change was not merged yet (https://github.com/kodadot/snek/pull/170).
When it is merged ILYK

**Comment by yangwao** [comment]
> Volume sorting is supported in latest unreleased indexer, no ETA on the release (but should be soon)

```
"id": 4638,
"name": "v3",
"squidName": "marck",
"status": "SYNCED",
"syncStatus": {
"totalBlocks": 17722593,
"currentBlock": 17722593
```

marckV3 seems synced, is it stable already @vikiival ?

**Comment by vikiival** [comment]
Synced and using on prod

**Comment by Matehoo** [comment]
> @Matehoo this can go out I guess?

@vikiival are all indexers with this feature in prod?

**Comment by roiLeo** [comment]
> * snek: Yes https://squid.subsquid.io/snekk/graphql

please release 004 as this won't work on `snek`

**Review by roiLeo — APPROVED** [review]
snek `https://squid.subsquid.io/sneck/graphql` has been released in #6125

**Review by preschian — APPROVED** [review]

**Review by daiagi — DISMISSED** [review]

**Comment by vikiival** [comment]
@preschian looks like sneck is back again? 

- also I am happy to release rubick 
- https://github.com/kodadot/loligo/issues/25

**Comment by Matehoo** [comment]
> @preschian looks like sneck is back again?
> 
> * also I am happy to release rubick
> * [Make new deployment config loligo#25](https://github.com/kodadot/loligo/issues/25)

@vikiival Do you have ETA for rubick release?

**Comment by vikiival** [comment]
Made low budget release of **rubick**

- https://github.com/kodadot/rubick/pull/266


should be up soon

- https://github.com/kodadot/rubick/actions/runs/5831018634

**Comment by vikiival** [comment]
Screenshot 2023-08-11 at 12 58 36

Making new release yolo

**Comment by roiLeo** [comment]
> Making new release yolo

Please don't forget snekk 004

**Comment by vikiival** [comment]
oof so short adventure 

- https://github.com/kodadot/rubick/pull/268

**Comment by vikiival** [comment]
> > Making new release yolo
> 
> Please don't forget snekk 004

I already made deploy for it 

https://app.subsquid.io/squids/sneck/v1

> CREATED: 28.05.2023

**Comment by roiLeo** [comment]
> > > Making new release yolo
> > 
> > 
> > Please don't forget snekk 004
> 
> I already made deploy for it
> 
> https://app.subsquid.io/squids/sneck/v1
> 
> > CREATED: 28.05.2023

Oooh didn't knew about that one, then we need to update snek endpoint (we still query 004)

**Comment by vikiival** [comment]
Screenshot 2023-08-11 at 16 12 39

**Comment by vikiival** [comment]
Another issue with same code :)))))))

- https://github.com/kodadot/rubick/pull/272

Screenshot 2023-08-14 at 16 10 50

**Comment by yangwao** [comment]
any updates?

**Comment by vikiival** [comment]
> any updates?

rubick updated in 4eb48a1a5a2984d51a6d6e1334f7d035709ae1cf

**Comment by yangwao** [comment]
@prury can you check this one 😌 and then let's merge it

**Comment by prury** [comment]
RMRK 1 and 2:
image

**Comment by vikiival** [comment]
Oki thanks will recheck

**Comment by roiLeo** [comment]
> Can we have it merged?

Not yet

**Comment by vikiival** [comment]
> Can we have it merged? 

Do you remember what was the issue with marck v3? 🥺

It is needed for this. 
And for some reason we reverted that

**Comment by yangwao** [comment]
> Do you remember what was the issue with marck v3? 🥺

no, link to issue?

> It is needed for this.

maybe do some hotfix or exclude volume sort for that for now.

**Comment by vikiival** [comment]
> no, link to issue?

https://github.com/kodadot/nft-gallery/issues/5853

Most probably this was the reason

**Comment by yangwao** [comment]
> Most probably this was the reason

But that's 4 mo old?

**Comment by vikiival** [comment]
Won't make it for now

**Pull request closed without merging**
