### PR TITLE
fix: Redirect to incorrect place after click on collection on navbar

### LINKED ISSUE #4133: Redirect to incorrect place after click on collection on navbar
### What happened?

Click on the `collection` button on navbar.
Then it does not lead to collection tab.
image

image

### Please reproduce in steps

Click on the `collection` button on navbar.

### Expected Behavior

image

### What browsers are you seeing the problem on?

_No response_

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

_No response_

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

_No response_

### Screenshots

redirect to collection tab page

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #4133 

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by yangwao** [comment]
pay 30

**Review by yangwao — APPROVED** [review]
yes

**Comment by yangwao** [comment]
pay 30

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
pay 30 usd 

seems webhooks or something is slowing down bot 👀

**Comment by Jarsen136** [comment]
> pay 30 usd
> 
> seems webhooks or something is slowing down bot 👀

Hey, I did not put the payment link there. It's a small fix.

**Comment by Jarsen136** [comment]
By the way, could you pls check this issue?  @yangwao 
https://github.com/kodadot/nft-gallery/pull/4048#issuecomment-1276897606

**Comment by yangwao** [comment]
> Hey, I did not put the payment link there. It's a small fix.

lmao, I'm going too fast ;D

**Pull request merged**
