### PR TITLE
fix: bring back responsive navbar

### LINKED ISSUE #4042: Responsive navbar be gone?
Seems on 1054px width it does this, can't log out 

1024-1215 range 

image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #4042 
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
1025px:   
image

1214px: 
image

### CODE REVIEW

**Comment by petersopko** [comment]
this is 1034px @ windows/chrome setup 
image

**Review by petersopko — COMMENTED** [review]
minor adjustment pls

**Comment by Jarsen136** [comment]
How about now? 👀 
1025px on mac chrome
image

**Comment by petersopko** [comment]
goood, works for me :rocket

**Review by petersopko — APPROVED** [review]

**Comment by yangwao** [comment]
pay 50

**Comment by Jarsen136** [comment]
pay 50

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 37.57 USD/KSM ~ 1.331 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x4b24d7f1a00d8f8fc45bdac4859cf106be6a7646c4fc85c47056f56401044483](https://kusama.subscan.io/extrinsic/0x4b24d7f1a00d8f8fc45bdac4859cf106be6a7646c4fc85c47056f56401044483)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
