### PR TITLE
fix: buy not working on rmrk2

### LINKED ISSUE #5370: Buy not working on rmrk2
image
image

- close this if its a duplicate

nft: https://beta.kodadot.xyz/rmrk2/gallery/14049591-b46a62619cb12c7a15-LUM-A-G-0401_487_MB_GREGORY_THE_ILLUMINATOR-00000401

### PR DESCRIPTION
**Pull request by floyd-li**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5370
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EZiu1PjV2j2JHKxY6mHnFwwCRCoV27uHKQSkKXATSh1srJT)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image
image

### CODE REVIEW

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
Does rmrk2 emits correct string?

**Comment by floyd-li** [comment]
> Does rmrk2 emits correct string?

sorry i don't understand what did you mean?

**Comment by vikiival** [comment]
> * Buy not working on rmrk2 #5370

Screenshot 2023-03-28 at 14 45 31

**Review by vikiival — APPROVED** [review]
pay 10 usd

**Comment by vikiival** [comment]
pay 10 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $10 @ 34.57 USD/KSM ~ 0.289 $KSM
🧗 [EZiu1PjV2j2JHKxY6mHnFwwCRCoV27uHKQSkKXATSh1srJT](https://kusama.subscan.io/account/EZiu1PjV2j2JHKxY6mHnFwwCRCoV27uHKQSkKXATSh1srJT)
🔗 [0xb5a3a36865d5ce8fd2c095060a9b6806aa50b574096d9dcad40ac3345bc410f8](https://kusama.subscan.io/extrinsic/0xb5a3a36865d5ce8fd2c095060a9b6806aa50b574096d9dcad40ac3345bc410f8)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
