### PR TITLE
style: navbar menu on mobile

### LINKED ISSUE #6331: Connect button on Nova wallet is kinda off
I opened Nova Wallet and I wanted to log in. Connect button appeared like this: 

IMG_4011

Connect button is on top of the other text (light mode).

Maybe also be good to add an option to connect to your wallet on the main landing page (with no need to open the menu)? Just a suggestion. Or just put connect on the top of the list

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [x] Style

## Needs Design check

- @exezbcz please review

## Context

- [x] Closes #6331

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)

## Screenshot 📸

- [x] My fix has changed UI

Screenshot 2023-08-20 at 11 30 35 AM

### <samp>🤖 Generated by Copilot at bb72158</samp>

Improved the layout and responsiveness of the main navigation bar. Added a button to connect a wallet using the `button-connect-wallet` class.

### <samp>🤖 Generated by Copilot at bb72158</samp>

> _The navbar items had too much padding_
> _So the developer did some editing_
> _He made them responsive_
> _And removed the excessive_
> _Styles for `#NavProfile` and added `button-connect-wallet` fitting_

### CODE REVIEW

**Comment by preschian** [comment]
@exezbcz, how about this one? Smaller padding on the navbar item, but still more than 48px for the touch point. ref: material.io/develop/web/supporting/touch-target

**Comment by preschian** [comment]
oh wait still didnt show on safari ios

**Comment by exezbcz** [comment]
so from what i see, every nav item has now smaller height
image
- the connect as well. 

If this will ensure responsiveness on nova wallet, let's go


One small thing, I know its not part of the issue - could you please fix the text in the button in dark mode 
image
- should be black

**Comment by preschian** [comment]
> so from what I see, every nav item now has smaller height

yes correct. I made it smaller, but still more than > 48px. because based on google design, touch point for mobile is min 48x48

> One small thing, I know its not part of the issue - could you please fix the text in the button in dark mode

sure, let me update that

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 4.48 USD/DOT ~ 11.161 $DOT
🧗 [1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p](https://polkadot.subscan.io/account/1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)
🔗 [0x073cbd9a17ae6cdb57f521c0ff5370bff566db3d30555cb176137c99aecdba3d](https://polkadot.subscan.io/extrinsic/0x073cbd9a17ae6cdb57f521c0ff5370bff566db3d30555cb176137c99aecdba3d)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
