### PR TITLE
fix: option to show prices by default in user profile

### LINKED ISSUE #2139: Show prices when BUY now is on artist profile
I guess we should check to show prices by default when the user turns on buy now on the artist profile in the same manner as it on gallery view.

@kkukelka was making PR before so might be handy to do this? 

image

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

https://user-images.githubusercontent.com/17953978/151925854-da2e9016-db3e-41d6-9c40-42e0517a050c.mov

### What's new?

- [x] PR closes #2139
- [x] add prices-by-default functionality to user profile

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/u/JEqHBWjSQrVZi4AU42xPxKYs4ReZWSuSjLAoegPyzSzwhoY>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by roiLeo** [comment]
recording

Is this the expected behavior? I can see the prices while the checkbox is not active


<details><summary>Browser metadata</summary>





```
Path:      /settings?tab=advanced
Browser:   Firefox 97.0 on Mac OS 10.15
Viewport:  1920 x 995 @1x
Language:  en
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2149--koda-nuxt.netlify.app%2Fsettings%3Ftab%3Dadvanced&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=97.0&resolution=1920x995&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-2149--koda-nuxt.netlify.app/settings?tab=advanced) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=61f8dbd8626be40008d315d0&commentID=61f8e6140a7b796d332938fc&resolution=resolved)

**Comment by kkukelka** [comment]
> Is this the expected behavior? I can see the prices while the checkbox is not active

In this case, I believe you have "Buy On" activated on Gallery Page
Click on Filter Icon and it will show up in the dropdown.

**Comment by roiLeo** [comment]
> In this case, I believe you have "Buy On" activated on Gallery Page Click on Filter Icon and it will show up in the dropdown.

Yup! it felt strange to have checkbox uncheck & price on.

**Comment by yangwao** [comment]
> > In this case, I believe you have "Buy On" activated on Gallery Page Click on Filter Icon and it will show up in the dropdown.
> 
> Yup! it felt strange to have checkbox uncheck & price on.

We would like to show you by default NFTs which you can grab and if you turn off buy now, would show prices only on NFTs which are for sale. 
Maybe you did uncheck and been in moment or state there was already last 9-12 NFTs for SALE?

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 164.81 USD/KSM ~ 0.607 $KSM
🧗 [EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW](https://kusama.subscan.io/account/EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)
🔗 [0xd77705693cc6fec65d6f52156ffe6c39791c4e0e41be2c741a7ce34eb30e10c4](https://kusama.subscan.io/extrinsic/0xd77705693cc6fec65d6f52156ffe6c39791c4e0e41be2c741a7ce34eb30e10c4)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
