### PR TITLE
fix: invisible close btn in modal

### LINKED ISSUE #3914: modal: close button not visible in light mode
In KeyboardShortcutModal component the close button is not visible, should be the same on QRcode modal

Capture d’écran 2022-09-05 à 12 20 04 PM

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3914
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

image

### CODE REVIEW

**Comment by Jarsen136** [comment]
> 



> 👀 hiden text Capture d’écran 2022-09-05 à 5 33 39 PM
> 
> would it be possible that the modal take the content width? as it feels a bit weird Screenshot 2022-09-05 at 17-34-57 ~ KodaDot - Kusama NFT Market Explorer

will check

**Comment by Jarsen136** [comment]
image

image

✅  Fixed

**Review by kkukelka — APPROVED** [review]
lgtm

**Review by roiLeo — APPROVED** [review]
Nice!
small note: https://caniuse.com/?search=fit-content

**Review by kkukelka — APPROVED** [review]

**Comment by petersopko** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 52.77 USD/KSM ~ 0.948 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xc3db034f63d1a455eaf7d457068bafc788779560871b9e3776fbc89fa66b1520](https://kusama.subscan.io/extrinsic/0xc3db034f63d1a455eaf7d457068bafc788779560871b9e3776fbc89fa66b1520)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
