### PR TITLE
fix: cart action button

### LINKED ISSUE #7769: cart action button
image
- should be the primary big button - same as in modals, gallery item, etc

### PR DESCRIPTION
**Pull request by Jarsen136**
## PR Type

  - [x] Bugfix

  ## Needs Design check

  - @exezbcz please review

  ## Context

  - [x] Closes #7769

  ## Screenshot 📸

  - [x] My fix has changed UI

image

### CODE REVIEW

**Review by daiagi — APPROVED** [review]

**Comment by exezbcz** [comment]
could you please apply the same style to the mass list button? 
image


thanks a lot!

**Comment by Jarsen136** [comment]
> could you please apply the same style to the mass list button? ![image](https://user-

✅ Done

**Review by roiLeo — COMMENTED** [review]
or what if we use at least once `size` prop on button (medium or large)

if it's still not the right size you can try to tweak `--oruga-button-font-size-*`

**Review by preschian — APPROVED** [review]

**Comment by Jarsen136** [comment]
> or what if we use at least once `size` prop on button (medium or large)
> 
> if it's still not the right size you can try to tweak `--oruga-button-font-size-*`

OK. It also works.

**Review by roiLeo — APPROVED** [review]
👍 nice

**Pull request merged**
