### PR TITLE
fix(ui): sidebar collapse animation issue

### PR DESCRIPTION
**Pull request by floyd-li**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

this issue was mentioned by @roiLeo 
https://github.com/kodadot/nft-gallery/pull/5235#pullrequestreview-1335927496

tested on chrome/firefox/safari work well

https://user-images.githubusercontent.com/16473062/226096875-df77ab25-8654-40c6-be76-d7b1fdb732d3.mp4

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [ ] Closes #<issue_number>
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EZiu1PjV2j2JHKxY6mHnFwwCRCoV27uHKQSkKXATSh1srJT&usdamount=0&donation=true)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

https://user-images.githubusercontent.com/16473062/226096878-72e57414-9e41-467b-bfa0-0156d9b5ab72.mp4

### CODE REVIEW

**Comment by vikiival** [comment]
pay 9 usd

**Comment by floyd-li** [comment]
@yangwao did you make the transfer?

**Comment by floyd-li** [comment]
@vikiival seems the transfer is not sent 🤔️

**Comment by vikiival** [comment]
pay 9 usd

**Comment by vikiival** [comment]
Probably your address is not correct, please check it

**Comment by vikiival** [comment]
pay 10 usd

**Pull request merged**
