### PR TITLE
feat: Display success message after transaction is in block

### LINKED ISSUE #10231: Display success message after transaction is in block
**Display success message after transaction is in block** 

with @vikiival we discussed that it should be possible (preview should be already ready to display in the modal" 

Why it would be nice? Since the block time is quite long, and it takes ~30 seconds from signing to success, displaying the success message a bit earlier would decrease waiting times and make Polkadot feel a bit faster 

## Design and changes 
- after a transaction is in the block, display a success message 
- success message will have a different transaction status

image
https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=6886-20058&mode=design&t=neRjoavRuafpIGjV-11

When it gets confirmed, it switches to the "confirmed status"

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

changed normal and auto-teleport flow of:

- create collection
- buy nft
- list nft

@prury pls test all these flows

note: mint drop will be a follow up,  [blocked by](https://github.com/kodadot/nft-gallery/issues/10231#issuecomment-2110473760)

- [x] Closes #10231

## Needs QA check

- @kodadot/qa-guild please review

## Needs Design check

- @exezbcz please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

## normal

https://github.com/kodadot/nft-gallery/assets/44554284/769e81e1-e2ed-4f83-8c67-971b4312e51d

## autotelport 

https://github.com/kodadot/nft-gallery/assets/44554284/d5bb9d73-3efc-465c-bbbd-61ae3297d3f6

## create collection with autotelport 

https://github.com/kodadot/nft-gallery/assets/44554284/bb11ac32-94d4-41c0-acab-5f3fc901ff77

## listing cart autoteleport 

https://github.com/kodadot/nft-gallery/assets/44554284/13d895f8-e0a3-4ffe-9b11-d066f4b2ea30

### CODE REVIEW

**Comment by prury** [comment]
superb testing @hassnian!

**Comment by prury** [comment]
only i could not test was collection creation, as success modal does not open here for me(issue opened), but the other interactions work fine.

**Comment by hassnian** [comment]
> And i guess for NFT creation we still don't show success modal?

nope we don't have one implanted, I guess it would be the same as the successful drop modal . cc @exezbcz

**Review by daiagi — APPROVED** [review]

**Comment by vikiival** [comment]
cc @preschian can you please review?

**Review by preschian — APPROVED** [review]

**Pull request merged**
