### PR TITLE
fix: Unable to mint continuously on ahk

### LINKED ISSUE #8054: Unable to mint on ahk
- account: [GCFRnbhJSEUWGfbPA3LvU2T1eRAtRDP722mm65GeNEsbVYD](https://assethub-kusama.subscan.io/extrinsic?address=GCFRnbhJSEUWGfbPA3LvU2T1eRAtRDP722mm65GeNEsbVYD)
- token id is the same, minting is in error

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix

  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #8054
  - [ ] Requires deployment <snek/rubick/worker>

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [ ] My fix has changed UI

image

  ## Copilot Summary
  
### <samp>🤖 Generated by Copilot at 20d5b2f</samp>

Improved token minting logic for Statemine collections by querying the chain for the last used token id and avoiding id collisions. Modified `transactionMintStatemine.ts` to implement this logic.

  
### <samp>🤖 Generated by Copilot at 20d5b2f</samp>

> _Sing, O Muse, of the skillful coder who devised_
> _A cunning scheme to mint the tokens of the chain,_
> _Avoiding the dread peril of colliding ids_
> _That would mar the beauty of the digital domain._

### CODE REVIEW

**Comment by prury** [comment]
Minted the second one right after the first one succeed:  
First: https://deploy-preview-8075--koda-canary.netlify.app/ahk/gallery/224-11
https://assethub-kusama.subscan.io/tx/0xf265eba020bd9ed39954c51d347f7625ba87b498e259256dbcdd6f80e86d8dd6

Second: https://deploy-preview-8075--koda-canary.netlify.app/ahk/gallery/224-12
https://assethub-kusama.subscan.io/tx/0x80618d06b25fc27166ae442a49c32c36e8f47e1abc7245ec8a4cd18a21c1c3d4

waiting for indexer to show images...

**Review by roiLeo — APPROVED** [review]

**Comment by Jarsen136** [comment]
TODO:

- [ ] Adjust unit test accordingly : )

**Comment by prury** [comment]
@Jarsen136 lmk if more tests are required

**Comment by daiagi** [comment]
>id an additional test by trying to trigger another transactions while the other was still pending
result: only the first one was minted and the second was cancelled:

that's expected, need to wait a little while longer

**Comment by daiagi** [comment]
@prury  please test mass mint as well

**Comment by Jarsen136** [comment]
> Ahp: NFT 1 https://deploy-preview-8075--koda-canary.netlify.app/ahp/gallery/39-2 https://assethub-polkadot.subscan.io/tx/0x4788035b67b5e17434d97be0ae2be545c7bb0821d862f61c1e553405804434e1
> 
> NFT 2 https://deploy-preview-8075--koda-canary.netlify.app/ahp/gallery/39-3 https://assethub-polkadot.subscan.io/tx/0x2f87af34cf07447fad17c70fc4122e89384c26e0b39001141537c439bfab6fb7
> 
> did an additional test by trying to trigger another transactions while the other was still pending result: only the first one was minted and the second was cancelled: image

It's as expected. The second one should wait for the first one to be minted successfully first.

**Comment by Jarsen136** [comment]
> @prury please test
> 
> 1. mass mint
> 2. multiple copies
> 3. combination: i.e. mint in fast succession 1 nft with multiple copies and then another 1
> 
> if it is possible to add these kinds of tests to the automated tests that would be great. 

It's a good idea. We could leave it on another issue to add more test cases. 

> but I guess that requires a test network right?

Probably we could mock the API interface instead of fetching data from the test network.

**Review by preschian — APPROVED** [review]
nice 👍

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 5.71 USD/DOT ~ 5.254 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x070967b7d6bd54b9e10849c281f5ef0173bcbfff3eb3b96776c5e66ee311b6ef](https://polkadot.subscan.io/extrinsic/0x070967b7d6bd54b9e10849c281f5ef0173bcbfff3eb3b96776c5e66ee311b6ef)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
