### PR TITLE
fix: unit display on snek network

### LINKED ISSUE #5819: fix the `unit` display on `snek` item
reproduce link: https://beta.kodadot.xyz/snek/gallery/2773267381-1

image

_Originally posted by @floyd-li in https://github.com/kodadot/nft-gallery/issues/5774#issuecomment-1525760559_

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5819
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

image

### <samp>🤖 Generated by Copilot at 4408de1</samp>

Removed hardcoded value from `getKusamaAssetId` function in `utils/api/bsx/query.ts`. This allows the function to return the correct asset id for the Kusama network based on the input network name.

### <samp>🤖 Generated by Copilot at 4408de1</samp>

> _No more `return 5`_
> _`getKusamaAssetId` works_
> _With `networks` object_

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
Not sure about that one:
```
    // '0' if paying in bsx (on Basilisk and Snek)
    // '1' if paying in ksm (on basilisk)
    // '5' if paying in ksm (on Snek)
```

**Comment by Jarsen136** [comment]
> Not sure about that one:
> 
> ```
>     // '0' if paying in bsx (on Basilisk and Snek)
>     // '1' if paying in ksm (on basilisk)
>     // '5' if paying in ksm (on Snek)
> ```

Could you pls review this? @vikiival 👀

**Comment by vikiival** [comment]
Yes this is still correct

Screenshot 2023-04-28 at 17 18 49

**Review by vikiival — CHANGES_REQUESTED** [review]
This would point to Phala token on snek

**Comment by Jarsen136** [comment]
Query `assetList` does not return the asset id of `5`, that's why we have the `unit` display. So I think it's a resolver issue related to snek squid side.

image

**Comment by vikiival** [comment]
SNEK (rococo)

```
https://squid.subsquid.io/snekk/v/004/graphql
```

Screenshot 2023-04-29 at 13 54 57

BSX

```
https://squid.subsquid.io/snekk/v/005/graphql
```

Screenshot 2023-04-29 at 13 55 45

**Comment by Jarsen136** [comment]
> SNEK (rococo)
> 
> ```
> https://squid.subsquid.io/snekk/v/004/graphql
> ```
> 
> BSX
> 
> ```
> https://squid.subsquid.io/snekk/v/005/graphql
> ```
> 
Thanks for checking the query. Then I got the root reason why it does not work. Please review the code again.

**Review by vikiival — APPROVED** [review]
Nice one

**Review by roiLeo — APPROVED** [review]
Wfm, I think I'll remove this plugin in #5655

**Comment by roiLeo** [comment]
Hello, something might be wrong with this change (tested on `/snek/create`)
Screenshot 2023-05-02 at 09-03-53 KodaDot Low fees and low carbon minting KodaDot - NFT Market Explorer

**Comment by vikiival** [comment]
> This would point to Phala token on snek

cc @roiLeo

**Comment by vikiival** [comment]
> Hello, something might be wrong with this change

My bet is that someone changed the token number for snek (propably check assetList)

**Comment by roiLeo** [comment]
> My bet is that someone changed the token number for snek (propably check assetList)

I think I made a change recently on `Money` component that might be related

**Pull request merged**
