### PR TITLE
add average gain on flippers

### LINKED ISSUE #2820: For flippers table use average gain instead of total investment / total profit
So in the off-chain convo with @yangwao we iterated to the point where the current best metric would be to show is `average flip` 

What it means? 

https://github.com/kodadot/nft-gallery/pull/2804#issuecomment-1094930071

If you look on the table
Screenshot 2022-04-11 at 13 38 21

the first number should become (`46,66`)
photo_2022-04-11 13 55 18

it's the `sum of all percetage changes / number of items`

📟 @Jarsen136

_Originally posted by @vikiival in https://github.com/kodadot/nft-gallery/issues/2804#issuecomment-1094961779_

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2820
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [x] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

### CODE REVIEW

**Review by vikiival — COMMENTED** [review]
I would remove the red color :) 

OTHERWISE LGTM

**Comment by Jarsen136** [comment]
> I would remove the red color :) 
> 
> 
> 
> OTHERWISE LGTM

😅alright. btw, why we prefer to change the requirement in the pr instead of in the issue description

**Comment by Jarsen136** [comment]
@vikiival  hi, it seems forgot to pay bounty 
Wonder if it still need to remove the red color in percentage column 👀

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 131.24 USD/KSM ~ 0.381 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xef6410b1666d40bc95d4065e810e19d25631422981b3cd4bb318cd5d42cc673d](https://kusama.subscan.io/extrinsic/0xef6410b1666d40bc95d4065e810e19d25631422981b3cd4bb318cd5d42cc673d)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
