### PR TITLE
🐛 holders/flippers redirect link

### LINKED ISSUE #5156: redirect from flipper/holder tab to nft not working
image
- try clicking a nft here

https://beta.kodadot.xyz/rmrk/collection/7E982817A2D2575031-KDMN?tab=holders&page=1

### PR DESCRIPTION
**Pull request by petersopko**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5156
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [x] I've tested it at </bsx/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
Hey! I've seen we still have 1 results for `${urlPrefix}-gallery-id` in `History` component, would it be possible to fix it in this PR too?

**Comment by petersopko** [comment]
> Hey! I've seen we still have 1 results for `${urlPrefix}-gallery-id` in `History` component, would it be possible to fix it in this PR too?

🫡

**Review by roiLeo — APPROVED** [review]

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
pay 15 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $15 @ 35.01 USD/KSM ~ 0.428 $KSM
🧗 [FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y](https://kusama.subscan.io/account/FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y)
🔗 [0xc2fd072b2161806cd8ba4398cc9534a7bf808fe1ef94a8f988bac32ebed0900f](https://kusama.subscan.io/extrinsic/0xc2fd072b2161806cd8ba4398cc9534a7bf808fe1ef94a8f988bac32ebed0900f)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
