### PR TITLE
feat: use existing metadata when retry happen on minting

### LINKED ISSUE #3700: Retry minting pins same file again?
I guess it's not behaviour we want to have?
If the already file is there, we should not try uploading it again?

image

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3700 

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged the recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by preschian** [comment]
in this PR, use existing metadata when retry occurs. so not call the pin function multiple
feel free to close this PR in case this is not needed
cc @yangwao @petersopko 

https://user-images.githubusercontent.com/734428/183587065-ba6e4a83-4c1f-4cc9-8db7-8af95eb7caa7.mov

**Review by prachi00 — APPROVED** [review]
Code LGTM, I am not sure how to test this though

**Comment by preschian** [comment]
can't mint after update from main branch https://github.com/kodadot/nft-gallery/issues/3541#issuecomment-1210466667
will check later

**Comment by preschian** [comment]
nevermind, @vikiival already fix the error here https://github.com/kodadot/nft-gallery/pull/3709

**Comment by preschian** [comment]
> Code LGTM, I am not sure how to test this though

yaps, for this case a bit hard to test in a real-world scenario. I mocked in my local to trigger the `retry` function

similar to this PR https://github.com/kodadot/nft-gallery/pull/3554

**Comment by DeluneClaire** [comment]
Is this something that should happen? I'm not sure how to test the retry.

https://user-images.githubusercontent.com/104791453/184135779-e26a9d72-0798-4160-afe0-1615cc3d60b6.mov

**Comment by preschian** [comment]
> Is this something that should happen? I'm not sure how to test the retry.
> 
>  Zaznam.obrazovky.2022-08-11.v.14.41.27.mov

oohh, I think you found edge cases
did you close the popup after the sign request? and then you click the create nft button again?

when the popup is closed, the network is still in progress. I think we have two options to tackle this
1. set the button to loading when the network is still in progress
2. or make the popup not closeable

**Comment by DeluneClaire** [comment]
I clicked only on the create NFT button again.

**Comment by vikiival** [comment]
> But look this is super strange... it's living its own life.

That means you posted same transaction twice

**Comment by DeluneClaire** [comment]
So is this somehow fixed? Because I'm not sure how to test this...

**Review by DeluneClaire — APPROVED** [review]

**Comment by DeluneClaire** [comment]
This still needs to be tested, I add approve here by mistake

**Comment by preschian** [comment]
btw, since we have this PR https://github.com/kodadot/nft-gallery/pull/3711
maybe we can move these issues to that PR instead? so we can close this PR instead, wdyt?
cc @yangwao @petersopko @Jarsen136 

list of issues:
- https://github.com/kodadot/nft-gallery/issues/3700
- https://github.com/kodadot/nft-gallery/pull/3702#issuecomment-1211983233

**Comment by preschian** [comment]
another way to reproduce flooded pinata requests:
1. click "create nft" button
2. close popup
3. repeat several times

how about disabling the popup from being able closed by the user in the middle of processing?
close the popup before signing or after signing the request will cause an error

| before | after |
| --- | --- |
| https://user-images.githubusercontent.com/734428/184703514-292442e3-72e0-4940-b4a2-35547351e663.mov | https://user-images.githubusercontent.com/734428/184704221-6b935d97-b5f3-46f5-8787-c32f004ea166.mov |

**Comment by petersopko** [comment]
> Code LGTM, I am not sure how to test this though

image

**Review by petersopko — APPROVED** [review]
alright, wfm

**Comment by petersopko** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 54.64 USD/KSM ~ 0.549 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0xf1809c921e6bad42f24565b0efa323b98168c40fc78b2cddb5643a9562c87984](https://kusama.subscan.io/extrinsic/0xf1809c921e6bad42f24565b0efa323b98168c40fc78b2cddb5643a9562c87984)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
