### PR TITLE
fix: reset pagination if there is search query present

### LINKED ISSUE #2192: Searchbar not working
#### To replicate
- Goto `/gallery/`
- Goto page "20" for example
- Search something
- no result & error in console

Capture d’écran 2022-02-03 à 8 43 37 AM

#### Test case
`/rmrk/gallery?page=10&search=yeet`

#### Possible Solution
remove/initialise the page parameter from the query on SearchInput

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2192
- [x] during `<Pagination>` component mounting, check if there is search query present and if so, set page to 1
-> this ofcourse doesnt affect pagination afterwards since component doesnt get remounted

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/gallery/?search=Kitty&page=2>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by yangwao** [comment]
I mean, when I'm searching some term I would reset to the first page :)

Google also doesn't throw you on results in the middle like on page 10 😅

I've clicked the last page, then searched valley and ended up on the 4th page.
image

**Comment by kkukelka** [comment]
> I mean, when I'm searching some term I would reset to the first page :)
> 
> Google also doesn't throw you on results in the middle like on page 10 😅

It should reset now on any search query or filter

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 184.95 USD/KSM ~ 0.541 $KSM
🧗 [EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW](https://kusama.subscan.io/account/EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)
🔗 [0xc0f1f7b05e045ee14071ceb6733a29d44934376fa80f91886bc8a924e4644184](https://kusama.subscan.io/extrinsic/0xc0f1f7b05e045ee14071ceb6733a29d44934376fa80f91886bc8a924e4644184)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
