### PR TITLE
New endpoint for RMRK2

### PR DESCRIPTION
**Pull request by vikiival**
Seems like rubick@009-rc.0 can't recover from the issues, it is going super slow

Screenshot 2023-03-29 at 19 29 41

Here I propose new indexer for rmrk2 called `marck` (Mark from Remark)
It's running on [new dedicated infra by subsquid](https://docs.subsquid.io/deploy-squid/deploy-manifest/) so should be insanely fast, will see

Screenshot 2023-03-29 at 19 29 50

### CODE REVIEW

**Comment by yangwao** [comment]
@vikiival seems doesn't build https://github.com/kodadot/nft-gallery/actions/runs/4556228513/jobs/8036317260?pr=5425#step:3:340

**Comment by yangwao** [comment]
going way faster 
- https://deploy-preview-5425--koda-nuxt.netlify.app/rmrk2/collection/c210bd52d397099b2c-JPS/activity

**Comment by yangwao** [comment]
https://squiki.kodadot.workers.dev/status/marck

```json
"syncState": {
"totalBlocks": 17254515,
"currentBlock": 12322987
```

**Comment by vikiival** [comment]
Screenshot 2023-03-30 at 11 28 06

**Comment by yangwao** [comment]
Probably then cherry-pick it to production `hyper-jpeg` ?

**Comment by vikiival** [comment]
> Probably then cherry-pick it to production hyper-jpeg ?

Production should not have rmrk2 ?

**Comment by vikiival** [comment]
Screenshot 2023-03-30 at 13 02 14

**Comment by vikiival** [comment]
Screenshot 2023-03-30 at 16 35 12


Screenshot 2023-03-30 at 16 35 17

**Review by roiLeo — APPROVED** [review]
🚀

**Pull request merged**
