### PR TITLE
🔧 round 2 card price

### LINKED ISSUE #8173: Too many zeros in decimals
Why are we showing so many zeros? ahp/ahp etc... I know that we are rounding on 4 decimals, but in case we have a number like 0.5 it would be good to show it as 0.5 not 0.5000. 

Screenshot 2023-11-21 at 13 42 40

Screenshot 2023-11-21 at 13 46 00

### PR DESCRIPTION
**Pull request by roiLeo**
- close #8173 

Capture d’écran 2023-11-21 à 2 07 33 PM

### CODE REVIEW

**Review by Jarsen136 — APPROVED** [review]

**Comment by prury** [comment]
@roiLeo only problem i see with rounding is this:
image
and also some zero value NFTs when you sort by lowest price
but i guess is the price we have to pay for it?

**Comment by roiLeo** [comment]
> @roiLeo only problem i see with rounding is this: image and also some zero value NFTs when you sort by lowest price but i guess is the price we have to pay for it?

please share link

**Comment by prury** [comment]
> > @roiLeo only problem i see with rounding is this: image and also some zero value NFTs when you sort by lowest price but i guess is the price we have to pay for it?
> 
> please share link

2 cents transactions: 
https://deploy-preview-8174--koda-canary.netlify.app/ahk/u/CmWHiv7h4m9tEzKD94DH4mqwGTvsdYQe2nouWPF7ipmHpqA?tab=activity&buy=true&sale=true

explorer low value items: 

https://deploy-preview-8174--koda-canary.netlify.app/ksm/explore/items?listed=true&sort=price_ASC

**Comment by roiLeo** [comment]
Capture d’écran 2023-11-21 à 2 50 27 PM

I made a change that can have break part of code, now numbers show well but with `.` as separator

**Comment by prury** [comment]
> Capture d’écran 2023-11-21 à 2 50 27 PM
> 
> I made a change that can have break part of code, now numbers show well but with `.` as separator

i don't even know how you got those commas, it was always a `.` here for me
(i do prefer commas, its the separator i use irl )
thanks for fixing it!

**Comment by roiLeo** [comment]
> i don't even know how you got those commas, it was always a `.` here for me (i do prefer commas, its the separator i use irl ) thanks for fixing it!

It's determined by your Browser language (european use ',')

**Pull request merged**
