### PR TITLE
fix: icons in wallet dialog redesign

### LINKED ISSUE #4830: redesign: icons in wallet dialog redesign
During the wallet redesign, I found that some icons in the Figma are not supported by our icon package`fontawesome v5`. 

icons in figma:
image

icons in `fontawesome v5`
image

possible solution:
1. use custom svg file
2.  fontawesome  v6 / pro version   ref: #4788

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4830
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

image

### CODE REVIEW

**Comment by vikiival** [comment]
I would move svgs to separate files :)

**Comment by Jarsen136** [comment]
> I would move svgs to separate files :)

Will move them to files

**Comment by Jarsen136** [comment]
> I would move svgs to separate files :)

Ohh, I found that there will be a problem. If we move svg to files, we must prepare two icons with light and dark colors. The reason is that the svg attribute `stroke="currentColor"` would not work on `` tag. 
ref: https://stackoverflow.com/questions/24933430/img-src-svg-changing-the-styles-with-css

In short, there are two solutions to solve.
1. Using inline svg tag
2. Using some svg-loader like (@nuxtjs/svg) to process the svg file properly.

**Comment by yangwao** [comment]
it just works :D 

pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 36.28 USD/KSM ~ 0.827 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x89847cac295f9200cf14c7c07484f0b3aeefa40d8cca205e220ea9e491d5fa10](https://kusama.subscan.io/extrinsic/0x89847cac295f9200cf14c7c07484f0b3aeefa40d8cca205e220ea9e491d5fa10)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
