### PR TITLE
Fix: falls back to english on navigate #3131

### LINKED ISSUE #3131: When switching tabs in `/rmrk/explore`, it falls back to English
@prachi00 I found something strange when switching tabs in `/rmrk/explore`, it fall back to English 

https://user-images.githubusercontent.com/9987732/172563536-17b06de8-2ddc-4185-88cb-63d30a9b4b87.mov

_Originally posted by @roiLeo in https://github.com/kodadot/nft-gallery/issues/3110#issuecomment-1149589287_

### PR DESCRIPTION
**Pull request by Spatlani**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3131
- [ ] Requires deployment <rubick/magick_issue>
- [x] I've added `skipSettingLocaleOnNavigate: true` in `nuxt.config.js` to skip resetting locale on route change.

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=5H6EZuYaiU9sJ426Zbt6LPSZ2GQ8GTwYZzacxeSMje2kwjVn)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

### CODE REVIEW

**Review by kkukelka — APPROVED** [review]
Huh, odd bug. When i18 was present on page it seems like it then quickly jumped back to spanish or whatever. This fixes it.

**Comment by kkukelka** [comment]
pay 50

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 51.53 USD/KSM ~ 0.97 $KSM
🧗 [5H6EZuYaiU9sJ426Zbt6LPSZ2GQ8GTwYZzacxeSMje2kwjVn](https://kusama.subscan.io/account/5H6EZuYaiU9sJ426Zbt6LPSZ2GQ8GTwYZzacxeSMje2kwjVn)
🔗 [0x5e61ec9cdc3065480bffb98a3bbcecabbf74102f230e1382610b1a0e06bfd9dd](https://kusama.subscan.io/extrinsic/0x5e61ec9cdc3065480bffb98a3bbcecabbf74102f230e1382610b1a0e06bfd9dd)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by roiLeo** [comment]
Nice! Thanks for the fix

**Pull request merged**
