### PR TITLE
#5697 Clickable nft in holders/flipper tab

### LINKED ISSUE #5697: Clickable nft in holders/flipper tab
image
image
- the nft should be clickable
- the name and the img preview - cursor pointer

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Closes #5697
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at c5fa806</samp>

Added links to NFT gallery pages for flips and holders in owner insights tabs. This improves the user experience and navigation for collection owners. Used a common `urlPrefix` variable to handle different network and environment settings in `Flipper.vue` and `Holder.vue` components.

### <samp>🤖 Generated by Copilot at c5fa806</samp>

> _`urlPrefix` helps_
> _link to NFT galleries_
> _autumn of the flip_

### CODE REVIEW

**Comment by exezbcz** [comment]
the whole text now in the flipper tab changes 
image
- you cant copy select from the data because you have pointer cursor 

remove hover color from the link please
image


can you seperate the version to holders tab and flippers please? the holders could have the pointer all over the are, but flipper tab only pointer on pfp and name of nft

**Comment by prachi00** [comment]
> the whole text now in the flipper tab changes image
> 
> * you cant copy select from the data because you have pointer cursor
> 
> remove hover color from the link please image
> 
> can you seperate the version to holders tab and flippers please? the holders could have the pointer all over the are, but flipper tab only pointer on pfp and name of nft

done

**Comment by exezbcz** [comment]
> remove hover color from the link please
> image

this please as last thing, otherwise oki

> can you seperate the version to holders tab and flippers please? the holders could have the pointer all over the are, but flipper tab only pointer on pfp and name of nft

with this in mind

**Comment by vikiival** [comment]
pay 10 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $10 @ 30.42 USD/KSM ~ 0.329 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x9a459ec5097bbd4b7d2693e7199614227dc640f286b46a9dc1cb17a9a05fd1b1](https://kusama.subscan.io/extrinsic/0x9a459ec5097bbd4b7d2693e7199614227dc640f286b46a9dc1cb17a9a05fd1b1)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
