### PR TITLE
#4116 Search shadow fix

### LINKED ISSUE #4116: Search background on dark mode in beta
I guess the background shadow should not be pink? 

📟 @exezbcz 

image

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #4116
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screen Shot 2022-10-17 at 4 21 08 PM

Screen Shot 2022-10-17 at 4 21 00 PM

### CODE REVIEW

**Review by kkukelka — APPROVED** [review]
lgtm

**Comment by yangwao** [comment]
let's go 
pay 50

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 37.73 USD/KSM ~ 1.325 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x27d39de13ee753b1d394887549f2e4a5c3ad101146d2b1fe3a17070b6dde91c4](https://kusama.subscan.io/extrinsic/0x27d39de13ee753b1d394887549f2e4a5c3ad101146d2b1fe3a17070b6dde91c4)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
oops, some bug? interesting 😅

**Comment by prachi00** [comment]
@yangwao yeah seems I have received it twice, which address do I send it back to? `G29NScLSew5zqwmJAPupvJWDCDkpxKUhDnMeVdD2BBcnHar` this one?

**Comment by prachi00** [comment]
> @yangwao yeah seems I have received it twice, which address do I send it back to? `G29NScLSew5zqwmJAPupvJWDCDkpxKUhDnMeVdD2BBcnHar` this one?

@yangwao

**Pull request merged**
