### PR TITLE
fix: BSX price input handling and input conversion

### LINKED ISSUE #3389: Disable minting button if user set zero value for listing
Disable submit button if a user submits NFT with listing price 0 as seems we've got an error.

image

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3389
- [ ] Requires deployment <rubick/magick_issue>
- [x] disabled minting button on BSX if price is 0 or above safe integer, further fixed price conversion

https://user-images.githubusercontent.com/17953978/180408120-b0053bb6-12f2-47db-8183-bccb77f89600.mov

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </bsx/create>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by Jarsen136 — APPROVED** [review]
LGTM

**Review by DeluneClaire — APPROVED** [review]
works  for me

**Comment by Jarsen136** [comment]
pay 100

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 68.11 USD/KSM ~ 1.468 $KSM
🧗 [EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW](https://kusama.subscan.io/account/EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)
🔗 [0x8a31986f85b3996a65a0a2e16543d8798e3fea9782356adcf0bc60ee438642ef](https://kusama.subscan.io/extrinsic/0x8a31986f85b3996a65a0a2e16543d8798e3fea9782356adcf0bc60ee438642ef)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
