### PR TITLE
feat: fontawesome pro sharp regular by default

### LINKED ISSUE #4788: Upgrade fontawesome to v6
> ufff, that check from font awesome does not look good xd, is there thinner version or? I would stick to the think one if its possible.

I revert it back for now. thinner is only on the pro version on fontawesome. free version on the newest version looks thinner

fa v5: https://fontawesome.com/v5/icons/check?s=solid&f=classic
fa v6: https://fontawesome.com/icons/check?s=solid&f=classic

_Originally posted by @preschian in https://github.com/kodadot/nft-gallery/issues/4782#issuecomment-1399182696_
            
upgrade `@fortawesome/*` packages to v6

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #4788. add fa-sharp (pro) for oruga component

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

Screenshot 2023-03-02 135432

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
I'm not too keen on importing the whole library in the project.
(paid library on open source?)
and how will you handle version update?

imo we should change how we use icons (https://github.com/kodadot/nft-gallery/issues/4788#issuecomment-1443836670)

**Review by daiagi — COMMENTED** [review]
:white_check_mark:  code lgtm

**Review by daiagi — APPROVED** [review]

**Comment by exezbcz** [comment]
Can we use the regular icon weight? 
image

**Comment by exezbcz** [comment]
Little confused, we already have the pro version, right? I mean, I'm fine with anything that makes development easier; my only requirement is that the icons not be thick and rounded :D

**Review by roiLeo — CHANGES_REQUESTED** [review]
hmmm.. 🤔 
Screenshot 2023-03-03 at 09-40-06 Low minting fees and carbonless NFTs KodaDot - NFT Market Explorer

**Comment by roiLeo** [comment]
> aw, does anyone face this also? could you try to open it on incognito mode?

same stuff, cleared cache as well

**Comment by roiLeo** [comment]
> aw. hhmm, what is the response status from css kits?

403 forbidden :/

> image

**Comment by roiLeo** [comment]
> @roiLeo how about now? I change it with js kit

works now

Screenshot 2023-03-03 at 11-42-16 Low minting fees and carbonless NFTs KodaDot - NFT Market Explorer

are we going to have conflicts with `vue-fontawesome`?

**Comment by exezbcz** [comment]
> > @roiLeo how about now? I change it with js kit
> 
> works now
> 
> Screenshot 2023-03-03 at 11-42-16 Low minting fees and carbonless NFTs KodaDot - NFT Market Explorer
> 
> are we going to have conflicts with `vue-fontawesome`?

yy, looking good but now we have the checkmarks in both states

**Comment by exezbcz** [comment]
yes!

**Review by roiLeo — APPROVED** [review]
Lets try this, it will only affects libs/ui anyway

**Comment by roiLeo** [comment]
> Lets try this, it will only affects libs/ui anyway

Wait.. I see that it is included in nuxt project, how it will work if we remove `libs/ui` package outside the project?
Can't we include pro version only in `libs/ui`?

**Comment by roiLeo** [comment]
> hhmm, I don't really understand why we need to include the pro version only in `libs/ui`

idk I was thinking about conflicts with free version.

> This PR extends Neo/Oruga wrapper to use the fa-pro prefix. refer to `plugins/icons.ts`. by default, if we use a component from Neo, it will use the fa-pro prefix. that's only prefix

So we still can extend buefy to use pro prefix.

**Review by vikiival — APPROVED** [review]
Let it roll

**Pull request merged**
