### PR TITLE
MassMint - Upload description file

### LINKED ISSUE #5179: Mass Mint: Step 3 - upload description file
* #4964 

## Figma
---
- [Detailed interactions and logic is available Figma](https://www.figma.com/file/HCmIzbN0a2XhsOstHkLiwi/Mass-Mint---Handoff?node-id=0%3A1&t=ynDINS3WQGGG9Dj0-1). 
- all the needed screens
- [interactive prototype ](https://www.figma.com/proto/HCmIzbN0a2XhsOstHkLiwi/Mass-Mint---Handoff?page-id=0%3A1&node-id=1%3A332&viewport=1014%2C587%2C0.04&scaling=scale-down-width&starting-point-node-id=1%3A332&show-proto-sidebar=1)

Please take the prototype with a grain of salt, not everything is perfect and 1:1 to final design how it should look, so in case you don't know something, don't hesitate to ask @VladoTheBoi 

## STEP 3: UPLOAD DESCRIPTION FILE (optional step)**
- Supported files: .TXT, .CSV OR .JSON
- same logic as for Upload Pictures
- in case user plans to mint many NFTs, he can create a description file containing information for each NFT
  - in our case it would contain: 
    - FILE NAME (e.g. awesome_art_1.jpeg)
    - NAME (e.g. Soldier#1)
    - DESCRIPTION (e.g. This is the rarest soldier of the collection)
    - PRICE (e.g. 200 KSM)
  - file needs to have correct structure to be able to connect the information to uploaded art files @yangwao we can discuss the structure and technical implementation of this to provide more information

---

image

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #5179 
- [ ] Requires deployment <snek/rubick/worker>
- [x] Branch From #5765

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at de4c805</samp>

This pull request adds and improves the components and functionality for the mass mint feature, which allows the user to mint multiple NFTs from a zip file and a description file. It refactors the `Massmint.vue` component to use existing and new components, such as `NeoCollapse`, `NeoButton`, `OverviewTable`, `EditPanel`, and various modal components. It also improves the validation and parsing of the zip and description files, and the display and editing of the NFTs in a table. It adds some type definitions, helper functions, and styles for the mass mint feature, and a new layout component `noFooter.vue` that does not include the footer.

### <samp>🤖 Generated by Copilot at de4c805</samp>

> _Mass minting NFTs_
> _`EditPanel`, `NeoInput`_
> _Autumn of crypto_

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
let it roll 🎢 

code lg

**Comment by prury** [comment]
> @kodadot/qa-guild it should be testable on https://deploy-preview-5824--koda-canary.netlify.app/ksm/massmint (Minting not present in this PR)

The interface shows up properly, but when i try to select a collection it wont show up, thus not allowing me to test the dropdowns:

**Comment by daiagi** [comment]
@prury 
> The interface shows up properly, but when i try to select a collection it wont show up, thus not allowing me to test the drop downs

fixed

**Comment by prury** [comment]
> @prury
> 
> > The interface shows up properly, but when i try to select a collection it wont show up, thus not allowing me to test the drop downs
> 
> fixed

same happens when i use the link you sent previously (https://deploy-preview-5824--koda-canary.netlify.app/ksm/massmint)
do you have a new one?

**Comment by daiagi** [comment]
>i did create a specific RMRK collection specific for this test

maybe your collection is on kusama network?

try  https://deploy-preview-5824--koda-canary.netlify.app/rmrk/massmint

**Comment by prury** [comment]
> 

it was all under RMRK2 as shown in the screenshots below, still wont work.

Collection punktest on RMRK2:


I can see it when i try to add more NFTs:


Still not able to choose it from the dropdown:


Console error:

**Comment by daiagi** [comment]
@prury 
should work now

**Comment by prury** [comment]
> @prury should work now

it shows my collection now! :)

lets go forward then:
uploaded a zip file, generated from both winrar and default windows zipping method, but it says the filetype is invalid:
invalid file type

- i would recommend adding support for .rar files as well in the future

**Comment by daiagi** [comment]
> > @prury should work now
> 
> it shows my collection now! :)
> 
> lets go forward then:
> uploaded a zip file, generated from both winrar and default windows zipping method, but it says the filetype is invalid:
> invalid file type
> 
> - i would recommend adding support for .rar files as well in the future
> 

Oh yes. I actually ran into that myself on windows
Are you using windows?

**Comment by prury** [comment]
@daiagi 
Successfully loaded the NFTs into it using a .txt file, thank you

issue1: their order seems odd, it's not being sorted by name or price
uploadfile

issue2: when i try to change the price, if i use a float like 1.3 or 1,3 it wont go
not able to put prices

**Comment by daiagi** [comment]
>issue1: their order seems odd, it's not being sorted by name or price

the order is the order of appearance in the zip file
the name and price can be missing in the description file and can be changed by user, sorting by any of these will cause rows to move around whenever user changes values

>issue2: when i try to change the price, if i use a float like 1.3 or 1,3 it wont go

apologies i forgot to take care of this. fixed

**Comment by prury** [comment]
> > issue1: their order seems odd, it's not being sorted by name or price
> 
> the order is the order of appearance in the zip file the name and price can be missing in the description file and can be changed by user, sorting by any of these will cause rows to move around whenever user changes values
> 
> > issue2: when i try to change the price, if i use a float like 1.3 or 1,3 it wont go
> 
> apologies i forgot to take care of this. fixed

Thank you @daiagi, no need for apologies :)

regarding the order: 

order

**Comment by daiagi** [comment]
> regarding the order:

the order of appearance in the zip file containing the images
keep in mind that the description file is optional

tbh i don't see a need of any ordering, except maybe by user in the form of arrows next to the table titles
and that should be done in another issue if required

**Comment by daiagi** [comment]
@Jarsen136 may I get your review please?

**Review by Jarsen136 — APPROVED** [review]

**Comment by daiagi** [comment]
@vikiival  merge?

**Comment by vikiival** [comment]
> @vikiival merge?

Like let's move :)

**Pull request merged**
