### PR TITLE
refactor: transactionList.ts

### PR DESCRIPTION
**Pull request by floyd-li**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

to resolve this one: https://codeclimate.com/github/kodadot/nft-gallery/composables/transaction/transactionList.ts

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Part of #6782
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at 2888e8e</samp>

Refactored transaction execution code in `composables/transaction/transactionList.ts` to use a function map and helper functions for different urlPrefixes. This improves code readability and reduces duplication.

### <samp>🤖 Generated by Copilot at 2888e8e</samp>

> _`urlPrefix` maps_
> _to functions and arguments_
> _cutting duplication_

### CODE REVIEW

**Comment by stephenjason89** [comment]
code lgtm

**Review by stephenjason89 — APPROVED** [review]

**Review by Jarsen136 — APPROVED** [review]

**Comment by prury** [comment]
i've realized tests to check if those actions would trigger transactions (i did not went it them, just canceled when asked for signing):

- buying : bsx✔️ | rmrk1✔️ | rmrk2✔️ | Ahk ✔️
- mass minting : bsx✔️ | rmrk1✔️ | rmrk2✔️ | Ahk ✔️
- collection creation : bsx ✔️  | rmrk1✔️ | rmrk2✔️ | Ahk ✔️
- create token : bsx ✔️ | rmrk1 ✔️ | rmrk2 ✔️ | Ahk ✔️
- drop container : no drop available
- transfer : dot ✔️| ksm ✔️
- gallery item offer ✔️
- transfer item on gallery : bsx ✔️ | rmrk1✔️ | rmrk 2 ✔️ | Ahk ✔️
- relist: bsx ✔️ | rmrk1✔️ | rmrk2 ✔️ | Ahk ✔️

I've also verified the description on the transaction to see if matches the action

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 4.43 USD/DOT ~ 6.772 $DOT
🧗 [13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A](https://polkadot.subscan.io/account/13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A)
🔗 [0xd08f5d41548fa5765f580d6b7b3bfba663d1c1c7853bb54ab4fffa5809509b92](https://polkadot.subscan.io/extrinsic/0xd08f5d41548fa5765f580d6b7b3bfba663d1c1c7853bb54ab4fffa5809509b92)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
