### PR TITLE
Placement should be in front of you to the ground, 1m before

### LINKED ISSUE #2666: Placement should be in front of you to the ground, 1m before
> placement should be in front of you to the ground, 1m before

_Originally posted by @vikiival in https://github.com/kodadot/nft-gallery/issues/1321#issuecomment-1067065034_

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2666
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
befor:

image

after change:

image

### CODE REVIEW

**Comment by vikiival** [comment]
And for the AR?

**Comment by Jarsen136** [comment]
> And for the AR?

Maybe I need to do some more research to see if it's possible.

**Comment by Jarsen136** [comment]
Seem that the distance to AR model could not be set. @vikiival 

ref: https://github.com/google/model-viewer/discussions/1938#discussioncomment-300556
official docs: https://modelviewer.dev/examples/augmentedreality/#ar

**Comment by vikiival** [comment]
> Seem that the distance to AR model could not be set.

So what does this PR do then?

**Comment by Jarsen136** [comment]
> > Seem that the distance to AR model could not be set.
> 
> 
> 
> So what does this PR do then?

Maybe we can close the issue? depends on you~

**Pull request closed without merging**
