### PR TITLE
⚒️ mobile landing

### LINKED ISSUE #2744: Mobile container 🫙 is broken on mobile again 😬
Found container 🫙 is broken on mobile again 😬 and it's moving, but I guess we can postpone it to another following issue.

https://user-images.githubusercontent.com/5887929/161374871-2edd68c8-ee2e-4395-833a-a5359da66682.mp4

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/pull/2722#issuecomment-1086590712_

### PR DESCRIPTION
**Pull request by roiLeo**
### PR type

- [x] Bugfix

### Closes 
- [x] closes #2744 

### What's new?

- [x] align logo with content on mobile
- [x] reduce padding top on mobile (landing)
- [x] reduce "title" size on mobile
- [x] hide "KODADOT" logo on mobile

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=HguGafrfk8nRP9a4tgJf7hLvSSFie8GtkDjyWFHQ2kDUAMc)

### Screenshot
Screenshot 2022-04-05 at 17-05-07 KodaDot - Kusama NFT Market Explorer

### CODE REVIEW

**Comment by yangwao** [comment]
Maybe #2744 is fixed here 🥲

**Comment by roiLeo** [comment]
> Maybe #2744 is fixed here 🥲

#2744 videos are blank, would you mind sharing a screenshot?

**Comment by yangwao** [comment]
> > Maybe #2744 is fixed here 🥲
> 
> #2744 videos are blank, would you mind sharing a screenshot?
> 
> 

Seems like gh app uploads or my 📱 is break. Put there link to other video

**Comment by roiLeo** [comment]
Tested preview on mobile compared to beta and there is no more horizontal scroll, I didn't know #2744 was related

**Comment by yangwao** [comment]
> Tested preview on mobile compared to beta and there is no more horizontal scroll, I didn't know #2744 was related

well it was meanwhile fixed (dunno in which pr.. and then suddenly happened on landing again) 
wasn't until I realized it relevant again :D

**Review by vikiival — APPROVED** [review]
Tested both safari and nova wallet, looks good

**Comment by vikiival** [comment]
pay 100

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 179.96 USD/KSM ~ 0.556 $KSM
🧗 [HguGafrfk8nRP9a4tgJf7hLvSSFie8GtkDjyWFHQ2kDUAMc](https://kusama.subscan.io/account/HguGafrfk8nRP9a4tgJf7hLvSSFie8GtkDjyWFHQ2kDUAMc)
🔗 [0xf2e36a4006de560039ab865472ab73411e9ea87ca0ea0422d6d0ba8ebb561dc8](https://kusama.subscan.io/extrinsic/0xf2e36a4006de560039ab865472ab73411e9ea87ca0ea0422d6d0ba8ebb561dc8)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
