### PR TITLE
[ARTICLE] keyboard shortcuts

### LINKED ISSUE #2283: Article about keyboard shortcuts in KodaDot
Let's write writing how easy is controlling KodaDot on desktop and collecting faster
Probably animated video with most actions would be really needed in the article 
The tutorial form would be great as well to demonstrate where on video user will see which keyboards were pressed
Definitely, someone with super-fast internet to cut load times on video :)

Deliver in form of medium article, can be on your medium.

Once it's merged
- #2097
- #2216
- #2259 

image

### PR DESCRIPTION
**Pull request by AshutoshSingh72**
Thank you for your contribution to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz/).

👇 __ Let's make a quick check before the contribution.

## PR Type
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #2283
## Did your issue had any of the "$" label on it?
- [x] My DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=158VTDxZJidzsMcAdh7h828domveRvpmk1SCxwLUEHhcgY4v&usdamount=0&donation=true)

### CODE REVIEW

**Comment by AshutoshSingh72** [comment]
@yangwao finally everything is corrected and you can review my PR

**Comment by yangwao** [comment]
yes reached out in DMs, to improve title and add footer and I'm good with it to help us with SEO in this way!

**Comment by AshutoshSingh72** [comment]
> 

dm replied @yangwao

**Comment by yangwao** [comment]
i mean for now it's ok, we will be refreshing this later one day 😄

pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 4.93 USD/DOT ~ 6.085 $DOT
🧗 [158VTDxZJidzsMcAdh7h828domveRvpmk1SCxwLUEHhcgY4v](https://polkadot.subscan.io/account/158VTDxZJidzsMcAdh7h828domveRvpmk1SCxwLUEHhcgY4v)
🔗 [0xec12c4962460aea11bf7f3f3d0e39ea109a3cc0467d334c8e8e18845b748f6dd](https://polkadot.subscan.io/extrinsic/0xec12c4962460aea11bf7f3f3d0e39ea109a3cc0467d334c8e8e18845b748f6dd)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
pay 40 usd 

so in total 70 USD :)

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $40 @ 4.93 USD/DOT ~ 8.114 $DOT
🧗 [158VTDxZJidzsMcAdh7h828domveRvpmk1SCxwLUEHhcgY4v](https://polkadot.subscan.io/account/158VTDxZJidzsMcAdh7h828domveRvpmk1SCxwLUEHhcgY4v)
🔗 [0xaa826a89dbc8ff6520f4b7bd98ed7823c3b0725a4ef9e2ec38345dc8c43fd95f](https://polkadot.subscan.io/extrinsic/0xaa826a89dbc8ff6520f4b7bd98ed7823c3b0725a4ef9e2ec38345dc8c43fd95f)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
