### PR TITLE
🔧 collection stats hide burned nfts

### LINKED ISSUE #3936: Collection numbers total items
Seems I don't see 34 items.
Does it also count burned NFTs? Seems yes.
Listed 5 is ok when I switch to buy now.

Thinking we should show only items on RMRKv1 available in brackets, like, there are 12 of them to keep overall information on how much has been minted in a particular collection to pass user sensible information.
It would look a bit messy for now and the collection view is in the redesign pipeline as well. 

In this case 
`5 ⊆ 34 (12)` 
https://beta.kodadot.xyz/rmrk/collection/c0e28f6cce627bbf5d-CYBERBARONG500?page=1

image

### PR DESCRIPTION
**Pull request by roiLeo**
### PR type

- [x] Bugfix

### What's new?

- [x] PR closes #3936 
- [x] remove burned nfts in stats

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Screenshot

Capture d’écran 2022-09-12 à 9 06 34 AM

### CODE REVIEW

**Review by petersopko — APPROVED** [review]
wfm

**Comment by yangwao** [comment]
thing user won't see what has a collection originally total number of items :(

**Comment by petersopko** [comment]
> thing user won't see what has a collection originally total number of items :(

not sure what do you mean by this. do you want to display the total number of minted NFTs separately in collection stats?

**Comment by roiLeo** [comment]
> thing user won't see what has a collection originally total number of items :(

would you rather show hidden/deleted stuff that might confuse user or show/count only what's visible.
Or we can add original n° of items between brackets? 

Same apply for some collection Stats that keeps track of burned data.

screenshot from singular:
Screenshot 2022-09-12 at 14-59-16 Singular Kusama-native NFTs #RMRK #NFT

**Review by kkukelka — APPROVED** [review]
code lgtm

**Comment by roiLeo** [comment]
I'll merge this, lmk if it need a minor tweak

**Pull request merged**
