### PR TITLE
fix: Limit ability to go minus on mass mint drop

### LINKED ISSUE #9761: Limit ability to go minus on mass mint drop
We probably won't sell discounted drops for a while 🙂‍↔️ 

https://github.com/kodadot/nft-gallery/assets/5887929/0089a71f-b8ac-4faa-a158-4613d9f5e677

### LINKED ISSUE #9779: Step button in mass mint drop page
image

I think we can remove this one, or does it have a special purpose? 

with the arrows, you can actually go to 0 

image

not ideal :D 

when it will be removed, please center out the number

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #9761
- [x] Closes #9779

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed UI

image

## Copilot Summary

copilot:summary

copilot:poem

### CODE REVIEW

**Comment by Jarsen136** [comment]
✅  Fixed another issue #9779 on current PR 

cc @exezbcz

**Comment by exezbcz** [comment]
lets go, frontrunning 


i have one request tho, you cannot input 3 by overriding it 


https://github.com/kodadot/nft-gallery/assets/90852205/b1579201-373a-4eba-a8c3-503c6fdfb13f

**Comment by prury** [comment]
> lets go, frontrunning
> 
> i have one request tho, you cannot input 3 by overriding it
> Screen.Recording.2024-03-14.at.17.48.27.mov

oh, its true, chrome only tho

**Comment by Jarsen136** [comment]
> lets go, frontrunning
> 
> i have one request tho, you cannot input 3 by overriding it
> 

✅ Fixed
enable overriding number on input

**Comment by yangwao** [comment]
> ✅ Fixed
> enable overriding number on input

@exezbcz have some points but he will articulate in video soon :D probably follow up 

Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 11.43 USD/DOT ~ 2.625 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0xb43a174a6d525687256c6165a6ae81b05dcdd424bbd16fa87506cdb0a21fe016](https://polkadot.subscan.io/extrinsic/0xb43a174a6d525687256c6165a6ae81b05dcdd424bbd16fa87506cdb0a21fe016)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
