### PR TITLE
refactor: a faster Kodadot without passion feed

### LINKED ISSUE #3421: Disabling passion feed to have stable endpoint for RMRK
As seems passion feed does more harm than good, i.e crashing and breaking the basic usability of KodaDot
**To bring back stability, it's time to turn passion feed off everywhere**, until we will inspect outside production what's the culprit. 
Later we will adjust and relaunch it with new and optimal resources as seems this query is super hungry.

Suggestions are more than welcome what could be the cause of this. 
Query which drops rubick is mentioned in https://github.com/kodadot/rubick/issues/109

First downtimes we've noticed are around May 28 ~

### Potential queries
- explorer
- series-insight
- spotlight

image

### Ref 
- https://github.com/kodadot/rubick/issues/109
- https://github.com/kodadot/nft-gallery/issues/3420
- https://github.com/kodadot/nft-gallery/issues/3419
- https://github.com/kodadot/rubick/pulls?q=is%3Apr+sort%3Aupdated-desc+passion+is%3Aclosed
- https://github.com/kodadot/nft-gallery/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+passion
- https://github.com/kodadot/nft-gallery/pulls?q=is%3Apr+sort%3Aupdated-desc+passion+is%3Amerged
- https://github.com/kodadot/nft-gallery/pull/3023
- https://github.com/kodadot/nft-gallery/issues/2222
- https://github.com/kodadot/nft-gallery/pull/3101
- https://github.com/kodadot/nft-gallery/pull/3304
- https://github.com/kodadot/rubick/blob/main/src/mappings/utils/cache.ts#L11
- https://github.com/kodadot/rubick/issues/97
- https://github.com/kodadot/nft-gallery/issues/3287
- https://github.com/kodadot/nft-gallery/pull/2995

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #3421
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by roiLeo** [comment]
duplicate or extend #3151?

**Comment by Jarsen136** [comment]
> duplicate or extend #3151?

They are quite different. This PR goes through all the codebase and removes all the passion feed.

#3151 focus on the enable/disable option on landing page.

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 48.27 USD/KSM ~ 2.072 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x5031db51251c794906936e04b44552c000c39b6a37ec2a980fe9ebc42f8f788d](https://kusama.subscan.io/extrinsic/0x5031db51251c794906936e04b44552c000c39b6a37ec2a980fe9ebc42f8f788d)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
