### PR TITLE
fix: update profile links and user profile overflow

### LINKED ISSUE #2220: Rework profile links a bit
At a collection view 
- replace subscan icon with identicon
- remove dot scanner link

At a profile
On left
- remove dotscanner and sub.id

On right, add over sharing, in same style into boxes
- dotscanner
- sub.id
- subscan
- polkascan

https://kusama.polkastats.io/account/Hqa6PRbEH25UiaPmcfeCfdG8FSqBUtNR5KtVfG3oSCBFSg9

image

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

Screenshot 2022-02-09 at 12 05 30
Screenshot 2022-02-09 at 12 07 47

### What's new?

- [x] PR closes #2220
- [x] reordered network icons, added identicon, added polkascan icon, fixed mobile b-tab overflow on user profile

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at /rmrk/u/JEJRr7uK5rwjTFgsps9LHGo4qHSBQdmfv7mEdo7M32pMvSu
- [x] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
Wouldn't it be better to change the size of the logos to 16 by 16?

**Comment by kkukelka** [comment]
> Wouldn't it be better to change the size of the logos to 16 by 16?

kind of worried about icon readability here
Screenshot 2022-02-10 at 10 38 16

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 187.28 USD/KSM ~ 0.534 $KSM
🧗 [EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW](https://kusama.subscan.io/account/EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)
🔗 [0x8ef5e454d2215da5ce01542810104336807eea10998c8c6a420905a94bb3c437](https://kusama.subscan.io/extrinsic/0x8ef5e454d2215da5ce01542810104336807eea10998c8c6a420905a94bb3c437)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by roiLeo** [comment]
> kind of worried about icon readability here 

I asked this because the different size of icons caught my attention, It seemed a little strange to me

**Pull request merged**
