### PR TITLE
refactor: plugins

### PR DESCRIPTION
**Pull request by pbkompasz**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [X] Refactoring

## Context

- [X] Part of #5314  
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [X] My contribution builds **clean without any errors or warnings**
- [X] I've merged recent default branch -- **main** and I've no conflicts
- [X] I've tried to respect high code quality standards
- [X] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [X] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16hqk8Tjugo9AwSzKkxXc1dsRK7iJetpx1YBaoXYwdHzuNAt&usdamount=50&donation=true)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at 029198b</samp>

Refactored several components and plugins to use the `@vueuse/core` library, the `useShare` hook, the `defineNuxtPlugin` function, and the `truncateStr` function. These changes simplify the code, reduce dependencies, improve performance, and fix bugs. Added support for Kusama and Polkadot network logos and names in the wallet component. Added a prop to control the visibility of the unlockable content button in the collection component.

### <samp>🤖 Generated by Copilot at 029198b</samp>

> _Sing, O Muse, of the mighty refactorings_
> _That the skilled developers wrought on the code_
> _With `defineNuxtPlugin` and `useClipboard` they enhanced_
> _The performance and functionality of the mode_

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
would it be possible to make this changes on `nuxt` branch?

**Review by roiLeo — CHANGES_REQUESTED** [review]
Not building & not working for me

**Comment by pbkompasz** [comment]
@roiLeo I have tested it while making the changes but not after merging it with the nuxt branch. I will look at it later today or tomorrow.

**Comment by pbkompasz** [comment]
@roiLeo I don't why it's not building but I cannot work on this now. I will have to close this and open a new one on Monday.

**Pull request closed without merging**
