### PR TITLE
fix: use infura gateway

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix Temporary
- [ ] Feature
- [ ] Refactoring

## Context

- [x] use infura gateway while pinata down

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by roiLeo** [comment]
I've got some errors on landing, is it related with this new provider?
Capture d’écran 2023-01-03 à 8 49 01 AM

it seemed to me that infura pricing were more expensive, is this a temporary solution? how long will we keep it?

**Comment by roiLeo** [comment]
> can you give me that list of error URLs

```
error [BasicImage] to load: https://r2.infura-ipfs.io/ipfs/bafybeiatkjlzk7rsrr4hgaq4dbx4uypvp2ecj7wad6xt334bb4iwrnfcxi
error [BasicImage] to load: https://r2.infura-ipfs.io/ipfs/bafybeic2vnueynsiiuezdtooilpskkcgsmlme574qgvvfd4f4g5kmjekdy 
error [BasicImage] to load: https://r2.infura-ipfs.io/ipfs/bafybeihs2baqyzydacsrbssgsv3yud2pemyllcisb7s4yl527zdmq7fj3y
```

this one not working for me https://deploy-preview-4588--koda-nuxt.netlify.app/bsx/gallery/2608295324-7

**Comment by vikiival** [comment]
This should be temporary solution.

**Comment by yangwao** [comment]
hmm 🤔 
so at current stuff I've set up host origin working well from production like kodadot.xyz so we should be ok there yet from deploy preview and beta it's pitty.

Terms of numbers I've been inspecting that even recent billing cycle made over 200-300g easily, and usually we do currently 2T per month but things is that even pinata isn't best as we already hit half of their high plan where they limit to 10M reqs and we did 4-6M easy peasy so I guess we will wait for @vikiival fix and it's should be faster and cheaper as CF has far cost effective plans for us.

I'm also curious why we have such lot reqs either pinata is miss reporting or restricted gateway should help but they simply have strategy in restricted mode they serve only pinned content through their gateway... which is pitty as their storage limits are not much comparing to nft.storage.. so I guess r2 would be way cheaper as terms of storage prices of pinata uses some expensive s3

**Comment by yangwao** [comment]
Let's make hack 

https://github.com/kodadot/nft-gallery/issues/4587#issuecomment-1369901103

**Pull request closed without merging**
