### PR TITLE
fix: sortBy shouldn't be empty string

### LINKED ISSUE #7149: Canceling sort may cause the collection query to fail
### What happened?

If the sort option is ever checked on collection list page, and then all sort options are unchecked, the query will throw error.

https://github.com/kodadot/nft-gallery/assets/10708802/536cf878-6547-4a72-a7fe-e5004c2725de

### Please reproduce in steps

1. https://canary.kodadot.xyz/ksm/explore/collectibles
2. Clicks sort by Newest.
3. Waiting results.
4. Clicks sort by Newest again to uncheck it.
5. See error.

### Expected Behavior

The query returns normal results.

### What browsers are you seeing the problem on?

_No response_

### At which address did you encounter bug?

_No response_

### Are you logged in?

None

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

_No response_

### Screenshots

see above.

### Relevant log output

_No response_

### Payment link for reward

[Payout](https://canary.kodadot.xyz/dot/transfer?target=1CAv6Zq3yVxL3eKhC94GWTWVwp1w4jZbqeZ6wXx1rPAhrce&usdamount=0&donation=true)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by newraina**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #7149 
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer?target=1CAv6Zq3yVxL3eKhC94GWTWVwp1w4jZbqeZ6wXx1rPAhrce&usdamount=0&donation=true)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at 5f7bf4a</samp>

Fixed a bug that prevented sorting collections by using `undefined` as a default value for `searchQuery.value.sortBy` in `CollectionGrid.vue`.

### <samp>🤖 Generated by Copilot at 5f7bf4a</samp>

> _`searchQuery` fixed_
> _No more empty `sort_by`_
> _API happy_

### CODE REVIEW

**Comment by daiagi** [comment]
toggling sort on and off makes all the results disappear

 it isn't any better on canary => This PR didn't cause the bug, but didn't fix it yet

image

playing with filters may make them reappear

image


### it isn't any better on canary => This PR didn't cause the bug, but didn't fix it yet

**Comment by newraina** [comment]
> toggling sort on and off makes all the results disappear

@daiagi It's a different issue, I've fixed it in https://github.com/kodadot/nft-gallery/pull/7110, you can try it in that PR to see if it's still there.

This PR focuses on fixing the problem that toggling sort on and off on collection list page may cause incorrect query parameters.

**Comment by daiagi** [comment]
OK. ill review this one again after #7110 gets merged, as it is difficult to separate that bug from this one

**Review by roiLeo — APPROVED** [review]

**Comment by yangwao** [comment]
good spot!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 4.25 USD/DOT ~ 7.059 $DOT
🧗 [1CAv6Zq3yVxL3eKhC94GWTWVwp1w4jZbqeZ6wXx1rPAhrce](https://polkadot.subscan.io/account/1CAv6Zq3yVxL3eKhC94GWTWVwp1w4jZbqeZ6wXx1rPAhrce)
🔗 [0x262410ee08dd3811a66bf81b05e18f0284768350b0d3b243600087f71ce7b08e](https://polkadot.subscan.io/extrinsic/0x262410ee08dd3811a66bf81b05e18f0284768350b0d3b243600087f71ce7b08e)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
