### PR TITLE
✨ useLocalStorage composable

### PR DESCRIPTION
**Pull request by roiLeo**
Might be needed (#5057)

### Usage

```ts
const walletProvider = useLocalStorage('wallet')
```

### CODE REVIEW

**Comment by vikiival** [comment]
Wondering why not cone from vue-use?

**Comment by roiLeo** [comment]
> Wondering why not cone from vue-use?

Forgot [useStorage](https://vueuse.org/core/useStorage/#usestorage) exist.

> When using with Nuxt 3, this functions will NOT be auto imported in favor of Nitro's built-in [useStorage()](https://nitro.unjs.io/guide/introduction/storage). Use explicit import if you want to use the function from VueUse.

I prefer to rely on simple tools rather than having to maintain package version upgrade.
Feel free to close it if not needed.

**Comment by vikiival** [comment]
> > Wondering why not cone from vue-use?
> 
> 
> 
> Forgot [useStorage](https://vueuse.org/core/useStorage/#usestorage) exist.
> 
> 
> 
> > When using with Nuxt 3, this functions will NOT be auto imported in favor of Nitro's built-in [useStorage()](https://nitro.unjs.io/guide/introduction/storage). Use explicit import if you want to use the function from VueUse.
> 
> 
> 
> I prefer to rely on simple tools r - ather than having to maintain package version upgrade.
> 
> Feel free to close it if not needed.


If we reexport use storage to use local storage

**Comment by vikiival** [comment]
cc @roiLeo

**Comment by roiLeo** [comment]
> If we reexport use storage to use local storage

14608107_1180665285312703_1558693314_n

**Review by vikiival — APPROVED** [review]

**Pull request merged**
