### PR TITLE
6625 fix cart excess truncation

### LINKED ISSUE #6625: Dance in cart
I would like to see items in cart expanded at most.
Collection name probably smaller size?

At price we can skip those small amounts less than $1 
so instead of 96.5000 KSM -> 96 KSM

Follow design best 

image

### PR DESCRIPTION
**Pull request by god-of-js**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

Screenshot 2023-08-10 at 3 51 35 PM
Screenshot 2023-08-10 at 3 51 55 PM

- [ ] Closes #6625  and #6617 
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?
Yes, it had `$`

- [ ] My DOT address: 12AVSmE1QguooF6HCMzJxTiYcWaaFb6Vgm7YixmMRyE8S9pV [Payout](https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>)

### <samp>🤖 Generated by Copilot at 8bc2246</samp>

Improved the shopping cart UI by enhancing the layout and responsiveness of each item row in `ShoppingCartItemRow.vue`.

### <samp>🤖 Generated by Copilot at 8bc2246</samp>

> _Shopping cart item_
> _`gap-8` adds some breathing space_
> _Overflow hidden_

### CODE REVIEW

**Comment by prury** [comment]
From what I've understood from the Issue, i think @exezbcz wanted to show more info about the NFT when not in the hovering trashcan state as well. Regarding price i believe at least one decimal could be taken off, if not two.

**Comment by god-of-js** [comment]
> From what I've understood from the Issue, i think @exezbcz wanted to show more info about the NFT when not in the hovering trashcan state as well. Regarding price i believe at least one decimal could be taken off, if not two.
> 
> let's wait for his feedback

I considered that and that was my first implementation until I looked a little bit more into the problem and noticed that the main reason it wasn't exactly following the design was because it was truncating too early.

Also, I felt since we are dealing with money/numbers maybe fixing the truncation rather than rounding it to the nearest whole number would be ideal.

If the team would prefer rounding it up to the nearest whole number, I can do that right away.

But when I do, `3.576KSM` would be rounded up to `4KSM`. I am wondering if that is ideal.

**Comment by exezbcz** [comment]
> Also, I felt since we are dealing with money/numbers maybe fixing the truncation rather than rounding it to the nearest whole number would be ideal.

lets cut the number up to hundreds - e.g. 9.9860 KSM -> 9.98 - not rounding, showing only 2 decimals 

ad truncation
### Nft name 
- would be nice to display the nft name - bold one, like here - most extended, even without hover over
image
- then truncate the text when it will be longer, or you hover over, so the trash can could be displayed 
- here is how it would look like when you hover over title that is longer: 
image

### Nft collection
- now for the collection:
- it would be nice if the collection name would not expand on hover (it happens because the trash can occupies less space than price) 
- so if it possible, can you make the collection same on hover as it is by default? 
- since we also shorten the price, the collection will have more space and in the end will be longer
- it just does not look good when the collection name is sometimes fully revealed when you are trying to remove the item from cart 

do you have any question?

**Comment by god-of-js** [comment]
> > Also, I felt since we are dealing with money/numbers maybe fixing the truncation rather than rounding it to the nearest whole number would be ideal.
> 
> lets cut the number up to hundreds - e.g. 9.9860 KSM -> 9.98 - not rounding, showing only 2 decimals
> 
> ad truncation
> 
> ### Nft name
> * would be nice to display the nft name - bold one, like here - most extended, even without hover over
>   image
> * then truncate the text when it will be longer, or you hover over, so the trash can could be displayed
> * here is how it would look like when you hover over title that is longer:
>   image
> 
> ### Nft collection
> * now for the collection:
> * it would be nice if the collection name would not expand on hover (it happens because the trash can occupies less space than price)
> * so if it possible, can you make the collection same on hover as it is by default?
> * since we also shorten the price, the collection will have more space and in the end will be longer
> * it just does not look good when the collection name is sometimes fully revealed when you are trying to remove the item from cart
> 
> do you have any question?

When the NFT name is long, should it go to the next line?
E.g in the picture below, the one hovered on is too long and if left without truncation, it could go to the next line.


Screenshot 2023-08-11 at 8 40 38 PM

**Comment by god-of-js** [comment]
Hey guys, I messed up this branch a bit.
So, I created a new branch and moved my changes there.
I would love it if we could continue with that branch.
https://github.com/kodadot/nft-gallery/pull/6684

The recent changes from the conversations had here are implemented there.
Sorry for the inconvenience

CC: @exezbcz @yangwao @prury

**Pull request closed without merging**
