### PR TITLE
🔧 basicImage responsive to src props changes

### LINKED ISSUE #6399: Hover card on Statemine collections doesn't work
When I hover over address, it doesn't fetch proper images, but when I click on picture, it works

https://kodadot.xyz/stmn/collection/u-2024?collectionId=u-2024

image

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #6399
- [ ] Requires deployment <snek/rubick/worker>

## Test
https://deploy-preview-6402--koda-canary.netlify.app/stmn/collection/u-2024?collectionId=u-2024

Hover over the identity link, images will show

#### Did your issue had any of the "$" label on it?
Yes, $

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)

## Screenshot 📸

- [x] My fix has changed UI

image

### <samp>🤖 Generated by Copilot at 05f3404</samp>

Added a `watchEffect` function to `BasicImage.vue` to handle dynamic image source changes. This improves the image component's compatibility with IPFS and blockchain data.

### <samp>🤖 Generated by Copilot at 05f3404</samp>

> _`watchEffect` listens_
> _`src` prop changes, `imageSrc` too_
> _Dynamic images, like spring_

### CODE REVIEW

**Review by Jarsen136 — APPROVED** [review]

**Review by roiLeo — APPROVED** [review]
won't this work better with `const imageSrc = computed(() => props.src)`?

otherwise code lgtm ✅

**Comment by daiagi** [comment]
> won't this work better with `const imageSrc = computed(() => props.src)`?
> 
> otherwise code lgtm white_check_mark

I avoided that as it would require a `let`. it would have looked something like:

```typescript


let innerImageSrc = props.src
const loaded = ref(false)

const imageSrc = computed({
  get: () => innerImageSrc,
  set: (newValue: string) => {
    innerImageSrc = newValue
  },
})

const onImageLoad = () => {
  loaded.value = true
}
const onImageError = (ev: Event) => {
  $consola.error('[BasicImage] to load:', props.src, ev)
  imageSrc.value = placeholder.value
}
```

**Comment by vikiival** [comment]
pay 15 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $15 @ 5.29 USD/DOT ~ 2.836 $DOT
🧗 [1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8](https://polkadot.subscan.io/account/1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)
🔗 [0xfe578923b09e60babf147b23c2ae49f12a5660aa88fd41467b9b40e516d089c4](https://polkadot.subscan.io/extrinsic/0xfe578923b09e60babf147b23c2ae49f12a5660aa88fd41467b9b40e516d089c4)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
