### PR TITLE
bugfix: Weird border on burger menu on mobile in light mode

### LINKED ISSUE #3780: Weird border on burger menu on mobile in light mode
seems some smol glitch 
after reload is not there tho so some state needs better handling

https://user-images.githubusercontent.com/5887929/185371135-deefbf1f-14ea-4732-9588-c61187363516.mov

### PR DESCRIPTION
**Pull request by zhengow**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3780
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

https://user-images.githubusercontent.com/38389586/185686589-347678fd-64ba-40e0-8eb5-2d27b1645af9.mp4

### CODE REVIEW

**Comment by yangwao** [comment]
Seems good!

**Review by Jarsen136 — APPROVED** [review]
LGTM and WFM

**Comment by roiLeo** [comment]
Wdyt about this option by just removing margin from logo
Capture d’écran 2022-08-20 à 11 49 33

**Comment by yangwao** [comment]
> removing margin from logo

can be, let's make another PR for that )

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
pay 50

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 49.72 USD/KSM ~ 1.006 $KSM
🧗 [EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws](https://kusama.subscan.io/account/EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)
🔗 [0x9c234fbdad43b3d4a0731eadd871de8ff5a2869cf52e99d8dc31e9196dbb820e](https://kusama.subscan.io/extrinsic/0x9c234fbdad43b3d4a0731eadd871de8ff5a2869cf52e99d8dc31e9196dbb820e)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
