### PR TITLE
fix: Address KSM does not match but successfully sent

### LINKED ISSUE #2494: Address KSM does not match but successfully sent
### What happened?

this is like a bug I encountered in issue #2460
but this time I found the page https://kodadot.xyz/rmrk/admin/,

in the column "Distribute NFTs to multiple addresses" there is no correct address filter,
so that anything written with 1-3 digit words can be sent even if it is the wrong address.

### Please reproduce in steps

I found it with Google Dork.

> 1. Go to Google and search for "site:kodadot.xyz inurl:admin"
> 2. Click https://nft.kodadot.xyz/ or https://beta.kodadot.xyz/ (it's the same)
> 3. Connect the wallet and select NFT from the collection
> 4. Click the SEND button
> 5. Fill in the invalid address into the field MINT.EXPERT.BATCHSEND. 
> then CLICK TO SEND NFT(S)

### Expected Behavior

supposedly the "**CLICK TO SEND NFT(S)**" button won't light up if it's the wrong address.
"**CLICK TO SEND NFT(S)**" button will light up if the address matches

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Mobile iOS Safari, Mobile Android Chrome, Mobile Firefox

### Are you logged in?

Yes

### At which address did you encounter bug?

beta.kodadot.xyz, kodadot.xyz

### Screenshots

https://user-images.githubusercontent.com/43703018/156430340-40778c0a-8aa9-47c5-a424-2ae9135242e0.mp4

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2494
- [ ] <brief_description_of_what_I've_added>

change log:
1. bugFix: disable submit button when the KSM address is invalid
2. do some refactor to make the code more readable and reasonable

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [x] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

https://user-images.githubusercontent.com/31397967/159218628-b17f551b-43df-4f95-9e65-c5871a80c435.mov

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
it would be nice to know which ones are right and which ones are wrong.

ps: missing translation `mint.expert.batchSend`

**Comment by Jarsen136** [comment]
> it would be nice to know which ones are right and which ones are wrong.

Alright, I add some reason about why I write so. 
Is there still anything confused?



> ps: missing translation `mint.expert.batchSend`

TBH, I don't know which translation is appropriate.

**Comment by vikiival** [comment]
any particular reason why u removed `@Debounce` ?

**Comment by Jarsen136** [comment]
> any particular reason why u removed `@Debounce` ?

I just move the position of `@Debounce`, from every attribute update function to final `onInput` function.

**Comment by Jarsen136** [comment]
Is there anything I need to modify? 👀

**Review by vikiival — APPROVED** [review]
oki

**Comment by vikiival** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 183.8 USD/KSM ~ 0.544 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x5bf8e579f4578ace56a3d4774e6e74b159d3d94ac613bb8717293af1882bed7e](https://kusama.subscan.io/extrinsic/0x5bf8e579f4578ace56a3d4774e6e74b159d3d94ac613bb8717293af1882bed7e)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
