### PR TITLE
fix: teleport tabs hover color

### LINKED ISSUE #6763: Teleport buttons hover effect dark mode
### What happened?

Should not change the text color i suppose? @exezbcz 

https://github.com/kodadot/nft-gallery/assets/36627808/a11b0767-b0bf-4bcd-852a-ff40130fd615

### PR DESCRIPTION
**Pull request by thnaylor**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #6763 
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [ ] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=123PCJXhjb15i6JwVVRGd7KvN2sSNZrtPjr5doJq9oWctoTt)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image
image

### <samp>🤖 Generated by Copilot at 4cc1ef7</samp>

Improved the appearance and theme compatibility of the teleport tabs component by using a variable for the hover color.

### <samp>🤖 Generated by Copilot at 4cc1ef7</samp>

> _`teleport` tabs change_
> _hover color from theme, not_
> _black `textColor` kireji_

### CODE REVIEW

**Comment by thnaylor** [comment]
I saw in PR #6755 that Neo button implements the theme & text color now so I'm wondering if it would be better to remove the entire theme from from ".teleport-tabs-button" in this PR as it seems like duplicate code and let the styles fall onto the NeoButton?

**Comment by Jarsen136** [comment]
> I saw in PR #6755 that Neo button implements the theme & text color now so I'm wondering if it would be better to remove the entire theme from from ".teleport-tabs-button" in this PR as it seems like duplicate code and let the styles fall onto the NeoButton?

Yes. You could have a try if it does not break something.

**Comment by thnaylor** [comment]
## Screenshot 📸

image

image


LGTM! It will be more consistent now.

**Review by Jarsen136 — APPROVED** [review]

**Review by exezbcz — APPROVED** [review]

**Review by preschian — APPROVED** [review]

**Comment by yangwao** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 4.49 USD/DOT ~ 4.454 $DOT
🧗 [123PCJXhjb15i6JwVVRGd7KvN2sSNZrtPjr5doJq9oWctoTt](https://polkadot.subscan.io/account/123PCJXhjb15i6JwVVRGd7KvN2sSNZrtPjr5doJq9oWctoTt)
🔗 [0x243deb79d16e0c88961b558a9609d58e4fd114faeab50a42c828b8f9f1d93111](https://polkadot.subscan.io/extrinsic/0x243deb79d16e0c88961b558a9609d58e4fd114faeab50a42c828b8f9f1d93111)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
