### PR TITLE
fix: Neobrutalism landing page release UI

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR #4185

- [x] At the search bar, the link should navigate to explorer view like when click on Basilisk will land at https://beta.kodadot.xyz/bsx/explore/ 
- [x] Top collections: Stroke around the collection icon
- [x]  Subscribe button design
- [x] lines that seperates containers are white, not black. 
- [x] Hide history component on navbar 

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

- [x] At the search bar, the link should navigate to explorer view like when click on Basilisk will land at https://beta.kodadot.xyz/bsx/explore/ 
- [x] Top collections: Stroke around the collection icon
image

- [x]  Subscribe button design

image
image

- [x] lines that seperates containers are white, not black. 

image

- [x] Hide history component on navbar

### CODE REVIEW

**Comment by exezbcz** [comment]
image
- please change the text to black on the subscribe part
- no border between subscribe and email input

Is there option to have hover on the subscribe button?

**Comment by Jarsen136** [comment]
> * please change the text to black on the subscribe part
> * no border between subscribe and email input
> 
> Is there option to have hover on the subscribe button?

Yes,  I have added the hover style.

image

**Review by roiLeo — APPROVED** [review]
✅ wfm

- ✔️ chain redirect to explore
- ✔️ hide history component in navbar
- ✔️ border on top collection image
- ✔️ substack button design
- ✔️ white lines separator (dark mode)

missing:
- navbar blur bg
- search bar results

**Comment by yangwao** [comment]
build fails 👀😬

**Comment by roiLeo** [comment]
> build fails 👀😬

*test failed
but not related with this PR

**Comment by yangwao** [comment]
see now, let's merge, will be pushing it live, because there was lot of side bugs fixed and getting reported tho

**Comment by yangwao** [comment]
pay 60

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $60 @ 34.73 USD/KSM ~ 1.728 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x0d2bae3bda434e61ccf3fdecb0b727e06a0d928ae818e7d6b5e7bb9602c306bd](https://kusama.subscan.io/extrinsic/0x0d2bae3bda434e61ccf3fdecb0b727e06a0d928ae818e7d6b5e7bb9602c306bd)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
pay 60

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $60 @ 24.66 USD/KSM ~ 2.433 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xd383daabba60a871ab24fe845ee143633725e0b892d83e035495cad1be0e6b7b](https://kusama.subscan.io/extrinsic/0xd383daabba60a871ab24fe845ee143633725e0b892d83e035495cad1be0e6b7b)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
