### PR TITLE
feat: Price sort by logic

### LINKED ISSUE #8890: Price sort by logic
so, currently, our price filter, either low to high or high to low only work when buy now filter is applied 

i don't know what tunel vision I had, but it should work differently

image

## changes
- since its "sort by" it should actually sort without any other filter applied 
- when the low to high filter is active, show listed first, sorted by the sort by filter, and then leave the rest untouched. It takes all the supply and just reorders it so the listed ones are on top.
- then, when "buy now" is active as well, it filters out only the listed

**sort by price + buy now = listed items sorted by price** 

**sort by price = all items sorted based on price, non listed are there as well, but only after the listed ones**

**lets also rename "buy now" to listed** 

price range should work the same

image
- it does not show the ones with 1 dot first

probably this needs to be changed, sorry for that 
- https://github.com/kodadot/nft-gallery/pull/8809

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

❗️❗️ Needs https://github.com/kodadot/stick/pull/285

- [x] Closes #8890

## Needs QA check

- @kodadot/qa-guild please review

## Needs Design check

- @exezbcz please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [ ] My fix has changed **something** on UI;

### CODE REVIEW

**Comment by exezbcz** [comment]
what is needed here to be finished?

**Comment by exezbcz** [comment]
i am a ping

**Comment by vikiival** [comment]
cc @hassnian ?

**Comment by hassnian** [comment]
> cc @hassnian ?

with `price_ASC_NULLS_LAST` sort applied it's still showing unlisted nfts first

@vikiival `NULL LAST` does nothing atm since unlisted nfts are saved as `0` not `NULL` ,  I might be missing something

CleanShot 2024-09-21 at 14 34 31@2x

**Comment by vikiival** [comment]
>  does nothing atm since unlisted nfts are saved as 0 not NULL , do we change this ?

can you open a PR please? 
you need to update: mint, transfer, list functions

**Comment by hassnian** [comment]
> > does nothing atm since unlisted nfts are saved as 0 not NULL , do we change this ?
> 
> can you open a PR please? you need to update: mint, transfer, list functions

sure

**Comment by hassnian** [comment]
continue https://github.com/kodadot/nft-gallery/pull/11075

**Pull request closed without merging**
