### PR TITLE
fix: price range isn't queried on reload

### LINKED ISSUE #2399: Repetitive search shows empty results
When I set price filter and then wanted to search for `mug` I've got empty results. If I hit reload it appears back.
Where in that price range Mug was showing.

image

### PR DESCRIPTION
**Pull request by newraina**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2399
- [x] <brief_description_of_what_I've_added>
  - make price range queried on reload if url params contains `min` or `max`
  - the `Prices ranging from ...` prompt will appear if `min` or `max` url params works

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=CmVS5edpZFQeATFWFu72JzMnv6c3RzbyikpLJpYwZa9GXw9)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by newraina** [comment]
After fixed:

https://user-images.githubusercontent.com/10708802/160277009-ece4bfe0-11f4-4ca6-86de-c1e14d7cba85.mov

**Review by vikiival — APPROVED** [review]
YOLO mode,
It works

**Comment by vikiival** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 183.73 USD/KSM ~ 0.544 $KSM
🧗 [CmVS5edpZFQeATFWFu72JzMnv6c3RzbyikpLJpYwZa9GXw9](https://kusama.subscan.io/account/CmVS5edpZFQeATFWFu72JzMnv6c3RzbyikpLJpYwZa9GXw9)
🔗 [0x03c6489039fa02fd2e6666cd19bcde974e3dd1530da6d800356a080cf5e0e647](https://kusama.subscan.io/extrinsic/0x03c6489039fa02fd2e6666cd19bcde974e3dd1530da6d800356a080cf5e0e647)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
