### PR TITLE
fix: parentnode

### LINKED ISSUE #9075: Issues with redirect in create
- i always need to refresh the page to get on the desired link 

https://github.com/kodadot/nft-gallery/assets/90852205/f8b96712-1e76-4723-a3b4-16ac7c85b5e0

https://github.com/kodadot/nft-gallery/assets/90852205/6e74c955-d3fa-4140-becb-f1712d09743b

### LINKED ISSUE #9178: Clicking on user pop-over breaks page redirection/refresh
Access canary -> explore collections -> enter inside collection -> click on user popover to go to its profile -> try to switch tabs or click links on navbar: 

https://github.com/kodadot/nft-gallery/assets/36627808/d5520990-ebe6-42ed-8e3b-fd4ec1e14324

U is null

Same occurs when going to settings -> and then create -> nft

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Related `https://github.com/vuejs/core/issues/10098`
- [x] Closes #9075
- [x] Closes #9178

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
Nice! How did you manage to find it?

**Comment by preschian** [comment]
> Nice! How did you manage to find it?

At first, I check it by running the previous commit. First occurrence in this commit https://github.com/kodadot/nft-gallery/compare/99fee410d7677a79512ad2de79b9abae9cc81510...2c63a4387251e811d161241bc7ea4e361b204cc2

But when I made the changes to the current `main` branch, the error still occurred. Then give up and search the issue on vue/nuxt repo 🤣

**Review by Jarsen136 — APPROVED** [review]
nice

**Comment by yangwao** [comment]
Thanks!
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 6.93 USD/DOT ~ 7.215 $DOT
🧗 [1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p](https://polkadot.subscan.io/account/1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)
🔗 [0x2abcf7c3a049fbf0a3ebf3a18143df3f3ea15617f28077fc36fc9f5d4dc07cf3](https://polkadot.subscan.io/extrinsic/0x2abcf7c3a049fbf0a3ebf3a18143df3f3ea15617f28077fc36fc9f5d4dc07cf3)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
