### PR TITLE
feat: hover card msdos shadow and pink border

### LINKED ISSUE #1816: hover card v1.1
- border let be $primary
- add depth effect some like MS-DOS, ncurses ui
- depth could be made by black shadow or use texture in the third picture on the floor, yet really don't know its name @XyloDrone may whisper!

image

image

image

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇  _ Do a quick check before the merge.

Screenshot 2022-01-14 at 15 00 51

### PR type
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?
- [x] PR closes #1816
- [x] made border primary pink and added msdos style box shadow

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main-nuxt** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases

### Had issue bounty label ?
- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation
- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [x] My fix has changed **something** on UI, a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by yangwao** [comment]
Wow, looks amazing! 

Thinking, can we add it to Profile, Create, Extra, languages ?

image

image

image

image

**Comment by kkukelka** [comment]
@yangwao done
Screenshot 2022-01-14 at 16 15 40

**Comment by yangwao** [comment]
What if shadow could be bit more on left?

Thinking to have some symmetry, ie either 45 or 60 degrees? 🤔

**Comment by kkukelka** [comment]
> What if shadow could be bit more on left?
> 
> Thinking to have some symmetry, ie either 45 or 60 degrees? 🤔
> 
> Like currently it feels shadow way too far?
> 
Screenshot 2022-01-14 at 16 42 30
bra 📐

**Comment by kkukelka** [comment]
> What if shadow could be bit more on left?
> 
> Thinking to have some symmetry, ie either 45 or 60 degrees? 🤔
> 
> Like currently it feels shadow way too far?
> 

Screenshot 2022-01-14 at 16 46 45

put it closer and slightly down

**Comment by yangwao** [comment]
Perfect, I’ve sent the payout https://kusama.subscan.io/extrinsic/0x2136d226c6c059e916c7e11fa49cd9ede0a61f6b883267ec16574f896ace30be

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/

**Pull request merged**
