### PR TITLE
fix: collection and profile on bsx

### LINKED ISSUE #3039: Features that does not work with Basilisk
They are hardcoded - using `'subsquid'`, using ss58 `2`, using `KSM`

- #3136 
- #3137
- #3138
- #3279 

### Detail

`Error: Network error: Response not successful: Received status code 400`

### PR DESCRIPTION
**Pull request by KngZhi**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR related #3039
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer?target=DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by roiLeo — CHANGES_REQUESTED** [review]
Tested on `/bsx/u/bXjmyHufR6HcjAtKNVTV4UjHj3poQW3d2yYWKDdWe5cGGmg3z`
Screenshot 2022-06-09 at 08-41-48 NFT Artist Profile on KodaDot
Screenshot 2022-06-09 at 08-42-10 NFT Artist Profile on KodaDot

History & Sales tab are empty

**Comment by yangwao** [comment]
I guess it should be split into smaller issues.

**Comment by KngZhi** [comment]
For given `/bsx/u/bXjmyHufR6HcjAtKNVTV4UjHj3poQW3d2yYWKDdWe5cGGmg3z` the reason `Sales` does not show is

1. the query was hardcode
2. the following pic of response data of bsx and code showed.

image

and according to the sales logic
```js
for (const newEvent of this.events) {
      let isListedByUser =
        newEvent &&
        newEvent.nft &&
        newEvent.nft.events &&
        newEvent.nft.events.find(
          (e) => e.caller === this.issuer && e.interaction == 'LIST'
        )

      if (!isListedByUser) {
        continue
      }
}
```

Thus, we have to determine, either the code is not suitable with bsx, nor bsx returned wrong data that events should at least contain `LIST` event rather than none.

**Review by vikiival — CHANGES_REQUESTED** [review]
this will break rmrk

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
pay 70 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $70 @ 51.13 USD/KSM ~ 1.369 $KSM
🧗 [DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc](https://kusama.subscan.io/account/DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc)
🔗 [0x2985027ddd523dc2cd80692bcad968969c8b974595e6536000a3452dfcbcf198](https://kusama.subscan.io/extrinsic/0x2985027ddd523dc2cd80692bcad968969c8b974595e6536000a3452dfcbcf198)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
