### PR TITLE
NeoSteps to tailwindcss

### PR DESCRIPTION
**Pull request by shashkovdanil**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Closes #8222 
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [x] I've tested it at </ksm/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer?target=16SpvdDgKNiQ3c53DxX7refnQcKUD3uRNim3Z1HBJLNGrtSP&usdamount=0)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 032c5ed</samp>

Refactored the steps component to use Tailwind CSS utilities and custom properties, and updated the Tailwind configuration and scss files accordingly. This improves the UI code quality and design consistency.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 032c5ed</samp>

> _Oh we're the crew of the NeoSteps, and we sail the web with ease_
> _We use `Tailwind CSS` to style our ship, and custom properties_
> _We heave away on the `tailwind.config.js`, and we make it nice and clear_
> _We set the colors and the opacities, for the UI we hold dear_

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]

**Review by daiagi — CHANGES_REQUESTED** [review]
the color of the line between steps is not same as in canary:
https://canary.kodadot.xyz/ahk/waifu

**Comment by prury** [comment]
Dark mode: 
Deployed:
image

Canary:
image

**Comment by yangwao** [comment]
thanks!
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 6.5 USD/DOT ~ 3.077 $DOT
🧗 [16SpvdDgKNiQ3c53DxX7refnQcKUD3uRNim3Z1HBJLNGrtSP](https://polkadot.subscan.io/account/16SpvdDgKNiQ3c53DxX7refnQcKUD3uRNim3Z1HBJLNGrtSP)
🔗 [0xcde718915600e849a3af52353defe3a7da277d7df6f5808e085f1e76b9733b9f](https://polkadot.subscan.io/extrinsic/0xcde718915600e849a3af52353defe3a7da277d7df6f5808e085f1e76b9733b9f)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
