### PR TITLE
#1749 Fixing transfer and teleport

### LINKED ISSUE #1749: Transfer seems broken on Beta
Seems it's missing
Test at https://beta.kodadot.xyz/transfer/?usdamount=100&target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU

- the current price of $KSM
- when I enter USD value, doesn't update KSM amount
- when I enter KSM amount, doesn't update USD amount
- missing unit for native asset?

### Ref
image

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇  _ Do a quick check before the merge.

### PR type
- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?
- [x] PR closes #1749
- [x] Changed getters for both **transfer** and **teleport**, thanks @roiLeo for the solution 

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main-nuxt** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases

### Had issue bounty label ?
- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation
- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [ ] My fix has changed **something** on UI, a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by roiLeo — CHANGES_REQUESTED** [review]
missing:
```js
    this.$store.dispatch('fiat/fetchFiatPrice')
```
in Transfer.vue & Teleport.vue

console.warn is not rly the best solution to hide the router errors

**Comment by roiLeo** [comment]
> @roiLeo in transfer and teleport `this.$store.dispatch('fetchFiatPrice')` this is already there, is this `this.$store.dispatch('fiat/fetchFiatPrice') `different?

- `this.$store.dispatch('fetchFiatPrice')` will not work because it look into `/store/index`
- `this.$store.dispatch('fiat/fetchFiatPrice')`  will look into `/store/fiat` & dispatch fetchFiatPrice action

> Also, the other way to solve the error is to add an if check comparing current and previous route, I am not sure how to get the previous route in this case tho, since the route is dynamic

I don't have any idea for now, could be fixed with watcher option? we'll leave it like that

**Review by roiLeo — APPROVED** [review]
lgtm

by the way, random text found in /teleport.vue
Screenshot 2022-01-10 at 17-58-04 #1749 Fixing transfer and teleport by prachi00 · Pull Request #1750 · kodadot nft-gallery

**Comment by prachi00** [comment]
> teleport

I have went ahead and removed this

**Comment by prachi00** [comment]
> > teleport
> 
> I have went ahead and removed the random text

**Review by roiLeo — APPROVED** [review]

**Comment by yangwao** [comment]
can we have it together?

image
image

**Comment by prachi00** [comment]
> can we have it together?
> 
> image image

@yangwao should I do this in this PR only or another one? I think it would be better to do it in another one

**Comment by prachi00** [comment]
> > can we have it together?
> > image image
> 
> @yangwao should I do this in this PR only or another one? I think it would be better to do it in another one

**EDIT:** @yangwao decided to do it in this PR only since it was a small css change

Screenshot 2022-01-11 at 1 58 25 PM

**Review by roiLeo — CHANGES_REQUESTED** [review]
- please use `layout()` like in transfer.vue

**Comment by prachi00** [comment]
> * transfer.vue
Screenshot 2022-01-11 at 4 18 39 PM
@roiLeo used layout

**Review by roiLeo — APPROVED** [review]
lgtm

**Comment by yangwao** [comment]
hey @prachi00 seems doesn't work as the payment link is generating this kind of URL https://undefined.subscan.io/extrinsic/0x7a0addacaff4e14a036fb9255665c311fb6fb4d9cd447a965a654eb33f87dadb :)

can you please take a look?

**Comment by prachi00** [comment]
> hey @prachi00 seems doesn't work as the payment link is generating this kind of URL https://undefined.subscan.io/extrinsic/0x7a0addacaff4e14a036fb9255665c311fb6fb4d9cd447a965a654eb33f87dadb :)
> 
> can you please take a look?

@yangwao Have fixed this, working now.

**Comment by yangwao** [comment]
Seems this time it could not generate a link to the transaction 
This is what I have in console

image

**Comment by prachi00** [comment]
@yangwao seems to work fine for me, I tried doing it on local

**Comment by yangwao** [comment]
okay tested https://kusama.subscan.io/extrinsic/0xd03980f2adbe9fb10d39bbd5777450c7743f23f102604f16331f52aa88e48be4

seems cache... but that warning of navigationduplicated should be solved tho made issue on that for #1769 if you are keen to debug that

**Comment by yangwao** [comment]
Perfect, I’ve sent the payout https://kusama.subscan.io/extrinsic/0x7a0addacaff4e14a036fb9255665c311fb6fb4d9cd447a965a654eb33f87dadb

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/

**Pull request merged**
