### PR TITLE
Show keyboard shortcuts board when user presses ? key.

### LINKED ISSUE #2259: Add keyboard shortcuts cheat sheet on kbd short cut
I guess we should add some keyboard shortcuts board like this 
Once the user presses `?` it will show 

Once is done #2097 
image

### PR DESCRIPTION
**Pull request by chandradot99**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2259
- [ ] Added keyboard shortcuts modal and it will show when user presses ? key

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=CeBWgisygADqqxGk7ju8aMNEKz1K2WkxMKC3G8HsMnm119n)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by chandradot99** [comment]
Screenshot 2022-02-09 at 3 14 54 AM

**Comment by chandradot99** [comment]
@yangwao  In this case, if background page has some text, then it's overlapping with modal text.

Screenshot 2022-02-09 at 6 41 30 PM

**Comment by yangwao** [comment]
> @yangwao In this case, if background page has some text, then it's overlapping with modal text.
> 
> Screenshot 2022-02-09 at 6 41 30 PM

hmm let's play with opacity and go with something, let's try 0.6 ?

**Comment by chandradot99** [comment]
Ok @yangwao i will make the necessary changes

**Comment by chandradot99** [comment]
Screenshot 2022-02-11 at 2 42 56 AM

@yangwao this looks better, I am going with this option.

**Comment by chandradot99** [comment]
@yangwao @roiLeo I have added some css in `global.scss`, but after that I am not able to commit because it's giving me below error, any idea on this.

Screenshot 2022-02-11 at 3 15 19 AM

Do we need to exclude scss files from eslint ??

**Comment by chandradot99** [comment]
this is how scss looks like, not sure why it's giving error on line 3:3

Screenshot 2022-02-11 at 3 19 22 AM

**Comment by chandradot99** [comment]
In `package.json` I changed this

```
"lint-staged": {
    "*.{js,ts,vue,css,scss,md}": [
      "prettier --write",
      "yarn lint:quiet"
    ]
  },

```

to

```
"lint-staged": {
    "*.{js,ts,vue,md}": [
      "prettier --write",
      "yarn lint:quiet"
    ]
  },
```

then it works.

**Comment by chandradot99** [comment]
@yangwao I am done with the changes.

**Comment by yangwao** [comment]
love it 

pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 180.96 USD/KSM ~ 0.553 $KSM
🧗 [CeBWgisygADqqxGk7ju8aMNEKz1K2WkxMKC3G8HsMnm119n](https://kusama.subscan.io/account/CeBWgisygADqqxGk7ju8aMNEKz1K2WkxMKC3G8HsMnm119n)
🔗 [0xc97b799d5527e492f09c709677c90a55e3f824f78c36202b280404a12e39d6cd](https://kusama.subscan.io/extrinsic/0xc97b799d5527e492f09c709677c90a55e3f824f78c36202b280404a12e39d6cd)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
