### PR TITLE
feat: add tooltip for expiration on offer table

### LINKED ISSUE #3639: expiration time detail tooltip
can we somehow give user the ability to see the actual approximation of expiration time? Like full date popup on click or something. Maybe @roiLeo can think of something UX friendly 😅 I think sometimes it will matter, like what does 1 day mean except the information that it's >24 and <48

_Originally posted by @petersopko in https://github.com/kodadot/nft-gallery/issues/3625#issuecomment-1200382765_

### LINKED ISSUE #3649: We could add the tooltip for expiration on offer table also in a user profile
https://user-images.githubusercontent.com/104791453/182393646-bf74d159-c77c-4c3b-ba2a-76ce08b16c4c.mov

We could add the time also in a user profile.

### PR DESCRIPTION
**Pull request by KngZhi**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3639
- [x] PR closes #3649
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer?target=HgpGWWmqrw8t6viwSy6LPcTVr2SuVPKWW5ArdNp2xCJY2U4)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

https://user-images.githubusercontent.com/11361147/182155614-6b082128-24ab-4dd3-b708-d66c4ce2eff1.mov

image

### CODE REVIEW

**Comment by KngZhi** [comment]
@petersopko for now, I kind of hide the tooltip of the expiration date.

**Comment by petersopko** [comment]
just one thing I've noticed, we're not showing timezone here (utc) so can we add that as well, please? I've checked how is it done in: https://deploy-preview-3642--koda-nuxt.netlify.app/sales and that looks more informative to me

**Comment by DeluneClaire** [comment]
> **Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz). 👇 _ Let's make a quick check before the contribution.
> ### PR type
> 
>     * [ ]  Bugfix
> 
>     * [x]  Feature
> 
>     * [ ]  Refactoring
> 
> 
> ### What's new?
> 
>     * [x]  PR closes [expiration time detail tooltip #3639](https://github.com/kodadot/nft-gallery/issues/3639)
> 
>     * [ ]  Requires deployment <rubick/magick_issue>
> 
>     * [ ]  <brief_description_of_what_I've_added>
> 
> 
> ### Before submitting Pull Request, please make sure:
> 
>     * [x]  My contribution builds **clean without any errors or warnings**
> 
>     * [x]  I've merged recent default branch -- **main** and I've no conflicts
> 
>     * [x]  I've tried to respect high code quality standards
> 
>     * [x]  I've didn't break any original functionality
> 
>     * [x]  I've posted a screenshot of demonstrated change in this PR
> 
> 
> ### Optional
> 
>     * [ ]  I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
> 
>     * [ ]  I've tested PR on mobile and everything seems works
> 
>     * [ ]  I found edge cases
> 
>     * [ ]  I've written some unit tests 🧪
> 
> 
> ### Had issue bounty label?
> 
>     * [x]  Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer?target=DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc)
> 
> 
> ### Community participation
> 
>     * [x]  [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)
> 
> 
> ### Screenshot
> 
>     * [x]  My fix has changed **something** on UI; a screenshot is best to understand changes for others.
> 
> 
> Screen.Recording.2022-08-01.at.9.11.46.PM.mov

Hi, could you please load the screen recording again? It's not working, and it would be helpful to see it.

**Comment by KngZhi** [comment]
image

**Review by DeluneClaire — APPROVED** [review]
WFM.

**Comment by prachi00** [comment]
@KngZhi 
https://deploy-preview-3641--koda-nuxt.netlify.app/bsx/gallery/10000001-0
here
it says expiration is 2 months, on hover it says November which would be like 3 months?
Screen Shot 2022-08-02 at 3 26 39 PM

**Comment by KngZhi** [comment]
image

this is 2 months 30 days. @prachi00

**Review by prachi00 — APPROVED** [review]

**Comment by prachi00** [comment]
pay 75 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $75 @ 60.73 USD/KSM ~ 1.235 $KSM
🧗 [HgpGWWmqrw8t6viwSy6LPcTVr2SuVPKWW5ArdNp2xCJY2U4](https://kusama.subscan.io/account/HgpGWWmqrw8t6viwSy6LPcTVr2SuVPKWW5ArdNp2xCJY2U4)
🔗 [0x018b8eb9d61eadd0aad84edc676b2218cdb19ac1871af898ae4a7a8cf6ca84c5](https://kusama.subscan.io/extrinsic/0x018b8eb9d61eadd0aad84edc676b2218cdb19ac1871af898ae4a7a8cf6ca84c5)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
