### PR TITLE
fix: Change description of SEO Cards

### LINKED ISSUE #4732: Change description of SEO Cards
I guess since we are multi-chain, we should adjust punch line from "Creating Carbonless NFTs on Kusama" to "One Stop Shop NFTs on Polkadot" is more marketable stuff 

test at https://beta.kodadot.xyz/bsx/gallery/4155379122-13

where is "kodadot-nft-gallery" coming from? Probably change it to "KodaDot NFT Marketplace"

image

ok seems it works to fetch descriptions sometimes? that's ok then!

image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4732
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by Jarsen136** [comment]
✅  tested in discord

https://deploy-preview-4737--koda-nuxt.netlify.app/bsx/gallery/4155379122-11
image

image

**Review by roiLeo — APPROVED** [review]
🚀

**Comment by yangwao** [comment]
Grammar n*** has bumped me

@Jarsen136 can you change it pls to 🥹

"One Stop NFT Shop on Polkadot"

**Review by vikiival — APPROVED** [review]

**Comment by Jarsen136** [comment]
> Grammar n*** has bumped to me
> 
> @Jarsen136 can you change it pls to 🥹
> 
> "One Stop NFT Shop on Polkadot"

✅ Done

**Comment by vikiival** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 36.44 USD/KSM ~ 0.549 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x5dc94374b8519364bccd99d2832e173f3ab06c021f5dad6d6ba8666a2086e032](https://kusama.subscan.io/extrinsic/0x5dc94374b8519364bccd99d2832e173f3ab06c021f5dad6d6ba8666a2086e032)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
pay 20

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 34.98 USD/KSM ~ 0.572 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x2c71520008eb7cff7ad4f8c12aef79b5437358d855a7aabeb1c003fda4717bb8](https://kusama.subscan.io/extrinsic/0x2c71520008eb7cff7ad4f8c12aef79b5437358d855a7aabeb1c003fda4717bb8)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
