### PR TITLE
fix: radio button on waifu

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [ ] Closes #<issue_number>
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [ ] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>)

## Screenshot 📸

- [ ] My fix has changed UI

### <samp>🤖 Generated by Copilot at 44dd3d6</samp>

Refactored some form components to use `v-model` and Vue 3 conventions for two-way data binding and event emitting. Fixed a visual bug in `NeoRadioButton` component.

### <samp>🤖 Generated by Copilot at 44dd3d6</samp>

> _We bind the data with `v-model`_
> _We simplify the logic with `emit`_
> _We fix the bugs with computed props_
> _We refactor the code with `useVModel`_

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
Capture d’écran 2023-10-06 à 12 05 45 PM

**Comment by preschian** [comment]
> Capture d’écran 2023-10-06 à 12 05 45 PM

Could you try to reload the page again?

**Comment by roiLeo** [comment]
> > Capture d’écran 2023-10-06 à 12 05 45 PM
> 
> Could you try to reload the page again?

still an issue, same as when I checkout the branch

**Comment by preschian** [comment]
> still an issue, same as when I checkout the branch

interesting, error on local or production build?

**Comment by roiLeo** [comment]
now it work

**Pull request merged**
