### PR TITLE
#9112

### LINKED ISSUE #9112: Profile stats reorder
- based on community feedback, let's reorder the stats in the profile 

image

lets put max sold price under listed, and the highest buy/amount spent under number of buys

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #9112

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)

## Screenshot 📸

- [x] My fix has changed UI

Screen Shot 2024-01-23 at 3 19 33 PM

### CODE REVIEW

**Review by preschian — APPROVED** [review]
long time no see 👋 welcome back

**Review by roiLeo — APPROVED** [review]

**Comment by yangwao** [comment]
thanks!
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 6.41 USD/DOT ~ 3.12 $DOT
🧗 [13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1](https://polkadot.subscan.io/account/13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)
🔗 [0x8da5322439f3239400448f02322eafa702a7d783101779642cad618cc7d6994b](https://polkadot.subscan.io/extrinsic/0x8da5322439f3239400448f02322eafa702a7d783101779642cad618cc7d6994b)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by prachi00** [comment]
> long time no see 👋 welcome back

Hi, yes I went on a long holiday to India for 2 months, thank you

**Pull request merged**
