### PR TITLE
remove padding from collectionprofile image

### LINKED ISSUE #7981: Profile picture collection
while i do not oppose the background centering change, i think the issue was about this:

image

and it is still ocurring

_Originally posted by @prury in https://github.com/kodadot/nft-gallery/issues/7943#issuecomment-1794766117_

correct, this was also meant to be part of the previous issue

happens here too: 
https://deploy-preview-7968--koda-canary.netlify.app/ahk/collection/258

should set to cover

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs Design check

- @exezbcz please review

## Context

- [x] Closes #7981
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)

## Screenshot 📸

- [x] My fix has changed UI

### Before
image

### After

image

### <samp>🤖 Generated by Copilot at 34a0eea</samp>

Refactored collection banner component to use Tailwind CSS. Removed padding style from `.collection-banner` class in `CollectionBanner.vue`.

### <samp>🤖 Generated by Copilot at 34a0eea</samp>

> _`collection-banner`_
> _No more custom padding style_
> _`p-4` in autumn_

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]

**Comment by prury** [comment]
nice, but i think we still have a problem tho, it should look similar to collection cards imo:
Cards:
image
Collection:
image

**Comment by daiagi** [comment]
@prury  assuming you were talking about the padding size around the image
fixed

**Comment by prury** [comment]
> @prury assuming you were talking about the padding size around the image fixed

yup, ty!

**Comment by yangwao** [comment]
thanks!
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 5.3 USD/DOT ~ 3.774 $DOT
🧗 [1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8](https://polkadot.subscan.io/account/1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)
🔗 [0x42af22910fbe4c3ff7e7888ae6b6c0adc9f0d77f76ef96ec735349ebb3607097](https://polkadot.subscan.io/extrinsic/0x42af22910fbe4c3ff7e7888ae6b6c0adc9f0d77f76ef96ec735349ebb3607097)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
