### PR TITLE
feat: add ability to download asset

### LINKED ISSUE #2557: Add ability to download asset you own from actions
As we disabled right-click context menu #2443 
despite PFP culture, we would like to enable owners, to download their assets and used them elsewhere. (twitter, discord, telegram,steam, elsewhere social network)

Add to action list 
[Right-Click-Save] use club-mate yellow, posting pic for reference:D
 
and it will download the asset at which you are the owner.

image

image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2557 
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [x] I found edge cases
- [x] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by Jarsen136** [comment]
> Thinking why you used this hacky approach ? https://www.npmjs.com/package/file-saver

Thanks your comment. I can give you some reason.
1. This approach isn't hacky.  It is a common way with js to download image in browser.
more details: https://dev.to/sbodi10/download-images-using-javascript-51a9
2. Import new package is a big deal which need some necessary reasons. In this case, downloading image is just a simple function and there is no need for customization. [file-saver] is a good tool but it's unnecessary for this case. Import new package will increase bundle size also.

**Comment by yangwao** [comment]
wfm, waiting for review )

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 145.58 USD/KSM ~ 0.687 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x0620d24e13b9ee0c01de03a92fc9ceb40ae787c10cd194a3775bfb39c62da422](https://kusama.subscan.io/extrinsic/0x0620d24e13b9ee0c01de03a92fc9ceb40ae787c10cd194a3775bfb39c62da422)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
