### PR TITLE
Updating portuguese Language

### PR DESCRIPTION
**Pull request by virtugroweey**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [X] Refactoring

### What's new?

- [ ] PR closes #<issue_number>
- [X] Translation to the new interface en to pt. 

### Before submitting Pull Request, please make sure:

- [X] My contribution builds **clean without any errors or warnings**
- [X] I've merged recent default branch -- **main** and I've no conflicts
- [X] I've tried to respect high code quality standards
- [X] I've didn't break any original functionality
- [X] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [X] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer?target=E7vqtZ89f4wKZwbiVHQ2MDKiQ1DuTxHnRHpri6zLQzHwv5B)

### Community participation

- [X] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [X] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

### CODE REVIEW

**Comment by yangwao** [comment]
I guess we are missing translation strings for these?

**Comment by virtugroweey** [comment]
I can't find the original string in json to modify to portuguese.

**Comment by yangwao** [comment]
Let's merge this one and open issue to requesting further strings to have there so you could translate them :)

Someone will pick it up and can give it priority and bounty tho.

pay 100 usd

**Comment by virtugroweey** [comment]
Ok thank you very much. How i can close this? I'm newbie :P

**Comment by yangwao** [comment]
Ah. Put there your address in your first, in template, hit edit :)

Usually workflow is I pay it out to your address and merge it to main.

**Comment by virtugroweey** [comment]
> Ah. Put there your address in your first, in template, hit edit :)
> 
> Usually workflow is I pay it out to your address and merge it to main.

Ok done. I edited the my commit first template.

Wow is so good work here in this github platform. I didn't know that is so cool.

**Comment by virtugroweey** [comment]
I think i made it

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
> I think i made it

I guess you need keep up formatting))

**Comment by virtugroweey** [comment]
> > I think i made it
> 
> I guess you need keep up formatting))

Ok. I like to learn with my mistakes lmao. thank you for all. I would like to help more

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
Bot is weird, paid out 100$ )
https://kusama.subscan.io/extrinsic/0xc62df416cfc829e216bc05902599ae7d4bd893a1ec14588fcddcabf4e98142d8

**Pull request merged**
