### PR TITLE
fix: balanceInput is broken

### LINKED ISSUE #3632: BalanceInput.vue is broken - again
It seems that we have, once again, merged into beta something which broke price setting. We're at the same problem as last time:

1. you cannot submit offer, because price is always too low
2. listing NFTs is possible, but most of the price is always turned to zero

Last time, this was a formatting problem iirc, check:
- https://github.com/kodadot/nft-gallery/pull/3595

### LINKED ISSUE #3634: When I want to relist a nft, it tells me that the price I set should be lower than my balance
I found another bug related to balanceInput on `https://beta.kodadot.xyz/`.

1. When I want to relist a nft, it tells me that the price I set should be lower than my balance.
image

2. What's more, the price I set should be greater than 10000
image

_Originally posted by @Jarsen136 in https://github.com/kodadot/nft-gallery/issues/3633#issuecomment-1200399394_

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3632
- [x] PR close #3634
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by Jarsen136** [comment]
This bug was introduced from #3573 in the conflict-solving process : )  cc @petersopko

**Review by petersopko — APPROVED** [review]
wfm

**Comment by petersopko** [comment]
@yangwao can we speedtrack this to get beta back on track ? (currently mints with 0bsx and offers are not working)

**Comment by Jarsen136** [comment]
I found another bug related to balanceInput on `https://beta.kodadot.xyz/`.

1. When I want to relist a nft, it tells me that the price I set should be lower than my balance.
image

2. What's more, the price I set should be greater than 10000
image

**Comment by Jarsen136** [comment]
> I found another bug related to balanceInput on `https://beta.kodadot.xyz/`.
> 

✅  Fixed

image
image

**Comment by yangwao** [comment]
> 2\. What's more, the price I set should be greater than 10000

yes, this is some basilisk thing, the minimum price for the offer, 
I guess with the upcoming Rococo deployment, it will change.

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 64.01 USD/KSM ~ 0.781 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x3a0dc687823cd52062c1bcf4d455f7dcd617fef8a63e5acf68baec9137b0e5c6](https://kusama.subscan.io/extrinsic/0x3a0dc687823cd52062c1bcf4d455f7dcd617fef8a63e5acf68baec9137b0e5c6)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
