### PR TITLE
fix unsupported file on bsx

### LINKED ISSUE #3262: Support for GLTF ?
It's supposed to show through a model-viewer?

https://beta.kodadot.xyz/bsx/gallery/2444376227-1

https://kodadot.mypinata.cloud/ipfs/bafkreigmublnwqdssbr4nhyxhsgkamrwwh3hejpbime27xdbzkrwrblwza
image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3262 
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others. 

image

### CODE REVIEW

**Comment by Jarsen136** [comment]
It seems that the url in the file JSON is invalid. 👀 


`/bsx/gallery/2444376227-1`

image


image

image

image

**Comment by petersopko** [comment]
> * [ ]  <brief_description_of_what_I've_added>

@Jarsen136 can you please help me out here? Not sure what I'm supposed to be seeing from the screenshot, ball is still not loading?

**Review by petersopko — CHANGES_REQUESTED** [review]
> > * [ ]   <brief_description_of_what_I've_added>
> 
> @Jarsen136 can you please help me out here? Not sure what I'm supposed to be seeing from the screenshot, ball is still not loading?

pls check

**Comment by Jarsen136** [comment]
> > * [ ]   <brief_description_of_what_I've_added>
> 
> @Jarsen136 can you please help me out here? Not sure what I'm supposed to be seeing from the screenshot, ball is still not loading?

It's still in progress. I used view-model to display the nft, but seems its file is invalid. 
I'm not sure if it's a problem with the file or the interface `kodadot.mypinata.cloud/ipfs/`.  
I need some help from @vikiival @roiLeo

**Comment by roiLeo** [comment]
I uploaded a wrong file as it need two file to be displayed 
Can't be replaced so i'm going to burn this one

**Comment by Jarsen136** [comment]
> I uploaded a wrong file as it need two file to be displayed Can't be replaced so i'm going to burn this one

Then I think this PR is good to go. It needs another AR nft to test.

**Comment by roiLeo** [comment]
2nd Test with glb file `/bsx/gallery/2444376227-2` 

Capture d’écran 2022-06-25 à 9 04 53 PM


When user create 3D nft, we could add a preview on the dropzone

**Comment by Jarsen136** [comment]
The 3D ball is back 🏓 

image

**Comment by Jarsen136** [comment]
> 2nd Test with glb file `/bsx/gallery/2444376227-2`


The 3D ball is back now 🏓
> 

>

image

**Review by petersopko — APPROVED** [review]
wfm

**Comment by petersopko** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 56.9 USD/KSM ~ 1.757 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x0c177f083cfe1e3343f7019a86ce871483a5f98291b3a726284d5250bcf370a4](https://kusama.subscan.io/extrinsic/0x0c177f083cfe1e3343f7019a86ce871483a5f98291b3a726284d5250bcf370a4)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by roiLeo** [comment]
So what changed here? What does it fix?

**Comment by Jarsen136** [comment]
> So what changed here? What does it fix?

Hey, pls take a look at this PR. Your second ball is back now.

**Pull request merged**
