### PR TITLE
added new medium article writings list

### LINKED ISSUE #3053: Status of KodaDot Github repositories & dynamics
Write an article status quo and activity of KodaDot's GitHub repositories

- draft the current contributors culture of how we are operating, from issue, discussion, pull-request, code-review and paying out contributors
- the flow of someone makes the issue, bug report, contribute to code review  
- code review guild - why is it important to have quality code and peer-reviewed codebase
- highlight 
  - assign bot (petersopko will be launching writing on that #3010 )
  - payout bot (that trusted developers does payouts between themselves for PRs)
- contributors, forks, stars, growth of the repository
- name our popular repositories, so people can contribute elsewhere
- mention contributing.md
- post it to dev.to

Anything else we should mention?

image

### Ref
- #1661

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3053
- [ ] Requires deployment <rubick/magick_issue>
- [x] this PR marks the completion and release of medium article https://medium.com/p/665243d3d6a6

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by petersopko** [comment]
@kkukelka I like the article, clear and concise writing as usual 🚀 Can we just please not link to the KodaBot repo but to the [KodaBot article](https://dev.to/petersopko/kodabot-pt-1-1ge3) instead? The repo itself isn't very maintained (I'm working on it) and not really ready for some wider presentation 😆

**Comment by kkukelka** [comment]
> @kkukelka I like the article, clear and concise writing as usual 🚀 Can we just please not link to the KodaBot repo but to the [KodaBot article](https://dev.to/petersopko/kodabot-pt-1-1ge3) instead? The repo itself isn't very maintained (I'm working on it) and not really ready for some wider presentation 😆

sure thing. now links to article
Screenshot 2022-08-12 at 15 31 11

**Comment by petersopko** [comment]
this lgtm, @yangwao might wanna take a peak?

**Review by petersopko — APPROVED** [review]

**Comment by kkukelka** [comment]
maybe @cryptodamsky can give final approve since he actually published it

**Comment by kkukelka** [comment]
someone want to give second approval? 😭

**Review by roiLeo — APPROVED** [review]
I got you 🦖

**Comment by roiLeo** [comment]
Something strange lint stage is in error 😶‍🌫️

**Comment by preschian** [comment]
> > Something strange lint stage is in error 😶‍🌫️
> 
> i'll rerun the failed cypress tests. probably some errors due to some endpoint being unresponsive

safe to merge I think. I guess that e2e for the media component is still flaky because of `429 too many request` error https://github.com/kodadot/nft-gallery/issues/3745#issuecomment-1221730107

I still don't know how to fix that e2e test case :( any idea how to fix it? or should I disable it instead?

**Comment by kkukelka** [comment]
> > > Something strange lint stage is in error 😶‍🌫️
> > 
> > 
> > i'll rerun the failed cypress tests. probably some errors due to some endpoint being unresponsive
> 
> safe to merge I think. I guess that e2e for the media component is still flaky because of `429 too many request` error [#3745 (comment)](https://github.com/kodadot/nft-gallery/issues/3745#issuecomment-1221730107)
> 
> I still don't know how to fix that e2e test case :( any idea how to fix it? or should I disable it instead?

well we would need to adapt the corresponding endpoint such that it will accept more requests in a specified timeframe. i guess the limit is there to prevent overusage of some kind of serverless function or DDOS prevention

**Comment by kkukelka** [comment]
all green 👀

**Pull request merged**
