### PR TITLE
fix: clear search url

### LINKED ISSUE #5185: Clearer urls
make it so hitting enter without searching for anything would not write search query param into the url

_Originally posted by @daiagi in https://github.com/kodadot/nft-gallery/pull/5170#discussion_r1125953028_

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5185
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### CODE REVIEW

**Review by daiagi — APPROVED** [review]

**Review by roiLeo — COMMENTED** [review]
Is it normal that the search param is not kept between tabs? or it's out of spec?

Step to reproduce:
- chain bsx
- seach "kitty"
- (no breadcrumb in collection page)
- toggle Items page
- search is reset

**Comment by vikiival** [comment]
> Is it normal that the search param is not kept between tabs? or it's out of spec?
> 
> Step to reproduce:
> 
> * chain bsx
> * seach "kitty"
> * (no breadcrumb in collection page)
> * toggle Items page
> * search is reset

cc @yangwao || @exezbcz

**Comment by exezbcz** [comment]
yup, I did not include that in the design but I we should add it there. Since we did not remove the divider and we are still showing the collection count, we can show search tag here as well. 
@roiLeo 

I will create issue in a moment

**Comment by Jarsen136** [comment]
> yup, I did not include that in the design but I we should add it there. Since we did not remove the divider and we are still showing the collection count, we can show search tag here as well. @roiLeo
> 
> I will create issue in a moment

I have seen the issue created here https://github.com/kodadot/nft-gallery/issues/5199  Then I guess we could merge this PR

**Pull request merged**
