### PR TITLE
Make sure if user has enough funds to make offer

### LINKED ISSUE #3346: Make sure if user has enough funds to make offer (decimal points)
Seems we don't check whether users can submit a higher offer than has the amount of balance on own account? 
EDIT seems different kind of issue plus it's related to LIST, check screenshot below

https://user-images.githubusercontent.com/5887929/177558642-96455301-62ee-4446-b45f-e0327edc6b45.mov

image

Seems related when you doing LIST as well

image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3346 
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by yangwao** [comment]
Seems works as anticipated 
Let's someone check the code 

image

image

**Comment by prachi00** [comment]
@Jarsen136 @yangwao this should have been already fixed by #3324

**Comment by prachi00** [comment]
> @Jarsen136 @yangwao this should have been already fixed by #3324

oh I see, this pr only formats the balance, makes sense

**Review by prachi00 — APPROVED** [review]

**Comment by prachi00** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 53.32 USD/KSM ~ 0.938 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xba879a5ce26fedfc81b6fe0321f0e30d2f216a091523eec4997e06b93ce3c010](https://kusama.subscan.io/extrinsic/0xba879a5ce26fedfc81b6fe0321f0e30d2f216a091523eec4997e06b93ce3c010)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
