### PR TITLE
Refactor seoMetaGenerator

### PR DESCRIPTION
**Pull request by nick-dev123**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [X] Refactoring

## Context

- [X] Related to #5314
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [X] My contribution builds **clean without any errors or warnings**
- [X] I've merged recent default branch -- **main** and I've no conflicts
- [X] I've tried to respect high code quality standards
- [X] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [X] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?usdamount=20&target=12ZLwasAvpdxDiiMedr11VeKUyQkY3WfneMkswBCAHVvxAqe)

#### Community participation

- [ ] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at ccf9e6d</samp>

This pull request refactors several pages to use the composition API and the `useHead` composable from `@vueuse/head` library. This improves the code readability and consistency, and simplifies the document head management. The pages affected are `pages/e2e-login.vue`, `pages/privacy-policy.vue`, `pages/series-insight.vue`, `pages/carbonless.vue`, `pages/cookie-notice.vue`, `pages/hot.vue`, `pages/qrCode.vue`, and `pages/sales.vue`.

### <samp>🤖 Generated by Copilot at ccf9e6d</samp>

> _To manage the document head_
> _They used `useHead` instead_
> _Of the old `head` method_
> _That was not so splendid_
> _And refactored some pages they said_

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
Hello what about other pages that use `this.$seoMeta`?

**Comment by nick-dev123** [comment]
> Hello what about other pages that use `this.$seoMeta`?

Wanted to check if these are okay before doing all of them. Are there any issues with these?

**Comment by roiLeo** [comment]
> Wanted to check if these are okay before doing all of them. Are there any issues with these?

not at all, that's what we expected. 

I would:
- remove `seoMetaGenerator` file too and see if we can't reuse stuff from it.
- check if there are defaults meta tags too.
- check seo preview on GalleryItem & CollectionItem pages


Keep it up!

**Comment by roiLeo** [comment]
I'll merge it from now, feel free to add the rest

**Comment by yangwao** [comment]
pay 20 usd

**Comment by yangwao** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 4.03 USD/DOT ~ 4.963 $DOT
🧗 [12ZLwasAvpdxDiiMedr11VeKUyQkY3WfneMkswBCAHVvxAqe](https://polkadot.subscan.io/account/12ZLwasAvpdxDiiMedr11VeKUyQkY3WfneMkswBCAHVvxAqe)
🔗 [0xee4677025458bcda32bf5fc72714facabd7df1444ba8cab7771fc2f15c254aad](https://polkadot.subscan.io/extrinsic/0xee4677025458bcda32bf5fc72714facabd7df1444ba8cab7771fc2f15c254aad)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
