### PR TITLE
fix: I invented time warp

### LINKED ISSUE #9919: I invented time warp
USS enterprise warping
-

Me at kodadot 
-
image

image

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

tried multiple times but I haven't been able to reproduce it, the issue is that somehow the main action got finalized before any of the pre steps were completed. 

Ensure all steps are completed before triggering an auto-teleport finalized event.

@prury pls test inside any a paid drop and also when buying or any other action, thanks

- [x] Closes #9919

## Needs QA check

- @kodadot/qa-guild please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

https://github.com/kodadot/nft-gallery/assets/44554284/a0e2e715-bfd3-47db-9b2e-2cfc6736c5ab

https://github.com/kodadot/nft-gallery/assets/44554284/23cdd5bd-54ed-4d4d-ad8e-2e3e14013e48

### CODE REVIEW

**Comment by vikiival** [comment]
@yangwao can you please test? 

As you are the glitch master, thanks

**Comment by prury** [comment]
could not reproduce either on canary, but all my tests worked ok

**Comment by vikiival** [comment]
> could not reproduce either on canary, but all my tests worked ok

🤠

**Review by vikiival — APPROVED** [review]
Without test or explanation from @yangwao. 

Marked as YOLO merge 🤠

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 8.53 USD/DOT ~ 3.517 $DOT
🧗 [16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD](https://polkadot.subscan.io/account/16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)
🔗 [0x94e2861f9ea5c942cc20f985078c026bff67ffa5652ef4330a92681fbfba5529](https://polkadot.subscan.io/extrinsic/0x94e2861f9ea5c942cc20f985078c026bff67ffa5652ef4330a92681fbfba5529)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
