### PR TITLE
fix: Sometimes Audio resources are shown as images

### LINKED ISSUE #7499: Sometimes Audio resources are shown as images
CleanShot 2023-10-04 at 11 30 45@2x

              > /ksm/gallery/15297922-900d19dc7d3c444e4c-PLANETPO-DEEPOLOGIC_PLANET_PO_EP-00000003

@preschian 
this seems an issue unrelated to this pr , animation url is NULL 

CleanShot 2023-10-04 at 11 19 35@2x

CleanShot 2023-10-04 at 11 10 24@2x

this is an indexer issue isn't or how else do you know that a resource is of audio type?

atm that watch runs this

CleanShot 2023-10-04 at 11 25 11@2x

I think I saw a comment referencing that this needed to be fixed on the indexer side

_Originally posted by @hassnian in https://github.com/kodadot/nft-gallery/issues/7436#issuecomment-1746213766_

### PR DESCRIPTION
**Pull request by hassnian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

use nft resource's  animation url if animation url is not present for the first resource  

test : https://deploy-preview-7517--nuxt-kodadot.netlify.app/ksm/gallery/14968743-3629a3ff458d113e25-MUSIC-MOOD-00000068

- [x] Closes #7499

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; 

CleanShot 2023-10-05 at 16 27 32@2x

### <samp>🤖 Generated by Copilot at ca87612</samp>

Enhanced the gallery item component to display animations for NFTs. Used the `useGalleryItem` hook to get the animation URL from the NFT metadata.

### <samp>🤖 Generated by Copilot at ca87612</samp>

> _Sing, O Muse, of the skillful coder who improved the gallery_
> _Of NFTs, those wondrous works of art that shine like stars_
> _He used the `index` parameter, a clever tool, to find the first_
> _And from the `nftEntity.meta.animation_url` he drew the motion of the image_

### CODE REVIEW

**Comment by prury** [comment]
nice find @hassnian , does it load there for you?

**Comment by hassnian** [comment]
yep , icons are fixed here  #7436


https://github.com/kodadot/nft-gallery/assets/44554284/0bd51e71-0928-4e48-a88f-97c5cf4ae551

**Review by preschian — APPROVED** [review]

**Review by Jarsen136 — APPROVED** [review]

**Comment by prury** [comment]
> yep , icons are fixed here #7436
> CleanShot.2023-10-06.at.09.53.55.mp4

hmm, on chrome it loads and plays the song
but on firefox (loading icon never disappears): 
image

ok, let's see if 7436 fixes it

**Review by prury — APPROVED** [review]

**Comment by vikiival** [comment]
Is the build failing?

Screenshot 2023-10-09 at 12 51 11

**Comment by yangwao** [comment]
builds

image

**Comment by yangwao** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 3.82 USD/DOT ~ 5.236 $DOT
🧗 [13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh](https://polkadot.subscan.io/account/13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)
🔗 [0x57ea967f480f3bc71592cf31e85977d66149f3c4f5304f8866649262f06408d3](https://polkadot.subscan.io/extrinsic/0x57ea967f480f3bc71592cf31e85977d66149f3c4f5304f8866649262f06408d3)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
