### PR TITLE
fix: hover transition effect on cards

### LINKED ISSUE #4536: UI proposal: hover transition effect on cards
### Feature request
I think it would be interesting to add some animation while hovering Neo Cards.

### Possible solution
- add `transition: 0.3s;` on `collection-card` & `nft-card`

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4536
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

Kapture 2022-12-22 at 21 01 03

Kapture 2022-12-22 at 21 02 32

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
✅ code lgtm

Not sure if we should keep the scale transform, wdyt @exezbcz

**Comment by roiLeo** [comment]
In #4536 I wanted transition for box-shadow but your solution is fine too

**Comment by exezbcz** [comment]
hmmm, i dont think this is great. I dont think we should add this. 
Can we make the animation for the cards like the translate x -4 and y+4, so it like move up and the dropshadow is where the card was if that makes sense? 
- like gumroad has on their buttons
image
https://gumroad.com/discover
- they did not use it for cards tho, so curious how it looks. If its too disturbing than we should leave it how it is.

**Comment by Jarsen136** [comment]
> hmmm, i dont think this is great. I dont think we should add this. Can we make the animation for the cards like the translate x -4 and y+4, so it like move up and the dropshadow is where the card was if that makes sense?
> 
> * like gumroad has on their buttons
>   image
>   https://gumroad.com/discover
> * they did not use it for cards tho, so curious how it looks. If its too disturbing than we should leave it how it is.

I will make it into our card.

**Comment by roiLeo** [comment]
@Jarsen136 could you check on gumroad the smooth hover transition fading 


https://user-images.githubusercontent.com/9987732/209167204-0ecdea75-b7a5-4f0b-94a4-ec20da79df06.mov

**Comment by Jarsen136** [comment]
Kapture 2022-12-22 at 23 39 32

How about this effect?

**Comment by exezbcz** [comment]
> Kapture 2022-12-22 at 23 39 32 [ Kapture 2022-12-22 at 23 39 32 ](https://user-images.githubusercontent.com/31397967/209169776-29d34804-060b-4e8f-88da-c29f925218b8.gif) [ ](https://user-images.githubusercontent.com/31397967/209169776-29d34804-060b-4e8f-88da-c29f925218b8.gif)
> 
> How about this effect?

it looks a bit off, i think its the timing and animation easing.

**Comment by Jarsen136** [comment]
> 
> it looks a bit off, i think its the timing and animation easing.
> 
> edit: the dropshadow animation is maybe late?

Will check it.

**Comment by Jarsen136** [comment]
Kapture 2022-12-24 at 00 04 53


Kapture 2022-12-24 at 00 02 31

If I understand correctly, this effect is what you are waiting for 👀  @exezbcz

**Comment by exezbcz** [comment]
yup, thats it, question is whether its not that distracting, wdyt @Jarsen136 @roiLeo @yangwao 
if we decide to keep it, are we going to update the animation on landing page as well?

**Comment by yangwao** [comment]
🤔🤔🤔

for button 🔘 it make sense to feel it's moving towards user, for bigger card I would keep it like they have it on their blog? so shadow drop effect? but I'm biased that if I'm looking on some visual picture and it moves it would distract me.

other that also make sense to have aligned clickables should hover like this?

**Comment by yangwao** [comment]
I mean let's go with this what we have; it's doable.

Let's resolve conflicts @Jarsen136 and let it fly:)

**Comment by exezbcz** [comment]
> I mean let's go with this what we have; it's doable.
> 
> Let's resolve conflicts @Jarsen136 and let it fly:)
> 
>  [ 68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f3344417230547176376b6e73586a4839744e2f67697068792e676966 ](https://camo.githubusercontent.com/8771411ec163dd09df0d6145a1975658dae074d5ac611e539b51a5b5a2d2cc17/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f3344417230547176376b6e73586a4839744e2f67697068792e676966) [ ](https://camo.githubusercontent.com/8771411ec163dd09df0d6145a1975658dae074d5ac611e539b51a5b5a2d2cc17/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f3344417230547176376b6e73586a4839744e2f67697068792e676966)

hmm, not sure if we should use this version, the hover effect would be different on landing page and on explore...

**Comment by yangwao** [comment]
Oh, I think this effect would be a much better transition on drop shadow rather than moving the whole card?

https://user-images.githubusercontent.com/9987732/209167204-0ecdea75-b7a5-4f0b-94a4-ec20da79df06.mov

**Comment by Jarsen136** [comment]
> Oh, I think this effect would be a much better transition on drop shadow rather than moving the whole card?
> 
> 
> 
> https://user-images.githubusercontent.com/9987732/209167204-0ecdea75-b7a5-4f0b-94a4-ec20da79df06.mov
> 
> 
> 
> 
> 
> 
> 
> 

Oki, I will make it later

**Comment by Jarsen136** [comment]
✅  new card shadow animation is coming.

Kapture 2023-01-03 at 13 43 43

Kapture 2023-01-03 at 13 45 31

**Comment by roiLeo** [comment]
> ✅ new card shadow animation is coming.

will we have the same on carousel & landing cards?

**Comment by Jarsen136** [comment]
> 
> will we have the same on carousel & landing cards?

✅  Done. Now we have the same animation for all kinds of cards on landing page (on both dark and light mode).

Kapture 2023-01-03 at 21 14 33

**Comment by yangwao** [comment]
waiting for @exezbcz for visual validation

**Pull request merged**
