### PR TITLE
Feat: Total Supply for AssetHubs #8346

### LINKED ISSUE #8346: Total Supply for AssetHubs
### Is your feature request related to a problem?

Currently when an artist creates his collection he enters some maximum supply limit but what if he forgets the max supply and try to create more nfts in the collection he will get a error which will be confusing and time consuming
and also buyers who will buy their nft would like know more about the collection details like maximum numbers of nfts so we need a Total Supply in collection details

### Describe the solution you would like

Adding maxSupply to the collection details

### Describe alternatives you have considered

nothing

### Screenshots

Screenshot 2023-12-01 at 11 46 27 PM
Screenshot 2023-12-01 at 11 46 00 PM

### Are there opened related issues?

not yet

### PR DESCRIPTION
**Pull request by AshutoshSingh00001**
Thank you for your contribution to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz/).

👇 __ Let's make a quick check before the contribution.

## PR Type
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #8346
- [x] ## Did your issue had any of the "$" label on it?
- [x] My DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=158VTDxZJidzsMcAdh7h828domveRvpmk1SCxwLUEHhcgY4v&usdamount=0&donation=true)

### CODE REVIEW

**Comment by AshutoshSingh72** [comment]
> please could you share a screenshot? plus we don't need to call api since you can retrieve the data from indexer

View #8346 for screenshot
Ok i'll try to fetch from indexer if it will be possible

**Comment by AshutoshSingh72** [comment]
> please could you share a screenshot? plus we don't need to call api since you can retrieve the data from indexer

I'll update you soon with indexer data fetch results

**Comment by AshutoshSingh00001** [comment]
> please could you share a screenshot? plus we don't need to call api since you can retrieve the data from indexer

I think it's a good idea to use indexer but it works the same and also by using api  we get the same values and a lot of time api is used in many different places view #8346 for screenshots

**Comment by AshutoshSingh00001** [comment]
Screenshot 2023-12-01 at 11 46 00 PM
Screenshot 2023-12-01 at 11 46 27 PM

it works fine and is it necessary to use indexer if I have an option to use api as I saw on kodadot contributors.md indexer is preferred but api can also be used I had to get the value then convert it into Json format then call a specific object so I used it

**Review by roiLeo — CHANGES_REQUESTED** [review]
please use indexer instead, it doesn't work on some collection (i.e. `/ahk/collection/u-65535`)

Screenshot 2023-12-02 at 20-41-44 Премия «Просветитель» 2022 года

**Comment by AshutoshSingh00001** [comment]
> please use indexer instead, it doesn't work on some collection (i.e. `/ahk/collection/u-65535`)
> 
> Screenshot 2023-12-02 at 20-41-44 Премия «Просветитель» 2022 года

I already knew about this is why I didn't used indexer it is just for nft pallet not for uniques pallet ``u-65535`` this is uniques collection

**Comment by AshutoshSingh00001** [comment]
> please use indexer instead, it doesn't work on some collection (i.e. `/ahk/collection/u-65535`)
> 
> Screenshot 2023-12-02 at 20-41-44 Премия «Просветитель» 2022 года

uniques is now depreciated https://wiki.polkadot.network/docs/learn-nft-pallets#uniques-pallet read this and we are moving to nft pallet

**Comment by roiLeo** [comment]
https://canary.kodadot.xyz/ahp/collection/30
vs
https://deploy-preview-8347--koda-canary.netlify.app/ahp/collection/30

your code throw error on empty collection

**Comment by AshutoshSingh00001** [comment]
> u-65535

this is why other stats are also not showing like items and owners

**Comment by AshutoshSingh00001** [comment]
> https://canary.kodadot.xyz/ahp/collection/30 vs https://deploy-preview-8347--koda-canary.netlify.app/ahp/collection/30
> 
> your code throw error on empty collection

@roiLeo  it is still not merged how is it possible to view it on canary is there some difference ?

**Comment by AshutoshSingh00001** [comment]
@roiLeo genuinely your review is too good you gave me a link of destroyed collection this is why I used api which actually helps us to catch bugs

**Review by roiLeo — COMMENTED** [review]
> @roiLeo changes are made can you review again

please see #8389

**Comment by roiLeo** [comment]
> sorry but this not fair I had took this issue first 🥲 so sad I'll no more contribute if this happens

I asked you to use indexer, still no changes just comments.

**Pull request closed without merging**
