### PR TITLE
#2731 Change payout address to reward me in transfer and change condi…

### LINKED ISSUE #2731: Change payout address to reward me in transfer
In transfer dialkog, kodadot.xyz/transfer/

- We rename "Copy Payout Address" to "Copy Reward Me link", 
- Show Copy Reward Me link without need adding amount

the payout might get lost in translation and to ease the process we should be showing it despite the need to enter an amount to make it easier for first-time devs.

Once this is done, #2717 can be updated accordingly

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/2717#issuecomment-1085761331_

### PR DESCRIPTION
**Pull request by prachi00**
…tion

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #2731

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screenshot 2022-04-01 at 4 41 08 PM

### CODE REVIEW

**Review by vikiival — CHANGES_REQUESTED** [review]
🌐 translations pls 🥺

**Comment by prachi00** [comment]
> 🌐 translations pls 🥺

done

**Review by vikiival — APPROVED** [review]
oki

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 184.07 USD/KSM ~ 0.272 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x0a79ced36012303f84bcd3819ab718510dd0289b3d50557c62492d55d17c3972](https://kusama.subscan.io/extrinsic/0x0a79ced36012303f84bcd3819ab718510dd0289b3d50557c62492d55d17c3972)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
