### PR TITLE
#1529 Fix: collections social card display image

### PR DESCRIPTION
**Pull request by atharva3010**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇  _ Do a quick check before the merge. 

### PR type
- [x] Bugfix
- [ ] Feature
- [x] Refactoring

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything works
- [ ] I found edge cases

### What's new?
- [x] PR closes #<issue_number>
- [ ] <brief_description_of_what_I've_added>

### Had issue bounty label?
- [ ] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=<My_Kusama_Address>)

### Community participation
- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [ ] My fix has changed **something** on UI, a screenshot for others, is best to understand changes.

### CODE REVIEW

**Comment by yangwao** [comment]
hey, please fill up PR template so we know more context and don't forget add you KSM address! :)

**Comment by yangwao** [comment]
here is deploy preview url https://deploy-preview-1671--koda-nuxt.netlify.app/

**Comment by yangwao** [comment]
for some bad ass reason netlify did not post it :D

**Comment by yangwao** [comment]
using https://cards-dev.twitter.com/validator

image

**Comment by atharva3010** [comment]
@yangwao can you approve the deploy again? It's pending, thanks.

**Comment by yangwao** [comment]
yeah I see, you must be special! haven't approving for one pr more than once, now three times lol


image

**Comment by atharva3010** [comment]
@yangwao sadly this fix cannot be tested locally, as it's something that breaks only on deploy :(

**Comment by yangwao** [comment]
yeah no worries, we have some spare build  minutes! :D

**Comment by yangwao** [comment]
done in https://github.com/kodadot/nft-gallery/pull/1676

**Pull request closed without merging**
