### PR TITLE
fix: update balance after chain switched

### LINKED ISSUE #3395: Balance on account not loading properly
~Trying to burn NFT, my balance shows me zero on both Transfer / item detail, didn't catch that in screenshot, after refresh there's a balance, but still won't let me burn because apparently, balance 0.~

When the balance reappears after refresh, I can burn/buy/perform transaction now thanks to:
- #3396 

The issue with balance initially loading with 0 is still here on deploy from #3396 or on beta.

image

Only thing I can get from console is this
image

### LINKED ISSUE #3587: Incorrect balance number after switching current chain
tested on https://deploy-preview-3500--koda-nuxt.netlify.app/transfer

I could see an incorrect balance after I switch current chain from BSX to RMRK
image

After I reload the page, it works well as usual.
image

_Originally posted by @Jarsen136 in https://github.com/kodadot/nft-gallery/issues/3500#issuecomment-1196511306_

### PR DESCRIPTION
**Pull request by KngZhi**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3587, closes #3395
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer?target=DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by KngZhi** [comment]
It seems the root cause hasn't been found yet.

**Review by JustLuuuu — APPROVED** [review]
wfm

**Comment by prachi00** [comment]
> wfm

its not working so removing the label

**Comment by prachi00** [comment]
@KngZhi are we still working on this one or should we close this?

**Comment by KngZhi** [comment]
still working on it. Trying to find out a better way.

**Pull request closed without merging**
