### PR TITLE
cleaned readme added activity

### LINKED ISSUE #2899: Probably move activity batches from Readme.md to Activity.md
@skylla54 suggested that we should lightweight stuff from our Readme into dedicated Activity.md to make it more streamable and readable for others

@skylla54 will propose some PR to make something

### PR DESCRIPTION
**Pull request by thea-exe**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x ] Refactoring

### What's new?

- [ x] PR closes #2899 >
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=FLct4GSJ7X8wf3C1hXesWNKEKikYXDUfHfvvfSzTCBkZmc6)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by thea-exe** [comment]
NOTE: I took off the little boxes that were provided by Discord and GitHub because they looked REALLY ugly.....

**Review by vikiival — CHANGES_REQUESTED** [review]
Nice contribution
I just miss the link to Activity.md from readme

and tbh I would keep the contribution avatars in the readme (may @yangwao can have an opinion)

**Comment by vikiival** [comment]
kk last thing is to provide your address :)

**Comment by thea-exe** [comment]
[Address](https://kodadot.xyz/transfer?target=FLct4GSJ7X8wf3C1hXesWNKEKikYXDUfHfvvfSzTCBkZmc6&usdamount=0&donation=true) :D

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
pay 50 usd

**Pull request merged**
