### PR TITLE
feat: Drop landing v2

### LINKED ISSUE #9329: Drop landing v2
image

# Design
- updated in drop page figma: https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=394-6126&mode=design&t=EZGixzENJor1FtBi-11
- simpler cards
- clear headings 
- divided into past drops 
- upcoming and live drops are together 
- add to calendar feature

# Top part 
- heading, clear that its every Thursday 
- there are three cards, on ultra wide it could be more - dynamic count of cards please

mobile layout for the heading: 
image

## Add to calendar 
once clicked, user is presented with easy modal
image
- let me know if you would like to add another calendar, IMO these two are enough for start

# Cards
- under main heading, there are cards - sorted similarly like on the landing page
- first is shows minting live, and then the soonest drop taking place - scheduled 

## past art drops 
- this is clear IMO (there wont be minting live status)

## Buttons
- button have hover effects like in the component page

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #9329

## Needs Design check

- @exezbcz please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2024-02-14 at 16 40 48@2x

### CODE REVIEW

**Comment by exezbcz** [comment]
i sense we would need dynamic grid for this aswell 

image
image
image

**Comment by hassnian** [comment]
> i sense we would need dynamic grid for this aswell
> 
> image image image
> other than that, everything works smoothly!

yeah , min width?

**Comment by hassnian** [comment]
@exezbcz min width added

**Comment by prury** [comment]
responsiveness looks great ✔️ 
dark/white mode good ✔️ 
hover effect nice ✔️ 
looks like design ✔️  
link redirection ✔️ 
create your own ✔️ 
calendar set the right time/date ✔️ 
calendar modal nice ✔️ 

will create issue to add iCal later

**Comment by exezbcz** [comment]
> will create issue to add iCal later

we had a chat about it with hassnian and it seems its bit harder to create one click add event

**Comment by prury** [comment]
> > will create issue to add iCal later
> 
> we had a chat about it with hassnian and it seems its bit harder to create one click add event

google calendar good enough then? ok for me

**Comment by yangwao** [comment]
Thanks!
pay 90 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $90 @ 7.6 USD/DOT ~ 11.842 $DOT
🧗 [16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD](https://polkadot.subscan.io/account/16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)
🔗 [0xf72350ac642540048b61f9a1734e82371e7a1057b703b3bb4cf25ebe00f69dad](https://polkadot.subscan.io/extrinsic/0xf72350ac642540048b61f9a1734e82371e7a1057b703b3bb4cf25ebe00f69dad)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
