### PR TITLE
fix: Replace IPFS GW

### LINKED ISSUE #7432: 🚑🚑 Replace IPFS GW
### What happened?

Replace kodadot image gw with filebase kodadot gw. 

'https://kodadot-ultra.myfilebase.com',

### Please reproduce in steps

-

### Expected Behavior

-

### What browsers are you seeing the problem on?

_No response_

### At which address did you encounter bug?

_No response_

### Are you logged in?

None

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

_No response_

### Screenshots

-

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/ksm/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix

  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #7432

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [ ] My fix has changed UI

  ## Copilot Summary
  
### <samp>🤖 Generated by Copilot at 2bc1b86</samp>

Updated the IPFS provider for NFT images and metadata to myfilebase.com in various files. This improves the performance and reliability of the IPFS service and ensures the tests match the actual open graph and Twitter card data.

  
### <samp>🤖 Generated by Copilot at 2bc1b86</samp>

> _We're sailing on the IPFS sea, with myfilebase as our guide_
> _We've left behind the old domains, they served us well and true_
> _But now we need a faster ship, to load the NFTs_
> _So heave away, me hearties, heave away on `SERVICES`_

### CODE REVIEW

**Comment by yangwao** [comment]
This is equally same UX as with 500 errors lol 

image

**Comment by vikiival** [comment]
> This is equally same UX as with 500 errors lol 
> 

@Jarsen136 can be filebase used only for metadata image for images?

**Comment by Jarsen136** [comment]
> > This is equally same UX as with 500 errors lol
> 
> @Jarsen136 can be filebase used only for metadata image for images?

For now, the filebase only used for images. Look like there are too many image requests during the details page loading. It causes slow loading.

image

**Comment by roiLeo** [comment]
infinite loop on my side 

- https://deploy-preview-7433--koda-canary.netlify.app/ahp/gallery/13-1003

Capture d’écran 2023-09-30 à 4 35 03 PM

**Comment by vikiival** [comment]
It replaced both metadata and images :)

**Comment by Jarsen136** [comment]
> > > This is equally same UX as with 500 errors lol
> > 
> > 
> > @Jarsen136 can be filebase used only for metadata image for images?
> 
> For now, the filebase only used for images. Look like there are too many image requests during the details page loading. It causes slow loading.
> 
> image

I found the point is that filebase gw does not provide the ability to compress the size of the image like we have on `image.w.kodadot.xyz`. It loaded the original image, resulting in a slower speed. @vikiival

**Comment by Jarsen136** [comment]
> It replaced both metadata and images :)

On the prod env, we only use one ipfs gw `image.w.kodadot.xyz`, no matter if it is metadata or images. Do you mean to split them into two ipfs requests from now on ?
For images:    `image.w.kodadot.xyz` 
For metadata:   `kodadot-ultra.myfilebase.com`
 I'm not sure if it would significantly improve the image loading speed mentioned in the previous comment.

The low speed of image loading is because we do not compress the image size on myfilebase gw. We should solve it first.

**Comment by vikiival** [comment]
> For images:  image.w.kodadot.xyz
> For metadata:  kodadot-ultra.myfilebase.com

The point is that app is currently DDOSing image gw on metadata, if you the request fails, nothing is loaded :)

**Comment by Jarsen136** [comment]
> > For images:  image.w.kodadot.xyz
> > For metadata:  kodadot-ultra.myfilebase.com
> 
> The point is that app is currently DDOSing image gw on metadata, if you the request fails, nothing is loaded :)

I see. Thanks for expanding the reason. I have updated the implementation. Let me know if I still miss something. @vikiival

**Comment by preschian** [comment]
> > Does this make sense with [kodadot/workers#162](https://github.com/kodadot/workers/pull/162) and [kodadot/workers#163](https://github.com/kodadot/workers/pull/163) fix?
> 
> If the issue of 500 errors has been solved, we could close this PR and keep the original gw

what if we put a fallback gateway in `ENV`? so, just in case we face 500 again, we can switch to a fallback gateway temporary

**Comment by vikiival** [comment]
> what if we put a fallback gateway in `ENV`? so, just in case we face 500 again, we can switch to a fallback gateway temporary

it fetches from two+ sources 
https://github.com/kodadot/packages/tree/main/minipfs

**Pull request closed without merging**
