### PR TITLE
🔧 wip: nuxt3

### PR DESCRIPTION
**Pull request by roiLeo**
- ref #2690 

@kodadot/code-review-guild I'm stuck on some build errors if anyone want to try out feel free to checkout this branch

- Goal is to display simple hello world on Landing

Screenshot 2023-08-23 at 15-59-18 🔧 wip nuxt3 by roiLeo · Pull Request #6917 · kodadot_nft-gallery
jerry

### CODE REVIEW

**Comment by yangwao** [comment]
Hey, is insider trading allowed, what do you think 
https://app.zeitgeist.pm/markets/238

**Comment by yangwao** [comment]
maybe @stephenjason89 😄

**Comment by roiLeo** [comment]
Screenshot 2023-08-24 at 16-37-19 https __deploy-preview-6917--koda-canary netlify app

Now it builds 🎊 

excited-happy

**Comment by stephenjason89** [comment]
Good job @roiLeo, It's 12midnight here. If you need help just let me know. My tg handle is SOW89

**Comment by vikiival** [comment]
🔥🔥🔥🔥🔥🔥🔥🔥

**Comment by yangwao** [comment]
> Now it builds 🎊

yours fast charged drive has arrived

image

**Comment by stephenjason89** [comment]
@roiLeo, seems like i18n is working now. I made a PR to your repo. Thanks

**Comment by yangwao** [comment]
Nuxt3.7 out 😍
- https://twitter.com/danielcroe/status/1695231761351930182

**Comment by yangwao** [comment]
@roiLeo your PR has been visited by @danielroe. Now you are a success. 

image

**Comment by preschian** [comment]
> @roiLeo your PR has been visited by @danielroe. Now you are a success.

wooogh 🤩

**Comment by stephenjason89** [comment]
> Nuxt3.7 out 😍
> 
> * https://twitter.com/danielcroe/status/1695231761351930182

https://github.com/roiLeo/nft-gallery/pull/26 ❤️

**Comment by stephenjason89** [comment]
> Nuxt3.7 out 😍
> 
> * https://twitter.com/danielcroe/status/1695231761351930182

Here's the PR for it @roiLeo, https://github.com/roiLeo/nft-gallery/pull/26 ❤️

**Comment by stephenjason89** [comment]
@roiLeo we need oruga modal

import { NeoModalExtendProgrammatic } from '@kodadot1/brick' returns undefined

further checking 
NeoModalExtend/plugin.js

errors on @oruga-ui imports even if it is already installed and in the node_modules folder.

**Comment by vikiival** [comment]
> import { NeoModalExtendProgrammatic } from '@kodadot1/brick' returns undefined

Cc @preschian

**Comment by preschian** [comment]
> > import { NeoModalExtendProgrammatic } from '@kodadot1/brick' returns undefined
> 
> Cc @preschian

@stephenjason89 For modal and notification need to fork oruga implementation. For oruga-next you can see it here https://github.com/oruga-ui/oruga/blob/4915c4dbcb1a6c2cd39bc7660d41916b330bc0cd/packages/oruga-next/src/components/modal/index.ts#L15

> @roiLeo we need oruga modal

anyway, if you want to test the the plugin, `plugins/filters.ts` should be easier to start

**Comment by roiLeo** [comment]
> For modal and notification need to fork oruga implementation. 

ref #5568 #6277 #6714

**Comment by yangwao** [comment]
What's the strategy for merging this? 

You want to do page by page or do some nuxt layout?

**Comment by roiLeo** [comment]
> What's the strategy for merging this?

Wait for some issue to be resolved, I can handle conflicts & push from others (fork my repo)

- #6911 : devs can handle package migration, one by one (some of them have been made) link #5314
- #6277 : major need

> You want to do page by page or do some nuxt layout?

- fix all gql calls (some of theme have been fixed) page by page & components by components


From https://github.com/kodadot/nft-gallery/issues/2690#issuecomment-1525341446

I've done:
- [x] upgrade to nuxt3, remove nuxt-bridge & edge
- [x] upgrade [i18](https://v8.i18n.nuxtjs.org/getting-started/setup) 
- [x] upgrade [@nuxtjs/apollo](https://apollo.nuxtjs.org/getting-started/quick-start)
- [x] update layouts & page with vue3 composition (`<NuxtLayout><NuxtPage /></NuxtLayout>`)
- [x] rename `/static` folder to `/public`

We need to fix some packages config now.

@stephenjason89 have you made some progress on I18n plugin?

**Comment by preschian** [comment]
@roiLeo, it seems like we can use a proxy to gradually release it to the user page by page. Maybe we can start with `/blog` by implementing `@nuxt/content`? It would be great if we could support SSR also for `/blog`. So, we can drop prerender.io for `/blog`

> fix all gql calls (some of theme have been fixed) page by page & components by components

I think this is the major one

> https://github.com/kodadot/nft-gallery/issues/6277 : major need

this one can't be solved with just a fork?

**Comment by preschian** [comment]
@roiLeo, but if you prefer not to use a proxy, we can stick with this way

> rename /static folder to /public

Are there any changes that need to merge in `main` to reduce the diff? I guess that renaming `/static` to `/public` can be made in the `main` branch

**Comment by roiLeo** [comment]
> @roiLeo, it seems like we can use a proxy to gradually release it to the user page by page. Maybe we can start with `/blog` by implementing `@nuxt/content`? It would be great if we could support SSR also for `/blog`. So, we can drop prerender.io for `/blog`

nuxt/content doesn't work on `ssr: false`, SSR support will be a major update, I don't think it's a good idea to realease first version of nuxt3 with it.

> > #6277 : major need
> 
> this one can't be solved with just a fork?

wdym? I want to use it like it's on Doc (`const { oruga } = useProgrammatic()`) I think we can extend it (`const { neo } = useProgrammatic()`)

> @roiLeo, but if you prefer not to use a proxy, we can stick with this way

I'd rather not

> > rename /static folder to /public
> 
> Are there any changes that need to merge in `main` to reduce the diff? I guess that renaming `/static` to `/public` can be made in the `main` branch

Idk if `public` folder is working with nuxt-bridge

**Comment by preschian** [comment]
> wdym? I want to use it like it's on Doc (`const { oruga } = useProgrammatic()`) I think we can extend it (`const { neo } = useProgrammatic()`)

You need to fork this script first https://github.com/oruga-ui/oruga/blob/4915c4dbcb1a6c2cd39bc7660d41916b330bc0cd/packages/oruga-next/src/components/modal/index.ts#L8

and then can create or inject the composables through a plugin. this is how they install it to the plugin:
- https://github.com/oruga-ui/oruga/blob/4915c4dbcb1a6c2cd39bc7660d41916b330bc0cd/packages/oruga-next/src/utils/useProgrammatic.ts#L9
- https://github.com/oruga-ui/oruga/blob/4915c4dbcb1a6c2cd39bc7660d41916b330bc0cd/packages/oruga-next/src/utils/plugins.ts#L14
- we need this one in our app: https://github.com/oruga-ui/oruga/blob/4915c4dbcb1a6c2cd39bc7660d41916b330bc0cd/packages/oruga-next/src/components/modal/index.ts#L59

I can help with this one once I'm done with a simple mint

**Comment by yangwao** [comment]
> Wait for some issue to be resolved

So I can create a new chief issue for migration and replace this one? 
- https://github.com/kodadot/nft-gallery/issues/2690#issuecomment-1525341446

To not break our current flow and keep a flawless release cycle, I would propose making `alpha` branch with a deployment. 

Later we can still back merge new things and once it is even 1:1 `alpha` with `main` we can update.

lmk and I can proceed.

Hanging out in one PR for this major upgrade is not so good I think.

**Comment by roiLeo** [comment]
> I can help with this one once I'm done with a simple mint

Yes please! could you push your code to my repo?

**Comment by roiLeo** [comment]
> So I can create a new chief issue for migration and replace this one?

- finish #4750 first

> To not break our current flow and keep a flawless release cycle, I would propose making `alpha` branch with a deployment.

IMO, it's better that someone (Kodadev insider) handle the migration, it would be less exhausting than having to go through multiple reviews and better to resolve conflicts.

> Later we can still back merge new things and once it is even 1:1 `alpha` with `main` we can update.

Yes! Once we fix oruga (programmatic) & apollo config, we could be able to release an alpha branch.

> Hanging out in one PR for this major upgrade is not so good I think.

why that?

**Comment by daiagi** [comment]
@roiLeo 
I'm lost in the discussion
is there anything concrete I can help you with right now?

**Comment by roiLeo** [comment]
> @roiLeo I'm lost in the discussion is there anything concrete I can help you with right now?

Would you like to check/fix a component, a page or a plugin? Just let me know wich part you want to work on.
For now preschian want to work on programmatic modal (oruga modal) & stephen is on i18n config.

**Comment by roiLeo** [comment]
> component/page please

Try first with something easy/doable like spotlight, series-insight, assets page then push on my repo and I'll merge it as quickly as I can (if it's working)

**Comment by yangwao** [comment]
> IMO, it's better that someone (Kodadev insider) handle the migration, it would be less exhausting than having to go through multiple reviews and better to resolve conflicts.

I've made `nuxt` branch, deployment is working on https://nuxt.kodadot.xyz 
- @roiLeo please merge it there what you have and we can split load. Thank you for understanding.


> why that?

This 

image

and because the process is not around the KodaDot branch in this repository and we can split load among others, not make you block migration by single dev on resolving conflicts. Hopefully, you understand.

Rather encourage split tasks in 
- #7034

For others likewise, making it against `nuxt` branch.

**Comment by roiLeo** [comment]
- continue in #7039

**Pull request closed without merging**
