### PR TITLE
fix/chain-token

### LINKED ISSUE #3896: Changing BSX to KSM on /snek
There are still some leftovers from roccoco implementation which need to be adjusted, I may have forgotten something:

collections on-hover:
image
collections history tab:
image
gallery item history tab:
image
profile stats:
image
profile history + sales, offers made, etc. -> check all tabs
image
navbar profile dropdown -> here we could show both in some sensical way:
image

### PR DESCRIPTION
**Pull request by KngZhi**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3896
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer?target=DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by prachi00 — APPROVED** [review]

**Comment by petersopko** [comment]
@KngZhi great, your fix seems to have fixed almost all of it, one thing is still left tho:
image

Since /snek is multi-token(multi-currency), can we temporarily show both in the format of those? Word `Balance` can be centered in the middle (vertically) with upper balance shown in BSX and lower in KSM.

We need to eventually decide how will we handle chains with 2+ currencies/tokens, but as of now, this seems like a quick fix which will do it's job

**Comment by KngZhi** [comment]
image

**Comment by KngZhi** [comment]
Hi, @petersopko I don't have any KSM and BSX, may I bother you to test for that? And is this the UI you expected?

**Review by roiLeo — COMMENTED** [review]
Something might be wrong for me as it don't show the right amount
Capture d’écran 2022-09-05 à 8 41 45 AM

> Word `Balance` can be centered in the middle (vertically) with upper balance shown in BSX and lower in KSM.

can we have align "Balance" align left with grey text color and in smaller size?
`has-text-left has-text-grey is-size-7`

image

**Comment by petersopko** [comment]
> can we have align "Balance" align left with grey text color and in smaller size? `has-text-left has-text-grey is-size-7`

sure, I'm all ears, @KngZhi let's do what @roiLeo proposed + check what kind of amount it shows (you can check yours at /assets)

**Comment by roiLeo** [comment]
> (you can check yours at /assets)

Thanks for the tip!

Capture d’écran 2022-09-05 à 9 05 33 AM

**Comment by KngZhi** [comment]
> > can we have align "Balance" align left with grey text color and in smaller size? `has-text-left has-text-grey is-size-7`
> 
> sure, I'm all ears, @KngZhi let's do what @roiLeo proposed + check what kind of amount it shows (you can check yours at /assets)

Is there any way (e.g., faucet) I can get some test tokens in snek?

**Comment by petersopko** [comment]
> Is there any way (e.g., faucet) I can get some test tokens in snek?

There's a bot (faucet) on our [discord channel](https://discord.com/channels/840514076538830888/881839877140930630)

**Comment by JustLuuuu** [comment]
> 

yes same issue
image
Im supposed to have that amount in BSX not in KSM

**Comment by KngZhi** [comment]
image

**Review by petersopko — APPROVED** [review]
wfm

**Comment by petersopko** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 49.51 USD/KSM ~ 1.01 $KSM
🧗 [DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc](https://kusama.subscan.io/account/DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc)
🔗 [0x2b398c4dd734a4e411f13de088e5e320e60985714bcde864c6b70b965ce9ecbf](https://kusama.subscan.io/extrinsic/0x2b398c4dd734a4e411f13de088e5e320e60985714bcde864c6b70b965ce9ecbf)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
