### PR TITLE
Tailwind extension (for Ktheme)

### LINKED ISSUE #9032: refactor: text-shadow using tailwind
this but using tailwind
```
@include ktheme() {
  color: theme('text-color-inverse');
  text-shadow:
    1px 1px 0 theme('text-color'),
    1px -1px 0 theme('text-color'),
    -1px 1px 0 theme('text-color'),
    -1px -1px 0 theme('text-color'),
    1px 0px 0 theme('text-color'),
    0px 1px 0 theme('text-color'),
    -1px 0px 0 theme('text-color'),
    0px -1px 0 theme('text-color'),
    4px 4px theme('text-color');
}
```

### PR DESCRIPTION
**Pull request by Temidayo32**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #9032
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [ ] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>)

## Screenshot 📸

-

### CODE REVIEW

**Review by roiLeo — CHANGES_REQUESTED** [review]
I would rename class to something more meaningful maybe `k-text-shadow`

Please check out and replace in `assets/styles/components/_search`& `pages/blog/index` the initial implementation

**Comment by Temidayo32** [comment]
@roiLeo  Okay. Alright. thanks!

**Comment by prury** [comment]
@Temidayo32 please user PR template

https://github.com/kodadot/nft-gallery/blob/a5ed403857aa38018e7cc51cb4151078e6116862/.github/PULL_REQUEST_TEMPLATE/QUICK_AND_QA_PULL_REQUEST_TEMPLATE.md#L4

**Comment by Temidayo32** [comment]
Okay, I will make the change

**Comment by Temidayo32** [comment]
> Please check out and replace in `assets/styles/components/_search`& `pages/blog/index` initial implementation

For some reasons, making the change for this two file is giving an unexpected result. Here is what the two pages look like when I make the change.
image

This is using the `search.scss`

**Comment by Temidayo32** [comment]
> Please check out and replace in `assets/styles/components/_search`& `pages/blog/index` initial implementation

For some reasons, making the change for this two file is giving an unexpected result. Here is what the two pages look like when I make the change.
image

This is using the `search.scss`
image

**Pull request closed without merging**
