### PR TITLE
chore: fix pwa icons not empty

### LINKED ISSUE #4747: Directory not empty `.nuxt\pwa\icons`
after bumping nuxt-bridge to the latest version, our CI sometimes throw an error like this. currently, need to retry the github actions if you guys find this error
image

### LINKED ISSUE #5035: Build App Failed directory not empty .nuxt/pwa/icons
Screenshot 2023-02-17 at 15 32 58

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4747
- [x] Closes #5035

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by roiLeo** [comment]
I know that `static` folder is changed by `public` in nuxt3 maybe it's related?

**Comment by daiagi** [comment]
Will it solve the issue in dev too? Or is it just me that have that?

**Comment by daiagi** [comment]
Will it solve the issue in dev too? Or is it just me that have that?

**Review by daiagi — APPROVED** [review]

**Comment by yangwao** [comment]
pay 20 usd
it builds! :)

**Pull request merged**
