### PR TITLE
fix: New Profile creation/editing better field validation/error handling

### LINKED ISSUE #10164: New Profile creation/editing better field validation/error handling
When creating a new profile/editing using the new profile design, user have to type the full address with `https://` in order for it to work

### Web Link
- When field has lost focus, add `https://` to the url if it isn't already present
 image

<hr/>

- Prevent the full address from being shown on

### Farcaster

if i type `/koda` on the farcaster field, it will redirect me to https://warpcast.com//koda instead of https://warpcast.com/koda, so we may have to add the `/` there as well for the user. 

-  Make sure the correct handle is sent to worker,  whether or not the user has chosen to start with `/`

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #10164

goes after #10140

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

Kapture 2024-04-30 at 13 02 46
image

### CODE REVIEW

**Comment by daiagi** [comment]
@Jarsen136

Ive changed base branch

This allows to focus on your changes more clearly

Base branch will automatically change to main after the other pr is merged and it's branch deleted

**Comment by Jarsen136** [comment]
> 
> Base branch will automatically change to main after the other pr is merged and it's branch deleted

Thanks, that's good.

**Comment by prury** [comment]
thank you very much @Jarsen136

**Review by daiagi — APPROVED** [review]

**Comment by daiagi** [comment]
@prury  why close?

**Comment by prury** [comment]
> @prury why close?

it was automatic, i did not clicked on close

**Comment by daiagi** [comment]
openinig

**Comment by prury** [comment]
> openinig

i think jarsen has to change branch to main and reopen

**Comment by daiagi** [comment]
>i think jarsen has to change branch to main and reopen

indeed

i can't seem to change the base branch

**Comment by daiagi** [comment]
open

**Comment by daiagi** [comment]
@Jarsen136 

I've resolved merge conflicts for you
https://github.com/kodadot/nft-gallery/pull/10169/commits/434b418ecfe9eede4bd6fb29c72ea070d1eb1a21


hope you don't mind

**Comment by daiagi** [comment]
@Jarsen136 somehow it did work for me very well recently

I'm guessing it's because I was branching a pr off of my own branches

**Review by preschian — APPROVED** [review]

**Pull request merged**
