### PR TITLE
feat: better markdown support

### LINKED ISSUE #5361: Autolink in item description
Can we do autolinking from text in description of items like for example Github does or Telegram?

https://t.me/BLAGO_108
https://lum-a.com
https://discord.gg/XRGWVRhudj
https://twitter.com/FLAT_E_A_R_T_H
https://bastyon.com/gregory_the_lum_a
https://t.me/TheIllums
https://www.youtube.com/channel/UCDJ6CySN0ZkdufCqVEBViQw

image

https://beta.kodadot.xyz/rmrk2/gallery/13898634-b46a62619cb12c7a15-LUM-A-G-0443_514_MB_GREGORY_THE_ILLUMINATOR-00000443

Ref
---
- #5218

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [x] Refactoring

## Context

- [x] Closes #5361 support auto link in markdown content
- [x] unify `useRedirectModal`
- [x] Markdown common component

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
@Jarsen136 please resolve conflicts 🥺

**Comment by Jarsen136** [comment]
> @Jarsen136 please resolve conflicts 🥺

✅ DONE

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
pay 25 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $25 @ 33.14 USD/KSM ~ 0.754 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xb67216b97f9efa093910c3518f36004290585e5a0e1716c74d29281028a31c21](https://kusama.subscan.io/extrinsic/0xb67216b97f9efa093910c3518f36004290585e5a0e1716c74d29281028a31c21)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
