### PR TITLE
move fallbackMetaByNftEvent function and pin nuxt-edge version

### LINKED ISSUE #2830: Dist is not being commited to filesystem but generated
Seems even after revert, GH does build but the test fails?

- #2826 
- https://github.com/kodadot/nft-gallery/issues/2826#issuecomment-1096606454
- #2828 

image

Seems everything is building here at [`3049c4d` (#2805)](https://github.com/kodadot/nft-gallery/pull/2805/commits/3049c4d1a9be1407cc61130f8f314c3263ce8971) 

 https://github.com/kodadot/nft-gallery/pull/2805

image

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2830

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged the recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by preschian** [comment]
@yangwao @vikiival @kkukelka do we need enable netlify in renovate bot?

**Comment by yangwao** [comment]
> we need to enable netlify in renovate bot?

no, it would eat our precious build minutes :)
also would be nice to merge that renovate bumps in one PR minor+patch, why it's splitted now?

**Review by roiLeo — APPROVED** [review]
code lgtm, build & test passed

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 155.18 USD/KSM ~ 0.644 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0x6d144110fada6b90e2119f0d432fe58e4caa8edd6cb58092215fbf4ba9bbd47a](https://kusama.subscan.io/extrinsic/0x6d144110fada6b90e2119f0d432fe58e4caa8edd6cb58092215fbf4ba9bbd47a)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
