### PR TITLE
feat: update code-checker parts

### LINKED ISSUE #10705: Remove/Reword code-checker parts
related: https://github.com/kodadot/ops-internal/issues/1774

Some checkers are probably unrelated since we changed how the capture service works.
- "Not Using WebGL" (now we can capture it, so it is safe to remove. Or is there any concern related to WebGL?)
- "Art Is Consistent" & "Automatic Sizing - Responsiveness" (need manual review for these? Maybe use gray question mark icon instead?)
- "Variation loading time < 3 seconds" (should we adjust this? since we already have an art that > 3s. less than **30s** should be fine, I think)

wdyt? @ThomasssArt @JustLuuuu 
cc @kodadot/internal-dev

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [x] Feature

## Needs Design check

- @exezbcz please review

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #10705

- remove WEBGL check
- rename `Variation loading time < {0} seconds` to `Variation loading time`
- optional check: "Automatic Sizing - Responsiveness" "Variation loading time"   If failed with these two items, it only show grey question mark instead of failure cross mark.
- fix wrong description for `Variation loading time` -> `[components/codeChecker/issueHint/VariationLoadingTime.vue]`

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by JustLuuuu** [comment]
Can someone ping me once this is merged? So I can adjust hello page.

**Comment by JustLuuuu** [comment]
Random question: why is it showing art not consistent on this drop (hal09999) even if the code IS producing the same hashes/images?
Screenshot 2024-08-05 at 17 17 04

Link to code here: https://github.com/kodadot/ops-internal/issues/1799#issuecomment-2269195721

**Comment by vikiival** [comment]
It has probably incorrect implementation of messages

**Review by ThomasssArt — APPROVED** [review]
From visual point of view it looks good!

**Comment by vikiival** [comment]
Missing reviews @kodadot/code-review-guild

**Review by preschian — APPROVED** [review]

**Review by hassnian — APPROVED** [review]

**Pull request merged**
