### PR TITLE
🔧 GalleryItem redesign MessageNotify

### LINKED ISSUE #4602: Adjust congrats message
Huh, I see two messages. 
One is toast which should be removed.
 
- [ ] remove grey toast from there 
- [ ] missing `MessageNotify` on redesign page
- [ ] " You Have New NFT(s) " text => "You have successfully purchased this/a new NFT"
- [ ] put congrats message in the middle, look for responsive version

Test with `?message=congrats` 

image

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/4576#issuecomment-1371089052_

### PR DESCRIPTION
**Pull request by roiLeo**
`?redesign=true&message=congrats`

## PR Type

- [x] Bugfix
- [x] Refactoring

## Context

- [x] Closes #4602 

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=HguGafrfk8nRP9a4tgJf7hLvSSFie8GtkDjyWFHQ2kDUAMc)

## Screenshot 📸

Screenshot 2023-01-10 at 09-16-13 KodaDot - Kusama NFT Market Explorer

### CODE REVIEW

**Comment by exezbcz** [comment]
I believe it was supposed to be on top, correct? It's a popup with no close button, and I'm against putting it in the middle of the screen.
Wdyt? @roiLeo

**Comment by roiLeo** [comment]
> I believe it was supposed to be on top, correct? It's a popup with no close button, and I'm against putting it in the middle of the screen.

- right
Screenshot 2023-01-11 at 10-55-06 KodaDot - Kusama NFT Market Explorer

- left
Screenshot 2023-01-11 at 10-56-25 KodaDot - Kusama NFT Market Explorer


> Additionally, I would delete the confetti icon from the heading.

Aight!

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
Nice refactor

**Comment by vikiival** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 26.64 USD/KSM ~ 1.877 $KSM
🧗 [HguGafrfk8nRP9a4tgJf7hLvSSFie8GtkDjyWFHQ2kDUAMc](https://kusama.subscan.io/account/HguGafrfk8nRP9a4tgJf7hLvSSFie8GtkDjyWFHQ2kDUAMc)
🔗 [0x91f93e09ca494c08560cad46f416ecd29d0a5b18796882007d5551e7374049f5](https://kusama.subscan.io/extrinsic/0x91f93e09ca494c08560cad46f416ecd29d0a5b18796882007d5551e7374049f5)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by exezbcz** [comment]
> hey @exezbcz, lmk which message possition you prefer (left/center/right) and I'll change it

hi! I think right seems ok.

**Pull request merged**
