### PR TITLE
Added gasless drop modal feature to require funds on account

### LINKED ISSUE #8411: Required funds for gasless drop
Let's experiment here
- after discussion with the team we decided to try one drop where funds for listing are required 

thus one more modal here

## Design

image

- updated in handoff confirmation modal site
- https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=1458-19091&mode=design&t=WG1ovEJnOa34mcHH-11

## How it works? 
- this modal will be displayed in our fund requirement drop everytime user does not have enough funds on the wallet
- modal will be before the email signup 
- modal does not show when the user has enough funds 
- when user clicks mint nft now it checks the funds, not sure how long this can take, we can use loading modal
image

changes in the drop page itself
image

can we make it till Thursday? 👀

### PR DESCRIPTION
**Pull request by shashkovdanil**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Closes #8411 
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [x] I've tested it at </ksm/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer?target=16SpvdDgKNiQ3c53DxX7refnQcKUD3uRNim3Z1HBJLNGrtSP&usdamount=0)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
**DEMO video, it's with sound**

https://github.com/kodadot/nft-gallery/assets/19692986/7b186cd3-ae89-47b6-a147-07633e1be3d6

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at f0e843d</samp>

This pull request adds a feature to the collection drop component that checks and updates the user's balance and shows a modal dialog to add funds if needed. It also adds and fixes some translations for the minting and drop UI.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at f0e843d</samp>

> _Sing, O Muse, of the skillful code that the heroes wrought_
> _To enhance the minting of the generative art divine_
> _With `AddFundsModal.vue`, a component of cunning thought_
> _That guides the users to the gasless drop with grace and shine_

### CODE REVIEW

**Comment by exezbcz** [comment]
Hey guys @kodadot/internal, can you please continuously check this one as it needs to be ready for tomorrow


Thanks!

**Review by vikiival — CHANGES_REQUESTED** [review]
Minumum amount is in `props.drop.meta`

**Comment by vikiival** [comment]
> Fixed

Maybe push?

Screenshot 2023-12-06 at 13 55 49

**Comment by vikiival** [comment]
@shashkovdanil you are still missing

https://github.com/kodadot/nft-gallery/issues/8411#issuecomment-1840892440

**Comment by yangwao** [comment]
> Does not work

when you clicked claim nft which dialog showed up?

**Comment by yangwao** [comment]
@shashkovdanil some conflicts left after recent merging let's fix one more time

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $110 @ 6.02 USD/DOT ~ 18.272 $DOT
🧗 [16SpvdDgKNiQ3c53DxX7refnQcKUD3uRNim3Z1HBJLNGrtSP](https://polkadot.subscan.io/account/16SpvdDgKNiQ3c53DxX7refnQcKUD3uRNim3Z1HBJLNGrtSP)
🔗 [0x9b74f49baef8bfe4a9f91fc3cc72749dd3e92ba0e81cee7a822977967a25ba9e](https://polkadot.subscan.io/extrinsic/0x9b74f49baef8bfe4a9f91fc3cc72749dd3e92ba0e81cee7a822977967a25ba9e)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
