### PR TITLE
fix: Cards in gallery item

### LINKED ISSUE #8747: Cards in gallery item
image
- can we please make the network on the cards behave like on the cards from explorer? 

image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix

  ## Needs Design check

  - @exezbcz please review

  ## Context

  - [x] Closes #8747

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

image

  ## Copilot Summary
  copilot:summary

  copilot:poem

### CODE REVIEW

**Review by daiagi — APPROVED** [review]

**Comment by exezbcz** [comment]
ahp caps please, somehow we changed it on explore, lets follow that as well

**Comment by roiLeo** [comment]
> ahp caps please, somehow we changed it on explore, lets follow that as well

?

Maybe open new issue since we still show it capitalized in navbar

**Comment by daiagi** [comment]
@roiLeo 

one of these

image

**Comment by roiLeo** [comment]
> @roiLeo
> 
> one of these

haha thank you for this, should be good now

**Review by roiLeo — APPROVED** [review]

**Pull request merged**
