### PR TITLE
feat: add NeoSteps

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [x] Refactoring

## Context

- [x] Related #5852 
- [x] add NeoSteps
- [x] add story for NeoCarousel

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

Screenshot 2023-05-11 151734

### <samp>🤖 Generated by Copilot at 14f2188</samp>

Added custom steps and carousel components to the `@kodadot1/brick` library and used them in the generative minting UI. Updated the theme variables and styles for the library components to match the kodadot design system. Created story files to showcase the usage and appearance of the new components.

### <samp>🤖 Generated by Copilot at 14f2188</samp>

> _We wrapped some components from `Oruga`_
> _And gave them some styles and some sugar_
> _We used `NeoSteps` for minting_
> _And changed the theme tinting_
> _To make our UI look much snugga_

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
**preview**
Screenshot 2023-05-12 at 08-13-50 KodaDot Low fees and low carbon minting KodaDot - NFT Market Explorer
Screenshot 2023-05-12 at 08-13-34 KodaDot Low fees and low carbon minting KodaDot - NFT Market Explorer


**beta**
Screenshot 2023-05-12 at 08-14-02 KodaDot Low fees and low carbon minting KodaDot - NFT Market Explorer
Screenshot 2023-05-12 at 08-12-59 KodaDot Low fees and low carbon minting KodaDot - NFT Market Explorer

otherwise wfm

**Comment by preschian** [comment]
> preview

oohh thanks, forgot to check it on dark mode

updated
image

**Comment by vikiival** [comment]
cc @kodadot/qa-guild

**Comment by prury** [comment]
- looking good on light/dark mode
- looking good when resizing the window


dark2
light

**Review by Jarsen136 — APPROVED** [review]

**Comment by yangwao** [comment]
Please, resolve conflicts in code, happy to merge it!

**Pull request merged**
