### PR TITLE
feat: Addressable spotlight

### LINKED ISSUE #1164: Addressable spotlight
Whenever you click on the sort at Spotlight https://kodadot.xyz/spotlight on various columns, update address bar accordingly
Add turned on off identity check

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #1164 
- [ ] <brief_description_of_what_I've_added>

addressable with columns、sorting and identity

Add turned on off identity check
### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by Jarsen136** [comment]
> * [ ]  sorting by `Score` doesn't seem to work?

Yes, it is the same as online env (https://kodadot.xyz/spotlight)

After some tries,  I found that it needs to extend some function at `rubick` if it supports sorting by 'score'.
Maybe need to create a new issue to make it.

> * [ ]  `unique items`, `unique collectors` and `score` have regular mouse cursor on hover which doesn't indicate it's clickable + all of those columns are underlined unlike the others. can we unify how the columns look/feel?
>   image

This is an UI effect called dashed.  (underline and unclickable)
more details ref: https://buefy.org/documentation/table/#custom-headers
image


> * [x]  please add space in `Last 30Days Sold` column (30 Days)

done!

**Review by petersopko — APPROVED** [review]

**Comment by petersopko** [comment]
@Jarsen136 can we update / resolve conflicts so we can merge?

**Comment by Jarsen136** [comment]
> @Jarsen136 can you please update / resolve conflicts so we can merge?

Oki, there is no conflicts

**Comment by petersopko** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 70.66 USD/KSM ~ 1.415 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x6e339c0d3ab3a25525b3406a3066d7da9ae64be5198d93266c4911e76b92c2e1](https://kusama.subscan.io/extrinsic/0x6e339c0d3ab3a25525b3406a3066d7da9ae64be5198d93266c4911e76b92c2e1)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
