### PR TITLE
Generative mints drop page

### LINKED ISSUE #9476: Recent generative nft mints in drop page
some updates, the main one is the look, filters, infinite scroll 
image

## design
- updated in handoff https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=394-6126&mode=design&t=EmUe59kRyBTfd3zb-11
- new heading
- new filters
- footer removed
- infinity scroll
- please Reuse Explorer layout 
- new slightly upgraded card 

## Bottom section
shares some similarities with profile layout 
image

- new heading 
- filters - please refer to the component page or reuse the same ones as in the profile 
- default filter is sort by newest - active buy now filter is button active 

## card
image
card is small card from explorer with one addition, instead of the network, there is time, there is no"ago" etc. just time. 

its the same grey tag we are using next to cursor in partykit:
- #9413 

thanks!

### PR DESCRIPTION
**Pull request by pbkompasz**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [X] Refactoring

## Context

- [X] Closes #9476
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [X] My contribution builds **clean without any errors or warnings**
- [X] I've merged recent default branch -- **main** and I've no conflicts
- [X] I've tried to respect high code quality standards
- [X] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [X] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16hqk8Tjugo9AwSzKkxXc1dsRK7iJetpx1YBaoXYwdHzuNAt&usdamount=50&donation=true)

#### Community participation

- [ ] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by yangwao** [comment]
Update PR template and let's make it ready for review

**Comment by hassnian** [comment]
@pbkompasz are you going to continue working on this issue ?

**Comment by yangwao** [comment]
> otherwise, I can take over

I think you can take over on this one

**Comment by hassnian** [comment]
> > otherwise, I can take over
> 
> I think you can take over on this one

on it

**Pull request closed without merging**
