### PR TITLE
feat: Paid drop improvements

### LINKED ISSUE #8833: Paid drop improvements
we will change some things and add warning box into the modal 
- since its paid, we need to ensure user has ED
- and its a plus when user has already for listing fees 

## Design 
updated in figma file: https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=1458-19091&mode=design&t=OQiw3j5B40sVvje5-11

image

## How it works 
- its divided into two main possible cases
   - user has more than 0.5 dot on wallet -> don't show anything and continue like normally 
   - user has less than 0.5
      - autoteleport is available -> show autoteleport and also change copy in the warning to the message with autoteleport
      - no funds on other chains -> show add funds and change copy in the warning box to: "Please add funds to proceed." 

### Warning box 
image

- icon is from fontawesome and has name: circle-exclamation-check 

please also check the colors - some are new, would like to reuse in other UI elements, the other yellow was too aggressive

after hovering over "why?" it shows a tooltip 
image

- learn more redirects to our hello page about existential deposit 

### Dark mode 
image

- in the figma as well

## How it looks on the drop page UI? 
- we will just change the copy of the button to "Mint for 0.3 DOT"

### LINKED ISSUE #8834: Signing paid drop
some changes here as well 

image

## Design 
- updated in the section under paid drop 
- https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=1458-19091&mode=design&t=OQiw3j5B40sVvje5-11

reuses a lot of things from auto teleport signing and free drop claim 

# Modals

## When using autoteleport
image
- similar logic, but instead of the last buying nft step, there will be minting nft 

## All funds okay 
- one little step - changing based on the transaction status
image
- once tx is completed, it automatically goes into a success message for drops

this one: 

image

it applies also to the autoteleport signing - after all txs are done, the bottom button changes into "finish" - that takes you to the same modal

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #8833
- [x] Closes #8834

needs  #8842

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2024-01-04 at 16 49 06@2x

CleanShot 2024-01-04 at 16 35 31@2x

CleanShot 2024-01-04 at 16 36 06@2x

https://github.com/kodadot/nft-gallery/assets/44554284/8aa111c2-0cdd-444e-805d-dd6033686563

## Copilot Summary
copilot:summary

copilot:poem

### CODE REVIEW

**Comment by hassnian** [comment]
@prury pls test ahk/drops/coretime

**Comment by hassnian** [comment]
ref #8842

**Comment by vikiival** [comment]
Honestly this looks like magical glitch to me 

Screenshot 2024-01-04 at 12 51 14

I have never clicked anything on THIS PR and it is magically closed. 

can you please open a new PR please? 

Will report this to @github

**Comment by Jarsen136** [comment]
> I have never clicked anything on THIS PR and it is magically closed.
> 
> can you please open a new PR please?
> 
> EDIT:
> 
> @hassnian took wrong branch :)
> 
> Screenshot 2024-01-04 at 12 53 25

@vikiival  : ) It‘s not wrong because this PR is blocked by #8835. He has to raise a PR and target it to issue-8835. Once we merge `issue-8835` to the main branch, this PR 8846 should change the target to main. And then it's good to go.

**Pull request closed without merging**
