### PR TITLE
RELIST + UNLIST Action Button

### LINKED ISSUE #3605: RELIST + UNLIST action buttons
> List the nft when while minting i’ve already chosen to list it?

to relist it for a different price. Make sense to adjust it for different verb once has some price set and I also notice we don't have that "Unlist" button there

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/3595#issuecomment-1198187387_

following up from the comment above:
1. let's change the wording of `LIST` button to reflect the action, I propose `RELIST` once the NFT is already listed (let's change this cross-chains)
2. let's add option to `UNLIST` the listed NFT (seems to be missing on Basilisk)

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3605
- [x] ui fix: display only top border for action button
image

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

RMRK
image

image

BSX: 
image

image

### CODE REVIEW

**Review by kkukelka — APPROVED** [review]
code lgtm

**Comment by cryptodamsky** [comment]
Why are these price values not shown the same?

image

It’s a bit missleading to see 2 different numbers ? (comma or dot missing down there) 

I belive this is listed for 10k BSX, but it shows something else?



+ the nft is listed afaik for

**Comment by cryptodamsky** [comment]
When i try to explore and look for the minted nft, it’s not anywhere - ( not sure if related, is this logged? )

LOG:

Access to fetch at 'https://app.gc.subsquid.io/beta/snekk/003/graphql' from origin 'https://deploy-preview-3617--koda-nuxt.netlify.app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
app.gc.subsquid.io/beta/snekk/003/graphql:1          Failed to load resource: net::ERR_FAILED
cabe47c.modern.js:2 Uncaught (in promise) Error: Network error: Failed to fetch
    at new t (cabe47c.modern.js:2:2668514)
    at cabe47c.modern.js:2:2689352
    at cabe47c.modern.js:2:2695409
    at Set.forEach (<anonymous>)
    at cabe47c.modern.js:2:2695385
    at Map.forEach (<anonymous>)
    at e.broadcastQueries (cabe47c.modern.js:2:2695335)
    at cabe47c.modern.js:2:2687980
    
    
image

**Comment by cryptodamsky** [comment]
+ I’d go for a bit user friendly term and that would be "Change price" or "Adjust price" instead of relist. The term itself isn’t very explaining for end-user

**Comment by petersopko** [comment]
> When i try to explore and look for the minted nft, it’s not anywhere - ( not sure if related, is this logged? )
> 
image

**Comment by petersopko** [comment]
> Why are these price values not shown the same?
> 
> image
> 
> It’s a bit missleading to see 2 different numbers ? (comma or dot missing down there)
> 
> I belive this is listed for 10k BSX, but it shows something else?
> 
> * the nft is listed afaik for 10k?

I need link or ID of NFT in order to verify it's price in indexer, however the screenshot looks pretty much okay to me:

1. NFT is listed for 100k
2. You're trying to relist it for 5k
3. Minimal amount required to list any NFT on BSX is 10k -> hence the warning

**Comment by cryptodamsky** [comment]
> > Why are these price values not shown the same?
> > image
> > It’s a bit missleading to see 2 different numbers ? (comma or dot missing down there)
> > I belive this is listed for 10k BSX, but it shows something else?
> > 
> > * the nft is listed afaik for 10k?
> 
> I need link or ID of NFT in order to verify it's price in indexer, however the screenshot looks pretty much okay to me:
> 
>     1. NFT is listed for 100k
> 
>     2. You're trying to relist it for 5k
> 
>     3. Minimal amount required to list any NFT on BSX is 10k -> hence the warning

Ye that makes sense, but, why is the price in this format 100,000 BSX and the disclaimer down there in this format? (10000)  (which is not even 100k)

**Comment by petersopko** [comment]
> * I’d go for a bit user friendly term and that would be "Change price" or "Adjust price" instead of relist. The term itself isn’t very explaining for end-user

wao said we can move on with `RELIST`, I think it's pretty common term when it comes to real estate etc., some ref:

https://www.collinsdictionary.com/dictionary/english/relist

Companies have used them to relist their shares after coming out of bankruptcy
Times, Sunday Times (2018)

Early moves to relist the shares are unlikely, though.
Times, Sunday Times (2010)

If it can, it will attempt to relist; if not, it will almost certainly call in the liquidators.
Times, Sunday Times (2009)

**Comment by cryptodamsky** [comment]
We even have it in FAQ, which means ppl don’t necessarily understand this even tho it’s used worldwide. Anyway, i’ve given my feedback, will test this once the indexer works and go with whatever you choose :)

**Comment by cryptodamsky** [comment]
I spotted unusual behavior, while listing or unlisting, the state updates, but it takes super long till the loading goes away?

https://user-images.githubusercontent.com/92786519/182181976-bb6d0ce8-71b6-4110-8631-d0b3871810b9.mov


+ While clicking on UNLIST, there’s a popup with " 1 LIST NFT"

**Comment by Jarsen136** [comment]
> I spotted unusual behavior, while listing or unlisting, the state updates, but it takes super long till the loading goes away?
> 

It really needs that long time to confirm the transaction ; )

> * While clicking on UNLIST, there’s a popup with "1 LIST NFT"

`1` is the id number of the nft.

The `LIST` text is a little bit misleading to the user, even though `LIST\UNLIST\RELISE` are both "LIST" actions on the technical side.

**Comment by cryptodamsky** [comment]
I mean, if the issues in the console are ok, then i guess this is a go :)

**Comment by cryptodamsky** [comment]
image

Do we want to show user this information or is this not related aswell? I feel like there’s a lot tied to listing and unlisting, but i don’t know if this should be reported to new issue, or if that’s something that is supposed to be solved with this issue :)

**Comment by cryptodamsky** [comment]
Listed NFT for sale, but it still shows "List" option?

image

https://deploy-preview-3617--koda-nuxt.netlify.app/rmrk/gallery/11918599-3E9CFBE2606C288A06-ANON-ASDF-0000000000000005?page=1

**Comment by Jarsen136** [comment]
> 
> Do we want to show user this information instead of the name of the nft or is this not related aswell? I feel like there’s a lot tied to listing and unlisting, but i don’t know if this should be reported to new issue, or if that’s something that is supposed to be solved with this issue :)

It should be reported to a new issue IMO.

**Comment by Jarsen136** [comment]
> Listed NFT for sale, but it still shows "List" option and doesn’t show unlist?
> 
> image
> 
> https://deploy-preview-3617--koda-nuxt.netlify.app/rmrk/gallery/11918599-3E9CFBE2606C288A06-ANON-ASDF-0000000000000005?page=1

so strange. It's the same as on `kodadot.xyz`.  I will check it later.
https://kodadot.xyz/rmrk/gallery/11918599-3E9CFBE2606C288A06-ANON-ASDF-0000000000000005

**Comment by Jarsen136** [comment]
> > Listed NFT for sale, but it still shows "List" option and doesn’t show unlist?
> > image
> > https://deploy-preview-3617--koda-nuxt.netlify.app/rmrk/gallery/11918599-3E9CFBE2606C288A06-ANON-ASDF-0000000000000005?page=1
> 
> so strange. It's the same as on `kodadot.xyz`. I will check it later. https://kodadot.xyz/rmrk/gallery/11918599-3E9CFBE2606C288A06-ANON-ASDF-0000000000000005

It's a new issue related to magick/subSquid cc @vikiival 
For the same [nft](https://kodadot.xyz/rmrk/gallery/11918599-3E9CFBE2606C288A06-ANON-ASDF-0000000000000005
),  there are two different event results.

**graphql: nftByIdMinimal**
return mint ans list events
image

**magick: nftByIdMinimal**
return only mint event
image

**Comment by vikiival** [comment]
Please do not use magick #3640

**Comment by Jarsen136** [comment]
> Please do not use magick #3640

Thanks a lot!

With the fixed in #3640, everything is good to go.

@cryptodamsky  Pls take a look at your nft.
https://deploy-preview-3617--koda-nuxt.netlify.app/rmrk/gallery/11918599-3E9CFBE2606C288A06-ANON-ASDF-0000000000000005?page=1

image

**Review by cryptodamsky — APPROVED** [review]

**Comment by petersopko** [comment]
pay 100 usd

**Comment by petersopko** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 61.4 USD/KSM ~ 1.629 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xe48fee4fd97f1e9401e129906e94ac74494ac8318be3c6fade95004d87ffd4ae](https://kusama.subscan.io/extrinsic/0xe48fee4fd97f1e9401e129906e94ac74494ac8318be3c6fade95004d87ffd4ae)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
