### PR TITLE
fix: Separator height

### LINKED ISSUE #5045: Separator height
image
- it should be 1px solid black

same with the line separating number of results and nfts

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5045
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by exezbcz** [comment]
color to black please, otherwise ok 👍 
image

**Comment by Jarsen136** [comment]
> color to black please, otherwise ok 👍 image

I also wonder which color should the separator line to be in dark mode.

**Comment by exezbcz** [comment]
@Jarsen136 
ah, ic. 
So, the top one should be solid black - there outlining the box so its not actual separator, but the ones that are not full width are k-grey
dark mode for this stays k-grey 
image
soo, this to k-grey, in dark mode as well

the rest to k-black please

sorry for the confusion :D

**Comment by Jarsen136** [comment]
> @Jarsen136 ah, ic. So, the top one should be solid black - there outlining the box so its not actual separator, but the ones that are not full width are k-grey dark mode for this stays k-grey image soo, this to k-grey, in dark mode as well
> 
> the rest to k-black please - in dark mode white
> 
> sorry for the confusion :D

Thanks for your clarification. Fixed now

**Comment by vikiival** [comment]
@exezbcz is it visually ok?

**Comment by exezbcz** [comment]
@vikiival yes

**Pull request merged**
