### PR TITLE
➖ unused dependencies

### PR DESCRIPTION
**Pull request by roiLeo**
- #8807 
- #8386

### CODE REVIEW

**Comment by yangwao** [comment]
stealing @renovate-bot job?

**Comment by roiLeo** [comment]
> stealing @renovate-bot job?

yup and still breaking workflow hehehe

**Comment by yangwao** [comment]
isn't better remove update on oruga major version and do renovate job?

Human can't win over robots.

image

**Comment by roiLeo** [comment]
> isn't better remove update on oruga major version and do renovate it's job?

Doable but you'll have to do it and note that oruga update is considered as a "minor" upgrade.

Meanwhile this PR is more about removing some unused dep and add missing peer dep but I still have some issue with eslint.

**Comment by yangwao** [comment]
> is considered as a "minor" upgrade.

ah I see

**Comment by yangwao** [comment]
meanwhile
- https://github.com/kodadot/nft-gallery/pull/8826

**Comment by roiLeo** [comment]
> meanwhile
> 
>     * [Set oruga to 7 #8826](https://github.com/kodadot/nft-gallery/pull/8826)

no changes?

**Comment by yangwao** [comment]
> no changes?

new year, keyboard still drunk

**Comment by yangwao** [comment]
chuckles
- https://github.com/kodadot/nft-gallery/pull/8386

**Comment by yangwao** [comment]
builds

**Pull request merged**
