### PR TITLE
feat: setup Microsoft Clarity

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Feature

  ## Context

  - [x] Closes https://github.com/kodadot/ops-internal/issues/572

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Copilot Summary
  copilot:summary

  copilot:poem

### CODE REVIEW

**Comment by Jarsen136** [comment]
@yangwao  It should work now.

**Comment by yangwao** [comment]
let me check

**Comment by yangwao** [comment]
Thanks!
pay 50 usd

speedy delivery like it 

image

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 7.77 USD/DOT ~ 6.435 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0xfee4e192cf86d1231cac47ac221a197205450df1e595ac5e91265f15fad03a7d](https://polkadot.subscan.io/extrinsic/0xfee4e192cf86d1231cac47ac221a197205450df1e595ac5e91265f15fad03a7d)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
