### PR TITLE
build: reduce manifest size

### LINKED ISSUE #6518: Inspect why Sentry plugin breaks builds on CloudFlare Pages
@preschian Okay, it's a sentry plugin. Seems builds.  

- https://github.com/nuxt-community/sentry-module

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/6470#issuecomment-1662093932_

### PR DESCRIPTION
**Pull request by preschian**
## Summary

Avoid importing images directly in javascript. e.g., `import logo from './path/to/logo.png'`. Use `logo` or `logo` instead

## Details

After implementing https://github.com/kodadot/nft-gallery/pull/6690, I can see clearly which file failed to parse. Based on the logs, there is some problem with [`client.manifest.mjs`](https://cloudflare-ipfs.com/ipfs/QmRqavwfqq7Re6Mx2paAVpDmivrc537jxXFmFcxK9aF1VL). The build failed because the file itself is not a valid `.mjs` format. The file is invalid because there is some plain string instead of javascript/JSON format in the middle of the file. After some checking, I found that the file size is 2.6MB. I think it makes sense if the build failed because [read or write](https://github.com/nuxt/bridge/blob/e1c033e72088484ca44980de9d8014aa018a667c/packages/bridge/src/nitro.ts#L240-L251) 2.6MB file size is quite heavy.

### Improvements

We need to avoid importing images in javascript. I discovered that if we import one image, it can be repeated to 2k times in that manifest file. You can see broken `client.manifest.mjs` in [here](https://cloudflare-ipfs.com/ipfs/QmRqavwfqq7Re6Mx2paAVpDmivrc537jxXFmFcxK9aF1VL).

Screenshot 2023-08-14 at 7 39 37 PM

I moved some `` tags in this PR using images from the `static` folder instead. As a result, the file size is reduced to **680KB** from 2.6MB

| &nbsp; | before | after |
|---|---|---|
| file sizes | 2.6MB | **680KB** |
| line numbers | 99688 | **48145** |
| screenshot | Screenshot 2023-08-14 at 6 56 48 PM | Screenshot 2023-08-14 at 6 56 44 PM |

Now `client.manifest.mjs` is more lighter than before. I think we can close the issue now. And let's reopen in case we face the similar issue again later.

## PR Type

- [x] Bugfix

## Needs QA check

- [x] @kodadot/qa-guild please review

## Context

- [x] Closes #6518

#### Did your issue have any "$" labels on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)

### CODE REVIEW

**Comment by prury** [comment]
nice investigation! 🕵️

**Review by roiLeo — APPROVED** [review]
✅ lgtm

note: `static` will be replaced by `public` with nuxt3

**Review by Jarsen136 — APPROVED** [review]
good job!

**Review by vikiival — APPROVED** [review]
let's roll

**Comment by vikiival** [comment]
pay 111 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $111 @ 4.98 USD/DOT ~ 22.289 $DOT
🧗 [1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p](https://polkadot.subscan.io/account/1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)
🔗 [0xf9ed68df2bef2295cd54f74b00e4d7f3d5db2d2712b272c7540328781f8e3a01](https://polkadot.subscan.io/extrinsic/0xf9ed68df2bef2295cd54f74b00e4d7f3d5db2d2712b272c7540328781f8e3a01)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
