### PR TITLE
feat: add route to snek/assets

### LINKED ISSUE #3875: Assets page
two things I'd like to see:

- [ ]  add route to /assets to profile dropdown - currently, only way to get to https://beta.kodadot.xyz/snek/assets/ is through link which prompts you to change the fees, such as on gallery item page  
image

- [ ] add explanation of what is the user looking at when arriving at /assets, feel free to start with "Select which asset you'd like to use for paying fees for transactions" -> I'll get something more pleasing once PR is open and I see where is it positioned

question to @vikiival why is it called assets? I get that name in relation to wallet (you're managing your assets), but in this case, we are talking strictly about selecting which currency I'd like to pay the fees in, no?

### PR DESCRIPTION
**Pull request by zhengow**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3875
- [ ] Requires deployment <rubick/magick_issue>
- [x] <brief_description_of_what_I've_added>
add route + add explanation

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

### CODE REVIEW

**Comment by petersopko** [comment]
wfm :) let's wait for quick code review from @prachi00 and it's gtg

**Review by petersopko — APPROVED** [review]
✅

**Review by prachi00 — APPROVED** [review]

**Comment by petersopko** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 46.83 USD/KSM ~ 1.068 $KSM
🧗 [EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws](https://kusama.subscan.io/account/EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)
🔗 [0xb79547be390bee6a7af580cd0195363453fc9a15c82cd2bc3f1276bf1f6843a6](https://kusama.subscan.io/extrinsic/0xb79547be390bee6a7af580cd0195363453fc9a15c82cd2bc3f1276bf1f6843a6)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
