### PR TITLE
fix: 4955 gallery item price chart

### LINKED ISSUE #4955: Gallery item chart showing wrong currency
Transaction was made in KSM on Basilisk.

https://beta.kodadot.xyz/bsx/gallery/3579963603-27

image

Also other UX when event is recent under dropdown

image

### PR DESCRIPTION
**Pull request by maderi21**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4955  
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [x] I've tested it at </bsx/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=JHJGu2aWyAFBfcso8bR7ma82p15YAavyN6vQfJyWuhniNGa)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by maderi21** [comment]
two questions here :) 
1. is there some util for converting these currencies?
2. I have some trouble changing the z-index of the tooltip on price chart, what should the correct solution be here from the design perspective? Is adding margin allowed?

**Comment by maderi21** [comment]
> actually, it would be better if put that section in composables chain

moved to composables, and also used it in https://github.com/kodadot/nft-gallery/blob/main/components/gallery/GalleryItemAction/GalleryItemActionSection.vue#L49

**Comment by exezbcz** [comment]
> 2\. I have some trouble changing the z-index of the tooltip on price chart, what should the correct solution be here from the design perspective? Is adding margin allowed?

yy, first and foremost the design of the popup should be different, but there is a issue with the styling iirc. 
image
- I think it can then overflow the chart and even the card itself if its not going to break other things

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
pay 35 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $35 @ 32.73 USD/KSM ~ 1.069 $KSM
🧗 [JHJGu2aWyAFBfcso8bR7ma82p15YAavyN6vQfJyWuhniNGa](https://kusama.subscan.io/account/JHJGu2aWyAFBfcso8bR7ma82p15YAavyN6vQfJyWuhniNGa)
🔗 [0xa600801aea9d29f030988be56db5d28430c9b3efdecb793fe4d0b7ffef5f285f](https://kusama.subscan.io/extrinsic/0xa600801aea9d29f030988be56db5d28430c9b3efdecb793fe4d0b7ffef5f285f)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
