### PR TITLE
Implement sorting by date under holders address

### LINKED ISSUE #2741: Implement sorting by date under address
Implementing sorting by date under address could be interesting

sort them by last bought (date)?

https://user-images.githubusercontent.com/31397967/161295939-684a00a5-096a-480c-8de7-5308c6b9d643.png

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/2724#issuecomment-1086136418_

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2741
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by Jarsen136** [comment]
Note that sorting is based on the latest time of the three: SEND、BUY、MINT.   Instead of the last activity time.

**Comment by yangwao** [comment]
so how it's sorted here? 

at https://deploy-preview-2742--koda-nuxt.netlify.app/rmrk/collection/0a8ce195286c168f19-DONKEY?tab=holders

image

**Comment by yangwao** [comment]
when I clicked to sort by date, it sorts like this, notice 3 days ago on the bottom

https://deploy-preview-2742--koda-nuxt.netlify.app/rmrk/collection/0a8ce195286c168f19-DONKEY?tab=holders

image

**Comment by Jarsen136** [comment]
> collection/0a8ce195286c168f19-DONKEY?tab=holders

Already fixed!

image

**Comment by Jarsen136** [comment]
> so how it's sorted here?
> 
> at https://deploy-preview-2742--koda-nuxt.netlify.app/rmrk/collection/0a8ce195286c168f19-DONKEY?tab=holders
> 
> image

This result is correct. We need to check the history info of nft item and see when 'gift' 'buy' 'mint' event happened.

**Comment by yangwao** [comment]
okay seems fixed 

image

except this one is weird.. but it's LIST tho?  

image

**Comment by Jarsen136** [comment]
> 
> except this one is weird.. but it's LIST tho?
> 
> image


nft-228 the buy time is 4 months ago, so I think the sorting result is correct. 👀  

image

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 196.69 USD/KSM ~ 0.508 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xb8dc2c736f7a54a1230a67c29e5a64d7228842be7e386972460f1f3aed59b200](https://kusama.subscan.io/extrinsic/0xb8dc2c736f7a54a1230a67c29e5a64d7228842be7e386972460f1f3aed59b200)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
