### PR TITLE
🔧 disable button on expired offer

### LINKED ISSUE #3790: Handle expired offers acceptation
Currently on our front end, we leave space for confusion when it comes to expired offers. On image below, there is one of my NFTs after clicking on Action button, accept offer.

Proposed solution:
Let user click on the button and show red text above the table, saying `Selected offer is expired and can no longer be accepted`. Inspiration can be found in the way errors are handled at Create NFTs `/bsx/create` Maybe @roiLeo can chip in on how to handle this properly, but iirc you don't like disabling buttons + tooltips 😆.

Don't forget to test:
Every place which has option of accepting offers.

image

### PR DESCRIPTION
**Pull request by roiLeo**
### PR type

- [x] Bugfix

### What's new?

- [x] PR closes #3790 

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DVYy1qnocE8t6ZvUfPx3rEjG829khNRXx3YrCGVHHj19Lcb)

### Screenshot

Capture d’écran 2022-10-04 à 2 37 19 PM

### Note

Would it be possible for the currentOwner to remove expired offers?

### CODE REVIEW

**Review by kkukelka — APPROVED** [review]
code lgtm

**Review by petersopko — APPROVED** [review]
wfm

**Comment by petersopko** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 43.37 USD/KSM ~ 1.153 $KSM
🧗 [DVYy1qnocE8t6ZvUfPx3rEjG829khNRXx3YrCGVHHj19Lcb](https://kusama.subscan.io/account/DVYy1qnocE8t6ZvUfPx3rEjG829khNRXx3YrCGVHHj19Lcb)
🔗 [0x827ac0ea8f5e6597493fd423d4cf4af3eff413b1106f62dac5aee49ad9f5f580](https://kusama.subscan.io/extrinsic/0x827ac0ea8f5e6597493fd423d4cf4af3eff413b1106f62dac5aee49ad9f5f580)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
