### PR TITLE
#5144 highlight clickable

### LINKED ISSUE #5144: Highlight clickable link in item description
how users will know there is clickable link in description?

https://user-images.githubusercontent.com/5887929/222238820-056b3371-7fab-42d1-9d27-397c5085c42c.mov

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [ ] Closes #5144
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [ ] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screen Shot 2023-03-01 at 10 55 19 PM

### CODE REVIEW

**Review by roiLeo — CHANGES_REQUESTED** [review]
please add `:hover` state

**Review by roiLeo — APPROVED** [review]
✅ code lgtm & wfm

**Review by daiagi — APPROVED** [review]
Wfm

**Comment by vikiival** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 34.18 USD/KSM ~ 0.585 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0xaae2c4f666b503f07d2f6cd5f94568e4cb5257fd23e3f618954773433b929eea](https://kusama.subscan.io/extrinsic/0xaae2c4f666b503f07d2f6cd5f94568e4cb5257fd23e3f618954773433b929eea)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
