### PR TITLE
fix: Email signup modal button animation 

### LINKED ISSUE #8317: Email signup modal button animation
image
- looks good! 
- some small details
- one line is not under the text 
image
dark mode is bit off 
- the text should be white 
- no animation on hover 

so when you hover over, the animation is not displayed, the button on hover is the same as other buttons

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #8317

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2023-12-02 at 12 06 57@2x

CleanShot 2023-12-02 at 12 08 04@2x

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 854d471</samp>

Added a new custom color variable `--k-accent2` and used it for various UI elements. Improved the `shineEffect` mixin to allow more flexibility in positioning the effect.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 854d471</samp>

> _We're shining in the dark with our custom accent_
> _We're using mixins to control the effect_
> _We're changing colors on hover to make them react_
> _We're the masters of the `tailwind` dialect_

### CODE REVIEW

**Comment by exezbcz** [comment]
fancy

thanks 


one thing left 
> so when you hover over, the animation is not displayed, the button on hover is the same as other buttons

**Comment by hassnian** [comment]
> fancy
> 
> thanks
> 
> one thing left
> 
> > so when you hover over, the animation is not displayed, the button on hover is the same as other buttons

hmm not sure what you mean 

https://github.com/kodadot/nft-gallery/assets/44554284/5cbe25ae-3e37-41f9-896e-8a49e27b308d

https://github.com/kodadot/nft-gallery/assets/44554284/262e3d02-a1cc-47b0-9908-310e2311a294

**Comment by roiLeo** [comment]
> hmm not sure what you mean

I think on hover you shouldn't have the animation, only simple bg + text color

**Comment by exezbcz** [comment]
> > hmm not sure what you mean
> 
> I think on hover you shouldn't have the animation, only simple bg + text color
> 

Exactly thanks sir

**Review by roiLeo — APPROVED** [review]
check conflicts please

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 5.56 USD/DOT ~ 5.396 $DOT
🧗 [13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh](https://polkadot.subscan.io/account/13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)
🔗 [0x880490967cd2b73f01dcef1fbd55d8d6cfd25371f23a185fb70164508c88ce0b](https://polkadot.subscan.io/extrinsic/0x880490967cd2b73f01dcef1fbd55d8d6cfd25371f23a185fb70164508c88ce0b)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
