### PR TITLE
#3430 curated list doesnt change with chain/prefix change

### LINKED ISSUE #3430: curated list doesn't change with chain/prefix change
currently on landing, when I change between RMRK/BSX, everything changes accordingly, except for curated list which stays the same
happening both from rmrk -> bsx and bsx -> rmrk
image

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #3430 
- [ ] Requires deployment <rubick/magick_issue>
- [x] Tried many solutions but `settimeout` is the only solution that seems to work, lmk if anyone can think of a better solution 

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by kkukelka — APPROVED** [review]
@prachi00 doesn't work for me on Statemine and Westmint. Or is that because we don't have  Curated Lists for them?

**Comment by prachi00** [comment]
> @prachi00 doesn't work for me on Statemine and Westmint. Or is that because we don't have Curated Lists for them?

yeah we probably dont have for them

**Comment by kkukelka** [comment]
> > @prachi00 doesn't work for me on Statemine and Westmint. Or is that because we don't have Curated Lists for them?
> 
> yeah we probably dont have for them

alrighty then, ticket mentioned bsx/rmrk and back which works so i'll proceed to merge

**Comment by kkukelka** [comment]
pay 100

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 48.75 USD/KSM ~ 2.051 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0xd24935e659705ddd3079e9d2162b85c70c302ebdfd1da9038d259028b391083f](https://kusama.subscan.io/extrinsic/0xd24935e659705ddd3079e9d2162b85c70c302ebdfd1da9038d259028b391083f)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
