### PR TITLE
feat(collection): pagination

### LINKED ISSUE #1018: Add pagination to collection
Now we have an issue that the user scrolls, 
while it loads items one by one, on slow internet, which could be a pain.

Let's add pagination for 3x3 as we will be releasing mass-mint and mass-airdrops

https://nft.kodadot.xyz/rmrk/collection/96A4D072A809BD211F-0XV

### PR DESCRIPTION
**Pull request by roiLeo**
easy one
Still need ToggleLayout component as said in #986 to make filtering better/nicer

### PR type
- [x] Feature

### Before submitting this PR, please make sure:
- [x] Code builds clean without any errors or warnings
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional
- [x] I've tested it on mobile and everything works

### What's new? (may be part of changelog)
- This PR closes #1018 

### Screenshot
Screenshot 2021-11-04 at 10-15-59 0xVentures KodaDot mass mint

### CODE REVIEW

**Review by vikiival — COMMENTED** [review]
Cood looks good

**Comment by vikiival** [comment]
https://user-images.githubusercontent.com/22471030/140306438-96eed61f-69a6-40dc-9b31-85a5a4f67841.mov

**Comment by roiLeo** [comment]
> Can we fix this ? https://user-images.githubusercontent.com/22471030/140306438-96eed61f-69a6-40dc-9b31-85a5a4f67841.mov

Looks like [scroll behavior](https://router.vuejs.org/guide/advanced/scroll-behavior.html) has been configured.
Every route change scroll position is reseting to {0, 0}. (this happen on Gallery, Collection, Profile ...)
We can remove it in src/router/index.ts, but I don't why it has been introduced in code and it could break something else.
I think it would be better to open a new issue.

**Comment by yangwao** [comment]
> > Can we fix this ? https://user-images.githubusercontent.com/22471030/140306438-96eed61f-69a6-40dc-9b31-85a5a4f67841.mov
> 
> Looks like [scroll behavior](https://router.vuejs.org/guide/advanced/scroll-behavior.html) has been configured. Every route change scroll position is reseting to {0, 0}. (this happen on Gallery, Collection, Profile ...) We can remove it in src/router/index.ts, but I don't why it has been introduced in code and it could break something else. I think it would be better to open a new issue.
> 
> edit: seems we can disable scroll behavior on specific route

I guess because when you scroll in gallery and hit next page, it putted you scrolled on new page, what I've recall.

**Comment by roiLeo** [comment]
> I guess because when you scroll in gallery and hit next page, it putted you scrolled on new page, what I've recall. oh yeah, disable scroll here and let's merge it!

There is already a ScrollTop each page change (pagination component) and it's not looking very well on collection.

**Comment by vikiival** [comment]
> There is already a ScrollTop each page change (pagination component) and it's not looking very well on collection.

so may fix for this?

```ts
@Prop(Boolean) preserveScroll!: boolean
```

**Pull request merged**
