### PR TITLE
#4276 Landing page visual change

### LINKED ISSUE #4276: Landing page visual change
Hey, after some time, I am here with fresh designs for landing pages. I think it's not a very big change from the code perspective, but definitely from the visual one.
image

The question is, how do you want to export it? It's basically a blurred shape with a noise texture on top. Is there any way to apply noise texture to the layer above the blurred shapes? I will drop the frames into the landing page handoff so you can have a look.
Lmk

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #4276
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screen Shot 2022-12-03 at 3 39 39 PM
Screen Shot 2022-12-03 at 3 39 46 PM

### CODE REVIEW

**Comment by yangwao** [comment]
ooo looks really nice! :)

**Comment by exezbcz** [comment]
It's near, but it's not it, especially on smaller displays. Perhaps it would be good to separate the components, the blurry shapes, and then the graphics. As a result, it can be scaled and turned off separately. - I'll export it and name it accordingly. The visuals would then behave just as they do on the present page (not showing on smaller screens)
image
- here, i would only show the blurred shapes. 
- they are also cropped badly, my fault - in latest export it should be correct. 
image


image
it would be also nice staying from this behavior - graphics collapsing into the heading. 
it can maybe scale down? 
image

new svgs - again, sorry for that, lmk if it is working properly
light mode left
light mode right
light mode shapes left
light mode shapes right
dark mode left
dark mode right
dark mode shapes left
dark mode shapes right

Thanks!

**Comment by exezbcz** [comment]
one more thing, please dont constraint the blurred shapes only to the footer
image

**Comment by prachi00** [comment]
@exezbcz for the new svgs, why are there four blurred shapes? and also the shapes for light mode is missing

**Comment by exezbcz** [comment]
> @exezbcz for the new svgs, why are there four blurred shapes? and also the shapes for light mode is missing

yes, i was exporting that in bulk, its excessive. 
Shapes for light mode are also in the comment. 
image

**Comment by prachi00** [comment]
Screen Shot 2022-12-05 at 9 49 22 PM
I am still trying to figure out the footer thing, because if I remove the z-index, while it shows correctly, it makes see more and the 1st article non clickable, so trying to find a way around this but rest of the changes I pushed

**Comment by exezbcz** [comment]
footer graphics missing on darkmode

**Comment by prachi00** [comment]
> footer graphics missing on darkmode

fixed and the bg issue is fixed too

**Comment by exezbcz** [comment]
> @exezbcz on hover barely to see the text, is that expected?

haha, It took me a while to notice it :DDD 
Yup, thats a problem. First issue I see is that there should not be hover offect on text like this. I never mentioned it anywhere. I should have raised an issue for that, my bad.

**Comment by prachi00** [comment]
@preschian I have removed that code for now
@exezbcz can we keep the footer as it is right now and create a new issue to make it overflow to the top, I am facing issues with it, so not really sure how to go on about doing that

**Comment by yangwao** [comment]
> can we keep the footer as it is right now and create a new issue

yes, otherwise lgtm for me 
- #4458

**Comment by yangwao** [comment]
pay 80 usd

**Pull request merged**
