### PR TITLE
fix: total sold items from real events

### LINKED ISSUE #9474: profile statistics do not match activity
okay, so from clarity i found one user that was struggling with activity in profile 

https://kodadot.xyz/ahp/u/1246pXonxsWRB1AFrWswiRxsdSArq6R6vyd719g6A1WWasH5?tab=activity&buy=true&sale=true&mint=true&transfer=true&list=true

it shows that he sold one item and bought 6 
image

but when you click to activity, there is no sale activity 
image

### PR DESCRIPTION
**Pull request by pbkompasz**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [X] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [X] Closes #9474
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [X] My contribution builds **clean without any errors or warnings**
- [X] I've merged recent default branch -- **main** and I've no conflicts
- [X] I've tried to respect high code quality standards
- [X] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [X] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16hqk8Tjugo9AwSzKkxXc1dsRK7iJetpx1YBaoXYwdHzuNAt&usdamount=50&donation=true)

#### Community participation

- [ ] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by prury** [comment]
i think the problem may be bigger than we thought 

please compare: 
https://deploy-preview-9497--koda-canary.netlify.app/ahk/u/CmWHiv7h4m9tEzKD94DH4mqwGTvsdYQe2nouWPF7ipmHpqA?tab=activity&buy=false&sale=true&page=2

https://canary.kodadot.xyz/ahk/u/CmWHiv7h4m9tEzKD94DH4mqwGTvsdYQe2nouWPF7ipmHpqA

if you look at activity, there are like way more than 20 sell actions

**Comment by pbkompasz** [comment]
@prury Seems like it. I will investigate it further.

**Comment by pbkompasz** [comment]
@prury The `profileStatsById` query returns wrong values for sell events. The listed, sold, holdings, max sold price, etc. values are wrong. One solution would be injecting these vaues from `Activity.vue` given that these are all fetched there aswell and would also improve the loading time.

**Comment by prury** [comment]
> @prury The `profileStatsById` query returns wrong values for sell events. The listed, sold, holdings, max sold price, etc. values are wrong. One solution would be injecting these vaues from `Activity.vue` given that these are all fetched there aswell and would also improve the loading time.

let's see what internal dev thinks

**Comment by Jarsen136** [comment]
> @prury The `profileStatsById` query returns wrong values for sell events. The listed, sold, holdings, max sold price, etc. values are wrong. 

It's related to the graphql query file. Could you check why it's wrong?
image


> One solution would be injecting these vaues from `Activity.vue` given that these are all fetched there aswell and would also improve the loading time.

`Activity.vue` component is not loaded at the beginning because it's on-demand. You have to force load it if you would like to get the values from it.
loading time would not be improved because the `Activity` component would take much more time to load all data.

**Comment by pbkompasz** [comment]
@Jarsen136 Sure, I will look into it. Is there some documentation on the queries, I couldn't find any.

**Comment by Jarsen136** [comment]
> @Jarsen136 Sure, I will look into it. Is there some documentation on the queries, I couldn't find any.

https://github.com/vikiival/slides/blob/main/graphql-intro/slides.md
https://graphql.org/learn/

**Review by preschian — COMMENTED** [review]
any updates?

**Comment by exezbcz** [comment]
ugh two weeks, closing

**Pull request closed without merging**
