### PR TITLE
:tada: unify the metadata

### PR DESCRIPTION
**Pull request by vikiival**
- :tada: Initial commit of @kodadot1/content
- :test_tube: attributeFrom
- :broom: use any, that is how docs said that
- :zap: tags
- :zap: thumbnail, other metadata extended
- :label: thumbnail
- :label: generative art
- :zap: do no break original logick
- :zap: normalize
- :wastebasket: no one will use or
- :label: Opensea Metadata are split
- :zap: correct order of metadta
- :test_tube: tests
- :arrow_up: dev deps for minipfs

**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

I was sad that like small metadata inconsistencies costs us a lot of on the user satisfaction.
I wrote a simple package that should most probably translate all the Possilbe Metadata to Content object.
Take this as v0.1 

**If you seen something in the code that should be a part of this lib please lmk.**

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [x] I've written unit tests 🧪
- [x] I've found edge cases

### <samp>🤖 Generated by Copilot at 634a65b</samp>

This pull request adds the `@kodadot1/content` package to the `libs/content` folder. This package is a library for getting unified NFT content from different metadata sources and formats. It provides some functions, types, constants, and config files for normalizing, accessing, and displaying NFT content. It also includes some unit tests, documentation, and license files for the package. It also updates the `pnpm-lock.yaml` file and adds some code style and quality tools, such as ESLint, Prettier, Just, and EditorConfig, to the `libs/content` folder.

### <samp>🤖 Generated by Copilot at 634a65b</samp>

> _There once was a package for content_
> _That needed some files to augment_
> _It added some `config`s_
> _And some tests and some `utils`_
> _And a `README` to document_

### CODE REVIEW

**Comment by vikiival** [comment]
cc @kodadot/internal-dev anything missing here?

**Review by roiLeo — COMMENTED** [review]
- I would put this code in `/utils` instead of adding a new package
- typo `constatnts.ts` filename
- is the package name definitive? I'm afraid that we may have conflict with nuxt/content package

**Comment by vikiival** [comment]
> I would put this code in /utils instead of adding a new package

I need that also for Squid indexers, that is the reason

> typo constatnts.ts filename

Thanks will fix

> is the package name definitive? I'm afraid that we may have conflict with nuxt/content package

no it is not any ideas for name?

**Comment by roiLeo** [comment]
> I need that also for Squid indexers, that is the reason

Could be in kodadot/packages then?

> no it is not any ideas for name?

What's the purpose? toolbox? utils?

**Comment by vikiival** [comment]
What's the purpose? toolbox? utils?

Screenshot 2023-09-01 at 15 46 02


https://github.com/kodadot/nft-gallery/discussions/4754#discussioncomment-6281383


> name 

https://en.wikipedia.org/wiki/Hyperdata

**Comment by vikiival** [comment]
Screenshot 2023-09-01 at 16 26 53

**Comment by poppyseedDev** [comment]
Sooo... is going to be 🫑 or 🍅

**Pull request merged**
