### PR TITLE
e2e: fix flaky test

### LINKED ISSUE #3755: E2E - Flaky test?
seems like there is some flaky test. for example, try to open `test` jobs in this pipeline https://github.com/kodadot/nft-gallery/actions/runs/2862034445
Screen Shot 2022-08-16 at 21 21 07

sometimes, it can be reproducible on local also. try to retry the test several times. there is some test that needs several attempts to succeed (marked with yellow colour)
Screen Shot 2022-08-16 at 21 20 02

for a temporary fix, try to retry your pipeline in case you get an error.

it would be great if the issue was resolved. possible fix (maybe):
- increase the timeout from 4s to 10s?
- increase retries attempts from 2 to 3?

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3755 
- [x] add `cypress-network-idle`. make sure to run next steps when the network completed the requests
- [x] adjust `viewportWidth`
- [x] adjust `defaultCommandTimeout` to 10s
- [x] adjust `retries` to 3x

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged the recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
code lgtm & tests pass

I don't know what else to say since I don't have enough experience with cypress.
I'll let peter add comments if needed.

**Review by petersopko — APPROVED** [review]
Personally, I haven't seen the `cy.waitForNetworkIdle` used before, but if the package doesn't get deprecated, it seems to be exactly what we need :)

**Comment by petersopko** [comment]
pay 50 usd

**Comment by yangwao** [comment]
pay 50

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 54.64 USD/KSM ~ 0.915 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0xee545bb36386b18db33159060acfa1e4e7b499104c398df0dcaeeb92ae66598d](https://kusama.subscan.io/extrinsic/0xee545bb36386b18db33159060acfa1e4e7b499104c398df0dcaeeb92ae66598d)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
