### PR TITLE
#6262 sidebar consistency

### LINKED ISSUE #6262: Sidebar consistency
image
image
image
- please make the top part of the notification sidebar the same as the other sidebars - that means 32px horizontal padding and 16px vertical. 
- change the text of connect wallet sidebar to "connect wallet." 

image

### PR DESCRIPTION
**Pull request by prachi00**
a**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #6262
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)

## Screenshot 📸

- [x] My fix has changed UI

Screen Shot 2023-06-19 at 9 16 53 PM

### CODE REVIEW

**Review by preschian — APPROVED** [review]

**Comment by prury** [comment]
They are all about the same height now, good.

@prachi00, when you changed the Connect Wallet sidebar to Connect Wallet, you also changed the profile to Connect wallet: 
image

**Comment by prachi00** [comment]
> They are all about the same height now, good.
> 
> @prachi00, when you changed the Connect Wallet sidebar to Connect Wallet, you also changed the profile to Connect wallet: image

arent they the same sidebar modal?

**Comment by exezbcz** [comment]
@prachi00 yes, but connect wallet is not what the profile sidebar is about

**Comment by prury** [comment]
> > They are all about the same height now, good.
> > @prachi00, when you changed the Connect Wallet sidebar to Connect Wallet, you also changed the profile to Connect wallet: image
> 
> arent they the same sidebar modal?

they are, but their states are different depending if the user has his/her wallet connected or not, for example: 

- the title here should be "connect wallet":
image

and once the user connects its wallet, it should be renamed to Profile: 
image

**Comment by prachi00** [comment]
@prury got it, fixed

**Review by vikiival — APPROVED** [review]

**Pull request merged**
