### PR TITLE
Gasless mint

### LINKED ISSUE #7956: Simple mint gasless toggle and small changes
ref 
- https://github.com/kodadot/nft-gallery/issues/7825

# Abstract 
image
- added section in simple mint; when activated, it mints into our kodadot collective collection)
- design updated in handoff file: https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=5000%3A1078&mode=design&t=bdDUIMGGuJOQsWYI-1
added also the banners etc. 
image
- blue one is for polkadot hub, grey for kusama hub, white for dev

# Design changes
- already mentioned added section
- background UI changed to white (in dark mode, normal background color user everywhere)
- reordered sections - Network put before collection selection; it did not make sense the other way around

----------

## Collection selection
image
- The default state is simple
- when you activate the kodadot collective, a glow is displayed behind the icon

Are there any additional transactions that the user has to sign? cc @vikiival 

if you have any question feel free to ask

### PR DESCRIPTION
**Pull request by pbkompasz**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [X] Feature
- [X] Refactoring

## Context

- [X] Closes #7956
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [X] My contribution builds **clean without any errors or warnings**
- [X] I've merged recent default branch -- **main** and I've no conflicts
- [X] I've tried to respect high code quality standards
- [X] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [X] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16hqk8Tjugo9AwSzKkxXc1dsRK7iJetpx1YBaoXYwdHzuNAt&usdamount=50&donation=true)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at 15e2e68</samp>

This pull request improves the user experience of the create page by introducing a new collection option component with a switch and an image, and by updating the styles and labels of the page. The new component simplifies the collection selection process for minting NFTs and replaces the old interface. The changes affect the files `create.scss`, `CreateNft.vue`, and `en.json`.

### <samp>🤖 Generated by Copilot at 15e2e68</samp>

> _Oh we're the minters of the NFTs_
> _We make them with our `collectionOption`s_
> _We heave and ho and switch them as we please_
> _And we don't need no `NFT description`s_

### CODE REVIEW

**Comment by exezbcz** [comment]
helo sir, one thing i did not mention is that this toggle will be only visible for chains ahp and ahk, when user selects rmrk2 etc. it does not show

**Comment by exezbcz** [comment]
any updates sir @pbkompasz 👀

**Comment by pbkompasz** [comment]
@exezbcz Sorry for the delay.
I have a couple of questions:
- Should I use the icon next to the 'Your collection'?
- What is the value of `selectedCollection` in case of the collective option?

**Comment by exezbcz** [comment]
> * Should I use the icon next to the 'Your collection'?

yes please



### feedback 
- i know its a draft but few things here 
image

- the kodadot collective collection is not quite right (i think you can use the blue one and desaturate when disabled) 
- once toggled on, it becomes disabled

**Comment by pbkompasz** [comment]
@exezbcz Noted. I had trouble running the development server, it takes 2-3 minutes to reload the app and I was unable to run any of the tests.
I think it's related to this #7989.
I will write some more test cases to check every scenario once I am able to run them.

**Comment by exezbcz** [comment]
> I had trouble running the development server, it takes 2-3 minutes to reload the app and I was unable to run any of the tests.

have you managed to solve it? 👀

**Comment by daiagi** [comment]
@pbkompasz  any updates?

>I had trouble running the development server

try Firefox or Brave

**Comment by yangwao** [comment]
Hey @pbkompasz any updates on progress? As we would like to have it done for testing for next week.

**Pull request closed without merging**
