### PR TITLE
feat: On hover show absolute date of onchain event

### LINKED ISSUE #8987: On hover show absolute date of onchain event
In activity when user hovers on "1 year ago" it can be somewhere 1 year 1 months up to 1 year 12 months. Would be good to put on all relative times tool tip with precise date of event
image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Feature

  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #8987

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

image
image

  ## Copilot Summary
  copilot:summary

  copilot:poem

### CODE REVIEW

**Comment by prury** [comment]
maybe use the same format we have on profile activity? or vice versa, just for to have the same format across app
image

**Review by preschian — APPROVED** [review]

**Comment by Jarsen136** [comment]
> maybe use the same format we have on profile activity? or vice versa, just for to have the same format across app image

✅ Updated. The date has the same format across the app now. The current format is based on the locale instead of fixed UTC.

image

**Review by roiLeo — APPROVED** [review]
Noice! Can it use local for date format?

**Comment by Jarsen136** [comment]
> Noice! Can it use local for date format?

What kind of date format do you mean? 
Currently it is `'HH:mm | dd.MM.yyyy'`

**Comment by roiLeo** [comment]
> What kind of date format do you mean? Currently it is `'HH:mm | dd.MM.yyyy'`

[toLocaleString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString) or [toLocaleDateString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString)

**Comment by Jarsen136** [comment]
> > What kind of date format do you mean? Currently it is `'HH:mm | dd.MM.yyyy'`
> 
> [toLocaleString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString) or [toLocaleDateString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString)

✅ Updated. `toLocaleString` looks good to me.
image

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
tests?

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 7.39 USD/DOT ~ 4.06 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0xa5f2f4ab75ea129a02b501970327b1c055b2da0d37a5f7ccfa2260e10b71ac5e](https://polkadot.subscan.io/extrinsic/0xa5f2f4ab75ea129a02b501970327b1c055b2da0d37a5f7ccfa2260e10b71ac5e)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
