### PR TITLE
feat: Implement new collection search

### LINKED ISSUE #5795: Implement new collection search into the KodaDot // super charged search
### Is your feature request related to a problem?

Currently user is waiting a lot of time to fetch collections in search.
That's the reason why we wrote [polysearch](https://github.com/kodadot/workers/tree/main/polysearch).

### Describe the solution you would like

I would like to see that we are using polysearch in the search so loading times are much smaller.  **[The API is described here](https://github.com/kodadot/workers/tree/main/polysearch)** and in the attached screenshots.

### Describe alternatives you have considered

Acceptance criteria: 
1. When someone hits collection search it should fetch data from polysearch
2. all existing UI features has to be functional

### Screenshots

I prefer the POST impl:

Screenshot 2023-04-24 at 16 04 25

Screenshot 2023-04-24 at 16 04 21

### Example call

```
POST https://polysearch.w.kodadot.xyz/search
```

body 
```json
{
	"table": "collections",
	"search": "sub0"
}
```

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 \_\_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #5795
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### <samp>🤖 Generated by Copilot at ed2282c</samp>

This pull request enhances the search functionality of the NFT gallery by integrating the Polysearch API for collection suggestions and displaying the network name for each collection. It also fixes a bug in the search suggestion component and adds a new `chain` property to the NFT metadata interface.

### <samp>🤖 Generated by Copilot at ed2282c</samp>

> _To improve the search suggestion view_
> _We use Polysearch API too_
> _We add `chain` to `Metadata`_
> _And fix the image path we get_
> _And refactor some code we do_

### CODE REVIEW

**Comment by Jarsen136** [comment]
I have something missing to implement the new collection search.
1. For now it shows zero because there's a lack of parts in collections from api: unit and floor price. 
image

API result example:
image


2. Would we also like to bring the new collection search into collection explore page? If yes, we need to implement `sortBy` logic on the api side. Here are the total options of sorts.
image

3. It seems that still has not to support searching statemine collection.

cc @vikiival I need your help on the api side.

**Comment by yangwao** [comment]
> 1. shows zero because there's a lack of parts in collections from api

we can use skeleton for now and lazy fetch it from subsquid as it was done till now if possible?



> 2\. Would we also like to bring the new collection search into collection explore page

We can do in separate PR

> 3\. It seems that still has not to support searching statemine collection.

separate issue, @vikiival can add these data to be pushed from Stick to there

**Comment by vikiival** [comment]
Hey @Jarsen136 I will add statemine Collections today but I had to do a smol change

```json
{
  "id": "ksm-3cdf41f721e728d969-VARA",
  "name": "Gear Sub0 Collection",
  "image": "ipfs://ipfs/bafybeidbriqfhzj7cuz2jzcftpmk6czukjd7hunzfnmtpkffzporeee4zy",
  "media_url": "ipfs://ipfs/bafybeidbriqfhzj7cuz2jzcftpmk6czukjd7hunzfnmtpkffzporeee4zy",
  "metadata": "ipfs://ipfs/bafkreifys72uc26xqml5a3k4wbsxol6cbhypxwjikp2liwx3q4brz3i6ka",
  "chain": "ksm",
  "volume": 0,
  "collection_id": "3cdf41f721e728d969-VARA"
}
```

Id now need to contain chain prefix + collection id 
so for routing use `collection_id` (if you have better naming am open to that)

**Comment by vikiival** [comment]
Statemine is there
```
[
	{
		"id": "stmn-1",
		"name": "Birdboy",
		"image": "ipfs://ipfs/QmaTVEBZtj6m579TuxTHc5dFDWkZXMb4rSDNXw4qVDYjYs",
		"media_url": null,
		"metadata": "ipfs://ipfs/QmeXMHxaaWRAUPAFa9KAuDLmf4w3kSYyWwjw6aDjtKncnW",
		"chain": "stmn",
		"volume": 0,
		"collection_id": "1"
	}
]
```

**Comment by Jarsen136** [comment]
> Hey @Jarsen136 I will add statemine Collections today but I had to do a smol change
> 
> ```json
> {
>   "id": "ksm-3cdf41f721e728d969-VARA",
>   "name": "Gear Sub0 Collection",
>   "image": "ipfs://ipfs/bafybeidbriqfhzj7cuz2jzcftpmk6czukjd7hunzfnmtpkffzporeee4zy",
>   "media_url": "ipfs://ipfs/bafybeidbriqfhzj7cuz2jzcftpmk6czukjd7hunzfnmtpkffzporeee4zy",
>   "metadata": "ipfs://ipfs/bafkreifys72uc26xqml5a3k4wbsxol6cbhypxwjikp2liwx3q4brz3i6ka",
>   "chain": "ksm",
>   "volume": 0,
>   "collection_id": "3cdf41f721e728d969-VARA"
> }
> ```
> 
> Id now need to contain chain prefix + collection id so for routing use `collection_id` (if you have better naming am open to that)
> 
> * [polygrade workers#91](https://github.com/kodadot/workers/pull/91)
> 
> > we can use skeleton for now and lazy fetch it from subsquid as it was done till now if possible?
> 
> Yes, please use this

Ok, I will check it

**Comment by Jarsen136** [comment]
> should work for rmrk2?
> 
>

yes

image

**Comment by Jarsen136** [comment]
> >shows zero because there's a lack of parts in collections from api. 

> we can use skeleton for now and lazy fetch it from subsquid as it was done till now if possible?

✅ Updated

image

**Review by preschian — COMMENTED** [review]
is this related? I've got CORS error when I try to search collection

image

**Comment by yangwao** [comment]
> I've got CORS error when I try to search collection

Yes, I think it's related, cc @vikiival 

image

**Comment by vikiival** [comment]
> https://deploy-preview-6063--koda-canary.netlify.app

- https://github.com/kodadot/workers/pull/93

**Comment by vikiival** [comment]
```
Uploaded polysearch (3.09 sec)
Published polysearch (1.23 sec)
  https://polysearch.kodadot.workers.dev
Current Deployment ID: 2f514dfa-b1f2-434b-bf7d-20c8d0c21cb7
```

@Jarsen136 should work now

**Comment by yangwao** [comment]
some works some not, interesting

image

image

but on second it fetches fast apparently.

some collections are not there? cc @vikiival 

image

I have zero errors in console.

Do we have some full-text search magic inside/over it?

**Comment by yangwao** [comment]
pay 50 usd 
works, yet I spotted some glitches, maybe bc of workers?

Let's inspect in 
- #6096

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 25.01 USD/KSM ~ 1.999 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x062b7adb929d522dac8b93ba96fe40c39f76d540130432f4fb142e78e2de30de](https://kusama.subscan.io/extrinsic/0x062b7adb929d522dac8b93ba96fe40c39f76d540130432f4fb142e78e2de30de)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
