### PR TITLE
sync deposit with copies

### LINKED ISSUE #7935: Number of copies - does not affect the deposit price
Create NFT - add NFT to the collection. When adding more copies- it shows still the price of deposit for 1 NFT even though minting more copies I guess means paying more?

Tried on all chains its same. We need to show the real deposit price.

https://github.com/kodadot/nft-gallery/assets/104380776/74664e69-aa8a-4fe3-99c9-2ef9b2eccf3e

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Context

- [x] Closes #7935

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)

### <samp>🤖 Generated by Copilot at 46aadec</samp>

Updated deposit logic and UI for minting multiple NFT copies in `CreateNft.vue` component.

### <samp>🤖 Generated by Copilot at 46aadec</samp>

> _We're minting NFTs on the blockchain_
> _We need to calculate the right deposit_
> _We use the `form.copies` to get the sum_
> _And then we show it with the `deposit` prop_

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
✅ code lgtm

**Review by Jarsen136 — APPROVED** [review]

**Comment by yangwao** [comment]
thanks!
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 5 USD/DOT ~ 4 $DOT
🧗 [1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8](https://polkadot.subscan.io/account/1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)
🔗 [0xd61037953055fef4d877b60357b3743ece452026069b7ecfa740510cf0557ab5](https://polkadot.subscan.io/extrinsic/0xd61037953055fef4d877b60357b3743ece452026069b7ecfa740510cf0557ab5)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
oh no wild conflicts has appeared x_X

**Pull request merged**
