### PR TITLE
chore: enable nitro on production build

### LINKED ISSUE #4396: some `@polkadot` packages has multiple versions
after syncing from the main branch got this warning message. some `@polkadot` use multiple version
image

image

_Originally posted by @preschian in https://github.com/kodadot/nft-gallery/issues/4375#issuecomment-1325919645_

### LINKED ISSUE #4585: Bump new @polkadot packages
Seems would be nice to align the versions we are using with https://github.com/kodadot/packages/tree/main/sub-api to recent one  

image

### LINKED ISSUE #4608: check @nuxt/kit lock later
After some research, I found that the core problem is that the version of `@nuxt/kit` has been changed to `3.0.0`. 
This version seems that does not work well on nuxt2.
(ref: https://github.com/nuxt/framework/issues/9115)

image

I try to lock its version to `3.0.0-rc.13` and then it could build successfully. However, some new warnings came out after build. : )

Maybe someone could help to look into these warnings.
image

_Originally posted by @Jarsen136 in https://github.com/kodadot/nft-gallery/pull/4525#issuecomment-1369060288_

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #4585
- [x] PR closes #4608
- [x] PR closes #4396
- [x] currently there is no official pwa modules for nuxt3/bridge, for temporary using this https://github.com/kevinmarrec/nuxt-pwa-module
- [x] enable nitro on production build

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

Screenshot 2023-01-16 at 00 23 17

### CODE REVIEW

**Comment by yangwao** [comment]
it's happening 🤔👀

**Review by roiLeo — APPROVED** [review]
✅ wfm

I've tested new QR code implementation

Note:
small build error:
```log
[Error: ENOENT: no such file or directory, chmod '.../nft-gallery/.nuxt/pwa/icons/144x144.bdfd6a1d.png'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'chmod',
  path: '.../nft-gallery/.nuxt/pwa/icons/144x144.bdfd6a1d.png'
}

 ERROR  [unhandledRejection] 1
```

**Review by Jarsen136 — APPROVED** [review]
WFM

Good job! Now I could not see the warning about the package version while building and also runtime.

**Comment by yangwao** [comment]
why it was canceled 👀
image

**Comment by yangwao** [comment]
> 6:27:52 PM: Finished processing build request in 4m38.308200318s

idk why I thought this will speed up build times 🤔

**Comment by yangwao** [comment]
> currently there is no official pwa modules for nuxt3/bridge, for temporary using this [kevinmarrec/nuxt-pwa-module](https://github.com/kevinmarrec/nuxt-pwa-module)

let's check on this later one

**Comment by yangwao** [comment]
@preschian ups, conflict 🙈

**Comment by yangwao** [comment]
pay 80 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $80 @ 31.54 USD/KSM ~ 2.536 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0x531348abb5a06a99b9e338c47eeaa735483b7bf1ba5fb489bd9c7c23edbd51f9](https://kusama.subscan.io/extrinsic/0x531348abb5a06a99b9e338c47eeaa735483b7bf1ba5fb489bd9c7c23edbd51f9)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
