### PR TITLE
Activity-chart-outliers

### LINKED ISSUE #6109: Show outliers on chart in activity
We chatted w/ @exezbcz about this that we should stop showing outliers LISTs as it's makes chart ugly

I would propose filter out data points which are LISTS which are not SALEs (and those trade hasn't happened and owners just spamming chart with useless data)

I would cut anything which is probably beyond .75 of usual deviation median

https://kodadot.xyz/stmn/collection/2022/activity
image

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #6109
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?
$

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)

### <samp>🤖 Generated by Copilot at 87c592d</samp>

Improved the collection activity price chart by filtering out outlier data points using a new `removeOutliers` function. Added `median` and `medianAbsoluteDeviation` functions to `@/utils/math` for general math utilities.

### <samp>🤖 Generated by Copilot at 87c592d</samp>

> _We'll filter out the outliers from the data points_
> _With `median` and `medianAbsoluteDeviation`_
> _We'll make the price chart more reliable and fair_
> _Heave away, me hearties, heave away_

#### Before
image

#### After
image

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
Tested on https://deploy-preview-6138--koda-canary.netlify.app/stmn/collection/2022/activity

Doesn't load for me compared to beta

**Comment by daiagi** [comment]
> /stmn/collection/2022/activity

hi @roiLeo 
I've created this PR:
* https://github.com/kodadot/nft-gallery/pull/6146
to illustrate a point, in that PR there are no code diff compare to main yet that collection doesn't load
https://deploy-preview-6146--koda-canary.netlify.app/stmn/collection/2022/activity

this collection is very big and the issue goes back to these:

* https://github.com/kodadot/nft-gallery/issues/5388
* https://github.com/kodadot/loligo/issues/5

**Review by roiLeo — APPROVED** [review]
> hi @roiLeo I've created this PR:
> 
>     * [Test/activity-chart-outliers #6146](https://github.com/kodadot/nft-gallery/pull/6146)
>       to illustrate a point, in that PR there are no code diff compare to main yet that collection doesn't load
>       https://deploy-preview-6146--koda-canary.netlify.app/stmn/collection/2022/activity


Alright noted! personally I would have hidden this feature (Activity Tab) for the time being until fixed  https://github.com/kodadot/nft-gallery/issues/5540#issuecomment-1500272746

**Comment by prury** [comment]
About the outliers, they are still present when i open this deployed version: 
https://deploy-preview-6138--koda-canary.netlify.app/ksm/gallery/11778219-2644199cf3652aaa78-KQ01-008_PIZZA-00000008

**Comment by daiagi** [comment]
> About the outliers, they are still present when i open this deployed version: https://deploy-preview-6138--koda-canary.netlify.app

the issue was about collection activity chart
* https://github.com/kodadot/nft-gallery/issues/6109#issue-1727133764

the chart you've mentioned is a single NFT chart and was not touched in this PR

as to the specific example you've presented, not sure why you are saying there are outliers, the graph looks well behaved and easy to read to me

**Comment by prury** [comment]
> > About the outliers, they are still present when i open this deployed version: https://deploy-preview-6138--koda-canary.netlify.app
> 
> the issue was about collection activity chart
> 
>     * [Show outliers on chart in activity #6109 (comment)](https://github.com/kodadot/nft-gallery/issues/6109#issue-1727133764)
> 
> 
> the chart you've mentioned is a single NFT chart and was not touched in this PR
> 
> as to the specific example you've presented, not sure why you are saying there are outliers, the graph looks well behaved and easy to read to me

@daiagi I apologize, the whole time i was reading outlines instead of outliners and i did not knew this collection activity page existed, will verify this PR properly today, only did a quick check yesterday and assumed it wasn't working.

**Comment by prury** [comment]
- Collection: https://deploy-preview-6138--koda-canary.netlify.app/ksm/collection/dac5c7f54029d0e73c-HXAI8/activity 

before: 
image
after:
image

- Collection: https://deploy-preview-6138--koda-canary.netlify.app/ksm/collection/a0c4801b6dbf04c674-P1Z70/activity

before:
image
after:
image

- Collection: https://deploy-preview-6138--koda-canary.netlify.app/ksm/collection/36bad3dc147db9792b-ARCHIVERSE_BANNERS_ITEMS/activity

before:
image
after:
image

- Collection: https://deploy-preview-6138--koda-canary.netlify.app/ksm/collection/8453d0ccb4cb7e9e59-A51/activity

before:
image
after: 
image


so, most charts are looking better than before indeed, not sure if its the best final solution tho, what do you think @yangwao ?

**Comment by daiagi** [comment]
@prury

let's let it roll
there is no "best final solution"
in any case we will need to use 1 method to clean data from charts that may look quite different from each other
it will work better for some and worst for other

it looks better now and the data is easier to read then it was before, so let's continue
we can always tweak it as needed in the future

**Comment by daiagi** [comment]
@Jarsen136  review please?

**Review by preschian — APPROVED** [review]

**Review by Jarsen136 — APPROVED** [review]

**Comment by vikiival** [comment]
pay 35 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $35 @ 5.2 USD/DOT ~ 6.731 $DOT
🧗 [1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8](https://polkadot.subscan.io/account/1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)
🔗 [0x3cb6a99d643fcdc4d303f84c76707035e757cfcaaa7720e3bf1437857665c141](https://polkadot.subscan.io/extrinsic/0x3cb6a99d643fcdc4d303f84c76707035e757cfcaaa7720e3bf1437857665c141)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
