### PR TITLE
fix: Fix auto-teleport modal on mobile

### LINKED ISSUE #8176: Fix auto-teleport modal on mobile
jumps out of screen: 
image

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #8176

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2023-11-22 at 08 39 21@2x

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 0986fb0</samp>

Improved mobile UI for `AutoTeleportWelcomeModal` component. Adjusted modal width and grid layout to fit smaller screens.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 0986fb0</samp>

> _`AutoTeleportWelcomeModal` is the gate to a new world_
> _But on mobile devices it was broken and unfurled_
> _We fixed the width and the grid to make it shine_
> _Now you can travel anywhere with your phone in line_

### CODE REVIEW

**Comment by hassnian** [comment]
> bento boxes

 🍱 fixed 🙌

**Review by roiLeo — COMMENTED** [review]
ref #8133 might change again

**Comment by hassnian** [comment]
> ref #8133 might change again

yep ic

**Comment by prury** [comment]
lets wait for https://github.com/kodadot/nft-gallery/pull/8136, since @Jarsen136 is doing a superb work of unifying mobile modals

**Review by roiLeo — COMMENTED** [review]
✅ looks way better

Capture d’écran 2023-11-23 à 4 29 17 PM

**Review by roiLeo — APPROVED** [review]

**Comment by yangwao** [comment]
thanks!
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 5.14 USD/DOT ~ 3.891 $DOT
🧗 [13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh](https://polkadot.subscan.io/account/13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)
🔗 [0xae43b46bdcfbcfbdc062b1ec0649aa19959b93cabfbc09e607affc2513b942a4](https://polkadot.subscan.io/extrinsic/0xae43b46bdcfbcfbdc062b1ec0649aa19959b93cabfbc09e607affc2513b942a4)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
