### PR TITLE
fix: Landing top collections overflow

### LINKED ISSUE #4908: Landing top collections overflow
Seems around 1600px it overflows 

image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4908
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
Can't we keep 3 collumns on larger screen? 🥺 (maybe >= 1800px)
Overflow affects only rmrk (ALL period) for now because of big numbers

Otherwise lgtm ✅

**Comment by Jarsen136** [comment]
> Can't we keep 3 collumns on larger screen? 🥺 (maybe >= 1800px) 

It does not work because the container has a width limitation on the landing page. And the width could not contain 3 columns.
image


> Overflow affects only rmrk (ALL period) for now because of big numbers
> 
We could set 2 columns only for rmrk for sure if you prefer to it. 👀

**Comment by yangwao** [comment]
> keep 3 collumns on larger screen? 🥺 (maybe >= 1800px)

probably yes

**Comment by Jarsen136** [comment]
I have made the top collection section wider than other section on large screen landing page. How about now? 
image

**Review by roiLeo — COMMENTED** [review]
Now it looks weird :/ component overflow container

Screenshot 2023-02-06 at 09-19-03 KodaDot - NFT Market Explorer

We could try to hide floorPrice % change since there won't be data

**Review by roiLeo — APPROVED** [review]

**Comment by yangwao** [comment]
pay 30 usd

**Pull request merged**
