### PR TITLE
[TEST PR : DO NOT MERGE]

### LINKED ISSUE #9997: First preview is loading slowly
image
not sure if any of you had the same issues, but for me, the first preview is loading for a good 30 seconds

after it loads, the variation loading time is quick 

what should i check to help with debugging?

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs Design check

- @exezbcz  speed better?

## Context

- [x] Closes #9997 

#### Did your issue had any of the "$" label on it?

- [ ] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by exezbcz** [comment]
was just lurking here 
image

**Comment by prury** [comment]
> was just lurking here image

issue opened

**Comment by daiagi** [comment]
>was just lurking here

exists in canary as well

image



@exezbcz  is the loading time any better for you in this PR?

**Comment by daiagi** [comment]
closing...

**Pull request closed without merging**
