### PR TITLE
Translation hi.json issue #9253

### LINKED ISSUE #9253: Translation incomplete
tried to switch to our hindi translation, and it seems some things are not in the translation file? 
image
image
image
image

### PR DESCRIPTION
**Pull request by TouchstoneTheDev**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #9253
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [ ] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>)

#### Community participation

- [ ] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
Screenshot 2024-02-04 at 20-35-17 KodaDot - NFT Market Explorer

Still missing important key, I think the main goal is to open new PR with missing key in `en.json` file

**Comment by roiLeo** [comment]
> When i run pnpm run locales:check it formats all files ?! when i am trying to look for missing keys also it's just formatting other translations, so it'll be chaos at PR submission !? @roiLeo

Like I said:
> main goal is to open new PR with missing key in en.json file

So first add en translation, then add hi

**Comment by roiLeo** [comment]
> what do you mean by by en translations ? i didn't cahnged anything in en.json !

We need to add missing keys in `en.json` file as the whole app is not fully translated. 
And then you will need to add these missing keys to `hi.json` file

**Comment by roiLeo** [comment]
> where to find the original or missing keys ?

look around in app, each text that is not wrapped in `$t(...)` need to be in `en.json` file

For example see https://github.com/kodadot/nft-gallery/pull/9271#pullrequestreview-1861546317 it's missing these keys

**Comment by roiLeo** [comment]
> Isn't there any version history where you have all the keys as expected :)

Nope, that's why we need to add them

**Review by preschian — COMMENTED** [review]
safe to merge?

**Comment by yangwao** [comment]
@TouchstoneTheDev looks like stale PR to me since 17/2.

Please reopen if you plan to finish it. 
It's eligible for bounty.

**Pull request closed without merging**
