### PR TITLE
Disable ksm/rmrk minting

### LINKED ISSUE #9387: Disable minting on RMRK/KSM
### Is your feature request related to a problem?

Currently minting on RMRK/KSM is no longer viable option as we have AssetHubs where fees are already very friendly and with RFC they would become even lower.

### Describe the solution you would like

I would like to see disabled minting on RMRK/KSM so users can choose only AHP and AHk

### Describe alternatives you have considered

People can already migrate their NFTs from RMRK/KSM to AHK/AHP

### Screenshots

_No response_

### Are there opened related issues?

- https://github.com/kodadot/ops-internal/discussions/1327

### PR DESCRIPTION
**Pull request by Temidayo32**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Closes #9387 
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer?target=14rs1iTduAn9YrqtDwsTZxK9YDbkzDekBstqxc78M6An87fX&amount=0)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by prury** [comment]
@Temidayo32 the issue requires that you disable minting on rmrk1/2 (create->nft, create->multiple nfts), your solution disabled both rmrk1/2 all over the app

**Comment by prury** [comment]
@Temidayo32 there's also massminting on RMRK/RMRK2 that also needs to be disabled, you can either also disable it or you can keep your PR as it is and change this to `related` instead of `closes`:

image

**Comment by Temidayo32** [comment]
@prury thanks for mentioning that. I realised I need to fix that too. Thanks

**Comment by prury** [comment]
rmrk2 and 1 collections still appearing here for me on massminting: 
image

**Comment by prury** [comment]
hey @Temidayo32 let me know if you are still going to work in this PR

**Comment by prury** [comment]
closing this one, can be reopened if contributor comes back

**Comment by Temidayo32** [comment]
I will like this issue merged as `related`.

**Pull request closed without merging**
