### PR TITLE
#1227 warning fix transfer

### LINKED ISSUE #1227: Annoying warning on Transfer
Every time I load transfer with an address like https://kodadot.xyz/transfer/?target=HcEvTkvAPYEEGEndFV9sMmS3P83jdtwhwZq37GfdzA3mLrL it this pops up

Probably it would be a harder one.

image

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇  _ Do a quick check before the merge. 

### PR type
- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted screenshot of demonstrated change in this PR

### Optional
- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything works
- [ ] I found edge cases

### What's new?
- [x] PR closes #1227
- [x] Added a default value when store has empty values

### Had issue bounty label ?
- [x] Fill up your KSM address: 
[Payout](https://kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation
- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [ ] My fix has changed **something** on UI, a screenshot for others, is best to understand changes.

### CODE REVIEW

**Review by vikiival — CHANGES_REQUESTED** [review]
This is not the fix :) 

I would just throw the warning when the address is incorrect.
Not when there is bad format.

💡 : look for the `isAddressValid` function (I used it in some tests)

**Comment by prachi00** [comment]
> isAddressValid

@vikiival the address is correct tho, the issue is with `this.chainProperties?.ss58Format` , chainProperties is undefined during initialization

**Comment by yangwao** [comment]
> > isAddressValid
> 
> @vikiival the address is correct tho, the issue is with `this.chainProperties?.ss58Format` , chainProperties is undefined during initialization

yeah because it's waiting for a connection. Is it possible to skip it, put the transaction into queue and dispatch once it's connected?

**Comment by yangwao** [comment]
continue to #1263

**Pull request closed without merging**
