### PR TITLE
#2771 Bug in hover card "minting ago" and adding bought details

### LINKED ISSUE #2771: Bug in hover card "minting ago"
I sense on the holder's tab we have a bug on hovercard about minting time or activity. 

How is it's calculated right now? 

Hence when I click on the profile I don't see any mints https://kodadot.xyz/rmrk/u/5E7GyFap8TgQYhbKZ65XVRk4BjY37YWQGdmrSXrhzeqoFs2S?tab=collected

image

i.e I'm checking it here https://kodadot.xyz/rmrk/collection/DE9F84C58887199B5F-KALIENOT?tab=holders

Probably we should show at hovercard
- last bought ago, with an icon of the dollar - to show the activity of that account
- the last minting could be there as well

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2771
- [x] Wasn't sure about which key to use for bought details, have used updatedBy for now

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screenshot 2022-04-05 at 11 12 38 PM

### CODE REVIEW

**Comment by yangwao** [comment]
We would like to have 
- minting activity (mint)
- collecting activity (buy event of that user)

**Comment by prachi00** [comment]
> We would like to have
> 
> * minting activity (mint)
> * collecting activity (buy event of that user)

@yangwao this user does not have any minting activity tho

**Comment by yangwao** [comment]
Tricky NFT seems minted and bought something and shows only minted to me

https://deploy-preview-2779--koda-nuxt.netlify.app/rmrk/u/GAYBQX5f7NXS4dv5EnL7NRSGLnAQmoDqajx998nYLv8QoJT?tab=collected

image

**Comment by prachi00** [comment]
> Tricky NFT seems minted and bought something and shows only minted to me
> 
> https://deploy-preview-2779--koda-nuxt.netlify.app/rmrk/u/GAYBQX5f7NXS4dv5EnL7NRSGLnAQmoDqajx998nYLv8QoJT?tab=collected
> 
> image


@yangwao the issue with this is that we dont fetch the collected data from the query unless the collected tab is clicked,  we would have to call the query once this page is loaded then , or maybe there is some other way to fetch last bought data? @vikiival

**Comment by prachi00** [comment]
Screenshot 2022-04-06 at 8 03 07 PM
If you click on collected tab it starts to show up

**Comment by prachi00** [comment]
@vikiival should I fetch the collected query on load then?

**Comment by yangwao** [comment]
Seems doesn't work?

Not even I click collected 

https://deploy-preview-2779--koda-nuxt.netlify.app/rmrk/u/F5Zia5tvajsQzcrXkNiANuaf39C7KpxPydcnbCAkuaz27Wc?tab=collected

image


https://deploy-preview-2779--koda-nuxt.netlify.app/rmrk/collection/6ec662611f161fd10a-TMAGCAT?tab=holders

image

**Comment by yangwao** [comment]
Maybe a recent merge https://github.com/kodadot/rubick/issues/40 would help to tackle this?

📟 @vikiival

**Comment by prachi00** [comment]
Screenshot 2022-04-13 at 3 46 55 PM
 
weird it shows up for me

**Comment by yangwao** [comment]
wait we have two different components doing the "same" ?

https://user-images.githubusercontent.com/5887929/163170903-40529b31-4b0d-47cf-8585-f6b1861ab972.mov

**Comment by yangwao** [comment]
seems works for me, we can fix formatting in another PR

pay 150 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $150 @ 158.87 USD/KSM ~ 0.944 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0xfa0a96ea6279d6c42ad206b39d44072abcea65c64bbdca9566866250272d9635](https://kusama.subscan.io/extrinsic/0xfa0a96ea6279d6c42ad206b39d44072abcea65c64bbdca9566866250272d9635)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
