### PR TITLE
Update template-typescript-w-decorator.vue

### LINKED ISSUE #1522: Update template-typescript-w-decorator.vue to use nuxt
- We will need to update .vscode/vetur/snippetstemplate-typescript-w-decorator.vue to 
```js
import { Vue } from 'nuxt-property-decorator'
```

### PR DESCRIPTION
**Pull request by petersopko**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Do a quick check before the merge.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #1522
- [x] Changed import to come from `nuxt-property-decorator` and removed `Watch` from the imports as it was throwing warning as unused import. I was hesitant to remove `private value2: any` but it's also showed as unused and I can remove it after confirmation (if I'm not missing something). I've checked Vetur docs and I couldn't find what is that `vue.json` file inside of `.vscode/vetur/snippets` doing, but I think, not much? In case the answer's yes, I'd suggest to delete it, if not, perhaps it should be updated to match the file changed in this PR?

### Before submitting Pull Request, please make sure:

- [X] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases

### Had issue bounty label ?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI, a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
> Changed import to come from `nuxt-property-decorator` and removed `Watch` from the imports as it was throwing warning as unused import. I was hesitant to remove `private value2: any` but it's also showed as unused and I can remove it after confirmation (if I'm not missing something). I've checked Vetur docs and I couldn't find what is that `vue.json` file inside of `.vscode/vetur/snippets` doing, but I think, not much? In case the answer's yes, I'd suggest to delete it, if not, perhaps it should be updated to match the file changed in this PR?

Hey, this file is used to have a common default template when we create new component.
There are 2 small things I would change: more meaningful variables (value, value2 ...), change default type `any` because it could be misleading.
For the second point, I think you can safely remove `.vscode/vetur/snippets/vue.json` because template still work without.

**Comment by petersopko** [comment]
> > Changed import to come from `nuxt-property-decorator` and removed `Watch` from the imports as it was throwing warning as unused import. I was hesitant to remove `private value2: any` but it's also showed as unused and I can remove it after confirmation (if I'm not missing something). I've checked Vetur docs and I couldn't find what is that `vue.json` file inside of `.vscode/vetur/snippets` doing, but I think, not much? In case the answer's yes, I'd suggest to delete it, if not, perhaps it should be updated to match the file changed in this PR?
> 
> Hey, this file is used to have a common default template when we create new component. There are 2 small things I would change: more meaningful variables (value, value2 ...), change default type `any` because it could be misleading. For the second point, I think you can safely remove `.vscode/vetur/snippets/vue.json` because template still work without.

I've changed the values to `templateValue` to make it clear, and types to `undefined, so it won't be suggesting it can stay as `any`. Removed the .json file and added back the `Watch` import after the usefulness of template clicked for me.

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 169.01 USD/KSM ~ 0.592 $KSM
🧗 [FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y](https://kusama.subscan.io/account/FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y)
🔗 [0xba8bf3b4cc9a8db436eed9e93d1423f3a7e962ce064222ae9d02acb94a7559f1](https://kusama.subscan.io/extrinsic/0xba8bf3b4cc9a8db436eed9e93d1423f3a7e962ce064222ae9d02acb94a7559f1)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 157.68 USD/KSM ~ 0.634 $KSM
🧗 [FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y](https://kusama.subscan.io/account/FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y)
🔗 [0x47f6702224f107900f6ad7fc90074ec24828efb136ed26242331164d1189e443](https://kusama.subscan.io/extrinsic/0x47f6702224f107900f6ad7fc90074ec24828efb136ed26242331164d1189e443)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
