### PR TITLE
fix: Activity table does not work on Base

### LINKED ISSUE #10383: Activity table does not work on Base
## Context

I wanted to check when the NFT was minted but the activity table showed me no data

## Reproduce 

1. [Go to NFT on base](https://deploy-preview-10354--koda-canary.netlify.app/base/gallery/0xa676ca834b90f5adeb9ffa27fb632f524bb38155-1)
2. In Activity table set all
3. Table is empty

## Result

I expect that activity table works correctly 

Screenshot 2024-06-03 at 14 04 17

## Ref 

propbably same bug as - #10381

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #10383

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

There are still two issues related to the indexer side for Base. @vikiival 
1. incorrect price amount 
2. missing from/to address
image

### CODE REVIEW

**Comment by vikiival** [comment]
Thanks @Jarsen136 issue is on the indexer side.
Will deploy a new version.

AHP

Screenshot 2024-06-04 at 12 23 37

Base

Screenshot 2024-06-04 at 12 24 36


## Notes

> incorrect price amount

Mint does not have price 

Mint (from) is always address(0)

https://opensea.io/assets/ethereum/0x1352149cd78d686043b504e7e7d96c5946b0c39c/1937

Screenshot 2024-06-04 at 12 19 00

**Comment by vikiival** [comment]
I have released a new version of 
- https://github.com/kodadot/basick/pull/23

**Comment by prury** [comment]
> Mint does not have price
>

@vikiival 

for some, mint has price: 

image
https://opensea.io/assets/base/0xc029b380f8a451cfd9e5124fa9fcad4397b8c119/10

**Review by preschian — APPROVED** [review]

**Comment by prury** [comment]
let me know if we are merging it in its current state (unreal minting price)

**Comment by vikiival** [comment]
https://deploy-preview-10387--koda-canary.netlify.app/base/gallery/0xc029b380f8a451cfd9e5124fa9fcad4397b8c119-1


Screenshot 2024-06-05 at 12 36 15

**Review by vikiival — APPROVED** [review]
Works as a charm

**Pull request merged**
