### PR TITLE
fix: neo button hover color

### LINKED ISSUE #6749: Tabs hover effect dark mode
image
guess what is wrong

Correct, its the text inside that changes to its hover state as well - only the bg should change 

please fix the light mode as well
image

### PR DESCRIPTION
**Pull request by floyd-li**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #6749
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

图片
图片

### <samp>🤖 Generated by Copilot at 3211467</samp>

Added theme-based color to button text in `NeoButton.scss`. This improves the appearance and accessibility of the `NeoButton` component.

### <samp>🤖 Generated by Copilot at 3211467</samp>

> _`color` for button_
> _theme function sets the hue_
> _dark mode adapts it_

### CODE REVIEW

**Comment by floyd-li** [comment]
> might be good to look if there is no side effects

yes just checked. i think there's no other effects since this rule only affect `NeoButton`

**Comment by vikiival** [comment]
@kodadot/qa-guild plz

**Comment by roiLeo** [comment]
> yes just checked. i think there's no other effects since this rule only affect `NeoButton`

In fact, this component is used in several places (not only tabs)

**Comment by vikiival** [comment]
pay 15 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $15 @ 4.49 USD/DOT ~ 3.341 $DOT
🧗 [13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A](https://polkadot.subscan.io/account/13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A)
🔗 [0x839b69c4227c6739e071028027b120f7b79562ee898da906ac389bea8738f02a](https://polkadot.subscan.io/extrinsic/0x839b69c4227c6739e071028027b120f7b79562ee898da906ac389bea8738f02a)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
