### PR TITLE
feat: UI migrate - home page

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- Related #7560

## Screenshot 📸

https://deploy-preview-7656--koda-canary.netlify.app/migrate

image

### <samp>🤖 Generated by Copilot at 82dc6df</samp>

No summary available (Limit exceeded: required to process 58889 tokens, but only 50000 are allowed per call)

copilot:poem

### CODE REVIEW

**Comment by exezbcz** [comment]
letsgo! 

# First round 
- most of the layout is oki, I will comment on some spacing, tooltip, and cards, plus a few things from dark mode

### Spacing 
image
 - this to 96px please 

- more space between the container for faq and the subheading 
image

between the sections: 
image
- 64px 
- here too 
image
here
image



### Tooltip
image
- also over the text, not only the icon 


### destination section 
image

- this text to k-grey in both modes 
- please match the styling of the dropdowns and effects to the version in #7363 
- there is also page in the figma.
image

- hover from the default state is only bg change - to the hover color (pink and in dark mode the grey) 

### cards 
- mostly oki, one thing missing is the overlay over the cover img (not the pfp), it should be covered similarly as cards on the drop page and collection, white and dark overlay depending on the mode. 


### dark mode
missing arrow (no white color) 
image

**Review by daiagi — COMMENTED** [review]
missing some translations

**Comment by preschian** [comment]
@exezbcz @daiagi updated

**Review by roiLeo — COMMENTED** [review]
I would like to see better folder structure for Migrate components to be able to use auto imports, could be something like:

- `components/migrate/index.vue`
- `components/migrate/MigrateContent.vue` or `components/migrate/index/content.vue`
- `components/migrate/MigrateHeadervue`

**Comment by prury** [comment]
mobile still needs work, do you wish to do it here on in another PR? lmk

**Comment by exezbcz** [comment]
works for me, I will create some followups for the home page later. 

thanks! Letsgo migration

**Review by exezbcz — APPROVED** [review]

**Comment by preschian** [comment]
> thanks! Letsgo migration

ok, I will merge this



> I would like to see better folder structure for Migrate components to be able to use auto imports, could be something like:
> 
> * `components/migrate/index.vue`
> * `components/migrate/MigrateContent.vue` or `components/migrate/index/content.vue`
> * `components/migrate/MigrateHeadervue`

will check this in separate PR

**Review by daiagi — APPROVED** [review]

**Pull request merged**
