### PR TITLE
#3492 Small UI change

### LINKED ISSUE #3492: Request: Small UI change
Capture d’écran 2022-07-20 à 11 31 34 AM

In GalleryItem, I would like to see spacing under nft title when there is no legend set (just before "Traits" component)

Tested on bsx, this could break rmrk stuff (description, emotes...)

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #3492
- [ ] Requires deployment <rubick/magick_issue>
- [x] the margin looks good even if we have legends, so I kept it for all the cases in bsx, lmkwyt

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screen Shot 2022-07-20 at 6 35 10 PM

Screen Shot 2022-07-20 at 6 34 51 PM

### CODE REVIEW

**Comment by kkukelka** [comment]
hmm for me it now also removes the border
Screenshot 2022-07-21 at 06 58 28

**Comment by prachi00** [comment]
> hmm for me it now also removes the border Screenshot 2022-07-21 at 06 58 28

@kkukelka can you send the url of this item?

**Review by roiLeo — COMMENTED** [review]
can we get rid of this unused `.nft-title` class?

instead I would like:
```html
<Name :nft="nft" :isLoading="isLoading" class="mb-5" />
```
like we do for rmrk galleryItem

**Comment by kkukelka** [comment]
> @kkukelka can you send the url of this item?

Sure thing, https://deploy-preview-3503--koda-nuxt.netlify.app/rmrk/gallery/13562627-3892e43e923e5ad973-KAG-FOOD_1000-0000000000000458?page=2

**Review by JustLuuuu — COMMENTED** [review]
wfm

**Comment by prachi00** [comment]
> > @kkukelka can you send the url of this item?
> 
> Sure thing, https://deploy-preview-3503--koda-nuxt.netlify.app/rmrk/gallery/13562627-3892e43e923e5ad973-KAG-FOOD_1000-0000000000000458?page=2

https://beta.kodadot.xyz/rmrk/gallery/13562627-3892e43e923e5ad973-KAG-FOOD_1000-0000000000000458?page=2
it seems to be like this on beta as well, I guess we only have the border on bsx

**Comment by prachi00** [comment]
> ```
> <Name :nft="nft" :isLoading="isLoading" class="mb-5" />
> ```

done

**Comment by kkukelka** [comment]
> > > @kkukelka can you send the url of this item?
> > 
> > 
> > Sure thing, https://deploy-preview-3503--koda-nuxt.netlify.app/rmrk/gallery/13562627-3892e43e923e5ad973-KAG-FOOD_1000-0000000000000458?page=2
> 
> https://beta.kodadot.xyz/rmrk/gallery/13562627-3892e43e923e5ad973-KAG-FOOD_1000-0000000000000458?page=2 it seems to be like this on beta as well, I guess we only have the border on bsx

already, all good then

**Review by kkukelka — APPROVED** [review]

**Review by roiLeo — CHANGES_REQUESTED** [review]
`mb-3` on bsx while `mb-5` on rmrk, can we keep consitency?

> ```
> <Name :nft="nft" :isLoading="isLoading" class="mb-5" />
> ```
> 
> like we do for rmrk galleryItem

**Review by roiLeo — APPROVED** [review]
✅ lgtm, 
did you know you can put class directly on component?

**Comment by kkukelka** [comment]
pay 50

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 62.25 USD/KSM ~ 0.803 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x6ead4810aadbb1ae52cf89c02e28f750de5850eed0909e74ab56fe7a9394eeaa](https://kusama.subscan.io/extrinsic/0x6ead4810aadbb1ae52cf89c02e28f750de5850eed0909e74ab56fe7a9394eeaa)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
pay 50

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 62.75 USD/KSM ~ 0.797 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x1dccb6b73c463035bb66a7fdd89b65fb06db23037de2900dca7a34cb29dc5456](https://kusama.subscan.io/extrinsic/0x1dccb6b73c463035bb66a7fdd89b65fb06db23037de2900dca7a34cb29dc5456)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
