### PR TITLE
#3508 Sorting by name collection fix

### LINKED ISSUE #3508: sorting by name
### Is your feature request related to a problem?

no, rather with convenience

### Describe the solution you would like

I think it would be good to do nft sorting by name and collection nameBe descriptive and short.
https://beta.kodadot.xyz/bsx/stats/?page=1

### Describe alternatives you have considered

did not consider

### Screeenshots

image

### Are there opened related issues?

_No response_

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3508
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by Jarsen136** [comment]
code lgtm

**Review by Jarsen136 — APPROVED** [review]

**Review by roiLeo — APPROVED** [review]
✅ Tested on https://deploy-preview-3526--koda-nuxt.netlify.app/bsx/stats

I can now sort by collection name & nft name

**Comment by roiLeo** [comment]
pay 50

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 67.74 USD/KSM ~ 0.738 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0xf340531882f69b549053e53c222a526a3f502897b11b126d65eafe2ccd1fbbac](https://kusama.subscan.io/extrinsic/0xf340531882f69b549053e53c222a526a3f502897b11b126d65eafe2ccd1fbbac)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
