### PR TITLE
feat: going rounded - tag changes 

### LINKED ISSUE #7443: going rounded - tag changes
image

few changes to these tags
- since tags and filters are mostly rounded now, let's change this one as well; it will make it look better in the notif sidebar, too 
- let's also remove the hover effect from the tag as it's not needed, and keep only the hover on the x-mark
- updated in small things handoff
- https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=1287%3A18959&mode=design&t=UGn0ZiYKSZ5svmYe-1

### PR DESCRIPTION
**Pull request by hassnian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #7443

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2023-10-02 at 15 06 41@2x

### <samp>🤖 Generated by Copilot at 138d9a9</samp>

Enhanced the appearance and usability of the `NeoTag` component for gallery filtering. Applied a uniform style to the tags and removed unnecessary interactions.

### <samp>🤖 Generated by Copilot at 138d9a9</samp>

> _Oh, we're the crew of the `NeoTag` ship_
> _And we sail the web with skill and wit_
> _We make our tags so round and light_
> _And we don't need no hover in the night_

### CODE REVIEW

**Comment by hassnian** [comment]
@exezbcz there was a blue tag variant , made the same changes

**Comment by exezbcz** [comment]
search tag not working for me: 
image
- this is canary, deploy does not search

search on top of collections does not work either 
image

**Comment by prury** [comment]
> search on top of collections does not work either image
 will add this to nuxt issues

**Comment by exezbcz** [comment]
@prury ah ic, totally missed its on the nuxt

**Review by exezbcz — APPROVED** [review]

**Review by roiLeo — APPROVED** [review]

**Comment by hassnian** [comment]
@yangwao  payout if any thanks

**Pull request merged**
