### PR TITLE
✨ #1422 feat: identity preview hover card

### LINKED ISSUE #1422: Add preview hover card
Like on Github, seems [hic.af](https://hic.af/o/528559) has it as well, was thinking about this a long time ago so it can help preview on a particular artist

Would be great just to prepare components for this as it will be reusable for other contextual stuff

The first implementation could carry this information about the artist
- 🕛 Time from the first mint. Like "3 months ago"
- 💸 number of collected - Bought 
- 🖌 created NFTs - Created
- 💰 Sales - Sold 

https://hic.af/o/528559
image

[From GoodReads](https://www.goodreads.com/choiceawards/best-science-fiction-books-2021) 

image

### Ref
- https://github.com/kodadot/nft-gallery/issues/1421

### PR DESCRIPTION
**Pull request by jbienesdev**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇  _ Do a quick check before the merge. 

### PR type
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main-nuxt** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional
- [x] I've tested it at `/rmrk/u/:id` and `/rmrk/gallery/:id`
- [x] I've tested PR on mobile and everything works
- [ ] I found edge cases

### What's new?
- [x] PR closes #1422
- [x] Opens an identity information card when hovering over the user identity link

### Had issue bounty label ?
- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=F2zKdNM77s17cmtdgqCooGVphz8UFv4jUEuFJ366VVAb53G)

### Community participation
- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [x] My fix has changed **something** on UI, a screenshot for others, is best to understand changes.

https://user-images.githubusercontent.com/17470909/145553042-6912b17a-a234-41cb-a56e-ffc6e9c8a1ed.mp4

--------------------

@yangwao @roiLeo 
Created a new graphql query to query all the nft information inside the popover. Description is the only one that is hardcoded right now. Do you have any ideas what information I can put in place of the "Lorem ipsum" placeholder?

Also, just drop any suggestions for the identicon replacement. Thanks! 😄

### CODE REVIEW

**Comment by yangwao** [comment]
Hey found bug on collection detail 

Have you tried pull latest `main-nuxt` ? 
Happend here to me https://deploy-preview-1474--koda-nuxt.netlify.app/rmrk/collection/3aa8cecefcfd331304-MANEKITTIES-SPECIALS

image

**Comment by yangwao** [comment]
I guess @rhaicode you need to merge recent upstream from `main-nuxt` to get it working! :)

https://user-images.githubusercontent.com/5887929/145576094-23e6c255-8ed7-4719-9655-056e95d18fa3.mov

**Comment by jbienesdev** [comment]
@yangwao I've noticed that when using the `Identicon` component. I've also pulled the latest `main-nuxt` branch before creating the PR but will try to merge it again.

**Comment by jbienesdev** [comment]
Still occurring on Netlify though. I will investigate since it's working on my local and have encountered this issue intermittently.

**Comment by yangwao** [comment]
curious, can you try to disable identicon for now and push it like that?

**Comment by jbienesdev** [comment]
Sure. It will look like this 
image

**Comment by jbienesdev** [comment]
Initially, it seems that Identicon is rendering the `Gallery` page instead of the `Polkadot` component from Identicon's internal code.

image

This should be the correct component order
image

**Comment by yangwao** [comment]
Perfect, I’ve sent the payout https://kusama.subscan.io/extrinsic/0x4ad632aec1050d1af4ad957a0e049e3d3ed51ab64236a58784bd1fae2442483b

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/

**Comment by jbienesdev** [comment]
Received. Thanks! 🚀

**Pull request merged**
