### PR TITLE
fix(ipfs): remove dynamic metadata check from sanitizeIpfsUrl

### LINKED ISSUE #10531: Snail speed load of nft
https://github.com/kodadot/nft-gallery/assets/90852205/57d304aa-ea32-4c34-81e6-7cc05630af8d

https://canary.kodadot.xyz/ahp/gallery/134-2405242232

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #10531. we have this endpoint in the image-workers: `/type/endpoint/${any_url}`. it will cache any url and store to cf-images/cf-r2 based on mimeType. similar with `/ipfs/cid` endpoint, but for non-ipfs content

### CODE REVIEW

**Comment by exezbcz** [comment]
works better for me

**Comment by vikiival** [comment]
@preschian missing more context

**Comment by vikiival** [comment]
Missin review @kodadot/internal-dev

**Review by hassnian — APPROVED** [review]

**Comment by preschian** [comment]
> missing more context

updated the description

**Review by Jarsen136 — APPROVED** [review]

**Pull request merged**
