### PR TITLE
fix(Appreciation): show Emojipicker only if connected

### LINKED ISSUE #597: can't see emojis on gallery Item
**Describe the bug**
We can see emoji on gallery list but we can't see emoji on item when logged off.

**To Reproduce**
1. Go to Gallery
2. Find an Item with one or more emojis
3. Click on it
4. Emoji is not visible on Gallery item

**Expected behavior**
Show emojis on Item or hide it on list.

**Screenshots**
#### Gallery list with an emoji
Screenshot 2021-08-12 at 15-19-41 Low minting fees and carbonless NFTs

#### Gallery Item without emoji
Screenshot 2021-08-12 at 15-20-46 Kulupu - Part of the Substrate DNA

**Additional context**
#589 related

### PR DESCRIPTION
**Pull request by roiLeo**
These will show EmojiPicker Button & EmotionList to disconnected users.
They will not be able to show EmojiPicker unless they're logged in.

### Before submitting this PR, please make sure:
- [x] Code builds clean without any errors or warnings
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I didn't break any original functionality

### PR type
- [x] Bugfix close #597 

### Screenshot
Screenshot 2021-08-17 at 14-28-02 Kulupu - Part of the Substrate DNA

### CODE REVIEW

**Comment by vikiival** [comment]
Cool, maybe hide the emote button when a user is not logged in ?

**Comment by roiLeo** [comment]
> Cool, maybe hide the emote button when a user is not logged in ?

Work in progress some minor css tweak need to be done.

**Comment by roiLeo** [comment]
### Screen 
#### not logged in
Screenshot 2021-08-17 at 16-14-25 Kulupu - Part of the Substrate DNA

#### logged in 
Screenshot 2021-08-17 at 16-17-28 Kulupu - Part of the Substrate DNA

**Review by vikiival — APPROVED** [review]
Awesome!

**Comment by yangwao** [comment]
@vikiival seems emoji layouts are bit off

https://deploy-preview-604--nftkodadot.netlify.app/rmrk/detail/8815586-420ae612726839da09-%F0%9F%98%88-THC_03_NINJA_TUNA_COMMON_315-0000000000000003
image


https://nft.kodadot.xyz/rmrk/detail/8815586-420ae612726839da09-%F0%9F%98%88-THC_03_NINJA_TUNA_COMMON_315-0000000000000003
image

**Comment by yangwao** [comment]
WFM! @vikiival check
image

**Pull request merged**
