### PR TITLE
fix #5298

### LINKED ISSUE #5298: Not showing the name of the NFT properly
### What happened?

Artist asked me for help (he is not using GitHub) - This collection was burned twice and was minted for the third time because there were issues with minting before and he had to burn it - please tell me that he does not need to burn it again 😅
- https://github.com/kodadot/nft-gallery/issues/5126 I think one of his previous issues was related to this on
### Problem
His collection is **not showing the name of the NFT in NFT detail**. But its visible in the collection. Collection: https://kodadot.xyz/bsx/collection/3268254081?page=1 
Here you can see the name of the NFT:
Screenshot 2023-03-19 at 12 18 35
After you open it to see the NFT. You see only numbers as a name:
Screenshot 2023-03-19 at 12 18 40

This is happening only in some cases. Not all the NFTs in the collection have a problem like this.
Screenshot 2023-03-19 at 12 24 41

### Please reproduce in steps

Open [this](https://kodadot.xyz/bsx/collection/3268254081?page=1 ) collection - check [this](https://kodadot.xyz/bsx/gallery/3268254081-8) NFT. 

### Expected Behavior

Have visible name

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz, kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### Screenshots

-

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5298
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [x] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=#5298)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image
image

### CODE REVIEW

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
pay 15 usd

**Comment by daiagi** [comment]
> pay 15 usd

@vikiival no payout?

**Comment by daiagi** [comment]
oops

EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L

**Comment by daiagi** [comment]
pay 15 usd

**Comment by vikiival** [comment]
pay 15 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $15 @ 34.45 USD/KSM ~ 0.435 $KSM
🧗 [EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L](https://kusama.subscan.io/account/EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L)
🔗 [0x558edac21b935fa320dab3e0ffc147fb5be407aeadad3387e75776bc5f6f5f51](https://kusama.subscan.io/extrinsic/0x558edac21b935fa320dab3e0ffc147fb5be407aeadad3387e75776bc5f6f5f51)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
