### PR TITLE
Nuxt Speed kit test

### PR DESCRIPTION
**Pull request by yangwao**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Related #5031

### <samp>🤖 Generated by Copilot at 454f382</samp>

Added `nuxt-speedkit` module to optimize website performance. This is part of a pull request that improves the loading speed and user experience of the NFT gallery website.

### <samp>🤖 Generated by Copilot at 454f382</samp>

> _`nuxt-speedkit` added_
> _to boost Nuxt gallery site_
> _winter wind is swift_

### CODE REVIEW

**Comment by yangwao** [comment]
On mobile, it doesn't seem to have an impact, yet on desktop, it does improves 10 points on average. 

Current canary
image
vs this PR
image

We can tune settings later.

**Comment by yangwao** [comment]
Has impact on other metrics

Canary
-
image
This PR
-
image

**Comment by yangwao** [comment]
> deploy failed

reseted cache on netlify, strange, it's happence once a while but not often, I sense something will explode soon lol

**Comment by prury** [comment]
> > deploy failed
> 
> reseted cache on netlify, strange, it's happence once a while but not often, I sense something will explode soon lol

minimalist koda version: 

image

**Comment by yangwao** [comment]
> minimalist koda version:

this one has worked https://6537c9f104be790008ad5a84--koda-canary.netlify.app/ that means zero config is it for now, let's see

**Comment by yangwao** [comment]
I sense something is wrong with Netlify or Nuxt3.8 it's failing builds *randomly*, same error different lines mm, well at least worked initially.

- https://app.netlify.com/sites/koda-canary/deploys/6537d56a15bb58006ff50626#L225
- https://app.netlify.com/sites/koda-canary/deploys/6537d50d3f9aee00085cb912#L63

**Comment by yangwao** [comment]
> image
> vs this PR
> image

This seems completely random, then, as nuxt-speedkit was never loaded by config.

Continue to
- https://github.com/kodadot/nft-gallery/pull/7806

**Pull request closed without merging**
