### PR TITLE
fix(search): price is missing on search suggestion

### LINKED ISSUE #3987: search suggestion w/o price
[here's first nft](https://beta.kodadot.xyz/rmrk/gallery/12937186-5A37C441DF4354913E-KSMNDL-KUSAMANDALA_4-0000000000000003), clearly listed with price (happening on /snek as well):
image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3987
- [x] fix: missing price & extra scroll bar

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Review by petersopko — CHANGES_REQUESTED** [review]
snek?

**Comment by petersopko** [comment]
@Jarsen136 doesn't work on snek yet?
image

**Comment by Jarsen136** [comment]
> @Jarsen136 doesn't work on snek yet? 


Could you pls refresh your page and try again ? Seem WFM
image

**Review by roiLeo — COMMENTED** [review]
on my side something weird: 

Screenshot 2022-09-21 at 12-48-49 KodaDot - Kusama NFT Market Explorer

**Comment by petersopko** [comment]
> Seem WFM

well it didn't show up for me at all previously, and there's `Unit` in your screenshot

**Comment by Jarsen136** [comment]
will check later

**Comment by Jarsen136** [comment]
✅  Fixed incorrect unit

image

image

**Review by roiLeo — APPROVED** [review]
✅ lgtm

**Review by petersopko — APPROVED** [review]
wfm

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 42.32 USD/KSM ~ 1.181 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xa8dc045917768ac6ac4b1164bafca9477a4e27df21a368a3514866f78e579ae3](https://kusama.subscan.io/extrinsic/0xa8dc045917768ac6ac4b1164bafca9477a4e27df21a368a3514866f78e579ae3)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
