### PR TITLE
feat: Mental shift from gen art tag to normal png tag

### LINKED ISSUE #10449: Mental shift from gen art tag to normal png tag
Since most of the content is generative now, let's change the tags a bit 

image

- normal jpg and non-generative images will get a picture tag - generative art won't have the tag now 
- ignore the card design, using the one that was there 
- its a image icon from font awesome 
- 24px x 24px box, rounded corners

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Feature

## Needs Design check

- @exezbcz please review

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #10449

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by exezbcz** [comment]
image

**Comment by Jarsen136** [comment]
> image

Fixed, thanks

**Comment by prury** [comment]
it is showing the symbol while is loading, and then it disappears: 
image
image

**Comment by prury** [comment]
base genart being labeled as non-genart: 

image
https://deploy-preview-10455--koda-canary.netlify.app/base/collection/0x2cc76e51c4ae3ed7b0dcada34c1ea4fe059d5881

**Comment by Jarsen136** [comment]
> it is showing the symbol while is loading, and then it disappears:  could be because of loading slowness on my end

✅ Updated. I found a hack to fix it.

**Comment by Jarsen136** [comment]
> base genart being labeled as non-genart:
> 
> image https://deploy-preview-10455--koda-canary.netlify.app/base/collection/0x2cc76e51c4ae3ed7b0dcada34c1ea4fe059d5881


Even though on the canary env, the nfts are not identified as special tag. On Base network, they are all static images, not animations 

https://canary.kodadot.xyz/base/collection/0x2cc76e51c4ae3ed7b0dcada34c1ea4fe059d5881
image

**Comment by prury** [comment]
found some that are not showing the icon, can you check if the same happens for you?


https://deploy-preview-10455--koda-canary.netlify.app/ahp/collection/80
https://deploy-preview-10455--koda-canary.netlify.app/ahp/collection/129

in this one some load the icon and some not:
https://deploy-preview-10455--koda-canary.netlify.app/ahp/collection/78

**Comment by Jarsen136** [comment]
> found some that are not showing the icon, can you check if the same happens for you?
> 
> https://deploy-preview-10455--koda-canary.netlify.app/ahp/collection/80 https://deploy-preview-10455--koda-canary.netlify.app/ahp/collection/129
> 
> in this one some load the icon and some not: https://deploy-preview-10455--koda-canary.netlify.app/ahp/collection/78
> 
> i believe kodachain collections were showing the icon before and are not showing anymore

✅ Updated. They should be fixed.

**Comment by prury** [comment]
@exezbcz should we show the jpeg icon on audio and video as well?

**Comment by exezbcz** [comment]
> @exezbcz should we show the jpeg icon on audio and video as well?
> 
> [deploy-preview-10455--koda-canary.netlify.app/ahp/collection/1](https://deploy-preview-10455--koda-canary.netlify.app/ahp/collection/1)

edge case, could be

**Comment by prury** [comment]
> > @exezbcz should we show the jpeg icon on audio and video as well?
> > [deploy-preview-10455--koda-canary.netlify.app/ahp/collection/1](https://deploy-preview-10455--koda-canary.netlify.app/ahp/collection/1)
> 
> edge case, could be

@Jarsen136

**Comment by Jarsen136** [comment]
> > > @exezbcz should we show the jpeg icon on audio and video as well?
> > > [deploy-preview-10455--koda-canary.netlify.app/ahp/collection/1](https://deploy-preview-10455--koda-canary.netlify.app/ahp/collection/1)
> > 
> > 
> > edge case, could be
> 
> @Jarsen136

image

It does show the icon after a while.

**Review by preschian — APPROVED** [review]

**Comment by vikiival** [comment]
cc @hassnian

**Review by hassnian — APPROVED** [review]

**Pull request merged**
