### PR TITLE
feat(2223): passion feed for stats

### LINKED ISSUE #2223: Passion feed for spotlight & series
This switch will be added to spotlight and series 

- Add new resolver to https://github.com/kodadot/rubick 
- add a switch to show passion <> all 
- query
-- where a collector is a current owner but not the issuer
-- all nfts where the issuer is in the array from list 1

### Ref
- query could be find in previous issue
- #2222 
- https://github.com/kodadot/rubick/issues/27

### PR DESCRIPTION
**Pull request by KngZhi**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2223
- [ ] Requires deployment <rubick/magick_issue>

- feat: spotlight passion query
- feat: passion switch for spotlight
- refactor: remove unused code and add i18
- feat: passion list mixin
- feat: add passionListMixin
- feat: passion filter on series

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer?target=DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by KngZhi** [comment]
rely on https://github.com/kodadot/rubick/pull/92

**Comment by KngZhi** [comment]
🤣 lucky day. but can we wait for a moment.

**Comment by KngZhi** [comment]
> You have good day today 🦑 Releasing the Squid at [kodadot/rubick@91f590d](https://github.com/kodadot/rubick/commit/91f590dde7e892b9f756224899d70c680a444bd1)

I need to add a field for series resolver `emoteCount`

**Comment by vikiival** [comment]
there is already emote count :D 
https://github.com/kodadot/rubick/blob/68f8d6ee648bb1e1562fce9a1a4c90f5b3f39363/src/mappings/utils/cache.ts

**Comment by KngZhi** [comment]
> there is already emote count :D https://github.com/kodadot/rubick/blob/68f8d6ee648bb1e1562fce9a1a4c90f5b3f39363/src/mappings/utils/cache.ts

for resolver, not cache. I will submit it now. I will not use the `series` but `seriesInsightTable` query for data-range feature. 😄

**Review by prachi00 — APPROVED** [review]

**Comment by prachi00** [comment]
LGTM

**Comment by vikiival** [comment]
>  final testing on this one and when you click on the passion feed toggle, the api is giving error

Looks like bad query

**Comment by KngZhi** [comment]
cause `ids` is empty arrary.

**Comment by prachi00** [comment]
LGTM

**Comment by prachi00** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 52.86 USD/KSM ~ 1.892 $KSM
🧗 [DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc](https://kusama.subscan.io/account/DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc)
🔗 [0x98f5c1f8b4a31a2e601caf207648abf00d3e06de25e8a3fda0d4456391d27f19](https://kusama.subscan.io/extrinsic/0x98f5c1f8b4a31a2e601caf207648abf00d3e06de25e8a3fda0d4456391d27f19)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
