### PR TITLE
adjust renovate config

### LINKED ISSUE #2617: Make Renovate to prefer major version (v16)
> btw, how about using a major version (`v16`) instead of a specific patch version (`v16.14.2`)?
> 
> * [https://github.com/kodadot/nft-gallery/blob/main/package.json#L46](https://github.com/kodadot/nft-gallery/blob/main/package.json?rgh-link-date=2022-03-21T08%3A21%3A49Z#L46)
> * [https://github.com/kodadot/nft-gallery/blob/main/Dockerfile#L2](https://github.com/kodadot/nft-gallery/blob/main/Dockerfile?rgh-link-date=2022-03-21T08%3A21%3A49Z#L2)
> * [https://github.com/kodadot/nft-gallery/blob/main/.github/workflows/build.yml#L17](https://github.com/kodadot/nft-gallery/blob/main/.github/workflows/build.yml?rgh-link-date=2022-03-21T08%3A21%3A49Z#L17)
> * [https://github.com/kodadot/nft-gallery/blob/main/.github/workflows/reviewdog.yml#L17](https://github.com/kodadot/nft-gallery/blob/main/.github/workflows/reviewdog.yml?rgh-link-date=2022-03-21T08%3A21%3A49Z#L17)

I guess so would be nice, yet renovate has updating it whenever new version or security version node is out to particular version, let's give it a shot if you can find in renovate docs to opt out from bumping nodejs version as it's send immortal PRs :)
Making this as extra issue

### Ref 
- https://github.com/kodadot/nft-gallery/issues/2340

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/2611#issuecomment-1073693610_

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #2617 

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged the recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by preschian** [comment]
need to merge it to `main` to see the result

before
- ❌ [[skip netlify] Update Node.js to v17](https://github.com/preschian/nft-gallery/pull/4)
- ❌ [[skip netlify] Update dependency css-loader to v6](https://github.com/preschian/nft-gallery/pull/5)
- ❌ [[skip netlify] Update dependency mingo to v6](https://github.com/preschian/nft-gallery/pull/6)
- ❌ [[skip netlify] Update Bumped minor version of packages (major)](https://github.com/preschian/nft-gallery/pull/8)

after
- ✅ clean https://github.com/preschian/nft-gallery/issues/7

**Comment by yangwao** [comment]
checking, but this will stop updating major version of other packages? hmm

**Comment by yangwao** [comment]
let's resolve conflicts and let's merge it tho, we will experiment with this :)

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 167.8 USD/KSM ~ 0.596 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0x7a6ff9c776012c1047a010d3f786ee9eedfa6cb3831d5d6d49d8c17c31628da5](https://kusama.subscan.io/extrinsic/0x7a6ff9c776012c1047a010d3f786ee9eedfa6cb3831d5d6d49d8c17c31628da5)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
