### PR TITLE
feat: drops geolocation

### LINKED ISSUE #9460: Geolocation for generative drops
team will have a generative drop at ethdenver
- for that we need some sort of geofencing 

rel: 
- https://github.com/kodadot/private-workers/issues/65

here is the design, simple and efficient 

# Design
- updated in drop page handoff: https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=394-6126&mode=design&t=YFX0SiJFdq4k18Qr-11
- it consists of one modal and one requirement row in requirement section

## modal
image

- when you click the main cta button, a popup from a chrome/other browser is displayed
- if you cancel it - for example on desktop, it will show the error message
- if you accept, it will then let you go to the drop page (it will also let you when you just click the x-mark icon on the modal to close)

## Requirements
1) here it will be based on whether you agreed and you are in Denver, or not
2) or you closed it/blocked

ad 1 
image

ad2 
image
- when clicking the blue link, browser popup is displayed, no modal 

### note
putting this one to intern as its required to have access to private workers probably

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #9460
- [x] Requires deployment https://github.com/kodadot/private-workers/pull/78

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)

## Screenshot 📸

- [x] My fix has changed UI

Please note multiple cities are for testing purposes only **(Denver, Jakarta)**

image

image

### CODE REVIEW

**Comment by yangwao** [comment]
Can we test?

**Comment by preschian** [comment]
> Can we test?

sure, let me merge PR (and deploy) on private-workers first

**Comment by preschian** [comment]
@yangwao @prury ready to test, lmk if you need to change the location

image

**Comment by yangwao** [comment]
First ok I guess
image

Second probably not as I'm in Denver and I see where is issue
image

when I'm at - https://whatismyipaddress.com/ip/63.149.110.243 
image

it shows 
image

**Comment by preschian** [comment]
@yangwao, what do you get if you visit this one: https://geolocation.kodadot.workers.dev/. We can use the value from that

**Review by daiagi — APPROVED** [review]
Code lgtm

**Review by Jarsen136 — APPROVED** [review]

**Comment by yangwao** [comment]
I think region Colorado should be good? 

> We can use the value from that

```
Geolocation: Hello World!
You now have access to geolocation data about where your user is visiting from.

Colo: DFW

Country: US

City: Dillon

Continent: NA

Latitude: 39.59150

Longitude: -105.97860

PostalCode: 80435

MetroCode: 751

Region: Colorado

RegionCode: CO

Timezone: America/Denver
```

**Comment by preschian** [comment]
> I think region Colorado should be good?

updated

image

**Comment by prury** [comment]
using vpn: 

image

@preschian i'm getting the error below on this PR when trying to mint, can you verify?

image

**Comment by prury** [comment]
@yangwao 
i know you are busy, but i ran out of KSM on Assethub on the testing account
would exchange with my personal account but i also ran out of assethub ksm there
address: CmWHiv7h4m9tEzKD94DH4mqwGTvsdYQe2nouWPF7ipmHpqA

i need this to test this PR and others

**Comment by prury** [comment]
yup got this error again:

image

also: 

image

**Comment by preschian** [comment]
> yup got this error again:
> 
> 
> 
> image
> 
> 
> 
> also: 
> 
> 
> 
> image
> 
> 

Could you compare it with canary? I think both of them are unrelated to the PR

sent the link for the image error. It can be safe to ignore if the image tag tries to load a non-image link (such as html/video)

**Comment by preschian** [comment]
@prury Oh, maybe the PR is not synced with the updated `main` branch. updated now

**Comment by prury** [comment]
> @prury Oh, maybe the PR is not synced with the updated `main` branch. updated now

all solved now ty

**Review by vikiival — APPROVED** [review]
LGTM

**Comment by yangwao** [comment]
Thanks!
pay 80 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $80 @ 8.34 USD/DOT ~ 9.592 $DOT
🧗 [1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p](https://polkadot.subscan.io/account/1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)
🔗 [0xb8c9df67541f0306205ee1abb40a153326484088763323be82adb68a2730c0c7](https://polkadot.subscan.io/extrinsic/0xb8c9df67541f0306205ee1abb40a153326484088763323be82adb68a2730c0c7)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
