### PR TITLE
Add Rococo Basilisk & Basilisk explorer

### LINKED ISSUE #3655: Add Rococo Basilisk explorer
There is Basilisk Rococo explorer.

Add it to history components transactions. 

https://calamar.play.hydration.cloud/extrinsic/0000542017-000001-7647c

Once it's deployed and done issues below
- #3512 
- #3511

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3655
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

image

### CODE REVIEW

**Comment by Jarsen136** [comment]
This PR is blocked. related to https://github.com/kodadot/nft-gallery/issues/3671

**Comment by yangwao** [comment]
Made transactions https://github.com/kodadot/nft-gallery/pull/3784#issuecomment-1230212345

https://calamar.play.hydration.cloud/rococo%20basilisk/extrinsic/0000715279-000002-98663

**Comment by petersopko** [comment]
hmm, still can't see the explorer at /transfers, we've hidden it here so perhaps some things need to be tweaked? 
- https://github.com/kodadot/nft-gallery/pull/3406

**Comment by Jarsen136** [comment]
> hmm, still can't see the explorer at /transfers, we've hidden it here so perhaps some things need to be tweaked?

Hey, I'm not sure what you mean. Even though I'm at RMRK, I still could not see any explorer at `/transfers`.

image

In this PR, I added the explorer link for basilisk in the History component.

image

**Comment by petersopko** [comment]
> Hey, I'm not sure what you mean. Even though I'm at RMRK, I still could not see any explorer at `/transfers`.

if you punch in address at rmrk, there's link generated to the profile at subscan
image

**Comment by Jarsen136** [comment]
> > Hey, I'm not sure what you mean. Even though I'm at RMRK, I still could not see any explorer at `/transfers`.
> 
> if you punch in address at rmrk, there's link generated to the profile at subscan 

✅ Done

image

**Comment by petersopko** [comment]
nice, wfm :)

**Comment by petersopko** [comment]
@kkukelka can review the code now and we have explorer back :)

**Review by petersopko — APPROVED** [review]
✅

**Review by kkukelka — APPROVED** [review]
code lgtm, just 1 question: whats with the `#` as return value in some cases?

**Comment by kkukelka** [comment]
pay 100

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 46.63 USD/KSM ~ 2.145 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x897bccb0fb9365894205be9b45cfa9ffda803b80161f20598cdf12e02a9c0e50](https://kusama.subscan.io/extrinsic/0x897bccb0fb9365894205be9b45cfa9ffda803b80161f20598cdf12e02a9c0e50)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by Jarsen136** [comment]
> just 1 question: whats with the `#` as return value in some cases?

It would not happen because the element would only render when it has block explorer.

`v-if="$route.query.target && hasBlockExplorer"`

**Pull request merged**
