### PR TITLE
feat(SearchBar): Categorize search results in search bar

### LINKED ISSUE #2376: Categorize search results in search bar
I guess it's time to show collections name match first and items as last.

Once we will have Search for artists as well, we can add it showing users as well

Probably add button on bottom [All Results]

Inspiration from Rarible
image

### PR DESCRIPTION
**Pull request by zhengow**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2376 
- [x] Categorize search results in search bar

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

https://user-images.githubusercontent.com/38389586/155739763-b35b3cc0-50e1-4dd2-9a39-e1c79a4e88d8.mp4

### CODE REVIEW

**Comment by yangwao** [comment]
Let's put collections first as people look for them more often, items later. 
I will test once done :)

**Comment by zhengow** [comment]
> Let's put collections first as people look for them more often, items later. I will test once done :)

How about "History" and "Search"? 
Do we still need them?
image

**Comment by yangwao** [comment]
> > Let's put collections first as people look for them more often, items later. I will test once done :)
> 
> How about "History" and "Search"? 
> Do we still need them?
> image
> 

Good q. History should be kept but history searching 🔎 term is already in upper row. So it could be removed :)

Will check once I'm around on 💻

**Comment by zhengow** [comment]
> 

done~

**Comment by yangwao** [comment]
works!

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 133.02 USD/KSM ~ 0.752 $KSM
🧗 [EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws](https://kusama.subscan.io/account/EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)
🔗 [0xee44b6ba3efc3ed8d09e42e72ac7eab636b1c30147cd2e9ecc4a734ddcf40a21](https://kusama.subscan.io/extrinsic/0xee44b6ba3efc3ed8d09e42e72ac7eab636b1c30147cd2e9ecc4a734ddcf40a21)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
