### PR TITLE
refactor: remove `IDB` on carousel

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] related with https://github.com/kodadot/nft-gallery/issues/4744. remove idb on carousel

### CODE REVIEW

**Review by Jarsen136 — APPROVED** [review]
code lgtm

**Review by roiLeo — APPROVED** [review]
Since you're removing idb cache on carousel, are we going to experience some loading (Time) issue from user perspective ? Otherwise wfm

**Comment by vikiival** [comment]
> Since you're removing idb cache on carousel, are we going to experience some loading (Time) issue from user perspective ? Otherwise wfm



From what @preschian claimed, it will be now managed by service worker

**Review by vikiival — CHANGES_REQUESTED** [review]
Please clarify the loading times. 

OTHERWISE LGTM

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
Let it roll. 
It thought that I merged it🙈

**Pull request merged**
