### PR TITLE
fix: Collection Gallery Image low quality

### LINKED ISSUE #7141: Collection Gallery Image low quality
### What happened?

The collection image is low res and looks bad
Bildschirmfoto 2023-09-04 um 17 18 21
photo_2023-09-04_17-29-51

https://kodadot.xyz/ahk/collection/110

and other collections too. I am on a retina mac and to my knowledge to be sharp the image would need a 2x height = 1120px for a displayed height of 560px

@preschian 

### Please reproduce in steps

see above

### Expected Behavior

sharp images

### What browsers are you seeing the problem on?

Chrome, Firefox, Safari

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### Screenshots

see above

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/ksm/transfer/?target=DT7kRjGFvRKxGSx5CPUCA1pazj6gzJ6Db11xmkX4yYSNK7m

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix

  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #7141
  - [ ] Requires deployment <snek/rubick/worker>

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

image

  ## Copilot Summary
  
### <samp>🤖 Generated by Copilot at e6290d3</samp>

Added custom banner images for collections. Updated `collection-banner` component to use `toOriginalContentUrl` function for IPFS images.

  
### <samp>🤖 Generated by Copilot at e6290d3</samp>

> _Sing, O Muse, of the skillful coder who devised_
> _A wondrous feature for the `collection-banner` component,_
> _That it might display the glorious images of collections_
> _Fetched from the IPFS hash by the `toOriginalContentUrl` function._

### CODE REVIEW

**Comment by prury** [comment]
much better now (video compression doesn't do justice ofc 😄 ) 

https://github.com/kodadot/nft-gallery/assets/36627808/8099140f-7cc6-492a-a39d-85d5d46c7118

**Review by stephenjason89 — APPROVED** [review]
Code lgtm

**Review by preschian — APPROVED** [review]

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 4.25 USD/DOT ~ 7.059 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x56c408b4cf6a4f5c050496b93dd3b6cb9fed0a3f13ac0521cc4fd791e4ac2ff7](https://polkadot.subscan.io/extrinsic/0x56c408b4cf6a4f5c050496b93dd3b6cb9fed0a3f13ac0521cc4fd791e4ac2ff7)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
