### PR TITLE
Fixed slider borders

### LINKED ISSUE #8139: Progress indicator
sorry guys 
image
image
image

not prio, p4

### PR DESCRIPTION
**Pull request by shashkovdanil**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #8139 
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [x] I've tested it at </ksm/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer?target=16SpvdDgKNiQ3c53DxX7refnQcKUD3uRNim3Z1HBJLNGrtSP&usdamount=0)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screenshot 2023-11-19 at 12 30 54

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 41568a9</samp>

Refactored and styled the `unlockable-slider` component to make it more responsive and consistent with the design.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 41568a9</samp>

> _To make the `unlockable-slider` look better_
> _The coder removed some classes and a letter_
> _They enhanced a computed prop_
> _And tweaked some CSS on top_
> _And now the component is a go-getter_

### CODE REVIEW

**Comment by exezbcz** [comment]
small thing when its still progressing
image
- its not 1px stroke all around the pink lin

**Comment by shashkovdanil** [comment]
@exezbcz fixed

**Comment by exezbcz** [comment]
perfect

**Review by exezbcz — APPROVED** [review]

**Review by roiLeo — APPROVED** [review]

**Review by preschian — APPROVED** [review]

**Comment by yangwao** [comment]
thanks!
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 5.14 USD/DOT ~ 3.891 $DOT
🧗 [16SpvdDgKNiQ3c53DxX7refnQcKUD3uRNim3Z1HBJLNGrtSP](https://polkadot.subscan.io/account/16SpvdDgKNiQ3c53DxX7refnQcKUD3uRNim3Z1HBJLNGrtSP)
🔗 [0x8fde4da0e97bc17032d16745c6420059292d10ea0d5cfff07bae6d6c21bde05d](https://polkadot.subscan.io/extrinsic/0x8fde4da0e97bc17032d16745c6420059292d10ea0d5cfff07bae6d6c21bde05d)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
