### PR TITLE
fix: Video thumbnail in activity preview

### LINKED ISSUE #6310: Video thumbnail in activity preview
image
https://canary.kodadot.xyz/ksm/collection/22ce51e9b0f7260f62-POLKADOTHUBMX/activity
- its a video, but it's not showing the thumbnail of it. Would it be possible to take frame 1 maybe and use it as a preview? If not, we can use a placeholder. The main is to maintain the square preview everywhere.

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Needs Design check

- @exezbcz please review

## Context

- [x] Closes #6310
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed UI

image

### <samp>🤖 Generated by Copilot at a16a726</samp>

Improved image loading and error handling in collection components. Replaced `` tags with `<BasicImage>` component in `Flipper.vue` and `Holder.vue` to reduce code duplication and ensure consistent behavior.

### <samp>🤖 Generated by Copilot at a16a726</samp>

> _`BasicImage` helps_
> _load and handle NFTs well_
> _in the `Holder` - spring_

### CODE REVIEW

**Comment by exezbcz** [comment]
Just to be sure, this was not affected by the pr, no? 
image
- other previews are not keeping the square preview style
- if not, I will create a separate issue

Otherwise good, thanks!

**Comment by Jarsen136** [comment]
> Just to be sure, this was not affected by the pr, no? image
> 

Yes, I will fix it.

**Comment by prury** [comment]
- RMRK2(working): 
image

- BSX(working, with image preview):
image

- Statemine (to be tested)
waiting for: #6229

**Review by roiLeo — APPROVED** [review]
✅ code lgtm

**Review by daiagi — APPROVED** [review]

**Review by vikiival — APPROVED** [review]

**Pull request merged**
