### PR TITLE
ref: Deprecate and remove create

### LINKED ISSUE #10427: Deprecate and remove create
Time has come

# What
removing create as in: 
- https://github.com/kodadot/nft-gallery/issues/10390

-> not our product, our scope is gen art, not single nfts - we will introduce minter for generative drops

for now, there will be a placeholder page that will redirect traffic if anyone accidentally enters the page

# Task
- remove nft minter
- remove ai minter
- remove collection minter
- remove navbar link
- move navbar link to footer 
- add placeholder page
- save the code somewhere if we need it (really small probability) 

# Placeholder page
design updated here: https://www.figma.com/design/JXNtryaNYhY0XJNArzvPQx/Handoff?node-id=1287-18959&t=Dt9j4HyS2vIGJGpV-11

image

- super simple, just text and links
- form redirects here: https://form.kodadot.xyz/drop-interest
- documentation here: https://hello.kodadot.xyz/generative/generative-art

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

A lot of code got removed, went through each function/component/translation  that was removed one by one,I would appreciate if reviewers could also test if everything feels right, tyvm  

### Removed
- `/create/collection` and `/create/nft` 
- `/ahk/waifu` waifu minter
- `/prefix/massmint`
- `add nfts`from collection page
-  unused carbon offset from preferences
- all unused translations related to create  

### Added 

- redirect old create pages (/prefix/create, /ahk/waifu, /prefix/massmint, etc) to placeholder `/create`
- test regarding new redirects

- [x] Closes #10427

## Needs QA check

- @kodadot/qa-guild please review

## Needs Design check

- @exezbcz please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2024-06-28 at 10 02 32@2x

### CODE REVIEW

**Comment by prury** [comment]
i'm changing tests to match PR

**Comment by exezbcz** [comment]
nice 
image

**Comment by vikiival** [comment]
Amazing pls @kodadot/internal-dev for review

**Review by preschian — APPROVED** [review]

**Comment by vikiival** [comment]
> /create/collection and /create/nft

This

**Comment by vikiival** [comment]
> /prefix/massmint
> add nftsfrom collection page

This

**Pull request merged**
