### PR TITLE
fix: cant mint if I dont want to put NFT on sale

### LINKED ISSUE #3532: can't mint if I don't want to put NFT on sale?
Can't mint if I don't want to put NFT on sale? 
The balance should be there, as you see.

image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3532
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Review by kkukelka — APPROVED** [review]

**Comment by yangwao** [comment]
wfm 

pay 50 usd 

image

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 68.31 USD/KSM ~ 0.732 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xcd19a98d8781ae91a0c944eb8de575c3725742ea299fa00e560888d6df1593ec](https://kusama.subscan.io/extrinsic/0xcd19a98d8781ae91a0c944eb8de575c3725742ea299fa00e560888d6df1593ec)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
wait, but doesn't builds? 

```
sh: 1: husky: Permission denied
 ELIFECYCLE  Command failed with exit code 126.
Error: Process completed with exit code 1.
```

**Comment by Jarsen136** [comment]
> wait, but doesn't builds?
> 
> ```
> sh: 1: husky: Permission denied
>  ELIFECYCLE  Command failed with exit code 126.
> Error: Process completed with exit code 1.
> ```

Oh, seem many PR has this problem at the same time.

**Comment by Jarsen136** [comment]
image

**Review by petersopko — APPROVED** [review]

**Pull request merged**
