### PR TITLE
🔧 ExploreGrid NeoField mb-0

### LINKED ISSUE #6179: Explore buttons alignement
Screenshot 2023-06-07 at 08-49-00 Low minting fees and carbonless NFTs KodaDot - NFT Market Explorer

### LINKED ISSUE #6181: pnpm build errors
Capture d’écran 2023-06-07 à 9 31 00 AM

### PR DESCRIPTION
**Pull request by roiLeo**
Just fyi `<NeoField />` component has margin-bottom by default

- [x] closes #6179 
- [x] closes #6181 

Screenshot 2023-06-07 at 09-20-15 Low minting fees and carbonless NFTs KodaDot - NFT Market Explorer

### CODE REVIEW

**Comment by preschian** [comment]
@roiLeo try to install it with pnpm@8.6.0? https://github.com/kodadot/nft-gallery/blob/main/package.json#L62

**Comment by roiLeo** [comment]
> @roiLeo try to install it with pnpm@8.6.0? https://github.com/kodadot/nft-gallery/blob/main/package.json#L62

build with pnpm 8.6.1, with 8.5 I can't run it..

still have uncommit changes

**Review by preschian — APPROVED** [review]

**Comment by preschian** [comment]
> build with pnpm 8.6.1, with 8.5 I can't run it..

they revert it again on pnpm 8.6.2 😅😅😅 cc @roiLeo 
https://github.com/pnpm/pnpm/issues/6648

**Comment by roiLeo** [comment]
🙄 
which is why I don't update my package manager often

**Pull request merged**
