### PR TITLE
feat: More cards on mobile carousels 

### LINKED ISSUE #9094: More cards on mobile carousels
image

afaik, we had smaller cards on mobiles - it was the mobile cards (without the collection and network )

these one: 
image

can we have it back?

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #9094

## Needs Design check

- @exezbcz please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2024-01-25 at 12 30 23

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
any way to do it without passing `minimal` prop?

**Comment by hassnian** [comment]
> any way to do it without passing `minimal` prop?

without a prop called `minimal` ?
maybe what `nftcard`does with a prop `variant`   'primary'| 'minimal' 

or using a slot?

**Comment by exezbcz** [comment]
there should not even be the network IMO 

image
- this is the card from explore


in old explorer v0.9 figma file its without 


image


- its not that important on mobile to see what network is it

**Comment by preschian** [comment]
> > any way to do it without passing `minimal` prop?
> 
> without a prop called `minimal` ? maybe what `nftcard`does with a prop `variant` 'primary'| 'minimal'
> 
> or using a slot?

Use `$device.isMobile`? so we can drop the prop

**Comment by exezbcz** [comment]
loooks okay! 
image

**Review by preschian — APPROVED** [review]
lgtm. It can be a follow-up issue for the CSS helper (`isMobile`). Related:
- https://github.com/kodadot/nft-gallery/issues/8767
- https://github.com/kodadot/nft-gallery/issues/8489

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 6.7 USD/DOT ~ 4.478 $DOT
🧗 [16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD](https://polkadot.subscan.io/account/16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)
🔗 [0xadfa9894c3cea2836c87bdc902457bea0dac6630970396083d9657551af21880](https://polkadot.subscan.io/extrinsic/0xadfa9894c3cea2836c87bdc902457bea0dac6630970396083d9657551af21880)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
