### PR TITLE
feat: btn fill up address

### LINKED ISSUE #3852: Master offers - easier address fill up
As @prachi00 mentioned in the comment on the bottom, current implementation of master offers results in some edge cases which I'd like to see handled in better way.

Continuing from:
- #3463

1. if user without connected wallet visits `/bsx/offers` and then connects the wallet, he gets logged in but his address won't get filled up
2. refreshing the page doesn't help (check the comment) 
3. the only way to get the address prefilled automatically is to navigate there through navbar (relying on URL -> suboptimal)

One thought on how to solve this: add button which fills up address based on logged in wallet, disabled if there's no logged in wallet.

@roiLeo thoughts on this from the UX perspective?

comment from PR:
for 1 and 2, I actually depend on the url to fill out the address in the input
`/bsx/offers?target=bXjGftu3aagU6RzMCKHi66X84jap3RKtvv6t1kxD2KXbJMiG2`
because not doing this was creating a lot of edge cases for example, if you erase the input bar to view all the offers and then reload, it would show user's offers again

_Originally posted by @prachi00 in https://github.com/kodadot/nft-gallery/issues/3692#issuecomment-1221432598_

### PR DESCRIPTION
**Pull request by KngZhi**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #3852
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer?target=HgpGWWmqrw8t6viwSy6LPcTVr2SuVPKWW5ArdNp2xCJY2U4)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

https://user-images.githubusercontent.com/11361147/187481236-58ea83e4-efe1-40ff-a137-d09df309a080.mov

### CODE REVIEW

**Review by kkukelka — APPROVED** [review]
code lgtm

**Comment by kkukelka** [comment]
but still merge conflicts

**Comment by KngZhi** [comment]
> but still merge conflicts

Solved.

**Comment by petersopko** [comment]
@KngZhi awesome, wfm, just one more thing, can you please add an option to clear up the input bar as well? same as in search bar. That's the last thing, but works as expected, thank you 🙏🏻 

image

**Comment by KngZhi** [comment]
No problem, out of computer now, would finish that ASAP.

**Comment by KngZhi** [comment]
@petersopko it's updated.

**Review by petersopko — APPROVED** [review]
wfm

**Comment by petersopko** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 49.03 USD/KSM ~ 1.02 $KSM
🧗 [HgpGWWmqrw8t6viwSy6LPcTVr2SuVPKWW5ArdNp2xCJY2U4](https://kusama.subscan.io/account/HgpGWWmqrw8t6viwSy6LPcTVr2SuVPKWW5ArdNp2xCJY2U4)
🔗 [0xf046942c8baa1f4283472bc86ad694151c7d8743ed8f28390245f5a5783cd172](https://kusama.subscan.io/extrinsic/0xf046942c8baa1f4283472bc86ad694151c7d8743ed8f28390245f5a5783cd172)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
