### PR TITLE
Add vue-social-sharing plugin

### PR DESCRIPTION
**Pull request by JKrupinski**
Related to #161

My proposition is to add vue-social-sharing package. I've added `ShareNetwork` component which helps share link to a facebook.
Twitter, Telegram, Line can be added too. With this plugin you can share content without leaving kodadot page.

More details here: https://github.com/nicolasbeauvais/vue-social-sharing

You can see new facebook icon in the nft detail page
alt text

### CODE REVIEW

**Comment by yangwao** [comment]
I was thinking.. what if we could make a show in a default state with just a Twitter button and three dots?
Under three dots could expand into rest buttons?
The purpose of this would be to preserve and keep users low on brain load. 
Towards cleaner and highlighting only buttons which are more used for now :)

Dots could be, probably horizontal fit better?
https://fontawesome.com/icons/ellipsis-v?style=solid
https://fontawesome.com/icons/ellipsis-h?style=solid

**Comment by yangwao** [comment]
Oh missed the first part.

Sure, I'm up to adding vue-social-sharing.

**Comment by vikiival** [comment]
Yeah, It would be awesome to have a plugin for that

**Comment by JKrupinski** [comment]
Good idea @yangwao I think we can hide them all under `share-alt` icon

**Comment by yangwao** [comment]
I mean, I would add even embeding button and leave just copy link and share, to cut on ones brain load :)

Pic from Twitter

IMG_20210415_094215

**Pull request merged**
