### PR TITLE
fix: Optimize search to search collection

### LINKED ISSUE #6096: Optimize search to search collection with lower caps
Do we have some full-text search magic inside/over it? 

I think does not match collection name, if someone types everything lower capitals and collection has capital letter in collection name. i.e. when I search `whitehole` did not showed `Mr Whitehole` 

Are there some cache issues with workers which takes them while or? 

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/6063#issuecomment-1560895346_

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 \_\_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #6096
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

lazy loading
image

### <samp>🤖 Generated by Copilot at fc6885f</samp>

This pull request enhances the search suggestion component by adding animations, optimizing API calls, and refactoring the code. It aims to improve the user experience and the performance of the search feature.

### <samp>🤖 Generated by Copilot at fc6885f</samp>

> _The search suggestion feature was slow_
> _And the code was hard to follow_
> _But with animations and less API calls_
> _And async updates for collection stats_
> _The feature is now smooth and mellow_

### CODE REVIEW

**Review by vikiival — COMMENTED** [review]
Code looks oki 

@yangwao is main tester for this ;D

**Comment by yangwao** [comment]
image

now doesn't even show current collections, like fetching through subsquid? 

image

**Comment by yangwao** [comment]
ugh 
image

I mean at some point it goes bit faster subjectively

**Comment by Jarsen136** [comment]
> image
> 
> now doesn't even show current collections, like fetching through subsquid?
> 
> image

It's the same issue related to worker api side. https://github.com/kodadot/workers/issues/9
On canary env, its behavior is the same.
image

**Comment by Jarsen136** [comment]
> I mean at some point it goes bit faster subjectively

This PR is mainly focused on the lazy-loading of collection stats from subsquid , which would make the search faster.

**Comment by yangwao** [comment]
ah got it, we got limites bc 100M for search db, we can raise limit for D1 as we can put probably more data there and speed it up everywhere. Let me fill the form to raise limits and we can start putting probably 90% of item maybe more.

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 5.5 USD/DOT ~ 9.091 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x0a84e98717fd1b92fd26730225ed3e5fa361ef8c278799b0cb630f596e5ee91e](https://polkadot.subscan.io/extrinsic/0x0a84e98717fd1b92fd26730225ed3e5fa361ef8c278799b0cb630f596e5ee91e)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
