### PR TITLE
✨ newest listed nfts

### PR DESCRIPTION
**Pull request by roiLeo**
Responsive need some fix (mobile version) plus I've got some huge page loading issue
We could try to limit the numbers of displayed nfts, for now it's 10 (by row) 

### PR type

- [x] Bugfix
- [x] Feature

### What's new?

- [x] Newest List NFT with carrousel card list

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Screenshot

Capture d’écran 2022-02-07 à 12 03 25 PM

### CODE REVIEW

**Comment by yangwao** [comment]
I've seen it work twice, where it did not load the latest sales.. just the newest list.. and this loading only the latest sales 

image


Some network issue or endpoint hmm 

image

**Comment by yangwao** [comment]
mmm seems super rare...
 
image

lol wait seems more serious 
image

**Comment by yangwao** [comment]
okay bumped subsquid tho to airdrop some space

**Comment by roiLeo** [comment]
Don't merge this for now, something is blocking UI

**Comment by yangwao** [comment]
> Don't merge this for now, something is blocking UI

Might be errors with SubSquid?

**Comment by yangwao** [comment]
SubSquid updated instance so it might be way better now

**Pull request merged**
