### PR TITLE
chore: upgrade to nuxt 3.9

### PR DESCRIPTION
**Pull request by stephenjason89**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## Description
This PR updates our project from Nuxt 3.8 to the latest version, 3.9.0. This minor release, tagged c28ef02, includes several enhancements, performance improvements, and bug fixes.

### Highlights of Nuxt 3.9.0:

 - Vite 5 and Rollup 4 Support: Ensures compatibility with the latest releases of Vite 5 and Rollup 4. This includes a range of improvements and bug fixes. Module authors should verify the compatibility of their vite plugins with these updates.
 - Vue 3.4 Ready: The release is tested with the latest Vue 3.4 release candidate, offering new features such as debugging hydration errors in production.
 - Interactive Server Components: Introduction of an experimental feature for interactive components within Nuxt server components.
 - Automatic Server Optimisations: Enhanced server-side code handling using Vite's AST-aware 'define'.
 - Granular Loading API: A new hook-based system for <NuxtLoadingIndicator> and a useLoadingIndicator composable for better control over the loading state.
 - CallOnce Utility: A new utility for running code only once across client and server.
 - Improved Error Typing: Enhanced typing for errors returned by useAsyncData and useFetch.
Schema Performance Improvements: Minor performance improvements aimed at enhancing the initial load time of the Nuxt dev server.

### Upgrading Process

Followed the recommended upgrade process using nuxi upgrade --force. This ensures updates from other dependencies in the unjs ecosystem are also included.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [ ] Closes #<issue_number>
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer?target=13rFRPVKjJzQXVC8ZqHZv5YMmwmk4MU7z4HeYk218hEMpQXH&usdamount=100&donation=true)

#### Community participation

- [ ] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

## Copilot Summary
copilot:summary

copilot:poem

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
Why put it in devDependencies?

Cloudflare build fail
Screenshot 2023-12-29 at 22-07-00 🔧 link holder collection id by roiLeo · Pull Request #8806 · kodadot_nft-gallery

**Comment by stephenjason89** [comment]
> Why put it in devDependencies?
> 
> Cloudflare build fail Screenshot 2023-12-29 at 22-07-00 🔧 link holder collection id by roiLeo · Pull Request #8806 · kodadot_nft-gallery

It was actually automatically placed there after nuxi upgrade --force
I didn't manually change the package.json

Would you want me to move it back?

**Comment by roiLeo** [comment]
> Upon further checking, their latest stackblitz also has nuxt on the devDependencies

Ok why not, question is will it change something? will it improve something? 
we already have renovate for packages bump see #8386 which is currently blocked by oruga upgrade #8479.

if you want to tackle this issue feel free.

ps: your changes made all builds failing

**Comment by stephenjason89** [comment]
@roiLeo Thank you for checking this PR out. Here's another thread i've found where Daniel Roe answered this.
https://github.com/nuxt/nuxt/discussions/10400
image

So I have updated the package.json to just use devDependencies for nuxt and vue, since it seems like the recommended approach. 

> question is will it change something? will it improve something?

I am not really certain but I believe it won't change anything, this is what Daniel said.
image

Anyway, tests are now succeeding besides node-fetch and 2 playwright tests
image
image


Should we close this PR or resolve the issues?

**Comment by roiLeo** [comment]
continue in #8807

**Comment by roiLeo** [comment]
use `pnpm upgrade "package" --latest` next time, so we don't need to handle some obscure package build bug

**Comment by stephenjason89** [comment]
> use `pnpm upgrade "package" --latest` next time, so we don't need to handle some obscure package build bug

Will do, i just followed the recommended upgrade process using `nuxi upgrade --force`. This ensures updates from other dependencies in the unjs ecosystem are also included.

But yeah kinda breaks the node fetch.

**Pull request closed without merging**
