### PR TITLE
fix: 4958 add hover card stroke

### LINKED ISSUE #4958: Hover card stroke
image
stroke around the highest sales should be white in dark mode 

in white mode its all good

### PR DESCRIPTION
**Pull request by maderi21**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4958
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [x] I've tested it at </bsx/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=JHJGu2aWyAFBfcso8bR7ma82p15YAavyN6vQfJyWuhniNGa)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by prachi00** [comment]
@maderi21 @roiLeo @yangwao can we not merge this please, it will be fixed by #4855

**Comment by maderi21** [comment]
hello 👋 I have updated the PR to reflect the Themes changes and avoid conflicts with #4855

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
@preschian any idea why is this failing? 

Screenshot 2023-02-12 at 15 31 46

**Comment by prachi00** [comment]
@maderi21 it would still cause conflicts I think because these changes have already been done in that PR, I would rather prefer to close this one though

**Comment by vikiival** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 30.85 USD/KSM ~ 0.648 $KSM
🧗 [JHJGu2aWyAFBfcso8bR7ma82p15YAavyN6vQfJyWuhniNGa](https://kusama.subscan.io/account/JHJGu2aWyAFBfcso8bR7ma82p15YAavyN6vQfJyWuhniNGa)
🔗 [0xfc65dc5b76fb3cf3d9245ff2c38df7724c496656f7dd683dd31b49e0e748060a](https://kusama.subscan.io/extrinsic/0xfc65dc5b76fb3cf3d9245ff2c38df7724c496656f7dd683dd31b49e0e748060a)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
