### PR TITLE
🔧  make listing cart state responsive to profile page filters

### LINKED ISSUE #7322: Mass list select only what is visible on preview
image
- it's possible to select all even when you don't see them, that makes the filter useless  

image

select all - 5 items selected, only 2 visible via the filter

image

- this is when I remove the filter

- I applied the filter before clicking select all 

It would be nice to fix this, I am thinking about adding more filters to the own section for making it even easier to select all

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #7322

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)

### <samp>🤖 Generated by Copilot at 06a27e2</samp>

The pull request adds a feature to show and list unlisted NFTs owned by the user. It implements a new function in `useItemsGrid.ts` to fetch and prepare these NFTs, a new mutation in `stores/listingCart.ts` to store them, and a watcher in `ItemsGrid.vue` to trigger the function. It also integrates the listing cart store with the `ProfileDetail.vue` component and removes redundant code from `ItemsGridImage.vue`.

### <samp>🤖 Generated by Copilot at 06a27e2</samp>

> _`ItemsGrid` shows_
> _unlisted NFTs to list_
> _autumn harvest time_

### CODE REVIEW

**Comment by prury** [comment]
Scrolling makes you lose the selection

https://github.com/kodadot/nft-gallery/assets/36627808/cca96bb1-ecce-4dff-846d-c6c5f4105791

**Comment by daiagi** [comment]
@prury
scroll issue fixed

**Review by roiLeo — APPROVED** [review]

**Comment by yangwao** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 4.04 USD/DOT ~ 4.95 $DOT
🧗 [1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8](https://polkadot.subscan.io/account/1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)
🔗 [0x84ca64d1a6df49b8815b95b9bbbd38d6f8bda1aac765e981476a423f65849d5a](https://polkadot.subscan.io/extrinsic/0x84ca64d1a6df49b8815b95b9bbbd38d6f8bda1aac765e981476a423f65849d5a)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
