### PR TITLE
#5560 update footer links

### LINKED ISSUE #5560: Footer changes
image- we are going to reorganize the footer so it makes more sense and we can have more links 

- this issue is only initial structure, some links are going to be removed/added

- the footer will keep its links, 2 more are added: 
       - merch shop - it is curently in the icons - we would like to make it more visible 
       - artist ambassador: https://docs.kodadot.xyz/artist-ambassador.html#conditions-%F0%9F%94%8D
 
image

- visual stays the same

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Closes #5560
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screen Shot 2023-04-08 at 5 51 09 PM

### CODE REVIEW

**Review by daiagi — APPROVED** [review]

**Comment by exezbcz** [comment]
and what about the other section? :D 
image

**Comment by prachi00** [comment]
> 

oh, done :D
Screen Shot 2023-04-09 at 5 52 50 PM

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
pay 10 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $10 @ 32.83 USD/KSM ~ 0.305 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x6f3ae8693cfbbc4d1c9575cdca351da176f98a1069a4e03421dfb76ad5ee140f](https://kusama.subscan.io/extrinsic/0x6f3ae8693cfbbc4d1c9575cdca351da176f98a1069a4e03421dfb76ad5ee140f)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
