### PR TITLE
fix: Supply has been set but shows unlimited on collection page

### LINKED ISSUE #8391: Set collection max supply via separate call
### What happened?

@prury found out in - https://github.com/kodadot/nft-gallery/pull/8389

> @roiLeo made a collection with limited supply and it still shows unlimited:

> https://deploy-preview-8389--koda-canary.netlify.app/ahk/collection/289

This is caused by a bug in Polkadot SDK - https://github.com/paritytech/polkadot-sdk/issues/2293

and therefore we cannot pick it up in the indexer yet - https://github.com/kodadot/stick/issues/147

### Please reproduce in steps

1. Create a collection on ah*
2. Set max supply to any arbitrary number (1000)
3. UI will not pick the number

### Task

1. remove the max from `create()` call
2. if `max` is set append new call to the batch `api.tx.nfts.setCollectionMaxSupply(id, max)`
3. Enjoy

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #8909: Supply has been set but shows unlimited on collection page
Supply has been set to 50: 
image

Collecion:
https://canary.kodadot.xyz/ahp/collection/72

works after manually set via collection page

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Needs QA check

- @prury  please review

## Context

- [x] Closes #8909
- [x] Closes #8391 

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI;

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
code lgtm

**Comment by prury** [comment]
https://deploy-preview-8919--koda-canary.netlify.app/ahp/collection/75

image

**Review by preschian — APPROVED** [review]

**Review by Jarsen136 — APPROVED** [review]

**Review by Jarsen136 — APPROVED** [review]

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 7.18 USD/DOT ~ 4.178 $DOT
🧗 [13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh](https://polkadot.subscan.io/account/13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)
🔗 [0x61a7c77b36d9cbd7810e86faf0a364c80ff1cdaa8eab9c218029ffb1a4dbda13](https://polkadot.subscan.io/extrinsic/0x61a7c77b36d9cbd7810e86faf0a364c80ff1cdaa8eab9c218029ffb1a4dbda13)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
