### PR TITLE
#2031 Carefully remove unused components

### LINKED ISSUE #2031: Carefully remove unused components
https://www.npmjs.com/package/vue-unused-components-checker

I've ran 
```
npx check-unused-comp .
```

but seems some components we are using, probably doesn't handle nuxt well? Are we using all from pages and well linked?

Anyway, let's check which we can drop as aren't used anymore.
image

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Do a quick check before the merge.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #2031
- [x] these components are not being used anywhere, let me know if you think any of these should stay in the codebase 

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases

### Had issue bounty label ?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI, a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
I think `layouts/error.vue` can or is used to manage error states

**Comment by prachi00** [comment]
> I think `layouts/error.vue` can or is used to manage error states

@roiLeo I found similar in `pages/error.vue `, so I thought that was being used and `layouts/error.vue` is a duplicate?

**Comment by roiLeo** [comment]
> > I think `layouts/error.vue` can or is used to manage error states
> 
> @roiLeo I found similar in `pages/error.vue `, so I thought that was being used and `layouts/error.vue` is a duplicate?

I thin we should try to use it from layout, it seems to be a standard in the [Nuxt doc](https://nuxtjs.org/docs/concepts/views/#error-page),

**Comment by prachi00** [comment]
> Nuxt doc

okay got it, I will add this back

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 172.26 USD/KSM ~ 0.581 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x426731c07eadbb1aa6ef4ef64095d968eadee79db76458fd05f43c75fd542336](https://kusama.subscan.io/extrinsic/0x426731c07eadbb1aa6ef4ef64095d968eadee79db76458fd05f43c75fd542336)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
