### PR TITLE
#2018 Removing from landing page footer

### LINKED ISSUE #2018: Rework landing page a bit - add recent mints for sale
### Spec
- remove from footer substack, telegram, reddit (as we don't maintain them right now) Pic1
- add to footer https://docs.kodadot.xyz as Documentation 

```graphql
query lastListed {
  events(limit: 20, where:{ interaction_eq: LIST }, orderBy: blockNumber_DESC) {
    meta
    nft {
      name
      meta {
        image
      }
    }
  }
}
```

###
Being done in #2172 
- [x] add shadows to the buttons [Create,...,What Are NFTs] -- buttons are gone meanwhile
- [x] copy box Recent Sales over and add showing newest NFTs for sale in the same format
- [x] put inside the last three NFT items previews where sales have happened once the user came to the site
- [x] collection detail could be like is at gallery feed, check pt3 
- [x] in the recent sales box add the text "Recently Sold" so newcomers will know
- [x] remove CTA text from homepage__box, make it extended, add shadow there as well
- [x] remove background
- [x] clicking on NFTs will lead you to NFT item detail 

pt1
image

pt2
image

pt3
image

### Ref
- #876 bit start for this
- #1596 
- https://github.com/kodadot/nft-gallery/issues/2180

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #2018
- [x] Removing from footer substack, telegram, reddit 

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screenshot 2022-02-23 at 12 50 43 PM

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
Not related with this PR but "Documentation" & "Grant" link are not working, could you take a look?

**Comment by prachi00** [comment]
> Not related with this PR but "Documentation" & "Grant" link are not working, could you take a look?

@roiLeo have fixed this

**Review by roiLeo — APPROVED** [review]
lgtm

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 133.62 USD/KSM ~ 0.374 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x409292130455ae8a28c90cde154b1b32ea5496063fd2f3ad6a81218896c609d4](https://kusama.subscan.io/extrinsic/0x409292130455ae8a28c90cde154b1b32ea5496063fd2f3ad6a81218896c609d4)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
