### PR TITLE
style: replace .container.is-fluid (again)

### LINKED ISSUE #9245: refactor: container size to tailwind
Replace `container is-*` to tailwind equivalent

- ref #9013 
- https://bulma.io/documentation/layout/container/
- https://tailwindcss.com/docs/container

### PR DESCRIPTION
**Pull request by pbkompasz**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [X] Refactoring

## Context

- [X] Closes #9245
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [X] My contribution builds **clean without any errors or warnings**
- [X] I've merged recent default branch -- **main** and I've no conflicts
- [X] I've tried to respect high code quality standards
- [X] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [X] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16hqk8Tjugo9AwSzKkxXc1dsRK7iJetpx1YBaoXYwdHzuNAt&usdamount=50&donation=true)

#### Community participation

- [ ] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by preschian — APPROVED** [review]
code lgtm (not tested)

**Comment by exezbcz** [comment]
could you check @prury ?

**Comment by prury** [comment]
@exezbcz 20 seconds later: 
navbar stretched: 
image

overall: 

https://github.com/kodadot/nft-gallery/assets/36627808/0c5143d6-61ca-4b21-b406-481727baee3c

will not proceed and test it all over since PR was clearly not tested by author

**Comment by prury** [comment]
closing since no proper testing/response

**Pull request closed without merging**
