### PR TITLE
#5889 hiding stats

### LINKED ISSUE #5889: Hide Stats
Hide stats from the menu. The stats are not working so we agreed with @yangwao to hide/remove them. 
- from all networks

Screenshot 2023-05-09 at 15 08 35

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Closes #5889
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screen Shot 2023-05-09 at 6 22 33 PM

### <samp>🤖 Generated by Copilot at eb8cd9a</samp>

Removed `StatsDropdown` from navbar and cleaned up unused code. This change makes the navbar faster and less cluttered.

### <samp>🤖 Generated by Copilot at eb8cd9a</samp>

> _Sing, O Muse, of the swift and skillful coder_
> _Who from the navbar `StatsDropdown` removed_
> _To make the page more swift and less encumbered_
> _And please the users with a smoother groove._

### CODE REVIEW

**Review by preschian — COMMENTED** [review]
adjust e2e test also please https://github.com/kodadot/nft-gallery/blob/2a950ae3c2a0d22c0f299d29f73d2c936b7231ee/tests/cypress/support/commands.ts#L33. otherwise lgtm

**Review by roiLeo — COMMENTED** [review]
```bash
  2 failing

  1) landingRmrk
       loadLanding:
     AssertionError: Timed out retrying after 10000ms: Expected to find element: `[data-cy="spotlight"]`, but never found it.
      at Context.eval (webpack:///./cypress/support/commands.ts:34:5)

  2) landingBsx
       loadLanding:
     AssertionError: Timed out retrying after 10000ms: Expected to find element: `[data-cy="global-offers"]`, but never found it.
      at Context.eval (webpack:///./cypress/support/commands.ts:56:5)
```
Comment code instead of remove it?

**Comment by preschian** [comment]
@prachi00 almost, and fix deepscan

```
  2 failing

  1) landingRmrk
       loadLanding:
     AssertionError: Timed out retrying after 10000ms: Expected to find element: `[data-cy="series-insight"]`, but never found it.
      at Context.eval (webpack:///./cypress/support/commands.ts:34:5)

  2) landingBsx
       loadLanding:
     AssertionError: Timed out retrying after 10000ms: Expected to find element: `[data-cy="offers-stats"]`, but never found it.
      at Context.eval (webpack:///./cypress/support/commands.ts:53:5)
```

**Comment by prachi00** [comment]
> @prachi00 almost, and fix deepscan
> 
> ```
>   2 failing
> 
>   1) landingRmrk
>        loadLanding:
>      AssertionError: Timed out retrying after 10000ms: Expected to find element: `[data-cy="series-insight"]`, but never found it.
>       at Context.eval (webpack:///./cypress/support/commands.ts:34:5)
> 
>   2) landingBsx
>        loadLanding:
>      AssertionError: Timed out retrying after 10000ms: Expected to find element: `[data-cy="offers-stats"]`, but never found it.
>       at Context.eval (webpack:///./cypress/support/commands.ts:53:5)
> ```

fixed

**Comment by preschian** [comment]
> fixed

still error. could you please test in your local first and then commit 😅

**Comment by prachi00** [comment]
> > fixed
> 
> still error. could you please test in your local first and then commit 😅

yes would you mind confirming the correct e2e command with me, I run test:e2e this on my local but it never finds these errors it seems

**Review by roiLeo — APPROVED** [review]

**Review by preschian — APPROVED** [review]

**Comment by preschian** [comment]
> yes would you mind confirming the correct e2e command with me, I run test:e2e this on my local but it never finds these errors it seems

aahh i see, for me usually run `test:e2e-gui` and test specific test case

**Comment by vikiival** [comment]
pay 10 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $10 @ 24.69 USD/KSM ~ 0.405 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0xbad30f2dd5da36dff8e527c6e21ade28d61567444d629d6de5f0b9b96e344d17](https://kusama.subscan.io/extrinsic/0xbad30f2dd5da36dff8e527c6e21ade28d61567444d629d6de5f0b9b96e344d17)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
