### PR TITLE
feat: add offers tab

### LINKED ISSUE #4233: redesign: Offers section
requirements: https://github.com/kodadot/nft-gallery/issues/4111#offers-section

## <a href="#offers-section" id="offers-section">Offers</a>
image
This would actually work only on Basilisk, as there support for offers. 
We will show all offers on particular NFT.
Columns like we have in current offers.
It has a column price in assets; this will be in future multi-currency. 
**Price** in asset, in future, can be KSM, BSX, aUSD and so on
**USD** denomination of those assets... this will be tricky as there might be assets which are not always will be traded.. we will need figure out write wrapper probably for this one
**Floor Differences** will be query which will check against floor of current collection and calculate if offer is above or below from nominal floor
**Expiration** of offer in relative time, like hours, days, weeks, months
**From** would show the address with resolver for identity on top of the address

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [x] Redesign

## Context

- [x] Closes #4233

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by roiLeo** [comment]
> this is for the design or the component itself? maybe could you explain why and what is the alternative? for the component because the style same as the other table used in offers. for the design maybe can explain it to @exezbcz

You're right, on Figma design we use table :/ 
I would keep the box like we use before since I find we have to many table in this interface

> renamed to `GalleryItemTabsPanel` is that ok?

OK

> there is no scss variable for `height` in `Tabs`, so I change it to `contentClass` props

NVM wrong component, this rule will be global and we will have this display for any table we add
edit: new `&--fixed` ✅ 



Shouldn't we hide Properties when empty?

Screenshot 2022-11-22 at 10-43-38 KodaDot - Kusama NFT Market Explorer

**Review by roiLeo — APPROVED** [review]
✅ code lgtm

**Comment by exezbcz** [comment]
Yes, a table is being used. What is wrong about it? It is, in my opinion, better when it is unified. Additionally, you can order the table by rarity in the future. You can locate everything you need fast and easily in tables. Wdyt?

**Comment by roiLeo** [comment]
> Yes, a table is being used. What is wrong about it? It is, in my opinion, better when it is unified. 

it just gives me the impression that the page is loaded with tables, compared to other platform where Properties have different design so that it comes out of the page.

> Additionally, you can order the table by rarity in the future. You can locate everything you need fast and easily in tables. Wdyt?

Just fyi we are far away from having "rarity" query so it is not applicable at this time.

**Comment by yangwao** [comment]
why tests have failed? 

image

**Comment by yangwao** [comment]
Oh I guess we've been changing this? 

`Module not found: Error: Can't resolve '@/utils/formatBalance' in 'components/gallery/GalleryItemTabsPanel'`

To this ? https://github.com/kodadot/nft-gallery/blob/main/utils/format/balance.ts

**Comment by yangwao** [comment]
> I would keep the box like we use before since I find we have to many table in this interface

hey that box is OK if we would use just traits, hence we plan to have Advanced Traits, it would be bit complex later

https://docs.kodadot.xyz/reactive-nfts.html#advanced-nested-traits-system-gamefi-ready

> Just fyi we are far away from having "rarity" query so it is not applicable at this time.

Yes, we need to prioritize once we finish our travel, I've seen some demo already :)

overall, looks good to me!

**Comment by yangwao** [comment]
Accepting & Cancelling offers 
- https://github.com/kodadot/nft-gallery/issues/4437

> * I'm not a fan of using table for properties

@roiLeo  I know it does not look appealing, but for some stuff and trading is way more efficient as we plan to have there sorting fn in later

> Shouldn't we hide Properties when empty? (and show by default Description)

Yes, good point

**Comment by yangwao** [comment]
@preschian for me, it's ready to go in this state! :)

**Comment by yangwao** [comment]
yes! :)

**Comment by yangwao** [comment]
nice 
image

**Pull request merged**
