### PR TITLE
#1804 Change facts in preloader after 10 seconds

### LINKED ISSUE #1804: Change facts in preloader after 10 seconds
Let's change the quote after a while, probably 10 seconds it should be enough to read every quote?

Bonus stage: bring your own quote! 

image

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇  _ Do a quick check before the merge.

### PR type
- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?
- [x] PR closes #1804
- [x] added an interval of 8 seconds, felt 10 was too long
       added two facts as well 

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main-nuxt** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases

### Had issue bounty label ?
- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation
- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [x] My fix has changed **something** on UI, a screenshot is best to understand changes for others.

https://user-images.githubusercontent.com/39299315/149616278-6eb6289b-e36d-462d-8065-bc0a33bcda22.mp4

### CODE REVIEW

**Comment by yangwao** [comment]
It would be possible to make the window fixed height and width, so while changing the quote, it would not change window size with a quote? 


https://user-images.githubusercontent.com/5887929/149626391-c3227815-f802-49ad-909a-1f7fa9413a71.mov

**Comment by yangwao** [comment]
Let's fix that fixed window width and height tho in this PR :)

Perfect, I’ve sent the payout https://kusama.subscan.io/extrinsic/0x5e9e6fdb26642e63c3d44e709bfc4719345d4b2cb371e9c9b7f8047483c7beeb

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/

**Comment by prachi00** [comment]
@yangwao have fixed the height and width

**Comment by yangwao** [comment]
Thinking out loud that to be aligned with all dialogs in KodaDot, could we add shadow there? :)

Like it was made here https://github.com/kodadot/nft-gallery/pull/1820

and then we can merge it finally 😄

**Comment by prachi00** [comment]
> Thinking out loud that to be aligned with all dialogs in KodaDot, could we add shadow there? :)
> 
> Like it was made here #1820
> 
> and then we can merge it finally 😄

@yangwao with the primary colour, its not really visible, so experimented with gray for this, let me know if it looks fine?

Screenshot 2022-01-16 at 3 58 33 PM
Screenshot 2022-01-16 at 4 00 03 PM

**Comment by prachi00** [comment]
Screenshot 2022-01-16 at 4 02 07 PM
or another option is to have it like this instead, with the background darker instead of gray

**Comment by yangwao** [comment]
> Screenshot 2022-01-16 at 4 02 07 PM
> 
> or another option is to have it like this instead, with the background darker instead of gray

yes, this is perfect!

**Comment by prachi00** [comment]
@yangwao have pushed the updated changes

**Pull request merged**
