### PR TITLE
feat: bsx landing page add lastest and newest list

### LINKED ISSUE #3570: Newest List for Basilisk
I guess adding the same component as we have for RMRK, but for Basilisk on Landing would be nice. 

image

### LINKED ISSUE #3571: Latest sales for Basilsik
Same as we have latest sales on RMRK, we should have for Basilisk on landing 

image

### PR DESCRIPTION
**Pull request by zhengow**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3570; PR closes #3571
- [x] Requires deployment [snek#42](https://github.com/kodadot/snek/pull/42)
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at <http://localhost:9090/>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by yangwao** [comment]
> Do I need to show popular collection list for bsx?

I think once we will be live we can show some popular collections :)
I can make an issue for that tho

**Review by yangwao — APPROVED** [review]

**Review by JustLuuuu — APPROVED** [review]
wfm

**Comment by petersopko** [comment]
@zhengow can't we use the same query for the bsx/rmrk? seems like an overkill in the code 👀 if the `passionAccount` thing causes problems, we can throw it out for now as we have disabled passion feed anyways

**Review by petersopko — CHANGES_REQUESTED** [review]
more [KISS](https://en.wikipedia.org/wiki/KISS_principle) pls 💋 😆

**Comment by petersopko** [comment]
👀 
image

**Comment by yangwao** [comment]
good to go?

**Review by kkukelka — APPROVED** [review]
gtg from my pov

**Comment by yangwao** [comment]
pay 150

**Pull request merged**
