### PR TITLE
chore: fa sharp regular as default icon

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] context here https://github.com/kodadot/nft-gallery/pull/7208#issuecomment-1725278656
- [x] Remove unused packages
- [x] set fa sharp as default icon
- [x] similar with #7251. in this PR, I change all of the icons to `fasr`. in case some of icons intended to use `fass` feel free to create a new PR

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)

## Screenshot 📸

- [ ] My fix has changed UI

### <samp>🤖 Generated by Copilot at 6e473db</samp>

Refactored several components to use reusable components and a new icon pack for `NeoIcon` and `NeoButton` components. This improves the code quality, consistency, and performance of the UI. Removed unnecessary `pack` and `icon-pack` props from various components that use the default icon pack. Moved some code from `DropContainer.vue` and `BlogPost.vue` to `Navbar.vue` to create reusable components for displaying drop-related and blog-related information.

### <samp>🤖 Generated by Copilot at 6e473db</samp>

> _Sing, O Muse, of the glorious pull request_
> _That simplified the code of `NeoIcon` and `NeoButton`_
> _And removed the needless `pack` and `icon-pack` props_
> _That burdened the components with redundant attributes._

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]

**Comment by prury** [comment]
smaller than it was on canary: 
image

not loading: 
image

smaller than it was on canary: 
image

**Comment by exezbcz** [comment]
after changes that prury mentioned, feel free to merge

**Comment by preschian** [comment]
> * many icons got this change(nut sure if that's a problem tho):
> 
>  icon.change.mp4

Oh, intended. This is the one that I am trying to fix in this PR. Previously, by default, we used `fa classic solid`. in this PR, I change it to `fa sharp regular.`
before: https://fontawesome.com/icons/share-alt?f=classic&s=solid
after: https://fontawesome.com/icons/share-alt?f=sharp&s=regular

**Pull request merged**
