### PR TITLE
chore: remove unnecessary i18n dependencies

### LINKED ISSUE #2039: Use @nuxtjs/i18n in favour of vue-i18n
I guess during migration to nuxt there was no transition from vue-i18n to @nuxtjs/i18n, even though the latter is included as a dependency already

Goal: Deprecate vue-i18n and reimplement via @nuxtjs/i18n 🏗️ 

Maybe the following dependencies can be removed too:
```json
"@intlify/vue-i18n-loader": "^1.1.0",
"vue-cli-plugin-i18n": "^1.0.1",
```

followup for #1999 #2038

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Do a quick check before the merge.

### PR type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [x] Chore

### What's new?

- [x] PR closes #2039
- [x] removed unnecessary dependencies which should already be installed through nuxt/i18n and added i18n types

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases

### Had issue bounty label ?

- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI, a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
Could you check if it's possible to merge `i18n` from nuxt.config.js with `utils/config/i18n.ts` into one config?

**Comment by kkukelka** [comment]
> Could you check if it's possible to merge `i18n` from nuxt.config.js with `utils/config/i18n.ts` into one config?

will be done in #2096 👍

**Review by roiLeo — APPROVED** [review]

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 171.16 USD/KSM ~ 0.584 $KSM
🧗 [EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW](https://kusama.subscan.io/account/EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)
🔗 [0x99c0e9218f185a22a4524d7c893d24cd14088ce30e51624fe02f959b49ee58ab](https://kusama.subscan.io/extrinsic/0x99c0e9218f185a22a4524d7c893d24cd14088ce30e51624fe02f959b49ee58ab)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
