### PR TITLE
Landing-reconstruction

### LINKED ISSUE #8669: Landing reconstruction
To move this faster and keep landing engaging we've discussed with @exezbcz that would need some minor refresh before whole rehaul

- [x] #8676
- [ ] remove or shuffle spotlight lower
- [x] https://github.com/kodadot/nft-gallery/issues/8423
- [ ] tune top collections with engaging information 

Reasoning
-
- search bar is barely used and people apparently scroll down right away, can help us maybe our landing page performance bit, but nothing thrill. 
- spotlight - haven't seen much people clicked and artists collection on AHK aren't traded anyways, wasted space in attention space
- top collections are good but nothing innovative and there are already hefty tips how to make it better ie more coingecko styled
- substack is not active and we opt for beehive with weekly pace to harvest more reccuring users

Final order
- 
- chain selector 
- top collections
- signups email
- generative
- sales
- newest list
- beehiiv

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Feature

## Needs Design check

- @exezbcz please review

## Context

- [x] Closes #8669

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)

## Screenshot 📸

- [x] My fix has changed UI

### CODE REVIEW

**Comment by daiagi** [comment]
need to update tests

**Comment by daiagi** [comment]
@prury can you take a look at the remaining failing tests plz?

**Review by roiLeo — COMMENTED** [review]
no more footer gradient?
Screenshot 2023-12-26 at 15-01-47 KodaDot - NFT Market Explorer


IMO footer is important (seo, sitemap etc..) for landing page and shouldn't be hidden 

sad for spotlight too :(

**Comment by exezbcz** [comment]
> the issue requirements but I Also think footer belongs in landing

where is written that footer should be gone? one issue is about the articles on top of footer, nothing IMO mentioned about footer itself

**Comment by daiagi** [comment]
Sorry, you're right.
I must have misread

**Comment by exezbcz** [comment]
@daiagi its okay, its not super clear from the issue 


will check soon

the spotlight is getting removed since there will be hero section remake, we just have to agree internally what the transition will be

**Comment by daiagi** [comment]
@exezbcz  footer is back

**Comment by prury** [comment]
i think this PR could be part of the related issue, since there's also this inside it: 
> 
> tune top collections with engaging information

**Comment by yangwao** [comment]
good, thanks!
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 8.66 USD/DOT ~ 2.309 $DOT
🧗 [1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8](https://polkadot.subscan.io/account/1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)
🔗 [0x02b698bdb5fb30180b2eea622059d6ee7afea3cd8146ddd34be0cd6bd3bb8534](https://polkadot.subscan.io/extrinsic/0x02b698bdb5fb30180b2eea622059d6ee7afea3cd8146ddd34be0cd6bd3bb8534)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
