### PR TITLE
Replace Jest with Vitest

### LINKED ISSUE #2413: Replace Jest with Vitest
Found nice article
Maybe would be a good bet for KodaDot

[Testing Vite with minimal config using Vitest](https://blog.logrocket.com/testing-vite-minimal-config-using-vitest/)

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [X] Feature
- [ ] Refactoring

### What's new?

- [X] PR closes #2413
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

`yarn test` 
image

### CODE REVIEW

**Comment by yangwao** [comment]
hence we've updated to pnpm and vite, time to merge `main`

**Comment by Jarsen136** [comment]
> hence we've updated to pnpm and vite, time to merge `main` and resolve conflicts to merge this :)

Sure, I just finished it.

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 167.8 USD/KSM ~ 0.596 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xef5bf39e487d77fad0b3d0a6a605ad5b3c8da18385875f954eb7ef7b2f43bf4c](https://kusama.subscan.io/extrinsic/0xef5bf39e487d77fad0b3d0a6a605ad5b3c8da18385875f954eb7ef7b2f43bf4c)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
