### PR TITLE
feat: Item preview: Show creator & current owner

### LINKED ISSUE #10898: Item preview: Show owner
Im happy that we are showing the creator here finally, but can we also show the owner?
So there will be two fields, creator AND current owner

Screenshot 2024-08-24 at 15 21 49

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Feature

## Needs Design check

- @exezbcz please review

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #10898

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by vikiival** [comment]
issuer != creator :)

**Comment by Jarsen136** [comment]
> issuer != creator :)

I know but it's what was expected from the original issue.  https://github.com/kodadot/nft-gallery/issues/10898#issue-2484592170 cc @JustLuuuu

**Comment by JustLuuuu** [comment]
> > issuer != creator :)
> 
> I know but it's what was expected from the original issue. [#10898 (comment)](https://github.com/kodadot/nft-gallery/issues/10898#issue-2484592170) cc @JustLuuuu

Yeah we should show both: Creator (artist who made the collection) + current owner of the NFT

**Comment by vikiival** [comment]
Yup but the
Issuer of the NFT is not creator

**Comment by Jarsen136** [comment]
Or we could rename `creator` to `collection creator` for the generative NFT. Then only the `collection creator` and `owner` will be displayed on this page. 👀

**Comment by Jarsen136** [comment]
updated @vikiival @JustLuuuu 
image

**Comment by JustLuuuu** [comment]
great!

**Pull request merged**
