### PR TITLE
feat: support non ipfs metadata url

### LINKED ISSUE #6618: Statemine collection not loading
This collection on statemine is not loading properly: production and canary too
- https://kodadot.xyz/stmn/collection/88
- https://canary.kodadot.xyz/stmn/collection/88

Screenshot 2023-08-08 at 16 43 03

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #6618
- [x] Related https://github.com/kodadot/workers/pull/136

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)

## Screenshot 📸

| Before | After |
|--------|--------|
| Screenshot 2023-10-13 at 6 42 20 PM | Screenshot 2023-10-13 at 6 42 30 PM | 

### <samp>🤖 Generated by Copilot at f776156</samp>

The code improves the IPFS integration by using a configurable image service URL and adding a new provider and a fallback option. It also removes some unused code from `utils/ipfs.ts`.

### <samp>🤖 Generated by Copilot at f776156</samp>

> _Oh we're the crew of the image service ship_
> _And we sail the web with a clever script_
> _We've refactored the URL to a `config` object_
> _And we've added `kodaImage` to our IPFS socket_

### CODE REVIEW

**Comment by yangwao** [comment]
S3 "NFT" coming to kodadot?

**Comment by preschian** [comment]
> S3 "NFT" coming to kodadot?

yes, expand our worker capabilities XD
https://www.cloudflare.com/en-gb/pg-cloudflare-r2-vs-aws-s3/

**Review by roiLeo — APPROVED** [review]

**Review by Jarsen136 — APPROVED** [review]

**Comment by yangwao** [comment]
Hopefully everything works well!
Thanks!
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 4.59 USD/DOT ~ 10.893 $DOT
🧗 [1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p](https://polkadot.subscan.io/account/1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)
🔗 [0x04f7faf51b4bb75b60154bdd7e23d8e70f314267fa0d8303254f4ba33a5f5e71](https://polkadot.subscan.io/extrinsic/0x04f7faf51b4bb75b60154bdd7e23d8e70f314267fa0d8303254f4ba33a5f5e71)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
