### PR TITLE
#6489 padding

### LINKED ISSUE #6489: landing page container content not lined up
image
- the line should full width
- the shapes should also start at the edge of the screen

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #6489
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)

## Screenshot 📸

- [x] My fix has changed UI
Screen Shot 2023-07-29 at 4 55 06 PM

### CODE REVIEW

**Comment by prachi00** [comment]
> 



> Comes from #6457, landing page should be using `'full-width-layout'`

@roiLeo what do you mean?

**Comment by roiLeo** [comment]
@prachi00 you should use full-width-layout on landing page and it will fix this issue. Check old code before vue3 migration on the page.

**Comment by prachi00** [comment]
> @prachi00 you should use full-width-layout on landing page and it will fix this issue. Check old code before vue3 migration on the page.

done

**Review by roiLeo — APPROVED** [review]
Code lgtm ✅

**Comment by prury** [comment]
it affected other elements as well: 
image

**Comment by prachi00** [comment]
> it affected other elements as well: image
> 
> image

@roiLeo I guess the previous fix was better then?

**Comment by roiLeo** [comment]
> it affected other elements as well: 

Are you sure it is related with this PR? Looks weird as I can only see changes related to landing page

**Comment by prury** [comment]
> > it affected other elements as well:
> 
> Are you sure it is related with this PR? Looks weird as I can only see changes related to landing page

i don't know what the heck happened, i opened again now and its working properly
checked all the other PRs to see if was one of them and found nothing

**Comment by prachi00** [comment]
> > > it affected other elements as well:
> > 
> > 
> > Are you sure it is related with this PR? Looks weird as I can only see changes related to landing page
> 
> i don't know what the heck happened, i opened again now and its working properly checked all the other PRs to see if was one of them and found nothing

um okay with me 😂

**Review by vikiival — APPROVED** [review]

**Pull request merged**
