### PR TITLE
feat: update links in footer

### LINKED ISSUE #5706: Update links in footer to new hello page
We have new hello.kodadot.xyz and we could put in another release new links in footer already. 

I guess maybe links needs bit edit @JustLuuuu like removing that "knowledgebase" ?, "technical -> referral-program" ?, About rename from "faq to about" ? 

FAQ -> https://hello.kodadot.xyz/knowledgebase/general-1/faq
About -> https://hello.kodadot.xyz/knowledgebase/general/faq
Referral Program -> https://hello.kodadot.xyz/knowledgebase/technical/kodadots-programs/artist-referral-program
Artist Ambassador -> https://hello.kodadot.xyz/knowledgebase/technical/kodadots-programs/artist-ambassadot-program
Ambassador Program -> https://hello.kodadot.xyz/knowledgebase/technical/kodadots-programs/artist-ambassadot-program

image

Wait from Luu for green check and we can update it there so we can bundle it with upcoming release, approximate it can go out in 2-3 weeks.

### PR DESCRIPTION
**Pull request by floyd-li**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #5706
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EZiu1PjV2j2JHKxY6mHnFwwCRCoV27uHKQSkKXATSh1srJT)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at 70bd5f9</samp>

Updated footer links to new knowledge base site. This enhances the UX and the information quality of `TheFooter.vue` component.

### <samp>🤖 Generated by Copilot at 70bd5f9</samp>

> _Sing, O Muse, of the skillful coder who updated the links_
> _Of many a page in `TheFooter.vue`, the component divine,_
> _To match the new site of the knowledge base, where wisdom shines_
> _Like the bright-eyed Athena, who guides the seekers of truth._

### CODE REVIEW

**Comment by vikiival** [comment]
hey there is a typo in the link which needs to be fixed by @JustLuuuu 


Screenshot 2023-04-18 at 18 58 23

**Comment by yangwao** [comment]
AmbassaDOT just dropped

**Comment by vikiival** [comment]
cc @floyd-li

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
pay 10 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $10 @ 31.81 USD/KSM ~ 0.314 $KSM
🧗 [EZiu1PjV2j2JHKxY6mHnFwwCRCoV27uHKQSkKXATSh1srJT](https://kusama.subscan.io/account/EZiu1PjV2j2JHKxY6mHnFwwCRCoV27uHKQSkKXATSh1srJT)
🔗 [0x189dd88140b5b957eeb37a3c2683dae7cbd66d7155453a5739cba40021a93731](https://kusama.subscan.io/extrinsic/0x189dd88140b5b957eeb37a3c2683dae7cbd66d7155453a5739cba40021a93731)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
