### PR TITLE
prefetch gallery Items on infinity scroll

### LINKED ISSUE #4882: Skeleton Items on infinity scroll
Can we have a skeleton on scrolling down on infinity scroll? 
Let's say 5 rows ahead instead of 3?

Can we maybe trigger preload sooner, not just when user hits bottom?

Right now it's doing that jumping effect which is not so good

https://user-images.githubusercontent.com/5887929/216006702-19944a1f-5a90-49e2-87c2-0f4ec90632a9.mov

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #4882
- [ ] Requires deployment <>

1. prefetch pages on gallery items list
2. fetch the next pages ahead before hitting the bottom.

3. fix: infinity scroll can get glitched on gallery explore items page

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

Kapture 2023-02-06 at 00 06 59

### CODE REVIEW

**Comment by Jarsen136** [comment]
> 
> 1. prefetch pages on gallery items list
> 2. fetch the next pages ahead before hitting the bottom.

I'm about to make a follow-up issue to add the prefetch strategy to all the other pages using infinity scroll. WDYT?

**Comment by exezbcz** [comment]
maybe use this as well for collections? Otherwise ok for me

**Comment by yangwao** [comment]
seems going blazing fast! 

now I'm thinking mass-mints should be grouped somehow, I can't find issue but seen it few days ago hmm 😭

https://user-images.githubusercontent.com/5887929/216832451-ed226ccf-d854-4c5d-b749-1b2870ffaed5.mov

**Comment by yangwao** [comment]
oh, found issue, scrolling up is not so fast ? 

https://user-images.githubusercontent.com/5887929/216832793-b85400b1-a223-411d-8aa2-f2339ff7650d.mov

**Comment by Jarsen136** [comment]
> oh, found issue, scrolling up is not so fast ? 
> 
> 
> 
> https://user-images.githubusercontent.com/5887929/216832793-b85400b1-a223-411d-8aa2-f2339ff7650d.mov
> 
> 
> 
> 

Oh yes, Let me add prefetch also for srcoll up. Will fix it later.

**Review by vikiival — APPROVED** [review]

**Comment by yangwao** [comment]
> make a follow-up issue to add the prefetch strategy to all the other pages using infinity scroll. WDYT?

yes! I think it's doable. It's possible make it as util to dedupe code?

**Comment by Jarsen136** [comment]
> > make a follow-up issue to add the prefetch strategy to all the other pages using infinity scroll. WDYT?
> 
> yes! I think it's doable. It's possible make it as util to dedupe code?

Sure. Will make it reusable.

**Comment by Jarsen136** [comment]
> oh, found issue, scrolling up is not so fast ?
> 

It should be faster now when scrolling up. I have added prefetch for scrolling up, though it's not as smooth as scrolling down. I think it could be improved in the next issue.

**Comment by yangwao** [comment]
it's far so good for me!

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 35.96 USD/KSM ~ 1.39 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xdd65121fdb2cf5138693c65d681791cf75b7beaf228d510f43d4e678385e5ecd](https://kusama.subscan.io/extrinsic/0xdd65121fdb2cf5138693c65d681791cf75b7beaf228d510f43d4e678385e5ecd)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
