### PR TITLE
End March release

### LINKED ISSUE #5354: Can’t click on footer links on kodadot.xyz
### What happened?

I know it’s working on beta, however links in  footer on main site kodadot.xyz are not clickable. Let’s fix this please. 

### Please reproduce in steps

/

### Expected Behavior

/

### What browsers are you seeing the problem on?

Desktop Chrome

### At which address did you encounter bug?

_No response_

### Are you logged in?

None

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

_No response_

### Screenshots

image

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by vikiival**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] RELEASE

## Context

- [x] Closes #5354

### CODE REVIEW

**Comment by yangwao** [comment]
I would like to see to highlight visual changes

**Comment by yangwao** [comment]
Waiting for some PR to merge? @vikiival

**Comment by vikiival** [comment]
> Waiting for some PR to merge? @vikiival 

Everything was merged. Lets merge

**Pull request merged**
