### PR TITLE
fix: Missing collection link

### LINKED ISSUE #4781: Missing collection link?
https://beta.kodadot.xyz/bsx/gallery/2551182625-5

sadly on production too https://kodadot.xyz/bsx/gallery/2551182625-5

image

other collections has it 

image

https://kodadot.xyz/bsx/gallery/2608295324-7

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4781
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by yangwao** [comment]
> For now, I would use the id of item as its name if the data is empty.
> 
> image
> The missing name should be solved on the indexer side.  related to #4775

means indexer failed to fetch?

**Comment by Jarsen136** [comment]
> > The missing name should be solved on the indexer side.  related to #4775
> 
> means indexer failed to fetch?

Yes, I think so.

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 34.25 USD/KSM ~ 0.876 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x0920a835c00b7546e7b3bab371a5c4295df5cec9a558b5029a509370b43353e3](https://kusama.subscan.io/extrinsic/0x0920a835c00b7546e7b3bab371a5c4295df5cec9a558b5029a509370b43353e3)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by Jarsen136** [comment]
> fallback meta title also?
> 

There is already a placeholder image for the meta fallback.

image

**Pull request merged**
