### PR TITLE
fix: Robots.txt is invalid

### LINKED ISSUE #6330: Robots.txt is invalid
Screenshot 2023-06-26 at 13 44 28

https://developer.chrome.com/docs/lighthouse/seo/invalid-robots-txt/?utm_source=lighthouse&utm_medium=devtools

first iteration #6286

### PR DESCRIPTION
**Pull request by Jarsen136**
## PR Type

- [x] Bugfix

## Context

- [x] Closes #6330 
- [ ] Requires deployment <snek/rubick/worker>

### CODE REVIEW

**Comment by Jarsen136** [comment]
I just learn that `a disallow line should contain a "path" as opposed to a full URL including the domain` after some search.
That means we could not disallow the page index on these subdomains `beta` `canary` etc only by changing the `robot.txt`.

https://stackoverflow.com/questions/71514881/can-domains-be-used-in-robots-txt

**Review by roiLeo — APPROVED** [review]

**Comment by yangwao** [comment]
> That means we could not disallow the page index on these subdomains `beta` `canary` etc only by changing the `robot.txt`.

Or maybe set no-index on those pages based on ENV?

**Comment by Jarsen136** [comment]
> > That means we could not disallow the page index on these subdomains `beta` `canary` etc only by changing the `robot.txt`.
> 
> Or maybe set no-index on those pages based on ENV?

I just added `no-index` meta on all pages except for `kodadot.xyz`. Let's see if it work in some case. 
ref: https://developers.google.com/search/docs/crawling-indexing/block-indexing
image

(As for the pages with prefix `.w.`\ `nft ` \`form`, we still need to add different robot.txt for them, or just leave them there.)

**Comment by vikiival** [comment]
For Workers I made a separated issue 
- https://github.com/kodadot/workers/issues/114

**Review by vikiival — APPROVED** [review]
let's give it a shot

**Pull request merged**
