### PR TITLE
#6223 double stroke issues

### LINKED ISSUE #6223: Double stroke visual issue
it is visible, for example, here: 
- #6219

image
- slider 

card layout buttons
image

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #6223
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)

## Screenshot 📸

- [x] My fix has changed UI

Screen Shot 2023-06-17 at 3 45 41 PM

Screen Shot 2023-06-17 at 3 46 09 PM

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
This look like a hotfix, Imo something wrong with `NeoTab` scss config

**Comment by prachi00** [comment]
> This look like a hotfix, Imo something wrong with `NeoTab` scss config

what do you mean wrong?

**Comment by prachi00** [comment]
@roiLeo does something needs to be changed here?

**Comment by roiLeo** [comment]
> @roiLeo does something needs to be changed here?

I don't really like this solution, we'll always have this problem check profile page buttons for example

Capture d’écran 2023-06-20 à 8 55 29 AM

**Comment by prachi00** [comment]
> > @roiLeo does something needs to be changed here?
> 
> I don't really like this solution, we'll always have this problem check profile page buttons for example
> 
> Capture d’écran 2023-06-20 à 8 55 29 AM

I dont think there is any other way to fix it though other than manual css?

**Comment by roiLeo** [comment]
> I dont think there is any other way to fix it though other than manual css?

it should work using default oruga css, check out doc example of [field](https://oruga.io/components/field.html) with addons.

**Comment by prachi00** [comment]
Screen Shot 2023-06-21 at 10 08 54 PM
Screen Shot 2023-06-21 at 10 09 07 PM
@roiLeo even in oruga fields, there is double border

**Review by roiLeo — COMMENTED** [review]
I would try someting different, create a css rule where all element inside a `NeoField` with `addons` should have border-right removed but `:not(:last-child)`

**Comment by prury** [comment]
@prachi00, i know i said in the issue that some other PR fixed it, but i've checked again and is still happening: 
image

**Comment by prachi00** [comment]
> @prachi00, i know i said in the issue that some other PR fixed it, but i've checked again and is still happening: image

which chain is this? I dont see it

**Comment by prury** [comment]
> > @prachi00, i know i said in the issue that some other PR fixed it, but i've checked again and is still happening: image
> 
> which chain is this? I dont see it

RMRK2: 
https://deploy-preview-6263--koda-canary.netlify.app/ksm/gallery/18429103-7EA1DCF47E98A25067-3MAX-UNIEDITION_1-00000001

**Comment by prachi00** [comment]
Screen Shot 2023-06-24 at 2 31 23 PM
@prury weird I dont see it, I am on chrome, and you are on chrome too?

**Comment by prury** [comment]
> Screen Shot 2023-06-24 at 2 31 23 PM @prury weird I dont see it, I am on chrome, and you are on chrome too?

You got it, it's a Firefox only issue, tested on Chrome and it won't happen.

**Comment by prachi00** [comment]
@prury 
I cant reproduce this even in firefox 
Screen Shot 2023-06-27 at 11 54 41 AM

@roiLeo can we merge this one for now? We can create a different issue to track firefox issue
Also, PS giving border left to fields might not work as in some cases we have border bottom as well that is double stroked and in some cases its not the fields but tabs

**Review by roiLeo — COMMENTED** [review]
I don't see any difference with beta, why would we merge it?

**Comment by prachi00** [comment]
Screen Shot 2023-06-28 at 7 38 34 PM
in beta there is double stroke

**Comment by prachi00** [comment]
maybe we can close this pr if its not relevant anymore
@exezbcz @roiLeo

**Review by roiLeo — COMMENTED** [review]
For multiple buttons wrapped in NeoField I would see something like:

```css
.o-field--addons > :not(:first-child):not(:last-child) button,
.o-field--addons > button:not(:first-child):not(:last-child) {
  border-right: 0;
  border-left: 0;
}
```

and I think we can do something similar for MassMint tabs

Why do you have some changes in `CreateDropdown` component?

**Comment by prachi00** [comment]
> For multiple buttons wrapped in NeoField I would see something like:
> 
> ```css
> .o-field--addons > :not(:first-child):not(:last-child) button,
> .o-field--addons > button:not(:first-child):not(:last-child) {
>   border-right: 0;
>   border-left: 0;
> }
> ```
> 
> and I think we can do something similar for MassMint tabs
> 
> Why do you have some changes in `CreateDropdown` component?

for massmints, cant find a common class as it an <a tag 
dropdown changes are gone after resolving conflicts

**Review by roiLeo — APPROVED** [review]
> for massmints, cant find a common class as it an <a tag dropdown changes are gone after resolving conflicts

Alright, noted.

code lgtm

**Comment by prury** [comment]
only double stroke remaining was the one on profile, but let's leave it for profile redesign, works for me.

**Comment by prachi00** [comment]
can we merge this pls

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
pay 13 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $13 @ 5.15 USD/DOT ~ 2.524 $DOT
🧗 [13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1](https://polkadot.subscan.io/account/13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)
🔗 [0x0bc14f00dfadf159899946f804442dd4283186ac4a9703d8326465af8cb55241](https://polkadot.subscan.io/extrinsic/0x0bc14f00dfadf159899946f804442dd4283186ac4a9703d8326465af8cb55241)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
