### PR TITLE
fix: Drops pages could have dedicated og:image

### LINKED ISSUE #6349: Drops pages could have dedicated og:image
I think in the future we could have og:image there? Like it could be fetched from header?

image

### PR DESCRIPTION
**Pull request by Jarsen136**
- [x] Closes #6349

### CODE REVIEW

**Comment by Jarsen136** [comment]
Emm. I still do not figure out why it does not work, as the seo tag had been updated accordingly.

link: https://deploy-preview-6363--koda-canary.netlify.app/stmn/drops/free-drop
image

The preview information is still the same as the previous one. 
image

**Comment by prury** [comment]
/drops shows the image correctly
drops/free-drop shows the image correctly
items inside the drop collection shows their respective image/description
tested on: twitter, telegram, discord (open graph site wont load the image, don't know why, but not important.)  

as Jarsen said, the right description for the drop link still won't show

opengraph tags: 

```
  <!-- HTML Meta Tags -->
  <title>undefined</title>
  <meta name="description" content="undefined">

  <!-- Facebook Meta Tags -->
  <meta property="og:url" content="https://deploy-preview-6363--koda-canary.netlify.app/stmn/drops/free-drop">
  <meta property="og:type" content="website">
  <meta property="og:title" content="undefined">
  <meta property="og:description" content="undefined">
  <meta property="og:image" content="">

  <!-- Twitter Meta Tags -->
  <meta name="twitter:card" content="summary_large_image">
  <meta property="twitter:domain" content="deploy-preview-6363--koda-canary.netlify.app">
  <meta property="twitter:url" content="https://deploy-preview-6363--koda-canary.netlify.app/stmn/drops/free-drop">
  <meta name="twitter:title" content="undefined">
  <meta name="twitter:description" content="undefined">
  <meta name="twitter:image" content="">

  <!-- Meta Tags Generated via https://www.opengraph.xyz -->
        
```

**Comment by roiLeo** [comment]
maybe something related with kodadot workers? ssr-opengraph?

**Comment by preschian** [comment]
> Emm. I still do not figure out why it does not work, as the seo tag had been updated accordingly.
> 
> link: [deploy-preview-6363--koda-canary.netlify.app/stmn/drops/free-drop](https://deploy-preview-6363--koda-canary.netlify.app/stmn/drops/free-drop)

seems like prerendering on netlify is not working. I can help with canary/beta by using worker
so, what we can do in this PR is validate the metadata (or image) on the client side by using [chrome extension](https://chrome.google.com/webstore/detail/meta-seo-inspector/ibkclpciafdglkjkcibmohobjkcfkaef)

I will open the PR on the workers side

**Review by preschian — APPROVED** [review]
adjust e2e test? otherwise lgtm 👍

**Comment by Jarsen136** [comment]
> adjust e2e test? otherwise lgtm 👍

✅ E2E test pass

**Comment by prury** [comment]
> > Emm. I still do not figure out why it does not work, as the seo tag had been updated accordingly.
> > link: [deploy-preview-6363--koda-canary.netlify.app/stmn/drops/free-drop](https://deploy-preview-6363--koda-canary.netlify.app/stmn/drops/free-drop)
> 
> seems like prerendering on netlify is not working. I can help with canary/beta by using worker so, what we can do in this PR is validate the metadata (or image) on the client side by using [chrome extension](https://chrome.google.com/webstore/detail/meta-seo-inspector/ibkclpciafdglkjkcibmohobjkcfkaef)
> 
> I will open the PR on the workers side

image
image
image
image

**Pull request merged**
