### PR TITLE
feat: Landing hero iteration (farcaster notif and heading change)

### LINKED ISSUE #9685: Landing hero iteration (farcaster notif and heading change)
image

## Design 
updated in design handoff 

https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=7854-37012&mode=design&t=HlJQf0pMdusPXbsG-11

- farcaster notif and heading change

mobile styles: 
image

There is no hover effect - its is like banner - clicking will lead the user to https://warpcast.com/~/channel/koda

thanks!

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Feature

  ## Needs Design check

  - @exezbcz please review

  ## Context

  - [x] Closes #9685

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

image

image

  ## Copilot Summary
  copilot:summary

  copilot:poem

### CODE REVIEW

**Comment by exezbcz** [comment]
image
and it should be also full width until it has to be stacked please

**Review by preschian — APPROVED** [review]
code lgtm

for border radius, might be helpful:
- https://cloudfour.com/thinks/the-math-behind-nesting-rounded-corners/
- https://7kayoh.medium.com/ui-border-rounded-b252b8e4d041

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

@prury can merge when text will be oke

**Comment by Jarsen136** [comment]
> image and it should be also full width until it has to be stacked please
> 
> just visually, i think bigger corner radius will be need on the purple part image

Updated

**Comment by yangwao** [comment]
oke looks good to me

image

**Pull request merged**
