### PR TITLE
#4441 Add close option into search navbar on mobile

### LINKED ISSUE #4441: Add close option into search navbar on mobile
Can someone also change the search navbar on mobile? In current version of kodadot you dont have option to close it :D
image
 
image
also in components page 
https://www.figma.com/file/3iOjW12ERFRDSVnpLuhQmf/landing-page-handoff?node-id=1305%3A5613

_Originally posted by @exezbcz in https://github.com/kodadot/nft-gallery/issues/4196#issuecomment-1295952650_

### PR DESCRIPTION
**Pull request by vkbishu**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Feature

## Context

- [x] Closes #4441

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [x] I've tested PR on mobile

#### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screen Shot 2022-12-05 at 21 05 46 PM

### CODE REVIEW

**Comment by yangwao** [comment]
Brilliant

fill up your payout address please 🥺

**Comment by exezbcz** [comment]
dark mode does not look ok
image

**Comment by vkbishu** [comment]
> Brilliant
> 
> fill up your payout address please 🥺

Thanks 

https://kodadot.xyz/transfer?target=GhvqRXYu6pywEkdCzyuoUrEgaKkUML2mCW9dWz7wniQtcMw

**Comment by vkbishu** [comment]
> dark mode does not look ok image

@exezbcz Ohh. Didn't find the dark mode option. Should I create a separate PR for this fix?

**Pull request merged**
