### PR TITLE
fix: Dark/light mode hover effect

### LINKED ISSUE #5041: Dark/light mode hover effect
## Dark 
image
- should go to k-shade in dark mode
- this hover effect is only correct in light mode 
image

the effect is incorrect in several places
image

## Light 
navbar links should have the same hover effect as footer links 
image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5041
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

image

image

### CODE REVIEW

**Comment by exezbcz** [comment]
> navbar links should have the same hover effect as footer links

- this was only for light mode, now it looks like its changed in dark mode as well
## Dark mode 
image
- should be same as the under search links - that means to k-shade

Thanks!

**Comment by Jarsen136** [comment]
> > navbar links should have the same hover effect as footer links
> 
> * this was only for light mode, now it looks like its changed in dark mode as well
> 
> ## Dark mode
> image
> 
> * should be same as the under search links - that means to k-shade
> 
> Thanks!

✅  Fixed

**Comment by exezbcz** [comment]
> > > navbar links should have the same hover effect as footer links
> > 
> > 
> > 
> > * this was only for light mode, now it looks like its changed in dark mode as well
> > 
> > ## Dark mode
> > image
> > 
> > * should be same as the under search links - that means to k-shade
> > 
> > Thanks!
> 
> ✅ Fixed

ah, few more things :D 
image
image
- can you apply it here too?

**Review by roiLeo — APPROVED** [review]
code lgtm

**Comment by vikiival** [comment]
@exezbcz if it is ok, we can merge

**Comment by Jarsen136** [comment]
> 
> ah, few more things :D image image
> 
> * can you apply it here too?

✅ DONE

**Comment by exezbcz** [comment]
@vikiival yes

**Comment by vikiival** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 40.35 USD/KSM ~ 0.496 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xf5eec30796e1a933d153ce4e63a838c6cf1c229fdbe406c6b1396aed01758c9c](https://kusama.subscan.io/extrinsic/0xf5eec30796e1a933d153ce4e63a838c6cf1c229fdbe406c6b1396aed01758c9c)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 5 USD/DOT ~ 4 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0xdc4da965ea4c044c4e880d5f78ecb10c3d0ec56915389d5bb8f47a8ec0426025](https://polkadot.subscan.io/extrinsic/0xdc4da965ea4c044c4e880d5f78ecb10c3d0ec56915389d5bb8f47a8ec0426025)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
