### PR TITLE
⚒️ missing mediaUri meta

### LINKED ISSUE #2836: Missing nfts in profile created tab
### What happened?

A bug happened!

### Please reproduce in steps

- Go to `/rmrk/u/DVa676uebTkgH8uZyS2umio7JtmkcSHHoPvPJJQY3bbYoAu`
- See missing nfts

### Expected Behavior

I've expected to see all nfts

### What browsers are you seeing the problem on?

Firefox

### Are you logged in?

_No response_

### At which address did you encounter bug?

beta.kodadot.xyz, kodadot.xyz

### Screenshots

Capture d’écran 2022-04-13 à 8 41 49 AM

### Relevant log output

```shell
None
```

### Payment link for reward

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by roiLeo**
⚠️ need to be tested, page with multiple media video is slow

### PR type

- [x] Bugfix

### What's new?

- [x] PR closes #2836 
- [x] missing `meta.mediaUri`
- [x] fix `/rmrk/u/DVa676uebTkgH8uZyS2umio7JtmkcSHHoPvPJJQY3bbYoAu`
- [x] fix `/rmrk/detail/12009176-289d0e953cbdc59a73-HHK-0072_HYPEHELL_KEYCHAIN-0000000000000072`
- [x] fix `/rmrk/collection/289d0e953cbdc59a73-HHK`

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=HguGafrfk8nRP9a4tgJf7hLvSSFie8GtkDjyWFHQ2kDUAMc)

### CODE REVIEW

**Comment by vikiival** [comment]
https://github.com/rmrk-team/rmrk-tools/blob/530223d0da9a4fb2b7e2f6b9fb82e545ae988cf1/src/rmrk2.0.0/tools/types.ts#L40

**Comment by vikiival** [comment]
pay 75 usd

**Comment by vikiival** [comment]
@yangwao looks like the bot failed

**Comment by yangwao** [comment]
pay 75 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $75 @ 158.05 USD/KSM ~ 0.475 $KSM
🧗 [HguGafrfk8nRP9a4tgJf7hLvSSFie8GtkDjyWFHQ2kDUAMc](https://kusama.subscan.io/account/HguGafrfk8nRP9a4tgJf7hLvSSFie8GtkDjyWFHQ2kDUAMc)
🔗 [0xfecb0199096f022d13e3a15cc0d6def192c6c75f96e7f6b0c618a2426761d124](https://kusama.subscan.io/extrinsic/0xfecb0199096f022d13e3a15cc0d6def192c6c75f96e7f6b0c618a2426761d124)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
I have changed nothing. 
Sometimes GH webhooks fails. 😅

**Pull request merged**
