### PR TITLE
add to faq

### LINKED ISSUE #1015: Royalties, make and accept offer add to faq
Add to faq

"We've been long working with https://bsx.fi team to have working **royalties, make an offer and accept an offer** for creators. Therefore we are offering this preview of the feature set what would be possible on MetaPrime.network once it will be part of Kusama.network. Current implementation on BSX is in beta, testing with a private group of folks. Whenever you want to test with us, visit qa-lobby channel on our discord https://discord.gg/35hzy2dXXh"

### PR DESCRIPTION
**Pull request by thea-exe**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [X] Refactoring

### What's new?

- [x] PR closes #1015
- [ ] Requires deployment <rubick/magick_issue>
- [ ] Added quote to FAQ & fixed grammar

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
-  [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screen Shot 2022-07-11 at 11 23 15 AM

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
>     1. I put the quote under "Royalties streams settings?" because we are currently saying that we have no chain logic for it. I thought it would be a good idea to put it under that question because it's an update regarding it. Let me know if I should change the location!

Ok!

>     2. The links are BROKEN, I would like some guidance on how links are formatted

see my comment, you can take example on any links on this file

>     3. I think I need to update the other languages? I forgot the process so please remind me!

There is no process lol, we fallback to default english when no translation can be found.
For the moment it's fine like this, afterwards you can try to modify each translation file by hand but it's a bit of a headache.

**Comment by petersopko** [comment]
@thea-exe any updates on this? :) I see some changes requested, let's fix and merge

**Comment by thea-exe** [comment]
Thank you for the reminder!

**Review by roiLeo — APPROVED** [review]
✅ thanks for the changes! lgtm

**Pull request merged**
