### PR TITLE
fix: Small cards mobile layout

### LINKED ISSUE #8515: Small cards mobile layout
There should be two cards next to each other in the explore on mobile
- since there is no option to change layout

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #8515

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2023-12-12 at 11 39 46

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 7588a54</samp>

Increased the number of columns for the `DynamicGrid` component on mobile devices to improve layout and responsiveness. Modified the file `components/shared/DynamicGrid.vue` accordingly.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 7588a54</samp>

> _`Dynamic grid` grows_
> _Two columns for mobile screens_
> _Springtime of layout_

### CODE REVIEW

**Comment by hassnian** [comment]
@exezbcz  ui check thanks

**Comment by prury** [comment]
collections got wrecked 😄 : 

image

**Comment by hassnian** [comment]
@prury fixed

**Review by Jarsen136 — APPROVED** [review]

**Review by daiagi — APPROVED** [review]
code looks ok
but won't it make more sense to have 1 colum by default and then overwrite it in explore?

**Comment by hassnian** [comment]
> code looks ok but won't it make more sense to have 1 colum by default and then overwrite it in explore?

yep indeed fixed

**Pull request merged**
