### PR TITLE
fix: collectionListWithSearch doesnot work

### LINKED ISSUE #3321: collectionListWithSearch doesn't work with https://api.subquery.network/sq/vikiival/magick
### What happened?

A bug happened!
when type some keywords in search bar, `collectionListWithSearch` query doesn't work with `https://api.subquery.network/sq/vikiival/magick`

### Please reproduce in steps

Go to ... Click on .... See error

### Expected Behavior

I've expected ...
query successfully

### What browsers are you seeing the problem on?

_No response_

### Are you logged in?

_No response_

### At which address did you encounter bug?
https://beta.kodadot.xyz/

### Screenshots

Paste from your clipboard or upload screenshots/video
截屏2022-07-03 下午12 19 53
截屏2022-07-03 下午12 20 19

### Relevant log output

_No response_

### Payment link for reward

Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3321
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
This fix only RMRK chain, doesn't work with bsx.

By the way the number of query sent when I type in the search bar is huge!

**Comment by roiLeo** [comment]
For now it fix the error but there big chance this will come back after #3161
we need to use subsquid instead of magick in Searchbar

it's more of a temporary fix, should we merge it?

**Review by petersopko — COMMENTED** [review]
looks like this solves 
- https://github.com/kodadot/nft-gallery/issues/3393

I say let's merge this even if this needs to be reworked later as @roiLeo mentioned.

I think this was introduced by the multiple sorting options:
- https://github.com/kodadot/nft-gallery/pull/3067

**Comment by petersopko** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 48.93 USD/KSM ~ 1.022 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xa0e6e4f9727bbddd5aee2d3c480782b58269a885c8f178d2da4bb830cfdac443](https://kusama.subscan.io/extrinsic/0xa0e6e4f9727bbddd5aee2d3c480782b58269a885c8f178d2da4bb830cfdac443)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
