### PR TITLE
add `eslint` in lint-staged

### LINKED ISSUE #3777: Husky pre-commit sort-imports
Since a new eslint rule has been introduce [sort-imports](https://eslint.org/docs/rules/sort-imports), we may need to auto fix this on commit hook

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3777 

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged the recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by preschian** [comment]
@roiLeo btw, I couldn't find a prettier-plugin which compatible with vue and sort-imports so for now loosen some of the configs

**Comment by roiLeo** [comment]
User story:
_As a dev, when I edit a file, I want to auto fix imports order on commit the same way we do to fix indentation_ 

Is Volar dependencies necessary? I personally use Vetur

Why don't we run `eslint --fix` on edited files?

**Comment by preschian** [comment]
> Is Volar dependencies necessary? I personally use Vetur

I just followed the instruction https://github.com/simonhaenisch/prettier-plugin-organize-imports#vuejs. for Vue3, Volar replace Vetur, and Volar support Vue2 https://marketplace.visualstudio.com/items?itemName=Vue.volar

> Why don't we run `eslint --fix` on edited files?

oh, ok will also add eslint in lint-staged. will be useful for fixing the rule from `plugin:vue/recommended`. but, for `sort-imports` still not able auto fix correctly when I tested in the `.vue` file. on `.ts` files should be no problem

**Comment by roiLeo** [comment]
> I just followed the instruction https://github.com/simonhaenisch/prettier-plugin-organize-imports#vuejs. for Vue3, Volar replace Vetur, and Volar support Vue2 https://marketplace.visualstudio.com/items?itemName=Vue.volar

Ok, I'll try Volar never had problem with Vetur

> oh, ok will also add eslint in lint-staged. will be useful for fixing the rule from `plugin:vue/recommended`. but, for `sort-imports` still not able auto fix correctly when I tested in the `.vue` file. on `.ts` files should be no problem

It looks like it work only when imports are in between "{ }" in vue files

Do we still need `prettier-plugin-organize-imports` dep?

**Comment by preschian** [comment]
> Do we still need prettier-plugin-organize-imports dep?

seems like not needed, will remove it 👍

**Review by roiLeo — APPROVED** [review]
Works well! I've try to edit a file with this config and it's fixed after commit.

**Review by petersopko — APPROVED** [review]

**Comment by preschian** [comment]
thanks for the merge. the other PR causing error in `deepsource` because `sort-imports` rules. should be fine for now

sorry for the inconvenience 🙏🏻

**Pull request merged**
