### PR TITLE
#5132 Gallery item detail description

### LINKED ISSUE #5132: Gallery item detail description at 770px
image

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5132
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by roiLeo — CHANGES_REQUESTED** [review]
break mobile container

**Review by roiLeo — APPROVED** [review]
weird fix but ok.

**Comment by Jarsen136** [comment]
I could still reproduce it on the smaller screen in your preview env
image

**Comment by yangwao** [comment]
Don't want to break something on production

**Comment by prachi00** [comment]
> I could still reproduce it on the smaller screen in your preview env image

can you tell me the exact screen size? not happening for me

**Comment by Jarsen136** [comment]
> 
> can you tell me the exact screen size? not happening for me

 the screen with is shorter than 315px
image

**Comment by prachi00** [comment]
> > can you tell me the exact screen size? not happening for me
> 
> the screen with is shorter than 315px image

@Jarsen136 should we even support screens that are shorter than 315 px? I dont think any smartphone has that, right? 
https://accessally.com/blog/mobile-responsive-screen-sizes/
according to this, iphone 5 has the smallest screen currently at 320px
I dont think we need to handle this, what do you think?

**Comment by Jarsen136** [comment]
> @Jarsen136 should we even support screens that are shorter than 315 px? I dont think any smartphone has that, right? https://accessally.com/blog/mobile-responsive-screen-sizes/ according to this, iphone 5 has the smallest screen currently at 320px I dont think we need to handle this, what do you think?

Alright, let it go.

**Review by Jarsen136 — APPROVED** [review]

**Comment by vikiival** [comment]
pay 10 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $10 @ 34.88 USD/KSM ~ 0.287 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0xc0b09582e282d0a52e5411a4071173c442b101035acb4d45b21d7d3337dd9ebf](https://kusama.subscan.io/extrinsic/0xc0b09582e282d0a52e5411a4071173c442b101035acb4d45b21d7d3337dd9ebf)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
