### PR TITLE
fix: Collection page can't change prefix

### LINKED ISSUE #11294: Collection page can't change prefix
https://github.com/user-attachments/assets/992224bb-818b-4b7b-ab42-35073d122d6f

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #11294

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

https://github.com/user-attachments/assets/ca2cb996-49a9-4eba-a633-fd268a5ec6ab

### CODE REVIEW

**Review by Jarsen136 — COMMENTED** [review]
I can't reproduce the bug as on the original issue. I also can't understand why we make this change. Could you pls provide the output of `routeName` on your side?

**Comment by hassnian** [comment]
> I can't reproduce the bug as on the original issue. I also can't understand why we make this change. Could you pls provide the output of `routeName` on your side?

Mb didn't provide context 

You have to be in one of the other tabs (activity or swaps) , selecting those adds '-activity' '-swaps' at the end of the route name, the old code did not catch those cases

**Comment by Jarsen136** [comment]
> > I can't reproduce the bug as on the original issue. I also can't understand why we make this change. Could you pls provide the output of `routeName` on your side?
> 
> Mb didn't provide context
> 
> You have to be in one of the other tabs (activity or swaps) , selecting those adds '-activity' or '-swaps' at the end of the route name, the old code did not catch those cases

Got it, thanks! It's kind of a special case on the collection page. Adding a comment above that line may help.

**Review by Jarsen136 — APPROVED** [review]

**Review by vikiival — APPROVED** [review]

**Comment by preschian** [comment]
Let's add it to the unit/e2e testing for every bug-fix PR, if possible. I think bug fixes that do not require chain interaction are easier to include in the unit/e2e testing

**Comment by preschian** [comment]
> Let's add it to the unit/e2e testing for every bug-fix PR, if possible. I think bug fixes that do not require chain interaction are easier to include in the unit/e2e testing

cc @hassnian just minor stuff 🤏🏻

**Pull request merged**
