### PR TITLE
feat: Hover card changes

### LINKED ISSUE #10457: Hover card changes
# Design
image

## anatomy 
- profile picture
- follow button - has the same states as on the profile 
- offchain name, if no offchain name, display address
- underneath the name, there is address, and 16px icon to copy, the address is copiable all over the address and the icon 
- divider
- nfts created count
- follower count
- 2 latest creations/latest buys - lets experiment with that 

## File
image

updated here: https://www.figma.com/design/JXNtryaNYhY0XJNArzvPQx/Handoff?node-id=1287-18959&t=7EV2FWXqowv0DK9U-11

## darkmode 
- follows color pair rules

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #10457

## Needs QA check

- @kodadot/qa-guild please review

## Needs Design check

- @exezbcz please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2024-06-17 at 16 00 18

### CODE REVIEW

**Comment by prury** [comment]
i think profile image should be clickable and lead to profile instead of clicking on address to go to profile, wdyt @exezbcz ?

**Comment by exezbcz** [comment]
maybe i wrote it wrong, this should be clickable and redirect to a profile 
image

**Comment by exezbcz** [comment]
@prury yeah we can add redirect there as well

**Comment by hassnian** [comment]
> maybe i wrote it wrong, this should be clickable and redirect to a profile

> i think profile image should be clickable and lead to profile instead of clicking on address to go to profile

done

CleanShot 2024-06-18 at 09 12 47

**Review by preschian — APPROVED** [review]

**Review by Jarsen136 — APPROVED** [review]

**Pull request merged**
