### PR TITLE
fix: Modal loading styling

### LINKED ISSUE #8287: Modal loading styling
image
somehow we missed the dark mode 
- the skeleton should respect the neutral color pairing 

more on that here
- #8137

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #8287

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2023-12-01 at 10 20 44

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at be42cbf</samp>

Changed the `k-grey-light` color variable to a darker shade for better text contrast on the dark theme. This was part of a pull request to fix some dark mode UI issues.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at be42cbf</samp>

> _`k-grey-light` shifts_
> _contrast and readability_
> _autumn leaves darken_

### CODE REVIEW

**Comment by hassnian** [comment]
@exezbcz pls ui check 

not sure if I did it right 

light : #ECECEC as per design 
dark: #454545 couldn't find the opposite of light

**Comment by exezbcz** [comment]
@hassnian regarding colors, please always refer to this system 

image
- in the row there are color pairs 

https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=5311%3A18771&mode=design&t=IgTCX5nB2C4yuxT0-1



Based on the naming, it should be this pair 

image
- neutral 3 for light

this is the newer modal with loading, where I am actually also using grey colors 
image


updated this one 
image


thanks!

**Review by roiLeo — APPROVED** [review]
code lgtm

**Comment by yangwao** [comment]
thanks!
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 5.56 USD/DOT ~ 3.597 $DOT
🧗 [13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh](https://polkadot.subscan.io/account/13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)
🔗 [0xafdf9ef9e75da4306544d3ef933458d5965df57bde06f2a88846c05a8f4999cb](https://polkadot.subscan.io/extrinsic/0xafdf9ef9e75da4306544d3ef933458d5965df57bde06f2a88846c05a8f4999cb)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
