### PR TITLE
release update

### PR DESCRIPTION
**Pull request by vikiival**
Release Update 

- https://github.com/kodadot/nft-gallery/pull/10285
- https://github.com/kodadot/nft-gallery/pull/10275
- https://github.com/kodadot/nft-gallery/pull/10272
- https://github.com/kodadot/nft-gallery/pull/10266
- https://github.com/kodadot/nft-gallery/pull/10265
- https://github.com/kodadot/nft-gallery/pull/10257
- https://github.com/kodadot/nft-gallery/pull/10255
- https://github.com/kodadot/nft-gallery/pull/10252
- https://github.com/kodadot/nft-gallery/pull/10250
- https://github.com/kodadot/nft-gallery/pull/10248
- https://github.com/kodadot/nft-gallery/pull/10239
- https://github.com/kodadot/nft-gallery/pull/10238
- https://github.com/kodadot/nft-gallery/pull/10235
- https://github.com/kodadot/nft-gallery/pull/10232
- https://github.com/kodadot/nft-gallery/pull/10226
- https://github.com/kodadot/nft-gallery/pull/10219
- https://github.com/kodadot/nft-gallery/pull/10217
- https://github.com/kodadot/nft-gallery/pull/10211
- https://github.com/kodadot/nft-gallery/pull/10208
- https://github.com/kodadot/nft-gallery/pull/10206
- https://github.com/kodadot/nft-gallery/pull/10201
- https://github.com/kodadot/nft-gallery/pull/10196
- https://github.com/kodadot/nft-gallery/pull/10195
- https://github.com/kodadot/nft-gallery/pull/10192
- https://github.com/kodadot/nft-gallery/pull/10186
- https://github.com/kodadot/nft-gallery/pull/10182
- https://github.com/kodadot/nft-gallery/pull/10180
- https://github.com/kodadot/nft-gallery/pull/10176
- https://github.com/kodadot/nft-gallery/pull/10173
- https://github.com/kodadot/nft-gallery/pull/10172

### CODE REVIEW

**Comment by vikiival** [comment]
cc @prury are there any bugs which should be merged into prod ?

**Comment by prury** [comment]
> cc @prury are there any bug fixes which should be merged into prod ?

making a fast comparison, i think this release is pretty much the sum of what we merged to beta + recent merged stuff

- https://github.com/kodadot/nft-gallery/pull/10263

in my mind it worked differently, like the following:

batch 1 of PRs goes to beta and then release PR would merge this same batch into prod

what do i think its happening:

batch 1 of PRs goes to beta and then release PR would merge batch1 + newbatch into prod

**Comment by vikiival** [comment]
Yes, 

they are the same, Q is if there is anything in beta that needs to be fixed, or is it safe to release this one

**Comment by prury** [comment]
> Yes,
> 
> they are the same, Q is if there is anything in beta that needs to be fixed, or is it safe to release this one

i believe it is safe, i will check prod right after, ty

**Pull request merged**
