### PR TITLE
Showing last NFT mint from user profile in OG:image

### PR DESCRIPTION
**Pull request by miguel-quezada63**
From issue #287. og:image was missing from link cards shown on social media platforms. Added og:image meta property in which displays the user's latest NFT that is an image.

### CODE REVIEW

**Comment by yangwao** [comment]
Do you think you could stretch your PR to other OG-related issues we have? 
There are also bounties :)
You can feel free to set netlify setup or preview through PR here.
https://github.com/kodadot/nft-gallery/issues/117
https://github.com/kodadot/nft-gallery/issues/118

**Comment by miguel-quezada63** [comment]
@yangwao I will take a look at these other issues. I left some comments on them in order to get some clarification. Whenever you get the chance may you please take a look.

**Comment by yangwao** [comment]
Yes, @miguel-quezada63 just replied https://github.com/kodadot/nft-gallery/issues/287#issuecomment-829085201 :)
Found there is also #243 issue which could be merged with this

**Comment by yangwao** [comment]
Checking through https://cards-dev.twitter.com/validator url https://deploy-preview-306--nftkodadot.netlify.app/rmrk/u/Dx6nVUy6f2znn4ZwNZ3TGbEyUz3FLbCRGQGKAut4LxjCVRs
looks neat @miguel-quezada63 
image

**Comment by yangwao** [comment]
Hey, let me merge this as it's feasible to work.
Post your KSM address. 
We owe you a bounty ~ $100 :)

**Comment by yangwao** [comment]
Hey, let me merge this as it's feasible to work.
Post your KSM address. 
We owe you a bounty ~ $100 :)

**Comment by yangwao** [comment]
Hey, @miguel-quezada63  let me merge this as it's feasible to work.
Post your KSM address. 
We owe you a bounty ~ $100 :)

Feel free to continue on 
- https://github.com/kodadot/nft-gallery/issues/287 
- https://github.com/kodadot/nft-gallery/issues/243 

there are bounties too!

**Comment by miguel-quezada63** [comment]
@yangwao definitely will continue to work on other issues related to SEO.

For the bounty, my KSM address is:
JFPBQxThSDUwMYAerdBssm7u7KJBf966u5MMysnC5pB2rgo

**Comment by yangwao** [comment]
Sent! https://kusama.subscan.io/account/JFPBQxThSDUwMYAerdBssm7u7KJBf966u5MMysnC5pB2rgo

Perfect, looking forward for #243 :)

**Pull request merged**
