### PR TITLE
#7779 explore chain dropdown label

### LINKED ISSUE #7779: Remove beta from explore networks dropdown
- it is causing responsivity issues on mobile and IMO, it does not look good, 
- it can be kept in the dropdown, but not in the main button please 
image
- after the change, please check explore/assethub on mobile, the buttons should not be distributed over 3 rows

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #7779
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)

## Screenshot 📸

- [x] My fix has changed UI
Screen Shot 2023-10-24 at 8 01 03 PM
Screen Shot 2023-10-24 at 8 01 07 PM

### CODE REVIEW

**Comment by prachi00** [comment]
@exezbcz is this okay?

**Comment by prury** [comment]
truncating may not be the best solution because of Kusama:
Kusama shows as Kusama 
and Kusama Assethub shows as Kusama...
and still, on smaller screens, long names like Snek[Rococo] still takes 3 rows

possible solutions(not ideal): 
- remove 'network'
- rename network to 'chain'
- use prefixes, ahp, ahk, bsx

let's see what exez thinks

**Comment by exezbcz** [comment]
> * remove 'network

letsgo with this for mobile please, good idea @prury

**Comment by prachi00** [comment]
@prury @exezbcz 
Screen Shot 2023-10-25 at 7 57 25 PM
Screen Shot 2023-10-25 at 7 57 29 PM
Screen Shot 2023-10-25 at 7 57 36 PM

**Review by roiLeo — APPROVED** [review]

**Comment by yangwao** [comment]
thanks!
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 4.35 USD/DOT ~ 4.598 $DOT
🧗 [13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1](https://polkadot.subscan.io/account/13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)
🔗 [0xdf19cd95a78a7207bccfd4452eabe5584b4a9dc5eee10681e2989434ac513d66](https://polkadot.subscan.io/extrinsic/0xdf19cd95a78a7207bccfd4452eabe5584b4a9dc5eee10681e2989434ac513d66)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
