### PR TITLE
history of gallery item for muti chain

### LINKED ISSUE #3409: History in top nav in BSX shows RMRK nfts
### What happened?

A bug happened

Screen Shot 2022-07-10 at 6 14 54 PM

### Please reproduce in steps

Go to ... Click on .... See error

### Expected Behavior

I've expected ...

### What browsers are you seeing the problem on?

_No response_

### At which address did you encounter bug?

_No response_

### Are you logged in?

_No response_

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

_No response_

### Screenshots

Paste from your clipboard or upload screenshots/video

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3409 
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

image

### CODE REVIEW

**Comment by Jarsen136** [comment]
It's still in progress. Found a strange bug.
image

**Comment by Jarsen136** [comment]
> It's still in progress. Found a strange bug. image

- [x] Already Fixed. It's a bug exist for a long time.

- [x] Support history item for Moonsame

**Comment by Jarsen136** [comment]
✅ Support history item for Moonsame.

**Review by petersopko — COMMENTED** [review]
I can't seem to get any history for BSX? tried multiple search terms, nothing shows up in the searchbar

**Comment by Jarsen136** [comment]
> I can't seem to get any history for BSX? tried multiple search terms, nothing shows up in the searchbar

I think the origin issue means fixing the history item on nav bar?

image

As for the search history, it's another topic related to https://github.com/kodadot/nft-gallery/issues/3293

**Comment by petersopko** [comment]
> > I can't seem to get any history for BSX? tried multiple search terms, nothing shows up in the searchbar
> 
> I think the origin issue means fixing the history item on nav bar? Try to open some gallery item page, then you could see it. 

Well all of the searchbars are in navbar now, but only now I read we support this history feature only on gallery item detail, that seems weird to me. I was trying to reproduce it here 😆 don't we want to support this in gallery / collections as well? 

https://user-images.githubusercontent.com/73316633/179351033-4240ab34-aa85-4173-a29a-3727c9caaad9.mp4

**Comment by yangwao** [comment]
> don't we want to support this in gallery / collections as well?

Past searches should appear in the search bar afaik, but only on RMRK, I bet? 
But it would be good to have them for bsx for sure.  

With history gallery items, the component is aimed just for items rn, if you lurk old issues on history v1.1 or so, you'll find that we would like to show them there in a similar fashion to Spotify mobile on Android, where it could also see collections but turns out it's pretty complicated and rather would keep it on hold and focus on making some existing components to work 

- https://github.com/kodadot/nft-gallery/issues/1814

**Comment by Jarsen136** [comment]
✅ Support search history on BSX

Though it's still another topic related to Search bar instead of History component imo. 😂 


image

**Review by petersopko — COMMENTED** [review]
lgtm

**Comment by petersopko** [comment]
> turns out it's pretty complicated and rather would keep it on hold and focus on making some existing components to work

ok 👍🏻

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 58.6 USD/KSM ~ 1.706 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x4288ed465a0ddf08f407bff7bd7b318a87fdd3214f2767ca1b1ed868f4aa13a8](https://kusama.subscan.io/extrinsic/0x4288ed465a0ddf08f407bff7bd7b318a87fdd3214f2767ca1b1ed868f4aa13a8)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
