### PR TITLE
fix: Create drop down overflowing

### LINKED ISSUE #6267: Create drop down overflowing
telegram-cloud-photo-size-4-5798493960757428068-x
- use "?redesign=true" on the canary to reproduce

### LINKED ISSUE #6268: Make mass mint available for everyone
image

We will make it available for the public, and we will do the silent release 👀

Apparently some CSS flex is required here too 😉

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/4964#issuecomment-1596133660_

### PR DESCRIPTION
**Pull request by Jarsen136**
- [x] Closes #6267
- [x] Closes #6268

image

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
Hey just saw that right part of "Waifu" link is not clickable 

Capture d’écran 2023-06-19 à 10 22 07 AM

**Comment by exezbcz** [comment]
@preschian +1

Space on the right is too low, can you please increase it 👀 

Thanks!

**Comment by Jarsen136** [comment]
✅ Updated

**Comment by prury** [comment]
looks good in terms of functionality
working properly on mobile

**Comment by preschian** [comment]
time to release mass mint also? https://github.com/kodadot/nft-gallery/issues/6268

**Review by vikiival — APPROVED** [review]

**Comment by Jarsen136** [comment]
> time to release mass mint also? #6268

✅ done

**Comment by vikiival** [comment]
Screenshot 2023-06-21 at 13 35 37

CLicking faster

**Comment by vikiival** [comment]
pay 15 usd

**Pull request merged**
