### PR TITLE
1657 resolve manifest warnings and optimize icon

### LINKED ISSUE #1657: Clear out errors from manifest.json
Seems we've got some errors

image

image

image

too much glitches in this desert cake

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇  _ Do a quick check before the merge. 

### PR type
- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
Screenshot 2022-01-02 at 16 27 51
Screenshot 2022-01-02 at 16 05 37

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything works
- [ ] I found edge cases

### What's new?
- [x] PR closes #1657
- [x] resolve warnings in manifest file and added safe padding correctly

### Had issue bounty label ?
- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation
- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [ ] My fix has changed **something** on UI, a screenshot for others, is best to understand changes.

### CODE REVIEW

**Comment by yangwao** [comment]
hmm if we are changing logos everywhere, what's about favicon? 

image

**Comment by kkukelka** [comment]
> hmm if we are changing logos everywhere, what's about favicon?
> 
> image

yes, good catch. gonna append it to this PR. just give me a minute

**Comment by kkukelka** [comment]
@yangwao done
Screenshot 2022-01-02 at 17 08 38

**Comment by yangwao** [comment]
Perfect, I’ve sent the payout https://kusama.subscan.io/extrinsic/0x9706a64c3b009d960d08f160fa2666f70758a616004ca276aeef38ec5c1c9fcb

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/

**Pull request merged**
