### PR TITLE
fix: wrong route path

### LINKED ISSUE #4874: wrong route path from searchbar in explore items
### Step to reproduce
- go to beta.kodadot.xyz (bsx chain)
- click on "Explore"
- click on "Items" tab
- type "kitty" in searchbar
- press enter
- profit! (url is `/bsx/explore/bsx/explore/items?page=1&search=kitty` instead of `/bsx/explore/items?page=1&search=kitty`)

### PR DESCRIPTION
**Pull request by maderi21**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4874 
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [x] I've tested it at </bsx/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=JHJGu2aWyAFBfcso8bR7ma82p15YAavyN6vQfJyWuhniNGa)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by Jarsen136 — APPROVED** [review]
code lgtm

**Review by roiLeo — APPROVED** [review]
✅ nice, wfm!

**Comment by yangwao** [comment]
pay 40 usd - it was super quick @maderi21

**Comment by yangwao** [comment]
pay 40 usd

**Pull request merged**
