### PR TITLE
💅 top collection responsive & new landing font

### PR DESCRIPTION
**Pull request by roiLeo**
### PR type

- [x] Bugfix
- [x] Feature
- [x] Refactoring

### What's new?

- [x] PR related #4059
- [x] "Work Sans" font in new landing
- [x] move `fonts.scss` file
- [x] fix "See More" link
- [x] fix top collection responsiveness (tablet & small screen)

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DVYy1qnocE8t6ZvUfPx3rEjG829khNRXx3YrCGVHHj19Lcb)

### Screenshot

Screenshot 2022-10-03 at 10-11-29 KodaDot - Kusama NFT Market Explorer

### CODE REVIEW

**Comment by petersopko** [comment]
@roiLeo to followup from the issue:

> size of screen? Numbers are big, it make multiple lines, I might reduce the collection name text

screen was 16 inch, looks very well now ✅

**Comment by roiLeo** [comment]
> just one thing, don't we want to include some formatting to the numbers?
> 
> image
> 
> kinda hard to read, or is it just me?

I completely agree, ref #3355

**Review by petersopko — APPROVED** [review]
wfm

**Review by kkukelka — APPROVED** [review]
code lgtm

**Comment by kkukelka** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 42.38 USD/KSM ~ 2.36 $KSM
🧗 [DVYy1qnocE8t6ZvUfPx3rEjG829khNRXx3YrCGVHHj19Lcb](https://kusama.subscan.io/account/DVYy1qnocE8t6ZvUfPx3rEjG829khNRXx3YrCGVHHj19Lcb)
🔗 [0xc034b1e149b1a2dc09ceb04fb55271f974c1e53e5090cb9a80bacdf58d764a04](https://kusama.subscan.io/extrinsic/0xc034b1e149b1a2dc09ceb04fb55271f974c1e53e5090cb9a80bacdf58d764a04)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
