### PR TITLE
Show art in original format 

### PR DESCRIPTION
**Pull request by AndreyGrin**
Hey, here is still some issues like not sure how to include new icons correctly so Fullscreen button doesn't have it right now.

### CODE REVIEW

**Comment by AndreyGrin** [comment]
hm, actually I see that on deploy preview icons works fine... So, waiting for feedback :)

**Comment by AndreyGrin** [comment]
@yangwao have a look plz

**Comment by yangwao** [comment]
Checking https://deploy-preview-386--nftkodadot.netlify.app/rmrk/detail/7500338-124a3f95695165ff10-CZJSF-M_KWIATKOWSKI_TIME_RACE_BIKE_PINARELLO-0000000000000001

Looks good tho! But probably would be nice to tune the cards component to be design native or we can come up with something else 

### theatre mode
- probably we could make it default? or on theatre mode it preserves original dimensions?

###  price component 
- design
image

- probably we could use something more native to design?
image

### facts card 
- probably remove shadows?

### on mobile
I would probably full screen button?

**Comment by vikiival** [comment]
Closes #372 

This is Really nice!
However I aggree with @yangwao 's suggestions

**Comment by AndriiHrynchuk** [comment]
I agree as well)
but, how to show USD only price? I know how to show KSM from previous PR so then I can tune up price block.

Theatre mode uses 12 columns and height:auto. If use by default, will be quite stupid for portrait images.
Default: fits into 6 columns.
Full: fit browser height and width:auto.

I can make cards look this way, but it will be global change (can be local as well, but probably doesn't make sense.)
Screenshot 2021-05-17 at 21 04 14
Screenshot 2021-05-17 at 21 04 32

**Comment by yangwao** [comment]
> I agree as well)
> but, how to show USD only price? I know how to show KSM from previous PR so then I can tune up price block.

I mean, let's skip USD In this iteration 👯 

> Theatre mode uses 12 columns and height:auto. If use by default, will be quite stupid for portrait images.
> Default: fits into 6 columns.
> Full: fit browser height and width:auto.
> 

> I can make cards look this way, but it will be global change (can be local as well, but probably doesn't make sense.)
> Screenshot 2021-05-17 at 21 04 14
> Screenshot 2021-05-17 at 21 04 32

okay let's go with global :)


I found that would be nice to style this actions part as well 

image

**Comment by AndriiHrynchuk** [comment]
Reserved place and styles for USD (commented in the code)
Screenshot 2021-05-18 at 22 34 00

@yangwao Can you give me a link to NFT where some emotions already exists?
Screenshot 2021-05-19 at 02 24 07

I realised that card component won't be globally changed as there is no real component, just used same html code. So if you would like to apply new styles somewhere else, just include this to the file
<style scoped lang="scss">
@import "@/colors";
@import "@/typography";
</style>

**Comment by yangwao** [comment]
> Can you give me a link to NFT where some emotions already exists?
Here is the one https://deploy-preview-386--nftkodadot.netlify.app/rmrk/detail/6745804-3CD8C53D036D48B952-SX-SONG_FOR_A_XENOMORPH-0000000000000001

I would remove this shadow from the card when unfolded?
image
image

Otherwise I guess it looks perfect :)

**Comment by AndreyGrin** [comment]
Screenshot 2021-05-20 at 23 55 59
styled Appreciations block and this is how screen looks now

**Comment by yangwao** [comment]
> Screenshot 2021-05-20 at 23 55 59
> styled Appreciations block and this is how screen looks now

Perfect, for me, is looks awesome! :)

cc @vikiival

**Comment by vikiival** [comment]
674B2595-29A6-4721-8A92-049DDDEAC5FD

tbh I love it. 

Just two small things:

- [ ] I have a horizontal scrollbar on the phone (maybe I have too small resolution: iPhone 8)
- [ ] I would like to have padding from the left and right (so data are not so close to the edge) 

Is it possible to fix these things please ?
Otherwise I love it

**Comment by AndreyGrin** [comment]
I will check and update mobile today

**Comment by AndreyGrin** [comment]
@vikiival @yangwao now it should be good on mobile as well

**Comment by yangwao** [comment]
Seems perfect on mobile! 
Can silently launch till @xylodrone will make tutorials :)

**Comment by vikiival** [comment]
@yangwao does this happen to you ? 
Screenshot 2021-05-24 at 12 30 24

**Comment by yangwao** [comment]
Nope, try refreshing?

**Pull request merged**
