### PR TITLE
fix: Swap collection and blockchain fields in minting

### LINKED ISSUE #9023: Swap these two fields in minting
Create - single NFT:

these two fields should be swapped. first people should choose blockchain then collection.

Pls swap

Screenshot 2024-01-16 at 17 24 15

### PR DESCRIPTION
**Pull request by iMac7**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #9023 
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=14dLrAvjDw7cFLaxM7VWR6YtHd7bGZY2QpzXDhAJJ4yv6oGw&usdamount=100)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]

**Review by preschian — APPROVED** [review]
hi, please use PR template https://github.com/kodadot/nft-gallery/blob/main/.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md

otherwise lgtm

**Comment by prury** [comment]
> **Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).
> 
> 👇 __ Let's make a quick check before the contribution.
> ## PR Type
> 
>     * [x]  Bugfix
> 
>     * [ ]  Feature
> 
>     * [ ]  Refactoring
> 
> 
> ## Context
> 
>     * [x]  Closes [Swap these two fields in minting #9023](https://github.com/kodadot/nft-gallery/issues/9023)
> 
>     * [ ]  Requires deployment <snek/rubick/worker>
> 
> 
> #### Before submitting pull request, please make sure:
> 
>     * [x]  My contribution builds **clean without any errors or warnings**
> 
>     * [x]  I've merged recent default branch -- **main** and I've no conflicts
> 
>     * [x]  I've tried to respect high code quality standards
> 
>     * [x]  I've didn't break any original functionality
> 
> 
> #### Optional
> 
>     * [ ]  I've tested it at </ksm/collection>
> 
>     * [x]  I've tested PR on mobile
> 
>     * [ ]  I've written unit tests 🧪
> 
>     * [ ]  I've found edge cases
> 
> 
> #### Did your issue had any of the "$" label on it?
> 
>     * [ ]  Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=%3CMy_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address%3E)
> 
> 
> #### Community participation
> 
>     * [x]  [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)
> 
> 
> ## Screenshot 📸
> 
>     * [x]  My fix has changed **something** on UI; a screenshot is best to understand changes for others.
>       image

edit your first post with the message you wrote above

**Comment by prury** [comment]
@iMac7 edited the first message on this PR for you, please insert your DOT address there

**Comment by iMac7** [comment]
Done!

**Comment by yangwao** [comment]
thanks!
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 7.06 USD/DOT ~ 2.833 $DOT
🧗 [14dLrAvjDw7cFLaxM7VWR6YtHd7bGZY2QpzXDhAJJ4yv6oGw](https://polkadot.subscan.io/account/14dLrAvjDw7cFLaxM7VWR6YtHd7bGZY2QpzXDhAJJ4yv6oGw)
🔗 [0x1f8aaba66496e8f7be8f39b7846f7e4739348e141415f6441d5567995b78faff](https://polkadot.subscan.io/extrinsic/0x1f8aaba66496e8f7be8f39b7846f7e4739348e141415f6441d5567995b78faff)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
