### PR TITLE
fix: Loaders and skeletons for new profile

### LINKED ISSUE #10167: Loaders and skeletons for new profile
New profile that is being designed lacks skeletons, loaders and placeholders

Example: followers takes a bit to load, so would be good to have a skeleton
big images may take a while to upload, maybe a loader is required 

related: #10160

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #10167

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

Kapture

### CODE REVIEW

**Review by daiagi — APPROVED** [review]
Nitpick

The wrapping div seems to uneeded


Other that that let's roll

**Comment by Jarsen136** [comment]
> Nitpick
> 
> The wrapping div seems to uneeded
> 
> Other that that let's roll

It's because we could not put `v-if` and `v-for` on the same element.
ref: https://vuejs.org/guide/essentials/conditional.html#v-if-with-v-for

**Review by hassnian — APPROVED** [review]

**Comment by prury** [comment]
here for me they are too close to each other: 

image

**Comment by Jarsen136** [comment]
> here for me they are too close to each other:
> 
> image

✅ Fixed

**Pull request merged**
