### PR TITLE
modern flag doesnt work as intented

### LINKED ISSUE #2826: Builds are broken
To me looks like a Netlify outage?

`Deploy did not succeed: Deploy directory 'dist' does not exist`

First failed build seems on `main` at 11:44am

My bet is at 

https://github.com/kodadot/nft-gallery/pull/2815/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R27

### Ref
- https://github.com/kodadot/nft-gallery/pull/2812
- https://github.com/kodadot/nft-gallery/pull/2825
- #2718 

https://app.netlify.com/teams/yangwao/builds/625549e849e59900089b0d26

image

https://app.netlify.com/sites/koda-nuxt/deploys/62554a7806c0270008e7f412

image

### PR DESCRIPTION
**Pull request by yangwao**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix

### What's new?

- [x] PR closes #2826 

### Before submitting Pull Request, please make sure:

- [x] Having fun.
### Optional

- [x] Yolo

### Screenshot

- [ ] Awaiting successful build

### CODE REVIEW

**Comment by vikiival** [comment]
PLS ❤️

**Comment by yangwao** [comment]
CF 
> Error: Output directory "dist" not found.

**Review by vikiival — APPROVED** [review]
my-blessing-you-have

**Comment by vikiival** [comment]
Like what I merged 
https://github.com/kodadot/nft-gallery/pull/2821/
https://github.com/kodadot/nft-gallery/pull/2812/

**Pull request closed without merging**
