### PR TITLE
fix: created nfts undefined

### LINKED ISSUE #7548: Error message while minting: Cannot read properties of undefined
An artist (eric2049 on tg) is trying to mint an NFT to an existing collection he created a moments ago, and he got this message "[ERR] TypeError: Cannot read properties of undefined (reading 'createdNFTs')". He did a collection first without nft's and after he continued to classic mint. The error appears before the polkadot.js extension appears to sign.

He is on the laptop, using Brave

Chain: Ahp
His address: 1RMsczeNX2Rss8qroqL1DtgSCM73yRBSSYKUveqCooy77FD

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #7548
- [x] Not sure how to reproduce it. But, this is the corrected code from the ‘nuxt’ branch

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)

## Screenshot 📸

- [ ] My fix has changed UI

### <samp>🤖 Generated by Copilot at f47df07</samp>

This pull request enhances the user interface and experience of creating nfts. It fixes some layout issues, refactors some code, and updates some variables and options in `components/create/CreateNft.vue`.

### <samp>🤖 Generated by Copilot at f47df07</samp>

> _We're creating nfts with style and grace_
> _We've fixed the `NeoField` and the `w-100` case_
> _We've refactored and simplified, we've set the `transactionStatus`_
> _So heave away, me hearties, heave away on the count of three_

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]

**Comment by yangwao** [comment]
I think it would be nice to switch on `nuxt` as I sense more user-facing bugs being fixed in nuxt meanwhile than on the current `main` and backporting them is double work.

**Comment by roiLeo** [comment]
> I think it would be nice to switch on `nuxt` as I sense more user-facing bugs being fixed in nuxt meanwhile than on the current `main` and backporting them is double work.

we have some minor issue with seo on nuxt branch

**Comment by yangwao** [comment]
> we have some minor issue with seo on nuxt branch

other than this? 

> Opengraph only showing [basic info](https://github.com/kodadot/nft-gallery/assets/36627808/2812f251-c10d-4c49-aeef-7e345283f1aa) about koda

**Comment by JustLuuuu** [comment]
will this thing be fixed? 🥹

**Pull request closed without merging**
