### PR TITLE
fix: When switching from transfer on polkadot, refresh network

### LINKED ISSUE #8321: When switching from transfer on polkadot, refresh network
image
- this happens sometimes: you are transferring funds in Polkadot transfer, decide to go to the landing page, and the network is still switched to Polkadot 
- refresh the network to Polkadot asset hub anytime you go out of the transfer

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix
  
  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #8321
  - [ ] Requires deployment <snek/rubick/worker>

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [ ] My fix has changed UI

  ## Copilot Summary
  
### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at c9330f8</samp>

This pull request redirects users from the `dot` prefix to the `ahp` prefix for some routes using the `prefix.global.ts` middleware. It also moves the logic for checking the route availability for the explorer feature from the components to the middleware.

  
### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at c9330f8</samp>

> _`dot` to `ahp`_
> _redirecting users now_
> _fall of old prefix_

### CODE REVIEW

**Comment by Jarsen136** [comment]
> @Jarsen136 playwright detection: if you switch the currency to DOT and then switch to KSM, it doesn't really go to KSM

Good catch! I have fixed it.

**Comment by Jarsen136** [comment]
> why fallback to ahp?

We have to fallback to another available prefix if someone visits the polkadot unsupported prefix. Is there any better choice instead of `ahp`?

**Comment by yangwao** [comment]
thanks!
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 5.9 USD/DOT ~ 3.39 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x3aa968a7629acf845916b88df827db0f5afd48168b157b245b7ff52b1b667afb](https://polkadot.subscan.io/extrinsic/0x3aa968a7629acf845916b88df827db0f5afd48168b157b245b7ff52b1b667afb)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
