### PR TITLE
Add iqr/h-spread and box plot chart

### LINKED ISSUE #1483: Add H-spread to the chart
This is continued from 
- #1121
- #1291 
You might find research done by @rhaicode on this topic for faster implementation

### Spec
- Add H-spread to chart  #1119 
- User could see the box plot  on the chart https://codepen.io/sgratzl/pen/QxoLoY
- it could be done as a dedicated chart or shown as separate column next to the main chart on the right

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #1483 

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged the recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

URL: https://deploy-preview-3585--koda-nuxt.netlify.app/rmrk/collection/2644199cf3652aaa78-KK01?tab=chart
Screen Shot 2022-07-27 at 17 47 40

### CODE REVIEW

**Comment by preschian** [comment]
move back to draft PR

still checking why the tooltip only works on localhost
Screen Shot 2022-07-27 at 18 48 47

**Comment by preschian** [comment]
cc @yangwao for feedback

**Comment by preschian** [comment]
move to draft PR. will revisit again when https://github.com/kodadot/nft-gallery/pull/3651 merged

**Comment by preschian** [comment]
> Also what kind of data do you need ?
> 
> we can do that on rubick instead of making fancy magic on frontend

I almost forgot these changes. let me resolve the conflicts first

**Comment by preschian** [comment]
> Also what kind of data do you need ?
> 
> we can do that on rubick instead of making fancy magic on frontend

regarding data on Rubick, what if we start by revisiting the line chart?
currently, the line chart on bsx and rmrk use different data sources/API

from the latest discussion, there are still areas of improvement regarding the line chart also https://github.com/kodadot/nft-gallery/issues/3646#issuecomment-1207985634

**Comment by petersopko** [comment]
@preschian @vikiival not sure what the status is here, are we going to do this on rubick or is this ready for review? It seems to me that we have at least some functioning version here 😄 
image

**Comment by preschian** [comment]
> @preschian @vikiival not sure what the status is here, are we going to do this on rubick or is this ready for review? It seems to me that we have at least some functioning version here 😄 

from me is ready to review. but I need @vikiival approval is it ok to go or not

> we can do that on rubick instead of making fancy magic on frontend

either way, later on, I will open an issue regarding the @vikiival concern. because currently chart on collection only works on `rmrk`. need to figure it out, maybe we can reuse data from the `History` tab to show the chart or need additional data

**Review by petersopko — APPROVED** [review]

**Review by vikiival — COMMENTED** [review]
Math is legit

> later on, I will open an issue regarding

👀

**Comment by preschian** [comment]
@vikiival I tried to explain here https://github.com/kodadot/nft-gallery/issues/4052

**Comment by petersopko** [comment]
can we move this forward and solve the multichain support elsewhere? :)

**Review by prachi00 — APPROVED** [review]

**Review by vikiival — APPROVED** [review]
YOLO

**Comment by vikiival** [comment]
YOLO v2

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 24.32 USD/KSM ~ 4.112 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0xb5fde6abf8fb1e7baf9f9f4c3aeb6bc332699dd20d822e80d6b645181055e89c](https://kusama.subscan.io/extrinsic/0xb5fde6abf8fb1e7baf9f9f4c3aeb6bc332699dd20d822e80d6b645181055e89c)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
