### PR TITLE
feat: Drop page cards carousel on landing page

### LINKED ISSUE #9277: Drop page cards carousel on landing page
image

the first change of the landing page, there will be one more 

- this one focuses on the hero section, drop page strip 

## Basics
- it's a carousel - please add the arrow there 
- carousel will have at least 6 cards
- now there will also be past drops 
- cards are also replacing the cards we have in drop landing currently - they are simpler, better looking imo
- please check the margins as always

**Hierarchy** 
- how will cards show in the carousel? 
   - First will be mints that are live, then scheduled (sorted descending by time left), then coming soon if any - those are drops that will be as a drop but don't a have a date yet, then ended/sold out
   - so TLDR the more you scroll the older drops you get there 

## Design
- new page in figma: https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=7854-37012&mode=design&t=t61QGwlS2c4TGFw3-11

cards have states: 
image

- there are also dark-mode cards

**dynamic states:** 
image

- minutes and hours are shown after the time to drop is less than 24 hours, till then its just a date 

### Top part of the landing

image
different gradient, let's evolve

i guess you guys want png right: 

gradientV3

let me know if svg is better

gm

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #9277
- [x] Needs https://github.com/kodadot/private-workers/pull/56

## Needs Design check

- @exezbcz please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2024-02-07 at 14 19 37@2x

### CODE REVIEW

**Comment by exezbcz** [comment]
i will give feedback throughout


https://github.com/kodadot/nft-gallery/assets/90852205/1e267280-3d26-47bd-903b-d01f074e0f42

- have a look at the nft card - when you hover over img there should not be another stroke added


## more cards
- it should be carousel with more cards

**Comment by yangwao** [comment]
drops showing in KSM? 

image

**Comment by hassnian** [comment]
> drops showing in KSM? 
> 
> 
> 
> image
> 
> 


hmm if you mean these new drops , they are not from this pr , [canary](https://canary.kodadot.xyz/ahp/drops) already has them , there was some drop url change iirc

**Comment by yangwao** [comment]
ah they are testing ones, got it, make sense :)

**Comment by exezbcz** [comment]
> ah they are testing ones, got it, make sense :)

could you please hide them on the production? So there are only ahp drops - as they are the primary ones

**Comment by hassnian** [comment]
> @hassnian let's make it to the weekly release, I will be doing one in 3-4h and this is a huge visual update 😄

I'm doing one of the requirements , basically the sorting order , requires changes on fxart private worker , requires adding the start_at date for new drops, atm we don't keep track of each drops starting date 


can do this on a separate issue and we can release what we have , wdyt

**Comment by exezbcz** [comment]
> > @hassnian let's make it to the weekly release, I will be doing one in 3-4h and this is a huge visual update 😄
> 
> I'm doing one of the requirements , basically the sorting order , requires changes on fxart private worker , requires adding the start_at date for new drops, atm we don't keep track of each drop's starting date 
> 
> 
> can do this on a separate issue and we can release what we have , wdyt 

Can we maybe hard code it for now?

**Comment by yangwao** [comment]
@hassnian yup we can hardcode it for now it's good and feel free to make follow up, we have a weekly schedule for now, we planned to do HolderOf on Friday but doesn't need to be on landing for now, loyal people will discover it 😉 (maybe reading this as well)

**Comment by hassnian** [comment]
> > ah they are testing ones, got it, make sense :)
> 
> could you please hide them on the production? So there are only ahp drops - as they are the primary ones

already hidden on prod

**Comment by hassnian** [comment]
@yangwao needs https://github.com/kodadot/private-workers/pull/56 to pull only 6 drops and include old ones , without it only active drops will be shown

**Comment by yangwao** [comment]
Thanks!
pay 90 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $90 @ 6.92 USD/DOT ~ 13.006 $DOT
🧗 [16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD](https://polkadot.subscan.io/account/16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)
🔗 [0x6e494ec066f65d1ab4ca192a9a958d62e613306f42749e83719aca3de2840078](https://polkadot.subscan.io/extrinsic/0x6e494ec066f65d1ab4ca192a9a958d62e613306f42749e83719aca3de2840078)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
