### PR TITLE
feat: search bar with suggestion on mobile

### LINKED ISSUE #3882: Search Bar on mobile
two postfixes on 📱 searchbar:

- [ ] search bar doesn't open up on displays with 481px > width -> please make it so that we have fully responsive searchbar
- [ ] suggestions don't show up on mobile at all - > same as the issue above, please make it work seamlessly in a way it works on desktop

Important: please test this on all chains

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [x] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #3882

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
Arrows on Gallery Item overlaps
Capture d’écran 2022-09-22 à 9 10 29 AM

When I click on an Item I'm redirected but I still see the searchbar open 
Capture d’écran 2022-09-22 à 9 12 46 AM

When I click on "x" I except the searchInput to be empty/erased

**Comment by Jarsen136** [comment]
✅ Fixed: Arrows on Gallery Item overlaps

image

**Comment by Jarsen136** [comment]
As for these two bugs, I create another issue for them.

- When I click on an Item I'm redirected but I still see the searchbar open
- When I click on "x" I except the searchInput to be empty/erased

**Review by petersopko — APPROVED** [review]
wfm

**Comment by yangwao** [comment]
pay 50

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 40.96 USD/KSM ~ 1.221 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x3689695b33e0972604ea0c3353b1a28913550466a3fa87486e0d93f524a8d811](https://kusama.subscan.io/extrinsic/0x3689695b33e0972604ea0c3353b1a28913550466a3fa87486e0d93f524a8d811)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
