### PR TITLE
#4153 redesign spotlight leftovers

### LINKED ISSUE #4153: Redesign: Spotlight leftovers
### Is your feature request related to a problem?

Originial issue - #4090
- All of the cards in the carousel, including single nft cards in Newest lists, Latest sales, etc. should overflow over the edges of the content. They should scale up/down to show only 4 in the case of the spotlight and single nfts. Once it overflows, it should change its opacity to 30% and mode to luminosity. That means we see the content, but it's clear we can scroll. See the picture below.
now:  
image
in the design file: 
image
- heading should be white and also respect the font sizing of h2 - in this case, it's 39px, but that's a minor problem. 
- also the images in the spotlight card should have a stroke of 1px. Like this: 
image
- Then there's a slight problem with the drop shadow effect, but I think that will be solved with problem n. 1.
image

### Describe the solution you would like

.

### Describe alternatives you have considered

.

### Screeenshots

_No response_

### Are there opened related issues?

_No response_

### PR DESCRIPTION
**Pull request by gigor**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #4153
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

Changes:
1. "Spotlight" title now is white
2. All cards are visible on all sliders. Off main screen cards are faded
3. Arrows are hidden if there is no more cards that way

Screenshot 2022-11-01 at 18 33 59

Screenshot 2022-11-01 at 18 34 20

Screenshot 2022-11-01 at 18 36 21

### CODE REVIEW

**Comment by exezbcz** [comment]
Hey, Good job! 
Few changes: 
- always display the arrow, as you could now unintentionally click on the collection or card when you are scrolling through the carousel and reach the end. 
- Scroll on the bottom of the container: 
image

**Comment by gigor** [comment]
@exezbcz should we may be loop through the collection or somehow indicate the disabled state of the arrow buttons?

**Comment by exezbcz** [comment]
> @exezbcz should we may be loop through the collection or somehow indicate the disabled state of the arrow buttons?

I dont think its necessary because you see at the end of the carousel. Looping would be confusing. Can you also make the arrows bit smaller? 

Or maybe im thinking of moving the view by 4 cards after each click, so that there are some new cards after each click. Then we could keep the showing/hiding arrow

**Comment by gigor** [comment]
Is the size on the right ok?

Screenshot 2022-11-01 at 21 20 03

>Or maybe im thinking of moving the view by 4 cards after each click, so that there are some new cards after each click. Then we could keep the showing/hiding arrow and maybe add loop?

Not sure how to make this plugin to scroll by the whole view. Will implement if will come up with an idea.

**Comment by exezbcz** [comment]
> Is the size on the right ok?

yup, sorry for that, the original size seems to be good, but the drop shadow is looking bit weird and the stroke looks bigger than 1px - should have the same as the cards
image
- right is figma design 
- figma file right here: https://www.figma.com/file/3iOjW12ERFRDSVnpLuhQmf/landing-page-handoff?node-id=0%3A1

Thanks!

**Comment by gigor** [comment]
That's as close as I can make it to the design in figma without just getting an svg from figma.

Screenshot 2022-11-01 at 22 44 49

**Comment by yangwao** [comment]
Looks great! 

@gigor can you update your address in PR? 
Merging till then

**Comment by gigor** [comment]
@yangwao glad you like it, it was fun to remember vue : )  I thought this issue didn't have a bounty though

**Comment by yangwao** [comment]
> I thought this issue didn't have a bounty though

let's grab another one tho! :)

**Pull request merged**
