### PR TITLE
🧪 partial nova wallet fix

### PR DESCRIPTION
**Pull request by roiLeo**
I managed to log in with Nova Wallet (click "Connect" 2 times something wrong with async stuff) at least now you can choose an account from the list

### PR type

- [x] hotfix

### PR related

- [x] #2630 

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=HguGafrfk8nRP9a4tgJf7hLvSSFie8GtkDjyWFHQ2kDUAMc)

### CODE REVIEW

**Comment by prachi00** [comment]
lgtm

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 190.57 USD/KSM ~ 0.525 $KSM
🧗 [HguGafrfk8nRP9a4tgJf7hLvSSFie8GtkDjyWFHQ2kDUAMc](https://kusama.subscan.io/account/HguGafrfk8nRP9a4tgJf7hLvSSFie8GtkDjyWFHQ2kDUAMc)
🔗 [0xa740734494d4765c581157512c5ca5af75bdc5c6c4d95985115a23f9b672db6a](https://kusama.subscan.io/extrinsic/0xa740734494d4765c581157512c5ca5af75bdc5c6c4d95985115a23f9b672db6a)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by roiLeo** [comment]
Tested on MathWallet and it looks like working too 🎉

**Pull request merged**
