### PR TITLE
#2127 Routing on clicking on collections broken sometimes

### LINKED ISSUE #2127: Routing on clicking on collections broken?
Seems I can't replicate it on kodadot.xyz as it did not happen for me, must be something in recent `main` ?
Funny enough, the first page it has worked okay, when I listed through the next pages, it started happening on other collections.

Seems like some routing is terrible broken?

Could this be this warning related? 

image
Hint for this would be issue to sync paginations up and down? Maybe make new component for this?

https://deploy-preview-2123--koda-nuxt.netlify.app/rmrk/collections/

https://user-images.githubusercontent.com/5887929/151759422-1a20f493-dedc-49b7-8f6d-9ee97c0e6683.mov

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2127
- [x] `/rmrk/collections/?page=1` issue happens when route is like this, so have changed it full url so this doesn't happen

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by vikiival — CHANGES_REQUESTED** [review]
please also check the /statemine collections

**Comment by prachi00** [comment]
> please also check the /statemine collections

Done for statemine also

**Review by roiLeo — COMMENTED** [review]
Wouldn't it be better to use route name?
```
:to="{ name: 'rmrk-collection-id', params: { id: collection.id } }">
```

**Comment by prachi00** [comment]
> * /rmrk/collection/26902bc2f7c20c546a-1FVG7

@roiLeo tried doing this, didn't work properly

**Comment by yangwao** [comment]
let's resolve conflict and we can merge it tho :)

I prefer named routes as well

**Comment by yangwao** [comment]
What's about nested named views? https://router.vuejs.org/guide/essentials/named-views.html#nested-named-views

**Comment by prachi00** [comment]
> What's about nested named views? https://router.vuejs.org/guide/essentials/named-views.html#nested-named-views

this seems unrelated to this though?

**Comment by prachi00** [comment]
@yangwao have resolved the conflicts

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 159.84 USD/KSM ~ 0.626 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x1b6d89dc0950ee85e3dc629c1928fe4e2ebbc51bd05c89200b61e8672747e5ff](https://kusama.subscan.io/extrinsic/0x1b6d89dc0950ee85e3dc629c1928fe4e2ebbc51bd05c89200b61e8672747e5ff)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
