### PR TITLE
fix: Some images not loading properly on Kusama

### LINKED ISSUE #7596: Some images not loading properly on Kusama
### What happened?

https://canary.kodadot.xyz/rmrk/explore/items?listed=true&min=100000000000000

image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix

  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #7596
  - [x] fix: nft is not loading properly on gallery list  https://kodadot.xyz/rmrk/collection/6c380dc2e061d72103-CV8888
  - [x] fix: nft is not loading properly on gallery details

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

image

image

  ## Copilot Summary
  
### <samp>🤖 Generated by Copilot at 222b33f</samp>

Simplified `getMimeType` function in `utils/gallery/media.ts` to avoid CORS errors when fetching media from IPFS.

  
### <samp>🤖 Generated by Copilot at 222b33f</samp>

> _`getMimeType` changed_
> _No more `method: 'HEAD'` woes_
> _CORS errors gone - spring_

### CODE REVIEW

**Comment by prury** [comment]
they do load now, ty!

**Review by roiLeo — APPROVED** [review]
any side effects that we should be aware?

**Comment by Jarsen136** [comment]
> any side effects that we should be aware?

It would cost more time to fetch the `content-type` of metadata the first time. After the first fetching, the follow-up request would be from the cache.

**Review by vikiival — APPROVED** [review]

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $10 @ 3.69 USD/DOT ~ 2.71 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x911069baab8687ddeae1b626e149826dbc5864183d4dad7aeba0bea99a17ad4e](https://polkadot.subscan.io/extrinsic/0x911069baab8687ddeae1b626e149826dbc5864183d4dad7aeba0bea99a17ad4e)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
