### PR TITLE
remove only if dataset not affected too much

### LINKED ISSUE #8108: List is not showing on chart but appears in activity
https://canary.kodadot.xyz/ahp/collection/38/activity
image

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Context

- [x] Closes #8108

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)

## Screenshot 📸

- [x] My fix has changed UI

image

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 3aa3a30</samp>

Improved activity chart by filtering out outliers if they are not too prevalent. Modified `ActivityChart.vue` to implement this logic.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 3aa3a30</samp>

> _The data is corrupted by the outliers_
> _They distort the truth and the vision_
> _But we have a `CUTOFF` to defy them_
> _And a condition to avoid division_

### CODE REVIEW

**Comment by daiagi** [comment]
>or we can compare the dataset size before and after outlier removal, and only remove if less then (10%?) of points have been remove
i.e clean/dirty > 0.9
from https://github.com/kodadot/nft-gallery/issues/8108#issuecomment-1822634671

since it's quick and easy, i went ahead and implemented
@yangwao if you don't agree with this solution, lmk

**Review by roiLeo — APPROVED** [review]

**Review by preschian — APPROVED** [review]

**Comment by yangwao** [comment]
Which charts tells more? I would propose make that checkbox, which could be enabled by default [x] hide outliers and anyone can uncheck it, cc @exezbcz on design

this pr
image

vs canary
image

**Comment by exezbcz** [comment]
@yangwao yeah mentioned somewhere that I would put it to the settings 

- by default, it would be on. 
- option to turn it off

will create issue with the design

**Comment by daiagi** [comment]
Yessir, waiting on the checkbox. Drafting for now

**Comment by exezbcz** [comment]
@daiagi 
image
simple as that 

https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=1287%3A18959&mode=design&t=l9ITDxHsKHJcI9sz-1

**Comment by daiagi** [comment]
closing
alt solution in #8234

**Pull request closed without merging**
