### PR TITLE
fix: Landing page visual change footer part

### LINKED ISSUE #4458: Landing page visual change footer part
@exezbcz can we keep the footer as it is right now and create a new issue to make it overflow to the top, I am facing issues with it, so not really sure how to go on about doing that

_Originally posted by @prachi00 in https://github.com/kodadot/nft-gallery/issues/4440#issuecomment-1341904558_

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4458
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by prachi00** [comment]
> > @Jarsen136  the footer is still inside the footer container, it should be overflowing to the container above it
> 
> Hey, @prachi00 I'm not sure why I should adjust the dom structure as you say. Could you pls tell me why? I think the target of the original issue is to render the background of the footer properly, and not to affect the other part. Or have I missed something in the figma design 👀


Screen Shot 2022-12-08 at 11 39 43 PM



so this is how it is suppose to look like with the footer image overflowing to the top instead of just staying in footer, right @exezbcz ? but there were issues with z-index and items not being clickable

**Comment by Jarsen136** [comment]
> 
> Screen Shot 2022-12-08 at 11 39 43 PM
> 
> so this is how it is suppose to look like with the footer image overflowing to the top instead of just staying in footer, right @exezbcz ? but there were issues with z-index and items not being clickable

Oh my bad. Thanks for your answer. now I got it.

**Comment by Jarsen136** [comment]
✅ UPDATED

image

image

**Comment by exezbcz** [comment]
> > Screen Shot 2022-12-08 at 11 39 43 PM
> > so this is how it is suppose to look like with the footer image overflowing to the top instead of just staying in footer, right @exezbcz ? but there were issues with z-index and items not being clickable
> 
> Oh my bad. Thanks for your answer. now I got it.

yup, sorry for the confusion, one thing left - why is the dark mode blurred shape not in footer? It should have the same position as in light mode. 
Thanks! 
image

**Comment by Jarsen136** [comment]
> 
> yup, sorry for the confusion, one thing left - why is the dark mode blurred shape not in footer? It should have the same position as in light mode. Thanks! 

Because I see that in the figma : ) I will place it to where as in light mode.
image

**Comment by Jarsen136** [comment]
✅ UPDATED
dark mode
image
light mode
image

**Comment by exezbcz** [comment]
> > yup, sorry for the confusion, one thing left - why is the dark mode blurred shape not in footer? It should have the same position as in light mode. Thanks!
> 
> Because I see that in the figma : ) I will place it to where as in light mode. image

xd, that makes sense; I wasn't too concerned with the organization in figma:DDD. Thanks again

**Comment by prachi00** [comment]
Screen Shot 2022-12-09 at 10 33 01 AM
okay looks good, I am not sure about the other pages though @exezbcz

**Comment by exezbcz** [comment]
upss
- The line is missing there. (top of the footer) 
- Do you know why it has the grey background? I tried to open the svg and it looks fine.

**Comment by yangwao** [comment]
can we merge

**Comment by Jarsen136** [comment]
> 
> * The line is missing there. (top of the footer)

✅  Done
> * Do you know why it has the grey background? I tried to open the svg and it looks fine.

✅  Done
It's because the default color of the html element is grey (according to the previous code). It's not related to the svg background. Now I set the correct default color.


Now the footer on all pages was changed. Is it looks good to you?
image

image

image

**Comment by yangwao** [comment]
pay 40 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $40 @ 29.87 USD/KSM ~ 1.339 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x17297f85a96bdf5c3d4bc76b5db81d70bfe9d75b9e8094e651a7d2e0a0413ddf](https://kusama.subscan.io/extrinsic/0x17297f85a96bdf5c3d4bc76b5db81d70bfe9d75b9e8094e651a7d2e0a0413ddf)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
