### PR TITLE
bugfix and refactor: History tab at Profile

### LINKED ISSUE #2997: Followup: TypeError breaks History Items / Pagination 🐛
### What happened?

Followup ticket for #2973

When paginating through https://deploy-preview-2973--koda-nuxt.netlify.app/rmrk/u/CuHWHNcBt3ASMVSJmcJyiBWGxxiWLyjYoYbGjfhL4ovoeSd?tab=history&page=1&event=%25F0%259F%2596%25BC%2520MINT history will get stuck like the following

Probably some weird issue with history items. 

Screenshot 2022-05-11 at 07 40 18

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #2997
- [x] refactor something from PR: https://github.com/kodadot/nft-gallery/pull/2973
  1. Fix naming from `profil` to `profile` 
  2. delete some unused functions and variables

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

walk through any page index without error
image

### CODE REVIEW

**Review by kkukelka — APPROVED** [review]
perfect, works as intended now. clicked through all the way to page 36 👍 
https://deploy-preview-3000--koda-nuxt.netlify.app/rmrk/u/CuHWHNcBt3ASMVSJmcJyiBWGxxiWLyjYoYbGjfhL4ovoeSd?tab=history&page=1&event=%25F0%259F%2596%25BC%2520MINT
Screenshot 2022-05-12 at 06 33 35

**Comment by kkukelka** [comment]
pay 50

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 65.14 USD/KSM ~ 0.768 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xee20372ccb970c786e7daad877ff73dd4e62ab052a8f656f211d3eb541570dd3](https://kusama.subscan.io/extrinsic/0xee20372ccb970c786e7daad877ff73dd4e62ab052a8f656f211d3eb541570dd3)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
cg to # 3k ! :D

**Pull request merged**
