### PR TITLE
[nuxt3] checkpoint neo modal

### PR DESCRIPTION
**Pull request by preschian**
Hi @roiLeo @stephenjason89, It seems like we have another blocker for programmatic composables. This is the error.

Screenshot 2023-09-01 142947

I tested the same code in the new Nuxt3 app, and it works well. Here is the test repository: https://github.com/preschian/test-oruga-next
- plugin.ts - https://github.com/preschian/test-oruga-next/blob/66f0c16d49a70190039cd2e69a5fe3f91f702744/components/plugin.ts
- useProgrammatic.ts - https://github.com/preschian/test-oruga-next/blob/66f0c16d49a70190039cd2e69a5fe3f91f702744/composables/useProgrammatic.ts

I will check again later. Currently, I still have a simple mint task in the backlog.

### CODE REVIEW

**Comment by preschian** [comment]
oh wait, let me test once again

**Comment by roiLeo** [comment]
> oh wait, let me test once again

I'll merge some fix for gql query and I can take a look

**Comment by preschian** [comment]
@roiLeo @stephenjason89 sorry, false alarm. should be works now. turns out in oruga-next no need to set `parent` attributes

**Comment by preschian** [comment]
I also removed `$once` in this PR, unsupported in vue3

**Comment by roiLeo** [comment]
Hey @preschian do you mind apply same changes but for `neoNotification` ?

**Comment by preschian** [comment]
> Hey @preschian do you mind apply same changes but for `neoNotification` ?

sure, will update that also, because similar methods to fork

**Comment by stephenjason89** [comment]
> @roiLeo @stephenjason89 sorry, false alarm. should be works now. turns out in oruga-next no need to set `parent` attributes

Great job bro 😊 glad it worked out 💪

**Pull request merged**
