### PR TITLE
#5435 rmrk label

### LINKED ISSUE #5435: Show on landing in latest sales & listing RMRK2 in card
To indicate type of network, RMRK2 items missing rmrk2 in corner as we have Kusama or Basilisk

image

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5435
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screen Shot 2023-04-07 at 3 44 11 PM

### CODE REVIEW

**Comment by prachi00** [comment]
it seems like my changes got reversed somehow, works now @yangwao

**Review by Jarsen136 — APPROVED** [review]
code lgtm

**Comment by yangwao** [comment]
@prachi00 doesn't build

**Comment by prachi00** [comment]
> @prachi00 doesn't build
> 
> https://github.com/kodadot/nft-gallery/actions/runs/4641899175/jobs/8217336465?pr=5561#step:3:317

@yangwao fixed

**Comment by yangwao** [comment]
perfect 👍

**Comment by yangwao** [comment]
pay 10 usd

**Pull request merged**
