### PR TITLE
fix: improve infinite loading request

### LINKED ISSUE #4997: Infinity scroll issues on explorer
I want KodaDot to offer non-interrupted browsing experience for user at infinity scrolls. 

I would raise preload from 20 pics to 30 for example as hot fix, but seems issues is that when preload is triggered?
- https://github.com/kodadot/nft-gallery/pull/4991/files#diff-bb79535ca1061d3bf27078cc98173dd8bd7e3ee7595aaa4a4be339ff15435101R17
- https://github.com/kodadot/nft-gallery/blob/9925adda320955c482ca2d386322847fdf3f61b4/utils/mixins/infiniteScrollMixin.ts#L17

There are seems tons of errors, if loading much more pictures, can be that culprit it's get's stuck and I'm getting to the bottom?

https://user-images.githubusercontent.com/5887929/218721607-bfd0c5ae-ecc6-417c-b522-9caefe4e601f.mov

https://user-images.githubusercontent.com/5887929/218721615-b5688fdc-e2ef-49b3-b0e7-019ebb86ab29.mov

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4997
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by Jarsen136** [comment]
✅ Tested: I try to scroll down with more than 25+ pages with 500+ nft items and then there is no request error any more.

**Review by roiLeo — APPROVED** [review]
I still got weird behavior when scrolling up and down
Can't really reproduce it

https://user-images.githubusercontent.com/9987732/219299528-c4ee6905-bc53-496b-bd2d-2bcca24a8d37.mov


otherwise wfm

**Comment by Jarsen136** [comment]
> 
> how about this one? when I open this URL in a new tab https://deploy-preview-5018--koda-nuxt.netlify.app/rmrk/explore/items?page=65 it will always trigger the previous page

It seems tricky to handle the page fetching while scrolling up. I'll give it some thought. 🤔

**Comment by yangwao** [comment]
> I'll give it some thought. 🤔

maybe we can till then merge this part? 

It was working way better than current one :)

**Comment by Jarsen136** [comment]
> > I'll give it some thought. 🤔
> 
> maybe we can till then merge this part?
> 
> It was working way better than current one :)

Yes, I think so. In this PR, we add some cache for the metadata of nft. That would reduce lots of request error.

**Comment by Jarsen136** [comment]
> > how about this one? when I open this URL in a new tab https://deploy-preview-5018--koda-nuxt.netlify.app/rmrk/explore/items?page=65 it will always trigger the previous page
> 
> It seems tricky to handle the page fetching while scrolling up. I'll give it some thought. 🤔

I have added a click button to trigger loading the previous page, only for explore items page.  So that it is good to go for now.

https://deploy-preview-5018--koda-nuxt.netlify.app/rmrk/explore/items?page=65 
image


As for the collections explore page, the infinite scroll for both the top and bottom directions works well as usual.
https://deploy-preview-5018--koda-nuxt.netlify.app/rmrk/explore/collectibles?page=65

**Comment by vikiival** [comment]
pay 20 usd

**Pull request merged**
