### PR TITLE
1121: median line, trailing average and h-spread

### LINKED ISSUE #1121: Showing median line from BUY events and H-spread
- Show median line from BUY events on the chart
- Add H-spread #1119 
- Trailing avg 

### ref
Once #1110 is merged, you can continue into `main-nuxt` 

image

### PR DESCRIPTION
**Pull request by rhaicode**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇  _ Do a quick check before the merge. 

### PR type
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged the recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything works
- [ ] I found edge cases

### What's new?
- [x] PR closes #1121
- [x] Added median line, H-spread and 3 day trailing average support

### Had issue bounty label ?
- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EJ4LJsZAefUW5pwokk5G5b96CpHaABiXXaEUpdBakP8oYJr)

### Community participation
- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [x] My fix has changed **something** on UI, a screenshot for others, is best to understand changes.

### CODE REVIEW

**Comment by rhaicode** [comment]
This is a branched-out branch from #1110. 

Initial progress:
Capture

**Comment by vikiival** [comment]
hey @rhaicode, 
which branch do you use as the base ? `main` or `main-nuxt`? 
I am asking because you have a lot of unrelated code changes

**Comment by rhaicode** [comment]
Hello @vikiival. This PR is from #1110 which is from main-nuxt. As soon as #1110 is merged, I think 1072 commits should be gone as well

**Comment by yangwao** [comment]
> Hello @vikiival. This PR is from #1110 which is from main-nuxt. As soon as #1110 is merged, I think 1072 commits should be gone as well

Recently merged #1110 !

**Comment by yangwao** [comment]
@rhaicode you probably need update PR as Netlify wasn't triggered, so whenever you add something new it should be building fine I guess if you push recent `main-nuxt` :)

**Comment by rhaicode** [comment]
@yangwao you can now check the deployed build for this PR

**Comment by yangwao** [comment]
These dots are box plots my best guess? If so, let's make them outlined probably so it's not attention disruptive

Looking at https://deploy-preview-1291--koda-nuxt.netlify.app/rmrk/collection/2644199cf3652aaa78-KK01

image

**Comment by rhaicode** [comment]
@yangwao no, these points actually draw a one big box plot with the tip of the box plot on the yellow dots, which I feel is incorrect

**Comment by rhaicode** [comment]
Hello @yangwao , I'm having difficulty in finding a way to support box plot charts with line charts. As you can see from this [Codepen](https://codepen.io/sgratzl/pen/QxoLoY), it's only composed with box plots with the defined x-axis (for example months Jan, Feb, Mar, etc) without any line charts inside.

I think this is the farthest development I can provide.
http://somup.com/crlfj304Fl

**Comment by yangwao** [comment]
Hey there, so let's put the box plot as a separate issue and we can add it later, what do you think?
Let's recap what is working there @rhaicode :)

**Comment by rhaicode** [comment]
Hello @yangwao. These are the following only supported of this commit:
- median line
- trailing average

**Comment by yangwao** [comment]
I would like test it but our partner Subquery who provides indexer is down for some unknown reason and put it into investigation, I feel really really bad about it https://github.com/kodadot/nft-gallery/issues/1481

**Comment by yangwao** [comment]
Perfect, I’ve sent the payout https://kusama.subscan.io/extrinsic/0x4e13575846bb8044dc9ba4cd6cf3b64e6e51316dd3bd45417dcc7a4f01c52e0f

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/

I've created a separate issue for that h-spread in chart, 
so when we will be looking at it that later can find you did the heavy lifting amount of research here 
Continue to the https://github.com/kodadot/nft-gallery/issues/1483

**Pull request merged**
