### PR TITLE
feat: improve profile tabs item count load time 

### LINKED ISSUE #7437: improve profile tabs item count load time
goes after 
* #7318

              @exezbcz  is right, the query time is rather slow

the query as it is takes about 3 seconds to return 
image

however, you only need this query:
```graphql
query profileStatsById($id: String!, $interactionIn: [Interaction!], $denyList: [String!]) {

  obtained: nftEntitiesConnection(
    where: {currentOwner_eq: $id, burned_eq: false, metadata_not_eq: "", issuer_not_in: $denyList}
    orderBy: name_ASC
  ) {
    totalCount
  }
  created: nftEntitiesConnection(
    where: {issuer_eq: $id, burned_eq: false, metadata_not_eq: ""}
    orderBy: blockNumber_DESC
  ) {
    totalCount
  }
  events: eventsConnection(
    where: {AND: [{caller_eq: $id, OR: {currentOwner_eq: $id}}], interaction_in: $interactionIn}
    orderBy: blockNumber_DESC
  ) {
    totalCount
  }
  collections: collectionEntitiesConnection(
    where: {nfts_some: {burned_eq: false}, issuer_eq: $id, issuer_not_in: $denyList, metadata_isNull: false}
    orderBy: blockNumber_DESC
  ) {
    totalCount
  }
}

```

and this one takes about 1.2 seconds

image

so, instead of adding to the existing query, maybe create a new query?
so that both the existing and the new could be called in parallel, hopefully reducing load time

can be a follow-up issue

_Originally posted by @daiagi in https://github.com/kodadot/nft-gallery/issues/7318#issuecomment-1742044843_

### PR DESCRIPTION
**Pull request by hassnian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #7437

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; 

### <samp>🤖 Generated by Copilot at 3277466</samp>

Refactored and optimized the profile component and the GraphQL queries related to it. Removed unused code and simplified the queries by using a new `profileTabCounts` query that fetchs the counts for the profile tabs. Improved the performance and accuracy of the profile tabs.

### <samp>🤖 Generated by Copilot at 3277466</samp>

> _To improve the profile stats query_
> _We removed some parameters, very_
> _And added a new one_
> _`profileTabCounts` done_
> _To fetch the counts for each tab, clearly_

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
`ProfileActivitySummery`

otherwise code lgtm, hope nothing break

**Comment by hassnian** [comment]
> `ProfileActivitySummery`
> 
> otherwise code lgtm, hope nothing break

wait you mean to rename the query wouldn't it be profileDetails or something like that , that query is not part of ProfileActivitySummery

**Review by prury — APPROVED** [review]

**Review by daiagi — APPROVED** [review]
nice!

**Comment by exezbcz** [comment]
notable difference, excellent job!

**Comment by yangwao** [comment]
pay 70 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $70 @ 4.05 USD/DOT ~ 17.284 $DOT
🧗 [13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh](https://polkadot.subscan.io/account/13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)
🔗 [0xd277e619189dc5e2a28b77001f2aa4472ecb8e195c3904448393dbdd67ba57b8](https://polkadot.subscan.io/extrinsic/0xd277e619189dc5e2a28b77001f2aa4472ecb8e195c3904448393dbdd67ba57b8)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
