### PR TITLE
Generate social cards on the fly with NFT name, price and KodaDot branding

### PR DESCRIPTION
**Pull request by AndreyGrin**
Here image preview should already work. 
But to make it really nice, I will require some help, probably from @vikiival 

1. How can I get `nft.price` in the same view as <money> component returns but I need only value as string.
2. Is it possible to get `width` and `height` attributes for images? This will allow me to build previews based on image sizes and not with fixed dimensions.

### CODE REVIEW

**Comment by AndreyGrin** [comment]
I think build fails for same reason as I had in local. `vue-social-sharing` package is missing in package.json Should I push updates `package.json` as well?

**Comment by vikiival** [comment]
> Should I push updates package.json as well?
Yes please.

> How can I get nft.price in the same view as component returns but I need only value as string.

I'm not sure that I understand the question.

> Is it possible to get width and height attributes for images? 

[Reading Image Sizes and Dimensions with Vue.js](https://www.raymondcamden.com/2019/06/13/reading-image-sizes-and-dimensions-with-vuejs)

[Vue: get image width + height](https://stackoverflow.com/questions/59253669/vue-get-image-width-height-returns-zero-on-component-load)

**Comment by yangwao** [comment]
Just testing out
Telegram works perfect! 
image
Twitter is probably using other format? 
image
Discord plays a well! 
image

**Comment by AndreyGrin** [comment]
Tested in twitter. It doesn't work in their validator but works fine in twitter posts.
Screenshot 2021-05-10 at 11 18 53
@yangwao Do you want to change anything or we are good to go? I would say it looks good with wide format even if it cropped, but this is really stands out and takes attention for my opinion.

**Comment by vikiival** [comment]
Wow nice ! 🚀

**Comment by yangwao** [comment]
> Tested in twitter. It doesn't work in their validator but works fine in twitter posts.
> Screenshot 2021-05-10 at 11 18 53
> @yangwao Do you want to change anything or we are good to go? I would say it looks good with wide format even if it cropped, but this is really stands out and takes attention for my opinion.

Wow, I could not add more positive emotions to this! I like it! As first iteration on this big chunk is lot of stuff :)
Also never realized that twitter has X on the left in preview mode. 

But hey, what about the text when it's posted, it's cropped?

Just noted that Medium is doing some previews as well 
image

**Comment by AndreyGrin** [comment]
Changed aspect ratio to be 2:1 as in twitter doc, but now it cuts on sides.
Screenshot 2021-05-10 at 16 11 40 How could I test medium? I tried to use link in post and comment but it doesn't build preview

**Comment by yangwao** [comment]
> Changed aspect ratio to be 2:1 as in twitter doc, but now it cuts on sides.
> Screenshot 2021-05-10 at 16 11 40 

I mean perfect, let's put logo slightly far from edge and it would be perfect to fly! :)
Yet I see you need to handle undefined there :)

> How could I test medium? I tried to use link in post and comment but it doesn't build preview

Log into medium
open https://medium.com/new-story 
paste link
hit enter
take a while <- this seems really random

and boom
but sometimes, takes longer than.. while.

image

Anyway, seems medium doesn't have tool for themselves, but have links to other debugers 
https://help.medium.com/hc/en-us/articles/215769058-Update-social-media-preview-cards

Preview from linkedin 
image

**Comment by AndreyGrin** [comment]
Screenshot 2021-05-10 at 20 20 28 Yay, twitter finally good. Pushed price and logo few pixel more from sides to avoid cutting at other resources. 
For a note: while testing, use different images, since Vercel caches image forever, so it won't regenerate it with new size/styles. Fixed undefined price. The only thing what's left is a correct price display in KSM/USD format. Who can help with that?

**Comment by yangwao** [comment]
@vikiival can guide you through, there is a format balance component and we would like to show just KSM as USD may change since then when was it was first cached.

What's are options for vercel pricing or it's free tier I guess for now?
I mean, you can then probably transfer the repository to kodadot and we can deploy it? )
Love to have your long-term contributions :)

**Comment by vikiival** [comment]
@AndreyGrin we use this [formatBalance function](https://github.com/kodadot/nft-gallery/blob/acc45dff2299b2580dcb5d6ee64f14770f524c26/dashboard/src/utils/formatBalance.ts)

so if you call `{{ value | formatBalance }}` it should be allright

**Comment by AndreyGrin** [comment]
Got error: `You don’t have the permission to create public repositories on kodadot` so probably I need transfer it to user. Should I transfer to you @yangwao ?

**Comment by yangwao** [comment]
Yes, @AndreyGrin  you can transfer it to me, I'll make deploy on vercel and we can let it merge into main and probably push to the production :)

**Comment by yangwao** [comment]
okay, we hope that vercel won't limit us but eventually we can afford migrate under organisation later, sometime :)

**Pull request merged**
