### PR TITLE
toggle ramp instance variant

### LINKED ISSUE #8127: exiting on ramp screen
image

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Context

- [x] Closes #8127

## QA

@prury plz review

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 61db843</samp>

Added responsive design to `useRamp` composable to improve fiat-to-crypto buying experience. Used `useWindowSize` and `variant` option to adjust Ramp Instant widget size and layout according to device screen.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 61db843</samp>

> _Sing, O Muse, of the skillful Ramp Instant team_
> _Who made their widget responsive with `useWindowSize`_
> _And gave it variants to suit each device and screen_
> _As Proteus changes his shape to elude his enemies_

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]

**Comment by prury** [comment]
@daiagi exit now works, but buying process got affected: 

Imagem do WhatsApp de 2023-11-17 à(s) 10 53 21_90895257

**Comment by daiagi** [comment]
Looks good on my phone (android, nova wallet) 

@kodadot/internship-dev  could you check on your mobiles?

**Comment by roiLeo** [comment]
Tested with Nova Wallet

**Review by Jarsen136 — APPROVED** [review]

**Comment by prury** [comment]
@Jarsen136 could you check on your mobile if on ramp screen is ok?

**Comment by prury** [comment]
@roiLeo reason we are asking ppl to test inside nova specifically is because mine looks like this: 
aa

**Comment by roiLeo** [comment]
> @roiLeo reason we are asking ppl to test inside nova specifically is because mine looks like this

Is your Nova app up to date? What android version? Maybe iOS?

**Comment by prury** [comment]
> > @roiLeo reason we are asking ppl to test inside nova specifically is because mine looks like this
> 
> Is your Nova app up to date? What android version? Maybe iOS?

Yup, up do date, android version 12

**Comment by Jarsen136** [comment]
> @Jarsen136 could you check on your mobile if on ramp screen is ok? 

image

**Comment by prury** [comment]
> > @Jarsen136 could you check on your mobile if on ramp screen is ok?
> 
> It work for me on IOS Nova image

thank you!

**Comment by prury** [comment]
well, not sure how to proceed then, I've reinstalled the wallet, deleted the cache, imported acc again and the error still persists, canary works properly for me tho

**Comment by daiagi** [comment]
>well, not sure how to proceed then, I've reinstalled the wallet, deleted the cache, imported acc again and the error still persists, canary works properly for me tho

not much i can do here tbh
the funding screen is not our own, it is hosted by Ramp
all i did was to change the mode from desktop to auto => respond to screen width

not much i can do further then that

**Comment by roiLeo** [comment]
Let's merge it for now.

**Pull request merged**
