### PR TITLE
feat: Increase card number on landing

### LINKED ISSUE #5256: Increase number of cards on carousel landing page
image
- maybe something similar as with dynamic grid on explore? 

image
the cards are too big

### PR DESCRIPTION
**Pull request by floyd-li**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

just increase the card number on landing page, make it 6 card on width > 1280 and 4 on width > 1024.

also improve the card slide step on different width

@exezbcz mr.designer if there's any suggestion please tell me lol

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #5256
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EZiu1PjV2j2JHKxY6mHnFwwCRCoV27uHKQSkKXATSh1srJT&usdamount=0&donation=true)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

image

### CODE REVIEW

**Comment by exezbcz** [comment]
bruh, new thing calling me like that? :D 
Let's make it 5 card on width > 1280 and 4 on width > 1024.
and if it would be possible - add breakpoint for 1540 (where currently is for the top collections) and put 6 cards there
This way you wont get 6 small cards on 13" screens 
+ plus for the xl screens, can you edit the featured articles part? Maybe like from 1540 - 4 cards instead of 3

Thanks!

**Comment by floyd-li** [comment]
@exezbcz updated

**Comment by exezbcz** [comment]
@floyd-li yes, good!

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 37.31 USD/KSM ~ 0.536 $KSM
🧗 [EZiu1PjV2j2JHKxY6mHnFwwCRCoV27uHKQSkKXATSh1srJT](https://kusama.subscan.io/account/EZiu1PjV2j2JHKxY6mHnFwwCRCoV27uHKQSkKXATSh1srJT)
🔗 [0x9982ef70cac1c1a1052bcf0c8b37ec7dd0a687acfe7138914c4aba98dc54bb3f](https://kusama.subscan.io/extrinsic/0x9982ef70cac1c1a1052bcf0c8b37ec7dd0a687acfe7138914c4aba98dc54bb3f)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
