### PR TITLE
justify border style

### LINKED ISSUE #2806: Match top-border style where we miss it
I noticed a few inconsistencies, so tried to name them down. 
Would be nice if we can have it merged with #2791 so we can push to production and make probably a release.

In the actions component, make borders top-border only and 1px, including input.
Thinking for Buy we could also try to have just top-border.

image

Search bar on input make top-border 1px, now it seems is 2px 
image

In the profile dropdown, the logout button needs top-border 1px love

image

On the item detail, the control buttons remove top-border

image

on left and right arrow - top-border 1px 
image
image

Let's make Action, Chart, History top-border 1px as well 

image

image

Emoji button as well 1px 

image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2806 
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

1px on buttons
image

2px on buy button
image

### CODE REVIEW

**Comment by Jarsen136** [comment]
Pls let me know if I have missed something.

**Review by vikiival — COMMENTED** [review]
If it's possible I would make 

```scss
$sleek-primary-border=1px solid $primary
```

**Comment by Jarsen136** [comment]
> If it's possible I would make
> 
> ```css-scss
> $sleek-primary-border=1px solid $primary
> ```

Okay

**Review by vikiival — APPROVED** [review]
LGTM

**Comment by vikiival** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 174.32 USD/KSM ~ 0.287 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x572d949d93d4be1982f9eb650f1fda008ac0e2d5ac04b836615eda70aa952b61](https://kusama.subscan.io/extrinsic/0x572d949d93d4be1982f9eb650f1fda008ac0e2d5ac04b836615eda70aa952b61)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
