### PR TITLE
fix: search gallery on bsx

### LINKED ISSUE #3504: search query in gallery
suggestions and their routing should be fixed once we have merged
- https://github.com/kodadot/nft-gallery/pull/3491

last thing (afaik) is to fix the actual search query for words in Gallery

```json
{
   "errors":[
      {
         "message":"Variable \"$search\" got invalid value { name: { likeInsensitive: \"%test%\" } } at \"search[0]\"; Field \"name\" is not defined by type \"NFTEntityWhereInput\".",
         "extensions":{
            "code":"BAD_USER_INPUT",
            "exception":{
               "stacktrace":[
                  "GraphQLError: Variable \"$search\" got invalid value { name: { likeInsensitive: \"%test%\" } } at \"search[0]\"; Field \"name\" is not defined by type \"NFTEntityWhereInput\".",
                  "    at /squid/node_modules/graphql/execution/values.js:116:15",
                  "    at coerceInputValueImpl (/squid/node_modules/graphql/utilities/coerceInputValue.js:114:9)",
                  "    at coerceInputValueImpl (/squid/node_modules/graphql/utilities/coerceInputValue.js:54:14)",
                  "    at /squid/node_modules/graphql/utilities/coerceInputValue.js:70:14",
                  "    at Array.map (<anonymous>)",
                  "    at safeArrayFrom (/squid/node_modules/graphql/jsutils/safeArrayFrom.js:36:23)",
                  "    at coerceInputValueImpl (/squid/node_modules/graphql/utilities/coerceInputValue.js:68:50)",
                  "    at coerceInputValue (/squid/node_modules/graphql/utilities/coerceInputValue.js:37:10)",
                  "    at _loop (/squid/node_modules/graphql/execution/values.js:109:69)",
                  "    at coerceVariableValues (/squid/node_modules/graphql/execution/values.js:121:16)"
               ]
            }
         }
      }
   ]
}
```

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3504 
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
Hey! can we keep consistency in code? it will be better when we do a refactoring


```ts
    if (this.searchQuery.search) {
      if (this.isRmrk) {
        params.push({
          name: { likeInsensitive: this.searchQuery.search },
        })
      } else {
        params.push({ name_containsInsensitive: this.searchQuery.search })
      }
    }
```

**Comment by Jarsen136** [comment]
ok, I will modify it later

**Review by DeluneClaire — APPROVED** [review]
works for me

**Review by roiLeo — APPROVED** [review]
✅ lgtm

**Comment by petersopko** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 67.76 USD/KSM ~ 1.476 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xcd2d464d3c90212247df6b468960fa972224d5cf4da14688af65ed4969e634a6](https://kusama.subscan.io/extrinsic/0xcd2d464d3c90212247df6b468960fa972224d5cf4da14688af65ed4969e634a6)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
