### PR TITLE
Trying to make EVM work [Feat/evm/v1]

### PR DESCRIPTION
**Pull request by vikiival**

### CODE REVIEW

**Comment by vikiival** [comment]
@Jarsen136 can you please make it buildable ?

**Comment by Jarsen136** [comment]
> @Jarsen136 can you please make it buildable ?

I have no idea about it as it builds well on my side.
Is there any useful failed log that could be referred?

**Comment by vikiival** [comment]
> > @Jarsen136 can you please make it buildable ?
> 
> I have no idea about it as it builds well on my side. Is there any useful failed log that could be referred?

[koda-art-prod.11204c0b-8a72-44f3-8c35-b568c811d71a.log](https://github.com/user-attachments/files/16014629/koda-art-prod.11204c0b-8a72-44f3-8c35-b568c811d71a.log)

**Comment by Jarsen136** [comment]
Here we go~  @vikiival 
image

https://github.com/kodadot/nft-gallery/pull/10534/commits/a526949e81c79091a59fffa8901aedf2410ec51d

Another way to fix this is to replace the build command from `pnpm run generate` to `pnpm run build`.
image

cc @preschian

**Comment by vikiival** [comment]
Amazing ❤️❤️❤️

**Comment by vikiival** [comment]
@Jarsen136 can you pls resolve?

Screenshot 2024-06-28 at 12 53 22

**Comment by Jarsen136** [comment]
> @Jarsen136 can you pls resolve?
> 

Fixed

**Comment by Jarsen136** [comment]
Is it time to merge it?  👀

**Comment by vikiival** [comment]
Yup

**Pull request merged**
