### PR TITLE
feat: Drop image examples and carousel

### LINKED ISSUE #6280: Drop image examples and carousel
At the start I personally thought that the nft you get would be random - thus, I made the design look like it is now. :D 
image
>In past we thought selecting waifus would be good, yet as we want to remove any kind of cognitive load on users and play good numbers (as it's heavily important for us) make it dumb and easy.

Now we will prepare it for future campaigns - random drop 

Changes 
---
- add copy to the img carousel: 
image
- limit the imgs displayed to only 4 and make it an infinite carousel
- add arrows 
image

### Mobile 
image
- copy in the middle

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Needs Design check

- @exezbcz please review

## Context

- [x] Closes #6280
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed UI

image

### <samp>🤖 Generated by Copilot at a9dfde4</samp>

This pull request improves the image slider component for the unlockable campaign feature, by adding a looping feature, a text message, and custom styling. It also refactors some code, fixes some bugs, and adds some localization and constants. The main files affected are `ImageSlider.vue`, `UnlockableContainer.vue`, `const.ts`, `en.json`, and some style files.

### <samp>🤖 Generated by Copilot at a9dfde4</samp>

> _Sing, O Muse, of the skillful coder who enhanced the image slider_
> _With looping feature, text message, and custom styling for the arrows_
> _He fetched and displayed the latest waifu images, `DISPLAY_SLIDE_IMAGE_COUNT`_
> _And added the `mint.unlockable.imageTip` to the `en.json` file_

### CODE REVIEW

**Comment by exezbcz** [comment]
looking good!

one thing to the carousel: 
- it wont basically be a carousel, the images wont move, only 4 imgs total 
>limit the imgs displayed to only 4 and make it an infinite carousel

sorry for the confusion with an infinite one.

**Review by vikiival — APPROVED** [review]

**Comment by prury** [comment]
@exezbcz is mobile ok to you or it should be aligned to the left?
image

**Comment by exezbcz** [comment]
@prury yeah, the copy that indicates that the preview is only one of many possible drops should not be 2 row
- then the preview on mobile should be also square - not changing the ar of 1:1

**Comment by Jarsen136** [comment]
I have made some updates according to the above comments. Pls check it. @exezbcz @prury 
image

**Comment by exezbcz** [comment]
nice job! thanks

**Review by preschian — APPROVED** [review]

**Pull request merged**
