### PR TITLE
:bug: navbar non-mobile smaller screen

### LINKED ISSUE #4513: Broken navbar on non-mobile narrow device
This can be fixed in this issue as it's for the non-mobile devices but on 600px width. 

image

On 600px width non-mobile, I see this 

image
image

Address select dialogue
but I guess that's going to be resolved in #4405 
image

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/4483#issuecomment-1354745469_

### PR DESCRIPTION
**Pull request by petersopko**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4513
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [x] I've tested it at </bsx/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

### CODE REVIEW

**Comment by yangwao** [comment]
what's about bottom part?

**Comment by petersopko** [comment]
> what's about bottom part?

what do you want to do about the bottom part?  do you mean it should be centered? 

or should all of this look as on mobile? I've looked into the figma and can't find design spec for smaller screen desktop.

maybe @exezbcz can guide me here?

**Comment by yangwao** [comment]
> do you mean it should be centered?

yes

> should all of this look as on mobile?

yes, use mobile approach till we will have tablet/smaller desktop screen

https://github.com/kodadot/nft-gallery/issues/4125#issue-1410746496

**Comment by yangwao** [comment]
probably remove those bottom lines and it's ok to go

image

this happens actually when mobile is triggered, on narrow desktop it's centered (but still has bottom lines)

image

**Comment by exezbcz** [comment]
this is the design for the bottom part - its old so it doesnt have the features like in wallet hover - but its basically the profile 

- in navbar, profile and wallet should collapse to its sections. 
image
(connected)
- and when opening profile section - 
image

so there isnt a design for the case like this - that means it should not be here

At the bottom there should be connect button when you are not connected.

**Comment by petersopko** [comment]
@yangwao updated

**Comment by yangwao** [comment]
Some sections don't work along like the design

Create
image

Stats
image

Missing Change Account to be consistent with desktop
image

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 25.19 USD/KSM ~ 1.985 $KSM
🧗 [FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y](https://kusama.subscan.io/account/FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y)
🔗 [0x5e1f1ab2c2e534ec33d924e03a2dffc84a932767b172d792ea3b00a6265da0ee](https://kusama.subscan.io/extrinsic/0x5e1f1ab2c2e534ec33d924e03a2dffc84a932767b172d792ea3b00a6265da0ee)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
