### PR TITLE
Add buy now from gallery feed when there is grouped NFTs

### LINKED ISSUE #1041: Add buy now from gallery feed when there is grouped NFTs
Whenever you are surfing with BUY NOW turned on, we should show BUY somewhere on the card.

I would add to the bottom right corner shop button on hover https://fontawesome.com/v5.15/icons/shopping-cart?style=solid

image

### PR DESCRIPTION
**Pull request by TK-Development**
**Thank you for your contribution** to the KodaDot NFT gallery.
Let's do a quick check before the merge.
Your contribution will be an eternal part of the community codebase.

### PR type
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### Before submitting this PR, please make sure:
- [x] Code builds clean without any errors or warnings
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional
- [x] I've tested it on mobile and everything works
- [ ] I found edge cases

### What's new? (may be part of changelog)
- This PR resolves #1041 - Add buy now from gallery feed when there is grouped NFTs

### If issue had bounty label ($,$$,$$$)
- Fill up your KSM address: https://kodadot.xyz/transfer/?target=Ef14jyREXDkhsZV6wVfRqzgE2ayUe7fiK357ma6siwEpHtr

### Community participation
- [x] Are you at KodaDot Discord? If not yet, [let's join us - https://discord.gg/35hzy2dXXh](https://discord.gg/35hzy2dXXh)

### Screenshot
- [x] Whenever my fix has changed **something** on UI, a screenshot for others, is more than welcome

### CODE REVIEW

**Comment by TK-Development** [comment]
@yangwao , @vikiival , please check this.
I'd like to close this one and resolve new one.
image

**Comment by yangwao** [comment]
why is there `public/cart.svg` ?

doesn't work for me, where it should appear? 
image

**Comment by TK-Development** [comment]
Removed cart.svg file. I used fontawesome.

**Comment by yangwao** [comment]
> @yangwao , @vikiival , @roiLeo please check this. I'd like to close this one and resolve new one. image

I don't see it, how I can reproduce it to see what you did?

**Comment by yangwao** [comment]
Found it on collection https://deploy-preview-1050--nftkodadot.netlify.app/rmrk/collection/fc494d56d641ea4d7f-NEUROGANG

But seems just redirects me to the gallery item.

Let's add it on each NFT which has LIST price so ppl can directly buy it, w/o redirect.

**Comment by TK-Development** [comment]
Add these icon in collection and gallery for NFTs which has LIST price?
And when user click this, the user can directly buy it?

**Comment by yangwao** [comment]
> Add these icon in collection and gallery for NFTs which has LIST price? And when user click this, the user can directly buy it?

In the collection, it's probably won't work because the collection doesn't need inherently the same NFT.
In gallery yes for every NFT with LIST and grouped makes sense.

When a user clicks, it should offer him to trigger the same BUY as is on gallery item detail.

**Comment by yangwao** [comment]
Hey @TK-Development let's finish this one! :)
Happy to send payout when it's done!

**Comment by yangwao** [comment]
Converted to draft as I didn't see the response for 2 days.

**Comment by yangwao** [comment]
Pinged DMs Arsen on Discord about this, if no reply, will close it.

**Comment by yangwao** [comment]
Hey, I'm closing this as seems to lack progress and attention from the PR author.

**Pull request closed without merging**
