### PR TITLE
Delete cypress again

### PR DESCRIPTION
**Pull request by prury**
Part of #6598 

tried to delete cypress following instructions from an old PR, moved all contents to a cypress-deprecated folder in case its information is needed in the near future.

be aware that this is my first PR, ever. 
Be gentle😄 

**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

### <samp>🤖 Generated by Copilot at c30af1e</samp>

Removed Cypress and its dependencies from the project and moved the existing Cypress tests to a deprecated folder. This was done to switch to Playwright as the new end-to-end testing framework.

### <samp>🤖 Generated by Copilot at c30af1e</samp>

> _Sing, O Muse, of the valiant code review_
> _That purged the testing scripts of Cypress old_
> _And brought instead the swift Playwright anew_
> _To run the end-to-end tests manifold._

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
Hello new developer!
That's a good start, I would deprecate/remove more stuff:
- `cypress.config.ts` file in tests folder
-  `**/cypress/**` line in `vite.config.js`
- cypress badge in `README.md`
- comment cypress line in `.gitignore`
- cypress stuff in `CONTRIBUTING.md`

I would keep `unsplash-image.jpg` because this can be used to rewrite some tests.

Goal of #6598 is to migrate cypress to playwright, you can find loads of tutorials online (like [this post](https://dev.to/lucgagan/migrating-from-cypress-to-playwright-pn0)).
Maybe you can try something 😉

**Comment by prury** [comment]
> 



> Hello new developer! That's a good start, I would deprecate/remove more stuff:
> 
>     * `cypress.config.ts` file in tests folder
> 
>     * `**/cypress/**` line in `vite.config.js`
> 
>     * cypress badge in `README.md`
> 
>     * comment cypress line in `.gitignore`
> 
>     * cypress stuff in `CONTRIBUTING.md`
> 
> 
> I would keep `unsplash-image.jpg` because this can be used to rewrite some tests.
> 
> Goal of #6598 is to migrate cypress to playwright, you can find loads of tutorials online (like [this post](https://dev.to/lucgagan/migrating-from-cypress-to-playwright-pn0)). Maybe you can try something 😉

ohhh, he called me a new developer ❤️ 
will make the changes, i appreciate. 

Yes I'm already researching on how to install playwright, will read the link you sent, I'm using this guide atm: [Playwright](https://snyk.io/blog/how-to-add-playwright-tests-pr-ci-github-actions/)

**Review by preschian — APPROVED** [review]

**Review by roiLeo — APPROVED** [review]
Noice!

✅ code lgtm

**Comment by yangwao** [comment]
> be aware that this is my first PR, ever.

you are making it !

**Pull request merged**
