### PR TITLE
#2886 instagram link on landing page

### LINKED ISSUE #2886: Can we put instagram link somewhere on our landing page?
### Is your feature request related to a problem?

Since we are currently starting with KodaDot instagram account, let's put link to our landing page and officially release it on twitter etc. There is currently 9 posts so it's ready to get some proper attention.

https://instagram.com/kodadot.xyz/

### Describe the solution you would like

Only thing i'm asking - where would be the ideal placement?

### Describe alternatives you have considered

/

### Screeenshots

/

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #2886

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screenshot 2022-04-19 at 5 36 52 PM

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
I thought it would be interesting to change the order of the icons, like:
Discord -> Twitter -> Instagram -> Youtube -> Medium
What do you think?

**Comment by prachi00** [comment]
@roiLeo changed the order

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 165.04 USD/KSM ~ 0.606 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x253d9a39daf971388a24ff6d3bc354b220ef4e08b2cad7c59527f77e97d03fa2](https://kusama.subscan.io/extrinsic/0x253d9a39daf971388a24ff6d3bc354b220ef4e08b2cad7c59527f77e97d03fa2)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
