### PR TITLE
Migrated NeoSecondaryButton to tailwindcss

### PR DESCRIPTION
**Pull request by shashkovdanil**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Closes #8222 
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [x] I've tested it at </ksm/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer?target=16SpvdDgKNiQ3c53DxX7refnQcKUD3uRNim3Z1HBJLNGrtSP&usdamount=0)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 07d26e6</samp>

This pull request optimizes the SCSS and Vue code for the NeoButton and NeoSecondaryButton components, by importing only the needed SCSS files from Oruga UI, and using Tailwind CSS utility classes for styling.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 07d26e6</samp>

> _`Oruga` imports trimmed_
> _Tailwind classes simplify_
> _`NeoButton` shines_

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
see #8362

**Comment by roiLeo** [comment]
> > see #8362
> 
> What exactly?

I'm already working on this one, I think `NeoSecondaryButton` should be in `NeoButton` with variant

**Comment by prury** [comment]
> > > see #8362
> > 
> > 
> > What exactly?
> 
> I'm already working on this one, I think `NeoSecondaryButton` should be in `NeoButton` with variant

close this one or wait?

**Comment by roiLeo** [comment]
continue in #8362

**Pull request closed without merging**
