### PR TITLE
fix: ipfs utils bypass kodaimage

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Prevent unnecessary loop kodaimage domain. `https://image-beta.w.kodadot.xyz/type/url?endpoint=https%3A%2F%2Fimage-beta.w.kodadot.xyz%2Fipfs%2FQmemp5BQHr6QBBqd3Qf3subgZ4tm2xVYjFv5AC4Tf2bzqS%2Flegs%2FSports+Shorts+thumb.png`
- [x] Open https://canary.kodadot.xyz/ksm/gallery/15878768-342f12106eab6d904c-YOUDLECHEST-YOUDLECHEST-00011691 and see `Media` link on the Details tab. The link was not broken, but it was unnecessary

Screenshot 2023-11-13 at 9 36 01 PM

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)

## Screenshot 📸

- [ ] My fix has changed UI

### <samp>🤖 Generated by Copilot at ba952cb</samp>

Refactored IPFS utils to handle different URL formats and added documentation.

### <samp>🤖 Generated by Copilot at ba952cb</samp>

> _Sing, O Muse, of the skillful coder who refined_
> _the IPFS utils, that wondrous tool of the web,_
> _where images of Koda, the swift-footed hound, reside_
> _and shine like stars in the dark vault of the net._

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]

**Review by daiagi — APPROVED** [review]

**Comment by yangwao** [comment]
@prury so I guess it's good? 

image

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 5.51 USD/DOT ~ 5.445 $DOT
🧗 [1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p](https://polkadot.subscan.io/account/1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)
🔗 [0x7fa3764e6092c4a827dbb49061f7e8cc7654effc2306b8a8a7fe16feb4b9435d](https://polkadot.subscan.io/extrinsic/0x7fa3764e6092c4a827dbb49061f7e8cc7654effc2306b8a8a7fe16feb4b9435d)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by prury** [comment]
> @prury so I guess it's good?
> 
> image

i guess, was talking to preschian in dms but let it roll

**Pull request merged**
