### PR TITLE
fix: Sorting by price should always keep Buy Now on

### LINKED ISSUE #3516: Sorting by price should always keep 'BUY NOW' on
> btw it seems to have issues even in the other way around? when I untoggle 'BUY NOW' the filter for gt.than > 0 disappears, but when I'm sorting by price desc.; I get to see NFTs with highest price (but price isn't showing in the gallery card).

Always been like this, no? 
https://kodadot.xyz/rmrk/explore?page=1&tab=GALLERY&listed=false&sort=PRICE_DESC

> Maybe this is something we should fix elsewhere, if the price is 0 we don't need the gallery card desc. but if it's more than that, we should show the price regardless of the 'BUY NOW' toggle position

Or we could try to toggle "BUY NOW" when sorting by PRICE and it would show the price on cards

_Originally posted by @roiLeo in https://github.com/kodadot/nft-gallery/pull/3474#issuecomment-1191402096_

just additional comment here, since sorting by price implies, you'd like to see NFTs with price more than 0, picking this sorting option should check whether 'BUY NOW' toggle is on and if not, turn it on

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3516
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by petersopko** [comment]
works exactly as expected, code LGTM

**Review by petersopko — APPROVED** [review]

**Review by cryptodamsky — COMMENTED** [review]
Yup this feature works:)

**Review by cryptodamsky — APPROVED** [review]

**Comment by petersopko** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 68.13 USD/KSM ~ 0.734 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x16c13b7784febb36bbfcac663ad5f402c44f8d7296765dce096bed00b809d613](https://kusama.subscan.io/extrinsic/0x16c13b7784febb36bbfcac663ad5f402c44f8d7296765dce096bed00b809d613)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
