### PR TITLE
fix: keep desc while loading

### LINKED ISSUE #4094: Keep description of collection between pagination
After fixing 
- #4089 
- #4093 

There is some weird thing happening fetching metadata of collection, especially in this case description of the collection. 
Would it be possible to not re-render the component and keep it there when switching between pages of items?
Longer description collection has, worse it is :|

Test here 
https://beta.kodadot.xyz/glmr/collection/0xfd86d63748a6390e4a80739e776463088811774d?page=32

https://user-images.githubusercontent.com/5887929/194698596-43a82c2f-4a1c-4f61-857c-5e0134e11ca7.mov

### PR DESCRIPTION
**Pull request by KngZhi**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #4094
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer?target=DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

https://user-images.githubusercontent.com/11361147/194735034-c978f3fa-9962-4711-b37b-b5937ffab36b.mov

### CODE REVIEW

**Review by prachi00 — APPROVED** [review]

**Comment by KngZhi** [comment]
@petersopko mind making a review :)

**Comment by yangwao** [comment]
yes! thank you!

pay 30

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 41.54 USD/KSM ~ 0.722 $KSM
🧗 [DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc](https://kusama.subscan.io/account/DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc)
🔗 [0x3bd7bfcbe634b8c09a25bcd53fcb9fb9c2601c2ded0cf11daef2e0b4edebb10c](https://kusama.subscan.io/extrinsic/0x3bd7bfcbe634b8c09a25bcd53fcb9fb9c2601c2ded0cf11daef2e0b4edebb10c)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
