### PR TITLE
fix: series insight sorting (client-only)

### LINKED ISSUE #1757: Sorting doesn't work on series
Sorting doesn't work on series.

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/1663#issuecomment-1003765030_

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇  _ Do a quick check before the merge.

### PR type
- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

https://user-images.githubusercontent.com/17953978/149520423-deb5a5d4-fc31-4eb2-8d7b-b300b05469da.mov

### What's new?
- [x] PR closes #1757
- [x] note that this only fixed client-side sorting; im not aware that backend can handle sorting and only goes by rank right?

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main-nuxt** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional
- [x] I've tested it at </series-insight>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases

### Had issue bounty label ?
- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation
- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [ ] My fix has changed **something** on UI, a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by yangwao** [comment]
I guess I would like to join it to be the more cohesive solution by @roiLeo 
- https://github.com/kodadot/rubick/pull/14
- https://github.com/kodadot/rubick/pull/18

Not sure which PR (14 or 18 is better) @vikiival can speak

**Comment by kkukelka** [comment]
@yangwao sure thing. i'll keep this open until the backend stuff is merged and adapt to changes

**Comment by vikiival** [comment]
Rubick is redeployed again :) @kkukelka

**Comment by kkukelka** [comment]
> /giphy what is happening here

@roiLeo seems to be doing it already in #1913 so i think i will just close this

**Pull request closed without merging**
