### PR TITLE
fix: Mobile landing on new neobrutalism design

### LINKED ISSUE #4146: Mobile landing on new neobrutalism design
Seems we need to check on mobile issues with view port and navbar tho :)

https://user-images.githubusercontent.com/5887929/196670975-071dff05-367b-4ac6-bc89-9e5e65e149d9.mov

## Ref
- https://github.com/kodadot/nft-gallery/issues/4125

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #4146
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

Kapture 2022-10-19 at 22 53 28

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
- got trouble to connect wallet on mobile
- same things for changing language or theme
- I find the buttons in the footer a bit too close for my hand

**Comment by Jarsen136** [comment]
> * got trouble to connect wallet on mobile
> * same things for changing language or theme
> * I find the buttons in the footer a bit too close for my hand

Hey, this PR is to close #https://github.com/kodadot/nft-gallery/issues/4146, related to the viewport when scrolling. 👀

**Comment by yangwao** [comment]
> * I find the buttons in the footer a bit too close for my hand

fwded to #4125

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 38.01 USD/KSM ~ 1.315 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xa3cf77f8fb013d271fd287612bd19021d0c36442deb9e8dff18f70e035e26544](https://kusama.subscan.io/extrinsic/0xa3cf77f8fb013d271fd287612bd19021d0c36442deb9e8dff18f70e035e26544)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
