### PR TITLE
#2230 Move views to bottom right and border changes

### LINKED ISSUE #2230: Move 'default view' to bottom right
In the upper corner, we have a button default / theatre view 
- move it to bottom right next to full screen mode and replace it with icon cube https://fontawesome.com/v5.15/icons/cube?style=solid
- replace icon for full screen with expand https://fontawesome.com/v5.15/icons/expand?style=solid
- on full screen replace minimize with compress https://fontawesome.com/v5.15/icons/compress?style=solid
image
- remove border from NFT art
- for icons only keep top-border 
- on arrow keep only top-border as well 
 

image
image

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2230
- [ ] 

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screenshot 2022-02-07 at 6 48 44 PM
Screenshot 2022-02-07 at 6 48 56 PM

### CODE REVIEW

**Comment by yangwao** [comment]
- I would swap order icons, first modify picture and second fullscreen.

image

- plus I guess we can make them be at the edge of the picture 

image

and I'm thinking let's try to add some opacity

- at bottom right, let's remove top-border and add opacity to background
```css
background: rgb(0 0 0 / 0%)
```
image

- on navigation buttons I guess 
```css
background: rgb(0 0 0 / 60%)
```
With full width picture it should be way better I guess #2256 

image

**Comment by prachi00** [comment]
Screenshot 2022-02-08 at 12 14 31 A src=
@yangwao with this level of opacity, if the background is light, it wont be visible, same for the navigation button as well

I have pushed the other change with icon position, let me know what to do about this one.

**Comment by prachi00** [comment]
> @yangwao with this level of opacity, if the background is light, it wont be visible, same for the navigation button as well 
Screenshot 2022-02-08 at 12 15 57 AM
> 
and also opacity makes it look like they are disabled buttons

> I have pushed the other change with icon position, let me know what to do about this one.

**Comment by yangwao** [comment]
> @yangwao with this level of opacity, if the background is light, it wont be visible, same for the navigation button as well Screenshot 2022-02-08 at 12 15 57 AM

Oh good catch, let's try 60% ? 
Or we can set the icon to greyscale spectrum whenever pic will be black/white, let's try?

> And also, opacity makes the button look disabled I think

Yeah, we will look for what's best in other iterations :)

> I have pushed the other change with icon position, let me know what to do about this one.

image

Let's put it next to each other so we don't have that vertical spacing between them

**Comment by yangwao** [comment]
lgtm, great work there! :) 
let's wait for a review from @roiLeo as NFT item detail is precious asset for us

**Review by roiLeo — APPROVED** [review]
lgtm

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 186.82 USD/KSM ~ 0.535 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0xc3257fb73e22d0dcc0491e63afe23c4064c85cf51772180d928579de101d4616](https://kusama.subscan.io/extrinsic/0xc3257fb73e22d0dcc0491e63afe23c4064c85cf51772180d928579de101d4616)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
