### PR TITLE
feat: Generate symbol at simple mint from name

### LINKED ISSUE #2150: Generate symbol at simple mint from name
Plus add a check if under the same artists doesn't exist the same symbol if does, short it one char and add increment number? 

Like if I have NFTLOVE, the next symbol could not be NFTLOVE so it would generate NFTLOV2 simple as that.
OR 
use https://www.npmjs.com/package/nanoid for generating symbol as collision would be super low I bet

We want to lower the barrier for entry users, really :)

Check which symbols could be used according to spec https://github.com/rmrk-team/rmrk-spec

image

### PR DESCRIPTION
**Pull request by zhengow**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2150
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at <rmrk/mint>
- [x] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

https://user-images.githubusercontent.com/38389586/156399796-b38935a7-3524-424d-9a2e-52b0fdd69731.mp4

### CODE REVIEW

**Comment by yangwao** [comment]
lgtm 

pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 121.05 USD/KSM ~ 0.826 $KSM
🧗 [EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws](https://kusama.subscan.io/account/EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)
🔗 [0x47b94a4b83ace3b1e4f0e987506a208294cabd5efd113a2069f9e16ac7b4f344](https://kusama.subscan.io/extrinsic/0x47b94a4b83ace3b1e4f0e987506a208294cabd5efd113a2069f9e16ac7b4f344)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Review by vikiival — CHANGES_REQUESTED** [review]
This is no good at all

## Ad1: 

Why do you query all NFTs by the user?

Instead, you should query a minimum of collections by the user (id, symbol)

## Ad2:

function `generateSymbolCore` is really hard for me to read
rather use already made function from `minimark`

```ts
import { findUniqueSymbol } from '@kodadot1/minimark'
```

implementation of [findUniqueSymbol](https://github.com/vikiival/minimark/blob/22d57f62b85b5c4b9bbcf7660b5299e46b4fcf4d/src/rmrk/identification.ts#L33)

P.S.: Most of this is implemented in branch [bye-symbol](https://github.com/kodadot/nft-gallery/compare/bye-symbol)

**Comment by zhengow** [comment]
> 



> ```ts
> import { findUniqueSymbol } from '@kodadot1/minimark'
> ```

**Comment by zhengow** [comment]
> To be honest: I am not fan of this implementation at all
> 
> ## Ad1:
> Why do you query all NFTs by the user?
> 
> Instead, you should query a minimum of collections by the user (id, symbol)
> 
> ## Ad2:
> function `generateSymbolCore` is really hard for me to read rather use already made function from `minimark`
> 
> ```ts
> import { findUniqueSymbol } from '@kodadot1/minimark'
> ```
> 
> implementation of [findUniqueSymbol](https://github.com/vikiival/minimark/blob/22d57f62b85b5c4b9bbcf7660b5299e46b4fcf4d/src/rmrk/identification.ts#L33)
> 
> P.S.: Most of this is implemented in branch [bye-symbol](https://github.com/kodadot/nft-gallery/compare/bye-symbol)

Learned a lot, thanks.
Already fix by what u said, plz check again

**Pull request merged**
