### PR TITLE
fix: Auto teleport - user should have at least 1.5 DOT

### LINKED ISSUE #9929: Auto teleport - user should have at least 1.5 DOT
> The only option for now is for the user to have at least 1.5DOT on Polkadot and only transfer sum they have above 1.5 DOT

Please check all dialogs where we use teleport 

@kodadot/internal-dev if someone can have look? Thank you very much

Ref
-
- https://github.com/kodadot/nft-gallery/issues/9596

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/pull/9928#issuecomment-2026906885_

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

based on 

CleanShot 2024-04-01 at 13 14 01@2x

CleanShot 2024-04-01 at 13 28 41@2x

ED is already 1.5  DOT, disabled the feature that allowed the autotelport of all balance in the case of slashing, 

**now you can only autotelport any sum above of 1.5** 

just to make sure tested all the remaining autotelport logic , as far I can see it's working as expected. @prury please test  

- [x] Closes #9929

## Needs QA check

- @kodadot/qa-guild 

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [ ] My fix has changed **something** on UI;

### CODE REVIEW

**Comment by prury** [comment]
nice finding, it was this then that was causing the bug, ty

**Comment by vikiival** [comment]
If it works let's merge it.

The code you have commented out is unreadable for me, sorry

**Comment by hassnian** [comment]
> The code you have commented out is unreadable for me, sorry

fair enough,  can remove it if you want

the auto-teleport needs some refactoring to be done https://github.com/kodadot/nft-gallery/issues/9695

**Review by daiagi — APPROVED** [review]

**Comment by prury** [comment]
@vikiival can we get approval?

**Review by vikiival — APPROVED** [review]

**Comment by prury** [comment]
pay 15 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $15 @ 8.63 USD/DOT ~ 1.738 $DOT
🧗 [16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD](https://polkadot.subscan.io/account/16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)
🔗 [0x7d8344caa179a23c93c6faedb9a2de9149e76fbec9c1203ce2fdd822c88da1ed](https://polkadot.subscan.io/extrinsic/0x7d8344caa179a23c93c6faedb9a2de9149e76fbec9c1203ce2fdd822c88da1ed)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
