### PR TITLE
fix: identity and remove persist in wallet store

### LINKED ISSUE #5949: Unable To mint on localhost
### What happened?

encounter while testing massmint minting
i am now unable to mint on RMRK on localhost

tested on main branch => not related to massmint itself

### Please reproduce in steps

on local host
kusama network
try minting an NFT
got ```unable to retrieve keypair 'H2a3UNNEUL7e2WZYR47twJr4KEbyXZn9gBYnWzxdpqyJ2Q3'```

### Expected Behavior

be able to mint

### What browsers are you seeing the problem on?

Desktop Chrome

### At which address did you encounter bug?

localhost

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### At which chain did you encounter bug?

Kusama

### Screenshots

image

image

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #5956: Unable to retrieve keypair on canary for transfer
Can we have working Transfer on Canary again please? 

On Beta I've already processed payments through with same wallet so it worked there. 
I've tried empty cache, did not worked. Not even trigger authentication request when I deleted access in PolkadotJS extension

https://github.com/kodadot/nft-gallery/assets/5887929/4ba26cdf-86fb-4ab0-8e95-5418630d7378

I've also noticed there is missing identity in Transfer too

Any idea?

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5949
- [x] Closes #5956
- [x] fix identity same with https://github.com/kodadot/nft-gallery/pull/5950/files#diff-b47b7c47a2240d029254629652541a3a5747873eec36f5b11ffa1203cfc64c34R89

Screenshot 2023-05-14 153509

### <samp>🤖 Generated by Copilot at f3aff54</samp>

This pull request improves the identity and wallet state management by fetching the identity data on component mount and disabling the local storage persistence of the wallet store. It affects the files `useIdentity.ts` and `wallet.ts`.

### <samp>🤖 Generated by Copilot at f3aff54</samp>

> _`useIdentity` calls_
> _`whichIdentity` on mount_
> _identity shown_

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
Code lgtm

**Comment by yangwao** [comment]
perfecto 👌 

pay 30 usd

image


https://kusama.subscan.io/extrinsic/0x9d8c7a9c91a2cdf4ace499c6d3d388303e4f574fa8b3f12208f2e5bf0d0d772b

**Comment by yangwao** [comment]
pay 30 usd

updated issue for you :)

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 25.23 USD/KSM ~ 1.189 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0xf1821b1628ea505eceb8741640567b4a1c12bdfcf41e14a0b6634e9ab4a422a7](https://kusama.subscan.io/extrinsic/0xf1821b1628ea505eceb8741640567b4a1c12bdfcf41e14a0b6634e9ab4a422a7)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
