### PR TITLE
#1417 Add YOLO to user preference

### LINKED ISSUE #1417: Add YOLO to user preference
- replace for user Buy Now with Yolo at particular places
- in collection filter, gallery, collections etc
- Replace BUY button at item detail with Yolo

### Ref
- https://github.com/kodadot/nft-gallery/issues/1382
- #942 
- #1160 
- https://github.com/kodadot/nft-gallery/issues/1311
- https://github.com/kodadot/nft-gallery/pull/1395

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇  _ Do a quick check before the merge. 

### PR type
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything works
- [ ] I found edge cases

### What's new?
- [x] PR closes #1417
- [x] Added in
        - [x]  Gallery Item
        - [x]  Collections
  
### Had issue bounty label ?
- [x] Fill up your KSM address: 
[Payout](https://kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation
- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [x] My fix has changed **something** on UI, a screenshot for others, is best to understand changes.
Screenshot 2021-12-26 at 7 22 57 PM
Screenshot 2021-12-26 at 7 23 13 PM
Screenshot 2021-12-26 at 7 25 35 PM

### CODE REVIEW

**Comment by yangwao** [comment]
@prachi00 gallery has "buy now" which should be changed :)
image

**Comment by prachi00** [comment]
> @prachi00 gallery has "buy now" which should be changed :) image

@yangwao yeah missed this one, added now.

**Comment by yangwao** [comment]
Not sure where is an error if service worker push old data even after flushed application still see old one 
Build seems successfull.
image

**Comment by yangwao** [comment]
oh I see, there is even more complicated error, like service worker on that toast receive a new update, but won't update running runtime, that seems badass

image

**Comment by yangwao** [comment]
Perfect, I’ve sent the payout https://kusama.subscan.io/extrinsic/0x4d07721377a8b264d524b6641ba7118a6cafea478edfe74723a94afb3e30e358

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/

**Pull request merged**
