### PR TITLE
Fix : Identity creation: Add Select chain #7823

### LINKED ISSUE #7823: Identity creation: Add Select chain
It would be cool to have an option to select on what chain you want to create your identity. At the moment its possible only  change it only when you change chain in the main menu.

Screenshot 2023-10-25 at 12 10 03

### PR DESCRIPTION
**Pull request by AshutoshSingh00001**
Thank you for your contribution to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz/).

👇 __ Let's make a quick check before the contribution.

## PR Type
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #7823
- [x] ## Did your issue had any of the "$" label on it?
- [x] My DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=158VTDxZJidzsMcAdh7h828domveRvpmk1SCxwLUEHhcgY4v&usdamount=0&donation=true)

### CODE REVIEW

**Review by roiLeo — CHANGES_REQUESTED** [review]
Screenshot 2023-10-31 at 16-26-41 Fix Identity creation Add Select chain #7823 by AshutoshSingh00001 · Pull Request #7905 · kodadot_nft-gallery

**Comment by AshutoshSingh00001** [comment]
> Screenshot 2023-10-31 at 16-26-41 Fix Identity creation Add Select chain #7823 by AshutoshSingh00001 · Pull Request #7905 · kodadot_nft-gallery
> 
> error-the-simpsons [ error-the-simpsons ](https://user-images.githubusercontent.com/9987732/279430104-bacd9890-ea3b-4007-a65e-f96e9467cc86.gif) [ ](https://user-images.githubusercontent.com/9987732/279430104-bacd9890-ea3b-4007-a65e-f96e9467cc86.gif)

got it bro working on it

**Comment by AshutoshSingh00001** [comment]
@roiLeo All checks have passed

**Review by roiLeo — COMMENTED** [review]
> @roiLeo All checks have passed

Yes but the code doesn't work as excepted, please test it before adding changes.

**Comment by AshutoshSingh00001** [comment]
> > @roiLeo All checks have passed
> 
> Yes but the code doesn't work as excepted, please test it before adding changes.

sure

**Comment by AshutoshSingh00001** [comment]
> > @roiLeo All checks have passed
> 
> Yes but the code doesn't work as excepted, please test it before adding changes.

My final upgrade with all new changes with All checks passed @roiLeo @daiagi

**Comment by exezbcz** [comment]
image
it does not check if i have my onchain identity set or not


image
- please apply the same spacing as is between handle and the input, plus more space between handle and the input above

**Comment by AshutoshSingh00001** [comment]
> image it does not check if i have my onchain identity set or not
> 
> image
> 
> * please apply the same spacing as is between handle and the input, plus more space between handle and the input above

1: okay so you mean this form should disappear when you already have an identity right ?
2: okay I'll apply it

**Comment by AshutoshSingh00001** [comment]
> image it does not check if i have my onchain identity set or not
> 
> image
> 
> * please apply the same spacing as is between handle and the input, plus more space between handle and the input above

well there is one problem which is already there which I want to fix but not mentioned in this issues I have took but I'll still update it I mean that when a user already have an identity the button name should change to update identity  not create identity

**Comment by AshutoshSingh00001** [comment]
closing this one too many commits refreshing with new one

**Pull request closed without merging**
