### PR TITLE
integration/mantle

### PR DESCRIPTION
**Pull request by vikiival**
- **mantle in libs/static/src/chains.ts**
- **mantle in libs/static/src/endpoints.ts**
- **mantle in libs/static/src/indexers.ts**
- **mantle in libs/static/src/names.ts**
- **mantle in libs/static/src/services.ts**
- **mantle in libs/static/src/types.ts**

**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [x] Integration

## Context

Adds integration of mantle to KodaDot 

- [x] Requires deployment kodadot/basick/flock.yml

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

Indexer not ready yet

### CODE REVIEW

**Comment by vikiival** [comment]
@hassnian If I forgot some setting pls let me knwo

**Comment by vikiival** [comment]
Screenshot 2024-08-07 at 15 43 58

need help with this one cc @hassnian

**Comment by vikiival** [comment]
Also I cannot go to /mnt/drops

**Comment by hassnian** [comment]
@vikiival should work now

 I have enabled transactions to any vm that is evm, let me know if should revert that and have it specific,  see these commits

CleanShot 2024-08-08 at 12 26 34@2x

`MNT` price will return 0 , could be fixed in the front, I've opened an issue https://github.com/kodadot/workers/issues/325

**Comment by vikiival** [comment]
> I have enabled transactions to any vm that is evm

Amazing ❤️

**Comment by vikiival** [comment]
deploy-preview-10767--koda-canary netlify app_mnt_drops_circuits(iPad Air)

**Pull request merged**
