### PR TITLE
feat: create and follow profiles on Base

### LINKED ISSUE #10382: Create profile dies on Base
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

Since the button allowes me to to it, I tried to create a profile with my EVM wallet.
Sadly the whole component died

### Please reproduce in steps

1. - https://github.com/kodadot/nft-gallery/pull/10354
2. Log in
3. Go to profile
4. Try to create profile

### Expected Behavior

1. I expect that I am able to create a profile

### What browsers are you seeing the problem on?

_No response_

### At which address did you encounter bug?

_No response_

### Are you logged in?

None

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

_No response_

### Screenshots

Screenshot 2024-06-03 at 13 59 52

### Wallet Address & Transaction hash

_No response_

### Relevant log output

_No response_

### Payment link for reward

https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #10466: Enable following of non-created profiles on BASE
Make it possible on base
show followers/following there as well

related: #10444

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Feature

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #10382
- [x] Closes #10466

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by vikiival** [comment]
Won't this fail on backend?

**Comment by Jarsen136** [comment]
> Won't this fail on backend?

no, I have tested it. On backend, the field of `address` is just a string.

**Comment by prury** [comment]
profile creation/editing works: 

image

following does not work there yet tho

**Comment by Jarsen136** [comment]
> following does not work there yet tho

 Fixed 
- [x] Closes #10466

**Comment by vikiival** [comment]
WFM

Screenshot 2024-06-13 at 11 24 23

**Review by vikiival — APPROVED** [review]

**Review by hassnian — APPROVED** [review]

**Pull request merged**
