### PR TITLE
459 classic mint

### PR DESCRIPTION
**Pull request by vikiival**
- 459 new ui for creating collections
- 459 updated api
- 459 WIP
- 459 collection minting works!
- 459 WIP: NFT mint
- 459 WIP: minting
- 459 still WIP
- ss58 works !
- 459 dropupload handles preview nice!
- 459 can set price
- 459 fixed critical bugs
- 459 formating && stuff
- Flexed after mint redirect
- updated redirect in simple mint

### CODE REVIEW

**Comment by yangwao** [comment]
Estimate doesn't work 
image
Warning sign is green hmm 
image
In simple mint estimate works... but it's all on white
image

**Comment by yangwao** [comment]
Tried mint but 
image
and then it passed 
image

**Comment by yangwao** [comment]
and subsocial has failed somehow
image

**Comment by vikiival** [comment]
Thanks for review @yangwao ! The update was pushed in 12a4955a41030bff72eed1fdeefecef139fa5ea4

**Comment by yangwao** [comment]
Seems pass w/o errors 🚀 
image

**Pull request merged**
