### PR TITLE
refactor: Unify usage of dark/ light mode

### LINKED ISSUE #5096: Unify usage of dark/ light mode
context: You will get `system` instead of `dark/light` value, when you visit the preview env the first time and have not set any color mode. So, I introduced this method to solve the incorrect color mode issue.  
image
   
IMO, we should make this solution a global composable method and use it everywhere to replace `useColorMode`. That could be a follow-up issue.

_Originally posted by @Jarsen136 in https://github.com/kodadot/nft-gallery/pull/5033#discussion_r1112517671_

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Closes #5096
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by vikiival** [comment]
Just wondering if we can reuse something from VueUse https://vueuse.org/core/useDark/

**Comment by Jarsen136** [comment]
> > Just wondering if we can reuse something from VueUse https://vueuse.org/core/useDark/
> 
> Yes! seems to be the way with nuxt3

Both `useDark`(VueUse) and `useColorMode`([@nuxtjs/color-mode](https://www.npmjs.com/package/@nuxtjs/color-mode)) are well supported with nuxt3 and easy to apply. I have written a demo to switch to one of the solutions. 
However, I found that we could not use  `useDark`(VueUse) for now, because some class components still use `$colorMode.preference` and so we still need to keep `@nuxtjs/color-mode` in the codebase. Once we finally refactor all components to vue3 composition api, both these two solutions could be chosen without barrier. 
@vikiival @roiLeo 

image

**Comment by vikiival** [comment]
So dumb question what will we break if we use vueuse now?

**Comment by Jarsen136** [comment]
> So dumb question what will we break if we use vueuse now?

We could not use both VueUse and useColorMode at the same time. 

For example, if we use `useToggle` from vueuse to change dark mode to true, the state($colorMode.preference) from [@nuxtjs/color-mode](https://www.npmjs.com/package/@nuxtjs/color-mode) would still be false. They will have different color mode in different componets. 

If we would like both of them have the same state, we need to do useToggle and change the `$colorMode.preference` in the same time. I guess it was a bad way.

**Comment by Jarsen136** [comment]
I'm waiting for https://github.com/kodadot/nft-gallery/pull/5033 to be merged first, so that I could apply the color mode composables to navbar component.

**Comment by Jarsen136** [comment]
> I'm waiting for #5033 to be merged first, so that I could apply the color mode composables to navbar component.

✅ Done

**Comment by vikiival** [comment]
pay 35 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $35 @ 38.8 USD/KSM ~ 0.902 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x1189cc64163cc32578c0a68db807a809c356a3731d14239ca2fd1169190a93be](https://kusama.subscan.io/extrinsic/0x1189cc64163cc32578c0a68db807a809c356a3731d14239ca2fd1169190a93be)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
