### PR TITLE
test: copy address in identity component

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] test case for this bug https://github.com/kodadot/nft-gallery/issues/3851

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by Jarsen136 — APPROVED** [review]
LGTM

**Comment by petersopko** [comment]
@preschian tried to run this in GUI, got this on all tests: 
`Timed out retrying after 10000ms: Expected to find element: .tippy-popper, but never found it.`

tried to run it locally in terminal, got this on all tests:
`Error: Browser context management is not supported.` 🤔

**Review by petersopko — CHANGES_REQUESTED** [review]
am I doing something wrong here?

**Comment by preschian** [comment]
hhmm, let's try again

> @preschian tried to run this in GUI, got this on all tests: `Timed out retrying after 10000ms: Expected to find element: .tippy-popper, but never found it.`

I put the config to disabled auto scroll on GUI. sometimes GUI auto scrolls to the bottom, so the test couldn't find the popover component

> tried to run it locally in terminal, got this on all tests: `Error: Browser context management is not supported.` 🤔

on headless, try to run with `--browser chrome`. currently I use clipboard API for chrome only because on the pipeline e2e runs with chrome. and cypress have different clipboard APIs for electron https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/testing-dom__clipboard/cypress/e2e/permissions-spec.cy.js#L11

I also change the 3d user to a non-3d user. maybe because sometimes it takes longer to render 3d assets

**Review by petersopko — APPROVED** [review]
wfm

**Comment by petersopko** [comment]
all good now, just a sidenote: I found out that if you have previously copied something to your clipboard at windows, and you run this in GUI, it's going to try to paste whatever is in your clipboard into the app. Weird, but not a problem.

**Pull request merged**
