### PR TITLE
chore: updated readme with public good writing

### LINKED ISSUE #2277: Common Good & Public good writing
More than welcome I would like to fund bounty for writing about the common good and the public good. 
You can frame it within the case study as KodaDot is doing public well being open source and sharing knowledge further and growing "framework" for NFTs 
Feel free to include their MetaPrime as common/public good for experimental NFTs

We've talked about this with @cryptodamsky and I gues whoever would like to take this one, happy to fund it. 
I guess we aim for the long-read articles, short-read would be nice as well, this more likely will be continuos bounty as we are collecting more perspectives on the public good.

Work done on Internet should be recognized as a public good. 

Maybe is worth including ReFi, [like regenerative finance](https://twitter.com/carl_cervone/status/1450593675550019586)
### 
- https://guide.kusama.network/docs/learn-common-goods/
- https://www.youtube.com/results?search_query=public+goods
- https://www.youtube.com/watch?v=JcX5urijD0s - web3foundation
- https://twitter.com/owocki 
- https://twitter.com/gitcoin
- I've asked https://twitter.com/yangWao/status/1490978403230568448
- https://twitter.com/owocki/status/1384896939293093890
- https://twitter.com/lrettig/status/1118832963683270656
- https://twitter.com/gabriellemic/status/1228860215447048192
- https://twitter.com/_Dave__White_/status/1390686770900070404
- https://twitter.com/search?q=public%20good%20%40owocki&src=typeahead_click
- https://twitter.com/owocki/status/1373810510542426113
- https://twitter.com/VitalikButerin/status/1224905811274715138
- https://twitter.com/bianca_troveaux/status/1286336472409419777
- https://twitter.com/owocki/status/1474491893803196416
- https://twitter.com/carl_cervone/status/1450593675550019586
- https://greenpill.party/

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [x] chore

### What's new?

- [x] PR closes #2277
- [x] Article went live on medium 🎉 https://medium.com/kodadot/on-sustaining-open-source-as-a-public-good-a3e8c36e67d6

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by prachi00 — APPROVED** [review]

**Comment by kkukelka** [comment]
@prachi00 Oh forgot to mention. This PR is kind of the indirect payment way for the articles we write since all the work is done on Medium 😛 
I guess you can regard this as a $$ issue. (most writing tasks are in that range too. $$$ would be way too much)

**Comment by prachi00** [comment]
pay 200 usd

**Comment by kkukelka** [comment]
> pay 200 usd

whoopsies, forgot my payout address. 😓  now it should work

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $200 @ 68.25 USD/KSM ~ 2.93 $KSM
🧗 [EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW](https://kusama.subscan.io/account/EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)
🔗 [0x31c9e81fab701b33214159361dd295412acd3443457dd328a16283644ee3ae86](https://kusama.subscan.io/extrinsic/0x31c9e81fab701b33214159361dd295412acd3443457dd328a16283644ee3ae86)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
