### PR TITLE
redesign: Carousel component

### LINKED ISSUE #3865: Redesign: Carousel
blocked by https://github.com/kodadot/nft-gallery/issues/3774

- [ ] redesign carousel to new design
- [ ] use feature flags behind it?

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #3865
- [x] to see new design pass `?redesign=true` in URL
- [x] style pagination
- [x] style arrow
- [x] use agnostic slider https://keen-slider.io/ (looks cool)

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by prachi00** [comment]
@preschian how do we see the new design?
Screen Shot 2022-09-10 at 10 36 33 PM
I changed the url but I dont see the carousel

**Comment by preschian** [comment]
> @preschian how do we see the new design? 

I need to update the redesigned layout since this PR was updated with the main branch. in the meantime, you can check the carousel on the gallery item page such as https://deploy-preview-3889--koda-nuxt.netlify.app/rmrk/gallery/10938663-0488b1a94fd8d61738-SHIBITS-SHIBITS_OR_PHARAOH_NIKU_OR_KUSAMA_KINGS-0000000000000354?redesign=true

**Comment by preschian** [comment]
@prachi00 updated, should be able to see on the homepage https://deploy-preview-3889--koda-nuxt.netlify.app/?redesign=true

**Review by petersopko — APPROVED** [review]
this wfm :)

**Comment by petersopko** [comment]
nice, landing page incoming! 🚀

**Comment by yangwao** [comment]
Hey pinging @exezbcz if the button should be animated on the press?

from figma file
https://user-images.githubusercontent.com/5887929/189707645-4a8b19cd-bccd-4f8c-a612-93795ca997b8.mov

image

**Comment by preschian** [comment]
> Hey, pinging @exezbcz if the triangle button should be animated on the press? It seems Figma isn't, but some interaction would be nice.
> plus, I see the background shadow and hover state of the arrow are not there.

aahh, I missed this part. will open another PR for this issue here https://github.com/kodadot/nft-gallery/issues/3945

**Review by prachi00 — APPROVED** [review]

**Comment by prachi00** [comment]
Responsive is being done in another issue right?

**Comment by yangwao** [comment]
yas 
image

looking forward it to updates for the carousel then :)

**Comment by yangwao** [comment]
pay 100

**Pull request merged**
