### PR TITLE
Update ParaSpell to v5.5.0

### PR DESCRIPTION
**Pull request by dudo50**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [x] Feature
- [ ] Refactoring

(please remove design and QA checks below if not needed)

## Context

PR introduces hotfix to breaking change introduced by Parity in runtime 1.2.5. Should work out of the box now.  We also introduced Polkadot<>Kusama bridge in this version. If you find useful usecase for it within Kodadot let us know in Telegram. We also had to update peer dependencies (PJS packages, that did not have breaking change implemented yet).

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] Tested on main net

#### Optional

- [ ] I've tested it at </ahp/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

-

#### Community participation

- [x] [Are you at Koda Ecosystem Telegram?](https://t.me/koda_eco)

## Screenshot 📸

-

### CODE REVIEW

**Comment by vikiival** [comment]
Thank you @dudo50!

I need to update internal packages too 😅

**Comment by prury** [comment]
its the fee now being subtracted from the teleported amount or was it always the case?

**Comment by dudo50** [comment]
@prury  Could you explain a little more in detail what you meant? I don't understand what fee you mean. Is this regarded to ParaSpell XCM SDK or Kodadot? Thanks!

With kind regards,
Team ParaSpell

**Comment by prury** [comment]
> @prury Could you explain a little more in detail what you meant? I don't understand what fee you mean. Is this question regarded to ParaSpell XCM SDK or Kodadot? Thanks!
> 
> With kind regards, Team ParaSpell



> @prury Could you explain a little more in detail what you meant? I don't understand what fee you mean. Is this question regarded to ParaSpell XCM SDK or Kodadot? Thanks!
> 
> With kind regards, Team ParaSpell

nevermind dudo, i made some tests and found what i was looking for

**Review by Jarsen136 — APPROVED** [review]

**Comment by dudo50** [comment]
@vikiival , done

**Pull request merged**
