### PR TITLE
🤖 update @polkadot extension

### PR DESCRIPTION
**Pull request by roiLeo**
This will make building a bit longer than before.
I need polkadot updates to work on #2427 

### What's new?

- [x] PR related with: 
- #2356 
- #2357 
- #2367 
- #2393
- #2427 

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

**EDIT**
New error?
Capture d’écran 2022-02-24 à 3 28 43 PM

### CODE REVIEW

**Comment by yangwao** [comment]
So it's work's to be ready to merge?

**Comment by roiLeo** [comment]
> So it's work's to be ready to merge?

It look like it work but I need to investigate the errors I have in console

**Comment by yangwao** [comment]
So let's merge it once it's to be good :)

**Comment by roiLeo** [comment]
This console error might come from @kodadot1/sub-api package, @vikiival do you have any idea why?

**Comment by yangwao** [comment]
> This console error might come from @kodadot1/sub-api package, @vikiival do you have any idea why?

My bet it's does need to bump deps there?

**Comment by vikiival** [comment]
Hey @roiLeo you have to also update a sub-api to the latest version. (Bump polkadot-api version). If you can please make a pr to the kodadot/packages

**Comment by yangwao** [comment]
Merged https://github.com/kodadot/packages/pull/8 but I guess it does need public new packages?

**Comment by roiLeo** [comment]
> Merged [kodadot/packages#8](https://github.com/kodadot/packages/pull/8) but I guess it does need public new packages?

Well, it doesn't look like we need to publish a new version (maybe we should increment version to rc.3) as I have no more console errors. I had to add more polkadot packages to transpile option to fix new errors.

**Pull request merged**
