### PR TITLE
#7507 Full screen button

### LINKED ISSUE #7507: Full screen button
image
https://canary.kodadot.xyz/ahp/gallery/13-1003

- the image should fit on the page
- also, please make the preview bg full height minus navbar
image

- the gaps there should not be there 
- would also be nice if the go back button would not cover the img

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #7507
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)

## Screenshot 📸

- [x] My fix has changed UI
Screen Shot 2023-10-04 at 9 59 04 PM

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
I wanted to compare agains some popular marketplace:

<details>
  <summary>Rarible</summary>
  
Capture d’écran 2023-10-05 à 5 29 43 PM

</details>


<details>
  <summary>Opensea</summary>
  
Screenshot 2023-10-05 at 17-29-11 Groupie #2603 - PEACEFUL GROUPIES OpenSea

</details>

<details>
  <summary>Kodadot (preview)</summary>
  
Screenshot 2023-10-05 at 17-30-21 Solar Flare One Stop Shop for Polkadot NFTs

</details>

it's disturbing from UX aspect, user need to scroll down to see full picture on large screen.

Can we have another option please? ping @exezbcz

**Comment by exezbcz** [comment]
thanks @roiLeo 

> the image should fit on the page

- this was actually meant as no-scrolling, my bad for the description

**Comment by prachi00** [comment]
> thanks @roiLeo
> 
> > the image should fit on the page
> 
> * this was actually meant as no-scrolling, my bad for the description

@exezbcz can you see now

**Review by roiLeo — COMMENTED** [review]
can't we display it over the navbar?

Capture d’écran 2023-10-11 à 8 36 46 AM

**Comment by prachi00** [comment]
uh which branch should this be pointed to then? @roiLeo @yangwao

**Comment by roiLeo** [comment]
Main

**Pull request closed without merging**
