### PR TITLE
Adjust renovate with minor/patch only

### LINKED ISSUE #2798: Renovate has stopped bumping dependencies?
I recall every 2-3 days we had a bump from renovating to bump new deps or package updates to running the most recent code.
The last merge is 13 days ago from renovate.

Since this commit https://github.com/kodadot/nft-gallery/commit/e01c64b268890ce379758a9ab3a2d91b9fadd712 which **was 12 days ago,** we closed open Node.js upgrade but nothing seen so far. 

Maybe @preschian can elaborate 🤔

image

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #2798  

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged the recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by preschian** [comment]
tested on forked repository:
- Dependency Dashboard: https://github.com/preschian/nft-gallery/issues/7
- will bump minor and patch packages:
	- https://github.com/preschian/nft-gallery/pull/35
	- https://github.com/preschian/nft-gallery/pull/27

**Comment by kkukelka** [comment]
so "matchDepTypes": ["dependencies", "devDependencies"] did the trick?

**Review by kkukelka — APPROVED** [review]
lgtm

**Comment by kkukelka** [comment]
pay 100

**Comment by preschian** [comment]
@kkukelka and need define the major also
```
{
  "matchUpdateTypes": ["major"],
  "enabled": false
}
```

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 173.9 USD/KSM ~ 0.575 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0xa27aa2937e1e5ac25c03293172f7e49123f95b9ca0d80acdbb9386bf9579eb03](https://kusama.subscan.io/extrinsic/0xa27aa2937e1e5ac25c03293172f7e49123f95b9ca0d80acdbb9386bf9579eb03)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by kkukelka** [comment]
> @kkukelka and need define the major also
> 
> ```
> {
>   "matchUpdateTypes": ["major"],
>   "enabled": false
> }
> ```

sweet :)
i squashed you PR btw so we dont pollute history. hope you dont mind

**Comment by preschian** [comment]
@kkukelka it's oke 👍 tbh, I prefer squashed instead of normal merge

**Comment by yangwao** [comment]
But this would be opening two separate PRs?

**Comment by preschian** [comment]
@yangwao yaps, to unify them remove this config `"separateMinorPatch": true,`. I separate them because the minor failed in the build stages

**Pull request merged**
