### PR TITLE
Profile-fix-visuals

### LINKED ISSUE #10145: Profile redesign - visual things
# Profile creation
- ref: https://github.com/kodadot/nft-gallery/pull/10114

Outstanding job @daiagi, thank you!

some visual things 

# Entry modal
image

## img 
lets probably use png, as it will have a bit better quality because of the SVG export thing in figma
image

## heading
image
"new" thing
image
image

## Paragraph
- text align center 
image
- highlighting of certain text is missing 

# Import or start fresh
image
 
image
should have more white space 

- remove the drop shadow from the buttons
- use our disabled button for farcaster disabled button - turn it all grey 
image
- "or" grey 

# Input modal
image
- should be 20px bold

## Finish customization button
image
- button should have no drop shadow
- should be our large button as in confirm modals 
image

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs Design check

- @exezbcz please review

## Context

- [x] Closes #10145

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)

### CODE REVIEW

**Review by Jarsen136 — APPROVED** [review]

**Review by preschian — APPROVED** [review]

**Comment by exezbcz** [comment]
image
 - center align please 


image


image

capital bold please

**Comment by daiagi** [comment]
> center align please
> capital bold please


@exezbcz  Done

**Comment by prury** [comment]
mobile buttons too close: 

image

**Comment by prury** [comment]
title needs some centering on mobile: 

image

**Comment by daiagi** [comment]
thx @prury 

done

**Comment by daiagi** [comment]
@prury 

i'm merging this

@exezbcz 

plz open new issue if any visual imperfections remain 

Thank you

**Pull request merged**
