### PR TITLE
feat: issue_4022

### LINKED ISSUE #4022: Price related features on Moonriver
Same as with
- https://github.com/kodadot/nft-gallery/issues/4021

~Since we don't have indexed the price of the NFTs, let's disable the features which are currently not operating:~

~1. sorting options related to price~
~2. price input~
~3. buy now button (both gallery and collections)~

image
image
image

### PR DESCRIPTION
**Pull request by zhengow**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR related #4022 
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </movr/explore/?tab=COLLECTION&page=1>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image
image

### CODE REVIEW

**Review by kkukelka — CHANGES_REQUESTED** [review]
since most of these components extend `PrefixMixin` already i would suggest making a new computed property in the mixin itself, something like
```
get isMoonriver(): boolean {
 return this.urlPrefix === 'movr'
}
```

and access it directly in every component without Props

**Comment by zhengow** [comment]
> since most of these components extend `PrefixMixin` already i would suggest making a new computed property in the mixin itself, something like
> 
> ```
> get isMoonriver(): boolean {
>  return this.urlPrefix === 'movr'
> }
> ```
> 
> and access it directly in every component without Props

done

**Review by kkukelka — APPROVED** [review]
sweet, gtg 🏆

**Review by petersopko — APPROVED** [review]
wfm

**Comment by petersopko** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 43.38 USD/KSM ~ 1.153 $KSM
🧗 [EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws](https://kusama.subscan.io/account/EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)
🔗 [0x2c4aa5186fdfc121ded60bc9cf66e9cf1158fb695c4e93c0a5f52f3afb58e874](https://kusama.subscan.io/extrinsic/0x2c4aa5186fdfc121ded60bc9cf66e9cf1158fb695c4e93c0a5f52f3afb58e874)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
