### PR TITLE
hotfix: incorrect url prefix on gallery item page

### LINKED ISSUE #4733: Error handling on cloudflare images
Do we handle errors properly? 

@JustLuuuu has this issue and no errors, weird?

telegram-cloud-photo-size-4-5925008226825386562-y

telegram-cloud-photo-size-4-5925008226825386565-y

telegram-cloud-photo-size-4-5925008226825386567-y

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4733
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by Jarsen136** [comment]
How to reproduce this bug:
1. open https://beta.kodadot.xyz/rmrk
2. click any gallery item in another chain (bsx /snek..)
then you could see the empty page
image

**Comment by Jarsen136** [comment]
> just checked the browser console from local, I got this error message from `'gallery/getGalleryItem'`
> 
> need to change the filename also from `_id.vue` to `_id/index.vue`
> 
> vue 3 way maybe?
> 
> ```
> <script lang="ts" setup>
> import GalleryItem from '@/components/gallery/GalleryItem.vue'
> 
> const { $store } = useNuxtApp()
> const { urlPrefix } = usePrefix()
> const route = useRoute()
> const router = useRouter()
> 
> onBeforeMount(() => {
>   const prefix = route.params.prefix
> 
>   if (urlPrefix.value !== prefix) {
>     $store.dispatch('setUrlPrefix', prefix)
>     router.go(0)
>   }
> })
> </script>
> ```

Thanks, I have modified them.

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 35.54 USD/KSM ~ 1.407 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xa5c28d45dd616d00a27fb5058323393c4105c3aa4015cec31919fbeb0e9ab608](https://kusama.subscan.io/extrinsic/0xa5c28d45dd616d00a27fb5058323393c4105c3aa4015cec31919fbeb0e9ab608)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
pay 50

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 35.07 USD/KSM ~ 1.426 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xcebe9def9f432e6ab8aaacfb5486b7e93b8d685159d86431c5f149cf67d17867](https://kusama.subscan.io/extrinsic/0xcebe9def9f432e6ab8aaacfb5486b7e93b8d685159d86431c5f149cf67d17867)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
