### PR TITLE
chore: update subapi package without warnings 📦 

### LINKED ISSUE #4055: update @kodadot1/sub-api package
Update `@kodadot1/sub-api` to version `0.1.1-alpha.3`

after installing new sub-api package, it throws multiple @polkadot/ errors in console:
```
@polkadot/** has multiple versions, ensure that there is only one installed.
```

This could fix #3966 
Don't forget to reintroduce test from #4002

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #4055 and #3966
- [ ] Requires deployment <rubick/magick_issue>
- [x] this ensures that only a single version of a dependency package is installed throughout the workspace
due to **pnpm's inability to resolve this correctly in every case**, we have to manually do an override for `@polkadot/utils`
you can read more about the issue here
https://github.com/pnpm/pnpm/issues/2713
https://github.com/pnpm/pnpm/issues/1221
Screenshot 2022-10-01 at 17 26 59

this also **fixed transaction fees at simple mint**
Screenshot 2022-10-01 at 17 17 15

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by petersopko** [comment]
built and tested without problem 👍🏻

**Review by petersopko — APPROVED** [review]
wfm

**Review by roiLeo — APPROVED** [review]
✅ Niiiiiice! did you spend more time than expected on this task?

**Comment by kkukelka** [comment]
> ✅ Niiiiiice! did you spend more time than expected on this task?

debugging the pnpm problem was quite a hassle... 😓 (going through all the dependency trees and stuff like that)

**Comment by kkukelka** [comment]
> as far as I can tell this is gtg, please let's just resolve conflicts (sorry, merged some packages updates prematurely) @kkukelka 🙏🏻

done

**Comment by roiLeo** [comment]
I'd be in favor of increasing the bounty on this PR maybe add some bonus for the time spent

**Comment by petersopko** [comment]
pay 125 usd

**Comment by petersopko** [comment]
> pay 125 usd

@yangwao looks like hit or miss with the payouts for the past couple of days, could you check when you find time?

**Pull request merged**
