### PR TITLE
fix: spotlight navbar misalignment

### LINKED ISSUE #2386: Can we have mobile spotlight done right 🥺
Seems while on mobile it's way off on Spotlight

image

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

Screenshot 2022-02-18 at 12 38 40

### What's new?

- [x] PR closes #2386
- [x] remove append-to-body attribute since it introduces some weird max-width css properties to column header

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by yangwao** [comment]
oh look who is back and loaded ! 😍 
let me wait to build finish

**Comment by kkukelka** [comment]
> oh look who is back and loaded ! 😍 let me wait to build finish
> 
> oh we haven't doing scoped CSS 🥲

armed and ready 😺 

the deepsource issue can be ignored i guess? we never document SFC classes

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 151.33 USD/KSM ~ 0.661 $KSM
🧗 [EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW](https://kusama.subscan.io/account/EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)
🔗 [0xeff1210d8429c83e0724b2e847f3976069167eaf89e07ef3c921c5ca85ae969f](https://kusama.subscan.io/extrinsic/0xeff1210d8429c83e0724b2e847f3976069167eaf89e07ef3c921c5ca85ae969f)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
