### PR TITLE
feat: More from the same collection

### LINKED ISSUE #3720: More from this collection is missing?
We had a side-scrolling feed on the gallery item detail showing other NFTs from the same collection in the past, and it seems, it's gone now. 
Can we have it back, please? :D 

Maybe the query needs to be remade to use subsquid? As we removed SubQuery recently maybe it was removed by that?

Bring it back, please for 
- RMRK
- BSX 

Query should be somewhere in code 👀

image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [x] Feature

### What's new?

- [x] PR closes #3720

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

RMRK: 
image

BSX: 
image

### CODE REVIEW

**Comment by yangwao** [comment]
https://deploy-preview-3724--koda-nuxt.netlify.app/bsx/collection/2526524581?page=1

I see only 3 of them from this collection 🤔

image

image


https://deploy-preview-3724--koda-nuxt.netlify.app/bsx/collection/1739922977

It seems nothing from that collection 👀
image

https://deploy-preview-3724--koda-nuxt.netlify.app/bsx/gallery/983246251-12
there should be 13 items https://deploy-preview-3724--koda-nuxt.netlify.app/bsx/collection/983246251

image

**Comment by Jarsen136** [comment]
> https://deploy-preview-3724--koda-nuxt.netlify.app/bsx/collection/2526524581?page=1
> 
> I see only 3 of them from this collection 🤔

There's a limit that will hide nfts that have a price of 0.

I removed this limitation. How about now?

**Comment by yangwao** [comment]
Hmm for bsx make sense because price doesn't need to be set and users can make offer

That's ones with 0 BSX is I guess some issue on our side and glitched data from previous broken stuff 😅😇

Lgtm then for me

**Comment by yangwao** [comment]
pay 100

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 57.91 USD/KSM ~ 1.727 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x2001847eb6d3794e9116c6af9201d49649c85d681c375839bbc764caa4843772](https://kusama.subscan.io/extrinsic/0x2001847eb6d3794e9116c6af9201d49649c85d681c375839bbc764caa4843772)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
