### PR TITLE
🔧 asset page & NeoTable

### PR DESCRIPTION
**Pull request by roiLeo**
No Darkmode yet
`NeoTable` & `NeoTableColumn` integrated in libs/ui

## PR Type

- [x] Bugfix
- [x] Feature
- [x] Refactoring

## Context

- [x] Related with #5852 (`NeoTable`)
- [x] fix old button

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

## Screenshot 📸
Screenshot 2023-05-26 at 11-47-35 KodaDot - NFT Market Explorer

Screenshot 2023-05-26 at 11-49-27 KodaDot - NFT Market Explorer

### <samp>🤖 Generated by Copilot at 86f8be6</samp>

The pull request migrates the `AssetTable.vue` component from Buefy to Oruga UI, using custom `NeoTable` and `NeoTableColumn` components from the `@kodadot/ui` library. These components are created and exported in the `@kodadot/ui` library as part of a UI library migration for the project.

### <samp>🤖 Generated by Copilot at 86f8be6</samp>

> _We're breaking free from Buefy's chains_
> _We're building our own `NeoTable` reign_
> _We're using Oruga UI to unleash our power_
> _We're migrating our UI library in this dark hour_

### CODE REVIEW

**Comment by yangwao** [comment]
Related
- #5759

**Review by vikiival — APPROVED** [review]

**Comment by prury** [comment]
White mode: 
- Buttons working properly
- Hover effect works properly
- mobile works fine

this text should be normal font weight: 
image

@roiLeo since you said no darkmote yet, will it be done on this PR or in another one?

**Comment by vikiival** [comment]
Сс @roiLeo ?

**Comment by roiLeo** [comment]
Do we have basic table design somewhere on figma?

**Comment by prury** [comment]
> Do we have basic table design somewhere on figma?

found it on the Assets part:
image

**Review by daiagi — APPROVED** [review]

**Comment by roiLeo** [comment]
Updated design
Screenshot 2023-05-30 at 09-32-58 KodaDot - NFT Market Explorer

**Comment by roiLeo** [comment]
Darkmode done, I'm merging this one let me know if you want to add some changes
Screenshot 2023-05-30 at 11-00-56 KodaDot - NFT Market Explorer

**Comment by prury** [comment]
> 



> This is already present on beta Screenshot 2023-05-30 at 15-08-51 KodaDot - NFT Market Explorer
> 
> I didn't touched mobile table design (yet?)

they are indeed, i was just thinking that since we don't have this specific page on Figma, it should look similar to light mode or with what you did for the desktop view (almost invisible thin lines). Sorry to bother, another pr another day then?

**Comment by roiLeo** [comment]
> they are indeed, i was just thinking that since we don't have this specific page on Figma, it should look similar to light mode or with what you did for the desktop view (almost invisible thin lines). Sorry to bother, another pr another day then?

Yup! in any case this page will be taken to disappear (by #4119)

**Pull request merged**
