### PR TITLE
remove unlockable collection banner border bottom

### LINKED ISSUE #7836: gap between the timer and cover img
small 1px gap 

image

### PR DESCRIPTION
**Pull request by newraina**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #7836
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer?target=1CAv6Zq3yVxL3eKhC94GWTWVwp1w4jZbqeZ6wXx1rPAhrce&usdamount=0&donation=true)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

CleanShot 2023-10-27-1d6uhbrX@2x

### <samp>🤖 Generated by Copilot at eca732c</samp>

Removed border style from `UnlockableCollectionBanner` component to fix visual bug. Moved border logic to parent component.

### <samp>🤖 Generated by Copilot at eca732c</samp>

> _`border-bottom` gone_
> _Fixes visual bug in `Banner`_
> _Winter of overlap_

### CODE REVIEW

**Comment by exezbcz** [comment]
image
- please have a look at figma file: https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=394%3A6126&mode=design&t=7tMJcPShgd5S2aia-1

## Dark mode 
image
- no grey please
- the banner should be directly on the cover img

same for white mode, the top stroke should not be there, or it should be in the color of the banner

**Comment by newraina** [comment]
@exezbcz updated, please check again :)

CleanShot 2023-10-29-fs3uYUw5@2x

**Comment by exezbcz** [comment]
@newraina yes, thank you 😍

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 4.21 USD/DOT ~ 7.126 $DOT
🧗 [1CAv6Zq3yVxL3eKhC94GWTWVwp1w4jZbqeZ6wXx1rPAhrce](https://polkadot.subscan.io/account/1CAv6Zq3yVxL3eKhC94GWTWVwp1w4jZbqeZ6wXx1rPAhrce)
🔗 [0xd6c631be634de732f64c64d31d907531150a6fd19b58660173d330d1143dcc1b](https://polkadot.subscan.io/extrinsic/0xd6c631be634de732f64c64d31d907531150a6fd19b58660173d330d1143dcc1b)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
