### PR TITLE
⬆️ Nuxt 3

### LINKED ISSUE #5611: Update `libs/ui` packages
- Check out official repo example [nuxt3](https://github.com/histoire-dev/histoire/tree/main/examples/nuxt3) or [vue3](https://github.com/histoire-dev/histoire/tree/main/examples/vue3)
- add `@oruga-ui/oruga-next`
- check components

### PR DESCRIPTION
**Pull request by roiLeo**
- ref #7034 
- close #5611 

we-did-it-stan-marsh

### CODE REVIEW

**Comment by preschian** [comment]
SoExcited~GIF

**Comment by roiLeo** [comment]
lemme fix reviewdog first

**Review by preschian — APPROVED** [review]
WeDidItKarenCheeGIF

**Comment by prury** [comment]
WAIT, look what happens when i click on create -> collection: 

https://github.com/kodadot/nft-gallery/assets/36627808/e3197695-19ec-4b0e-be42-a099a2ea24cf

**Comment by yangwao** [comment]
image

**Comment by prury** [comment]
- found some minor white/dark mode and icon related bugs
- explore -> collection: images not loading
 
what's the best path? merging this one and continue to pursue #7375 ?

**Comment by roiLeo** [comment]
> * found some minor white/dark mode and icon related bugs
> 
>     * explore -> collection: images not loading
> 
> 
> what's the best path? merging this one and continue to pursue #7375 ?

Oops I might have made a change in #7586 and #7585 that is breaking the UI, let me check again

**Review by prury — APPROVED** [review]

**Pull request merged**
