### PR TITLE
disable polkadot teleport

### LINKED ISSUE #9596: Disable teleport and autoteleport on Polkadot <-> Polkadot Assethub
The same bug that happened on Kusama in the last month(XCM related) is also happening on Polkadot where users lose funds when trying to teleport an amount near ED. 

let's disable teleport and autoteleport until there's a fix from parity

### PR DESCRIPTION
**Pull request by iMac7**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #9596 
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/ahp/transfer?target=14dLrAvjDw7cFLaxM7VWR6YtHd7bGZY2QpzXDhAJJ4yv6oGw&usdamount=undefined)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by prury** [comment]
i know that this was the same solution used in a previous PR to disable teleport from Kusama/Assethub, but it doesn't really disables auto-teleport

**Comment by prury** [comment]
lets see if I'm following, here's my balance on testing account: 3,6 DOT
so, the maximum amount i could teleport from Polkadot should be: 3,6 - 2 * 1 = 1,6 DOT, correct? 

but when i try to buy + teleport an NFT above this value, it still let me: 

image

am i correct?

**Comment by exezbcz** [comment]
any updates?

**Comment by prury** [comment]
@iMac7 i'll close this one then, so another dev can pick it up

**Pull request closed without merging**
