### PR TITLE
og_url_fix

### LINKED ISSUE #2086: open graph protocol url
### What happened?

- og url is referencing to localhost instead of https://kodadot.xyz  
- as a result, for example, when sharing a link on twitter, result is this:  
image

### Please reproduce in steps

check elements and metatags in head

### Expected Behavior

i'd expect it to be pointing to right image source which shows this 
image
from this url:
https://kodadot.xyz/kodadot_card_root.png

### What browsers are you seeing the problem on?

Chrome

### Are you logged in?

_No response_

### At which address did you encounter bug?

nft.kodadot.xyz / kodadot.xyz

### Screenshots

image

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by petersopko**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Do a quick check before the merge.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2086
- [x] minor og:url fix

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [ ] I found edge cases

### Had issue bounty label ?

- [ ] Fill up your KSM address: no label, minor fix

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI, a screenshot is best to understand changes for others

### CODE REVIEW

**Review by kkukelka — COMMENTED** [review]
why would this be necessary, shouldn't BASE_URL be set in Netlify variables? ( @yangwao  maybe )

**Comment by petersopko** [comment]
> why would this be necessary, shouldn't BASE_URL be set in Netlify variables? ( @yangwao maybe )

I know embarrassingly little about deploying to Netlify, so advice/guidance here is greatly appreciated  :)
I was trying to fix this  
image

**Comment by kkukelka** [comment]
> > why would this be necessary, shouldn't BASE_URL be set in Netlify variables? ( @yangwao maybe )
> 
> I know embarrassingly little about deploying to Netlify, so advice/guidance here is greatly appreciated :) I was trying to fix this image

Aha, I see. 😸 
Actually, what you see is working as intended, as you are trying to share the deploy-preview of the kodadot website, therefore the BASE_URL is set to `https://deploy-review-whatevercomesnext...`.
If you would share a page of the production state (https://kodadot.xyz/) then the BASE_URL would be set to `https://kodadot.xyz/`.

changing `'http://localhost:9090'` like you just did doesn't actually fix the perceived problem, as it only serves as fallback if no env-variables are set in our deployment setup on netlify/cloudflare

The reason why we do `const baseUrl = process.env.BASE_URL || 'http://localhost:9090'` is that when still working in the local development environment, one usually doesn't have a BASE_URL set in the `.env` file and we then have `'http://localhost:9090'` as fallback to test static assets or whatever locally

**Comment by petersopko** [comment]
> > > why would this be necessary, shouldn't BASE_URL be set in Netlify variables? ( @yangwao maybe )
> > 
> > 
> > I know embarrassingly little about deploying to Netlify, so advice/guidance here is greatly appreciated :) I was trying to fix this image
> 
> Aha, I see. 😸 Actually, what you see is working as intended, as you are trying to share the deploy-preview of the kodadot website, therefore the BASE_URL is set to `https://deploy-review-whatevercomesnext...`. If you would share a page of the production state (https://kodadot.xyz/) then the BASE_URL would be set to `https://kodadot.xyz/`.
> 
> changing `'http://localhost:9090'` like you just did doesn't actually fix the perceived problem, as it only serves as fallback if no env-variables are set in our deployment setup on netlify/cloudflare
> 
> The reason why we do `const baseUrl = process.env.BASE_URL || 'http://localhost:9090'` is that when still working in the local development environment, one usually doesn't have a BASE_URL set in the `.env` file and we then have `'http://localhost:9090'` as fallback to test static assets or whatever locally
> 
> hope this adds some sense of clarity to your question 👍

thank you, definitely adds clarity, I saw it's a fallback, I just figured it was something forgotten, since the 'http://localhost:9090' appears in metatags and since my local app running as instructed by starting guide here isn't even building at 'http://localhost:9090'. But after your comment, it obviously makes more sense to figure out why is it falling back to it in the first place (i.e. fix the BASE_URL / Netlify variables I guess).

**Comment by kkukelka** [comment]
> thank you, definitely adds clarity, I saw it's a fallback, I just figured it was something forgotten, since the 'http://localhost:9090' appears in metatags and since my local app running as instructed by starting guide here isn't even building at 'http://localhost:9090'. But after your comment, it obviously makes more sense to figure out why is it falling back to it in the first place (i.e. fix the BASE_URL / Netlify variables I guess).

ohhh i just now actually looked at the issue you opened. yep, definitely seems like we have forgotten to set this variable somewhere in the deployment pipeline!

**Comment by yangwao** [comment]
This sounds something like lost in translations when we're migrating from Netlify to Cloudflare.
Actually, we went for an uphill decision for short-term pain and long-term gain. Keeping Netlify for deploy previews (BASE_URL) is injected, you can see it in env somewhere and parallel we've decided to drop as much possible ENV to have set for entry developers and for particular deployments. 

So yeah can set BASE_URL to https://kodadot.xyz and at the earliest `main` -> `hyper-jpeg` merge it will be deployed.

As @kkukelka stated, it's important to have localhost as a fallback to have it working while developing locally and the best environment agnostic solution wins here.

Sending bounty to @petersopko for raising awareness on this!

**Comment by petersopko** [comment]
> As @kkukelka stated, it's important to have localhost as a fallback to have it working while developing locally and the best environment agnostic solution wins here.
> 
> Sending bounty to @petersopko for raising awareness on this!

I understand now. Thank you.

**Pull request closed without merging**
