### PR TITLE
fix: set prefix parameter to /rmrk/mint router

### LINKED ISSUE #5247: tests failing over and over
```

  ✓ should render correct twitter opengraph on item page (12223ms)

  1 passing (13s)



  simple mint in rmrk
    (Attempt 1 of 4) should able to simple mint
    (Attempt 2 of 4) should able to simple mint
    (Attempt 3 of 4) should able to simple mint
    1) should able to simple mint


  0 passing (2m)
  1 failing

  1) simple mint in rmrk
       should able to simple mint:

      Timed out retrying after 10000ms
      + expected - actual

      -'\n    0\n    BSX\n  '
      +'\n    0\n    KSM\n  '
      
      at Context.eval (webpack:///./cypress/e2e/rmrk-simple-mint.cy.ts:16:35)
```

### PR DESCRIPTION
**Pull request by zj9495**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5247
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=GnewdcaiomNSHXDa67te4WBSvXtpyv2AfVEKNfQsSbCQaEV)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

### CODE REVIEW

**Review by roiLeo — CHANGES_REQUESTED** [review]
RMRK should indeed have text "KSM"

**Review by vikiival — CHANGES_REQUESTED** [review]
The test is correct imo there is something wrong imo in simple mint or so

**Comment by zj9495** [comment]
> The test is correct imo there is something wrong imo in simple mint or so
https://github.com/kodadot/nft-gallery/pull/4869/files#diff-54c1adb4f9778fc990b6a8b75f23df009e785c09226ab6659af40d4346368b77R2
I found that we are using router.params instead of regular expressions to obtain the urlPrefix, so /rmrk/mint cannot obtain the correct urlPrefix, so I think I should configure the prefix parameter for the /rmrk/mint route, is this correct? I will try it later,

**Comment by zj9495** [comment]
> The test is correct imo there is something wrong imo in simple mint or so

https://github.com/kodadot/nft-gallery/pull/4869/files#diff-54c1adb4f9778fc990b6a8b75f23df009e785c09226ab6659af40d4346368b77L1
I found that we are using `router.params` instead of regular expressions to obtain the urlPrefix, so `/rmrk/mint` cannot obtain the correct urlPrefix, so I think I should configure the `prefix` parameter for the /rmrk/mint route, is this correct? 
I will try it later

**Comment by vikiival** [comment]
> for the /rmrk/mint route, is this correct? I will try it later

Yup! exactly nice one.

@zj9495 I will close this issue since we try to avoid force pushes into codebase (chceck CONTRIBUTING.MD)

Screenshot 2023-03-14 at 11 43 08

Please create a new PR and I am happy to merge ❤️

**Comment by zj9495** [comment]
> > for the /rmrk/mint route, is this correct? I will try it later
> 
> Yup! exactly nice one.
> 
> @zj9495 I will close this issue since we try to avoid force pushes into codebase (chceck CONTRIBUTING.MD)
> 
> Screenshot 2023-03-14 at 11 43 08
> 
> Please create a new PR and I am happy to merge ❤️

make sense, i raised a new PR, plz review again

**Pull request closed without merging**
