### PR TITLE
feature: show original content if the user clicks the preview button

### LINKED ISSUE #6638: Show original content
Hi guys, currently, we show optimised images on the gallery detail page. **The downside** is that gif content will be transformed into a static image. For example, this page https://deploy-preview-6599--koda-canary.netlify.app/stmn/gallery/u-117-382

I'm using https://wsrv.nl/ to resize images on cf-workers. For now, that page still does not support resizing big-resolution gif to smaller-size gif.

## Reason

To avoid loading "big" size images to the user. Because it will hurt performance and give them a bad experience on our website. Ref:
- https://github.com/kodadot/nft-gallery/issues/5202
- https://github.com/kodadot/workers/pull/54

For example comparison, **17.8kB** vs **2.2MB**
|  | screenshot |
|--------|--------|
| [kodadot](https://deploy-preview-6599--koda-canary.netlify.app/stmn/gallery/u-117-382) | image |
| [singular](https://singular.app/collectibles/statemine/2/2350) | image |

## Solution

1. In this [PR](https://github.com/kodadot/nft-gallery/pull/6599), I change the URL in the "Details" tab to a public IPFS gateway. So, if the user clicks the "Media" or "Animated Media" link, they will see the original content

image

2. Second solution, what if we show original content if the user clicks the preview button?

image

wdyt? cc @kodadot/internal-dev

### PR DESCRIPTION
**Pull request by justskinny5**
## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #6638
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=129QwMHtmhf7qGF5EoMxVT7dosyb9SYZTkJTfQHYQ3kUQap4&usdamount=0&donation=true)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
https://github.com/kodadot/nft-gallery/assets/17610879/a2a2a15e-7c47-4e54-ac4f-26ec71b4de5f

### <samp>🤖 Generated by Copilot at 0558524</samp>

Improved gallery preview images by using IPFS original content URLs. Modified `GalleryItem.vue` to use the `toOriginalContentUrl` utility function.

### <samp>🤖 Generated by Copilot at 0558524</samp>

> _`toOriginalContentUrl`_
> _transforms IPFS base links_
> _gallery shines in spring_

### CODE REVIEW

**Review by stephenjason89 — APPROVED** [review]
looks good

**Review by Jarsen136 — APPROVED** [review]

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 4.54 USD/DOT ~ 6.608 $DOT
🧗 [129QwMHtmhf7qGF5EoMxVT7dosyb9SYZTkJTfQHYQ3kUQap4](https://polkadot.subscan.io/account/129QwMHtmhf7qGF5EoMxVT7dosyb9SYZTkJTfQHYQ3kUQap4)
🔗 [0x326715f453969fc4cbb5ee42a06389d2991663bbf7fe05ca208efd2bbae2f9d2](https://polkadot.subscan.io/extrinsic/0x326715f453969fc4cbb5ee42a06389d2991663bbf7fe05ca208efd2bbae2f9d2)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by justskinny5** [comment]
@yangwao Thanks for the payout! but the tx is failed🥲
CleanShot 2023-08-29 at 19 58 05@2x

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 4.58 USD/DOT ~ 6.55 $DOT
🧗 [129QwMHtmhf7qGF5EoMxVT7dosyb9SYZTkJTfQHYQ3kUQap4](https://polkadot.subscan.io/account/129QwMHtmhf7qGF5EoMxVT7dosyb9SYZTkJTfQHYQ3kUQap4)
🔗 [0x795308664eb1425faf2b7c08f532414ea1da3166bd1bebc6734c821a017ed7ca](https://polkadot.subscan.io/extrinsic/0x795308664eb1425faf2b7c08f532414ea1da3166bd1bebc6734c821a017ed7ca)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
