### PR TITLE
fix: More Space on mobile drop page

### LINKED ISSUE #9947: More Space on mobile drop page
image

Let's add more space between the view collection and the drop card 

Something like 32px or 24 should work

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs Design check

- @exezbcz please review

## Context

- [x] Closes #9947

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by exezbcz** [comment]
Yes! Thanks

**Comment by prury** [comment]
pay 5 usd

**Comment by prury** [comment]
pay 5 usd

**Comment by prury** [comment]
pay 5 usd

**Comment by prury** [comment]
pay 10 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $10 @ 8.46 USD/DOT ~ 1.182 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x4c1e65c13015ea97c5be673322a8953c4cdf54e0c1163f13f49ae38499bc636f](https://polkadot.subscan.io/extrinsic/0x4c1e65c13015ea97c5be673322a8953c4cdf54e0c1163f13f49ae38499bc636f)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
