### PR TITLE
Remove-nuxt-property-decorator-#2

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Related with #4750

## Pages in this PR
1. massmint
2. massmint/onboarding
3. bsx/assets
4. bsx/claim
5. bsx/incomingOffers
6. bsx/offers
7. bsx/stats
8. bsx/waifu
9. rmrk/mint

## desired outcome
no change in look and/or behavior

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)

## Screenshot 📸

- [ ] My fix has changed UI

### <samp>🤖 Generated by Copilot at 9850182</samp>

Refactored several components in the `pages` directory to use default export and dynamic import syntax, and removed unused or unnecessary code. This improved the code consistency, readability, maintainability, and performance across the project.

### <samp>🤖 Generated by Copilot at 9850182</samp>

> _We're refactoring our components, me hearties, yo ho ho_
> _We're using default export and dynamic import, yo ho ho_
> _We're removing unused code and decorators, yo ho ho_
> _We're improving our performance and readability, yo ho ho_

### CODE REVIEW

**Review by Jarsen136 — APPROVED** [review]

**Review by roiLeo — APPROVED** [review]
✅ code lgtm

**Comment by vikiival** [comment]
bulk one

**Comment by vikiival** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 5.48 USD/DOT ~ 5.474 $DOT
🧗 [1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8](https://polkadot.subscan.io/account/1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)
🔗 [0xa3175c0243d27bed38a997df19a5f069e6e4db78d98af24a7b8443990a2ffc58](https://polkadot.subscan.io/extrinsic/0xa3175c0243d27bed38a997df19a5f069e6e4db78d98af24a7b8443990a2ffc58)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
