### PR TITLE
🐛 list button for unlisted owned items

### LINKED ISSUE #4818: List option missing when you are owner
design:
image
beta: 
image
list button should be primary button. 
change price should be visible only when the item is already listed.

### PR DESCRIPTION
**Pull request by petersopko**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4818
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [x] I've tested it at </bsx/collection>
- [x] I've tested PR on mobile
- [x] I've written unit tests 🧪
- [x] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
darkmode input text color
Screenshot 2023-01-25 at 08-56-28 The Afterlife KodaDot - NFT Market Explorer

**Review by roiLeo — APPROVED** [review]
Tested on `/snek/gallery/331660682-6`

✅ wfm


small note (that can be improved later):
- after LIST or CHANGE PRICE, slide-content is still open
Screenshot 2023-01-25 at 15-40-09 KodaDot - NFT Market Explorer

- related with #4804?
Screenshot 2023-01-25 at 15-35-00 KodaDot - NFT Market Explorer

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 33.58 USD/KSM ~ 0.893 $KSM
🧗 [FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y](https://kusama.subscan.io/account/FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y)
🔗 [0xb77b204ee1cee990a09cd4e91cb18145c09b7904d35295260646419df4888181](https://kusama.subscan.io/extrinsic/0xb77b204ee1cee990a09cd4e91cb18145c09b7904d35295260646419df4888181)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
