### PR TITLE
fix: collection description/info not refresh after search

### LINKED ISSUE #5516: Collection description and numbers doesn't update after search
Go to the 
- https://beta.kodadot.xyz/rmrk2/collection/3e6f301b0a0b1a0e4e-MRWH?page=1
- search in top bar redhead utopia
- notice that loads new pfp of collection and banner and items, but description stays same and items and owners &c for collection

https://user-images.githubusercontent.com/5887929/229832054-65b65d98-b3f0-469e-9d60-3816cd9b55ab.mov

h/t @JustLuuuu for reporting

same 
- #5487

### PR DESCRIPTION
**Pull request by floyd-li**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5516
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EZiu1PjV2j2JHKxY6mHnFwwCRCoV27uHKQSkKXATSh1srJT)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by yangwao** [comment]
@JustLuuuu it's fixed 🥹
https://deploy-preview-5518--koda-canary.netlify.app/

**Review by Jarsen136 — APPROVED** [review]
code lgtm

**Comment by yangwao** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 33.82 USD/KSM ~ 0.591 $KSM
🧗 [EZiu1PjV2j2JHKxY6mHnFwwCRCoV27uHKQSkKXATSh1srJT](https://kusama.subscan.io/account/EZiu1PjV2j2JHKxY6mHnFwwCRCoV27uHKQSkKXATSh1srJT)
🔗 [0x464a4899965d7c96df938dad11d1c6eee0b664e383d9b75209a0448e5a6cbc54](https://kusama.subscan.io/extrinsic/0x464a4899965d7c96df938dad11d1c6eee0b664e383d9b75209a0448e5a6cbc54)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
