### PR TITLE
fix(3197, 3220) - stuck chains

### LINKED ISSUE #3197: Sometimes I don't see collections under my account
Seems sometimes I don't see any collections at all under my account on basilisk, no errors in the console

image

### LINKED ISSUE #3220: Glitch on make offer in basilisk
Sometimes I can't make an offer 🤔

image

### PR DESCRIPTION
**Pull request by petersopko**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?
https://github.com/kodadot/nft-gallery/issues/3169
- [x] PR closes #3197, closes #3220
- [ ] Requires deployment <rubick/magick_issue>
- [ ] This bug was created by removal of plugin in https://github.com/kodadot/nft-gallery/issues/3169

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by vikiival** [comment]
Looks like this was caused by 
- #3173 

cc @zhengow

**Review by vikiival — APPROVED** [review]
LGTM 🚀

**Comment by zhengow** [comment]
> Looks like this was caused by
> 
> * [Try out different RPC endpoint when error occurs #3173](https://github.com/kodadot/nft-gallery/pull/3173)
> 
> cc @zhengow

I see how this bug create: dispatch method `setUrlPrefix` also call `setApiUrl` while I delete `myPlugin`.
Let me help to fix this bug.

**Comment by zhengow** [comment]
> Looks like this was caused by
> 
> * [Try out different RPC endpoint when error occurs #3173](https://github.com/kodadot/nft-gallery/pull/3173)
> 
> cc @zhengow

Plz review [kodadot/packages#27](https://github.com/kodadot/packages/pull/27).
When above PR is done, I need to change some code in `transfer.vue` and `SettingChooser.vue` to fix this bug.
😶‍🌫️

**Pull request merged**
