### PR TITLE
fix: Disable button when minted out even when not connected with wallet

### LINKED ISSUE #8899: Disable button when minted out even when not connected with wallet
> @prury could be, for another issue i guess 
> 
> 
> I am more interested in why the button is active tho :D 
> image
> 

When disconnected it stays active all the time, it only gets disabled once you connect your wallet

_Originally posted by @prury in https://github.com/kodadot/nft-gallery/issues/8896#issuecomment-1879738372_

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix

  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #8899

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

image

  ## Copilot Summary
  copilot:summary

  copilot:poem

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]

**Comment by exezbcz** [comment]
and after connecting, will there still be the "see you nft message" right 


works for me

**Comment by Jarsen136** [comment]
> and after connecting, will there still be the "see you nft message" right

No, it's not supported for now. 
related with https://github.com/kodadot/private-workers/issues/29

**Review by exezbcz — APPROVED** [review]

**Review by preschian — APPROVED** [review]

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 7.32 USD/DOT ~ 4.098 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0xbe1c4397997417db0c5326ba6135c68e4e66576556f0c6fa29c7bcab3b17a8be](https://polkadot.subscan.io/extrinsic/0xbe1c4397997417db0c5326ba6135c68e4e66576556f0c6fa29c7bcab3b17a8be)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
