### PR TITLE
feat: add append to body option to NeoModal

### LINKED ISSUE #7179: mass listing followup - modal background
image

- please apply the same style as other modals have. That means black color with low opacity overlay. It should cover the navbar as well.

### PR DESCRIPTION
**Pull request by floyd-li**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #7179  
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

图片
### <samp>🤖 Generated by Copilot at a5e58a2</samp>

This pull request improves the NeoModal component by using `teleport` to render it in the `body` element and by adding a z-index property to its style. These changes enhance the accessibility, performance, and visibility of the modal.

### <samp>🤖 Generated by Copilot at a5e58a2</samp>

> _Oh we're the coders of the `neo-modal` class_
> _We set the z-index high so it won't be surpassed_
> _We use the `teleport` to render it in the `body`_
> _And we give a prop to change it if you're feeling naughty_

### CODE REVIEW

**Comment by exezbcz** [comment]
does not work for me - listing multiple items and also single 
image

**Review by roiLeo — CHANGES_REQUESTED** [review]
Screenshot 2023-10-09 at 08-14-16 KodaDot - NFT Market Explorer

Big modal header now, check notificaiton, shopping cart, and wallet

**Comment by floyd-li** [comment]
> Big modal header now, check notificaiton, shopping cart, and wallet

got it. seems we used to add `padding` manually to avoid header.  is it better to set `append-to-body` to false by default? or remove the `padding` in these components? 🤔

图片

**Comment by roiLeo** [comment]
> got it. seems we used to add `padding` manually to avoid header. is it better to set `append-to-body` to false by default? or remove the `padding` in these components? 🤔

I would remove fixed padding in these components but things is that we don't have to hide what's behind (navbar profile)
so maybe `append-to-body` to false will fix this issue

**Comment by roiLeo** [comment]
> > Still weird on my side
> 
> my bad... now fixed
> 
> btw, does the deepscan got mistake? i did not change this file `utils/transactionExecutor.ts`

try to update your branch

**Comment by floyd-li** [comment]
> > btw, does the deepscan got mistake? i did not change this file `utils/transactionExecutor.ts`
> 
> try to update your branch

alright...deepscan goes and sonarcloud fails 😓

**Comment by exezbcz** [comment]
could you apply it to every modal please? as mentioned in the issue: 
image


>please apply the same style as other modals have. That means black color with low opacity overlay. It should cover the navbar as well.

**Comment by floyd-li** [comment]
> could you apply it to every modal please? as mentioned in the issue: image
> 
> > please apply the same style as other modals have. That means black color with low opacity overlay. It should cover the navbar as well.

sure

**Comment by floyd-li** [comment]
also, the style issue of `Connect Wallet` and `Notification` modal is not caused by the code add to the `NeoModal`, they do use the other component called `NeoModalExtend` that issue is caused by the `z-index: 999` added to its scss file. i just removed them. 

so i set `append-to-body` back to `true` by default. `NeoModal` and the `NeoModalExtend` both worked well

cc @roiLeo

**Review by roiLeo — APPROVED** [review]
✅ code lgtm

til [Teleport](https://vuejs.org/guide/built-ins/teleport.html#teleport)

**Comment by exezbcz** [comment]
image


hmmm, is this only on my side or?

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 3.8 USD/DOT ~ 7.895 $DOT
🧗 [13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A](https://polkadot.subscan.io/account/13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A)
🔗 [0xf948e8213c17048dbedebab4bd8644d79389a143ce114d00ec87855d85bf8ab9](https://polkadot.subscan.io/extrinsic/0xf948e8213c17048dbedebab4bd8644d79389a143ce114d00ec87855d85bf8ab9)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
