### PR TITLE
fix: disable movr & glmr on production env

### LINKED ISSUE #4019: Hide MoonRiver & Moonbeam (/glmr) route on production
Not sure what the current  status is on the implementation here, but we have both on production and beta link to select moonbeam which leads nowhere, so please let's hide it until we move this issue furthe:

image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #4019 
Hide MOVR & GLMR on kodadot.xyz .
On beta.kodadot.xyz and localhost MOVR & GLMR could be shown.

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by petersopko** [comment]
@Jarsen136 how does one test this? 😆 I've tried to checkout the thing locally and replace `kodadot.xyz` with `localhost:9090` but that didn't do the trick.

> I've posted a screenshot of demonstrated change in this PR

code lgtm but can you provide screenshot?

**Review by petersopko — COMMENTED** [review]
small stuff

**Comment by Jarsen136** [comment]
> @Jarsen136 how does one test this? 😆 I've tried to checkout the thing locally and replace `kodadot.xyz` with `localhost:9090` but that didn't do the trick.
> 

Hey, you could checkout the branch locally and replace `kodadot.xyz` with `localhost`, and then you will see it works.

> > I've posted a screenshot of demonstrated change in this PR
> 
> code lgtm but can you provide screenshot?

Yup, I will provide a screenshot later.

**Comment by petersopko** [comment]
> you could checkout the branch locally and replace kodadot.xyz with localhost, and then you will see it works

thanks, works now :)
image

**Review by petersopko — APPROVED** [review]
wfm

**Review by prachi00 — APPROVED** [review]

**Comment by yangwao** [comment]
pay 50

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 42.38 USD/KSM ~ 1.18 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x973c441c1800b12d37a6734d170d6c08dd1e19e743dac40fcac07c51fa29f578](https://kusama.subscan.io/extrinsic/0x973c441c1800b12d37a6734d170d6c08dd1e19e743dac40fcac07c51fa29f578)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
