### PR TITLE
[Blogpost] The Rise of Onchain NFTs: Shaping the Future of Digital Collectibles

### LINKED ISSUE #6498: [Blogpost] The Rise of Onchain NFTs: Shaping the Future of Digital Collectibles
Follow markdown formatting best; put it up as previously
- #6432 
thankyou!

date
---
11/11/2022 (when onchain NFTs started:)

# The Rise of Onchain NFTs: Shaping the Future of Digital Collectibles

image

From the realm of decentralization, a new breed of digital assets has emerged, known as onchain NFTs. These digital tokens, which are stored directly on the blockchain, are poised to revolutionize the way we deal with digital collectibles.

## Understanding the Basics of Non-Fungible Tokens (NFTs)

Non-Fungible Tokens (NFTs) have taken the digital world by storm, representing a new way of owning and trading digital assets. Unlike fungible tokens like Bitcoin or Ethereum, which are identical and interchangeable, NFTs are unique and distinguishable from one another. This uniqueness is what gives NFTs their value, similar to how a one-of-a-kind painting or a rare baseball card holds value.

## The Problem with Traditional NFTs

Traditional NFTs, while groundbreaking in their own right, have a significant vulnerability: their metadata and digital assets are typically stored off the blockchain. This off-chain data is usually stored on servers, cloud storage, or the InterPlanetary File System (IPFS), which presents potential issues.

For instance, if the server or cloud storage provider experiences downtime, the link to the NFT's digital asset could be broken. This means that the owner of the NFT may no longer be able to access or verify the digital asset associated with the NFT, rendering it virtually worthless.

## Enter Onchain NFTs: A Solution to the Problem

To address the shortcomings of traditional NFTs, a new breed of NFTs has emerged: onchain NFTs. As the name suggests, onchain NFTs store both the metadata and the digital asset directly on the blockchain. This means that as long as the blockchain exists, the NFT and its associated digital asset will be accessible, thereby eliminating the potential issue of a broken link.

## The Technical Components of Onchain NFTs

Onchain NFTs consist of two key components: the metadata and the smart contracts. The metadata is the core information associated with an NFT, such as its name, custom properties, and the digital asset itself. Meanwhile, the smart contracts are self-executing contracts with the terms of the agreement directly written into code. These contracts help facilitate the minting and exchange of the NFTs.

Because both the metadata and smart contracts of onchain NFTs are stored directly on the blockchain, they are truly decentralized and do not rely on any third-party service or server.

## The Benefits of Onchain NFTs

Onchain NFTs come with a host of benefits that make them an ideal solution for the digital collectibles market. For one, they are immutable. Since the metadata and digital asset are stored directly on the blockchain, they cannot be altered or deleted. This means that the authenticity and ownership of an onchain NFT can be verified at any time.

Moreover, onchain NFTs are highly durable. Unlike traditional NFTs, which rely on third-party services for storage, onchain NFTs exist as long as the blockchain exists. This ensures that the NFT and its associated digital asset are always accessible, regardless of external factors.

## The Challenges of Onchain NFTs

Despite their numerous benefits, onchain NFTs are not without their challenges. The primary obstacle is the cost associated with storing data directly on the blockchain. Given the average size of an NFT project, storing all the NFTs and their associated metadata on the blockchain can be prohibitively expensive.

For instance, when Cryptopunks, a popular NFT collection, moved to become fully onchain, it reportedly cost the developers a whopping 73 million in gas fees. While this cost may be justifiable for high-value NFTs, it is a significant barrier for smaller projects and individual creators.

## Notable Onchain NFT Projects

Despite the challenges, there are a number of notable projects that have embraced the onchain NFT model. Here are a few:

### Cryptopunks
 - Launched in 2017, Cryptopunks is a highly valued NFT collection that moved to be fully onchain in 2021.

### Nouns
 - An experimental collection that has grown into a successful public domain project with a thriving community and a well-developed DAO.

### OnChain Monkey
 - Claiming to be the first profile picture NFT collection to be generated on-chain in a single transaction, OnChain Monkey has made strides in reducing Ethereum gas fees.

## The Future of Onchain NFTs

Despite the high cost associated with onchain NFTs, their benefits are undeniable. For high-value NFTs, the cost is well worth the advantages of immutability, durability, and authenticity. As blockchain technology continues to evolve and become more efficient, the cost of onchain storage is likely to decrease, making onchain NFTs more accessible to a broader range of creators and collectors.

In conclusion, the rise of onchain NFTs represents a significant milestone in the evolution of digital collectibles. By storing all data directly on the blockchain, onchain NFTs provide a more secure and reliable solution for the digital collectibles market. While the high cost of onchain storage is currently a barrier, the future looks bright for onchain NFTs as blockchain technology continues to evolve and improve.

## Wrapping Up

In a nutshell, onchain NFTs represent the next frontier in the evolution of digital collectibles. While they come with their own set of challenges, their benefits are undeniable. By storing all data directly on the blockchain, onchain NFTs provide a level of security and reliability that is unparalleled in the digital collectibles market. As we move forward, it will be exciting to see how this new breed of NFTs shapes the future of digital assets.

### LINKED ISSUE #6509: Only one blog is shown on the `canary.kodadot.xyz/blog/`
### What happened?

The rest of the blogs are missing.
image

The bug should be introduced from this PR https://github.com/kodadot/nft-gallery/pull/6505

image

### Please reproduce in steps

canary.kodadot.xyz/blog/

### Expected Behavior

All blogs could be displayed correctly.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #6498
- [x] Closes #6509 
- [ ] Requires deployment <snek/rubick/worker>

/blog/shaping-the-future-of-digital-collectibles

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

### <samp>🤖 Generated by Copilot at 7a20599</samp>

This pull request adds a new blog post about onchain NFTs and improves the blog index page. The post introduces the concept and features of onchain NFTs, and showcases some examples of projects using them. The index page fixes the URL generation and adds some styling to the content list.

### <samp>🤖 Generated by Copilot at 7a20599</samp>

> _Sing, O Muse, of the skillful coder who devised_
> _A wondrous blog post on the onchain NFTs,_
> _The new-born digital collectibles that reside_
> _On the blockchain, storing both the form and the keys._

### CODE REVIEW

**Comment by JustLuuuu** [comment]
Please correct **onchain** **NFTs** to **on-chain NFTs** in the text and in the headlines. We are missing the dash "-".🚀 Besides that, it's good to go.

**Review by roiLeo — APPROVED** [review]
Capture d’écran 2023-07-31 à 11 00 05 AM

☹️ inb4 seo blacklist

**Comment by Jarsen136** [comment]
> Please rename all **onchain** **NFTs** to **on-chain NFTs** in the text and in the headlines. We are missing the dash "-".🚀 Besides that, it's good to go.

✅ Done

**Comment by yangwao** [comment]
pay 50 usd

Let's resolve conflicts @Jarsen136  and it's good to merge so we can push it out live 🙏🔥

**Comment by Jarsen136** [comment]
also close this issue https://github.com/kodadot/nft-gallery/issues/6509#issuecomment-1660603735 

image

**Comment by Jarsen136** [comment]
> spacing and bold on the collections title:
> 
image

@prury  I'm not sure if it's related to Windows OS or not, but I could not reproduce the bold text issue you mentioned. It's a h3 title with bold font weight on my side.
image

**Comment by prury** [comment]
> @prury I'm not sure if it's related to Windows OS or not, but I could not reproduce the bold text issue you mentioned. It's a h3 title with bold font weight on my side. image

aww thats odd, allright! thank you

**Pull request merged**
