### PR TITLE
ensure copy works on all devices

### LINKED ISSUE #8191: copy link does not work on Android nova wallet
I just found that on Android nova, the functionality of `copy link` does not work at all, while on IOS it works.

image

_Originally posted by @Jarsen136 in https://github.com/kodadot/nft-gallery/issues/8188#issuecomment-1823016804_

### LINKED ISSUE #8192: Pretty much nothing related to copy/paste works there

### LINKED ISSUE #8530: Copy address, pay me link, recurring payment buttons on transfer do not work

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #8191
- [x] Closes #8192
- [x] Closes #8530

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at aaf1d15</samp>

The pull request fixes a clipboard bug and adds a custom `copyToClipboard` function. The `plugins/vueClipboard.ts` file was modified to use the new function, and the `utils/copyToClipboard.ts` file was added to export it.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at aaf1d15</samp>

> _`copyToClipboard`_
> _Fixes bug, adds toast option_
> _Winter of clipboard_

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
I would rename `vueClipboard.ts` to `clipboard.client.ts` and maybe add test? @prury 

otherwise code lgtm

**Comment by daiagi** [comment]
>I would rename vueClipboard.ts to clipboard.client.ts

done

**Comment by daiagi** [comment]
failing tests

**Comment by prury** [comment]
> I would rename `vueClipboard.ts` to `clipboard.client.ts` and maybe add test? @prury
> 
> otherwise code lgtm

we have some clipboard tests already, playwright failing because recurring payment button and pay me button not working as they should

**Review by Jarsen136 — APPROVED** [review]

**Comment by yangwao** [comment]
Thanks!
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 7.27 USD/DOT ~ 6.878 $DOT
🧗 [1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8](https://polkadot.subscan.io/account/1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)
🔗 [0xe03742dbd899199e5d54cb47f2ce52b400caeeab60863a7d7a9428e7cf05ed11](https://polkadot.subscan.io/extrinsic/0xe03742dbd899199e5d54cb47f2ce52b400caeeab60863a7d7a9428e7cf05ed11)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
