### PR TITLE
feat: show nft royalties on basilisk

### LINKED ISSUE #3250: Show royalties under the price in basilisk
### Is your feature request related to a problem?

Currently afaik we do not show how much percent of the price are royalties.

### Describe the solution you would like

It would be good to show them under the price

### Describe alternatives you have considered

~

### Screeenshots

I added a couple of screenshots from the past :)

1_i2tmRmrqqWVov8HiDUECVw

1_uow2nQEO4vNG4FogVXPwuw

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

Screenshot 2022-06-24 at 11 08 02

### What's new?

- [x] PR closes #3250
- [ ] Requires deployment <rubick/magick_issue>
- [x] if royalty interaction is set in events, show its value below price on nft detail

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </bsx/gallery/1328724063-1>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by kkukelka** [comment]
still having issue with formatting... any ideas?

**Comment by petersopko** [comment]
> still having issue with formatting... any ideas?

hey, check Money.vue component, I think we need an update there regardless (only way to show number rounded up to 2 decimals is to hide it's unit right now).

**Review by vikiival — CHANGES_REQUESTED** [review]

**Comment by kkukelka** [comment]
should work as intended now
`/bsx/gallery/2735277589-1` 
```javascript
price:"20000000000000000"
royalty:25
```
Screenshot 2022-06-24 at 15 23 32

**Comment by vikiival** [comment]
Screenshot 2022-06-24 at 16 19 46


Darshana knows the codebase well, I'll leave the review for her :)

**Comment by prachi00** [comment]
LGTM

**Review by prachi00 — APPROVED** [review]

**Comment by prachi00** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 56.33 USD/KSM ~ 1.775 $KSM
🧗 [EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW](https://kusama.subscan.io/account/EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)
🔗 [0x28534dbd22b8f3a4e244fb4c4fb48a065ce5217ea480eecca24c07a36e829822](https://kusama.subscan.io/extrinsic/0x28534dbd22b8f3a4e244fb4c4fb48a065ce5217ea480eecca24c07a36e829822)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by vikiival** [comment]
Lovely ❤️ review @prachi00

**Pull request merged**
