### PR TITLE
fix: Visual things in modals

### LINKED ISSUE #7654: Visual things in modals
- it looks like a few things broke
image

image

### changes 
- of the top section to k-shade, in dark mode k-hovergrey or k-grey 
- padding around the to 10px, right now its too big
image

### heading
image
- this alignment does not seem right 

image

- please apply that for other modals as well

### PR DESCRIPTION
**Pull request by hassnian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #7654

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2023-10-15 at 16 03 24@2x

### <samp>🤖 Generated by Copilot at 5fd393a</samp>

Improved the styles and consistency of some modal and identity components. Adjusted the padding, alignment, and color of `IdentityItem.vue`, `ConfirmPurchaseModal.vue`, and `ListingCartModal.vue`.

### <samp>🤖 Generated by Copilot at 5fd393a</samp>

> _To make the modal header look nice_
> _They removed `modal-card-head` in a trice_
> _And added some classes_
> _For padding and axes_
> _Like `is-align-items-center` and `py-5`_

### CODE REVIEW

**Comment by hassnian** [comment]
@exezbcz pls visual check 

> of the top section to k-shade, in dark mode k-hovergrey or k-grey

it's unclear what you mean , i changed the "connected with"  label to have these colors

**Comment by exezbcz** [comment]
> @exezbcz pls visual check 
> 
> > of the top section to k-shade, in dark mode k-hovergrey or k-grey
> 
> it's unclear what you mean , i changed the "connected with"  label to have these colors 

I meant the stroke of the section

**Comment by hassnian** [comment]
@exezbcz 🚀

CleanShot 2023-10-15 at 16 03 24@2x

**Comment by exezbcz** [comment]
It's a really small detail, but now the x-mark is not aligned on the x-axis. 
image

**Comment by yangwao** [comment]
pay 30 usd
thanks! 
small details later 👋

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 3.73 USD/DOT ~ 8.043 $DOT
🧗 [13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh](https://polkadot.subscan.io/account/13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)
🔗 [0x96202e309304ba85b8725e27dedcbca6500f5ef7c517e6c57581c39d569b81de](https://polkadot.subscan.io/extrinsic/0x96202e309304ba85b8725e27dedcbca6500f5ef7c517e6c57581c39d569b81de)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by exezbcz** [comment]
> small details later 👋

its not really small since its the same that was before just on other side..

**Pull request merged**
