### PR TITLE
#1942 Cookie banner seeking shadow

### LINKED ISSUE #1942: Cookie banner seeking shadow
Probably add shadow for banner and for buttons to feel like having depth?

image

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Do a quick check before the merge.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #1942

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases

### Had issue bounty label ?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI, a screenshot is best to understand changes for others.
Screenshot 2022-01-20 at 1 13 14 PM

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
lgtm, I feel that this code will be repeated often, we could create a scss variable or extend it from a rule

edit: seems we've got `$dropdown-content-shadow` variable

**Comment by vikiival** [comment]
> I feel that this code will be repeated often, we could create a scss variable or extend it from a rule

@prachi00  can we have it ❤️ pls?

**Comment by prachi00** [comment]
> 

sure I will do this

**Comment by prachi00** [comment]
Have updated the pr with the changes mentioned

**Comment by yangwao** [comment]
Perfect, I’ve sent the payout https://kusama.subscan.io/extrinsic/0x6eb64e4d0f88c211d2dd90f1f459b78b350b548e5140d402369725ce991cfcba

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/

**Pull request merged**
