### PR TITLE
fix: Check for balances for address more often

### LINKED ISSUE #6750: Check for balances for address more often
> @yangwao I think something went wrong with the payout 👀

yeah we are caching balances too much and I was topping up balance on bot, yet wasn't that much on the address as it showed on sidebar in kodadot, so it failed and then failed in cascade here :) 

Would be nice to check balances on the sidebar and check for that like at least once per 20-30 seconds on-chain balances?

Or before users lands on transfer screen for example at least? Doesn't need to be on sidebar tbh. 

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/6688#issuecomment-1682041120_

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #6750
- [x] Update the balance every 30 seconds

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [ ] My fix has changed UI

### <samp>🤖 Generated by Copilot at 9dc9b29</samp>

This pull request moves the multiple balance feature from the `MultipleBalances` component to the `Navbar` component and adds a timer to update the balance periodically. This improves the user experience and reduces the complexity of the `MultipleBalances` component.

### <samp>🤖 Generated by Copilot at 9dc9b29</samp>

> _To show the user's balance in the navbar_
> _We moved some logic from `MultipleBalances` far_
> _We used a reactive timer_
> _And a blockchain query primer_
> _And cleaned up the timer when we left the car_

### CODE REVIEW

**Comment by vikiival** [comment]
Like a quickfix good

**Comment by prury** [comment]
should it automatically update my transfer page balance if ? if yes, it didn't work
the balance from the sidebar was updated accordingly

**Comment by vikiival** [comment]
> if yes, it didn't work
> the balance from the sidebar was updated accordingly

It periodically updates the balance

As I mentioned before it a good quickfix though we can use proper Talismans or RPC api to get realtime balance

**Comment by prury** [comment]
> > if yes, it didn't work
> > the balance from the sidebar was updated accordingly
> 
> It periodically updates the balance
> 
> As I mentioned before it a good quickfix though we can use proper Talismans or RPC api to get realtime balance

yeah, i waited for the 30 sec and the balance that shows on transfer did not update, only sidebar

**Comment by Jarsen136** [comment]
> > > if yes, it didn't work
> > > the balance from the sidebar was updated accordingly
> > 
> > 
> > It periodically updates the balance
> > As I mentioned before it a good quickfix though we can use proper Talismans or RPC api to get realtime balance
> 
> yeah, i waited for the 30 sec and the balance that shows on transfer did not update, only sidebar

✅ Fixed. 
It's related to another issue that the balance on the transfer page would not change any more, even though the balance on the global state has been updated correctly. Thanks for testing.

**Review by daiagi — APPROVED** [review]

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 4.49 USD/DOT ~ 11.136 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x055549e1a6e5cf92aa611eef2faa6ee9f51615c7eea383a03cb9669fc9b57e2e](https://polkadot.subscan.io/extrinsic/0x055549e1a6e5cf92aa611eef2faa6ee9f51615c7eea383a03cb9669fc9b57e2e)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
