### PR TITLE
WIP: Vue to Nuxt migration

### PR DESCRIPTION
**Pull request by dezine2dev**
**Story**
Migration nft-gallery into Nuxt

**Summary**
 This is work in progress 
 Everything is in /nuxt folder. (One everything is done, it will be replaced with root folder)
 node version - v16

Related #584 
Related https://github.com/kodadot/nft-gallery/issues/912

https://koda-nuxt.netlify.app/ for `main-nuxt` branch

### CODE REVIEW

**Comment by yangwao** [comment]
I'll set up some deployment for Nuxt so others can go through and click it for non-tech savvy people out there.
Other than, I really welcome progress. :)

**Comment by yangwao** [comment]
Approx migration strategy 

https://www.adssx.com/p/a-brief-history-of-cloud-countries

**Review by vikiival — CHANGES_REQUESTED** [review]
It would be good if we migrate only those which we currently use:



### Create
- [ ] Classic mint
- [ ] Simple

### View
- [ ] Gallery
- [ ] Gallery Detail
- [ ] Collection Detail
- [ ] Profile

### Stats
- [ ] Spotlight
- [ ] Series

### Misc
- [ ] Credit
- [ ] FAQ
- [ ] Admin
- [ ] Transfer
- [ ] Settings
- [ ] Tutorial
- [ ] Carbonless
- [ ] Landing
- [ ] Identity

### Footer
- [ ] About
- [ ] Partnership

Please migrate only used components

**Comment by yangwao** [comment]
When I clicked to from https://deploy-preview-843--koda-nuxt.netlify.app/rmrk/gallery/9935513-466e8b6338599eaf1e-GAVCUBE-GAV_CUBE_056-0000000000000056

to profile author 
image

I landed on a blank screen, the probably routing is broken?

**Comment by dezine2dev** [comment]
> When I clicked to from https://deploy-preview-843--koda-nuxt.netlify.app/rmrk/gallery/9935513-466e8b6338599eaf1e-GAVCUBE-GAV_CUBE_056-0000000000000056
> 
> to profile author image
> 
> I landed on a blank screen, the probably routing is broken?

Yes it is another routing breaks.
I will handle that and possible other things as well.
The main reason of this kind of issues is because original app handles routing by name and that name does not match in nuxt. Nuxt creates routing name by folder structure and I need to do navigation by path.

**Pull request merged**
