### PR TITLE
Feat(1285) : Recent Sales for Creator

### LINKED ISSUE #1285: Recent Sales for Creator
help artist navigate and show up recent sales to its account
create a new view for that
probably easy table, querying last 25-50 sales?

Just thinking where to add it, probably right now as a new view? Clicking from profile?

The end goal is to have an addressable page where creators can back check daily/weekly/monthly to take a peak on their performance

### spec
Let's start as a primitive table there with a dropdown.
Route should be `/profile/sales` once you are logged in.
In the dropdown, you could choose view per collection or ALL.

| **NFT Collection** | **address** which bought it | price | date - ago (absolute on hover) |
|-|-|-|-|

# 💳 
I recall @vikiival was this suggesting like analytics for artists quite long time. Let's put something on race line.

### From #571 

As a creator I would love to see statistics for myself

Total earned
Number of sales
Avg history price
[add your creativity here]
Additional context
This can be done by one or two queries via subquery (I can help here)

For Chart library I don't have any preference.

In case of any question feel free to hit me up on Discord/ Telegram/ Twitter.

# Ref 
- inspiration https://analytics.viberate.com/

### PR DESCRIPTION
**Pull request by MSghais**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [X] Feature
- [ ] Refactoring

### What's new?

- [X] PR closes #1285 
- [X] Table with all sales of nft for a creator.

### Before submitting Pull Request, please make sure:

- [X] My contribution builds **clean without any errors or warnings**
- [X] I've merged recent default branch -- **main** and I've no conflicts
- [X] I've tried to respect high code quality standards
- [X] I've didn't break any original functionality
- [X] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [X] I've tested PR on mobile and everything seems works
- [X] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EFuhGSJpetTgoZ2dfWxwirxADBWgAzWmVfJmTCauZuPxz6z

### Community participation

- [X] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [X] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

image

### CODE REVIEW

**Comment by prachi00** [comment]
Screen Shot 2022-05-19 at 9 34 46 AM

can we move the pagination to the right to keep things consistent in all the tabs?

**Comment by prachi00** [comment]
https://www.loom.com/share/4b0694dec1984ff5a98ddc10e94b4131 
when you click on pagination buttons, the width changes erratically

**Comment by prachi00** [comment]
> https://www.loom.com/share/4b0694dec1984ff5a98ddc10e94b4131 when you click on pagination buttons, the width changes erratically

so turns out it happens on buefy also https://buefy.org/documentation/pagination/
so we can ignore this one for now. 

@MSghais

**Comment by vikiival** [comment]
> Self review

I see you are super autonomous sir!
gj!

6h6gdr

**Review by prachi00 — APPROVED** [review]

**Comment by prachi00** [comment]
pay 150 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $150 @ 84.39 USD/KSM ~ 1.777 $KSM
🧗 [EFuhGSJpetTgoZ2dfWxwirxADBWgAzWmVfJmTCauZuPxz6z](https://kusama.subscan.io/account/EFuhGSJpetTgoZ2dfWxwirxADBWgAzWmVfJmTCauZuPxz6z)
🔗 [0xe3a7c9a61f68ab830ae07fbcbd86edbe6bdf2744d7ddbd6ad58c70b904f05a8b](https://kusama.subscan.io/extrinsic/0xe3a7c9a61f68ab830ae07fbcbd86edbe6bdf2744d7ddbd6ad58c70b904f05a8b)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by prachi00** [comment]
pay 50 usd

**Pull request merged**
