### PR TITLE
add contribution to footer

### LINKED ISSUE #2661: Link contribute to footer 😇
oh, I forgot if we can link contribute to footer 😇

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/2644#issuecomment-1077558235_

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2661
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by yangwao** [comment]
"Contribute" would sound more like call to action, rather contribution, please change it and we can merge it 😇

**Comment by yangwao** [comment]
pay 50 usd

**Comment by Jarsen136** [comment]
> pay 50 usd

Looks like the payment process failed 👀   @yangwao

**Comment by Jarsen136** [comment]
> 
> Looks like the payment process failed 👀 @yangwao

Hi, please take a look at this problem~ @yangwao

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 167.8 USD/KSM ~ 0.298 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xeeda7bd858048a8eba7794963c2f70f70a0b779b6727bb28d78efde03a2ae227](https://kusama.subscan.io/extrinsic/0xeeda7bd858048a8eba7794963c2f70f70a0b779b6727bb28d78efde03a2ae227)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
> > pay 50 usd
> 
> Looks like the payment process failed 👀 @yangwao

yeah github webhook were down so, need think of more resilient way if something this happen in future

**Pull request merged**
