### PR TITLE
fix: explore tabs & btn responsive (mobile/tablet)

### LINKED ISSUE #4992: explore tabs & btn responsive (mobile/tablet)
### First point

On tablet and/or small screen the navigation bar does not seem to be responsive, we can scale down tab selector (Collection/items) 
image

### Second point

left margin missing (container for galleryItem & collectionItem) same on mobile 
use `section` class
image

_Originally posted by @exezbcz in https://github.com/kodadot/nft-gallery/issues/4961#issuecomment-1425820138_

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4992
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
lgtm on mobile & tablet

but on desktop it's not aligned
Screenshot 2023-02-14 at 09-17-37 Low minting fees and carbonless NFTs KodaDot - NFT Market Explorer

I think you need to do something like:
```html
<div class="section">
  <div class="container">
    ...
  </div>
</div>
```

**Comment by Jarsen136** [comment]
> lgtm on mobile & tablet
> 
> but on desktop it's not aligned Screenshot 2023-02-14 at 09-17-37 Low minting fees and carbonless NFTs KodaDot - NFT Market Explorer
> 
> I think you need to do something like:
> 
> ```
> <div class="section">
>   <div class="container">
>     ...
>   </div>
> </div>
> ```


Thanks! I have fixed it.

image

**Review by roiLeo — APPROVED** [review]
Noice! 

✅ lgtm

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 32.46 USD/KSM ~ 0.924 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xb54dd5eebd54b08d8e7a0d496f2d7283eb0b913ca18722629c3cc67cb84790a6](https://kusama.subscan.io/extrinsic/0xb54dd5eebd54b08d8e7a0d496f2d7283eb0b913ca18722629c3cc67cb84790a6)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
