### PR TITLE
fix: Mobile menu gone on 640-1024px

### LINKED ISSUE #9915: Mobile menu gone on 640-1024px
image

burger menu is missing 

to reproduce: switch to mobile, refresh, move in this range

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs Design check

- @exezbcz please review

## Context

- [x] Closes #9915

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by exezbcz** [comment]
lol that was fast

**Comment by prury** [comment]
it appears now but its position its not covering the whole screen: 

https://github.com/kodadot/nft-gallery/assets/36627808/76b8c9bc-f907-4a7c-93bd-9e1d77aae402

**Comment by Jarsen136** [comment]
> it appears now but its position its not covering the whole screen:
> 

✅ Fixed. It's from canary env though.

**Comment by daiagi** [comment]
the width of the navbar change when opening/closing the burger menu

**Comment by prury** [comment]
> > it appears now but its position its not covering the whole screen:
> 
> ✅ Fixed. It's from canary env though.

thank you for going beyond then

**Comment by Jarsen136** [comment]
> the width of the navbar change when opening/closing the burger menu

✅ Fixed too

**Review by daiagi — APPROVED** [review]

**Review by preschian — APPROVED** [review]

**Comment by prury** [comment]
@Jarsen136 create another issue, lmk if you want to solve it here or on another PR

- https://github.com/kodadot/nft-gallery/issues/9933

**Comment by Jarsen136** [comment]
> @Jarsen136 created another issue, lmk if you want to solve it here or on another PR
> 
> * [burguer menu options overlapping with Navbar on 640-1024px width #9933](https://github.com/kodadot/nft-gallery/issues/9933)

I would make it on another PR

**Comment by prury** [comment]
@yangwao payment

**Comment by prury** [comment]
pay 15 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $15 @ 8.45 USD/DOT ~ 1.775 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0xf8b4832e5cbddf7518b03c1a3a10d42220ef72fad7884ea317b0c3d6b5a681d7](https://polkadot.subscan.io/extrinsic/0xf8b4832e5cbddf7518b03c1a3a10d42220ef72fad7884ea317b0c3d6b5a681d7)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
