### PR TITLE
feat: download option for gen art

### LINKED ISSUE #10028: No download option for gen art
for normal nfts, we had option in the three dots to download the image as jpg 

image

can we have it for gen art as well?

Luu will thank you

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Feature

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #10028

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed UI

image

### CODE REVIEW

**Comment by yangwao** [comment]
One wish @Jarsen136 can we make that downloaded file won't be called download.png

but something like
<collection_name>_<item_name> ?

🫡

**Comment by Jarsen136** [comment]
> One wish @Jarsen136 can we make that downloaded file won't be called download.png
> 
> but something like <collection_name>_<item_name> ?
> 
> 🫡

Sure yes 🫡

image

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
Screenshot 2024-04-10 at 13 26 03

**Comment by prury** [comment]
pay 25 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $25 @ 8.25 USD/DOT ~ 3.03 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x194444608c49fd6078f7a5d2a2d1e3065e6c23d6c64cbb3a8c22cb8f0a0f9640](https://polkadot.subscan.io/extrinsic/0x194444608c49fd6078f7a5d2a2d1e3065e6c23d6c64cbb3a8c22cb8f0a0f9640)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
