### PR TITLE
feat: Show search term on collection

### LINKED ISSUE #5199: Show search term on collection
when switching from items to collection the searched tag disappear.
We should display it there as well - as filter between menu and divider 
image
after switching to collection
image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #5199
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Review by vikiival — APPROVED** [review]
Looks LGTM

**Comment by roiLeo** [comment]
something weird:
- pressed enter two times to search "kitty"
- tried to close search Breadcrumb (collections page) and it won't reset search

recording


<details><summary>Browser metadata</summary>





```
Path:      /bsx/explore/collectibles?page=1
Browser:   Firefox 111.0 on Mac OS 10.15
Viewport:  1920 x 995 @1x
Language:  en
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-5204--koda-nuxt.netlify.app%2Fbsx%2Fexplore%2Fcollectibles%3Fpage%3D1&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=111.0&resolution=1920x995&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-5204--koda-nuxt.netlify.app/bsx/explore/collectibles?page=1) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=64088617212ee70008a0e35a&commentID=6408b1ca66f09a5997e81d6a&resolution=resolved)

**Comment by Jarsen136** [comment]
> something weird:
> 
> * pressed enter two times to search "kitty"
> * tried to close search Breadcrumb (collections page) and it won't reset search
> 

I will check them.

**Comment by Jarsen136** [comment]
> something weird:
> 
> * pressed enter two times to search "kitty"

(I have to operate fast after reload page to reproduce this bug.)
I could also reproduce this bug on beta env, so let's trace it on another issue #5213

> * tried to close search Breadcrumb (collections page) and it won't reset search

✅ Fixed

**Pull request merged**
