### PR TITLE
fix: responsive ModalWrapper content

### LINKED ISSUE #5975: responsive ModalWrapper content
On tablet modal has weird behavior

Screenshot 2023-05-15 at 10-47-57 Budget Spaceships KodaDot - NFT Market Explorer

### Step to reproduce
- go to any collection
- click on share button
- click on qrcode
- modal content width should only contain qr code

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 \_\_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5975
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/ksm/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### <samp>🤖 Generated by Copilot at 987aae5</samp>

Improved the responsiveness and layout of the `NeoModal` component by setting its width to `auto` in `NeoModal.scss`.

### <samp>🤖 Generated by Copilot at 987aae5</samp>

> _`Modal` adapts_
> _To its content gracefully_
> _Like a spring blossom_

### CODE REVIEW

**Review by preschian — APPROVED** [review]

**Review by roiLeo — APPROVED** [review]
Lgtm

**Comment by yangwao** [comment]
pay usd 20

**Comment by yangwao** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 5 USD/DOT ~ 4 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x6a6e4fee36bdd182476ae81712ccb32c3b4f9e61121004f3da94b112fb5f35ee](https://polkadot.subscan.io/extrinsic/0x6a6e4fee36bdd182476ae81712ccb32c3b4f9e61121004f3da94b112fb5f35ee)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
