### PR TITLE
#4241 Navbar scroll update

### LINKED ISSUE #4241: Redesign: Navbar on scroll updates
## Navbar 
- navbar on scroll, if you scroll outside of the navbar section in the hero range, should look like this: 
image
- it should also have white fill.
image
summary: 
1) remove blur bg, add white

this part @prachi00 

if something is unclear, lmk

_Originally posted by @exezbcz in https://github.com/kodadot/nft-gallery/issues/4185#issuecomment-1301041576_

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## PR Context?

- [x] Closes #4241
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screen Shot 2022-11-02 at 7 24 06 PM

### CODE REVIEW

**Comment by prachi00** [comment]
@exezbcz let me know if this is what you expected

**Comment by exezbcz** [comment]
image
yup, the bg is correct. 
- there are just some info missing 
- search bar should not expand to the rest of the nav
- similar like this: 
image

**Comment by prachi00** [comment]
> image yup, the bg is correct.
> 
> * there are just some info missing
> * search bar should not expand to the rest of the nav
> * similar like this:
>   image

so would it also show all the other info like  explore, create, stats, connect button?

**Comment by exezbcz** [comment]
Yup

**Comment by prachi00** [comment]
> image yup, the bg is correct.
> 
> * there are just some info missing
> * search bar should not expand to the rest of the nav
> * similar like this:
>   image

done

**Comment by yangwao** [comment]
> missing searchbar on scroll?

yes, it's missing @prachi00

**Comment by prachi00** [comment]
Added the searchbar

**Comment by yangwao** [comment]
pay 40

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $40 @ 37.42 USD/KSM ~ 1.069 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x88121febc076931f2f660c3575a2b57f5f78c383b7c572fb811ecf121d056920](https://kusama.subscan.io/extrinsic/0x88121febc076931f2f660c3575a2b57f5f78c383b7c572fb811ecf121d056920)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
@prachi00 👀

image

**Pull request merged**
