### PR TITLE
#3737 landing css issue

### LINKED ISSUE #3737: Landing Touch Up on 📱
I've noticed our landing at beta could use touch up, here's part of it
image

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #3737
- [x] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screen Shot 2022-08-15 at 10 20 38 PM

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
✅ works well on mobile

**Review by petersopko — APPROVED** [review]
lgtm

**Comment by petersopko** [comment]
pay 20 usd

**Comment by petersopko** [comment]
> pay 20 usd

@yangwao 👀 looks like you were right about the bot

**Comment by yangwao** [comment]
pay 20

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 54.61 USD/KSM ~ 0.366 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0xa788af57283413232d31a321b228a8e45040f2c9c4e047d20806e54520580027](https://kusama.subscan.io/extrinsic/0xa788af57283413232d31a321b228a8e45040f2c9c4e047d20806e54520580027)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
