### PR TITLE
feat: add item column and relative time to history

### LINKED ISSUE #2547: Rework feed for collection bit
At buy events, we are missing Item name. 
- Add there as the second col as item name, where name length keeps first six and last six characters. 
- Change the date to relative time (20 minutes ago). On hover show the exact time. This could be changed for the history component at nft item as well. 

image

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

https://user-images.githubusercontent.com/17953978/158453923-8e1830c9-241e-4bd4-9ab2-8985d397ac37.mov

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2547
- [x] Added column which shows item id and links to gallery page (name is not available so we take id for now), added relative time and tooltip with exact stamp on hover

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by yangwao** [comment]
Probably #2545 broke something here 👀

**Comment by vikiival** [comment]
Screenshot 2022-03-16 at 13 28 30

My mac has frozen.
@yangwao said that there is a pagination for the history component

**Comment by vikiival** [comment]
@kkukelka may update your PR with the latest main?

**Comment by yangwao** [comment]
> @kkukelka may update your PR with the latest main?

Maybe you drink too much club mate?

**Comment by kkukelka** [comment]
> @kkukelka may update your PR with the latest main?

done

**Comment by kkukelka** [comment]
looks normal here or am i missing something?
Screenshot 2022-03-16 at 14 36 25

**Comment by yangwao** [comment]
here https://deploy-preview-2552--koda-nuxt.netlify.app/rmrk/collection/2644199cf3652aaa78-KK01?tab=history

**Comment by yangwao** [comment]
I sense that pagination doesn't work here? 

almost frozen my stuff https://deploy-preview-2552--koda-nuxt.netlify.app/rmrk/collection/b45071647155359951-SUBSTRA?tab=history&page=5

**Comment by yangwao** [comment]
clicked update branch, let's see?

**Comment by yangwao** [comment]
Schumacher, seems lots of caffeine today lol

otherwise, it's working?

https://user-images.githubusercontent.com/5887929/158605663-78a5d3cb-c963-46ce-ae5d-8ed42791724a.mov

**Review by vikiival — APPROVED** [review]

**Comment by yangwao** [comment]
oh found bug, link to item doesn't work 
leads to non-existing nft https://deploy-preview-2552--koda-nuxt.netlify.app/rmrk/gallery/9181565-dac5c7f54029d0e73c-HXAI8-E_V_EM-0000000000000052-BUYg54M6_EPLgXDtmfTDP663

image

**Comment by vikiival** [comment]
Good eye! 

```json
{
  "id": "9181565-dac5c7f54029d0e73c-HXAI8-E_V_EM-0000000000000052",
  "events": [
    {
      "id": "9181565-dac5c7f54029d0e73c-HXAI8-E_V_EM-0000000000000052-MINTNFTKZ6hxTeIVTR8CKEx1UGac"
    },
    {
      "id": "9181565-dac5c7f54029d0e73c-HXAI8-E_V_EM-0000000000000052-LISTVg-SA9ZqfMYVyNOq0TRRy"
    },
    {
      "id": "9181565-dac5c7f54029d0e73c-HXAI8-E_V_EM-0000000000000052-BUYpfpKvJxNHW2JrskhHZoDM"
    },
    {
      "id": "9181565-dac5c7f54029d0e73c-HXAI8-E_V_EM-0000000000000052-LISTQDPhuXFgDiG2C42oehjeQ"
    },
    {
      "id": "9181565-dac5c7f54029d0e73c-HXAI8-E_V_EM-0000000000000052-BUYLSmNCpMZBeiwl2CHMj7Uu"
    },
    {
      "id": "9181565-dac5c7f54029d0e73c-HXAI8-E_V_EM-0000000000000052-LISTRWcsa83ZhcXY3dTLX81su"
    },
    {
      "id": "9181565-dac5c7f54029d0e73c-HXAI8-E_V_EM-0000000000000052-LISTXXxJ1lYPxRa8uf7uTg4m2"
    },
    {
      "id": "9181565-dac5c7f54029d0e73c-HXAI8-E_V_EM-0000000000000052-LISTeBoxa_zCzB9uig5eWfKif"
    },
    {
      "id": "9181565-dac5c7f54029d0e73c-HXAI8-E_V_EM-0000000000000052-LISTwINca_XiQf6yN1mMZJwRB"
    },
    {
      "id": "9181565-dac5c7f54029d0e73c-HXAI8-E_V_EM-0000000000000052-LISTSC43fZxm5Mg1XE4_Eyduh"
    }
  ]
}
```

@kkukelka fast fix is to remove everything after the last dash

```js
const reg = /-[a-zA-Z0-9_]+$/

id.replace(reg, '')
```

**Comment by vikiival** [comment]
Better approach is to select name and id from NFT :)

**Comment by kkukelka** [comment]
> @kkukelka fast fix is to remove everything after the last dash
> 
> ```js
> const reg = /-[a-zA-Z0-9_]+$/
> 
> id.replace(reg, '')
> ```

gonna opt for regex as i dont have time update graphql query
```javascript
event['Item'] = newEvent['id']?.replace(
          /-(BUY|CONSUME|LIST|MINT|MINFNFT|SEND).+$/,
          ''
        )
```

also made sure not to show item column on NFT Detail page

**Comment by yangwao** [comment]
Add the name of the item to the history, once it would be available. 
Right now making this issue name was not available.

**Pull request merged**
