### PR TITLE
#611 Unlist button in NFT

### LINKED ISSUE #611: Add ability to unlist NFT when is on sale
When a user accidentally list NFT for sale, would be nice to have a button there ppl can unlist it but not burn it.
Now way around @vikiival suggest is to LIST it for 0 KSM which not everyone gets.
Having a dedicated **UNLIST** button would be way easier for creators to achieve.
image

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the KodaDot NFT gallery.
Let's do a quick check before the merge.
Your contribution will be an eternal part of the community codebase

### Before submitting this PR, please make sure:
- [x] Code builds clean without any errors or warnings
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I didn't break any original functionality

### Optional
- [ ] I've tested it on mobile and everything works

### PR type
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new? (maybe part of changelog)
- closes #611 - I have added an Unlist button Alongside price. I have used refs, so that the common function from Actions component can be reused. 

### If issue contains bounty label ($,$$,$$$)
- Your KSM address: EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU

### Community participation
- [x] Are you at KodaDot Discord? If no, [let's join us - https://discord.gg/35hzy2dXXh](https://discord.gg/35hzy2dXXh)

### Screenshot
- [x
Screenshot 2021-09-01 at 10 44 17 PM
]
 Whenever your fix will change **something** on UI, a screenshot is more than welcome

### CODE REVIEW

**Comment by roiLeo** [comment]
Should we see the button when the user is not logged in? Is this a normal behavior? I thought the "unlist" button was only visible for the owner.

**Comment by vikiival** [comment]
> Should we see the button when the user is not logged in? Is this a normal behavior? I thought the "unlist" button was only visible for the owner.

Yup @roiLeo is right.
Unlist should be visible only if `currentOwner === accountId and nft.price > 0`

**Review by vikiival — CHANGES_REQUESTED** [review]
Unlist should be visible only if `currentOwner === accountId and nft.price > 0`

**Comment by prachi00** [comment]
> Unlist should be visible only if `currentOwner === accountId and nft.price > 0`

@roiLeo @vikiival Have added the check for this, seems to be working fine now.

**Review by vikiival — APPROVED** [review]
LGTM

**Review by roiLeo — APPROVED** [review]

**Pull request merged**
