### PR TITLE
fix: Unable to show html media

### LINKED ISSUE #7495: Unable to show html media
### What happened?

I minted an NFT where `animation_url` is a folder (aka html with some css and js)

https://canary.kodadot.xyz/snek/gallery/3919361082-3

[Content here](https://ipfs.io/ipfs/bafybeiau53zl3gfhcmnplmafmfwr7ryx237klgzwu6mp6ug7fat333ihqe/)

And app just 

### Please reproduce in steps

1.Go to NFT https://canary.kodadot.xyz/snek/gallery/3919361082-3
2.Only image is shown and animation_url not

### Expected Behavior

I expect that html would be loaded via iframe

```html
<iframe
  sandbox="allow-scripts allow-same-origin allow-modals"
  allow="accelerometer *; camera *; gyroscope *; microphone *; xr-spatial-tracking *;"
  src=""
>
</iframe>
```

### What browsers are you seeing the problem on?

_No response_

### At which address did you encounter bug?

_No response_

### Are you logged in?

None

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

_No response_

### Screenshots

Screenshot 2023-10-03 at 14 28 50

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/ksm/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix: Unable to show html media
  - [x] fix: iframe style on the nft card

  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #7495
  - [ ] Requires deployment <snek/rubick/worker>

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

  ## Copilot Summary
  
### <samp>🤖 Generated by Copilot at 3924348</samp>

Refactored and improved the `IFrameMedia` component to support responsive and secure embedding of various media types in the NFT gallery. Moved the component from `libs/ui` to `components/media` and updated its usage and style accordingly.

  
### <samp>🤖 Generated by Copilot at 3924348</samp>

> _`iframe` improved_
> _responsive, flexible, safe_
> _winter of refactor_

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
Why do we have same component used twice? which one is used in galleryitem?

otherwise ✅ code lgtm

**Review by preschian — APPROVED** [review]

**Comment by Jarsen136** [comment]
> Why do we have same component used twice? which one is used in galleryitem?
> 
One is used for gallery item on the details page, the other one is for nft card in the grid list. I bet we could make a follow-up issue to unify these two similar components.

**Comment by vikiival** [comment]
> Why do we have same component used twice? which one is used in galleryitem?

can be fixed by #7535

**Comment by vikiival** [comment]
Looks like app does not build

**Comment by Jarsen136** [comment]
> Looks like app does not build

It does build normally. https://deploy-preview-7524--koda-canary.netlify.app/

**Comment by vikiival** [comment]
Screenshot 2023-10-09 at 11 49 18


`/snek/collection/3919361082`

1. app shows just part of the image

This can be done in https://github.com/kodadot/nft-gallery/issues/7535

Screenshot 2023-10-09 at 11 50 14

2. app shows just part of the image in the item detail

this is a no-go since it does not make sense to show just a small portion

Screenshot 2023-10-09 at 11 50 35

**Comment by yangwao** [comment]
I see it normally on gallery item. 
- https://deploy-preview-7524--nuxt-kodadot.netlify.app/snek/gallery/3919361082-3
image

**Comment by vikiival** [comment]
https://github.com/kodadot/nft-gallery/assets/22471030/b8fbdaf8-4d31-4b03-a4bf-e5c9bc0adf52

**Comment by vikiival** [comment]
pay 10 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $10 @ 3.86 USD/DOT ~ 2.591 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x5510c64da00095963d88bc75460c481ef1f7441679beddc5c8879fde078b6c36](https://polkadot.subscan.io/extrinsic/0x5510c64da00095963d88bc75460c481ef1f7441679beddc5c8879fde078b6c36)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
