### PR TITLE
:tada: Polkadot for Specific things

### LINKED ISSUE #6020: Add option to use DOT in Transfer
we would like to internally migrate to DOT for now.

how to do it best? add prefix to URL /dot/ and it will connect you to DOT rpc nodes?

how users could generate link, add extra network switch to Polkadot? if so needs update into packages for extra network

### LINKED ISSUE #6091: add showing DOT balances to sidebar
I think we should add also showing DOT balances to sidebar 

image

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/6088#issuecomment-1559655794_

### PR DESCRIPTION
**Pull request by vikiival**
## TL;DR 

We will be slowly onboarding Kodadot into DOT ecosystem.
So @yangwao asked me to make DOT for transfers

- :bookmark: static@0.0.3-rc.0
- :bookmark: static@0.0.3-rc.1
- :bug: readonly
- :tada: dot works
- :wrench: disable dot
- :zap: hide explorer for dot

**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 \_\_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #6020
- [x] Closes #6091  

#### Before submitting pull request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/ksm/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

Screenshot 2023-05-23 at 16 16 58

Screenshot 2023-05-23 at 16 18 16

### <samp>🤖 Generated by Copilot at 9552ece</samp>

This pull request adds support for Polkadot as a new chain to the KodaDot app. It updates the `@kodadot1/static` library and adds the Polkadot constants, endpoints, indexers, and names to the static files. It also adds a feature to hide the explore option in the navbar for chains that do not have a subscan explorer, using a utility function `explorerVisible`. It disables the create and explore options for Polkadot in the permission config, and adds the `dot` prefix to the relevant types. It also updates some dependencies in `pnpm-lock.yaml` and `package.json`.

### <samp>🤖 Generated by Copilot at 9552ece</samp>

> _We're adding Polkadot to the KodaDot app_
> _`@kodadot1/static` is the library we tap_
> _We update the endpoints, indexers, and names_
> _We hide the explore option for the chains with no subscan flames_

### CODE REVIEW

**Review by Jarsen136 — APPROVED** [review]
code lgtm

**Comment by yangwao** [comment]
https://deploy-preview-6088--koda-canary.netlify.app/dot/transfer?target=1KxzJHoRJHi8EgWVhrGDueeyzg8PyihAvSL3NP6QMcxEve6&usdamount=0&donation=true

hmm it generates something 👀

**Comment by yangwao** [comment]
I think we should add also showing DOT balances to sidebar 

image

**Comment by vikiival** [comment]
Added in the last commit for KogaDot sir

Screenshot 2023-05-23 at 18 07 18

**Comment by yangwao** [comment]
> Added in the last commit for KogaDot sir

image

lgtm!

**Comment by prury** [comment]
Nice! 
image
https://polkadot.subscan.io/tx/0xe03cd396b0f2f5ca31b482ac327cd3eb742792c21cadb23160a36c9e2138b835

**Review by roiLeo — APPROVED** [review]

**Comment by yangwao** [comment]
https://polkadot.subscan.io/extrinsic/0xfeba1973d3506809c9f1f046e4f2ccfd19e5604496e19cc52655fea8346d8e03 sent @vikiival $100 seems works!

image

**Pull request merged**
