### PR TITLE
🔧 GalleryItem SEO

### PR DESCRIPTION
**Pull request by roiLeo**
- ref #7375 

Tested on `/ksm/gallery/16759320-8453d0ccb4cb7e9e59-A51-THE_FOUNDRY-00000246`

Capture d’écran 2023-10-10 à 10 28 48 AM

### CODE REVIEW

**Comment by roiLeo** [comment]
idk why but I can see the metadata in my plugin

Capture d’écran 2023-10-10 à 10 41 13 AM

**Review by preschian — APPROVED** [review]

**Comment by preschian** [comment]
> idk why but I can see the metadata in SeoMetaInspector

it means we still need [ssr-opengraph](https://github.com/kodadot/workers/blob/main/ssr-opengraph/wrangler.toml) or [prerender](https://github.com/kodadot/workers/blob/main/prerender/wrangler.toml) workers

Unless we found a way to enable ssr mode on our `nuxt` branch. https://nuxt.com/docs/api/composables/use-server-seo-meta

currently nuxt subdomain is served on netlify. I can't put ssr-opengraph or prerender on netlify

Screenshot 2023-10-10 161846

**Comment by roiLeo** [comment]
> it means we still need [ssr-opengraph](https://github.com/kodadot/workers/blob/main/ssr-opengraph/wrangler.toml) or [prerender](https://github.com/kodadot/workers/blob/main/prerender/wrangler.toml) workers

Do we need to run a worker to fix this?

> Unless we found a way to enable ssr mode on our `nuxt` branch. https://nuxt.com/docs/api/composables/use-server-seo-meta

We could try https://github.com/harlan-zw/nuxt-og-image & `nuxt-seo-kit` package

> currently nuxt subdomain is served on netlify. I can't put ssr-opengraph or prerender on netlify

do you mean that it need to be on the same subdomain to generate image?

**Comment by preschian** [comment]
> Do we need to run a worker to fix this?
> 
> > Unless we found a way to enable ssr mode on our `nuxt` branch. [nuxt.com/docs/api/composables/use-server-seo-meta](https://nuxt.com/docs/api/composables/use-server-seo-meta)
> 
> We could try [harlan-zw/nuxt-og-image](https://github.com/harlan-zw/nuxt-og-image) & `nuxt-seo-kit` package

if we can enable SSR support in the `nuxt` branch, it's better to drop prerender workers. use that nuxt-og-image or nuxt-seo-kit instead

**Comment by yangwao** [comment]
I would vote for nuxt-og-image as we can play with that easier

**Comment by roiLeo** [comment]
> if we can enable SSR support in the `nuxt` branch, it's better to drop prerender workers. use that nuxt-og-image or nuxt-seo-kit instead

I'm pretty sure that if we enable ssr support now it will break many things (`window` & `document` need to be on client-side)

**Comment by preschian** [comment]
> > if we can enable SSR support in the `nuxt` branch, it's better to drop prerender workers. use that nuxt-og-image or nuxt-seo-kit instead
> 
> I'm pretty sure that if we enable ssr support now it will break many things (`window` & `document` need to be on client-side)

yes 👍

I think if we want to start to check ssr mode, we can start from `/blog` first. In the meantime, we still use our prerender workers.

**Pull request merged**
