### PR TITLE
fix: New wallets: Autoteleport: Got stuck on checking funds

### LINKED ISSUE #10225: New wallets: Autoteleport: Got stuck on checking funds
I tried to buy one [hdd](https://kodadot.xyz/ahp/drops/hdd) NFT. I had 0 DOT on AHK, so I used auto teleport, apparently I teleported 0.081 DOT.

Transaction here - teleport: https://polkadot.subscan.io/extrinsic/0x8f238f4bcb6a745e8d717274f3641f22370954ccedf656b9978dbe4353a6ed31 

I got stuck on checking funds. 
Screenshot 2024-05-05 at 13 50 32

Wallet: 14SsBi9vrcKZciZTqyCrF5EzD2SPGmaEAcbyeuiDzsLUNC6Q

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- there is a discrepancy between the amount that should arrive and the amount arriving, probably its the delivery fee, that atm it's not being accounted for by polkadot js 

- tried with 0 DOT on ahp account and the balance check was successful 

- [x] Closes #10225

## Needs QA check

- @kodadot/qa-guild please review

## Needs Design check

- @exezbcz please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

https://github.com/kodadot/nft-gallery/assets/44554284/10dbd695-73e5-4b57-9e5b-d244e495bdb4

### CODE REVIEW

**Comment by prury** [comment]
problem still persists here: 

[hassnian-checkinfunds.webm](https://github.com/kodadot/nft-gallery/assets/36627808/05f6a208-b434-4825-ad76-52f96425bf70)

**Comment by hassnian** [comment]
@prury  try again 

thanks

https://github.com/kodadot/nft-gallery/assets/44554284/c0b5a1e8-9c89-4985-9b8b-6392235e3859

**Comment by prury** [comment]
> @prury try again
> 

tried again, checking funds error seems to be gone, cancelled mint and tried again, received an error that i was not receiving before: 

[Gravação de tela de 09-05-2024 10:44:37.webm](https://github.com/kodadot/nft-gallery/assets/36627808/daa5c09c-de2b-4674-af38-7a936f48c518)

**Comment by prury** [comment]
ok, checking funds works properly, the other error is not related to this PR

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
cc @daiagi

**Comment by JustLuuuu** [comment]
A peson just got stuck again on checking funds.

**Comment by vikiival** [comment]
@JustLuuuu can you please test if this works?

**Pull request merged**
