### PR TITLE
#2059 Use only border-top on control buttons/actions

### LINKED ISSUE #2059: Use only border-top on control buttons/actions
Time to lightweight our UI for easier adoption.

- Let's remove the border and keep only border-top like on pic1
- Use border-top on emojis as well 
- remove the white shadow from accordion/cards at price chart and history
- rename "Price Chart" -> "Chart"
- at history button, language and profile button as well, pic4

Test case https://kodadot.xyz/rmrk/gallery/11079135-00da54310732f6437d-QBCVI-ONI_10125-0000000000000016
image
image
image
image

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Do a quick check before the merge.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #2059
- [ ] 

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases

### Had issue bounty label ?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI, a screenshot is best to understand changes for others.
Screenshot 2022-01-27 at 3 37 40 PM
Screenshot 2022-01-27 at 3 37 47 PM
Screenshot 2022-01-27 at 3 37 50 PM

### CODE REVIEW

**Comment by yangwao** [comment]
@prachi00 seems we need to resolve some battle in files and we are good to go! :)

**Comment by prachi00** [comment]
@yangwao Have resolved the conflicts, seems good now.

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 167.62 USD/KSM ~ 0.597 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0xb611db9bd6fd4db8f7a5cf28c373d51b148f24f2f67a617441124adf7808aae0](https://kusama.subscan.io/extrinsic/0xb611db9bd6fd4db8f7a5cf28c373d51b148f24f2f67a617441124adf7808aae0)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 157.66 USD/KSM ~ 0.634 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0xca942b855b720c50ba2bdbae728a7824ab78b26bcd96e0e34b26f3c06d55e9ed](https://kusama.subscan.io/extrinsic/0xca942b855b720c50ba2bdbae728a7824ab78b26bcd96e0e34b26f3c06d55e9ed)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
