### PR TITLE
🇮🇳 hindi translation

### PR DESCRIPTION
**Pull request by roiLeo**
- continue #9088

### CODE REVIEW

**Comment by yangwao** [comment]
I mean we are missing some key keys

**Comment by roiLeo** [comment]
@yangwao why merge the other one?

**Comment by yangwao** [comment]
> why merge the other one? now I have load of conflicts..

continue https://github.com/kodadot/nft-gallery/pull/9088


thought it's follow, we can revert than 9088 ?

**Comment by yangwao** [comment]
let's @roiLeo resolve it please, feel revert anything on your own, thought want to push it to production :)

**Comment by roiLeo** [comment]
Aight sorry for the salty comment, should be good now.

**Comment by yangwao** [comment]
> will try to fix it again but it's a bit annoying ☹️

sorry for misscordination 

friends, again?

**Comment by roiLeo** [comment]
it's kind of my fault anyway, let's move on

ohyoushiba

**Comment by yangwao** [comment]
@roiLeo can merge?

**Comment by roiLeo** [comment]
> @roiLeo can merge?

yessir 🚀

**Pull request merged**
