### PR TITLE
#4314 height issue

### LINKED ISSUE #4314: Footer should be fixed at the bottom
### What happened?

Footer is floating

### Please reproduce in steps

1. go to create
2. select NFT

### Expected Behavior

Footer is fixed at the bottom of the page without the whitespace below it.

### What browsers are you seeing the problem on?

_No response_

### At which address did you encounter bug?

_No response_

### Are you logged in?

_No response_

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

_No response_

### Screenshots

Screenshot 2022-11-12 at 14 59 28

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4314
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screen Shot 2023-03-30 at 8 32 20 PM

### CODE REVIEW

**Comment by vikiival** [comment]
Hey @prachi00,
I have this black stripe https://deploy-preview-5439--koda-nuxt.netlify.app/bsx/create

Screenshot 2023-03-31 at 11 56 21

**Review by vikiival — CHANGES_REQUESTED** [review]
As per comment above

**Comment by prachi00** [comment]
@vikiival fixed

**Comment by vikiival** [comment]
Looks oki on iPad

**Comment by vikiival** [comment]
image

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
image

**Comment by vikiival** [comment]
pay 10 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $10 @ 33.7 USD/KSM ~ 0.297 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x62cf393fcea64a4e6f822f8d958482765b7fc1e8dcb2c5b49b8a0ba5f33b8ab7](https://kusama.subscan.io/extrinsic/0x62cf393fcea64a4e6f822f8d958482765b7fc1e8dcb2c5b49b8a0ba5f33b8ab7)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by VladoTheBoi** [comment]
Not really sure if its fixed. I can still see the black space under the footer :/ 
Screenshot 2023-04-03 at 11 58 06

**Comment by vikiival** [comment]
Vlad have you checked https://canary.kodadot.xyz/bsx/create/ ?

**Comment by VladoTheBoi** [comment]
Ohh my bad, I've checked these 2:
- https://kodadot.xyz/
- https://beta.kodadot.xyz/bsx/create 

I wasnt sure about the new domains. So how exactly to understand the new ones?

**Pull request merged**
