### PR TITLE
fast stats

### PR DESCRIPTION
**Pull request by vikiival**
- :alien: added api for cached series insight
- :zap: Series Table is using cached data instead of resolvers
- :zap: spotlight table is using cached queries

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [ ] PR closes #<issue_number>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### CODE REVIEW

**Comment by yangwao** [comment]
when click on floor price

image

```json
{
    "errors": [
        {
            "message": "Variable \"$orderBy\" got invalid value \"floor_price_DESC\"; Value \"floor_price_DESC\" does not exist in \"SeriesOrderByInput\" enum. Did you mean the enum value \"floorPrice_DESC\", \"floorPrice_ASC\", or \"averagePrice_DESC\"?",
            "extensions": {
                "code": "BAD_USER_INPUT",
                "exception": {
                    "stacktrace": [
                        "GraphQLError: Variable \"$orderBy\" got invalid value \"floor_price_DESC\"; Value \"floor_price_DESC\" does not exist in \"SeriesOrderByInput\" enum. Did you mean the enum value \"floorPrice_DESC\", \"floorPrice_ASC\", or \"averagePrice_DESC\"?",
                        "    at /squid/node_modules/graphql/execution/values.js:116:15",
                        "    at coerceInputValueImpl (/squid/node_modules/graphql/utilities/coerceInputValue.js:131:9)",
                        "    at coerceInputValue (/squid/node_modules/graphql/utilities/coerceInputValue.js:37:10)",
                        "    at _loop (/squid/node_modules/graphql/execution/values.js:109:69)",
                        "    at coerceVariableValues (/squid/node_modules/graphql/execution/values.js:121:16)",
                        "    at getVariableValues (/squid/node_modules/graphql/execution/values.js:50:19)",
                        "    at buildExecutionContext (/squid/node_modules/graphql/execution/execute.js:203:61)",
                        "    at executeImpl (/squid/node_modules/graphql/execution/execute.js:101:20)",
                        "    at execute (/squid/node_modules/graphql/execution/execute.js:60:35)",
                        "    at execute (/squid/node_modules/apollo-server-core/dist/requestPipeline.js:205:48)"
                    ]
                }
            }
        }
    ]
}
```

**Comment by yangwao** [comment]
spotlight unique collection
```json
{
    "errors": [
        {
            "message": "Variable \"$orderBy\" got invalid value \"unique_collectors_DESC\"; Value \"unique_collectors_DESC\" does not exist in \"SpotlightOrderByInput\" enum. Did you mean the enum value \"uniqueCollectors_DESC\", \"uniqueCollectors_ASC\", or \"collections_DESC\"?",
            "extensions": {
                "code": "BAD_USER_INPUT",
                "exception": {
                    "stacktrace": [
                        "GraphQLError: Variable \"$orderBy\" got invalid value \"unique_collectors_DESC\"; Value \"unique_collectors_DESC\" does not exist in \"SpotlightOrderByInput\" enum. Did you mean the enum value \"uniqueCollectors_DESC\", \"uniqueCollectors_ASC\", or \"collections_DESC\"?",
                        "    at /squid/node_modules/graphql/execution/values.js:116:15",
                        "    at coerceInputValueImpl (/squid/node_modules/graphql/utilities/coerceInputValue.js:131:9)",
                        "    at coerceInputValue (/squid/node_modules/graphql/utilities/coerceInputValue.js:37:10)",
                        "    at _loop (/squid/node_modules/graphql/execution/values.js:109:69)",
                        "    at coerceVariableValues (/squid/node_modules/graphql/execution/values.js:121:16)",
                        "    at getVariableValues (/squid/node_modules/graphql/execution/values.js:50:19)",
                        "    at buildExecutionContext (/squid/node_modules/graphql/execution/execute.js:203:61)",
                        "    at executeImpl (/squid/node_modules/graphql/execution/execute.js:101:20)",
                        "    at execute (/squid/node_modules/graphql/execution/execute.js:60:35)",
                        "    at execute (/squid/node_modules/apollo-server-core/dist/requestPipeline.js:205:48)"
                    ]
                }
            }
        }
    ]
}```

**Comment by roiLeo** [comment]
👀 something new here

**Comment by vikiival** [comment]
Secret perks of rubick v005 🤫

**Pull request merged**
