### PR TITLE
fix: init modal migration from buefy to oruga

### LINKED ISSUE #6277: Programmatic Modal
## Specs
- replace [Buefy Programmatic Modal](https://buefy.org/documentation/modal/#programmatic) with Oruga [equivalent](https://oruga.io/components/modal.html)
- close all opened modals when one is opened

### PR DESCRIPTION
**Pull request by dxphilo**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Part of https://github.com/kodadot/nft-gallery/issues/5852

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [ ] Closes #6277
- [ ] Requires deployment <snek/rubick/worker>

Bumped into some errors while configuring Oruga. Still investigating. Might be compatibility issues

Screenshot 2023-08-08 at 13 02 27

#### Before submitting pull request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [ ] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at ae3eed4</samp>

This pull request mainly replaces the buefy modal components with the oruga modal components in various files, as part of a UI library refactoring. It also changes some props to use kebab-case instead of camelCase, as suggested by the Vue style guide. Additionally, it reorders some imports to follow the alphabetical order, as suggested by the TypeScript style guide.

### <samp>🤖 Generated by Copilot at ae3eed4</samp>

> _`buefy` to `oruga`_
> _kebab-case for props and imports_
> _a fresh spring cleaning_

### CODE REVIEW

**Comment by dxphilo** [comment]
It appears that these errors might be somehow connected to https://github.com/kodadot/nft-gallery/pull/6610. Isn't that the case, @roiLeo?

**Comment by roiLeo** [comment]
> It appears that these errors might be somehow connected to #6610. Isn't that the case, @roiLeo?

Yes, not possible to use oruga-next with nuxt-bridge (vue2) project. have you tried with oruga instead of oruga-next?

**Comment by dxphilo** [comment]
> > It appears that these errors might be somehow connected to #6610. Isn't that the case, @roiLeo?
> 
> Yes, not possible to use oruga-next with nuxt-bridge (vue2) project. have you tried with oruga instead of oruga-next?

Not yet, I can try it out and see what works here.

**Comment by roiLeo** [comment]
> Not yet, I can try it out and see what works here.

I don't think this is a good idea we'll still need to upgrade to Vue3 version..

**Comment by dxphilo** [comment]
I'll close this for now.

**Pull request closed without merging**
