### PR TITLE
fix: 5103 add back mintnft activity

### LINKED ISSUE #5103: missing `MINT` event in Activity table
In gallery Item details we don't have `MINT` event anymore 

Tested on BSX & RMRK
Screenshot 2023-02-23 at 09-51-51 KodaDot - NFT Market Explorer

### PR DESCRIPTION
**Pull request by maderi21**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5103 
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [x] I've tested it at </bsx/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=JHJGu2aWyAFBfcso8bR7ma82p15YAavyN6vQfJyWuhniNGa)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

### CODE REVIEW

**Comment by Jarsen136** [comment]
It's related with https://github.com/kodadot/nft-gallery/pull/5028
 I'm thinking if we should hide `mint` and `burns` on the tabs of activity on rmrk2. WDYT @roiLeo 

tested on: https://deploy-preview-5104--koda-nuxt.netlify.app/rmrk2/gallery/16759320-8453d0ccb4cb7e9e59-A51-THE_FOUNDRY-00000246?page=1

image

**Comment by roiLeo** [comment]
> It's related with #5028 I'm thinking if we should hide `mint` and `burns` on the tabs of activity on rmrk2. WDYT @roiLeo

Why? I find it important to have information of the mint date.
more or less the same thing for burn

**Comment by maderi21** [comment]
> > It's related with #5028 I'm thinking if we should hide `mint` and `burns` on the tabs of activity on rmrk2. WDYT @roiLeo
> 
> Why? I find it important to have information of the mint date. more or less the same thing for burn

why was it hidden on rmrk2?

**Comment by Jarsen136** [comment]
> > It's related with #5028 I'm thinking if we should hide `mint` and `burns` on the tabs of activity on rmrk2. WDYT @roiLeo
> 
> Why? I find it important to have information of the mint date. more or less the same thing for burn

@vikiival may tell us if we could have the mint and burns information on rmrk2.

related changes:
image

**Comment by roiLeo** [comment]
> why was it hidden on rmrk2?

I think it's because interaction changed on rmrk2 compared to v1
`MINTNFT => MINT`
`CONSUME => BURN`

**Comment by maderi21** [comment]
> > why was it hidden on rmrk2?
> 
> I think it's because interaction changed on rmrk2 compared to v1 `MINTNFT => MINT` `CONSUME => BURN`

I've checked the indexer and currently, I don't think there are burn events indexed?
image

Mints are present however, maybe let's create a new issue for handling of the newly named events in gallery item? I can work on it. wdyt @Jarsen136 @roiLeo

**Comment by roiLeo** [comment]
> I've checked the indexer and currently, I don't think there are burn events indexed?

This indexer is still in beta some of the features are not correctly implemented. 
Like `BURN` event isn't handled yet.

**Comment by maderi21** [comment]
what should be done here to move this forward ? 🤔 are we hiding the tabs for rmrk2? or altering it somehow else ?

**Comment by maderi21** [comment]
👀 @vikiival

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 37.45 USD/KSM ~ 0.801 $KSM
🧗 [JHJGu2aWyAFBfcso8bR7ma82p15YAavyN6vQfJyWuhniNGa](https://kusama.subscan.io/account/JHJGu2aWyAFBfcso8bR7ma82p15YAavyN6vQfJyWuhniNGa)
🔗 [0x2140c978ce363ebeb725895990cfb28492cc1961acde8b2aec3a22bd8b431f01](https://kusama.subscan.io/extrinsic/0x2140c978ce363ebeb725895990cfb28492cc1961acde8b2aec3a22bd8b431f01)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
