### PR TITLE
Feat: Add Support for keyboard shortcuts

### LINKED ISSUE #1783: Add keyboard shortcuts
We want to control kodadot with keyboard shortcuts for much pleasant and faster browsing

- g n - go to next page on gallery/collections/collections detail
- g p - go to the previous page on gallery/collections/collections detail
- g a - go-to own artist profile
- g c - go to your collected items
- g s - go to your sold items 
- g m - go-to simple mint
- g t - go to transfer
- g i - go to series insights
- g d - go to creators directory 
- g r - go to the random page at a particular view 

#### on item detail
- e p - expand price chart
- e h - expand history chart
- e d - expand the description

#### filter toggle on gallery/collection view
- f b - filter buy now
- f n - filter new first
- f e - filter expensive first
- f c - filter cheap one

#### actions
- a b - buy the item
- a s - send the item
- a c - consume
- a l - list

### probably everywhere
- c c - copy current URL where is used to clipboard and show notification about that

Add a way to recall this manual for shortcuts like overlay, check gmail and smash shift / 

### Ref
- #349 
- ref gmail https://support.google.com/mail/answer/6594?hl=en

### PR DESCRIPTION
**Pull request by chandradot99**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Do a quick check before the merge.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #1783 
- [ ] Added support for keyboard shortcuts

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases

### Had issue bounty label ?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=CeBWgisygADqqxGk7ju8aMNEKz1K2WkxMKC3G8HsMnm119n)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI, a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by chandradot99** [comment]
@yangwao @vikiival there are still some keyboard shortcuts which needs to be mapped, but first need to confirm if this is the correct way to implement this feature.

**Comment by yangwao** [comment]
- need to handle when the user is not logged in

image

- Some actually did not work for me.
- Missing explanation board, how I would trigger it?
 
I guess as first hacky implementation would be okayish 
We can improve on code quality later:)

**Comment by chandradot99** [comment]
@yangwao should I add new tab under settings page to show all keyboard shortcuts.

**Comment by yangwao** [comment]
> @yangwao should I add new tab under settings page to show all keyboard shortcuts.

yup for now it's good I guess

**Comment by chandradot99** [comment]
@yangwao I am done with the changes, also added keyboard shortcuts tab in settings page https://deploy-preview-2097--koda-nuxt.netlify.app/settings?tab=keyboardShortcuts

One thing which I am not aware of is the (g + d) shortcut, which needs to be mapped to creators directory, so can you tell me where do we have this page in our application.

**Comment by yangwao** [comment]
> One thing which I am not aware of is the (g + d) shortcut, which needs to be mapped to creators directory, so can you tell me where do we have this page in our application.

ah, that's Spotlight now https://kodadot.xyz/spotlight

**Comment by chandradot99** [comment]
ok @yangwao I will add that also.

**Comment by chandradot99** [comment]
@yangwao all of the required changes are done in this PR, can you check and let me know if something is missing. If everything works fine, then can we merge this PR.

**Comment by yangwao** [comment]
I would swap in the manual, shortcut column first, will test later 

image

**Comment by yangwao** [comment]
@chandradot99 let's reflect changes so we are not hanging too long as future conflicts might arise! :)

**Comment by yangwao** [comment]
Perfect, test most of it, buying worked as well, really delighted tho!

pay 300 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $300 @ 192.37 USD/KSM ~ 1.559 $KSM
🧗 [CeBWgisygADqqxGk7ju8aMNEKz1K2WkxMKC3G8HsMnm119n](https://kusama.subscan.io/account/CeBWgisygADqqxGk7ju8aMNEKz1K2WkxMKC3G8HsMnm119n)
🔗 [0x4b37dce5adf5ff4f7642a85c2f5d2b2c23ebbe6597198025df9a43c6d2bc889a](https://kusama.subscan.io/extrinsic/0x4b37dce5adf5ff4f7642a85c2f5d2b2c23ebbe6597198025df9a43c6d2bc889a)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
I've made follow up issue as well tho if you are interested continue on this! 

https://github.com/kodadot/nft-gallery/issues/2283

**Pull request merged**
