### PR TITLE
#2738 Hiding the burned nfts

### LINKED ISSUE #2738: Hunting the burned once
### What happened?

Viki was like: let me try Darshana's PR on this fish

Screenshot 2022-04-01 at 16 25 47

Fish is burned
Screenshot 2022-04-01 at 16 25 37

Task is:
- Go through app
- check where we can find this edgecases - (burned should not be visible on any list page)
- fix the queries

### Please reproduce in steps

🔥 

### Expected Behavior

I've expected see only existing NFTs on the app

### What browsers are you seeing the problem on?

Chrome

### Are you logged in?

No

### At which address did you encounter bug?

kodadot.xyz

### Screenshots

Paste from your clipboard or upload screenshots/video

### Relevant log output

_No response_

### Payment link for reward

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #2738

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Angler fish is gone  😆
Screenshot 2022-04-01 at 9 02 17 PM

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
lgtm

**Comment by vikiival** [comment]
My only concern is if this is done ? 


Screenshot 2022-04-04 at 11 22 30

**Comment by prachi00** [comment]
> My only concern is if this is done ?
> 
> Screenshot 2022-04-04 at 11 22 30

@vikiival checked the apis for the landing pages, gallery, collection seems fine

**Comment by prachi00** [comment]
> and profile?

@vikiival just checked, the apis have the burned check there so seems fine

**Comment by roiLeo** [comment]
I think it's missing in `allCollectionSaleEvents` and maybe Spotlight/Series not sure about this one got different numbers between singulare & kodadot

**Comment by prachi00** [comment]
> allCollectionSaleEvents

checking

**Comment by prachi00** [comment]
Added in allCollectionSaleEvents

**Comment by prachi00** [comment]
can we add burned check in spotlight and series? checked the query but could not figure out @roiLeo @vikiival

**Comment by roiLeo** [comment]
> can we add burned check in spotlight and series? checked the `spotlight` query but could not figure out since no filter param is supported @roiLeo @vikiival

I don't know if this is possible with the current resolver but it can be fixed by modifying the basic query, could be related with https://github.com/kodadot/rubick/issues/39

**Comment by prachi00** [comment]
> > can we add burned check in spotlight and series? checked the `spotlight` query but could not figure out since no filter param is supported @roiLeo @vikiival
> 
> I don't know if this is possible with the current resolver but it can be fixed by modifying the basic query, could be related with [kodadot/rubick#39](https://github.com/kodadot/rubick/issues/39)

ok so maybe we can make another issue for this one?

**Comment by yangwao** [comment]
> > > can we add burned check in spotlight and series? checked the `spotlight` query but could not figure out since no filter param is supported @roiLeo @vikiival
> > 
> > 
> > I don't know if this is possible with the current resolver but it can be fixed by modifying the basic query, could be related with [kodadot/rubick#39](https://github.com/kodadot/rubick/issues/39)
> 
> ok so maybe we can make another issue for this one?

sure, create follow up issue what's is missing :)

**Comment by vikiival** [comment]
https://github.com/kodadot/rubick/issues/47

**Comment by prachi00** [comment]
@vikiival this can be merged now right?

**Comment by vikiival** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 185.23 USD/KSM ~ 0.27 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0xadb76f0dab3dd9bd012d50962c6d30bb62011ee340ddc04d6c00dc10c4233be6](https://kusama.subscan.io/extrinsic/0xadb76f0dab3dd9bd012d50962c6d30bb62011ee340ddc04d6c00dc10c4233be6)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
