### PR TITLE
✨ hotfix display top collection

### PR DESCRIPTION
**Pull request by roiLeo**
### PR type

- [x] Bugfix

### What's new?

- [x] TopCollection component is hidden on beta (new landing)

### CODE REVIEW

**Comment by roiLeo** [comment]
`collectionsBuyNow` test failing?

**Review by Jarsen136 — APPROVED** [review]
code lgtm

**Review by petersopko — APPROVED** [review]
wfm

**Comment by petersopko** [comment]
> `collectionsBuyNow` test failing?

I assume rerun worked

**Pull request merged**
