### PR TITLE
fix: Enable RMRK2 on production - kodadot.xyz

### LINKED ISSUE #5887: Enable RMRK2 on production - kodadot.xyz
We've decided to enable rmrk2 on all domains, so it should work on 
- canary.kodadot.xyz
- beta.kodadot.xyz
- kodadot.xyz

Looking for PR enabling this :)

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5887
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at 4b2b892</samp>

Simplified the logic for filtering out chains based on the environment in `utils/chain.ts`. Removed the unused `disableChainListOnProductionEnv` variable and condition.

### <samp>🤖 Generated by Copilot at 4b2b892</samp>

> _`disableChainList`_
> _gone, only one check remains_
> _code is simpler now_

### CODE REVIEW

**Comment by yangwao** [comment]
and can we set it as default? 

so when someone opens kodadot.xyz it will switch them to rmrk2 :)

thanks!

**Comment by Jarsen136** [comment]
> and can we set it as default?
> 
> so when someone opens kodadot.xyz it will switch them to rmrk2 :)
> 
> thanks!

✅ Done

**Review by roiLeo — APPROVED** [review]

**Comment by yangwao** [comment]
pay 20 usd

let's go

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 25.58 USD/KSM ~ 0.782 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x58b3001232d498cbeaac1f53a86c5e2bb7c9d850757dab8c505a27f5e088893c](https://kusama.subscan.io/extrinsic/0x58b3001232d498cbeaac1f53a86c5e2bb7c9d850757dab8c505a27f5e088893c)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
