### PR TITLE
feat: Redesign scroll up button

### LINKED ISSUE #4204: Redesign scroll up button
I guess it's a small component, but it's really cutting my eyes now having round stuff 😅

Once @exezbcz provide the design, we can start working on that :)

https://beta.kodadot.xyz/bsx/explore/?page=2
image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #4204
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image
image

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
✅ lgtm

To go further:
- this component can bo written with [histoire](https://histoire.dev/) & Nuxt3 way
- is it normal that we don't have the same hover state as footer button?

**Comment by Jarsen136** [comment]
> * is it normal that we don't have the same hover state as footer button?

✅ FIXED

**Comment by yangwao** [comment]
pay 50 
love it

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 34.14 USD/KSM ~ 1.465 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x58f705967b5bd278891c5673dc508112f90c07d4c95f120e8369cc226f4ecd26](https://kusama.subscan.io/extrinsic/0x58f705967b5bd278891c5673dc508112f90c07d4c95f120e8369cc226f4ecd26)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
