### PR TITLE
fix: redirection when listed=true

### LINKED ISSUE #5573: weird redirection from collection to explorer?
click on this link should land you on KUBOTs collection I guess

https://canary.kodadot.xyz/rmrk2/collection/daf9e25824d4bd9357-KUBOTS?page=1&listed=true

EDIT

this one works

https://canary.kodadot.xyz/rmrk2/collection/daf9e25824d4bd9357-KUBOTS?page=1

https://user-images.githubusercontent.com/5887929/230783724-5fe9b9a8-a9e5-4463-a385-e35129179bfa.mp4

---
could be this because of this ?
- https://github.com/kodadot/nft-gallery/pull/5472/files#diff-613782391289f244ec818f03a518d8278d5125e276730817f2e23106506b283cR43

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5573

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
I would change order of condition to avoid negative check on ternary

otherwise ✅ code lgtm

**Review by Jarsen136 — CHANGES_REQUESTED** [review]
This change would introduce a new bug. It will redirect you to item explore when you search something on collection tab.
Kapture 2023-04-12 at 00 14 10

Posible solution:
- extend the range of `isExplorePage` to more cases.

**Review by roiLeo — APPROVED** [review]
✅ wfm

Screenshot 2023-04-12 at 10-16-26 kittys KodaDot - NFT Market Explorer

**Comment by yangwao** [comment]
> Do we need to add this feature? If so, how should users conduct searches on the collection page? Would they use the search bar at the top?

- https://github.com/kodadot/nft-gallery/issues/5333

**Comment by Jarsen136** [comment]
> > This change would introduce a new bug. It will redirect you to item explore when you search something on collection tab
> 
> how about now, I changed it to this `path: this.$route.path` only. seems like the redirection is already handled by `redirectToGalleryPageIfNeed()`

wfm

**Review by Jarsen136 — APPROVED** [review]

**Comment by yangwao** [comment]
works 

image

**Pull request merged**
