### PR TITLE
Sometimes after fog, comes sunny day.

### PR DESCRIPTION
**Pull request by yangwao**
#654 
#663 
#661

### CODE REVIEW

**Comment by AndreyGrin** [comment]
Where could I preview changes?

**Comment by vikiival** [comment]
It's already merged so https://nft.kodadot.xyz

**Comment by AndreyGrin** [comment]
hm.. don't see my changes there :/

**Comment by yangwao** [comment]
oh seems failed builds, we will check on that! you will probably redeploy or let you know on discord:)
image

**Pull request merged**
