### PR TITLE
feat: show animationUrl on carousel items

### LINKED ISSUE #2919: Display animated nft in carousel
I would like to display animated nft (video, 3d file...) when there isn't `meta.image` available.

Components:
- NewestList.vue
- LatestSales.vue
- GalleryItemCarousel.vue

Something should be done in `handleResult` method to attach `e.nft.meta.animation_url` to nfts data.

#### Screenshot
Capture d’écran 2022-04-29 à 11 13 20 AM
Capture d’écran 2022-04-29 à 11 21 10 AM

#### Step to reproduce
- sometimes showing placeholder on landing page
or
- go to `/rmrk/gallery/11452166-629a449743cd29bf21-3DGINO-SUBSTRA_PLANE_WORLD_WAR_1_EDITION-0000000000000043` and check "More From This Collection"

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

Screenshot 2022-04-29 at 17 33 24

### What's new?

- [x] PR closes #2919
- [x] add animationUrl to graphql request & implement PreviewMediaResolver in CarouselItem

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/gallery/11452166-629a449743cd29bf21-3DGINO-SUBSTRA_PLANE_WORLD_WAR_1_EDITION-0000000000000043>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by roiLeo — CHANGES_REQUESTED** [review]
Capture d’écran 2022-05-02 à 8 18 18 AM

Some data is not loading, check out:
https://deploy-preview-2924--koda-nuxt.netlify.app/rmrk/collection/629a449743cd29bf21-3DGINO?page=1


vs

https://beta.kodadot.xyz/rmrk/collection/629a449743cd29bf21-3DGINO?page=1

**Comment by kkukelka** [comment]
> Some data is not loading
@roiLeo 
hmm could you pls recheck, I couldn't reproduce your problem. works on deploy-preview and also locally for me 
Screenshot 2022-05-02 at 18 25 59

it looks like your view is kinda bugged in the picture you posted, as it should either show kodadot previewimage or poster image of nft if available + loading indicator bar on the top

**Comment by roiLeo** [comment]
Cleared cache on Firefox: still not working
Capture d’écran 2022-05-02 à 7 26 01 PM

Tested on chrome and it's showing well
Capture d’écran 2022-05-02 à 7 30 50 PM

we might found another bug.
infinite scroll isn't working on firefox nor chrome (it show max 8 items)

**Comment by roiLeo** [comment]
Tested on https://deploy-preview-2924--koda-nuxt.netlify.app/rmrk/collection/7cf9daa38281a57331-BSS?page=1 and it's working

Capture d’écran 2022-05-03 à 9 10 25 AM

but on https://deploy-preview-2924--koda-nuxt.netlify.app/rmrk/collection/629a449743cd29bf21-3DGINO?page=1 I can't even see the pagination

wut?

**Comment by kkukelka** [comment]
> Tested on https://deploy-preview-2924--koda-nuxt.netlify.app/rmrk/collection/7cf9daa38281a57331-BSS?page=1 and it's working
> 
> Capture d’écran 2022-05-03 à 9 10 25 AM
> 
> but on https://deploy-preview-2924--koda-nuxt.netlify.app/rmrk/collection/629a449743cd29bf21-3DGINO?page=1 I can't even see the pagination
> 
> wut?

👀  uff, ill have to check that in the evening. no idea whats going on there

**Comment by kkukelka** [comment]
@roiLeo i guess it doesnt show no pagination because the collection only has 16 items and we show 16 items per page
https://deploy-preview-2924--koda-nuxt.netlify.app/rmrk/collection/629a449743cd29bf21-3DGINO?page=1

**Review by roiLeo — APPROVED** [review]
I've tested it locally + I had a second check let's see how it will go on beta

**Comment by roiLeo** [comment]
pay 100

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 141.35 USD/KSM ~ 0.707 $KSM
🧗 [EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW](https://kusama.subscan.io/account/EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)
🔗 [0xcb21180c72e32ed1c587d8d1a502232f0c4af5e8d9c3bb3af8567cea2e900963](https://kusama.subscan.io/extrinsic/0xcb21180c72e32ed1c587d8d1a502232f0c4af5e8d9c3bb3af8567cea2e900963)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
