### PR TITLE
💅 sort by volume DESC

### LINKED ISSUE #5678: Sort collections by volume
I heard @Matehoo knows more 👀

image

### PR DESCRIPTION
**Pull request by roiLeo**
Capture d’écran 2023-12-15 à 10 08 48 AM

- closes #5678

### CODE REVIEW

**Review by vikiival — APPROVED** [review]

**Comment by prury** [comment]
a wild waifu appears: 

dot
image

kusama: 

image

**Comment by roiLeo** [comment]
`volume` is string 😭

**Comment by roiLeo** [comment]
> `volume` is string 😭

I legit don't know why these unique collection are showing
Capture d’écran 2023-12-15 à 2 16 54 PM
I'll investigate

**Comment by vikiival** [comment]
> volume is string 😭

Please if you have some type update either kodadot/stick or kodadot/loligo is a good start .

**Comment by roiLeo** [comment]
> I I'll investigate

- indexer issue, will be fixed by kodadot/stick#163

**Review by preschian — APPROVED** [review]

**Comment by roiLeo** [comment]
I'll merge it for now

**Pull request merged**
