### PR TITLE
:fire: green glow begone!

### LINKED ISSUE #4422: Remove green glow
Hi! there is weird glow on the nft cards - it indicates that you are the owner. 
Can we remove it? 
image

### PR DESCRIPTION
**Pull request by petersopko**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Closes #4422
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [x] I've tested it at </bsx/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y)
#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

My NFT on BSX: 
image

### CODE REVIEW

**Review by Jarsen136 — APPROVED** [review]
code lgtm

**Comment by vikiival** [comment]
Hey, maybe check if the code is not repeated on other components?

Otherwise LGTM

**Comment by petersopko** [comment]
> Hey, maybe check if the code is not repeated on other components?
> 
> Otherwise LGTM

I didn't find any other places where it was used, I think it's okay like this.

**Comment by yangwao** [comment]
pay 30

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 28.15 USD/KSM ~ 1.066 $KSM
🧗 [FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y](https://kusama.subscan.io/account/FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y)
🔗 [0xbb32555b11c0502b538971cdc843bd322bc317fa22aa1010a987920d8e7af809](https://kusama.subscan.io/extrinsic/0xbb32555b11c0502b538971cdc843bd322bc317fa22aa1010a987920d8e7af809)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
