### PR TITLE
File import not working in massmint

### LINKED ISSUE #6532: File import not working in massmint
image
tried importing this zip: 

[export quire.zip](https://github.com/kodadot/nft-gallery/files/12259691/export.quire.zip)

It appears to me that the import does not work when compressing grouped file - tried only compressing the items inside without them being in a group, and it works 
- this one works
[Archive.zip](https://github.com/kodadot/nft-gallery/files/12259711/Archive.zip)

### PR DESCRIPTION
**Pull request by hassnian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

Images nested inside a folder are ignored this pr fixes that 

This first zip has the images nested inside a folder 
[nested images.zip](https://github.com/kodadot/nft-gallery/files/12259691/export.quire.zip)

this one they are not 
[just images.zip](https://github.com/kodadot/nft-gallery/files/12259711/Archive.zip)

- [x] Closes #6532
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

zip with nested folder
CleanShot 2023-08-06 at 07 40 35

zip with just images
CleanShot 2023-08-06 at 07 42 30

### <samp>🤖 Generated by Copilot at 1281dab</samp>

Simplified the warning condition for zip file entries in `useZipValidator.ts` to improve readability and avoid false positives.

### <samp>🤖 Generated by Copilot at 1281dab</samp>

> _`isDirectory` /_
> _No need for slash check now /_
> _Code is simpler - spring_

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
✅ code lgtm

**Comment by prury** [comment]
work wonders, good job!

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 4.98 USD/DOT ~ 10.04 $DOT
🧗 [16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD](https://polkadot.subscan.io/account/16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)
🔗 [0xd0d2a7a2912629b65b546496f3e12ec44d80888a818fe86e09206d63b903985a](https://polkadot.subscan.io/extrinsic/0xd0d2a7a2912629b65b546496f3e12ec44d80888a818fe86e09206d63b903985a)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
