### PR TITLE
Vercel previews support for collections and svg type

### PR DESCRIPTION
**Pull request by AndreyGrin**
#973 support for animated SVG previews
Collections page Vercel preview with amount of collection's item

### CODE REVIEW

**Comment by AndreyGrin** [comment]
what's best practise right now with `main-nuxt` branch?  do you want another PR with same changes to that branch as well?

**Comment by yangwao** [comment]
Thinking this would be good to have in both branches. 
in `main` and in `main-nuxt` as well. 
There should be recent stuff working for `main-nuxt` through https://beta.kodadot.xyz

**Comment by yangwao** [comment]
> what's best practise right now with `main-nuxt` branch? do you want another PR with same changes to that branch as well?

Ah I've re-read it, yes, that would be more than welcome! :)

**Comment by yangwao** [comment]
Testing it 
https://deploy-preview-1159--nftkodadot.netlify.app/rmrk/detail/9948415-900D19DC7D3C444E4C-EXCANARY-EXPECT_CANARY_10-0000000000000010

image

On these did not yield any result
- https://deploy-preview-1159--nftkodadot.netlify.app/rmrk/detail/9855896-900D19DC7D3C444E4C-CHALINES1-CHAOS_LINES_VOL.1-0000000000000002
- https://deploy-preview-1159--nftkodadot.netlify.app/rmrk/detail/9809826-900D19DC7D3C444E4C-TRIACANAR-TRIANGULAR_CANARY_4-0000000000000002
- https://deploy-preview-1159--nftkodadot.netlify.app/rmrk/detail/9920932-900D19DC7D3C444E4C-GOLDENCUBE-THE_GOLDEN_CUBE_(COMMON_10)-0000000000000010

**Comment by AndreyGrin** [comment]
I think that ones might be cached. Checked with some other randoms 
https://og-image-green-seven.vercel.app/Expect%20Canary%20%2321.png?price=&image=https://kodadot.mypinata.cloud/ipfs/QmYEYGcv5CpunBe9PnpHbVTC1thqTrzkfCviygKdDg9j9S&mime=image/svg+xml
Yeah, I think they're cached.
https://og-image-green-seven.vercel.app/Chaos%20Lines%20vol.w1.png?price=0.1600%20KSM&image=https://kodadot.mypinata.cloud/ipfs/QmQ2K4gqVdxyixy5qagWFxFGZZ74kwW3aaDsYeatXA9PoH&mime=image/svg+xml
this one didn't work until I changed a name of the NFT in the url.
Can't purge that cache, unfortunately but I can check it, maybe something can be changed on Vercel side for this.

**Comment by AndreyGrin** [comment]
changed cache time to 1 month instead of 1 year

**Comment by vikiival** [comment]
> changed cache time to 1 month instead of 1 year

maybe let's put there one week / one day?

**Comment by AndriiHrynchuk** [comment]
Changed cache policy for SVG - 1 day, jpg/png - 1 year.

**Comment by yangwao** [comment]
> > changed cache time to 1 month instead of 1 year
> 
> maybe let's put there one week / one day?

Why one day? To warm up IPFS GWs? 😄 
A week should be enough. I mean in the end, we are caching immutable assets tho. 
Just right now a lot of SVGs are being cached tho with older cache

**Comment by yangwao** [comment]
Ah I see, this one plays if I change name https://og-image-green-seven.vercel.app/Chaos%20Lineees%20vol.w1.png?price=0.1600%20KSM&image=https://kodadot.mypinata.cloud/ipfs/QmQ2K4gqVdxyixy5qagWFxFGZZ74kwW3aaDsYeatXA9PoH&mime=image/svg+xml

**Comment by yangwao** [comment]
Let's merge it and see how it would work on production! :)
I'll DM you back tho!

**Pull request merged**
