### PR TITLE
🔧 owner calculation

### LINKED ISSUE #6242: activity owner tab shows wrong info
Take this collection for example: https://deploy-preview-6229--koda-canary.netlify.app/bsx/collection/3579963603/activity

it has some holders, one of them its: 
image

He bought it at the price of 1KSM, yet, it doesn't show it in the holders tab: 
image

Investigated because i was feeling strange that all KSM values on holders were 0

_Originally posted by @prury in https://github.com/kodadot/nft-gallery/issues/6229#issuecomment-1593615669_

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #6242 
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)

## Screenshot 📸

- [x] My fix has changed UI

image

image

### <samp>🤖 Generated by Copilot at 12e5b24</samp>

Improved the handling of nft ownership changes in `collectionActivity` composable. Refactored and fixed some helper functions in `helpers.ts` to make them more reliable and readable.

### <samp>🤖 Generated by Copilot at 12e5b24</samp>

> _Oh we're the coders of the sea, and we work with `nfts`_
> _We refactor and we fix, to make them all agree_
> _Heave away, me hearties, heave away with glee_
> _We simplify the logic in `collectionActivity/helpers.ts`_

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
✅ code lgtm

**Comment by prury** [comment]
working fine! 
image
image

**Review by Jarsen136 — APPROVED** [review]

**Comment by vikiival** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 4.64 USD/DOT ~ 6.466 $DOT
🧗 [1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8](https://polkadot.subscan.io/account/1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)
🔗 [0x699157e3a631b6dc1a659949c85207d7477f2586590f6d969eccc88e1b48d388](https://polkadot.subscan.io/extrinsic/0x699157e3a631b6dc1a659949c85207d7477f2586590f6d969eccc88e1b48d388)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
