### PR TITLE
renovate bot - unify minor and patch

### LINKED ISSUE #2835: Merge minor+patch updates for rennovate
would be nice to merge that renovate bumps in one PR minor+patch, why is it's split now?

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/pull/2831#issuecomment-1097127111_

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #2835  

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged the recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by preschian** [comment]
seems like a new version of `@google/model-viewer` is broken.
same on nextjs: https://codesandbox.io/s/determined-wozniak-0c688c?file=/components/Model.js

got this error when I try to import script as external script 
`<script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"></script>`
Screen Shot 2022-04-14 at 2 32 36 PM

**Comment by preschian** [comment]
updates:
- disable bump pinned deps
- use the range version for prettier
- pin `google/model-viewer` because the newer version seems broken (let me know if you guys have a concern)

results:
dashboard | bump
--- | ---
Screen Shot 2022-04-14 at 3 23 20 PM | Screen Shot 2022-04-14 at 3 23 33 PM

**Comment by yangwao** [comment]
> It seems like a new version of `@google/model-viewer` is broken (or need an additional bundler/loader). same on nextjs: [codesandbox.io/s/determined-wozniak-0c688c?file=/components/Model.js](https://codesandbox.io/s/determined-wozniak-0c688c?file=/components/Model.js) by changing the model-viewer to `1.10.1` looks fine
> 
> got this error when I try to import script as external script `<script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"></script>` Screen Shot 2022-04-14 at 2 32 36 PM
> 
> It will block renovate bot to update the other package. Should we pin this package also? the drawback is, we need to update manually for the pinned packages in the future if we want to upgrade pinned packages

yeah made issue on that https://github.com/kodadot/nft-gallery/issues/2852

**Comment by yangwao** [comment]
yeah let's merge it if it's passing
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 164.4 USD/KSM ~ 0.608 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0xb9ebb1a31af784d1d48085deaddebf8aa8c018390c24f1efa0ec384f516a6dde](https://kusama.subscan.io/extrinsic/0xb9ebb1a31af784d1d48085deaddebf8aa8c018390c24f1efa0ec384f516a6dde)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
