### PR TITLE
Netlify Deploy Button for Kodadot-app #1397

### LINKED ISSUE #1397: Create kodadot-app Netlify Deploy Button
Let's put stuff up to bring forking kodadot faster.
Be mindful of all environments if everything works well

- List KodaDot here https://templates.netlify.com/
- When deploy happen, make PR should be listed in #1171 

### Ref
- https://www.netlify.com/blog/2016/11/29/introducing-the-deploy-to-netlify-button/
- https://css-tricks.com/hack-the-deploy-to-netlify-button-using-environment-variables-to-make-a-customizable-site-generator/

### PR DESCRIPTION
**Pull request by AshutoshSingh00001**
Thank you for your contribution to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz/).

👇 __ Let's make a quick check before the contribution.

## PR Type
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #1397
- [x] ## Did your issue had any of the "$" label on it?
- [x] My DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=158VTDxZJidzsMcAdh7h828domveRvpmk1SCxwLUEHhcgY4v&usdamount=0&donation=true)

### CODE REVIEW

**Comment by AshutoshSingh00001** [comment]
@vikiival finally done

**Comment by AshutoshSingh00001** [comment]
Screenshot 2023-10-09 at 11 12 42 PM
@vikiival I finally made single commit pr

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
thanks for your contribution!

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $15 @ 3.85 USD/DOT ~ 3.896 $DOT
🧗 [158VTDxZJidzsMcAdh7h828domveRvpmk1SCxwLUEHhcgY4v](https://polkadot.subscan.io/account/158VTDxZJidzsMcAdh7h828domveRvpmk1SCxwLUEHhcgY4v)
🔗 [0xbf40faa841a861debbc382811340cc46903ac51f350e01b1a82b28039075f804](https://polkadot.subscan.io/extrinsic/0xbf40faa841a861debbc382811340cc46903ac51f350e01b1a82b28039075f804)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
