### PR TITLE
Adding Indonesia Language

### PR DESCRIPTION
**Pull request by magrisya**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [ ] PR closes #<issue_number>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [x] I found edge cases
- [x] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=GF4v68qJmh47eShYNpPs5JNfn5bxG5Kz1U2Y4xC2xAqXqmq)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
I think you'll need to edit file in `store/lang.ts` to add a new language

**Comment by yangwao** [comment]
add payout address and let me know when it's ready to merge. Best if someone from Indonesia could review this :)

**Comment by magrisya** [comment]
deploy-preview
deploy-preview2
deploy-preview3
ios
ios2
ios3
ios4

all goes well 

https://beta.kodadot.xyz/transfer/?target=GF4v68qJmh47eShYNpPs5JNfn5bxG5Kz1U2Y4xC2xAqXqmq

**Comment by magrisya** [comment]
> tambahkan alamat pembayaran dan beri tahu saya jika sudah siap untuk digabungkan. Lebih baik jika seseorang dari Indonesia dapat mengulas ini :)

https://beta.kodadot.xyz/transfer/?target=GF4v68qJmh47eShYNpPs5JNfn5bxG5Kz1U2Y4xC2xAqXqmq

do you have any suggestion someone to review this sir ❓

**Comment by yangwao** [comment]
> 

you need to put address into PR template at payout :)

**Comment by magrisya** [comment]
> > 
> 
> Anda harus memasukkan alamat ke dalam template PR saat pembayaran :)

already edited~ :heavy_dollar_sign:

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 138.53 USD/KSM ~ 0.722 $KSM
🧗 [GF4v68qJmh47eShYNpPs5JNfn5bxG5Kz1U2Y4xC2xAqXqmq](https://kusama.subscan.io/account/GF4v68qJmh47eShYNpPs5JNfn5bxG5Kz1U2Y4xC2xAqXqmq)
🔗 [0x9d2eeb9bd4f32b95bdefb9bff7f84025eb46473f3844c6107cb02613d85570a5](https://kusama.subscan.io/extrinsic/0x9d2eeb9bd4f32b95bdefb9bff7f84025eb46473f3844c6107cb02613d85570a5)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
@magrisya if you have twitter https://twitter.com/KodaDot/status/1498972701016395778 ;)

**Comment by ghifari444222** [comment]
hello, Indonesian here. I think You did a really good job with the word choice mate! But a really tiny improvement though, I think 'mengubah' should be 'ubah', judging from the word used in our english site :)

Thank You!

**Pull request merged**
