### PR TITLE
#5232 slider overflow

### LINKED ISSUE #5232: Carousel cards with new fluid container
it would be great if the next card that is not on screen would be more visible 
image

or we can remove it entirely (the coming card) - we have the arrows that are only visible if there is a next card, can you please tag me for the review if you would make it? Thanks!

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Closes #5232
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [ ] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screen Shot 2023-03-11 at 4 29 48 PM

### CODE REVIEW

**Comment by exezbcz** [comment]
works for me

**Comment by vikiival** [comment]
pay 9 usd

**Comment by prachi00** [comment]
@vikiival seems like the transaction failed

**Comment by prachi00** [comment]
@vikiival can we retry payment on this?

**Comment by yangwao** [comment]
pay 10 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $10 @ 5.05 USD/DOT ~ 1.98 $DOT
🧗 [13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1](https://polkadot.subscan.io/account/13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)
🔗 [0x5d0bfd7adfc4fbc4f28402032f8da81b0ae5ec71705d6855ed84652d7145d776](https://polkadot.subscan.io/extrinsic/0x5d0bfd7adfc4fbc4f28402032f8da81b0ae5ec71705d6855ed84652d7145d776)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
