### PR TITLE
fix: show migrate waiting section

### LINKED ISSUE #8189: Migration collection preview broken
### Is there an existing issue?

- [X] I have searched the existing issues

### What happened?

image

### Please reproduce in steps

https://canary.kodadot.xyz/migrate

### Expected Behavior

/

### What browsers are you seeing the problem on?

Desktop Chrome

### At which address did you encounter bug?

canary.kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

Kusama

### Screenshots

/

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/ksm/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #8196: Add migration to sidebar
image

- since migration is ready and close to being announced to public, we should add it to the sidebar 

The button will have a name "Migrate" 

more additions are coming, followup soon

### LINKED ISSUE #8197: Not possible to migrate
image

- this text is wrong no? The names mentioned in the copy are items from the collection 

Since you are not the owner you cannot initiate the migration - you are waiting for the collection to be migrated no? 

this is my only collection I have 
image

and my items 
image

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #8197
- [x] Closes #8196
- [x] Closes #8189

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)

## Screenshot 📸

- [ ] My fix has changed UI

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 2b36756</samp>

This pull request introduces a new feature for migrating NFTs to a new contract, refactors a component for reusability, and cleans up a localization file. It adds a menu item for the Migrate feature in `WalletAssetMenu.vue`, reuses the `Waiting.vue` component for different scenarios, and deletes obsolete and erroneous strings in `en.json`.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 2b36756</samp>

> _New menu item_
> _`Migrate` your NFTs with ease_
> _Spring cleaning `en.json`_

### CODE REVIEW

**Review by Jarsen136 — APPROVED** [review]

**Review by roiLeo — APPROVED** [review]

**Comment by exezbcz** [comment]
i dont think it solves the issue 


image

- now the waiting for your action is not correct. In the waiting for your action are items from collection, you don't own, but was migrated by the owner

for the bottom part, I will probably change the text a bit

**Review by daiagi — APPROVED** [review]

**Comment by vikiival** [comment]
> but was migrated by the owner


But the collection was migrated by owner.
Nfts have presignature for particular user. so if someone sells NFT on rmrk, new user won't be able to claim it

**Comment by exezbcz** [comment]
> But the collection was migrated by owner.

yes - collection was migrated by the owner 


you own some nfts from that collection - its waiting for your action to be migrated

is that correct? @vikiival ?

**Comment by vikiival** [comment]
> its waiting for your action to be migrated

Yes, you should claim the nfts (mind that you need balance on assethub)
and burn them on the old chain.

**Comment by preschian** [comment]
move the PR here https://github.com/kodadot/nft-gallery/pull/8280

**Pull request closed without merging**
