### PR TITLE
Fix img height bug

### LINKED ISSUE #8424: More from this collections - ultra vertical cards
https://canary.kodadot.xyz/ahk/gallery/291-2

image

### PR DESCRIPTION
**Pull request by shashkovdanil**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #8424 
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [x] I've tested it at </ksm/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer?target=16SpvdDgKNiQ3c53DxX7refnQcKUD3uRNim3Z1HBJLNGrtSP&usdamount=0)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 1f83ed7</samp>

Refactored `ImageMedia` component to use computed property for image classes and added debug log.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 1f83ed7</samp>

> _Refactor the image of doom_
> _Compute the class names in the gloom_
> _No more hard-coded template_
> _Log the debug to escape the fate_

### CODE REVIEW

**Comment by prury** [comment]
@shashkovdanil any method to reproduce the error?

**Comment by prury** [comment]
> @prury it will not be easy. You have to find carousel with a broken image. Now we have next system in images:
> 
>     1. Try to load image
> 
>     2. If error try again
> 
>     3. If again error use placeholder
> 
> 
> So you must find a carousel with an image that stops on the 2nd step. It's not easy because the data in the carousel changes frequently.
> 
> When I was testing it, it was https://kodadot.xyz/ahp/gallery/49-433 this item in carousel

i've blocked one of the urls via network tab 😎 

image

**Comment by yangwao** [comment]
> the one with 350 W

oh I noticed that one with error true!

**Review by roiLeo — APPROVED** [review]

**Review by vikiival — APPROVED** [review]
Let's try

**Comment by vikiival** [comment]
pay 10 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $10 @ 6.69 USD/DOT ~ 1.495 $DOT
🧗 [16SpvdDgKNiQ3c53DxX7refnQcKUD3uRNim3Z1HBJLNGrtSP](https://polkadot.subscan.io/account/16SpvdDgKNiQ3c53DxX7refnQcKUD3uRNim3Z1HBJLNGrtSP)
🔗 [0x4902bed2c49ce63f89b3678f0a6f1f8c82c5b9c8dec008dd65ff7279671d52e5](https://polkadot.subscan.io/extrinsic/0x4902bed2c49ce63f89b3678f0a6f1f8c82c5b9c8dec008dd65ff7279671d52e5)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
