### PR TITLE
🔧 vue 3 composition create pages

### PR DESCRIPTION
**Pull request by roiLeo**
- part of #4750 
- #6392 

<s>⚠️ need to test `/massmint` page</s>

edit: 
massmint tabs doesn't work on beta

### CODE REVIEW

**Comment by prury** [comment]
- **BSX:**
Massmint: 
https://basilisk.subscan.io/tx/0x7995a248086df736647cacad700991957c58fad546775592a16eb6a019e3c9d4
NFTs listed properly
redirection after minting working


- **RMRK2:**
creating a collection redirects to the NFT tab properly
massmint: 
image

**Review by daiagi — APPROVED** [review]
code lgtm

**Comment by prury** [comment]
**RMRK2**
Massmint: ✔️ 
mint: https://kusama.subscan.io/tx/0x54ef873876b94b72e1c73940bf579f9344065c58bf49d3bbf794a9ad1ab0e69e
listing: https://kusama.subscan.io/tx/0x6917fe3ba84973f209e9b714350268858ddc59ae82b5ae0be2bb4f505b734061
obs: asked for 2 transactions

Collection: https://kusama.subscan.io/tx/0xceada1d1fb90ef8c9ddc7f2b403883feb4e812ef5ed633cf9ff24639a673ef40
NFT: https://kusama.subscan.io/tx/0x71c325b27f413fe520e5e8348eab00280713f8f3120c5c3239396c4f5efeefec
https://kusama.subscan.io/tx/0x84622531c1750d5306e5598e3d15c420395fa0c4ef8ed47d2e1f4a53fbf0a7f5

**RMRK1**


**BSX**


**SNEK**


**STMN**

will be updating as i go

**Comment by roiLeo** [comment]
Hello, just so you know I didn't change anything related to minting process.
Only thing changed are pages redirection & tab related with url (`/:prefix/create/?tab=NFT` & `/:prefix/create/?tab=Collection`)

**Comment by vikiival** [comment]
Looks oki, 
let's fix the redirect and happy to proceed

**Review by vikiival — APPROVED** [review]

**Comment by roiLeo** [comment]
Wait does the redirection work for you? When I tested it on my side it was working as excepted (tab relates with URL path)

**Comment by prury** [comment]
> Wait does the redirection work for you? When I tested it on my side it was working as excepted (tab relates with URL path)

Oh, i got it now, yes , the tab redirection works properly for all of them. When testing i was testing both the tab redirection and the automatic redirection that happens after i mint something (this is what is not working)

**Comment by roiLeo** [comment]
> > Wait does the redirection work for you? When I tested it on my side it was working as excepted (tab relates with URL path)
> 
> Oh, i got it now, yes , the tab redirection works properly for all of them. When testing i was testing both the tab redirection and the automatic redirection that happens after i mint something (this is what is not working)
> 
> I may have got confused because i saw a timeout function 

Alright I'll be checking this next week

**Comment by prury** [comment]
> > > Wait does the redirection work for you? When I tested it on my side it was working as excepted (tab relates with URL path)
> > 
> > Oh, i got it now, yes , the tab redirection works properly for all of them. When testing i was testing both the tab redirection and the automatic redirection that happens after i mint something (this is what is not working)
> > 
> > I may have got confused because i saw a timeout function 
> 
> Alright I'll be checking this next week

Thank you for clarifying it for me

**Pull request merged**
