### PR TITLE
🚀 release new squid version

### PR DESCRIPTION
**Pull request by roiLeo**
may @prury check if data is good?

⚠️ don't merge this, will set indexer to production once tested

### CODE REVIEW

**Comment by roiLeo** [comment]
@yangwao blocked?

**Comment by prury** [comment]
@roiLeo it does solve the problem, I'm performing an overall check to see if there's any other problem

https://canary.kodadot.xyz/ahk/gallery/276-33
https://deploy-preview-8931--koda-canary.netlify.app/ahk/gallery/276-33

**Comment by roiLeo** [comment]
> @roiLeo it does solve the problem, I'm performing an overall check to see if there's any other problem

should solve #8675 & #8839 too

**Comment by prury** [comment]
> > @roiLeo it does solve the problem, I'm performing an overall check to see if there's any other problem
> 
> should solve #8675 & #8839 too

it does

**Comment by prury** [comment]
my brain feels like smashed potato today, but i found something: 

https://github.com/kodadot/nft-gallery/assets/36627808/fc3b3ff3-86c2-4666-9929-258c27abc022

**Comment by roiLeo** [comment]
> my brain feels like smashed potato today, but i found something:

yeah I think we removed royalties in kodadot/stick#161, idk how it will be handled after that

**Comment by vikiival** [comment]
We can revert them cc @yangwao

**Comment by yangwao** [comment]
Seems floor prices works well? 

image

**Comment by prury** [comment]
> Seems floor prices works well?

yes, but check comment about royalties https://github.com/kodadot/nft-gallery/pull/8931#issuecomment-1884776464

**Comment by vikiival** [comment]
> yes, but check comment about royalties

Royalties will be back
https://github.com/kodadot/stick/pull/183

**Comment by yangwao** [comment]
can it go with this release? 
cc @prury

**Comment by vikiival** [comment]
> can it go with this release?

Screenshot 2024-01-11 at 13 21 47

**Comment by prury** [comment]
> > yes, but check comment about royalties
> 
> Royalties will be back [kodadot/stick#183](https://github.com/kodadot/stick/pull/183)

nice, working!

**Comment by roiLeo** [comment]
> nice, working!

Thanks! closing it then

**Pull request closed without merging**
