### PR TITLE
refactor: add expiration date and filtering options to offers everywhere

### LINKED ISSUE #3567: add expiration date and filtering options to offers everywhere
There are two features / enhancements which I'd like to see added to **every offer table**. They are already added at some points, but not everywhere:

1. Filtering by offer status (currently being added here):
- https://github.com/kodadot/nft-gallery/pull/3564

2. Estimation of time to expiration of offer (added here):
- https://github.com/kodadot/nft-gallery/pull/3452

Currently we're showing offers at four points:
1. [user level](https://beta.kodadot.xyz/bsx/u/bXkVgiXLvvJAmUNni8huN9NZdjaxKGav9fSszhRXFeg6Xuvih?tab=offers&page=1)
2. [global stats level](https://beta.kodadot.xyz/bsx/stats)
3. [item level](https://beta.kodadot.xyz/bsx/gallery/1380208565-1)
4. [collection level](https://beta.kodadot.xyz/bsx/collection/1380208565?tab=offers&page=1)

Let's make sure each of those tables is providing information about expiration of offers as well as option to filter for desired Offer status.

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [x] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #3567
- [ ] Requires deployment <rubick/magick_issue>
- [x] bugfix: incorrect sorting of Expiration Date Column

image

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

image

### CODE REVIEW

**Review by petersopko — APPROVED** [review]
worked as expected, great :)

**Comment by petersopko** [comment]
One thing I've noticed at couple of places is that we don't have status of offer that would say `EXPIRED`, therefore all of the expired offers are whatever states they are in (expiration doesn't change status of Offer). @vikiival mentioned something like hook which could solve this, I'm opening up and issue and marking as research.

image

**Comment by JustLuuuu** [comment]
Created a new NFT to my collection - in Explore - I see my and all other NFTs with a price of 0. 
image
or even without the price: with the possibility only to make an offer:
image
The minimum offer was supposed to be 10 000 or more; I tried to make an offer and got error:
image

**Review by JustLuuuu — APPROVED** [review]
wfm

**Comment by Jarsen136** [comment]
This PR has merged something from #3572, so let's wait for #3572 to be merged first.

**Review by prachi00 — APPROVED** [review]

**Comment by prachi00** [comment]
pay 75 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $75 @ 65.34 USD/KSM ~ 1.148 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x28079d174b8a4ac45bdeff3a7b337cce252c809032a122543d6bdc560c44cfde](https://kusama.subscan.io/extrinsic/0x28079d174b8a4ac45bdeff3a7b337cce252c809032a122543d6bdc560c44cfde)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
