### PR TITLE
Refactor head() -> useHead()

### PR DESCRIPTION
**Pull request by nick-dev123**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [X] Refactoring

## Context

- [X] Related to #5314
- [X] Related to #7375
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [X] My contribution builds **clean without any errors or warnings**
- [X] I've merged recent default branch -- **main** and I've no conflicts
- [X] I've tried to respect high code quality standards
- [X] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [X] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=12ZLwasAvpdxDiiMedr11VeKUyQkY3WfneMkswBCAHVvxAqe)

#### Community participation

- [ ] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at 1ab8ce2</samp>

This pull request improves the accessibility, usability, and SEO of various components and pages by replacing unnecessary anchor tags with span tags, adding alt attributes to images, and using the useHead hook to set the head tags. It also refactors some code to simplify and remove redundancies. The files affected are `components/explore/FilterMenuButton.vue`, `components/gallery/GalleryItem.vue`, `components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue`, `pages/[prefix]/collection/[id]/activity.vue`, `components/collection/unlockable/UnlockableCollectionBanner.vue`, `components/gallery/GalleryItemDescription.vue`, `components/gallery/GalleryItemTabsPanel/GalleryItemActivity.vue`, `components/navbar/NotificationBoxButton.vue`, `components/rmrk/Gallery/Holder/Holder.vue`, `components/shared/collapse/CollapseCardWrapper.vue`, `components/shared/filters/MobileFilter.vue`, `components/shared/filters/modules/EventTypeFilter.vue`, `components/shared/filters/modules/PopularCollections.vue`, `components/shared/filters/modules/PriceFilter.vue`, `components/shared/filters/modules/StatusFilter.vue`, `pages/[prefix]/collection/[id]/index.vue`, `pages/[prefix]/create/collection.vue`, `pages/[prefix]/explore/collectibles.vue`, `pages/[prefix]/explore/items.vue`, and `pages/[prefix]/massmint/index.vue`.

### <samp>🤖 Generated by Copilot at 1ab8ce2</samp>

> _We're sailing on the web with `useHead` and `span`_
> _We're setting meta tags and links for every fan_
> _We're heaving on the ropes and making our code clean_
> _We're the best NFT crew that you have ever seen_

### CODE REVIEW

**Comment by nick-dev123** [comment]
Screenshot from 2023-09-28 00-11-33

Screenshot from 2023-09-27 23-56-46

**Review by roiLeo — COMMENTED** [review]
Hello, looks like you have some conflicts here.

initial issue is to replace `...this.$seoMeta`, I would do seo refactoring in a follow up PR.

**Comment by yangwao** [comment]
cc @nick-dev123 let's move this one forward

**Comment by roiLeo** [comment]
Hey I'm clossing this one since no change and to many conflicts.
Feel free to open a new PR.

**Pull request closed without merging**
