### PR TITLE
⚡️ Activity: lazy load owner insights

### LINKED ISSUE #5540: Super heavy loading on activity
there is pretty intense loading on some collection activity like this: https://canary.kodadot.xyz/rmrk2/collection/dac5c7f54029d0e73c-6AFVH/activity

items load fairly quickly but once you switch to activity, everything starts to be laggy
it has lot of items: 
image

ends with: 
image

### LINKED ISSUE #5574: Too much graphql calls on activity tab
seems when you open activity tab fires over 2k+ requests.

I guess we should lazy load queries on and embrace put them into Graphql and not like REST style to generate lot of requests 
- holders
- flippers
- activity

https://canary.kodadot.xyz/rmrk2/collection/daf9e25824d4bd9357-KUBOTS/activity

https://user-images.githubusercontent.com/5887929/230784234-186a2dfd-847a-4a2e-9811-d4ff19633679.mov

---
- #5540

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5574
- [x] Closes #5540
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by yangwao** [comment]
this was really quick load!
- https://deploy-preview-5608--koda-canary.netlify.app/ksm/collection/9ecdab6f55355b191a-GAMMA/activity
- https://deploy-preview-5608--koda-canary.netlify.app/ksm/collection/800f8a914281765a7d-KITTY/activity

- Quick too! https://deploy-preview-5608--koda-canary.netlify.app/ksm/collection/a2a383db29d7601e4b-TONICS/activity
image


- seems doesn't load :| https://deploy-preview-5608--koda-canary.netlify.app/ksm/collection/3208723ec6f65df810-ITEM?page=1
image

**Comment by daiagi** [comment]
https://deploy-preview-5608--koda-canary.netlify.app/ksm/collection/dac5c7f54029d0e73c-6AFVH/activity

Loaded for me. On mobile

It is too slow however
I'm not sure it can be farther improved until we have new schema

**Comment by vikiival** [comment]
>  I'm not sure it can be farther improved until we have new schema

Yup the issue was picked up

- https://github.com/kodadot/loligo/issues/10

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 33.27 USD/KSM ~ 1.503 $KSM
🧗 [EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L](https://kusama.subscan.io/account/EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L)
🔗 [0x1438d742c69daf0b18b0c1a68b6a8e71e80d6569292409b76c0fbc5fb65f4433](https://kusama.subscan.io/extrinsic/0x1438d742c69daf0b18b0c1a68b6a8e71e80d6569292409b76c0fbc5fb65f4433)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
