### PR TITLE
feat/3509-desc-table-bsx

### LINKED ISSUE #3509: add description to table in bsx/stats
### What happened?

I can't find my nft that I put on listing. there are two of them. price 10002 and 10004 bsx.
https://beta.kodadot.xyz/bsx/stats/?page=1

### Please reproduce in steps

I created two nft and put them on the listing at the prices of 10002 (today) and 10004 (two days ago). switched to https://beta .kodadot.xyz/bsx/stats/?page=1 and I can't find them there.
my profile
https://beta.kodadot.xyz/bsx/u/bXiovEsrLpx6fYRBJf1XZiXTEz4txu5FqGtAY4XqHvbxTVEHK

### Expected Behavior

I think I should have found them in the specified section

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### At which chain did you encounter bug?

Basilisk

### Screenshots

image

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by KngZhi**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3509
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer?target=DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by Jarsen136** [comment]
I prefer the title text to be vertical central.

image

**Comment by KngZhi** [comment]
hi, @Jarsen136 this is actually vertically centered. 

But I know what you mean, by doing that it has to change the upper section, I kind of want to avoid doing that in case of any overflow error.

image

image

**Comment by KngZhi** [comment]
This would be no-padding-no-margin and vertical output. Maybe a little bit too packed 🤔?
image

**Comment by Jarsen136** [comment]
> hi, @Jarsen136 this is actually vertically centered.
> 
> But I know what you mean, by doing that it has to change the upper section, I kind of want to avoid doing that in case of any overflow error.
> 


Oki. How about just keeping these two border line to be the same style(color). They look a little bit wired.

image

**Comment by KngZhi** [comment]
> > hi, @Jarsen136 this is actually vertically centered.
> > But I know what you mean, by doing that it has to change the upper section, I kind of want to avoid doing that in case of any overflow error.
> 
> Oki. How about just keeping these two border line to be the same style(color). They look a little bit wired.
> 
> image

Okay, no problem.

**Comment by KngZhi** [comment]
@Jarsen136 🤦‍♂️ checked with CSS, and those two colors are actually the same.

**Comment by Jarsen136** [comment]
> @Jarsen136 🤦‍♂️ checked with CSS, and those two colors are actually the same.
> 
> The width of border altered our vision...

I mean keep them in the same style (color\width\opacity) 😄

**Comment by KngZhi** [comment]
image

**Review by Jarsen136 — APPROVED** [review]
LGTM

**Review by petersopko — APPROVED** [review]

**Comment by petersopko** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 67.78 USD/KSM ~ 0.738 $KSM
🧗 [DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc](https://kusama.subscan.io/account/DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc)
🔗 [0xb8c6d3581222f67e5a7e951331fe1877d30d0d169d6a17016a7051d918154f97](https://kusama.subscan.io/extrinsic/0xb8c6d3581222f67e5a7e951331fe1877d30d0d169d6a17016a7051d918154f97)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
