### PR TITLE
[blogpost] KodaDots Drop Page explained

### LINKED ISSUE #6619: [blogpost] KodaDot's Drop Page explained
date
---
7/7/2023

title
---
KodaDot's Drop Page explained

DALL·E 2023-08-08 17 35 52 - create a me a picture with dark background where various diginal paintings are circlining in the air

You may notice this exciting feature that appeared a few weeks ago on [KodaDot](https://twitter.com/KodaDot) - Polkadot NFT marketplace. Drop Page was inspired by other marketplaces outside of the Polkadot ecosystem, but also it was a feature needed by artists. And the potential behind it? Exciting.

## Why do we need drop pages?
When an NFT project plans to release a new collection, they typically make an announcement on their official Twitter or Discord platform. This announcement typically includes information about the allowlist, reveal, and drop schedule, which creates an exciting opportunity to generate excitement about the collection.

## The first versions of the KodaDot minting page
Initially, we developed an anime waifu minter as a fun feature for various crypto events. We did not have any concrete plans at that time. Our intention was to make KodaDot more engaging and interactive. The AI model we created was well-received by users who enjoyed the minting process. We programmed it to generate anime characters, and each user was able to mint one NFT, received either through mail or directly to their wallet.

### NFTs from the first version of our AI minter - Sub0, 2022
Screenshot 2023-08-08 at 12 47 16

We made some updates to our model, beginning with simple images and gradually improving until they reached a much higher quality.

### NFTs from the new version of our AI minter - BlockSplit, 2023
Screenshot 2023-08-08 at 12 47 46

_Kudos to [Vikival](https://twitter.com/vikiival), who spent hours programming, testing various anime AI models, and training them to our needs. He is the real MVP._

But that was just the beginning. Many events and versions passed till we got to our current Drop Page. Created by who else - [Vikival](https://twitter.com/vikiival) and with the help of our excellent designer [Exez](https://twitter.com/OndraPulc), we managed to get to the point we were satisfied. But Im sure we are not done yet.

## So, what is the KodaDot Drop Page? 
When you go to https://kodadot.xyz/ and in the right-up corner select [Drops](https://kodadot.xyz/stmn/drops), you will see drops that are happening at the moment. They are time-limited collections that are created for a specific audience. The goal of these is to create a unique experience for people visiting our platform. Artists, creators, and collectors can use and, in some cases, obtain free NFTs, with extra surprises coming with each one. 

Screenshot 2023-08-07 at 19 39 17

Every Drop has its own unique page that can be customized to enhance the experience for artists and projects. This includes options such as setting phases, limits, availability, and schedules. You can showcase specific NFTs or provide the option for people to choose which NFT they wish to mint. The possibilities are endless!

Screenshot 2023-08-08 at 11 01 52

Using our drop page is a straightforward process. All you need to do is connect your wallet and mint your NFT for free (or sometimes for a fee). Drop Page offers a customizable canvas that can cater to different needs. At the time of writing this article, there were two ongoing drops. Both were NFTs generated with the assistance of an AI minter that was trained for distinct outcomes. To mint your NFT, simply connect your wallet, and the AI model will produce a unique one for you and send it to your wallet.

## Unlockable surprise
And there's more! We've added unlockables so you can enjoy the thrill of discovering hidden rewards! Each NFT from the official [KodaDot](https://twitter.com/KodaDot) drops had hidden content available only for those who minted their NFT. You only need to check your profile to find the NFT and click "Unlockable Content" to reveal the surprise. 

Screenshot 2023-08-08 at 15 44 50

On the [Upcoming](https://kodadot.xyz/stmn/drops) page, you can view scheduled releases and discover drop pages for those interested in obtaining them. Additionally, your page may be featured on this page.

Screenshot 2023-08-08 at 11 10 55

## A bundle of features you can combine 💫
We already mentioned some of the features we implemented in this article. All of them are customizable. You can choose which one you want and which one you don't. Here is a small preview of the main features we have:
1. Dedicated times for minting
Select what day your minting starts, what hours will be available, and how long. We can adjust this to your needs. Minting one hour every day for one week? No problem. We can also include an attractive countdown so your audience can better understand upcoming events.
2. Limits
The basic limit is selecting how many NFTs in total can be minted. This varies on your collection size, but in some cases (AI minting, generative art), this number can be adjusted regarding your preferences. 
You can also limit mints by the number of NFTs that can be minted at various times. Choose how many can be minted max during different phases. And, of course, we can show the availability of your NFTs so people know how much of them are left.
3. AI tools
We had anime waifus in our previous campaigns created by a highly trained AI model. Im sure we can also use it in your case. You just need to tell us [your idea](https://form.kodadot.xyz/drop-page-interest). 
4. Custom link
Do you want your custom link to your drop page? No problem. In some exceptional cases, we can also hide your Drop so you can target a specific audience. 
5. Free mint - Paid mint
Depends on you. You can choose.
6. Connection with our merch shop
This is one of the BEST benefits we offer. We allow you to connect your NFT collection to our merch shop and reward your loyal audience with a free merchandise drop. Depending on your budget, the size of the project, and the audience, we can offer you some starting amount for free. 
7. Your design in our shop
To make these drops even more interesting, we allow, in some cases, custom designs in our shop. You only need to deliver your design, and our shop will handle everything else. 
7. Unlockables
Adding your own unlockable content. Learn more about unlockables [here](https://kodadot.xyz/blog/how-do-unlockable-content-nfts-work-on-kodadot).
And More
We already have a lot of features, and we are still planning to add more in the future. Is something missing from the list? Let us know! Our team can work on it. 

## Interested? 
Are you a project looking to release an exciting new collection or an artist exploring fresh ideas? Let's collaborate! Simply fill out [this form](https://form.kodadot.xyz/drop-page-interest) to share your vision with us. If you're interested in featuring your collection in our shop, please keep in mind your budget. This form will provide us with a general idea of your plans, and we'll discuss all the specifics later. We'll be in touch soon!

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [x] Feature
- [ ] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #6619
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [ ] My fix has changed UI

### <samp>🤖 Generated by Copilot at 44a41b6</samp>

This pull request adds a new blog post about the Drop Page feature and improves the link styling in the BlogPost component. The blog post `content/blog/kodadot's-drop-page-explained.md` explains how to use the Drop Page and showcases its benefits. The style rule in `components/blog/BlogPost.vue` makes the links in the blog posts more visible and consistent with the theme.

### <samp>🤖 Generated by Copilot at 44a41b6</samp>

> _`BlogPost` links styled_
> _New markdown for Drop Page_
> _Winter feature guide_

### CODE REVIEW

**Comment by yangwao** [comment]
@JustLuuuu review

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 5.06 USD/DOT ~ 9.881 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0xdba2191c98d5e5500930b9b3d200b80c46e579d4f28a6365898002f1da58212c](https://polkadot.subscan.io/extrinsic/0xdba2191c98d5e5500930b9b3d200b80c46e579d4f28a6365898002f1da58212c)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by JustLuuuu** [comment]
> @JustLuuuu review

good that you told me, there is a bad picture I uploaded. @Jarsen136 can you please delete the picture under Unlockable surprise: 

This one delete: Screenshot 2023-08-08 at 15 44 50

Use this one instead, please. 
Screenshot 2023-08-08 at 11 27 53

**Pull request merged**
