### PR TITLE
#4763 gallery fixes

### LINKED ISSUE #4763: Owner gallery item ui
## Buttons 
image
- dark mode boxes are light, please make them dark
- text has almost zero padding

image
- change price should not have primary color 
- make it same as transfer please
## Burn and delist
- looks like these buttons are missing in more options?

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Closes #4763
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screen Shot 2023-01-18 at 7 30 37 PM

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
Screenshot 2023-01-19 at 16-47-11 🌑 Dark side KodaDot - NFT Market Explorer


buttons (action slide) design should be unified, it miss new padding on "Transfer"

**Comment by exezbcz** [comment]
missing padding, otherwise ok

i guess this is connected with the full width action buttons? 
image

**Comment by prachi00** [comment]
fixed

**Comment by exezbcz** [comment]
i guess this is for another issue? 
image

**Comment by yangwao** [comment]
> i guess this is for another issue?

yes

**Comment by vikiival** [comment]
pay 10 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $10 @ 35.4 USD/KSM ~ 0.282 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x5ad471623e7888e21be2adf2d02bcaaee1fa3935b6dd05984c8695b9467510ac](https://kusama.subscan.io/extrinsic/0x5ad471623e7888e21be2adf2d02bcaaee1fa3935b6dd05984c8695b9467510ac)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
