### PR TITLE
#2256 Mobile-first experience

### LINKED ISSUE #2256: Rehaul for mobile-first experience
I guess this would be starter to bring full widths picture to mobile as wider picture might have higher impress on people on already small screen tho.

We will start with feeds pic1

Would be really much needed for 
- gallery
- artist profile feeds
- collections
- collection detail
- NFT item detail pic2

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #2256
- [ ] 

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screenshot 2022-02-09 at 4 26 09 PM

### CODE REVIEW

**Comment by yangwao** [comment]
Let's make it full-width edge to edge on mobile phones :)

**Comment by prachi00** [comment]
@yangwao done

**Comment by yangwao** [comment]
Let's move previous and next button to edge and fullscreen to corner and we are good to go!

**Comment by prachi00** [comment]
@yangwao doneee

**Comment by yangwao** [comment]
oh yeah, love it! 
image

pay 150 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $150 @ 187.07 USD/KSM ~ 0.802 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x24a1529e5dd5b0b7b8e9b8391a7a4cd6804465968283551bb03187cd38c7793c](https://kusama.subscan.io/extrinsic/0x24a1529e5dd5b0b7b8e9b8391a7a4cd6804465968283551bb03187cd38c7793c)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
