### PR TITLE
fix: Incorrect url of nft on More From This Collection

### LINKED ISSUE #4158: Incorrect url of nft on 'More From This Collection'
### What happened?

visit https://beta.kodadot.xyz/bsx/gallery/3813476019-44

click any item on 'More From This Collection'
image

error happen
image

### Please reproduce in steps

1. visit https://beta.kodadot.xyz/bsx/gallery/3813476019-44

2. click any item on 'More From This Collection'

### Expected Behavior

should open the correct link of the nft without error toast.

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

_No response_

### Are you logged in?

No

### Which wallet you are using?

PolkadotJS

### At which chain did you encounter bug?

Basilisk

### Screenshots

image

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #4158 
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
/bsx/gallery/3813476019-44

image

image

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
`Expected 2 arguments, but got 1` in useCarousel.ts

I was thinking more of something like:
in `formatNFT`
```ts
return {
  ...,
  chain: urlPrefix,
}
```

**Review by roiLeo — APPROVED** [review]

**Comment by Jarsen136** [comment]
> `Expected 2 arguments, but got 1` in useCarousel.ts
> 

✅ fixed ts error

> I was thinking more of something like: in `formatNFT`
> 
> ```ts
> return {
>   ...,
>   chain: urlPrefix,
> }
> ```

We could not do that because `Newest list` would display nfts from different chains at one list. That's why we have this 'chain' parameter.

**Comment by roiLeo** [comment]
pay 20

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 34.69 USD/KSM ~ 0.577 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xbee0d5fef748ef200a342174daf160c57172ba2f8ce2c3b1f381920ee9ea94ed](https://kusama.subscan.io/extrinsic/0xbee0d5fef748ef200a342174daf160c57172ba2f8ce2c3b1f381920ee9ea94ed)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
