### PR TITLE
redesign: prepare landing page for new design

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] prepare landing page for new design https://github.com/kodadot/nft-gallery/issues/3844#issuecomment-1234091517
- [x] access new design with `?redesign=true`
- [x] existing design should be still ok 
- [x] https://github.com/kodadot/nft-gallery/discussions/3710#discussioncomment-3501133

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by preschian** [comment]
hi, I need your feedback, should we go with this approach or not? the goal is, we can start redesigning components without blocking deployment to production. because the new design only can be accessed with query parameters

alternative from query parameters:
- custom cookie
- custom http-header

**Comment by roiLeo** [comment]
wait what? why this way?
My suggestion would be to manage a new branch and cherry-pick new version of landing

**Comment by preschian** [comment]
> wait what? why this way? My suggestion would be to manage a new branch and cherry-pick new version of landing

I thought this way was easier. but if we already have another simpler solution I will follow it 👍

**Comment by preschian** [comment]
> My suggestion would be to manage a new branch and cherry-pick new version of landing

for this, does it means we have another big branch for a redesign? for example `main-redesign`

**Comment by roiLeo** [comment]
> for this, does it means we have another big branch for a redesign? for example `main-redesign`

yes! maybe with another branch name, since we're migrating app to use vue3 composition api

**Comment by preschian** [comment]
> yes! maybe with another branch name, since we're migrating app to use vue3 composition api

I thought that with another big branch would be difficult once ready to merge into the main branch, because of some file conflicts

but, no issue for me if everyone prefers that way 👍

**Comment by roiLeo** [comment]
> but, no issue for me if everyone prefers that way 👍

Let's wait for another developer's point of view

**Comment by yangwao** [comment]
uno momento  🤌

**Comment by roiLeo** [comment]
Since we're going to use new typo, different font-size & update components (inputs, select, dropdown) design. I would be in favor to make these developments on a new branch so as not to disrupt the existing one.

**Comment by preschian** [comment]
> Since we're going to use new typo, different font-size & update components (inputs, select, dropdown) design. I would be in favor to make these developments on a new branch so as not to disrupt the existing one. I find that it might be difficult to maintain 2 different design system on the same project/branch.

maybe describe and define the branch name in here [#3710](https://github.com/kodadot/nft-gallery/discussions/3710?sort=new). so on every redesign PR can follow the guideline to that link

**Comment by yangwao** [comment]
I've dropped some wisdom https://github.com/kodadot/nft-gallery/discussions/3710 

> define the branch name

`canary` 

> Since we're going to use new typo, different font-size & update components (inputs, select, dropdown) design. I would be in favor to make these developments on a new branch so as not to disrupt the existing one.

just for the landing page, I promise 🤞🥹

**Comment by preschian** [comment]
ready for review 🙏🏻

it's decided that we use query parameters for the landing page only https://github.com/kodadot/nft-gallery/discussions/3710#discussioncomment-3584493. the goal is still the same, hopefully not break/block the existing design while creating a new redesign component

**Comment by yangwao** [comment]
yas, let's kick this off! :)

works old version and the new one seems div containers ready to be there.

pay 100

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 51.94 USD/KSM ~ 1.925 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0x926dced7f7648ebc43def691b88111f371532bafea39338a1ee731110078a9a4](https://kusama.subscan.io/extrinsic/0x926dced7f7648ebc43def691b88111f371532bafea39338a1ee731110078a9a4)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
