### PR TITLE
fix: subscribe form missing on route navigation

### LINKED ISSUE #7724: Missing email signup input field in footer
image

canary: 
image

### PR DESCRIPTION
**Pull request by thnaylor**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #7724 
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [ ] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=123PCJXhjb15i6JwVVRGd7KvN2sSNZrtPjr5doJq9oWctoTt)

## Comments
- Seems to be an issue when loading a script from useHead in a component when using nuxt internal navigation and the component gets remounted a second time.
- Substackapi script also expects a div with id 'custom-substack-embed' to exist so loading the script globally/premounted causes errors.

### <samp>🤖 Generated by Copilot at dfd2ead</samp>

Improved substack script loading in `CustomSubstackEmbed` component. The component now creates and removes the script element on mount and unmount instead of using `useHead`.

### <samp>🤖 Generated by Copilot at dfd2ead</samp>

> _`CustomSubstackEmbed`_
> _Loads script on mount, unmount_
> _Snowflakes melt away_

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
already fixed in #7725

**Comment by prury** [comment]
please update PR @thnaylor

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 4.34 USD/DOT ~ 4.608 $DOT
🧗 [123PCJXhjb15i6JwVVRGd7KvN2sSNZrtPjr5doJq9oWctoTt](https://polkadot.subscan.io/account/123PCJXhjb15i6JwVVRGd7KvN2sSNZrtPjr5doJq9oWctoTt)
🔗 [0x1c0e3340a5aea188c98a878efc03544e1cdd2eb93800e530fcb7a39ffc510c67](https://polkadot.subscan.io/extrinsic/0x1c0e3340a5aea188c98a878efc03544e1cdd2eb93800e530fcb7a39ffc510c67)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 4.34 USD/DOT ~ 4.608 $DOT
🧗 [123PCJXhjb15i6JwVVRGd7KvN2sSNZrtPjr5doJq9oWctoTt](https://polkadot.subscan.io/account/123PCJXhjb15i6JwVVRGd7KvN2sSNZrtPjr5doJq9oWctoTt)
🔗 [0x7b04d937aed19b8f27d3b96fe552aa33fe70e80f583142b4cd8cdfe502ab38ba](https://polkadot.subscan.io/extrinsic/0x7b04d937aed19b8f27d3b96fe552aa33fe70e80f583142b4cd8cdfe502ab38ba)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
