### PR TITLE
🔧 bsx collection sort & own

### LINKED ISSUE #3434: Search for NFTs in specific collection
currently we have 4 options when it comes to search on top of collection:
image

- [x] search bar input (hotfixed implemented thanks to @roiLeo)
- https://github.com/kodadot/nft-gallery/pull/3432
- [x] buy now toggle works properly for me (showing only NFTs with price)
- [ ] sorting doesn't seem to do anything
- [ ] own toggle indicating to show which NFTs are mine (wallet logged in) seems to be same issue as in 
- https://github.com/kodadot/nft-gallery/issues/3433
```json
{
  "errors": [
    {
      "message": "Variable \"$search\" got invalid value { currentOwner: { equalTo: \"bXkVgiXLvvJAmUNni8huN9NZdjaxKGav9fSszhRXFeg6Xuvih\" } } at \"search[0]\"; Field \"currentOwner\" is not defined by type \"NFTEntityWhereInput\". Did you mean \"currentOwner_eq\", \"currentOwner_gt\", \"currentOwner_in\", \"currentOwner_lt\", or \"currentOwner_gte\"?",
      "extensions": {
        "code": "BAD_USER_INPUT",
        "exception": {
          "stacktrace": [
            "GraphQLError: Variable \"$search\" got invalid value { currentOwner: { equalTo: \"bXkVgiXLvvJAmUNni8huN9NZdjaxKGav9fSszhRXFeg6Xuvih\" } } at \"search[0]\"; Field \"currentOwner\" is not defined by type \"NFTEntityWhereInput\". Did you mean \"currentOwner_eq\", \"currentOwner_gt\", \"currentOwner_in\", \"currentOwner_lt\", or \"currentOwner_gte\"?",
            "    at /squid/node_modules/graphql/execution/values.js:116:15",
            "    at coerceInputValueImpl (/squid/node_modules/graphql/utilities/coerceInputValue.js:114:9)",
            "    at coerceInputValueImpl (/squid/node_modules/graphql/utilities/coerceInputValue.js:54:14)",
            "    at /squid/node_modules/graphql/utilities/coerceInputValue.js:70:14",
            "    at Array.map (<anonymous>)",
            "    at safeArrayFrom (/squid/node_modules/graphql/jsutils/safeArrayFrom.js:36:23)",
            "    at coerceInputValueImpl (/squid/node_modules/graphql/utilities/coerceInputValue.js:68:50)",
            "    at coerceInputValue (/squid/node_modules/graphql/utilities/coerceInputValue.js:37:10)",
            "    at _loop (/squid/node_modules/graphql/execution/values.js:109:69)",
            "    at coerceVariableValues (/squid/node_modules/graphql/execution/values.js:121:16)"
          ]
        }
      }
    }
  ]
}

```

### PR DESCRIPTION
**Pull request by roiLeo**
Tested on `/bsx/collection/2532142859`
Thanks @petersopko for spoting this

### PR type

- [x] Bugfix

### What's new?

- [x] PR closes #3434 
- [x] fix "own" toggle for subsquid in /collection/{id}
- [x] fix "sort" for subsquid in /collection/{id}

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

### CODE REVIEW

**Review by DeluneClaire — COMMENTED** [review]
Hello, I didn't find it after I used ctr+C and added the name. When I wrote, it could find but couldn't see any NFTs - so I couldn't look for any.

https://user-images.githubusercontent.com/104791453/179211427-1cefa136-d08a-41cb-b6d9-914bab8320ea.mov

This is the error I got after not showing the collection:

Uncaught (in promise) NavigationDuplicated: Avoided redundant navigation to current location: "/bsx/explore?page=1&search=%20BSxPunks&sort=blockNumber_DESC".
    next 66
        Pt
        confirmTransition
        transitionTo
        replace
        replace
        replace
        redirectToGalleryPageIfNeed
        updateSearch
        value
        o
        setTimeout handler*o/</t.methods[n]
        r
        mounted
        ne
        mn
        insert
        $
        ui
        _update
        r
        get
        run
        On
        he
        ce
        promise callback*ie
        he
        update
        update
        notify
        set
        set
        toggleSearchBarDisplay
        ne
        n
        _wrapper
        yo
        be
        wo
        _
        v
        ui
        _update
        r
        get
        Cn
        mount
        $mount
        $mount
        init
        v
        v
        w
        v
        w
        v
        w
        v
        w
        v
        w
        v
        ui
        _update
        r
        get
:

This is the error I got after not showing any NFTs in the collection:

Uncaught (in promise) Error: Network error: Response not successful: Received status code 400
    NuxtJS 54
        t
        queryListenerForObserver
        broadcastQueries
        broadcastQueries
        broadcastQueries
        _
        promise callback*ja</e.prototype.fetchQuery/</<
        c
        c
        ra
        ra
        fetchQuery
        observeQuery
        setUpQuery
        onSubscribe
        l
        e
        value
        result
        result
        query
        query
        query
        value
        fetchPageData
        r
        l
        promise callback*r
        l
        o
        o
        fetchPageData
        created
        r
        l
        o
        o
        created
        ne
        mn
        _init
        f
        componentInstance
        init
        v
        v
        ui
        _update
        r
        get
        Cn
        mount
        $mount
        $mount

**Comment by roiLeo** [comment]
@DeluneClaire these changes doesn't concern the navigation bars but rather the search in the details of a collection.

You can test the difference between [beta](https://beta.kodadot.xyz/bsx/collection/2532142859 ) & this [preview](https://deploy-preview-3441--koda-nuxt.netlify.app/bsx/collection/2532142859)

(`/bsx/collection/2532142859`)

**Review by kkukelka — APPROVED** [review]
code lgtm

**Review by DeluneClaire — COMMENTED** [review]
Works for me

**Comment by DeluneClaire** [comment]
> @DeluneClaire these changes doesn't concern the navigation bars but rather the search in the details of a collection. I tend to explain the changes in "What's new?" paragraph.
> 
> You can test the difference between [beta](https://beta.kodadot.xyz/bsx/collection/2532142859) & this [preview](https://deploy-preview-3441--koda-nuxt.netlify.app/bsx/collection/2532142859)
> 
> (`/bsx/collection/2532142859`)

Yes i know. I fixed it. Sorry

**Pull request merged**
