### PR TITLE
feat(collection): status signaling

### LINKED ISSUE #703: Status signaling for collections
mne by sa ešte v nahladoch kolekcií toto velmi páčilo - či už z pohľadu kupujúceho (lahšie sa rozhodne, že dobre tak toto ludia kupujú, to kúpim aj ja) tak aj z pohladu predávajúceho (že fíha, tak už 10 ludí vlastní nftčko z mojej kolekcii? :smile: )

To engage more collectibles as SoV from the perspective of collectors and appreciate the great work of creators, would be nice to leverage subquery to enhance the collection view for 
- [ ] number of items
- [ ] owners (number of address that has it?)
- [ ] floor price (this would be a harder one but I guess WAGMI!)
- [ ] total volume traded
- [ ] 24h volume traded

originally raised by @jkdizajn
image

i.e collections to test 
- https://nft.kodadot.xyz/rmrk/collection/cadffbe2992cea506c-CAVDO
- https://nft.kodadot.xyz/rmrk/collection/900D19DC7D3C444E4C-KSMG22

or feel free put one we should do test case against!

### PR DESCRIPTION
**Pull request by roiLeo**
Tested on:
- /rmrk/collection/800f8a914281765a7d-KITTY
- /rmrk/collection/466e8b6338599eaf1e-GAVS371
- /rmrk/collection/900D19DC7D3C444E4C-KSMG22

### PR type
- [x] Feature

### Before submitting this PR, please make sure:
- [x] Code builds clean without any errors or warnings
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional
- [x] I've tested it on mobile and everything works
- [x] I found edge cases: 
1. When collection doesn't have floor price
2. When there is multiple "BUY" events on one single NFT

### What's new? (may be part of changelog)
- This PR closes #703 

### Screenshot
Screenshot 2021-09-13 at 11-58-58 Kitty Paradise
Screenshot 2021-09-13 at 11-59-38 GAV Sphere - Generative AudioVisual Collection

### Notes
In this PR i've edited some typescript file to fix building errors/warnings and I don't know if it break something.
24h volume traded feels weird :/

### CODE REVIEW

**Review by vikiival — CHANGES_REQUESTED** [review]
Really nice work. 

I would just move view to the separated `.vue` file along with the getters 👁️ 

Also I would move filtering to the graphql
https://doc.subquery.network/de/create/graphql/#json-type

**Comment by roiLeo** [comment]
Should I create a new component (CollectionActivity) with "collection.nft" as prop ? or move code into GalleryCardList ?
Do I have to create 2 graphql query ? (one for Traded NFT and one for Traded Volume) or I need something else ? 
I'm a bit confused with this, are we going to perform a new API call instead of filter actual data ?

**Comment by vikiival** [comment]
> Should I create a new component (CollectionActivity) with "collection.nft" as prop
Yes please :)

**Review by vikiival — APPROVED** [review]

**Comment by yangwao** [comment]
All good, only **24h volume traded** is missing, should we wait for the next commit or will for another PR? @roiLeo 👀😄

**Comment by yangwao** [comment]
> Tested on Kitty
> while code feel ugly
> 
> I need more test case

I guess, let's push it and we will see how it goes? :)

I guess we will receive some feedback as well.

**Pull request merged**
