### PR TITLE
fix: banner background position

### LINKED ISSUE #7942: Collection preview
Some collections preview img looks like this 

 - happens on desktop as well, for example on generative collection

https://canary.kodadot.xyz/ahp/collection/21

### PR DESCRIPTION
**Pull request by pbkompasz**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [X] Refactoring

## Context

- [X] Closes #7942
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [X] My contribution builds **clean without any errors or warnings**
- [X] I've merged recent default branch -- **main** and I've no conflicts
- [X] I've tried to respect high code quality standards
- [X] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [X] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16hqk8Tjugo9AwSzKkxXc1dsRK7iJetpx1YBaoXYwdHzuNAt&usdamount=50&donation=true)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screenshot from 2023-11-03 23-39-19
Screenshot from 2023-11-03 23-39-05
Screenshot from 2023-11-03 23-38-34

### <samp>🤖 Generated by Copilot at 59eb2c8</samp>

Improved the styling of the collection banner component by centering the background image. This change affects the file `components/collection/CollectionHeader/CollectionBanner.vue`.

### <samp>🤖 Generated by Copilot at 59eb2c8</samp>

> _`collection-banner`_
> _background image centered now_
> _autumn leaves align_

### CODE REVIEW

**Comment by exezbcz** [comment]
works for me, thanks!

**Review by roiLeo — APPROVED** [review]

**Comment by prury** [comment]
while i do not oppose the background centering change, i think the issue was about this:

image

and it is still ocurring

**Comment by yangwao** [comment]
thanks!
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 4.86 USD/DOT ~ 4.115 $DOT
🧗 [16hqk8Tjugo9AwSzKkxXc1dsRK7iJetpx1YBaoXYwdHzuNAt](https://polkadot.subscan.io/account/16hqk8Tjugo9AwSzKkxXc1dsRK7iJetpx1YBaoXYwdHzuNAt)
🔗 [0x2c95f9a1c81e530802d114d3c48e812059ada3400493cc56bb78d56ae4c0cd5c](https://polkadot.subscan.io/extrinsic/0x2c95f9a1c81e530802d114d3c48e812059ada3400493cc56bb78d56ae4c0cd5c)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
