### PR TITLE
#1897 fix emoji parser and add orderby count

### LINKED ISSUE #1897: long Emotes list on nft
on `/rmrk/gallery/6802639-24d573f4dfa1d7fd33-KAN-KANL-0000000000006001` I came across a big list of Emotes (Appreciations), some of them where duplicated when they should be grouped

Screenshot 2022-01-17 at 16-45-02 Limited Edition Kanaria Egg

#### Possible solution
- show a certain amount of emojis

#### Bonus
- sort Emoji List by most reacted

### LINKED ISSUE #1918: Show which user has sent an emote to nft
### Is your feature request related to a problem?

I'm always frustrated when someone react on my NFT but I don't know who this is.

### Describe the solution you would like

I would like to see, on hover emoji, to show me wich identity reacted to the nft.

### Describe alternatives you have considered

Logic could be in `EmotionList` component & we can reuse `IdentityPopover`

### Screeenshots

Paste your vision

group it with #1897

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #1897
- [x] fix emoji parser from `String.fromcodePoint(int)` to `String.fromcodePoint(int, int, int, int)`
- [x] fix issuerid
- [x] add orderBy count
- [x] PR closes #1918 add emotion modal

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

https://user-images.githubusercontent.com/734428/159213609-f86a17b7-2e49-42b6-a88d-b3d3e4625a11.mov

### CODE REVIEW

**Comment by yangwao** [comment]
mmm, I would show only the first row emojis with the highest count to not disrupt the layout. 
rest I would show some kind of modal on click.
plus 1px top-border 🥺

The next step would be to show on click in that modal which addresses emoted. 

https://kodadot.xyz/rmrk/gallery/6802639-24d573f4dfa1d7fd33-KAN-KANL-0000000000006001

image

vs

https://deploy-preview-2610--koda-nuxt.netlify.app/rmrk/gallery/6802639-24d573f4dfa1d7fd33-KAN-KANL-0000000000006001
image

**Comment by preschian** [comment]
updated, related to this one also #1918

preview:

https://user-images.githubusercontent.com/734428/159287601-728b5b45-4bd9-4b1d-b5d3-c8c13cac5330.mov

**Comment by yangwao** [comment]
lgtm 
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 165.04 USD/KSM ~ 0.606 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0x60cee8d8ae7f14f144b51354e833e6d6560005f230565dd5026edf2469671fd3](https://kusama.subscan.io/extrinsic/0x60cee8d8ae7f14f144b51354e833e6d6560005f230565dd5026edf2469671fd3)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
