### PR TITLE
Navbar breakpoints to hide tab

### LINKED ISSUE #2760: Navbar breakpoints on 1037px
Should be folding.. or we can think of hiding particular buttons based on importance?

Like hide button in a particular order
- Language
- Create
- Chain/protocol switch
- history
- stats
- profile

image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2760
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by Jarsen136** [comment]
> You should check [these](https://bulma.io/documentation/helpers/visibility-helpers/#hide) responsive helpers

Thanks, it's helpful. However, in this case these ranges are not precise enough, we need to accurately control the display of each tab.
image

**Comment by Jarsen136** [comment]
Okey, now this searchBar is responsive. 👀

**Comment by yangwao** [comment]
I mean previous hiding technique was a great approach. 
Maybe just hide out chain selector and language, so the search bar won't look bad if someone use it, for example, someone is using a split-screen on 13" 

1110px width 
image

**Comment by Jarsen136** [comment]
> I mean previous hiding technique was a great approach. Maybe just hide out chain selector and language, so the search bar won't look bad if someone use it, for example, someone is using a split-screen on 13"
> 
> 1110px width image

Oh I misread what you meant. Let me revert to the original state

**Comment by yangwao** [comment]
> > I mean previous hiding technique was a great approach. Maybe just hide out chain selector and language, so the search bar won't look bad if someone use it, for example, someone is using a split-screen on 13"
> > 1110px width image
> 
> Oh I misread what you meant. Let me revert to the original state

yes, a flexible search bar with hiding would be great I guess! :)

yes, in the previous state was an issue that search bar was fixed :)

**Comment by Jarsen136** [comment]
> 
> yes, a flexible search bar with hiding would be great I guess! :)
> 
> yes, in the previous state was an issue that search bar was fixed :)

How about now? 👀   shorten the width of search-bar first, and then hide out language and chain selector

**Comment by yangwao** [comment]
I mean way better, I guess we will rework the whole navbar later :) 

image

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 191.64 USD/KSM ~ 0.522 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xfd0992102b23d4b9b9b3c73967cc03fc133b499c62dc94a61f3ee0cb9418e205](https://kusama.subscan.io/extrinsic/0xfd0992102b23d4b9b9b3c73967cc03fc133b499c62dc94a61f3ee0cb9418e205)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
We should rework and refactor the navbar code in a much more sensible way and what's should be merged and exclude on different widths.

Hidding least popular buttons from first, hence we don't have any UX research I can only bet.
- language
- chain/protocol selector
- create
- history
- stats
- profile

With search bar should be flexible and fill up the rest space next to the buttons.

**Pull request merged**
