### PR TITLE
feat: Share collection - as frame and other options

### LINKED ISSUE #10031: Share collection - as frame and other options
**before:** 
image

**after:** 
image

- adding icons to all sections
- renamed twitter to X 
- added "share as farcaster frame" 

related: 
- https://github.com/kodadot/nft-gallery/issues/9839

using this: 
- https://github.com/kodadot/frames/issues/1

design updated here: 
https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=1287-18959&mode=design&t=fA9qr1PUumCPFnJo-11

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Feature

## Needs Design check

- @exezbcz please review

## Context

- [x] Closes #10031

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image
image

### CODE REVIEW

**Comment by exezbcz** [comment]
works for me! thanks a lot

**Review by daiagi — APPROVED** [review]

**Review by vikiival — APPROVED** [review]
TY

**Comment by prury** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 8.26 USD/DOT ~ 3.632 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x26e4ddc924a8457ce8763b19470ad5043eac618596546b8e56bec7233d1528fb](https://polkadot.subscan.io/extrinsic/0x26e4ddc924a8457ce8763b19470ad5043eac618596546b8e56bec7233d1528fb)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
