### PR TITLE
1253 tell your friends about ss58

### PR DESCRIPTION
**Pull request by vikiival**
- Closing #1227
- :egg: Transfer can take any valid address

### Before submitting this PR, please make sure:
- [x] Your code builds clean without any erros or warnigns
- [ ] You've posted screenshot of demonstrated change in this PR
- [ ] Merged recent default branch, **main** and you have no conflicts
- [x] Didn't break any original functionality 

### Optional
- [ ] You've tested it on mobile

### PR type
- [x] Bugfix
- [x] Feature
- [ ] Refactoring

### Changelog - What's new? (may be part of changelog)

Closing #1227, #1253

### CODE REVIEW

**Comment by yangwao** [comment]
hmm, I would show other disabled input with a new **converted**  address for that chain, once we will be running on statemine/bsx &c it will be more than needed. 

Let's add it there plus quick short explanation for normies

**Comment by yangwao** [comment]
When I put 
5HbsVS3M36Gy3dtwiLuwswJBZtuWCdebgk48Ek2BCGdD38Lj
New field with KSM appears 
 J7V9kPDfTHtoHiPV3izmtfBiVBk1JTn97tsdQJ8g4qhnH3z

**Comment by vikiival** [comment]
> When I put
> 5HbsVS3M36Gy3dtwiLuwswJBZtuWCdebgk48Ek2BCGdD38Lj
> New field with KSM appears
> J7V9kPDfTHtoHiPV3izmtfBiVBk1JTn97tsdQJ8g4qhnH3z

This sound like a master glitch to me 👀

**Comment by vikiival** [comment]
here you go sir @yangwao 

Screenshot 2021-11-23 at 14 04 32

**Pull request merged**
