### PR TITLE
feat: Small recent tag when connecting wallet

### LINKED ISSUE #7568: Small recent tag when connecting wallet
image
- would it be possible to put a small "recent" tag there? 
- design in handoff - light mode invert colors. 

https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=1287%3A18959&mode=design&t=dxVk780B0E5Al9nw-1

### PR DESCRIPTION
**Pull request by hassnian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #7568

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2023-10-11 at 13 55 15@2x

### <samp>🤖 Generated by Copilot at 88f5baa</samp>

This pull request adds a wallet history feature that allows users to view and switch between their recent wallets in the `ConnectWallet` component. It also improves the style and usability of the component and adds some helper functions and global styles.

### <samp>🤖 Generated by Copilot at 88f5baa</samp>

> _Sing, O Muse, of the skillful coder who wrought_
> _Many changes to the wallet app, and brought_
> _Beauty and function to the elements with `.border-rounded`_
> _And the `WalletMenuItem.vue` that recent wallets sounded_

### CODE REVIEW

**Comment by yangwao** [comment]
pay 30 usd
great!@

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 3.78 USD/DOT ~ 7.937 $DOT
🧗 [13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh](https://polkadot.subscan.io/account/13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)
🔗 [0x7cf9ed40538a44eacf0a523c7894adc8f7689da6ca958c7500354ec4eaf2001d](https://polkadot.subscan.io/extrinsic/0x7cf9ed40538a44eacf0a523c7894adc8f7689da6ca958c7500354ec4eaf2001d)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by hassnian** [comment]
@yangwao payout failed

**Comment by hassnian** [comment]
@yangwao kindly check, payout failed thanks

CleanShot 2023-10-13 at 16 19 16@2x

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 3.78 USD/DOT ~ 7.937 $DOT
🧗 [13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh](https://polkadot.subscan.io/account/13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)
🔗 [0x16d4da0cb78447166c09714a79691371267e62005a8ed6679f6cec11b4b3d3c3](https://polkadot.subscan.io/extrinsic/0x16d4da0cb78447166c09714a79691371267e62005a8ed6679f6cec11b4b3d3c3)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
