### PR TITLE
⚠️ Breaking: Support of the latest SubSquid

### LINKED ISSUE #3930: Replace ID with String in SubSquid GraphQL queries
### What happened?

The new GraphQL server does not expose `ID` type anymore.

Everything is exposed as the `String` type

### Please reproduce in steps

- Update `@subsquid/graphql-server` to the latest version on any indexer (rubick, click, snek)
- try to run any query that requires `ID` type
- Query will fail

### Expected Behavior

Query should run.

Fix.

In subsquid queries replace:
- `ID` -> `String`
- `ID!` -> `String!`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by vikiival**
# :warning: Breaking API change

The new version of SubSquid changed from ID to String

Will migrate indexers one by one today

6u207v

- :see_no_evil: suite is good for small scripts
- :zap: rubick support new queries
- :zap: snek support new queries
- :zap: general support of new queries
- :zap: some lost query

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [x] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #3930
- [ ] ref kodadot/rubick#138
- [ ] ref kodadot/snek#69
- [ ] ref kodadot/click#36

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### CODE REVIEW

**Comment by yangwao** [comment]
oh_sh_here_we_go_again.gif

**Comment by vikiival** [comment]
here-we-go-again-gta

**Comment by petersopko** [comment]
I assume I get this error at https://beta.kodadot.xyz/movr/collection/0xa90f3fc517d9126976dd59c5efec8de447f7ff7e because of new deploy?

```json
{
   "errors":[
      {
         "message":"Unknown type \"ID\".",
         "extensions":{
            "code":"GRAPHQL_VALIDATION_FAILED",
            "exception":{
               "stacktrace":[
                  "GraphQLError: Unknown type \"ID\".",
                  "    at Object.NamedType (/squid/node_modules/graphql/validation/rules/KnownTypeNamesRule.js:57:29)",
                  "    at Object.enter (/squid/node_modules/graphql/language/visitor.js:323:29)",
                  "    at Object.enter (/squid/node_modules/graphql/utilities/TypeInfo.js:370:25)",
                  "    at visit (/squid/node_modules/graphql/language/visitor.js:243:26)",
                  "    at validate (/squid/node_modules/graphql/validation/validate.js:69:24)",
                  "    at validate (/squid/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)",
                  "    at processGraphQLRequest (/squid/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)",
                  "    at runMicrotasks (<anonymous>)",
                  "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
                  "    at async processHTTPRequest (/squid/node_modules/apollo-server-core/dist/runHttpQuery.js:220:30)"
               ]
            }
         }
      }
   ]
}

```

**Review by roiLeo — APPROVED** [review]
✅ code lgtm, no more `ID`

**Comment by vikiival** [comment]
@petersopko yup already updated `click`

**Comment by vikiival** [comment]
PR 

Screenshot 2022-09-21 at 13 13 01

DEV

Screenshot 2022-09-21 at 13 12 58

**Review by petersopko — APPROVED** [review]
wfm

**Pull request merged**
