### PR TITLE
:bug: landing layout shapes

### LINKED ISSUE #4623: Landing layout at medium screens
There's an issue with centering landing (search and title section) on medium to small screens (looks like it's sub 1300px to 1024px)
image

### PR DESCRIPTION
**Pull request by petersopko**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4623
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [x] I've tested it at </bsx/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

### CODE REVIEW

**Comment by petersopko** [comment]
@exezbcz two questions:
1. is this the desired outcome? is it okay to make the shapes smaller once they don't fit? or do we want to eliminate the gap between them and the search section (gets us 100px more leeway, I still need to know what should happen to them after). Or hide them completely once they don't fit ?
2. I've noticed, and also checked the figma, that right shape is 309 wide, left one is 312px. Both are 311px high. Is this intentional?

**Comment by exezbcz** [comment]
> @exezbcz two questions:
> 
> 1. is this the desired outcome? is it okay to make the shapes smaller once they don't fit? or do we want to eliminate the gap between them and the search section (gets us 100px more leeway, I still need to know what should happen to them after). Or hide them completely once they don't fit ?

yup, its okay, i would not change the gap between the shapes and the search section. I think we can hide them sooner, somewhere around 1124px looks good to me instead of the 1024. 

> 2. I've noticed, and also checked the figma, that right shape is 309 wide, left one is 312px. Both are 311px high. Is this intentional?

Yes, that's my inaccuracy; the shapes aren't pixel perfect, but they'll work for now. Are 3px an issue while working with CSS? If so, let me know and I'll recreate it.

**Comment by petersopko** [comment]
> yup, its okay, i would not change the gap between the shapes and the search section. I think we can hide them sooner, somewhere around 1124px looks good to me instead of the 1024.
> 
done 🚀 
> 
> Yes, that's my inaccuracy; the shapes aren't pixel perfect, but they'll work for now. Are 3px an issue while working with CSS? If so, let me know and I'll recreate it.

no worries, just caught my eye

**Comment by exezbcz** [comment]
hmm, weird, it still behaves like the shapes are there but they are not visible
image

**Comment by petersopko** [comment]
> hmm, weird, it still behaves like the shapes are there but they are not visible

My bad; it should be fixed now. I made the shapes invisible between 1024 and 1124 to avoid changing the layout much; smaller than 1024 are entirely gone now.


https://user-images.githubusercontent.com/73316633/211169668-5bad946c-3439-4bfb-b3be-e865c04ba539.mp4

**Comment by exezbcz** [comment]
No problem. I mean, it would be better if the text shapes were removed because the text jumps to the next row and it is excessive.

Otherwise it works.

**Review by Jarsen136 — COMMENTED** [review]
code lgtm

**Review by Jarsen136 — APPROVED** [review]

**Comment by yangwao** [comment]
pay 30

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 25.92 USD/KSM ~ 1.157 $KSM
🧗 [FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y](https://kusama.subscan.io/account/FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y)
🔗 [0x08eb0863b10658d548a69c363b59f986431c0e558f60f0f7dfa21a84d3e06284](https://kusama.subscan.io/extrinsic/0x08eb0863b10658d548a69c363b59f986431c0e558f60f0f7dfa21a84d3e06284)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
