### PR TITLE
#4004 covering missing strings

### LINKED ISSUE #4004: Covering the missing strings
To followup on this comment, we need to look through the app again and cover all of the strings as there are still some leftovers 

ref:

- https://github.com/kodadot/nft-gallery/issues/3805
- https://github.com/kodadot/nft-gallery/pull/3886

- [ ] [No1](https://media.discordapp.net/attachments/958772808215822396/1022474753921003520/unknown.png?width=720&height=405)
- [ ] [No2](https://media.discordapp.net/attachments/958772808215822396/1022474753921003520/unknown.png?width=720&height=405)
- [ ] [No3](https://media.discordapp.net/attachments/958772808215822396/1022475114769555506/unknown.png?width=720&height=405)
- [ ] [No4](https://media.discordapp.net/attachments/958772808215822396/1022475583218798642/unknown.png?width=720&height=405)
- [ ] [No5](https://media.discordapp.net/attachments/958772808215822396/1022475801125453924/unknown.png?width=720&height=405)
- [ ] [No6](https://media.discordapp.net/attachments/958772808215822396/1022475801125453924/unknown.png?width=720&height=405)
- [ ] [No7](https://media.discordapp.net/attachments/958772808215822396/1022476065052049438/unknown.png?width=720&height=405)
- [ ] [No8](https://media.discordapp.net/attachments/958772808215822396/1022476065052049438/unknown.png?width=720&height=405)
- [ ] [No9](https://media.discordapp.net/attachments/958772808215822396/1022476336348008448/unknown.png?width=720&height=405)
- [ ] [No10](https://media.discordapp.net/attachments/958772808215822396/1022476514396209202/unknown.png?width=720&height=405)
- [ ] [No11](https://media.discordapp.net/attachments/958772808215822396/1022477116991877140/unknown.png?width=720&height=405)
- [ ] [No12](https://media.discordapp.net/attachments/958772808215822396/1022477605271765052/unknown.png?width=720&height=405)
- [ ] [No13](https://media.discordapp.net/attachments/958772808215822396/1022478026098888775/unknown.png?width=720&height=405)
- [ ] [No14](https://media.discordapp.net/attachments/958772808215822396/1022478404991332382/unknown.png?width=720&height=405)
- [ ] [No15](https://media.discordapp.net/attachments/958772808215822396/1022478404991332382/unknown.png?width=720&height=405)

_Originally posted by @FrankBevr in https://github.com/kodadot/nft-gallery/issues/3918#issuecomment-1254942854_

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #4004
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by prachi00** [comment]
I'll keep updating this PR with more missing strings

**Comment by petersopko** [comment]
> I'll keep updating this PR with more missing strings

Maybe you know this, maybe you don't but I found pretty good plugin which helps identify / scan the codebase for hardcoded strings or possible missed translations:
- https://github.com/lokalise/i18n-ally
- https://plugins.jetbrains.com/plugin/17212-i18n-ally

**Comment by petersopko** [comment]
just a note: we should probably reopen most of the translations once this get done properly

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 34.35 USD/KSM ~ 0.873 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x3be9c118fbee811f9c8ebb4357595686a1bcb64ec1d75774f25a8e8410468b29](https://kusama.subscan.io/extrinsic/0x3be9c118fbee811f9c8ebb4357595686a1bcb64ec1d75774f25a8e8410468b29)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
