### PR TITLE
#3103 Show passion feed in gallery only if it is greater than 10

### LINKED ISSUE #3103: Show passion feed in gallery only if it is greater than 10
### Is your feature request related to a problem?

Passion feed blocking the view by showing empty screen in gallery

https://www.loom.com/share/dd29b39d53a349b195e963b979af6451

### Describe the solution you would like

Adding a check to only turn it on if it has a length greater than 10 maybe, else it should be off

### Describe alternatives you have considered

I have tried this alternative

### Screeenshots

Paste your vision

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #3103
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
Let's imagine I got 2 accounts, one whith passion feed and the other one without.
If I log in with this second account will I see passion feed? Don't we need an else statement?

**Comment by prachi00** [comment]
> Let's imagine I got 2 accounts, one whith passion feed and the other one without. If I log in with this second account will I see passion feed? Don't we need an else statement?

we don't right? because if they have passion feed and the length is greater than 9, then only it will be shown, otherwise not.

**Review by roiLeo — COMMENTED** [review]
So I must own 10 different nfts to be able to see passion list? isn't that a lot? Can we add an option to hide/show passionList?

> > Let's imagine I got 2 accounts, one whith passion feed and the other one without. If I log in with this second account will I see passion feed? Don't we need an else statement?
> 
> we don't right? because if they have passion feed and the length is greater than 9, then only it will be shown, otherwise not.

I thought that when I changed my account it would reload a new passionList but this is not the case at the moment

**Comment by prachi00** [comment]
> So I must own 10 different nfts to be able to see passion list? isn't that a lot? Can we add an option to hide/show passionList?
> 
> > > Let's imagine I got 2 accounts, one whith passion feed and the other one without. If I log in with this second account will I see passion feed? Don't we need an else statement?
> > 
> > 
> > we don't right? because if they have passion feed and the length is greater than 9, then only it will be shown, otherwise not.
> 
> I thought that when I changed my account it would reload a new passionList but this is not the case at the moment

yeah you are right, length should probably be less maybe 2?
there is already an option to hide it right, its a toggle?

**Comment by roiLeo** [comment]
> yeah you are right, length should probably be less maybe 2? 

Yeah around 4.
The problem is that there is nothing to tell me that my home page is different because it is based on my purchases

> there is already an option to hide it right, its a toggle?

I don't see it for landing page, would it be possible to add it in user preferences? same stuff for `/rmrk/explore/?tab=GALLERY` passion feed switch

**Comment by prachi00** [comment]
> > yeah you are right, length should probably be less maybe 2?
> 
> Yeah around 4. The problem is that there is nothing to tell me that my home page is different because it is based on my purchases
> 
> > there is already an option to hide it right, its a toggle?
> 
> I don't see it for landing page, would it be possible to add it in user preferences? same stuff for `/rmrk/explore/?tab=GALLERY` passion feed switch

yeah maybe we can add it to user preferences and have it be ON by default , creating a separate issue for this

**Review by roiLeo — COMMENTED** [review]
Hey, you've got conflict over here

**Comment by prachi00** [comment]
> Hey, you've got conflict over here

fixed

**Comment by prachi00** [comment]
@roiLeo can you approve the PR as well so I can merge it

**Review by roiLeo — APPROVED** [review]

**Comment by prachi00** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 49.63 USD/KSM ~ 2.015 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x8974dac56187936862a36adc3cc5d6e5b57df8167cfb832dc8039c9f2a9fccec](https://kusama.subscan.io/extrinsic/0x8974dac56187936862a36adc3cc5d6e5b57df8167cfb832dc8039c9f2a9fccec)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
