### PR TITLE
#3202 Disable make offer button after offer was made

### LINKED ISSUE #3202: Disable make offer button after offer was made
User currently cannot make offer on same NFT twice, him trying to do so results in error (offer already made).
I'd suggest disabling the button and adding tooltip, so user won't be tempted to try offering again.
image

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [ ] PR closes #3202
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screen Shot 2022-06-25 at 7 36 43 PM

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
If I make an offer, it won't be possible to make another one higher after the first one?
When offer is refused, how does it work? same question when accepted

**Comment by prachi00** [comment]
> If I make an offer, it won't be possible to make another one higher after the first one? When offer is refused, how does it work? same question when accepted

not sure, but if you tey to make another offer there is an error that says 'offer already made'

**Comment by petersopko** [comment]
> If I make an offer, it won't be possible to make another one higher after the first one? When offer is refused, how does it work? same question when accepted

In the current setting, you need to withdraw previous offer in order to submit a new one, like @prachi00  said, there's an error like this after app tries to process transaction:

image

No reason to let user try to go forward with transaction at this point :)

**Review by petersopko — CHANGES_REQUESTED** [review]
Can we please change the wording to "You have already made an offer for this NFT. " ? Other than that, I think this one's good to go :rocket:

**Comment by prachi00** [comment]
> Can we please change the wording to "You have already made an offer for this NFT. " ? Other than that, I think this one's good to go 🚀

done

**Comment by petersopko** [comment]
@prachi00 yeah, even deepsource is screaming https://deepsource.io/gh/kodadot/nft-gallery/run/bb3631a3-02ae-4fe0-82a5-a7b29384f6b5/javascript/, let's fix the console log and merge :)

**Comment by prachi00** [comment]
> @prachi00 yeah, even deepsource is screaming https://deepsource.io/gh/kodadot/nft-gallery/run/bb3631a3-02ae-4fe0-82a5-a7b29384f6b5/javascript/, let's fix the console log and merge :)

oops, didnt realise this one, fixed now

**Review by petersopko — APPROVED** [review]
lgtm

**Comment by petersopko** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 52.3 USD/KSM ~ 1.912 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x6d18bc31ec1d9eff298e96211fc754d2564e853df7303c0f5262238c28f0813c](https://kusama.subscan.io/extrinsic/0x6d18bc31ec1d9eff298e96211fc754d2564e853df7303c0f5262238c28f0813c)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
Seems like I can make an offer? 

https://beta.kodadot.xyz/bsx/gallery/58921832-1?page=1

image

**Comment by petersopko** [comment]
> Seems like I can make an offer?

this is weird, because it works from me from the deploy stated above and also from local latest main 🤔. Beta is same as yours.
image

**Comment by prachi00** [comment]
Screen Shot 2022-07-04 at 6 04 01 PM
@yangwao @petersopko works for me too

**Comment by petersopko** [comment]
> @yangwao @petersopko works for me too

wfm now

**Pull request merged**
