### PR TITLE
style: update gallery item previewer

### LINKED ISSUE #6072: Full screen preview no bg
image
should be more like this: 
image
- navbar should still be visible. Just add the background and maybe move the button to go back to the left (+remove drop shadow and stroke so the image is clear as it can be)

### PR DESCRIPTION
**Pull request by floyd-li**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #6072
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=12zQP2JviSyZzAX2j31F2TR5uSvDNerruSJBWxEZXjW3KMaN)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

图片
图片
图片

### <samp>🤖 Generated by Copilot at 990f26e</samp>

Enhanced the UI of the `GalleryItemPreviewer` component to fit different screen sizes and improve the user experience.

### <samp>🤖 Generated by Copilot at 990f26e</samp>

> _Sing, O Muse, of the skillful coder who refined_
> _The `GalleryItemPreviewer`, a wondrous component of the web,_
> _And made it more responsive and well-aligned,_
> _Like Hephaestus shaping metal with his hammer on his anvil._

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
✅ wfm

**Comment by prury** [comment]
really nice one! working well with non square images as well

**Review by preschian — APPROVED** [review]

**Comment by vikiival** [comment]
pay 15 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $15 @ 4.9 USD/DOT ~ 3.061 $DOT
🧗 [12zQP2JviSyZzAX2j31F2TR5uSvDNerruSJBWxEZXjW3KMaN](https://polkadot.subscan.io/account/12zQP2JviSyZzAX2j31F2TR5uSvDNerruSJBWxEZXjW3KMaN)
🔗 [0xfcac6e47cb4db0570f98d6c9857de1dd1333a40345a30abf9d07db33c979ec8d](https://polkadot.subscan.io/extrinsic/0xfcac6e47cb4db0570f98d6c9857de1dd1333a40345a30abf9d07db33c979ec8d)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
