### PR TITLE
Profile page minor fixes/improvements

### LINKED ISSUE #6927: Profile items not showing, only after filter is applied few times
https://github.com/kodadot/nft-gallery/assets/90852205/b8052001-4eaa-4c4b-a521-5004660281a2

The items are showing pretty randomly. It would be nice if they were displayed on the first visit.  
try here: 
https://canary.kodadot.xyz/ksm/u/EuJAYheXvPywhDqB9YYG9RYbp2iENUqT261FPRhhTioPxSu?buy_now=false
- maybe the solution is skeleton like on explore? 

plus please rename this filter from buy_now to Buy now 
image

### PR DESCRIPTION
**Pull request by pbkompasz**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [ ] Closes #6927 (the label issue)
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [ ] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>)

### <samp>🤖 Generated by Copilot at c595449</samp>

This pull request improves various components related to the collection, item, profile, and search features of the NFT gallery. It fixes some bugs, enhances the error handling and feedback, and adds some conditional rendering and filtering logic. It also updates some type definitions and query parameters to match the data types and API requirements. The main files affected are `CollectionGrid.vue`, `useItemsGrid.ts`, `Activity.vue`, `ProfileDetail.vue`, `FilterButton.vue`, `OrderByDropdown.vue`, and `types.ts`.

### <samp>🤖 Generated by Copilot at c595449</samp>

> _`FilterButton` swaps_
> _props to fix a bug. Watch_
> _`route.query.sort` change._

### CODE REVIEW

**Comment by prury** [comment]
can you please provide screenshots on PR description?

**Comment by daiagi** [comment]
Is this pr related to any issue?

**Comment by yangwao** [comment]
@pbkompasz let's link related issues what you've been trying to do here for others to understand

**Comment by prury** [comment]
Closing this one because there was someone already assigned to this issue and initially this PR had no related issue.

**Pull request closed without merging**
