### PR TITLE
🎉 STATEMINE v0

### PR DESCRIPTION
**Pull request by vikiival**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Related #5879 
- [x] Deployment https://github.com/kodadot/stick

#### Before submitting pull request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality

### <samp>🤖 Generated by Copilot at 878a6df</samp>

This pull request integrates the Statemine chain into the app, adding support for creating, buying, selling, sending, and burning NFTs on the chain. It also improves the performance and usability of some components, and updates the static package and its dependencies. The main files affected are `components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue`, `components/stmn/Create/CreateCollection.vue`, and `libs/static/src/chains.ts`.

### <samp>🤖 Generated by Copilot at 878a6df</samp>

> _Sing, O Muse, of the mighty deeds of the `kodadot` team,_
> _Who forged a path for the `Statemine` chain, the new realm of NFTs,_
> _With skill and craft they shaped the code, the `mimeType` and the `CreateCollection`,_
> _And made the `GalleryItemOffers` shine like the stars of the night._

### CODE REVIEW

**Comment by vikiival** [comment]
> Cannot find module '/home/runner/work/nft-gallery/nft-gallery/node_modules/@kodadot1/static/dist/index.cjs'

Somehow I still get this weird dual routes

**Comment by yangwao** [comment]
Let's make issues for refactor and if @kodadot/qa-guild approves it at some extent, happy to merge v0

**Comment by prury** [comment]
- Interface seems good
- Statemine chain selection working properly
- Some items are not loading properly when trying to see the available collections:
images not loading properly
Items:
itens not loading properly

**Comment by yangwao** [comment]
> * Some items are not loading properly when trying to see the available collections:

can you create separate issue with those collection so we can have a look once this is merged? Thanks! :)

**Comment by prury** [comment]
> > * Some items are not loading properly when trying to see the available collections:
> 
> can you create separate issue with those collection so we can have a look once this is merged? Thanks! :)

done, #5940

**Comment by vikiival** [comment]
There are still some picutures that are uploading to the gateway

Screenshot 2023-05-12 at 21 25 47

**Comment by yangwao** [comment]
Resolving conflicts of code I don't undestand, playing doctor. Let's see if it's builds.

Made follow up for refactor 
- https://github.com/kodadot/nft-gallery/issues/5954

**Comment by yangwao** [comment]
image

**Pull request merged**
