### PR TITLE
#2455 Add to Transfer generate payment link with self  address

### LINKED ISSUE #2455: Add to Tranafer generate payment link with my address
To make life easier for first timer and whatever what reason, add way to people in transfer generate payment link to receive funds on their logged address.

Probably something like button "payout to my address" and copy to clipboard 📋 link

In the end it would copy transfer link with one's logged address.

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2455
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screenshot 2022-02-27 at 8 31 04 PM

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
Looks a bit confusing to me when an adress is set
Screenshot 2022-02-28 at 09-32-30 KodaDot - Kusama NFT Market Explorer

some small changes I would consider adding:
- disable "payout link" if amount is equal 0
- make the difference between the two buttons (color, icon ...)
- wording (button should contain word "copy")
- you could reuse `generatePaymentLink()` function and pass the adress as parameter

**Comment by prachi00** [comment]
Screenshot 2022-02-28 at 4 51 17 PM
@roiLeo added a user icon, since its self payout? does it make sense?

**Comment by roiLeo** [comment]
> @roiLeo added a user icon, since its self payout? does it make sense?

mmh, kinda
Let's wait for another opinion otherwise I was thinking of using: 
- fa-hand-holding-usd
- fa-wallet
- fa-copy
- fa-clipboard

**Comment by prachi00** [comment]
> > @roiLeo added a user icon, since its self payout? does it make sense?
> 
> mmh, kinda Let's wait for another opinion otherwise I was thinking of using one of these icons:
> 
> * fa-hand-holding-usd
> * fa-wallet
> * fa-copy
> * fa-clipboard

yeah I like wallet
Screenshot 2022-02-28 at 7 07 06 PM

**Comment by yangwao** [comment]
I guess so, it's ok

pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 133.58 USD/KSM ~ 0.749 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x219a7240e4b76d863f64a08032870015e5ea30b0de6274117140e5091d33a018](https://kusama.subscan.io/extrinsic/0x219a7240e4b76d863f64a08032870015e5ea30b0de6274117140e5091d33a018)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
