### PR TITLE
fix: block navigation if certain elements are being focused

### LINKED ISSUE #2196: Keyboard shorcuts left-right on nft item detail should not listen on input
I've tried input to change the price in LIST 

when I press the left arrow or right arrow to move in the input box, it changes another nft item detail

https://user-images.githubusercontent.com/5887929/152340640-3921808e-ea7b-4824-9af3-2043c18b790a.mov

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

https://user-images.githubusercontent.com/17953978/152405384-f06ad148-8dcd-4b57-8684-1412d2a9ef99.mov

### What's new?

- [x] PR closes #2196
- [x] Check if currently focused element is one of the following `['input', 'select', 'button', 'textarea']` and block NFT navigation if that is the case

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/gallery/11034169-7cf9daa38281a57331-BSS-LB_SPACESHIP_329-0000000000000329>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by yangwao** [comment]
Curious why it hasn't build?

**Comment by kkukelka** [comment]
> Curious why it hasn't build?
```
Test suite failed to run

    Cannot find module '@babel/plugin-transform-runtime'
```

**Comment by yangwao** [comment]
wfm 

pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 175.69 USD/KSM ~ 0.569 $KSM
🧗 [EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW](https://kusama.subscan.io/account/EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)
🔗 [0x1ecb0ff7e59f738b1fa29dea7c1a0dfb3e670b51c63928272a0670045f0fc59c](https://kusama.subscan.io/extrinsic/0x1ecb0ff7e59f738b1fa29dea7c1a0dfb3e670b51c63928272a0670045f0fc59c)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
