### PR TITLE
fix: some 3D nft in /collection/{id} could not display correctly

### LINKED ISSUE #3534: some 3D nft in /collection/{id}
There's some collection with only 3D items that we can't see.
_I would like to be able to see model preview on collection_ (like spaceship)

Tested on:

- `/rmrk/collection/7cf9daa38281a57331-BSS` (working well)
Capture d’écran 2022-07-22 à 4 25 06 PM

- `/rmrk/collection/FC77C33AB229A2056A-BTFLSUZANN` (not working, but can see text in responsive)
Capture d’écran 2022-07-22 à 4 26 07 PM

Capture d’écran 2022-07-22 à 4 26 17 PM

- `/bsx/collection/2444376227` (😟 bring back my ping pong ball)

Screenshot 2022-07-22 at 16-32-09 Ping Pong Ball KodaDot - Kusama NFT Market Explorer

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3534
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

image

image

### CODE REVIEW

**Review by prachi00 — APPROVED** [review]

**Review by roiLeo — APPROVED** [review]
✅ lgtm

**Comment by prachi00** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 62.29 USD/KSM ~ 0.803 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x9640daff406577d9370d077bd4614d03fbeb6b64c43d35b9633c1ee04513abc8](https://kusama.subscan.io/extrinsic/0x9640daff406577d9370d077bd4614d03fbeb6b64c43d35b9633c1ee04513abc8)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
pay 50

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 62.76 USD/KSM ~ 0.797 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xf4bbd96c80543a925f9f20c9989a8598f3355de3a6f63062d22b251560862fb7](https://kusama.subscan.io/extrinsic/0xf4bbd96c80543a925f9f20c9989a8598f3355de3a6f63062d22b251560862fb7)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
