### PR TITLE
🧹 rename langDir folder to locales

### PR DESCRIPTION
**Pull request by roiLeo**
### PR type

- [x] Refactoring

### What's new?

- [x] PR relate with #3311 
- [x] better view from dev, conventional name

### Screenshot

Capture d’écran 2022-08-19 à 10 04 40 AM

### CODE REVIEW

**Review by kkukelka — APPROVED** [review]
checks out 🍏

**Comment by yangwao** [comment]
We'll need to fill up translations where we are missing them.

image

**Comment by roiLeo** [comment]
> We'll need to fill up translations where we are missing them.

#2 for a more user friendly way of updating translation but we'll still need to add more "word/data" in en.json file

**Comment by yangwao** [comment]
ugh that history, let's put it bit higher 😅

**Pull request merged**
