### PR TITLE
enable classic mint on ahk

### LINKED ISSUE #7049: AssetHub Kusama Minting: Where is Classic mint?
So I'm trying to onboard an artist to mint her collection on AssetHub Kusama, but apparently, we don't have this option anymore. Where is classic minting? It's possible to mint only Waifu or Mass Mint. 

She will be minting on rmrk2 for now. 

## Proof:
Screenshot 2023-08-30 at 15 42 35

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #7049
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)

## Screenshot 📸

- [x] My fix has changed UI

### <samp>🤖 Generated by Copilot at d2eb27a</samp>

Removed a condition that hid the chain switching button on a test chain. This enables testing the chain switching functionality on `components/navbar/CreateDropdown.vue`.

### <samp>🤖 Generated by Copilot at d2eb27a</samp>

> _`v-if` condition_
> _gone from `NeoDropdownItem`_
> _now ahk can show_

### CODE REVIEW

**Comment by daiagi** [comment]
image

**Comment by prury** [comment]
today is minting friday

**Comment by yangwao** [comment]
> today is minting friday

I think this is hard to test until this will pass
- https://kusama.polkassembly.io/referenda/263

**Review by vikiival — APPROVED** [review]
Made the same

**Comment by vikiival** [comment]
> I think this is hard to test until this will pass


Tested on AssetHub Polkadot and code is the same

**Pull request merged**
