### PR TITLE
Top up all packages

### PR DESCRIPTION
**Pull request by vikiival**
- **:arrow_up: deps**
- **:arrow_up: polkadot 10.13.1**
- **:arrow_up: kodadot // sub-api**

**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Chore

## Context

Top up all polkadot packages + need identicon for BASE :)

#### Before submitting pull request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ahp/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [ ] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>)

#### Community participation

- [ ] [Are you at Koda Ecosystem Telegram?](https://t.me/koda_eco)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

Screenshot 2024-04-23 at 10 33 21

### CODE REVIEW

**Comment by vikiival** [comment]
@prury-temporary can u please check?

**Review by Jarsen136 — APPROVED** [review]
image

**Comment by prury** [comment]
checking

**Comment by prury** [comment]
nft creation:
https://deploy-preview-10130--koda-canary.netlify.app//ahk/gallery/276-39

transfer:
https://polkadot.subscan.io/extrinsic/0xacee63f19d3b3a4778fe0dee72c88b287727269e03fc9eceabee5c7be9a5ca46

teleport:
https://polkadot.subscan.io/tx/0x32852d826ee0ccfdee3b12046fb66df3ded19f9acae6a4781c9df2868091e322

drop minted/listed: 
https://assethub-kusama.subscan.io/tx/0xf6013d4b63d3381496009ae67a149e06aa047f13cf09259f97fe61fa750ce5f3
https://assethub-kusama.subscan.io/tx/0x9cec799c5a8be058aeaa547448d5de14d405d1c69afdd9f1f20dddc0c141476a

collection created:
https://deploy-preview-10130--koda-canary.netlify.app/ahk/collection/421

nft transfer: 
https://assethub-kusama.subscan.io/tx/0xaae99e8d97553a42c6cc7a8cda5589048087c69a307c02585c688abc79ef877d

**Review by preschian — APPROVED** [review]

**Comment by vikiival** [comment]
- Closes #9922

**Pull request merged**
