### PR TITLE
fix/bug when navigating back to collection page

### LINKED ISSUE #9440: Going back from Item Preview to Collection Preview messes up URL
Idk how to explain it, so I made a video. I was checking [Echo collection](https://kodadot.xyz/ahp/collection/95) with the "art view" filter on. Once I opened a random NFT to check it and then returned back to the collection view - some NFTs from the collection view disappeared. I did it again and all NFTs in the collection disappeared.

Check the video:
---
Also, check how the URL is changing. Probably that's the problem.

https://github.com/kodadot/nft-gallery/assets/104380776/53c69f55-20aa-4787-a4cc-105a48a5f0f7

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #9440

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)

### CODE REVIEW

**Comment by hassnian** [comment]
would be interesting to know to how users interact with the collection gallery page. 

tested it a bit and unless you open each nft on new tab the ux is impacted quite a lot if the user is doing what @JustLuuuu  `s video showed  but idk

> b. fix scrolling, when navigating to page n, all pages 0 => n should be loaded 

I feel like the option b you mention would have been a better fit 

regardless LGTM  🚀

**Comment by daiagi** [comment]
> the ux is impacted quite a lot

What do you mean, this fix is harming performance / slow down 
or?

**Comment by hassnian** [comment]
> > the ux is impacted quite a lot
> 
> It's a trade off
> 
> Loading all pages until page n would be slow to load, with speed decreasing as n increases
> 
> Navigation back to top is annoying, but speedy
> 
> We tried keep alive before to improve performance and it was a disaster

fair enough.

**Comment by prury** [comment]
> > We tried keep alive before to improve performance and it was a disaster
> 
true

open new tab with middle mouse ftw

**Review by prury — APPROVED** [review]

**Review by preschian — APPROVED** [review]

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 7.77 USD/DOT ~ 3.861 $DOT
🧗 [1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8](https://polkadot.subscan.io/account/1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)
🔗 [0x2a9dcb7b6f093909ba9a6485d69547d6dffc7b4b74c7745b37b4e279bb0fee08](https://polkadot.subscan.io/extrinsic/0x2a9dcb7b6f093909ba9a6485d69547d6dffc7b4b74c7745b37b4e279bb0fee08)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
