### PR TITLE
fix: Not possible to play with generative art drop page when not connected

### LINKED ISSUE #7888: Not possible to play with generative art drop page when not connected
It's not possible to play with generative drops (Generate new NFTs) if you are not logged in. It would be cool if even people who are not connected could play with it. For example, if someone is checking it on the phone, they have no chance to try this in a normal browser via phone. This may look like its not working.

Screenshot 2023-10-30 at 12 11 56

## Solution
1. allow _generate new_ option to people who are not connected
2. or add text under generate new saying: connect your wallet first. Here:
Screenshot 2023-10-30 at 12 19 37

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix
  - [x] Feature

  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #7888
  - [ ] Requires deployment <snek/rubick/worker>

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

image

  ## Copilot Summary
  copilot:summary

  copilot:poem

### CODE REVIEW

**Comment by prury** [comment]
@Jarsen136 i think one point could be improved, let's say I'm disconnected and i find one image i like, i click on connect wallet, but as soon as i connect, the page runs the generate new automatically and i lose that image i wanted. (same happens when disconnecting)

**Comment by Jarsen136** [comment]
> @Jarsen136 i think one point could be improved, let's say I'm disconnected and i find one image i like, i click on connect wallet, but as soon as i connect, the page runs the generate new automatically and i lose that image i wanted. (same happens when disconnecting)

It was implemented purposely like that because the image consists of the current address and a random value. When you connect/disconnect the wallet, the image will change accordingly. @prury

**Comment by prury** [comment]
> > @Jarsen136 i think one point could be improved, let's say I'm disconnected and i find one image i like, i click on connect wallet, but as soon as i connect, the page runs the generate new automatically and i lose that image i wanted. (same happens when disconnecting)
> 
> It was implemented purposely like that because the image consists of the current address and a random value. When you connect/disconnect the wallet, the image will change accordingly. @prury

hmm i see, ok then i guess

**Review by daiagi — APPROVED** [review]

**Review by preschian — APPROVED** [review]

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Pull request merged**
