### PR TITLE
refactor: little bit cleanup drops component

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Related https://github.com/kodadot/private-workers/pull/76#issuecomment-1960936933
- [ ] Safe to merge after deployment from https://github.com/kodadot/private-workers/pull/76

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)

### CODE REVIEW

**Comment by preschian** [comment]
In this PR, I removed `userMintedNftId` usage. If I drill down the props, it is being used in this component. https://github.com/kodadot/nft-gallery/blob/87a8bddef68d5a2dab8159ba598dd9d01a1cd92e/components/collection/drop/MintSection/MintSection.vue#L34-L44

But `MintSection.vue` is no longer used, I guess? There are no component imports that

cmiiw @Jarsen136 @vikiival

**Comment by Jarsen136** [comment]
> But `MintSection.vue` is no longer used, I guess? There are no component imports that

Yes, It's not used.

**Comment by prury** [comment]
@preschian so far so good:
its filling the missing ids 
image

next ones should be: 28 , 31 ,32
will keep going till it goes back to 42

**Comment by prury** [comment]
done! 

image

**Comment by vikiival** [comment]
@Jarsen136 , @daiagi can I ask you for the review?

**Review by Jarsen136 — APPROVED** [review]

**Review by daiagi — APPROVED** [review]

**Comment by yangwao** [comment]
@preschian let's resolve conflicts and we can merge it

**Comment by yangwao** [comment]
Thanks, I hope it won't break something! 
pay 60 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $60 @ 7.9 USD/DOT ~ 7.595 $DOT
🧗 [1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p](https://polkadot.subscan.io/account/1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)
🔗 [0x2ab8d86b2cddd8689cc33d44d264986d69b03db06f38f684cbd47a2b2dcdd67a](https://polkadot.subscan.io/extrinsic/0x2ab8d86b2cddd8689cc33d44d264986d69b03db06f38f684cbd47a2b2dcdd67a)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
