### PR TITLE
fix: Newly minted nft have Carbonless properties by default (bsx)

### LINKED ISSUE #3265: Newly minted nft have Carbonless properties by default (bsx)
Is it normal? I record of a "carbonless" switch which allowed to add or not the property

### LINKED ISSUE #4010: Traits on Basilisk
We are still by default attaching 1 trait (carbonless) to every NFT which I find weird
Pasted image 20220923084319
and it would be perhaps desirable to get rid of it or give user an option to select it voluntarily (I remember talking about this with @roiLeo somewhere)
image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #4010, closes #3265

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

/snek/create

image

### CODE REVIEW

**Comment by petersopko** [comment]
Couple of comments here:
1. On gallery item we are showing `traits`, here we've added option to add KodaForest `property` and we can also add `attributes`. And on RMRK, we call these `tags` when minting and again `traits` on item detail. Are all of these the same thing and can we have unified name for it? I'd go with `traits`, but I need final nod from either @vikiival or @yangwao, I'm not sure if `traits` isn't a bit misleading. Unfortunately even the data isn't the same:

Basilisk traits: 
image
RMRK traits:
image
Moonriver traits:
image

3. Once we have toggled the "add KodaForest", I'd expect it to show up in the list of other `traits` (attributes/properties)?
image

**Review by petersopko — CHANGES_REQUESTED** [review]
some stuff to figure out

**Comment by Jarsen136** [comment]
> Are all of these the same thing and can we have unified name for it
>
IMO, we could not rename the property of nft that minted before.


> 
> 3. Once we have toggled the "add KodaForest", I'd expect it to show up in the list of other `traits` (attributes/properties)?

I would take a try.

**Comment by petersopko** [comment]
> IMO, we could not rename the property of nft that minted before.

I don't mean renaming the data in indexer, just the way we are showing it on front end. @yangwao can you please take a look?

**Comment by Jarsen136** [comment]
>Once we have toggled the "add KodaForest", I'd expect it to show up in the list of other traits (attributes/properties)?


✅ Done

How about now?
image

image

**Comment by petersopko** [comment]
@Jarsen136 alright, can we do trait: KodaForest, value: Carbonless? "value:1" looks really weird and doesn't really say anything. Also, please rename the "property" to "attribute", let's stick with that one.
image
On gallery item detail, let's rename the "Traits" to "Attributes" where each attribute will have it's "Trait" and "Value" (same as before), I think this way it'll have some logical coherence. 
image

**Comment by vikiival** [comment]
Just FYI :) 

Screenshot 2022-09-29 at 14 10 50

So fix: 
remove the switch
but having that in the traits is a nice addition.

**Comment by petersopko** [comment]
I guess if we don't want to give users choice of disabling this trait in the screen where they are actually deciding about attributes (create) then this works for me ✅

**Comment by roiLeo** [comment]
Can't we reintroduce toggle on create? It's really difficult for an end user to find the "minting settings"

Why do we have a new "Kodaforest" attribute? I find it frustrating that I'm not able to remove it

**Comment by Jarsen136** [comment]
Alright. Let's give the choice to users. I guess it would be better.

image

**Review by petersopko — APPROVED** [review]

**Review by prachi00 — APPROVED** [review]

**Comment by petersopko** [comment]
@vikiival pls take a look if it's okay with you

**Comment by vikiival** [comment]
Lgtm

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 37.57 USD/KSM ~ 1.331 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x0f53557e7c441054509842c80917489978c9ba9f89e89205ff7be6d4c350b048](https://kusama.subscan.io/extrinsic/0x0f53557e7c441054509842c80917489978c9ba9f89e89205ff7be6d4c350b048)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
