### PR TITLE
#4262 redesign loading screen

### LINKED ISSUE #4262: Redesign Loading screen
Time to redesign our most precious component, which people often see. 
Especially if waiting for a transaction, indexer is down, some glitch happened on our backend or loading of the profile, collection,gallery, items, or explorer takes a while
### Old
image

### New
image
- figma file: landing page handoff, second page: https://www.figma.com/file/3iOjW12ERFRDSVnpLuhQmf/landing-page-handoff?node-id=0%3A1
- dark mode is also there
- text has max length, so the box stays always the same when the text changes - please make that so the maximum did you know phrase fits there. 
- svg animation: 
KodaDot_preloader_final_nov_22

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## PR Context?

- [x] Closes #4262
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screen Shot 2022-11-06 at 2 55 45 PM
Screen Shot 2022-11-06 at 2 56 09 PM

### CODE REVIEW

**Review by kkukelka — APPROVED** [review]
code lgtm

**Comment by exezbcz** [comment]
looks good

**Comment by exezbcz** [comment]
looks good

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 33.25 USD/KSM ~ 1.504 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0xa047229e2ade177fbbf095b52ffb39dee137dd15d2f8c1abce101773dbe36c4e](https://kusama.subscan.io/extrinsic/0xa047229e2ade177fbbf095b52ffb39dee137dd15d2f8c1abce101773dbe36c4e)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
