### PR TITLE
style: mass listing selector popup

### LINKED ISSUE #7175: Mass listing followup - selector popup
after: 
- #7076 

image

Should look like this: 
image
- consists of primary buy button 
- height 55px 

Select all and clear all buttons -> k-grey

Please space it so it does not collapse with the go-up button 
image

### PR DESCRIPTION
**Pull request by floyd-li**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #7175
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

图片

### <samp>🤖 Generated by Copilot at 09f8002</samp>

Improved the appearance and alignment of the `ListingCartMini` component to match the design mockup. Removed unnecessary border and adjusted colors.

### <samp>🤖 Generated by Copilot at 09f8002</samp>

> _`ListingCart` styled_
> _Colors, border, position_
> _Harmonize in spring_

### CODE REVIEW

**Comment by daiagi** [comment]
@floyd-li 
1. looks like the fonts are bigger than what required in the issue
2. please move `no-border-left` to global.scss

**Comment by exezbcz** [comment]
> after: 
> - #7076 
> 
> 
> image
> 
> Should look like this: 
> image
> - consists of primary buy button 
> - height 55px 
> 


Please check the height again

**Comment by daiagi** [comment]
looks like it's missing an "s"

image

**Review by daiagi — APPROVED** [review]
other then the "s"
lgtm

**Comment by exezbcz** [comment]
@daiagi 1 item - list item

**Comment by daiagi** [comment]
@exezbcz 
image

**Review by Jarsen136 — APPROVED** [review]

**Comment by prury** [comment]
@exezbcz what about hover effect on Clear all and select all? is it supposed not to have any in this modification?

**Comment by exezbcz** [comment]
smooth, sorry for the delay, oki for me thanks!

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 4.05 USD/DOT ~ 7.407 $DOT
🧗 [13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A](https://polkadot.subscan.io/account/13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A)
🔗 [0x27da486d2a7c1138992530b630c0c580b884dcc949e10d815f3c4b83024c0946](https://polkadot.subscan.io/extrinsic/0x27da486d2a7c1138992530b630c0c580b884dcc949e10d815f3c4b83024c0946)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
