### PR TITLE
quick and dirty  mobile

### LINKED ISSUE #6163: Continue unlockable items page
Tasks
---
- [x] https://github.com/kodadot/nft-gallery/issues/6204
- [ ] refactor unlockable items by comments in https://github.com/kodadot/nft-gallery/pull/6137#discussion_r1217605814
- [ ] add strip to running collection per drop (reuse same item from galery item/landing)
- [x] #6185 
- [x] #6205 
- [x] #6206 

happy line
---
- [x] #6186 
- [x] #6164
- [x] https://github.com/kodadot/nft-gallery/issues/6171

working version
---
- https://canary.kodadot.xyz/stmn/unlockable

_Originally posted by @daiagi in https://github.com/kodadot/nft-gallery/pull/6137#pullrequestreview-1462245688_

### LINKED ISSUE #6164: fix mobile as noted before

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Needs Visual check

- @exezbcz  please review

## Context

- [x] Closes #6164
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)

## Screenshot 📸

- [x] My fix has changed UI

image

### <samp>🤖 Generated by Copilot at 998cd91</samp>

Improved the responsiveness and layout of the unlockable collection components. Adjusted the size and position of the image slider, thumbnails, banner, and columns in `ImageSlider.vue`, `UnlockableContainer.vue`, and `CollectionBanner.vue` using media queries and Bulma modifiers.

### <samp>🤖 Generated by Copilot at 998cd91</samp>

> _Sing, O Muse, of the skillful web developers_
> _Who made the collection banner and the image slider_
> _Responsive and adaptive to the varied devices of mortals_
> _With media queries and object-fit, like Hephaestus shaping metal_

### CODE REVIEW

**Comment by Jarsen136** [comment]
Something not works as expected. 
image

image


Just FYI, the mobile design is here https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=395-6222&t=T8FVk2HlFvn5mj1C-0

**Comment by yangwao** [comment]
testing
https://deploy-preview-6165--koda-canary.netlify.app/stmn/unlockable

**Comment by yangwao** [comment]
I think we should change text, will make follow up issue

image

**Comment by yangwao** [comment]
I think it's good for v0 !

**Comment by yangwao** [comment]
uh githb not today 
image

pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 5.09 USD/DOT ~ 9.823 $DOT
🧗 [1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8](https://polkadot.subscan.io/account/1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)
🔗 [0xde741c244215138820bfa77c0b52ec593acdfdc513855ddc7fe78d902207d97f](https://polkadot.subscan.io/extrinsic/0xde741c244215138820bfa77c0b52ec593acdfdc513855ddc7fe78d902207d97f)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
