### PR TITLE
fix: close notification modal after clicking a notification

### LINKED ISSUE #7071: Notification sidebar won't close when clicking on a notification
### What happened?

true for mobile and desktop: 

https://github.com/kodadot/nft-gallery/assets/36627808/4a61324e-18da-421e-9703-820ca52e9bbb

### PR DESCRIPTION
**Pull request by xiiiAtCn**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #7071 
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] my DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=12jXHf7yYF4wTRjDPbwFB24V1nVRPRkuU2S8Ke5ZWTfvyBGW&usdamount=8.82&donation=true)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

### <samp>🤖 Generated by Copilot at 870fcf7</samp>

This pull request improves the user experience of the notification system by enabling the user to mark notifications as read and close the modal by clicking on the notification items. It uses the Vue 3 composition API and the native modifier for the `nuxt-link` element in the `NotificationItem` component, and adds a click event handler to the `NotificationBoxModal` component.

### <samp>🤖 Generated by Copilot at 870fcf7</samp>

> _To close the modal with a click_
> _They added a handler that's slick_
> _Using `closeModal`_
> _On `NotificationItem`_
> _It works for each notification pick_

### CODE REVIEW

**Review by Jarsen136 — APPROVED** [review]

**Comment by prury** [comment]
works fine the first time, but when trying the second one it would not close the menu: 

https://github.com/kodadot/nft-gallery/assets/36627808/5c2d6999-bbe7-4c20-8cb4-91069c48622b

**Comment by xiiiAtCn** [comment]
> works fine the first time, but when trying the second one it would not close the menu:

@prury I have fixed it. And I find cart modal has the similar bug. Please check them together

**Comment by prury** [comment]
> > works fine the first time, but when trying the second one it would not close the menu:
> 
> @prury I have fixed it. And I find cart modal has the similar bug. Please check them together

cool, thank you! 

when checking this PR last time, a bug happened to me but went away after refreshing, i thought it was just a one time thing, but it happened to me again today, can you try to reproduce it? 

if you mess enough times with the menu items, the icons disappear : 

image

**Comment by xiiiAtCn** [comment]
> when checking this PR last time, a bug happened to me but went away after refreshing, i thought it was just a one time thing, but it happened to me again today

All these missing icons are `FontAwesome Icon`. These fonts are loaded from cdn: `https://ka-p.fontawesome.com/`.  I blocked this domain and icons disappeared.  So there's a big chance that network latency  causes these icons missing.
(As you can see, `search` and `cart` icon are images so they both aren't affected)

**Review by preschian — APPROVED** [review]

**Comment by prury** [comment]
> 



> > when checking this PR last time, a bug happened to me but went away after refreshing, i thought it was just a one time thing, but it happened to me again today
> 
> @prury All these missing icons are `FontAwesome Icon`. These fonts are loaded from cdn: `https://ka-p.fontawesome.com/`. I blocked this domain and icons disappeared. So there's a big chance that network latency causes these icons missing. (As you can see, `search` and `cart` icon are images so they both aren't affected)

ok, ty!

**Review by prury — APPROVED** [review]

**Review by Jarsen136 — APPROVED** [review]

**Comment by xiiiAtCn** [comment]
@yangwao sir, this pr is ready for merge

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 4.25 USD/DOT ~ 11.765 $DOT
🧗 [12jXHf7yYF4wTRjDPbwFB24V1nVRPRkuU2S8Ke5ZWTfvyBGW](https://polkadot.subscan.io/account/12jXHf7yYF4wTRjDPbwFB24V1nVRPRkuU2S8Ke5ZWTfvyBGW)
🔗 [0x62b2c1decf9a67259c151c447e0573be1a498790e44f89230840ad2953e3028e](https://polkadot.subscan.io/extrinsic/0x62b2c1decf9a67259c151c447e0573be1a498790e44f89230840ad2953e3028e)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
