### PR TITLE
✨ gallery order by Most emoted

### PR DESCRIPTION
**Pull request by roiLeo**
### PR type

- [x] Feature

### What's new?

- [x] PR related with #1174 
- [x] `/explore/gallery` order by "Most reacted"
- [x] hide Guardians collection in DenyList (rmrk eggs)

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=HguGafrfk8nRP9a4tgJf7hLvSSFie8GtkDjyWFHQ2kDUAMc)

### Screenshot

Capture d’écran 2022-04-26 à 2 48 14 PM

### CODE REVIEW

**Review by kkukelka — APPROVED** [review]
very cool 😎

**Comment by yangwao** [comment]
Seems sorting by Most Reacted takes time? Maybe writing resolver to rubick?

**Comment by roiLeo** [comment]
> Seems sorting by Most Reacted takes time? Maybe writing resolver to rubick?

hmm... I don't think it's needed, it loads quickly for me (like instant)

**Comment by yangwao** [comment]
restarted chrome, so it's not that slow, it was like 10s, but still ain't fastest :|

Oh I see, once I click on most reacted, switch to old first, then most reacted, it's almost instant. 

Probably something to do query once caches it's goes fast

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 160.94 USD/KSM ~ 0.621 $KSM
🧗 [HguGafrfk8nRP9a4tgJf7hLvSSFie8GtkDjyWFHQ2kDUAMc](https://kusama.subscan.io/account/HguGafrfk8nRP9a4tgJf7hLvSSFie8GtkDjyWFHQ2kDUAMc)
🔗 [0xbada733bb91f426c7be029bafcd238be12b5887849c91f91e80eb13e9051a38d](https://kusama.subscan.io/extrinsic/0xbada733bb91f426c7be029bafcd238be12b5887849c91f91e80eb13e9051a38d)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
