### PR TITLE
feat: Price sort by logic

### LINKED ISSUE #8890: Price sort by logic
so, currently, our price filter, either low to high or high to low only work when buy now filter is applied 

i don't know what tunel vision I had, but it should work differently

image

## changes
- since its "sort by" it should actually sort without any other filter applied 
- when the low to high filter is active, show listed first, sorted by the sort by filter, and then leave the rest untouched. It takes all the supply and just reorders it so the listed ones are on top.
- then, when "buy now" is active as well, it filters out only the listed

**sort by price + buy now = listed items sorted by price** 

**sort by price = all items sorted based on price, non listed are there as well, but only after the listed ones**

**lets also rename "buy now" to listed** 

price range should work the same

image
- it does not show the ones with 1 dot first

probably this needs to be changed, sorry for that 
- https://github.com/kodadot/nft-gallery/pull/8809

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Needs Design check

- @exezbcz please review

## Context

- [x] Closes #8890

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI;

### CODE REVIEW

**Comment by hassnian** [comment]
@exezbcz pls check , let me know if it's working as you mentioned

**Comment by exezbcz** [comment]
nope, not working yet 

image


when this filter is applied it should show listed first - sorted by price **and then the rest**

**Comment by hassnian** [comment]
> sorted by price and then the rest

@roiLeo this is not possible only using `tokenListWithSearch` query right ?

**Comment by roiLeo** [comment]
> > sorted by price and then the rest
> 
> @roiLeo this is not possible only using `tokenListWithSearch` query right ?

Doesn't look like it's possible with `tokenEntities` this might be indexer issue, let's open issue on https://github.com/kodadot/stick/issues with what you need

**Comment by yangwao** [comment]
waiting to resolve this 
- https://github.com/kodadot/stick/issues/188

**Review by preschian — COMMENTED** [review]
blocked by this. lets re-review again once ready

> waiting to resolve this
> 
> * [orderBy price ascending should put prioritise "listed" tokens stick#188](https://github.com/kodadot/stick/issues/188)

**Comment by yangwao** [comment]
@vikiival can do silent release of new Stick for you
- https://github.com/kodadot/stick/pull/194

**Comment by vikiival** [comment]
https://app.subsquid.io/squids/arrow-speck/v1

**Comment by hassnian** [comment]
> https://squid.subsquid.io/arrow-speck/v/v1/graphql

CleanShot 2024-02-22 at 14 31 22@2x

can you deploy it again: d

thanks

**Comment by vikiival** [comment]
meanwhile we run arrowsquid, prob continue?

**Comment by hassnian** [comment]
> meanwhile we run arrowsquid, prob continue?

yes

>when the low to high filter is active, show listed first, sorted by the sort by filter, and then leave the rest untouched. It takes all the supply and just reorders it so the listed ones are on top.

we have 

CleanShot 2024-04-11 at 16 58 54@2x

and we need `price_ASC_NULL_LAST`

**Comment by vikiival** [comment]
yes

**Comment by vikiival** [comment]
I have missunderstood your question @hassnian 

closing as this is not resolved

https://t.me/HydraDevs/9433

**Comment by hassnian** [comment]
@vikiival any updates ? is https://github.com/kodadot/stick/issues/275 the blocker ?

**Comment by vikiival** [comment]
Yes

**Comment by hassnian** [comment]
new pr https://github.com/kodadot/nft-gallery/pull/10529

**Pull request closed without merging**
