### PR TITLE
🔧 onboarding Markdown text

### LINKED ISSUE #7885: massming onboarding code block broken
pretty sure that there used to be a code block here with proper new lines and indents:

image

actually if people follow this as it is right now the txt will not work

also should add line in the txt description saying that need a line gap between one block and another (block being the details of single nft) @exezbcz 

this space is important:
image

### PR DESCRIPTION
**Pull request by roiLeo**
- close #7885 
- <s>⚠️ 'v-html' directive can lead to XSS attack.eslint [vue/no-v-html](https://eslint.vuejs.org/rules/no-v-html.html)</s> https://github.com/kodadot/nft-gallery/pull/7887/commits/e78b75277357a7c31c833c5b62052aad3565c5c0

Screenshot 2023-10-30 at 11-34-41 Massmint - Onboarding One Stop Shop for Polkadot NFTs

### CODE REVIEW

**Review by preschian — COMMENTED** [review]
add allowed tag here? https://github.com/kodadot/nft-gallery/blob/main/plugins/vueHtmlSecure.ts#L7

**Comment by roiLeo** [comment]
> add allowed tag here? https://github.com/kodadot/nft-gallery/blob/main/plugins/vueHtmlSecure.ts#L7

Looks a bit different
Screenshot 2023-10-30 at 11-58-51 KodaDot - NFT Market Explorer

**Review by preschian — APPROVED** [review]

**Comment by daiagi** [comment]
great.
would you mind adding something about the needed line gap in txt file?

**Review by daiagi — APPROVED** [review]

**Comment by exezbcz** [comment]
@daiagi 
image
yes, or maybe like comment?

**Comment by roiLeo** [comment]
> yes, or maybe like comment?

IMO this can break if user copy/paste with comment (if not managed on upload).

**Pull request merged**
