### PR TITLE
Replace magic wand with dice

### LINKED ISSUE #1602: Replace magic wand with dice
Seems when I google "random", more dices appears than magic wands, so it would be way more recognized what it does for now

image

### PR DESCRIPTION
**Pull request by lohba**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇  _ Do a quick check before the merge. 

### PR type
- [ ] Bugfix
- [ ] Feature
- [X] Refactoring

### Before submitting Pull Request, please make sure:
- [X] My contribution builds **clean without any errors or warnings**
- [X] I've merged recent default branch -- **main** and I've no conflicts
- [X] I've tried respect high code quality standards
- [X] I've didn't break any original functionality
- [X] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything works
- [ ] I found edge cases

### What's new?
- [X] PR closes #1602 

### Had issue bounty label ?
- [X] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EAeSkdwjgMBmVFcACVFGzqxmGqib8k8uXdNmtWTcWsLoGPU)

### Community participation
- [X] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [X] My fix has changed **something** on UI, a screenshot for others, is best to understand changes.
Screen Shot 2021-12-27 at 12 24 28 PM

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
lgtm

**Comment by yangwao** [comment]
What are other "dices" as options? Was thinking of something easier recognizable on a small icon. If there is nothing else good around, let's go with this one then

**Comment by vikiival** [comment]
> What are other "dices" as options? Was thinking of something easier recognizable on a small icon. If there is nothing else good around, let's go with this one then

@yangwao you have other options listed in the issue #1602

**Comment by yangwao** [comment]
@lohba let's post your KSM address in template

**Comment by yangwao** [comment]
Perfect, I’ve sent the payout https://kusama.subscan.io/extrinsic/0x00915c8de0bdc4a8b91dab001bf9b3c538e397d80139e88fdebd1f177c6eaae0

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/

**Pull request merged**
