### PR TITLE
fix: btn style on notifier

### LINKED ISSUE #3734: Fix share icons on minted NFT
Minted NFT, refreshed page (had to, tracked in #3722) and these are the icons I am looking at
RMRK/light mode, but please, test this for bsx as well
image

### PR DESCRIPTION
**Pull request by KngZhi**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3734
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer?target=HgpGWWmqrw8t6viwSy6LPcTVr2SuVPKWW5ArdNp2xCJY2U4)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to un

image

image

image

image

#### icon issue
image

### CODE REVIEW

**Review by JustLuuuu — APPROVED** [review]
wfm

**Review by roiLeo — COMMENTED** [review]
Instead of doing `:type="btnType"` you can do `:type="{'is-primary': isPrimary}` or in you're case `:type="[{'is-primary': isPrimary}, 'is-bordered-light share-button']"`

Things is I find the design of the notification not great, you can't really seen when you hover buttons, we really need to refactor this notification into something more reusable & same thing for Sharing component as I sense it will be harder to maintain.
Plus `is-primary` shouldn't be added next to `is-border-light` because that 2 different types of buttons.

**Comment by roiLeo** [comment]
Here's what I would like to see:
- Create new success message component (in shared folder)
- add class `has-text-white` on `subtitle` & `title` in this new component (remove `has-text-black`)

in Sharing component:
- move component outside rmrk folder
- wrap `<b-button />` with `<p class="control">` 
- remove `<div class="share">`
- remove `.share-button` ⚠️ cypress tests might break

**Comment by KngZhi** [comment]
got it.

**Comment by KngZhi** [comment]
just update on RMRK, if everything goes well, will update to other chains.
@roiLeo

**Review by roiLeo — APPROVED** [review]
perfect!

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 54.63 USD/KSM ~ 0.915 $KSM
🧗 [HgpGWWmqrw8t6viwSy6LPcTVr2SuVPKWW5ArdNp2xCJY2U4](https://kusama.subscan.io/account/HgpGWWmqrw8t6viwSy6LPcTVr2SuVPKWW5ArdNp2xCJY2U4)
🔗 [0x87f9a90715987a38fefe01991b571ac01e2730ee18b68117520e94fd7be2e238](https://kusama.subscan.io/extrinsic/0x87f9a90715987a38fefe01991b571ac01e2730ee18b68117520e94fd7be2e238)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
