### PR TITLE
#5967 dropdown visual changes

### LINKED ISSUE #5967: dropdown visual changes
As @JustLuuuu has OCD about sorting items in the collection by name, my OCD is colors and pixel alignment :D 

image
- this isn't true black; it looks a bit like the black we use in dark mode - can you please check the shades? 
- same here: 
image

can you also please make the language category the same height as the other items 
image
- there is also a 14px font size - change that to standard 16px please

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 \_\_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5967
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

Screen Shot 2023-05-15 at 9 36 10 PM

### <samp>🤖 Generated by Copilot at dc6faf2</samp>

Improved the design and accessibility of the profile menu in the navbar, especially the language option. Added a new class `language-heading` in `styles/layouts/_main-navigation.scss` and applied it to the `b-dropdown-item` element in `components/navbar/ProfileDropdown.vue`.

### <samp>🤖 Generated by Copilot at dc6faf2</samp>

> _The profile menu got a new look_
> _With a `language-heading` class for the book_
> _The `b-dropdown-item` changed its hue_
> _And the code formatting improved too_
> _Now the menu is more appealing to the cook_

### CODE REVIEW

**Comment by vikiival** [comment]
cc @exezbcz

**Review by daiagi — APPROVED** [review]

**Comment by vikiival** [comment]
pay 20 usd

**Comment by yangwao** [comment]
sounds like bot wants upgrade for new links

**Comment by vikiival** [comment]
pay 20 usd

**Review by vikiival — APPROVED** [review]

**Pull request merged**
