### PR TITLE
🔧 collection small layout

### LINKED ISSUE #4740: Change default view on collection detail to small display by default
Let's switch to small display in collection detail by default

image

image

### PR DESCRIPTION
**Pull request by roiLeo**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Context

- [x] Closes #4740 

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=GemsyWUUtZU5HAiEQJqqgVz4YkekKXnmutYryBhbcVD4YW3)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

⏳

### CODE REVIEW

**Comment by vikiival** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 36.66 USD/KSM ~ 0.546 $KSM
🧗 [GemsyWUUtZU5HAiEQJqqgVz4YkekKXnmutYryBhbcVD4YW3](https://kusama.subscan.io/account/GemsyWUUtZU5HAiEQJqqgVz4YkekKXnmutYryBhbcVD4YW3)
🔗 [0x5ff2e420b493b4352c682d37d04f04879c09122fc74edebc4f5d60c227664d84](https://kusama.subscan.io/extrinsic/0x5ff2e420b493b4352c682d37d04f04879c09122fc74edebc4f5d60c227664d84)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
pay 20

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 34.98 USD/KSM ~ 0.572 $KSM
🧗 [GemsyWUUtZU5HAiEQJqqgVz4YkekKXnmutYryBhbcVD4YW3](https://kusama.subscan.io/account/GemsyWUUtZU5HAiEQJqqgVz4YkekKXnmutYryBhbcVD4YW3)
🔗 [0x124799aa9120241a090e40e4335f96e207ac554a91c41a17951fb557e26870d4](https://kusama.subscan.io/extrinsic/0x124799aa9120241a090e40e4335f96e207ac554a91c41a17951fb557e26870d4)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
