### PR TITLE
beta update

### PR DESCRIPTION
**Pull request by yangwao**
### <samp>🤖 Generated by Copilot at a8c8f8d</samp>

This pull request introduces various improvements and updates to the KodaDot app, such as: 

- https://github.com/kodadot/nft-gallery/pull/5892
- https://github.com/kodadot/nft-gallery/pull/5890
- https://github.com/kodadot/nft-gallery/pull/5885
- https://github.com/kodadot/nft-gallery/pull/5871
- https://github.com/kodadot/nft-gallery/pull/5860
- https://github.com/kodadot/nft-gallery/pull/5859
- https://github.com/kodadot/nft-gallery/pull/5855
- https://github.com/kodadot/nft-gallery/pull/5851
- https://github.com/kodadot/nft-gallery/pull/5848
- https://github.com/kodadot/nft-gallery/pull/5847
- https://github.com/kodadot/nft-gallery/pull/5842
- https://github.com/kodadot/nft-gallery/pull/5833
- https://github.com/kodadot/nft-gallery/pull/5831
- https://github.com/kodadot/nft-gallery/pull/5823
- https://github.com/kodadot/nft-gallery/pull/5822
- https://github.com/kodadot/nft-gallery/pull/5821
- https://github.com/kodadot/nft-gallery/pull/5818
- https://github.com/kodadot/nft-gallery/pull/5815
- https://github.com/kodadot/nft-gallery/pull/5812
- https://github.com/kodadot/nft-gallery/pull/5810
- https://github.com/kodadot/nft-gallery/pull/5809
- https://github.com/kodadot/nft-gallery/pull/5802
- https://github.com/kodadot/nft-gallery/pull/5801
- https://github.com/kodadot/nft-gallery/pull/5798
- https://github.com/kodadot/nft-gallery/pull/5796
- https://github.com/kodadot/nft-gallery/pull/5794
- https://github.com/kodadot/nft-gallery/pull/5783
- https://github.com/kodadot/nft-gallery/pull/5778
- https://github.com/kodadot/nft-gallery/pull/5776
- https://github.com/kodadot/nft-gallery/pull/5774

### CODE REVIEW

**Comment by yangwao** [comment]
Did someone merged beta back to main? 

image

**Comment by roiLeo** [comment]
> Did someone merged beta back to main?

ou2d77b8qsb51

maybe https://github.com/kodadot/nft-gallery/commit/39b4a8a6a6013800b8b348a807954efd413a31e6

**Comment by yangwao** [comment]
> maybe [39b4a8a](https://github.com/kodadot/nft-gallery/commit/39b4a8a6a6013800b8b348a807954efd413a31e6)

actually it was happening before that tho

**Comment by yangwao** [comment]
huh, netlify builds, our gh action not, strange.

- https://deploy-preview-5896--koda-canary.netlify.app/

**Pull request merged**
