### PR TITLE
feat: hover popup for collection item

### LINKED ISSUE #3653: Show total volume on hover in collection explorer
We should show the total volume in collection explorer on collections where buy events happened. 

image

https://deploy-preview-3651--koda-nuxt.netlify.app/bsx/collection/3248880134?tab=history&event=BUY

image

https://user-images.githubusercontent.com/5887929/183053333-60115eff-f125-45d8-9e87-19d8cea43b29.mov

ht jrafaelangarita

### PR DESCRIPTION
**Pull request by KngZhi**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3653
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer?target=DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by yangwao** [comment]
seems I see some volume here  https://deploy-preview-3677--koda-nuxt.netlify.app/bsx/collection/1437651165
image


image

https://deploy-preview-3677--koda-nuxt.netlify.app/bsx/collection/1235404021

**Comment by JustLuuuu** [comment]
**My profile: offers made:** 

First issue: I'm not sure if that's possible, but it would be nice if expired offers would be cancelled automatically. 

Another issue: after clicking on cancel and cancelling one offer - it did not disappear automatically (dissapeared after refresh); it stayed like this: (look at the first picture - NFT Spodee - you can see that red X is "clicked").
image

Last issue: I was playing with the offers I made (cancelling them), but sometimes they did not disappear (I had to cancel them twice) I got notifications like this - and I don't understand them - so maybe make them user-friendly? 
image

image

**Review by JustLuuuu — APPROVED** [review]
wfm :)

**Review by kkukelka — APPROVED** [review]
lgtm

**Comment by kkukelka** [comment]
pay 100

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 64.91 USD/KSM ~ 1.541 $KSM
🧗 [DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc](https://kusama.subscan.io/account/DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc)
🔗 [0x73287438a18e244969b32cebc069cecf199a5569ca1ded69993d093fc10244b1](https://kusama.subscan.io/extrinsic/0x73287438a18e244969b32cebc069cecf199a5569ca1ded69993d093fc10244b1)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by jrafaelangarita** [comment]
Screenshot_2022-08-06-10-18-09-876_com android chrome
 Work well for me

**Pull request merged**
