### PR TITLE
feat/3507-renaming-sorting-options

### LINKED ISSUE #3507: renaming sorting options in gallery
let's update the sorting names to match

current implementation of sort on BSX:
image

in the meantime, we've updated RMRK in:
- https://github.com/kodadot/nft-gallery/issues/842

image

### PR DESCRIPTION
**Pull request by KngZhi**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #3507
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer?target=DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by cryptodamsky** [comment]
So why are there actually these two? It doesn’t make any sense to have them there?

- Oldest
- Unpopular

What does mean: 

- Serial number ascending?

And after clicking on this It doesnt work for me
 
 
image

and 

image

**Comment by KngZhi** [comment]
> So why are there actually these two? It doesn’t make any sense to have them there?
> 
> * Oldest
> * Unpopular

according to #3507 this is just trying to match the name with KSM chain sort keywords.

> What does mean:
> 
> * Serial number ascending?

@petersopko could answer this?

**Comment by KngZhi** [comment]
Original Sort Keywords. @cryptodamsky 

image

**Comment by cryptodamsky** [comment]
Ok, i’m just saying that the term "serial number ascending" doesn’t make sense to end user AND it doesn’t work when i click it.

**Review by cryptodamsky — COMMENTED** [review]
Ok, i’m just saying that the term "serial number ascending" doesn’t make sense to end user AND it doesn’t work when i click it.

**Comment by petersopko** [comment]
@cryptodamsky thank you for your valuable feedback, the issue which is being fixed was specifically concerning the names of the sorting options, but please feel free to contribute and clear up some of the confusion here:
- https://github.com/kodadot/nft-gallery/issues/3523

@KngZhi pls check to make sure, that on BSX the sort in Collections looks the same as the sort in Collections on RMRK as well (currently, New First got switched up with Recently Created - let's keep that only in Gallery on BSX), perhaps wrong translation track is being used in BSX collections sort.

bsx collections: 
image

rmrk collections:
image

**Comment by petersopko** [comment]
@KngZhi now the gallery doesn't match

**Comment by KngZhi** [comment]
> @KngZhi now the gallery doesn't match

On BSX, the collection and gallery share the same query keywords. If we want to conform with the KSM chain, we may need to add a flag on this and add i18 for the collection query keyword, which could be a little nasty on the code.

**Comment by KngZhi** [comment]
deployed version

https://user-images.githubusercontent.com/11361147/180430921-5d50f38d-7bdc-4585-9155-a0a85412db9e.mov

**Comment by petersopko** [comment]
It's same as RMRK now, wfm

**Review by petersopko — APPROVED** [review]

**Comment by petersopko** [comment]
@Jarsen136 pls check code and let's go 🚀

**Review by Jarsen136 — APPROVED** [review]
LGTM

**Comment by Jarsen136** [comment]
pay 50

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 65.36 USD/KSM ~ 0.765 $KSM
🧗 [DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc](https://kusama.subscan.io/account/DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc)
🔗 [0xf0b0e1cfad69e6fbd164720a389b4c86c76d32733e555496d10de285429bc45c](https://kusama.subscan.io/extrinsic/0xf0b0e1cfad69e6fbd164720a389b4c86c76d32733e555496d10de285429bc45c)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
