### PR TITLE
feat(rmrk2): add rmrk2 latest lists and sales

### LINKED ISSUE #5195: Showing RMRK2 latest sales on landing
Let's add showing rmrk2 sales to latest sales

image

### PR DESCRIPTION
**Pull request by floyd-li**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

**NOTE:**

as I make the queries at https://squid.subsquid.io/rubick/v/009-rc0/graphql, it get an error with `interaction = "LIST"` and return an empty result with `interaction = "BUY"`, but I tested the query at https://squid.subsquid.io/snekk/v/005/graphql for `snek` type, it goes well. so I'm wondering if the `subsquid` service failed?  it will be grateful if any one please check the service then merge this PR.

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #5195 #5196
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer?target=EZiu1PjV2j2JHKxY6mHnFwwCRCoV27uHKQSkKXATSh1srJT&usdamount=0&donation=true)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸
image
image

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
IMO it would be better to fix #5202 before merging this one

**Comment by vikiival** [comment]
Hello, the issue you have is caused by rubick, 
will try to fix that tomorrow.
Or if someone has time happy to pay.
The fix was already done on snek before just check commits/PR
cc @roiLeo ?

**Comment by roiLeo** [comment]
> The fix was already done on snek before just check commits/PR

which one kodadot/snek#157, kodadot/snek#158, kodadot/snek#144

> cc @roiLeo ?

I'm still on series resolver, problem with rubick, indexer is slow and greedy in storage. 
Do you know in which block rmrk2 start? or if we can use/restore some db

**Comment by vikiival** [comment]
@roiLeo 

https://github.com/kodadot/snek/commit/6135435d56b4ef129f312cddc4930134091573b2

**Comment by vikiival** [comment]
Looks like it was also fixed on rubick

https://github.com/kodadot/rubick/commit/0a4ca040c91f107f3f7976f6cd0f6fdbacd0f932

and I merged main into `rmrk2` yesterday

https://github.com/kodadot/rubick/commit/495278c770f8a6991e9043aa5d42f1384c4a1ca9

Lmk if this error is still present

**Comment by roiLeo** [comment]
> Lmk if this error is still present

`BUY` interaction still return empty

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
If the LIST bug is not present I am happy to merge it,
I opened issue 
- https://github.com/kodadot/rubick/issues/190

to investigate BUY issue

**Comment by vikiival** [comment]
pay 15 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $15 @ 33.48 USD/KSM ~ 0.448 $KSM
🧗 [EZiu1PjV2j2JHKxY6mHnFwwCRCoV27uHKQSkKXATSh1srJT](https://kusama.subscan.io/account/EZiu1PjV2j2JHKxY6mHnFwwCRCoV27uHKQSkKXATSh1srJT)
🔗 [0x3be696386ae638a524cc2535d99e85d55ced9e540d0052f15fcf49369bae4ec1](https://kusama.subscan.io/extrinsic/0x3be696386ae638a524cc2535d99e85d55ced9e540d0052f15fcf49369bae4ec1)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
Seems I don't see new lists on landing so this doesn't work?

https://github.com/kodadot/nft-gallery/issues/5196#issuecomment-1474086841

**Pull request merged**
