### PR TITLE
fix: Visual gap in drops new claim drop modal flow 

### LINKED ISSUE #8456: Visual gap in drops new claim drop modal flow
> that 8 second delay can make meh impression tbh

https://github.com/kodadot/nft-gallery/assets/5887929/906f47d7-7912-4db7-bb95-319398613603

> atm it's a visual est, so it should wait  till what time ? 

> 0 seconds ?

_Originally posted by @hassnian in https://github.com/kodadot/nft-gallery/issues/8440#issuecomment-1845421709_

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #8456

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

https://github.com/kodadot/nft-gallery/assets/44554284/d374afc3-6e55-4193-a7c4-42759841aff4

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 2cfe70f</samp>

This pull request enhances the countdown timer functionality for various components related to NFT minting and unlocking. It refactors the `useCountDown` hook to take an object argument for more flexibility and consistency. It also improves the image display and URL generation for the `DropConfirmModal` and `SuccessfulDrop` components.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 2cfe70f</samp>

> _To mint NFTs with a drop_
> _We refactored the `useCountDown` hook_
> _We moved some components around_
> _And improved the image and sound_
> _Now the user experience is top_

### CODE REVIEW

**Comment by hassnian** [comment]
tested it locally and it seemed to work , pls try @yangwao @prury thanks

**Comment by yangwao** [comment]
nope 

cca 10 seconds still blank
image

**Comment by hassnian** [comment]
https://github.com/kodadot/nft-gallery/assets/44554284/a31d2ec8-9e8a-43f1-9012-bc99e347f8a5


https://github.com/kodadot/nft-gallery/assets/44554284/8745692a-0c1c-4db0-b7a4-170db1c3b023

**Comment by yangwao** [comment]
cc @prury works?

**Comment by prury** [comment]
> cc @prury works?

was blocked by the new requirements 😅 
image

**Comment by yangwao** [comment]
> can we remove it from the test drop?

drop me address

**Comment by prury** [comment]
> > can we remove it from the test drop?
> 
> drop me address

EJRrMrt3bLtJj2VSTxkyvbywE8ySbqQ9A3xTzZ3Q2z9fzkT
not that I'm creating lots of new accounts for these tests and i will delete them later

**Comment by yangwao** [comment]
> EJRrMrt3bLtJj2VSTxkyvbywE8ySbqQ9A3xTzZ3Q2z9fzkT

Luuuu is sending to you 0.5KSM, should arrive in any minute



> note that I'm creating lots of new accounts for these tests and i will delete them later

yeah reasonable, maybe change some DOT for KSM, can reimburse, gonna send you 10DOT for this testing

**Comment by prury** [comment]
> > EJRrMrt3bLtJj2VSTxkyvbywE8ySbqQ9A3xTzZ3Q2z9fzkT
> 
> Luuuu is sending to you 0.5KSM, should arrive in any minute
> 
> https://statemine.subscan.io/extrinsic/0x29965f32f8315b1849c564eddd1fe3f73ac26bbcf3c123236337be990b9c2102
> 
> > note that I'm creating lots of new accounts for these tests and i will delete them later
> 
> yeah reasonable, maybe change some DOT for KSM, can reimburse, gonna send you 10DOT for this testing

https://github.com/kodadot/nft-gallery/assets/36627808/38fc9d6b-d887-4ced-917f-62ae49239f47

it works

**Comment by vikiival** [comment]
> we remove it from the test drop?

Yes will do

**Comment by yangwao** [comment]
> it works

what's monitor that? or viewport? 13" seems good time to improve that modal on desktop to have better effect

**Comment by yangwao** [comment]
Thanks @hassnian !
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 6.61 USD/DOT ~ 7.564 $DOT
🧗 [13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh](https://polkadot.subscan.io/account/13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)
🔗 [0xb91a3337c76e21b4ecbf9ebaf2497066b347dbf04de7fe1044e7c3fdcd67d0e5](https://polkadot.subscan.io/extrinsic/0xb91a3337c76e21b4ecbf9ebaf2497066b347dbf04de7fe1044e7c3fdcd67d0e5)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by prury** [comment]
> > it works
> 
> what's monitor that? or viewport? 13" seems good time to improve that modal on desktop to have better effect

24'' on 1920x1080 res

**Pull request merged**
