### PR TITLE
fix: add on-chain identity after destination address

### LINKED ISSUE #1317: Show on-chain identity for destination address in transfer
Right now user could be unsure where is sending money to,
let's start showing destination address on-chain identity, show it next to the shortened address.

image

### PR DESCRIPTION
**Pull request by jbienesdev**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇  _ Do a quick check before the merge. 

### PR type
- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional
- [x] I've tested it at `/transfer`
- [ ] I've tested PR on mobile and everything works
- [ ] I found edge cases

### What's new?
- [x] PR closes #1317
- [x] Added the receiver's on-chain identity after the destination address

### Had issue bounty label ?
- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=F2zKdNM77s17cmtdgqCooGVphz8UFv4jUEuFJ366VVAb53G)

### Community participation
- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [x] My fix has changed **something** on UI, a screenshot for others, is best to understand changes.

---------------

## Receiver with on-chain identity
image

## Receiver without on-chain identity
image

### CODE REVIEW

**Comment by yangwao** [comment]
LGTM, yet I'm thinking about the state till resolving finishes. 
To tell the user if it's fetching identity so can be sure there is no identity of the destination address.

Do you have an idea how to do that?

**Comment by jbienesdev** [comment]
@yangwao we can add the infinity loader that we're using while it's still fetching the identity.

This is how it would look like with the loader (added a setTimeout for it to be noticeable)

### Address with on-chain identity
https://user-images.githubusercontent.com/17470909/144797910-a9a01327-832b-4f01-80de-fb338c213dbc.mp4

### Address without on-chain identity
https://user-images.githubusercontent.com/17470909/144797983-8f8aed8b-b195-4cc3-b495-bdf6d63901dd.mp4

Also, I added a new prop `showOnchainIdentity` so that other components that uses `<Identity />` will not be affected. What do you think?

**Comment by yangwao** [comment]
yeah works for me!

**Comment by yangwao** [comment]
@jbienesdev I love emphasis on detial, here goes payout! https://kusama.subscan.io/extrinsic/0x08db70546ab386cbe844f4fbf98f979e219eae00765eb68a64300abb3db5f9bc

### [Let's chop on another issues ](https://github.com/kodadot/nft-gallery/issues/)
# 🌳🌳🌳 🪓   🪵

**Comment by jbienesdev** [comment]
Received. Thanks!

**Pull request merged**
