### PR TITLE
✨ update profile icon

### LINKED ISSUE #4406: Navbar profile icon
continuation of #4389 
Everything is good, however the current profile icon doesn't seem to fit the overall aesthetic.

- current one:
image
- it should look like this:
image

Figma has issues with exports in svg when you apply drop shadow, so i recreated them and here they are. 
profile (6)
profile (5)

### PR DESCRIPTION
**Pull request by shashkovdanil**
## PR Type

Refactoring

## Context

Closes #4406

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer?target=bXn3ExwLs8rpcpknp9wNqnNVgEYVLnTtFPDrJtaPHYds7Vfjv&usdamount=0&donation=true>)

## Screenshot 📸

image
image

### CODE REVIEW

**Comment by exezbcz** [comment]
image
stroke around the connected profile icon should be white - in dark mode
Can you change that please? 
Thanks!

**Comment by shashkovdanil** [comment]
image

**Comment by exezbcz** [comment]
> image

now it has 2 borders no?

**Comment by shashkovdanil** [comment]
No, only one border

image

**Comment by exezbcz** [comment]
> 

that is weird because it looks it has 2 strokes, one black and one white. Is it because the illustration of you account has some stroke by default? 
If it wouldnt be possible to remove the black outline, i think we can leave it how it was.

**Comment by shashkovdanil** [comment]
The problem is with the icon. The icon has a small transparent circle around it. There's no quick fix. Do I have to revert this commit https://github.com/kodadot/nft-gallery/pull/4407/commits/709586e3f81c3c89b68c457e800e57747e8dfcbf?

**Comment by exezbcz** [comment]
> The problem is with the icon. The icon has a small transparent circle around it. There's no quick fix. Do I have to revert this commit [709586e](https://github.com/kodadot/nft-gallery/commit/709586e3f81c3c89b68c457e800e57747e8dfcbf)?

in this case, yes. Sorry for that

**Comment by shashkovdanil** [comment]
Everything is fine 👌Reverted

**Comment by yangwao** [comment]
pay 30 usd 
nice

**Comment by yangwao** [comment]
ups, add KSM address please?

**Comment by shashkovdanil** [comment]
@yangwao J29ScJV5xTrMisy32HAcTCdhac4KRATkbsJnNZnE3ZFRTeC

**Pull request merged**
