### PR TITLE
🔧 disabled submit button

### PR DESCRIPTION
**Pull request by roiLeo**
No disabled pattern

## PR Type

- [x] Bugfix

## Context

- [x] ref #5067

### CODE REVIEW

**Comment by vikiival** [comment]
Nooo it will break the ui 😢

**Comment by roiLeo** [comment]
> Nooo it will break the ui 😢

What do you mean? I'm not able to submit when input are required.
Why would you introduce disabled button only on specific chain?

**Comment by vikiival** [comment]
I made it disabled because i was able to make collection with empty metadata

> why only one chain?

I forgot to add disabled to other chains 🥺

**Comment by roiLeo** [comment]
> I made it disabled because i was able to make collection with empty metadata

How? I can't reproduce empty form. 
It doesn't need to be that way instead wa can try to fix form.

**Comment by vikiival** [comment]
So the correct fix should be on the side of a package 

- https://github.com/kodadot/packages/issues/105

**Review by vikiival — APPROVED** [review]

**Pull request merged**
