### PR TITLE
#1669 Remove glowing effect from everywhere

### LINKED ISSUE #1669: Remove glowing effect from everywhere
Remove background glowing from cards

image

image

image

image

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇  _ Do a quick check before the merge. 

### PR type
- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything works
- [ ] I found edge cases

### What's new?
- [x] PR closes #1669

### Had issue bounty label ?
- [x] Fill up your KSM address: 
[Payout](https://kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation
- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [x] My fix has changed **something** on UI, a screenshot for others, is best to understand changes.
Screenshot 2022-01-03 at 4 27 45 PM
Screenshot 2022-01-03 at 4 27 49 PM

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
@prachi00 missing border on collection cards?
Screenshot 2022-01-03 at 12-42-22 KodaDot - Polkadot Kusama NFT explorer

**Comment by prachi00** [comment]
> @prachi00 missing border on collection cards? Screenshot 2022-01-03 at 12-42-22 KodaDot - Polkadot Kusama NFT explorer

@roiLeo for me it is visible, was there something specific you did?

Screenshot 2022-01-03 at 6 03 11 PM

**Comment by yangwao** [comment]
Seems @roiLeo had some older build? WFM 

image

**Comment by prachi00** [comment]
> Seems @roiLeo had some older build? WFM EDIT on gallery.
> 
> image
> 
> @prachi00 on collections it doesn't work
> 
> image

weird, for me it is visible, I'll check again @yangwao

**Comment by prachi00** [comment]
@yangwao @roiLeo on local it is visible to me, on the preview link it is not, also there are two collections.vue file, just noticed, I added the code on both of them, probably should be visible now. 

P.S do we need two collections.vue file?

**Comment by yangwao** [comment]
Perfect, I’ve sent the payout https://kusama.subscan.io/extrinsic/0x2fb9ca7ad7da0ccf00cead49e2215588ad5fa8d7314c6f1a26a5655ef36c3c6a

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/

**Pull request merged**
