### PR TITLE
:wrench: bsx gift unlist

### LINKED ISSUE #3687: Issue re: Unlist the nft, after it was sent as a gift
### What happened?

I sent an nft as a gift, to check that it was fixed and when entering the other account (n2), the nft is still listed (action performed in the original account or n1)

### Please reproduce in steps

list a nft, send it like gift, check on the receive adress, that is still listed

### Expected Behavior

being a gift, it should not save the previous action, and should  unlist the nft, otherwise, it may be bought and the owner does not notice

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

Talisman

### Screenshots

Screenshot_98
Screenshot_99

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/transfer?target=Hy8UnZSNvchEzKLBZ6X6qXq6xc8gVNGyo8ALuuNUXeTiD6K&usdamount=10&donation=true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by roiLeo**
Spent ⏳ trying to debug this

## PR Type

- [x] Bugfix
- [x] Feature

## Context

- [x] Closes #3687 

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [x] I've tested it at `/snek/gallery/331660682-1`

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=HguGafrfk8nRP9a4tgJf7hLvSSFie8GtkDjyWFHQ2kDUAMc)

## Screenshot 📸

Screenshot 2022-12-21 at 12-19-31 Shader 001 KodaDot - Kusama NFT Market Explorer

### CODE REVIEW

**Review by Jarsen136 — APPROVED** [review]
LGTM

**Comment by yangwao** [comment]
is this working well?

**Comment by roiLeo** [comment]
> is this working well?

Try it out 😉

**Comment by yangwao** [comment]
pay 60 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $60 @ 22.23 USD/KSM ~ 2.699 $KSM
🧗 [HguGafrfk8nRP9a4tgJf7hLvSSFie8GtkDjyWFHQ2kDUAMc](https://kusama.subscan.io/account/HguGafrfk8nRP9a4tgJf7hLvSSFie8GtkDjyWFHQ2kDUAMc)
🔗 [0x00008fa78c0db972534cd873aab4db26acf10f4fbd29104315f43b5fc61b7936](https://kusama.subscan.io/extrinsic/0x00008fa78c0db972534cd873aab4db26acf10f4fbd29104315f43b5fc61b7936)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
