### PR TITLE
fix(searchbar): Pagination buttons on explorer is off

### LINKED ISSUE #3807: Pagination buttons on explorer seems bit off
😅

https://beta.kodadot.xyz/rmrk/explore/?tab=GALLERY&page=1

image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3807
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by roiLeo** [comment]
#3360 is starting to be more than necessary

**Comment by yangwao** [comment]
> #3360 is starting to be more than necessary

something is being done in #3763  👀

**Comment by Jarsen136** [comment]
> > #3360 is starting to be more than necessary
> 
> something is being done in #3763 👀

This bug is introduced from PR https://github.com/kodadot/nft-gallery/pull/3794

**Comment by Jarsen136** [comment]
> #3360 is starting to be more than necessary

Yup, it's almost done : )

**Comment by yangwao** [comment]
pay 50

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 50.07 USD/KSM ~ 0.999 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xc14342c5f597757b32d533b548af36c5dad441c51fccdda6f0cb33193a82ba1c](https://kusama.subscan.io/extrinsic/0xc14342c5f597757b32d533b548af36c5dad441c51fccdda6f0cb33193a82ba1c)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
let's merge if tests pass 👀

**Comment by yangwao** [comment]
#3812 hmmm

**Pull request merged**
