### PR TITLE
fix: Showing countdown sometimes doesnt show whole row

### LINKED ISSUE #6172: Showing countdown sometimes doesn't show whole row
image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #6172

image

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

### <samp>🤖 Generated by Copilot at 09cb55b</samp>

Improved unlockable content slider UI in `CountdownTimer.vue` by removing margins and adding slides option.

### <samp>🤖 Generated by Copilot at 09cb55b</samp>

> _`CountdownTimer` is ticking, the end is near_
> _Unlock the secrets of the `keen-slider`_
> _No more margins to hold you back, only slides to set you free_
> _Break the chains of the layout, unleash the content you desire_

### CODE REVIEW

**Comment by prury** [comment]
@Jarsen136 how to reproduce the bug?

**Comment by Jarsen136** [comment]
> @Jarsen136 how to reproduce the bug?

At times on `https://canary.kodadot.xyz/stmn/unlockable`, the text may appear overlapped or cut off, especially on mobile
image

**Comment by prury** [comment]
@Jarsen136 

mobile: 
image

tablet: 
image

**Comment by Jarsen136** [comment]
> @Jarsen136
> 
> mobile: image
> 
> tablet: image

Did you reproduce it by adjusting the width of browser windows? It's not responsive right now. I think every time you open the page it displays well without overlapping.

**Comment by prury** [comment]
> Did you reproduce it by adjusting the width of browser windows after the page loaded? It's not responsive right now. I think every time you open the page it displays well without overlapping.

oh, you are right! 

image

**Review by daiagi — APPROVED** [review]

**Review by vikiival — APPROVED** [review]

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $15 @ 5.01 USD/DOT ~ 2.994 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0xf28dcab2baeec575d35733d752a9d80024be4deb3de4802a7ea83c5539db6673](https://polkadot.subscan.io/extrinsic/0xf28dcab2baeec575d35733d752a9d80024be4deb3de4802a7ea83c5539db6673)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
