### PR TITLE
chore: add eslint cache

### PR DESCRIPTION
**Pull request by shengxinjing**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [X] Refactoring

## Context

- [ ] Closes #<issue_number>
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [ ] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>)

## Copilot Summary

chore: add eslint cache

### CODE REVIEW

**Comment by prury** [comment]
@shengxinjing please user PR template

**Comment by prury** [comment]
@shengxinjing does it close any open issue?

**Comment by shengxinjing** [comment]
I just thought that adding eslint's cache would improve the DX, and there is no issue with that.

**Comment by yangwao** [comment]
> adding eslint's cache would improve the DX

does it cut some time?

**Comment by shengxinjing** [comment]
Without caching, each eslint script takes about 5 seconds.
With caching, the first eslint takes about 5 seconds, the second takes only 1 second.

**Comment by yangwao** [comment]
> With caching, the first execution of the eslint script takes about 5 seconds, and the second execution takes about 1 second.

reasonable for me, maybe from @kodadot/internal-dev can voucher that?

**Comment by shengxinjing** [comment]
emm... That's why the cache parameter exists

**Pull request merged**
