### PR TITLE
feat: add max buy and reorder collection

### LINKED ISSUE #2330: Add max buy and reorder collection insights
Merge 24h volume traded and total volume into one field and put on the original position of floor price.

Put floor price on the position of current 24h volume traded

On position, the total volume traded add 

- the highest buy within the collection.
- number of buys that happened in the collection (like is on series)

The easiest way is to use a subquery.
For higher bounty, writing resolver to subsquid.

image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [ ] PR closes #2330
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [x] I found edge cases
- [x] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

### CODE REVIEW

**Comment by vikiival** [comment]
Like the code is legit, but it's like using duct tape to glue two pieces of paper together

**Review by vikiival — CHANGES_REQUESTED** [review]
```graphql
query totalCollectionEvents($id: ID!, $and: [EventWhereInput!]) {
  eventsConnection(where: {nft: {collection: {id_eq: $id}}, AND: $and }, orderBy: meta_DESC) {
    totalCount
  }
  max: events(where: {nft: {collection: {id_eq: $id}}, AND: $and }, orderBy: meta_DESC, limit: 1) {
    id
    meta
  }
}

```

**Comment by Jarsen136** [comment]
> ```graphql
> query totalCollectionEvents($id: ID!, $and: [EventWhereInput!]) {
>   list: eventsConnection(where: {nft: {collection: {id_eq: $id}}, AND: $and }, orderBy: meta_DESC) {
>     count: totalCount
>   }
>   max: events(where: {nft: {collection: {id_eq: $id}}, AND: $and }, orderBy: meta_DESC, limit: 1) {
>     id
>     meta
>   }
> }
> ```

Thanks for your idea! But this solution don't work well, because of the sorting method. Meta is a string type so that the sorting result is not correct.
In my pull request, I transform the string to number and then sort the meta number. It can get the correct result.

I think we need a custom sorting method in graphql. https://github.com/graphql/graphql-spec/issues/8

Any ideas? @vikiival

**Comment by vikiival** [comment]
> Any ideas? @vikiival

Yup, we need to write the resolver to the [kodadot/rubick](https://github.com/kodadot/rubick) which will return the correct max and count

**Comment by Jarsen136** [comment]
> 

Thanks, I will have a try!

**Comment by yangwao** [comment]
👀

**Comment by vikiival** [comment]
Waiting to resolve https://github.com/kodadot/rubick/pull/37

**Comment by Jarsen136** [comment]
> Waiting to resolve [kodadot/rubick#37](https://github.com/kodadot/rubick/pull/37)

It seems that the new resolver has been merged into main branch.  I wonder when it will be deployed well so that I could change the frontend code. @vikiival

**Comment by vikiival** [comment]
@Jarsen136 🦑 should be up in a couple of minutes

**Comment by yangwao** [comment]
Can we test this so we can launch it with the upcoming push to production? cc @vikiival

**Comment by vikiival** [comment]
> Can we test this so we

yup

**Comment by vikiival** [comment]
@Jarsen136 please add translations and we are good to go 🫣

**Comment by yangwao** [comment]
Follow up issue 
- add translations 
- plus fix alignment 
image

**Comment by yangwao** [comment]
pay 300 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $300 @ 196.55 USD/KSM ~ 1.526 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xf5bd7c31947c7238ccdc88afcf5cfeee39fa72d6ed987b97ef904aa2307af3ae](https://kusama.subscan.io/extrinsic/0xf5bd7c31947c7238ccdc88afcf5cfeee39fa72d6ed987b97ef904aa2307af3ae)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
