### PR TITLE
#4213 Network switch

### LINKED ISSUE #4213: Add temporary network switch
continue from #4185  
> After a brief discussion, I believe that the landing isn't yet prepared for the multichain use as it was originally intended.
How it works right now:
>
>The selection under searchbar finally redirects to explore/network, that is good. The default network is BSX, where you cannot see top collection. Also now it could look like the bsx is the only active network - doesnt make sense if it redirects you to the explore page.
>
>Changing network is currently done by hovering over explore and selecting your desired network - these buttons are not meant to be used as network switch.
>
>Because it doesnt make sense to hover over explore to change a network i propose adding temporary network switch. This could eliminate user confusion and improve the ux once we the beta goes live.
>
>Changes required:
>
>Top collections
Collection card info - missing network
filter based on network, default is all networks
display collections from all networks

Lets add a temporary button for switching network until we complete the multichain features of the landing page. 
image
The network switch is now in explore hover dropdown, which doesnt make sense. So we will divide it for some time for better user experience. 
- design is in figma - landing page handoff - https://www.figma.com/file/3iOjW12ERFRDSVnpLuhQmf/landing-page-handoff?node-id=1305%3A5613
- working similarly as explore hover 
- once you hover over "network" in this case RMRK, dropdown is displayed. 
- Active network is in black, in dark mode white. See button behavior in #4111 button section. 

Feel free to ask any questions in the comments! Thanks

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## PR Context?

- [x] Closes #4213
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screen Shot 2022-11-02 at 7 04 44 PM

### CODE REVIEW

**Comment by prachi00** [comment]
> need to adjust e2e test also, located in `tests/cypress/e2e/basicE2E.cy.ts`

done

**Comment by yangwao** [comment]
okay temporary till we have multichain spotlight and collections

**Comment by yangwao** [comment]
pay 30

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 35.6 USD/KSM ~ 0.843 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0xd7bbd3faa4c52012fc2489fb1592a4b94351f2e79e28632429b7edc879fd006a](https://kusama.subscan.io/extrinsic/0xd7bbd3faa4c52012fc2489fb1592a4b94351f2e79e28632429b7edc879fd006a)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by exezbcz** [comment]
Hi! good job, one thing is the hover effect in the dark mode. Color of the text should be black, not white.
image
- see other dropdowns - create etc

**Comment by prachi00** [comment]
> 

sure fixed in #4245

**Pull request merged**
