### PR TITLE
fix: dot-drop transaction data not correct

### PR DESCRIPTION
**Pull request by thnaylor**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Bugfix #7403 
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [ ] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=123PCJXhjb15i6JwVVRGd7KvN2sSNZrtPjr5doJq9oWctoTt)

## Comments
- Trying to purchase dot drop results in an error before transaction begins.

## Screenshot
image

### <samp>🤖 Generated by Copilot at 39bc299</samp>

Improved type safety and readability of the code for buying NFTs from a collection drop. Used a `NFTBuy` type and an `InteractionType` enum in `DropContainer.vue`.

### <samp>🤖 Generated by Copilot at 39bc299</samp>

> _We deal in NFTs, the tokens of doom_
> _We simplify the transaction, no need to assume_
> _We use the enum value, to avoid confusion_
> _We interact with the contract, the final solution_

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]

**Review by Jarsen136 — APPROVED** [review]
code lgtm

**Comment by prury** [comment]
Transaction now goes nicely and NFT is minted
will add to the list issue: Congratulations message appears before approving transaction

**Comment by yangwao** [comment]
pay 50 usd 
thanks @thnaylor !

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 3.82 USD/DOT ~ 13.089 $DOT
🧗 [123PCJXhjb15i6JwVVRGd7KvN2sSNZrtPjr5doJq9oWctoTt](https://polkadot.subscan.io/account/123PCJXhjb15i6JwVVRGd7KvN2sSNZrtPjr5doJq9oWctoTt)
🔗 [0x2c8533aff237d358f964eaf52bf9423fe94b6d28a100c223829f3e613809cbca](https://polkadot.subscan.io/extrinsic/0x2c8533aff237d358f964eaf52bf9423fe94b6d28a100c223829f3e613809cbca)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
