### PR TITLE
style: refactor label size from globals.scss

### LINKED ISSUE #9008: remove `font-size` on global.scss
Related issue: https://github.com/kodadot/nft-gallery/issues/8071

### PR DESCRIPTION
**Pull request by pbkompasz**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [X] Refactoring

## Context

- [X] Closes #9008
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [X] My contribution builds **clean without any errors or warnings**
- [X] I've merged recent default branch -- **main** and I've no conflicts
- [X] I've tried to respect high code quality standards
- [X] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [X] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16hqk8Tjugo9AwSzKkxXc1dsRK7iJetpx1YBaoXYwdHzuNAt&usdamount=50&donation=true)

#### Community participation

- [ ] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by Jarsen136 — CHANGES_REQUESTED** [review]
It should be refactor `font-size` with tailwind across the whole codebase. 

Even for the only `global.scss` file, there is still some leftover. 

image

**Review by preschian — APPROVED** [review]

**Review by preschian — COMMENTED** [review]
some `is-size-*` still exists on global.scss

**Review by preschian — CHANGES_REQUESTED** [review]
some `is-size-*` still exists on global.scss

**Comment by pbkompasz** [comment]
@preschian That will be removed in #9238

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 6.76 USD/DOT ~ 4.438 $DOT
🧗 [16hqk8Tjugo9AwSzKkxXc1dsRK7iJetpx1YBaoXYwdHzuNAt](https://polkadot.subscan.io/account/16hqk8Tjugo9AwSzKkxXc1dsRK7iJetpx1YBaoXYwdHzuNAt)
🔗 [0x95b76e0bfe979f7767272b186bacb0bf0843f7bedccf89a8b73f9e3c2a7e47c9](https://polkadot.subscan.io/extrinsic/0x95b76e0bfe979f7767272b186bacb0bf0843f7bedccf89a8b73f9e3c2a7e47c9)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
