### PR TITLE
chore(eslint): extend eslint rules and STYLE_GUIDE.md

### PR DESCRIPTION
**Pull request by KngZhi**
- docs(STYLE_GUIDE): advice on no loop
- feat: add for-loop eslint rule
- chore: rule of if statement

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [ ] PR closes #<issue_number>
- [x] Make STYLE_GUIDE.md more actionable, give suggestion during coding and throw error before commit

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer?target=DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

Screen Shot 2022-04-30 at 12 27 54 PM

image

### CODE REVIEW

**Review by vikiival — APPROVED** [review]
Lovely ❤️ 
Great job @KngZhi

**Comment by vikiival** [comment]
@KngZhi please resolve conflicts and we are good to go 🚀

**Comment by KngZhi** [comment]
@vikiival Thanks! hahaha. The conflicts are solved.

**Comment by vikiival** [comment]
Loooks like your deploy is failing

**Comment by KngZhi** [comment]
image

image

Ummm, @vikiival the previous deploy issue was fixed, but new code coming... I guess we should merge that ASAP.. haha

I will fix those issues right now, pls hold merge for a moment.

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
pay 100 usd

**Comment by yangwao** [comment]
pay 100 usd

**Pull request merged**
