### PR TITLE
[WIP] fix: Modal scrollbar issue

### LINKED ISSUE #9067: Great scrollbar issue
even more and more recordings have these funny scrollbar behaviors, mainly on mobile 
image

telegram-cloud-photo-size-4-5857318700426838158-y

let's make it consistent

## Desktop 

question: can the modal cover navbar or it is still our limitation? 

- if not, lets make it max 90% viewport height 
   - if the modal does not even fit into that, it scrolls 
 
how it should scroll? 

like this: 
image

## Mobile 
- to avoid scroll, enable full width modals
- if its still bigger, its scrolls with the same as on desktop 

you can try this prototype: https://www.figma.com/proto/JXNtryaNYhY0XJNArzvPQx/Handoff?page-id=1157%3A17072&type=design&node-id=7343-31511&viewport=-316%2C-652%2C0.75&t=pocpMoCHcd6EJ9wU-1&scaling=min-zoom&starting-point-node-id=1159%3A17314&mode=design

its listing modal

### PR DESCRIPTION
**Pull request by pbkompasz**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [X] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [X] Closes #9067
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [X] My contribution builds **clean without any errors or warnings**
- [X] I've merged recent default branch -- **main** and I've no conflicts
- [X] I've tried to respect high code quality standards
- [X] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [X] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16hqk8Tjugo9AwSzKkxXc1dsRK7iJetpx1YBaoXYwdHzuNAt&usdamount=50&donation=true)

#### Community participation

- [ ] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸
Screenshot from 2024-02-24 15-34-57
Screenshot from 2024-02-24 15-34-46
Screenshot from 2024-02-24 15-34-06
Screenshot from 2024-02-24 14-46-48
- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by exezbcz** [comment]
hello sir @pbkompasz, are you planning to finish this one? 

would like to see this one finished

**Comment by pbkompasz** [comment]
@exezbcz I updated the description with the screenshots. In the cart the title and the button is fixed (desktop and mobile) and in the confirm purchase modal only the title is fixed.

**Comment by exezbcz** [comment]
@pbkompasz will have a look thanks

**Comment by exezbcz** [comment]
related? 
image

image

its not fixed even after refresh

**Comment by exezbcz** [comment]
scroll here 

https://github.com/kodadot/nft-gallery/assets/90852205/e03ea336-97a6-48e5-820e-7bb6cbe65120

**Comment by pbkompasz** [comment]
@exezbcz The scroll issue doesn't happen for me on either Chrome or Firefox.

**Comment by exezbcz** [comment]
@pbkompasz try resizing the window height

**Comment by exezbcz** [comment]
@pbkompasz did you manage to reproduce the issue?

**Comment by exezbcz** [comment]
sir, you are working on this pr 27 days. can you let me know if you are going to finish

**Comment by exezbcz** [comment]
no update, its more urgent, 1 month for one issue is quite a long time

**Pull request closed without merging**
