### PR TITLE
fix : scroll bar when timeframe dropdown is open in price chart

### LINKED ISSUE #4469: Chart tab switching to scroll
- when opening time frame dropdown
image
- without dropdown 
image

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Closes #4469 
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

no scroll bar when time frame dropdown is open:

image

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
would it be possible to use `NeoDropdown` component? 🥺

**Comment by daiagi** [comment]
> would it be possible to use `NeoDropdown` component? pleading_face

I guess so, but not without additional work

this is how it looks after when i replace:
 b-dropdown -> NeoDropdown 
 b-dropdown-item -> NeoDropdownItem

image

and the dropdown menu stays open, not responding to clicks

**Comment by roiLeo** [comment]
> and the dropdown menu stays open, not responding to clicks

have you done something like this?

```html
    <NeoDropdown>
      <NeoButton :label="selectedTimeRange.label" />

      <template #items>
        <NeoDropdownItem
          v-for="range in timeRangeList"
          :key="range.value"
          :item="range.label"
          class="is-flex is-justify-content-center px-0"
          aria-role="listitem"
          :value="selectedTimeRange"
          :class="{ 'is-active': selectedTimeRange.value === range.value }"
          @click.native="setTimeRange(range)"
        />
      </template>
    </NeoDropdown>
```

**Comment by daiagi** [comment]
>have you done something like this?

sorry i posted too quickly... nvm my previous comment

**Comment by daiagi** [comment]
> would it be possible to use `NeoDropdown` component? pleading_face

:heavy_check_mark:  Done

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 25.54 USD/KSM ~ 1.958 $KSM
🧗 [EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L](https://kusama.subscan.io/account/EfmnRhHaQqfT3phm4cUCHCU3gFVDoSPR1U9WXzMRQBMqZ4L)
🔗 [0xbfd49507dd2aed4d702e4f10db35dd2c0f699aa6f164808a9732892a5ff0e4f4](https://kusama.subscan.io/extrinsic/0xbfd49507dd2aed4d702e4f10db35dd2c0f699aa6f164808a9732892a5ff0e4f4)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
