### PR TITLE
#1933 Embed Contributing.md & First_time.md

### LINKED ISSUE #1933: Embed Contributing.md & First_time.md to kodadot web
I guess for a single point of truth (file) and SEO reasons, would be nice to embed currently existing Contributing.md and First_time to help easily onboard developers.

@roiLeo suggests https://content.nuxtjs.org/
The best would be probably to leverage the existing markdown module we are using? [vue-markdown-render](https://github.com/kodadot/nft-gallery/blob/main/package.json#L94) I guess?

routes could be 
- kodadot.xyz/contribute
- kodadot.xyz/first_time 

### Ref 
- #361
- #1075
- maybe https://github.com/wxsms/vue-md-loader ?

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Do a quick check before the merge.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #1933
- [ ] 
Used nuxt content for doing this
Had to do css changes as well for this because tags like `p`, `heading` tags and `table` got replaced with other classes from libraries and code and messed with the padding, fonts, margins, borders. 

Route is available at `/contribute` and `/firsttime`

Needed clarity in whether to delete the **md** files or keep them in root? 

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases

### Had issue bounty label ?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI, a screenshot is best to understand changes for others.
Screenshot 2022-01-22 at 6 24 06 PM
Screenshot 2022-01-22 at 6 24 19 PM

### CODE REVIEW

**Comment by yangwao** [comment]
> I guess for a single point of truth (file) 

We do not want to copy stuff over. 
The thing would be at build time fetch the content of 
- https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md
- https://github.com/kodadot/nft-gallery/blob/main/FIRST_TIME.md

To have the most up to date stuff, not maintaining another copy of the file.

**Comment by prachi00** [comment]
> To have the most up to date stuff, not maintaining another copy of the file.

oh okay, I'll check if we can do it this way

**Comment by prachi00** [comment]
@yangwao so the way this works is that nuxtcontent fetches from the `content` directory, so it wont be able to take the content from 
```
https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md
https://github.com/kodadot/nft-gallery/blob/main/FIRST_TIME.md
```
I think we can instead do is shift these files into the content directory **only** and then access it on github through
https://github.com/kodadot/nft-gallery/blob/main/content/CONTRIBUTING.md
https://github.com/kodadot/nft-gallery/blob/main/content/FIRST_TIME.md

Let me know what you think. 

CC @roiLeo @vikiival 

Ref: https://nuxtjs.org/docs/directory-structure/content/
https://content.nuxtjs.org/writing

**Comment by yangwao** [comment]
And why isn't possible embed existing CONTRIBUTING.md without copying it into /content directory?

**Comment by prachi00** [comment]
> And why isn't possible embed existing CONTRIBUTING.md without copying it into /content directory?
> 
> I mean FIRST Time wouldn't be issue but contributing.md is required by gh to be in top level directory tho.

@yangwao I couldn't find anything like this for nuxt/content

**Comment by prachi00** [comment]
@yangwao so what are we doing about this? maybe we can go for just `first_time.md` right now in the contents folder?

**Comment by yangwao** [comment]
I'm thinking we could semantically split some portion from contributing and have it in content if so.

At some point we are having https://doc.kodadot.xyz 
Where we could later highlight some portion for whatever reason having it at one single place.

I think I could prepared some light weight timeless version which could be embedded.

Let's keep this PR open and will get back to it later

**Comment by vikiival** [comment]
`22.01.2022` vs `16.03.2022` 

I recommend closing this pull request.

**Pull request closed without merging**
