### PR TITLE
chore/statick without rmrk

### PR DESCRIPTION
**Pull request by vikiival**
- **rmrk out of libs/static/src/chains.ts**
- **rmrk out of libs/static/src/endpoints.ts**
- **rmrk out of libs/static/src/indexers.ts**
- **rmrk out of libs/static/src/names.ts**
- **rmrk out of libs/static/src/services.ts**
- **rmrk out of libs/static/src/types.ts**
- **:technologist: show data based on assethubs**
- **app: remove rmrk prefix from composables/useBlockTime.ts**
- **app: remove rmrk prefix from composables/useTransak.ts**
- **app: remove rmrk prefix from composables/useUsdValue.ts**
- **app: remove rmrk prefix from stores/identity.ts**
- **app: remove rmrk prefix from utils/chain.ts**
- **app: remove rmrk prefix from utils/teleport.ts**

**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

removes rmrk prefix, ksm will be available

#### Before submitting pull request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ahp/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [ ] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>)

#### Community participation

- [ ] [Are you at Koda Ecosystem Telegram?](https://t.me/koda_eco)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by Jarsen136** [comment]
This page was broken. https://deploy-preview-11080--koda-canary.netlify.app/ahk/teleport

**Comment by Jarsen136** [comment]
> > This page was broken. https://deploy-preview-11080--koda-canary.netlify.app/ahk/teleport
> 
> Can I ask you to fix it pls?

will fix it

**Comment by Jarsen136** [comment]
> > > This page was broken. https://deploy-preview-11080--koda-canary.netlify.app/ahk/teleport
> > 
> > 
> > Can I ask you to fix it pls?
> 
> will fix it

Done https://github.com/kodadot/nft-gallery/pull/11080/commits/22c4b8022bd944db9f711dc35bcbb9b0deb05f4b

teleport Tested 
ksm -> ahk : https://assethub-kusama.subscan.io/xcm_message/kusama-c4aff010b59ff14266a4d6ef61523ea3023064a7

ahk -> ksm : https://assethub-kusama.subscan.io/xcm_message/kusama-d4e66672afa0cbdf6182da0cc3cead690ddb7b77

**Review by vikiival — COMMENTED** [review]
@kodadot/internal-dev can you pls review ?

**Review by Jarsen136 — APPROVED** [review]
wfm

**Review by hassnian — APPROVED** [review]

**Review by preschian — COMMENTED** [review]
transfer page on canary:
Screenshot 2024-10-21 at 18 25 51

in this PR doesnt show the message. `TypeError: Cannot read properties of undefined (reading 'ss58Format')`

**Comment by vikiival** [comment]
cc @Jarsen136  ❤️

**Comment by Jarsen136** [comment]
> transfer page on canary: Screenshot 2024-10-21 at 18 25 51
> 
> in this PR doesnt show the message. `TypeError: Cannot read properties of undefined (reading 'ss58Format')`
> 
> detected on e2e test

✅ Fixed  https://github.com/kodadot/nft-gallery/pull/11080/commits/49095762072710f53bcf63b826eaa420f2bf6a3a

**Review by preschian — APPROVED** [review]

**Pull request merged**
