### PR TITLE
fix: balanceInputComponent.checkValidity is not a function

### LINKED ISSUE #3597: TypeError: balanceInputComponent.checkValidity is not a function
### What happened?

When I type an address on the GIFT input, an error comes out.

`TypeError: balanceInputComponent.checkValidity is not a function`

https://beta.kodadot.xyz
image

local development environment. localhost:3000

Kapture 2022-07-29 at 00 10 38

image

### Please reproduce in steps

1. open https://beta.kodadot.xyz/
2. open nft detail page that shows nft you owned
3. click GITF button
4. type an address on the GIFT input and an error comes out.

### Expected Behavior

There is no any error while gifting nft.

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz

### Are you logged in?

Yes

### Which wallet you are using?

PolkadotJS

### At which chain did you encounter bug?

Basilisk

### Screenshots

local development environment. localhost:3000

Kapture 2022-07-29 at 00 10 38

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3597
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

Kapture 2022-07-29 at 00 22 21

### CODE REVIEW

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
Yeah this could be the error introduced in #3595

**Comment by vikiival** [comment]
WFM and tested ✅ 

Thanks so much @Jarsen136 ❤️ haven't spotted this one

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 64.29 USD/KSM ~ 0.778 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0x2045e8bfd3288617878190154a88fdfafaa5f73422362e11a5ea7a0903719884](https://kusama.subscan.io/extrinsic/0x2045e8bfd3288617878190154a88fdfafaa5f73422362e11a5ea7a0903719884)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
