### PR TITLE
1650 use new logo for android

### LINKED ISSUE #1650: New pwa icon seems doesn't work
Seems doesn't offer new icon 👀 from #1647

@kkukelka any idea 💡 why it doesn't work 🤔

https://user-images.githubusercontent.com/5887929/147846330-36bcb6be-dd51-44d3-ba9d-9b060728721e.mp4

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇  _ Do a quick check before the merge. 

### PR type
- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything works
- [ ] I found edge cases

### What's new?
- [x] PR closes #1650
- [ ] <brief_description_of_what_I've_added>

### Had issue bounty label ?
- [ ] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=<My_Kusama_Address>)

### Community participation
- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [ ] My fix has changed **something** on UI, a screenshot for others, is best to understand changes.

### CODE REVIEW

**Comment by yangwao** [comment]
Check bottom, doesn't seems to work 👀

We could name it KodaDot rather than nft-nuxt 😄

**Comment by kkukelka** [comment]
@yangwao fixed the name issue, but the problem for the icon is cache-related
can you somehow clear this folder in beta build via netlify?
Screenshot 2022-01-01 at 11 49 21

**Comment by yangwao** [comment]
Every build preview is fresh deployment, without any cache tho 🤔

Or are you using some absolute path instead relative?

**Comment by yangwao** [comment]
Name seems working now 🤔

**Comment by kkukelka** [comment]
> Every build preview is fresh deployment, without any cache tho 🤔
> 
> Or are you using some absolute path instead relative?

That's so weird... locally, after I deleted the previously mentioned icon folder from `node_modules`, it now correctly generates the pwa icons in the `dist` folder
Screenshot 2022-01-01 at 14 11 18

I'm curious if netlify actually clears `node_modules` and `package-lock.json` on every deploy.. I believe they just scrap the `dist` folder and just generate all files that need to be deployed to their CDN...

maybe we need to enhance build script this one time? 
https://answers.netlify.com/t/not-able-to-clear-cache-and-install-fresh-node-modules-again-after-running-an-npm-dedupe-command/20384

**Comment by yangwao** [comment]
Not sure if you have commited changes, but recent writing during now what I see is this 

https://deploy-preview-1651--koda-nuxt.netlify.app/_nuxt/manifest.3726bf25.json

where points to https://deploy-preview-1651--koda-nuxt.netlify.app/_nuxt/icons/icon_120x120.2c5963.png

which is an old logo, and works tho, errors seem elsewhere :)

If we aren't able clear error on preview deploy, it may slash us somewhere later :D
I mean feel free open new PR to try out if it generates new one, don't forget to refer back here :)

**Comment by kkukelka** [comment]
@yangwao omg finally! sorry for spamming deploys... 😓 

Screenshot 2022-01-01 at 17 35 54

**Comment by yangwao** [comment]
What's was the issue?

**Comment by yangwao** [comment]
hmm on desktop, I don't understand this world
image

**Comment by yangwao** [comment]
okay this time it was client cache lol

**Comment by yangwao** [comment]
working

**Pull request merged**
