### PR TITLE
feat: System appearance mode

### LINKED ISSUE #9806: System appearance mode
right now, we have light and dark mode, lets probably add system mode 

## Design
- instead of clicking to switch, there will be a dropdown
- in the sidebar, there will be visible the current theme

image

- if the whole text "system (dark)" does not fit, we can probably only put "system" with icon there

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Feature

## Needs Design check

- @exezbcz please review

## Context

- [x] Closes #9806

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed UI

image

## Copilot Summary

copilot:summary

copilot:poem

### CODE REVIEW

**Comment by prury** [comment]
i think design can be improved on mobile, just don't know how: 
maybe it could switch between 3 icons? 

image

**Comment by exezbcz** [comment]
> i think design can be improved on mobile, just don't know how: 
> maybe it could switch between 3 icons? 
> 
> image
> 
> 
> 

Yup, it was like that

**Comment by yangwao** [comment]
System Default to avoid confusion?

**Comment by yangwao** [comment]
is it as set default for unconnected users?

image

otherwise lgtm

**Comment by yangwao** [comment]
Thanks!
pay 50 usd

**Comment by Jarsen136** [comment]
> is it as set default for unconnected users?
> 
> image
> 
> otherwise lgtm

It always sets system default if the user has not chosen manually.

For this case unconnected users, I will add the system option there. Users could click the menu to switch to the next theme.

**Pull request merged**
