### PR TITLE
fix deepsource config for vue/multi-word-component-names

### LINKED ISSUE #2627: Fix deepsource configuration
https://deepsource.io/gh/kodadot/nft-gallery/run/6c9a4785-d45e-4867-9910-b90feafde43f/javascript/

image

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #2627

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by preschian** [comment]
Hello @yangwao 
Don't send the payout yet if you want to merge this PR. wait until 1/2 days to make sure the changes work or not

**Comment by yangwao** [comment]
okay so merging and ping me back once we don't see any more errors from deepsource, happy to have this tackled!

**Comment by yangwao** [comment]
run in #2665 
https://deepsource.io/gh/kodadot/nft-gallery/run/85f491ac-458a-4cae-b664-515c0ed18416/javascript/

**Comment by preschian** [comment]
Tested in https://github.com/kodadot/nft-gallery/pull/2676 seems works. hopefully, there is no false alarm again, so we can force to fix deepsource in PR

**Comment by preschian** [comment]
tested in https://github.com/kodadot/nft-gallery/pull/2687

**Comment by preschian** [comment]
@yangwao seems this one is fixed now

**Comment by yangwao** [comment]
seems yes, we have tons of others now! :)

pay 100 usd

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 184.37 USD/KSM ~ 0.542 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0x5f669918bd0ce31de89071c59e4b65dab0a60de0187871232484ab186df3ea0d](https://kusama.subscan.io/extrinsic/0x5f669918bd0ce31de89071c59e4b65dab0a60de0187871232484ab186df3ea0d)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
