### PR TITLE
feat: sticky header in series and spotlight.

### LINKED ISSUE #2353: Sticky header in series and spotlight
I guess in series we are missing ability to what's col name when scrolling 📜 down.

Could be potentially added to series as well for smaller screens

### PR DESCRIPTION
**Pull request by zhyd1997**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2353 
- [x] see the 1st comment I added below

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=H2DifyJqaansQREdGFU4BxZyaApbkCgP1a9Pq4xKaebSFZh)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **sticky header in series and spotlight** on UI; a screenshot is best to understand changes for others.
see the 1st comment I added below

### CODE REVIEW

**Comment by zhyd1997** [comment]
the docs I followed when finishing the task: [Table | Buefy](https://buefy.org/documentation/table).

| page/platform | Web | Mobile |
| ------------- | ------------- | ---------- |
| `/series`  |  :white_check_mark: | :white_check_mark: |
| `/spotlight`  | :white_check_mark:  | :x:  |

### Preview:
`series` on Web:

https://user-images.githubusercontent.com/31362988/154210050-266f8bcc-9038-4a9d-8d22-33a2c5bfebba.mov


`spotlight` on Web:

https://user-images.githubusercontent.com/31362988/154211743-b315ddb2-05e9-4bbf-a09b-7a4bd3b04f8d.mp4


`series` on Mobile:

https://user-images.githubusercontent.com/31362988/154209923-9df4b3be-d0a1-4a40-bbce-89724d8c54d8.mov

### The `spotlight` on Mobile is hard to implement.

two reasons:
1. strange behavior caused by [tooltip](https://buefy.org/documentation/tooltip)

https://user-images.githubusercontent.com/31362988/154212359-6be44657-a361-445f-b490-8b1e90a851ca.mov

**Comment by yangwao** [comment]
oh, I guess for mobile we should stick with the native buefy table component which is already there :)

image

**Comment by yangwao** [comment]
Something is broken there 
image

**Comment by yangwao** [comment]
Seems same bug for spotlight 

image

**Comment by yangwao** [comment]
I guess we can also add more results into the series, like bumping it to 200. As there will be lots of collections coming:)

**Comment by zhyd1997** [comment]
> I guess we can also add more results into the series, like bumping it to 200. As there will be lots of collections coming:)

It's breakpoint issue, and maybe you need change your system preference: try set scrolling to `always`:
system preference

**Comment by yangwao** [comment]
> 

huh, we will ask users to change their settings to use our page? :) 

you've posted me showing scrollbars, that's not the issue. 
The issue it's not showing the whole content of results and in your PR it seems broken, we need to find out why:)

This is how it should look like, screenshot from https://beta.kodadot.xyz which is `main` branch :)

image

**Comment by zhyd1997** [comment]
@yangwao the same issue found in https://beta.kodadot.xyz/, there is an empty space left when I resize my window to 25%.

Screen Shot 2022-02-16 at 19 03 46

and we have pagination for it, so more items may take a long time to load.

**Review by roiLeo — COMMENTED** [review]
I would change $table-sticky-header-height size (default is 300px)

**Comment by zhyd1997** [comment]
> https://beta.kodadot.xyz

I agree with it, but there is also an outer scrollbar, so we need to scroll back to see what the column name is.

is this the expected behavior?

**Comment by zhyd1997** [comment]
> I would change $table-sticky-header-height size (default is 300px)



I agree with it, but there is also an outer scrollbar, so we need to scroll back to see what the column name is.

is this the expected behavior?

**Comment by yangwao** [comment]
> @yangwao the same issue found in [beta.kodadot.xyz](https://beta.kodadot.xyz/), there is an empty space left when I resize my window to 25%.
> 

yes, because you have only 10 items set to show :)

**Comment by zhyd1997** [comment]
@yangwao Yes, I see 🙈

So any ideas for this issue, just double the table sticky header `height` from 300px to 600px?

**Comment by yangwao** [comment]
> @yangwao Yes, I see 🙈
> 
> So any ideas for this issue, just double the table sticky header `height` (from 300px to 600px)?

Remove fixed height of content :)

I see that sticky prop is cutting height which is unwanted
https://buefy.org/documentation/table/

**Comment by zhyd1997** [comment]
@yangwao Yes, it limits the table height to 300px as @roiLeo said.

but if no fixed height (even overwrite the default value) , it's hard to position the table with `sticky`.

**Comment by roiLeo** [comment]
> but if no fixed height (including overwrite the default value) , it's hard to position the table with `sticky`.

Try this on table header:
```css
top: 120px;
position: sticky;
background-color: #090909;
```

**Comment by zhyd1997** [comment]
> > but if no fixed height (including overwrite the default value) , it's hard to position the table with `sticky`.
> 
> Try this on table header:
> 
> ```css
> top: 120px;
> position: sticky;
> background-color: #090909;
> ```

@roiLeo it works well on PC 👍, I will figure out how to do this on mobile.

**Comment by yangwao** [comment]
> > > but if no fixed height (including overwrite the default value) , it's hard to position the table with `sticky`.
> > 
> > 
> > Try this on table header:
> > ```css
> > top: 120px;
> > position: sticky;
> > background-color: #090909;
> > ```
> 
> @roiLeo it works well on PC 👍, I will figure out how to do this on mobile.

on mobile, we don't need sticky header 🥺

**Comment by zhyd1997** [comment]
Sorry for misunderstood.


https://user-images.githubusercontent.com/31362988/154377737-ef0074bb-bd6f-4289-bec6-6105806476a0.mov

The image is so cute when scrolling, is it allowed?

**Comment by zhyd1997** [comment]
@yangwao 
the CI is broken because incompatible node version, I have upgraded node version to `16.14.0` on my local machine, and run `lint`, it works:
Screen Shot 2022-02-17 at 08 11 18

**Comment by zhyd1997** [comment]
I will update my forked repo (instead of merging the main branch) and submit a new PR to check if CI works.

**Comment by zhyd1997** [comment]
New PR still failed, I found the reason for it:

The node version is cached by CI (setup-node action), so even if we upgraded it on our codebase, it will still use cached node version 16.13.2

How to fix it?
[Set `check-latest` flag to `true`](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#check-latest-version)

**Review by roiLeo — CHANGES_REQUESTED** [review]
These css rules will be global, they could break other components. You can try to wrap-them in a component class.
Regarding images overlapping table header have you try something to fix it?

**Comment by zhyd1997** [comment]
@roiLeo got it

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 163.58 USD/KSM ~ 0.611 $KSM
🧗 [H2DifyJqaansQREdGFU4BxZyaApbkCgP1a9Pq4xKaebSFZh](https://kusama.subscan.io/account/H2DifyJqaansQREdGFU4BxZyaApbkCgP1a9Pq4xKaebSFZh)
🔗 [0xdf8eaeb1b335e02783eaeea11bbe91bb74a9b00001efcdfb22cd50ee0eda6ced](https://kusama.subscan.io/extrinsic/0xdf8eaeb1b335e02783eaeea11bbe91bb74a9b00001efcdfb22cd50ee0eda6ced)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
