### PR TITLE
Asset Hubs

### PR DESCRIPTION
**Pull request by vikiival**
## Renaming STMN / STT prefixes to AHK / AHP some code can break

**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes - kodadot/ops-internal#812
- [ ] Requires deployment <snek/rubick/worker>

### <samp>🤖 Generated by Copilot at edfcffe</samp>

This pull request refactors the codebase to use the new `ahk` prefix for the Statemine chain instead of the old `stmn` prefix, and the new `ahp` prefix for the Statemint chain instead of the old `stt` prefix. This is to avoid confusion between the two chains and to match the current subdomains. The changes affect various components, composables, and utils that interact with the chains.

### <samp>🤖 Generated by Copilot at edfcffe</samp>

> _`stmn` becomes `ahk`_
> _Statemine prefix changes_
> _Autumn of refactor_

### CODE REVIEW

**Comment by roiLeo** [comment]
Just why?!  external/internal stuff will certainly break (like https://github.com/dappforce/subid-api/pull/24/files)

**Comment by vikiival** [comment]
> Just why?!

see linked issue

> external/internal stuff will certainly break (like https://github.com/dappforce/subid-api/pull/24/files)

No it won't there is a redirect from stmn to ahk

**Comment by yangwao** [comment]
> Just why?!

Ask w3f why they renamed Statemine 😄
https://github.com/w3f/polkadot-wiki/commit/6231e069906553fe199504a72bce6b8fb957fbbf

**Comment by yangwao** [comment]
> external/internal stuff will certainly break

@roiLeo feel free open issue on that and we can have a look

**Comment by roiLeo** [comment]
Does Teleport page still work?

**Pull request merged**
