### PR TITLE
style: dead bird to X

### LINKED ISSUE #6851: replace dead bird in footer - Bird is ded, X is new vigilant
image

-> 

image

### PR DESCRIPTION
**Pull request by stephenjason89**
## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context
- [x] Closes #6851 

- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer?target=16UcV9V6nVvPYdHz98ymUKmNLkzjCEU5sbKJMi7hxYyTHjzR&usdamount=100&donation=true)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸
Footer and all the other locations uses that X
image

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at 769abca</samp>

Refactored the code for opening the shopping cart modal from the navbar. Moved the logic and configuration from `ShoppingCartModalConfig.ts` and `ShoppingCartButton.vue` to `Navbar.vue` to improve code organization and performance.

### <samp>🤖 Generated by Copilot at 769abca</samp>

> _`ShoppingCartButton`_
> _Simpler, no more `emit` -_
> _Autumn leaves falling_

### CODE REVIEW

**Comment by stephenjason89** [comment]
@yangwao When Twitter rebranded to X, the bird didn't fly away—it just got crossed out! 🐦✖️

**Comment by stephenjason89** [comment]
@yangwao The Twitter bird didn't just fly away; X marks its final resting spot.

**Review by preschian — APPROVED** [review]

**Review by roiLeo — APPROVED** [review]

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 4.48 USD/DOT ~ 6.696 $DOT
🧗 [16UcV9V6nVvPYdHz98ymUKmNLkzjCEU5sbKJMi7hxYyTHjzR](https://polkadot.subscan.io/account/16UcV9V6nVvPYdHz98ymUKmNLkzjCEU5sbKJMi7hxYyTHjzR)
🔗 [0x577e8b29080d74c5e35980ddae54c135bf64610a18847ad47fc8a9f2c29b9792](https://polkadot.subscan.io/extrinsic/0x577e8b29080d74c5e35980ddae54c135bf64610a18847ad47fc8a9f2c29b9792)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
