### PR TITLE
🔥 remove tabs from massmint

### LINKED ISSUE #6455: Massmint tabs are not working
### What happened?

nothing happens when you: 
image

found by @roiLeo 

### Please reproduce in steps

Create -> Multiple NFTs

### Expected Behavior

should lead to either nft creation page or collection creation page

### What browsers are you seeing the problem on?

Desktop Firefox

### At which address did you encounter bug?

canary.kodadot.xyz

### Are you logged in?

None

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

_No response_

### Screenshots

^

### Relevant log output

_No response_

### Payment link for reward

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #6455

#### Did your issue had any of the "$" label on it?

- [ ] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>)

### <samp>🤖 Generated by Copilot at 5ea8887</samp>

Refactored the Mass Mint feature to have its own route and page. Cleaned up unused and redundant code in `Massmint.vue`.

### <samp>🤖 Generated by Copilot at 5ea8887</samp>

> _Sing, O Muse, of the code review that sparked a great debate_
> _Among the developers of the app that mints NFTs with ease_
> _How one of them, a skillful coder, wise and diligent,_
> _Removed the unused tabs that cluttered `Massmint.vue` with grace_

### CODE REVIEW

**Comment by Jarsen136** [comment]
before 
image

after
image


I'm not sure if we should keep only the "Mass mint" tab or make other tabs disabled status.

**Comment by daiagi** [comment]
@Jarsen136 
I remember seeing somewhere discussion with @exezbcz 
about removing these tabs and unifying the mass mint page with a new design flow of mint
* https://github.com/kodadot/nft-gallery/issues/5939


these tabs are left over from old design and are no longer needed
@exezbcz is that correct?

**Comment by exezbcz** [comment]
@daiagi yes, that is correct
more info here: 
- #6318

**Review by Jarsen136 — APPROVED** [review]

**Comment by prury** [comment]
@daiagi can you make it look like that?

image

as requested inside the figma file:

image

**Comment by prury** [comment]
> @prury done

perfect, thank you!

**Pull request merged**
