### PR TITLE
feat: mobile menu ui rework

### LINKED ISSUE #2772: Mobile menu is overlapping
Searchbar width is breaking on iPhone 12
Capture d’écran 2022-04-05 à 2 12 24 PM
We can delete the small gap in navbar item button (left margin) because it is not present on the right.
History button could be move outside burger menu.
I would also put the connect button full width as a call to action (change to primary color) to encourage users to log in.

As I tap to "create" something is wrong with focus  
image

When using searchBar the navbar is overlapping and we can see the logo behind
Capture d’écran 2022-04-05 à 2 10 32 PM

We could try to add a search Icon near burger menu that would display the search bar and hide logo on mobile
something like this: 
Capture d’écran 2022-04-05 à 2 35 28 PM

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2772
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything seems works
- [x] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

image

### CODE REVIEW

**Comment by Jarsen136** [comment]
It's so hard to make this change... because the logic of the search bar is too heavy

**Comment by Jarsen136** [comment]
I wonder is there anything I should do for this pr, and when it could be merged  👀

**Comment by roiLeo** [comment]
> I wonder is there anything I should do for this pr, and when it could be merged 👀

I'll merge it soon, I need to test it more on mobile no need to rush

**Review by roiLeo — APPROVED** [review]
I made some changes, tested it on nova wallet and the mobile experience is better

**Comment by roiLeo** [comment]
pay 50

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 167.04 USD/KSM ~ 0.299 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xe496db33da803462c8aa51ff2ae876326699cec6558dc96127f08aee9d31f19a](https://kusama.subscan.io/extrinsic/0xe496db33da803462c8aa51ff2ae876326699cec6558dc96127f08aee9d31f19a)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
