### PR TITLE
feat: setup fa icon for oruga

### LINKED ISSUE #4689: `NeoButton` UI component icon
We need to find a smart way to use (fontawesome) icon in `libs/ui` components

might be needed in some PR, you could start to use it in footer btn

### LINKED ISSUE #4760: Dropdown buttons on mobile
image
- it should be normal dropdown under the button as on desktop

share button on mobile is collapsed - not with text "share" 
image

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #4760
- [x] PR closes #4689

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

localhost_9090_rmrk_gallery_9785567-0a24c7876a892acb79-RADTOADZ-RADTOADZ-0000000000000018(iPhone 12 Pro)

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
✅ code lgtm

**Comment by exezbcz** [comment]
> oh wait, there's something missing on explore Screenshot 2023-01-20 at 22 51 42

also the button fill looks like is not black :D

**Review by Jarsen136 — APPROVED** [review]
code lgtm

**Comment by exezbcz** [comment]
> some adjustment:
> 
> * to remove the warning message on the browser console, I set the medium-size button as default. is that ok? (I adjust the styling to match with the default size button)
> * checkmark icon on explore button little bit thicker, because now using font-awesome. is that ok? cc @exezbcz
> 
> Screenshot 2023-01-20 at 23 55 49

ufff, that check from font awesome does not look good xd, is there thinner version or? I would stick to the think one if its possible.

**Comment by exezbcz** [comment]
looks good, one thing is that now in dark mode it does not show the check. The icon is there but has white/black color and is invisible. Again, not sure whether it was changed here. 
image

**Pull request merged**
