### PR TITLE
fix: Profile: Activity: Not showing NFT numbers

### LINKED ISSUE #9444: Profile: Activity: Not showing NFT numbers
AHP, Generative
Go to Profile - activity, and NFTs with #numbers are missing these numbers:
Screenshot 2024-02-16 at 15 35 50

It would look better if we showed these numbers.

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Feature

  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #9444

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

profile page
image

collection page
image

  ## Copilot Summary
  copilot:summary

  copilot:poem

### CODE REVIEW

**Review by vikiival — APPROVED** [review]
Very ugly function name `addSnSuffixName,`

but LGTM

**Comment by Jarsen136** [comment]
> Very ugly function name `addSnSuffixName,`
> 
> but LGTM

How about `appendSerialNumberToName`, `addSnToName` or `nameWithSn`?

**Review by daiagi — APPROVED** [review]

**Comment by vikiival** [comment]
`nameWithIndex` :D but can be done in separated issue

**Comment by prury** [comment]
here or followup? 
mobile not showing sn, 

image

**Comment by vikiival** [comment]
> here

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 7.82 USD/DOT ~ 3.836 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x2422d63ccb92d957f39a2b6f81f18c0fdea3b55aa43154c6330857ac75425946](https://polkadot.subscan.io/extrinsic/0x2422d63ccb92d957f39a2b6f81f18c0fdea3b55aa43154c6330857ac75425946)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
