### PR TITLE
feat: Estimate in signing modal 

### LINKED ISSUE #9150: Estimate in signing modal
lets add an estimate to a signing modal as it is in the transfer

image

(here)
image

updated in figma: https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=6886-20058&mode=design&t=wM446sUazK1vdZK8-11

- could the pill-shaped thing please not rescaled with every second? 
- The solution would be to make it fixed and the text inside centered

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #9150

## Needs Design check

- @exezbcz please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

https://github.com/kodadot/nft-gallery/assets/44554284/99d430e1-1415-48fa-b5ef-c97585239665

### CODE REVIEW

**Review by preschian — APPROVED** [review]
code lgtm

*not tested

**Comment by exezbcz** [comment]
works for me

https://github.com/kodadot/nft-gallery/assets/90852205/52357ccb-5333-486f-b5cb-3ec4863bf498



followup coming 



thanks!

**Review by roiLeo — APPROVED** [review]

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 6.75 USD/DOT ~ 4.444 $DOT
🧗 [16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD](https://polkadot.subscan.io/account/16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)
🔗 [0x931b57d8b0bea1f1f22e5e64ab1935affea28438539cf03fbe0a2b6b8df5c17d](https://polkadot.subscan.io/extrinsic/0x931b57d8b0bea1f1f22e5e64ab1935affea28438539cf03fbe0a2b6b8df5c17d)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
