### PR TITLE
feat: support passion feed searching

### LINKED ISSUE #3239: support passion feed searching in lastEvent resolver
In order to avoid duplicate elements on 【Newest List】/【Latest Salse】, we create a new resolver 'lastEvent'. Still need to make it support passion feed searching.

ref: https://github.com/kodadot/nft-gallery/pull/3062

- [x] remove duplicate item from [Newest List]/[Latest sales]
- [x]  inaccurate time to nft listing
- [x] nft may be displayed on [Newest List] even if  its listing price equal to 0.

- [ ] support passion feed
image

_Originally posted by @Jarsen136 in https://github.com/kodadot/nft-gallery/issues/3062#issuecomment-1161050376_

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #3239 
- [x] Requires deployment https://github.com/kodadot/rubick/pull/102
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by kkukelka — APPROVED** [review]
Code looks good. Please @Jarsen136 let me know when the needed  api is deployed so i can merge

**Comment by petersopko** [comment]
pay 200 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $200 @ 45.71 USD/KSM ~ 4.375 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xee12ababeab961a06ec6aefe80ed947e1c9855572a2589c9e1b984fefeb1a170](https://kusama.subscan.io/extrinsic/0xee12ababeab961a06ec6aefe80ed947e1c9855572a2589c9e1b984fefeb1a170)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by prachi00** [comment]
@Jarsen136 @petersopko 
Screen Shot 2022-07-04 at 6 32 14 PM
Even though the `passionFeed` query gives out empty array as a result, the `lastNftListByEvent` query gives out results, it should be empty for this query in case of passionfeed, I think it happened with the new changes with adding `passionAccount` field
Screen Shot 2022-07-04 at 6 32 56 PM
Screen Shot 2022-07-04 at 6 33 08 PM

**Comment by Jarsen136** [comment]
> Even though the `passionFeed` query gives out empty array as a result, the `lastNftListByEvent` query gives out results, it should be empty for this query in case of passionfeed, I think it happened with the new changes with adding `passionAccount` field 

@prachi00  Hey, it's true. `lastNftListByEvent` will return some last events if someone does not have any passionFeed. I would rather call it as a feature.
If not, the person who login without any passionFeed will see nothing at `Newest List` on landing page.

**Comment by prachi00** [comment]
> > Even though the `passionFeed` query gives out empty array as a result, the `lastNftListByEvent` query gives out results, it should be empty for this query in case of passionfeed, I think it happened with the new changes with adding `passionAccount` field
> 
> @prachi00 Hey, it's true. `lastNftListByEvent` will return some last events if someone does not have any passionFeed. I would rather call it as a feature. If not, the person who login without any passionFeed will see nothing at `Newest List` on landing page.

yeah does make sense but it causes issues for #3132 because if you toggle in the landing page data doesn't change and it looks confusing, how do we handle that then?
@roiLeo what do you suggest we do?

**Comment by Jarsen136** [comment]
> > > Even though the `passionFeed` query gives out empty array as a result, the `lastNftListByEvent` query gives out results, it should be empty for this query in case of passionfeed, I think it happened with the new changes with adding `passionAccount` field
> > 
> > 
> > @prachi00 Hey, it's true. `lastNftListByEvent` will return some last events if someone does not have any passionFeed. I would rather call it as a feature. If not, the person who login without any passionFeed will see nothing at `Newest List` on landing page.
> 
> yeah does make sense but it causes issues for #3132 because if you toggle in the landing page data doesn't change and it looks confusing, how do we handle that then? 

there are two solutions
1. if `passionFeed` query gives out an empty array as a result, then show nothing on landing when enable passionFeed.
It's very strange but works.
2. modify the `lastEvent` resolver.

> @roiLeo what do you suggest we do?

I wonder what do you expect it to show if `'passionFeed' query gives out an empty array as a result`. Show nothing or ..

**Comment by prachi00** [comment]
> 

yeah until now we were showing empty right, so should be fine

**Comment by roiLeo** [comment]
I don't really know what's this PR is about but here's how I see things:
**As a user, I need/want to know when the data is biased**

I find it really important to show to the logged user when the data is coming from the passionFeed or from the lastest event

**Comment by prachi00** [comment]
> I don't really know what's this PR is about but here's how I see things: **As a user, I need/want to know when the data is biased**
> 
> I find it really important to show to the logged user when the data is coming from the passionFeed or from the lastest event

yeah I agree, I am just confused about how to detect that now since the api isnt giving out empty results for passionfeed in `lastNftListByEvent`
can we like get this query to give out empty results like before so we know its getting the correct data and user can know  @Jarsen136

**Comment by Jarsen136** [comment]
>can we like get this query to give out empty results like before so we know its getting the correct data and user can know >@Jarsen136


> there are two solutions
> 
> 1. if `passionFeed` query gives out an empty array as a result, then show nothing on landing when enable passionFeed.
>    It's very strange but works.
> 2. modify the `lastEvent` resolver.
> 



How about taking the first solution? if `passionFeed` query result is empty, it's unnecessary to fetch an empty events feed result from api.

**Comment by prachi00** [comment]
> > can we like get this query to give out empty results like before so we know its getting the correct data and user can know >@Jarsen136
> 
> > there are two solutions
> > 
> > 1. if `passionFeed` query gives out an empty array as a result, then show nothing on landing when enable passionFeed.
> >    It's very strange but works.
> > 2. modify the `lastEvent` resolver.
> 
> How about taking the first solution? if `passionFeed` query result is empty, it's unnecessary to fetch an empty events feed result from api.

uh yeah that is right, but do you know why we did it like that in the first place? hoping it wont break any existing flow that we have 😅

**Comment by Jarsen136** [comment]
>  uh yeah that is right, but do you know why we did it like that in the first place? hoping it wont break any existing flow that we have 😅

For better user experience I guess. It works well for now.  😄

**Comment by prachi00** [comment]
> > uh yeah that is right, but do you know why we did it like that in the first place? hoping it wont break any existing flow that we have 😅
> 
> For better user experience I guess. It works well for now. 😄

cool thanks

**Pull request merged**
