### PR TITLE
fix: 3D NFT Thumbnail Preview

### LINKED ISSUE #6953: 3D NFT Thumbnail Preview
### What happened?

I created 3D NFT collection on RMRK 1.0 and was unable to migrate in time. I would like to promote the collection on Koda but can only see the 3D NFT individually. When viewing the whole collection on one page the NFT shows as K. 

Can Koda please add preview for 3D NFTs. I noticed Videos also dont have a preview for thumbnails. If this can be resolved I will promote my collection through Koda. Thank you! 

Please email response to info@zigastudio.com :)

### Please reproduce in steps

Here are links to collection for reference. 

Individual 3D NFT works but loads slowly. 
https://kodadot.xyz/rmrk/gallery/11906995-f4f8d7504c60bb5721-VB7SA-MONEYBIRD18-0000000000000018

Collection shows many K logos but no 3D preview. 
https://kodadot.xyz/rmrk/collection/f4f8d7504c60bb5721-VB7SA

### Expected Behavior

I would expect to be able to view the NFTs as a group with 3D thumbnails as RMRK does. I also noticed it takes some time to load the model. 
Screen Shot 2023-08-25 at 11 16 36 AM

### What browsers are you seeing the problem on?

Desktop Chrome

### At which address did you encounter bug?

kodadot.xyz

### Are you logged in?

No

### Which wallet you are using?

PolkadotJS

### At which chain did you encounter bug?

Kusama

### Screenshots

Screen Shot 2023-08-25 at 11 16 36 AM

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/ksm/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix
  - [ ] Refactoring: remove unused components
  `components/shared/gallery/GalleryItemCardList.vue` and `components/shared/gallery/NftCard.vue`

  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #6953
  - [ ] Requires deployment <snek/rubick/worker>

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

/rmrk/collection/f4f8d7504c60bb5721-VB7SA
(It took some time to download the 3D object)
image

  ## Copilot Summary
  
### <samp>🤖 Generated by Copilot at ee3f53c</samp>

This pull request standardizes the NFT metadata format across the app by using the `BaseNFTMeta` interface and a `formatNFT` utility function. It also removes some unused components and renames an inconsistent property.

  
### <samp>🤖 Generated by Copilot at ee3f53c</samp>

> _We are the masters of the NFTs_
> _We shape their metadata as we please_
> _We use the `BaseNFTMeta` to unify_
> _We crush the chaos with our standardize_

### CODE REVIEW

**Comment by Jarsen136** [comment]
As for [More From This Collection] section, all the 3d items do not display properly.

image

I debugged it and found that there is a comment code for this logic from @preschian. That means it's blocked by another issue #6237

image

**Comment by prury** [comment]
took a long time, but all of them loaded properly: 

image

**Review by stephenjason89 — APPROVED** [review]
Code lgtm

**Review by preschian — COMMENTED** [review]
I thought the fix was in this line https://github.com/kodadot/nft-gallery/blob/main/libs/ui/src/components/NeoNftCard/NeoNftCard.vue#L17

`nft.animationUrl || nft.animation_url`

**Comment by daiagi** [comment]
I'm going to admit to something
I am confused about why we have so many "paths" to get to the media of an NFT
Plus we seem to have recurring  bugs from these issues, always some media not working here or there

maybe we can take a deep approach and sort out this mess more properly?

Ideally, I think I would like to see a single URL coming from the indexer and the mime type

@kodadot/internal-dev  @yangwao

**Comment by preschian** [comment]
> I debugged it and found that there is a comment code for this logic from @preschian. That means it's blocked by another issue #6237

for this one, I think it better to revert that @Jarsen136 wdyt? re-add back animation-src

**Comment by preschian** [comment]
> I am confused about why we have so many "paths" to get to the media of an NFT

I think this is the challenge we face to support multi-chain. Because each chain has different specs. For example, this is a related issue between rmrk1 and rmrk2 https://github.com/kodadot/workers/issues/95

another challenge related to metadata stuff is, on the asset hub creators can put their metadata on non-ipfs. ref: https://github.com/kodadot/nft-gallery/issues/6618#issuecomment-1671163766

**Comment by Jarsen136** [comment]
> I thought the fix was in this line https://github.com/kodadot/nft-gallery/blob/main/libs/ui/src/components/NeoNftCard/NeoNftCard.vue#L17
> 
> `nft.animationUrl || nft.animation_url`

I would like to unify them. Or it would be confused that if there is `animationUrl` or `animation_url`.

Moreover, there is already a type definition with only `animationUrl` in the nft meta.
image

**Comment by Jarsen136** [comment]
> > I debugged it and found that there is a comment code for this logic from @preschian. That means it's blocked by another issue #6237
> 
> for this one, I think it better to revert that @Jarsen136 wdyt? re-add back animation-src

I agree with you

**Comment by preschian** [comment]
> Moreover, there is already a type definition with only `animationUrl` in the nft meta.

do we need handle `animation_url || animationUrl` somewhere? I found out that we have something like this in our query `animation_url: animationUrl`

**Comment by vikiival** [comment]
> to be honest,
> 

> 

> 
> 
> 
> maybe we can take a deep approach and sort out this mess more properly?

Hello,


> I am confused about why we have so many "paths" to get to the media of an NFT

the majority of f*ckups we had is with RMRK 2.0 standard they invented their own metadata types that differ a lot for the industry standard. 

> Ideally, I think I would like to see a single URL coming from the indexer and the mime type

All indexers have metadada available. We can fetch the mimetype from indexer too via HEAD. 


To unify metadata standard for one I opened an issue for the minipfs. 

https://github.com/kodadot/packages/issues/161


> Two URLs, one for full media and another for scaled-down version would also be good so we can display videos and improve loading times

Already done with image-worker, please open issue in kodadot/workers if in case you find a bug, or have feature request. 


> Plus we seem to have recurring  bugs from these issues, always some media not working here or there

In ideal scenario client should not fetch ipfs metadata from gateway but opt-in for indexer. 

If there is generally missing something in indexer please open issue in kodadot/loligo. 

If you find a bug/ miss something in specific indexer we have:
- ksm, rmrk - rubick
- bsx, snek - snek
- ahk, ahp - stick

**Comment by vikiival** [comment]
@Jarsen136 can you remove the components in separated PR?

**Comment by Jarsen136** [comment]
> > Moreover, there is already a type definition with only `animationUrl` in the nft meta.
> 
> do we need handle `animation_url || animationUrl` somewhere? I found out that we have something like this in our query `animation_url: animationUrl`

Seems not. I found that most of the cases would use `getNftMetadata` to fetch the final metadata. They are not using that from the indexer side directly.

**Comment by Jarsen136** [comment]
> @Jarsen136 can you remove the components in separated PR?

Done. I have reverted it.

**Comment by Jarsen136** [comment]
> > I debugged it and found that there is a comment code for this logic from @preschian. That means it's blocked by another issue #6237
> 
> for this one, I think it better to revert that @Jarsen136 wdyt? re-add back animation-src

✅ DONE. Now they are back.

image

**Review by daiagi — APPROVED** [review]

**Comment by yangwao** [comment]
> took a long time, but all of them loaded properly:

can you try again? iirc our gateway stores it afterwards which load times should be much faster next time :)

**Comment by yangwao** [comment]
pay 50 usd 
gg!

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 4.5 USD/DOT ~ 11.111 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x026c4f6f57863666ff4956daa088e9b2db4e02b670fa3695ce9803bd88e61e31](https://polkadot.subscan.io/extrinsic/0x026c4f6f57863666ff4956daa088e9b2db4e02b670fa3695ce9803bd88e61e31)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by prury** [comment]
> > took a long time, but all of them loaded properly:
> 
> can you try again? iirc our gateway stores it afterwards which load times should be much faster next time :)

indeed, much faster now, nice!

**Comment by ziga-hash** [comment]
Impressive work!

**Pull request merged**
