### PR TITLE
feat: Transfer Page does not verify correct adrress format

### LINKED ISSUE #6949: Transfer Page does not verify correct adrress format
### What happened?

in short, it seems possible to send to wrong ss58 format address

### Please reproduce in steps

Transfer page
Select to transfer KSM
paste in a DOT address

the address is not changed into ksm format nor there is a warning  / disabling the submit button

### Expected Behavior

@exezbcz does your design address this issue?

I guess the two options are:
1. Show the user the correct address, like it was in the old transfer page
2. show a warning and block the submit button button

### What browsers are you seeing the problem on?

_No response_

### At which address did you encounter bug?

_No response_

### Are you logged in?

None

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

_No response_

### Screenshots

image

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/ksm/transfer/?target=%3CMy_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address%3E

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by hassnian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #6949

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

eth address
CleanShot 2023-09-02 at 11 39 30@2x

Wrong polkadot Network address
CleanShot 2023-09-02 at 11 39 59@2x

change address 
CleanShot 2023-09-02 at 11 40 34

### <samp>🤖 Generated by Copilot at 310f493</samp>

This pull request adds and improves address validation functionality for transferring NFTs. It introduces a new `AddressChecker.vue` component that shows an info box with a message and a button to correct invalid or wrong network addresses. It also modifies the `AddressInput.vue` component to emit events and accept a prop for clearing and validating the input. It updates the `Transfer.vue` component to use these features and handle errors. It also adds new translation keys and values to the `locales/en.json` file.

### <samp>🤖 Generated by Copilot at 310f493</samp>

> _Oh we're the crew of the `Transfer.vue`_
> _And we sail the network sea_
> _We check the address with the `AddressChecker`_
> _Or we clear it on the count of three_

### CODE REVIEW

**Comment by hassnian** [comment]
@exezbcz pls visual check

**Comment by exezbcz** [comment]
let me make the dark mode in a sec: 
image

how is this not a polkadot ecosystem address? 5FNRfuQfuBymCXiuY5rq7ewBXZzVQ8gPEmt4LTDG7kZeecFm
- its a general non formated address from polkadot js

**Comment by hassnian** [comment]
> 5FNRfuQfuBymCXiuY5rq7ewBXZzVQ8gPEmt4LTDG7kZeecFm

on it

**Comment by exezbcz** [comment]
dark mode colors: 
image
- the red stroke stays the same, green stroke is different color but reuses the same as the bg of activity offer tag: 
image
- green stroke: `#056A02`
- green background - new color: `#0A3009` 
- red stroke - same as on light mode 
- red bg - new color: `#390B0B` 

Ad button: this button has no hover effect, only the cursor pointer 
image
- The default state is stroke black, rest transparent

**Comment by hassnian** [comment]
@exezbcz do we have this button "transparent" being used anywhere else in the app ?

**Comment by exezbcz** [comment]
@hassnian okay, you can use the button secondary hover effects for that - default state is this: 
image
hover: 
image

**Comment by hassnian** [comment]
@exezbcz so what would happen if you are on DOT and you input that address what should be the message

**Comment by exezbcz** [comment]
@hassnian yes cc @EthVlad 

I am still not sure about the heading. I think it would be more accurate and easier to understand with heading: "wrong address format" 
- okay, lets make it "wrong network address"

- Then there rest could stay the same 

- I would also change DOT and KSM, since it's a currency ticker, not a network name. 



> @exezbcz so what would happen if you are on DOT and you input that address what should be the message

if you are on dot and you input Polkadot address - its okay

this dialog popups when the address inputted is different from the network you are sending the token on 
- does that makes sense? I will create more instances of the popup for you

**Comment by exezbcz** [comment]
basically like this: 
image

**Comment by hassnian** [comment]
@exezbcz  yep makes sense , the only thing I need is the text for this case 

you have a generic substrate address and you are on dot for example , that would be invalid and we should show that pop up  

like you entered a Generic Substrate Adress please provide a DOT address . Something like this idk

**Comment by exezbcz** [comment]
> Generic Substrate Adress please provide a DOT address

exactly, works for me

**Comment by hassnian** [comment]
> basically like this: 
> 
> image
> 
> 

ok got it , it's the same just update the chain names

**Comment by hassnian** [comment]
@exezbcz pls visual check 

feel free to do it on the preview build 

CleanShot 2023-09-03 at 12 13 15@2x

CleanShot 2023-09-03 at 12 12 59@2x

**Review by prury — APPROVED** [review]

**Comment by hassnian** [comment]
@preschian I saw you added `vue-safe-html` 

In this pr I also needed translation variables and I ended up using the markdown component since I wasn't sure about introducing a new package , as mentioned [here](https://github.com/ecosia/vue-safe-html/issues/85)  this package will strip a all atributes

CleanShot 2023-09-05 at 12 16 35@2x


I have an a tag  with href and this package wont work 

CleanShot 2023-09-05 at 12 18 30@2x

can we switch to another solution like [this](https://www.npmjs.com/package/vue-dompurify-html) maybe, or any other solution ?

**Comment by preschian** [comment]
> @preschian I saw you added `vue-safe-html`
> 
> In this pr I also needed translation variables with html and I ended up using the markdown component since I wasn't sure about introducing a new package , as mentioned [here](https://github.com/ecosia/vue-safe-html/issues/85) this package will strip a all attributes
> 
> can we switch to another solution like [this](https://www.npmjs.com/package/vue-dompurify-html) maybe, or any other solution ?

Sure, feel free to replace that with `vue-dompurify-html`. I'm okay as long the package handles both of them 👍

**Review by preschian — APPROVED** [review]

**Comment by stephenjason89** [comment]
Looks good to me

**Review by stephenjason89 — APPROVED** [review]

**Comment by yangwao** [comment]
pay 60 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $60 @ 4.27 USD/DOT ~ 14.052 $DOT
🧗 [13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh](https://polkadot.subscan.io/account/13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)
🔗 [0xf02cb8fd64f89a1f1a0ecef37ac394d3e328bc42759ebf48e408b3472e78cb73](https://polkadot.subscan.io/extrinsic/0xf02cb8fd64f89a1f1a0ecef37ac394d3e328bc42759ebf48e408b3472e78cb73)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
