### PR TITLE
check ED on source and target chains 

### LINKED ISSUE #8614: Teleporting max and lower amounts dont work
So, my job is customer support right now

One user encountered issues with teleporting from ahp back to polkadot 

>I completed the transaction 3 times but not receive

>what wallet address?

>14W7pYFQ8ZqevGR9yiiCsPW1Qhs2axU2xZW4XLKb2zPpXh9k

>and what mobile wallet you use?

>Subwallet

telegram-cloud-photo-size-5-6336743557259442151-y

so as you can see, on the img he has 
image

he could not teleport max, it did not even work when he used 2.1 dot 

it finally worked when he sent 2 dot

one tx id i got: 0x7eceb58add08811c686363e3e67cad816272ee20c16ace885634a22449b834f8

thanks @hassnian for helping with problem identification

### LINKED ISSUE #8635: Teleport warning should check balance on target account
related with #8631 

>@daiagi strange, i'm still not seeing the currency, even after cache clear or browser change
and now message appears even if i funds on destination chain

need to retrieve currant balance of target account and compare it to required ED

### LINKED ISSUE #8733: Gas fees Was deducted but my fund was not transferred
My address - 12mzts3xRmQiZtUJPMZTUBVaCuXRDVMeFLZCJnPrCg6t7eKn

I was doing a transfer from my PolkaDot asset hub to native Polka Dot but the fee got deducted every time and the funds were not transferred I did it like 10 times but its still the same

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [x] Feature
- [x] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #8635
- [x] Closes #8733 
- [x] Closes #8614

## More Info
- bug fix
a. fix the bug listed in the issue
b. buffer fees were 10X too large

- Refactoring
cleaned up the code, merged some computed refs for better ergonomics

- Feature
 Prevent teleport that will be less then ED on both sending and receiving ends
warning message and warning modal reflect that
still allow teleport of entire balance as this will not cause loss of funds on sending end (as long as it is bigger then recivenig ED obv)

#### Did your issue had any of the "$" label on it?

Yes, $ on #8614

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)

### ED on sending side
image
image

### ED on Receiving side
image
image

### teleport entire balance(ok)
image

### teleport entire balance (not Ok)

image

### CODE REVIEW

**Comment by exezbcz** [comment]
could you test please @prury 👀

**Comment by prury** [comment]
missing rest of message:
image


### Warning tests: 

- Polkadot( balance 1 DOT ) -> Polkadot Hub ( balance 0 DOT ) - warning appears if i try to transfer less than 1 DOT (Source)

- Polkadot ( Balance 1.2 DOT ) -> Polkadot Hub ( balance 0 DOT ) - warning appears if i try to transfer less than 0.12 (Destination)

- PolkadotHub ( balance 0.2 DOT) -> Polkadot ( balance 1 DOT ) - warning appears if i try to transfer more than 0.1 DOT (Source)

- Max on both PolkadotHub and Polkadot works

- KusamaHub( balance 0.009 KSM ) -> Kusama ( Balance 0 KSM) - warning message appears if i try to transfer less than 0.0005 KSM (Destination)

- KusamaHub ( KSM) -> Kusama ( KSM) - warning message appears if i try to leave my account with less than 0.000003333 KSM (Source)

i think KusamaHub ED message is missing one 0, there's only 4
image

**Comment by daiagi** [comment]
>missing rest of message:

>i think KusamaHub ED message is missing one 0, there's only 4

 did i understand correctly these are the only issues to fix?

**Comment by prury** [comment]
> >missing rest of message:
> 
> >i think KusamaHub ED message is missing one 0, there's only 4
> 
>  did i understand correctly these are the only issues to fix?

Yes! Sorry for not being clearer

**Comment by daiagi** [comment]
@prury 
image

**Comment by yangwao** [comment]
Thanks!
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 8.64 USD/DOT ~ 5.787 $DOT
🧗 [1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8](https://polkadot.subscan.io/account/1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)
🔗 [0x2256feba9d0add200d087039bafa0621c358802e597e08c309b285dcd4e24c98](https://polkadot.subscan.io/extrinsic/0x2256feba9d0add200d087039bafa0621c358802e597e08c309b285dcd4e24c98)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
