### PR TITLE
feat: highlight code

### LINKED ISSUE #6487: Syntax highlighting and dark mode for code blocks on blog markdown
one last thing sir, can we make the code blocks for dark mode too? 
image

_Originally posted by @exezbcz in https://github.com/kodadot/nft-gallery/issues/6471#issuecomment-1656735850_
            

ref: highlight.js

### PR DESCRIPTION
**Pull request by floyd-li**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

enable code highlight on blog post. support light and dark theme.

code syntax theme based on `atom-one` theme

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #6487
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

图片

图片

### <samp>🤖 Generated by Copilot at 60f740a</samp>

Added code highlighting feature for blog posts using `highlight.js`. Adjusted code block style to match page theme.

### <samp>🤖 Generated by Copilot at 60f740a</samp>

> _In the dark of the night, we write our stories_
> _With the power of code, we shape our glories_
> _We unleash the light, we highlight our code blocks_
> _We adapt to the fight, we change our syntax_

### CODE REVIEW

**Comment by floyd-li** [comment]
@exezbcz pls review this pr

**Comment by floyd-li** [comment]
>  Is it needed for it to have left-right padding? 

>  could you please make the font size in the code bloc 16px

both done @exezbcz

**Comment by exezbcz** [comment]
image
something weird here
https://deploy-preview-6794--koda-canary.netlify.app/blog/first-time

By the way, is there any way to add copy code to each of them in the follow-up, or would it require more than I think?

works for me

**Comment by floyd-li** [comment]
> image something weird here https://deploy-preview-6794--koda-canary.netlify.app/blog/first-time
> 

图片

manually adjust the color of the inline code-block to match the code syntax theme 

> By the way, is there any way to add copy code to each of them in the follow-up, or would it require more than I think?

i think this feature need integration of [clipboard.js](https://github.com/zenorocha/clipboard.js), if you want it i may do it in another pr. wdyt? 

cc @vikiival @yangwao

**Review by preschian — APPROVED** [review]

**Comment by exezbcz** [comment]
> i think this feature need integration of [clipboard.js](https://github.com/zenorocha/clipboard.js), if you want it i may do it in another pr. wdyt?

I did follow up with p4, let's see if its demanded


nice job!

**Comment by vikiival** [comment]
4 mb package 🥲

**Comment by exezbcz** [comment]
@vikiival then its pass

**Comment by yangwao** [comment]
> 4 mb package 🥲

@floyd-li isn't there lighter package?

**Comment by floyd-li** [comment]
> 4 mb package 🥲

sorry but which package? i did not import any new package this pr 🤔️

**Comment by yangwao** [comment]
> sorry but which package? i did not import any new package this pr 🤔️

ah I see we are already using it 
https://github.com/kodadot/nft-gallery/blob/main/package.json#L100

@vikiival then whatever merge?

**Comment by vikiival** [comment]
Yup, proceed and merge

**Review by vikiival — APPROVED** [review]

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 4.49 USD/DOT ~ 6.682 $DOT
🧗 [13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A](https://polkadot.subscan.io/account/13rv1SWoLg9Gb3tmvHPZxb7JbVy51BtMziX7k9WQGSJ7Kp3A)
🔗 [0xab1358d4fa0efa486149e1811374ea8e3ceb131c6c1da662da2b2654f2594597](https://polkadot.subscan.io/extrinsic/0xab1358d4fa0efa486149e1811374ea8e3ceb131c6c1da662da2b2654f2594597)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
