### PR TITLE
fix: attach fall through attributes to teleport component

### LINKED ISSUE #9661: NeoModal class props warning
image

### PR DESCRIPTION
**Pull request by AnmolBansalDEV**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

(please remove design and QA checks below if not needed)

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #9661
- [ ] Requires deployment <worker/stick/speck>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ahp/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=12b5bwwugf3CgWy58MPYQAX9wazLX1S71ghgZ4YPb6g4qbEP)

#### Community participation

- [x] [Are you at Koda Ecosystem Telegram?](https://t.me/koda_eco)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by preschian — APPROVED** [review]

**Comment by vikiival** [comment]
@Jarsen136

**Review by Jarsen136 — APPROVED** [review]

**Comment by AnmolBansalDEV** [comment]
@vikiival what are the next steps for claiming the bounty? Thanks!

**Comment by vikiival** [comment]
pay 10 usd

**Comment by AnmolBansalDEV** [comment]
Thank you @vikiival ! This is my first bounty. I hope to contribute more to the project 😄

**Comment by vikiival** [comment]
pay 10 usd

**Comment by vikiival** [comment]
😍 Perfect, I’ve sent the payout
💵 $10 @ 6.19 USD/DOT ~ 1.616 $DOT
🧗 [12b5bwwugf3CgWy58MPYQAX9wazLX1S71ghgZ4YPb6g4qbEP](https://polkadot.subscan.io/account/12b5bwwugf3CgWy58MPYQAX9wazLX1S71ghgZ4YPb6g4qbEP)
🔗 [0x99d28db3f8e396dd4252f1f7eeed2be096c3a65318f688a058514542dec2c06b](https://polkadot.subscan.io/extrinsic/0x99d28db3f8e396dd4252f1f7eeed2be096c3a65318f688a058514542dec2c06b)
🪅 Let’s grab another issue and get rewarded!
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
