### PR TITLE
Should fix missing unit in simple mint

### PR DESCRIPTION
**Pull request by vutran6853**
Should fix missing unit in simple mint Issue #356

### CODE REVIEW

**Comment by yangwao** [comment]
Perfect, can you @vutran6853  post your KSM address? :)

**Review by yangwao — CHANGES_REQUESTED** [review]
Oh, you probably meant KSM? 

I mean not sure if this is good way to do it as this is will be used for other than KSM networks

**Comment by vutran6853** [comment]
Sorry for misspell. Made update.

So there another place this will be reuse at?

**Comment by vikiival** [comment]
It's not a good fix. 

@vutran6853 we are trying to be chain agnostic as we would like to reuse this code for metaprime later on .

**Review by vikiival — CHANGES_REQUESTED** [review]
You can still fetch the unit from Vuex

**Comment by vutran6853** [comment]
I don't see anything in vuex for this unit is being use at. Should we have 2 array/lists? One for unit for simple mint and other for metaprime?

**Comment by vikiival** [comment]
Closing as it can be obsolete

**Pull request closed without merging**
