### PR TITLE
Add middleware to redirect transformed link

### LINKED ISSUE #1364: Link Transform go to link
Actually when I transform the link, maybe I want to go to that link...

image

### PR DESCRIPTION
**Pull request by MubarakSULAYMAN**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇  _ Do a quick check before the merge. 

### PR type
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted screenshot of demonstrated change in this PR

### Optional
- [x] I've tested it at `/transform?url=https%3A%2F%2Fsingular.rmrk.app%2Fcollectibles%2F10321410-0E76E3AC15B4C1FA1E-KODADOT-KODADOT_PATRONAGE_PART_1_1-0000000000000001`
- [x] I've tested PR on mobile and everything works
- [ ] I found edge cases

### What's new?
- [x] PR closes #1364
- [x] I added a created hook to watch if the transform page route on page creation has a query address and redirects to the detail page instead.

### Had issue bounty label ?
- [ ] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=<My_Kusama_Address>)

### Community participation
- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [ ] My fix has changed **something** on UI, a screenshot for others, is best to understand changes.

### CODE REVIEW

**Review by vikiival — CHANGES_REQUESTED** [review]
- check how the url is transformed in the component
 - optional: [Middleware](https://nuxtjs.org/examples/middlewares/anonymous) can be your friend here

**Comment by MubarakSULAYMAN** [comment]
@vikiival is everything in order?

**Comment by yangwao** [comment]
posting for later https://kodadot.xyz/transfer/?target=115MLM3vGnaRLQ5LShjqcTrHM8z4PbhVMEBgXTVjsxixdd6

**Comment by yangwao** [comment]
let's close this one @vikiival 😇

**Review by vikiival — CHANGES_REQUESTED** [review]
That's not correct.
You are only handling 1 of 3 cases.

please use `transform` defined in `utils/urlTransformer.ts`

**Comment by MubarakSULAYMAN** [comment]
@vikiival, kindly review.

**Review by vikiival — APPROVED** [review]
Looks good

**Comment by yangwao** [comment]
Perfect, I’ve sent the payout https://kusama.subscan.io/extrinsic/0x090b138463050c4141ae314c92f0aff9fd8474e122b7cde55a667ec67ab2ea9f

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/

**Pull request merged**
