### PR TITLE
🔧 show collection royalty

### PR DESCRIPTION
**Pull request by roiLeo**
`/ahp/collection/49`

Screenshot 2023-12-08 at 15-08-33 Wall Street Art

### CODE REVIEW

**Comment by vikiival** [comment]
and royalty recipient? 🥺 ?

**Comment by roiLeo** [comment]
> and royalty recipient? 🥺 ?

hmmmmm need to be better on indexer side

Capture d’écran 2023-12-11 à 11 57 07 AM

**Comment by vikiival** [comment]
> hmmmmm need to be better on indexer side

Will be indexed soon

Screenshot 2023-12-11 at 13 14 44

**Comment by roiLeo** [comment]
> Will be indexed soon 

Nice! I'll check v8/v9 when synced

**Comment by roiLeo** [comment]
Screenshot 2023-12-11 at 14-08-37 Wall Street Art

**Pull request merged**
