### PR TITLE
Move assets to the public for faster loads #664

### LINKED ISSUE #664: Move assets to the public for faster loads
We need a smaller bundle for the client.
Move all stuff from assets which are really needed to have smaller bundle loaded on the client from https://github.com/kodadot/nft-gallery/tree/main/src/assets to public https://github.com/kodadot/nft-gallery/tree/main/public

Don't forget if all stuff works and name down files which you've been moving and check screenshot if everything loads correctly

### PR DESCRIPTION
**Pull request by ksbek**
### Before submitting this PR, please make sure:
- [x] Code builds clean without any errors or warnings
- [x] I've merged the recent default branch -- **main** and I've no conflicts
- [x] I didn't break any original functionality

### PR type
- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new? (maybe part of changelog)
- closes #664 - Move assets to the public for faster loads

### CODE REVIEW

**Comment by yangwao** [comment]
Hey, I've tried in the network tab, throttling use 'Slow 3G' and this is happening at your PR https://deploy-preview-676--nftkodadot.netlify.app/rmrk/gallery

image

Do you mind what it could be?

**Comment by yangwao** [comment]
When I click on text do this 
image

**Comment by yangwao** [comment]
on https://nft.kodadot.xyz on Slow 3G looks like this 

image

**Comment by ksbek** [comment]
Hmm, I think it's just a browser cache issue. I guess you loaded https://nft.kodadot.xyz on your browser already before. I just saw a similar issue on both at first loads. Now I'm not seeing them.
I mean it's just not related to the images.

**Comment by yangwao** [comment]
okay now in incognito is fine, weird. 
let's see, pushing it into production.
image

**Pull request merged**
