### PR TITLE
chore: add minimum minting fee to faq

### LINKED ISSUE #1287: Expand what are minting costs on KodaDot
We are missing right now what's are costs of minting 1 nft on kodadot 

let's find transactions and expand it to the faq 

hint check on transactions costs on subscan for example

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇  _ Do a quick check before the merge. 

### PR type
- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

kodadot-pr-faq

### Optional
- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything works
- [ ] I found edge cases

### What's new?
- [x] PR closes #1287
- [x] added minimum minting fee for 1 NFT based on recent minting activities (checked via subscan)
https://kusama.subscan.io/extrinsic/0x5ed57a0226431c48c28904bfcd1e813a047d3e06755e5c5d14f332e9a3c1bf69
https://kusama.subscan.io/extrinsic/0xe1dd6a684f3c1a9e5f8238327efa30f45f6a886a1cd90b4a6effacd252acc807
https://kusama.subscan.io/extrinsic/0xd5b25af23ec4c0a219c62ea0dbe9900d56a1cf514b2e55f7a1432d062ce05c30

### Had issue bounty label ?
- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation
- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [ ] My fix has changed **something** on UI, a screenshot for others, is best to understand changes.

### CODE REVIEW

**Comment by yangwao** [comment]
@kkukelka can you merge recent `main-nuxt` as we've found out recent builds we're failing and now should be okayish! 
So I can check on your contribution

**Comment by kkukelka** [comment]
> @kkukelka can you merge recent `main-nuxt` as we've found out recent builds we're failing and now should be okayish! So I can check on your contribution

done 👍

**Review by roiLeo — COMMENTED** [review]
wouldn't it be better to have current nft minting fee in common file (@.common:data.KSM.fee) or something like that?

**Comment by yangwao** [comment]
> wouldn't it be better to have current nft minting fee in common file (@.common:data.KSM.fee) or something like that?

Oh, I've misread.

Yes, @kkukelka if you can add it to one place, so it's not copied over, that would be more than perfect and I can even close #1419

**Comment by kkukelka** [comment]
> > wouldn't it be better to have current nft minting fee in common file (@.common:data.KSM.fee) or something like that?
> 
> Oh, I've misread. That's great suggestion!
> 
> Yes, @kkukelka if you can add it to one place, so it's not copied over, that would be more than perfect and I can even close #1419

Sure thing!

**Review by roiLeo — APPROVED** [review]
lgtm 👍

**Comment by yangwao** [comment]
Perfect, I’ve sent the payout https://kusama.subscan.io/extrinsic/0x1e5bf56e85c51afa49a2a895fd9d119337daa198ead7e6288e20d0d167f77a9a

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/

**Pull request merged**
