### PR TITLE
feat: Partykit mass minting status

### LINKED ISSUE #9723: Partykit mass minting status
image

in https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=394-6126&mode=design&t=PSb4J29xNN7N426D-11

it will show random nft the user minted ( can be the first one) and then show the total-1 amount

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [x] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] https://github.com/kodadot/workers/pull/263
- [x] Fix: free drop email confirm modal not working at all (https://github.com/kodadot/nft-gallery/pull/9882/commits/a5766d119866dffbc46011b2ffe121871d8bccf0)
- [x] Fix: massmint `generating` event not triggered 
- [x] Closes #9723

## Needs QA check

- @kodadot/qa-guild please review

## Needs Design check

- @exezbcz please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2024-03-26 at 17 34 18

CleanShot 2024-03-26 at 15 48 36@2x

https://github.com/kodadot/nft-gallery/assets/44554284/57d146fa-9bee-48cd-b00d-766b3b44265b

### CODE REVIEW

**Comment by hassnian** [comment]
massmint

CleanShot 2024-03-27 at 10 58 04


free 

CleanShot 2024-03-27 at 13 23 27@2x

**Comment by exezbcz** [comment]
can you have a look please @prury 👀 

visually its okay

**Comment by hassnian** [comment]
> can you have a look please after its ready @prury 👀
> 
> visually its okay

ready to test

**Comment by yangwao** [comment]
deployed
- https://github.com/kodadot/workers/pull/263#issuecomment-2022632966

**Comment by yangwao** [comment]
what we broke 

image

**Comment by prury** [comment]
> what we broke
> 
past drops, will fail on every PR

- https://github.com/kodadot/nft-gallery/issues/9891

**Comment by yangwao** [comment]
Thanks!
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 9.39 USD/DOT ~ 5.325 $DOT
🧗 [16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD](https://polkadot.subscan.io/account/16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)
🔗 [0x6b44ec4ce15e5005d0eebf10dbc8107042a92bd3778003ac54a26c1d93a6730c](https://polkadot.subscan.io/extrinsic/0x6b44ec4ce15e5005d0eebf10dbc8107042a92bd3778003ac54a26c1d93a6730c)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
