### PR TITLE
#2344 Rework navbar

### LINKED ISSUE #2344: Rework navbar a bit
I was thinking it would be time to rehaul the navbar and to be more useful.

### Actionables
Squeeze 
- Collections, Gallery under "Explore" dropdown
- Spotlight, Series under Stats dropdown

Together Explore, Stats and Create put on the right close to the language 

Next to the logo put a search bar. 
Search bar results would drive the user to the gallery feed as usual

Refactor search a bit if needed as now it's only used in Gallery items.

The goal is to users can instantly go search when they open kodadot.xyz and don't need to think looking for that, like clicking extra on gallery step (new users barely know about it)

Inpiration at opensea.io
image

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #2344
- [ ] 

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screenshot 2022-02-14 at 1 22 51 PM

### CODE REVIEW

**Review by roiLeo — CHANGES_REQUESTED** [review]
IMO, I would keep language switcher next to login button like this:
Screenshot 2022-02-14 at 11-56-02 KodaDot - Kusama NFT Market Explorer

When on another chain some of the menu should be hidden (Stats?) 
Screenshot 2022-02-14 at 11-59-49 KodaDot - Kusama NFT Market Explorer

**Comment by prachi00** [comment]
@roiLeo doneee

**Comment by yangwao** [comment]
Doesn't take me anywhere :| 

https://user-images.githubusercontent.com/5887929/153859039-058ef7cc-8117-4fb0-a390-1173b6dc49ac.mov

**Comment by prachi00** [comment]
> Doesn't take me anywhere :|
> 
>  Screen.Recording.2022-02-14.at.12.49.00.mov

found the issue, fixing it

**Comment by prachi00** [comment]
@yangwao check now

**Comment by yangwao** [comment]
love you! 😘 

pay 200 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $200 @ 161.6 USD/KSM ~ 1.238 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x0f683cefd64ee30ab53b073df12d9707b4c7ba07fb225984257d00d9c993d093](https://kusama.subscan.io/extrinsic/0x0f683cefd64ee30ab53b073df12d9707b4c7ba07fb225984257d00d9c993d093)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
