### PR TITLE
feat: migrate button on collection page

### LINKED ISSUE #8650: Collection migration ready notif
image

- same specs as the pill shape notif we have on the landing page 
- will disappear when there is no space for it. (its not prio on mobiles)
- it displayed only to the owner of the collection 
- updated in migration UI figma: https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=4218-2062&mode=design&t=yQtWqWoOaWBXdaBF-11

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Needs Design check

- @exezbcz please review

## Context

- [x] Closes #8650

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)

## Screenshot 📸

- [x] My fix has changed UI

Screenshot 2024-01-12 at 2 47 17 PM

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]

**Review by Jarsen136 — APPROVED** [review]

**Comment by prury** [comment]
- button is not centered, it moves depending on char number on collection title: 



- button is being shown even for burned/zero items collections: (can open followup for this one, please lmk)

image

- mobile needs a small adjustment on smaller sizes(360p width)

**Comment by exezbcz** [comment]
could you please reuse this component we have on landing page? 

image


 better to have it consistent 
image



- could you make the green circle look the same as on landing page (pink circle) but in green

**Comment by preschian** [comment]
> * button is not centered, it moves depending on char number on collection title:
> * button is being shown even for burned/zero items collections: (can open followup for this one, please lmk)

> could you please reuse this component we have on landing page?

updated

> * mobile needs a small adjustment on smaller sizes(360p width)

I hide it on mobile

**Review by exezbcz — APPROVED** [review]

**Comment by yangwao** [comment]
best migration UX in world, no irony.

Thanks!
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 7.59 USD/DOT ~ 6.588 $DOT
🧗 [1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p](https://polkadot.subscan.io/account/1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)
🔗 [0x1d24aab3c1cffdccaba948df2dcdc1cfbadaa45c628d7626daf9b15a96a497c9](https://polkadot.subscan.io/extrinsic/0x1d24aab3c1cffdccaba948df2dcdc1cfbadaa45c628d7626daf9b15a96a497c9)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
