### PR TITLE
feat: Transak

### LINKED ISSUE #6722: On ramp not working
### What happened?

how dare they! 

image

found by @hassnian 

### Please reproduce in steps

login -> Sidebar -> Add funds

### Expected Behavior

should allow user to buy crypto and FIAT

### What browsers are you seeing the problem on?

Desktop Firefox

### At which address did you encounter bug?

canary.kodadot.xyz, beta.kodadot.xyz

### LINKED ISSUE #6864: Ramping service not working?
I tried to add funds to my wallet, but ramping service decided that it was not working. On production. Does this mean we don't have ramping service at all? What happened to Banx?

Screenshot 2023-08-21 at 20 38 43

### LINKED ISSUE #7119: Transak
Will get key
- https://docs.transak.com
- https://docs.transak.com/docs/integration-options
- https://global.transak.com/
dot and KSM check ✅ 
image
image
gpay too 
image
ah got smol kyc
image
so not so smol kyc
image
> few
image

### PR DESCRIPTION
**Pull request by hassnian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

Requires `?transak=true` to test 

- [x] Closes #7119
- [x] Removes code related to Instant Ramp , since Transak is the default one and instant ramp is not working atm , once we have that we can merge #6727
- [X] Closes #6864 
- [X] Closes #6722 

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2023-09-05 at 15 43 48@2x

CleanShot 2023-09-05 at 17 33 36@2x

### <samp>🤖 Generated by Copilot at 2c0f25c</samp>

This pull request integrates the Transak service into the NFT gallery app, allowing users to buy and sell crypto assets with fiat currencies. It adds the `@transak/transak-sdk` module as a dependency, and exposes the Transak API key and environment variables as runtime config options. It also adds a new `useTransak.ts` composable that handles the initialization and usage of the Transak SDK, and modifies the `WalletAssetPortfolio.vue` component to invoke the Transak modal. Additionally, it introduces a new feature flag `transak` to control the availability of the Transak service, and adds some custom styles for the Transak modal.

### <samp>🤖 Generated by Copilot at 2c0f25c</samp>

> _To buy and sell crypto with fiat_
> _We integrate Transak in our app_
> _We add `TRANSAK_API_KEY`_
> _And `useTransak` composable_
> _And tweak some styles for the modal wrap_

### CODE REVIEW

**Comment by hassnian** [comment]
🚧 WIP 🚧 is not draft bcz otherwise we don't gave a preview build

**Comment by yangwao** [comment]
this long part is weird, iframe auto height doesn't work well?

image

**Comment by yangwao** [comment]
Well, apart I haven't submitted any KYC, and I've passed KYC, which is strange; seems it worked for gpay
yet I think we need to tell the user that money should arrive shortly as their iframe just disappears, leaving user in confusion :D 

cc @exezbcz 

another thing is that it's opt for pop-up which is bit meh :/ 

image

payment is arriving in 3 minutes, which is not that bad 

image

**Comment by yangwao** [comment]
> not draft bcz otherwise we don't get a preview build

@hassnian it works to put it in ready for review and than back to draft, Netlify Hooks keep watching it and rebuilding what I've noticed. 
Can put it in draft till so

**Comment by hassnian** [comment]
@yangwao fixing that height issue 

they do provide a param to specify the height but it seems is not well implemented

without any params :d 
CleanShot 2023-09-05 at 16 36 11@2x

**Comment by hassnian** [comment]
@yangwao  added a `TRANSAK_ENV` key pls set it to `STAGING` on preview builds if you dont' want the production experience ie doesn't require visual check

**Comment by yangwao** [comment]
> should we get rid off `?transak=true` and make it the default since the other one doesn't work ?

I guess so and we can put into production for now

**Comment by hassnian** [comment]
@prury feel free to try now , 

no need of key param 

as mentioned 
CleanShot 2023-09-05 at 21 09 38@2x

transak will be the default option

**Comment by yangwao** [comment]
Loads, however it could be a bit shorter. 

image

**Comment by yangwao** [comment]
added related issues and closing in favour broken on-ramps to make release

pay 50

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 4.26 USD/DOT ~ 11.737 $DOT
🧗 [13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh](https://polkadot.subscan.io/account/13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)
🔗 [0x47a17761e0f423e84cdcd5f27fb4d38bf2fc0b290d2e4577fae4bbd72460305e](https://polkadot.subscan.io/extrinsic/0x47a17761e0f423e84cdcd5f27fb4d38bf2fc0b290d2e4577fae4bbd72460305e)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
