### PR TITLE
fix: Description more important than Properties

### LINKED ISSUE #4734: Gallery item redesign: Description more important than Properties.
### Is your feature request related to a problem?

Gallery item redesign: @exezbcz
When you open any NFT you can see this:
image
It will automatically open the properties of the NFT. There is not much info you can learn about the art piece from Properties.

### Describe the solution you would like

I would suggest after opening an NFT; you will see Description by default. Not properties. For a buyer, I think the Description is more interesting (especially when not many artists use more than one property).

So when you open an NFT, you will first see the Description (then you can click on the Properties if you want).

### Describe alternatives you have considered

Maybe also switch Properties with Description? Like this:
image

Not necessary.

### Screenshots

_No response_

### Are there opened related issues?

_No response_

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4734
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by vikiival** [comment]
Screenshot 2023-01-17 at 14 35 11

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 35.17 USD/KSM ~ 0.569 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xc01b730b80b9218f5890c49ad52487982f2c9b7f1164de9289886486840b802b](https://kusama.subscan.io/extrinsic/0xc01b730b80b9218f5890c49ad52487982f2c9b7f1164de9289886486840b802b)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
pay 20

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 35.11 USD/KSM ~ 0.57 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xeeb41b90452f5cfdcbe55f5d1cbf35278be723a7a96ad9d659af82aae339ebe2](https://kusama.subscan.io/extrinsic/0xeeb41b90452f5cfdcbe55f5d1cbf35278be723a7a96ad9d659af82aae339ebe2)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
