### PR TITLE
fix: Mobile top collections missing USD

### LINKED ISSUE #9070: Mobile top collections missing USD
https://github.com/kodadot/nft-gallery/assets/5887929/1d5aca4d-eb06-47f6-a619-1bd70956e7f1

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix

  ## Needs Design check

  - @exezbcz please review

  ## Context

  - [x] Closes #9070
  - [ ] Requires deployment <snek/rubick/worker>

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

image
image

Better than nothing, wdyt?

  ## Copilot Summary
  copilot:summary

  copilot:poem

### CODE REVIEW

**Comment by yangwao** [comment]
seen it first time, did re-run jobs 🤞 let's see

image

**Comment by Jarsen136** [comment]
> seen it first time, did re-run jobs 🤞 let's see
> 
> image

It works now.
image

**Review by roiLeo — APPROVED** [review]

**Comment by yangwao** [comment]
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 6.9 USD/DOT ~ 2.899 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x6ee9b4bc3602f72b2b3cc63da4f005f9c788d5bfa6cbde2e3791f6397280484a](https://polkadot.subscan.io/extrinsic/0x6ee9b4bc3602f72b2b3cc63da4f005f9c788d5bfa6cbde2e3791f6397280484a)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
