### PR TITLE
add: add top collection to sidebar on polkadothub

### LINKED ISSUE #7441: add top collection to sidebar on polkadothub
image

let's add these 3 for now. Better than empty

https://canary.kodadot.xyz/ahp/collection/13
https://canary.kodadot.xyz/ahp/collection/11
https://canary.kodadot.xyz/ahp/collection/10

### PR DESCRIPTION
**Pull request by hassnian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #7441

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2023-10-02 at 14 03 58@2x

### <samp>🤖 Generated by Copilot at 1ceb784</samp>

Added new Kodachain collections to the popular filter. This change supports the feature of displaying Kodachain NFTs on the gallery page.

### <samp>🤖 Generated by Copilot at 1ceb784</samp>

> _`POPULAR_COLLECTIONS`_
> _Kodachain NFTs join them_
> _Autumn of art blooms_

### CODE REVIEW

**Comment by daiagi** [comment]
Collection names are cut
image


compare this with RMRK2 where there is an ellipsis

**Comment by hassnian** [comment]
> Collection names are cut image
> 
> compare this with RMRK2 where there is an ellipsis

checking

**Review by roiLeo — APPROVED** [review]

**Comment by hassnian** [comment]
CleanShot 2023-10-02 at 14 03 58@2x

**Review by daiagi — APPROVED** [review]

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 4.25 USD/DOT ~ 7.059 $DOT
🧗 [13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh](https://polkadot.subscan.io/account/13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)
🔗 [0x3b12ca31d443d82526211ca61e728520c44875de2040b3c8597cb8c8af17343b](https://polkadot.subscan.io/extrinsic/0x3b12ca31d443d82526211ca61e728520c44875de2040b3c8597cb8c8af17343b)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
