### PR TITLE
Drops-max-card-width

### LINKED ISSUE #8111: Max width on drop cards
image
- A 910px width for one card is imo good enough, once this size is reached, the card does not scale further more. 
- If there will be more drops, the cards will behave like collection cards 

- it looks like the min width size is this: 
image

- this will hopefully fix the wide screen stretched cards

### LINKED ISSUE #8112: Drop page heading truncation
image
- it does not truncate and then it makes the height not equal to the other cards 
- 
image

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs Design check

- @exezbcz please review

## Context

- [x] Closes #8111
- [x] Closes #8112
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

yes , $

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)
## Screenshot 📸

- [x] My fix has changed UI

image

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 2b39045</samp>

Improved the drop card component by adding text truncation and responsive grid layout. Modified `DropCard.vue` and `Drops.vue` files.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 2b39045</samp>

> _`is-ellipsis` class_
> _truncates collection names_
> _cleaner drop cards_

### CODE REVIEW

**Comment by exezbcz** [comment]
nice! could you please align the cards to the left

image


otherwise oki, thanks

**Comment by daiagi** [comment]
>nice! could you please align the cards to the left
@exezbcz  Done :)

**Review by exezbcz — APPROVED** [review]

**Review by preschian — APPROVED** [review]

**Comment by exezbcz** [comment]
@prury lol where did the stroke go

**Comment by daiagi** [comment]
>mobile got changed a bit on smaller screens: ❌
thx @prury 
fixed

**Comment by yangwao** [comment]
thanks!
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 5.13 USD/DOT ~ 3.899 $DOT
🧗 [1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8](https://polkadot.subscan.io/account/1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)
🔗 [0x194607760817026d46240f6a97f12010535712117a9fc55a82a3768209f74b6c](https://polkadot.subscan.io/extrinsic/0x194607760817026d46240f6a97f12010535712117a9fc55a82a3768209f74b6c)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
