### PR TITLE
fix: re-add dot in sidebar

### LINKED ISSUE #6091: add showing DOT balances to sidebar
I think we should add also showing DOT balances to sidebar 

image

_Originally posted by @yangwao in https://github.com/kodadot/nft-gallery/issues/6088#issuecomment-1559655794_

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #6091 (sorry didnt aware we have dot now. getting overriden when I resolve conflicts in this PR https://github.com/kodadot/nft-gallery/pull/6052)

### <samp>🤖 Generated by Copilot at 878b734</samp>

This pull request adds Polkadot integration to the NFT gallery. It enables the display and fetching of Polkadot balances in the `MultipleBalances.vue` component and the `identity.ts` store.

### <samp>🤖 Generated by Copilot at 878b734</samp>

> _Sing, O Muse, of the code that was changed by the skillful developer_
> _Who added support for the Polkadot chain and its token, the `dot`_
> _And simplified the fiat value calculation with a `tokenMap` clever_
> _And a generic getter to fetch the current price of any token, a lot_

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]

**Comment by yangwao** [comment]
I would suggest put chain name with smaller caps and ticket can be UPPPERCAPS 

It's rule of thumb among traders.

image

otherwise LGTM!

**Comment by exezbcz** [comment]
@yangwao agree

good job!

**Comment by preschian** [comment]
> chain name with smaller caps and ticket can be UPPPERCAPS

sry, I didn't understand the requirements. something like this? or capitalize? or something else?
image

**Comment by exezbcz** [comment]
First letter capital?

**Review by vikiival — APPROVED** [review]
Good, first letter capital plsky

**Comment by yangwao** [comment]
image

we are so back, perfect!

**Comment by roiLeo** [comment]
weird flex but ok

**Pull request merged**
