### PR TITLE
Better Unlockable Waifu

### PR DESCRIPTION
**Pull request by vikiival**
# TL;DR changes

- notification
- auto redirect to waifu after 60 sec
- link to waifu if already minted

Commits:

- :alien: get first nft owned by account
- :label: typed response
- :globe_with_meridians: unlockable translations
- :wrench: props
- :zap: smooth UI Criminal

**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [ ] Closes #<issue_number>
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [ ] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at 23aab24</samp>

This pull request adds a feature to mint a new NFT from an unlockable collection and show the user a message and a link to their new NFT. It also updates the data fetching and subscription logic to use the Subsquid API. It modifies the `MessageNotify` component, the `locales/en.json` file, the `doWaifu` function, and adds a new GraphQL query file.

### <samp>🤖 Generated by Copilot at 23aab24</samp>

> _To mint a new NFT from `UnlockableContainer`_
> _You need to wait for the timer or enter_
> _But if you already own one from the collection_
> _You'll get a message with a link and direction_
> _To see your unique NFT and its `sn` and `collection`_

### CODE REVIEW

**Review by Jarsen136 — APPROVED** [review]
code lgtm

**Comment by prury** [comment]
is there a way to do some manual testing on this one? i went to /unlockable in the right time, but it never ask me to sign a transactions, is it deactivated to prevent minting rn?

**Comment by vikiival** [comment]
Depends what app tells you

**Review by preschian — APPROVED** [review]

**Comment by prury** [comment]
> Depends what app tells you

uh, sorry Viki, i did not understood what you meant

**Comment by vikiival** [comment]
>  but it never ask me to sign a transaction, is it deactivated to prevent minting rn?

There are some rules that the button is disabled, but in general you don't need to sign anything

**Pull request merged**
