### PR TITLE
fix(GalleryCard): resposive nft title

### LINKED ISSUE #1230: when i visit my profile i can't see the number of the SOLD NFTs till i click on it
### What happened?

can't see the number of the sold nfts till i click on it
and i think its a must , because it helps give a good first impression of the artist ^^

### Please reproduce in steps

just visit my profile, or any profile

### Expected Behavior

to see the number of the SOLD nfts before clicking on it 

### What browsers are you seeing the problem on?

Chrome

### Are you logged in?

Yes

### At which address did you encounter bug?

nft.kodadot.xyz / kodadot.xyz

### Screenshots

Paste from your clipboard or upload screenshots

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #1310: scaling of text in profiles
### What happened?

when changing view from large display to small display , the name of the nft should also change 
 

### Please reproduce in steps

visit any profile and change the size 

### Expected Behavior

I've expected ...

### What browsers are you seeing the problem on?

Chrome

### Are you logged in?

Yes

### At which address did you encounter bug?

nft.kodadot.xyz / kodadot.xyz

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by roiLeo**
- component could need some rework

### PR type
- [x] Bugfix
- [x] Refactoring

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted screenshot of demonstrated change in this PR

### Optional
- [x] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [x] I've tested PR on mobile and everything works
- [x] I found edge cases: maybe widescreen

### What's new?
- [x] PR closes #1310

### CODE REVIEW

**Comment by vikiival** [comment]
@roiLeo maybe you picked up wrong issue number ?

**Comment by roiLeo** [comment]
> @roiLeo maybe you picked up wrong issue number ?

Oups! Fixed.

**Comment by vikiival** [comment]
> Ah I got it. So text should be smaller on smaller layout

Old: 
Screenshot 2021-11-29 at 12 20 12

Screenshot 2021-11-29 at 12 20 03


New:

Screenshot 2021-11-29 at 12 19 35

Screenshot 2021-11-29 at 12 19 52

**Comment by vikiival** [comment]
Nice fix, just personally for me the text on the `Large display` layout is small

**Pull request merged**
