### PR TITLE
fix: Extremely lucky breakpoint

### LINKED ISSUE #9354: Extremely lucky breakpoint
I'm not intentively seeking visual bugs, but when I do and open dev tools
0 days without (Lenny, Simpsons)

hint 1024px

image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix

  ## Needs Design check

  - @exezbcz please review

  ## Context

  - [x] Closes #9354

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

image

  ## Copilot Summary
  copilot:summary

  copilot:poem

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]

**Comment by prury** [comment]
i think it may have broken mobile smaller sizes: 

https://github.com/kodadot/nft-gallery/assets/36627808/e1866c99-1c9c-4034-b1a4-275d06a72191

**Comment by exezbcz** [comment]
image


this does not look good 



IMO solution would be to reduce the card amount and stretch the others

**Comment by Jarsen136** [comment]
> IMO solution would be to reduce the card amount and stretch the others

It make sense. Updated

**Review by preschian — APPROVED** [review]

**Comment by prury** [comment]
@Jarsen136 

something that wasn't happening before(last drop card gets cutted): 

image

**Comment by Jarsen136** [comment]
> @Jarsen136
> 
> something that wasn't happening before(last drop card gets cutted):
> 

It's not getting "cutted", but showing less cards on the small screen. There are some screenshots for different size screen.




image

image


image

**Comment by prury** [comment]
> > @Jarsen136
> > something that wasn't happening before(last drop card gets cutted):
> 
> It's not getting "cutted", but showing less cards on the small screen. There are some screenshots for different size screen.

lol, cutted does not exist my bad, getting cut
its only the last one tho, can you check?

**Comment by Jarsen136** [comment]
> > > @Jarsen136
> > > something that wasn't happening before(last drop card gets cutted):
> > 
> > 
> > It's not getting "cutted", but showing less cards on the small screen. There are some screenshots for different size screen.
> 
> lol, cutted does not exist my bad, getting cut its only the last one tho, can you check?

Oh you are talking about the gap between the last card and the edge of the screen. It happens on every carousel list by the way. For example, you could see the gap at the latest sales on landing. If I remember correct, we had an issue for this UI change. 

image

**Comment by prury** [comment]
> 
> Oh you are talking about the gap between the last card and the edge of the screen. It happens on every carousel list by the way. For example, you could see the gap at the latest sales on landing. If I remember correct, we had an issue for this UI change.


is this actually: check the last one(first video is canary)

https://github.com/kodadot/nft-gallery/assets/36627808/f36e6b82-7bbc-44a0-bb59-7338c4f61f9b

**Comment by Jarsen136** [comment]
> > Oh you are talking about the gap between the last card and the edge of the screen. It happens on every carousel list by the way. For example, you could see the gap at the latest sales on landing. If I remember correct, we had an issue for this UI change.
> 
> is this actually: check the last one(Alchemy)(first video is canary)
> 
>  cut.mp4

Thanks for the video, I fixed it.

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Pull request merged**
