### PR TITLE
fix: build on cf-pages

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Currently canary deployment was failed since #8154
- [x] add test case build with cf-pages preset

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)

## Screenshot 📸

- [ ] My fix has changed UI

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at f993677</samp>

Add a new job to the build workflow for Cloudflare Pages deployment. The job uses a custom action to install dependencies and runs `npm run build:cf` with a preset.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at f993677</samp>

> _`Pages` job added_
> _Builds the project on Ubuntu_
> _Winter deployment_

### CODE REVIEW

**Comment by yangwao** [comment]
What's is issue? I think it's something I've noticed that merged PR didn't working on canary right?

**Comment by preschian** [comment]
> What's is issue? I think it's something I've noticed that merged PR didn't working on canary right?

I suspect that `dependabot` not proper bump `pnpm-lock.yaml` at that time

**Review by roiLeo — APPROVED** [review]

**Comment by roiLeo** [comment]
> > What's is issue? I think it's something I've noticed that merged PR didn't working on canary right?
> 
> I suspect that `dependabot` not proper bump `pnpm-lock.yaml` at that time

Yes every time

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 5.06 USD/DOT ~ 5.929 $DOT
🧗 [1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p](https://polkadot.subscan.io/account/1xjvRADwdJcnmUCLWerEHR4iGCT5EBTm4D4fzLLg4LcAC9p)
🔗 [0x5b82430eea9007f8f418c2e30007340a02095adb498f9d219d5af45eaec88b5f](https://polkadot.subscan.io/extrinsic/0x5b82430eea9007f8f418c2e30007340a02095adb498f9d219d5af45eaec88b5f)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
