### PR TITLE
feat(2359): date range for series-insight

### LINKED ISSUE #2359: Trednding Series - Add date range for series insight
Right now we are showing collections overall lifetime stats.

Would be super nice to have a data range to show people easier to choose and see which collections are trending in time.

Might require a tune bit resolver in https://github.com/kodadot/rubick 

Desired ranges, last 
- 24 hours
- 7 days
- 14 days
- 30 days
- 90 days
- 180 days
- All-time

Default could be 7 days. Don't forget to add URL params so it could be easily shared

### PR DESCRIPTION
**Pull request by KngZhi**
- feat: timeRange init
- refactor: use obejct to pass params
- feat: add timeRange to params

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #2359
- [x] PR related https://github.com/kodadot/rubick/pull/94
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer?target=DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by KngZhi** [comment]
@yangwao this feature has a conflict with mini-pulse history #2195, the date range is fixed at 30days. Do you want to keep it or the user can change it with the date option?

> In the series, show buys for the last 30 days

My suggestion would be to keep it and since we already add the table header `last 30 days`

Besides if the user selects `All-time`, it would be very lagging, and if the user selects `14 Days` or less, the data point would be too less to provide meaningful trending.

**Comment by KngZhi** [comment]
@yangwao 

> > My suggestion would be to keep it and since we already add the table header last 30 days
> 
> the header could be changed with date range selection

It can be easily done, but the main issue is fetching time would be very long, for days > 30days or all-time.

**Comment by KngZhi** [comment]
@yangwao some updates on PR, you can see that when Rubick was deployed. This video is local dev env.

https://user-images.githubusercontent.com/11361147/168328041-7330581d-8449-4e02-bd32-41802b451654.mov

**Comment by yangwao** [comment]
seems I can't test 

```
{
    "errors": [
        {
            "message": "Cannot query field \"emoteCount\" on type \"SeriesEntity\".",
            "extensions": {
                "code": "GRAPHQL_VALIDATION_FAILED",
                "exception": {
                    "stacktrace": [
                        "GraphQLError: Cannot query field \"emoteCount\" on type \"SeriesEntity\".",
                        "    at Object.Field (/squid/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:48:31)",
                        "    at Object.enter (/squid/node_modules/graphql/language/visitor.js:323:29)",
                        "    at Object.enter (/squid/node_modules/graphql/utilities/TypeInfo.js:370:25)",
                        "    at visit (/squid/node_modules/graphql/language/visitor.js:243:26)",
                        "    at validate (/squid/node_modules/graphql/validation/validate.js:69:24)",
                        "    at validate (/squid/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)",
                        "    at processGraphQLRequest (/squid/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)",
                        "    at runMicrotasks (<anonymous>)",
                        "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
                        "    at async processHTTPRequest (/squid/node_modules/apollo-server-core/dist/runHttpQuery.js:220:30)"
                    ]
                }
            }
        }
    ]
}
```

image

**Comment by KngZhi** [comment]
The rubick haven't deployed~ the feat based on new resolver.

**Comment by vikiival** [comment]
kodadot/rubick#d9dea66476f28225fb1ccfa5ed8f38cdec5386e0

**Comment by kkukelka** [comment]
series-insight broken?
https://deploy-preview-2982--koda-nuxt.netlify.app/series-insight/
Screenshot 2022-06-04 at 06 47 01

**Comment by KngZhi** [comment]
> series-insight broken? https://deploy-preview-2982--koda-nuxt.netlify.app/series-insight/ Screenshot 2022-06-04 at 06 47 01

Yes, added a new field, has to wait for the new deployment.

**Comment by petersopko** [comment]
@KngZhi hey, are we still waiting for the rubick deployment here? seems this one was opened up too early ~7 weeks ago

**Pull request closed without merging**
