### PR TITLE
1478: Add preloader

### LINKED ISSUE #1478: Change preloader on beta
let's change the preloader on the beta on something more creative and kodadotish 

image

### PR DESCRIPTION
**Pull request by rhaicode**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇  _ Do a quick check before the merge. 

### PR type
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything works
- [ ] I found edge cases

### What's new?
- [x] PR closes #1478
- [x] New loader screen

### Had issue bounty label ?
- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EJ4LJsZAefUW5pwokk5G5b96CpHaABiXXaEUpdBakP8oYJr)

### Community participation
- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [x] My fix has changed **something** on UI, a screenshot for others, is best to understand changes.

http://somup.com/crl2fL0HUU
Capture

### CODE REVIEW

**Comment by vikiival** [comment]
Please use linter, looks like yours made a ton of changes into `nuxt.config.js
`

**Comment by yangwao** [comment]
> Please use linter, looks like yours made a ton of changes into `nuxt.config.js `

yeah @rhaicode let's use linter and we can merge, it's def nicer than basic one! :)

**Comment by rhaicode** [comment]
sure thing!

**Comment by roiLeo** [comment]
Hey! IMO, you should change the .html to a .vue component as seen in [Nuxt doc](https://nuxtjs.org/examples/loading/custom-loading-component)

Some of the css can be removed and replaced by [Bulma class](https://bulma.io/documentation/helpers/visibility-helpers/)

**Comment by rhaicode** [comment]
Hello @vikiival , since we have `ssr:false`, it is not applicable. Therefore, this is the Nuxt doc (https://nuxtjs.org/examples/loading/customize-loading-indicator) that I have followed where in we have to use `loadingIndicator`.

More about `loadingIndicator` : https://nuxtjs.org/docs/configuration-glossary/configuration-loading-indicator/ and head over to 'Custom indicators'. It will refer you to Nuxt's built-in source code that are using .html instead

**Comment by yangwao** [comment]
hey let's add this one "folding square" from spinkit https://tobiasahlin.com/spinkit/
and we are good to go! :)

https://user-images.githubusercontent.com/5887929/146398460-8cfa88f4-06ff-441b-9573-6e615f79ffb3.mov

**Comment by rhaicode** [comment]
sure, on it!

**Comment by rhaicode** [comment]
Hi @yangwao , what do you think now of the new preloader?

**Comment by yangwao** [comment]
Perfect, I’ve sent the payout https://kusama.subscan.io/extrinsic/0xdf0621c718394966b2bf3df5dcf74b988c62e9aa01e13a1ea3014e1ad9b92889

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/

**Pull request merged**
