### PR TITLE
fix collection names

### LINKED ISSUE #3215: Collection names seems doesn't load when I open them
At create dialog I see them 

image

on Collection view likewise 

https://user-images.githubusercontent.com/5887929/174566743-3c1c3737-7e5f-4de7-a3d8-95855c1d343b.mov

but when I click on a particular Collection, don't and no error in console

https://deploy-preview-3210--koda-nuxt.netlify.app/bsx/collection/2113767959

image

### PR DESCRIPTION
**Pull request by zhengow**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3215 
- [ ] Requires deployment <rubick/magick_issue>
- [x] <brief_description_of_what_I've_added> assign `name` property to `this.collection`

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested it at </bsx/collection/2113767959?page=1>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=EgCzZLpVe7zg7RHh79qPyC8UrykVkA22YY2oj7sWMZf15Ws)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

### CODE REVIEW

**Comment by Jarsen136** [comment]
pay 50 usd

**Comment by Jarsen136** [comment]
> pay 50 usd

Let's check this. cc @yangwao

**Comment by zhengow** [comment]
@yangwao Hi there👀

**Comment by yangwao** [comment]
@Jarsen136 try now? I've added you to admin list for payout bot :)

**Comment by Jarsen136** [comment]
pay 50 usd

**Comment by Jarsen136** [comment]
> @Jarsen136 try now? I've added you to admin list for payout bot :)

It works 🚀

**Pull request merged**
