### PR TITLE
chore: fix warning on money and dropdown

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] chore: fix warning on money and dropdown

#### Did your issue had any of the "$" label on it?

- [ ] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=<My_Polkadot_Address_check_https://github.com/kodadot/nft-gallery/blob/main/REWARDS.md#creating-your-dot-address>)

### <samp>🤖 Generated by Copilot at 9d220f1</samp>

Removed unnecessary attributes from `CommonTokenMoney.vue`, refactored props definition in `Money.vue`, and added `position` prop to `NeoDropdown.vue`. These changes improve the code quality, fix TypeScript errors, and enhance the UI flexibility of the components.

### <samp>🤖 Generated by Copilot at 9d220f1</samp>

> _`data-testid` gone_
> _`props` and `position` changed_
> _Autumn of refactor_

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
hello, I've made a small change on `CommonTokenMoney` in Nuxt branch

```vue
<template>
  <TokenMoney
    v-if="tokenId"
    :value="value"
    :data-testid="dataCy"
    :round="round"
    inline />
  <Money v-else :value="value" :data-testid="dataCy" inline :round="round" />
</template>

<script lang="ts" setup>
import Money from '@/components/shared/format/Money.vue'
import TokenMoney from '@/components/bsx/format/TokenMoney.vue'

defineProps({
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-expect-error
  value: {
    type: [Number, String, BigInt],
    default: '0',
  },
  dataCy: {
    type: String,
    required: false,
    default: '',
  },
  round: {
    type: Number,
    default: 4,
  },
})

const { tokenId } = usePrefix()
</script>
```

**Comment by preschian** [comment]
> hello, I've made a small change on `CommonTokenMoney` in Nuxt branch

oh thank you, will copy that

**Comment by preschian** [comment]
@roiLeo no `:token-id="tokenId"` as a prop to `TokenMoney`, is that expected?

**Comment by roiLeo** [comment]
btw it would be cool if you can take a look why I have a ton of warning related with font awesome

Capture d’écran 2023-09-27 à 3 18 09 PM

**Comment by roiLeo** [comment]
> > btw it would be cool if you can take a look why I have a ton of warning related with font awesome
> 
> which page is this? seems like should be fixed on the fa side, since we do not control their version https://bugzilla.mozilla.org/show_bug.cgi?id=1851623

nuxt branch, all pages

**Comment by preschian** [comment]
> nuxt branch, all pages

firefox only? I didn't get the warning message

**Comment by roiLeo** [comment]
> firefox only? I didn't get the warning message

oops, looks like it's firefox only

**Comment by prury** [comment]
@preschian why change the data-testid to dataCy? 
i don't understand what this code does tho, just asking

**Comment by roiLeo** [comment]
> @preschian why change the data-testid to dataCy? i don't understand what this code does tho, just asking

its passed as props, you made a breaking change in your cypress PR because "money" is not defined in this component as prop

**Comment by prury** [comment]
> > @preschian why change the data-testid to dataCy? i don't understand what this code does tho, just asking
> 
> its passed as props, you made a breaking change in your cypress PR because "money" is not defined in this component as prop

oh, sorry for that 😅

**Comment by vikiival** [comment]
Can we target this to `nuxt` branch?

**Comment by roiLeo** [comment]
> Can we target this to `nuxt` branch?

I think I already made this change on nuxt branch

**Comment by vikiival** [comment]
So @preschian resolve conflicts and we can merge

**Comment by roiLeo** [comment]
let's close it for now, or change branch to `nuxt`

**Pull request closed without merging**
