### PR TITLE
Fix/issue 6886

### LINKED ISSUE #6886: Basilisk showing BSX as currency instead of KSM
### What happened?

check: 
https://github.com/kodadot/nft-gallery/assets/36627808/abee5d47-3b7f-4845-8320-622661e9d9cf

### Please reproduce in steps

a

### Expected Behavior

a

### What browsers are you seeing the problem on?

_No response_

### At which address did you encounter bug?

_No response_

### Are you logged in?

None

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

_No response_

### Screenshots

a

### Relevant log output

_No response_

### Payment link for reward

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by xiiiAtCn**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #6886 

#### Did your issue had any of the "$" label on it?

my DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=12jXHf7yYF4wTRjDPbwFB24V1nVRPRkuU2S8Ke5ZWTfvyBGW&usdamount=8.82&donation=true)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### <samp>🤖 Generated by Copilot at fdc2a5f</samp>

Added support for Basilisk chain and its currency symbol in `useChain.ts`. This enables the app to display NFTs from the new parachain on the Kusama network.

### <samp>🤖 Generated by Copilot at fdc2a5f</samp>

> _`chainSymbol` grows_
> _Basilisk joins the gallery_
> _Winter of NFTs_

### CODE REVIEW

**Review by roiLeo — CHANGES_REQUESTED** [review]
Hello, issue is still present

Capture d’écran 2023-08-24 à 9 03 26 AM
Capture d’écran 2023-08-24 à 9 03 12 AM
Capture d’écran 2023-08-24 à 9 02 17 AM

**Comment by xiiiAtCn** [comment]
> Hello, issue is still present
> 
> Capture d’écran 2023-08-24 à 9 03 26 AM Capture d’écran 2023-08-24 à 9 03 12 AM Capture d’écran 2023-08-24 à 9 02 17 AM

I guess he/she wants to use BSX as symbol in bsx gallery detail page not KSM.

**Comment by prury** [comment]
> 
> I guess he/she wants to use BSX as symbol in bsx gallery detail page not KSM.

Hey, in Koda we use Basilisk KSM when inside the basilisk chain to list and sell NFTs, BSX is used only for paying fees.
To clarify, what we need is to show KSM insted of BSX on the explorer:

image

**Comment by xiiiAtCn** [comment]
> > I guess he/she wants to use BSX as symbol in bsx gallery detail page not KSM.
> 
> Hey, in Koda we use Basilisk KSM when inside the basilisk chain to list and sell NFTs, BSX is used only for paying fees. To clarify, what we need is to show KSM insted of BSX on the explorer:

okay. I will fix this asap. forgive a new guy's misunderstanding

**Comment by prury** [comment]
> > > I guess he/she wants to use BSX as symbol in bsx gallery detail page not KSM.
> > 
> > 
> > Hey, in Koda we use Basilisk KSM when inside the basilisk chain to list and sell NFTs, BSX is used only for paying fees. To clarify, what we need is to show KSM insted of BSX on the explorer:
> 
> okay. I will fix this asap. forgive a new guy's misunderstanding

no problem at all!

**Comment by yangwao** [comment]
pay 30 usd

**Pull request merged**
