### PR TITLE
1439 added nft history browsing feature to navbar

### LINKED ISSUE #1439: History browsing component of user history
Would be nice to 
- add an icon to the navbar so you can return to previously browsed NFTs
- Store it into Vuex for the last 50 NFTs?

In the popup, on the click -- fetch data from indexer? render toast to show them
- small preview of NFT
- name
- price if it's still available for sale
- X for removing it from the store
- Order it by days -- with headlines Today, yesterday, 2 days ago &c

image

https://user-images.githubusercontent.com/5887929/145190674-8dbb5800-ce38-4fc4-8b28-4376ed16743b.mov

### Answers

Someone has asked me where it's from, so I'm using this for modern Wikipedia https://chrome.google.com/webstore/detail/modern-design-for-wikiped/emdkdnnopdnajipoapepbeeiemahbjcn

by modernwiki.app Modern Design for Wikipedia

### Ref 
- #990 
- #1172

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇  _ Do a quick check before the merge. 

### PR type
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR
Screenshot 2021-12-10 at 13 48 11

### Optional
- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything works
- [ ] I found edge cases

### What's new?
- [x] PR closes #1439
- [x] added a history browser that enables you to browse through the 30 last visited nft detail pages.  correctly handles case if nft is visited multiple times, is ordered by date when nft was visited and is saved persistently via localstorage

### Had issue bounty label ?
- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation
- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [x] My fix has changed **something** on UI, a screenshot for others, is best to understand changes.

### CODE REVIEW

**Comment by yangwao** [comment]
Let's align-right border window with the right side of the history button so it will pop closer to the center.

image

I've meanwhile updated the issue to show it a more "structured" way as we do have collections, so it could help users navigate way better what they browsed.

**Comment by yangwao** [comment]
> image

Feel free to make it bigger, even double size and remove time per observation as we want to categorize it just by days for now to save brain load/bandwidth on user

**Comment by kkukelka** [comment]
> > image
> 
> Feel free to make it bigger, even double size and remove time per observation as we want to categorize it just by days for now to save brain load/bandwidth on user

@yangwao Your current idea regarding collections will be a mess from an implementation standpoint. Instead I would propose something like this:
kodadot-history-browser-v2
The ordering headlines contain ['Today', 'Yesterday', 'Past 7 Days', 'Past Month', 'Earlier' ]  <--- **OPEN FOR SUGGESTIONS**

I still don't get why we would need headlines since the history is chronological by nature, but it's not that to implement.

**Comment by yangwao** [comment]
> @yangwao Your current idea regarding collections will be a mess from an implementation standpoint. Instead I would propose something like this: kodadot-history-browser-v2 The ordering headlines contain ['Today', 'Yesterday', 'Past 7 Days', 'Past Month', 'Earlier' ] <--- **OPEN FOR SUGGESTIONS**
> 
> I still don't get why we would need headlines since the history is chronological by nature, but it's not that to implement.

Okay, we can iterate later on that. 

- Align right borders, so the history button right border is aligned with window right border
- Yup let's now make it bigger, 400px width should be good for start, it would make the NFT pictures is recognizable easier
- show delete action on hover per row only, so it doesn't pollute UI
- headlines could be half size

**Comment by kkukelka** [comment]
> > @yangwao Your current idea regarding collections will be a mess from an implementation standpoint. Instead I would propose something like this: kodadot-history-browser-v2 The ordering headlines contain ['Today', 'Yesterday', 'Past 7 Days', 'Past Month', 'Earlier' ] <--- **OPEN FOR SUGGESTIONS**
> > I still don't get why we would need headlines since the history is chronological by nature, but it's not that to implement.
> 
> Okay, we can iterate later on that.
> 
> * Align right borders, so the history button right border is aligned with window right border
> * Yup let's now make it bigger, 400px width should be good for start, it would make the NFT pictures is recognizable easier
> * show delete action on hover per row only, so it doesn't pollute UI
> * headlines could be half size

@yangwao  final state for **now**. will definitely checkout followup tasks next week and do a separate PR

❗ somebody needs to refactor the <NFT> Interface... typing doesn't reflect actual response -> will open Issue regarding that

Screenshot 2021-12-12 at 17 53 08

**Comment by yangwao** [comment]
When I don't have anything in history and click there... 
image

**Comment by yangwao** [comment]
the bottom border should be fixed? 
image

I would preserve dialog once remove button is clicked as user might want to remove more than one from browsing history, like 2-3 and don't want to open dialog each time.
https://user-images.githubusercontent.com/5887929/145807133-f646dab0-5d8b-44eb-9a31-76c2064be451.mov

**Comment by yangwao** [comment]
Perfect, I’ve sent the payout https://kusama.subscan.io/extrinsic/0x64c3ca0cd9215db1bf8be15b22b9ea7540e5b41edd0c409ad63a07c7621065cb

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/

I've created a bug issue as it's quite a lot of code and rather merge it now to avoid further conflicts in code and later you can take it from there.

**Pull request merged**
