### PR TITLE
#1413 Handle non existing collection

### LINKED ISSUE #1413: Handle non existing collection
When I open 
https://kodadot.xyz/rmrk/collection/10352274-409E451AFD98397563-AURA3D-AURA-V-0000000000000006

Keeps loading, but users really don't know if it's an issue in internet, our bug or what's happening.

We should handle somehow that user is opening non-existing collection, item, etc.

image

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇  _ Do a quick check before the merge. 

### PR type
- [x] Bugfix
- [ ] Feature
- [x] Refactoring

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything works
- [ ] I found edge cases

### What's new?
- [x] PR closes #1413
- [ ] <brief_description_of_what_I've_added>

### Had issue bounty label ?
- [x] Fill up your KSM address: 
[Payout](https://kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation
- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [x] My fix has changed **something** on UI, a screenshot for others, is best to understand changes.
Screenshot 2021-12-19 at 5 11 13 PM

### CODE REVIEW

**Review by roiLeo — CHANGES_REQUESTED** [review]
Hey!
- I would add a button allowing to come back to `/collections`
- could you open PR on main-nuxt branch?

**Comment by prachi00** [comment]
> Hey!
> 
> * I would add a button allowing to come back to `/collections`
> * could you open PR on main-nuxt branch?

@roiLeo you mean close this pr and raise another one against nuxt? or keep this one as well?

**Comment by roiLeo** [comment]
> @roiLeo you mean close this pr and raise another one against nuxt? or keep this one as well?

It would be better if all new developments were on main-nuxt branch

**Comment by prachi00** [comment]
> * /collections

@roiLeo made a new PR, should I close this one then?

**Pull request closed without merging**
