### PR TITLE
Sitemap and meta Title and descriptions

### PR DESCRIPTION
**Pull request by AndreyGrin**

### CODE REVIEW

**Comment by AndreyGrin** [comment]
I see Netlify don't want to build now. My idea is to generate sitemap every time we make a build. If it's not necessary, we can manually generate it using `yarn run sitemap` when we want to update. Sitemap have mostly static pages so it will be ok to have it like that. Let me know what do you think.

**Comment by yangwao** [comment]
> I see Netlify don't want to build now. My idea is to generate sitemap every time we make a build. If it's not necessary, we can manually generate it using `yarn run sitemap` when we want to update. Sitemap have mostly static pages so it will be ok to have it like that. Let me know what do you think.

I mean if we can save some build minutes and lay off stuff which doesn't needed everytime, I'm okay with it to be static and upon manually run :)

**Comment by yangwao** [comment]
Closes #243

**Comment by yangwao** [comment]
Interesting on https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fdeploy-preview-409--nftkodadot.netlify.app%2Frmrk%2Fdetail%2F6788636-3CD8C53D036D48B952-CS-CLOUDSCALPING-0000000000000001

image

however I see it here 
image

**Pull request merged**
