### PR TITLE
#3438 Fixing search focus issue

### LINKED ISSUE #3438: BUG: Focusing on search bar and then clicking outside anywhere redirects to gallery
### What happened?

A bug happened!
https://www.loom.com/share/8e0f8669d834436085f3c563e33756e6

### Please reproduce in steps

Go to ... Click on .... See error

### Expected Behavior

I've expected ...

### What browsers are you seeing the problem on?

_No response_

### At which address did you encounter bug?

_No response_

### Are you logged in?

_No response_

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

_No response_

### Screenshots

Paste from your clipboard or upload screenshots/video

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by prachi00**
… redirects to gallery

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3438
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by DeluneClaire — COMMENTED** [review]
wfm

**Review by roiLeo — CHANGES_REQUESTED** [review]
One more step to make it perfect: remove empty `&search=`

#### step to reproduce
- go to bsx chain
- click on explore
- click on searchBar
- click outside searchbar
- an unnecessary request is sent, query is updating with empty value in url (`&search=`)

**Review by roiLeo — APPROVED** [review]
✅ lgtm

**Comment by petersopko** [comment]
pay 50 usd

**Pull request merged**
