### PR TITLE
fix: link color override

### LINKED ISSUE #9095: Settings active in profile sidebar?
black sheep
image

it's white even when you don't hover over it

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix

  ## Needs Design check

  - @exezbcz please review

  ## Context

  - [x] Closes #9095
  - [x] Fixed the wrong style on link element

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI
image

  ## Copilot Summary
  copilot:summary

  copilot:poem

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
this clearly look like a hotfix, would you mind migrate this part to Tailwind?

**Comment by yangwao** [comment]
> would you mind migrate this part to Tailwind?

good idea, @Jarsen136 ? I mean it's not urgent or important fix so can be migrated if so :)

**Comment by Jarsen136** [comment]
> > would you mind migrate this part to Tailwind?
> 
> good idea, @Jarsen136 ? I mean it's not urgent or important fix so can be migrated if so :)

✅ It's a good idea. Updated

**Review by roiLeo — APPROVED** [review]

**Review by preschian — APPROVED** [review]

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 6.06 USD/DOT ~ 4.95 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0xf434ce0785efeee176e5d4a22896b59aa576c04e367de06c87701e94b0bbf54b](https://polkadot.subscan.io/extrinsic/0xf434ce0785efeee176e5d4a22896b59aa576c04e367de06c87701e94b0bbf54b)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
