### PR TITLE
🔧 bsx/snek balance issue

### LINKED ISSUE #4941: Balance issue on mint & buy (only snek)
Show 0 KSM in mint while wallet shows a different number

Screenshot 2023-02-08 at 08-54-11 KodaDot Low fees and low carbon minting KodaDot - NFT Market Explorer

Same things in GalleryItem

Screenshot 2023-02-08 at 10-41-44 Vortex 004-6914 KodaDot - NFT Market Explorer

### PR DESCRIPTION
**Pull request by roiLeo**
## PR Type

- [x] Bugfix

## Context

- [x] Closes #4941
- [x] fix balance `$NaN` in wallet sidebar
- [x] fix balance in basilisk create (nft/collection)
- [x] made a change that will check pallet version
BSX (mainnet) => 82
BSX (snek Rococo) => 88

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=HguGafrfk8nRP9a4tgJf7hLvSSFie8GtkDjyWFHQ2kDUAMc)

## Screenshot 📸

Screenshot 2023-02-08 at 13-17-21 KodaDot Low fees and low carbon minting KodaDot - NFT Market Explorer

### CODE REVIEW

**Comment by roiLeo** [comment]
@vikiival could you explain this change https://github.com/kodadot/nft-gallery/commit/b4a627465ce812027b95b9cb2c6668e95a8a5d83 ? Why it's not working as excepted and where can I find related doc?

**Comment by Jarsen136** [comment]
It seems does not work for me on bsx.

Here is the preview env: https://deploy-preview-4945--koda-nuxt.netlify.app/bsx/create
The balance shows zero.
image


What's more,  it works well on beta env. https://beta.kodadot.xyz/bsx/create

image

**Comment by roiLeo** [comment]
> It seems does not work for me on bsx.

thank you for your review it helped me to understand what was wrong.

New pallet (Rococo) asset is `Kusama` while it's currently (mainnet) `KSM` we will have to make the change when switching
#4941 is blocking me since I can't test some `/snek` features so I'll probably base it on the prefix

**Review by Jarsen136 — APPROVED** [review]
WFM

**Comment by vikiival** [comment]
> @vikiival could you explain this


Yeah I was having the same trouble that rococo calls it differently


Apart from that:
Let this roll

Side note:
These data can be fetched from Squid

**Comment by vikiival** [comment]
Btw wasn't the id issue fixed by checking if KSM returns null?

**Comment by roiLeo** [comment]
> Yeah I was having the same trouble that rococo calls it differently

Any way to know when bsx team make breaking changes? 

> Side note: These data can be fetched from Squid

where? `assetEntities`? 

> Btw wasn't the id issue fixed by checking if KSM returns null?

Since it didn't work on beta I don't think so.

**Comment by vikiival** [comment]
> where? assetEntities?

Yes can write resolver for that:
- https://github.com/kodadot/snek/issues/140

**Comment by vikiival** [comment]
Nah YOLO

**Review by vikiival — APPROVED** [review]

**Pull request merged**
