### PR TITLE
#10425: remove onchain identity

### LINKED ISSUE #10425: Remove onchain id
The link does not work anyway, lol

https://github.com/kodadot/nft-gallery/assets/90852205/04c3ede4-d7cc-4d58-98da-f56e5e95a4a9

If anyone asks, there are alternatives: 
- https://support.polkadot.network/support/solutions/articles/65000181981-how-to-set-and-clear-an-identity

# task
- remove it
- say bye

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #10425

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)

## Screenshot 📸

- [x] My fix has changed UI

Screenshot 2024-06-07 at 3 02 31 PM

### CODE REVIEW

**Comment by exezbcz** [comment]
whole ui should be removed

**Comment by prachi00** [comment]
> * Remove onchain id #10425

@exezbcz what do you mean whole ui?

**Comment by exezbcz** [comment]
@prachi00 you removed only the link from the sidebar 
image

**Comment by prachi00** [comment]
> @prachi00 you removed only the link from the sidebar image

@exezbcz we don not have the /identity code in our repo it seems, its already not there, that is why the link doesnt work, this part, it isnt there
Screenshot 2024-06-09 at 4 58 38 PM

**Comment by exezbcz** [comment]
> @exezbcz we don not have the /identity code in our repo it seems, its already not there, that is why the link doesnt work, this part, it isnt there

oki, please double check, otherwise works for me

**Comment by prachi00** [comment]
> > @exezbcz we don not have the /identity code in our repo it seems, its already not there, that is why the link doesnt work, this part, it isnt there
> 
> oki, please double check, otherwise works for me

I did, I cant find this component in our codebase

**Review by vikiival — APPROVED** [review]

**Review by Jarsen136 — CHANGES_REQUESTED** [review]
How about `components/common/ConnectWallet/WalletAssetSetIdentity.vue`. Could you please remove them all?
image

**Comment by prachi00** [comment]
> WalletAssetSetIdentity

what about WalletAsset (it uses WalletAssetSetIdentity) component? are we deleting this one too? its being used in connectwalletmodal, which is being used in a couple of places
Screenshot 2024-06-11 at 11 33 06 AM

**Comment by Jarsen136** [comment]
> > WalletAssetSetIdentity
> 
> what about WalletAsset (it uses WalletAssetSetIdentity) component? are we deleting this one too? its being used in connectwalletmodal, which is being used in a couple of places 

1. remove `WalletAssetSetIdentity.vue` and also remove the lines that are using it
2. remove the related translation 

> > what about WalletAsset (it uses WalletAssetSetIdentity) component? are we deleting this one too?

No, it's not related to identity

**Comment by Jarsen136** [comment]
> 2\. remove the related translation
> 


The last stuff. Otherwise lgtm

**Comment by prachi00** [comment]
> > 2. remove the related translation
> 
> The last stuff. Otherwise lgtm



> > 2. remove the related translation
> 
> The last stuff. Otherwise lgtm

@Jarsen136 it doesnt have any

**Comment by vikiival** [comment]
> @Jarsen136 it doesnt have any

image

**Comment by Jarsen136** [comment]
> > > 2. remove the related translation
> > 
> > 
> > The last stuff. Otherwise lgtm
> 
> > > 2. remove the related translation
> > 
> > 
> > The last stuff. Otherwise lgtm
> 
> @Jarsen136 it doesnt have any

Here is it.
image

**Review by Jarsen136 — APPROVED** [review]

**Pull request merged**
