### PR TITLE
feat: Drop page party kit action status

### LINKED ISSUE #9454: Drop page party kit action status
Once 
- #9439 merged

We would like to have statuses of people so it's not just floating numbers, but to see actions of other people
---
- [x] - default is dot spent, which works now well
- [ ] - clicking on generating preview - "generating"
- [ ] - when users click on minting - "minting" 
- [ ] - on the success modal, we can show a small preview of minted art next to the user cursor, the size can be 64x64

### PR DESCRIPTION
**Pull request by hassnian**
## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

❗️ Needs https://github.com/kodadot/workers/pull/255

- [x] Closes #9454

## Needs Design check

- @exezbcz please review

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

https://github.com/kodadot/nft-gallery/assets/44554284/f369ee37-b904-4872-99aa-e343ba74b8f9

### CODE REVIEW

**Comment by yangwao** [comment]
> ❗️ Needs [kodadot/workers#255](https://github.com/kodadot/workers/pull/255)

done

**Comment by yangwao** [comment]
brutal, like it a lot

image

image

image

image

**Comment by hassnian** [comment]
> Can we make it to Wednesday release?

ready to test

**Comment by hassnian** [comment]
> Maybe include this? Or in another pr?
> 
> * [Party kit showing funds for user that are not connected #9488](https://github.com/kodadot/nft-gallery/issues/9488)

working on https://github.com/kodadot/nft-gallery/issues/9456 atm 

if you want to merge this already, I'll make a new pr otherwise I'll add it here.

**Comment by exezbcz** [comment]
> ready to test

@prury 👀

**Comment by prury** [comment]
@hassnian this party kit thing never really worked well here for me, any instructions on how to activate it? 
just connect with wallet? and then wait? it partially works sometimes tho

**Comment by hassnian** [comment]
> @hassnian this party kit thing never really worked well here for me, any instructions on how to activate it? 
> 
> just connect with wallet? and then wait? it partially works sometimes tho

hmm weird , it should work right away 

even if you don't have a wallet connected 

Open two tabs , same drop you'll see the cursor on the other tab

Maybe something it's failing , can you share your console ?

**Comment by prury** [comment]
> > @hassnian this party kit thing never really worked well here for me, any instructions on how to activate it?
> > just connect with wallet? and then wait? it partially works sometimes tho
> 
> hmm weird , it should work right away
> 
> even if you don't have a wallet connected
> 
> Open two tabs , separate user sessions , for example as many incognito tabs , same drop you'll see the cursor on the other tab
> 
> Maybe something it's failing , can you share your console ?

nevermind, reopened everything and it worked

minting: 

https://github.com/kodadot/nft-gallery/assets/36627808/106fc3f7-1109-4ef0-b6a0-44b9f45acab7

generating: 

https://github.com/kodadot/nft-gallery/assets/36627808/530cd4f2-66cd-4c9b-9eec-d7f46ef84956

minor: after generating it balance goes to 0 and then it loads proper balance

don't think its showing my correct balance tho:

image

**Comment by hassnian** [comment]
> minor: after generating it balance goes to 0 and then it loads proper balance

Will check 

it's not showing your balance , its the amount that you have spent so far , it's the same value as the profile page 

I also thought the same the first time I saw the design

**Comment by prury** [comment]
> > minor: after generating it balance goes to 0 and then it loads proper balance
> 
> Will check

❤️ 

> 
> it's not showing your balance , its the amount that you have spent so far , it's the same value as the profile page
> 
> I also thought the same , the first time I saw the design

ahhhh makes sense, ty

**Comment by prury** [comment]
@hassnian I've put the works for me, since its super minor and we have bigger things to focus

**Comment by yangwao** [comment]
Thanks!
pay 90 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $90 @ 7.59 USD/DOT ~ 11.858 $DOT
🧗 [16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD](https://polkadot.subscan.io/account/16faLfsywwNATaEfbH2ah75dn6ZmctQWpMS5G4KFhbmj5hnD)
🔗 [0x7670397bdf8c4f30e1fe7464c7f6cdf06f39785916a3c123fb8a0ecadb22219b](https://polkadot.subscan.io/extrinsic/0x7670397bdf8c4f30e1fe7464c7f6cdf06f39785916a3c123fb8a0ecadb22219b)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
