### PR TITLE
:wrench: rubickV9

### PR DESCRIPTION
**Pull request by vikiival**
## ⚠️ Please close this PR if the rmrk chain is allright

**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [x] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- https://github.com/kodadot/nft-gallery/discussions/4754#discussioncomment-7111297

## Screenshot 📸

- [ ] My fix has changed UI

### <samp>🤖 Generated by Copilot at 2255d57</samp>

Added RMRK NFT support by changing the GraphQL endpoint and client configuration in `utils/constants.ts`.

### <samp>🤖 Generated by Copilot at 2255d57</samp>

> _We summon the power of RMRK_
> _To unleash our NFTs in the dark_
> _We change the `URLS.rubick` and the `apolloClientConfig`_
> _To connect with the GraphQL endpoint of the gods_

### CODE REVIEW

**Comment by prury** [comment]
this happens when RMRK2 -> explore items -> uncheck buynow
image

**Comment by prury** [comment]
images taking a bit longer to load but rmrk1 and 2 seems ok

**Comment by vikiival** [comment]
this is for `rmrk` chain

**Comment by prury** [comment]
**rmrk:** 
images on explore items load ✔️ 
images inside collections load ✔️ 
collection banners load ✔️ 
(landing) top collections won't load ❌ 
(landing) spotlight missing results ❌ 
newest list ✔️ 
latest sales ✔️ 
more from this collection ✔️ 

Different results count: 

Deployed version: 


Canary(has more):

**Review by roiLeo — COMMENTED** [review]
- https://github.com/kodadot/nft-gallery/blob/927a6ba16f679e2adb46179d4c634fac34f1c31d/queries/config/.graphqlconfig#L7
- https://github.com/kodadot/nft-gallery/blob/927a6ba16f679e2adb46179d4c634fac34f1c31d/libs/static/src/indexers.ts#L9

**Comment by vikiival** [comment]
> - https://github.com/kodadot/nft-gallery/blob/927a6ba16f679e2adb46179d4c634fac34f1c31d/queries/config/.graphqlconfig#L7
> 
> - https://github.com/kodadot/nft-gallery/blob/927a6ba16f679e2adb46179d4c634fac34f1c31d/libs/static/src/indexers.ts#L9

image

**Comment by vikiival** [comment]
Thanks @prury for testing, squid will be removed

**Pull request closed without merging**
