### PR TITLE
1655 Fix Search input suggestions and search history

### PR DESCRIPTION
**Pull request by chandradot99**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇  _ Do a quick check before the merge. 

### PR type
- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main-nuxt** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases

### What's new?
- [x] PR closes #1715 
- [x] Added client option in apollo manual query.

### Had issue bounty label ?
- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=CeBWgisygADqqxGk7ju8aMNEKz1K2WkxMKC3G8HsMnm119n)

### Community participation
- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [x] My fix has changed **something** on UI, a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by yangwao** [comment]
Works when I search 

image


But doesn't work when I'm coming from previous search

image

and it opens me wrong results on different string 
image

Try yourself https://deploy-preview-1715--koda-nuxt.netlify.app/rmrk/gallery?search=kusama

**Comment by chandradot99** [comment]
@yangwao I have fixed the history issue also, can you check once again. If have also tested if from my side. If there is still any issue, can you please send me small video so that I can reproduce it on my side easily.

**Comment by yangwao** [comment]
> @yangwao I have fixed the history issue also, can you check once again. If have also tested if from my side. If there is still any issue, can you please send me small video so that I can reproduce it on my side easily.

Please update PR template and all needed stuff to proceed

**Comment by chandradot99** [comment]
> > @yangwao I have fixed the history issue also, can you check once again. If have also tested if from my side. If there is still any issue, can you please send me small video so that I can reproduce it on my side easily.
> 
> Please update PR template and all needed stuff to proceed

sure @yangwao

**Review by roiLeo — APPROVED** [review]
lgtm, it's working as excepted

**Comment by yangwao** [comment]
Perfect, I’ve sent the payout https://kusama.subscan.io/extrinsic/0x1c9ffac9f4eb4caf128eb246b33ddd6b81ac909aff8ece44e2b383c60f4dbe88

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/

**Pull request merged**
