### PR TITLE
fix: price_gte to only be included when min is explicitly specified

### LINKED ISSUE #6893: useSearchParam's useSearchPriceRange returns incorrect defaultParams
useSearchParam's useSearchPriceRange returns incorrect defaultParams

image

_Originally posted by @daiagi in https://github.com/kodadot/nft-gallery/pull/6868#pullrequestreview-1589351287_
_Additional context by @stephenjason89 : https://github.com/kodadot/nft-gallery/pull/6868#issuecomment-1688219208_

### PR DESCRIPTION
**Pull request by stephenjason89**
blocked by: #6868 

Buy Now filter
`listed=true`
Shows items that has 0 price or more

Well i don't know if it's by design. 

This has been considered by @daiagi as issue which i have linked in the issue #6893

Further investigation shows me that useSearchPriceRange returns wrong defaultParams

It is because default params have `price_gte=0`
it is illogical to have that argument together with `price_gt=0` when price is actually 0 

unless explicitly specified by the `min` filter

This PR corrects this issue

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context
- [x] Closes #6893

- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [ ] I've tested it at </ksm/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer?target=16UcV9V6nVvPYdHz98ymUKmNLkzjCEU5sbKJMi7hxYyTHjzR&usdamount=100&donation=true)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖 Generated by Copilot at 769abca</samp>

Refactored the code for opening the shopping cart modal from the navbar. Moved the logic and configuration from `ShoppingCartModalConfig.ts` and `ShoppingCartButton.vue` to `Navbar.vue` to improve code organization and performance.

### <samp>🤖 Generated by Copilot at 769abca</samp>

> _`ShoppingCartButton`_
> _Simpler, no more `emit` -_
> _Autumn leaves falling_

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]

**Review by daiagi — APPROVED** [review]

**Comment by roiLeo** [comment]
Capture d’écran 2023-08-23 à 9 02 43 AM

**Comment by stephenjason89** [comment]
@roiLeo  That's because of #6868

**Comment by roiLeo** [comment]
> @roiLeo That's because of #6868

spider-man-1967-double-identity-meme-pointing

**Comment by stephenjason89** [comment]
@roiLeo let me explain a bit further. I'm sorry for the confusion.

#6868 fixes the filter of buy now
Basically without that, Buy Now is not working.

This on the other hand, fixes the query for the graphql side. Because the query is incorrectly returning items with 0 price.

I hope that clears it up 😂 

I like your memes 🤭

**Comment by stephenjason89** [comment]
@yangwao 20th PR 🎉🙏🥳

**Pull request merged**
