### PR TITLE
fix: 5014 Disable Mint for {{space}} only input

### LINKED ISSUE #5014: Disable mint when NFT name is empty.
the name and description metadata for this NFT is an empty string

https://cloudflare-ipfs.com/ipfs/bafkreiefflxuhmidgwadjruzznzuyktndaepkriki66hffc77hsvfkxudm

_Originally posted by @preschian in https://github.com/kodadot/nft-gallery/issues/5003#issuecomment-1430874336_

### PR DESCRIPTION
**Pull request by maderi21**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #5014 
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [x] I've tested it at </bsx/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=JHJGu2aWyAFBfcso8bR7ma82p15YAavyN6vQfJyWuhniNGa)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

upper input: space
lower input: empty
image

### CODE REVIEW

**Comment by maderi21** [comment]
@roiLeo is this solution okay? looks like it's doing what we need

**Comment by roiLeo** [comment]
> @roiLeo is this solution okay? looks like it's doing what we need

not the solution I was looking for :/
I don't really like using regex and if I'm correct this one means input shouldn't be empty where there is some `BasicInput` that can be empty (like `IdentityForm`)

**Comment by maderi21** [comment]
> if I'm correct this one means input shouldn't be empty where there is some `BasicInput` that can be empty (like `IdentityForm`)

The regex only checks if the input isn't just space/s. It can stay empty, the prop `required` takes care of that. If there should be allowed spaces somewhere, such as IdentityForm, we can make this an optional prop.

> I don't really like using regex

is there something wrong with regex?

**Comment by roiLeo** [comment]
> The regex only checks if the input isn't just space/s. It can stay empty, the prop `required` takes care of that. If there should be allowed spaces somewhere, such as IdentityForm, we can make this an optional prop.

So to understand, with this change I won't be able to create nft with space chars in name?
I thought issue was about empty input but it look like it's working as excepted

> > I don't really like using regex
> 
> is there something wrong with regex?

personal experience it's a pain to maintain and can have side effects

> //edit: if the regex isn't okay, can you please point me in a direction of solution that would be acceptable?

maybe @preschian can enlighten us on the original error (are we sure it's not a metadata issue?)

**Comment by maderi21** [comment]
> So to understand, with this change I won't be able to create nft with space chars in name?

that wasn't intended, but that's the effect now. reverting back to draft for now.

**Comment by maderi21** [comment]
now the regex which doesn't allow spaces is applied only if the field is required and if the contents of the field are only spaces. otherwise, everything is allowed.

**Review by roiLeo — APPROVED** [review]

**Comment by yangwao** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 39.47 USD/KSM ~ 0.76 $KSM
🧗 [JHJGu2aWyAFBfcso8bR7ma82p15YAavyN6vQfJyWuhniNGa](https://kusama.subscan.io/account/JHJGu2aWyAFBfcso8bR7ma82p15YAavyN6vQfJyWuhniNGa)
🔗 [0x8c0668e5e41c0fd9858a444426d91b4ab5f1ca5a1d831961fc75104a19b95c4f](https://kusama.subscan.io/extrinsic/0x8c0668e5e41c0fd9858a444426d91b4ab5f1ca5a1d831961fc75104a19b95c4f)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
