### PR TITLE
Payout leaderboard for KodaDot #1477 1/2

### PR DESCRIPTION
**Pull request by petersopko**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] PR ~closes~ moves issue #1477
- [x] briefly: scraped all the data about PRs up to this point, went over old PRs, Subscan transactions, and finally produced accurate (as accurate as it can get) table of current Leaderboard when it comes to contributions. I have ready python to produce this table at any time now, however, as stated in #1477 , this should be transformed into Typescript/GitHub Action/Autocode Bot. Second part will be coming in march.

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
image

### CODE REVIEW

**Comment by vikiival** [comment]
Since this is markdown I would prefer to have short links. 
[last tx](https://kusama.subscan.io/extrinsic/0x9621824e4a94442bde24d21ab56b79a599)

**Comment by petersopko** [comment]
> Since this is markdown I would prefer to have short links. [last tx](https://kusama.subscan.io/extrinsic/0x9621824e4a94442bde24d21ab56b79a599)

image
like this?

**Comment by vikiival** [comment]
> this should be transformed into Typescript/GitHub Action/Autocode Bot. The second part will be coming in March.

@petersopko, I already leverage python with the GH action. Check [bao](https://github.com/kodadot/bao)

**Comment by petersopko** [comment]
> @petersopko, I already leverage python with the GH action. Check [bao](https://github.com/kodadot/bao)

I will happily transform it into bot with proper APIs (I've received one from Subscan later in the data collection process) but if nothing changed @yangwao wanted this to be specifically written in typescript so that is more accessible.

**Comment by yangwao** [comment]
yas lets at least do some progress on this :)

pay 300 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $300 @ 151.28 USD/KSM ~ 1.983 $KSM
🧗 [FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y](https://kusama.subscan.io/account/FNyt7T1xdbhN7dagf7yGYCRJuE3R45VmTCE3tjzy1rKxa7y)
🔗 [0xab1c553c4c2782d7480e9626939b6846ae9ed9ac9602b4a27172db0f4abe7c61](https://kusama.subscan.io/extrinsic/0xab1c553c4c2782d7480e9626939b6846ae9ed9ac9602b4a27172db0f4abe7c61)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
