### PR TITLE
1600 Add link to presskit to the footer

### LINKED ISSUE #1600: Add link to presskit to the footer
Add link **Press Kit** pointing to https://github.com/kodadot/kodadot-presskit/tree/main/v3 to footer

image

### PR DESCRIPTION
**Pull request by kkukelka**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇  _ Do a quick check before the merge. 

### PR type
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

Screenshot 2021-12-26 at 20 11 54

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything works
- [ ] I found edge cases

### What's new?
- [x] PR closes #1600
- [x] added interlinking to kodadot press kit to footer

### Had issue bounty label ?
- [ ] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=EqdyzrzVmeHwMdMwvPeCMnNdbuQDbD3YrjY93xq9Ln3jUGW)

### Community participation
- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [x] My fix has changed **something** on UI, a screenshot for others, is best to understand changes.

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
Hey! could you take a look on deepsource analysis?
It seem a new security issue has been introduced:
> Avoid target='_blank' attribute without rel='noopener noreferrer'

**Comment by kkukelka** [comment]
> Hey! could you take a look on deepsource analysis? It seem a new security issue has been introduced:
> 
> > Avoid target='_blank' attribute without rel='noopener noreferrer'

Sure, I just additionally added noreferrer. Strange issue however, since Google states that adding either rel="noopener" or rel="noreferrer" should be enough. https://web.dev/external-anchors-use-rel-noopener/?utm_source=lighthouse&utm_medium=devtools

**Review by roiLeo — APPROVED** [review]
lgtm

**Comment by yangwao** [comment]
Perfect, I’ve sent the payout https://kusama.subscan.io/extrinsic/0x83d8296921987d21f80367ae64a17ad027b39f5f62b9c0069d2bdee2222bdd04

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/

**Pull request merged**
