### PR TITLE
feat: Change footer in pure text

### LINKED ISSUE #9913: Change footer in pure text
wyt @exezbcz 
ours 
image
into
image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Feature

## Needs Design check

- @exezbcz please review

## Context

- [x] Closes #9913

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

image

### CODE REVIEW

**Comment by exezbcz** [comment]
amazing, just how i imagined it 

can we please maybe remove these non active platforms? So its not overcrowded 
image

- my pick is Instagram, reddit

**Review by vikiival — APPROVED** [review]

**Comment by exezbcz** [comment]
Thank you!

**Comment by prury** [comment]
thank you for fixing the test

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $15 @ 8.62 USD/DOT ~ 1.74 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0xdbadfde82bf212a5e9ab0cd09f929764e60a562ebac7da19c5c76691f1595321](https://polkadot.subscan.io/extrinsic/0xdbadfde82bf212a5e9ab0cd09f929764e60a562ebac7da19c5c76691f1595321)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
