### PR TITLE
🔧 explore filterMenuButton size and pack

### LINKED ISSUE #6216: Icon issue
Screenshot 2023-06-14 at 12-32-27 Low minting fees and carbonless NFTs KodaDot - NFT Market Explorer

### PR DESCRIPTION
**Pull request by roiLeo**
closes #6216 

- remove NeoIcon forced size px... (please use `customSize` if you want to set custom size)
- small refactor component
- fix icon alignment
- fix icon pack

Screenshot 2023-06-14 at 12-55-18 Low minting fees and carbonless NFTs KodaDot - NFT Market Explorer

### CODE REVIEW

**Comment by exezbcz** [comment]
small thing, can you please align it to the center on the y-axis 
image

+ could you please change the icon to this: https://fontawesome.com/icons/bars?f=sharp&s=regular

**Comment by roiLeo** [comment]
Can't be more aligned now hehe

Capture d’écran 2023-06-14 à 3 29 25 PM

**Comment by exezbcz** [comment]
ye 
s s

**Comment by roiLeo** [comment]
> It would also be nice to make the icon activation area bigger. I will create a separate issue since this was not the subject of the issue.

Yes! Best solution I find need a slight change in buttons config, what do you think about this example? (hover state)

Capture d’écran 2023-06-14 à 5 14 12 PM

**Comment by exezbcz** [comment]
@roiLeo, is it meant to show the area where the icon is in a hover state, or will you fill the background with a slightly grey color? 

This works for me! I would only make the icon change on hover and cursor pointer with the area displayed, which means no background change.

**Pull request merged**
