### PR TITLE
fix: Prevent user from adding comma on drops

### LINKED ISSUE #10465: Prevent user from adding comma on drops
image

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [Koda - Generative Art Marketplace](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #10465

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by hassnian — COMMENTED** [review]
I'd make this part of `NeoStepper`

**Comment by Jarsen136** [comment]
> I'd make this part of `NeoStepper`

Updated

**Comment by hassnian** [comment]
@Jarsen136 let's add a pattern to allow only numbers

CleanShot 2024-06-14 at 10 45 54@2x

**Comment by Jarsen136** [comment]
> @Jarsen136 let's add a pattern to allow only numbers
> 
> CleanShot 2024-06-14 at 10 45 54@2x

As we have set `type="number"` on the input oruga component, It should be handled properly. With chrome browser, it does not allow me to type any special character. 

Then I tried to reproduce the bug and found it could happen on Safari. I can't find a simple way to detect if there is any special char. The `modal-value` doesn't return the special char in this case.

**Comment by Jarsen136** [comment]
> Still, I managed to get "" so let's add 0 in that case, can we fix that, and I think we are good

I've thought about this before, but it's not appropriate. Imagine someone wants to delete all the entered numbers, set it to “”, and then enter “11”. The input box will always show ”0“  @hassnian 

Let's come back to the original issue. It fixes the problem of inputting non-integer with comma(,)/dot(.)

**Review by hassnian — APPROVED** [review]

**Review by preschian — APPROVED** [review]

**Pull request merged**
