### PR TITLE
#3035 Column overflow issue

### LINKED ISSUE #3035: series-insight table disaligned
### What happened?

A bug happend.

### Please reproduce in steps

jump to the page https://beta.kodadot.xyz/series-insight

### Expected Behavior

I've expected this should be the same with the [spotlight page](https://beta.kodadot.xyz/spotlight).

### What browsers are you seeing the problem on?

Chrome

### Are you logged in?

Yes

### At which address did you encounter bug?

beta.kodadot.xyz

### Screenshots

image

### Relevant log output

_No response_

### Payment link for reward

https://beta.kodadot.xyz/transfer?target=DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] PR closes #3035
- [x] Narrowed the cells works fine

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screen Shot 2022-05-20 at 4 07 14 PM

### CODE REVIEW

**Comment by kkukelka** [comment]
still overflowing, no? 
Screenshot 2022-05-21 at 06 56 33

or am i looking at the wrong page?

**Comment by prachi00** [comment]
> still overflowing, no? Screenshot 2022-05-21 at 06 56 33
> 
> or am i looking at the wrong page?

yeah its the correct page, can you tell me your screen size?

**Comment by kkukelka** [comment]
> 
> yeah its the correct page, can you tell me your screen size?

1470px

**Comment by prachi00** [comment]
> 👁️ 👅 👁️ how is it goin with the issue @prachi00 ?

Working on it todayyyyy

**Comment by prachi00** [comment]
@vikiival @kkukelka 
Had to make the table scrollable, there is no other way to handle this I believe. Looks fine though.

**Review by kkukelka — APPROVED** [review]
i guess we can leave it like that. we would probably have to remove a column otherwise.

still has a merge conflict though ☹️

**Comment by kkukelka** [comment]
pay 50

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 81.39 USD/KSM ~ 0.614 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x07cf883dd8d38cefb21e5606ebf2bdd90a61b08914542d8207cde2f398e4cf5f](https://kusama.subscan.io/extrinsic/0x07cf883dd8d38cefb21e5606ebf2bdd90a61b08914542d8207cde2f398e4cf5f)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
