### PR TITLE
fix: Hide testnet, movr & glmr on production

### LINKED ISSUE #4101: Hide testnet, movr & glmr on production
Hide on the upcoming redesign at kodadot.xyz 
- Snek
- MoonRiver
- MoonBeam

Keep it on beta.kodadot.xyz for development & testing purposes 

image

Seems this was done on chainselector
- https://github.com/kodadot/nft-gallery/issues/4019
- #4031 

Just removed (Kusama) to match the designs 
- https://github.com/kodadot/packages/commit/b99a1d7b9933b6bad530355021c0783aaa910f40
- rc10 package is incoming soon https://github.com/kodadot/packages/commit/89fbac229a513c739afd08943b2b0fccc098de9f

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #4101
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

image

### CODE REVIEW

**Comment by Jarsen136** [comment]
Should I place the `RMRK` at the first one?

**Review by roiLeo — COMMENTED** [review]
could we keep snek, glmr & movr on deploy-preview? as it would be better for review

**Comment by Jarsen136** [comment]
> could we keep snek, glmr & movr on deploy-preview? as it would be better for review

Make sense if we would like to preview something on snek\xx\xx.

**Review by roiLeo — APPROVED** [review]
✅ code lgtm

**Comment by kkukelka** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 41.62 USD/KSM ~ 1.201 $KSM
🧗 [Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG](https://kusama.subscan.io/account/Caiv9TbPz68q5dC8EcHu5xKYPRnremimGzqmEejDFNpWWLG)
🔗 [0xf9695666ce78d4c57ae2cde9eee98d4535e98b796311d45e776f4c3c7ef673cf](https://kusama.subscan.io/extrinsic/0xf9695666ce78d4c57ae2cde9eee98d4535e98b796311d45e776f4c3c7ef673cf)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
