### PR TITLE
🎩 Top Collections

### LINKED ISSUE #3866: Landing: Top/Trending Collections component
This is a placeholder

### PR DESCRIPTION
**Pull request by roiLeo**
### PR type

- [x] Feature

### What's new?

- [x] PR closes #3866 
- [x] New component visible on RMRK landing
- [x] waiting for BSX series resolver? (link kodadot/snek#63)

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've tested PR on mobile and everything seems works
- [x] I found edge cases: `seriesInsightTable` resolver floorPricee null
- [ ] I've written some unit tests 🧪

### What can be improved

- [x] chunk array in 2 column stack (left side 1 -> 6, right side 6 -> 12)
- [x] large screen 3 columns
- [x] new Design?
- [ ] hover image effects
- [ ] missing range volume (dailyVolume, dailyRangeVolume)

### Screenshot

**V1** (series resolver)
Screenshot 2022-08-29 at 12-22-29 KodaDot - Kusama NFT Market Explorer

**V2** (seriesInsightTable resolver)
Capture d’écran 2022-09-02 à 10 24 25 AM

**V3** (seriesInsightTable resolver)
Screenshot 2022-09-13 at 10-39-32 KodaDot - Kusama NFT Market Explorer

**V4** (series resolver, new landing)
Screenshot 2022-09-28 at 16-47-30 KodaDot - Kusama NFT Market Explorer
Screenshot 2022-09-28 at 16-36-54 KodaDot - Kusama NFT Market Explorer

### CODE REVIEW

**Comment by yangwao** [comment]
Since https://github.com/kodadot/nft-gallery/pull/3895 was merged, can this move on?

**Comment by roiLeo** [comment]
> Since
> 
>     * [redesign: prepare landing page for new design #3895](https://github.com/kodadot/nft-gallery/pull/3895) was merged, can this move on?

This was one not related with #3895, design is different from figma file. 
It's in DRAFT because of "What can be improved" content.

Do I need to start integrating the new design on this one?

I gotta change query for rmrk (ref kodadot/rubick#136) & wait for kodadot/snek#63

**Comment by petersopko** [comment]
@roiLeo seems that floor shows 0 on some collection where it isn't 0:
https://deploy-preview-3869--koda-nuxt.netlify.app/rmrk/collection/A4598F5615F201D739-GBD
image

**Comment by roiLeo** [comment]
> seems that floor shows 0 on some collection where it isn't 0

>  I found edge cases: seriesInsightTable resolver floorPricee null

**Comment by petersopko** [comment]
> maybe I'll change it back with Series resolver but I won't be able to filters rangeDate (24h, 7d, 30d)

I think we want both, the accurate floor price and filtering by rangeDate. Sounds to me like new resolver is needed for this?

**Review by petersopko — CHANGES_REQUESTED** [review]
doesn't seem ready to go to me

**Comment by yangwao** [comment]
> Do I need to start integrating the new design on this one?

yes, that would be doable!:)


> maybe I'll change it back with Series resolver but I won't be able to filters rangeDate (24h, 7d, 30d)

what if we skip it for this time rangeDate filter just to be closer to release? 🙏🛐

**Comment by yangwao** [comment]
> wen release?

https://github.com/kodadot/snek/pull/63 should be released, by @vikiival broke prod, working on that

**Comment by vikiival** [comment]
Yup we got unexpected runtime upgrade #4000

**Comment by yangwao** [comment]
Snek should be up and running https://discord.com/channels/840514076538830888/881839877140930630/1022801375182192680

**Comment by petersopko** [comment]
@roiLeo so what's the status on this? Are we waiting for something? I can see two things which need to be done to move forward with this PR:
> what if we skip it for this time rangeDate filter just to be closer to release?
1. sacrifice the range for the floor price (temporarily, until better solution comes around from the indexer side)

> > > Do I need to start integrating the new design on this one?

> > yes, that would be doable!:)

> I'll think about that :)

2. Make this available on `?redesign=true` in the style of new design, since that's where we are soon going anyway (correct me if I'm wrong here)

**Comment by roiLeo** [comment]
> @roiLeo so what's the status on this? Are we waiting for something? I can see two things which need to be done to move forward with this PR:

I'm waiting for snek series resolver to work https://github.com/kodadot/nft-gallery/pull/3869#issuecomment-1254913453 (empty result)

>  sacrifice the range for the floor price (temporarily, until better solution comes around from the indexer side)

Aight, now using series resolver for rmrk landing

> Make this available on `?redesign=true` in the style of new design, since that's where we are soon going anyway (correct me if I'm wrong here)

IMO, this is not ready for "new design" since the endpoint is only working for rmrk (no multichain, no date range, no % change). I might take a look in the next few days.

**Comment by petersopko** [comment]
> I'm waiting for snek series resolver to work https://github.com/kodadot/nft-gallery/pull/3869#issuecomment-1254913453 (empty result)

> [kodadot/snek#63](https://github.com/kodadot/snek/pull/63) should be released, by @vikiival broke prod, working on that

so I'm not still sure I understand, I thought the latest snek upgrades at 004 should be done now (working in prod etc.), yet the series resolver works like this: 
image

When it comes to snek this PR is going to work only on new Basilisk (005), i.e. after this gets merged and starts getting used?
- https://github.com/kodadot/nft-gallery/issues/4003

**Comment by roiLeo** [comment]
> so I'm not still sure I understand, I thought the latest snek upgrades at 004 should be done now (working in prod etc.), yet the series resolver works like this: image

Series resolver has been introduce in snekk 004 but it's still show empty result. (same goes for 005)
`seriesInsightTable` resolver worked for me in my local setup (ref screenshot https://github.com/kodadot/snek/pull/63#issue-1364440732), I don't really know why it's doing this but I'll try to have a look at it even if the project is very resource-intensive (maybe cache related? db migration?)

**Comment by vikiival** [comment]
https://github.com/kodadot/snek/actions/runs/3142494629

**Comment by vikiival** [comment]
Deployed also for basilisk

https://github.com/kodadot/snek/actions/runs/3142565744

**Comment by roiLeo** [comment]
Screenshot 2022-09-28 at 13-49-52 🎩 Top Collections by roiLeo · Pull Request #3869 · kodadot_nft-gallery

working on it, please be patient

**Comment by petersopko** [comment]
our new landing is beginning to look really nice ✅

**Review by petersopko — APPROVED** [review]
wfm, nice

**Review by petersopko — CHANGES_REQUESTED** [review]
small thing, I found out that the links are sometimes leading to undefined collections such as "/rmrk/undefined/24d573f4dfa1d7fd33-KAN"

**Review by petersopko — APPROVED** [review]

**Comment by yangwao** [comment]
hey, @roiLeo you should add the payout address!:)

- merging till then works flawlessly!
- made follow-up #4059

**Review by yangwao — APPROVED** [review]

**Comment by roiLeo** [comment]
updated with payout

**Pull request merged**
