### PR TITLE
Balance Input

### LINKED ISSUE #3560: Zero price at listings ?
I'm not sure if it's legit or if it's the same bug as #3533 ?

Seems I've bought NFT for 0 BSX 
https://beta.kodadot.xyz/bsx/gallery/3060885173-9
image

0 BSX at listing 
https://beta.kodadot.xyz/bsx/gallery/3060885173-7?page=1
image

### Ref
- https://github.com/kodadot/nft-gallery/issues/3533
- https://github.com/kodadot/nft-gallery/blob/3466fad47460414ca89b1ca4cf658b4098a8c8ff/utils/format/balance.ts#L37

### LINKED ISSUE #3589: Can't place offers
The minimum offer was supposed to be 10 000 or more; I tried to make an offer and got error:
image

_Originally posted by @JustLuuuu in https://github.com/kodadot/nft-gallery/issues/3578#issuecomment-1196744902_

### PR DESCRIPTION
**Pull request by vikiival**
## This PR is a hotfix for #3529

- :test_tube: validate balance implementation
- :zap: finally balance utils <3
- :test_tube: using balance utils
- :zap: SimpleBalanceInput
- :zap: NewBalanceInput
- :zap: New Balance Input
- :ambulance: critical hotfix for BalanceInput 67be7d78

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [x] Feature
- [x] Refactoring

### What's new?

- [ ] PR closes #3560, closes #3589
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by yangwao** [comment]
can't mint 

image

can mint

image

difference one digit

**Comment by yangwao** [comment]
seems list doesn't work as well? 

time to revert whole part of it? 

image

**Comment by vikiival** [comment]
> time to revert whole part of it?

This is the task for the new upcoming balance input which comes after this

**Review by petersopko — APPROVED** [review]
wfm:
- minted with correct price
- placed offer with correct price

**Comment by yangwao** [comment]
wfm too 👌

image

image

@cryptodamsky let's check, and we can merge! :D

**Comment by cryptodamsky** [comment]
Why is it showing option to List the nft when while minting i’ve already chosen to list it?

image

**Comment by yangwao** [comment]
> List the nft when while minting i’ve already chosen to list it?

to relist it for a different price. Make sense to adjust it for different verb once has some price set and I also notice we don't have that "Unlist" button there

**Comment by cryptodamsky** [comment]
Creating a collection and minting into it works, also inputting price and royalties, but


**Not sure if related, or if this is already tracked**
- When i create collection and it takes me to the second part where i mint into it, it doesn’t show up, i have to refresh


- One of my collections is still showing as number, not a name, wiz:

Screenshot 2022-07-28 at 15 56 23

**Comment by DeluneClaire** [comment]
WFM
- mint NFT with price
- offer for the price and shows the correct price

**Review by DeluneClaire — APPROVED** [review]
WFM
- mint NFT with price
- offer for the price and shows the correct price

**Comment by yangwao** [comment]
> * When i create collection and it takes me to the second part where i mint into it, it doesn’t show up, i have to refresh

- #3291 
- #3333 

> * One of my collections is still showing as number, not a name, wiz:

might be related with previous one

**Review by Jarsen136 — APPROVED** [review]
LGTM

**Review by cryptodamsky — APPROVED** [review]

**Review by yangwao — APPROVED** [review]

**Pull request merged**
