### PR TITLE
🔧 NeoButton final story

### PR DESCRIPTION
**Pull request by roiLeo**
link #7957
Capture d’écran 2023-12-02 à 2 08 25 PM
Capture d’écran 2023-12-02 à 2 09 39 PM

### CODE REVIEW

**Comment by exezbcz** [comment]
button story, 


is anything needed from me sir? 👀

**Comment by exezbcz** [comment]
what is needed here to be finished? 


some styles I see that are not correct: 


image
image
image

**Comment by roiLeo** [comment]
> what is needed here to be finished?

styling, and remove old integration

> some styles I see that are not correct:

yup, wip will try to finish as soon as I've got time

**Comment by yangwao** [comment]
Stale, please reopen if there is intent to finish it.

**Pull request closed without merging**
