### PR TITLE
update github actions

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### What's new?

- [x] update GitHub actions to the latest node.js version
- [x] is it safe to delete unused GitHub actions files? Because there are email notifications about that everytime I open PR
Screen Shot 2022-03-21 at 1 35 22 PM

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by preschian** [comment]
btw, how about using a major version (`v16`) instead of a specific patch version (`v16.14.2`)? 
- https://github.com/kodadot/nft-gallery/blob/main/package.json#L46
- https://github.com/kodadot/nft-gallery/blob/main/Dockerfile#L2
- https://github.com/kodadot/nft-gallery/blob/main/.github/workflows/build.yml#L17
- https://github.com/kodadot/nft-gallery/blob/main/.github/workflows/reviewdog.yml#L17

**Comment by yangwao** [comment]
> btw, how about using a major version (`v16`) instead of a specific patch version (`v16.14.2`)?
> 
> * [https://github.com/kodadot/nft-gallery/blob/main/package.json#L46](https://github.com/kodadot/nft-gallery/blob/main/package.json?rgh-link-date=2022-03-21T08%3A21%3A49Z#L46)
> * [https://github.com/kodadot/nft-gallery/blob/main/Dockerfile#L2](https://github.com/kodadot/nft-gallery/blob/main/Dockerfile?rgh-link-date=2022-03-21T08%3A21%3A49Z#L2)
> * [https://github.com/kodadot/nft-gallery/blob/main/.github/workflows/build.yml#L17](https://github.com/kodadot/nft-gallery/blob/main/.github/workflows/build.yml?rgh-link-date=2022-03-21T08%3A21%3A49Z#L17)
> * [https://github.com/kodadot/nft-gallery/blob/main/.github/workflows/reviewdog.yml#L17](https://github.com/kodadot/nft-gallery/blob/main/.github/workflows/reviewdog.yml?rgh-link-date=2022-03-21T08%3A21%3A49Z#L17)

I guess so would be nice, yet renovate has updating it whenever new version or security version node is out to particular version, let's give it a shot if you can find in renovate docs to opt out from bumping nodejs version as it's send immortal PRs :)
Making this as extra issue

**Comment by yangwao** [comment]
pay 100 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $100 @ 155.35 USD/KSM ~ 0.644 $KSM
🧗 [DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM](https://kusama.subscan.io/account/DY4SQF2iD456tH89aQtz5wv1EV3BbSW8wKKuMcwbmXaj1pM)
🔗 [0xe021bd1f6b844a4309f3dd6664388788ab3fde4782a7e91464f0404ddae159ed](https://kusama.subscan.io/extrinsic/0xe021bd1f6b844a4309f3dd6664388788ab3fde4782a7e91464f0404ddae159ed)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
updated #2641

**Pull request merged**
