### PR TITLE
🎩 update new favicon

### PR DESCRIPTION
**Pull request by roiLeo**
### PR type

- [x] Feature

### What's new?

- [x] PR related #3345 
- [x] new favicon check preview

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

### CODE REVIEW

**Review by kkukelka — APPROVED** [review]
wohoo!

**Comment by petersopko** [comment]
@roiLeo not sure if it's me, but is it possible to make the icon bigger?
image
Just this perspective in tabs, seems to be the case that GH has much better visibility on this icon 🤔

**Comment by roiLeo** [comment]
Capture d’écran 2022-08-16 à 10 58 21 PM

thomas the tank

**Comment by roiLeo** [comment]
> @roiLeo not sure if it's me, but is it possible to make the icon bigger? image Just this perspective in tabs, seems to be the case that GH has much better visibility on this icon 🤔

Tried to make it bigger, I may need to create svg version

**Comment by roiLeo** [comment]
meh
Capture d’écran 2022-08-17 à 8 39 05 AM

**Comment by vikiival** [comment]
Force push au 🥲

**Review by DeluneClaire — APPROVED** [review]
The new favicon looks nice! WFM

**Pull request merged**
