### PR TITLE
fix: loader

### LINKED ISSUE #4009: Missing loader on Offer tab user detail
tried to withdraw offer through user profile (snek/u/address) and when hitting the action button (X) no loader shows up, just prompt from wallet to sign transaction. After signing, I don't see any loader even though, offer is being withdrawn / accepted
image
after some time this shows up: 
image

please make sure:

1. loader shows up when withdrawing offer through profile detail
2. same for accepting offer

### PR DESCRIPTION
**Pull request by KngZhi**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #4009
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer?target=DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc)

### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by Jarsen136 — APPROVED** [review]
code lgtm.
 I'm not sure the loader could cover everywhere when it comes to offers.

**Comment by KngZhi** [comment]
> I'm not sure the loader could cover everywhere when it comes to offers.

Both incoming offer and nft detail offer tables have `<Loader>`, and they work well.

**Review by petersopko — APPROVED** [review]
wfm 🚀

**Comment by petersopko** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 41.66 USD/KSM ~ 0.72 $KSM
🧗 [DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc](https://kusama.subscan.io/account/DaWoVNNhBTdqJ5iPN3UcaLeamkPpJeGWdrs8LhvX9TQbadc)
🔗 [0x8d607dc52fb5bba52c387bb3d03f8e4cc98afc20b67c487044274f2c905bfb87](https://kusama.subscan.io/extrinsic/0x8d607dc52fb5bba52c387bb3d03f8e4cc98afc20b67c487044274f2c905bfb87)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
