### PR TITLE
#1037 Put collections status to between artist and actions

### LINKED ISSUE #1037: Put collections status to between artist and actions
Till we figure out better design for collection, to save space on smaller screens, let's put collection status like 
items, owned, floor price, traded, &c between artist profile and actions.

Put it in order like
| items | floor price | volume traded | 
| :--: | :--: | :--: |
| owned | distribution  | 24h volume traded |

distribution == owned items by users / unique owners 

image

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the KodaDot NFT gallery.

👇 Let's do a quick check before the merge.

### PR type
- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional
- [x] I've tested PR on mobile and everything works
- [ ] I found edge cases

### What's new?
- [x] PR closes #1037

### Had issue bounty label ?
- [x] Fill up your KSM address: 
[Payout](https://kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation
- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [x] My fix has changed **something** on UI, a screenshot for others, is best to understand changes.

Screenshot 2021-11-10 at 3 19 44 PM

### CODE REVIEW

**Comment by yangwao** [comment]
bump, you've made it against `main-nuxt` which isn't finished on migration and I've changed it to `main` 
we will resolve this in #1077

**Comment by prachi00** [comment]
> @prachi00 is that possible to put it a bit smaller numbers? Reason is to be bit horizontal alignment plus extra, let's put labels under number, as brain reads from up to down, left to right :)
> 
> image

@yangwao you mean I should decrease the font size of numbers? Sure, that could be done

**Comment by prachi00** [comment]
> > @prachi00 is that possible to put it a bit smaller numbers? Reason is to be bit horizontal alignment plus extra, let's put labels under number, as brain reads from up to down, left to right :)
> > image
> 
> @yangwao you mean I should decrease the font size of numbers? Sure, that could be done
Screenshot 2021-11-10 at 9 28 31 PM
 @yangwao something like this?

**Comment by yangwao** [comment]
LGTM! 
https://deploy-preview-1079--nftkodadot.netlify.app/rmrk/collection/8c5359d2bddaca9f4c-BBSF
image

Let's expand rounding to 4 decimal numbers to be consistent.

**Comment by prachi00** [comment]
> /rmrk/collection/8c5359d2bddaca9f4c-BBSF

@yangwao done

**Comment by prachi00** [comment]
> > /rmrk/collection/8c5359d2bddaca9f4c-BBSF
> 
> @yangwao done
Screenshot 2021-11-10 at 9 50 57 PM

**Comment by roiLeo** [comment]
@prachi00 I'm changing column size in #1063, so collectionActivity will be aligned to the center of the screen.

**Comment by prachi00** [comment]
> @prachi00 I'm changing column size in #1063, so collectionActivity will be aligned to the center of the screen.

@roiLeo In this pr, I have aligned it in between 

> @prachi00 I'm changing column size in #1063, so collectionActivity will be aligned to the center of the screen.

@roiLeo but in this pr, its getting aligned between profile and actions?

**Comment by yangwao** [comment]
payout sent! 
https://kusama.subscan.io/extrinsic/0x21990f2dc1f4c111206d22417c11afd97ce92ca1c6fcac9a126cfd2172eda2d4
merging

**Pull request merged**
