### PR TITLE
#3974 links from stats at /snek

### LINKED ISSUE #3974: links from stats at /snek
generated hyperlinks in the tables at /offers and /stats are leading to /bsx prefixed destination -> should be /snek

steps to reproduce:

1. go to https://beta.kodadot.xyz/snek/stats

2. click on the first item in the table, see where link follows

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

### What's new?

- [x] PR closes #3974
- [ ] Requires deployment <rubick/magick_issue>
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Comment by yangwao** [comment]
@petersopko 👀

**Review by roiLeo — COMMENTED** [review]
missing `MyOffer` component? https://github.com/kodadot/nft-gallery/blob/25b4f685fd170e56f09cec4c1b2e7f18c5d722af/components/bsx/Offer/MyOffer.vue#L23

**Comment by petersopko** [comment]
@prachi00 please check also links from https://deploy-preview-3975--koda-nuxt.netlify.app/snek/incomingoffers

**Review by petersopko — CHANGES_REQUESTED** [review]
/incomingoffers

**Review by petersopko — APPROVED** [review]
wfm

**Comment by petersopko** [comment]
this lgtm, @roiLeo pls check 👀

**Review by roiLeo — APPROVED** [review]
🚀 looks good

**Comment by petersopko** [comment]
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 40.18 USD/KSM ~ 0.747 $KSM
🧗 [EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU](https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)
🔗 [0x1d11407c7a80d4394b4a325491be22ab1d3cd8d3d706cbce19e83bd749d396bb](https://kusama.subscan.io/extrinsic/0x1d11407c7a80d4394b4a325491be22ab1d3cd8d3d706cbce19e83bd749d396bb)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
