### PR TITLE
🔧 in activity chart - fix case where not enough data for binning

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

fix a bug in activity chart when buy events/ list events array length < 2

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
Hey! I don't really know what does this PR fix. 
Can you share exemple to reproduce this bug to see what this is about?
or link which particular nft/collection

**Comment by daiagi** [comment]
> Hey! I don't really know what does this PR fix. 
> Can you share exemple to reproduce this bug to see what this is about?
> or link which particular nft/collection

Some collections have no buy events or just 1 buy event.
In these cases binning (moving average) is not needed and cannot be done
That is what this pr fixes, its an edge case I failed to consider when writing the moving average code

For example here no chart is visible due to this bug 
https://beta.kodadot.xyz/bsx/collection/1165325904/activity

**Comment by yangwao** [comment]
🚨 just notice `main` is now https://canary.kodadot.xyz 
- https://github.com/kodadot/nft-gallery/issues/5420

**Review by roiLeo — APPROVED** [review]
Tested on `/bsx/collection/2551182625/activity` 

| Before  | After          | 
| :---------------: |:---------------:| 
| Screenshot 2023-04-04 at 14-03-15 KodaDot - NFT Market Explorer | Screenshot 2023-04-04 at 14-03-00 Luna Witches KodaDot - NFT Market Explorer |  

✅ wfm I guess

**Review by Jarsen136 — APPROVED** [review]

**Pull request merged**
