### PR TITLE
Replace bulma flex helpers with tailwindcss

### LINKED ISSUE #8556: Remove bulma flex helpers and change it with tailwindcss
Context is here: https://github.com/kodadot/nft-gallery/discussions/8066

The first step of removing bulma from the project I'm going to do is to remove flex classes such as:

`is-flex`
`is-align-items-*`
`is-justify-content-*`
`is-flex-direction-*`
`is-flex-grow-*`

These are the least dangerous classes, which have an exact equivalent in tailwindcss

cc @roiLeo can I start doing this?

### PR DESCRIPTION
**Pull request by shashkovdanil**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Context

- [x] Closes #8556
- [ ] Requires deployment <snek/rubick/worker>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality

#### Optional

- [x] I've tested it at </ksm/collection>
- [x] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer?target=16SpvdDgKNiQ3c53DxX7refnQcKUD3uRNim3Z1HBJLNGrtSP&usdamount=0)

#### Community participation

- [x] [Are you at KodaDot Ecosystem Telegram?](https://t.me/kodadot_eco)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at fe4a31e</samp>

This pull request migrates the frontend styling from Bulma to Tailwind CSS, by replacing the Bulma flex classes with the equivalent Tailwind flex classes in various components. This improves the consistency and maintainability of the codebase, and simplifies the flexbox layout and alignment. The pull request also removes the unused `.is-flex-1` class from the `global.scss` file.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at fe4a31e</samp>

> _`Bulma` fades away_
> _`Tailwind` flexes its power_
> _A new spring for code_

### CODE REVIEW

**Comment by daiagi** [comment]
210 files in a single PR is a bit much to check and verify
i would prefer closing this one and splitting the work between multiple PR's

**Review by roiLeo — APPROVED** [review]

**Review by hassnian — APPROVED** [review]

**Comment by prury** [comment]
ok, i looked into what i could, too many files.

**Comment by yangwao** [comment]
This would break many things I sense?

image

Also lot of conflicts 

image

**Comment by roiLeo** [comment]
> @roiLeo Could you do a merge? It's a big PR and I'll often have to fix conflicts

need 2nd approval

**Comment by daiagi** [comment]
OK. Let's roll

**Review by daiagi — APPROVED** [review]

**Pull request merged**
