### PR TITLE
fix: #4459 Inconsistent hover state on selected language

### LINKED ISSUE #4459: Inconsistent hover state on selected language
### What happened?

I have noticed some inconsistencies in the language dropdown. When I hover over the selected language, it shows like this:

Screen Shot 2022-12-08 at 18 56 50 PM

While at other places, I have seen hover state style on selected options as

Screen Shot 2022-12-08 at 19 01 02 PM

### Please reproduce in steps

1. Go to user icon in the header
2. Choose the language option
3. Hover over the selected language

### Expected Behavior

The background color should be black on the hover state for the selected language. So, It looks consistent. 

### What browsers are you seeing the problem on?

Chrome

### At which address did you encounter bug?

beta.kodadot.xyz, kodadot.xyz

### Are you logged in?

None

### Which wallet you are using?

_No response_

### At which chain did you encounter bug?

_No response_

### Screenshots

Screen Shot 2022-12-08 at 18 56 50 PM

### Relevant log output

_No response_

### Payment link for reward

https://kodadot.xyz/transfer?target=GhvqRXYu6pywEkdCzyuoUrEgaKkUML2mCW9dWz7wniQtcMw

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by vkbishu**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Context

- [x] Closes #4459 
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer?target=GhvqRXYu6pywEkdCzyuoUrEgaKkUML2mCW9dWz7wniQtcMw)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

Screen Shot 2022-12-08 at 20 01 59 PM

### CODE REVIEW

**Comment by petersopko** [comment]
https://github.com/kodadot/nft-gallery/issues/4459#issuecomment-1342828426

note: it's same on beta, there isn't black on hover, just black on selected?

**Comment by vkbishu** [comment]
> [#4459 (comment)](https://github.com/kodadot/nft-gallery/issues/4459#issuecomment-1342828426)
> 
> note: it's same on beta, there isn't black on hover, just black on selected?

@petersopko I am talking about the hover state on the selected language in the language dropdown. On the selected language, the hover background color should be black, not light pink.

**Comment by petersopko** [comment]
> @petersopko I am talking about the hover state on the selected language in the language dropdown. On the selected language, the hover background color should be black, not light pink.

my bad, I [misunderstood](https://twitter.com/elonmusk/status/1600439088560996353?s=20&t=uVH13ORgmjntoSsT4-WOfg)

**Comment by exezbcz** [comment]
Yes, this works fine; we will most likely add a check to these buttons to make it more obvious what section is selected.

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 29.93 USD/KSM ~ 1.002 $KSM
🧗 [GhvqRXYu6pywEkdCzyuoUrEgaKkUML2mCW9dWz7wniQtcMw](https://kusama.subscan.io/account/GhvqRXYu6pywEkdCzyuoUrEgaKkUML2mCW9dWz7wniQtcMw)
🔗 [0xfe78bc056332fdab734d38f9775b687012e2de4a6a479b841b25e0d914224ecb](https://kusama.subscan.io/extrinsic/0xfe78bc056332fdab734d38f9775b687012e2de4a6a479b841b25e0d914224ecb)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
