### PR TITLE
feat: Share on Farcaster / Warpcast

### LINKED ISSUE #9679: Share on Farcaster / Warpcast
Add icon of Warpcast / Farcaster on this dialog

image

rel
--
- #9576

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Feature

  ## Needs QA check

  - @kodadot/qa-guild please review

  ## Context

  - [x] Closes #9679

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

image

  ## Copilot Summary
  copilot:summary

  copilot:poem

### CODE REVIEW

**Comment by daiagi** [comment]
looking at the screenshot you've posted
X icon looks not aligned vertically

**Comment by yangwao** [comment]
> X icon looks not aligned vertically

close, Farcaster is down like 2-3px along others

**Comment by Jarsen136** [comment]
Good catch! I have updated the icon of Farcaster for a better fit.
image

**Comment by yangwao** [comment]
Minor

> Move to svg Farcaster file in public
> I thought so too, but moving to a separate svg file will cause the currentColor to be invalid.

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 10.65 USD/DOT ~ 2.817 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x393350b8038c9c92325e7c031bdc337a9747ee374e34a3032b10849f8bc5b8e9](https://polkadot.subscan.io/extrinsic/0x393350b8038c9c92325e7c031bdc337a9747ee374e34a3032b10849f8bc5b8e9)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
Let's add to the success modal share which # you've minted out of total supply, i.e. coinbase inspiration

image

**Pull request merged**
