### PR TITLE
re-organized placement for aesthetics

### PR DESCRIPTION
**Pull request by thea-exe**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [ ] Feature
- [x ] Refactoring

### What's new?

- [ ] PR closes #<issue_number>
- [x ] I reorganized the placements of the links in the bottom footer for aesthetic purposes and from most-->least importance

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases
- [ ] I've written some unit tests 🧪

### Had issue bounty label?

- [x] Fill up your KSM address: [Payout](https://kodadot.xyz/transfer/?target=FLct4GSJ7X8wf3C1hXesWNKEKikYXDUfHfvvfSzTCBkZmc6&usdamount=0)

### Community participation

- [ x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot

- [ x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.
Screen Shot 2022-04-24 at 6 21 12 PM

### CODE REVIEW

**Comment by yangwao** [comment]
let's update update your address to payout and we can merge this! :)

**Comment by thea-exe** [comment]
Done :D @yangwao

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 146.17 USD/KSM ~ 0.342 $KSM
🧗 [FLct4GSJ7X8wf3C1hXesWNKEKikYXDUfHfvvfSzTCBkZmc6](https://kusama.subscan.io/account/FLct4GSJ7X8wf3C1hXesWNKEKikYXDUfHfvvfSzTCBkZmc6)
🔗 [0x093bdf32d514684250b6290a530fc8fe2cc4e24804cd41b654020b1a7d0cfa6f](https://kusama.subscan.io/extrinsic/0x093bdf32d514684250b6290a530fc8fe2cc4e24804cd41b654020b1a7d0cfa6f)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
