### PR TITLE
Bump ParaSpell version

### LINKED ISSUE #4509: Paraspell SDK Version Bump
### Is your feature request related to a problem?

New version of ParaSpell SDK featuring little different syntax will come out today.
change from `transferParaToRelay` into `send` which now combines ParaToPara and ParaToRelay scenarios in one function.

### Describe the solution you would like

Our team will open PR that will implement support for new version for you and then link it here.

### Describe alternatives you have considered

-

### Screenshots

_No response_

### Are there opened related issues?

_No response_

### PR DESCRIPTION
**Pull request by dudo50**
- update syntax for ParaToRelay scenario

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes #4509 
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by Jarsen136 — COMMENTED** [review]
Please excute `pnpm install` in your local env to update the `pnpm-lock.yaml` file

**Comment by yangwao** [comment]
> ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with package.json

@dudo50 seems your PR doesn't build.

> Please excute `pnpm install` in your local env to update the pnpm-lock.yaml file

**Comment by dudo50** [comment]
@yangwao, the lock.json file in ParaSpell has just been bumped. I hope this resolves the issue.

**Comment by dudo50** [comment]
Oh, thanks for letting me know @Jarsen136, just pushed updated lock file :) hope this does it

**Comment by Jarsen136** [comment]
> Oh, thanks for letting me know @Jarsen136, just pushed updated lock file :) hope this does it

Yes, that's it

**Comment by Jarsen136** [comment]
I have done a test for teleportin KSM token. It works as before.

image

**Review by Jarsen136 — APPROVED** [review]

**Pull request merged**
