### PR TITLE
fix: button styling retry

### LINKED ISSUE #9626: button styling retry
image

should have hover effect of this button: 
image

https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=5311-18771&mode=design&t=Q6SRMfYAQmOItuKE-11

please don't combine the hover effect of a secondary button with this one

### PR DESCRIPTION
**Pull request by Jarsen136**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

  👇 __ Let's make a quick check before the contribution.

  ## PR Type

  - [x] Bugfix

  ## Needs Design check

  - @exezbcz please review

  ## Context

  - [x] Closes #9626

  #### Did your issue had any of the "$" label on it?

  - [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)

  ## Screenshot 📸

  - [x] My fix has changed UI

image

image

  ## Copilot Summary
  copilot:summary

  copilot:poem

### CODE REVIEW

**Comment by exezbcz** [comment]
cant test :D looks like another bug appeared, opening issue

image

**Comment by prury** [comment]
> cant test :D looks like another bug appeared, opening issue
> 

indeed, thank you

**Comment by prury** [comment]
width got reduced in comparison to canary: 

https://github.com/kodadot/nft-gallery/assets/36627808/3971a1bc-b691-4dc0-b72c-9890aa4e1179

hover looks ok:

image

**Comment by Jarsen136** [comment]
> width got reduced in comparison to canary:
> 

✅ Updated

**Review by prury — APPROVED** [review]

**Comment by yangwao** [comment]
thanks!
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 10.29 USD/DOT ~ 1.944 $DOT
🧗 [16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z](https://polkadot.subscan.io/account/16SjUbGKSdjCdWTy3NNT3JxbRVGGqD4mwkHpc6BD9U2Rp29Z)
🔗 [0x8466fc18103187b0d6ecd2651ed27f122fcdfcb2d0d611a3e109a9c52b07dfcb](https://polkadot.subscan.io/extrinsic/0x8466fc18103187b0d6ecd2651ed27f122fcdfcb2d0d611a3e109a9c52b07dfcb)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
