### PR TITLE
Fix: Change the NeoButton style that so that  button style is disable…

### LINKED ISSUE #10210: Button states (active, focus) - revisions
followup for: 
- #10066 

in the components, there is defined focus state, by focus state i mean the state that happens when you navigate tab using tab

image
- it should not be the state when you hold the button 

image

on thing are dropdowns, when clicking, it turns the black stroke to white one

image

https://www.figma.com/file/JXNtryaNYhY0XJNArzvPQx/Handoff?type=design&node-id=5311-18771&mode=design&t=wIR4vUyhVh1KHnUu-11

### PR DESCRIPTION
**Pull request by Victor0355**
Thank you for your contribution to the [Koda - Generative Art Marketplace](https://kodadot.xyz/).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Needs Design check

- @exezbcz please review

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #10210

## Screenshot 📸

- [x] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

- [x] This is the style before change.
image

- [x] This is the style after change.
image

### CODE REVIEW

**Comment by vikiival** [comment]
cc @daiagi @has

**Review by hassnian — CHANGES_REQUESTED** [review]
missing https://github.com/kodadot/nft-gallery/issues/10210#issuecomment-2094838938

CleanShot 2024-05-13 at 17 48 09

@exezbcz visual check , thanks

**Comment by Victor0355** [comment]
Hi @hassnian ,
I'd like you to check my new commit as soon as possible.
image

**Comment by prury** [comment]
Contribution does not match our code standards: 
- too much duplicated code and failing to solve the issue

**Pull request closed without merging**
