### PR TITLE
feat: Audio player Waveform timeline

### LINKED ISSUE #7366: music files follow up - improve loading indication
How about change this event to 'canplay'?

That should give the feeling of quick loading and it will be inline with @exezbcz suggestion

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/canplay_event

Then can use this event
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/waiting_event

To show loading spinner while buffering

_Originally posted by @daiagi in https://github.com/kodadot/nft-gallery/pull/7275#discussion_r1335099021_

### LINKED ISSUE #7381: Clickable timeline with audio
followup after: 
- https://github.com/kodadot/nft-gallery/pull/7275
image
- when you click in the middle, it still does not work for me
- it moves the player to the start, not where the user clicked 

possible improvement, replacing timeline with sound wave 

image
- more on that here: #5228

### PR DESCRIPTION
**Pull request by hassnian**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

## Context

- [x] Closes kodadot/nft-gallery#7381
- [x] Closes kodadot/nft-gallery#7366

#### Did your issue had any of the "$" label on it?

- [x] Fill up your DOT address: [Payout](https://kodadot.xyz/dot/transfer?target=13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)

#### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [x] My fix has changed **something** on UI; 

CleanShot 2023-10-01 at 11 17 31

### <samp>🤖 Generated by Copilot at e96239f</samp>

This pull request adds a new feature to the `NeoAudioPlayer` component that allows users to see and interact with the audio waveform using the `wavesurfer.js` library. It also updates the `pnpm-lock.yaml` and `package.json` files to install and secure the new dependency, and fixes a type mismatch in the `usePlayerEventBus` composable.

### <samp>🤖 Generated by Copilot at e96239f</samp>

> _We are the masters of the wave, we render the sound of doom_
> _We change the type of the id, we make it a string of gloom_
> _We bind the audio element, we unleash the power of src_
> _We update the lockfile version, we secure the wavesurfer.js_

### CODE REVIEW

**Comment by exezbcz** [comment]
clicking on the timelines still does not work for me, any ideas on how to fix that? It resets always to zero

**Comment by hassnian** [comment]
> clicking on the timelines still does not work for me, any ideas on how to fix that? It resets always to zero

is it throwing any errors on the console ?

**Comment by exezbcz** [comment]
> > clicking on the timelines still does not work for me, any ideas on how to fix that? It resets always to zero
> 
> is it throwing any errors on the console ?

Will do recording

**Comment by exezbcz** [comment]
the waveform is loading quite slowly, would it be possible to mby waveform with fewer points? 
image

**Comment by hassnian** [comment]
@exezbcz regarding the waveform colors 

progress -> black 
waveColor -> k-grey 

and also dark mode pls 

atm 

CleanShot 2023-10-01 at 16 50 23@2x

pls have a look and let me know 

> the waveform is loading quite slowly, would it be possible to mby waveform with fewer points? image

will check

**Comment by exezbcz** [comment]
> can you provide white and also dark mode pls

sure, I think for dark mode it could be k-grey and white

**Comment by hassnian** [comment]
> the waveform is loading quite slowly, would it be possible to mby waveform with fewer points? image

from what I can see this is the suggested solution https://github.com/katspaugh/wavesurfer.js/issues/1563#issuecomment-478339492

CleanShot 2023-10-02 at 10 00 02@2x

load pre-generated peaks, that'd make it faster

**Comment by hassnian** [comment]
@preschian pls review , also what do you think about this https://github.com/kodadot/nft-gallery/pull/7436#issuecomment-1742413899

**Comment by preschian** [comment]
how to play the audio? I'm getting this

image


https://deploy-preview-7436--nuxt-kodadot.netlify.app/ksm/gallery/14968743-3629a3ff458d113e25-MUSIC-MOOD-00000068

**Comment by preschian** [comment]
I'm not able to navigate to the middle of song. is that related to this? https://github.com/kodadot/nft-gallery/pull/7436#issuecomment-1742413899

https://deploy-preview-7436--nuxt-kodadot.netlify.app/ksm/gallery/15297922-900d19dc7d3c444e4c-PLANETPO-DEEPOLOGIC_PLANET_PO_EP-00000003

**Comment by hassnian** [comment]
> I'm not able to navigate to the middle of song. is that related to this? [#7436 (comment)](https://github.com/kodadot/nft-gallery/pull/7436#issuecomment-1742413899)
> 
> https://deploy-preview-7436--nuxt-kodadot.netlify.app/ksm/gallery/15297922-900d19dc7d3c444e4c-PLANETPO-DEEPOLOGIC_PLANET_PO_EP-00000003

checking that 

that comment is related to this 

CleanShot 2023-10-03 at 16 44 46@2x

**Comment by hassnian** [comment]
> ksm/gallery/15297922-900d19dc7d3c444e4c-PLANETPO-DEEPOLOGIC_PLANET_PO_EP-00000003

@preschian 
this seems an issue unrelated to this pr , animation url is NULL 

CleanShot 2023-10-04 at 11 19 35@2x

CleanShot 2023-10-04 at 11 10 24@2x

this is an indexer issue isn't or how else do you know that a resource is of audio type?

**Review by preschian — APPROVED** [review]

**Comment by hassnian** [comment]
@preschian regarding the seeking issue 

doesn't work 
https://image-beta.w.kodadot.xyz/ipfs/bafybeiflsfxthods2dvw2a5zewh4slmtl5rne7me7uxrk5geos52vd456q
CleanShot 2023-10-04 at 11 59 12


does work 
https://bafybeiflsfxthods2dvw2a5zewh4slmtl5rne7me7uxrk5geos52vd456q.ipfs.dweb.link/
CleanShot 2023-10-04 at 12 00 00

same ipfs file

**Comment by preschian** [comment]
@hassnian I think keep this issue open https://github.com/kodadot/nft-gallery/issues/7381, need to find a way to navigate audio in the middle of song

**Comment by hassnian** [comment]
sure

**Comment by preschian** [comment]
> @preschian regarding the seeking issue
> 
> doesn't work [image-beta.w.kodadot.xyz/ipfs/bafybeiflsfxthods2dvw2a5zewh4slmtl5rne7me7uxrk5geos52vd456q](https://image-beta.w.kodadot.xyz/ipfs/bafybeiflsfxthods2dvw2a5zewh4slmtl5rne7me7uxrk5geos52vd456q)

aahh, I see, this is an issue on image workers then. out of scope from this PR

**Comment by hassnian** [comment]
closing then ?

**Comment by preschian** [comment]
> closing that issue then ?

I think we can close it once it is fixed in this repo: https://github.com/kodadot/nft-gallery/issues/7500

**Comment by prury** [comment]
working here for me, in the future i would reduce the number of waves tho

shitty drawing: 
image

**Comment by exezbcz** [comment]
should not there be some settings on the sensitivity? or something that normalizes the wave form. 

btw, clicking on the waveform still does not work for me, but if it works for other, I don't want to hold it. Thanks

**Comment by yangwao** [comment]
pay 50 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $50 @ 3.82 USD/DOT ~ 13.089 $DOT
🧗 [13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh](https://polkadot.subscan.io/account/13QUj3pZyFNfYj4AM336hRdyLQbevj5H3sR4PKmLEXLdwZhh)
🔗 [0x0a5a2608b70a53fadc98211406e340d811ef885e0e4acf4aa33c38c2e2fe677b](https://polkadot.subscan.io/extrinsic/0x0a5a2608b70a53fadc98211406e340d811ef885e0e4acf4aa33c38c2e2fe677b)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Comment by yangwao** [comment]
pay 50 usd

**Pull request merged**
