### PR TITLE
#1748 adding identity option

### LINKED ISSUE #1748: Add Identity back and extend it with possibility add Discord
Please return back our Identity form -- https://kodadot.xyz/identity
and extend it with the possibility to add a Discord username based on #1739 

### Ref
- #1421 
- #1739 
- #1060 
- #1612 
image

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇  _ Do a quick check before the merge.

### PR type
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?
- [x] PR closes #1748
- [ ] <brief_description_of_what_I've_added>

### Before submitting Pull Request, please make sure:
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main-nuxt** and I've no conflicts
- [x] I've tried respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted screenshot of demonstrated change in this PR

### Optional
- [ ] I've tested it at </rmrk/collection/26902bc2f7c20c546a-1FVG7>
- [ ] I've tested PR on mobile and everything seems works
- [ ] I found edge cases

### Had issue bounty label ?
- [x] Fill up your KSM address: 
[Payout](https://beta.kodadot.xyz/transfer/?target=EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU)

### Community participation
- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### Screenshot
- [x] My fix has changed **something** on UI, a screenshot is best to understand changes for others.
Screenshot 2022-01-11 at 9 24 32 PM
Screenshot 2022-01-11 at 9 24 36 PM

### CODE REVIEW

**Comment by yangwao** [comment]
Have you tested it?

**Comment by yangwao** [comment]
> > Have you tested it?
> 
> Yes, but I couldn't submit the form since I get insufficient balance error

Ah, I see you need some KSM, maybe keep some for testing? 
https://kusama.subscan.io/account/EzGc4s9PgCPx1YnF3fqzhLzVHpHMTL4LWPScwpDrR8JKgSU?tab=transfer

**Comment by prachi00** [comment]
@yangwao just tested, it is working fine
Screenshot 2022-01-14 at 5 00 57 PM

**Comment by vikiival** [comment]
Screenshot 2022-01-14 at 12 56 28

WFM

**Comment by yangwao** [comment]
Checking if we could link directly to that user.. https://www.swipetips.com/how-to-send-a-link-to-a-discord-profile/

seems needs to be there like 
`https://discordapp.com/users/prachi#4004/`
So this should reach @prachi00 on discord? https://discordapp.com/users/prachi#4004/

**Comment by vikiival** [comment]
I would change the placeholder 
Screenshot 2022-01-14 at 12 53 53

**Comment by prachi00** [comment]
> Checking if we could link directly to that user.. https://www.swipetips.com/how-to-send-a-link-to-a-discord-profile/
> 
> seems needs to be there like `https://discordapp.com/users/prachi#4004/` So this should reach @prachi00 on discord? https://discordapp.com/users/prachi#4004/
> 
> edit doesn't work.

yeah this doesn't work, currently there is no way to do this I think

**Comment by yangwao** [comment]
@vikiival try https://discord.com/users/prachi#4004

**Comment by prachi00** [comment]
> I would change the placeholder Screenshot 2022-01-14 at 12 53 53

yeah, maybe just yourdiscordusername 

> I would change the placeholder Screenshot 2022-01-14 at 12 53 53

changed to `Discord Username`

**Comment by vikiival** [comment]
> changed to Discord Username

or `Discord User Name#0000`

**Comment by yangwao** [comment]
> > changed to Discord Username
> 
> or `Discord User Name#0000`

yup, this is more exact as I bet not much ppl realize there are some numbers 😄

**Comment by yangwao** [comment]
Perfect, I’ve sent the payout https://kusama.subscan.io/extrinsic/0x52a1d0d5440d88ab4c8cf129bab26551834eaa81612c41f484ec20588873c83c

Let’s grab another issue and get rewarded! 
https://github.com/kodadot/nft-gallery/issues/

**Pull request merged**
