### PR TITLE
Faster Loading wheel 

### LINKED ISSUE #9147: Loading wheel faster spinning
image
lets make the wheel spin faster, psychologically better

### PR DESCRIPTION
**Pull request by prachi00**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring

## Needs QA check

- @kodadot/qa-guild please review

## Context

- [x] Closes #9147

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)

## Screenshot 📸

- [] My fix has changed UI

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]

**Review by preschian — APPROVED** [review]
ignore the build at the moment, related to https://github.com/kodadot/nft-gallery/issues/9174

**Comment by prachi00** [comment]
I am a bit lost, @daiagi @roiLeo any idea why this build is failing? its only 1 character change

**Comment by preschian** [comment]
> I am a bit lost, @daiagi @roiLeo any idea why this build is failing? its only 1 character change

safe to ignore. https://github.com/kodadot/nft-gallery/pull/9166#pullrequestreview-1850341638

**Comment by yangwao** [comment]
mkey then

thanks!
pay 20 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $20 @ 6.93 USD/DOT ~ 2.886 $DOT
🧗 [13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1](https://polkadot.subscan.io/account/13Qx65nLd6SwdtjrRyuoEtp9CKXhF651xdHBPaXcvhwKm4N1)
🔗 [0xe98cced2edcdb4b94012f88b626d100574c37e9f2e3fe011582f787bc9c18e29](https://polkadot.subscan.io/extrinsic/0xe98cced2edcdb4b94012f88b626d100574c37e9f2e3fe011582f787bc9c18e29)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
