### PR TITLE
5535 final prefix

### LINKED ISSUE #5535: Replace rmrk2 to ksm
- #5484 introduced ksm prefix as a replacement to ksm

your task is to:
- [x] find occurences of `rmrk2` prefix and replace it with `ksm`
- [x] in static remove that fancy `ksmToRmrk` functions

### PR DESCRIPTION
**Pull request by vikiival**
- :wastebasket: remove rmrk2 from static
- :wastebasket: from chain.config
- :coffin: last words from rmrk2
- :wastebasket: bye for rmrk2
- :truck: rename rmrk2 to ksm
- :alien: deprecating rmrk2 prefix
- :truck: rename rmrk2 to ksm  in components/carousel/utils/useCarousel.ts
- :truck: rename rmrk2 to ksm  in components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
- :truck: rename rmrk2 to ksm  in components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
- :truck: rename rmrk2 to ksm  in components/gallery/GalleryItemDescription.vue
- :truck: rename rmrk2 to ksm  in components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
- :truck: rename rmrk2 to ksm  in components/gallery/GalleryItemTabsPanel/GalleryItemTabsPanel.vue
- :truck: rename rmrk2 to ksm  in components/items/ItemsGrid/useItemsGrid.ts
- :truck: rename rmrk2 to ksm  in components/landing/LandingPage.vue
- :truck: rename rmrk2 to ksm  in components/navbar/NavbarExploreOptions.vue
- :truck: rename rmrk2 to ksm  in components/navbar/ProfileDropdown.vue
- :truck: rename rmrk2 to ksm  in components/navbar/StatsDropdown.vue
- :truck: rename rmrk2 to ksm  in composables/collectionActivity/helpers.ts
- :truck: rename rmrk2 to ksm  in composables/transaction/mintCollection/constructMeta.ts
- :truck: rename rmrk2 to ksm  in composables/transaction/transactionBurn.ts
- :truck: rename rmrk2 to ksm  in composables/transaction/transactionBuy.ts
- :truck: rename rmrk2 to ksm  in composables/transaction/transactionList.ts
- :truck: rename rmrk2 to ksm  in composables/transaction/transactionMintCollection.ts
- :truck: rename rmrk2 to ksm  in composables/transaction/transactionMintToken.ts
- :truck: rename rmrk2 to ksm  in composables/transaction/transactionSend.ts
- :truck: rename rmrk2 to ksm  in composables/useChain.ts
- :truck: rename rmrk2 to ksm  in composables/useNft.ts
- :truck: rename rmrk2 to ksm  in libs/static/src/chains.ts
- :truck: rename rmrk2 to ksm  in middleware/prefix.ts
- :truck: rename rmrk2 to ksm  in pages/series-insight.vue
- :truck: rename rmrk2 to ksm  in utils/api/bsx/query.ts
- :truck: rename rmrk2 to ksm  in utils/config/defineApolloConfig.ts
- :truck: rename rmrk2 to ksm  in utils/config/types.ts
- :truck: rename rmrk2 to ksm  in utils/prefix.ts
- :truck: rename rmrk2 to ksm  in utils/queryPathResolver.ts
- :arrow_up: @kodadot1/vuex-options
- :heavy_minus_sign: netlify-lambda
- :truck: rename chain-rmrk2 to chain-ksm  in components/carousel/utils/useCarousel.ts
- :truck: rename chain-rmrk2 to chain-ksm  in components/gallery/useGalleryItem.ts
- :truck: rename chain-rmrk2 to chain-ksm  in components/items/ItemsGrid/useItemsGrid.ts
- :truck: rename chain-rmrk2 to chain-ksm  in components/massmint/useMassMint.ts
- :truck: small renames

**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).

👇 \_ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [x] Feature
- [x] Refactoring

## Context

- [x] Closes #5535
- [ ] Requires deployment <>

#### Before submitting pull request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

#### Optional

- [ ] I've tested it at </bsx/collection>
- [ ] I've tested PR on mobile
- [ ] I've written unit tests 🧪
- [ ] I've found edge cases

#### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

#### Community participation

- [ ] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

## Screenshot 📸

- [ ] My fix has changed **something** on UI; a screenshot is best to understand changes for others.

### CODE REVIEW

**Review by roiLeo — COMMENTED** [review]
Some missing stuff:
- [x] `utils/queryPathResolver`
- [ ] `components/common/ConnectWallet/ConnectWalletModal`
- [x] `middleware/prefix`
- [ ] kodadot packages update?

**Comment by vikiival** [comment]
- utils/queryPathResolver - 46e87c9ebafe678463a2ef1e95a38cb653fc69c4
- components/common/ConnectWallet/ConnectWalletModal- it would break the whitelist
- middleware/prefix - eb3af71bf5eec95185d19c329ae8349376a0a81d
- kodadot packages update? - already updated https://www.npmjs.com/package/@kodadot1/vuex-options

**Review by roiLeo — APPROVED** [review]
✅ code lgtm

we might want to keep some middleware to fallback /rmrk2/ prefix to /ksm/ so we won't loose everything that has already been shared on social

**Comment by vikiival** [comment]
So let's break

**Pull request merged**
