### PR TITLE
Fix/scrolling-redirect

### LINKED ISSUE #8187: Scrolling down redirects you back to a collection you have visited
- sort of strange bug, was not yet able to understand how it happens
- notice that in the video i never click on anything
- i had visited those two collections previously when browsing
- i'm browsing items but it redirects me to a collection? 

https://github.com/kodadot/nft-gallery/assets/36627808/5e72f220-ced8-4cf1-add8-bcde5d075cec

how to reproduce: explore items -> enter inside any item -> from the item access its collection -> click on explore items -> scroll down

### LINKED ISSUE #8219: Cant scroll on collection activity
https://github.com/kodadot/nft-gallery/assets/5887929/8f24d91d-b327-4e75-88f8-2027d1463e68

### PR DESCRIPTION
**Pull request by daiagi**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix

## Context

- [x] Closes #8187
- [x] Closes #8219 

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer/?target=1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 76843fc</samp>

Removed the `keepalive` property from the `activity.vue` and `index.vue` components in the collection pages. This improves the reactivity and performance of the collection details and the activity list.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 76843fc</samp>

> _`keepalive` gone_
> _no more caching components_
> _spring cleaning the code_

### CODE REVIEW

**Comment by daiagi** [comment]
removed keepalive from collection pages
1. it was introduced to solve #8044 , but it seems to me it didn't solve it (see video below)
2. causes unexpected scrolling bugs, navigation from collection to any page with ItemsGrid will cause faulty scrolling


### no change in collection page performance
left: this pr, no keep-alive
right: canary - with keep alive
[Screencast from 24-11-23 12:24:28.webm](https://github.com/kodadot/nft-gallery/assets/22791238/82d0cf05-c4d3-45d2-9bea-c43c0ccf93d7)

**Comment by preschian** [comment]
Is it fixed this one also? https://github.com/kodadot/nft-gallery/issues/8219

**Comment by daiagi** [comment]
> Is it fixed this one also? #8219
yes

we should be cautious when using keep alive, or maybe better not use it at all

**Comment by Jarsen136** [comment]
> removed keepalive from collection pages
> 
> 1. it was introduced to solve [Refetch data after changing tab #8044](https://github.com/kodadot/nft-gallery/issues/8044) , but it seems to me it didn't solve it (see video below)

The preview env for this PR #8044: https://deploy-preview-8059--koda-canary.netlify.app/

Could you compare it with canary? There should be some additional change on canary

**Comment by daiagi** [comment]
>It did avoid some reloading.

even so, the addition of keep alive creates these unexpected bugs and it's not worth it for a bit of better loading between tabs

i think we should not use it and find another solution for #8044

**Comment by Jarsen136** [comment]
> > It did avoid some reloading.
> 
> even so, the addition of keep alive creates these unexpected bugs and it's not worth it for a bit of better loading between tabs
> 
> i think we should not use it and find another solution for #8044
> 
Yes sure, let's make this hotfix to solve the main bugs first. Then we could reopen issue #8044 to find a better solution.

**Review by Jarsen136 — APPROVED** [review]

**Comment by preschian** [comment]
@daiagi @Jarsen136 Anyway, on my end issue #8044 looks fine in this PR. I guess that was already fixed by removing the `:key` on `<CollectionBanner />`. Or does it still refetch on your side?

I don't remember why I added that in `<CollectionBanner />` 😅 https://github.com/kodadot/nft-gallery/commit/273abb5bb87046126e799b3f2461c233d607674f#diff-e882aa1e99087943716fb2e71e021492fd58ce6b1cd70834292c0fdacf66d6a4R15. Maybe to avoid some glitch on Nuxt2. In the same commit, I added `router.scrollBehavior.js` also, this file seems like it doesn't work on Nuxt3

**Review by preschian — APPROVED** [review]

**Comment by daiagi** [comment]
@preschian 
the collection Banner indeed doesn't reload when moving between tabs
and it does look like that was the main issue reported in #8044, not the reloading of the tab content

**Comment by yangwao** [comment]
Seems I can scroll down finally 😅

Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 5.23 USD/DOT ~ 5.736 $DOT
🧗 [1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8](https://polkadot.subscan.io/account/1cAsKZYNRb8dkSCpn4eVkEn6ycNZTGoDo5dGDgB8J1UUWK8)
🔗 [0x328bb09100afdec0bec0070c1e6cbe76b3a7144cd9e9a36246a90e0a1b1b1439](https://polkadot.subscan.io/extrinsic/0x328bb09100afdec0bec0070c1e6cbe76b3a7144cd9e9a36246a90e0a1b1b1439)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
