### PR TITLE
fix drop banner container padding

### LINKED ISSUE #9286: Alignment of top section on drop page
image

the profile picture with the name should have the same margin left as the other content 

@newraina wanna pick up? 👀

### PR DESCRIPTION
**Pull request by newraina**
**Thank you for your contribution** to the [KodaDot - One Stop Shop for Polkadot NFTs](https://kodadot.xyz).

👇 __ Let's make a quick check before the contribution.

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring

## Needs Design check

- @exezbcz please review

## Context

- [x] Closes #9286 
- [ ] Requires deployment <snek/rubick/worker>

#### Did your issue had any of the "$" label on it?

- [x] My DOT address: [Payout](https://canary.kodadot.xyz/dot/transfer?target=1CAv6Zq3yVxL3eKhC94GWTWVwp1w4jZbqeZ6wXx1rPAhrce&usdamount=0&donation=true)

## Screenshot 📸

- [ ] My fix has changed UI

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]

**Comment by exezbcz** [comment]
works for me 
image

**Comment by prury** [comment]
looks good on mobile/desktop/tablet

**Comment by yangwao** [comment]
Thanks!
pay 30 usd

**Comment by yangwao** [comment]
😍 Perfect, I’ve sent the payout 
💵 $30 @ 6.69 USD/DOT ~ 4.484 $DOT
🧗 [1CAv6Zq3yVxL3eKhC94GWTWVwp1w4jZbqeZ6wXx1rPAhrce](https://polkadot.subscan.io/account/1CAv6Zq3yVxL3eKhC94GWTWVwp1w4jZbqeZ6wXx1rPAhrce)
🔗 [0x9c457645aa239795d427fe4dcf8bc0da62d1efe1d38dcd00c284fdca851ccd5b](https://polkadot.subscan.io/extrinsic/0x9c457645aa239795d427fe4dcf8bc0da62d1efe1d38dcd00c284fdca851ccd5b)

🪅 Let’s grab another issue and get rewarded! 
🪄 [github.com/kodadot/nft-gallery/issues](https://github.com/kodadot/nft-gallery/issues/)

**Pull request merged**
